function lnls_create_waitbar(label, period, nr_points)

mywaitbar.title = label;
mywaitbar.P = 0;
mywaitbar.nr_points = nr_points;
mywaitbar.C = { ...
    '|o-o-o-Oooo----------|'; ...
    '|-o-o-o-Oooo---------|'; ...
    '|--o-o-o-Oooo--------|'; ...
    '|---o-o-o-Oooo-------|'; ...
    '|----o-o-o-Oooo------|'; ...
    '|-----o-o-o-Oooo-----|'; ...
    '|------o-o-o-Oooo----|'; ...
    '|-------o-o-o-Oooo---|'; ...
    '|--------o-o-o-Oooo--|'; ...
    '|---------o-o-o-Oooo-|'; ...
    '|----------o-o-o-Oooo)'; ...
    '|-----------o-o-oOooo)'; ...
    '|------------oooO-ooo)'; ...
    '|-----------oooO-o-oo|'; ...
    '|----------oooO-o-o-o|'; ...
    '|---------oooO-o-o-o-|'; ...
    '|--------oooO-o-o-o--|'; ...
    '|-------oooO-o-o-o---|'; ...
    '|------oooO-o-o-o----|'; ...
    '|-----oooO-o-o-o-----|'; ...
    '|----oooO-o-o-o------|'; ...
    '|---oooO-o-o-o-------|'; ...
    '|--oooO-o-o-o--------|'; ...
    '|-oooO-o-o-o---------|'; ...
    '(oooO-o-o-o----------|'; ...
    '(oooOo-o-o-----------|'; ...
    '(ooo-Oooo------------|'; ...
    '|oo-o-Oooo-----------|'; ...
    };
mywaitbar.I = 1;
    
    

mywaitbar.TH = timer('Name', label, 'TimerFcn', @update_waitbar_, 'Period', period, 'ExecutionMode', 'fixedSpacing');
mywaitbar.WH = waitbar(0, label, 'Name', label);
mywaitbar.T0 = clock;
setappdata(0, 'MYWAITBAR', mywaitbar);
start(mywaitbar.TH);



function update_waitbar_(timerhandle, eventhandle)

mywaitbar = getappdata(0, 'MYWAITBAR');
if ~isempty(mywaitbar.title)
    try
    x = mywaitbar.P / mywaitbar.nr_points;
    tt = etime(clock, mywaitbar.T0);
    h = floor(tt / 3600);
    tt = tt - h * 3600;
    m = floor(tt / 60);
    tt = tt - m * 60;
    s = floor(tt);
    ms = tt - s;
    tt = sprintf('%02ih%02im%02is%03i', h,m,s,round(1000*ms));
    waitbar(x, mywaitbar.WH, [num2str(100*x, '%4.1f') '% ' mywaitbar.C{mywaitbar.I} ' ' tt]);
    mywaitbar.I = mod(mywaitbar.I + 1 - 1, length(mywaitbar.C)) + 1;
    setappdata(0, 'MYWAITBAR', mywaitbar);
    catch
        lnls_delete_waitbar;
        %disp('ok');
    end
else
    if mywaitbar.WH ~= 0
        mywaitbar.WH = 0;
        mywaitbar.P = 0;
        mywaitbar.nr_points = 1;
    end
end
drawnow;



