function lnls_setpath_mml_at

root_folder = lnls_get_root_folder();

paths = { ...
    fullfile(root_folder, 'code', 'MatlabMiddleLayer', 'Release', 'lnls', 'at-mml_modified_scripts'); ...
    fullfile(root_folder, 'code', 'MatlabMiddleLayer', 'Release', 'mml'); ...
    fullfile(root_folder, 'code', 'MatlabMiddleLayer', 'Release', 'applications', 'common'); ...
    fullfile(root_folder, 'code', 'MatlabMiddleLayer', 'Release', 'applications', 'loco'); ...
    fullfile(root_folder, 'code', 'MatlabMiddleLayer', 'Release', 'mml', 'at'); ...
    fullfile(root_folder, 'code', 'MatlabMiddleLayer', 'Release', 'at'); ...
    fullfile(root_folder, 'code', 'MatlabMiddleLayer', 'Release', 'at', 'atdemos'); ...
    fullfile(root_folder, 'code', 'MatlabMiddleLayer', 'Release', 'at', 'atgui'); ...
    fullfile(root_folder, 'code', 'MatlabMiddleLayer', 'Release', 'at', 'atphysics'); ...
    fullfile(root_folder, 'code', 'MatlabMiddleLayer', 'Release', 'at', 'lattice'); ...
    fullfile(root_folder, 'code', 'MatlabMiddleLayer', 'Release', 'at', 'simulator'); ...
    fullfile(root_folder, 'code', 'MatlabMiddleLayer', 'Release', 'at', 'simulator', 'element'); ...
    fullfile(root_folder, 'code', 'MatlabMiddleLayer', 'Release', 'at', 'simulator', 'element', 'obsolete'); ...
    fullfile(root_folder, 'code', 'MatlabMiddleLayer', 'Release', 'at', 'simulator', 'element', 'user'); ...
    fullfile(root_folder, 'code', 'MatlabMiddleLayer', 'Release', 'at', 'simulator', 'track'); ...
    fullfile(root_folder, 'code', 'MatlabMiddleLayer', 'Release', 'applications', 'naff', 'nafflib'); ...
    fullfile(root_folder, 'code', 'MatlabMiddleLayer', 'Release', 'applications', 'naff', 'naffutils', 'touscheklifetime'); ...
    fullfile(root_folder, 'code', 'MatlabMiddleLayer', 'Release', 'applications', 'naff', 'naffutils'); ...
    fullfile(root_folder, 'code', 'MatlabMiddleLayer', 'Release', 'applications', 'naff'); ...
    fullfile(root_folder, 'code', 'MatlabMiddleLayer', 'Release', 'applications', 'lnls'); ...
    fullfile(root_folder, 'code', 'MatlabMiddleLayer', 'Release', 'applications', 'lnls','nsga_ii'); ...
    fullfile(root_folder, 'code', 'MatlabMiddleLayer', 'Release', 'lnls', 'fac_scripts', 'tracy3'); ...
};

for i=length(paths):-1:1
    addpath(paths{i});
end