path = '\\centaurus\Repositorio\Grupos\DIG\Projetos\Ativos\DT_FOFB\LNLS\Experimentos\Aquisição rápida\20110618\500MeV\modoff\ond450Hz_step\baixaenergia_modoff_ond450Hz_step_libera\';
filename = '2011-6-18_11.37.26_TBT-DEC_3.dat';

n_bpms = 25;
bpm_index = 13;

data.bpm_names = {  'AMP01BH',...
                    'AMP02AH',...
                    'AMP02BH',...
                    'AMP03AH',...
                    'AMP03BH',...
                    'AMP03CH',...
                    'AMP04AH',...
                    'AMP04BH',...
                    'AMP05AH',...
                    'AMP05BH',...
                    'AMP06AH',...
                    'AMP06BH',...
                    'AMP07AH',...
                    'AMP07BH',...
                    'AMP08AH',...
                    'AMP08BH',...
                    'AMP09AH',...
                    'AMP09BH',...
                    'AMP10AH',...
                    'AMP10BH',...
                    'AMU11AH',...
                    'AMU11BH',...
                    'AMP12AH',...
                    'AMP12BH',...
                    'AMP01AH',...
                    'AMP01BV',...
                    'AMP02AV',...
                    'AMP02BV',...
                    'AMP03AV',...
                    'AMP03BV',...
                    'AMP03CV',...
                    'AMP04AV',...
                    'AMP04BV',...
                    'AMP05AV',...
                    'AMP05BV',...
                    'AMP06AV',...
                    'AMP06BV',...
                    'AMP07AV',...
                    'AMP07BV',...
                    'AMP08AV',...
                    'AMP08BV',...
                    'AMP09AV',...
                    'AMP09BV',...
                    'AMP10AV',...
                    'AMP10BV',...
                    'AMU11AV',...
                    'AMU11BV',...
                    'AMP12AV',...
                    'AMP12BV',...
                    'AMP01AV'};


libera_data = load([path filename]);
libera_data = libera_data(:,5:6)/1e6;

Ts = 64*148/476066000*1e3;

data.orb = zeros(size(libera_data,1),n_bpms*2);
data.orb(:,[bpm_index (bpm_index+n_bpms)]) = libera_data;
data.time = 0:Ts:Ts*(size(libera_data,1)-1);

save([path filename '.mat'], 'data');