function opt = set_options(si0)

fams  = {'sfa', 'sfb', 'sfpa','sfpb',...
         'sda', 'sdb', 'sdpa','sdpb'...
         'sd1j','sd1k','sd1l','sd1m',... %'sd1n','sd1o','sd1p','sd1q',...
         'sd2j','sd2k','sd2l','sd2m',... %'sd2n','sd2o','sd2p','sd2q',...
         'sd3j','sd3k','sd3l','sd3m',... %'sd3n','sd3o','sd3p','sd3q',...
         'sf1j','sf1k','sf1l','sf1m',... %'sf1n','sf1o','sf1p','sf1q',...
         'sf2j','sf2k','sf2l','sf2m',... %'sf2n','sf2o','sf2p','sf2q',...
         };
knobs = cell(1,length(fams));

for i=1:length(fams), knobs{i} = findcells(si0,'FamName',fams{i}); end


opt.fams       = fams;
opt.chromx     = 2.5/5;
opt.chromy     = -2.5/5;
opt.knobs      = knobs;
opt.ring       = si0;
opt.get_values = @knobs_get_values;
opt.set_values = @knobs_set_values;