Description of month
Home > applications > common > month.m
month
PURPOSE
Return the month number, given a string date
SYNOPSIS
function [n,m] = month(d)
DESCRIPTION
 Return the month number, given a string date
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
date2mdy DATE2MDY - Convert a Matlab date format to month, day, year
daxis Simplified version of the Financial Toolbox's 'dateaxis' command
mon2num MON2NUM - Converts month (string) to month number
SOURCE CODE
function [n,m] = month(d)
% Return the month number, given a string date
if nargin < 1
    d = date;
end
c = datevec(datenum(d));
n = c(:,2);
mths = ['Jan';'Feb';'Mar';'Apr';'May';'Jun';'Jul';
        'Aug';'Sep';'Oct';'Nov';'Dec'];
n = c(:,2);                          % Extract months
m = mths(c(:,2)+(c(:,2)==0),:);      % Month strings