Description of buildopsdatafiles
Home > mml > buildopsdatafiles.m
buildopsdatafiles
PURPOSE
BUILDOPSDATAFILES - Builds the files for the OpsData directory from the model
SYNOPSIS
function buildopsdatafiles
DESCRIPTION
BUILDOPSDATAFILES - Builds the files for the OpsData directory from the model
  buildopsdatafiles
CROSS-REFERENCE INFORMATION
This function calls:
copybpmrespfile COPYBPMRESPFILE - Copies a BPM response matrix file to the golden file
copychrorespfile COPYCHRORESPFILE - Copies a chromaticity response matrix file to the golden file
copydispersionfile COPYDISPERSIONFILE - Copies a dispersion file to golden file
copytunerespfile COPYTUNERESPFILE - Copies a tune response matrix file to the golden file
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
getmachineconfig GETMACHINECONFIG - Returns or saves to file the present storage ring setpoints and monitors
measbpmresp MEASBPMRESP - Measures the BPM response matrix in the horizontal and vertical planes
measchroresp MEASCHRORESP - measures the response from sextupoles to chromaticity
measdisp MEASDISP - Measures the dispersion function
meastuneresp MEASTUNERESP - Measures the response from quadrupole to tune
This function is called by:
SOURCE CODE
function buildopsdatafiles
%BUILDOPSDATAFILES - Builds the files for the OpsData directory from the model
%  buildopsdatafiles
getmachineconfig('Golden');
%copyinjectionconfigfile(FileName);
getmachineconfig('Injection');
%copymachineconfigfile(FileName);
FileName = [getfamilydata('Directory', 'BPMResponse'), getfamilydata('Default', 'BPMRespFile'), '_Model'];
[Rmat, FileName] = measbpmresp('Model', 'Archive', FileName);
copybpmrespfile(FileName);
FileName = [getfamilydata('Directory', 'DispData'), getfamilydata('Default', 'DispArchiveFile'), '_Model'];
[Dx, Dy, FileName] = measdisp('Model', 'Archive', FileName);
copydispersionfile(FileName);
FileName = [getfamilydata('Directory', 'TuneResponse'), getfamilydata('Default', 'TuneRespFile'), '_Model'];
[Rmat, FileName] = meastuneresp('Model', 'Archive', FileName);
copytunerespfile(FileName);
FileName = [getfamilydata('Directory', 'ChroResponse'), getfamilydata('Default', 'ChroRespFile'), '_Model'];
[Rmat, FileName] = measchroresp('Model', 'Archive', FileName);
copychrorespfile(FileName);