Description of channel2family
Home > mml > channel2family.m
channel2family
PURPOSE
CHANNEL2FAMILY - Convert a channel name to a Family, Field, DeviceList
SYNOPSIS
function [FamilyName, Field, DeviceList, ErrorFlag] = channel2family(varargin)
DESCRIPTION
CHANNEL2FAMILY - Convert a channel name to a Family, Field, DeviceList
  [Family, Field, DeviceList, ErrorFlag] = channel2family(ChannelNames, Family)
  INPUTS
  1. ChannelNames - List of channel names (string, matrix, or cell array)
  2. Family - Family Names to to limit search (string or cell of strings)
              Accelerator Object
              '' search all families {Default}
  OUTPUTS
  1. Family - Family name corresponding to the channel name
              If the channel name cannot be found an empty strings
             (or a blank string for matrix inputs) is returned
  2. Field - Field Name
  3. DeviceList - DeviceList corresponding to the common name
                  If no common names are found, an empty matrix is returned
                  If only some common names are not found, [NaN NaN] will be
                  inserted into the device list where they are not found.
  4. ErrorFlag - number of errors found
CROSS-REFERENCE INFORMATION
This function calls:
channel2dev CHANNEL2DEV - Converts a channel name list to a device list
This function is called by:
family2status FAMILY2STATUS - Returns the device status
getrunflag GETRUNFLAG - Returns position if the device is in the process of changing a setpoint
getspos GETSPOS - Returns the longitudinal position in meters
SOURCE CODE
function [FamilyName, Field, DeviceList, ErrorFlag] = channel2family(varargin)
%CHANNEL2FAMILY - Convert a channel name to a Family, Field, DeviceList
%  [Family, Field, DeviceList, ErrorFlag] = channel2family(ChannelNames, Family)
%
%  INPUTS
%  1. ChannelNames - List of channel names (string, matrix, or cell array)
%  2. Family - Family Names to to limit search (string or cell of strings)
%              Accelerator Object
%              '' search all families {Default}
%
%  OUTPUTS
%  1. Family - Family name corresponding to the channel name
%              If the channel name cannot be found an empty strings
%             (or a blank string for matrix inputs) is returned
%  2. Field - Field Name
%  3. DeviceList - DeviceList corresponding to the common name
%                  If no common names are found, an empty matrix is returned
%                  If only some common names are not found, [NaN NaN] will be
%                  inserted into the device list where they are not found.
%  4. ErrorFlag - number of errors found
%  Written by Greg Portmann
[DeviceList, FamilyName, Field, ErrorFlag] = channel2dev(varargin{:});