Description of correctors2golden
Home > mml > correctors2golden.m
correctors2golden
PURPOSE
CORRECTORS2GOLDEN - Sets the default corrector families to the golden configuration values
SYNOPSIS
function correctors2golden
DESCRIPTION
CORRECTORS2GOLDEN - Sets the default corrector families to the golden configuration values
  correctors2golden
  See also vcm2golden, hcm2golden
CROSS-REFERENCE INFORMATION
This function calls:
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
gethcmfamily GETHCMFAMILY - Returns the default horizontal corrector family
getvcmfamily GETVCMFAMILY - Returns the default vertical corrector family
setpv SETPV - Setpoint change of the online system or model
This function is called by:
SOURCE CODE
function correctors2golden
%CORRECTORS2GOLDEN - Sets the default corrector families to the golden configuration values
%  correctors2golden
%
%  See also vcm2golden, hcm2golden
%  Written by Greg Portmann
FileName = getfamilydata('OpsData', 'LatticeFile');
DirectoryName = getfamilydata('Directory', 'OpsData');
load([DirectoryName FileName]);
HCMFamily = gethcmfamily;
VCMFamily = getvcmfamily;
setpv(ConfigSetpoint.(HCMFamily).Setpoint, 0);
setpv(ConfigSetpoint.(VCMFamily).Setpoint, 0);