Description of elem2dev
Home > mml > elem2dev.m
elem2dev
PURPOSE
ELEM2DEV - Converts a device list to an element list
SYNOPSIS
function Output = elem2dev(Family, ElementList)
DESCRIPTION
ELEM2DEV - Converts a device list to an element list
  [Sector Device#] = elem2dev(Family, Element#)
  This function convects between the two methods of representing
  the same device in the ring.  The "Device" method is a two column
  matrix with the first being sector number and the seconds being
  the device number in the sector.  The "Element" method is a one column
  matrix with each entry being the element number starting at sector 1.
  The following are equivalent devices for VCMs at the ALS:
                     | 1  2 |                    |  2 |
                     | 1  3 |                    |  3 |
  [Sector Device#] = | 2  1 |    [ElementList] = |  9 |
                     | 2  2 |                    | 10 |
                     | 3  4 |                    | 20 |
  NOTES
  1. If ElementList is empty, the entire family list will be returned.
  2. If the device is not found, then an error will occur.
  3. If the Family is not found, then empty, [], is returned.
CROSS-REFERENCE INFORMATION
This function calls:
getlist GETLIST - Returns Device List for a Family
isfamily ISFAMILY - True for family names
This function is called by:
amp2mm AMPS2MM - Returns the maximum millimeter orbit change per change in corrector
checklimits CHECKLIMITS - Checks if the setpoint will exceed a limit
dev2common DEV2COMMON - Converts a device list to a common name list
family2status FAMILY2STATUS - Returns the device status
getdata GETDATA - Searches through a file (or group of files) for a data structure which matches the family name
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
getgolden GETGOLDEN - Returns the golden values for a family
getpv GETPV - Returns a variable from the online system or the model
getrespmat GETRESPMAT - Get response matrix data from a file
getsigma GETSIGMA - Return the standard deviation in the monitor for a family
inputparsingffd INPUTPARSINGFFD - Parses the typical input line of Family, Field, DeviceList
loadorbit LOADORBIT - Loads orbit by file/directory specification - or - Golden %orbit by default
measrespmat MEASRESPMAT - Measure a response matrix
mm2amp MM2AMPS - Returns the change in corrector need for a maximum orbit change
monrate MONRATE - Calculates the control system data rate of a noisy channel
raw2real RAW2REAL - Converts raw control system data to calibrated values
real2raw REAL2RAW - Converts "real" data (calibrated values) to control system data
rmgolden RMGOLDEN - Remove the golden values for data set
rmoffset RMOFFSET - Remove the offset values for data set
setfamilydata SETFAMILYDATA - Sets data associated with accelerator control
setphysdata SETPHYSDATA - Set physics data
setpv SETPV - Setpoint change of the online system or model
SOURCE CODE
function Output = elem2dev(Family, ElementList)
%ELEM2DEV - Converts a device list to an element list
%  [Sector Device#] = elem2dev(Family, Element#)
%
%  This function convects between the two methods of representing
%  the same device in the ring.  The "Device" method is a two column
%  matrix with the first being sector number and the seconds being
%  the device number in the sector.  The "Element" method is a one column
%  matrix with each entry being the element number starting at sector 1.
%
%  The following are equivalent devices for VCMs at the ALS:
%                     | 1  2 |                    |  2 |
%                     | 1  3 |                    |  3 |
%  [Sector Device#] = | 2  1 |    [ElementList] = |  9 |
%                     | 2  2 |                    | 10 |
%                     | 3  4 |                    | 20 |
%
%  NOTES
%  1. If ElementList is empty, the entire family list will be returned.
%  2. If the device is not found, then an error will occur.
%  3. If the Family is not found, then empty, [], is returned.
%  Written by Greg Portmann
if nargin == 0
    error('One input required.');
end
if nargin == 1
    Output = getlist(Family);
    return
end
if isempty(ElementList)
    Output = getlist(Family);
    return
end
if size(ElementList,2) == 2
    % Assume that the input was already a device list
    Output = ElementList;
    return
end
%Output = getfamilydata(Family, 'DeviceList', DevList);
[FamilyIndex, ACCELERATOR_OBJECT] = isfamily(Family);
if FamilyIndex
    DeviceListTotal  = ACCELERATOR_OBJECT.DeviceList;
    ElementListTotal = ACCELERATOR_OBJECT.ElementList;
    Err = 0;
    % Intersect removes duplicate devices so first store index of how to unsort in j_unique
    ElementListOld = ElementList;
    [ElementList, i_unique, j_unique] = unique(ElementList);
    % Find the indexes in the full device list (reorder and remove duplicates)
    [ElementList, ii, DeviceIndex] = intersect(ElementList, ElementListTotal);
    if size(ElementList,1) ~= size(ElementListOld,1)
        % All devices must exist (duplicate devices ok)
        [ElementListNotFound, iNotFound] = setdiff(ElementListOld, ElementListTotal);
        if ~isempty(iNotFound)
            % Device not found
            for i = 1:length(iNotFound)
                fprintf('   No devices to get for Family %s(%d)\n', ACCELERATOR_OBJECT.FamilyName, ElementListNotFound(i));
            end
            error(sprintf('%d Devices not found', length(iNotFound)));
        end
    end
    Output = DeviceListTotal(DeviceIndex,:);   % Only data referenced to DeviceList
    Output = Output(j_unique,:);               % Reorder and add multiple elements back
else
    error(sprintf('%s family not found', Family));
end