Description of family2dev
Home > mml > family2dev.m
family2dev
PURPOSE
FAMILY2DEV - Return the device list for a family
SYNOPSIS
function DeviceList = family2dev(Family, varargin)
DESCRIPTION
FAMILY2DEV - Return the device list for a family
  DeviceList = family2dev(FamilyName, StatusFlag, PowerSupplyFlag)
  DeviceList = family2dev(FamilyName, Field, StatusFlag, PowerSupplyFlag)
  INPUTS
  1. Family - Family name (ex., 'BEND', 'QFA', 'SF', 'SD', 'HCM', 'VCM', etc.)
              Data Structure (only the FamilyName field is used)
              Accelerator Object (only the FamilyName field is used)
              Cell Array
  2. Field - Option field input only effects the PowerSupplyFlag
  3. StatusFlag - 0 return all devices
                  1 return only devices with good status {Default}
  4. PowerSupplyFlag - 0 return all devices {Default}
                       1 return only unique channel names (like, power supplies for a magnet)
  OUTPUTS
  1. DeviceList - Device list corresponding to the Family
                  Empty if not found
  See also family2elem, family2common, family2status, family2tol, family2units
CROSS-REFERENCE INFORMATION
This function calls:
family2channel FAMILY2CHANNEL - Converts the family name to a channel name
family2dev FAMILY2DEV - Return the device list for a family
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
This function is called by:
amp2mm AMPS2MM - Returns the maximum millimeter orbit change per change in corrector
bpm2quad BPM2QUAD - Returns the nearest quadrupole to the specified BPM
builddevlist BUILDDEVLIST - Make a full device list from devices in one sector
checklimits CHECKLIMITS - Checks if the setpoint will exceed a limit
family2channel FAMILY2CHANNEL - Converts the family name to a channel name
family2common FAMILY2COMMON - Convert a family name, device list to a common name list
family2datastruct FAMILY2DATASTRUCTURE
family2dev FAMILY2DEV - Return the device list for a family
family2elem FAMILY2ELEM - Return the device list for a family
family2status FAMILY2STATUS - Returns the device status
findrf1 FINDRF1 - Finds the RF frequency that minimizes the horizonal dispersion
getbpm GETBPM - Returns the horizontal and vertical orbit
getbpmresp GETBPMRESP - Returns the BPM response matrix in the horizontal and vertical planes
getdisp GETDISP - Returns the dispersion for a BPM family (from file)
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
getgolden GETGOLDEN - Returns the golden values for a family
getlist GETLIST - Returns Device List for a Family
getnumberofsectors GETNUMBEROFSECTORS - Number of sectors in the lattice
getphysdata GETPHYSDATA - Gets physics data
getpv GETPV - Returns a variable from the online system or the model
getsigma GETSIGMA - Return the standard deviation in the monitor for a family
getspos GETSPOS - Returns the longitudinal position in meters
hw2physics HW2PHYSICS - Converts from 'Hardware' units to 'Physics' units
inputparsingffd INPUTPARSINGFFD - Parses the typical input line of Family, Field, DeviceList
makebump MAKEBUMP - Creates and orbit correction structure (OCS) usable by setorbit
measbeta MEASBETA - Measure the betatron functions
measbpmresp MEASBPMRESP - Measures the BPM response matrix in the horizontal and vertical planes
measbpmresplinearity MEASBPMRESPLINEARITY - Compute BPMlinearity
measrespmat MEASRESPMAT - Measure a response matrix
mm2amp MM2AMPS - Returns the change in corrector need for a maximum orbit change
mmlviewer MMLVIEWER M-file for mmlviewer.fig
monbpm MONBPM - Monitors the orbit
physics2hw PHYSICS2HW - Converts from 'Physics' units to 'Hardware' units
plotfamily PLOTFAMILY - Plots by middle layer family name
plotgoldenorbit PLOTGOLDENORBIT - Plots the golden orbit
plotoffsetorbit PLOTOFFSETORBIT - Plots the offset orbit
plotorbit PLOTORBIT - Plot the present orbit w.r.t. the golden or offset orbit
quad2bpm QUAD2BPM - Returns the nearest BPM to the specified quadrupole
quadplotall QUADPLOTALL - Collect the date from a quadrupole center run.
raw2real RAW2REAL - Converts raw control system data to calibrated values
real2raw REAL2RAW - Converts "real" data (calibrated values) to control system data
rmgolden RMGOLDEN - Remove the golden values for data set
rmoffset RMOFFSET - Remove the offset values for data set
scanorbit SCANORBIT - Scans 2 correctors 90 degrees out of phase
setfamilydata SETFAMILYDATA - Sets data associated with accelerator control
setorbit SETORBIT - Orbit correction function
setorbitbump SETORBITBUMP - Local bump program (uses setorbit)
setorbitbumpgui SETORBITBUMPGUI M-file for setorbitbumpgui.fig
setorbitgui SETORBITGUI - Orbit correction GUI
setpv SETPV - Setpoint change of the online system or model
sext2bpm SEXT2BPM - Returns the nearest BPM to the specified sextupole
showmachinedata SHOWMACHINEDATA - Display setpoints and readbacks for families in AcceleratorObjects
SOURCE CODE
function DeviceList = family2dev(Family, varargin)
%FAMILY2DEV - Return the device list for a family
%  DeviceList = family2dev(FamilyName, StatusFlag, PowerSupplyFlag)
%  DeviceList = family2dev(FamilyName, Field, StatusFlag, PowerSupplyFlag)
%
%  INPUTS
%  1. Family - Family name (ex., 'BEND', 'QFA', 'SF', 'SD', 'HCM', 'VCM', etc.)
%              Data Structure (only the FamilyName field is used)
%              Accelerator Object (only the FamilyName field is used)
%              Cell Array
%  2. Field - Option field input only effects the PowerSupplyFlag
%  3. StatusFlag - 0 return all devices
%                  1 return only devices with good status {Default}
%
%  4. PowerSupplyFlag - 0 return all devices {Default}
%                       1 return only unique channel names (like, power supplies for a magnet)
%
%  OUTPUTS
%  1. DeviceList - Device list corresponding to the Family
%                  Empty if not found
%
%  See also family2elem, family2common, family2status, family2tol, family2units
%  Written by Greg Portmann
if nargin == 0
    error('Must have at least one input.');
end
% Look for a field input
Field = '';
if length(varargin) >= 1
    if ischar(varargin{1})
        Field = varargin{1};
        varargin(1) = [];
    end
end
% StatusFlag
if length(varargin) >= 1
    StatusFlag = varargin{1};
else
    % This choice changes the default behavior for the entire middle layer !!!!
    StatusFlag = 1;  % Only return good status devices
end
% PowerSupplyFlag
if length(varargin) >= 2
    PowerSupplyFlag = varargin{2};
else
    PowerSupplyFlag = 0;
end
%%%%%%%%%%%%%%%%%%%%%
% Cell Array Inputs %
%%%%%%%%%%%%%%%%%%%%%
if iscell(Family)
    for i = 1:size(Family,1)
        for j = 1:size(Family,2)
            if iscell(StatusFlag) && iscell(PowerSupplyFlag)
                DeviceList{i,j} = family2dev(Family{i}, StatusFlag{i}, PowerSupplyFlag{i});
            elseif iscell(StatusFlag)
                DeviceList{i,j} = family2dev(Family{i}, StatusFlag{i}, PowerSupplyFlag);
            elseif iscell(PowerSupplyFlag)
                DeviceList{i,j} = family2dev(Family{i}, StatusFlag, PowerSupplyFlag{i});
            else
                DeviceList{i,j} = family2dev(Family{i}, StatusFlag, PowerSupplyFlag);
            end
        end
    end
    return
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Family or data structure inputs beyond this point %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if isstruct(Family)
    % Structures can be an accelerator object or a data structure (as returned by getpv)
    if isfield(Family, 'FamilyName')
        % Data structure
        Family = Family.FamilyName;
    else
        error('Family input of unknown type');
    end
end
DeviceList = getfamilydata(Family, 'DeviceList');
if isempty(DeviceList)
    error(sprintf('%s family not found', Family));
end
if StatusFlag
    Status = getfamilydata(Family, 'Status', DeviceList);
    if isempty(Status)
        fprintf('   WARNING:  Status field not in the AO, hence ignored.\n');
    else
        DeviceList = DeviceList(find(Status),:);
    end
end
if PowerSupplyFlag
    % There can be multiple channel names due to "ganged" power supplies
    if isempty(Field)
        ChannelNames0 = family2channel(Family, DeviceList);
    else
        ChannelNames0 = family2channel(Family, Field, DeviceList);
    end
    [ChannelNames, ii, jj] = unique(ChannelNames0, 'rows');
    if length(ii) ~= size(ChannelNames0,1)
        % Remove ' ' (' ' should always be the first row)
        if isempty(deblank(ChannelNames(1,:)))
            ii(1) = [];
            jj(jj==1) = [];
            jj = jj - 1;
        end
        ChannelNames = ChannelNames0(ii,:);
        % Unique does a sort and keeps the last device.
        % Remove the sort
        jjtmp = jj;
        for i = 1:max(jj)
            iDev(i) = jjtmp(1);
            jjtmp(jjtmp==jjtmp(1)) = [];
        end
        ChannelNames = ChannelNames(iDev,:);
        % Find the first device with that name
        i = findrowindex(ChannelNames, ChannelNames0);
        DeviceList = DeviceList(i,:);
    else
        % Remove ' ' (' ' should always be the first row)
        if isempty(deblank(ChannelNames(1,:)))
            iBlank = find(jj==1);
            DeviceList(iBlank,:) = [];
        end
    end
end
% if nargin >= 2
%     if varargin{1}
%         Status = getfamilydata(Family, 'Status', DeviceList);
%         if isempty(Status)
%             fprintf('   WARNING:  Status field not in the AO, hence ignored.\n');
%         else
%             DeviceList = DeviceList(find(Status),:);
%         end
%     end
% end