Description of getam
Home > mml > getam.m
getam
PURPOSE
GETAM - Gets monitor channels
SYNOPSIS
function [AM, tout, DataTime, ErrorFlag] = getam(varargin)
DESCRIPTION
GETAM - Gets monitor channels
  If using family name, device list method,
  [AM, tout, DataTime] = getam(Family, DeviceList, t, FreshDataFlag, TimeOutPeriod)
  If using data structure,
  [AM, tout, DataTime] = getam(DataStructure, t, FreshDataFlag, TimeOutPeriod)
  If using channel name method,
  [AM, tout, DataTime] = getam(ChannelName, t, FreshDataFlag, TimeOutPeriod)
  INPUTS & OUTPUTS
  See getpv.  getam is an alias to getpv with the Field='Monitor'.
  See also getpv, getsp, setsp, setpv
CROSS-REFERENCE INFORMATION
This function calls:
getpv GETPV - Returns a variable from the online system or the model
This function is called by:
findrf1 FINDRF1 - Finds the RF frequency that minimizes the horizonal dispersion
getmachineconfig GETMACHINECONFIG - Returns or saves to file the present storage ring setpoints and monitors
golden2sim GOLDEN2SIM - loads online machine configuration to AT configuration
machine2sim MACHINE2SIM - loads online machine configuration to AT configuration
magstep MAGSTEP - Script for testing the time responce of a magnet
makebump MAKEBUMP - Creates and orbit correction structure (OCS) usable by setorbit
measbeta MEASBETA - Measure the betatron functions
measbpmresp MEASBPMRESP - Measures the BPM response matrix in the horizontal and vertical planes
measbpmresplinearity MEASBPMRESPLINEARITY - Compute BPMlinearity
measchro MEASCHRO - measures the chromaticity function emperically
meascmhysteresis MEASCMHYSTERESIS - Measure corrector magnet hysteresis
measdisp MEASDISP - Measures the dispersion function
measidfftable MEASIDFFTABLE - Measures an insertion device feed forward table for the vertical gap
measrespmat MEASRESPMAT - Measure a response matrix
monbpm MONBPM - Monitors the orbit
monmags MONMAGS - Monitors all magnet power supplies and plots various statistics
monrate MONRATE - Calculates the control system data rate of a noisy channel
plotmemberof PLOTMEMBEROF - Plots the setpoint and monitor for all members in a "MemberOf" group
plotorbit PLOTORBIT - Plot the present orbit w.r.t. the golden or offset orbit
quadcenter QUADCENTER - Measure the magnet center of a quadrupole magnet
rmdisp RMDISP - Removes the portion of the orbit that correlates with the dispersion
setorbit1 SETORBIT1 - Correct the orbit using all the SVD (1 plane)
setorbitbump SETORBITBUMP - Local bump program (uses setorbit)
setpv SETPV - Setpoint change of the online system or model
showmachinedata SHOWMACHINEDATA - Display setpoints and readbacks for families in AcceleratorObjects
SOURCE CODE
function [AM, tout, DataTime, ErrorFlag] = getam(varargin)
%GETAM - Gets monitor channels
%  If using family name, device list method,
%  [AM, tout, DataTime] = getam(Family, DeviceList, t, FreshDataFlag, TimeOutPeriod)
%
%  If using data structure,
%  [AM, tout, DataTime] = getam(DataStructure, t, FreshDataFlag, TimeOutPeriod)
%
%  If using channel name method,
%  [AM, tout, DataTime] = getam(ChannelName, t, FreshDataFlag, TimeOutPeriod)
%
%  INPUTS & OUTPUTS
%  See getpv.  getam is an alias to getpv with the Field='Monitor'.
%
%  See also getpv, getsp, setsp, setpv
%  Written by Greg Portmann
if nargout < 3
    [AM, tout] = getpv(varargin{:});
else
    [AM, tout, DataTime, ErrorFlag] = getpv(varargin{:});
end
% if nargin == 0
%     error('Must have at least one input (Family, Data Structure or Channel Name).');
% end
%
% if iscell(Family)
% [AM, tout, DataTime, ErrorFlag] = getpv(Family, varargin{:});
% else
% [FamilyIndex, AO] = isfamily(Family);
%
% if nargout < 3
%     if FamilyIndex
%         % Family name method
%         [AM, tout] = getpv(AO, 'Monitor', varargin{:});
%     else
%         % ChannelName method
%         [AM, tout] = getpv(Family, '', varargin{:});
%     end
% else
%     if FamilyIndex
%         % Family name method
%         [AM, tout, DataTime, ErrorFlag] = getpv(AO, 'Monitor', varargin{:});
%     else
%         % ChannelName method
%         [AM, tout, DataTime, ErrorFlag] = getpv(Family, '', varargin{:});
%     end
% end
% end