Description of getad
Home > mml > getad.m
getad
PURPOSE
GETAD - returns the Accelerator Data (AD) structure
SYNOPSIS
function AD = getad
DESCRIPTION
GETAD - returns the Accelerator Data (AD) structure
 AD = getad
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
addmenuad ADDMENUAD - Adds a menu bar to view and edit the MML AD structure
addmenustruct ADDMENUSTRUCT - Adds a menu bar to view and edit a structure
getao GETAO - returns the AcceleratorObject (AO)
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
mmlviewer MMLVIEWER M-file for mmlviewer.fig
saveao SAVEAO - Saves the AO and AD to a .mat file
setfamilydata SETFAMILYDATA - Sets data associated with accelerator control
setmmldirectories SETMMLDIRECTORIES - Set the directory in the Matlab middle layer
showmachinedata SHOWMACHINEDATA - Display setpoints and readbacks for families in AcceleratorObjects
SOURCE CODE
function  AD = getad
%GETAD - returns the Accelerator Data (AD) structure
% AD = getad
AD = getappdata(0, 'AcceleratorData');
% if isempty(AD)
%     warning('AcceleratorData not initialized');
% end