Description of getao
Home > mml > getao.m
getao
PURPOSE
GETAO - returns the AcceleratorObject (AO)
SYNOPSIS
function AO = getao(FileName)
DESCRIPTION
GETAO - returns the AcceleratorObject (AO)
  AO = getao(FileName)
  If FileName = 'Archive', then the AO and AD are saved to the
                default directory under the data root
  If FileName = a string beside 'Archive', then the AO and AD are saved
                to that string name
CROSS-REFERENCE INFORMATION
This function calls:
getad GETAD - returns the Accelerator Data (AD) structure
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
This function is called by:
addaoprefix ADDAOPREFIX - Add a prefix to all AcceleratorObjects PV names
addmenuao ADDMENUAO - Adds a menu bar to view and edit the MML AO structure
aokeep AOKEEP - Removes families from the Accelerator Families except those included in KEEPLIST
channel2dev CHANNEL2DEV - Converts a channel name list to a device list
checkforao CHECKFORAO - Run aoinit if no middle layer is present
common2channel COMMON2CHANNEL - Convert a common name to a channel name
common2dev COMMON2DEV - Converts a common name to a device list
getfamilylist GETFAMILYLIST - Returns a list of all the family names
isfamily ISFAMILY - True for family names
saveao SAVEAO - Saves the AO and AD to a .mat file
setfamilydata SETFAMILYDATA - Sets data associated with accelerator control
showao SHOWAO - Display the AcceleratorObjects fields that have get or set capability
showfamily SHOWFAMILY - Displays a list of all families
SOURCE CODE
function  AO = getao(FileName)
%GETAO - returns the AcceleratorObject (AO)
%  AO = getao(FileName)
%
%  If FileName = 'Archive', then the AO and AD are saved to the
%                default directory under the data root
%  If FileName = a string beside 'Archive', then the AO and AD are saved
%                to that string name
AO = getappdata(0, 'AcceleratorObjects');
% if isempty(AO)
%     warning('AcceleratorObject not initialized');
%     return;
% end
% Archive data structure
if nargin >= 1
    if strcmpi(FileName,'archive')
        AD = getad;
        DirStart = pwd;
        FileName = appendtimestamp('AO', clock);
        DirectoryName = fullfile(getfamilydata('Directory','DataRoot'),'AO\');
        [DirectoryName, ErrorFlag] = gotodirectory(DirectoryName);
        save(FileName, 'AO', 'AD');
        cd(DirStart);
    else
        save(FileName, 'AO', 'AD');
    end
end