Description of getfamilylist
Home > mml > getfamilylist.m
getfamilylist
PURPOSE
GETFAMILYLIST - Returns a list of all the family names
SYNOPSIS
function [Families, AO] = getfamilylist(OutputFlag)
DESCRIPTION
GETFAMILYLIST - Returns a list of all the family names
  [Families, AO] = getfamilylist  (matrix of strings)
  [Families, AO] = getfamilylist('Cell')  (cell array of strings)
  See also showao, showfamily, isfamily
CROSS-REFERENCE INFORMATION
This function calls:
getao GETAO - returns the AcceleratorObject (AO)
This function is called by:
aokeep AOKEEP - Removes families from the Accelerator Families except those included in KEEPLIST
bpm2quad BPM2QUAD - Returns the nearest quadrupole to the specified BPM
bpm2sext BPM2SEXT - Returns the nearest sextupole to the specified BPM
channel2common CHANNEL2COMMON - Convert a channel name to a common name
channel2handle CHANNEL2HANDLE - Returns the MCA handle (obsolete)
common2channel COMMON2CHANNEL - Convert a common name to a channel name
common2handle COMMON2HANDLE - Converts a common name to a MCA handle (Obsolete function)
findmemberof FINDMEMBEROF - Finds all family members
getmachineconfig GETMACHINECONFIG - Returns or saves to file the present storage ring setpoints and monitors
getmemberof GETMEMBEROF - Returns the membership information of a family (cell of strings)
makephysdata MAKEPHYSDATA - Make a starting physics data file
mmlviewer MMLVIEWER M-file for mmlviewer.fig
plotfamily PLOTFAMILY - Plots by middle layer family name
quad2bpm QUAD2BPM - Returns the nearest BPM to the specified quadrupole
quadcenter QUADCENTER - Measure the magnet center of a quadrupole magnet
sext2bpm SEXT2BPM - Returns the nearest BPM to the specified sextupole
showmachinedata SHOWMACHINEDATA - Display setpoints and readbacks for families in AcceleratorObjects
switch2hardware SWITCH2HARDWARE - Switch family to hardware units
switch2manual SWITCH2MANUAL - Switch family to manual mode
switch2online SWITCH2ONLINE - Switch family to online mode
switch2physics SWITCH2PHYSICS - Switch family to physics units
switch2sim SWITCH2SIM - Switch family to simulator mode if the family is in online mode.
SOURCE CODE
function  [Families, AO] = getfamilylist(OutputFlag)
%GETFAMILYLIST - Returns a list of all the family names
%
%  [Families, AO] = getfamilylist  (matrix of strings)
%  [Families, AO] = getfamilylist('Cell')  (cell array of strings)
%
%  See also showao, showfamily, isfamily
%  Written by Greg Portmann
if nargin == 0
    OutputFlag = 'Matrix';
end
AO = getao;
if isempty(AO)
    error('Initialization is needed (aoinit)');
end
if strcmpi(OutputFlag, 'Cell')
    % Cell array output
    Families = fieldnames(AO);
else
    % Matrix output
    Families = [];
    AOFamilyCell = fieldnames(AO);
    for i = 1:length(AOFamilyCell)
        Families = strvcat(Families, AOFamilyCell{i});
    end
end
if nargout == 0
    % Print to the screen
    for i = 1:size(Families,1)
        if strcmpi(OutputFlag, 'Cell')
            fprintf('  %2d.  %s\n', i, Families{i});
        else
            fprintf('  %2d.  %s\n', i, deblank(Families(i,:)));
        end
    end
end