Description of getfamilydata
Home > mml > getfamilydata.m
getfamilydata
PURPOSE
GETFAMILYDATA - Gets data associated with the accelerator control
SYNOPSIS
function [Data, ErrorFlag] = getfamilydata(Family, Field1, Field2, DeviceList)
DESCRIPTION
GETFAMILYDATA - Gets data associated with the accelerator control
  When getting data from the accelerator object (AO):
  [Data, ErrorFlag] = getfamilydata(Family, Field1, Field2, DeviceList)
  [Data, ErrorFlag] = getfamilydata(Family, Field1, DeviceList)
  [Data, ErrorFlag] = getfamilydata(Family, Field1)
  [Data, ErrorFlag] = getfamilydata(Family)
  [Data, ErrorFlag] = getfamilydata
  When getting data from the accelerator data stucture (AD):
  [Data, ErrorFlag] = getfamilydata(Field1)
  [Data, ErrorFlag] = getfamilydata(Field1, Field2)
  [Data, ErrorFlag] = getfamilydata(Field1, Field2, Field3)
  [Data, ErrorFlag] = getfamilydata(Field1, Field2, Field3, Field4)
  INPUTS
  1. Family = Family Name
              Data Structure (only the FamilyName is used)
              Field
              Accelerator Object
  2. Field1 = Field name (string)
  3. Field2 = Field name (string)
  4. DeviceList = Device list for that family
  OUTPUT
  1. Data = AO.Field1.Field2  or  AD.Field1.Field2.Field3.Field4
     Looks for Family in the accelerator data structure and returns the appropriate data.
     If DeviceList is not an input, then the exact contents of the field is returned
     If DeviceList exists, then Data is indexed according to DeviceList
     If DeviceList is empty, [], then the entire DeviceList is returned
     If DeviceList is empty, [], and the field is one row (or cell) then Data is expanded
                                 to the size of the entire DeviceList
     Returns [] if the data could not be found
  2. ErrorFlag = 1 if the data could not be found
  NOTE
  1. If the inputs are cell arrays, then the output is a cell array
  2. If Family is a cell array, then DeviceList must also be a cell array,
     however, Field1 or Field2 can either be a cell array array or a string.
  EXAMPLES
  1. getfamilydata('BPMx')
  2. getfamilydata('BPMx','Monitor')
  3. getfamilydata('BPMx','Monitor','Units')
  4. getfamilydata('HCOR', 'Status')
  See also setfamilydata
CROSS-REFERENCE INFORMATION
This function calls:
elem2dev ELEM2DEV - Converts a device list to an element list
family2dev FAMILY2DEV - Return the device list for a family
getad GETAD - returns the Accelerator Data (AD) structure
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
isfamily ISFAMILY - True for family names
This function is called by:
addmenuad ADDMENUAD - Adds a menu bar to view and edit the MML AD structure
addmenuao ADDMENUAO - Adds a menu bar to view and edit the MML AO structure
bpm2quad BPM2QUAD - Returns the nearest quadrupole to the specified BPM
buildopsdatafiles BUILDOPSDATAFILES - Builds the files for the OpsData directory from the model
cddataroot CDDATAROOT - Change to the MML data directory
cdmachine CDMACHINE - Change directory to the sub-machine directory
cdopsdata CDOPSDATA - Change to the MML operational data directory
channel2common CHANNEL2COMMON - Convert a channel name to a common name
channel2handle CHANNEL2HANDLE - Returns the MCA handle (obsolete)
common2handle COMMON2HANDLE - Converts a common name to a MCA handle (Obsolete function)
copybpmrespfile COPYBPMRESPFILE - Copies a BPM response matrix file to the golden file
copybpmsigmafile COPYBPMSIGMAFILE - Copies a BPM data file to the golden BPM sigma file
copychrorespfile COPYCHRORESPFILE - Copies a chromaticity response matrix file to the golden file
copydispersionfile COPYDISPERSIONFILE - Copies a dispersion file to golden file
copydisprespfile COPYDISPRESPFILE - Copies a dispersion response matrix file to the golden file
copyinjectionconfigfile COPYINJECTIONCONFIGFILE - Copies a lattice file to the golden injection file
copymachineconfigfile COPYMACHINECONFIGFILE - Copies a lattice file to the golden file
copytunerespfile COPYTUNERESPFILE - Copies a tune response matrix file to the golden file
correctors2golden CORRECTORS2GOLDEN - Sets the default corrector families to the golden configuration values
dev2common DEV2COMMON - Converts a device list to a common name list
dev2elem DEV2ELEM - Converts an element list to a device list
family2channel FAMILY2CHANNEL - Converts the family name to a channel name
family2common FAMILY2COMMON - Convert a family name, device list to a common name list
family2datastruct FAMILY2DATASTRUCTURE
family2dev FAMILY2DEV - Return the device list for a family
family2elem FAMILY2ELEM - Return the device list for a family
family2status FAMILY2STATUS - Returns the device status
family2tol FAMILY2TOL - Return the (SP-AM) tolerance for a family
findrf1 FINDRF1 - Finds the RF frequency that minimizes the horizonal dispersion
getao GETAO - returns the AcceleratorObject (AO)
getbpm GETBPM - Returns the horizontal and vertical orbit
getbpmresp GETBPMRESP - Returns the BPM response matrix in the horizontal and vertical planes
getbrho GETBRHO - Calculations of the beam rigidity
getchro GETCHRO - Return the chromaticity function (from file)
getchroresp GETCHRORESP - Loads the chromaticity response vector (or matrix) for multiple sextupole families
getcircumference GETCIRCUMFERENCE - Returns the ring circumference
getcrunch GETCRUNCH- Returns the crunch values for a family (radians)
getdisp GETDISP - Returns the dispersion for a BPM family (from file)
getenergy GETENERGY - Returns the beam energy base on the bend magnet
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
getgain GETGAIN - Returns the gain for a family
getgolden GETGOLDEN - Returns the golden values for a family
getinjectionlattice GETINJECTIONLATTICE - Get data from the injection lattice file
getlattice GETLATTICE - Get data from a lattice file
getmachineconfig GETMACHINECONFIG - Returns or saves to file the present storage ring setpoints and monitors
getmachinename GETMACHINENAME - Return name of the machine loaded in MML
getmcf GETMCF - Returns the momentum compaction factor (MCF) stored in the AD or the model
getmemberof GETMEMBEROF - Returns the membership information of a family (cell of strings)
getmode GETMODE - Returns the present family mode ('Online', 'Simulator', 'Manual', 'Special', etc)
getnumberofsectors GETNUMBEROFSECTORS - Number of sectors in the lattice
getoffset GETOFFSET - Returns the offset values for a family
getphysdata GETPHYSDATA - Gets physics data
getproductionlattice GETPRODUCTIONLATTICE - Get data from the production (golden) lattice file
getpv GETPV - Returns a variable from the online system or the model
getramprate GETRAMPRATE - Returns the ramp rate for a family
getrespmat GETRESPMAT - Get response matrix data from a file
getrf GETRF - Gets the RF frequency
getroll GETROLL - Returns the roll values for a family (radians)
getrunflag GETRUNFLAG - Returns position if the device is in the process of changing a setpoint
getsigma GETSIGMA - Return the standard deviation in the monitor for a family
getspos GETSPOS - Returns the longitudinal position in meters
gettune GETTUNE - Returns the betatron tunes
gettuneresp GETTUNERESP - Loads the tune response vector (or matrix) for multiple quadrupole families
getunits GETUNITS - Return the present family units and units string
getuniverse GETUNIVERSE - Returns a structure of stable lattice configurations
getx GETX - Returns the horizontal orbit
gety GETY - Returns the vertical orbit
getz GETZ - Returns the vertical orbit
golden2sim GOLDEN2SIM - loads online machine configuration to AT configuration
hw2physics HW2PHYSICS - Converts from 'Hardware' units to 'Physics' units
isbooster ISBOOSTER - Is this a booster ring?
ismachine ISMACHINE - Test for accelerator location
isstoragering ISSTORAGERING - Is this a storage ring?
istransport ISTRANSPORT - Is this a transport line?
loadao LOADAO - Loads the AO and AD from a .mat file
loadorbit LOADORBIT - Loads orbit by file/directory specification - or - Golden %orbit by default
makebump MAKEBUMP - Creates and orbit correction structure (OCS) usable by setorbit
makephysdata MAKEPHYSDATA - Make a starting physics data file
maxpv MAXPV - Maximum value of a process variable
measbeta MEASBETA - Measure the betatron functions
measbpmresp MEASBPMRESP - Measures the BPM response matrix in the horizontal and vertical planes
measbpmresplinearity MEASBPMRESPLINEARITY - Compute BPMlinearity
measchro MEASCHRO - measures the chromaticity function emperically
measchroresp MEASCHRORESP - measures the response from sextupoles to chromaticity
meascmhysteresis MEASCMHYSTERESIS - Measure corrector magnet hysteresis
measdisp MEASDISP - Measures the dispersion function
measidfftable MEASIDFFTABLE - Measures an insertion device feed forward table for the vertical gap
measlocodata MEASLOCODATA - Measures a set of LOCO data
measrespmat MEASRESPMAT - Measure a response matrix
meastuneresp MEASTUNERESP - Measures the response from quadrupole to tune
minpv MinPV - Maximum value of a process variable
mmlviewer MMLVIEWER M-file for mmlviewer.fig
monbpm MONBPM - Monitors the orbit
monbpmpsd BPM_PSD - Computes the power spectral density of orbit data
monmags MONMAGS - Monitors all magnet power supplies and plots various statistics
orbitcorrectionmethods ORBITCORRECTIONMETHODS - Some the orbit correction methods used on light sources
physics2hw PHYSICS2HW - Converts from 'Physics' units to 'Hardware' units
plotbpmrespsym PLOTBPMRESPSYM - Looks for symmetry of the orbit response matrix
plotcm PLOTCM - Plots the horizontal and vertical corrector magnet families and
plotdisp PLOTDISP - Plots the dispersion function
plotfamily PLOTFAMILY - Plots by middle layer family name
plotgoldenorbit PLOTGOLDENORBIT - Plots the golden orbit
plotidfftable PLOTIDFFTABLE - Plots various information about the feed forward tables
plotlattice PLOTLATTICE - Plot the lattice
plotmeasbeta PLOTMEASBETA - plot quadrupole betatron function from measurement
plotmemberof PLOTMEMBEROF - Plots the setpoint and monitor for all members in a "MemberOf" group
plotoffsetorbit PLOTOFFSETORBIT - Plots the offset orbit
plotorbit PLOTORBIT - Plot the present orbit w.r.t. the golden or offset orbit
plotorbitdata PLOTORBITDATA - Plots BPM statistics
quad2bpm QUAD2BPM - Returns the nearest BPM to the specified quadrupole
quadcenter QUADCENTER - Measure the magnet center of a quadrupole magnet
quadgetdata QUADGETDATA - Collect the date from a quadrupole center run.
quadplot QUADPLOT - Plots quadrupole centering data
quadplotall QUADPLOTALL - Collect the date from a quadrupole center run.
quadplotphysics QUADPLOTPHYSICS - Plots quadrupole centering data in physics units
saveao SAVEAO - Saves the AO and AD to a .mat file
savegoldenorbit SAVEGOLDENORBIT - Save the golden orbit to a file
saveoffsetorbit SAVEOFFSETORBIT - Save the offset orbit to a file
setao SETAO - Set the MML Accelerator Object (AO)
setenergy SETENERGY - Sets the storage ring energy (GeV) by ramping all lattice magnets
setgolden SETGOLDEN - Set the golden values
setmachineconfig SETMACHINECONFIG - Sets the storage ring setpoints from a file or configuration data structure
setoffset SETOFFSET - Set the offset value for this matlab session (not saved)
setorbit SETORBIT - Orbit correction function
setorbitbump SETORBITBUMP - Local bump program (uses setorbit)
setorbitbumpgui SETORBITBUMPGUI M-file for setorbitbumpgui.fig
setorbitgui SETORBITGUI - Orbit correction GUI
setphysdata SETPHYSDATA - Set physics data
setpv SETPV - Setpoint change of the online system or model
setrf SETRF - Sets the RF frequency
switch2hardware SWITCH2HARDWARE - Switch family to hardware units
switch2manual SWITCH2MANUAL - Switch family to manual mode
switch2online SWITCH2ONLINE - Switch family to online mode
switch2physics SWITCH2PHYSICS - Switch family to physics units
switch2sim SWITCH2SIM - Switch family to simulator mode if the family is in online mode.
switchunits SWITCHUNITS - Change the units field for all families in the MML
whereami WHOAMI - Accelerator name
SUBFUNCTIONS
function Data = sortdatabydevicelist(Data, DeviceList, DeviceListTotal)
SOURCE CODE
function [Data, ErrorFlag] = getfamilydata(Family, Field1, Field2, DeviceList)
%GETFAMILYDATA - Gets data associated with the accelerator control
%
%  When getting data from the accelerator object (AO):
%  [Data, ErrorFlag] = getfamilydata(Family, Field1, Field2, DeviceList)
%  [Data, ErrorFlag] = getfamilydata(Family, Field1, DeviceList)
%  [Data, ErrorFlag] = getfamilydata(Family, Field1)
%  [Data, ErrorFlag] = getfamilydata(Family)
%  [Data, ErrorFlag] = getfamilydata
%
%  When getting data from the accelerator data stucture (AD):
%  [Data, ErrorFlag] = getfamilydata(Field1)
%  [Data, ErrorFlag] = getfamilydata(Field1, Field2)
%  [Data, ErrorFlag] = getfamilydata(Field1, Field2, Field3)
%  [Data, ErrorFlag] = getfamilydata(Field1, Field2, Field3, Field4)
%
%  INPUTS
%  1. Family = Family Name
%              Data Structure (only the FamilyName is used)
%              Field
%              Accelerator Object
%  2. Field1 = Field name (string)
%  3. Field2 = Field name (string)
%  4. DeviceList = Device list for that family
%
%  OUTPUT
%  1. Data = AO.Field1.Field2  or  AD.Field1.Field2.Field3.Field4
%     Looks for Family in the accelerator data structure and returns the appropriate data.
%
%     If DeviceList is not an input, then the exact contents of the field is returned
%     If DeviceList exists, then Data is indexed according to DeviceList
%     If DeviceList is empty, [], then the entire DeviceList is returned
%     If DeviceList is empty, [], and the field is one row (or cell) then Data is expanded
%                                 to the size of the entire DeviceList
%
%     Returns [] if the data could not be found
%
%  2. ErrorFlag = 1 if the data could not be found
%
%  NOTE
%  1. If the inputs are cell arrays, then the output is a cell array
%  2. If Family is a cell array, then DeviceList must also be a cell array,
%     however, Field1 or Field2 can either be a cell array array or a string.
%
%  EXAMPLES
%  1. getfamilydata('BPMx')
%  2. getfamilydata('BPMx','Monitor')
%  3. getfamilydata('BPMx','Monitor','Units')
%  4. getfamilydata('HCOR', 'Status')
%
%  See also setfamilydata
%  Written by Greg Portmann
if nargin == 0
    Data = getappdata(0, 'AcceleratorObjects');
    return
end
% Cell array input
if iscell(Family)
    if nargin >= 2
        if iscell(Field1)
            if length(Family) ~= length(Field1)
                error('If Field1 is a cell array, then it must be the same size as Family.');
            end
        end
    end
    if nargin >= 3
        if iscell(Field2)
            if length(Family) ~= length(Field2)
                error('If Field2 is a cell array, then it must be the same size as Family.');
            end
        end
    end
    if nargin >= 4
        if ~iscell(DeviceList)
            error('If family is a cell array, then DeviceList must be a cell array.');
        end
        if length(Family) ~= length(DeviceList)
            error('Family and DeviceList must be the same size cell arrays.');
        end
    end
    for i = 1:length(Family)
        if nargin == 1
            [Data{i}, ErrorFlag{i}] = getfamilydata(Family{i});
        elseif nargin == 2
            if iscell(Field1)
                [Data{i}, ErrorFlag{i}] = getfamilydata(Family{i}, Field1{i});
            else
                [Data{i}, ErrorFlag{i}] = getfamilydata(Family{i}, Field1);
            end
        elseif nargin == 3
            if iscell(Field1)
                if iscell(Field2)
                    [Data{i}, ErrorFlag{i}] = getfamilydata(Family{i}, Field1{i}, Field2{i});
                else
                    [Data{i}, ErrorFlag{i}] = getfamilydata(Family{i}, Field1{i}, Field2);
                end
            else
                if iscell(Field2)
                    [Data{i}, ErrorFlag{i}] = getfamilydata(Family{i}, Field1, Field2{i});
                else
                    [Data{i}, ErrorFlag{i}] = getfamilydata(Family{i}, Field1, Field2);
                end
            end
        else
            if iscell(Field1)
                if iscell(Field2)
                    [Data{i}, ErrorFlag{i}] = getfamilydata(Family{i}, Field1{i}, Field2{i}, DeviceList{i});
                else
                    [Data{i}, ErrorFlag{i}] = getfamilydata(Family{i}, Field1{i}, Field2, DeviceList{i});
                end
            else
                if iscell(Field2)
                    [Data{i}, ErrorFlag{i}] = getfamilydata(Family{i}, Field1, Field2{i}, DeviceList{i});
                else
                    [Data{i}, ErrorFlag{i}] = getfamilydata(Family{i}, Field1, Field2, DeviceList{i});
                end
            end
        end
    end
    return
end  % End cell inputs
%%%%%%%%%%%%%%%%%%%%%%%%%%
% Non-cell getfamilydata %
%%%%%%%%%%%%%%%%%%%%%%%%%%
ErrorFlag = 0;
[FamilyIndex, AO] = isfamily(Family);
if FamilyIndex
    if nargin == 1
        Data = AO;
        return
    end
else
    % Check the AD
    AD = getad;
    if isfield(AD, Family)
        Data = AD.(Family);
    else
        Data = [];
        ErrorFlag = 1;
        return
    end
    if nargin > 1
        if isfield(Data, Field1)
            Data = Data.(Field1);
        else
            Data = [];
            ErrorFlag = 1;
        end
    end
    if nargin > 2
        if isfield(Data, Field2)
            Data = Data.(Field2);
        else
            Data = [];
            ErrorFlag = 1;
        end
    end
    return
end
% Select field1
if isfield(AO, Field1)
    Data = AO.(Field1);
else
    Data = [];
    ErrorFlag = 1;
    return
end
if nargin == 2
    return
end
% Select field2 or field2 maybe a devicelist
if nargin == 3
    if ischar(Field2)
        if isfield(Data, Field2)
            Data = Data.(Field2);
        else
            Data = [];
            ErrorFlag = 1;
        end
        return
    else
        DeviceList = Field2;
    end
end
% Select field2
if nargin >= 4
    if isfield(Data, Field2)
        Data = Data.(Field2);
    else
        Data = [];
        ErrorFlag = 1;
        return
    end
end
% If you made it to here, DeviceList must exist
if isempty(DeviceList)
    DeviceList = family2dev(Family);
end
if (size(DeviceList,2) == 1)
    DeviceList = elem2dev(Family, DeviceList);
end
DeviceListTotal = AO.DeviceList;
%DeviceListTotal = family2dev(Family, 0);
if iscell(Data)
    if size(Data,1) == 1
        % For each cell array determine what rows needs to be altered
        for i = 1:size(Data,2)
            Data{i} = sortdatabydevicelist(Data{i}, DeviceList, DeviceListTotal);
        end
        return
    elseif size(Data,1) == size(DeviceListTotal,1)
        % Cell matrix is Ok (but not recommended)
    else
        error(sprintf('Number of rows in AO field must be 1 or equal to the number of rows in AO{}.DeviceList.'));
    end
elseif isstruct(Data)
    error('Structure AO fields can not be indexed by a DeviceList.');
end
Data = sortdatabydevicelist(Data, DeviceList, DeviceListTotal);
function Data = sortdatabydevicelist(Data, DeviceList, DeviceListTotal)
% Data should be equal to the number of row in DeviceListTotal or be one row
if size(DeviceListTotal,1) ~= size(Data,1)
    if size(Data,1) == 1
        % All the rows of output data will be the same
        if iscell(Data)
            % This will make a cell matrix which we decided not a allow
            fprintf('   When using a 1 row cell array, Instead of using a cell matrix, use a cell row.\n')
            error('Cell matrix error')
            % Repeat the 1 row Data cell array as many times as in the rows of DeviceListTotal
            Data1 = Data;
            Data = cell(size(DeviceList,1), size(Data1,2));
            for i = 1:size(Data1,2)
                Data(:,i) = Data1(1,i);
            end
        elseif ischar(Data)
            % Repeat the one row string as many times as in the rows of DeviceListTotal
            DataStr = Data;
            Data = [];
            for i = 1:size(DeviceList,1)
                Data = [Data; DataStr];
            end
        else
            % Repeat the one row Data vector as many times as in the rows of DeviceListTotal
            Data = ones(size(DeviceList,1),1) * Data;
        end
    else
        error(sprintf('Number of rows in AO field must be 1 or equal to the number of rows in AO{}.DeviceList.'));
    end
    return
end
[DeviceIndex, iNotFound] = findrowindex(DeviceList, DeviceListTotal);
if ~isempty(iNotFound)
    ErrorFlag = 1;
    for i = 1:length(iNotFound)
        fprintf('   Can''t find (%d,%d) device in DeviceList.\n', DeviceList(iNotFound(i),1), DeviceList(iNotFound(i),2));
    end
    error(sprintf('%d Devices not found', length(iNotFound)));
end
Data = Data(DeviceIndex,:);
% % Intersect removes duplicate devices so first store index of how to unsort in j_unique
% DeviceListOld = DeviceList;
% [DeviceList, i_unique, j_unique] = unique(DeviceList, 'rows');
%
% % Find the indexes in the full device list (reorder and remove duplicates)
% [DeviceList, ii, DeviceIndex] = intersect(DeviceList, DeviceListTotal, 'rows');
% if size(DeviceList,1) ~= size(DeviceListOld,1)
%     % All devices must exist (duplicate devices ok)
%     [DeviceListNotFound, iNotFound] = setdiff(DeviceListOld, DeviceListTotal, 'rows');
%     if length(iNotFound) > 0
%         % Device not found
%         for i = 1:length(iNotFound)
%             fprintf('   No devices to get for Family %s(%d,%d)\n', AO.FamilyName, DeviceListNotFound(i,1), DeviceListNotFound(i,2));
%         end
%         error(sprintf('%d Devices not found', length(iNotFound)));
%     end
% end
%
% % DataType='vector' only has one FamilyName and handle for a multiple element DeviceList
% % Hence, Data could have one row for a many rowed DeviceList.  To deal with this only index
% % by DeviceIndex if Data has more than one row.
% if size(Data,1) > 1
%     Data = Data(DeviceIndex,:);     % Only data referenced to DeviceList
%     Data = Data(j_unique,:);        % Reorder and add multiple elements back
% end