Description of gethbpmfamily
Home > mml > gethbpmfamily.m
gethbpmfamily
PURPOSE
GETHBPMFAMILY - Return the default horizontal BPM family
SYNOPSIS
function Family = gethbpmfamily(OneHit)
DESCRIPTION
GETHBPMFAMILY - Return the default horizontal BPM family
  Family = gethbpmfamily(OneHit)
  INPUTS
  1. OneHit - If true, return the first family found (Default: true)
  OUTPUTS
  1. Family - family name is determined by the MemberOf field equal to 'HBPM'
              If OneHit=0, then a cell array of families is returned.
  See also getvbpmfamily, gethcmfamily, getvcmfamily, findmemberof
CROSS-REFERENCE INFORMATION
This function calls:
findmemberof FINDMEMBEROF - Finds all family members
This function is called by:
amp2mm AMPS2MM - Returns the maximum millimeter orbit change per change in corrector
bpm2quad BPM2QUAD - Returns the nearest quadrupole to the specified BPM
bpm2sext BPM2SEXT - Returns the nearest sextupole to the specified BPM
getbpm GETBPM - Returns the horizontal and vertical orbit
getbpmresp GETBPMRESP - Returns the BPM response matrix in the horizontal and vertical planes
getdisp GETDISP - Returns the dispersion for a BPM family (from file)
getnumberofsectors GETNUMBEROFSECTORS - Number of sectors in the lattice
getx GETX - Returns the horizontal orbit
loadorbit LOADORBIT - Loads orbit by file/directory specification - or - Golden %orbit by default
measbpmresp MEASBPMRESP - Measures the BPM response matrix in the horizontal and vertical planes
measbpmresplinearity MEASBPMRESPLINEARITY - Compute BPMlinearity
measchro MEASCHRO - measures the chromaticity function emperically
meascmhysteresis MEASCMHYSTERESIS - Measure corrector magnet hysteresis
measdisp MEASDISP - Measures the dispersion function
mm2amp MM2AMPS - Returns the change in corrector need for a maximum orbit change
monbpm MONBPM - Monitors the orbit
monbpmpsd BPM_PSD - Computes the power spectral density of orbit data
orbitcorrectionmethods ORBITCORRECTIONMETHODS - Some the orbit correction methods used on light sources
plotdisp PLOTDISP - Plots the dispersion function
plotgoldenorbit PLOTGOLDENORBIT - Plots the golden orbit
plotoffsetorbit PLOTOFFSETORBIT - Plots the offset orbit
plotorbit PLOTORBIT - Plot the present orbit w.r.t. the golden or offset orbit
plotorbitdata PLOTORBITDATA - Plots BPM statistics
quad2bpm QUAD2BPM - Returns the nearest BPM to the specified quadrupole
quadcenterfit QUADCENTERFIT OR BBASEARCH - Model search method to find a quarupole center
savegoldenorbit SAVEGOLDENORBIT - Save the golden orbit to a file
saveoffsetorbit SAVEOFFSETORBIT - Save the offset orbit to a file
setgolden SETGOLDEN - Set the golden values
setorbit SETORBIT - Orbit correction function
setorbitbump SETORBITBUMP - Local bump program (uses setorbit)
setorbitbumpgui SETORBITBUMPGUI M-file for setorbitbumpgui.fig
setorbitgui SETORBITGUI - Orbit correction GUI
setorbitsetup SETORBITSETUP - BPM & CM setup function for setorbitgui
SOURCE CODE
function Family = gethbpmfamily(OneHit)
%GETHBPMFAMILY - Return the default horizontal BPM family
%  Family = gethbpmfamily(OneHit)
%
%  INPUTS
%  1. OneHit - If true, return the first family found (Default: true)
%
%  OUTPUTS
%  1. Family - family name is determined by the MemberOf field equal to 'HBPM'
%              If OneHit=0, then a cell array of families is returned.
%
%  See also getvbpmfamily, gethcmfamily, getvcmfamily, findmemberof
%  Written by Greg Portmann
%persistent WarningFlag
if nargin < 1
    OneHit = 1;
end
Family = findmemberof('HBPM', OneHit);
if isempty(Family)
    Family = findmemberof('BPMx', OneHit);
    if isempty(Family)
        fprintf('\n   No default horizontal BPM family has been specified in the MML.\n');
        fprintf('   To define one, add ''HBPM'' to the .MemberOf field for the default family.\n\n');
        error('No family found (gethbpmfamily)');
        %if isempty(WarningFlag)
        %    fprintf('\n   No default horizontal BPM family has been specified in the MML.\n');
        %    fprintf('   To define one, add ''BPMx'' or ''HBPM'' to the .MemberOf field for the default family.\n\n');
        %    WarningFlag = 1;
        %end
        %Family = {''};
    end
end
if OneHit
    Family = Family{1};
end