Description of gethcmfamily
Home > mml > gethcmfamily.m
gethcmfamily
PURPOSE
GETHCMFAMILY - Returns the default horizontal corrector family
SYNOPSIS
function Family = gethcmfamily(OneHit)
DESCRIPTION
GETHCMFAMILY - Returns the default horizontal corrector family
  Family = gethcmfamily(OneHit)
  INPUTS
  1. OneHit - If true, return the first family found (Default: true)
  OUTPUTS
  1. Family - family name is determined by the MemberOf field equal to 'HCM'
              If OneHit=0, then a cell array of families is returned.
  See also gethbpmfamily, getvbpmfamily, getvcmfamily, findmemberof
CROSS-REFERENCE INFORMATION
This function calls:
findmemberof FINDMEMBEROF - Finds all family members
This function is called by:
correctors2golden CORRECTORS2GOLDEN - Sets the default corrector families to the golden configuration values
findrf FINDRF - Finds the RF frequency that minimizes the energy change due
getbpmresp GETBPMRESP - Returns the BPM response matrix in the horizontal and vertical planes
getenergy GETENERGY - Returns the beam energy base on the bend magnet
getnumberofsectors GETNUMBEROFSECTORS - Number of sectors in the lattice
golden2sim GOLDEN2SIM - loads online machine configuration to AT configuration
hcm2golden HCM2GOLDEN - Set horizontal corrector strengths to golden values
hcm2zero HCM2ZERO - Set horizontal corrector strengths to zero
machine2sim MACHINE2SIM - loads online machine configuration to AT configuration
measbpmresp MEASBPMRESP - Measures the BPM response matrix in the horizontal and vertical planes
measbpmresplinearity MEASBPMRESPLINEARITY - Compute BPMlinearity
meascmhysteresis MEASCMHYSTERESIS - Measure corrector magnet hysteresis
measdispresp MEASDISPRESP - Measures Amman TERMs in response matrix
orbitcorrectionmethods ORBITCORRECTIONMETHODS - Some the orbit correction methods used on light sources
plotcm PLOTCM - Plots the horizontal and vertical corrector magnet families and
plotfamily PLOTFAMILY - Plots by middle layer family name
scanorbit SCANORBIT - Scans 2 correctors 90 degrees out of phase
setorbit SETORBIT - Orbit correction function
setorbitbump SETORBITBUMP - Local bump program (uses setorbit)
setorbitbumpgui SETORBITBUMPGUI M-file for setorbitbumpgui.fig
setorbitgui SETORBITGUI - Orbit correction GUI
setorbitsetup SETORBITSETUP - BPM & CM setup function for setorbitgui
SOURCE CODE
function Family = gethcmfamily(OneHit)
%GETHCMFAMILY - Returns the default horizontal corrector family
%  Family = gethcmfamily(OneHit)
%
%  INPUTS
%  1. OneHit - If true, return the first family found (Default: true)
%
%  OUTPUTS
%  1. Family - family name is determined by the MemberOf field equal to 'HCM'
%              If OneHit=0, then a cell array of families is returned.
%
%  See also gethbpmfamily, getvbpmfamily, getvcmfamily, findmemberof
%  Written by Greg Portmann
%persistent WarningFlag
if nargin < 1
    OneHit = 1;
end
Family = findmemberof('HCM', OneHit);
if isempty(Family)
    Family = findmemberof('HCOR', OneHit);
    if isempty(Family)
        fprintf('\n   No default horizontal corrector family has been specified in the MML.\n');
        fprintf('   To define one, add ''HCM'' to the .MemberOf field for the default family.\n\n');
        error('No family found (gethbpmfamily)');
        %if isempty(WarningFlag)
        %    fprintf('\n   No default horizontal corrector family has been specified in the MML.\n');
        %    fprintf('   To define one, add ''HCM'' or ''HCOR'' to the .MemberOf field for the default family.\n\n');
        %    WarningFlag = 1;
        %end
        %Family = {''};
    end
end
if OneHit
    Family = Family{1};
end