Description of getlist
Home > mml > getlist.m
getlist
PURPOSE
GETLIST - Returns Device List for a Family
SYNOPSIS
function DeviceList = getlist(varargin)
DESCRIPTION
GETLIST - Returns Device List for a Family
  getlist(FamilyName)
  (Same as family2dev)
  INPUTS
  1. FamilyNames
  OUTPUTS
  1. Device list for families specified in input
  2. StatusFlag = 0 return all devices
                 1 return only devices with good status {Default}
  EXAMPLES
  1. getlist('BPMx')
  2. getlist('HCOR',0)
  See also family2dev
CROSS-REFERENCE INFORMATION
This function calls:
family2dev FAMILY2DEV - Return the device list for a family
This function is called by:
bpm2sext BPM2SEXT - Returns the nearest sextupole to the specified BPM
dev2common DEV2COMMON - Converts a device list to a common name list
dev2elem DEV2ELEM - Converts an element list to a device list
elem2dev ELEM2DEV - Converts a device list to an element list
getphysdata GETPHYSDATA - Gets physics data
meascmhysteresis MEASCMHYSTERESIS - Measure corrector magnet hysteresis
monrate MONRATE - Calculates the control system data rate of a noisy channel
quadcenter QUADCENTER - Measure the magnet center of a quadrupole magnet
rmdisp RMDISP - Removes the portion of the orbit that correlates with the dispersion
setfamilydata SETFAMILYDATA - Sets data associated with accelerator control
setphysdata SETPHYSDATA - Set physics data
sext2bpm SEXT2BPM - Returns the nearest BPM to the specified sextupole
SOURCE CODE
function DeviceList = getlist(varargin)
%GETLIST - Returns Device List for a Family
%  getlist(FamilyName)
%  (Same as family2dev)
%
%  INPUTS
%  1. FamilyNames
%
%  OUTPUTS
%  1. Device list for families specified in input
%  2. StatusFlag = 0 return all devices
%                 1 return only devices with good status {Default}
%
%  EXAMPLES
%  1. getlist('BPMx')
%  2. getlist('HCOR',0)
%
%  See also family2dev
%  Written by Greg Portmann
DeviceList = family2dev(varargin{:});