Description of getnumberofsectors
Home > mml > getnumberofsectors.m
getnumberofsectors
PURPOSE
GETNUMBEROFSECTORS - Number of sectors in the lattice
SYNOPSIS
function [N, Nsymmetry] = getnumberofsectors
DESCRIPTION
GETNUMBEROFSECTORS - Number of sectors in the lattice
  [N, Nsymmetry] = getnumberofsectors
CROSS-REFERENCE INFORMATION
This function calls:
family2dev FAMILY2DEV - Return the device list for a family
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
gethbpmfamily GETHBPMFAMILY - Return the default horizontal BPM family
gethcmfamily GETHCMFAMILY - Returns the default horizontal corrector family
This function is called by:
SOURCE CODE
function [N, Nsymmetry] = getnumberofsectors
%GETNUMBEROFSECTORS - Number of sectors in the lattice
%  [N, Nsymmetry] = getnumberofsectors
% Get the sectors from the device list.
% Guess at a few family names.
List = family2dev(gethcmfamily);
if isempty(List)
    List = family2dev(gethbpmfamily);
end
if isempty(List)
    List = family2dev('BEND');
end
if isempty(List)
    N = 1;
else
    N = max(List(:,1));
end
if nargout >= 2
    if strcmpi(getfamilydata('Machine'), 'NSLS2')
        Nsymmetry = 15; %N/2;
    elseif strcmpi(getfamilydata('Machine'), 'SPEAR3')
        Nsymmetry = 2;
    elseif strcmpi(getfamilydata('Machine'), 'SSRF')
        Nsymmetry = 4;
    elseif strcmpi(getfamilydata('Machine'), 'ELSA')
        Nsymmetry = 1;
    else
        Nsymmetry = N;
    end
end