Description of getoffset
Home > mml > getoffset.m
getoffset
PURPOSE
GETOFFSET - Returns the offset values for a family
SYNOPSIS
function Data = getoffset(varargin)
DESCRIPTION
GETOFFSET - Returns the offset values for a family
  Offset = getoffset(Family, Field, DeviceList)
  Offset = getoffset(Family, DeviceList)
  Offset = getoffset(Family)
  INPUTS
  1. Family - Family Name
              Data Structure
              Accelerator Object
  2. Field - Accelerator Object field name ('Monitor', 'Setpoint', etc) {Default: 'Monitor' for BPM, 'Setpoint' for magnet}
  3. DeviceList ([Sector Device #] or [element #]) {Default: whole family}
  4. 'Physics'  - Use physics  units (optional override of units)
     'Hardware' - Use hardware units (optional override of units)
  5. 'Struct'  - Return a data structure
     'Numeric' - Return numeric outputs  {Default}
     'Object'  - Return a accelerator object (AccObj)
  OUTPUTS
  1. Offset - Offset value for the family {Default: 0}
  NOTES
  1. If Family is a cell array, then DeviceList can also be a cell arrays
  2. The offset orbit must be stored in hardware units.
  See also getfamilydata, getgolden, raw2real, real2raw
CROSS-REFERENCE INFORMATION
This function calls:
family2datastruct FAMILY2DATASTRUCTURE
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
getoffset GETOFFSET - Returns the offset values for a family
getphysdata GETPHYSDATA - Gets physics data
getunits GETUNITS - Return the present family units and units string
hw2physics HW2PHYSICS - Converts from 'Hardware' units to 'Physics' units
inputparsingffd INPUTPARSINGFFD - Parses the typical input line of Family, Field, DeviceList
ismemberof ISMEMBEROF - Returns turn if the membership information of a family (cell of strings)
This function is called by:
findrf1 FINDRF1 - Finds the RF frequency that minimizes the horizonal dispersion
getoffset GETOFFSET - Returns the offset values for a family
getsigma GETSIGMA - Return the standard deviation in the monitor for a family
hw2physics HW2PHYSICS - Converts from 'Hardware' units to 'Physics' units
makebump MAKEBUMP - Creates and orbit correction structure (OCS) usable by setorbit
meascmhysteresis MEASCMHYSTERESIS - Measure corrector magnet hysteresis
physics2hw PHYSICS2HW - Converts from 'Physics' units to 'Hardware' units
plotfamily PLOTFAMILY - Plots by middle layer family name
plotoffsetorbit PLOTOFFSETORBIT - Plots the offset orbit
plotorbit PLOTORBIT - Plot the present orbit w.r.t. the golden or offset orbit
quadcenter QUADCENTER - Measure the magnet center of a quadrupole magnet
quadcenterfit QUADCENTERFIT OR BBASEARCH - Model search method to find a quarupole center
quadplotall QUADPLOTALL - Collect the date from a quadrupole center run.
raw2real RAW2REAL - Converts raw control system data to calibrated values
real2raw REAL2RAW - Converts "real" data (calibrated values) to control system data
rmoffset RMOFFSET - Remove the offset values for data set
saveoffsetorbit SAVEOFFSETORBIT - Save the offset orbit to a file
setorbit SETORBIT - Orbit correction function
setorbitbump SETORBITBUMP - Local bump program (uses setorbit)
setorbitbumpgui SETORBITBUMPGUI M-file for setorbitbumpgui.fig
SOURCE CODE
function Data = getoffset(varargin)
%GETOFFSET - Returns the offset values for a family
%  Offset = getoffset(Family, Field, DeviceList)
%  Offset = getoffset(Family, DeviceList)
%  Offset = getoffset(Family)
%
%  INPUTS
%  1. Family - Family Name
%              Data Structure
%              Accelerator Object
%  2. Field - Accelerator Object field name ('Monitor', 'Setpoint', etc) {Default: 'Monitor' for BPM, 'Setpoint' for magnet}
%  3. DeviceList ([Sector Device #] or [element #]) {Default: whole family}
%  4. 'Physics'  - Use physics  units (optional override of units)
%     'Hardware' - Use hardware units (optional override of units)
%  5. 'Struct'  - Return a data structure
%     'Numeric' - Return numeric outputs  {Default}
%     'Object'  - Return a accelerator object (AccObj)
%
%  OUTPUTS
%  1. Offset - Offset value for the family {Default: 0}
%
%  NOTES
%  1. If Family is a cell array, then DeviceList can also be a cell arrays
%  2. The offset orbit must be stored in hardware units.
%
%  See also getfamilydata, getgolden, raw2real, real2raw
%  Written by Greg Portmann
%%%%%%%%%%%%%%%%%
% Input Parsing %
%%%%%%%%%%%%%%%%%
UnitsFlagCell = {};
StructOutputFlag = 0;
ObjectOutputFlag = 0;
for i = length(varargin):-1:1
    if isstruct(varargin{i})
        % Ignor structures
    elseif iscell(varargin{i})
        % Ignor cells
    elseif strcmpi(varargin{i},'struct')
        StructOutputFlag = 1;
        varargin(i) = [];
    elseif strcmpi(varargin{i},'numeric')
        StructOutputFlag = 0;
        varargin(i) = [];
    elseif strcmpi(varargin{i},'simulator') || strcmpi(varargin{i},'model') || strcmpi(varargin{i},'Online') || strcmpi(varargin{i},'Manual')
        % Remove and ignor
        varargin(i) = [];
    elseif strcmpi(varargin{i},'physics')
        UnitsFlagCell = {'Physics'};
        varargin(i) = [];
    elseif strcmpi(varargin{i},'hardware')
        UnitsFlagCell = {'Hardware'};
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Object')
        ObjectOutputFlag = 1;
        StructOutputFlag = 1;
        varargin(i) = [];
    end
end
if isempty(varargin)
    error('Must have at least a family name input');
end
%%%%%%%%%%%%%%
% Cell input %
%%%%%%%%%%%%%%
if iscell(varargin{1})
    for i = 1:length(varargin{1})
        if length(varargin) < 2
            Data{i} = getoffset(varargin{1}{i}, UnitsFlagCell{:});
        elseif length(varargin) < 3
            if iscell(varargin{2})
                Data{i} = getoffset(varargin{1}{i}, varargin{2}{i}, UnitsFlagCell{:});
            else
                Data{i} = getoffset(varargin{1}{i}, varargin{2}, UnitsFlagCell{:});
            end
        else
            if iscell(varargin{3})
                Data{i} = getoffset(varargin{1}{i}, varargin{2}{i}, varargin{3}{i}, UnitsFlagCell{:});
            else
                Data{i} = getoffset(varargin{1}{i}, varargin{2}{i}, varargin{3}, UnitsFlagCell{:});
            end
        end
    end
    return
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Parse Family, Field, DeviceList %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[Family, Field, DeviceList, UnitsFlag] = inputparsingffd(varargin{:});
% Units flag
if isempty(UnitsFlagCell)
    % For structure inputs, use the units in the structure (from inputparsingffd)
    % Else, get the default family value
    if isempty(UnitsFlag)
        UnitsFlag = getunits(Family);
    end
else
    % Input override has priority
    UnitsFlag = UnitsFlagCell{1};
end
% Default field is Monitor for BPMs else Setpoint
if isempty(Field)
    if ismemberof(Family,'BPM')
        Field = 'Monitor';
    else
        Field = 'Setpoint';
    end
end
%%%%%%%%%%%%
% Get data %
%%%%%%%%%%%%
% 1. Try the AO and AD
Data = getfamilydata(Family, Field, 'Offset', DeviceList);
if isempty(Data) && (strcmp(Field, 'Monitor') || strcmp(Field, 'Setpoint'))
    Data = getfamilydata(Family, 'Offset', DeviceList);
end
% 2. Then look in PhysData
if isempty(Data)
    try
        Data = getphysdata(Family, Field, 'Offset', DeviceList);
    catch
    end
end
if isempty(Data) && (strcmp(Field, 'Monitor') || strcmp(Field, 'Setpoint'))
    try
        Data = getphysdata(Family, 'Offset', DeviceList);
    catch
    end
end
% Default offset
if isempty(Data)
    Data = zeros(size(DeviceList,1),1);
end
if isstruct(Data)
    Data = Data.Data;
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Change to physics units if requested %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if strcmpi(UnitsFlag,'Physics')
    % Offsets in physics units are zero!
    Data = hw2physics(Family, Field, Data, DeviceList);
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Return a data structure if requested %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if StructOutputFlag
    DataNumeric = Data;
    if isempty(UnitsFlag)
        Data = family2datastruct(Family, Field, DeviceList);
    else
        Data = family2datastruct(Family, Field, DeviceList, UnitsFlag);
    end
    Data.Data = DataNumeric;
    Data.DataDescriptor = sprintf('%s.%s Offset', Family, Field);
    Data.CreatedBy = 'getoffset';
    % Make the output an AccObj object
    if ObjectOutputFlag
        Data = AccObj(Data);
    end
end