Description of getpv
Home > mml > getpv.m
getpv
PURPOSE
GETPV - Returns a variable from the online system or the model
SYNOPSIS
function [AM, tout, DataTime, ErrorFlag] = getpv(varargin)
DESCRIPTION
GETPV - Returns a variable from the online system or the model
  FamilyName/DeviceList Method
  [AM, tout, DataTime] = getpv(Family, Field, DeviceList, t, FreshDataFlag, TimeOutPeriod)
  Data Structure
  [AM, tout, DataTime] = getpv(DataStructure, t, FreshDataFlag, TimeOutPeriod)
  ChannelName Method
  [AM, tout, DataTime] = getpv(ChannelName, t, FreshDataFlag, TimeOutPeriod)
  CommonName Method (Family can be '' to search all families, Field is optional)
  [AM, tout, DataTime] = getpv(CommonName, Field, t, FreshDataFlag, TimeOutPeriod)
  [AM, tout, DataTime] = getpv(Family, Field, CommonName, t, FreshDataFlag, TimeOutPeriod)
  INPUTS
  1. Family - Family Name
              Data Structure
              Channel Name or matrix of Channel Names
              Accelerator Object (only the family name is used)
              For CommonNames, Family=[] searches all families
              (or Cell Array of inputs)
  2. Field - Subfield name of an accelerator family ('Monitor', 'Setpoint', etc)
             {Default: 'Monitor' or '' or ChannelName method}
             (For non-Family subfields, Field is added as .Field, see Note #8 below for more information.)
  3. DeviceList - [Sector Device #] or [element #] list {Default or empty list: Entire family}
                  Note: if input 1 is a cell array then DeviceList must be a cell array
     CommonName - Common name can replace a DeviceList (scalar or vector outputs)
  4. t - Time vector of when to start taking data (t can not be a cell) {Default: 0}
  5. FreshDataFlag -  0   -> Return after first measurement {Default}
                     else -> Return after FreshDataFlag number of new measurements have been read
                     Ie, getpv('BPMx',[1 1],0,2) measures the orbit then continues to read the orbit
                         until 2 new orbits have been measured and returns the last measurement.
                     Note: 1. t can only be a scalar when using the FreshDataFlag.
                           2. FreshDataFlag cannot be used with 'Matrix' data types.
  6. TimeOutPeriod - Time-out period when waiting for fresh data {Default: 10 seconds}
  7. 'Struct'  - Return a data structure {Default for data structure inputs}
     'Numeric' - Return numeric outputs  {Default for non-data structure inputs}
     'Object'  - Return a accelerator object (AccObj)
  8. Units flag overrides
     'Physics'  - Use physics  units
     'Hardware' - Use hardware units
  9. Mode flag overrides
     'Online' - Get data online
     'Model'  - get data on the model
     'Manual' - Get data manually
  10. 'Double' - The output will be a double {Default}
      'String' - The output will be a string
  OUTPUTS
  1. AM   - Monitor values (Column vector or matrix where each column is a data point in time)
  2. tout - Time when measurement was completed according to the computer time (Matlab time) (row vector)
            tout-t is the time it took to make the measurement.  diff(t) can be arbitarily small, but tout will
            report the actual completion time.
  3. DataTime - Time when the data was measured (as report by the hardware)
                Time since 00:00:00, Jan 1, 1970 in days (in the present time zone)
                Units are in Matlab "serial day number" format (days) to be compatible with
                timing functions like datevec, datenum, datetick, etc.
                For exmple, [d, tout, datatime] = getpv('BPMx', 'Monitor', [], 0:.5:10);
                            plot(datatime, d); datetick x
                When using the model, the datatime is the same a the computer time (Matlab time).
  NOTES
  1. The output will be a data structure if the word 'struct' appears somewhere on the input line
     or if the input is a data structure and 'numeric' is not on the input line.
  2. For data structure inputs:
     Family     - DataStructure.FamilyName (This field must exist)
     Field      - DataStructure.Field      (Field can be overridden on the input line)
     DeviceList - DataStructure.DeviceList (DeviceList can be overridden on the input line)
     Units      - DataStructure.Units      (Units can be overridden on the input line)
     (The Mode field is ignored!)
  3. For data structure outputs:
     TimeStamp  - Time (Matlab clock) at the start of the function
     tout       - Delta time vector at the end of each measurement (relative to TimeStamp)
  4. diff(t) should not be too small.  If the desired time to collect the data is too
     short then the data collecting will not be able to keep up.  Always check tout.
     (t - tout) is the time it took to collect the data on each iteration.
  5. An easy way to averaged 10 monitors is:
     PVmean = mean(getpv(Family,DeviceList,0:.5:4.5)')';   % .5 second between measurements
  6. Channel name method is always Online!
  7. It is often useful to measure the update rate of a set of channel by using a very
     small time between measurements.
     For exmple, [d, tout] = getpv('BPMx', 'Monitor', [], 0:eps:100*eps);
                 plot(tout(1:end-1), 1./diff(tout),'.-'); % Point-wise data rate
                 If the update rate of the hardware is slower then the control system, then
                 hardware data rate can be visually inspected by plotting,
                 plot(tout, d,'.-');
  8. For cell array inputs:
     a. Input 1 defines the size of all cells
     b. All of the cell array inputs must be the same size
     c. Field does not have to be a cell array but DeviceList does (if they exist)
     d. t, FreshDataFlag, TimeOutPeriod can not be cell arrays
     e. Waveforms do not work with cell arrays.
  8. The Field input can be used for getting the "dot" EPICS field.  For instance, at the ALS
     getpv('BPMx','SCAN',[1 2],'String') will return SR01S___IBPM2X_AM02.SCAN as a string.
     (Note: at Spear ':' is used instead of '.')
  10. Error flaga are not used at the moment since all errors cause a Matlab error.
      Use try;catch statements to catch errors.
  12. If say Golden is a software field in the MML structure in the BPMx family, then
      getpv('BPMx','Golden', DeviceList) will return the data in that field.
  See also getam, getsp, setpv, steppv
  Written by Greg Portmann
CROSS-REFERENCE INFORMATION
This function calls:
common2dev COMMON2DEV - Converts a common name to a device list
elem2dev ELEM2DEV - Converts a device list to an element list
family2channel FAMILY2CHANNEL - Converts the family name to a channel name
family2dev FAMILY2DEV - Return the device list for a family
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
getmode GETMODE - Returns the present family mode ('Online', 'Simulator', 'Manual', 'Special', etc)
getpv GETPV - Returns a variable from the online system or the model
getrf GETRF - Gets the RF frequency
getunits GETUNITS - Return the present family units and units string
hw2physics HW2PHYSICS - Converts from 'Hardware' units to 'Physics' units
isfamily ISFAMILY - True for family names
physics2hw PHYSICS2HW - Converts from 'Physics' units to 'Hardware' units
This function is called by:
getam GETAM - Gets monitor channels
getdcct GETDCCT - returns the beam current
getmachineconfig GETMACHINECONFIG - Returns or saves to file the present storage ring setpoints and monitors
getpv GETPV - Returns a variable from the online system or the model
getramprate GETRAMPRATE - Returns the ramp rate for a family
getrf GETRF - Gets the RF frequency
getrunflag GETRUNFLAG - Returns position if the device is in the process of changing a setpoint
getsp GETSP - Gets setpoint channels
gettune GETTUNE - Returns the betatron tunes
getx GETX - Returns the horizontal orbit
gety GETY - Returns the vertical orbit
getz GETZ - Returns the vertical orbit
measidfftable MEASIDFFTABLE - Measures an insertion device feed forward table for the vertical gap
measrespmat MEASRESPMAT - Measure a response matrix
mmlviewer MMLVIEWER M-file for mmlviewer.fig
monbpm MONBPM - Monitors the orbit
plotfamily PLOTFAMILY - Plots by middle layer family name
rmgolden RMGOLDEN - Remove the golden values for data set
rmoffset RMOFFSET - Remove the offset values for data set
setorbit SETORBIT - Orbit correction function
setorbitbumpgui SETORBITBUMPGUI M-file for setorbitbumpgui.fig
setorbitgui SETORBITGUI - Orbit correction GUI
setpv SETPV - Setpoint change of the online system or model
SUBFUNCTIONS
function [AM, tout, DataTime, DeviceList, ErrorFlag] = getbycommonname(CommonNames, Field, t, t0, FreshDataFlag, TimeOutPeriod, varargin)
function [AM, tout, DataTime, ErrorFlag] = local_getbyname(ChannelName, OutputDataType, N, t, FreshDataFlag, TimeOutPeriod)
function [AM, tout, DataTime, ErrorFlag, DeviceIndex] = local_getpv(AO, Field, DeviceList, OutputDataType, t, FreshDataFlag, TimeOutPeriod)
SOURCE CODE
function [AM, tout, DataTime, ErrorFlag] = getpv(varargin)
%GETPV - Returns a variable from the online system or the model
%
%  FamilyName/DeviceList Method
%  [AM, tout, DataTime] = getpv(Family, Field, DeviceList, t, FreshDataFlag, TimeOutPeriod)
%
%  Data Structure
%  [AM, tout, DataTime] = getpv(DataStructure, t, FreshDataFlag, TimeOutPeriod)
%
%  ChannelName Method
%  [AM, tout, DataTime] = getpv(ChannelName, t, FreshDataFlag, TimeOutPeriod)
%
%  CommonName Method (Family can be '' to search all families, Field is optional)
%  [AM, tout, DataTime] = getpv(CommonName, Field, t, FreshDataFlag, TimeOutPeriod)
%  [AM, tout, DataTime] = getpv(Family, Field, CommonName, t, FreshDataFlag, TimeOutPeriod)
%
%  INPUTS
%  1. Family - Family Name
%              Data Structure
%              Channel Name or matrix of Channel Names
%              Accelerator Object (only the family name is used)
%              For CommonNames, Family=[] searches all families
%              (or Cell Array of inputs)
%
%  2. Field - Subfield name of an accelerator family ('Monitor', 'Setpoint', etc)
%             {Default: 'Monitor' or '' or ChannelName method}
%             (For non-Family subfields, Field is added as .Field, see Note #8 below for more information.)
%
%  3. DeviceList - [Sector Device #] or [element #] list {Default or empty list: Entire family}
%                  Note: if input 1 is a cell array then DeviceList must be a cell array
%     CommonName - Common name can replace a DeviceList (scalar or vector outputs)
%
%  4. t - Time vector of when to start taking data (t can not be a cell) {Default: 0}
%
%  5. FreshDataFlag -  0   -> Return after first measurement {Default}
%                     else -> Return after FreshDataFlag number of new measurements have been read
%                     Ie, getpv('BPMx',[1 1],0,2) measures the orbit then continues to read the orbit
%                         until 2 new orbits have been measured and returns the last measurement.
%                     Note: 1. t can only be a scalar when using the FreshDataFlag.
%                           2. FreshDataFlag cannot be used with 'Matrix' data types.
%
%  6. TimeOutPeriod - Time-out period when waiting for fresh data {Default: 10 seconds}
%
%  7. 'Struct'  - Return a data structure {Default for data structure inputs}
%     'Numeric' - Return numeric outputs  {Default for non-data structure inputs}
%     'Object'  - Return a accelerator object (AccObj)
%
%  8. Units flag overrides
%     'Physics'  - Use physics  units
%     'Hardware' - Use hardware units
%
%  9. Mode flag overrides
%     'Online' - Get data online
%     'Model'  - get data on the model
%     'Manual' - Get data manually
%
%  10. 'Double' - The output will be a double {Default}
%      'String' - The output will be a string
%
%
%  OUTPUTS
%  1. AM   - Monitor values (Column vector or matrix where each column is a data point in time)
%
%  2. tout - Time when measurement was completed according to the computer time (Matlab time) (row vector)
%            tout-t is the time it took to make the measurement.  diff(t) can be arbitarily small, but tout will
%            report the actual completion time.
%
%  3. DataTime - Time when the data was measured (as report by the hardware)
%                Time since 00:00:00, Jan 1, 1970 in days (in the present time zone)
%                Units are in Matlab "serial day number" format (days) to be compatible with
%                timing functions like datevec, datenum, datetick, etc.
%                For exmple, [d, tout, datatime] = getpv('BPMx', 'Monitor', [], 0:.5:10);
%                            plot(datatime, d); datetick x
%                When using the model, the datatime is the same a the computer time (Matlab time).
%
%  NOTES
%  1. The output will be a data structure if the word 'struct' appears somewhere on the input line
%     or if the input is a data structure and 'numeric' is not on the input line.
%
%  2. For data structure inputs:
%     Family     - DataStructure.FamilyName (This field must exist)
%     Field      - DataStructure.Field      (Field can be overridden on the input line)
%     DeviceList - DataStructure.DeviceList (DeviceList can be overridden on the input line)
%     Units      - DataStructure.Units      (Units can be overridden on the input line)
%     (The Mode field is ignored!)
%
%  3. For data structure outputs:
%     TimeStamp  - Time (Matlab clock) at the start of the function
%     tout       - Delta time vector at the end of each measurement (relative to TimeStamp)
%
%  4. diff(t) should not be too small.  If the desired time to collect the data is too
%     short then the data collecting will not be able to keep up.  Always check tout.
%     (t - tout) is the time it took to collect the data on each iteration.
%
%  5. An easy way to averaged 10 monitors is:
%     PVmean = mean(getpv(Family,DeviceList,0:.5:4.5)')';   % .5 second between measurements
%
%  6. Channel name method is always Online!
%
%  7. It is often useful to measure the update rate of a set of channel by using a very
%     small time between measurements.
%     For exmple, [d, tout] = getpv('BPMx', 'Monitor', [], 0:eps:100*eps);
%                 plot(tout(1:end-1), 1./diff(tout),'.-'); % Point-wise data rate
%                 If the update rate of the hardware is slower then the control system, then
%                 hardware data rate can be visually inspected by plotting,
%                 plot(tout, d,'.-');
%
%  8. For cell array inputs:
%     a. Input 1 defines the size of all cells
%     b. All of the cell array inputs must be the same size
%     c. Field does not have to be a cell array but DeviceList does (if they exist)
%     d. t, FreshDataFlag, TimeOutPeriod can not be cell arrays
%     e. Waveforms do not work with cell arrays.
%
%  8. The Field input can be used for getting the "dot" EPICS field.  For instance, at the ALS
%     getpv('BPMx','SCAN',[1 2],'String') will return SR01S___IBPM2X_AM02.SCAN as a string.
%     (Note: at Spear ':' is used instead of '.')
%
%  10. Error flaga are not used at the moment since all errors cause a Matlab error.
%      Use try;catch statements to catch errors.
%
%  12. If say Golden is a software field in the MML structure in the BPMx family, then
%      getpv('BPMx','Golden', DeviceList) will return the data in that field.
%
%  See also getam, getsp, setpv, steppv
%
%  Written by Greg Portmann
% Starting time
t0 = clock;
% Defaults
FieldDefault = 'Monitor';
Field = FieldDefault;
DeviceList = [];
t = 0;
FreshDataFlag = 0;
TimeOutPeriod = 10;
ErrorFlag = 0;
StructOutputFlag = 0;
NumericOutputFlag = 0;
ObjectOutputFlag = 0;
ModeFlag = '';
UnitsFlag = '';
OutputDataType = 'Double';
% Look if 'struct' or 'numeric' in on the input line
InputFlags = {};
for i = length(varargin):-1:1
    if isstruct(varargin{i})
        % Ignor structures
    elseif iscell(varargin{i})
        % Ignor cells
    elseif isnumeric(varargin{i})
        % Ignor numeric
    elseif isa(varargin{i},'AccObj')
        AccObj1 = struct(varargin{i});
        Families = fieldnames(AccObj1);
        j = 0;
        for k = 1:length(Families)
            if ~isempty(AccObj1.(Families{k}))
                j = j + 1;
                tmpcell{j} = AccObj1.(Families{k});
            end
        end
        if length(tmpcell) == 1
            varargin{i} = tmpcell{1};
        else
            varargin{i} = tmpcell;
        end
        if ~NumericOutputFlag
            ObjectOutputFlag = 1;
            StructOutputFlag = 1;
        end
    elseif ischar(varargin{i}) && size(varargin{i},1)==1
        if strcmpi(varargin{i},'struct')
            StructOutputFlag = 1;
            ObjectOutputFlag = 0;
            varargin(i) = [];
        elseif strcmpi(varargin{i},'numeric')
            NumericOutputFlag = 1;
            StructOutputFlag = 0;
            ObjectOutputFlag = 0;
            varargin(i) = [];
        elseif strcmpi(varargin{i},'simulator') || strcmpi(varargin{i},'model')
            ModeFlag = 'SIMULATOR';
            InputFlags = [InputFlags varargin(i)];
            varargin(i) = [];
        elseif strcmpi(varargin{i},'Online')
            ModeFlag = 'Online';
            InputFlags = [InputFlags varargin(i)];
            varargin(i) = [];
        elseif strcmpi(varargin{i},'Manual')
            ModeFlag = 'Manual';
            InputFlags = [InputFlags varargin(i)];
            varargin(i) = [];
        elseif strcmpi(varargin{i},'Special')
            ModeFlag = 'Special';
            InputFlags = [InputFlags varargin(i)];
            varargin(i) = [];
        elseif strcmpi(varargin{i},'physics')
            UnitsFlag = 'Physics';
            InputFlags = [InputFlags varargin(i)];
            varargin(i) = [];
        elseif strcmpi(varargin{i},'hardware')
            UnitsFlag = 'Hardware';
            InputFlags = [InputFlags varargin(i)];
            varargin(i) = [];
        elseif strcmpi(varargin{i},'archive')
            % Just remove
            varargin(i) = [];
        elseif strcmpi(varargin{i},'noarchive')
            % Just remove
            varargin(i) = [];
        elseif strcmpi(varargin{i},'String') || strcmpi(varargin{i},'Char')
            OutputDataType = 'String';
            InputFlags = [InputFlags varargin(i)];
            varargin(i) = [];
        elseif strcmpi(varargin{i},'Double')
            OutputDataType = 'Double';
            InputFlags = [InputFlags varargin(i)];
            varargin(i) = [];
        elseif strcmpi(varargin{i},'WaveForm') || strcmpi(varargin{i},'Matrix')
            OutputDataType = 'Matrix';
            InputFlags = [InputFlags varargin(i)];
            varargin(i) = [];
        elseif strcmpi(varargin{i},'Object')
            ObjectOutputFlag = 1;
            StructOutputFlag = 1;
            varargin(i) = [];
        end
    end
end
if isempty(varargin)
    error('Must have at least one input (Family, Data structure, or Channel Name).');
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% CELL OR CELL ARRAY INPUT %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if iscell(varargin{1})
    %if strcmpi(ModeFlag, 'Online') | (isempty(ModeFlag) & strcmpi(getmode(varargin{1}{1}), 'Online'))
    %     % Unfortunately the following code using channelnames is not much of a speed improvement over
    %     % interating over cell arrays (which is needed for simulator mode)
    %
    %     % Online cell arrays
    %     %
    %     % Online cell arrays are treated differently because to the desired for speed.
    %     % By loading all the channel names into one array then sending to the c-function
    %     % with the t-vector, the total time is greatly sped up.  However, using channel names
    %     % only works in online mode.  The one problem is all output have to scalars.
    %
    %
    %     % Count the number of inputs which are cells (Family or DeviceList) or strings (possibly Field)
    %     NCellOrString = 1;
    %     for i = 2:length(varargin)
    %         if ~iscell(varargin{i})
    %             if ~ischar(varargin{i})
    %                 break;
    %             else
    %                 NCellOrString = NCellOrString + 1;
    %             end
    %         else
    %             NCellOrString = NCellOrString + 1;
    %             %if length(varargin{1})~=length(varargin{NCellOrString}) | length(varargin{NCellOrString})==1
    %             %    error('When using cell, all the cells must be the same size as input 1 or be length one.');
    %             %end
    %         end
    %     end
    %
    %     % t (if it exists) should be the next input
    %     if length(varargin) >= NCellOrString+1
    %         if iscell(varargin{NCellOrString+1})
    %             error(sprintf('Expecting input #%d to be a time vector not a cell', NCellOrString+1));
    %         end
    %         if ischar(varargin{NCellOrString+1})
    %             error(sprintf('Expecting input #%d to be a time vector not a string', NCellOrString+1));
    %         end
    %         t = varargin{NCellOrString+1};
    %         varargin{NCellOrString+1} = [];
    %         if isempty(t)
    %             t = 0;
    %         end
    %     end
    %
    %     % FreshDataFlag (if it exists) should be the next input
    %     if length(varargin) >= NCellOrString+1
    %         if iscell(varargin{NCellOrString+1})
    %             error(sprintf('Expecting input #%d to be FreshDataFlag not a cell', NCellOrString+2));
    %         end
    %         if ischar(varargin{NCellOrString+1})
    %             error(sprintf('Expecting input #%d to be FreshDataFlag not a string', NCellOrString+2));
    %         end
    %         FreshDataFlag = varargin{NCellOrString+1};
    %         varargin{NCellOrString+1} = [];
    %     end
    %
    %     % TimeOutPeriod (if it exists) should be the next input
    %     if length(varargin) >= NCellOrString+1
    %         if iscell(varargin{NCellOrString+1})
    %             error(sprintf('Expecting input #%d to be TimeOutPeriod not a cell', NCellOrString+2));
    %         end
    %         if ischar(varargin{NCellOrString+1})
    %             error(sprintf('Expecting input #%d to be TimeOutPeriod not a string', NCellOrString+2));
    %         end
    %         TimeOutPeriod = varargin{NCellOrString+1};
    %         varargin{NCellOrString+1} = [];
    %     end
    %
    %     % Build the channel name matrix
    %     ChannelNames = [];
    %     for i = 1:size(varargin{1},1)
    %         for j = 1:size(varargin{1},2)
    %             if NCellOrString == 1
    %                 NewNames = family2channel(varargin{1}{i,j});
    %             elseif NCellOrString == 2
    %                 if iscell(varargin{2})
    %                     NewNames = family2channel(varargin{1}{i,j}, varargin{2}{i,j});
    %                 else
    %                     NewNames = family2channel(varargin{1}{i,j}, varargin{2});
    %                 end
    %             elseif NCellOrString == 3
    %                 if iscell(varargin{2})
    %                     NewNames = family2channel(varargin{1}{i,j}, varargin{2}{i,j}, varargin{3}{i,j});
    %                 else
    %                     NewNames = family2channel(varargin{1}{i,j}, varargin{2}, varargin{3}{i,j});
    %                 end
    %             end
    %             ChannelNames = strvcat(ChannelNames, NewNames);
    %             NameSize(i,j) = size(NewNames,1);
    %         end
    %     end
    %
    %     ExtraTimeDelay = etime(clock, t0);
    %
    %     %if nargout >= 3
    %     [AMtmp, tout, DataTimetmp, ErrorFlag] = local_getbyname(ChannelNames, 'Double', 1, t-ExtraTimeDelay, FreshDataFlag, TimeOutPeriod);
    %     %else
    %     %    [AMtmp, tout] = local_getbyname(ChannelNames, 'Double', 1, t-ExtraTimeDelay, FreshDataFlag, TimeOutPeriod)
    %     %end
    %
    %     %if StructOutputFlag | nargout >= 3
    %     % .DataTime is the time on computer taking the data but
    %     % reference it w.r.t. the time zone where Matlab is running
    %     DateNumber1970 = 719529;  %datenum('1-Jan-1970');
    %     days = datenum(t0(1:3)) - DateNumber1970;
    %     t0_sec = 24*60*60*days + 60*60*t0(4) + 60*t0(5) + t0(6);
    %     TimeZoneDiff = round((t0_sec - real(DataTimetmp(1,1)))/60/60);
    %     DataTimetmp = (real(DataTimetmp)/60/60 + TimeZoneDiff)/24 + DateNumber1970 + imag(DataTimetmp)/(1e9 * 60 * 60 * 24);
    %
    %     % No time zone adjustment (UTC 00:00:00 Jan 1, 1970)
    %     %DataTime = real(DataTime)/60/60/24 + imag(DataTime)/(1e9 * 60 * 60 * 24);
    %     %end
    %
    %     for i = 1:size(varargin{1},1)
    %         for j = 1:size(varargin{1},2)
    %             AM{i,j} = AMtmp(1:NameSize(i,j),:);
    %             AMtmp(1:NameSize(i,j),:) = [];
    %             %if nargout >= 3
    %             DataTime{i,j} = DataTimetmp(1:NameSize(i,j),:);
    %             DataTimetmp(1:NameSize(i,j),:) = [];
    %             %end
    %
    %             % If input is a data structure, only change StructOutputFlag if 'numeric' is not on the input line
    %             StructOutputFlagStart = StructOutputFlag;
    %             if isstruct(varargin{1}{i,j})
    %                 if isfield(varargin{1}{i,j},'Field')
    %                     if ~NumericOutputFlag
    %                         StructOutputFlag = 1;
    %                     end
    %                 end
    %             end
    %
    %             if StructOutputFlag
    %                 Datatmp = AM{i,j};
    %                 DataTimetmp = DataTime{i,j};
    %                 if NCellOrString == 1
    %                     if isempty(UnitsFlag)
    %                         AM{i,j} = family2datastruct(varargin{1}{i,j});
    %                     else
    %                         AM{i,j} = family2datastruct(varargin{1}{i,j}, UnitsFlag);
    %                     end
    %                 elseif NCellOrString == 2
    %                     if iscell(varargin{2})
    %                         if isempty(UnitsFlag)
    %                             AM{i,j} = family2datastruct(varargin{1}{i,j}, varargin{2}{i,j});
    %                         else
    %                             AM{i,j} = family2datastruct(varargin{1}{i,j}, varargin{2}{i,j}, UnitsFlag);
    %                         end
    %                     else
    %                         if isempty(UnitsFlag)
    %                             AM{i,j} = family2datastruct(varargin{1}{i,j}, varargin{2});
    %                         else
    %                             AM{i,j} = family2datastruct(varargin{1}{i,j}, varargin{2}, UnitsFlag);
    %                         end
    %                     end
    %                 elseif NCellOrString == 3
    %                     if iscell(varargin{2})
    %                         if isempty(UnitsFlag)
    %                             AM{i,j} = family2datastruct(varargin{1}{i,j}, varargin{2}{i,j}, varargin{3}{i,j});
    %                         else
    %                             AM{i,j} = family2datastruct(varargin{1}{i,j}, varargin{2}{i,j}, varargin{3}{i,j}, UnitsFlag);
    %                         end
    %                     else
    %                         if isempty(UnitsFlag)
    %                             AM{i,j} = family2datastruct(varargin{1}{i,j}, varargin{2}, varargin{3}{i,j});
    %                         else
    %                             AM{i,j} = family2datastruct(varargin{1}{i,j}, varargin{2}, varargin{3}{i,j}, UnitsFlag);
    %                         end
    %                     end
    %                 end
    %                 AM{i,j}.Data = Datatmp;
    %                 AM{i,j}.t = t;
    %                 AM{i,j}.tout = tout;
    %                 AM{i,j}.DataTime = DataTimetmp;
    %                 AM{i,j}.Mode = 'Online';
    %                 AM{i,j}.CreatedBy = 'getpv';
    %             end
    %             StructOutputFlag = StructOutputFlagStart;
    %         end
    %     end
    %
    %     return
    %
    %else
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % CELL OR CELL ARRAY INPUT %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Iterate on each cell with special attention to the t vector input
    % For an empty input, return empty
    if isempty(varargin{1})
        AM =[]; tout = []; DataTime = []; ErrorFlag = 0;
        return
    end
    % If input is a data structure, only change StructOutputFlag if 'numeric' is not on the input line
    if isstruct(varargin{1}{1}) && isfield(varargin{1}{1},'Field')
        if ~NumericOutputFlag
            StructOutputFlag = 1;
        end
    end
    % Count the number of inputs which are cells (Family or DeviceList) or strings (possibly Field)
    NCellOrString = 1;
    for i = 2:length(varargin)
        if ~iscell(varargin{i})
            if ~ischar(varargin{i})
                break;
            else
                NCellOrString = NCellOrString + 1;
            end
        else
            NCellOrString = NCellOrString + 1;
            %if length(varargin{1})~=length(varargin{NCellOrString}) | length(varargin{NCellOrString})==1
            %    error('When using cell, all the cells must be the same size as input 1 or be length one.');
            %end
        end
    end
    % t (if it exists) should be the next input.  Save it then zero it in varargin
    if length(varargin) >= NCellOrString+1
        if iscell(varargin{NCellOrString+1})
            error(sprintf('Expecting input #%d to be a time vector not a cell', NCellOrString+1));
        end
        if ischar(varargin{NCellOrString+1})
            error(sprintf('Expecting input #%d to be a time vector not a string', NCellOrString+1));
        end
        t = varargin{NCellOrString+1};
        varargin{NCellOrString+1} = 0;
    end
    ExtraTimeDelay = etime(clock, t0);
    t = t - ExtraTimeDelay;
    % Loop according to t
    for itime = 1:length(t)
        T = t(itime)-etime(clock, t0);
        if T > 0
            pause(T);
        end
        for i = 1:size(varargin{1},1)
            for j = 1:size(varargin{1},2)
                % Build the input line
                for k = 1:length(varargin)
                    if ~iscell(varargin{k})
                        Inputs1{1,k} = varargin{k};
                    elseif length(varargin{k}) == 1
                        Inputs1{1,k} = varargin{k}{1};
                    elseif (size(varargin{k},1) == size(varargin{1},1)) && (size(varargin{k},2) == size(varargin{1},2))
                        Inputs1{1,k} = varargin{k}{i,j};
                    else
                        error('When using cells, all the cells must be the same size or length 1 (repeated).');
                    end
                end
                if StructOutputFlag
                    if itime == 1
                        % Form the structure on the first time
                        [AM{i,j}, tout(1,itime), DataTime{i,j}, ErrorFlagNew] = getpv(Inputs1{:}, 'Struct', InputFlags{:});
                    else
                        % Add to the Data and time fields
                        [AM{i,j}.Data(:,itime), tmp, AM{i,j}.DataTime(:,itime), ErrorFlagNew] = getpv(Inputs1{:}, 'Numeric', InputFlags{:});
                        AM{i,j}.t(1,itime) = t(itime);
                        AM{i,j}.tout(1,itime) = etime(clock, t0);
                        DataTime{i,j}(:,itime) = AM{i,j}.DataTime(:,itime);
                    end
                else
                    [AM{i,j}(:,itime), tmp, DataTime{i,j}(:,itime), ErrorFlagNew] = getpv(Inputs1{:}, 'Numeric', InputFlags{:});
                end
                ErrorFlag = ErrorFlag | any(ErrorFlagNew);
            end
            tout(itime) = etime(clock, t0);
        end
    end
    % Make the output an AccObj object
    if ObjectOutputFlag
        AM = AccObj(AM);
    end
    return
end
%%%%%%%%%%%%%%%%%%
% End cell input %
%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% COMMONNAME - Commonname input with no family input %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if isempty(varargin{1})
    if length(varargin) >= 2
        if ischar(varargin{2})
            Field = varargin{2};
            varargin(2) = [];
        end
    else
        % For an empty input, return empty
        if isempty(varargin{1})
            AM =[]; tout = []; DataTime = []; ErrorFlag = 0;
            return
        end
    end
    if isempty(Field)
        Field = FieldDefault;
    end
    if length(varargin) >= 2
        CommonNames = varargin{2};
    else
        error('Common names not found on the input line.');
    end
    if length(varargin) >= 3
        t = varargin{3};
    end
    if length(varargin) >= 4
        FreshDataFlag = varargin{4};
    end
    if length(varargin) >= 5
        TimeOutPeriod = varargin{5};
    end
    % Common names with no family name
    if ~ischar(CommonNames)
        error('If Family=[], then DeviceList must be a string of common names.')
    end
    [AM, tout, DataTime, DeviceList, ErrorFlag] = getbycommonname(CommonNames, Field, t, t0, FreshDataFlag, TimeOutPeriod, InputFlags{:});
    if ErrorFlag
        return;
    end
    if StructOutputFlag || nargout >= 3
        % .DataTime is the time on computer taking the data but
        % reference it w.r.t. the time zone where Matlab is running
        DateNumber1970 = 719529;  %datenum('1-Jan-1970');
        days = datenum(t0(1:3)) - DateNumber1970;
        t0_sec = 24*60*60*days + 60*60*t0(4) + 60*t0(5) + t0(6);
        TimeZoneDiff = round((t0_sec - real(DataTime(1,1)))/60/60);
        DataTime = (real(DataTime)/60/60 + TimeZoneDiff)/24 + DateNumber1970 + imag(DataTime)/(1e9 * 60 * 60 * 24);
    end
    % Structure output
    if StructOutputFlag
        AM = struct('Data', AM);
        AM.FamilyName = CommonNames;
        AM.Field = Field;
        AM.DeviceList = DeviceList;
        AM.Status = [];
        AM.t = t;
        AM.tout = tout;
        AM.DataTime = DataTime;
        AM.TimeStamp = t0;
        [DeviceList1, Family1] = common2dev(CommonNames(1,:));
        AM.Mode = getmode(Family1);                      % Base on just the first common name
        [AM.Units, AM.UnitsString] = getunits(Family1);  % Base on just the first common name
        AM.DataDescriptor = 'Get by Common Name';
        AM.CreatedBy = 'getpv';
        % Make the output an AccObj object
        if ObjectOutputFlag
            AM = AccObj(AM);
        end
    end
    return
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% End CommonName input with no family input %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Parce inputs depending on Data structure, AO structure, Family, ChannelName method %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if isstruct(varargin{1})
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % STRUCTURE INPUTS - Data structure or AO structure %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    if isfield(varargin{1},'FamilyName') && isfield(varargin{1},'Field')
        % Data structure - select FamilyName, DeviceList, Units  from the structure (.Mode flag???)
        % [AM, tout, DataTime, ErrorFlag] = getpv(DataStruct, Field {opt}, t, FreshDataFlag, TimeOutPeriod)
        % Only change StructOutputFlag if 'numeric' is not on the input line
        if ~NumericOutputFlag
            StructOutputFlag = 1;
        end
        Family = varargin{1}.FamilyName;
        Field = varargin{1}.Field;
        if length(varargin) >= 2
            if ischar(varargin{2})
                Field = varargin{2};
                varargin(2) = [];
            end
        end
        DeviceList = varargin{1}.DeviceList;
        if length(varargin) >= 2
            % If the input exists use it
            t = varargin{2};
        else
            % Else, get it from the structure if the field exists
            if isfield(varargin{1},'t')
                t = varargin{1}.t;
            end
        end
        if length(varargin) >= 3
            FreshDataFlag = varargin{3};
        end
        if length(varargin) >= 4
            TimeOutPeriod = varargin{4};
        end
        [FamilyIndex, AO] = isfamily(Family);
        % Change Units to the data structure units
        if isfield(AO, Field)
            AO.(Field).Units = varargin{1}.Units;
        end
    elseif isfield(varargin{1},'FamilyName')
        % AO structure - use the AO structure directly
        %  [AM, tout, DataTime, ErrorFlag] = getpv(AO, Field, DeviceList, t, FreshDataFlag, TimeOutPeriod)
        FamilyIndex = 1;
        AO = varargin{1};
        Family = varargin{1}.FamilyName;
        Field = '';
        if length(varargin) >= 2
            if ischar(varargin{2})
                Field = varargin{2};
                varargin(2) = [];
            end
        end
        if length(varargin) >= 2
            DeviceList = varargin{2};
        else
            DeviceList = AO.DeviceList;
            iStatus = find(varargin{1}.Status == 0);
            DeviceList(iStatus,:) = [];
        end
        if length(varargin) >= 3
            t = varargin{3};
        end
        if length(varargin) >= 4
            FreshDataFlag = varargin{4};
        end
        if length(varargin) >= 5
            TimeOutPeriod = varargin{5};
        end
    else
        error('Input #1 of unknown type');
    end
else
    % Family, ChannelName, or Common name are still left
    [FamilyIndex, AO] = isfamily(varargin{1});
    if FamilyIndex
        %%%%%%%%%%%%%%%%
        % FAMILY INPUT %
        %%%%%%%%%%%%%%%%
        %  [AM, tout, DataTime, ErrorFlag] = getpv(Family, Field {opt}, DeviceList, t, FreshDataFlag, TimeOutPeriod)
        Family = varargin{1};
        if length(varargin) >= 2
            if ischar(varargin{2})
                Field = varargin{2};
                varargin(2) = [];
            end
        end
        if isempty(Field)
            Field = FieldDefault;
        end
        if length(varargin) >= 2
            DeviceList = varargin{2};
        end
        if length(varargin) >= 3
            t = varargin{3};
        end
        if length(varargin) >= 4
            FreshDataFlag = varargin{4};
        end
        if length(varargin) >= 5
            TimeOutPeriod = varargin{5};
        end
    else
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % CHANNEL NAME OR COMMON NAME INPUT %
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Just do input parsing here
        Family = varargin{1};
        % Default field is '' for channel names or it would be added as ChannelName.Field
        % But for common names it needs to be 'Monitor'
        Field = '';
        if length(varargin) >= 2
            if ~isnumeric(varargin{2})
                Field = varargin{2};
                varargin(2) = [];
            end
        end
        if length(varargin) >= 2
            t = varargin{2};
        end
        if length(varargin) >= 3
            FreshDataFlag = varargin{3};
        end
        if length(varargin) >= 4
            TimeOutPeriod = varargin{4};
        end
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% End selection of inputs depending on Family, Data Structure, AO structure, or ChannelName method %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% AO, ChannelName, or CommonName %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if isempty(t)
    t = 0;
end
if FamilyIndex
    %%%%%%%%%%%%%%%%%
    % FAMILY INPUTS %
    %%%%%%%%%%%%%%%%%
    % All ready done
    %if isempty(Field)
    %    Field = 'Monitor';
    %end
    if isempty(DeviceList)
        DeviceList = family2dev(Family);     % Default behavior comes from family2dev
        %DeviceList = family2dev(Family,1);  % Good status only
        %DeviceList = AO.DeviceList;         % All devices
    end
    if ischar(DeviceList)
        % Convert common name to a DeviceList
        DeviceList = common2dev(DeviceList, AO);
    end
    if (size(DeviceList,2) == 1)
        DeviceList = elem2dev(Family, DeviceList);
    end
    % Look for command-line over-rides
    if isfield(AO, Field)
        if ~isempty(UnitsFlag)
            AO.(Field).Units = UnitsFlag;
        end
        if ~isempty(ModeFlag)
            if strcmp(ModeFlag, 'Online') && strcmp(AO.(Field).Mode, 'Special')
                % For Online over-rides, look for Special mode first
                AO.(Field).Mode = 'Special';
            else
                AO.(Field).Mode = ModeFlag;
            end
        end
    end
    % Get data
    ExtraTimeDelay = etime(clock, t0);
    if StructOutputFlag || nargout >= 3
        [AM, tout, DataTime, ErrorFlag, DeviceIndex] = local_getpv(AO, Field, DeviceList, OutputDataType, t-ExtraTimeDelay, FreshDataFlag, TimeOutPeriod);
    else
        [AM, tout] = local_getpv(AO, Field, DeviceList, OutputDataType, t-ExtraTimeDelay, FreshDataFlag, TimeOutPeriod);
    end
    tout = tout + ExtraTimeDelay;
    if StructOutputFlag
        % Structure output
        AM = struct('Data', AM);
        %AM.Data = AM;
        AM.FamilyName = Family;
        AM.Field = Field;
        AM.DeviceList = DeviceList;
        if length(AO.Status) == 1
            AM.Status = AO.Status * ones(size(DeviceIndex));
        else
            %AM.Status = family2status(Family, AM.DeviceList);
            AM.Status = AO.Status(DeviceIndex);
        end
        if isfield(AO, Field)
            AM.Mode = AO.(Field).Mode;
            AM.Units = AO.(Field).Units;
            if strcmpi(AM.Units,'hardware')
                AM.UnitsString = AO.(Field).HWUnits;
            else
                AM.UnitsString = AO.(Field).PhysicsUnits;
            end
            AM.DataDescriptor = 'Get by FamilyName';
        else
            AM.Mode = 'Online';
            AM.Units = '';
            AM.UnitsString = '';
            AM.DataDescriptor = 'Get by Channel Name';
        end
        AM.CreatedBy = 'getpv';
    end
else
    % Look to see if it's a channel name or a common name
    % Just check the first name so it's a faster test
    [DeviceListTest, FamilyTest] = common2dev(deblank(Family(1,:)));
    %FamilyTest = '';
    if ~isempty(FamilyTest)
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Family input is a common name list %
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Field default will come from getbycommonname via another getpv call
        % The DeviceList should not exist (and should not be used)
        CommonNames = Family;
        [AM, tout, DataTime, DeviceList, ErrorFlag] = getbycommonname(CommonNames, Field, t, t0, FreshDataFlag, TimeOutPeriod, InputFlags{:});
        if ErrorFlag
            return;
        end
        % Structure output
        if StructOutputFlag
            AM = struct('Data', AM);
            AM.FamilyName = CommonNames;
            AM.Field = Field;
            AM.DeviceList = DeviceList;
            AM.Status = [];
            AM.Mode = getmode(FamilyTest(1,:));                      % Base on just the first common name
            [AM.Units, AM.UnitsString] = getunits(FamilyTest(1,:));  % Base on just the first common name
            AM.DataDescriptor = 'Get by Common Name';
            AM.CreatedBy = 'getpv';
        end
    else
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % CHANNEL NAME - Online Only %
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % Can't use overrides with channel name method
        if ~isempty(UnitsFlag)
            error('You cannot change the units when using channel names.')
        end
        if ~(isempty(ModeFlag) || strcmpi(ModeFlag, 'Online'))
            error('Channel names only have an ''Online'' Mode.')
        end
        % Add Field to Family.Field
        FamilyOld = Family;
        if ~isempty(Field)
            Family = strcat(Family, ['.',Field]);
        end
        ExtraTimeDelay = etime(clock, t0);
        if strcmpi(OutputDataType,'String')
            % Get data with strings output
            if StructOutputFlag || nargout >= 3
                [AM, tout, DataTime, ErrorFlag] = getpvonline(Family, 'String', 0, t-ExtraTimeDelay);
            else
                [AM, tout] = getpvonline(Family, 'String', 0, t-ExtraTimeDelay);
            end
        else
            % Get data at every point in time vector, t
            if StructOutputFlag || nargout >= 3
                [AM, tout, DataTime, ErrorFlag] = local_getbyname(Family, OutputDataType, 0, t-ExtraTimeDelay, FreshDataFlag, TimeOutPeriod);
            else
                [AM, tout] = local_getbyname(Family, OutputDataType, 0, t-ExtraTimeDelay, FreshDataFlag, TimeOutPeriod);
            end
        end
        tout = tout + ExtraTimeDelay;
        % Structure output for channel name method
        if StructOutputFlag
            AM = struct('Data', AM);
            %AM.Data = AM;
            AM.FamilyName = FamilyOld;
            AM.Field = Field;
            AM.DeviceList = [];
            AM.Status = [];
            AM.Mode = 'Online';
            AM.Units = '';
            AM.UnitsString = '';
            AM.DataDescriptor = 'Get by Channel Name';
            AM.CreatedBy = 'getpv';
        end
    end
end
if StructOutputFlag || nargout >= 3
    % .DataTime is the time on computer taking the data but
    % reference it w.r.t. the time zone where Matlab is running
    DateNumber1970 = 719529;  %datenum('1-Jan-1970');
    days = datenum(t0(1:3)) - DateNumber1970;
    t0_sec = 24*60*60*days + 60*60*t0(4) + 60*t0(5) + t0(6);
    TimeZoneDiff = round((t0_sec - real(DataTime(1,1)))/60/60);
    DataTime = (real(DataTime)/60/60 + TimeZoneDiff)/24 + DateNumber1970 + imag(DataTime)/(1e9 * 60 * 60 * 24);
    % No time zone adjustment (UTC 00:00:00 Jan 1, 1970)
    %DataTime = real(DataTime)/60/60/24 + imag(DataTime)/(1e9 * 60 * 60 * 24);
end
% Structure output
if StructOutputFlag
    % Add time to structure
    AM.t = t;
    AM.tout = tout;
    AM.DataTime = DataTime;
    AM.TimeStamp = t0;
    % Make the output an AccObj object
    if ObjectOutputFlag
        AM = AccObj(AM);
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%  Main Function for Getting Data Using Common Names  %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [AM, tout, DataTime, DeviceList, ErrorFlag] = getbycommonname(CommonNames, Field, t, t0, FreshDataFlag, TimeOutPeriod, varargin)
% Convert all the common names to Family and Device lists
[DeviceList, Family, ErrorFlag] = common2dev(CommonNames);
if ErrorFlag
    AM=[]; tout=[]; DataTime=[];
    return;
else
1000
1001     if size(Family, 1) == 1
1002         % 1 Family, Multiple devices are ok
1003         [AM, tout, DataTime, ErrorFlag] = getpv(Family, Field, DeviceList, t, FreshDataFlag, TimeOutPeriod, 'Numeric', varargin{:});
1004     else
1005         % Multiple families (loop)
1006         % It has to be in a loop for the simulator and to pickup special functions
1007
1008         if FreshDataFlag >= 1
1009             error('The FreshDataFlag is not programmed yet when when getting common names from multiple families (GJP).');
1010         end
1011
1012         % Loop on the time vector (t0 has already been started)
1013         for itime = 1:length(t)
1014             T = t(itime)-etime(clock, t0);
1015             if T > 0
1016                 pause(T);
1017             end
1018             for i = 1:size(Family,1)
1019                 [AM(i,itime), tmp, DataTime(i,itime), ErrorFlag1] = getpv(Family(i,:), Field, DeviceList(i,:), 'Numeric', varargin{:});
1020                 tout(1,itime) = etime(clock, t0);
1021                 ErrorFlag = ErrorFlag | ErrorFlag1;
1022             end
1023         end
1024     end
1025 end
1026
1027
1028
1029 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1030 %  Main Function for Getting Data using the Channel Names  %
1031 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1032 function [AM, tout, DataTime, ErrorFlag] = local_getbyname(ChannelName, OutputDataType, N, t, FreshDataFlag, TimeOutPeriod)
1033
1034 t0 = clock;
1035 ErrorFlag = 0;
1036
1037
1038 if nargout < 3
1039     [AM, tout] = getpvonline(ChannelName, OutputDataType, N, t);
1040 else
1041     [AM, tout, DataTime, ErrorFlag] = getpvonline(ChannelName, OutputDataType, N, t);
1042 end
1043
1044
1045 % FreshDataFlag
1046 if FreshDataFlag && length(t) == 1
1047     % Only use FreshDataFlag for scalar t
1048     FreshDataCounter = FreshDataFlag;
1049     AM0 = AM;
1050     while FreshDataCounter
1051         if nargout < 3
1052             [AM, tout] = getpvonline(ChannelName, OutputDataType, N);
1053         else
1054             [AM, tout, DataTime, ErrorFlag] = getpvonline(ChannelName, OutputDataType, N);
1055         end
1056
1057         if ~any((AM-AM0)==0)
1058             FreshDataCounter = FreshDataCounter - 1;
1059             AM0 = AM;
1060         end
1061
1062         if etime(clock, t0) > TimeOutPeriod
1063             k = find((AM-AM0)==0);
1064             for j = 1:length(k)
1065                 fprintf('%s not changing.\n', deblank(ChannelName(k(j),:)));
1066             end
1067             error('Timed out waiting for fresh data.');
1068         end
1069     end
1070     tout = etime(clock, t0);
1071 end
1072
1073 return
1074
1075
1076
1077
1078 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1079 %  Main Function for Getting Data using the Accelerator Object  %
1080 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1081 function [AM, tout, DataTime, ErrorFlag, DeviceIndex] = local_getpv(AO, Field, DeviceList, OutputDataType, t, FreshDataFlag, TimeOutPeriod)
1082
1083 t0 = clock;
1084 ErrorFlag = 0;
1085 N = 0;  % Output size
1086
1087
1088 % Find the index for where the desired data is in the total device list
1089 DeviceListTotal = AO.DeviceList;
1090 [DeviceIndex, iNotFound] = findrowindex(DeviceList, DeviceListTotal);
1091 if ~isempty(iNotFound)
1092     % Device not found
1093     for i = 1:length(iNotFound)
1094         fprintf('   No devices to get for Family %s(%d,%d)\n', AO.FamilyName, DeviceList(i,1), DeviceList(i,2));
1095     end
1096     error(sprintf('%d Devices not found', length(iNotFound)));
1097 end
1098
1099 % Check the DeviceIndex
1100 if isempty(DeviceIndex)
1101     DataTime = 0 + 0*sqrt(-1);
1102     tout = etime(clock, t0);
1103     AM = [];
1104     %fprintf('   WARNING:  No devices to get for Family %s (getpv)\n', AO.FamilyName);
1105     return;
1106 end
1107
1108
1109 % If Field is not found in the AO, it is unclear what to do next.
1110 % I could error here, but it's convenient to try to get
1111 % EPICS subfields or other simulator fields at this point.
1112 if ~isfield(AO, Field);
1113     % Try to check it online or simulator
1114     if isfield(AO, 'Setpoint')
1115         Mode = getfamilydata(AO.FamilyName, 'Setpoint', 'Mode');
1116     elseif isfield(AO, 'Monitor')
1117         Mode = getfamilydata(AO.FamilyName, 'Monitor', 'Mode');
1118     else
1119         Mode = '';
1120     end
1121     if strcmpi(Mode,'Simulator') || strcmpi(Mode,'Model')
1122         ExtraTimeDelay = etime(clock, t0);
1123         [AM, tout, DataTime, ErrorFlag] = getpvmodel(AO.FamilyName, Field, DeviceList, t-ExtraTimeDelay, 'Physics', 'Numeric');
1124         tout = tout + ExtraTimeDelay;
1125
1126         % Since physics2hw conversions are not known for fields that are not families, just return
1127         return
1128     end
1129
1130     % Try changing the suffix of the Monitor or Setpoint field
1131     if isfield(AO, 'Setpoint')
1132         Channel = family2channel(AO, 'Setpoint', DeviceList);
1133     elseif isfield(AO, 'Monitor')
1134         Channel = family2channel(AO, 'Monitor', DeviceList);
1135     else
1136         error(sprintf('Field %s not found for Family %s', Field, AO.FamilyName));
1137     end
1138     if any(strcmpi(getfamilydata('Machine'),{'spear3','spear'}))
1139         % Spear likes to change the channel name after the ':'
1140
1141         %i = findstr(Channel(1,:),':');
1142         %if ~isempty(i)
1143         %    Channel(:,i:end) = [];
1144         %end
1145         %Channel = strcat(Channel, [':',Field]);
1146
1147         % Since the location of ":" can be different in each row, loop
1148         ChannelMat = [];
1149         for j = 1:size(Channel,1)
1150             i = findstr(Channel(j,:),':');
1151             if isempty(i)
1152                 % I'm not sure what to do if ":" is missing, I'm just add a ":"
1153                 ChannelMat = strvcat(ChannelMat, [Channel(j,1:i), ':', Field]);
1154             else
1155                 ChannelMat = strvcat(ChannelMat, [Channel(j,1:i), Field]);
1156             end
1157         end
1158         Channel = ChannelMat;
1159
1160     else
1161         % Add a .Field (EPICS)
1162         Channel = strcat(Channel, ['.',Field]);
1163     end
1164
1165     ExtraTimeDelay = etime(clock, t0);
1166     if nargout < 3
1167         [AM, tout] = getpvonline(Channel, OutputDataType, N, t-ExtraTimeDelay, FreshDataFlag, TimeOutPeriod);
1168     else
1169         [AM, tout, DataTime, ErrorFlag] = getpvonline(Channel, OutputDataType, N, t-ExtraTimeDelay, FreshDataFlag, TimeOutPeriod);
1170     end
1171     tout = tout + ExtraTimeDelay;
1172     return
1173 end
1174
1175
1176 AOField = AO.(Field);   % Should I replace this????
1177
1178 if isfield(AOField, 'Mode')
1179     Mode = AOField.Mode;
1180 else
1181     Mode = 'Online';
1182 end
1183
1184
1185 % Check if Online should really be special
1186 if strcmpi(Mode, 'Online')
1187    if isfield(AO.(Field), 'SpecialFunctionGet')
1188        Mode = 'Special';
1189    end
1190 end
1191
1192
1193 if ~isstruct(AO.(Field))
1194     % If it's not a structure that just get the field
1195     % Hardward and physics get ignored
1196     t1 = clock;
1197     [AM, ErrorFlag] = getfamilydata(AO.FamilyName, Field, DeviceList);
1198
1199     tout = etime(t1, t0);
1200     if nargout >= 3
1201         days = datenum(t1(1:3)) - 719529;  %datenum('1-Jan-1970');
1202         tt = 24*60*60*days + 60*60*t1(4) + 60*t1(5) + t1(6);
1203         DataTime(1:size(AM,1),1:length(t)) = fix(tt) + rem(tt,1)*1e9*sqrt(-1);
1204     end
1205
1206 elseif strcmpi(Mode,'online')
1207     % Online
1208     if strcmpi(AOField.DataType,'Scalar')
1209         N = 1;  % Output size
1210
1211         ExtraTimeDelay = etime(clock, t0);
1212         if nargout < 3
1213             [AM, tout] = getpvonline(AOField.ChannelNames(DeviceIndex,:), OutputDataType, N, t-ExtraTimeDelay);
1214         else
1215             [AM, tout, DataTime, ErrorFlag] = getpvonline(AOField.ChannelNames(DeviceIndex,:), OutputDataType, N, t-ExtraTimeDelay);
1216         end
1217         tout = tout + ExtraTimeDelay;
1218
1219         % FreshDataFlag
1220         if FreshDataFlag && length(t) == 1
1221             % Only use FreshDataFlag for scalar t
1222             FreshDataCounter = FreshDataFlag;
1223             AM0 = AM;
1224             while FreshDataCounter
1225                 if nargout < 3
1226                     [AM, tout] = getpvonline(AOField.ChannelNames(DeviceIndex,:), OutputDataType, N);
1227                 else
1228                     [AM, tout, DataTime, ErrorFlag] = getpvonline(AOField.ChannelNames(DeviceIndex,:), OutputDataType, N);
1229                 end
1230
1231                 if ~any((AM-AM0)==0)
1232                     FreshDataCounter = FreshDataCounter - 1;
1233                     AM0 = AM;
1234                 end
1235
1236                 if etime(clock, t0) > TimeOutPeriod
1237                     k = find((AM-AM0)==0);
1238                     for j = 1:length(k)
1239                         fprintf('%s not changing.\n', deblank((AOField.ChannelNames(DeviceIndex(k(j)),:))));
1240                     end
1241                     error('Timed out waiting for fresh data.');
1242                 end
1243             end
1244             tout = etime(clock, t0);
1245         end
1246
1247     elseif strcmpi(AOField.DataType, 'Vector')
1248
1249         % Output(DataTypeIndex) must be equal to the number of elements in the family
1250
1251         % There can only be one channel name for DataType='Vector'
1252         ChannelNames = deblank(AOField.ChannelNames(1,:));
1253
1254
1255         % Get data at every point in time vector, t
1256         AM = [];
1257         ExtraTimeDelay = etime(clock, t0);
1258         t = t - ExtraTimeDelay;
1259         for itime = 1:length(t)
1260             T = t(itime)-etime(clock, t0);
1261             if T > 0
1262                 pause(T);
1263             end
1264
1265             % Get data
1266             if nargout >= 3
1267                 [tmp, tout, DataTime(:,itime), ErrorFlag] = getpvonline(ChannelNames, 'Vector', N);
1268             else
1269                 tmp = getpvonline(ChannelNames, 'Vector', N);
1270             end
1271             if isfield(AOField, 'DataTypeIndex')
1272                 tmp = tmp(AOField.DataTypeIndex);
1273             end
1274             AM = [AM tmp(DeviceIndex,:)];
1275
1276             tout(itime) = etime(clock, t0);
1277         end
1278
1279         % FreshDataFlag
1280         if FreshDataFlag && length(t) == 1
1281             % Only use FreshDataFlag for scalar t
1282             FreshDataCounter = FreshDataFlag;
1283             AM0 = AM;
1284             while FreshDataCounter
1285                 if nargout >= 3
1286                     [AM, tout, DataTime, ErrorFlag] = getpvonline(ChannelNames, 'Vector', N);
1287                 else
1288                     AM = getpvonline(ChannelNames, 'Vector', N);
1289                 end
1290                 if isfield(AOField, 'DataTypeIndex')
1291                     AM = AM(AOField.DataTypeIndex);
1292                 end
1293                 AM = AM(DeviceIndex,:);
1294
1295                 if ~any((AM-AM0)==0)
1296                     FreshDataCounter = FreshDataCounter - 1;
1297                     AM0 = AM;
1298                 end
1299
1300                 if etime(clock, t0) > TimeOutPeriod
1301                     k = find((AM-AM0)==0);
1302                     for j = 1:length(k)
1303                         fprintf('%s[%d,%d] not changing.\n', AO.FamilyName, DeviceList(k(j),1), DeviceList(k(j),2));
1304                     end
1305                     error('Timed out waiting for fresh data.');
1306                 end
1307             end
1308             tout = etime(clock, t0);
1309         end
1310
1311     elseif strcmpi(AOField.DataType,'Matrix')
1312
1313         for iDev = 1:length(DeviceIndex)
1314             %AM(iDev,:) = rand(1,10); DataTime(iDev,:) = now; ErrorFlag(iDev,:)=0;
1315             [AM(iDev,:), tout, DataTime(iDev,:), ErrorFlag(iDev,1)] = getpvonline(AOField.ChannelNames(DeviceIndex(iDev),:), 'Matrix', N);
1316         end
1317         ErrorFlag = any(ErrorFlag);
1318         tout = etime(clock, t0);
1319
1320     else
1321         error(sprintf('Unknown DataType for family %s.', AO.FamilyName));
1322     end
1323
1324     % Change to physics units if Units = 'physics'
1325     if strcmpi(AO.(Field).Units,'physics')
1326         % Change to physics units
1327         AM = hw2physics(AO.FamilyName, Field, AM, DeviceList);
1328     end
1329
1330 elseif strcmpi(Mode,'Special')
1331
1332     if isfield(AOField, 'SpecialFunctionGet')
1333         SpecialFunction = AOField.SpecialFunctionGet;
1334     elseif isfield(AOField, 'SpecialFunction')
1335         SpecialFunction = AOField.SpecialFunction;
1336     else
1337         error(sprintf('No special function specified for Family %s (getpv).', AO.FamilyName));
1338     end
1339
1340     % Get data at every point in time vector, t
1341     ExtraTimeDelay = etime(clock, t0);
1342     t = t - ExtraTimeDelay;
1343     [AM, tout, DataTime, ErrorFlag] = feval(SpecialFunction, AO.FamilyName, Field, DeviceList, t);
1344     t1 = clock;
1345     if isempty(tout)
1346         tout = etime(t1, t0);
1347     end
1348     if nargout >= 3 && isempty(DataTime)
1349         days = datenum(t1(1:3)) - 719529;  %datenum('1-Jan-1970');
1350         tt = 24*60*60*days + 60*60*t1(4) + 60*t1(5) + t1(6);
1351         DataTime(1:size(AM,1),1) = fix(tt) + rem(tt,1)*1e9*sqrt(-1);
1352     end
1353     if length(t) > length(tout)
1354         for itime = 2:length(t)
1355             T = t(itime)-etime(clock, t0);
1356             if T > 0
1357                 pause(T);
1358             end
1359
1360             % Get data
1361             [Tmp, toutTmp, DataTimeTmp, ErrorFlag] = feval(SpecialFunction, AO.FamilyName, Field, DeviceList, t);
1362
1363             AM = [AM Tmp];
1364             DataTime = [DataTime DataTimeTmp];
1365
1366             t1 = clock;
1367             tout(1,itime) = etime(t1, t0);
1368             if nargout >= 3 && isempty(DataTimeTmp)
1369                 days = datenum(t1(1:3)) - 719529;  %datenum('1-Jan-1970');
1370                 tt = 24*60*60*days + 60*60*t1(4) + 60*t1(5) + t1(6);
1371                 DataTime(1:size(AM,1),itime) = fix(tt) + rem(tt,1)*1e9*sqrt(-1);
1372             end
1373         end
1374     end
1375
1376     % FreshDataFlag
1377     if FreshDataFlag && length(t) == 1
1378         % Only use FreshDataFlag for scalar t
1379         FreshDataCounter = FreshDataFlag;
1380         AM0 = AM;
1381         while FreshDataCounter
1382             % Get data
1383             [AM, tout, DataTime, ErrorFlag] = feval(SpecialFunction, AO.FamilyName, Field, DeviceList, t);
1384
1385             if ~any((AM-AM0)==0)
1386                 FreshDataCounter = FreshDataCounter - 1;
1387                 AM0 = AM;
1388             end
1389
1390             t1 = clock;
1391             if etime(t1, t0) > TimeOutPeriod
1392                 k = find((AM-AM0)==0);
1393                 for j = 1:length(k)
1394                     fprintf('%s[%d,%d] not changing.\n', AO.FamilyName, DeviceList(k(j),1), DeviceList(k(j),2));
1395                 end
1396                 error('Timed out waiting for fresh data.');
1397             end
1398         end
1399         tout = etime(t1, t0);
1400
1401         if nargout >= 3 && isempty(DataTime)
1402             days = datenum(t1(1:3)) - 719529;  %datenum('1-Jan-1970');
1403             tt = 24*60*60*days + 60*60*t1(4) + 60*t1(5) + t1(6);
1404             DataTime(1:size(AM,1),1) = fix(tt) + rem(tt,1)*1e9*sqrt(-1);
1405         end
1406     end
1407
1408     % Change to physics units if Units = 'physics'
1409     if strcmpi(AO.(Field).Units,'physics')
1410         % Change to physics units
1411         AM = hw2physics(AO.FamilyName, Field, AM, DeviceList);
1412     end
1413
1414 elseif strcmpi(Mode,'manual')
1415     % Always return in hardware units (like connected to the IOC)
1416     % The conversion to physics in done at the end
1417     t = 0;
1418     if strcmp(AO.FamilyName, 'TUNE')
1419         HarmNumber = [];
1420         RF = [];
1421         if find(DeviceIndex == 1)
1422             AM(1,1) = input(sprintf('   Input the horizontal tune (fraction or Hz) = '));
1423             if AM(1,1) > 1
1424                 HarmNumber = getharmonicnumber;
1425                 RF = getrf('Struct');
1426                 if strcmpi(RF.UnitsString,'MHz')
1427                     FundFreq = 1e6*RF.Data / HarmNumber;
1428                 elseif strcmpi(RF.UnitsString,'Hz')
1429                     FundFreq = RF.Data / HarmNumber;
1430                 else
1431                     error('RF units in not known.');
1432                 end
1433                 %AM(1,1) = (AM(1,1)- RF) / FundFreq;
1434                 AM(1,1) = AM(1,1) / FundFreq;
1435                 fprintf('   Horizontal fraction tune computed to be %f\n\n', AM(1,1));
1436             end
1437         end
1438         if find(DeviceIndex == 2)
1439             AM(2,1) = input(sprintf('   Input the vertical   tune (fraction or Hz) = '));
1440             if AM(2,1) > 1
1441                 if isempty(HarmNumber)
1442                     HarmNumber = getharmonicnumber;
1443                 end
1444                 if isempty(RF)
1445                     RF = getrf('Struct');
1446                 end
1447                 if strcmpi(RF.UnitsString,'MHz')
1448                     FundFreq = 1e6*RF.Data / HarmNumber;
1449                 elseif strcmpi(RF.UnitsString,'Hz')
1450                     FundFreq = RF.Data / HarmNumber;
1451                 else
1452                     error('RF units in not known.');
1453                 end
1454                 AM(2,1) = AM(2,1)/FundFreq;
1455                 %AM(2,1) = (AM(2,1) - HarmNumber * FundFreq)/FundFreq;
1456                 fprintf('   Vertical   fraction tune computed to be %f\n\n', AM(2,1));
1457             end
1458         end
1459         if find(DeviceIndex == 3)
1460             AM(2,1) = input('   Input the synchrotron tune = ');
1461         end
1462     elseif strcmp(AO.FamilyName, 'RF')
1463         if strcmpi(AO.(Field).Units, 'Hardware')
1464             AM(1) = input(sprintf('   Input the RF frequency [%s] = ', AO.(Field).HWUnits));
1465         else
1466             AM(1) = input(sprintf('   Input the RF frequency [%s] = ', AO.(Field).PhysicsUnits));
1467             AM = physics2hw(AO.FamilyName, Field, AM, [1 1]);
1468         end
1469     else
1470         for i = 1:length(DeviceIndex)
1471             if strcmpi(AO.(Field).Units, 'Hardware')
1472                 AM(i,:) = input(sprintf('   Manual input:  %s(%d,%d) [%s] = ', AO.FamilyName, AO.DeviceList(DeviceIndex(i),1), AO.DeviceList(DeviceIndex(i),2), AO.(Field).HWUnits));
1473             else
1474                 AM(i,:) = input(sprintf('   Manual input:  %s(%d,%d) [%s] = ', AO.FamilyName, AO.DeviceList(DeviceIndex(i),1), AO.DeviceList(DeviceIndex(i),2), AO.(Field).PhysicsUnits));
1475                 AM(i,:) = physics2hw(AO.FamilyName, Field, AM(i,:), AO.DeviceList(DeviceIndex(i),:));
1476             end
1477         end
1478     end
1479
1480     t1 = clock;
1481     tout = etime(t1, t0);
1482     days = datenum(t1(1:3)) - 719529;  %datenum('1-Jan-1970');
1483     tt = 24*60*60*days + 60*60*t1(4) + 60*t1(5) + t1(6);
1484     DataTime(1:size(AM,1),1) = fix(tt) + rem(tt,1)*1e9*sqrt(-1);
1485
1486     % Change to physics units if Units = 'physics'
1487     if strcmpi(AO.(Field).Units,'physics')
1488         % Change to physics units
1489         AM = hw2physics(AO.FamilyName, Field, AM, DeviceList);
1490     end
1491
1492
1493 elseif strcmpi(Mode,'Simulator') || strcmpi(Mode,'Model')
1494
1495     ExtraTimeDelay = etime(clock, t0);
1496     %[AM, tout, DataTime, ErrorFlag] = getpvmodel(AO, Field, DeviceList, t-ExtraTimeDelay, 'Physics', 'Numeric');
1497     [AM, tout, DataTime, ErrorFlag] = getpvmodel(AO, Field, DeviceList, t-ExtraTimeDelay, AO.(Field).Units, 'Numeric');
1498     tout = tout + ExtraTimeDelay;
1499
1500
1501     if strcmpi(OutputDataType, 'String')
1502         AM = num2str(AM);
1503     end
1504
1505     % Change to physics units if Units = 'physics'
1506     %if strcmpi(AO.(Field).Units,'Hardware')
1507     %    % Change to physics units
1508     %    AM = physics2hw(AO.FamilyName, Field, AM, DeviceList, getenergymodel);
1509     %end
1510
1511 else
1512     error(sprintf('Unknown mode for family %s.', AO.FamilyName));
1513 end
1514
1515
1516