Description of getsp
Home > mml > getsp.m
getsp
PURPOSE
GETSP - Gets setpoint channels
SYNOPSIS
function [SP, tout, DataTime, ErrorFlag] = getsp(Family, varargin)
DESCRIPTION
GETSP - Gets setpoint channels
  If using family name, device list method,
  [SP, tout, DataTime] = getsp(Family, DeviceList, t, FreshDataFlag, TimeOutPeriod)
  If using data structure,
  [AM, tout, DataTime] = getsp(DataStructure, t, FreshDataFlag, TimeOutPeriod)
  If using channel name method,
  [SP, tout, DataTime] = getsp(ChannelName, t, FreshDataFlag, TimeOutPeriod)
  INPUTS & OUTPUTS
  See getpv.  getsp is an alias to getpv with Field='Setpoint'.
  See also getam, setsp, getpv, setpv
CROSS-REFERENCE INFORMATION
This function calls:
getpv GETPV - Returns a variable from the online system or the model
isfamily ISFAMILY - True for family names
This function is called by:
finddispquad FINDDISPQUAD - Find the optimal setting for the dispersion correction quadrupole family
getenergy GETENERGY - Returns the beam energy base on the bend magnet
hcm2golden HCM2GOLDEN - Set horizontal corrector strengths to golden values
hcm2zero HCM2ZERO - Set horizontal corrector strengths to zero
magstep MAGSTEP - Script for testing the time responce of a magnet
measbpmresp MEASBPMRESP - Measures the BPM response matrix in the horizontal and vertical planes
measbpmresplinearity MEASBPMRESPLINEARITY - Compute BPMlinearity
measchroresp MEASCHRORESP - measures the response from sextupoles to chromaticity
meascmhysteresis MEASCMHYSTERESIS - Measure corrector magnet hysteresis
measdispresp MEASDISPRESP - Measures Amman TERMs in response matrix
measidfftable MEASIDFFTABLE - Measures an insertion device feed forward table for the vertical gap
measrespmat MEASRESPMAT - Measure a response matrix
monmags MONMAGS - Monitors all magnet power supplies and plots various statistics
orbitcorrectionmethods ORBITCORRECTIONMETHODS - Some the orbit correction methods used on light sources
plotcm PLOTCM - Plots the horizontal and vertical corrector magnet families and
plotfamily PLOTFAMILY - Plots by middle layer family name
plotmemberof PLOTMEMBEROF - Plots the setpoint and monitor for all members in a "MemberOf" group
quadcenter QUADCENTER - Measure the magnet center of a quadrupole magnet
scanorbit SCANORBIT - Scans 2 correctors 90 degrees out of phase
setorbit SETORBIT - Orbit correction function
setorbit1 SETORBIT1 - Correct the orbit using all the SVD (1 plane)
setorbitgui SETORBITGUI - Orbit correction GUI
setpv SETPV - Setpoint change of the online system or model
showmachinedata SHOWMACHINEDATA - Display setpoints and readbacks for families in AcceleratorObjects
stepchro STEPCHRO - Incremental change in the chromaticity (Delta Tune / Delta RF)
steptune STEPTUNE - Step the tune
sweepenergy SWEEPENERGY - Energy sweep of the storage ring
vcm2golden VCM2GOLDEN - Set vertical corrector strengths to golden values
vcm2zero VCM2ZERO - Set vertical corrector strengths to zero
SOURCE CODE
function [SP, tout, DataTime, ErrorFlag] = getsp(Family, varargin)
%GETSP - Gets setpoint channels
%  If using family name, device list method,
%  [SP, tout, DataTime] = getsp(Family, DeviceList, t, FreshDataFlag, TimeOutPeriod)
%
%  If using data structure,
%  [AM, tout, DataTime] = getsp(DataStructure, t, FreshDataFlag, TimeOutPeriod)
%
%  If using channel name method,
%  [SP, tout, DataTime] = getsp(ChannelName, t, FreshDataFlag, TimeOutPeriod)
%
%  INPUTS & OUTPUTS
%  See getpv.  getsp is an alias to getpv with Field='Setpoint'.
%
%  See also getam, setsp, getpv, setpv
%  Written by Greg Portmann
% if nargout < 3
%     [SP, tout] = getpv(varargin{:});
% else
%     [SP, tout, DataTime, ErrorFlag] = getpv(varargin{:});
% end
if nargin == 0
    error('Must have at least one input (Family, Data Structure or Channel Name).');
end
if iscell(Family)
    [SP, tout, DataTime, ErrorFlag] = getpv(Family, 'Setpoint', varargin{:});
else
    FamilyIndex = isfamily(Family);
    if nargout < 3
        if FamilyIndex
            % Family name method
            [SP, tout] = getpv(Family, 'Setpoint', varargin{:});
        else
            % ChannelName method
            [SP, tout] = getpv(Family, '', varargin{:});
        end
    else
        if FamilyIndex
            % Family name method
            [SP, tout, DataTime, ErrorFlag] = getpv(Family, 'Setpoint', varargin{:});
        else
            % ChannelName method
            [SP, tout, DataTime, ErrorFlag] = getpv(Family, '', varargin{:});
        end
    end
end