Description of getspos
Home > mml > getspos.m
getspos
PURPOSE
GETSPOS - Returns the longitudinal position in meters
SYNOPSIS
function S = getspos(Family, DeviceList)
DESCRIPTION
GETSPOS - Returns the longitudinal position in meters
  If using family name, device list method,
  S = getspos(Family, DeviceList)
  If using AT family name
  S = getspos(FamName, IndexVector)
  If using channel name method,
  S = getspos(ChannelNames)
  If using common name method,
  S = getspos(Family, CommonName)
  INPUTS
  1. Family = MiddleLayer or AT Family Name
              Accelerator Object
              Cell Array of Accelerator Objects or Family Names
              For CommonNames, Family=[] searches all families
     ChannelName = Channel access channel name
                   Matrix of channel names
                   Cell array of channel names
     CommonName = Common name
                  Matrix of common names
                  Cell array of common names
     DeviceList = [Sector Device #] or [element #] list {default or empty list: whole family}
                   Cell Array of DeviceList
  OUTPUTS
  1. S = the position of the device along the ring (S) [meters]
         Empty if Family or CommonName is found not found
CROSS-REFERENCE INFORMATION
This function calls:
channel2dev CHANNEL2DEV - Converts a channel name list to a device list
channel2family CHANNEL2FAMILY - Convert a channel name to a Family, Field, DeviceList
checkforcommonnames CHECKFORCOMMONNAMES - Checks for common names in the Family or DeviceList input
family2dev FAMILY2DEV - Return the device list for a family
family2status FAMILY2STATUS - Returns the device status
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
getspos GETSPOS - Returns the longitudinal position in meters
isfamily ISFAMILY - True for family names
This function is called by:
bpm2quad BPM2QUAD - Returns the nearest quadrupole to the specified BPM
bpm2sext BPM2SEXT - Returns the nearest sextupole to the specified BPM
getspos GETSPOS - Returns the longitudinal position in meters
makebump MAKEBUMP - Creates and orbit correction structure (OCS) usable by setorbit
measbpmresp MEASBPMRESP - Measures the BPM response matrix in the horizontal and vertical planes
measbpmresplinearity MEASBPMRESPLINEARITY - Compute BPMlinearity
measidfftable MEASIDFFTABLE - Measures an insertion device feed forward table for the vertical gap
mmlviewer MMLVIEWER M-file for mmlviewer.fig
plotbpmresp PLOTBPMRESP - Plots the orbit response matrix in various ways
plotbpmrespsym PLOTBPMRESPSYM - Looks for symmetry of the orbit response matrix
plotcm PLOTCM - Plots the horizontal and vertical corrector magnet families and
plotdisp PLOTDISP - Plots the dispersion function
plotfamily PLOTFAMILY - Plots by middle layer family name
plotgoldenorbit PLOTGOLDENORBIT - Plots the golden orbit
plotidfftable PLOTIDFFTABLE - Plots various information about the feed forward tables
plotlattice PLOTLATTICE - Plot the lattice
plotoffsetorbit PLOTOFFSETORBIT - Plots the offset orbit
plotorbit PLOTORBIT - Plot the present orbit w.r.t. the golden or offset orbit
quad2bpm QUAD2BPM - Returns the nearest BPM to the specified quadrupole
quadcenterfit QUADCENTERFIT OR BBASEARCH - Model search method to find a quarupole center
quadgetdata QUADGETDATA - Collect the date from a quadrupole center run.
rmdisp RMDISP - Removes the portion of the orbit that correlates with the dispersion
setorbit SETORBIT - Orbit correction function
setorbitbump SETORBITBUMP - Local bump program (uses setorbit)
setorbitbumpgui SETORBITBUMPGUI M-file for setorbitbumpgui.fig
sext2bpm SEXT2BPM - Returns the nearest BPM to the specified sextupole
SOURCE CODE
function S = getspos(Family, DeviceList)
%GETSPOS - Returns the longitudinal position in meters
%
%  If using family name, device list method,
%  S = getspos(Family, DeviceList)
%
%  If using AT family name
%  S = getspos(FamName, IndexVector)
%
%  If using channel name method,
%  S = getspos(ChannelNames)
%
%  If using common name method,
%  S = getspos(Family, CommonName)
%
%  INPUTS
%  1. Family = MiddleLayer or AT Family Name
%              Accelerator Object
%              Cell Array of Accelerator Objects or Family Names
%              For CommonNames, Family=[] searches all families
%     ChannelName = Channel access channel name
%                   Matrix of channel names
%                   Cell array of channel names
%     CommonName = Common name
%                  Matrix of common names
%                  Cell array of common names
%     DeviceList = [Sector Device #] or [element #] list {default or empty list: whole family}
%                   Cell Array of DeviceList
%
%  OUTPUTS
%  1. S = the position of the device along the ring (S) [meters]
%         Empty if Family or CommonName is found not found
%  Written by Greg Portmann
if nargin == 0
    error('At least one input required');
end
%%%%%%%%%%%%%%%%%%%%%
% Cell Array Inputs %
%%%%%%%%%%%%%%%%%%%%%
if iscell(Family)
    for i = 1:length(Family)
        if nargin < 2
            S{i} = getspos(Family{i});
        else
            if iscell(DeviceList)
                S{i} = getspos(Family{i}, DeviceList{i});
            else
                S{i} = getspos(Family{i}, DeviceList);
            end
        end
    end
    return
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Family or data structure inputs beyond this point %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if isstruct(Family)
    % Data structure inputs
    if nargin < 2
        if isfield(Family,'DeviceList')
            DeviceList = Family.DeviceList;
        else
            DeviceList = [];
        end
    end
    if isfield(Family,'FamilyName')
        Family = Family.FamilyName;
    else
        error('For data structure inputs FamilyName field must exist')
    end
else
    % Family string input
    if nargin < 2
        DeviceList = [];
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Check DeviceList or Family is a common name list %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
[Family, DeviceList] = checkforcommonnames(Family, DeviceList);
if isfamily(Family(1,:))
    %%%%%%%%%%%%%%%%%%%%%%
    % Family name method %
    %%%%%%%%%%%%%%%%%%%%%%
    if isempty(DeviceList)
        DeviceList = family2dev(Family);
    end
    % if (size(DeviceList,2) == 1)
    %     DeviceList = elem2dev(Family, DeviceList);
    % end
    % Get data
    S = getfamilydata(Family, 'Position', DeviceList);
else
    %%%%%%%%%%%%%%%%%%%%%%%
    % Channel name method %
    %%%%%%%%%%%%%%%%%%%%%%%
    ATIndex = family2atindex(Family(1,:), DeviceList);
    global THERING
    if ~isempty(ATIndex)
        S = findspos(THERING, ATIndex);
        S = S(:);
    else
        %%%%%%%%%%%%%%%%%%%%%%%
        % Channel name method %
        %%%%%%%%%%%%%%%%%%%%%%%
        % Try to convert to a family and device
        ChannelNames = Family;
        for i = 1:size(ChannelNames,1)
            Family = channel2family(ChannelNames(i,:));
            if isempty(Family)
                error('Channel name could not be converted to a Family.');
            end
            [FamilyIndex, ACCELERATOR_OBJECT] = isfamily(Family);
            DeviceList = channel2dev(ChannelNames(i,:), ACCELERATOR_OBJECT);
            if isempty(DeviceList) || isempty(DeviceList)
                error('Channel name could not be converted to a Family and DeviceList.');
            end
            S(i,:) = family2status(Family, DeviceList);
        end
    end
end