Description of getunits
Home > mml > getunits.m
getunits
PURPOSE
GETUNITS - Return the present family units and units string
SYNOPSIS
function [Units, UnitsString] = getunits(Family, Field)
DESCRIPTION
GETUNITS - Return the present family units and units string
  [Units, UnitsString] = getunits(Family, Field)
  INPUTS
  1. Family - Family Name
              Data Structure
              Accelerator Object
              (or a cell array of the above types)
  2. Field - Accelerator Object field name ('Monitor', 'Setpoint', etc) {Default: 'Monitor'}
  OUTPUTS
  1. Units - Units ('Physics' or 'Hardware') corresponding to the Family and Field
  2. UnitsSting - Units string corresponding to the Family and Field
  NOTES
  1. If the inputs are cell arrays, then the outputs are cell arrays
  2. Same as family2units
CROSS-REFERENCE INFORMATION
This function calls:
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
getunits GETUNITS - Return the present family units and units string
This function is called by:
family2datastruct FAMILY2DATASTRUCTURE
family2tol FAMILY2TOL - Return the (SP-AM) tolerance for a family
family2units FAMILY2UNITS - Return the present family units and units string
findrf FINDRF - Finds the RF frequency that minimizes the energy change due
getcrunch GETCRUNCH- Returns the crunch values for a family (radians)
getdata GETDATA - Searches through a file (or group of files) for a data structure which matches the family name
getgain GETGAIN - Returns the gain for a family
getgolden GETGOLDEN - Returns the golden values for a family
getoffset GETOFFSET - Returns the offset values for a family
getpv GETPV - Returns a variable from the online system or the model
getramprate GETRAMPRATE - Returns the ramp rate for a family
getrespmat GETRESPMAT - Get response matrix data from a file
getroll GETROLL - Returns the roll values for a family (radians)
getsigma GETSIGMA - Return the standard deviation in the monitor for a family
getunits GETUNITS - Return the present family units and units string
maxpv MAXPV - Maximum value of a process variable
minpv MinPV - Maximum value of a process variable
mmlviewer MMLVIEWER M-file for mmlviewer.fig
monbpm MONBPM - Monitors the orbit
monmags MONMAGS - Monitors all magnet power supplies and plots various statistics
plotcm PLOTCM - Plots the horizontal and vertical corrector magnet families and
rmdisp RMDISP - Removes the portion of the orbit that correlates with the dispersion
setorbitbump SETORBITBUMP - Local bump program (uses setorbit)
settune SETTUNE - Set the tune
SOURCE CODE
function [Units, UnitsString] = getunits(Family, Field)
%GETUNITS - Return the present family units and units string
%  [Units, UnitsString] = getunits(Family, Field)
%
%  INPUTS
%  1. Family - Family Name
%              Data Structure
%              Accelerator Object
%              (or a cell array of the above types)
%  2. Field - Accelerator Object field name ('Monitor', 'Setpoint', etc) {Default: 'Monitor'}
%
%  OUTPUTS
%  1. Units - Units ('Physics' or 'Hardware') corresponding to the Family and Field
%  2. UnitsSting - Units string corresponding to the Family and Field
%
%  NOTES
%  1. If the inputs are cell arrays, then the outputs are cell arrays
%  2. Same as family2units
%  Written by Greg Portmann
if nargin == 0
    error('Must have at least one input (''Family'')!');
end
%%%%%%%%%%%%%%%%%%%%%
% Cell Array Inputs %
%%%%%%%%%%%%%%%%%%%%%
if iscell(Family)
    for i = 1:length(Family)
        if nargin < 2
            [Units{i}, UnitsString{i}] = getunits(Family{i});
        elseif nargin < 3
            if iscell(Field)
                [Units{i}, UnitsString{i}] = getunits(Family{i}, Field{i});
            else
                [Units{i}, UnitsString{i}] = getunits(Family{i}, Field);
            end
        end
    end
    return
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Family or data structure inputs beyond this point %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if isstruct(Family)
    % Data structure inputs
    if nargin < 2
        if isfield(Family,'Field')
            Field = Family.Field;
        else
            Field = '';
        end
    end
    if isfield(Family,'FamilyName')
        Family = Family.FamilyName;
    else
        error('For data structure inputs FamilyName field must exist')
    end
else
    % Family string input
    if nargin < 2
        Field = '';
    end
end
if isempty(Field)
    Field = 'Monitor';
end
%%%%%%%%%%%%
% Get data %
%%%%%%%%%%%%
Units = getfamilydata(Family, Field, 'Units');
if nargout > 1
    if strcmpi(Units,'Hardware')
        UnitsString = getfamilydata(Family, Field, 'HWUnits');
    elseif strcmpi(Units,'Physics')
        UnitsString = getfamilydata(Family, Field, 'PhysicsUnits');
    else
        error('Units unknown');
    end
end