Description of isfamily
Home > mml > isfamily.m
isfamily
PURPOSE
ISFAMILY - True for family names
SYNOPSIS
function [FamilyFlag, AO] = isfamily(Family, Field)
DESCRIPTION
ISFAMILY - True for family names
  [Flag, Structure] = isfamily(Family)
  INPUTS
  1. FamilyName or Data Structure
     (only the FamilyName field is used for Data Structure inputs)
  2. Field - Middlelayer field name (optional)
  OUTPUTS
  1. Flag = 1 if FamilyName is a family
            0 if no family name was found
  2. Structure - the middle layer data structure for that family
                 or the data structure for that field if Field is input.
  NOTES
  1. For string matrix inputs a column vector is returned.
     However, the Structure output will be for the last row.
  2. Family and Field names are case sensitive.
  See also getmemberof, findmemberof
CROSS-REFERENCE INFORMATION
This function calls:
getao GETAO - returns the AcceleratorObject (AO)
isfamily ISFAMILY - True for family names
This function is called by:
checkforcommonnames CHECKFORCOMMONNAMES - Checks for common names in the Family or DeviceList input
elem2dev ELEM2DEV - Converts a device list to an element list
family2status FAMILY2STATUS - Returns the device status
getchro GETCHRO - Return the chromaticity function (from file)
getchroresp GETCHRORESP - Loads the chromaticity response vector (or matrix) for multiple sextupole families
getdcct GETDCCT - returns the beam current
getdisp GETDISP - Returns the dispersion for a BPM family (from file)
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
getmachineconfig GETMACHINECONFIG - Returns or saves to file the present storage ring setpoints and monitors
getpv GETPV - Returns a variable from the online system or the model
getrunflag GETRUNFLAG - Returns position if the device is in the process of changing a setpoint
getsp GETSP - Gets setpoint channels
getspos GETSPOS - Returns the longitudinal position in meters
gettuneresp GETTUNERESP - Loads the tune response vector (or matrix) for multiple quadrupole families
isfamily ISFAMILY - True for family names
machine2sim MACHINE2SIM - loads online machine configuration to AT configuration
measbeta MEASBETA - Measure the betatron functions
measbpmresp MEASBPMRESP - Measures the BPM response matrix in the horizontal and vertical planes
measchro MEASCHRO - measures the chromaticity function emperically
measrespmat MEASRESPMAT - Measure a response matrix
monbpm MONBPM - Monitors the orbit
plotdisp PLOTDISP - Plots the dispersion function
plotfamily PLOTFAMILY - Plots by middle layer family name
plotlattice PLOTLATTICE - Plot the lattice
quadcenter QUADCENTER - Measure the magnet center of a quadrupole magnet
rmdisp RMDISP - Removes the portion of the orbit that correlates with the dispersion
setfamilydata SETFAMILYDATA - Sets data associated with accelerator control
setgolden SETGOLDEN - Set the golden values
setmachineconfig SETMACHINECONFIG - Sets the storage ring setpoints from a file or configuration data structure
setoffset SETOFFSET - Set the offset value for this matlab session (not saved)
setpv SETPV - Setpoint change of the online system or model
setsp SETSP - Makes an absolute setpoint change to the 'Setpoint' field
showfamily SHOWFAMILY - Displays a list of all families
showmachinedata SHOWMACHINEDATA - Display setpoints and readbacks for families in AcceleratorObjects
stepsp STEPSP - Step the setpoint for family
tune2online TUNE2ONLINE - Sets the TUNE family to online mode
tune2sim TUNE2SIM - Sets the TUNE family to simulator mode
SOURCE CODE
function  [FamilyFlag, AO] = isfamily(Family, Field)
%ISFAMILY - True for family names
%  [Flag, Structure] = isfamily(Family)
%
%  INPUTS
%  1. FamilyName or Data Structure
%     (only the FamilyName field is used for Data Structure inputs)
%  2. Field - Middlelayer field name (optional)
%
%  OUTPUTS
%  1. Flag = 1 if FamilyName is a family
%            0 if no family name was found
%  2. Structure - the middle layer data structure for that family
%                 or the data structure for that field if Field is input.
%
%  NOTES
%  1. For string matrix inputs a column vector is returned.
%     However, the Structure output will be for the last row.
%  2. Family and Field names are case sensitive.
%
%  See also getmemberof, findmemberof
%  Written by Greg Portmann
if nargin == 0,
    error('Must have at least one input (''Family'')!');
end
if isstruct(Family)
    if isfield(Family,'FamilyName') && isfield(Family, 'Field')
        % Data structure: find the AO
        [FamilyFlag, AO] = isfamily(Family.FamilyName);
    elseif isfield(Family,'FamilyName')
        % AO structure: use the same structure
        FamilyFlag = 1;
        AO = Family;
    else
        %error('Family input of unknown type');
        AO = [];
        FamilyFlag = 0;
    end
elseif isnumeric(Family)
    FamilyFlag = 0;
    AO = [];
elseif size(Family,1) > 1
    for i = 1:size(Family, 1)
        if nargin == 1
            [FamilyFlag(i,1), AO] = isfamily(Family(i,:));
        else
            if size(Family,1) == size(Field,1)
                [FamilyFlag(i,1), AO] = isfamily(Family(i,:), Field(i,:));
            elseif size(Field,1) == 1
                [FamilyFlag(i,1), AO] = isfamily(Family(i,:), Field);
            else
                error('Field must be 1 row or equal to the number of rows in Family');
            end
        end
    end
else
    AO = getao;
    if isempty(AO)
        fprintf('   ACCELERATOR_OBJECT is empty.  Initialization is needed (aoinit).');
        AO = [];
        FamilyFlag = 0;
        return
    end
    if ~ischar(Family)
        error('Family input must be a string.');
    end
    Family = deblank(Family);
    if nargin > 1
        if ~ischar(Field)
            error('Field input must be a string.');
        end
        Field = deblank(Field);
    end
    if isfield(AO, Family)
        FamilyFlag = 1;
        AO = AO.(Family);
        if nargin > 1
            if ~isempty(Field)
                if isfield(AO, Field)
                    FamilyFlag = 1;
                    AO = AO.(Field);
                else
                    FamilyFlag = 0;
                    AO = [];
                end
            end
        end
    else
        FamilyFlag = 0;
        AO = [];
    end
end