Description of loadao
Home > mml > loadao.m
loadao
PURPOSE
LOADAO - Loads the AO and AD from a .mat file
SYNOPSIS
function FileName = loadao(FileName)
DESCRIPTION
LOADAO - Loads the AO and AD from a .mat file
  FileName = loadao(FileName)
  FileName = loadao('Golden') to load the golden MML setup file from the operations directory (MMLSetup.mat)
  See also saveao
CROSS-REFERENCE INFORMATION
This function calls:
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
setad SETAD - Sets the MML AcceleratorData cell array to appdata
setao SETAO - Set the MML Accelerator Object (AO)
This function is called by:
SOURCE CODE
function  FileName = loadao(FileName)
%LOADAO - Loads the AO and AD from a .mat file
%  FileName = loadao(FileName)
%  FileName = loadao('Golden') to load the golden MML setup file from the operations directory (MMLSetup.mat)
%
%  See also saveao
%  Written by Greg Portmann
if nargin < 1
    FileName = '';
end
if ischar(FileName)
    if isempty(FileName)
        [FileName, DirectoryName, FilterIndex] = uigetfile('*.mat','Select an MML setup file');
        if FilterIndex == 0
            return;
        end
        FileName = [DirectoryName, FileName];
    elseif strcmpi(FileName, 'Golden')
        FileName = [getfamilydata('Directory','OpsData'), 'GoldenMMLSetup.mat'];
    end
else
    error('Filename input must be a string');
end
load(FileName);
setao(AO);
setad(AD);