Description of machine2sim
Home > mml > machine2sim.m
machine2sim
PURPOSE
MACHINE2SIM - loads online machine configuration to AT configuration
SYNOPSIS
function machine2sim(ZeroCMFlag)
DESCRIPTION
MACHINE2SIM - loads online machine configuration to AT configuration
  machine2sim(ZeroCMFlag)
  ZeroCMFlag = 0 set the machine corrector setting to the simulator
               1 zero the correctors in the simulator {Default}
  NOTES
  1. The RF frequency of the simulator is not changed
  2. Use ZeroCMFlag = 1 when you think the corrector magnets on the
     online machine are restoring the orbit to the design orbit (or close)
  See also sim2machine, golden2sim
CROSS-REFERENCE INFORMATION
This function calls:
getam GETAM - Gets monitor channels
gethcmfamily GETHCMFAMILY - Returns the default horizontal corrector family
getmachineconfig GETMACHINECONFIG - Returns or saves to file the present storage ring setpoints and monitors
getvcmfamily GETVCMFAMILY - Returns the default vertical corrector family
isfamily ISFAMILY - True for family names
setmachineconfig SETMACHINECONFIG - Sets the storage ring setpoints from a file or configuration data structure
setsp SETSP - Makes an absolute setpoint change to the 'Setpoint' field
This function is called by:
plotfamily PLOTFAMILY - Plots by middle layer family name
SOURCE CODE
function machine2sim(ZeroCMFlag)
%MACHINE2SIM - loads online machine configuration to AT configuration
%  machine2sim(ZeroCMFlag)
%
%  ZeroCMFlag = 0 set the machine corrector setting to the simulator
%               1 zero the correctors in the simulator {Default}
%
%  NOTES
%  1. The RF frequency of the simulator is not changed
%  2. Use ZeroCMFlag = 1 when you think the corrector magnets on the
%     online machine are restoring the orbit to the design orbit (or close)
%
%  See also sim2machine, golden2sim
%  Written by Greg Portmann
if nargin < 1
    ZeroCMFlag = 1;
end
% Get from the online machine
ConfigSetpoint = getmachineconfig('Online');
% Set to the simulator (don't change the simulator RF)
if isfamily('RF')
    RFsim = getam('RF', 'Simulator');
end
if isfamily('RF')
    setmachineconfig(ConfigSetpoint, 'Simulator');
    setsp('RF', RFsim, 'Simulator');
end
if ZeroCMFlag
    setsp(gethcmfamily, 0, 'Simulator');
    setsp(getvcmfamily, 0, 'Simulator');
end