Description of measbpmresp
Home > mml > measbpmresp.m
measbpmresp
PURPOSE
MEASBPMRESP - Measures the BPM response matrix in the horizontal and vertical planes
SYNOPSIS
function [Rmat, OutputFileName] = measbpmresp(varargin)
DESCRIPTION
MEASBPMRESP - Measures the BPM response matrix in the horizontal and vertical planes
  For family name, device list inputs:
  [R, FileName] = measbpmresp(BPMxFamily, BPMxList, BPMyFamily, BPMyList, HCMFamily, HCMList, VCMFamily, VCMList, HCMKicks, VCMKicks, ModulationMethod, WaitFlag, FileName, DirectoryName, ExtraDelay)
  For data structure inputs:
  [R, FileName] = measbpmresp(BPMxStruct, BPMyStruct, HCMStruct, VCMStruct, HCMKicks, VCMKicks, ModulationMethod, WaitFlag, FileName, DirectoryName, ExtraDelay)
  INPUTS
  1. BPMxFamily       - BPMx family name {Default: gethbpmfamily}
     BPMxDeviceList   - BPMx device list {Default: all devices with good status}
     or
     BPMxStruct can replace BPMxFamily and BPMxList
  2. BPMyFamily       - BPMy family name {Default: getvbpmfamily}
     BPMyDeviceList   - BPMy device list {Default: all devices with good status}
     or
     BPMyStruct can replace BPMyFamily and BPMyList
  3. HCMFamily       - HCM family name {Default: gethcmfamily}
     HCMDeviceList   - HCM device list {Default: all devices with good status}
     or
     HCMStruct can replace HCMFamily and HCMList
  4. VCMFamily       - VCM family name {Default: getvcmfamily}
     VCMDeviceList   - VCM device list {Default: all devices with good status}
     or
     VCMStruct can replace VCMFamily and VCMList
  5. HCMKicks - Change in HCM correctors {Default: getfamilydata(HCMFamily,'Setpoint','DeltaRespMat',HCMDeviceList), then .05 mrad}
  6. VCMKicks - Change in VCM correctors {Default: getfamilydata(VCMFamily,'Setpoint','DeltaRespMat',VCMDeviceList), then .05 mrad}
  7. ModulationMethod - Method for changing the ActuatorFamily
                       'bipolar' changes the ActuatorFamily by +/- ActuatorDelta/2 on each step {Default}
                       'unipolar' changes the ActuatorFamily from 0 to ActuatorDelta on each step
  8. WaitFlag - (see setpv for WaitFlag definitions) {Default: []}
                WaitFlag = -5 will override gets to manual mode
  9. Optional input to change the default filename and directory
     FileName - Filename for the response matrix data
                (Empty prompts for a filename)
     DirectoryName - Directory name to store the response matrix data file
     Note: a. FileName can include the path if DirectoryName is not used
           b. For model response matrices, FileName must exist for a file save
           c. The 'Achive' flag is another way to input the filename
  10. ExtraDelay - extra time delay [seconds] after a setpoint change
  11. 'Struct'  - Output will be a response matrix structure {Default for     data structure inputs}
      'Numeric' - Output will be a numeric matrix            {Default for non-data structure inputs}
  12. Optional override of the units:
      'Physics'  - Use physics  units
      'Hardware' - Use hardware units
  13. Optional override of the mode:
      'Online'    - Set/Get data online
      'Model'     - Set/Get data directly from AT (uses locoresponsematrix)
      'Simulator' - Set/Get data on the simulated accelerator using AT (ie, same commands as 'Online')
      'Manual'    - Set/Get data manually
  14. 'Display'   - Prints status information to the command window {Default}
      'NoDisplay' - Nothing is printed to the command window
  15. 'NoArchive' - No file archive
      'Archive'   - Save the response matrix data to \<Directory.BPMResponse>\<BPMRespFile><Date><Time>.mat
                    To change the filename, included the filename after the 'Archive', '' to browse
  16. 'MinimumBeamCurrent' - Minimum beam current before prompting for a refill
                             The current (as returned by getdcct) must follow the flag.
                             measbpmresp('MinimumBeamCurrent', 32.1)
                             will pause at a beam current of 32.1 and prompt for a refill.
  17. Optional inputs when computing model response matrices:
      'FixedPathLength' or 'FixedMomentum' - hold the path length or momentum fixed  {Default: 'FixedPathLength'}
      'Full' or 'Linear' - use full nonlinear model or linear approximation (faster) {Default: 'Linear'}
      Note: The ModulationMethod input (7) is also used for the model calculation.
  OUTPUTS
  1. R = Orbit response matrix (delta(orbit)/delta(Kick))
     Numeric Output:
       R = [xx xy
            yx yy]
     Stucture Output:
     R(BPM Plane, Corrector Plane) - 2x2 struct array
     R(1,1).Data=xx;  % Kick x, look x
     R(2,1).Data=yx;  % Kick x, look y
     R(1,2).Data=xy;  % Kick y, look x
     R(2,2).Data=yy;  % Kick y, look y
     R(Monitor, Actuator).Data - Response matrix
                         .Monitor  - BPM data structure (starting orbit)
                         .Monitor1 - BPM matrix (first  data point)
                         .Monitor2 - BPM matrix (second data point)
                         .Actuator - Corrector data structure
                         .ActuatorDelta - Corrector kick vector
                         .GeV - Electron beam energy
                         .ModulationMethod - 'unipolar' or 'bipolar'
                         .WaitFlag - Wait flag used when acquiring data
                         .ExtraDelay - Extra time delay
                         .TimeStamp
                         .CreatedBy
                         .DCCT
  2. FileName = File name (including directory) where the data was saved (if applicable)
                (a machine configuration structure is saved in the data file as well)
  NOTES
  1. [] can be used on any input to obtain the default setting.
     However, most inputs can be left out altogether to get the default.
  2. For Mode = 'Model':
     a. AT family names (or 'All') can be used and DeviceList is ignored
     b. There is a lot of flexibility for getting response matrices, for instance,
        R = measbpmresp('QF', 'QD', 'HCM', 'VCM', 'Model', 'Physics');
        is the response matrix from the correctors to orbit at the sextupoles.
        The units when using nonstandard families for BPMs is always 'physics', meter/radian.
  3. Cell inputs are not allowed.
  4. BPM roll and crunch and corrector magnet roll errors are included only if they are
     in the AT model (field .GCR for BPMs and .Roll for correctors).
     BPM and corrector magnet gains are included in hardware units (not physics units).
  5. This function measures response matrices from 2 BPM families to 2 corrector families.
     If only one family is needed then use measrespmat.
  EXAMPLES
  1. Default:
       R = measbpmresp;
       is the same as,
       R = measbpmresp(gethbpmfamily, getvbpmfamily, gethcmfamily, getvcmfamily, 'Online', 'Bipolar', 'Numeric', 'Archive');
  2. Default using the model:
       R = measbpmresp('Model');
       is the same as,
       R = measbpmresp(gethbpmfamily, getvbpmfamily, gethcmfamily, getvcmfamily, 'Model', 'Bipolar', 'Numeric', 'NoArchive', 'FixedPathLength', 'Linear');
  3. Compare measured (or Default) and model BPM response
     Rmeas  = getbpmresp;
     Rmodel = measbpmresp('Model');
     subplot(2,1,1);
     surf(Rmeas);  title('Default BPM Response'); xlabel('BPM #'); ylabel('CM #'); zlabel('[mm/amp]');
     subplot(2,1,2);
     surf(Rmeas-Rmodel);  title('Default - Model BPM Response'); xlabel('BPM #'); ylabel('CM #'); zlabel('[mm/amp]');
  See also getbpmresp, measrespmat, meastuneresp, measchroresp
CROSS-REFERENCE INFORMATION
This function calls:
family2dev FAMILY2DEV - Return the device list for a family
getam GETAM - Gets monitor channels
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
gethbpmfamily GETHBPMFAMILY - Return the default horizontal BPM family
gethcmfamily GETHCMFAMILY - Returns the default horizontal corrector family
getmachineconfig GETMACHINECONFIG - Returns or saves to file the present storage ring setpoints and monitors
getrf GETRF - Gets the RF frequency
getsp GETSP - Gets setpoint channels
getspos GETSPOS - Returns the longitudinal position in meters
getvbpmfamily GETVBPMFAMILY - Return the default vertical BPM family
getvcmfamily GETVCMFAMILY - Returns the default vertical corrector family
hw2physics HW2PHYSICS - Converts from 'Hardware' units to 'Physics' units
isfamily ISFAMILY - True for family names
ismemberof ISMEMBEROF - Returns turn if the membership information of a family (cell of strings)
isstoragering ISSTORAGERING - Is this a storage ring?
istransport ISTRANSPORT - Is this a transport line?
measrespmat MEASRESPMAT - Measure a response matrix
physics2hw PHYSICS2HW - Converts from 'Physics' units to 'Hardware' units
This function is called by:
bpmresp2loco BPMRESP2LOCO - Convert a MML response matrix to LOCO units
buildopsdatafiles BUILDOPSDATAFILES - Builds the files for the OpsData directory from the model
getbpmresp GETBPMRESP - Returns the BPM response matrix in the horizontal and vertical planes
measlocodata MEASLOCODATA - Measures a set of LOCO data
orbitcorrectionmethods ORBITCORRECTIONMETHODS - Some the orbit correction methods used on light sources
plotbpmresp PLOTBPMRESP - Plots the orbit response matrix in various ways
SOURCE CODE
function [Rmat, OutputFileName] = measbpmresp(varargin)
%MEASBPMRESP - Measures the BPM response matrix in the horizontal and vertical planes
%
%  For family name, device list inputs:
%  [R, FileName] = measbpmresp(BPMxFamily, BPMxList, BPMyFamily, BPMyList, HCMFamily, HCMList, VCMFamily, VCMList, HCMKicks, VCMKicks, ModulationMethod, WaitFlag, FileName, DirectoryName, ExtraDelay)
%
%  For data structure inputs:
%  [R, FileName] = measbpmresp(BPMxStruct, BPMyStruct, HCMStruct, VCMStruct, HCMKicks, VCMKicks, ModulationMethod, WaitFlag, FileName, DirectoryName, ExtraDelay)
%
%  INPUTS
%  1. BPMxFamily       - BPMx family name {Default: gethbpmfamily}
%     BPMxDeviceList   - BPMx device list {Default: all devices with good status}
%     or
%     BPMxStruct can replace BPMxFamily and BPMxList
%
%  2. BPMyFamily       - BPMy family name {Default: getvbpmfamily}
%     BPMyDeviceList   - BPMy device list {Default: all devices with good status}
%     or
%     BPMyStruct can replace BPMyFamily and BPMyList
%
%  3. HCMFamily       - HCM family name {Default: gethcmfamily}
%     HCMDeviceList   - HCM device list {Default: all devices with good status}
%     or
%     HCMStruct can replace HCMFamily and HCMList
%
%  4. VCMFamily       - VCM family name {Default: getvcmfamily}
%     VCMDeviceList   - VCM device list {Default: all devices with good status}
%     or
%     VCMStruct can replace VCMFamily and VCMList
%
%  5. HCMKicks - Change in HCM correctors {Default: getfamilydata(HCMFamily,'Setpoint','DeltaRespMat',HCMDeviceList), then .05 mrad}
%  6. VCMKicks - Change in VCM correctors {Default: getfamilydata(VCMFamily,'Setpoint','DeltaRespMat',VCMDeviceList), then .05 mrad}
%
%  7. ModulationMethod - Method for changing the ActuatorFamily
%                       'bipolar' changes the ActuatorFamily by +/- ActuatorDelta/2 on each step {Default}
%                       'unipolar' changes the ActuatorFamily from 0 to ActuatorDelta on each step
%
%  8. WaitFlag - (see setpv for WaitFlag definitions) {Default: []}
%                WaitFlag = -5 will override gets to manual mode
%
%  9. Optional input to change the default filename and directory
%     FileName - Filename for the response matrix data
%                (Empty prompts for a filename)
%     DirectoryName - Directory name to store the response matrix data file
%     Note: a. FileName can include the path if DirectoryName is not used
%           b. For model response matrices, FileName must exist for a file save
%           c. The 'Achive' flag is another way to input the filename
%
%  10. ExtraDelay - extra time delay [seconds] after a setpoint change
%
%  11. 'Struct'  - Output will be a response matrix structure {Default for     data structure inputs}
%      'Numeric' - Output will be a numeric matrix            {Default for non-data structure inputs}
%
%  12. Optional override of the units:
%      'Physics'  - Use physics  units
%      'Hardware' - Use hardware units
%
%  13. Optional override of the mode:
%      'Online'    - Set/Get data online
%      'Model'     - Set/Get data directly from AT (uses locoresponsematrix)
%      'Simulator' - Set/Get data on the simulated accelerator using AT (ie, same commands as 'Online')
%      'Manual'    - Set/Get data manually
%
%  14. 'Display'   - Prints status information to the command window {Default}
%      'NoDisplay' - Nothing is printed to the command window
%
%  15. 'NoArchive' - No file archive
%      'Archive'   - Save the response matrix data to \<Directory.BPMResponse>\<BPMRespFile><Date><Time>.mat
%                    To change the filename, included the filename after the 'Archive', '' to browse
%
%  16. 'MinimumBeamCurrent' - Minimum beam current before prompting for a refill
%                             The current (as returned by getdcct) must follow the flag.
%                             measbpmresp('MinimumBeamCurrent', 32.1)
%                             will pause at a beam current of 32.1 and prompt for a refill.
%
%  17. Optional inputs when computing model response matrices:
%      'FixedPathLength' or 'FixedMomentum' - hold the path length or momentum fixed  {Default: 'FixedPathLength'}
%      'Full' or 'Linear' - use full nonlinear model or linear approximation (faster) {Default: 'Linear'}
%      Note: The ModulationMethod input (7) is also used for the model calculation.
%
%  OUTPUTS
%  1. R = Orbit response matrix (delta(orbit)/delta(Kick))
%
%     Numeric Output:
%       R = [xx xy
%            yx yy]
%
%     Stucture Output:
%     R(BPM Plane, Corrector Plane) - 2x2 struct array
%     R(1,1).Data=xx;  % Kick x, look x
%     R(2,1).Data=yx;  % Kick x, look y
%     R(1,2).Data=xy;  % Kick y, look x
%     R(2,2).Data=yy;  % Kick y, look y
%
%     R(Monitor, Actuator).Data - Response matrix
%                         .Monitor  - BPM data structure (starting orbit)
%                         .Monitor1 - BPM matrix (first  data point)
%                         .Monitor2 - BPM matrix (second data point)
%                         .Actuator - Corrector data structure
%                         .ActuatorDelta - Corrector kick vector
%                         .GeV - Electron beam energy
%                         .ModulationMethod - 'unipolar' or 'bipolar'
%                         .WaitFlag - Wait flag used when acquiring data
%                         .ExtraDelay - Extra time delay
%                         .TimeStamp
%                         .CreatedBy
%                         .DCCT
%
%  2. FileName = File name (including directory) where the data was saved (if applicable)
%                (a machine configuration structure is saved in the data file as well)
%
%  NOTES
%  1. [] can be used on any input to obtain the default setting.
%     However, most inputs can be left out altogether to get the default.
%  2. For Mode = 'Model':
%     a. AT family names (or 'All') can be used and DeviceList is ignored
%     b. There is a lot of flexibility for getting response matrices, for instance,
%        R = measbpmresp('QF', 'QD', 'HCM', 'VCM', 'Model', 'Physics');
%        is the response matrix from the correctors to orbit at the sextupoles.
%        The units when using nonstandard families for BPMs is always 'physics', meter/radian.
%  3. Cell inputs are not allowed.
%  4. BPM roll and crunch and corrector magnet roll errors are included only if they are
%     in the AT model (field .GCR for BPMs and .Roll for correctors).
%     BPM and corrector magnet gains are included in hardware units (not physics units).
%  5. This function measures response matrices from 2 BPM families to 2 corrector families.
%     If only one family is needed then use measrespmat.
%
%  EXAMPLES
%  1. Default:
%       R = measbpmresp;
%       is the same as,
%       R = measbpmresp(gethbpmfamily, getvbpmfamily, gethcmfamily, getvcmfamily, 'Online', 'Bipolar', 'Numeric', 'Archive');
%
%  2. Default using the model:
%       R = measbpmresp('Model');
%       is the same as,
%       R = measbpmresp(gethbpmfamily, getvbpmfamily, gethcmfamily, getvcmfamily, 'Model', 'Bipolar', 'Numeric', 'NoArchive', 'FixedPathLength', 'Linear');
%
%  3. Compare measured (or Default) and model BPM response
%     Rmeas  = getbpmresp;
%     Rmodel = measbpmresp('Model');
%     subplot(2,1,1);
%     surf(Rmeas);  title('Default BPM Response'); xlabel('BPM #'); ylabel('CM #'); zlabel('[mm/amp]');
%     subplot(2,1,2);
%     surf(Rmeas-Rmodel);  title('Default - Model BPM Response'); xlabel('BPM #'); ylabel('CM #'); zlabel('[mm/amp]');
%
%  See also getbpmresp, measrespmat, meastuneresp, measchroresp
%  Written by Greg Portmann
% Initialize defaults
BPMxFamily = gethbpmfamily;
BPMxList = [];
BPMyFamily = getvbpmfamily;
BPMyList = [];
HCMFamily = gethcmfamily;
HCMList = [];
HCMKicks = [];
Default2HCMKick = .05e-3;  % Radians, if getfamilydata(HCMFamily,'Setpoint','DeltaRespMat') is empty
VCMFamily = getvcmfamily;
VCMList = [];
VCMKicks = [];
Default2VCMKick = .05e-3;  % Radians, if getfamilydata(VCMFamily,'Setpoint','DeltaRespMat') is empty
ModulationMethod = 'bipolar';
% Map MML to LOCO naming
if strcmpi(ModulationMethod, 'bipolar')
    LOCORespFlags.ResponseMatrixMeasurement = 'Bidirectional';   % 'oneway'' or ''bidirectional'
else
    LOCORespFlags.DispersionMeasurement     = 'Bidirectional';
end
if isstoragering
    LOCORespFlags.ResponseMatrixCalculator  = 'Linear';
    LOCORespFlags.ClosedOrbitType           = 'fixedpathlength';
    LOCORespFlags.MachineType               = 'StorageRing';
else
    % Full is usually as fast as Linear for transport lines
    LOCORespFlags.ResponseMatrixCalculator  = 'full';
    LOCORespFlags.ClosedOrbitType           = 'fixedmomentum';
    LOCORespFlags.MachineType               = 'Transport';
end
WaitFlag = -2;
ExtraDelay = 0;
StructOutputFlag = 0;
NumericOutputFlag = 0;
DisplayFlag = -1;
ArchiveFlag = -1;
FileName = -1;
DirectoryName = '';
ModeFlag = '';  % model, online, manual, or '' for default mode
UnitsFlag = ''; % hardware, physics, or '' for default units
InputFlags = {};
DCCTFlag = {};
for i = length(varargin):-1:1
    if isstruct(varargin{i})
        % Ignor structures
    elseif iscell(varargin{i})
        % Ignor cells
    elseif strcmpi(varargin{i},'Struct')
        StructOutputFlag = 1;
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Numeric')
        StructOutputFlag = 0;
        NumericOutputFlag = 1;
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Model')
        ModeFlag = varargin{i};
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Simulator')
        ModeFlag = varargin{i};
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Online')
        ModeFlag = varargin{i};
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Manual')
        ModeFlag = varargin{i};
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Physics')
        UnitsFlag = varargin{i};
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Hardware')
        UnitsFlag = varargin{i};
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Archive')
        ArchiveFlag = 1;
        if length(varargin) > i
            % Look for a filename as the next input
            if ischar(varargin{i+1})
                FileName = varargin{i+1};
                varargin(i+1) = [];
            end
        end
        varargin(i) = [];
    elseif strcmpi(varargin{i},'NoArchive')
        ArchiveFlag = 0;
        varargin(i) = [];
    elseif strcmpi(varargin{i},'NoDisplay')
        DisplayFlag = 0;
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Display')
        DisplayFlag = 1;
        InputFlags = [InputFlags varargin(i)];
        varargin(i) = [];
    elseif strcmpi(varargin{i},'unipolar') || strcmpi(varargin{i},'oneway')
        ModulationMethod = 'unipolar';
        LOCORespFlags.ResponseMatrixMeasurement = 'oneway';
        varargin(i) = [];
    elseif strcmpi(varargin{i},'bipolar') || strcmpi(varargin{i},'bidirectional')
        ModulationMethod = 'bipolar';
        LOCORespFlags.ResponseMatrixMeasurement = 'bidirectional';
        varargin(i) = [];
    elseif strcmpi(varargin{i},'FixedPathLength')
        LOCORespFlags.ClosedOrbitType = 'FixedPathLength';
        varargin(i) = [];
    elseif strcmpi(varargin{i},'FixedMomentum')
        LOCORespFlags.ClosedOrbitType = 'FixedMomentum';
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Linear')
        LOCORespFlags.ResponseMatrixCalculator = 'Linear';
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Full')
        LOCORespFlags.ResponseMatrixCalculator = 'Full';
        varargin(i) = [];
    elseif strcmpi(varargin{i},'MinimumBeamCurrent')
        DCCTFlag = [varargin(i) varargin(i+1)];
        varargin(i+1) = [];
        varargin(i)   = [];
    end
end
%%%%%%%%%%%%%%%%
% Parse Inputs %
%%%%%%%%%%%%%%%%
% Look for BPMx family info
if length(varargin) >= 1
    if isstruct(varargin{1})
        BPMxFamily = varargin{1}.FamilyName;
        BPMxList = varargin{1}.DeviceList;
        % For structure inputs, units are determined by the first input
        if isempty(UnitsFlag)
            UnitsFlag = varargin{1}.Units;
        end
        varargin(1) = [];
        % Only change StructOutputFlag if 'Numeric' is not on the input line
        if ~NumericOutputFlag
            StructOutputFlag = 1;
        end
    elseif ischar(varargin{1})
        BPMxFamily = varargin{1};
        varargin(1) = [];
        if length(varargin) >= 1
            if isnumeric(varargin{1})
                BPMxList = varargin{1};
                varargin(1) = [];
            end
        end
    elseif isnumeric(varargin{1})
        BPMxList = varargin{1};
        varargin(1) = [];
    end
end
if isempty(BPMxList)
    BPMxList = family2dev(BPMxFamily, 1);
end
% Look for BPMy family info
if length(varargin) >= 1
    if isstruct(varargin{1})
        BPMyFamily = varargin{1}.FamilyName;
        BPMyList = varargin{1}.DeviceList;
        varargin(1) = [];
        if ~NumericOutputFlag
            StructOutputFlag = 1; % Only change StructOutputFlag if 'Numeric' is not on the input line
        end
    elseif ischar(varargin{1})
        BPMyFamily = varargin{1};
        varargin(1) = [];
        if length(varargin) >= 1
            if isnumeric(varargin{1})
                BPMyList = varargin{1};
                varargin(1) = [];
            end
        end
    elseif isnumeric(varargin{1})
        BPMyList = varargin{1};
        varargin(1) = [];
    end
end
if isempty(BPMyList)
    BPMyList = family2dev(BPMyFamily, 1);
end
% Look for HCM family info
if length(varargin) >= 1
    if isstruct(varargin{1})
        HCMFamily = varargin{1}.FamilyName;
        HCMList = varargin{1}.DeviceList;
        varargin(1) = [];
        if ~NumericOutputFlag
            StructOutputFlag = 1; % Only change StructOutputFlag if 'Numeric' is not on the input line
        end
    elseif ischar(varargin{1})
        HCMFamily = varargin{1};
        varargin(1) = [];
        if length(varargin) >= 1
            if isnumeric(varargin{1})
                HCMList = varargin{1};
                varargin(1) = [];
            end
        end
    elseif isnumeric(varargin{1})
        HCMList = varargin{1};
        varargin(1) = [];
    end
end
if isempty(HCMList)
    HCMList = family2dev(HCMFamily, 1);
end
% Look for VCM family info
if length(varargin) >= 1
    if isstruct(varargin{1})
        VCMFamily = varargin{1}.FamilyName;
        VCMList = varargin{1}.DeviceList;
        varargin(1) = [];
        if ~NumericOutputFlag
            StructOutputFlag = 1; % Only change StructOutputFlag if 'Numeric' is not on the input line
        end
    elseif ischar(varargin{1})
        VCMFamily = varargin{1};
        varargin(1) = [];
        if length(varargin) >= 1
            if isnumeric(varargin{1})
                VCMList = varargin{1};
                varargin(1) = [];
            end
        end
    elseif isnumeric(varargin{1})
        VCMList = varargin{1};
        varargin(1) = [];
    end
end
if isempty(VCMList)
    VCMList = family2dev(VCMFamily, 1);
end
% Look for HCMKicks
if length(varargin) >= 1
    if isempty(varargin{1})
        % Use default
        varargin(1) = [];
    elseif isnumeric(varargin{1})
        HCMKicks = varargin{1};
        varargin(1) = [];
    end
end
% Look for VCMKicks
if length(varargin) >= 1
    if isempty(varargin{1})
        % Use default
        varargin(1) = [];
    elseif isnumeric(varargin{1})
        VCMKicks = varargin{1};
        varargin(1) = [];
    end
end
% ModulationMethod has already been searched for
% % Look for ModulationMethod
% if length(varargin) >= 1
%     if isempty(varargin{1})
%         % Use default
%         varargin(1) = [];
%     end
%     if ischar(varargin{1})
%         ModulationMethod = varargin{1};
%         varargin(1) = [];
%     end
% end
if ~strcmpi(ModulationMethod, 'unipolar') && ~strcmpi(ModulationMethod, 'bipolar')
    error('ModulationMethod must be ''unipolar'' or ''bipolar''');
end
% Look for WaitFlag
if length(varargin) >= 1
    if isempty(varargin{1})
        % Use default
        varargin(1) = [];
    end
    if isnumeric(varargin{1})
        WaitFlag = varargin{1};
        varargin(1) = [];
    end
end
% FileName and DirectoryName
if length(varargin) >= 1
    if isempty(varargin{1})
        % Use default
        FileName = '';
        varargin(1) = [];
    end
    if ischar(varargin{1})
        FileName = varargin{1};
        varargin(1) = [];
    end
end
if length(varargin) >= 1
    if isempty(varargin{1})
        % Use default
        DirectoryName = getfamilydata('Directory', 'BPMResponse');
        FileName = [DirectoryName, FileName];
        varargin(1) = [];
    elseif ischar(varargin{1})
        DirectoryName = varargin{1};
        if strcmp(DirectoryName, filesep)
            FileName = [DirectoryName, FileName];
        else
            FileName = [DirectoryName, filesep, FileName];
        end
        varargin(1) = [];
    end
end
% Look for ExtraDelay
if length(varargin) >= 1
    if isempty(varargin{1})
        % Use default
        varargin(1) = [];
    end
    if isnumeric(varargin{1})
        ExtraDelay = varargin{1};
        varargin(1) = [];
    end
end
% Check units
if isempty(UnitsFlag)
    if strcmpi(getfamilydata(BPMxFamily,'Monitor','Units'), getfamilydata(BPMyFamily,'Monitor','Units'))
        UnitsFlag = getfamilydata(BPMxFamily,'Monitor','Units');
    else
        error('Mixed Units for orbits');
    end
end
if isempty(UnitsFlag)
    error('Unknown Units');
end
% Check mode
if isempty(ModeFlag)
    if strcmpi(getfamilydata(BPMxFamily,'Monitor','Mode'), getfamilydata(BPMyFamily,'Monitor','Mode'))
        %ModeFlag = getfamilydata(BPMxFamily,'Monitor','Mode');
    else
        error('Mixed Mode for orbits');
    end
    if strcmpi(getfamilydata(HCMFamily,'Monitor','Mode'), getfamilydata(VCMFamily,'Monitor','Mode'))
        ModeFlag = getfamilydata(HCMFamily,'Monitor','Mode');
    else
        error('Mixed Mode for correctors');
    end
end
if isempty(ModeFlag)
    error('Unknown Mode');
end
% Input parsing complete
% Starting time
TimeStart = gettime;
% Change defaults for the model (note: simulator mode mimics online)
if strcmpi(ModeFlag,'Model')
    % Only archive data if ArchiveFlag==1 or FileName~=[]
    if ischar(FileName) || ArchiveFlag == 1
        ArchiveFlag = 1;
    else
        ArchiveFlag = 0;
    end
    % Only display is it was turned on at the command line
    if DisplayFlag == 1
        % Keep DisplayFlag = 1
    else
        DisplayFlag = 0;
    end
else
    % Online or Simulator: Archive unless ArchiveFlag was forced to zero
    if ArchiveFlag ~= 0
        ArchiveFlag = 1;
        if FileName == -1
            FileName = '';
        end
    end
end
% % Print setup information
% if DisplayFlag
%     if ~strcmpi(ModeFlag,'Model')
%         fprintf('\n');
%         fprintf('   MEASBPMRESP measures the BPM response matrix for both HCM & VCM corrector families.\n');
%         fprintf('   The storage ring lattice and hardware should be setup for accurate orbit measurements.\n');
%         fprintf('   Make sure the following information is correct:\n');
%         fprintf('   1.  Proper magnet lattice\n');
%         fprintf('   2.  Proper electron beam energy\n');
%         fprintf('   3.  Proper electron bunch pattern\n');
%         fprintf('   4.  BPMs are functioning properly (calibrated, sample rate, etc.)\n');
%         fprintf('   5.  Corrector magnets are working\n');
%         fprintf('   6.  The injection bump magnets off\n');
%         fprintf('   7.  Corrector Settle Time WaitFlag=%f, Extra BPM Delay=%f\n', WaitFlag, ExtraDelay);
%         fprintf('   9.  Modulation Method: %s\n', ModulationMethod);
%     end
% end
if ArchiveFlag
    if isempty(FileName)
        FileName = appendtimestamp(getfamilydata('Default', 'BPMRespFile'));
        DirectoryName = getfamilydata('Directory', 'BPMResponse');
        if isempty(DirectoryName)
            DirectoryName = [getfamilydata('Directory','DataRoot'), 'Response', filesep, 'BPM', filesep];
        else
            % Make sure default directory exists
            DirStart = pwd;
            [DirectoryName, ErrorFlag] = gotodirectory(DirectoryName);
            cd(DirStart);
        end
        [FileName, DirectoryName] = uiputfile('*.mat', 'Select a BPM Response File ("Save" starts measurement)', [DirectoryName FileName]);
        drawnow;
        if FileName == 0
            ArchiveFlag = 0;
            disp('   BPM response measurement canceled.');
            Rmat = []; OutputFileName='';
            return
        end
        FileName = [DirectoryName, FileName];
    elseif FileName == -1
        FileName = appendtimestamp(getfamilydata('Default', 'BPMRespFile'));
        DirectoryName = getfamilydata('Directory', 'BPMResponse');
        if isempty(DirectoryName)
            DirectoryName = [getfamilydata('Directory','DataRoot'), 'Response', filesep, 'BPM', filesep];
        end
        FileName = [DirectoryName, FileName];
    end
    % Acquire initial data
    MachineConfig = getmachineconfig(InputFlags{:});
end
% Get the response matrices
if strcmpi(ModeFlag,'Model')
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Model Response Matrix - Use LOCO Method %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Just to make sure the proper AT model is the currrent model, do a get on one of the correctors
    % (This is needed because locoresponsematrix does not check the .AT.ATModel field)
    if isfamily(HCMFamily)
        tmp = getsp(HCMFamily, HCMList, 'Model');
    end
    % % Mask bpms and correctors for status
    % BPMxStatus = getfamilydata(BPMxFamily,'Status', BPMxList);
    % BPMxGoodIndex = find(BPMxStatus);
    % BPMxList = BPMxList(BPMxGoodIndex,:);
    %
    % BPMyStatus = getfamilydata(BPMyFamily,'Status', BPMyList);
    % BPMyGoodIndex = find(BPMyStatus);
    % BPMyList = BPMyList(BPMyGoodIndex,:);
    %
    % HCMStatus = getfamilydata(HCMFamily,'Status', HCMList);
    % HCMGoodIndex = find(HCMStatus);
    % HCMList = HCMList(HCMGoodIndex,:);
    % HCMKicks = HCMKicks(HCMGoodIndex);
    %
    % VCMStatus = getfamilydata(VCMFamily,'Status', VCMList);
    % VCMGoodIndex = find(VCMStatus);
    % VCMList = VCMList(VCMGoodIndex,:);
    % VCMKicks = VCMKicks(VCMGoodIndex);
    % Use AT (LOCO method)
    % 1. AT MODEL
    global THERING
    %setcavity off;
    RINGData.Lattice = THERING;
    iCavity = findcells(THERING, 'Frequency');
    if isempty(iCavity)
        if isstoragering
            RINGData.CavityFrequency  = getrf('Model', 'Physics');
            RINGData.CavityHarmNumber = getfamilydata('HarmonicNumber');
        else
            RINGData.CavityFrequency  = [];
            RINGData.CavityHarmNumber = [];
        end
    else
        RINGData.CavityFrequency  = THERING{iCavity(1)}.Frequency;
        RINGData.CavityHarmNumber = THERING{iCavity(1)}.HarmNumber;
    end
    % 2. BPM STRUCTURE
    % FamName and BPMIndex tells the findorbitrespm function which BPMs are needed in the response matrix
    % HBPMIndex/VBPMIndex is the sub-index of BPMIndex which correspond to the measured response matrix
    if strcmpi(BPMxFamily,'All')
        BPMxATIndex = 1:length(THERING);
    elseif isfamily(BPMxFamily)
        BPMxATIndex = family2atindex(BPMxFamily, BPMxList);
    else
        BPMxATIndex = findcells(THERING, 'FamName', BPMxFamily);
    end
    if isempty(BPMxATIndex)
        error(sprintf('BPMxFamily=%s could not be found in the AO or AT deck', BPMxFamily));
    else
        BPMxATIndex = BPMxATIndex(:)';    % Row vector
    end
    if strcmpi(BPMyFamily,'All')
        BPMyATIndex = 1:length(THERING);
    elseif isfamily(BPMyFamily)
        BPMyATIndex = family2atindex(BPMyFamily, BPMyList);
    else
        BPMyATIndex = findcells(THERING, 'FamName', BPMyFamily);
    end
    if isempty(BPMyATIndex)
        error(sprintf('BPMyFamily=%s could not be found in the AO or AT deck', BPMyFamily));
    else
        BPMyATIndex = BPMyATIndex(:)';    % Row vector
    end
    BPMData.BPMIndex = unique([BPMxATIndex BPMyATIndex]);
    BPMData.HBPMIndex = findrowindex(BPMxATIndex', BPMData.BPMIndex');  % Only used after locoresponsematrix is called
    BPMData.VBPMIndex = findrowindex(BPMyATIndex', BPMData.BPMIndex');  % Only used after locoresponsematrix is called
    % 3. CORRECTOR MAGNET STRUCTURE
    % FamName and HCMIndex/VCMIndex tells the findorbitrespm function which corrector magnets are in the response matrix
    % CMData.HCMKicks = starting value for the horizontal kicks in milliradian
    % CMData.VCMKicks = starting value for the vertical   kicks in milliradian
    % CMData.HCMCoupling = starting value for the horizontal coupling (default: zeros)
    % CMData.VCMCoupling = starting value for the vertical   coupling (default: zeros)
    % Note:  The kick strength should match the measured response matrix as best as possible
    % Note:  The kicks and Coupling are used all the time (fit or not!)
    % Note the different units between AT and LOCO
    if strcmpi(HCMFamily,'All')
        ATIndex = 1:length(THERING);
    elseif isfamily(HCMFamily)
        ATIndex = family2atindex(HCMFamily, HCMList);
    else
        ATIndex = findcells(THERING, 'FamName', HCMFamily);
    end
    if isempty(ATIndex)
        error(sprintf('HCMFamily=%s could not be found in the middle layer or AT model', HCMFamily));
    else
        ATIndex = ATIndex(:)';    % Row vector
    end
    CMData.HCMIndex = ATIndex;
    if strcmpi(VCMFamily,'All')
        ATIndex = 1:length(THERING);
    elseif isfamily(VCMFamily)
        ATIndex = family2atindex(VCMFamily, VCMList);
    else
        ATIndex = findcells(THERING, 'FamName', VCMFamily);
    end
    if isempty(ATIndex)
        error(sprintf('VCMFamily=%s could not be found in the middle layer or AT model', VCMFamily));
    else
        ATIndex = ATIndex(:)';    % Row vector
    end
    CMData.VCMIndex = ATIndex;
    % Kicks must be in Physics units
    % Default kicks
    if ismemberof(HCMFamily,'COR')
        if isempty(HCMKicks)
            HCMKicks = getfamilydata(HCMFamily, 'Setpoint', 'DeltaRespMat', HCMList);
            if isempty(HCMKicks)
                CMData.HCMKicks = Default2HCMKick;
            else
                %if strcmpi(getfamilydata(HCMFamily, 'Setpoint', 'Units'), 'Hardware')
                    HCMsp = getsp(HCMFamily, HCMList, 'Numeric', ModeFlag, 'Hardware');
                    CMData.HCMKicks = hw2physics(HCMFamily, 'Setpoint', HCMsp+HCMKicks, HCMList) - hw2physics(HCMFamily, 'Setpoint', HCMsp, HCMList);
                %else
                %    CMData.HCMKicks = HCMKicks;
                %end
            end
        else
            if strcmpi(UnitsFlag, 'Hardware')
                % Change to AT units [radian]
                HCMsp = getsp(HCMFamily, HCMList, 'Numeric', ModeFlag, 'Hardware');
                CMData.HCMKicks = hw2physics(HCMFamily, 'Setpoint', HCMsp+HCMKicks, HCMList) - hw2physics(HCMFamily, 'Setpoint', HCMsp, HCMList);
            else
                CMData.HCMKicks = HCMKicks;
            end
        end
    else
        % Not a corrector magnet location
        if isempty(HCMKicks)
            CMData.HCMKicks = Default2HCMKick;
        else
            % The kick must be in physics units
            if strcmpi(UnitsFlag, 'Hardware')
                fprintf('\n   You are using a non-corrector magnet actuator type and using hardware units.\n');
                fprintf('   Unknown conversion method from hardware to physics.\n\n');
                fprintf('   Change to a physics units input scheme.\n');
                error('Hardware to physics conversion error');
            else
                CMData.HCMKicks = HCMKicks;
            end
        end
    end
    if ismemberof(VCMFamily,'COR')
        if isempty(VCMKicks)
            VCMKicks = getfamilydata(VCMFamily, 'Setpoint', 'DeltaRespMat', VCMList);
            if isempty(VCMKicks)
                CMData.VCMKicks = Default2VCMKick;
            else
                %if strcmpi(getfamilydata(VCMFamily, 'Setpoint', 'Units'), 'Hardware')
                    VCMsp = getsp(VCMFamily, VCMList, 'Numeric', ModeFlag, 'Hardware');
                    CMData.VCMKicks = hw2physics(VCMFamily, 'Setpoint', VCMsp+VCMKicks, VCMList) - hw2physics(VCMFamily, 'Setpoint', VCMsp, VCMList);
                %else
                %    CMData.VCMKicks = VCMKicks;
                %end
            end
        else
            if strcmpi(UnitsFlag, 'Hardware')
                % Change to AT units [radian]
                VCMsp = getsp(VCMFamily, VCMList, 'Numeric', ModeFlag, 'Hardware');
                CMData.VCMKicks = hw2physics(VCMFamily, 'Setpoint', VCMsp+VCMKicks, VCMList) - hw2physics(VCMFamily, 'Setpoint', VCMsp, VCMList);
            else
                CMData.VCMKicks = VCMKicks;
            end
        end
    else
        % Not a corrector magnet location
        if isempty(VCMKicks)
            CMData.VCMKicks = Default2VCMKick;
        else
            % The kick must be in physics units
            if strcmpi(UnitsFlag, 'Hardware')
                fprintf('\n   You are using a non-corrector magnet actuator type and using hardware units.\n');
                fprintf('   Unknown conversion method from hardware to physics!\n\n');
                fprintf('   Change to a physics units input scheme.\n');
                error('Hardware to physics conversion error');
            else
                CMData.VCMKicks = VCMKicks;
            end
        end
    end
    CMData.HCMKicks = CMData.HCMKicks(:);
    if length(CMData.HCMKicks) == 1
        CMData.HCMKicks = CMData.HCMKicks * ones(length(CMData.HCMIndex),1);
    end
    CMData.VCMKicks = CMData.VCMKicks(:);
    if length(CMData.VCMKicks) == 1
        CMData.VCMKicks = CMData.VCMKicks * ones(length(CMData.VCMIndex),1);
    end
    % Corrector gain error have been taken into account by hw2physics
    % If the model has corrector rolls, adjust the kicks now.
    for i = 1:length(CMData.HCMIndex)
        if isfield(THERING{CMData.HCMIndex(i)}, 'Roll')
            Roll = THERING{CMData.HCMIndex(i)}.Roll;
        else
            Roll = [0 0];  % [Rollx Rolly]
        end
        HCMRoll(i,1) = Roll(1);
    end
    %HCMRoll = getroll(HCMFamily, HCMList);
    for i = 1:length(CMData.VCMIndex)
        if isfield(THERING{CMData.VCMIndex(i)}, 'Roll')
            Roll = THERING{CMData.VCMIndex(i)}.Roll;
        else
            Roll = [0 0];  % [Rollx Rolly]
        end
        VCMRoll(i,1) = Roll(2);
    end
    %VCMRoll = getroll(VCMFamily, VCMList);
    % The kicks need to be adjusted for roll (model coordinates)
    HCMKicks = CMData.HCMKicks;
    VCMKicks = CMData.VCMKicks;
    CMData.HCMKicks = CMData.HCMKicks .* cos(HCMRoll);
    CMData.VCMKicks = CMData.VCMKicks .* cos(VCMRoll);
    % Coupling term (convert from ML to LOCO coordinates)
    % The ./cos term is needed because LOCO coupling is scaling the unrolled kick
    CMData.HCMCoupling =  sin(HCMRoll) ./ cos(HCMRoll);
    CMData.VCMCoupling = -sin(VCMRoll) ./ cos(VCMRoll);
    % Generate a response matrix ('FixedPathLength' or 'FixedMomentum', 'Linear' or 'Full')
    % Flags is empty then the locoresponsematrix defaults are used (which was fix path length, linear the last time I checked)
    R0 = locoresponsematrix(RINGData, BPMData, CMData, LOCORespFlags);
    % Coupling correction
    % Convert the ML gain/rolls to LOCO gain/coupling
    % for i = 1:length(BPMData.BPMIndex)
    %     if isfield(THERING{BPMData.BPMIndex(i)}, 'GCR')
    %         GCR = THERING{BPMData.BPMIndex(i)}.GCR;
    %     else
    %         GCR = [1 1 0 0];  % [Gx Gy Crunch Roll]
    %     end
    %
    %     M = gcr2loco(GCR(1), GCR(2), GCR(3), GCR(4));
    %     BPMxGainLOCO(i,1)     = M(1,1);
    %     BPMxCouplingLOCO(i,1) = M(1,2);
    %     BPMyGainLOCO(i,1)     = M(2,2);
    %     BPMyCouplingLOCO(i,1) = M(2,1);
    % end
    %
    %
    % % Build a rotation matrix
    % C = [diag(BPMxGainLOCO)      diag(BPMxCouplingLOCO)
    %      diag(BPMyCouplingLOCO)  diag(BPMyGainLOCO)];
    % BPM coupling correction (only roll, crunch correction, gain is done in physics2hw (via real2raw))
    % Still in physics units, just rotate and crunch.
    NBPM = length(BPMData.BPMIndex);
    for i = 1:NBPM
        if isfield(THERING{BPMData.BPMIndex(i)}, 'GCR')
            GCR = THERING{BPMData.BPMIndex(i)}.GCR;
        else
            GCR = [1 1 0 0];  % [Gx Gy Crunch Roll]
        end
        %Gx = GCR(1);  % Not used
        %Gy = GCR(2);  % Not used
        Crunch = GCR(3);
        Roll = GCR(4);
        a(i,1) = ( Crunch * sin(Roll) + cos(Roll)) / sqrt(1 - Crunch^2);
        b(i,1) = (-Crunch * cos(Roll) + sin(Roll)) / sqrt(1 - Crunch^2);
        c(i,1) = (-Crunch * cos(Roll) - sin(Roll)) / sqrt(1 - Crunch^2);
        d(i,1) = (-Crunch * sin(Roll) + cos(Roll)) / sqrt(1 - Crunch^2);
        % Same as:
        %%m = gcr2loco(GCR(1), GCR(2), GCR(3), GCR(4));
        %m = gcr2loco(1, 1, GCR(3), GCR(4));
        %a(i,1)= m(1,1);
        %b(i,1)= m(1,2);
        %c(i,1)= m(2,1);
        %d(i,1)= m(2,2);
    end
    % Build a rotation matrix
    C = [diag(a)  diag(b)
         diag(c)  diag(d)];
    % Rotate & crunch the AT model response matrix
    R0 = C * R0;
    % Split up R0 into an array
    Rmat(1,1).Data = R0(                         BPMData.HBPMIndex , 1:length(CMData.HCMIndex));
    Rmat(2,1).Data = R0(length(BPMData.BPMIndex)+BPMData.VBPMIndex , 1:length(CMData.HCMIndex));
    Rmat(1,2).Data = R0(                         BPMData.HBPMIndex , length(CMData.HCMIndex)+(1:length(CMData.VCMIndex)));
    Rmat(2,2).Data = R0(length(BPMData.BPMIndex)+BPMData.VBPMIndex , length(CMData.HCMIndex)+(1:length(CMData.VCMIndex)));
    % Convert to meters/radian (don't use the rolled kick strength)
    for i = 1:length(CMData.HCMKicks)
        Rmat(1,1).Data(:,i) = Rmat(1,1).Data(:,i) / HCMKicks(i);
        Rmat(2,1).Data(:,i) = Rmat(2,1).Data(:,i) / HCMKicks(i);
    end
    for i = 1:length(CMData.VCMKicks)
        Rmat(1,2).Data(:,i) = Rmat(1,2).Data(:,i) / VCMKicks(i);
        Rmat(2,2).Data(:,i) = Rmat(2,2).Data(:,i) / VCMKicks(i);
    end
    % Build the rest of the response matrix structure in 'Physics' units
    if ismemberof(BPMxFamily,'BPM') && ismemberof(BPMyFamily,'BPM')
        % getpvmodel is better because crunch and roll are included
        Xat = getam(BPMxFamily, BPMxList, 'Physics', 'Model');
        Yat = getam(BPMyFamily, BPMyList, 'Physics', 'Model');
    else
        % The orbit does not have to be at the BPMs so use modeltwiss
        [Xat, Yat, Sx, Sy] = modeltwiss('ClosedOrbit', BPMxFamily, BPMxList, BPMyFamily, BPMyList);
    end
    X.Data = Xat(:);
    Y.Data = Yat(:);
    X.FamilyName = BPMxFamily;
    Y.FamilyName = BPMyFamily;
    X.Field = 'Monitor';
    Y.Field = 'Monitor';
    X.DeviceList = BPMxList;
    Y.DeviceList = BPMyList;
    X.Status = ones(length(Xat),1);
    Y.Status = ones(length(Yat),1);
    X.Mode = 'Model';
    Y.Mode = 'Model';
    X.t = 0;
    Y.t = 0;
    X.tout = 0;
    Y.tout = 0;
    X.TimeStamp = clock;
    Y.TimeStamp = X.TimeStamp;
    X.Units = 'Physics';
    Y.Units = 'Physics';
    X.UnitsString = 'm';
    Y.UnitsString = 'm';
    X.DataDescriptor = 'Horizontal Orbit';
    Y.DataDescriptor = 'Vertical Orbit';
    X.CreatedBy = 'getpv';
    Y.CreatedBy = 'getpv';
    HCMsp = getsp(HCMFamily, HCMList, 'Struct', 'Model', 'Physics');
    VCMsp = getsp(VCMFamily, VCMList, 'Struct', 'Model', 'Physics');
    Rmat(1,1).Monitor = X;
    Rmat(1,1).Actuator = HCMsp;
    Rmat(1,2).Monitor = X;
    Rmat(1,2).Actuator = VCMsp;
    Rmat(2,1).Monitor = Y;
    Rmat(2,1).Actuator = HCMsp;
    Rmat(2,2).Monitor = Y;
    Rmat(2,2).Actuator = VCMsp;
    Rmat(1,1).ActuatorDelta = HCMKicks;  %CMData.HCMKicks;
    Rmat(2,1).ActuatorDelta = HCMKicks;  %CMData.HCMKicks;
    Rmat(1,2).ActuatorDelta = VCMKicks;  %CMData.VCMKicks;
    Rmat(2,2).ActuatorDelta = VCMKicks;  %CMData.VCMKicks;
    for i = 1:2
1000         for j = 1:2
1001             Rmat(i,j).GeV = getenergymodel;
1002             Rmat(i,j).TimeStamp = X.TimeStamp;
1003             Rmat(i,j).DCCT = [];
1004             Rmat(i,j).ModulationMethod = ModulationMethod;
1005             Rmat(i,j).WaitFlag = WaitFlag;
1006             Rmat(i,j).ExtraDelay = ExtraDelay;
1007             Rmat(i,j).Units = 'Physics';
1008             Rmat(i,j).UnitsString = [Rmat(1,1).Monitor.UnitsString, '/', Rmat(1,1).Actuator.UnitsString];
1009             Rmat(i,j).DataDescriptor = 'Response Matrix';
1010             Rmat(i,j).CreatedBy = 'measbpmresp';
1011             Rmat(i,j).OperationalMode = getfamilydata('OperationalMode');
1012         end
1013     end
1014
1015     if strcmpi(UnitsFlag, 'Hardware')
1016         % Change to hardware units [mm/amp]
1017         if ismemberof(BPMxFamily,'BPM') && ismemberof(BPMyFamily,'BPM') && ismemberof(HCMFamily,'COR') && ismemberof(VCMFamily,'COR')
1018             Rmat = physics2hw(Rmat, getenergymodel);
1019         else
1020             fprintf('\n   You are asking for hardware units, but a nonstandard monitor and/or\n');
1021             fprintf('   actuator was used.  The response matrix will stay in physics units!\n\n');
1022         end
1023     end
1024
1025 else
1026
1027     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1028     % Online or Simulated Response Matrix %
1029     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1030
1031     % Default kicks
1032     if isempty(HCMKicks)
1033         HCMKicks = getfamilydata(HCMFamily, 'Setpoint', 'DeltaRespMat', HCMList);
1034         KickUnits = 'Hardware'; %getfamilydata(HCMFamily, 'Setpoint', 'Units');
1035         if isempty(HCMKicks)
1036             HCMKicks = Default2HCMKick;
1037             KickUnits = 'Physics';
1038         end
1039         if isempty(KickUnits)
1040             error('Units for the kick strength are unknown.  Try inputing units directly.');
1041         end
1042         if strcmpi(UnitsFlag, 'Physics') && strcmpi(KickUnits, 'Hardware')
1043             HCMsp = getsp(HCMFamily, HCMList, 'Numeric', ModeFlag, 'Hardware');
1044             HCMKicks = hw2physics(HCMFamily, 'Setpoint', HCMsp+HCMKicks, HCMList) - hw2physics(HCMFamily, 'Setpoint', HCMsp, HCMList);
1045         elseif strcmpi(UnitsFlag, 'Hardware') && strcmpi(KickUnits, 'Physics')
1046             HCMsp = getsp(HCMFamily, HCMList, 'Numeric', ModeFlag, 'Physics');
1047             HCMKicks = physics2hw(HCMFamily, 'Setpoint', HCMsp+HCMKicks, HCMList) - physics2hw(HCMFamily, 'Setpoint', HCMsp, HCMList);
1048         end
1049     end
1050     if isempty(VCMKicks)
1051         VCMKicks = getfamilydata(VCMFamily, 'Setpoint', 'DeltaRespMat', VCMList);
1052         KickUnits = 'Hardware'; %getfamilydata(VCMFamily, 'Setpoint', 'Units');
1053         if isempty(VCMKicks)
1054             VCMKicks = Default2VCMKick;
1055             KickUnits = 'Physics';
1056         end
1057         if isempty(KickUnits)
1058             error('Units for the kick strength are unknown.  Try inputing units directly.');
1059         end
1060         if strcmpi(UnitsFlag, 'Physics') && strcmpi(KickUnits, 'Hardware')
1061             VCMsp = getsp(VCMFamily, VCMList, 'Numeric', ModeFlag, 'Hardware');
1062             VCMKicks = hw2physics(VCMFamily, 'Setpoint', VCMsp+VCMKicks, VCMList) - hw2physics(VCMFamily, 'Setpoint', VCMsp, VCMList);
1063         elseif strcmpi(UnitsFlag, 'Hardware') && strcmpi(KickUnits, 'Physics')
1064             VCMsp = getsp(VCMFamily, VCMList, 'Numeric', ModeFlag, 'Physics');
1065             VCMKicks = physics2hw(VCMFamily, 'Setpoint', VCMsp+VCMKicks, VCMList) - physics2hw(VCMFamily, 'Setpoint', VCMsp, VCMList);
1066         end
1067     end
1068
1069     %% Query to begin measurement
1070     %if DisplayFlag
1071     %    tmp = questdlg('Begin response matrix measurement?','Response Matrix Measurement','Yes','No','No');
1072     %    if strcmpi(tmp,'No')
1073     %        fprintf('   Response matrix measurement aborted\n');
1074     %        Rmat = [];
1075     %        return
1076     %    end
1077     %end
1078
1079     % Mask bpms and correctors for status
1080     BPMxStatus = getfamilydata(BPMxFamily, 'Status', BPMxList);
1081     BPMxGoodIndex = find(BPMxStatus);
1082     BPMxList = BPMxList(BPMxGoodIndex,:);
1083
1084     BPMyStatus = getfamilydata(BPMyFamily, 'Status', BPMyList);
1085     BPMyGoodIndex = find(BPMyStatus);
1086     BPMyList = BPMyList(BPMyGoodIndex,:);
1087
1088     HCMStatus = getfamilydata(HCMFamily, 'Status', HCMList);
1089     HCMGoodIndex = find(HCMStatus);
1090     HCMList = HCMList(HCMGoodIndex,:);
1091     if length(HCMKicks) == 1
1092         HCMKicks = HCMKicks * ones(length(HCMGoodIndex),1);
1093     else
1094         HCMKicks = HCMKicks(HCMGoodIndex);
1095     end
1096
1097     VCMStatus = getfamilydata(VCMFamily, 'Status', VCMList);
1098     VCMGoodIndex = find(VCMStatus);
1099     VCMList = VCMList(VCMGoodIndex,:);
1100     if length(VCMKicks) == 1
1101         VCMKicks = VCMKicks * ones(length(VCMGoodIndex),1);
1102     else
1103         VCMKicks = VCMKicks(VCMGoodIndex);
1104     end
1105
1106     % Measure response matrix of all planes at once
1107     % (One advantage of this is the limits of all planes get checked before the measurement starts)
1108     if DisplayFlag
1109         fprintf('   Begin BPM response matrix measurement\n');
1110     end
1111
1112     %if strcmpi(getfamilydata('Machine'), 'ALS')
1113     %    fprintf('   Using measrespmat_als (with orbit correction)\n');
1114     %    Rcell = measrespmat_als({BPMxFamily,BPMyFamily}, {BPMxList,BPMyList}, {HCMFamily,VCMFamily}, {HCMList,VCMList}, {HCMKicks,VCMKicks}, 'Struct', ModulationMethod, WaitFlag, ExtraDelay, InputFlags{:}, DCCTFlag{:});
1115     %else
1116         Rcell = measrespmat({BPMxFamily,BPMyFamily}, {BPMxList,BPMyList}, {HCMFamily,VCMFamily}, {HCMList,VCMList}, {HCMKicks,VCMKicks}, 'Struct', ModulationMethod, WaitFlag, ExtraDelay, InputFlags{:}, DCCTFlag{:});
1117         %BPMFamilies = findmemberof({'measbpmresp'},'Monitor');
1118         %BPMDevLists = family2dev(BPMFamilies);
1119         %Rcell = measrespmat(BPMFamilies, BPMDevLists, {HCMFamily,VCMFamily}, {HCMList,VCMList}, {HCMKicks,VCMKicks}, 'Struct', ModulationMethod, WaitFlag, ExtraDelay, InputFlags{:}, DCCTFlag{:});
1120     %end
1121     if DisplayFlag
1122         fprintf('   Measurement complete.\n\n');
1123     end
1124
1125     % Convert cell array to a struct array
1126     % (We only did this because struct arrays were more familiar to people)
1127     % Rmat(1,1) = Rcell{1,1};  % Kick x, look x
1128     % Rmat(2,1) = Rcell{2,1};  % Kick x, look y
1129     % Rmat(2,2) = Rcell{2,2};  % Kick y, look y
1130     % Rmat(1,2) = Rcell{1,2};  % Kick y, look x
1131     for i = 1:size(Rcell,1)
1132         for j = 1:size(Rcell,2)
1133             if istransport
1134                 % For transport line zero the BPM noise for upstream BPMs
1135                 for k = 1:size(Rcell{i,j}.Data,2)
1136                     CMpos = getspos(Rcell{i,j}.Actuator.FamilyName, Rcell{i,j}.Actuator.DeviceList(k,:));
1137                     BPMpos = getspos(Rcell{i,j}.Monitor);
1138                     iUpStream = find(BPMpos < CMpos);
1139                     if ~isempty(iUpStream)
1140                         Rcell{i,j}.Data(iUpStream,k) = 0;
1141                     end
1142                 end
1143             end
1144             Rmat(i,j) = Rcell{i,j};
1145         end
1146     end
1147
1148
1149     % % Horizontal corrector plane
1150     % if DisplayFlag
1151     %     fprintf('   Begin Horizontal plane measurement ...\n');
1152     % end
1153     % mat = measrespmat('Struct', {BPMxFamily, BPMyFamily}, {BPMxList, BPMyList}, HCMFamily, HCMList, HCMKicks, ModulationMethod, WaitFlag, ExtraDelay, InputFlags{:});
1154     % if DisplayFlag
1155     %     fprintf('   Horizontal plane complete.\n\n');
1156     % end
1157     %
1158     % % Make a response matrix array
1159     % Rmat(1,1) = mat{1};  % Kick x, look x
1160     % Rmat(2,1) = mat{2};  % Kick x, look y
1161     %
1162     %
1163     % % Vertical corrector plane
1164     % if DisplayFlag
1165     %     fprintf('   Begin Vertical plane measurement...\n');
1166     % end
1167     % mat = measrespmat('Struct', {BPMxFamily, BPMyFamily}, {BPMxList, BPMyList}, VCMFamily, VCMList, VCMKicks, ModulationMethod, WaitFlag, ExtraDelay, InputFlags{:});
1168     % if DisplayFlag
1169     %     fprintf('   Vertical plane complete.\n\n');
1170     % end
1171     %
1172     % Rmat(2,2) = mat{2};  % Kick y, look y
1173     % Rmat(1,2) = mat{1};  % Kick y, look x
1174 end
1175
1176 % Save data in the proper directory
1177 if ArchiveFlag || ischar(FileName)
1178     [DirectoryName, FileName, Ext] = fileparts(FileName);
1179     DirStart = pwd;
1180     [DirectoryName, ErrorFlag] = gotodirectory(DirectoryName);
1181     if ErrorFlag
1182         fprintf('\n   There was a problem getting to the proper directory!\n\n');
1183     end
1184     save(FileName, 'Rmat','MachineConfig');
1185     cd(DirStart);
1186     OutputFileName = [DirectoryName, FileName, '.mat'];
1187
1188     if DisplayFlag
1189         fprintf('   BPM response matrix data structure ''Rmat'' saved to disk\n');
1190         fprintf('   Filename: %s\n', OutputFileName);
1191         fprintf('   The total response matrix measurement time was %.2f minutes.\n', (gettime-TimeStart)/60);
1192     end
1193 else
1194     OutputFileName = '';
1195 end
1196
1197
1198 if ~StructOutputFlag
1199     % Return a matrix
1200     % Rmat = [Rmat(1,1).Data Rmat(1,2).Data;
1201     %         Rmat(2,1).Data Rmat(2,2).Data];
1202     RmatData = [];
1203     for i = 1:size(Rmat,1)
1204         Rrow = [];
1205         for j = 1:size(Rmat,2)
1206             Rrow = [Rrow Rmat(i,j).Data];
1207         end
1208         RmatData = [RmatData; Rrow];
1209     end
1210
1211     Rmat = RmatData;
1212 end
1213