Description of plotfamily
Home > mml > plotfamily.m
plotfamily
PURPOSE
PLOTFAMILY - Plots by middle layer family name
SYNOPSIS
function varargout = plotfamily(varargin)
DESCRIPTION
PLOTFAMILY - Plots by middle layer family name
  To restrict the families to certain MemberOf group use:
  plotfamily MemberName
  FACTS
  1. Clicking on a data point in the plot will select the device in the
     listbox.  Clicking in the listbox will allow for a setpoint change.
  2. The lattice plot can also be used to change the setpoint.
     Just click on an object in the lattice drawing.  To remove the
     setpoint widget click on a drift pass or BPM.  Note that HCMs are
     drawn above the axis and VCMs below.
  3. The "Common Tasks" menu is a launch pad menu.  It actually has nothing
     to do with of the plotfamily application.  Many of the typical
     tasks for setup of storage rings are listed in this menu.
  4. Use plotfamilystartup to customize it for a particular accelerator.
     (Look at the ALS for an example.)
  5. This application can be compiled to run standalone.
CROSS-REFERENCE INFORMATION
This function calls:
checkforao CHECKFORAO - Run aoinit if no middle layer is present
family2channel FAMILY2CHANNEL - Converts the family name to a channel name
family2common FAMILY2COMMON - Convert a family name, device list to a common name list
family2datastruct FAMILY2DATASTRUCTURE
family2dev FAMILY2DEV - Return the device list for a family
getdata GETDATA - Searches through a file (or group of files) for a data structure which matches the family name
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
getfamilylist GETFAMILYLIST - Returns a list of all the family names
getgolden GETGOLDEN - Returns the golden values for a family
gethcmfamily GETHCMFAMILY - Returns the default horizontal corrector family
getoffset GETOFFSET - Returns the offset values for a family
getpv GETPV - Returns a variable from the online system or the model
getsp GETSP - Gets setpoint channels
getspos GETSPOS - Returns the longitudinal position in meters
getvcmfamily GETVCMFAMILY - Returns the default vertical corrector family
hw2physics HW2PHYSICS - Converts from 'Hardware' units to 'Physics' units
isfamily ISFAMILY - True for family names
ismemberof ISMEMBEROF - Returns turn if the membership information of a family (cell of strings)
machine2sim MACHINE2SIM - loads online machine configuration to AT configuration
maxpv MAXPV - Maximum value of a process variable
minpv MinPV - Maximum value of a process variable
physics2hw PHYSICS2HW - Converts from 'Physics' units to 'Hardware' units
plotfamily PLOTFAMILY - Plots by middle layer family name
setfamilydata SETFAMILYDATA - Sets data associated with accelerator control
setpv SETPV - Setpoint change of the online system or model
sim2machine SIM2MACHINE - Sets the AT configuration to the online machine
switch2hw SWITCH2HW - Switch a family to hardware units
switch2online SWITCH2ONLINE - Switch family to online mode
switch2physics SWITCH2PHYSICS - Switch family to physics units
switch2sim SWITCH2SIM - Switch family to simulator mode if the family is in online mode.
This function is called by:
plotfamily PLOTFAMILY - Plots by middle layer family name
SUBFUNCTIONS
function figure1_CloseRequestFcn(hObject, eventdata, handles)
function plotfamily_OpeningFcn(hObject, eventdata, handles, varargin)
function SetFigureTitle(h_fig, ModeString)
function Resize_Callback(hObject, eventdata, handles)
function varargout = plotfamily_OutputFcn(hObject, eventdata, handles)
function EditMiddleLayer_Callback(hObject, eventdata, handles)
function Delete_Callback(hObject, eventdata, handles)
function Timer_Callback(hObject, eventdata, handles)
function OnOff_Callback(hObject, eventdata, handles)
function OneShot_Callback(hObject, eventdata, handles)
function plotappdatalocal(handles)
function RawOrbit1_Callback(hObject, eventdata, handles)
function GoldenOrbit1_Callback(hObject, eventdata, handles)
function OffsetOrbit1_Callback(hObject, eventdata, handles)
function SaveOrbit1_Callback(hObject, eventdata, handles)
function FileOrbit1_Callback(hObject, eventdata, handles)
function RawOrbit2_Callback(hObject, eventdata, handles)
function GoldenOrbit2_Callback(hObject, eventdata, handles)
function OffsetOrbit2_Callback(hObject, eventdata, handles)
function SaveOrbit2_Callback(hObject, eventdata, handles)
function FileOrbit2_Callback(hObject, eventdata, handles)
function SaveOrbit1Now_Callback(hObject, eventdata, handles)
function LoadOrbit1_Callback(hObject, eventdata, handles)
function UpdateFileDisplayLocal(handles)
function Display1_Callback(hObject, eventdata, handles)
function Display2_Callback(hObject, eventdata, handles)
function DisplayDiff_Callback(hObject, eventdata, handles)
function Trace2A_Callback(hObject, eventdata, handles)
function Trace2B_Callback(hObject, eventdata, handles)
function Trace2A_B_Callback(hObject, eventdata, handles)
function Trace2Off_Callback(hObject, eventdata, handles)
function DataList1_Callback(hObject, eventdata, handles)
function DataList2_Callback(hObject, eventdata, handles)
function PopPlot_Callback(hObject, eventdata, handles)
function PopPlot1_Callback(hObject, eventdata, handles)
function PopPlot2_Callback(hObject, eventdata, handles)
function Axis1_Callback(hObject, eventdata, handles)
function Axis2_Callback(hObject, eventdata, handles)
function HorizontalAxis_Callback(hObject, eventdata, handles)
function HorizontalAxisSector_Callback(hObject, eventdata, handles)
function YScaleLog1_Callback(hObject, eventdata, handles)
function YScaleLinear1_Callback(hObject, eventdata, handles)
function YScaleLog2_Callback(hObject, eventdata, handles)
function YScaleLinear2_Callback(hObject, eventdata, handles)
function DataStruct = CreateListboxString(DataStruct)
function BPMxFamily_Callback(hObject, eventdata, handles)
function BPMyFamily_Callback(hObject, eventdata, handles)
function BPMxList_Callback(hObject, eventdata, handles)
function BPMyList_Callback(hObject, eventdata, handles)
function UpdatePeriod_Callback(hObject, eventdata, handles)
function PhysicsUnits_Callback(hObject, eventdata, handles)
function HardwareUnits_Callback(hObject, eventdata, handles)
function MicronFlag_Callback(hObject, eventdata, handles)
function SaveOrbitToFile_Callback(hObject, eventdata, handles)
function Online_Callback(hObject, eventdata, handles)
function Simulate_Callback(hObject, eventdata, handles)
function Sim2Machine_Callback(hObject, eventdata, handles)
function Machine2Sim_Callback(hObject, eventdata, handles)
function HorizontalAxesScaling(hObject, eventdata, handles)
function AddPlot_Nothing_Callback(hObject, eventdata, handles)
function AddPlot_Beta_Callback(hObject, eventdata, handles)
function AddPlot_Dispersion_Callback(hObject, eventdata, handles)
function DrawLattice_Callback(hObject, eventdata, handles)
function Graph1_ButtonDown(hObject, eventdata, handles)
function Graph2_ButtonDown(hObject, eventdata, handles)
function AutoScale1_Callback(hObject, eventdata, handles)
function AutoScale2_Callback(hObject, eventdata, handles)
function AutoScaleVertical(h_axis, ScaleFactor)
function AutoScaleH_Callback(hObject, eventdata, handles)
function AutoScaleYLocal(handles)
function Graph1ZoomInVertical_Callback(hObject, eventdata, handles)
function Graph1ZoomOutVertical_Callback(hObject, eventdata, handles)
function Graph2ZoomInVertical_Callback(hObject, eventdata, handles)
function Graph2ZoomOutVertical_Callback(hObject, eventdata, handles)
function Graph1OffsetUpVertical_Callback(hObject, eventdata, handles)
function Graph1OffsetDownVertical_Callback(hObject, eventdata, handles)
function Graph2OffsetUpVertical_Callback(hObject, eventdata, handles)
function Graph2OffsetDownVertical_Callback(hObject, eventdata, handles)
function HorizontalOffsetRight_Callback(hObject, eventdata, handles)
function HorizontalOffsetLeft_Callback(hObject, eventdata, handles)
function Graph1ZoomInHorizontal_Callback(hObject, eventdata, handles)
function Graph1ZoomOutHorizontal_Callback(hObject, eventdata, handles)
function Switch2HW_Callback(hObject, eventdata, handles)
function Switch2Physics_Callback(hObject, eventdata, handles)
function Switch2Online_Callback(hObject, eventdata, handles)
function Switch2Sim_Callback(hObject, eventdata, handles)
function Lattice_ButtonDown(hObject, eventdata, handles)
function SetpointGUI_Callback(hObject, eventdata, handles)
function SetpointRange_Callback(hObject, eventdata, handles)
function SetpointSlider_Callback(hObject, eventdata, handles)
function SetpointEditBox_Callback(hObject, eventdata, handles)
function SetpointPushButton_Callback(hObject, eventdata, handles)
function ChangeSetpointPlotfamily(hObject, eventdata, handles)
function Graph1Line_Callback(hObject, eventdata, handles)
function Graph1Bar_Callback(hObject, eventdata, handles)
function Graph2Line_Callback(hObject, eventdata, handles)
function Graph2Bar_Callback(hObject, eventdata, handles)
function DisabledSetpointChanges_Callback(hObject, eventdata, handles)
function TurnOffSetpointGUI_Callback(hObject, eventdata, handles)
SOURCE CODE
function varargout = plotfamily(varargin)
%PLOTFAMILY - Plots by middle layer family name
%
%  To restrict the families to certain MemberOf group use:
%  plotfamily MemberName
%
%  FACTS
%  1. Clicking on a data point in the plot will select the device in the
%     listbox.  Clicking in the listbox will allow for a setpoint change.
%
%  2. The lattice plot can also be used to change the setpoint.
%     Just click on an object in the lattice drawing.  To remove the
%     setpoint widget click on a drift pass or BPM.  Note that HCMs are
%     drawn above the axis and VCMs below.
%
%  3. The "Common Tasks" menu is a launch pad menu.  It actually has nothing
%     to do with of the plotfamily application.  Many of the typical
%     tasks for setup of storage rings are listed in this menu.
%
%  4. Use plotfamilystartup to customize it for a particular accelerator.
%     (Look at the ALS for an example.)
%
%  5. This application can be compiled to run standalone.
%  Written by Greg Portmann
% Last Modified by GUIDE v2.5 26-Aug-2007 09:07:25
% For the compiler
%#function plotfamilystartup
%#function aoinit setao setoperationalmode srinit
%#function srcycle getmachineconfig setmachineconfig
%#function setorbitdefault findrf findrf2 rmdisp setgolden setoffset
%#function settune steptune setchro stepchro
%#function plotorbit plotorbitdata plotcm plotgoldenorbit plotoffsetorbit
%#function plotorbit plotdata plotbpmresp plotbpmrespsym
%#function plotlattice plotdisp plotchro
%#function monbpm getbpm monmags
%#function gettune
%#function measchro plotchro
%#function measdisp plotdisp
%#function measbpmresp meastuneresp quadcenter
%#function copybpmrespfile
%#function copybpmsigmafile
%#function copychrorespfile
%#function copydispersionfile
%#function copydisprespfile
%#function copyinjectionconfigfile
%#function copymachineconfigfile
%#function copytunerespfile
%#function measlocodata locogui buildlocoinput buildloco buildlocofitparameters
% Begin initialization code - DO NOT EDIT
gui_Singleton = 0;
gui_State = struct('gui_Name',       mfilename, ...
    'gui_Singleton',  gui_Singleton, ...
    'gui_OpeningFcn', @plotfamily_OpeningFcn, ...
    'gui_OutputFcn',  @plotfamily_OutputFcn, ...
    'gui_LayoutFcn',  [] , ...
    'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end
if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDIT
% --- Executes when user attempts to close figure1.
function figure1_CloseRequestFcn(hObject, eventdata, handles)
% hObject    handle to figure1 (see GCBO)
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Hint: delete(hObject) closes the figure
delete(hObject);
% --- Executes just before plotfamily is made visible.
function plotfamily_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% varargin   command line arguments to plotfamily (see VARARGIN)
% Choose default command line output for plotfamily
handles.output = hObject;
% Update handles structure
guidata(hObject, handles);
% UIWAIT makes plotfamily wait for user response (see UIRESUME)
% uiwait(handles.figure1);
%%%%%%%%%%%%%%%%
% Set defaults %
%%%%%%%%%%%%%%%%
UpdatePeriod = 1;
set(handles.('UpdatePeriod'),'Label', sprintf('Update Period = %.2f sec',UpdatePeriod));
setappdata(handles.figure1, 'UpdatePeriod', UpdatePeriod);
% Units  (This should get over written by the default for the BPM family)
setappdata(handles.figure1,'UnitsFlag', 2);
set(handles.('PhysicsUnitsFlag'),'Checked','Off');
set(handles.('HardwareUnitsFlag'),'Checked','On');
set(handles.('MicronFlag'),'Checked','Off');
setappdata(handles.figure1,'ChannelA',1);
setappdata(handles.figure1,'ChannelB',2);
% Set the trace 1 defaults
%setappdata(handles.figure1,'Trace1',1);
set(handles.('DisplayDiff'),'Value', 1);
set(handles.('Display1'),'Value', 0);
set(handles.('Display2'),'Value', 0);
setappdata(handles.figure1,'Trace1',3);
setappdata(handles.figure1,'Trace2',4);
% Run initialization if it has not been run (like standalone)
checkforao;
if isempty(varargin)
    MemberofField = 'PlotFamily';
else
    MemberofField = varargin{1};
end
% Build Family menu
FoundOne = 0;
FamilyName = getfamilylist;
for i = 1:size(FamilyName,1)
    Family = deblank(FamilyName(i,:));
    try
        spos = getspos(Family);
    catch
        spos = [];
    end
    % Only include if there are S-position for the family
    if ~isempty(spos)
        FieldList = '';
        if ismemberof(Family, MemberofField)
            %if ismemberof(Family, 'PlotFamily') | ismemberof(Family, 'MachineConfig') | ismemberof(Family, 'BPM') | ...
            %        ismemberof(Family, 'COR') | ismemberof(Family, 'QUAD') | ...
            %        ismemberof(Family, 'HCM') | ismemberof(Family, 'VCM') | ...
            %        ismemberof(Family, 'SEXT') | ismemberof(Family, 'BEND') | ...
            %        ismemberof(Family, 'SkewQuad') | ismemberof(Family, 'SQSF') | ismemberof(Family, 'SQSD')
            FieldList = 'Monitor';
            FoundOne = 1;
        end
        % Look if any other fields are part of the MachineConfig
        AOFamily = getfamilydata(Family);
        FieldNameCell = fieldnames(AOFamily);
        for j = 1:size(FieldNameCell,1)
            if isfield(AOFamily.(FieldNameCell{j}),'MemberOf')
                if any(strcmpi(AOFamily.(FieldNameCell{j}).MemberOf, MemberofField))
                    %if any(strcmpi(AOFamily.(FieldNameCell{j}).MemberOf, MemberofField)) | any(strcmpi(AOFamily.(FieldNameCell{j}).MemberOf, 'MachineConfig'))
                    FieldList = strvcat(FieldList,FieldNameCell{j});
                    FoundOne = 1;
                end
            end
        end
        % Remove repeats but keep the row order
        [FieldListUnique, ii, jj] = unique(FieldList, 'rows');
        jj(find(diff(jj)==0)) = [];
        FieldList = FieldListUnique(jj,:);
        if size(FieldList,1) == 1
            Menu1 = handles.('BPMxFamily');
            Menu2 = handles.('BPMyFamily');
            h1 = uimenu(Menu1, 'Label',sprintf('%s',Family), 'Callback','plotfamily(''BPMxFamily_Callback'',gcbo,[],guidata(gcbo))');
            h2 = uimenu(Menu2, 'Label',sprintf('%s',Family), 'Callback','plotfamily(''BPMyFamily_Callback'',gcbo,[],guidata(gcbo))');
            set(h1, 'UserData', family2datastruct(Family, deblank(FieldList)));
            set(h2, 'UserData', family2datastruct(Family, deblank(FieldList)));
        elseif size(FieldList,1) > 1
            % Build off an extra menu
            Menu1 = handles.('BPMxFamily');
            Menu2 = handles.('BPMyFamily');
            Menu1 = uimenu(Menu1, 'Label', Family);
            Menu2 = uimenu(Menu2, 'Label', Family);
            for iField = 1:size(FieldList,1)
                h1 = uimenu(Menu1, 'Label',sprintf('%s.%s',Family,deblank(FieldList(iField,:))), 'Callback','plotfamily(''BPMxFamily_Callback'',gcbo,[],guidata(gcbo))');
                h2 = uimenu(Menu2, 'Label',sprintf('%s.%s',Family,deblank(FieldList(iField,:))), 'Callback','plotfamily(''BPMyFamily_Callback'',gcbo,[],guidata(gcbo))');
                set(h1, 'UserData', family2datastruct(Family, deblank(FieldList(iField,:))));
                set(h2, 'UserData', family2datastruct(Family, deblank(FieldList(iField,:))));
            end
        else
            % Skip family
        end
    end
end
if ~FoundOne
    % if MemberOf came up empty, then put all the families in the menu
    for i = 1:size(FamilyName,1)
        try
            Family = deblank(FamilyName(i,:));
            FamilyStruct = family2datastruct(Family,'Monitor');
            spos = getspos(FamilyStruct);
            if ~isempty(spos)
                h1 = uimenu(handles.('BPMxFamily'), 'Label',Family, 'Callback','plotfamily(''BPMxFamily_Callback'',gcbo,[],guidata(gcbo))');
                h2 = uimenu(handles.('BPMyFamily'), 'Label',Family, 'Callback','plotfamily(''BPMyFamily_Callback'',gcbo,[],guidata(gcbo))');
                set(h1, 'UserData', FamilyStruct);
                set(h2, 'UserData', FamilyStruct);
            end
        catch
            % Skip family
            %fprintf('Skipping family %s',Family);
        end
    end
end
% Initial families
try
    % Default orbit family names
    %BPMxFamily = gethbpmfamily;
    %
    %if isempty(BPMxFamily)
    %    FamilyList = getfamilylist;
    %    BPMxFamily = deblank(FamilyList(1,:));
    %end
    %BPMyFamily = getvbpmfamily;
    %if isempty(BPMyFamily)
    %    FamilyList = getfamilylist;
    %    BPMyFamily = deblank(FamilyList(2,:));
    %end
    %BPMxField = 'Monitor';
    %BPMyField = 'Monitor';
    %BPMxList = family2dev(BPMxFamily, 1);
    %BPMyList = family2dev(BPMyFamily, 1);
    %
    %set(handles.('BPMxFamily'),'Label',sprintf('Plot: %s', BPMxFamily));
    %set(handles.('BPMyFamily'),'Label',sprintf('Plot: %s', BPMyFamily));
    %
    %RawX = family2datastruct(BPMxFamily, BPMxField, BPMxList, UnitsFlag);
    %RawY = family2datastruct(BPMyFamily, BPMyField, BPMyList, UnitsFlag);
    %RawX.Data = zeros(size(BPMxList,1),1);
    %RawY.Data = zeros(size(BPMyList,1),1);
    % Base on first 2 families
    FamilyHandles = get(handles.('BPMxFamily'),'Children');
    if length(FamilyHandles) >= 1
        RawX = get(FamilyHandles(end),'UserData');
        if isempty(RawX)
            FamilyHandles2 = get(FamilyHandles(end),'Children');
            RawX = get(FamilyHandles2(end),'UserData');
        end
        BPMxFamily = RawX.FamilyName;
    else
        fprintf('   No families in the MML.\n');
    end
    if length(FamilyHandles) >= 2
        RawY = get(FamilyHandles(end-1),'UserData');
        if isempty(RawY)
            FamilyHandles2 = get(FamilyHandles(end-1),'Children');
            RawY = get(FamilyHandles2(end),'UserData');
        end
        BPMyFamily = RawY.FamilyName;
    else
        RawY = RawX;
        BPMyFamily = RawX.FamilyName;
    end
    % Initialize Mode
    % if strcmpi(get(handles.Simulate,'Checked'),'On')
    %     Mode = 'Simulator';
    % else
    %     Mode = 'Online';
    % end
    if strcmpi(RawX.Mode,'SIMULATOR')
        set(handles.Online,'Checked','Off');
        set(handles.Simulate,'Checked','On');
        Mode = 'Simulator';
        SetFigureTitle(handles.figure1, 'Model');
    else
        set(handles.Online,'Checked','On');
        set(handles.Simulate,'Checked','Off');
        Mode = 'Online';
        SetFigureTitle(handles.figure1, 'Online')
    end
    % Initialize Units
    if strcmpi(RawX.Units,'Physics')
        setappdata(handles.figure1,'UnitsFlag', 1);
        set(handles.('PhysicsUnitsFlag'),'Checked','On');
        set(handles.('HardwareUnitsFlag'),'Checked','Off');
        set(handles.('MicronFlag'),'Checked','Off');
        UnitsFlag = 'Physics';
    else
        setappdata(handles.figure1,'UnitsFlag', 2);
        set(handles.('PhysicsUnitsFlag'),'Checked','Off');
        set(handles.('HardwareUnitsFlag'),'Checked','On');
        set(handles.('MicronFlag'),'Checked','Off');
        UnitsFlag = 'Hardware';
    end
    set(handles.BPMxFamily,'Label',sprintf('Plot: %s', BPMxFamily));
    set(handles.BPMyFamily,'Label',sprintf('Plot: %s', BPMyFamily));
    % Create the list box string
    RawX = CreateListboxString(RawX);
    RawY = CreateListboxString(RawY);
    setappdata(handles.figure1, 'BPMxFamily', RawX);
    setappdata(handles.figure1, 'BPMyFamily', RawY);
    setappdata(handles.figure1,'RawX', RawX);
    setappdata(handles.figure1,'RawY', RawY);
    setappdata(handles.figure1,'SaveX', RawX);
    setappdata(handles.figure1,'SaveY', RawY);
    set(handles.SaveTime,'String', '');
    setappdata(handles.figure1,'FileX', RawX);
    setappdata(handles.figure1,'FileY', RawY);
    setappdata(handles.figure1,'FileNameX','');
    setappdata(handles.figure1,'FileNameY','');
    set(handles.FileNameX,'String', '');
    set(handles.FileNameY,'String', '');
    %p = get(handles.FileNameX,'Position');
    %set(handles.FileNameX,'Position', [p(1) 4 p(3) p(4)]);    % Points
    %set(handles.FileNameX,'Position', [p(1) .8 p(3) p(4)]);   % Characters
    %set(handles.FileNameX,'Position', [p(1) 0.02 p(3) p(4)]); % Normalized
    %p = get(handles.SaveTime,'Position');
    %set(handles.SaveTime,'Position', [p(1) 16.5 p(3) p(4)]);  % Points
    %set(handles.SaveTime,'Position', [p(1) 1.6 p(3) p(4)]);   % Characters
    %set(handles.SaveTime,'Position', [p(1) 0.052 p(3) p(4)]); % Normalized
    % Look to see it the AT model needs to be changed for this family
    ATModelNumber = getfamilydata(BPMxFamily, 'AT', 'ATModel');
    if ~isempty(ATModelNumber)
        global THERING THERINGCELL
        THERING = THERINGCELL{ATModelNumber};
        setfamilydata(findspos(THERING,length(THERING)+1), 'Circumference');
    end
catch
    % Starting units
    UnitMenu = getappdata(handles.figure1,'UnitsFlag');
    if UnitMenu == 1
        UnitsFlag = 'Physics';
    else
        UnitsFlag = 'Hardware';
    end
    % Initialize Mode
    if strcmpi(get(handles.Simulate,'Checked'),'On')
        Mode = 'Simulator';
    else
        Mode = 'Online';
    end
end
% % Look for the golden values
% try
%     GoldenValues = getgolden(BPMxFamily, BPMxList, 'Struct');
%     setappdata(handles.figure1,'GoldenX', GoldenValues);
% catch
%     setappdata(handles.figure1,'GoldenX', RawX);
% end
%
% % Look for the offset values
% try
%     OffsetValues = getoffset(BPMxFamily, BPMxList, 'Struct');
%     setappdata(handles.figure1,'OffsetX', OffsetValues);
% catch
%     if isempty(OffsetValues)
%         try
%             % If and offset does not exist than try using the setpoint
%             setappdata(handles.figure1,'OffsetX', getsp(BPMxFamily, BPMxList, Mode, 'Struct'));
%         catch
%             % Use zeros
%             setappdata(handles.figure1,'OffsetX', RawX);
%         end
%     end
% end
%
% % Look for the golden values
% try
%     GoldenValues = getgolden(BPMyFamily, BPMyList, 'Struct');
%     setappdata(handles.figure1,'GoldenY', GoldenValues);
% catch
%     setappdata(handles.figure1,'GoldenY', RawY);
% end
%
% % Look for the offset values
% try
%     OffsetValues = getoffset(BPMyFamily, BPMyList, 'Struct');
%     setappdata(handles.figure1,'OffsetY', OffsetValues);
% catch
%     try
%         % If and offset does not exist than try using the setpoint
%         setappdata(handles.figure1,'OffsetY', getsp(BPMyFamily, BPMyList, Mode, 'Struct'));
%     catch
%         % Use zeros
%         setappdata(handles.figure1,'OffsetY', RawY);
%     end
% end
L = getfamilydata('Circumference');
try
    s = getspos(RawX);
    setappdata(handles.figure1, 'SPosX', s);
    if isempty(L)
        L = max(s);
    end
    %setappdata(handles.figure1, 'AxisRange1X', [min(s) max(s)]);
catch
    %setappdata(handles.figure1, 'SPosX', 1:size(RawX.DeviceList,1));
end
setappdata(handles.figure1, 'AxisRange1X', [0 L]);
try
    s = getspos(RawY);
    setappdata(handles.figure1, 'SPosY', s);
    %setappdata(handles.figure1, 'AxisRange2X', [min(s) max(s)]);
catch
    %setappdata(handles.figure1, 'SPosY', 1:size(RawY.DeviceList,1));
end
setappdata(handles.figure1, 'AxisRange2X', [0 L]);
% Update time
set(handles.Time, 'String', '');
% Initialize plots
set(handles.Graph1, 'XLim', [0 L]);
set(handles.Graph2, 'XLim', [0 L]);
p1 = [0.07    0.65    0.74    0.29];
set(handles.Graph1, 'Position', p1);
set(handles.Graph3, 'Position', p1);
p2 = [0.07    0.27    0.74    0.29];
set(handles.Graph2, 'Position', p2);
set(handles.Graph4, 'Position', p2);
plot(handles.Graph3, NaN, NaN);
set(handles.Graph3, 'Visible', 'Off');
set(handles.Graph3, 'color', 'none');
set(handles.Graph3, 'XLim', [0 L]);
plot(handles.Graph4, NaN,NaN);
set(handles.Graph4, 'Visible', 'Off');
set(handles.Graph4, 'color', 'none');
set(handles.Graph4, 'XLim', [0 L]);
%axes(handles.LatticeAxes);
try
    % Add the lattice drawing
    drawlattice(0, 1.1, handles.LatticeAxes);
    % Match with DrawLattice_Callback
    g = .01;
    p1 = [0.07    0.65+g    0.74    0.29-g];
    set(handles.Graph1, 'Position', p1);
    set(handles.Graph3, 'Position', p1);
    p2 = [0.07    0.27      0.74    0.29-g];
    set(handles.Graph2, 'Position', p2);
    set(handles.Graph4, 'Position', p2);
    set(handles.LatticeAxes, 'Units', 'Normalized');
    %P = get(handles.LatticeAxes, 'Position');
    set(handles.LatticeAxes, 'Position', [0.07 0.5744-g 0.74 0.07+2*g]);  % p4 was 0.065
catch
    % Remove the lattice drawing
    d = .015;  % Match with DrawLattice_Callback
    p1 = [0.07    0.65-d    0.74    0.29+d];
    set(handles.Graph1, 'Position', p1);
    set(handles.Graph3, 'Position', p1);
    p2 = [0.07    0.27    0.74    0.29+d];
    set(handles.Graph2, 'Position', p2);
    set(handles.Graph4, 'Position', p2);
    set(handles.DrawLattice, 'Checked', 'Off');
    set(get(handles.LatticeAxes,'Children'), 'Visible' , 'Off');
end
try
    set(handles.LatticeAxes,'Visible','Off');
    set(handles.LatticeAxes,'Color','None');
    set(handles.LatticeAxes,'XMinorTick','Off');
    set(handles.LatticeAxes,'XMinorGrid','Off');
    set(handles.LatticeAxes,'YMinorTick','Off');
    set(handles.LatticeAxes,'YMinorGrid','Off');
    set(handles.LatticeAxes,'XTickLabel',[]);
    set(handles.LatticeAxes,'YTickLabel',[]);
    set(handles.LatticeAxes,'XLim', [0 L]);
    set(handles.LatticeAxes,'YLim', [-1.5 1.5]);
    % Add callback on each lattice element
    % set(handles.LatticeAxes ,'ButtonDownFcn','plotfamily(''Lattice_ButtonDown'',gcbo,[],guidata(gcbo))');
    h = get(handles.LatticeAxes,'Children');
    for i = 1:length(h)
        %ATIndex = get(h(i), 'UserData');
        set(h(i), 'ButtonDownFcn', 'plotfamily(''Lattice_ButtonDown'',gcbo,[],guidata(gcbo))');
    end
catch
end
% % Build middle layer edit menus
% %h = addmenuao(handles.('EditMiddleLayerAO'));
% %set(h, 'Label', 'Middle Layer Family Setup');
%
% hmenu = handles.('EditMiddleLayerAO');
% LabelString = 'Middle Layer Family Setup';
% ParentLabelString = 'MiddleLayer';
% DataStructure0 = getao;
% if isempty(DataStructure0)
%     aoinit;
% end
%
%
% % Build middle menu tree
% DataStructFieldName1 = fieldnames(DataStructure0);
% for i = 1:length(DataStructFieldName1)
%     DataStructure1 = DataStructure0.(DataStructFieldName1{i});
%     if isstruct(DataStructure1)
%         hmenu1 = uimenu(hmenu, 'Label',DataStructFieldName1{i}, 'Callback','');
%         DataStructFieldName2 = fieldnames(DataStructure1);
%         for j = 1:length(DataStructFieldName2)
%             DataStructure2 = DataStructure1.(DataStructFieldName2{j});
%             if isstruct(DataStructure2)
%                 hmenu2 = uimenu(hmenu1, 'Label',DataStructFieldName2{j}, 'Callback','');
%                 DataStructFieldName3 = fieldnames(DataStructure2);
%                 for k = 1:length(DataStructFieldName3)
%                     DataStructure3 = DataStructure2.(DataStructFieldName3{k});
%                     if isstruct(DataStructure3)
%                         hmenu3 = uimenu(hmenu2, 'Label',DataStructFieldName3{k}, 'Callback','');
%                         DataStructFieldName4 = fieldnames(DataStructure3);
%                         for l = 1:length(DataStructFieldName4)
%                             hmenu4 = uimenu(hmenu3, 'Label', DataStructFieldName4{l});
%                             set(hmenu4,'UserData', {DataStructure3.(DataStructFieldName4{l}) , DataStructFieldName1{l}, DataStructFieldName2{k}, DataStructFieldName3{k}, DataStructFieldName4{i}});
%                             set(hmenu4,'Callback', 'plotfamily(''EditMiddleLayer_Callback'',gcbo,[],guidata(gcbo))');
%                         end
%                     else
%                         hmenu3 = uimenu(hmenu2, 'Label',DataStructFieldName3{k});
%                         set(hmenu3,'UserData', {DataStructure3, DataStructFieldName1{i}, DataStructFieldName2{j}, DataStructFieldName3{k}});
%                         set(hmenu3,'Callback', 'plotfamily(''EditMiddleLayer_Callback'',gcbo,[],guidata(gcbo))');
%                     end
%                 end
%             else
%                 hmenu2 = uimenu(hmenu1, 'Label',DataStructFieldName2{j});
%                 set(hmenu2,'UserData', {DataStructure2, DataStructFieldName1{i}, DataStructFieldName2{j}});
%                 set(hmenu2,'Callback', 'plotfamily(''EditMiddleLayer_Callback'',gcbo,[],guidata(gcbo))');
%             end
%         end
%     else
%         hmenu1 = uimenu(hmenu, 'Label', DataStructFieldName1{i});
%         set(hmenu1,'UserData', {DataStructure1, DataStructFieldName1{i}});
%         set(hmenu1,'Callback', 'plotfamily(''EditMiddleLayer_Callback'',gcbo,[],guidata(gcbo))');
%     end
% end
% % Build the AD menu
% set(addmenuad(handles.EditMiddleLayerAD), 'Label', 'Middle Layer Parameter Setup');
set(handles.EditMiddleLayerAO, 'Visible', 'Off');
set(handles.EditMiddleLayerAD, 'Visible', 'Off');
% Machine specific startup function
if exist('plotfamilystartup', 'file')
    plotfamilystartup(handles);
end
% --------------------------------------------------------------------
function SetFigureTitle(h_fig, ModeString)
MachineName     = getfamilydata('Machine');
SubMachineName  = getfamilydata('SubMachine');
OperationalMode = getfamilydata('OperationalMode');
try
    if isdeployed
        TitleString = sprintf('Plot Family:  %s  -  %s  -  %s  (%s - Standalone)', MachineName, SubMachineName, OperationalMode, ModeString);
    else
        TitleString = sprintf('Plot Family:  %s  -  %s  -  %s  (%s)', MachineName, SubMachineName, OperationalMode, ModeString);
    end
catch
    TitleString = sprintf('Plot Family:  %s  -  %s  -  %s  (%s)', MachineName, SubMachineName, OperationalMode, ModeString);
end
set(h_fig,'Name',TitleString);
% --------------------------------------------------------------------
function Resize_Callback(hObject, eventdata, handles)
% SmallestPositionX = 174.800;
% SmallestPositionY  = 39.7692;
%
% % Units should be characters anyways
% Units = get(hObject,'Units');
% set(hObject,'Units', 'Characters');
% P = get(hObject, 'Position');
%
% if P(3) < SmallestPositionX
%    P(3) = SmallestPositionX;
%
%    if P(1)+P(3) < 0
%    end
% end
%
%
% if P(4) < SmallestPositionY
%    P(4) = SmallestPositionY;
% end
%
% set(hObject, 'Position', P);
% set(hObject, 'Units', Units);
% --- Outputs from this function are returned to the command line.
function varargout = plotfamily_OutputFcn(hObject, eventdata, handles)
% varargout  cell array for returning output args (see VARARGOUT);
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)
% Get default command line output from handles structure
if isfield(handles,'output')
    varargout{1} = handles.output;
end
% --- Executes onoff button press in OnOff.
function EditMiddleLayer_Callback(hObject, eventdata, handles)
Data = get(hObject, 'UserData');
% Get up-to-date data
Data{1} = getfamilydata(Data{2:end});
TitleString = sprintf('%s ',Data{2:end});
AddOpts.Resize='on';
AddOpts.WindowStyle='normal';
AddOpts.Interpreter='tex';
if length(Data) >= 3 && (strcmpi(deblank(Data{3}),'Status') || strcmpi(deblank(Data{3}),'DeviceList') || strcmpi(deblank(Data{3}),'ElementList'))
    if strcmpi(deblank(Data{3}),'ElementList')
        DeviceList = getfamilydata(deblank(Data{2}), 'ElementList');
    else
        DeviceList = getfamilydata(deblank(Data{2}), 'DeviceList');
    end
    Status = getfamilydata(deblank(Data{2}), 'Status');
    DeviceListNew = editlist(DeviceList, deblank(Data{2}), Status);
    [i, iNotFound] = findrowindex(DeviceListNew, DeviceList);
    if size(Status,1) == 1
        DeviceListTotal = family2dev(Data{2}, 0);
        Status = zeros(size(DeviceListTotal,1),1);
    else
        Status = 0 * Status;
    end
    Status(i) = 1;
    setfamilydata(Status, deblank(Data{2}), 'Status');
elseif isnumeric(Data{1})
    answer = inputdlg({sprintf('Change %s ',TitleString)}, 'Edit Middle Layer Family', size(Data{1},1), {num2str(Data{1})}, AddOpts);
    if isempty(answer)
        return
    end
    Data{1} = str2num(answer{1});
    set(hObject, 'UserData', Data);
    setfamilydata(Data{1:end});
elseif strcmpi(Data{2},'Directory')
    answer = uigetdir(Data{1}, sprintf('Change directory location for %s', Data{3}));
    if answer == 0
        return
    end
    Data{1} = answer;
    set(hObject, 'UserData', Data);
    setfamilydata(Data{1:end});
elseif ischar(Data{1})
    answer = inputdlg({sprintf('Change %s ',TitleString)}, 'Edit Middle Layer Family', size(Data{1},1), {num2str(Data{1})}, AddOpts);
    if isempty(answer)
        return
    end
    Data{1} = answer{1};
    set(hObject, 'UserData', Data);
    setfamilydata(Data{1:end});
end
% Reset graphs
BPMxFamily_Callback([], eventdata, handles);
BPMyFamily_Callback([], eventdata, handles);
function Delete_Callback(hObject, eventdata, handles)
% If timer is on, then turn it off by deleting the timer handle
try
    %h = get(gcbf, 'UserData');
    h = get(handles.figure1, 'UserData');
    if isfield(h,'TimerHandle')
        stop(h.TimerHandle);
        delete(h.TimerHandle);
    end
catch
    fprintf('   Trouble stopping the timer on exit.\n');
end
% --- Executes onoff button press in OnOff.
function Timer_Callback(hObject, eventdata, handles)
% Timer method
%disp('Timer executed.');
%handles = get(eventdata, 'UserData');
handles = get(hObject, 'UserData');
plotfamily('OneShot_Callback', hObject, [], handles);
% --- Executes onoff button press in OnOff.
function OnOff_Callback(hObject, eventdata, handles)
% Timer method
% % Update the title bar
% if strcmpi(get(handles.Simulate,'Checked'),'On')
%     SetFigureTitle(handles.figure1, 'Model');
% else
%     SetFigureTitle(handles.figure1, 'Online');
% end
OnFlag = get(handles.OnOff, 'Value');
if OnFlag
    % Turn on updates
    set(handles.OnOff, 'String', 'Running');
    % Setup timer
    UpdatePeriod = getappdata(handles.figure1, 'UpdatePeriod');
    t = timer;
    set(t,'StartDelay',0);
    set(t,'Period', UpdatePeriod);
    %set(t,'TimerFcn', 'plotfamily(''OneShot_Callback'', getfield(get(timerfind(''Tag'',''PlotFamilyTimer''),''Userdata''),''figure1''), [], get(timerfind(''Tag'',''PlotFamilyTimer''),''Userdata''));');
    set(t,'TimerFcn', ['plotfamily(''Timer_Callback'',', sprintf('%.30f',handles.figure1), ',',sprintf('%.30f',handles.figure1), ', [])']);
    set(t,'UserData', handles);
    set(t,'BusyMode', 'drop');  %'queue'
    set(t,'TasksToExecute', Inf);
    set(t,'ExecutionMode', 'FixedRate');
    set(t,'Tag', 'PlotFamilyTimer');
    handles.TimerHandle = t;
    set(handles.figure1, 'UserData', handles);
    start(t);
else
    try
        % Turn off updating by deleting timer handle
        h = get(handles.figure1, 'UserData');
        stop(h.TimerHandle);
        delete(h.TimerHandle);
        h = rmfield(h, 'TimerHandle');
        set(handles.figure1, 'UserData', h);
        % Delete all timers
        %h = timerfind('Tag','PlotFamilyTimer');
        %for i = 1:length(h)
        %    stop(h(i));
        %    delete(h(i));
        %end
        % Change OnOff label string
        set(handles.OnOff, 'String', 'Continuous');
    catch
        fprintf('   Trouble stopping the timer.\n');
    end
end
% % --- Executes onoff button press in OnOff.
% function OnOff_Callback(hObject, eventdata, handles)
% % Uses delay (not Timer)
%
% OrbitFeedbackFlag = 0;
%
% % Turn lattice menu back off
% set(handles.('LatticeMenu'),'enable','off');
%
% if strcmpi(get(handles.Simulate,'Checked'),'On')
%     Mode = 'Simulator';
% else
%     Mode = 'Online';
% end
%
% BPMxFamily = getappdata(handles.figure1, 'BPMxFamily');
% BPMxList = getappdata(handles.figure1, 'BPMxList');
% BPMyFamily = getappdata(handles.figure1, 'BPMyFamily');
% BPMyList = getappdata(handles.figure1, 'BPMyList');
%
% OnFlag = get(handles.('OnOff'),'Value');
% if OnFlag
%     % Turn on updates
%     set(handles.('OnOff'), 'String', 'Running')
% end
%
% if OrbitFeedbackFlag
%     [Nbpm, Tbpm] = getbpmaverages;
%     Tbpm = max(Tbpm);
% end
%
% while OnFlag
%     t0 = gettime;
%     OnFlag = get(handles.('OnOff'),'Value');
%     UpdatePeriod = getappdata(handles.figure1, 'UpdatePeriod');
%
%     if OnFlag
%         % Get new data
%         try
%             RawX = getam(BPMxFamily, BPMxList, Mode, 'Struct');
%         catch
%             RawX.Data = NaN*zeros(size(BPMxList,1),1);
%             RawX.Units = 'Hardware';
%             RawX.TimeStamp = clock;
%             fprintf('   %s, GETAM trouble in family %s\n', sprintf('%s',datestr(RawX.TimeStamp,14)), BPMxFamily);
%         end
%         setappdata(handles.figure1, 'RawX', RawX);
%
%         try
%             RawY = getam(BPMyFamily, BPMyList, Mode, 'Struct');
%         catch
%             RawY.Data = NaN*zeros(size(BPMyList,1),1);
%             RawY.Units = 'Hardware';
%             RawY.TimeStamp = clock;
%             fprintf('   %s, GETAM trouble in family %s\n', sprintf('%s',datestr(RawY.TimeStamp,14)), BPMyFamily);
%         end
%         setappdata(handles.figure1, 'RawY', RawY);
%
%         % For non-BPM the offset (ie, the setpoint) may have changed
%         if ~ismemberof(BPMxFamily,'BPM')
%             % Update the offset to the setpoint
%             setappdata(handles.figure1,'OffsetX', getsp(BPMxFamily, BPMxList, Mode));
%         end
%         if ~ismemberof(BPMyFamily,'BPM')
%             % Update the offset to the setpoint
%             setappdata(handles.figure1,'OffsetY', getsp(BPMyFamily, BPMyList, Mode));
%         end
%
%         % Update time
%         set(handles.('Time'),'String', sprintf('%s',datestr(RawY.TimeStamp,14)));
%
%         plotappdatalocal(handles);
%         drawnow;
%
%
%         if OrbitFeedbackFlag
%             % One could easily add a orbit feedback step
%             setorbitdefault([], 1, [], 'NoDisplay');
%             pause(2.2*Tbpm);
%         end
%
%     else
%         set(handles.('OnOff'), 'String', 'Continuous');
%
%         % Turn lattice menu back on
%         set(handles.('LatticeMenu'),'enable','on');
%
%         break
%     end
%
%     % Pause
%     T = UpdatePeriod-(gettime-t0);
%     if T > 0
%         pause(T);
%     end
% end
% --- Executes on button press in OneShot.
function OneShot_Callback(hObject, eventdata, handles)
% To break out of the continuous loop (if in it)
%set(handles.('OnOff'),'Value', 0);  % Not turned off with timer!
% Get Mode and update the title bar
if strcmpi(get(handles.Simulate,'Checked'),'On')
    SetFigureTitle(handles.figure1, 'Model')
    Mode = 'Simulator';
else
    SetFigureTitle(handles.figure1, 'Online')
    Mode = 'Online';
end
% Get the structures
DataStruct1 = getappdata(handles.figure1, 'BPMxFamily');
DataStruct2 = getappdata(handles.figure1, 'BPMyFamily');
% Get new data
try
    RawX = getpv(DataStruct1, Mode, 'Struct');
    %RawX = getpv(DataStruct1, Mode, UnitsFlag, 'Struct');
catch
    RawX.Data = NaN*zeros(size(DataStruct1.Data,1),1);
    RawX.Units = DataStruct1.Units;
    RawX.UnitsString = DataStruct1.UnitsString;
    RawX.Mode = Mode;
    RawX.TimeStamp = clock;
    fprintf('\n%s\n', lasterr);
    fprintf('   %s, GETPV trouble in family %s\n', sprintf('%s',datestr(RawX.TimeStamp,14)), DataStruct1.FamilyName);
end
setappdata(handles.figure1, 'RawX', RawX);
try
    RawY = getpv(DataStruct2, Mode, 'Struct');
    %RawY = getpv(DataStruct2, Mode, UnitsFlag, 'Struct');
catch
    RawY.Data = NaN*zeros(size(DataStruct2.Data,1),1);
    RawY.Units = DataStruct2.Units;
    RawY.UnitsString = DataStruct2.UnitsString;
    RawY.Mode = Mode;
    RawY.TimeStamp = clock;
    fprintf('\n%s\n', lasterr);
    fprintf('   %s, GETPV trouble in family %s\n', sprintf('%s',datestr(RawY.TimeStamp,14)), DataStruct2.FamilyName);
end
setappdata(handles.figure1, 'RawY', RawY);
% % For non-BPM the offset (ie, the setpoint) may have changed
% if ~isempty(getfamilydata(DataStruct1.FamilyName,'Setpoint'))
%     % Update the offset to the setpoint
%     setappdata(handles.figure1,'OffsetX', getsp(DataStruct1.FamilyName, Mode, DataStruct1.Units, 'Struct'));
% end
% if ~isempty(getfamilydata(DataStruct2.FamilyName,'Setpoint'))
%     % Update the offset to the setpoint
%     setappdata(handles.figure1,'OffsetY', getsp(DataStruct2.FamilyName, Mode, DataStruct2.Units, 'Struct'));
% end
% Update time
set(handles.Time, 'String', sprintf('%s',datestr(RawY.TimeStamp,14)));
plotappdatalocal(handles);
drawnow;
function plotappdatalocal(handles)
if strcmpi(get(handles.Simulate,'Checked'),'On')
    Mode = 'Simulator';
else
    Mode = 'Online';
end
% Get data from appdata
Trace1 = getappdata(handles.figure1,'Trace1');
Trace2 = getappdata(handles.figure1,'Trace2');
UnitsFlag = getappdata(handles.figure1,'UnitsFlag');
DataStruct1 = getappdata(handles.figure1, 'BPMxFamily');
1000 DataStruct2 = getappdata(handles.figure1, 'BPMyFamily');
1001
1002 RawX = getappdata(handles.figure1, 'RawX');
1003 RawY = getappdata(handles.figure1, 'RawY');
1004
1005 sx = getappdata(handles.figure1, 'SPosX');
1006 sy = getappdata(handles.figure1, 'SPosY');
1007
1008 if isempty(sx)
1009     error(sprintf('Position along ring information not available for %s family.', RawX.FamilyName));
1010     %sx = 1:size(RawX.Data,1);
1011 end
1012 if isempty(sy)
1013     error(sprintf('Position along ring information not available for %s family.', RawY.FamilyName));
1014     %sy = 1:size(RawY.Data,1);
1015 end
1016
1017 ChannelA = getappdata(handles.figure1, 'ChannelA');
1018 ChannelB = getappdata(handles.figure1, 'ChannelB');
1019
1020 if Trace1 == 1 || Trace1 == 3 || Trace2 == 1 || Trace2 == 3
1021     if ChannelA == 1
1022         DataA1 = RawX.Data;
1023         DataA2 = RawY.Data;
1024     elseif ChannelA == 2
1025         %DataA1 = getappdata(handles.figure1,'GoldenX');
1026         %DataA1 = DataA1.Data;
1027         %DataA2 = getappdata(handles.figure1,'GoldenY');
1028         %DataA2 = DataA2.Data;
1029
1030         if strcmpi(DataStruct1.Field, 'Monitor') && ~isempty(getfamilydata(DataStruct1.FamilyName,'Setpoint'))
1031             % Display the setpoint golden value
1032             DataA1 = getgolden(DataStruct1, 'Setpoint', DataStruct1.Units, 'Numeric');
1033         else
1034             DataA1 = getgolden(DataStruct1, DataStruct1.Units, 'Numeric');
1035         end
1036
1037         if strcmpi(DataStruct2.Field, 'Monitor') && ~isempty(getfamilydata(DataStruct2.FamilyName,'Setpoint'))
1038             % Display the setpoint golden value
1039             DataA2 = getgolden(DataStruct2, 'Setpoint', DataStruct2.Units, 'Numeric');
1040         else
1041             DataA2 = getgolden(DataStruct2, DataStruct2.Units, 'Numeric');
1042         end
1043
1044     elseif ChannelA == 3
1045         %DataA1 = getappdata(handles.figure1,'OffsetX');
1046         %DataA1 = DataA1.Data;
1047         %DataA2 = getappdata(handles.figure1,'OffsetY');
1048         %DataA2 = DataA2.Data;
1049
1050         if strcmpi(DataStruct1.Field, 'Monitor') && ~isempty(getfamilydata(DataStruct1.FamilyName,'Setpoint'))
1051             % Update the offset to the setpoint
1052             DataA1 = getsp(DataStruct1, Mode, DataStruct1.Units, 'Numeric');
1053         else
1054             DataA1 = getoffset(DataStruct1, DataStruct1.Units, 'Numeric');
1055         end
1056
1057         if strcmpi(DataStruct2.Field, 'Monitor') && ~isempty(getfamilydata(DataStruct2.FamilyName,'Setpoint'))
1058             % Update the offset to the setpoint
1059             DataA2 = getsp(DataStruct2, Mode, DataStruct2.Units, 'Numeric');
1060         else
1061             DataA2 = getoffset(DataStruct2, DataStruct2.Units, 'Numeric');
1062         end
1063
1064     elseif ChannelA == 4
1065         DataA1 = getappdata(handles.figure1,'SaveX');
1066         DataA1 = DataA1.Data;
1067         DataA2 = getappdata(handles.figure1,'SaveY');
1068         DataA2 = DataA2.Data;
1069     elseif ChannelA == 5
1070         DataA1 = getappdata(handles.figure1,'FileX');
1071         DataA1 = DataA1.Data;
1072         DataA2 = getappdata(handles.figure1,'FileY');
1073         DataA2 = DataA2.Data;
1074     else
1075         DataA1 = zeros(size(BPMxList,1),1);
1076         DataA2 = zeros(size(BPMyList,1),1);
1077     end
1078 end
1079
1080 if Trace1 == 2 || Trace1 == 3 || Trace2 == 2 || Trace2 == 3
1081     if ChannelB == 1
1082         DataB1 = RawX.Data;
1083         DataB2 = RawY.Data;
1084     elseif ChannelB == 2
1085         %DataB1 = getappdata(handles.figure1,'GoldenX');
1086         %DataB1 = DataB1.Data;
1087         %DataB2 = getappdata(handles.figure1,'GoldenY');
1088         %DataB2 = DataB2.Data;
1089
1090         if strcmpi(DataStruct1.Field, 'Monitor') && ~isempty(getfamilydata(DataStruct1.FamilyName,'Setpoint'))
1091             % Display the setpoint golden value
1092             DataB1 = getgolden(DataStruct1, 'Setpoint', DataStruct1.Units, 'Numeric');
1093         else
1094             DataB1 = getgolden(DataStruct1, DataStruct1.Units, 'Numeric');
1095         end
1096
1097         if strcmpi(DataStruct2.Field, 'Monitor') && ~isempty(getfamilydata(DataStruct2.FamilyName,'Setpoint'))
1098             % Display the setpoint golden value
1099             DataB2 = getgolden(DataStruct2, 'Setpoint', DataStruct2.Units, 'Numeric');
1100         else
1101             DataB2 = getgolden(DataStruct2, DataStruct2.Units, 'Numeric');
1102         end
1103
1104     elseif ChannelB == 3
1105         %DataB1 = getappdata(handles.figure1,'OffsetX');
1106         %DataB1 = DataB1.Data;
1107         %DataB2 = getappdata(handles.figure1,'OffsetY');
1108         %DataB2 = DataB2.Data;
1109
1110         if strcmpi(DataStruct1.Field, 'Monitor') && ~isempty(getfamilydata(DataStruct1.FamilyName,'Setpoint'))
1111             % Update the offset to the setpoint
1112             DataB1 = getsp(DataStruct1.FamilyName, DataStruct1.DeviceList, Mode, DataStruct1.Units, 'Numeric');
1113         else
1114             DataB1 = getoffset(DataStruct1, DataStruct1.DeviceList, DataStruct1.Units, 'Numeric');
1115         end
1116
1117         if strcmpi(DataStruct2.Field, 'Monitor') && ~isempty(getfamilydata(DataStruct2.FamilyName,'Setpoint'))
1118             % Update the offset to the setpoint
1119             DataB2 = getsp(DataStruct2, Mode, DataStruct2.Units, 'Numeric');
1120         else
1121             DataB2 = getoffset(DataStruct2, DataStruct2.Units, 'Numeric');
1122         end
1123     elseif ChannelB == 4
1124         DataB1 = getappdata(handles.figure1,'SaveX');
1125         DataB1 = DataB1.Data;
1126
1127         DataB2 = getappdata(handles.figure1,'SaveY');
1128         DataB2 = DataB2.Data;
1129
1130     elseif ChannelB == 5
1131         DataB1 = getappdata(handles.figure1,'FileX');
1132         DataB1 = DataB1.Data;
1133         DataB2 = getappdata(handles.figure1,'FileY');
1134         DataB2 = DataB2.Data;
1135     else
1136         DataB1 = zeros(size(BPMxList,1),1);
1137         DataB2 = zeros(size(BPMyList,1),1);
1138     end
1139 end
1140
1141
1142 % First line
1143 if Trace1 == 1
1144     Data1 = DataA1;
1145     Data2 = DataA2;
1146 elseif Trace1 == 2
1147     Data1 = DataB1;
1148     Data2 = DataB2;
1149 elseif Trace1 == 3
1150     Data1 = DataA1 - DataB1;
1151     Data2 = DataA2 - DataB2;
1152 end
1153
1154
1155 % Second line
1156 if Trace2 == 4
1157     Data3 = NaN * Data1;
1158     Data4 = NaN * Data2;
1159 else
1160     if Trace2 == 1
1161         Data3 = DataA1;
1162         Data4 = DataA2;
1163     elseif Trace2 == 2
1164         Data3 = DataB1;
1165         Data4 = DataB2;
1166     elseif Trace2 == 3
1167         Data3 = DataA1 - DataB1;
1168         Data4 = DataA2 - DataB2;
1169     end
1170 end
1171
1172
1173
1174 % if UnitsFlag == 1 && strcmpi(RawX.Units,'Hardware')
1175 %     % Physics units requested, data is in Hardware units
1176 %     Data1 = hw2physics(BPMxFamily, 'Monitor', Data1);
1177 %     Data2 = hw2physics(BPMyFamily, 'Monitor', Data2);
1178 %     Data3 = hw2physics(BPMxFamily, 'Monitor', Data3);
1179 %     Data4 = hw2physics(BPMyFamily, 'Monitor', Data4);
1180 % elseif (UnitsFlag==2 | UnitsFlag==3) && strcmpi(RawX.Units,'Physics')
1181 %     % Hardware units requested, data is in Physics units
1182 %     Data1 = physics2hw(BPMxFamily, 'Monitor', Data1);
1183 %     Data2 = physics2hw(BPMyFamily, 'Monitor', Data2);
1184 %     Data3 = physics2hw(BPMxFamily, 'Monitor', Data3);
1185 %     Data4 = physics2hw(BPMyFamily, 'Monitor', Data4);
1186 % end
1187
1188 UnitsString1 = DataStruct1.UnitsString;
1189 UnitsString2 = DataStruct2.UnitsString;
1190 % if UnitsFlag == 1
1191 %     % Physics units
1192 %     UnitsString1 = getfamilydata(DataStruct1.FamilyName, DataStruct1.Field, 'PhysicsUnits');
1193 %     UnitsString2 = getfamilydata(DataStruct2.FamilyName, DataStruct2.Field, 'PhysicsUnits');
1194 % elseif UnitsFlag == 2
1195 %     % Hardware units
1196 %     UnitsString1 = getfamilydata(DataStruct1.FamilyName, DataStruct1.Field, 'HWUnits');
1197 %     UnitsString2 = getfamilydata(DataStruct2.FamilyName, DataStruct2.Field, 'HWUnits');
1198 if UnitsFlag == 3
1199     % Hardware units time 1000
1200     Data1 = 1000 * Data1;
1201     Data2 = 1000 * Data2;
1202     Data3 = 1000 * Data3;
1203     Data4 = 1000 * Data4;
1204     %UnitsString1 = getfamilydata(DataStruct1.FamilyName, DataStruct1.Field, 'HWUnits');
1205     %UnitsString2 = getfamilydata(DataStruct2.FamilyName, DataStruct2.Field, 'HWUnits');
1206     if strcmpi(UnitsString1,'mm')
1207         UnitsString1 = '\mum';
1208     else
1209         %UnitsString1 = ['1000x', UnitsString1];
1210         UnitsString1 = ['milli', UnitsString1];
1211     end
1212     if strcmpi(UnitsString2,'mm')
1213         UnitsString2 = '\mum';
1214     else
1215         %UnitsString2 = ['1000x', UnitsString2];
1216         UnitsString2 = ['milli', UnitsString2];
1217     end
1218 end
1219
1220
1221 % Axes 1
1222 h = get(handles.Graph1,'Children');
1223 AxisRange1X = getappdata(handles.figure1, 'AxisRange1X');
1224
1225 % Bar graph setup
1226 if strcmpi(get(handles.Graph1Bar,'Checked'),'On')
1227     %  #pts  BarWidth
1228     Table = [
1229         0    .01
1230         24    .025
1231         48    .05
1232         120   .10
1233         1000  .3
1234         3000  .40
1235         1e5   .50
1236         ];
1237     L = getfamilydata('Circumference');
1238     WidthScaleFactor = interp1(Table(:,1), Table(:,2), length(Data1), 'linear');
1239     WidthScaleFactor = WidthScaleFactor * (L/length(sx)) / min(diff(sx));
1240 end
1241
1242 % Don't change the axis (unless it's the first time)
1243 if isempty(h)
1244     cla(handles.Graph1);
1245     if strcmpi(get(handles.Graph1Bar,'Checked'),'On')
1246         % Bar graph
1247         h(1) = bar(handles.Graph1, sx, Data1(:), WidthScaleFactor);
1248         hold(handles.Graph1, 'on');
1249         h(2) = bar(handles.Graph1, sx, Data3(:), WidthScaleFactor/2);
1250         hold(handles.Graph1, 'off');
1251         set(h(1),'FaceColor','b');
1252         set(h(1),'EdgeColor','b');
1253         if get(handles.Trace2Off, 'Value')
1254             set(h(2),'FaceColor','k');
1255             set(h(2),'EdgeColor','k');
1256         else
1257             set(h(2),'FaceColor','r');
1258             set(h(2),'EdgeColor','r');
1259         end
1260     else
1261         h = plot(handles.Graph1, sx, [Data1(:) Data3(:)],'.-');
1262         set(h(1),'Color','b');
1263         set(h(2),'Color','r');
1264     end
1265
1266     % plot(handles.Graph1, sx, Data3,'squarer','MarkerSize',3);
1267     % plot(handles.Graph1, sx, Data1,'squareb','MarkerSize',3);
1268
1269     % Set defaults
1270     set(handles.Graph1, 'Nextplot',      'Add');
1271     set(handles.Graph1, 'YGrid',         'On');
1272     set(handles.Graph1, 'YMinorTick',    'On');
1273     set(handles.Graph1, 'XMinorTick',    'On');
1274     set(handles.Graph1, 'XAxisLocation', 'Bottom');
1275     set(handles.Graph1, 'XTickLabel',    '');
1276
1277     a = axis(handles.Graph1);
1278     axis(handles.Graph1, [AxisRange1X(1) AxisRange1X(2) a(3) a(4)]);
1279
1280     if strcmpi(get(handles.('YScaleLog1'),'Checked'),'On')
1281         set(handles.Graph1,'YScale','Log');
1282     else
1283         set(handles.Graph1,'YScale','Linear');
1284     end
1285
1286     set(handles.Graph1 ,'ButtonDownFcn','plotfamily(''Graph1_ButtonDown'',gcbo,[],guidata(gcbo))');
1287     h = get(handles.Graph1,'Children');
1288     for i = 1:length(h)
1289         set(h(i) ,'ButtonDownFcn','plotfamily(''Graph1_ButtonDown'',gcbo,[],guidata(gcbo))');
1290     end
1291 else
1292     % This fixes a weird error with srcontrol
1293     h = sort(h(end-1:end));
1294
1295     a = axis(handles.Graph1);
1296     set(h(1), 'XData', sx, 'YData', Data1);
1297     set(h(2), 'XData', sx, 'YData', Data3);
1298
1299     if strcmpi(get(handles.Graph1Bar,'Checked'),'On')
1300         set(h(1),'BarWidth',WidthScaleFactor);
1301         set(h(2),'BarWidth',WidthScaleFactor/2);
1302         if get(handles.Trace2Off, 'Value')
1303             set(h(2),'FaceColor','k');
1304             set(h(2),'EdgeColor','k');
1305         else
1306             set(h(2),'FaceColor','r');
1307             set(h(2),'EdgeColor','r');
1308         end
1309     end
1310
1311     axis(handles.Graph1, [AxisRange1X(1) AxisRange1X(2) a(3) a(4)]);
1312 end
1313
1314 h_label=get(handles.Graph1,'ylabel');
1315
1316
1317 if strcmpi(DataStruct1.Field,'Monitor')
1318     if isempty(UnitsString1)
1319         set(h_label, 'String', sprintf('%s',      DataStruct1.FamilyName), 'Interpreter','None');
1320     elseif strcmpi(UnitsString1,'\mum')
1321         set(h_label, 'String', sprintf('%s [%s]', DataStruct1.FamilyName, UnitsString1), 'Interpreter','Tex');
1322     else
1323         set(h_label, 'String', sprintf('%s [%s]', DataStruct1.FamilyName, UnitsString1), 'Interpreter','None');
1324     end
1325 else
1326     if isempty(UnitsString1)
1327         set(h_label, 'String', sprintf('%s.%s',      DataStruct1.FamilyName, DataStruct1.Field), 'Interpreter','None');
1328     elseif strcmpi(UnitsString1,'\mum')
1329         set(h_label, 'String', sprintf('%s.%s [%s]', DataStruct1.FamilyName, DataStruct1.Field, UnitsString1), 'Interpreter','Tex');
1330     else
1331         set(h_label, 'String', sprintf('%s.%s [%s]', DataStruct1.FamilyName, DataStruct1.Field, UnitsString1), 'Interpreter','None');
1332     end
1333 end
1334
1335
1336 % Graph 3
1337 if strcmpi(get(handles.('AddPlot1_Nothing'),'Checked'),'Off')
1338     % Bring Graph 3 forward
1339     axes(handles.Graph3);
1340 end
1341
1342 % Remove NaN
1343 i = find(~isnan(Data1));
1344 if isempty(i)
1345     MeanString = '';
1346     RMSString  = '';
1347 else
1348     MeanString = sprintf('%+9.6e Mean', mean(Data1(i)));
1349     RMSString  = sprintf('%+9.6e RMS', (length(Data1(i))-1)*std(Data1(i))/length(Data1(i)));
1350 end
1351 set(handles.Trace1RMS,'String',{MeanString, RMSString});
1352 set(handles.Trace1RMS,'FontSize', 9);
1353
1354 % Set the list box
1355 Value = get(handles.DataList1, 'Value');
1356 set(handles.DataList1, 'Value', Value);
1357 ListBoxTop = get(handles.DataList1, 'ListBoxTop');
1358 set(handles.DataList1, 'String', [DataStruct1.ListBoxString, num2str(Data1(:),'%+.4e')]);
1359 set(handles.DataList1, 'ListBoxTop', ListBoxTop);
1360
1361
1362 % Axes 2
1363 h = get(handles.Graph2,'Children');
1364 AxisRange2X = getappdata(handles.figure1, 'AxisRange2X');
1365
1366 % Bar graph setup
1367 if strcmpi(get(handles.Graph2Bar,'Checked'),'On')
1368     %  #pts  BarWidth
1369     Table = [
1370         0    .01
1371         24    .025
1372         48    .05
1373         120   .10
1374         1000  .3
1375         3000  .40
1376         1e5   .50
1377         ];
1378     L = getfamilydata('Circumference');
1379     WidthScaleFactor = interp1(Table(:,1), Table(:,2), length(Data2), 'linear');
1380     WidthScaleFactor = WidthScaleFactor * (L/length(sy)) / min(diff(sy));
1381 end
1382
1383
1384 if isempty(h)
1385     cla(handles.Graph2);
1386     if strcmpi(get(handles.Graph2Bar,'Checked'),'On')
1387         % Bar graph
1388         h(1) = bar(handles.Graph2, sy, Data2(:), WidthScaleFactor);
1389         hold(handles.Graph2, 'on');
1390         h(2) = bar(handles.Graph2, sy, Data4(:), WidthScaleFactor/2);
1391         hold(handles.Graph2, 'off');
1392         set(h(1),'FaceColor','b');
1393         set(h(1),'EdgeColor','b');
1394         if get(handles.Trace2Off, 'Value')
1395             set(h(2),'FaceColor','k');
1396             set(h(2),'EdgeColor','k');
1397         else
1398             set(h(2),'FaceColor','r');
1399             set(h(2),'EdgeColor','r');
1400         end
1401     else
1402         h = plot(handles.Graph2, sy, [Data2(:) Data4(:)],'.-');
1403         set(h(1),'Color','b');
1404         set(h(2),'Color','r');
1405     end
1406
1407     % Set defaults
1408     set(handles.Graph2, 'Nextplot',      'Add');
1409     set(handles.Graph2, 'YGrid',         'On');
1410     set(handles.Graph2, 'YMinorTick',    'On');
1411     set(handles.Graph2, 'XMinorTick',    'On');
1412     set(handles.Graph2, 'XAxisLocation', 'Bottom');
1413
1414     a = axis(handles.Graph2);
1415     axis(handles.Graph2, [AxisRange2X(1) AxisRange2X(2) a(3) a(4)])
1416
1417     if strcmpi(get(handles.('YScaleLog2'),'Checked'),'On')
1418         set(handles.Graph2,'YScale','Log');
1419     else
1420         set(handles.Graph2,'YScale','Linear');
1421     end
1422
1423     set(handles.Graph2 ,'ButtonDownFcn','plotfamily(''Graph2_ButtonDown'',gcbo,[],guidata(gcbo))');
1424     h = get(handles.Graph2,'Children');
1425     for i = 1:length(h)
1426         set(h(i) ,'ButtonDownFcn','plotfamily(''Graph2_ButtonDown'',gcbo,[],guidata(gcbo))');
1427     end
1428 else
1429     % This fixes a weird error with srcontrol
1430     h = sort(h(end-1:end));
1431
1432     a = axis(handles.Graph2);
1433     set(h(1), 'XData', sy, 'YData', Data2);
1434     set(h(2), 'XData', sy, 'YData', Data4);
1435
1436     if strcmpi(get(handles.Graph2Bar,'Checked'),'On')
1437         set(h(1),'BarWidth',WidthScaleFactor);
1438         set(h(2),'BarWidth',WidthScaleFactor/2);
1439         if get(handles.Trace2Off, 'Value')
1440             set(h(2),'FaceColor','k');
1441             set(h(2),'EdgeColor','k');
1442         else
1443             set(h(2),'FaceColor','r');
1444             set(h(2),'EdgeColor','r');
1445         end
1446     end
1447
1448     %% Add the model orbit to the plot
1449     %[x, y, sx, sy] = modeltwiss('x', 'All');
1450     %h4 = get(handles.Graph4,'children');
1451     %set(h4, 'XData', sx, 'YData', x);
1452     %axis(h4, [AxisRange2X(1) AxisRange2X(2) a(3) a(4)]);
1453
1454     axis(handles.Graph2, [AxisRange2X(1) AxisRange2X(2) a(3) a(4)]);
1455 end
1456
1457 h_label = get(handles.Graph2,'ylabel');
1458 if strcmpi(DataStruct2.Field,'Monitor')
1459     if isempty(UnitsString2)
1460         set(h_label, 'String', sprintf('%s',      DataStruct2.FamilyName), 'Interpreter','None');
1461     elseif strcmpi(UnitsString2,'\mum')
1462         set(h_label, 'String', sprintf('%s [%s]', DataStruct2.FamilyName, UnitsString2), 'Interpreter','Tex');
1463     else
1464         set(h_label, 'String', sprintf('%s [%s]', DataStruct2.FamilyName, UnitsString2), 'Interpreter','None');
1465     end
1466 else
1467     if isempty(UnitsString2)
1468         set(h_label, 'String', sprintf('%s.%s',      DataStruct2.FamilyName, DataStruct2.Field), 'Interpreter','None');
1469     elseif strcmpi(UnitsString2,'\mum')
1470         set(h_label, 'String', sprintf('%s.%s [%s]', DataStruct2.FamilyName, DataStruct2.Field, UnitsString2), 'Interpreter','Tex');
1471     else
1472         set(h_label, 'String', sprintf('%s.%s [%s]', DataStruct2.FamilyName, DataStruct2.Field, UnitsString2), 'Interpreter','None');
1473     end
1474 end
1475
1476
1477 % Graph 4
1478 if strcmpi(get(handles.('AddPlot2_Nothing'),'Checked'),'Off')
1479     % Bring Graph 4 forward
1480     axes(handles.Graph4);
1481 end
1482
1483
1484 % Set the list box header
1485 i = find(~isnan(Data2));
1486 if isempty(i)
1487     MeanString = '';
1488     RMSString  = '';
1489 else
1490     MeanString = sprintf('%+9.6e Mean', mean(Data2(i)));
1491     RMSString  = sprintf('%+9.6e RMS', (length(Data2(i))-1)*std(Data2(i))/length(Data2(i)));
1492 end
1493 set(handles.Trace2RMS,'String',{MeanString, RMSString});
1494 set(handles.Trace2RMS,'FontSize', 9);
1495
1496
1497 % Set the list box
1498 Value = get(handles.DataList2,'Value');
1499 set(handles.DataList2,'Value', Value);
1500 ListBoxTop = get(handles.DataList2,'ListBoxTop');
1501 set(handles.DataList2,'String', [DataStruct2.ListBoxString, num2str(Data2(:),'%+.4e')]);
1502 set(handles.DataList2, 'ListBoxTop', ListBoxTop);
1503
1504
1505
1506 % --- Executes on button press in RawOrbit1.
1507 function RawOrbit1_Callback(hObject, eventdata, handles)
1508 set(handles.RawOrbit1,'Value', 1);
1509 set(handles.GoldenOrbit1,'Value', 0);
1510 set(handles.OffsetOrbit1,'Value', 0);
1511 set(handles.SaveOrbit1,'Value', 0);
1512 set(handles.FileOrbit1,'Value', 0);
1513 setappdata(handles.figure1, 'ChannelA', 1);
1514 plotappdatalocal(handles);
1515 %AutoScaleYLocal(handles);
1516
1517 % --- Executes on button press in GoldenOrbit1.
1518 function GoldenOrbit1_Callback(hObject, eventdata, handles)
1519 set(handles.RawOrbit1,'Value', 0);
1520 set(handles.GoldenOrbit1,'Value', 1);
1521 set(handles.OffsetOrbit1,'Value', 0);
1522 set(handles.SaveOrbit1,'Value', 0);
1523 set(handles.FileOrbit1,'Value', 0);
1524 setappdata(handles.figure1, 'ChannelA', 2);
1525 plotappdatalocal(handles);
1526 %AutoScaleYLocal(handles);
1527
1528 % --- Executes on button press in OffsetOrbit1.
1529 function OffsetOrbit1_Callback(hObject, eventdata, handles)
1530 set(handles.RawOrbit1,'Value', 0);
1531 set(handles.GoldenOrbit1,'Value', 0);
1532 set(handles.OffsetOrbit1,'Value', 1);
1533 set(handles.SaveOrbit1,'Value', 0);
1534 set(handles.FileOrbit1,'Value', 0);
1535 setappdata(handles.figure1, 'ChannelA', 3);
1536 plotappdatalocal(handles);
1537 %AutoScaleYLocal(handles);
1538
1539 % --- Executes on button press in SaveOrbit1.
1540 function SaveOrbit1_Callback(hObject, eventdata, handles)
1541 set(handles.RawOrbit1,'Value', 0);
1542 set(handles.GoldenOrbit1,'Value', 0);
1543 set(handles.OffsetOrbit1,'Value', 0);
1544 set(handles.SaveOrbit1,'Value', 1);
1545 set(handles.FileOrbit1,'Value', 0);
1546 setappdata(handles.figure1, 'ChannelA', 4);
1547 plotappdatalocal(handles);
1548 %AutoScaleYLocal(handles);
1549
1550 % --- Executes on button press in FileOrbit1.
1551 function FileOrbit1_Callback(hObject, eventdata, handles)
1552 set(handles.RawOrbit1,'Value', 0);
1553 set(handles.GoldenOrbit1,'Value', 0);
1554 set(handles.OffsetOrbit1,'Value', 0);
1555 set(handles.SaveOrbit1,'Value', 0);
1556 set(handles.FileOrbit1,'Value', 1);
1557 setappdata(handles.figure1, 'ChannelA', 5);
1558 plotappdatalocal(handles);
1559 %AutoScaleYLocal(handles);
1560
1561
1562 % --- Executes on button press in RawOrbit2.
1563 function RawOrbit2_Callback(hObject, eventdata, handles)
1564 set(handles.RawOrbit2,'Value', 1);
1565 set(handles.GoldenOrbit2,'Value', 0);
1566 set(handles.OffsetOrbit2,'Value', 0);
1567 set(handles.SaveOrbit2,'Value', 0);
1568 set(handles.FileOrbit2,'Value', 0);
1569 setappdata(handles.figure1, 'ChannelB', 1);
1570 plotappdatalocal(handles);
1571 %AutoScaleYLocal(handles);
1572
1573 % --- Executes on button press in GoldenOrbit2.
1574 function GoldenOrbit2_Callback(hObject, eventdata, handles)
1575 set(handles.RawOrbit2,'Value', 0);
1576 set(handles.GoldenOrbit2,'Value', 1);
1577 set(handles.OffsetOrbit2,'Value', 0);
1578 set(handles.SaveOrbit2,'Value', 0);
1579 set(handles.FileOrbit2,'Value', 0);
1580 setappdata(handles.figure1, 'ChannelB', 2);
1581 plotappdatalocal(handles);
1582 %AutoScaleYLocal(handles);
1583
1584 % --- Executes on button press in OffsetOrbit2.
1585 function OffsetOrbit2_Callback(hObject, eventdata, handles)
1586 set(handles.RawOrbit2,'Value', 0);
1587 set(handles.GoldenOrbit2,'Value', 0);
1588 set(handles.OffsetOrbit2,'Value', 1);
1589 set(handles.SaveOrbit2,'Value', 0);
1590 set(handles.FileOrbit2,'Value', 0);
1591 setappdata(handles.figure1, 'ChannelB', 3);
1592 plotappdatalocal(handles);
1593 %AutoScaleYLocal(handles);
1594
1595 % --- Executes on button press in SaveOrbit2.
1596 function SaveOrbit2_Callback(hObject, eventdata, handles)
1597 set(handles.RawOrbit2,'Value', 0);
1598 set(handles.GoldenOrbit2,'Value', 0);
1599 set(handles.OffsetOrbit2,'Value', 0);
1600 set(handles.SaveOrbit2,'Value', 1);
1601 set(handles.FileOrbit2,'Value', 0);
1602 setappdata(handles.figure1, 'ChannelB', 4);
1603 plotappdatalocal(handles);
1604 %AutoScaleYLocal(handles);
1605
1606 % --- Executes on button press in FileOrbit2.
1607 function FileOrbit2_Callback(hObject, eventdata, handles)
1608 set(handles.RawOrbit2,'Value', 0);
1609 set(handles.GoldenOrbit2,'Value', 0);
1610 set(handles.OffsetOrbit2,'Value', 0);
1611 set(handles.SaveOrbit2,'Value', 0);
1612 set(handles.FileOrbit2,'Value', 1);
1613 setappdata(handles.figure1, 'ChannelB', 5);
1614 plotappdatalocal(handles);
1615 %AutoScaleYLocal(handles);
1616
1617 % --- Executes on button press in SaveOrbit1Now.
1618 function SaveOrbit1Now_Callback(hObject, eventdata, handles)
1619 RawX = getappdata(handles.figure1,'RawX');
1620 RawY = getappdata(handles.figure1,'RawY');
1621 setappdata(handles.figure1,'SaveX', RawX);
1622 setappdata(handles.figure1,'SaveY', RawY);
1623 if isfield(RawY,'TimeStamp')
1624     set(handles.SaveTime,'String', sprintf('%s',datestr(RawY.TimeStamp,0)));
1625 else
1626     set(handles.SaveTime,'String', sprintf('%s',datestr(clock,0)));
1627 end
1628 plotappdatalocal(handles);
1629 %AutoScaleYLocal(handles);
1630
1631
1632 % --- Executes on button press in LoadOrbit1.
1633 function LoadOrbit1_Callback(hObject, eventdata, handles)
1634 UnitMenu = getappdata(handles.figure1,'UnitsFlag');
1635 if UnitMenu == 1
1636     UnitsFlag = 'Physics';
1637 else
1638     UnitsFlag = 'Hardware';
1639 end
1640
1641 DataStruct1 = getappdata(handles.figure1, 'BPMxFamily');
1642 DataStruct2 = getappdata(handles.figure1, 'BPMyFamily');
1643
1644 DirectoryName = getfamilydata('Directory','DataRoot');
1645 %DirectoryName = getfamilydata('Directory', 'BPMData');
1646 %FileNameX = getfamilydata('Default', 'BPMFile');
1647 [FileName, DirectoryName] = uigetfile('*.mat', 'Select a File', DirectoryName);
1648 if FileName == 0
1649     return
1650 end
1651
1652 % Remove .mat
1653 %if strcmpi(FileNameX(end-3:end), '.mat')
1654 %    FileNameX = FileNameX(1:end-4);
1655 %end
1656
1657 % Graph 1
1658 try
1659     DataStruct = getdata(DataStruct1, [DirectoryName FileName], 'Struct');
1660     if UnitMenu == 1 && strcmpi(DataStruct.Units,'Hardware')
1661         % Physics units requested
1662         DataStruct = hw2physics(DataStruct);
1663     elseif (UnitMenu==2 || UnitMenu==3) && strcmpi(DataStruct.Units,'Physics')
1664         % Hardware units requested, data is in Physics units
1665         DataStruct = physics2hw(DataStruct);
1666     end
1667     setappdata(handles.figure1, 'FileX', DataStruct);
1668     setappdata(handles.figure1, 'FileNameX', [DirectoryName FileName]);
1669 catch
1670 end
1671
1672 % Graph 2
1673 try
1674     DataStruct = getdata(DataStruct2, [DirectoryName FileName], 'Struct');
1675     if UnitMenu == 1 && strcmpi(DataStruct.Units,'Hardware')
1676         % Physics units requested
1677         DataStruct = hw2physics(DataStruct);
1678     elseif (UnitMenu==2 || UnitMenu==3) && strcmpi(DataStruct.Units,'Physics')
1679         % Hardware units requested, data is in Physics units
1680         DataStruct = physics2hw(DataStruct);
1681     end
1682     setappdata(handles.figure1, 'FileY', DataStruct);
1683     setappdata(handles.figure1, 'FileNameY', [DirectoryName FileName]);
1684 catch
1685 end
1686
1687 plotappdatalocal(handles);
1688 %AutoScaleYLocal(handles);
1689 UpdateFileDisplayLocal(handles);
1690
1691
1692 % --- local function to update filenamex on the display.
1693 function UpdateFileDisplayLocal(handles)
1694
1695 FileNameX = getappdata(handles.figure1, 'FileNameX');
1696 FileNameY = getappdata(handles.figure1, 'FileNameY');
1697
1698 if isempty(FileNameX) && isempty(FileNameY)
1699     set(handles.FileNameX,'String', '');
1700     set(handles.FileNameY,'String', '');
1701     drawnow;
1702     return;
1703 end
1704
1705 if ~isempty(FileNameX)
1706     % Remove directories
1707     i = findstr(FileNameX, filesep);
1708     if ~isempty(i)
1709         FileNameX = FileNameX(i(end)+1:end);
1710     end
1711
1712     % Shorten length
1713     if length(FileNameX) >= 31
1714         % Remove .mat
1715         if strcmpi(FileNameX(end-3:end),'.mat')
1716             FileNameX = FileNameX(1:end-4);  % remove .mat
1717         end
1718
1719         if length(FileNameX) >= 31
1720             FileNameX = FileNameX(1:31);
1721         end
1722     end
1723
1724     %set(handles.FileNameX,'String', sprintf('File 1: %s', FileNameX));
1725     set(handles.FileNameX,'String', sprintf('%s', FileNameX));
1726 else
1727     set(handles.FileNameX,'String', 'File 1: no data');
1728 end
1729
1730 if ~isempty(FileNameY)
1731     % Remove directories
1732     i = findstr(FileNameY,filesep);
1733     if ~isempty(i)
1734         FileNameY = FileNameY(i(end)+1:end);
1735     end
1736
1737     % Shorten length
1738     if length(FileNameY) >= 31
1739         % Remove .mat
1740         if strcmpi(FileNameY(end-3:end),'.mat')
1741             FileNameY = FileNameY(1:end-4);  % remove .mat
1742         end
1743         if length(FileNameY) >= 31
1744             FileNameY = FileNameY(1:31);
1745         end
1746     end
1747
1748     %set(handles.FileNameY,'String', sprintf('File 2: %s', FileNameY));
1749     set(handles.FileNameY,'String', sprintf('%s', FileNameY));
1750 else
1751     set(handles.FileNameY,'String', 'File 2: no data');
1752 end
1753
1754 if strcmpi(FileNameX, FileNameY) && ~isempty(FileNameX)
1755     set(handles.FileNameY,'Visible','off');
1756     set(handles.FileNameX,'String', sprintf('%s', FileNameX));
1757     p = get(handles.FileNameX,'Position');
1758     %set(handles.FileNameX,'Position', [p(1) 4 p(3) p(4)]);   % Points
1759     %set(handles.FileNameX,'Position', [p(1) .4 p(3) p(4)]);  % Characters
1760     set(handles.FileNameX,'Position', [p(1) 0.02 p(3) p(4)]); % Normalized
1761     p = get(handles.SaveTime,'Position');
1762     %set(handles.SaveTime,'Position', [p(1) 16.5 p(3) p(4)]);   % Points
1763     %set(handles.SaveTime,'Position', [p(1) 1.6 p(3) p(4)]);    % Characters
1764     set(handles.SaveTime,'Position', [p(1) 0.052 p(3) p(4)]);   % Normalized
1765 else
1766     p = get(handles.FileNameX,'Position');
1767     %set(handles.FileNameX,'Position', [p(1) 10 p(3) p(4)]);  % Points
1768     %set(handles.FileNameX,'Position', [p(1) 1.1 p(3) p(4)]);  % Characters
1769     set(handles.FileNameX,'Position', [p(1) 0.025 p(3) p(4)]);  % Normalized
1770     set(handles.FileNameY,'Visible','on');
1771     p = get(handles.SaveTime,'Position');
1772     %set(handles.SaveTime,'Position', [p(1) 20 p(3) p(4)]);  % Points
1773     %set(handles.SaveTime,'Position', [p(1) 2.0 p(3) p(4)]);  % Characters
1774     set(handles.SaveTime,'Position', [p(1) 0.055 p(3) p(4)]);  % Normalized
1775 end
1776
1777 drawnow;
1778
1779
1780 % --- Executes on button press in Display1.
1781 function Display1_Callback(hObject, eventdata, handles)
1782 set(handles.DisplayDiff,'Value', 0);
1783 set(handles.Display1,'Value', 1);
1784 set(handles.Display2,'Value', 0);
1785 setappdata(handles.figure1,'Trace1',1);
1786 plotappdatalocal(handles);
1787 %AutoScaleYLocal(handles);
1788
1789 % --- Executes on button press in Display2.
1790 function Display2_Callback(hObject, eventdata, handles)
1791 set(handles.DisplayDiff,'Value', 0);
1792 set(handles.Display1,'Value', 0);
1793 set(handles.Display2,'Value', 1);
1794 setappdata(handles.figure1,'Trace1',2);
1795 plotappdatalocal(handles);
1796 %AutoScaleYLocal(handles);
1797
1798 % --- Executes on button press in DisplayDiff.
1799 function DisplayDiff_Callback(hObject, eventdata, handles)
1800 set(handles.DisplayDiff,'Value', 1);
1801 set(handles.Display1,'Value', 0);
1802 set(handles.Display2,'Value', 0);
1803 setappdata(handles.figure1,'Trace1',3);
1804 plotappdatalocal(handles);
1805 %AutoScaleYLocal(handles);
1806
1807
1808 % --- Executes on button press in Trace2A.
1809 function Trace2A_Callback(hObject, eventdata, handles)
1810 set(handles.Trace2A,'Value', 1);
1811 set(handles.Trace2B,'Value', 0);
1812 set(handles.Trace2A_B,'Value', 0);
1813 set(handles.Trace2Off,'Value', 0);
1814 setappdata(handles.figure1,'Trace2',1);
1815 plotappdatalocal(handles);
1816 %AutoScaleYLocal(handles);
1817
1818 % --- Executes on button press in Trace2B.
1819 function Trace2B_Callback(hObject, eventdata, handles)
1820 set(handles.Trace2A,'Value', 0);
1821 set(handles.Trace2B,'Value', 1);
1822 set(handles.Trace2A_B,'Value', 0);
1823 set(handles.Trace2Off,'Value', 0);
1824 setappdata(handles.figure1,'Trace2',2);
1825 plotappdatalocal(handles);
1826 %AutoScaleYLocal(handles);
1827
1828 % --- Executes on button press in Trace2A_B.
1829 function Trace2A_B_Callback(hObject, eventdata, handles)
1830 set(handles.Trace2A,'Value', 0);
1831 set(handles.Trace2B,'Value', 0);
1832 set(handles.Trace2A_B,'Value', 1);
1833 set(handles.Trace2Off,'Value', 0);
1834 setappdata(handles.figure1,'Trace2',3);
1835 plotappdatalocal(handles);
1836 %AutoScaleYLocal(handles);
1837
1838 % --- Executes on button press in Trace2Off.
1839 function Trace2Off_Callback(hObject, eventdata, handles)
1840 set(handles.Trace2A,'Value', 0);
1841 set(handles.Trace2B,'Value', 0);
1842 set(handles.Trace2A_B,'Value', 0);
1843 set(handles.Trace2Off,'Value', 1);
1844 setappdata(handles.figure1,'Trace2',4);
1845 plotappdatalocal(handles);
1846 %AutoScaleYLocal(handles);
1847
1848
1849 % --- Executes on selection change in DataList1.
1850 function DataList1_Callback(hObject, eventdata, handles)
1851 if strcmpi(get(handles.Simulate,'Checked'),'On')
1852     Mode = 'Simulator';
1853 else
1854     Mode = 'Online';
1855 end
1856
1857 i = get(hObject,'Value');
1858 DataStruct = getappdata(handles.figure1, 'BPMxFamily');
1859
1860 Family = DataStruct.FamilyName;
1861 Field = DataStruct.Field;
1862 List = DataStruct.DeviceList;
1863 [tmp,ao] = isfamily(Family);
1864
1865 if strcmpi(Field, 'Monitor')
1866     Field = 'Setpoint';
1867 end
1868
1869 if isfield(ao, Field)
1870     if getappdata(handles.figure1,'UnitsFlag') == 1
1871         UnitsFlag = 'Physics';
1872     else
1873         UnitsFlag = 'Hardware';
1874     end
1875
1876     % Get/save the present setpoint then call the GUI for setpoint changes
1877     try
1878         SP = getpv(Family, Field, List(i,:), Mode, UnitsFlag, 'Struct');
1879         set(handles.SetpointSlider,     'UserData', SP);
1880         set(handles.SetpointPushButton, 'UserData', SP);
1881
1882         SetpointGUI_Callback(hObject, eventdata, handles);
1883     catch
1884         fprintf('   Trouble finding the present value of %s.%s(%d,%d)\n',Family, Field, List(i,:));
1885     end
1886 end
1887
1888
1889 % --- Executes on selection change in DataList2.
1890 function DataList2_Callback(hObject, eventdata, handles)
1891 if strcmpi(get(handles.Simulate,'Checked'),'On')
1892     Mode = 'Simulator';
1893 else
1894     Mode = 'Online';
1895 end
1896
1897 i = get(hObject,'Value');
1898 DataStruct = getappdata(handles.figure1, 'BPMyFamily');
1899
1900 Family = DataStruct.FamilyName;
1901 Field = DataStruct.Field;
1902 List = DataStruct.DeviceList;
1903 [tmp,ao] = isfamily(Family);
1904
1905 if strcmpi(Field, 'Monitor')
1906     Field = 'Setpoint';
1907 end
1908
1909 if isfield(ao, Field)
1910     if getappdata(handles.figure1,'UnitsFlag') == 1
1911         UnitsFlag = 'Physics';
1912     else
1913         UnitsFlag = 'Hardware';
1914     end
1915
1916     % Get/save the present setpoint then call the GUI for setpoint changes
1917     try
1918         SP = getpv(Family, Field, List(i,:), Mode, UnitsFlag, 'Struct');
1919         set(handles.SetpointSlider, 'UserData', SP);
1920         set(handles.SetpointPushButton, 'UserData', SP);
1921
1922         SetpointGUI_Callback(hObject, eventdata, handles);
1923     catch
1924         fprintf('   Trouble finding the present value of %s.%s(%d,%d)\n',Family, Field, List(i,:));
1925     end
1926 end
1927
1928
1929
1930 %%%%%%%%%%%%%%%%%%
1931 % MENU CALLBACKS %
1932 %%%%%%%%%%%%%%%%%%
1933
1934 % --------------------------------------------------------------------
1935 function PopPlot_Callback(hObject, eventdata, handles)
1936 a = figure;
1937 b = copyobj(handles.Graph1, a);
1938 set(b, 'Position', [0.1300    0.5811    0.7750    0.3439]);
1939 set(b, 'ButtonDownFcn','');
1940 set(b, 'XAxisLocation','Bottom');
1941
1942 b = copyobj(handles.Graph2, a);
1943 set(b, 'Position', [0.1300    0.1100    0.7750    0.3439]);
1944 set(b, 'ButtonDownFcn','');
1945 xlabel(b, 'Position [meters]');
1946
1947 Data = getappdata(handles.figure1, 'RawY');
1948 if isfield(Data, 'TimeStamp')
1949     addlabel(1,0,datestr(Data.TimeStamp,21));
1950 end
1951 orient tall
1952
1953
1954 % --------------------------------------------------------------------
1955 function PopPlot1_Callback(hObject, eventdata, handles)
1956 %set(handles.figure1, 'HandleVisibility','Callback');
1957
1958 a = figure;
1959 b = copyobj(handles.Graph1, a);
1960 set(b, 'Position',[0.13 0.11 0.775 0.815]);
1961 set(b, 'ButtonDownFcn','');
1962 set(b, 'XAxisLocation','Bottom');
1963 Axis1 = axis;
1964
1965 if strcmpi(get(handles.AddPlot1_Nothing,'Checked'),'Off')
1966     set(b, 'Position',[0.13 0.11 0.775 0.7]);
1967     c = copyobj(handles.Graph3, a);
1968
1969     % Plot on top of each other
1970     %set(c, 'Position',[0.13 0.11 0.775 0.815]);
1971
1972     % Separate plots
1973     set(c, 'Position',[0.13 0.11+.72 0.775 0.12]);
1974
1975     set(c,'color',[1 1 1]);
1976     set(c,'Visible','On');
1977     set(c,'XAxisLocation','Top');
1978     set(c,'XTick',get(b,'XTick'));
1979     %set(c,'XTickLabel',get(b,'XTickLabel'));
1980     set(c,'XTickLabel',[]);
1981     set(c,'XMinorTick','On');
1982     set(c,'XMinorGrid','Off');
1983     set(c,'XGrid','Off');
1984     set(c,'YGrid','Off');
1985     set(c,'XAxisLocation','Bottom');
1986     set(c,'YAxisLocation','Left');
1987     %set(c,'YAxisLocation','Right');
1988     set(c,'YTick',[]);
1989     set(c,'YMinorTick','Off');
1990     set(c,'YMinorGrid','Off');
1991     set(c,'YTickLabel',[]);
1992     axis(c,'tight');
1993     Axis2 = axis(c);
1994     axis(c,[Axis1(1) Axis1(2) Axis2(3)-.2*(Axis2(4)-Axis2(3)) Axis2(4)+.2*(Axis2(4)-Axis2(3))]);
1995
1996     set(c, 'ButtonDownFcn','');
1997
1998     if strcmpi(get(handles.AddPlot1_BetaX,'Checked'),'On')
1999         ylabel(c, 'Beta X');
2000     end
2001     if strcmpi(get(handles.AddPlot1_BetaY,'Checked'),'On')
2002         ylabel(c, 'Beta Y');
2003     end
2004     if strcmpi(get(handles.AddPlot1_DispX,'Checked'),'On')
2005         ylabel(c, 'Disp X');
2006     end
2007     if strcmpi(get(handles.AddPlot1_DispY,'Checked'),'On')
2008         ylabel(c, 'Disp Y');
2009     end
2010 end
2011 xlabel(b, 'Position [meters]');
2012 Data = getappdata(handles.figure1, 'RawX');
2013 if isfield(Data, 'TimeStamp') && ~isempty(Data.TimeStamp)
2014     addlabel(1,0,datestr(Data.TimeStamp,21));
2015 end
2016 orient portrait
2017
2018
2019 % --------------------------------------------------------------------
2020 function PopPlot2_Callback(hObject, eventdata, handles)
2021 set(handles.Graph2, 'HandleVisibility', 'Callback');
2022
2023 a = figure;
2024 b = copyobj(handles.Graph2, a);
2025 set(b, 'Position',[0.13 0.11 0.775 0.815]);
2026 set(b, 'ButtonDownFcn','');
2027 Axis1 = axis;
2028
2029 if strcmpi(get(handles.AddPlot2_Nothing,'Checked'),'Off')
2030     set(b, 'Position',[0.13 0.11 0.775 0.7]);
2031     c = copyobj(handles.Graph4, a);
2032
2033     % Plot on top of each other
2034     %set(c, 'Position',[0.13 0.11 0.775 0.815]);
2035
2036     % Separate plots
2037     set(c, 'Position',[0.13 0.11+.72 0.775 0.12]);
2038
2039     set(c,'color',[1 1 1]);
2040     set(c,'Visible','On');
2041     set(c,'XAxisLocation','Top');
2042     set(c,'XTick',get(b,'XTick'));
2043     set(c,'XTickLabel',get(b,'XTickLabel'));
2044     %set(c,'XTickLabel',[]);
2045     set(c,'XMinorTick','On');
2046     set(c,'XMinorGrid','Off');
2047     set(c,'XGrid','Off');
2048     set(c,'YGrid','Off');
2049     set(c,'YAxisLocation','Left');
2050
2051     % Turn y-axis on
2052     set(c,'YTick',[]);
2053     set(c,'YMinorTick','Off');
2054     set(c,'YMinorGrid','Off');
2055     set(c,'YTickLabel',[]);
2056     axis(c,'tight');
2057     Axis2 = axis(c);
2058     axis(c,[Axis1(1) Axis1(2) Axis2(3)-.2*(Axis2(4)-Axis2(3)) Axis2(4)+.2*(Axis2(4)-Axis2(3))]);
2059
2060     set(c, 'ButtonDownFcn','');
2061
2062     if strcmpi(get(handles.AddPlot2_BetaX,'Checked'),'On')
2063         ylabel(c,'Beta X');
2064     end
2065     if strcmpi(get(handles.AddPlot2_BetaY,'Checked'),'On')
2066         ylabel(c,'Beta Y');
2067     end
2068     if strcmpi(get(handles.AddPlot2_DispX,'Checked'),'On')
2069         ylabel(c,'Disp X');
2070     end
2071     if strcmpi(get(handles.AddPlot2_DispY,'Checked'),'On')
2072         ylabel(c,'Disp Y');
2073     end
2074 end
2075 xlabel('Position [meters]');
2076 Data = getappdata(handles.figure1, 'RawY');
2077 if isfield(Data, 'TimeStamp') && ~isempty(Data.TimeStamp)
2078     addlabel(1,0,datestr(Data.TimeStamp,21));
2079 end
2080 orient portrait
2081
2082
2083 % --------------------------------------------------------------------
2084 function Axis1_Callback(hObject, eventdata, handles)
2085 a = axis(handles.Graph1);
2086 a = a(3:4);
2087 answer = inputdlg('New upper graph vertical axis [2 element vector]','',1,{sprintf('[%s]',num2str(a))});
2088 if ~isempty(answer)
2089     a = str2num(answer{1});
2090     if length(a) == 2
2091         set(handles.Graph1, 'YLim', a);
2092     else
2093         fprintf('   Vertical axis needs to be a 2 element vector.\n');
2094     end
2095 end
2096
2097
2098 % --------------------------------------------------------------------
2099 function Axis2_Callback(hObject, eventdata, handles)
2100 a = axis(handles.Graph2);
2101 a = a(3:4);
2102 answer = inputdlg('New lower graph vertical axis [2 element vector]','',1,{sprintf('[%s]',num2str(a))});
2103 if ~isempty(answer)
2104     a = str2num(answer{1});
2105     if length(a) == 2
2106         set(handles.Graph2, 'YLim', a);
2107     else
2108         fprintf('   Vertical axis needs to be a 2 element vector.\n');
2109     end
2110 end
2111
2112
2113 % --------------------------------------------------------------------
2114 function HorizontalAxis_Callback(hObject, eventdata, handles)
2115 a = axis(handles.Graph2);
2116 a = a(1:2);
2117 answer = inputdlg('New horizontal axis [2 element vector]','',1,{sprintf('[%s]',num2str(a))});
2118 if ~isempty(answer)
2119     a = str2num(answer{1});
2120     if length(a) == 2
2121         set(handles.Graph1, 'XLim', a);
2122         set(handles.Graph2, 'XLim', a);
2123         set(handles.Graph3, 'XLim', a);
2124         set(handles.Graph4, 'XLim', a);
2125         set(handles.LatticeAxes, 'XLim', a);
2126         setappdata(handles.figure1, 'AxisRange1X', a(:)');
2127         setappdata(handles.figure1, 'AxisRange2X', a(:)');
2128     else
2129         fprintf('   Horizontal axis needs to be a 2 element vector.\n');
2130     end
2131 end
2132
2133
2134 % --------------------------------------------------------------------
2135 function HorizontalAxisSector_Callback(hObject, eventdata, handles)
2136 a = eventdata;
2137 if length(a) == 2
2138     set(handles.Graph1, 'XLim', a);
2139     set(handles.Graph2, 'XLim', a);
2140     set(handles.Graph3, 'XLim', a);
2141     set(handles.Graph4, 'XLim', a);
2142     set(handles.LatticeAxes, 'XLim', a);
2143
2144     setappdata(handles.figure1, 'AxisRange1X', a(:)');
2145     setappdata(handles.figure1, 'AxisRange2X', a(:)');
2146 else
2147     fprintf('   Horizontal axis needs to be a 2 element vector.\n');
2148 end
2149
2150
2151
2152
2153 % --------------------------------------------------------------------
2154 function YScaleLog1_Callback(hObject, eventdata, handles)
2155 if ~strcmpi(get(handles.Graph1Bar,'Checked'),'On')
2156     set(handles.Graph1,'YScale','Log');
2157     set(handles.YScaleLog1,'Checked','On');
2158     set(handles.YScaleLinear1,'Checked','Off');
2159     drawnow;
2160 else
2161     fprintf('   Log scale not allowed for bar graphs\n');
2162 end
2163
2164 % --------------------------------------------------------------------
2165 function YScaleLinear1_Callback(hObject, eventdata, handles)
2166 set(handles.Graph1,'YScale','Linear');
2167 set(handles.YScaleLog1,'Checked','Off');
2168 set(handles.YScaleLinear1,'Checked','On');
2169 drawnow;
2170
2171
2172 % --------------------------------------------------------------------
2173 function YScaleLog2_Callback(hObject, eventdata, handles)
2174 if ~strcmpi(get(handles.Graph2Bar,'Checked'),'On')
2175     set(handles.Graph2,'YScale','Log');
2176     set(handles.YScaleLog2,'Checked','On');
2177     set(handles.YScaleLinear2,'Checked','Off');
2178     drawnow;
2179 else
2180     fprintf('   Log scale not allowed for bar graphs\n');
2181 end
2182
2183 % --------------------------------------------------------------------
2184 function YScaleLinear2_Callback(hObject, eventdata, handles)
2185 set(handles.Graph2,'YScale','Linear');
2186 set(handles.YScaleLog2,'Checked','Off');
2187 set(handles.YScaleLinear2,'Checked','On');
2188 drawnow;
2189
2190
2191 % --------------------------------------------------------------------
2192 function DataStruct = CreateListboxString(DataStruct)
2193 DataStruct.ListBoxString = strcat(family2common(DataStruct.FamilyName, DataStruct.DeviceList),'=');
2194 % DataStruct.ListBoxString = [];
2195 % for i = 1:size(DataStruct.DeviceList,1)
2196 %     DataStruct.ListBoxString = strvcat(DataStruct.ListBoxString, sprintf('%s(%d,%d) = ', DataStruct.FamilyName, DataStruct.DeviceList(i,1), DataStruct.DeviceList(i,2)));
2197 % end
2198
2199 % --------------------------------------------------------------------
2200 function BPMxFamily_Callback(hObject, eventdata, handles)
2201 UnitMenu = getappdata(handles.figure1,'UnitsFlag');
2202 if UnitMenu == 1
2203     UnitsFlag = 'Physics';
2204 else
2205     UnitsFlag = 'Hardware';
2206 end
2207
2208 if strcmpi(get(handles.Simulate,'Checked'),'On')
2209     Mode = 'Simulator';
2210 else
2211     Mode = 'Online';
2212 end
2213
2214 if isempty(hObject)
2215     close(gcbf);
2216     error('PLOTFAMILY:  Menu corrupted, restart application.');
2217 else
2218     DataStruct = get(hObject, 'UserData');
2219 end
2220
2221 % Rebuild the data structure in case a status field was changed
2222 DataStruct = family2datastruct(DataStruct.FamilyName, DataStruct.Field);
2223
2224 if isfamily(DataStruct)
2225     % Create the list box string
2226     DataStruct = CreateListboxString(DataStruct);
2227
2228     setappdata(handles.figure1, 'BPMxFamily', DataStruct);
2229
2230     s = getspos(DataStruct);
2231     setappdata(handles.figure1, 'SPosX', s);
2232
2233     %L = getfamilydata('Circumference');
2234     %if isempty(L)
2235     %    setappdata(handles.figure1, 'AxisRange1X', [min(s) max(s)]);
2236     %else
2237     %    setappdata(handles.figure1, 'AxisRange1X', [0 L]);
2238     %end
2239
2240     ZeroData = DataStruct;
2241     ZeroData.Data = zeros(size(DataStruct.Data,1),1);
2242
2243     % Menu label
2244     set(handles.BPMxFamily,'Label',sprintf('Plot: %s.%s', DataStruct.FamilyName, DataStruct.Field));
2245
2246     setappdata(handles.figure1,'SaveX', ZeroData);
2247     tmp = getappdata(handles.figure1,'SaveY');
2248     tmp.Data = 0 * tmp.Data;
2249     setappdata(handles.figure1,'SaveY', tmp);
2250     set(handles.SaveTime,'String', '');
2251
2252 %     % Look for the golden values
2253 %     try
2254 %         if strcmpi(DataStruct.Field,'Monitor')
2255 %             % Use the golden setpoint
2256 %             GoldenValues = getgolden(DataStruct.FamilyName, DataStruct.DeviceList, 'Setpoint', UnitsFlag, 'Struct');
2257 %         else
2258 %             GoldenValues = getgolden(DataStruct, UnitsFlag, 'Struct');
2259 %         end
2260 %         setappdata(handles.figure1, 'GoldenX', GoldenValues);
2261 %     catch
2262 %         setappdata(handles.figure1, 'GoldenX', ZeroData);
2263 %     end
2264 %
2265 %     % Look for the offset values
2266 %     try
2267 %         OffsetValues = getoffset(DataStruct, UnitsFlag, 'Struct');
2268 %         setappdata(handles.figure1, 'OffsetX', OffsetValues);
2269 %     catch
2270 %         try
2271 %             % If and offset does not exist than try using the setpoint
2272 %             setappdata(handles.figure1, 'OffsetX', getsp(DataStruct.FamilyName, DataStruct.DeviceList, Mode, UnitsFlag, 'Struct'));
2273 %         catch
2274 %             % Use zeros
2275 %             setappdata(handles.figure1, 'OffsetX', ZeroData);
2276 %         end
2277 %     end
2278
2279     try
2280         FileName = getappdata(handles.figure1, 'FileName');
2281         if isempty(FileName)
2282             FileName = getappdata(handles.figure1, 'FileNameY');
2283         end
2284         if isempty(FileName)
2285             setappdata(handles.figure1,'FileX', ZeroData);
2286         else
2287             tmp = getdata(DataStruct, FileName, 'Struct');
2288             if UnitMenu == 1 && strcmpi(tmp.Units,'Hardware')
2289                 % Physics units requested, data is in Hardware units
2290                 tmp = hw2physics(tmp);
2291             else
2292                 % Hardware units requested, data is in Physics units
2293                 tmp = physics2hw(tmp);
2294             end
2295             setappdata(handles.figure1,'FileX', tmp);
2296             setappdata(handles.figure1,'FileNameX', FileName);
2297         end
2298     catch
2299         setappdata(handles.figure1,'FileX', ZeroData);
2300         setappdata(handles.figure1,'FileNameX','');
2301     end
2302
2303     % Make sure the scale is linear for bar plots
2304     if strcmpi(get(handles.Graph1Bar,'Checked'),'On')
2305         set(handles.Graph1,'YScale','Linear');
2306         set(handles.YScaleLog1,'Checked','Off');
2307         set(handles.YScaleLinear1,'Checked','On');
2308     end
2309
2310     set(handles.DataList1,'Value', 1);
2311     set(handles.DataList1,'ListBoxTop', 1);
2312     UpdateFileDisplayLocal(handles);
2313     OneShot_Callback(hObject, eventdata, handles);
2314
2315     % Auto scale y-axis
2316     % AutoScaleYLocal(handles);
2317     a = axis(handles.Graph1);
2318     axis(handles.Graph1, 'auto');
2319     set(handles.Graph1, 'XLim', a(1:2));
2320
2321 else
2322     fprintf('   %s is not a known family\n', DataStruct.FamilyName);
2323 end
2324
2325
2326 % --------------------------------------------------------------------
2327 function BPMyFamily_Callback(hObject, eventdata, handles)
2328 UnitMenu = getappdata(handles.figure1,'UnitsFlag');
2329 if UnitMenu == 1
2330     UnitsFlag = 'Physics';
2331 else
2332     UnitsFlag = 'Hardware';
2333 end
2334
2335 if strcmpi(get(handles.Simulate,'Checked'),'On')
2336     Mode = 'Simulator';
2337 else
2338     Mode = 'Online';
2339 end
2340
2341 if isempty(hObject)
2342     close(gcbf);
2343     error('PLOTFAMILY:  Menu corrupted, restart application.');
2344 else
2345     DataStruct = get(hObject, 'UserData');
2346 end
2347
2348 % Rebuild the data structure in case a status field was changed
2349 DataStruct = family2datastruct(DataStruct.FamilyName, DataStruct.Field);
2350
2351 if isfamily(DataStruct)
2352     % Create the list box string
2353     DataStruct = CreateListboxString(DataStruct);
2354
2355     setappdata(handles.figure1, 'BPMyFamily', DataStruct);
2356
2357     s = getspos(DataStruct);
2358     setappdata(handles.figure1, 'SPosY', s);
2359     %L = getfamilydata('Circumference');
2360     %if isempty(L)
2361     %    setappdata(handles.figure1, 'AxisRange2X', [min(s) max(s)]);
2362     %else
2363     %    setappdata(handles.figure1, 'AxisRange2X', [0 L]);
2364     %end
2365
2366     ZeroData = DataStruct;
2367     ZeroData.Data = zeros(size(DataStruct.Data,1),1);
2368
2369     % Menu label
2370     set(handles.BPMyFamily,'Label',sprintf('Plot: %s.%s', DataStruct.FamilyName, DataStruct.Field));
2371
2372     setappdata(handles.figure1,'SaveY', ZeroData);
2373     tmp = getappdata(handles.figure1,'SaveX');
2374     tmp.Data = 0 * tmp.Data;
2375     setappdata(handles.figure1,'SaveX', tmp);
2376     set(handles.SaveTime,'String', '');
2377
2378 %     % Look for the golden values
2379 %     try
2380 %         if strcmpi(DataStruct.Field,'Monitor')
2381 %             % Use the golden setpoint
2382 %             GoldenValues = getgolden(DataStruct.FamilyName, DataStruct.DeviceList, 'Setpoint', UnitsFlag, 'Struct');
2383 %         else
2384 %             GoldenValues = getgolden(DataStruct, UnitsFlag, 'Struct');
2385 %         end
2386 %         setappdata(handles.figure1,'GoldenY', GoldenValues);
2387 %     catch
2388 %         setappdata(handles.figure1, 'GoldenY', ZeroData);
2389 %     end
2390 %
2391 %     % Look for the offset values
2392 %     try
2393 %         OffsetValues = getoffset(DataStruct, UnitsFlag, 'Struct');
2394 %         setappdata(handles.figure1,'OffsetY', OffsetValues);
2395 %     catch
2396 %         try
2397 %             % If and offset does not exist than try using the setpoint
2398 %             setappdata(handles.figure1, 'OffsetY', getsp(DataStruct.FamilyName, DataStruct.DeviceList, Mode, UnitsFlag, 'Struct'));
2399 %         catch
2400 %             % Use zeros
2401 %             setappdata(handles.figure1, 'OffsetY', ZeroData);
2402 %         end
2403 %     end
2404
2405     % Look for file data
2406     try
2407         FileName = getappdata(handles.figure1, 'FileNameY');
2408         if isempty(FileName)
2409             FileName = getappdata(handles.figure1, 'FileName');
2410         end
2411         if isempty(FileName)
2412             setappdata(handles.figure1, 'FileY', ZeroData);
2413         else
2414             tmp = getdata(DataStruct, FileName, 'Struct');
2415             if UnitMenu == 1 && strcmpi(tmp.Units,'Hardware')
2416                 % Physics units requested, data is in Hardware units
2417                 tmp = hw2physics(tmp);
2418             else
2419                 % Hardware units requested, data is in Physics units
2420                 tmp = physics2hw(tmp);
2421             end
2422             setappdata(handles.figure1, 'FileY', tmp);
2423             setappdata(handles.figure1, 'FileNameY', FileName);
2424         end
2425     catch
2426         setappdata(handles.figure1, 'FileY', ZeroData);
2427         setappdata(handles.figure1, 'FileNameY','');
2428     end
2429
2430     % Make sure the scale is linear for bar plots
2431     if strcmpi(get(handles.Graph2Bar,'Checked'),'On')
2432         set(handles.Graph2,'YScale','Linear');
2433         set(handles.YScaleLog2,'Checked','Off');
2434         set(handles.YScaleLinear2,'Checked','On');
2435     end
2436
2437     set(handles.DataList2, 'Value', 1);
2438     set(handles.DataList2, 'ListBoxTop', 1);
2439     UpdateFileDisplayLocal(handles);
2440     OneShot_Callback(hObject, eventdata, handles);
2441
2442     % Auto scale y-axis
2443     % AutoScaleYLocal(handles);
2444     a = axis(handles.Graph2);
2445     axis(handles.Graph2, 'auto');
2446     set(handles.Graph2, 'XLim', a(1:2));
2447 else
2448     fprintf('   %s is not a known family\n', DataStruct.FamilyName);
2449 end
2450
2451
2452 % --------------------------------------------------------------------
2453 function BPMxList_Callback(hObject, eventdata, handles)
2454 UnitMenu = getappdata(handles.figure1,'UnitsFlag');
2455 if UnitMenu == 1
2456     UnitsFlag = 'Physics';
2457 else
2458     UnitsFlag = 'Hardware';
2459 end
2460
2461 if strcmpi(get(handles.Simulate,'Checked'),'On')
2462     Mode = 'Simulator';
2463 else
2464     Mode = 'Online';
2465 end
2466
2467 DataStruct = getappdata(handles.figure1, 'BPMxFamily');
2468 Family = DataStruct.FamilyName;
2469 List = DataStruct.DeviceList;
2470 FullList = family2dev(Family);
2471 CheckList = zeros(size(FullList,1),1);
2472 i = findrowindex(List, FullList);
2473 CheckList(i) = 1;
2474 List = editlist(FullList, Family, CheckList);
2475
2476 DataStruct.Data = NaN * ones(size(List,1),1);  %DataStruct.Data(i);
2477 DataStruct.DeviceList = List;
2478 DataStruct.Status = ones(size(List,1),1);
2479
2480 % Create the list box string
2481 DataStruct = CreateListboxString(DataStruct);
2482
2483 setappdata(handles.figure1, 'BPMxFamily', DataStruct);
2484
2485 s = getspos(DataStruct);
2486 setappdata(handles.figure1, 'SPosX', s);
2487
2488 ZeroData = DataStruct;
2489 ZeroData.Data = zeros(size(DataStruct.Data,1),1);
2490
2491 % % Look for the golden values
2492 % try
2493 %     if strcmpi(DataStruct.Field,'Monitor')
2494 %         % Use the golden setpoint
2495 %         GoldenValues = getgolden(DataStruct.FamilyName, DataStruct.DeviceList, 'Setpoint', UnitsFlag, 'Struct');
2496 %     else
2497 %         GoldenValues = getgolden(DataStruct, UnitsFlag, 'Struct');
2498 %     end
2499 %     setappdata(handles.figure1, 'GoldenX', GoldenValues);
2500 % catch
2501 %     setappdata(handles.figure1, 'GoldenX', ZeroData);
2502 % end
2503 %
2504 % % Look for the offset values
2505 % try
2506 %     OffsetValues = getoffset(DataStruct, UnitsFlag, 'Struct');
2507 %     setappdata(handles.figure1,'OffsetX', OffsetValues);
2508 % catch
2509 %     try
2510 %         % If and offset does not exist than try using the setpoint
2511 %         setappdata(handles.figure1, 'OffsetX', getsp(DataStruct.FamilyName, DataStruct.DeviceList, Mode, UnitsFlag, 'Struct'));
2512 %     catch
2513 %         % Use zeros
2514 %         setappdata(handles.figure1, 'OffsetX', ZeroData);
2515 %     end
2516 % end
2517
2518
2519 % Changing the list wipes out a save
2520 setappdata(handles.figure1,'SaveX', ZeroData);
2521 tmp = getappdata(handles.figure1,'SaveY');
2522 tmp.Data = 0 * tmp.Data;
2523 setappdata(handles.figure1,'SaveY', tmp);
2524 set(handles.SaveTime,'String', '');
2525
2526 try
2527     FileName = getappdata(handles.figure1, 'FileNameX');
2528     if isempty(FileName)
2529         FileName = getappdata(handles.figure1, 'FileNameY');
2530     end
2531     if isempty(FileName)
2532         setappdata(handles.figure1,'FileX', ZeroData);
2533     else
2534         tmp = getdata(DataStruct, FileName, 'Struct');
2535         if UnitMenu == 1 && strcmpi(tmp.Units,'Hardware')
2536             % Physics units requested, data is in Hardware units
2537             tmp = hw2physics(tmp);
2538         else
2539             % Hardware units requested, data is in Physics units
2540             tmp = physics2hw(tmp);
2541         end
2542         setappdata(handles.figure1,'FileX', tmp);
2543         setappdata(handles.figure1,'FileNameX', FileName);
2544     end
2545 catch
2546     setappdata(handles.figure1,'FileX', ZeroData);
2547     setappdata(handles.figure1,'FileNameX','');
2548 end
2549
2550 set(handles.DataList1,'Value', 1);
2551 set(handles.DataList1,'ListBoxTop', 1);
2552 UpdateFileDisplayLocal(handles);
2553 cla(handles.Graph1);
2554 OneShot_Callback(hObject, eventdata, handles);
2555
2556 % --------------------------------------------------------------------
2557 function BPMyList_Callback(hObject, eventdata, handles)
2558 UnitMenu = getappdata(handles.figure1,'UnitsFlag');
2559 if UnitMenu == 1
2560     UnitsFlag = 'Physics';
2561 else
2562     UnitsFlag = 'Hardware';
2563 end
2564
2565 if strcmpi(get(handles.Simulate,'Checked'),'On')
2566     Mode = 'Simulator';
2567 else
2568     Mode = 'Online';
2569 end
2570
2571 DataStruct = getappdata(handles.figure1, 'BPMyFamily');
2572 Family = DataStruct.FamilyName;
2573 List = DataStruct.DeviceList;
2574 FullList = family2dev(Family);
2575 CheckList = zeros(size(FullList,1),1);
2576 i = findrowindex(List, FullList);
2577 CheckList(i) = 1;
2578 List = editlist(FullList, Family, CheckList);
2579
2580 DataStruct.Data = NaN * ones(size(List,1),1);  %DataStruct.Data(i);
2581 DataStruct.DeviceList = List;
2582 DataStruct.Status = ones(size(List,1),1);
2583 %DataStruct.Data = DataStruct.Data(i);
2584
2585 % Create the list box string
2586 DataStruct = CreateListboxString(DataStruct);
2587
2588 setappdata(handles.figure1, 'BPMyFamily', DataStruct);
2589
2590 s = getspos(DataStruct);
2591 setappdata(handles.figure1, 'SPosY', s);
2592
2593 ZeroData = DataStruct;
2594 ZeroData.Data = zeros(size(DataStruct.Data,1),1);
2595
2596
2597 % % Look for the golden values
2598 % try
2599 %     if strcmpi(DataStruct.Field,'Monitor')
2600 %         % Use the golden setpoint
2601 %         GoldenValues = getgolden(DataStruct.FamilyName, DataStruct.DeviceList, 'Setpoint', UnitsFlag, 'Struct');
2602 %     else
2603 %         GoldenValues = getgolden(DataStruct, UnitsFlag, 'Struct');
2604 %     end
2605 %     setappdata(handles.figure1, 'GoldenY', GoldenValues);
2606 % catch
2607 %     setappdata(handles.figure1, 'GoldenY', ZeroData);
2608 % end
2609 %
2610 %
2611 % % Look for the offset values
2612 % try
2613 %     OffsetValues = getoffset(DataStruct, UnitsFlag, 'Struct');
2614 %     setappdata(handles.figure1,'OffsetY', OffsetValues);
2615 % catch
2616 %     try
2617 %         % If and offset does not exist than try using the setpoint
2618 %         setappdata(handles.figure1, 'OffsetY', getsp(DataStruct.FamilyName, DataStruct.DeviceList, Mode, UnitsFlag, 'Struct'));
2619 %     catch
2620 %         % Use zeros
2621 %         setappdata(handles.figure1, 'OffsetY', ZeroData);
2622 %     end
2623 % end
2624
2625
2626 % Changing the list wipes out a save
2627 setappdata(handles.figure1,'SaveY', ZeroData);
2628 tmp = getappdata(handles.figure1,'SaveX');
2629 tmp.Data = 0 * tmp.Data;
2630 setappdata(handles.figure1,'SaveX', tmp);
2631 set(handles.SaveTime,'String', '');
2632
2633
2634 try
2635     FileName = getappdata(handles.figure1, 'FileNameY');
2636     if isempty(FileName)
2637         FileName = getappdata(handles.figure1, 'FileName');
2638     end
2639     if isempty(FileName)
2640         setappdata(handles.figure1,'FileY', ZeroData);
2641     else
2642             tmp = getdata(DataStruct, FileName, 'Struct');
2643         if UnitMenu == 1 && strcmpi(tmp.Units,'Hardware')
2644             % Physics units requested, data is in Hardware units
2645             tmp = hw2physics(tmp);
2646         else
2647             % Hardware units requested, data is in Physics units
2648             tmp = physics2hw(tmp);
2649         end
2650         setappdata(handles.figure1,'FileY', tmp);
2651         setappdata(handles.figure1,'FileNameY', FileName);
2652     end
2653 catch
2654     setappdata(handles.figure1,'FileY', ZeroData);
2655     setappdata(handles.figure1,'FileNameY','');
2656 end
2657
2658 set(handles.DataList2,'Value', 1);
2659 set(handles.DataList2,'ListBoxTop', 1);
2660 UpdateFileDisplayLocal(handles);
2661 cla(handles.Graph2);
2662 OneShot_Callback(hObject, eventdata, handles);
2663
2664
2665 % --------------------------------------------------------------------
2666 function UpdatePeriod_Callback(hObject, eventdata, handles)
2667 answer = inputdlg('Enter new update period [seconds]','',1,{num2str(getappdata(handles.figure1, 'UpdatePeriod'))});
2668 if ~isempty(answer)
2669     UpdatePeriod = str2num(answer{1});
2670     if ~isempty(UpdatePeriod) && UpdatePeriod >= 0
2671         if UpdatePeriod > 15
2672             UpdatePeriod = 15;
2673         end
2674         set(handles.UpdatePeriod,'Label', sprintf('Update Period = %.2f sec',UpdatePeriod));
2675         setappdata(handles.figure1, 'UpdatePeriod', UpdatePeriod);
2676     end
2677 end
2678
2679 % --------------------------------------------------------------------
2680 function PhysicsUnits_Callback(hObject, eventdata, handles)
2681 UnitMenu = 1;
2682 setappdata(handles.figure1,'UnitsFlag', UnitMenu);
2683 set(handles.PhysicsUnitsFlag,'Checked','On');
2684 set(handles.HardwareUnitsFlag,'Checked','Off');
2685 set(handles.MicronFlag,'Checked','Off');
2686
2687 RawX = getappdata(handles.figure1, 'RawX');
2688 RawY = getappdata(handles.figure1, 'RawY');
2689
2690 if strcmpi(RawX.Units,'Hardware')
2691     % Physics units requested, data is in Hardware units
2692     setappdata(handles.figure1, 'RawX', hw2physics(RawX));
2693     setappdata(handles.figure1, 'RawY', hw2physics(RawY));
2694
2695 %     setappdata(handles.figure1, 'OffsetX', hw2physics(getappdata(handles.figure1,'OffsetX')));
2696 %     setappdata(handles.figure1, 'OffsetY', hw2physics(getappdata(handles.figure1,'OffsetY')));
2697 %
2698 %     setappdata(handles.figure1, 'GoldenX', hw2physics(getappdata(handles.figure1,'GoldenX')));
2699 %     setappdata(handles.figure1, 'GoldenY', hw2physics(getappdata(handles.figure1,'GoldenY')));
2700
2701     setappdata(handles.figure1, 'SaveX', hw2physics(getappdata(handles.figure1,'SaveX')));
2702     setappdata(handles.figure1, 'SaveY', hw2physics(getappdata(handles.figure1,'SaveY')));
2703
2704     setappdata(handles.figure1, 'FileX', hw2physics(getappdata(handles.figure1,'FileX')));
2705     setappdata(handles.figure1, 'FileY', hw2physics(getappdata(handles.figure1,'FileY')));
2706 end
2707
2708 DataStruct1 = getappdata(handles.figure1, 'BPMxFamily');
2709 if strcmpi(DataStruct1.Units,'Hardware')
2710     % Physics units requested, data is in Hardware units
2711     setappdata(handles.figure1, 'BPMxFamily', hw2physics(DataStruct1));
2712 end
2713
2714 DataStruct2 = getappdata(handles.figure1, 'BPMyFamily');
2715 if strcmpi(DataStruct2.Units,'Hardware')
2716     % Physics units requested, data is in Hardware units
2717     setappdata(handles.figure1, 'BPMyFamily', hw2physics(DataStruct2));
2718 end
2719
2720 plotappdatalocal(handles);
2721 AutoScaleYLocal(handles);
2722
2723 % Turn off the setpoint GUI (or change it to physics units)
2724 TurnOffSetpointGUI_Callback(hObject, eventdata, handles);
2725
2726
2727 % --------------------------------------------------------------------
2728 function HardwareUnits_Callback(hObject, eventdata, handles)
2729 UnitMenu = 2;
2730 setappdata(handles.figure1,'UnitsFlag', UnitMenu);
2731 set(handles.PhysicsUnitsFlag,'Checked','Off');
2732 set(handles.HardwareUnitsFlag,'Checked','On');
2733 set(handles.MicronFlag,'Checked','Off');
2734
2735 RawX = getappdata(handles.figure1, 'RawX');
2736 RawY = getappdata(handles.figure1, 'RawY');
2737
2738 if strcmpi(RawX.Units,'Physics')
2739     % Hardware units requested, data is in Physics units
2740     setappdata(handles.figure1, 'RawX', physics2hw(RawX));
2741     setappdata(handles.figure1, 'RawY', physics2hw(RawY));
2742
2743 %     setappdata(handles.figure1, 'OffsetX', physics2hw(getappdata(handles.figure1,'OffsetX')));
2744 %     setappdata(handles.figure1, 'OffsetY', physics2hw(getappdata(handles.figure1,'OffsetY')));
2745 %
2746 %     setappdata(handles.figure1, 'GoldenX', physics2hw(getappdata(handles.figure1,'GoldenX')));
2747 %     setappdata(handles.figure1, 'GoldenY', physics2hw(getappdata(handles.figure1,'GoldenY')));
2748
2749     setappdata(handles.figure1, 'SaveX', physics2hw(getappdata(handles.figure1,'SaveX')));
2750     setappdata(handles.figure1, 'SaveY', physics2hw(getappdata(handles.figure1,'SaveY')));
2751
2752     setappdata(handles.figure1, 'FileX', physics2hw(getappdata(handles.figure1,'FileX')));
2753     setappdata(handles.figure1, 'FileY', physics2hw(getappdata(handles.figure1,'FileY')));
2754 end
2755
2756 DataStruct1 = getappdata(handles.figure1, 'BPMxFamily');
2757 if strcmpi(DataStruct1.Units,'Physics')
2758     % Hardware units requested, data is in Physics units
2759     setappdata(handles.figure1, 'BPMxFamily', physics2hw(DataStruct1));
2760 end
2761
2762 DataStruct2 = getappdata(handles.figure1, 'BPMyFamily');
2763 if strcmpi(DataStruct2.Units,'Physics')
2764     % Hardware units requested, data is in Physics units
2765     setappdata(handles.figure1, 'BPMyFamily', physics2hw(DataStruct2));
2766 end
2767
2768 plotappdatalocal(handles);
2769 AutoScaleYLocal(handles);
2770
2771 % Turn off the setpoint GUI (or change it to physics units)
2772 TurnOffSetpointGUI_Callback(hObject, eventdata, handles);
2773
2774
2775 % --------------------------------------------------------------------
2776 function MicronFlag_Callback(hObject, eventdata, handles)
2777 UnitMenu = 3;
2778 setappdata(handles.figure1,'UnitsFlag', UnitMenu);
2779 set(handles.PhysicsUnitsFlag,'Checked','Off');
2780 set(handles.HardwareUnitsFlag,'Checked','Off');
2781 set(handles.MicronFlag,'Checked','On');
2782
2783 RawX = getappdata(handles.figure1, 'RawX');
2784 RawY = getappdata(handles.figure1, 'RawY');
2785
2786 if strcmpi(RawX.Units,'Physics')
2787     % Hardware units requested, data is in Physics units
2788     setappdata(handles.figure1, 'RawX', physics2hw(RawX));
2789     setappdata(handles.figure1, 'RawY', physics2hw(RawY));
2790
2791 %     setappdata(handles.figure1, 'OffsetX', physics2hw(getappdata(handles.figure1,'OffsetX')));
2792 %     setappdata(handles.figure1, 'OffsetY', physics2hw(getappdata(handles.figure1,'OffsetY')));
2793 %
2794 %     setappdata(handles.figure1, 'GoldenX', physics2hw(getappdata(handles.figure1,'GoldenX')));
2795 %     setappdata(handles.figure1, 'GoldenY', physics2hw(getappdata(handles.figure1,'GoldenY')));
2796
2797     setappdata(handles.figure1, 'SaveX', physics2hw(getappdata(handles.figure1,'SaveX')));
2798     setappdata(handles.figure1, 'SaveY', physics2hw(getappdata(handles.figure1,'SaveY')));
2799
2800     setappdata(handles.figure1, 'FileX', physics2hw(getappdata(handles.figure1,'FileX')));
2801     setappdata(handles.figure1, 'FileY', physics2hw(getappdata(handles.figure1,'FileY')));
2802 end
2803
2804 DataStruct1 = getappdata(handles.figure1, 'BPMxFamily');
2805 if strcmpi(DataStruct1.Units,'Physics')
2806     % Hardware units requested, data is in Physics units
2807     setappdata(handles.figure1, 'BPMxFamily', physics2hw(DataStruct1));
2808 end
2809
2810 DataStruct2 = getappdata(handles.figure1, 'BPMyFamily');
2811 if strcmpi(DataStruct2.Units,'Physics')
2812     % Hardware units requested, data is in Physics units
2813     setappdata(handles.figure1, 'BPMyFamily', physics2hw(DataStruct2));
2814 end
2815
2816 plotappdatalocal(handles);
2817 AutoScaleYLocal(handles);
2818 drawnow;
2819
2820
2821 % --------------------------------------------------------------------
2822 function SaveOrbitToFile_Callback(hObject, eventdata, handles)
2823
2824 Data1 = getappdata(handles.figure1, 'RawX');
2825 Data2 = getappdata(handles.figure1, 'RawY');
2826
2827 if isfield(Data1,'TimeStamp')
2828     DirStart = pwd;
2829
2830     FamilyName1 = Data1.FamilyName;
2831     FamilyName2 = Data2.FamilyName;
2832     if strcmpi(FamilyName1, FamilyName2)
2833         FileName = appendtimestamp(FamilyName1, Data1.TimeStamp);
2834     else
2835         FileName = appendtimestamp([FamilyName1,'_',FamilyName2], Data1.TimeStamp);
2836     end
2837     DirectoryName = getfamilydata('Directory','DataRoot');
2838
2839     [FileName, DirectoryName] = uiputfile('*.mat', 'Select File (Cancel to not save to a file)', [DirectoryName FileName, '.mat']);
2840     if FileName == 0
2841         %fprintf('   No data saved\n');
2842         return
2843     end
2844
2845     [DirectoryName, ErrorFlag] = gotodirectory(DirectoryName);
2846     save(FileName, 'Data1', 'Data2');
2847     cd(DirStart);
2848     fprintf('   Data saved to %s\n', [DirectoryName FileName]);
2849 else
2850     fprintf('   No data to save \n');
2851 end
2852
2853
2854 % --------------------------------------------------------------------
2855 function Online_Callback(hObject, eventdata, handles)
2856 set(handles.Online,  'Checked','On');
2857 set(handles.Simulate,'Checked','Off');
2858 SetFigureTitle(handles.figure1, 'Online');
2859 %switch2online;
2860 OneShot_Callback(hObject, eventdata, handles);
2861 plotappdatalocal(handles);
2862
2863 % --------------------------------------------------------------------
2864 function Simulate_Callback(hObject, eventdata, handles)
2865 set(handles.Online,  'Checked','Off');
2866 set(handles.Simulate,'Checked','On');
2867 SetFigureTitle(handles.figure1, 'Model');
2868 %switch2sim;
2869 OneShot_Callback(hObject, eventdata, handles);
2870 plotappdatalocal(handles);
2871
2872 % --------------------------------------------------------------------
2873 function Sim2Machine_Callback(hObject, eventdata, handles)
2874 sim2machine;
2875 OneShot_Callback(hObject, eventdata, handles);
2876 plotappdatalocal(handles);
2877
2878 % --------------------------------------------------------------------
2879 function Machine2Sim_Callback(hObject, eventdata, handles)
2880 machine2sim;
2881 OneShot_Callback(hObject, eventdata, handles);
2882 plotappdatalocal(handles);
2883
2884
2885 % --------------------------------------------------------------------
2886 function HorizontalAxesScaling(hObject, eventdata, handles)
2887 % Graph 1, 2, 3, & 4 axes scaling
2888 py = 0.74;
2889 p1 = get(handles.Graph1,'Position');
2890 p2 = get(handles.Graph2,'Position');
2891 p3 = get(handles.Graph3,'Position');
2892 p4 = get(handles.Graph4,'Position');
2893 pa = get(handles.LatticeAxes,'Position');
2894 if strcmpi(get(handles.AddPlot1_Nothing,'Checked'),'Off') || strcmpi(get(handles.AddPlot2_Nothing,'Checked'),'Off')
2895     py = py*.93;
2896 end
2897 set(handles.Graph1,     'Position', [p1(1) p1(2) py p1(4)]);
2898 set(handles.Graph2,     'Position', [p2(1) p2(2) py p2(4)]);
2899 set(handles.Graph3,     'Position', [p3(1) p3(2) py p3(4)]);
2900 set(handles.Graph4,     'Position', [p4(1) p4(2) py p4(4)]);
2901 set(handles.LatticeAxes,'Position', [pa(1) pa(2) py pa(4)]);
2902
2903 plotappdatalocal(handles);
2904
2905
2906 % --------------------------------------------------------------------
2907 function AddPlot_Nothing_Callback(hObject, eventdata, handles)
2908
2909 hp = get(hObject, 'Parent');
2910 hp = get(hp, 'Parent');
2911 if strcmp(get(hp,'Label'),'Graph #1')
2912     plot(handles.Graph3, NaN, NaN)
2913     set(handles.Graph3,'Visible','Off');
2914     set(handles.Graph3,'color','none');
2915     set(handles.AddPlot1_Nothing,'Checked','On');
2916     set(handles.AddPlot1_BetaX,'Checked','Off');
2917     set(handles.AddPlot1_BetaY,'Checked','Off');
2918     set(handles.AddPlot1_DispX,'Checked','Off');
2919     set(handles.AddPlot1_DispY,'Checked','Off');
2920 else
2921     plot(handles.Graph4, NaN, NaN)
2922     set(handles.Graph4,'Visible','Off');
2923     set(handles.Graph4,'color','none');
2924     set(handles.AddPlot2_Nothing,'Checked','On');
2925     set(handles.AddPlot2_BetaX,'Checked','Off');
2926     set(handles.AddPlot2_BetaY,'Checked','Off');
2927     set(handles.AddPlot2_DispX,'Checked','Off');
2928     set(handles.AddPlot2_DispY,'Checked','Off');
2929 end
2930
2931 HorizontalAxesScaling(hObject, eventdata, handles);
2932
2933
2934 % --------------------------------------------------------------------
2935 function AddPlot_Beta_Callback(hObject, eventdata, handles)
2936 % Plot Beta
2937 LineColor = [0 .5 0];
2938
2939 hp = get(hObject,'Parent');
2940 hp = get(hp,'Parent');
2941 hp = get(hp,'Parent');
2942 if strcmp(get(hp,'Label'),'Graph #1')
2943     hAxes = handles.Graph3;
2944 else
2945     hAxes = handles.Graph4;
2946 end
2947 [BetaX, BetaY, Sx, Sy] = modelbeta('All','All');
2948 if strcmp(get(hObject,'Label'),'Horizontal')
2949     plot(hAxes, Sx, BetaX, 'Color',LineColor);
2950     ylabel(hAxes, '{\it\beta_x} [meters]', 'Color',LineColor);
2951 else
2952     plot(hAxes, Sy, BetaY, 'Color',LineColor);
2953     ylabel(hAxes, '{\it\beta_y} [meters]', 'Color',LineColor);
2954 end
2955
2956 if strcmp(get(hp,'Label'),'Graph #1')
2957     AxisRangeX = getappdata(handles.figure1, 'AxisRange1X');
2958 else
2959     AxisRangeX = getappdata(handles.figure1, 'AxisRange2X');
2960 end
2961
2962 axis(hAxes, 'auto');
2963 a = axis(hAxes);
2964 del = a(4) - a(3);
2965 axis(hAxes, [AxisRangeX(1) AxisRangeX(2) a(3)-.4*del a(4)+.4*del]);
2966 AutoScaleVertical(hAxes, .77);
2967
2968 % Set axes defaults
2969 set(hAxes, 'Color', 'none');
2970 set(hAxes, 'Visible', 'On');  % Off to hide axis
2971 set(hAxes, 'YAxisLocation', 'Right');
2972 set(hAxes, 'XGrid', 'Off');
2973 set(hAxes, 'YGrid', 'Off');
2974 set(hAxes, 'XMinorGrid', 'Off');
2975 set(hAxes, 'YMinorGrid', 'Off');
2976 set(hAxes, 'YMinorTick', 'Off');
2977 set(hAxes, 'XMinorTick', 'Off');
2978 set(hAxes, 'XAxisLocation', 'Bottom');
2979 set(hAxes, 'XTickLabel', '');
2980 % set(hAxes, 'YTickLabel', []);
2981 % set(hAxes, 'XTick', []);
2982 % set(hAxes, 'YTick', []);
2983
2984 YTick = get(handles.Graph1, 'YTick');
2985
2986
2987 if strcmp(get(hp,'Label'),'Graph #1')
2988     set(handles.AddPlot1_Nothing,'Checked','Off');
2989     if strcmp(get(hObject,'Label'),'Horizontal')
2990         set(handles.AddPlot1_BetaX,'Checked','On');
2991         set(handles.AddPlot1_BetaY,'Checked','Off');
2992     else
2993         set(handles.AddPlot1_BetaX,'Checked','Off');
2994         set(handles.AddPlot1_BetaY,'Checked','On');
2995     end
2996     set(handles.AddPlot1_DispX,'Checked','Off');
2997     set(handles.AddPlot1_DispY,'Checked','Off');
2998
2999     set(hAxes ,'ButtonDownFcn','plotfamily(''Graph1_ButtonDown'',gcbo,[],guidata(gcbo))');
3000     h = get(hAxes,'Children');
3001     for i = 1:length(h)
3002         set(h(i) ,'ButtonDownFcn','plotfamily(''Graph1_ButtonDown'',gcbo,[],guidata(gcbo))');
3003     end
3004 else
3005     set(handles.AddPlot2_Nothing,'Checked','Off');
3006     if strcmp(get(hObject,'Label'),'Horizontal')
3007         set(handles.AddPlot2_BetaX,'Checked','On');
3008         set(handles.AddPlot2_BetaY,'Checked','Off');
3009     else
3010         set(handles.AddPlot2_BetaX,'Checked','Off');
3011         set(handles.AddPlot2_BetaY,'Checked','On');
3012     end
3013     set(handles.AddPlot2_DispX,'Checked','Off');
3014     set(handles.AddPlot2_DispY,'Checked','Off');
3015
3016     set(hAxes ,'ButtonDownFcn','plotfamily(''Graph2_ButtonDown'',gcbo,[],guidata(gcbo))');
3017     h = get(hAxes,'Children');
3018     for i = 1:length(h)
3019         set(h(i) ,'ButtonDownFcn','plotfamily(''Graph2_ButtonDown'',gcbo,[],guidata(gcbo))');
3020     end
3021 end
3022
3023 HorizontalAxesScaling(hObject, eventdata, handles);
3024
3025
3026 % --------------------------------------------------------------------
3027 function AddPlot_Dispersion_Callback(hObject, eventdata, handles)
3028 % Plot dispersion in physics units
3029 LineColor = [0 .5 0];
3030
3031 hp = get(hObject,'Parent');
3032 hp = get(hp,'Parent');
3033 hp = get(hp,'Parent');
3034
3035 if strcmp(get(hp,'Label'),'Graph #1')
3036     hAxes = handles.Graph3;
3037 else
3038     hAxes = handles.Graph4;
3039 end
3040
3041 [DispX, DispY, Sx, Sy] = modeldisp('All','All','Physics');
3042 if strcmp(get(hObject,'Label'),'Horizontal')
3043     plot(hAxes, Sx, 100*DispX, 'Color',LineColor);
3044     ylabel(hAxes, '{\it\eta_x} [cm]', 'Color',LineColor);
3045 else
3046     plot(hAxes, Sy, 100*DispY, 'Color',LineColor);
3047     ylabel(hAxes, '{\it\eta_y} [cm]', 'Color',LineColor);
3048 end
3049 if strcmp(get(hp,'Label'),'Graph #1')
3050     AxisRangeX = getappdata(handles.figure1, 'AxisRange1X');
3051 else
3052     AxisRangeX = getappdata(handles.figure1, 'AxisRange2X');
3053 end
3054
3055 axis(hAxes, 'auto');
3056 a = axis(hAxes);
3057 del = a(4) - a(3);
3058 axis(hAxes, [AxisRangeX(1) AxisRangeX(2) a(3)-.4*del a(4)+.4*del]);
3059 AutoScaleVertical(hAxes, .77);
3060
3061 % Set axes defaults
3062 set(hAxes, 'Color', 'none');
3063 set(hAxes, 'Visible', 'On');  % Off to hide axis
3064 set(hAxes, 'YAxisLocation', 'Right');
3065 set(hAxes, 'XGrid', 'Off');
3066 set(hAxes, 'YGrid', 'Off');
3067 set(hAxes, 'XMinorGrid', 'Off');
3068 set(hAxes, 'YMinorGrid', 'Off');
3069 set(hAxes, 'YMinorTick', 'Off');
3070 set(hAxes, 'XMinorTick', 'Off');
3071 set(hAxes, 'XAxisLocation', 'Bottom');
3072 set(hAxes, 'XTickLabel', '');
3073 % set(hAxes, 'YTickLabel', []);
3074 % set(hAxes, 'XTick', []);
3075 % set(hAxes, 'YTick', []);
3076
3077
3078 if strcmp(get(hp,'Label'),'Graph #1')
3079     set(handles.AddPlot1_Nothing,'Checked','Off');
3080     if strcmp(get(hObject,'Label'),'Horizontal')
3081         set(handles.AddPlot1_DispX,'Checked','On');
3082         set(handles.AddPlot1_DispY,'Checked','Off');
3083     else
3084         set(handles.AddPlot1_DispX,'Checked','Off');
3085         set(handles.AddPlot1_DispY,'Checked','On');
3086     end
3087     set(handles.AddPlot1_BetaX,'Checked','Off');
3088     set(handles.AddPlot1_BetaY,'Checked','Off');
3089
3090     set(hAxes ,'ButtonDownFcn','plotfamily(''Graph1_ButtonDown'',gcbo,[],guidata(gcbo))');
3091     h = get(hAxes,'Children');
3092     for i = 1:length(h)
3093         set(h(i) ,'ButtonDownFcn','plotfamily(''Graph1_ButtonDown'',gcbo,[],guidata(gcbo))');
3094     end
3095
3096 else
3097     set(handles.AddPlot2_Nothing,'Checked','Off');
3098     if strcmp(get(hObject,'Label'),'Horizontal')
3099         set(handles.AddPlot2_DispX,'Checked','On');
3100         set(handles.AddPlot2_DispY,'Checked','Off');
3101     else
3102         set(handles.AddPlot2_DispX,'Checked','Off');
3103         set(handles.AddPlot2_DispY,'Checked','On');
3104     end
3105     set(handles.AddPlot2_BetaX,'Checked','Off');
3106     set(handles.AddPlot2_BetaY,'Checked','Off');
3107
3108     set(hAxes, 'ButtonDownFcn','plotfamily(''Graph2_ButtonDown'',gcbo,[],guidata(gcbo))');
3109     h = get(hAxes, 'Children');
3110     for i = 1:length(h)
3111         set(h(i), 'ButtonDownFcn', 'plotfamily(''Graph2_ButtonDown'',gcbo,[],guidata(gcbo))');
3112     end
3113 end
3114
3115 HorizontalAxesScaling(hObject, eventdata, handles);
3116
3117
3118 % --------------------------------------------------------------------
3119 function DrawLattice_Callback(hObject, eventdata, handles)
3120 % Graph size is determined here and in function HorizontalAxesScaling
3121 CheckMark = get(handles.DrawLattice, 'Checked');
3122 if strcmpi(CheckMark, 'On')
3123     % Remove the lattice drawing
3124     d = .015;
3125     p1 = [0.07    0.65-d/2    0.74    0.29+d];
3126     set(handles.Graph1, 'Position', p1);
3127     set(handles.Graph3, 'Position', p1);
3128
3129     p2 = [0.07    0.27        0.74    0.29+d];
3130     set(handles.Graph2, 'Position', p2);
3131     set(handles.Graph4, 'Position', p2);
3132
3133     set(handles.DrawLattice, 'Checked', 'Off');
3134     set(get(handles.LatticeAxes,'Children'), 'Visible' , 'Off');
3135 else
3136     % Add the lattice drawing
3137     g = .01;
3138     p1 = [0.07    0.65+g    0.74    0.29-g];
3139     set(handles.Graph1, 'Position', p1);
3140     set(handles.Graph3, 'Position', p1);
3141
3142     p2 = [0.07    0.27      0.74    0.29-g];
3143     set(handles.Graph2, 'Position', p2);
3144     set(handles.Graph4, 'Position', p2);
3145
3146     set(handles.LatticeAxes, 'Units', 'Normalized');
3147     %P = get(handles.LatticeAxes, 'Position');
3148     set(handles.LatticeAxes, 'Position', [0.07 0.5744-g 0.74 0.07+2*g]);  % p4 was 0.065
3149
3150     set(handles.DrawLattice, 'Checked', 'On');
3151     set(get(handles.LatticeAxes,'Children'), 'Visible' , 'On');
3152 end
3153
3154 HorizontalAxesScaling(hObject, eventdata, handles);
3155
3156
3157 % --------------------------------------------------------------------
3158 function Graph1_ButtonDown(hObject, eventdata, handles)
3159 set(handles.figure1, 'HandleVisibility','Callback');
3160 CurrentPoint = get(gca, 'CurrentPoint');
3161 SposMouse = CurrentPoint(1,1);
3162 SposData = getappdata(handles.figure1, 'SPosX');
3163
3164 MeritFcn = abs(SposData-SposMouse);
3165 i = find(min(MeritFcn) == MeritFcn);
3166 set(handles.DataList1, 'value', i(1));
3167 set(handles.figure1, 'HandleVisibility','Off');
3168
3169 % --------------------------------------------------------------------
3170 function Graph2_ButtonDown(hObject, eventdata, handles)
3171 set(handles.figure1, 'HandleVisibility','Callback');
3172 CurrentPoint = get(gca, 'CurrentPoint');
3173 SposMouse = CurrentPoint(1,1);
3174 SposData = getappdata(handles.figure1, 'SPosY');
3175
3176 MeritFcn = abs(SposData-SposMouse);
3177 i = find(min(MeritFcn) == MeritFcn);
3178 set(handles.DataList2, 'value', i(1));
3179 set(handles.figure1, 'HandleVisibility','Off');
3180
3181
3182 % --- Executes on button press in AutoScale1.
3183 function AutoScale1_Callback(hObject, eventdata, handles)
3184 AutoScaleVertical(handles.Graph1, .95);
3185 AutoScaleVertical(handles.Graph3, .77);
3186
3187 % --- Executes on button press in AutoScale2.
3188 function AutoScale2_Callback(hObject, eventdata, handles)
3189 AutoScaleVertical(handles.Graph2, .95);
3190 AutoScaleVertical(handles.Graph4, .77);
3191
3192 %--------------------------------------------------------
3193 function AutoScaleVertical(h_axis, ScaleFactor)
3194 % Auto-scale y-axis
3195
3196 if nargin < 2
3197     ScaleFactor = 1;
3198 end
3199
3200 a = axis(h_axis);
3201 % if strcmpi(get(handles.Graph2Line,'Checked'),'On')
3202 %     % Line
3203 %     axis(h_axis, 'auto');
3204 %     set(h_axis, 'XLim', a(1:2));
3205 % else
3206     % Bar
3207     h = get(h_axis,'Children');
3208     if length(h) > 1
3209         h = sort(h(end-1:end));
3210         y1 = get(h(1),'YData');
3211         y2 = get(h(2),'YData');
3212     else
3213         y1 = get(h(1),'YData');
3214         y2 = y1;
3215     end
3216     x = get(h(1),'XData');
3217     i = find(x>a(1) & x<a(2));
3218     if ~isempty(i)
3219         % Select within present x-axis
3220         y1 = y1(i);
3221         y2 = y2(i);
3222     end
3223
3224     MaxY = max([y1(:); y2(:)]);
3225     MinY = min([y1(:); y2(:)]);
3226
3227     if isnan(MinY) || isnan(MaxY)
3228         axis(h_axis, 'auto');
3229         set(h_axis, 'XLim', a(1:2));
3230     else
3231         %if abs(MaxY-MinY) < eps
3232         %    MaxY = MaxY + .5;
3233         %    MinY = MinY - .5;
3234         %else
3235             % Add a buffer
3236             Delta = MaxY - MinY;
3237             if Delta == 0
3238                 Delta = 1e-15; %eps;
3239             end
3240             MaxY = MaxY + (1-ScaleFactor) * Delta;
3241             MinY = MinY - (1-ScaleFactor) * Delta;
3242         %end
3243         set(h_axis, 'YLim', [MinY MaxY]);
3244     end
3245 %end
3246
3247 % % Auto-scale y-axis
3248 % axis(handles.Graph2, 'auto');
3249 % a = axis(handles.Graph2);
3250 % axis(handles.Graph2, [AxisRange2X(1) AxisRange2X(2) a(3) a(4)]);
3251 % a = axis(handles.Graph4);
3252 % axis(handles.Graph4, [AxisRange2X(1) AxisRange2X(2) a(3) a(4)]);
3253
3254
3255
3256 % --- Executes on button press in AutoScale1.
3257 function AutoScaleH_Callback(hObject, eventdata, handles)
3258
3259 % Auto scale X-axis to the full range
3260 L = getfamilydata('Circumference');
3261 if isempty(L)
3262     DataStruct = getappdata(handles.figure1, 'BPMxFamily');
3263     s = getspos(DataStruct);
3264     AxisRangeX = [min(s) max(s)];
3265 else
3266     AxisRangeX = [0 L];
3267 end
3268 setappdata(handles.figure1, 'AxisRange1X', AxisRangeX);
3269 setappdata(handles.figure1, 'AxisRange2X', AxisRangeX);
3270
3271
3272 % Set x-axis for everybody else
3273 set(handles.Graph1,      'XLim', AxisRangeX);
3274 set(handles.Graph2,      'XLim', AxisRangeX);
3275 set(handles.Graph3,      'XLim', AxisRangeX);
3276 set(handles.Graph4,      'XLim', AxisRangeX);
3277 set(handles.LatticeAxes, 'XLim', AxisRangeX);
3278
3279 % % Auto scale X-axis to the full range
3280 % L = getfamilydata('Circumference');
3281 % if isempty(L)
3282 %     DataStruct = getappdata(handles.figure1, 'BPMyFamily');
3283 %     s = getspos(DataStruct);
3284 %     AxisRange2X = [min(s) max(s)];
3285 % else
3286 %     AxisRange2X = [0 L];
3287 % end
3288 % setappdata(handles.figure1, 'AxisRange2X', AxisRange2X);
3289 %
3290 % Set x-axis for everybody else
3291 %set(handles.Graph1,      'XLim', [AxisRange2X(1) AxisRange2X(2)]);
3292 %set(handles.Graph3,      'XLim', [AxisRange2X(1) AxisRange2X(2)]);
3293 %set(handles.LatticeAxes, 'XLim', [AxisRange2X(1) AxisRange2X(2)]);
3294
3295
3296 function AutoScaleYLocal(handles)
3297 a = axis(handles.Graph1);
3298 axis(handles.Graph1, 'auto');
3299 set(handles.Graph1, 'XLim', a(1:2));
3300
3301 a = axis(handles.Graph2);
3302 axis(handles.Graph2, 'auto');
3303 set(handles.Graph2, 'XLim', a(1:2));
3304
3305
3306
3307 % --- Executes on button press in Graph1ZoomInVertical.
3308 function Graph1ZoomInVertical_Callback(hObject, eventdata, handles)
3309 a = axis(handles.Graph1);
3310 ChangeFactor = 1.15;
3311 del = (1/ChangeFactor-1)*(a(4)-a(3));
3312 axis((handles.Graph1), [a(1) a(2) a(3)-del/2 a(4)+del/2]);
3313 set(hObject, 'Value', 0);
3314
3315
3316 % --- Executes on button press in Graph1ZoomOutVertical.
3317 function Graph1ZoomOutVertical_Callback(hObject, eventdata, handles)
3318 a = axis(handles.Graph1);
3319 ChangeFactor = 1.15;
3320 del = (ChangeFactor-1)*(a(4)-a(3));
3321 axis((handles.Graph1), [a(1) a(2) a(3)-del/2 a(4)+del/2]);
3322 set(hObject, 'Value', 0);
3323
3324
3325 % --- Executes on button press in Graph2ZoomInVertical.
3326 function Graph2ZoomInVertical_Callback(hObject, eventdata, handles)
3327 a = axis(handles.Graph2);
3328 ChangeFactor = 1.15;
3329 del = (1/ChangeFactor-1)*(a(4)-a(3));
3330 axis((handles.Graph2), [a(1) a(2) a(3)-del/2 a(4)+del/2]);
3331 set(hObject, 'Value', 0);
3332
3333
3334 % --- Executes on button press in Graph2ZoomOutVertical.
3335 function Graph2ZoomOutVertical_Callback(hObject, eventdata, handles)
3336 a = axis(handles.Graph2);
3337 ChangeFactor = 1.15;
3338 del = (ChangeFactor-1)*(a(4)-a(3));
3339 axis((handles.Graph2), [a(1) a(2) a(3)-del/2 a(4)+del/2]);
3340 set(hObject, 'Value', 0);
3341
3342
3343 % --- Executes on button press in Graph1ZoomInVertical.
3344 function Graph1OffsetUpVertical_Callback(hObject, eventdata, handles)
3345 ChangeFactor = 1.1;
3346 a1 = axis(handles.Graph1);
3347 del1 = (ChangeFactor-1)*(a1(4)-a1(3));
3348 axis(handles.Graph1, [a1(1) a1(2) a1(3)+del1 a1(4)+del1]);
3349 set(hObject, 'Value', 0);
3350
3351 % --- Executes on button press in Graph1ZoomOutVertical.
3352 function Graph1OffsetDownVertical_Callback(hObject, eventdata, handles)
3353 ChangeFactor = 1.1;
3354 a1 = axis(handles.Graph1);
3355 del1 = (1/ChangeFactor-1)*(a1(4)-a1(3));
3356 axis(handles.Graph1, [a1(1) a1(2) a1(3)+del1 a1(4)+del1]);
3357 set(hObject, 'Value', 0);
3358
3359
3360 % --- Executes on button press in Graph1ZoomInVertical.
3361 function Graph2OffsetUpVertical_Callback(hObject, eventdata, handles)
3362 ChangeFactor = 1.1;
3363 a1 = axis(handles.Graph2);
3364 del1 = (ChangeFactor-1)*(a1(4)-a1(3));
3365 axis(handles.Graph2, [a1(1) a1(2) a1(3)+del1 a1(4)+del1]);
3366 set(hObject, 'Value', 0);
3367
3368 % --- Executes on button press in Graph1ZoomOutVertical.
3369 function Graph2OffsetDownVertical_Callback(hObject, eventdata, handles)
3370 ChangeFactor = 1.1;
3371 a1 = axis(handles.Graph2);
3372 del1 = (1/ChangeFactor-1)*(a1(4)-a1(3));
3373 axis(handles.Graph2, [a1(1) a1(2) a1(3)+del1 a1(4)+del1]);
3374 set(hObject, 'Value', 0);
3375
3376
3377 % --- Executes on button press in HorizontalOffsetRight.
3378 function HorizontalOffsetRight_Callback(hObject, eventdata, handles)
3379 ChangeFactor = 1.05;
3380 a1 = axis(handles.Graph1);
3381 a2 = axis(handles.Graph2);
3382 a3 = axis(handles.Graph3);
3383 a4 = axis(handles.Graph4);
3384 del1 = (ChangeFactor-1)*(a1(2)-a1(1));
3385 del2 = (ChangeFactor-1)*(a2(2)-a2(1));
3386 axis(handles.Graph1, [a1(1)+del1 a1(2)+del1 a1(3) a1(4)]);
3387 axis(handles.Graph3, [a1(1)+del1 a1(2)+del1 a3(3) a3(4)]);
3388 axis(handles.Graph2, [a2(1)+del2 a2(2)+del2 a2(3) a2(4)]);
3389 axis(handles.Graph4, [a2(1)+del2 a2(2)+del2 a4(3) a4(4)]);
3390 set(handles.LatticeAxes, 'XLim', [a2(1)+del2 a2(2)+del2]);
3391 setappdata(handles.figure1, 'AxisRange1X', [a1(1)+del1 a1(2)+del1]);
3392 setappdata(handles.figure1, 'AxisRange2X', [a2(1)+del2 a2(2)+del2]);
3393
3394 function HorizontalOffsetLeft_Callback(hObject, eventdata, handles)
3395 ChangeFactor = 1.05;
3396 a1 = axis(handles.Graph1);
3397 a2 = axis(handles.Graph2);
3398 a3 = axis(handles.Graph3);
3399 a4 = axis(handles.Graph4);
3400 del1 = (1/ChangeFactor-1)*(a1(2)-a1(1));
3401 del2 = (1/ChangeFactor-1)*(a2(2)-a2(1));
3402 axis(handles.Graph1, [a1(1)+del1 a1(2)+del1 a1(3) a1(4)]);
3403 axis(handles.Graph3, [a1(1)+del1 a1(2)+del1 a3(3) a3(4)]);
3404 axis(handles.Graph2, [a2(1)+del2 a2(2)+del2 a2(3) a2(4)]);
3405 axis(handles.Graph4, [a2(1)+del2 a2(2)+del2 a4(3) a4(4)]);
3406 set(handles.LatticeAxes, 'XLim', [a2(1)+del2 a2(2)+del2]);
3407 setappdata(handles.figure1, 'AxisRange1X', [a1(1)+del1 a1(2)+del1]);
3408 setappdata(handles.figure1, 'AxisRange2X', [a2(1)+del2 a2(2)+del2]);
3409
3410 function Graph1ZoomInHorizontal_Callback(hObject, eventdata, handles)
3411 ChangeFactor = 1.3;
3412 a1 = axis(handles.Graph1);
3413 a2 = axis(handles.Graph2);
3414 a3 = axis(handles.Graph3);
3415 a4 = axis(handles.Graph4);
3416 del1 = (1/ChangeFactor-1)*(a1(2)-a1(1));
3417 del2 = (1/ChangeFactor-1)*(a2(2)-a2(1));
3418 axis(handles.Graph1, [a1(1)-del1/2 a1(2)+del1/2 a1(3) a1(4)]);
3419 axis(handles.Graph3, [a1(1)-del1/2 a1(2)+del1/2 a3(3) a3(4)]);
3420 axis(handles.Graph2, [a2(1)-del2/2 a2(2)+del2/2 a2(3) a2(4)]);
3421 axis(handles.Graph4, [a2(1)-del2/2 a2(2)+del2/2 a4(3) a4(4)]);
3422 set(handles.LatticeAxes, 'XLim', [a2(1)-del2/2 a2(2)+del2/2]);
3423 setappdata(handles.figure1, 'AxisRange1X', [a1(1)-del1/2 a1(2)+del1/2]);
3424 setappdata(handles.figure1, 'AxisRange2X', [a2(1)-del2/2 a2(2)+del2/2]);
3425
3426 function Graph1ZoomOutHorizontal_Callback(hObject, eventdata, handles)
3427 ChangeFactor = 1.3;
3428 a1 = axis(handles.Graph1);
3429 a2 = axis(handles.Graph2);
3430 a3 = axis(handles.Graph3);
3431 a4 = axis(handles.Graph4);
3432 del1 = (ChangeFactor-1)*(a1(2)-a1(1));
3433 del2 = (ChangeFactor-1)*(a2(2)-a2(1));
3434 axis(handles.Graph1, [a1(1)-del1/2 a1(2)+del1/2 a1(3) a1(4)]);
3435 axis(handles.Graph3, [a1(1)-del1/2 a1(2)+del1/2 a3(3) a3(4)]);
3436 axis(handles.Graph2, [a2(1)-del2/2 a2(2)+del2/2 a2(3) a2(4)]);
3437 axis(handles.Graph4, [a2(1)-del2/2 a2(2)+del2/2 a4(3) a4(4)]);
3438 set(handles.LatticeAxes, 'XLim', [a2(1)-del2/2 a2(2)+del2/2]);
3439 setappdata(handles.figure1, 'AxisRange1X', [a1(1)-del1/2 a1(2)+del1/2]);
3440 setappdata(handles.figure1, 'AxisRange2X', [a2(1)-del2/2 a2(2)+del2/2]);
3441
3442
3443 % Just in Lattice menu (Not plotfamily)
3444 function Switch2HW_Callback(hObject, eventdata, handles)
3445 switch2hw;
3446
3447 function Switch2Physics_Callback(hObject, eventdata, handles)
3448 switch2physics;
3449
3450 function Switch2Online_Callback(hObject, eventdata, handles)
3451 switch2online;
3452
3453 function Switch2Sim_Callback(hObject, eventdata, handles)
3454 switch2sim;
3455
3456
3457
3458
3459 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
3460 % Setpoint change callbacks %
3461 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
3462
3463 % --------------------------------------------------------------------
3464 function Lattice_ButtonDown(hObject, eventdata, handles)
3465 % Change setpoint request
3466 ErrorFlag = 0;
3467
3468 % Only works on setpoint fields (at the moment)
3469 Field = 'Setpoint';
3470
3471 try
3472     ATIndex = get(hObject, 'UserData');
3473
3474     CurrentPoint = get(handles.LatticeAxes, 'CurrentPoint');
3475     SposMouse = CurrentPoint(1,1);
3476
3477     [Family, List] = atindex2family(ATIndex);
3478
3479     if isempty(Family) || isempty(List)
3480         ErrorFlag = 1;
3481     else
3482
3483         List = List(1,:);
3484
3485         HCMFamily = gethcmfamily;
3486         VCMFamily = getvcmfamily;
3487         if any(strcmpi(Family, {HCMFamily, VCMFamily}))
3488             % A corrector was found (how do I know if it's a HCM or VCM?  AT does not differentiate)
3489             if strcmpi(Family, HCMFamily) && CurrentPoint(1,2)<0
3490                 % It should be a VCM family
3491                 DevList = family2dev(VCMFamily);
3492                 [i, col] = find(ATIndex == family2atindex(VCMFamily,DevList));
3493                 if ~isempty(i)
3494                     Family = VCMFamily;
3495                     List = DevList(i,:);
3496                 end
3497             elseif strcmpi(Family, VCMFamily) && CurrentPoint(1,2)>0
3498                 % It should be a HCM family
3499                 DevList = family2dev(HCMFamily);
3500                 [i, col] = find(ATIndex == family2atindex(HCMFamily,DevList));
3501                 if ~isempty(i)
3502                     Family = HCMFamily;
3503                     List = DevList(i,:);
3504                 end
3505             end
3506         end
3507
3508         [FamilyFlag,ao] = isfamily(Family);
3509
3510         if isfield(ao, Field)
3511             % Get/save the present setpoint then call the GUI for setpoint changes
3512             if strcmpi(get(handles.Simulate,'Checked'),'On')
3513                 Mode = 'Simulator';
3514             else
3515                 Mode = 'Online';
3516             end
3517             if strcmpi(get(handles.PhysicsUnitsFlag,'Checked'),'On')
3518                 %if getappdata(handles.figure1,'UnitsFlag') == 1
3519                 UnitsFlag = 'Physics';
3520             else
3521                 UnitsFlag = 'Hardware';
3522             end
3523
3524             SP = getpv(Family, Field, List, Mode, UnitsFlag, 'Struct');
3525             set(handles.SetpointSlider,     'UserData', SP);
3526             set(handles.SetpointPushButton, 'UserData', SP);
3527             SetpointGUI_Callback(hObject, eventdata, handles);
3528         else
3529             ErrorFlag = 1;
3530         end
3531     end
3532 catch
3533     ErrorFlag = 1;
3534     fprintf('\n%s\n', lasterr);
3535     fprintf('There was a problem getting %s.%s(%d,%d)\n', Family, Field, List);
3536 end
3537
3538 if ErrorFlag
3539     % Turn off the setpoint GUI
3540     TurnOffSetpointGUI_Callback(hObject, eventdata, handles);
3541 end
3542
3543
3544 % --------------------------------------------------------------------
3545 function SetpointGUI_Callback(hObject, eventdata, handles)
3546
3547 if strcmpi(get(handles.DisabledSetpointChanges,'Checked'),'Off')
3548     SP = get(handles.SetpointSlider, 'UserData');
3549
3550     % Use slider and edit box
3551     set(handles.SetpointSlider, 'UserData', SP);
3552     try
3553         MaxPV = maxpv(SP);
3554         MinPV = minpv(SP);
3555         %if isinf(MaxPV) && ~isnan(MaxPV)
3556         %    MaxPV = 1e10; %SP.Data + abs(SP.Data);
3557         %end
3558         %if isinf(MinPV) && ~isnan(MinPV)
3559         %    MinPV = -1e10; %SP.Data - abs(SP.Data);;
3560         %end
3561
3562         if MaxPV < MinPV
3563             tmp = MaxPV;
3564             MaxPV = MinPV;
3565             MinPV = tmp;
3566         end
3567
3568         if isnumeric(MaxPV) && isnumeric(MinPV) && ~isinf(MaxPV) && ~isinf(MinPV) && ~isnan(MaxPV) && ~isnan(MinPV) && (MaxPV-MinPV)~=0
3569             Range = abs(MaxPV-MinPV);
3570             if Range == 1
3571                 StepSize = 1;
3572             else
3573                 StepSize = Range/5000;
3574             end
3575         else
3576             StepSize = 1;
3577         end
3578         set(handles.SetpointStepSize, 'String', num2str(StepSize));
3579         %set(handles.SetpointStepSize, 'String', sprintf('%f',StepSize));
3580     catch
3581         MaxPV = Inf; % 1e10; % SP.Data + abs(SP.Data);
3582         MinPV =-Inf; %-1e10; % SP.Data - abs(SP.Data);
3583     end
3584
3585     set(handles.SetpointMax, 'String', sprintf('%f',MaxPV));
3586     set(handles.SetpointMin, 'String', sprintf('%f',MinPV));
3587
3588     if ~isinf(MaxPV) && ~isnan(MaxPV) && (MaxPV-MinPV)~=0
3589         set(handles.SetpointSlider, 'Max', MaxPV);
3590     end
3591     if ~isinf(MinPV) && ~isnan(MaxPV) && (MaxPV-MinPV)~=0
3592         set(handles.SetpointSlider, 'Min', MinPV);
3593     end
3594     SetpointRange_Callback(hObject, eventdata, handles);
3595
3596     set(handles.SetpointFamily, 'String', sprintf('%s.%s', deblank(family2common(SP.FamilyName, SP.DeviceList)), SP.Field));
3597     %set(handles.SetpointFamily, 'String', sprintf('%s.%s(%d,%d)', SP.FamilyName, SP.Field, SP.DeviceList));
3598     try
3599         set(handles.SetpointFamily,  'TooltipString', sprintf('%s', family2channel(SP)));
3600     catch
3601         set(handles.SetpointFamily,  'TooltipString', '');
3602     end
3603     set(handles.SetpointUnits,   'String', [SP.UnitsString, '/step']);
3604     set(handles.SetpointEditBox, 'String', sprintf('%f', SP.Data));
3605     set(handles.SetpointEditBox, 'TooltipString', sprintf('New setpoint in %s', SP.UnitsString));
3606
3607     set(handles.SetpointPushButton, 'String', sprintf('%f', SP.Data));
3608     set(handles.SetpointPushButton, 'TooltipString', sprintf('Restore original setpoint to %f %s', SP.Data, SP.UnitsString));
3609
3610
3611     set(handles.SetpointEditBox,   'Visible', 'On');
3612     set(handles.SetpointFamily,    'Visible', 'On');
3613     set(handles.SetpointUnits,     'Visible', 'On');
3614     set(handles.SetpointSlider,    'Visible', 'On');
3615     set(handles.SetpointMax,       'Visible', 'On');
3616     set(handles.SetpointMin,       'Visible', 'On');
3617     set(handles.SetpointFrame,     'Visible', 'On');
3618     set(handles.SetpointStepSize,  'Visible', 'On');
3619     set(handles.SetpointPushButton,'Visible', 'On');
3620
3621     % Change the save and file text to make room for the slider
3622     p = get(handles.SaveTime, 'Position');
3623     set(handles.SaveTime, 'Position',  [p(1) p(2) .353*p(3) p(4)]);
3624     p = get(handles.FileNameX, 'Position');
3625     set(handles.FileNameX, 'Position', [p(1) p(2) .353*p(3) p(4)]);
3626     p = get(handles.FileNameY, 'Position');
3627     set(handles.FileNameY, 'Position', [p(1) p(2) .353*p(3) p(4)]);
3628
3629     % % Other method: use input dialog box
3630     % answer = inputdlg(sprintf('Enter new setpoint for %s.%s(%d,%d) in %s (%s):', SP.FamilyName, SP.Field, SP.DeviceList, SP.UnitsString, SP.Mode),'FAMILYPLOT',1,{sprintf('%s',num2str(SP.Data))});
3631     % if ~isempty(answer)
3632     %     NewSP = str2num(answer{1});
3633     %     if ~isempty(NewSP)
3634     %         SP.Data = NewSP
3635     %         set(handles.SetpointSlider,  'UserData', SP);
3636     %         ChangeSetpointPlotfamily(hObject, eventdata, handles);
3637     %         %setpv(Family, Field, NewSP, List, Mode);
3638     %     end
3639     % end
3640 end
3641
3642
3643 % --------------------------------------------------------------------
3644 function SetpointRange_Callback(hObject, eventdata, handles)
3645
3646 MaxPV = str2num(get(handles.SetpointMax,'String'));
3647 MinPV = str2num(get(handles.SetpointMin,'String'));
3648
3649 if isnumeric(MaxPV) && isnumeric(MinPV) && ~isinf(MaxPV) && ~isinf(MinPV) && ~isnan(MaxPV) && ~isnan(MinPV) && (MaxPV-MinPV)~=0
3650     if MaxPV < MinPV
3651         fprintf('   Maximum range must be greater than the minimum range.\n');
3652         MaxPV = get(handles.SetpointSlider, 'Max');
3653         MinPV = get(handles.SetpointSlider, 'Min');
3654         set(handles.SetpointMax, 'String', sprintf('%f',MaxPV));
3655         set(handles.SetpointMin, 'String', sprintf('%f',MinPV));
3656     else
3657         StepSize = abs(str2num(get(handles.SetpointStepSize, 'String')));
3658         Range = abs(MaxPV-MinPV);
3659         if isempty(StepSize) || ~isnumeric(StepSize)
3660             fprintf('   Step size is not a numeric value.  Overwriting with the default step size.\n');
3661             StepSize = Range/1000;
3662         end
3663         set(handles.SetpointStepSize, 'String', num2str(StepSize));
3664         %set(handles.SetpointStepSize, 'String', sprintf('%f',StepSize));
3665         Steps = Range/StepSize;
3666         if Steps < 10
3667             Steps = 10;
3668         end
3669         set(handles.SetpointSlider, 'Max', MaxPV);
3670         set(handles.SetpointSlider, 'Min', MinPV);
3671         set(handles.SetpointSlider, 'SliderStep', [1/Steps 10/Steps]);
3672         %set(handles.SetpointSlider, 'SliderStep', [.001 .01]);
3673
3674         SP = get(handles.SetpointSlider, 'UserData');
3675         set(handles.SetpointSlider,  'Value',  SP.Data);
3676
3677         set(handles.SetpointSlider, 'Enable', 'On');
3678     end
3679 else
3680     set(handles.SetpointSlider, 'Enable', 'Off');
3681 end
3682
3683
3684
3685 % --------------------------------------------------------------------
3686 function SetpointSlider_Callback(hObject, eventdata, handles)
3687
3688 % Get setpoint from the slider
3689 NewSP = get(handles.SetpointSlider, 'Value');
3690
3691 SP = get(handles.SetpointSlider, 'UserData');
3692 SP.Data = NewSP;
3693
3694 % Update Slider
3695 set(handles.SetpointSlider, 'UserData', SP);
3696 set(handles.SetpointSlider, 'Value', NewSP);
3697
3698 % Update EditBox
3699 set(handles.SetpointEditBox, 'String', sprintf('%f', SP.Data));
3700
3701 % Make setpoint change
3702 ChangeSetpointPlotfamily(hObject, eventdata, handles);
3703
3704
3705 % --------------------------------------------------------------------
3706 function SetpointEditBox_Callback(hObject, eventdata, handles)
3707
3708 % Get setpoint from the editbox
3709 ValueStr = get(handles.SetpointEditBox, 'String');
3710
3711 if ~isempty(ValueStr)
3712     NewSP = str2num(ValueStr);
3713
3714     SP = get(handles.SetpointSlider, 'UserData');
3715     SP.Data = NewSP;
3716
3717     % Check range (if slider is enabled)
3718     ChangeFlag = 1;
3719     if strcmpi(get(handles.SetpointSlider,'Enable'), 'On')
3720         MaxPV = str2num(get(handles.SetpointMax,'String'));
3721         MinPV = str2num(get(handles.SetpointMin,'String'));
3722         if isnumeric(MaxPV) && isnumeric(MinPV) && ~isinf(MaxPV) && ~isinf(MinPV) && ~isnan(MaxPV) && ~isnan(MinPV)
3723             if MaxPV < NewSP  || NewSP < MinPV
3724                 fprintf('   The requested setpoint is outside the limits.  Requested cancelled.\n');
3725                 ChangeFlag = 0;
3726                 OldSP = get(handles.SetpointSlider, 'Value');
3727                 set(handles.SetpointEditBox, 'String', sprintf('%f',OldSP));
3728             end
3729         end
3730     end
3731
3732     % Update Slider
3733     if ChangeFlag
3734         set(handles.SetpointSlider, 'UserData', SP);
3735
3736         % Don't change the slider if it's not enabled
3737         if strcmpi(get(handles.SetpointSlider,'Enable'), 'On')
3738             set(handles.SetpointSlider, 'Value', NewSP);
3739         end
3740
3741         % Make setpoint change
3742         ChangeSetpointPlotfamily(hObject, eventdata, handles);
3743     end
3744 end
3745
3746
3747 % --------------------------------------------------------------------
3748 function SetpointPushButton_Callback(hObject, eventdata, handles)
3749
3750 % Get setpoint from the pushbutton
3751 SP = get(handles.SetpointPushButton, 'UserData');
3752
3753 % Update Slider if it's enabled
3754 if strcmpi(get(handles.SetpointSlider,'Enable'), 'On')
3755     set(handles.SetpointSlider, 'Value', SP.Data);
3756 end
3757
3758 % Store the setpoint change and update the editbox
3759 set(handles.SetpointSlider, 'UserData', SP);
3760 set(handles.SetpointEditBox, 'String', sprintf('%f',SP.Data));
3761
3762 % Make setpoint change
3763 ChangeSetpointPlotfamily(hObject, eventdata, handles);
3764
3765
3766 % --------------------------------------------------------------------
3767 function ChangeSetpointPlotfamily(hObject, eventdata, handles)
3768
3769 SP = get(handles.SetpointSlider, 'UserData');
3770
3771 % Get the present mode (units are stored with the data)
3772 if strcmpi(get(handles.Simulate,'Checked'),'On')
3773     Mode = 'Simulator';
3774 else
3775     Mode = 'Online';
3776 end
3777
3778
3779 % Make the setpoint change
3780 setpv(SP, 0, Mode);
3781
3782
3783 % Update plots
3784 OneShot_Callback(hObject, eventdata, handles);
3785
3786 if strcmpi(get(handles.AddPlot1_BetaX,'Checked'),'On')
3787     AddPlot_Beta_Callback(handles.AddPlot1_BetaX, eventdata, handles);
3788 end
3789 if strcmpi(get(handles.AddPlot2_BetaX,'Checked'),'On')
3790     AddPlot_Beta_Callback(handles.AddPlot2_BetaX, eventdata, handles);
3791 end
3792 if strcmpi(get(handles.AddPlot1_BetaY,'Checked'),'On')
3793     AddPlot_Beta_Callback(handles.AddPlot1_BetaY, eventdata, handles);
3794 end
3795 if strcmpi(get(handles.AddPlot2_BetaY,'Checked'),'On')
3796     AddPlot_Beta_Callback(handles.AddPlot2_BetaY, eventdata, handles);
3797 end
3798
3799 if strcmpi(get(handles.AddPlot1_DispX,'Checked'),'On')
3800     AddPlot_Dispersion_Callback(handles.AddPlot1_DispX, eventdata, handles);
3801 end
3802 if strcmpi(get(handles.AddPlot2_DispX,'Checked'),'On')
3803     AddPlot_Dispersion_Callback(handles.AddPlot2_DispX, eventdata, handles);
3804 end
3805 if strcmpi(get(handles.AddPlot1_DispY,'Checked'),'On')
3806     AddPlot_Dispersion_Callback(handles.AddPlot1_DispY, eventdata, handles);
3807 end
3808 if strcmpi(get(handles.AddPlot2_DispY,'Checked'),'On')
3809     AddPlot_Dispersion_Callback(handles.AddPlot2_DispY, eventdata, handles);
3810 end
3811
3812
3813
3814 % --------------------------------------------------------------------
3815 function Graph1Line_Callback(hObject, eventdata, handles)
3816 set(handles.Graph1Line,'Checked','On');
3817 set(handles.Graph1Bar, 'Checked','Off');
3818 cla(handles.Graph1);
3819
3820 % Update plot
3821 OneShot_Callback(hObject, eventdata, handles);
3822
3823 % --------------------------------------------------------------------
3824 function Graph1Bar_Callback(hObject, eventdata, handles)
3825 set(handles.Graph1Line,'Checked','Off');
3826 set(handles.Graph1Bar, 'Checked','On');
3827 cla(handles.Graph1);
3828
3829 % Make sure the scale is linear for bar plots
3830 set(handles.Graph1,'YScale','Linear');
3831 set(handles.YScaleLog1,'Checked','Off');
3832 set(handles.YScaleLinear1,'Checked','On');
3833
3834 % Update plot
3835 OneShot_Callback(hObject, eventdata, handles);
3836
3837
3838 % --------------------------------------------------------------------
3839 function Graph2Line_Callback(hObject, eventdata, handles)
3840 set(handles.Graph2Line,'Checked','On');
3841 set(handles.Graph2Bar, 'Checked','Off');
3842 cla(handles.Graph2);
3843
3844 % Update plot
3845 OneShot_Callback(hObject, eventdata, handles);
3846
3847 % --------------------------------------------------------------------
3848 function Graph2Bar_Callback(hObject, eventdata, handles)
3849 set(handles.Graph2Line,'Checked','Off');
3850 set(handles.Graph2Bar, 'Checked','On');
3851 cla(handles.Graph2);
3852
3853 % Make sure the scale is linear for bar plots
3854 set(handles.Graph2,'YScale','Linear');
3855 set(handles.YScaleLog2,'Checked','Off');
3856 set(handles.YScaleLinear2,'Checked','On');
3857
3858 % Update plot
3859 OneShot_Callback(hObject, eventdata, handles);
3860
3861
3862 % --------------------------------------------------------------------
3863 function DisabledSetpointChanges_Callback(hObject, eventdata, handles)
3864 if strcmpi(get(handles.DisabledSetpointChanges,'Checked'),'Off')
3865     set(handles.DisabledSetpointChanges,'Checked','On');
3866     TurnOffSetpointGUI_Callback(hObject, eventdata, handles);
3867 else
3868     set(handles.DisabledSetpointChanges,'Checked','Off');
3869 end
3870
3871
3872 % --------------------------------------------------------------------
3873 function TurnOffSetpointGUI_Callback(hObject, eventdata, handles)
3874 % Turn off the setpoint GUI
3875 if strcmpi(get(handles.SetpointEditBox,'Visible'),'On')
3876     set(handles.SetpointEditBox,   'Visible', 'Off');
3877     set(handles.SetpointFamily,    'Visible', 'Off');
3878     set(handles.SetpointUnits,     'Visible', 'Off');
3879     set(handles.SetpointSlider,    'Visible', 'Off');
3880     set(handles.SetpointMax,       'Visible', 'Off');
3881     set(handles.SetpointMin,       'Visible', 'Off');
3882     set(handles.SetpointFrame,     'Visible', 'Off');
3883     set(handles.SetpointStepSize,  'Visible', 'Off');
3884     set(handles.SetpointPushButton,'Visible', 'Off');
3885
3886     % Change the save and file text back to full size
3887     p = get(handles.SaveTime, 'Position');
3888     set(handles.SaveTime, 'Position',  [p(1) p(2) p(3)/.353 p(4)]);
3889     p = get(handles.FileNameX, 'Position');
3890     set(handles.FileNameX, 'Position', [p(1) p(2) p(3)/.353 p(4)]);
3891     p = get(handles.FileNameY, 'Position');
3892     set(handles.FileNameY, 'Position', [p(1) p(2) p(3)/.353 p(4)]);
3893
3894     drawnow;
3895 end
3896