Description of saveao
Home > mml > saveao.m
saveao
PURPOSE
SAVEAO - Saves the AO and AD to a .mat file
SYNOPSIS
function saveao(FileName)
DESCRIPTION
SAVEAO - Saves the AO and AD to a .mat file
  saveao(FileName)
  saveao('Golden') to save the MML structures ("AD" & "AD") file to the operations directory (MMLStructures.mat)
  See also loadao, savemml
CROSS-REFERENCE INFORMATION
This function calls:
getad GETAD - returns the Accelerator Data (AD) structure
getao GETAO - returns the AcceleratorObject (AO)
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
This function is called by:
SOURCE CODE
function  saveao(FileName)
%SAVEAO - Saves the AO and AD to a .mat file
%  saveao(FileName)
%  saveao('Golden') to save the MML structures ("AD" & "AD") file to the operations directory (MMLStructures.mat)
%
%  See also loadao, savemml
%  Written by Greg Portmann
if nargin < 1
    FileName = '';
end
if ischar(FileName)
    if isempty(FileName)
        [FileName, DirectoryName, FilterIndex] = uiputfile('*.mat','Save the AO or AD to ...', getfamilydata('Directory','DataRoot'));
        if FilterIndex == 0
            return;
        end
        FileName = [DirectoryName, FileName];
    elseif strcmpi(FileName, 'Golden')
        FileName = [getfamilydata('Directory','OpsData'), 'GoldenMMLSetup'];
    end
else
    error('Filename input must be a string');
end
AO = getao;
AD = getad;
save(FileName, 'AO', 'AD');