Description of setad
Home > mml > setad.m
setad
PURPOSE
SETAD - Sets the MML AcceleratorData cell array to appdata
SYNOPSIS
function setad(AD)
DESCRIPTION
SETAD - Sets the MML AcceleratorData cell array to appdata
  setad(AD)
  INPUTS
  1. Accelerator Data Structure
  See also getad, setao
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
loadao LOADAO - Loads the AO and AD from a .mat file
setao SETAO - Set the MML Accelerator Object (AO)
setfamilydata SETFAMILYDATA - Sets data associated with accelerator control
setmmldirectories SETMMLDIRECTORIES - Set the directory in the Matlab middle layer
setpathmml SETPATHMML - Initialize the Matlab MiddleLayer (MML) path
SOURCE CODE
function  setad(AD)
%SETAD - Sets the MML AcceleratorData cell array to appdata
%  setad(AD)
%
%  INPUTS
%  1. Accelerator Data Structure
%
%  See also getad, setao
setappdata(0, 'AcceleratorData', AD);