Description of setorbitgui
Home > mml > setorbitgui.m
setorbitgui
PURPOSE
SETORBITGUI - Orbit correction GUI
SYNOPSIS
function varargout = setorbitgui(varargin)
DESCRIPTION
SETORBITGUI - Orbit correction GUI
  See also setorbit, orbitcorrectionmethods, setorbitdefault, setorbitbump
CROSS-REFERENCE INFORMATION
This function calls:
family2dev FAMILY2DEV - Return the device list for a family
getdata GETDATA - Searches through a file (or group of files) for a data structure which matches the family name
getfamilydata GETFAMILYDATA - Gets data associated with the accelerator control
gethbpmfamily GETHBPMFAMILY - Return the default horizontal BPM family
gethcmfamily GETHCMFAMILY - Returns the default horizontal corrector family
getpv GETPV - Returns a variable from the online system or the model
getrf GETRF - Gets the RF frequency
getsp GETSP - Gets setpoint channels
getvbpmfamily GETVBPMFAMILY - Return the default vertical BPM family
getvcmfamily GETVCMFAMILY - Returns the default vertical corrector family
getx GETX - Returns the horizontal orbit
gety GETY - Returns the vertical orbit
setorbit SETORBIT - Orbit correction function
setorbitsetup SETORBITSETUP - BPM & CM setup function for setorbitgui
setpv SETPV - Setpoint change of the online system or model
This function is called by:
SUBFUNCTIONS
function varargout = setorbitgui_OutputFcn(hObject, eventdata, handles)
function varargout = CloseRequest_Callback(hObject, eventdata, handles)
function setorbitgui_OpeningFcn(hObject, eventdata, handles, varargin)
function SelectFlags_Callback(hObject, eventdata, handles)
function CalcSVD(handles)
function HorizontalPlane_Callback(hObject, eventdata, handles)
function VerticalPlane_Callback(hObject, eventdata, handles)
function SliderCMScaling_Callback(hObject, eventdata, handles)
function EditCMScaling_Callback(hObject, eventdata, handles)
function ScaleCorrectors_Callback(hObject, eventdata, handles)
function EditDevice_Callback(hObject, eventdata, handles)
function GetOrbit_Callback(hObject, eventdata, handles)
function StopCorrection_Callback(hObject, eventdata, handles)
function ApplyCorrection_Callback(hObject, eventdata, handles)
function RemoveCorrection_Callback(hObject, eventdata, handles)
function GetFile_Callback(hObject, eventdata, handles)
function RadioButton_Offset_Callback(hObject, eventdata, handles)
function RadioButton_Golden_Callback(hObject, eventdata, handles)
function RadioButton_File_Callback(hObject, eventdata, handles)
function RadioButton_Save_Callback(hObject, eventdata, handles)
function SaveOrbit_Callback(hObject, eventdata, handles)
function SaveOrbitToFile_Callback(hObject, eventdata, handles)
function SaveOCS_Callback(hObject, eventdata, handles)
function Graph_1_Callback(hObject, eventdata, handles)
function Graph_2_Callback(hObject, eventdata, handles)
function Graph_3_Callback(hObject, eventdata, handles)
function Graph_4_Callback(hObject, eventdata, handles)
function Graph_5_Callback(hObject, eventdata, handles)
function Graph_6_Callback(hObject, eventdata, handles)
function All_Graphs_Callback(hObject, eventdata, handles)
function Edit_SVD_Callback(hObject, eventdata, handles)
function RadioButton_RF_Callback(hObject, eventdata, handles)
function Print_Callback(hObject, eventdata, handles)
function Plots0_Callback(hObject, eventdata, handles)
function Plots3_Callback(hObject, eventdata, handles)
function Plots6_Callback(hObject, eventdata, handles)
function FigResize_Callback(hObject, eventdata, handles)
function UpdatePlots(handles)
function MinimumPeriod_Callback(hObject, eventdata, handles)
function CorrectorGain_Callback(hObject, eventdata, handles)
SOURCE CODE
function varargout = setorbitgui(varargin)
%SETORBITGUI - Orbit correction GUI
%
%  See also setorbit, orbitcorrectionmethods, setorbitdefault, setorbitbump
%  Written by Jacob Pachikara and Greg Portmann
% To do:
% Stop blinking of legends during orbit feedback
% Add ID tune feedforward, etc to setorbit?  (OCS.PreCorrectonFcn, OCS.PostCorrectonFcn)
% Can setorbit working during a ramp?  (ie, check the bend magnet for a change?)
% Last Modified by GUIDE v2.5 09-Jan-2007 11:53:49
% Begin initialization code - DO NOT EDITMENU
gui_Singleton = 0;
gui_State = struct('gui_Name',       mfilename, ...
                   'gui_Singleton',  gui_Singleton, ...
                   'gui_OpeningFcn', @setorbitgui_OpeningFcn, ...
                   'gui_OutputFcn',  @setorbitgui_OutputFcn, ...
                   'gui_LayoutFcn',  [] , ...
                   'gui_Callback',   []);
if nargin && ischar(varargin{1})
    gui_State.gui_Callback = str2func(varargin{1});
end
if nargout
    [varargout{1:nargout}] = gui_mainfcn(gui_State, varargin{:});
else
    gui_mainfcn(gui_State, varargin{:});
end
% End initialization code - DO NOT EDITMENU
% --- Outputs from this function are returned to the command line.
function varargout = setorbitgui_OutputFcn(hObject, eventdata, handles)
% Get default command line output from handles structure
varargout{1} = handles.output;
% --- Outputs from this function are returned to the command line.
function varargout = CloseRequest_Callback(hObject, eventdata, handles)
RingSetOrbit.RunFlag = -1;
setappdata(0, 'RingSetOrbit', RingSetOrbit);
pause(.1);
delete(handles.figure1);
% --- Executes just before setorbitgui is made visible.
function setorbitgui_OpeningFcn(hObject, eventdata, handles, varargin)
% This function has no output args, see OutputFcn.
% hObject    handle to figure
% eventdata  reserved - to be defined in a future version of MATLAB
% handles    structure with handles and user data (see GUIDATA)7
% varargin   command line arguments to setorbitgui (see VARARGIN)
% Choose default command line output for setorbitgui
handles.output = hObject;
% Update handles structure
guidata(hObject, handles);
% UIWAIT makes setorbitgui wait for user response (see UIRESUME)
% uiwait(handles.figure1);
set(handles.RadioButton_Golden,'Value', 1);
set(handles.HorizontalPlane,'Value', 1);
set(handles.VerticalPlane,'Value', 1);
set(handles.ApplyCorrection,'Enable','Off');
set(handles.RemoveCorrection,'Enable','Off');
set(handles.PopUpMenu_Iterations,'Value',1);
set(handles.SaveOrbit,'Enable','Off');
set(handles.RadioButton_Save,'Enable','Off');
set(handles.RadioButton_File,'Enable','Off');
set(handles.SliderCMScaling,'Value',100.0);
% The BPM and CM devices
try
    [BPM, CM, Flags, EVectors] = setorbitsetup;
catch
    Flags{1}.NIter = 3;
    Flags{1}.SVDIndex = [];
    Flags{1}.GoalOrbit = 'Golden';
    Flags{1}.PlaneFlag = 0;
    BPM.BPMxString{1} = sprintf('%s', gethbpmfamily);
    BPM.BPMyString{1} = sprintf('%s', getvbpmfamily);
    BPM.BPMx{1} = getx('Struct');
    BPM.BPMy{1} = gety('Struct');
    CM.HCMString{1} = sprintf('%s', gethcmfamily);
    CM.VCMString{1} = sprintf('%s', getvcmfamily);
    CM.HCM{1} = getsp(gethcmfamily, 'Struct');
    CM.VCM{1} = getsp(getvcmfamily, 'Struct');
    EVectors = [];
end
% Add number of devices to pulldown lists
for i = 1:length(BPM.BPMxString)
    Data = BPM.BPMx{i};
    if iscell(Data)
        NumberOfDevices = 0;
        for j = 1:length(BPM.BPMxString)
            NumberOfDevices = NumberOfDevices + size(Data{j}.DeviceList,1);
        end
    else
        NumberOfDevices = size(Data.DeviceList,1);
    end
    BPM.BPMxString{i} = sprintf('%s  (%d)', BPM.BPMxString{i}, NumberOfDevices);
end
for i = 1:length(BPM.BPMyString)
    Data = BPM.BPMy{i};
    if iscell(Data)
        NumberOfDevices = 0;
        for j = 1:length(BPM.BPMyString)
            NumberOfDevices = NumberOfDevices + size(Data{j}.DeviceList,1);
        end
    else
        NumberOfDevices = size(Data.DeviceList,1);
    end
    BPM.BPMyString{i} = sprintf('%s  (%d)', BPM.BPMyString{i}, NumberOfDevices);
end
for i = 1:length(CM.HCMString)
    Data = CM.HCM{i};
    if iscell(Data)
        NumberOfDevices = 0;
        for j = 1:length(CM.HCMString)
            NumberOfDevices = NumberOfDevices + size(Data{j}.DeviceList,1);
        end
    else
        NumberOfDevices = size(Data.DeviceList,1);
    end
    CM.HCMString{i} = sprintf('%s  (%d)', CM.HCMString{i}, NumberOfDevices);
end
for i = 1:length(CM.VCMString)
    Data = CM.VCM{i};
    if iscell(Data)
        NumberOfDevices = 0;
        for j = 1:length(CM.VCMString)
            NumberOfDevices = NumberOfDevices + size(Data{j}.DeviceList,1);
        end
    else
        NumberOfDevices = size(Data.DeviceList,1);
    end
    CM.VCMString{i} = sprintf('%s  (%d)', CM.VCMString{i}, NumberOfDevices);
end
% Set pull down strings
set(handles.SelectBPMx, 'String', BPM.BPMxString);
set(handles.SelectBPMy, 'String', BPM.BPMyString);
set(handles.SelectHCM,  'String', CM.HCMString);
set(handles.SelectVCM,  'String', CM.VCMString);
% Initialize variables
setappdata(handles.figure1, 'BPMxCell', BPM.BPMx);
setappdata(handles.figure1, 'BPMxCellOriginal', BPM.BPMx);
setappdata(handles.figure1, 'BPMyCell', BPM.BPMy);
setappdata(handles.figure1, 'BPMyCellOriginal', BPM.BPMy);
setappdata(handles.figure1, 'HCMCell', CM.HCM);
setappdata(handles.figure1, 'HCMCellOriginal', CM.HCM);
setappdata(handles.figure1, 'VCMCell', CM.VCM);
setappdata(handles.figure1, 'VCMCellOriginal', CM.VCM);
setappdata(handles.figure1, 'FlagsCell', Flags);
setappdata(handles.figure1, 'EVectors', EVectors);
setappdata(handles.figure1, 'OCS', '');
% Set the edit box equal to the slider value
set(handles.EditCMScaling, 'String', sprintf('%.1f',get(handles.SliderCMScaling,'Value')));
% Resize to less plots
%set(handles.Plots0, 'Checked', 'Off');
%set(handles.Plots3, 'Checked', 'On');
%set(handles.Plots6, 'Checked', 'Off');
FigResize_Callback(hObject, eventdata, handles);
% Update
SelectFlags_Callback(handles.HorizontalPlane, eventdata, handles);
% --------------------------------------------------------------------
function SelectFlags_Callback(hObject, eventdata, handles)
% Plane
% Family = get(hObject,'Tag');
% Family(1:6) = '';
% UpdateFlag = 1;
% if strcmpi(Family, 'BPMx') & ~get(handles.HorizontalPlane, 'Value')
%    UpdateFlag = 0;
% elseif strcmpi(Family, 'HCM') & ~get(handles.HorizontalPlane, 'Value')
%    UpdateFlag = 0;
% elseif strcmpi(Family, 'BPMy') & ~get(handles.VerticalPlane, 'Value')
%    UpdateFlag = 0;
% elseif strcmpi(Family, 'VCM') & ~get(handles.VerticalPlane, 'Value')
%    UpdateFlag = 0;
% end
% Orbit (Default, can get over written by FlagsCell)
set(handles.RadioButton_Golden, 'Value', 1);
set(handles.RadioButton_Offset, 'Value', 0);
set(handles.RadioButton_File,   'Value', 0);
set(handles.RadioButton_Save,   'Value', 0);
FlagsCell = getappdata(handles.figure1, 'FlagsCell');
if ~isempty(FlagsCell)
    if iscell(FlagsCell)
        i = get(hObject, 'Value');
        if length(FlagsCell) == 1
            Flags = FlagsCell{1};
        else
            Flags = FlagsCell{i};
        end
    else
        Flags = FlagsCell;
    end
    % Plane
    %if isfield(Flags, 'PlaneFlag')
    %    if Flags.PlaneFlag == 1
    %        set(handles.HorizontalPlane, 'Value', 1);
    %        set(handles.VerticalPlane,   'Value', 0);
    %    elseif Flags.PlaneFlag == 2
    %        set(handles.HorizontalPlane, 'Value', 0);
    %        set(handles.VerticalPlane,   'Value', 1);
    %    end
    %end
    % Orbit
    if isfield(Flags, 'GoalOrbit')
        if strcmpi(Flags.GoalOrbit, 'Golden')
            set(handles.RadioButton_Golden, 'Value', 1);
            set(handles.RadioButton_Offset, 'Value', 0);
            set(handles.RadioButton_File,   'Value', 0);
            set(handles.RadioButton_Save,   'Value', 0);
        elseif strcmpi(Flags.GoalOrbit, 'Offset')
            set(handles.RadioButton_Golden, 'Value', 0);
            set(handles.RadioButton_Offset, 'Value', 1);
            set(handles.RadioButton_File,   'Value', 0);
            set(handles.RadioButton_Save,   'Value', 0);
        end
    end
    % Interations
    if isfield(Flags, 'NIter')
        Flags.NIter = round(Flags.NIter);
        if Flags.NIter>15 && Flags.NIter~=Inf
            Flags.NIter = 15;
        end
        if Flags.NIter < 1
            Flags.NIter = 1;
        end
        if Flags.NIter == Inf
            set(handles.PopUpMenu_Iterations, 'Value', 16);
        else
            set(handles.PopUpMenu_Iterations, 'Value', Flags.NIter);
        end
    end
end
% Update the number of SV to use
CalcSVD(handles);
set(handles.GetOrbit,'Enable','On')
if get(handles.HorizontalPlane,'Value') == 1
    set(handles.SelectBPMx, 'Enable', 'On')
    set(handles.SelectHCM,  'Enable', 'On')
else
    set(handles.SelectBPMx, 'Enable', 'Off')
    set(handles.SelectHCM,  'Enable', 'Off')
    if get(handles.VerticalPlane,'Value') == 0
        set(handles.GetOrbit, 'Enable', 'Off')
    end
end
% if get(handles.VerticalPlane,'Value') == 1
%     set(handles.SelectBPMy, 'Enable', 'On')
%     set(handles.SelectVCM,  'Enable', 'On')
% else
%     set(handles.SelectBPMy, 'Enable', 'Off')
%     set(handles.SelectVCM,  'Enable', 'Off')
%     if get(handles.HorizontalPlane,'Value') == 0
%         set(handles.GetOrbit, 'Enable', 'Off')
%     end
% end
% Update the plots
GetOrbit_Callback(hObject, eventdata, handles);
function CalcSVD(handles)
% SVD
SVDStart = str2num(get(handles.Edit_SVD, 'String'));
try
    SVDIndex = 0;
    EVectors = getappdata(handles.figure1, 'EVectors');
    if isstruct(EVectors)
        if get(handles.HorizontalPlane, 'Value') == 1
            SVDIndex = SVDIndex + EVectors.BPMx(get(handles.SelectBPMx,'Value'));
            SVDIndex = SVDIndex + EVectors.HCM(get(handles.SelectHCM,'Value'));
        end
        if get(handles.VerticalPlane, 'Value') == 1
            SVDIndex = SVDIndex + EVectors.BPMy(get(handles.SelectBPMy,'Value'));
            SVDIndex = SVDIndex + EVectors.VCM(get(handles.SelectVCM,'Value'));
        end
    else
        if all(size(EVectors)==[1 1])
            SVDIndex = EVectors;
        else
            SVDIndex = SVDStart;
        end
    end
catch
    SVDIndex = SVDStart;
end
set(handles.Edit_SVD, 'String', num2str(SVDIndex));
% --------------------------------------------------------------------
function HorizontalPlane_Callback(hObject, eventdata, handles)
if get(hObject,'Value')
    set(handles.SelectBPMx, 'Enable', 'On')
    set(handles.SelectHCM,  'Enable', 'On')
    set(handles.GetOrbit,   'Enable', 'On')
else
    set(handles.SelectBPMx, 'Enable', 'Off')
    set(handles.SelectHCM,  'Enable', 'Off')
    % Make sure the RF is out of the fit if the horizontal plane is off
    set(handles.RadioButton_RF, 'Value', 0);
end
if ~get(hObject,'Value') && ~get(handles.VerticalPlane,'Value')
    set(handles.GetOrbit,'Enable','Off')
end
% Update the number of SV to use
CalcSVD(handles);
% Update the plots
GetOrbit_Callback(hObject, eventdata, handles);
% --------------------------------------------------------------------
function VerticalPlane_Callback(hObject, eventdata, handles)
if get(handles.VerticalPlane,'Value')
    set(handles.SelectBPMy, 'Enable', 'On')
    set(handles.SelectVCM,  'Enable', 'On')
    set(handles.GetOrbit,   'Enable', 'On')
else
    set(handles.SelectBPMy, 'Enable', 'Off')
    set(handles.SelectVCM,  'Enable', 'Off')
end
if ~get(hObject,'Value') && ~get(handles.HorizontalPlane,'Value')
    set(handles.GetOrbit,'Enable','Off')
end
% Update the number of SV to use
CalcSVD(handles);
% Update the plots
GetOrbit_Callback(hObject, eventdata, handles);
% --------------------------------------------------------------------
function SliderCMScaling_Callback(hObject, eventdata, handles)
set(handles.EditCMScaling, 'String', sprintf('%.1f',get(handles.SliderCMScaling,'Value')));
% --------------------------------------------------------------------
function EditCMScaling_Callback(hObject, eventdata, handles)
val = str2num(get(handles.EditCMScaling,'String'));
% Determine whether val is a number between 0 and 1
if isnumeric(val) && length(val)==1 && ...
    val >= get(handles.SliderCMScaling,'Min') && ...
    val <= get(handles.SliderCMScaling,'Max')
    set(handles.SliderCMScaling,'Value',val);
end
% --------------------------------------------------------------------
function ScaleCorrectors_Callback(hObject, eventdata, handles)
Gain = get(handles.SliderCMScaling,'Value')/100;
if Gain == 1
    return;
end
% Disable buttons during setpoint change
set(handles.GetOrbit,              'Enable',  'Off');
set(handles.ApplyCorrection,       'Enable',  'Off');
set(handles.RemoveCorrection,      'Enable',  'Off');
set(handles.ScaleCorrectors,       'Enable',  'Off');
set(handles.FileMenu,              'Enable',  'Off');
set(handles.EditMenu,              'Enable',  'Off');
set(handles.LatticeMenu,           'Enable',  'Off');
set(handles.RadioButton_Golden,    'Enable',  'Off');
set(handles.RadioButton_Offset,    'Enable',  'Off');
set(handles.RadioButton_File,      'Enable',  'Off');
set(handles.RadioButton_Save,      'Enable',  'Off');
set(handles.GetFile,               'Enable',  'Off');
set(handles.SaveOrbit,             'Enable',  'Off');
set(handles.Edit_SVD,              'Enable',  'Off');
set(handles.HorizontalPlane,       'Enable',  'Off');
set(handles.VerticalPlane,         'Enable',  'Off');
set(handles.SelectBPMx,            'Enable',  'Off');
set(handles.SelectBPMy,            'Enable',  'Off');
set(handles.SelectHCM,             'Enable',  'Off');
set(handles.SelectVCM,             'Enable',  'Off');
set(handles.PopUpMenu_Iterations,  'Enable',  'Off');
drawnow;
i = 0;
if get(handles.HorizontalPlane,'Value') == 1
    CMCell = getappdata(handles.figure1, 'HCMCell');
    iCell = get(handles.SelectHCM,'Value');
    Data = CMCell{iCell};
    if iscell(Data)
        % Cells
        for j = 1:length(Data)
            i = i + 1;
            SP{i} = getsp(Data{j}, 'Struct');
        end
    else
        % Data structure
        i = i + 1;
        SP{i} = getsp(Data, 'Struct');
    end
end
if get(handles.VerticalPlane,'Value') == 1
    CMCell = getappdata(handles.figure1, 'VCMCell');
    iCell = get(handles.SelectHCM,'Value');
    Data = CMCell{iCell};
    if iscell(Data)
        % Cells
        for j = 1:length(Data)
            i = i + 1;
            SP{i} = getpv(Data{j}, 'Struct');
        end
    else
        % Data structure
        i = i + 1;
        SP{i} = getpv(Data, 'Struct');
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% SaveOrbit the prsent setpoints %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
SP_History = getappdata(handles.figure1, 'SP_History');
SPwithRF = SP;
SPwithRF{length(SPwithRF)+1} = getrf('Struct');
SP_History{length(SP_History)+1} = SPwithRF;
setappdata(handles.figure1, 'SP_History', SP_History);
set(handles.RemoveCorrection, 'String', sprintf('Remove Correction %d',length(SP_History)))
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Set everything again with a wait flag of 0 then -1 %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if exist('turnoff','file') == 2
    for i = 1:length(SP)
        turnoff(SP{i}.FamilyName, SP{i}.DeviceList, Gain);
    end
else
    for i = 1:length(SP)
        SP{i}.Data = Gain * SP{i}.Data;
        setpv(SP{i}, 0);
    end
    for i = 1:length(SP)
        setpv(SP{i}, -1);
    end
end
% Get new BPM data and update plots
GetOrbit_Callback(hObject, eventdata, handles);
% Re-enable buttons
set(handles.GetOrbit,              'Enable',  'On');
set(handles.ApplyCorrection,       'Enable',  'On');
set(handles.RemoveCorrection,      'Enable',  'On');
set(handles.ScaleCorrectors,       'Enable',  'On');
set(handles.FileMenu,              'Enable',  'On');
set(handles.EditMenu,              'Enable',  'On');
set(handles.LatticeMenu,           'Enable',  'On');
set(handles.RadioButton_Golden,    'Enable',  'On');
set(handles.RadioButton_Offset,    'Enable',  'On');
set(handles.RadioButton_File,      'Enable',  'On');
set(handles.RadioButton_Save,      'Enable',  'On');
set(handles.GetFile,               'Enable',  'On');
set(handles.SaveOrbit,             'Enable',  'On');
set(handles.Edit_SVD,              'Enable',  'On');
set(handles.HorizontalPlane,       'Enable',  'On');
set(handles.VerticalPlane,         'Enable',  'On');
set(handles.SelectBPMx,            'Enable',  'On');
set(handles.SelectBPMy,            'Enable',  'On');
set(handles.SelectHCM,             'Enable',  'On');
set(handles.SelectVCM,             'Enable',  'On');
set(handles.PopUpMenu_Iterations,  'Enable',  'On');
% --------------------------------------------------------------------
function EditDevice_Callback(hObject, eventdata, handles)
%Family = 'BPMx';
Family = get(hObject,'Tag');
Family(1:4) = '';
DataCell         = getappdata(handles.figure1, [Family, 'Cell']);
DataCellOriginal = getappdata(handles.figure1, [Family, 'CellOriginal']);
iCell = get(handles.(['Select',Family]), 'Value');
Data = DataCell{iCell};
DataOriginal = DataCellOriginal{iCell};
NumberOfDevices = 0;
if iscell(DataOriginal)
    % Cell array
    for i = 1:length(DataOriginal)
        DeviceListTotal = family2dev(DataOriginal{i}.FamilyName);
        %DeviceListTotal = DataOriginal{i}.DeviceList;
        CheckList = zeros(size(DeviceListTotal,1),1);
        iDev = findrowindex(Data{i}.DeviceList, DeviceListTotal);
        CheckList(iDev) = 1;
        Data{i}.DeviceList = editlist(DeviceListTotal, Data{i}.FamilyName, CheckList);
        NumberOfDevices = NumberOfDevices + size(Data{i}.DeviceList,1);
    end
else
    % Data structure
    DeviceListTotal = family2dev(DataOriginal.FamilyName);
    %DeviceListTotal = DataOriginal.DeviceList;
    CheckList = zeros(size(DeviceListTotal,1),1);
    iDev = findrowindex(Data.DeviceList, DeviceListTotal);
    CheckList(iDev) = 1;
    Data.DeviceList = editlist(DeviceListTotal, Data.FamilyName, CheckList);
    NumberOfDevices = NumberOfDevices + size(Data.DeviceList,1);
end
DataCell{iCell} = Data;
setappdata(handles.figure1, [Family, 'Cell'], DataCell);
% Change the number of devices in the pulldown string
try
    StringCell = get(handles.(['Select',Family]), 'String');
    TitleString = StringCell{iCell};
    i = findstr(TitleString,'(');
    if ~isempty(i)
        TitleString = sprintf('%s  (%d)', TitleString(1:i(end)-1), NumberOfDevices);
        StringCell{iCell} = TitleString;
        set(handles.(['Select',Family]), 'String', StringCell);
    end
catch
end
GetOrbit_Callback(hObject, eventdata, handles);
% --------------------------------------------------------------------
function GetOrbit_Callback(hObject, eventdata, handles)
% setorbit(goalorbit,getx('Struct'),getsp('HCM','struct'),'NoSetSP','FigureHandles',[handles.axes1;handles.axes2;handles.axes3]);
RemoveCorrectionEnable = get(handles.RemoveCorrection, 'Enable');
set(handles.MinimumPeriod,    'Enable', 'Off');
set(handles.RemoveCorrection, 'Enable', 'Off');
set(handles.ApplyCorrection,  'Enable', 'Off');
set(handles.GetOrbit,         'Enable', 'Off');
drawnow;
OCS = getappdata(handles.figure1, 'OCS');
OCS.BPM       = [];
OCS.BPMWeight = [];
OCS.CM        = [];
OCS.CMWeight  = [];
i = 0;
if get(handles.HorizontalPlane,'Value') == 1
    i = i + 1;
    BPMCell = getappdata(handles.figure1, 'BPMxCell');
    j = get(handles.SelectBPMx,'Value');
    if iscell(BPMCell{j})
        OCS.BPM = BPMCell{j};
    else
        OCS.BPM{i} = BPMCell{j};
    end
    CMCell = getappdata(handles.figure1, 'HCMCell');
    j = get(handles.SelectHCM,'Value');
    if iscell(CMCell{j})
        OCS.CM = CMCell{j};
    else
        OCS.CM{i} = CMCell{j};
    end
    % Use default column weights
    OCS.CMWeight{i} = [];
end
if get(handles.VerticalPlane,'Value') == 1
    i = i + 1;
    BPMCell = getappdata(handles.figure1, 'BPMyCell');
    j = get(handles.SelectBPMy,'Value');
    if iscell(BPMCell{j})
        OCS.BPM = [OCS.BPM BPMCell{j}];
    else
        OCS.BPM{i} = BPMCell{j};
    end
    CMCell = getappdata(handles.figure1, 'VCMCell');
    j = get(handles.SelectVCM,'Value');
    if iscell(CMCell{j})
        OCS.CM = [OCS.CM CMCell{j}];
    else
        OCS.CM{i} = CMCell{j};
    end
    % Use default column weights
    OCS.CMWeight{i} = [];
end
if i==0
    return;
end
%%%%%%%%%%%%%%%%%%%%%%%
% Find the goal orbit %
%%%%%%%%%%%%%%%%%%%%%%%
% Goal orbit: golden orbit
if get(handles.RadioButton_Golden,'Value') == 1
    OCS.GoalOrbit = 'Golden';
end
% Goal orbit: offset orbit
if get(handles.RadioButton_Offset,'Value') == 1
    OCS.GoalOrbit = 'Offset';
end
% Goal orbit: saved orbit
if get(handles.RadioButton_Save,'Value') == 1
    OCS.GoalOrbit = [];
    bpmsave = getappdata(handles.figure1,'bpmsave');
    ErrorFlag = 0;
    for i = 1:length(OCS.BPM)
        for j = 1:length(bpmsave)
            if strcmp(OCS.BPM{i}.FamilyName, bpmsave{j}.FamilyName)
                [k, iNotFound] = findrowindex(OCS.BPM{i}.DeviceList, bpmsave{j}.DeviceList);
                if isempty(iNotFound)
                    OCS.GoalOrbit{i} = bpmsave{j}.Data(k);
                else
                    uiwait(warndlg({'BPMs not found in the save!','Setting the goal orbit to the golden orbit.'},'SETORBIT','Modal'));
                    set(handles.RadioButton_Golden,'Value', 1)
                    set(handles.RadioButton_Save,'Value', 0)
                    OCS.GoalOrbit = 'golden';
                    ErrorFlag = 1;
                    break;
                end
            end
        end
        if ErrorFlag
            break;
        end
    end
end
% Goal orbit from file
if get(handles.RadioButton_File,'Value') == 1
    FileName = getappdata(handles.figure1, 'FileName');
    OCS.GoalOrbit = [];
    for i = 1:length(OCS.BPM)
        OCS.GoalOrbit{i} = getdata(OCS.BPM{i}, FileName, 'Numeric');
        if any(isnan(OCS.GoalOrbit{i}))
            uiwait(warndlg({'BPMs not found in the file!','Setting the goal orbit to the golden orbit.'},'SETORBIT','Modal'));
            set(handles.RadioButton_Golden,'Value', 1)
            set(handles.RadioButton_Save,'Value', 0)
            OCS.GoalOrbit = 'golden';
            break;
        end
    end
end
OCS.SVDIndex = str2num(get(handles.Edit_SVD,'String'));
% Remove flags for now
if isfield(OCS, 'BPMWeight')
    OCS = rmfield(OCS, 'BPMWeight');
end
% RF flag
if get(handles.RadioButton_RF,'Value') == 1
    OCS.FitRF = 1;
else
    OCS.FitRF = 0;
end
% Update the BPM, CM, and RF
for i = 1:length(OCS.BPM)
    OCS.BPM{i} = getpv(OCS.BPM{i});
end
for i = 1:length(OCS.CM)
    OCS.CM{i} = getpv(OCS.CM{i});
end
OCS.RF = getrf('Struct');
% Iterations
NIter = get(handles.PopUpMenu_Iterations,'Value');
if NIter == 16
    NIter = Inf;
end
OCS.NIter = NIter;
% Update plots
OCS.Handles.TimeStamp = handles.GetOrbit;
setappdata(handles.figure1,'OCS',OCS);
UpdatePlots(handles);
OCS = getappdata(handles.figure1, 'OCS');
set(handles.ApplyCorrection, 'String', 'Apply Correction');
set(handles.GetOrbit,        'String', sprintf('Get Orbit: %s',datestr(OCS.BPM{1}.TimeStamp,0)),'FontSize',9.0);
set(handles.GetOrbit,         'Enable', 'On');
set(handles.MinimumPeriod,    'Enable', 'On');
set(handles.ApplyCorrection,  'Enable', 'On');
set(handles.SaveOrbit,        'Enable', 'On');
set(handles.RemoveCorrection, 'Enable', RemoveCorrectionEnable);
% --------------------------------------------------------------------
function StopCorrection_Callback(hObject, eventdata, handles)
% Stop corrector goes to the matlab command window
RingSetOrbit.RunFlag = -1;
setappdata(0, 'RingSetOrbit', RingSetOrbit);
% --------------------------------------------------------------------
function ApplyCorrection_Callback(hObject, eventdata, handles)
set(handles.figure1, 'HandleVisibility','Callback');
RingSetOrbit.RunFlag = 1;
setappdata(0, 'RingSetOrbit', RingSetOrbit);
OCS = getappdata(handles.figure1, 'OCS');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% SaveOrbit the present setpoints %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
CM = OCS.CM;
CM{length(CM)+1} = OCS.RF;
SP_History = getappdata(handles.figure1, 'SP_History');
SP_History{length(SP_History)+1} = CM;
setappdata(handles.figure1, 'SP_History', SP_History);
set(handles.RemoveCorrection, 'String', sprintf('Remove Correction %d',length(SP_History)))
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Make the corrector starting with the present OCS setpoints %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
set(handles.FileMenu,              'Enable',  'Off');
set(handles.EditBPMx,              'Enable',  'Off');
set(handles.EditBPMy,              'Enable',  'Off');
set(handles.EditHCM,               'Enable',  'Off');
set(handles.EditVCM,               'Enable',  'Off');
set(handles.LatticeMenu,           'Enable',  'Off');
set(handles.RadioButton_Golden,    'Enable',  'Off');
set(handles.RadioButton_Offset,    'Enable',  'Off');
set(handles.RadioButton_File,      'Enable',  'Off');
set(handles.RadioButton_Save,      'Enable',  'Off');
set(handles.GetFile,               'Enable',  'Off');
set(handles.SaveOrbit,             'Enable',  'Off');
set(handles.Edit_SVD,              'Enable',  'Off');
set(handles.HorizontalPlane,       'Enable',  'Off');
set(handles.VerticalPlane,         'Enable',  'Off');
set(handles.SelectBPMx,            'Enable',  'Off');
set(handles.SelectBPMy,            'Enable',  'Off');
set(handles.SelectHCM,             'Enable',  'Off');
set(handles.SelectVCM,             'Enable',  'Off');
set(handles.PopUpMenu_Iterations,  'Enable',  'Off');
set(handles.ScaleCorrectors,       'Enable',  'Off');
set(handles.GetOrbit,              'Enable',  'Off');
set(handles.RemoveCorrection,      'Enable',  'Off');
NIter = get(handles.PopUpMenu_Iterations,'Value');
if NIter == 16
    NIter = Inf;
end
OCS.NIter = NIter;
if NIter > 1
    set(handles.GetOrbit,         'String',  'GetOrbit');
    set(handles.ApplyCorrection,  'Enable',  'Off');
    set(handles.ApplyCorrection,  'Visible', 'Off');
    set(handles.StopCorrection,   'Enable',  'On');
    set(handles.StopCorrection,   'Visible', 'On');
else
    set(handles.ApplyCorrection,  'Enable',  'Off');
end
drawnow;
% MinimumPeriodString = get(handles.MinimumPeriod,'String');
% if isempty(MinimumPeriodString)
%     OCS.MinimumPeriod = [];
% else
%     OCS.MinimumPeriod = str2num(MinimumPeriodString);
% end
% if isempty(OCS.MinimumPeriod) || OCS.MinimumPeriod < 0
%     OCS.MinimumPeriod = 0;
% end
AxesHandles = [handles.axes1;handles.axes2;handles.axes3;];
if strcmpi(get(handles.Plots0,'Checked'),'On')
    OCS = setorbit(OCS, 'NoGetPV', 'NoDisplay');
else
    if strcmpi(get(handles.Plots6,'Checked'),'On')
        % Only update 6 plots if GetOrbit was not already called
        if isempty(findstr(get(get(handles.axes3,'YLabel'),'String'),'Residual'))
            AxesHandles = [handles.axes1;handles.axes2;handles.axes3;handles.axes4;handles.axes5;handles.axes6;];
        end
    end
    OCS = setorbit(OCS, 'NoGetPV', 'FigureHandles', AxesHandles);
end
try
    % If the figure was closed then handles is on longer valie
    setappdata(handles.figure1, 'OCS', OCS);
    %%%%%%%%%%%%%%%%%
    % Update figure %
    %%%%%%%%%%%%%%%%%
    set(handles.FileMenu,              'Enable',  'On');
    set(handles.EditBPMx,              'Enable',  'On');
    set(handles.EditBPMy,              'Enable',  'On');
    set(handles.EditHCM,               'Enable',  'On');
    set(handles.EditVCM,               'Enable',  'On');
    set(handles.LatticeMenu,           'Enable',  'On');
    set(handles.RadioButton_Golden,    'Enable',  'On');
    set(handles.RadioButton_Offset,    'Enable',  'On');
    set(handles.RadioButton_File,      'Enable',  'On');
    set(handles.RadioButton_Save,      'Enable',  'On');
    set(handles.GetFile,               'Enable',  'On');
    set(handles.SaveOrbit,             'Enable',  'On');
    set(handles.Edit_SVD,              'Enable',  'On');
    set(handles.HorizontalPlane,       'Enable',  'On');
    set(handles.VerticalPlane,         'Enable',  'On');
    set(handles.SelectBPMx,            'Enable',  'On');
    set(handles.SelectBPMy,            'Enable',  'On');
    set(handles.SelectHCM,             'Enable',  'On');
    set(handles.SelectVCM,             'Enable',  'On');
    set(handles.PopUpMenu_Iterations,  'Enable',  'On');
    set(handles.ScaleCorrectors,       'Enable',  'On');
    set(handles.RemoveCorrection,      'Enable',  'On');
    set(handles.StopCorrection,   'Visible', 'Off');
    set(handles.StopCorrection,   'Enable',  'Off');
    set(handles.ApplyCorrection,  'Visible', 'On');
    set(handles.ApplyCorrection,  'Enable',  'On');
    set(handles.GetOrbit,         'Enable',  'On');
    set(handles.GetOrbit,         'String', sprintf('Get Orbit: %s',datestr(OCS.BPM{1}.TimeStamp,0)),'FontSize',9.0);
    drawnow;
catch
end
set(handles.figure1, 'HandleVisibility','Off');
% --------------------------------------------------------------------
function RemoveCorrection_Callback(hObject, eventdata, handles)
CM = getappdata(handles.figure1, 'SP_History');
if ~isempty(CM)
    set(handles.GetOrbit,         'Enable', 'Off');
    set(handles.ApplyCorrection,  'Enable', 'Off');
    set(handles.RemoveCorrection, 'Enable', 'Off');
    drawnow;
    % Set (note: RF could be one the CM structures)
    CMlast = CM{end};
    for i = 1:length(CMlast)
        setpv(CMlast{i},  0);
    end
    for i = 1:length(CMlast)
        setpv(CMlast{i}, -1);
    end
    % Remove the last set
    CM(end) = [];
    setappdata(handles.figure1, 'SP_History', CM);
    % Get new BPM data and update plots
    GetOrbit_Callback(hObject, eventdata, handles);
    if isempty(CM)
        set(handles.RemoveCorrection, 'Enable', 'Off');
        set(handles.RemoveCorrection, 'String', 'Remove Correction');
    else
        set(handles.RemoveCorrection, 'Enable', 'On');
        set(handles.RemoveCorrection, 'String', sprintf('Remove Correction %d',length(CM)));
    end
    drawnow;
end
% --------------------------------------------------------------------
function GetFile_Callback(hObject, eventdata, handles)
DirectoryName = getfamilydata('Directory','DataRoot');
[FileName, DirectoryName] = uigetfile('*.mat', 'Select a File', DirectoryName);
if FileName == 0
    return
end
setappdata(handles.figure1, 'FileName', [DirectoryName FileName]);
set(handles.GetFile, 'String', sprintf('File:%s', FileName), 'FontSize', 8.0);
set(handles.RadioButton_File,'Enable','On');
% % Automatically set the filemenu radio button
% set(handles.RadioButton_File,'Value', 1);
% RadioButton_File_Callback(hObject, eventdata, handles);
% --------------------------------------------------------------------
function RadioButton_Offset_Callback(hObject, eventdata, handles)
set(handles.RadioButton_Golden,'Value', 0);
set(handles.RadioButton_File,'Value', 0);
set(handles.RadioButton_Save,'Value', 0);
set(handles.RadioButton_Offset,'Value', 1);
OCS = getappdata(handles.figure1, 'OCS');
if ~isfield(OCS,'BPM')
    return;
end
OCS.GoalOrbit = 'Offset';
% Update plots
setappdata(handles.figure1,'OCS',OCS);
UpdatePlots(handles);
1000 % --------------------------------------------------------------------
1001 function RadioButton_Golden_Callback(hObject, eventdata, handles)
1002 set(handles.RadioButton_Offset,'Value', 0);
1003 set(handles.RadioButton_File,'Value', 0);
1004 set(handles.RadioButton_Save,'Value', 0);
1005 set(handles.RadioButton_Golden,'Value', 1);
1006
1007 OCS = getappdata(handles.figure1, 'OCS');
1008 if ~isfield(OCS,'BPM')
1009     return;
1010 end
1011 OCS.GoalOrbit = 'Golden';
1012
1013 % Update plots
1014 setappdata(handles.figure1,'OCS',OCS);
1015 UpdatePlots(handles);
1016
1017
1018
1019 % --------------------------------------------------------------------
1020 function RadioButton_File_Callback(hObject, eventdata, handles)
1021 set(handles.RadioButton_Offset,'Value', 0);
1022 set(handles.RadioButton_File,'Value', 1);
1023 set(handles.RadioButton_Save,'Value', 0);
1024 set(handles.RadioButton_Golden,'Value', 0);
1025
1026 OCS = getappdata(handles.figure1,'OCS');
1027 if ~isfield(OCS,'BPM')
1028     return;
1029 end
1030 FileName = getappdata(handles.figure1, 'FileName');
1031 OCS.GoalOrbit = [];
1032 for i = 1:length(OCS.BPM)
1033     OCS.GoalOrbit{i} = getdata(OCS.BPM{i}, FileName, 'Numeric');
1034     if any(isnan(OCS.GoalOrbit{i}))
1035         uiwait(warndlg({'BPMs not found in the file!','Setting the goal orbit to the golden orbit.'},'SETORBIT','Modal'));
1036         set(handles.RadioButton_Golden,'Value', 1)
1037         set(handles.RadioButton_File,'Value', 0)
1038             OCS.GoalOrbit = 'golden';
1039             break;
1040     end
1041 end
1042
1043 setappdata(handles.figure1,'OCS',OCS);
1044
1045 % Update plots
1046 UpdatePlots(handles);
1047
1048
1049
1050 % --------------------------------------------------------------------
1051 function RadioButton_Save_Callback(hObject, eventdata, handles)
1052 set(handles.RadioButton_Golden,'Value', 0);
1053 set(handles.RadioButton_File,'Value', 0);
1054 set(handles.RadioButton_Offset,'Value', 0);
1055 set(handles.RadioButton_Save,'Value', 1);
1056
1057 OCS = getappdata(handles.figure1,'OCS');
1058 if ~isfield(OCS,'BPM')
1059     return;
1060 end
1061 OCS.GoalOrbit = [];
1062 bpmsave = getappdata(handles.figure1,'bpmsave');
1063 ErrorFlag = 0;
1064 for i = 1:length(OCS.BPM)
1065     for j = 1:length(bpmsave)
1066         if strcmp(OCS.BPM{i}.FamilyName, bpmsave{j}.FamilyName)
1067             [k, iNotFound] = findrowindex(OCS.BPM{i}.DeviceList, bpmsave{j}.DeviceList);
1068             if isempty(iNotFound)
1069                 OCS.GoalOrbit{i} = bpmsave{j}.Data(k);
1070             else
1071                 uiwait(warndlg({'BPMs not found in the save!','Setting the goal orbit to the golden orbit.'},'SETORBIT','Modal'));
1072                 set(handles.RadioButton_Golden,'Value', 1)
1073                 set(handles.RadioButton_Save,'Value', 0)
1074                 OCS.GoalOrbit = 'golden';
1075                 ErrorFlag = 1;
1076                 break;
1077             end
1078         end
1079     end
1080     if ErrorFlag
1081         break;
1082     end
1083 end
1084
1085 setappdata(handles.figure1,'OCS',OCS);
1086
1087 % Update plots
1088 UpdatePlots(handles);
1089
1090
1091 % --------------------------------------------------------------------
1092 function SaveOrbit_Callback(hObject, eventdata, handles)
1093
1094 OCS = getappdata(handles.figure1, 'OCS');
1095 set(handles.SaveOrbit,'String', sprintf('Save: %s',datestr(OCS.CM{1}.TimeStamp,0)),'FontSize',9.0);
1096 bpmsave = OCS.BPM;
1097 setappdata(handles.figure1,'bpmsave',bpmsave);
1098
1099 if get(handles.RadioButton_Save,'Value') == 1
1100     RadioButton_Save_Callback(hObject, eventdata, handles);
1101 end
1102 set(handles.RadioButton_Save,'Enable','On');
1103 % set(handles.SaveOrbit,'Enable','Off');
1104
1105 % % Automatically set the save radio button
1106 % set(handles.RadioButton_Save,'Value', 1);
1107 % RadioButton_Save_Callback(hObject, eventdata, handles);
1108
1109
1110
1111 % --------------------------------------------------------------------
1112 function SaveOrbitToFile_Callback(hObject, eventdata, handles)
1113
1114 OCS = getappdata(handles.figure1, 'OCS');
1115 BPMData = OCS.BPM;
1116
1117 DirStart = pwd;
1118 FileName = appendtimestamp('BPMData', BPMData{1}.TimeStamp);
1119 DirectoryName = getfamilydata('Directory', 'DataRoot');
1120 [FileName, DirectoryName] = uiputfile('*.mat', 'Select File (Cancel to not save to a file)', [DirectoryName FileName, '.mat']);
1121 if FileName == 0
1122     return
1123 end
1124
1125 [DirectoryName, ErrorFlag] = gotodirectory(DirectoryName);
1126 save(FileName, 'BPMData');
1127 cd(DirStart);
1128 fprintf('   BPM data saved to %s\n', [DirectoryName FileName]);
1129
1130
1131 % --------------------------------------------------------------------
1132 function SaveOCS_Callback(hObject, eventdata, handles)
1133 OCS = getappdata(handles.figure1, 'OCS');
1134
1135 DirStart = pwd;
1136 FileName = appendtimestamp('OCS', OCS.BPM{1}.TimeStamp);
1137 DirectoryName = getfamilydata('Directory', 'DataRoot');
1138 [FileName, DirectoryName] = uiputfile('*.mat', 'Select File (Cancel to not save to a file)', [DirectoryName FileName, '.mat']);
1139 if FileName == 0
1140     return
1141 end
1142
1143 [DirectoryName, ErrorFlag] = gotodirectory(DirectoryName);
1144 save(FileName, 'OCS');
1145 cd(DirStart);
1146 fprintf('   OCS structure saved to %s\n', [DirectoryName FileName]);
1147
1148
1149
1150
1151 %%%%%%%%%%%%%
1152 % Pop Plots %
1153 %%%%%%%%%%%%%
1154 function Graph_1_Callback(hObject, eventdata, handles)
1155 a = figure;
1156 b = copyobj(handles.axes1, a);
1157 set(b, 'Position', [0.1300    0.1100    0.7750    .93*0.8150]);
1158
1159 function Graph_2_Callback(hObject, eventdata, handles)
1160 a = figure;
1161 b = copyobj(handles.axes2, a);
1162 set(b, 'Position', [0.1300    0.1100    0.7750    0.8150]);
1163
1164 function Graph_3_Callback(hObject, eventdata, handles)
1165 a = figure;
1166 b = copyobj(handles.axes3, a);
1167 set(b, 'Position', [0.1300    0.1100    0.7750    0.8150]);
1168
1169 function Graph_4_Callback(hObject, eventdata, handles)
1170 a = figure;
1171 b = copyobj(handles.axes4, a);
1172 set(b, 'Position', [0.1300    0.1100    0.7750    .93*0.8150]);
1173
1174 function Graph_5_Callback(hObject, eventdata, handles)
1175 a = figure;
1176 b = copyobj(handles.axes5, a);
1177 set(b, 'Position', [0.1300    0.1100    0.7750    0.8150]);
1178
1179 function Graph_6_Callback(hObject, eventdata, handles)
1180 a = figure;
1181 b = copyobj(handles.axes6, a);
1182 set(b, 'Position', [0.1300    0.1100    0.7750    0.8150]);
1183
1184
1185 function All_Graphs_Callback(hObject, eventdata, handles)
1186 if strcmpi(get(handles.Plots3,'Checked'),'On')
1187     a = figure;
1188     b = copyobj(handles.axes1, a);
1189     set(b, 'Position', [0.1300    0.7093    0.7750    0.2157]);
1190
1191     b = copyobj(handles.axes2, a);
1192     set(b, 'Position', [0.1300    0.4096    0.7750    0.2157]);
1193
1194     b = copyobj(handles.axes3, a);
1195     set(b, 'Position', [0.1300    0.1100    0.7750    0.2157]);
1196
1197     Data = getappdata(handles.figure1, 'OCS');
1198     if isfield(Data, 'TimeStamp')
1199         addlabel(1,0,datestr(OCS.CM{1}.TimeStamp,21));
1200     end
1201     orient tall
1202
1203 elseif strcmpi(get(handles.Plots6,'Checked'),'On')
1204     a = figure;
1205     b = copyobj(handles.axes1, a);
1206     set(b, 'Position', [0.1300    0.7093    0.3347    0.2157]);
1207
1208     b = copyobj(handles.axes2, a);
1209     set(b, 'Position', [0.1300    0.4096    0.3347    0.2157]);
1210
1211     b = copyobj(handles.axes3, a);
1212     set(b, 'Position', [0.1300    0.1100    0.3347    0.2157]);
1213
1214     b = copyobj(handles.axes4, a);
1215     set(b, 'Position', [0.5703    0.7093    0.3347    0.2157]);
1216
1217     b = copyobj(handles.axes5, a);
1218     set(b, 'Position', [0.5703    0.4096    0.3347    0.2157]);
1219
1220     b = copyobj(handles.axes6, a);
1221     set(b, 'Position', [0.5703    0.1100    0.3347    0.2157]);
1222
1223     Data = getappdata(handles.figure1, 'OCS');
1224     if isfield(Data, 'TimeStamp')
1225         addlabel(1,0,datestr(OCS.CM{1}.TimeStamp,21));
1226     end
1227
1228     orient tall
1229 end
1230
1231
1232 % --------------------------------------------------------------------
1233 function Edit_SVD_Callback(hObject, eventdata, handles)
1234 OCS = getappdata(handles.figure1,'OCS');
1235
1236 a = get(handles.Edit_SVD,'String');
1237 if isempty(a)
1238     OCS.SVDIndex = [];
1239 else
1240     val = str2num(a);
1241     if isempty(val) || val < 0 || val == 0
1242         uiwait(warndlg({'Invalid Singular Value','Setting the value to default'},'SINGULAR VALUE','Modal'));
1243         OCS.SVDIndex = [];
1244         set(handles.Edit_SVD,'String','');
1245     elseif val < 1
1246         OCS.SVDIndex = val;
1247     else
1248         val = ceil(val);
1249         set(handles.Edit_SVD,'String',num2str(val));
1250         OCS.SVDIndex = (1:val)';
1251     end
1252 end
1253
1254
1255 % Update plots
1256 if ~isfield(OCS,'BPM')
1257     return;
1258 end
1259 setappdata(handles.figure1,'OCS',OCS);
1260 UpdatePlots(handles);
1261
1262
1263 % --------------------------------------------------------------------
1264 function RadioButton_RF_Callback(hObject, eventdata, handles)
1265
1266 RingSetOrbit = getappdata(0, 'RingSetOrbit');
1267
1268 if isfield(RingSetOrbit,'RunFlag') && RingSetOrbit.RunFlag == 1
1269
1270     % Orbit correction is running.  Request an RF change.
1271     if get(handles.RadioButton_RF,'Value') == 1
1272         RingSetOrbit.FitRF = 1;
1273     else
1274         RingSetOrbit.FitRF = 0;
1275     end
1276     setappdata(0, 'RingSetOrbit', RingSetOrbit);
1277
1278 else
1279
1280     OCS = getappdata(handles.figure1, 'OCS');
1281
1282     % Save the starting RF frequency
1283     OCS.RF = getrf('Struct');
1284
1285     if ~isfield(OCS,'BPM')
1286         return;
1287     end
1288     if get(handles.RadioButton_RF,'Value') == 1
1289         OCS.FitRF = 1;
1290     else
1291         OCS.FitRF = 0;
1292     end
1293     setappdata(handles.figure1,'OCS',OCS);
1294
1295     % Update plots
1296     FigResize_Callback(hObject, eventdata, handles);
1297     UpdatePlots(handles);
1298 end
1299
1300
1301
1302 % --------------------------------------------------------------------
1303 function Print_Callback(hObject, eventdata, handles)
1304
1305 printdlg(handles.figure1)
1306
1307
1308
1309
1310 % --------------------------------------------------------------------
1311 function Plots0_Callback(hObject, eventdata, handles)
1312
1313 if strcmpi(get(handles.Plots0,'Checked'),'Off')
1314     % Set the menus and graphs
1315     set(handles.Plots0, 'Checked', 'On');
1316     set(handles.Plots3, 'Checked', 'Off');
1317     set(handles.Plots6, 'Checked', 'Off');
1318     set(handles.Graph_1, 'Enable', 'Off');
1319     set(handles.Graph_2, 'Enable', 'Off');
1320     set(handles.Graph_3, 'Enable', 'Off');
1321     set(handles.Graph_4, 'Enable', 'Off');
1322     set(handles.Graph_5, 'Enable', 'Off');
1323     set(handles.Graph_6, 'Enable', 'Off');
1324
1325     % Save the figure width
1326     set(handles.figure1, 'Units', 'Characters');
1327     Pcharacters = get(handles.figure1, 'Position');
1328     setappdata(handles.figure1, 'FigurePosition', Pcharacters);
1329
1330     % Get the goal orbit panal position
1331     set(handles.figure1, 'Units', 'Characters');
1332     Pcharacters = get(handles.figure1, 'Position');
1333
1334     % Change the figure size
1335     Units = get(handles.PanelGoalOrbit, 'Units');
1336     set(handles.PanelGoalOrbit, 'Units', 'Characters');
1337     pPanal = get(handles.PanelGoalOrbit, 'Position');
1338     set(handles.PanelGoalOrbit, 'Units', Units);
1339
1340     % This also forces a FigResize_Callback
1341     set(handles.figure1, 'Units', 'Characters');
1342     set(handles.figure1, 'Position', [Pcharacters(1) Pcharacters(2) 2*pPanal(1)+pPanal(3) Pcharacters(4)]);set(handles.PanelGoalOrbit, 'Units', Units);
1343
1344     % Figure resize off
1345     set(handles.figure1, 'Resize', 'Off');
1346
1347     RingSetOrbit = getappdata(0, 'RingSetOrbit');
1348     if isfield(RingSetOrbit,'RunFlag') && RingSetOrbit.RunFlag == 1
1349         % If orbit correction is running, change the display
1350         RingSetOrbit.Display = 0;
1351         setappdata(0, 'RingSetOrbit', RingSetOrbit);
1352     end
1353
1354     %OCS = getappdata(handles.figure1, 'OCS');
1355     %if isfield(OCS, 'BPM')
1356     %    UpdatePlots(handles);
1357     %end
1358 end
1359
1360
1361
1362
1363 % --------------------------------------------------------------------
1364 function Plots3_Callback(hObject, eventdata, handles)
1365
1366 if strcmpi(get(handles.Plots3,'Checked'),'Off')
1367     if strcmpi(get(handles.Plots0,'Checked'),'On')
1368         ChangeWidthFlag = 1;
1369     else
1370         ChangeWidthFlag = 0;
1371     end
1372
1373     set(handles.Plots0, 'Checked', 'Off');
1374     set(handles.Plots3, 'Checked', 'On');
1375     set(handles.Plots6, 'Checked', 'Off');
1376     set(handles.Graph_1, 'Enable', 'On');
1377     set(handles.Graph_2, 'Enable', 'On');
1378     set(handles.Graph_3, 'Enable', 'On');
1379     set(handles.Graph_4, 'Enable', 'Off');
1380     set(handles.Graph_5, 'Enable', 'Off');
1381     set(handles.Graph_6, 'Enable', 'Off');
1382
1383     if ChangeWidthFlag
1384         % This also forces a FigResize_Callback
1385         FigurePositionOld = getappdata(handles.figure1, 'FigurePosition');
1386         set(handles.figure1, 'Units', 'Characters');
1387         Pcharacters = get(handles.figure1, 'Position');
1388         set(handles.figure1, 'Position', [Pcharacters(1) Pcharacters(2) FigurePositionOld(3) Pcharacters(4)]);
1389     else
1390         FigResize_Callback(hObject, eventdata, handles);
1391     end
1392
1393     % Figure resize on
1394     set(handles.figure1, 'Resize', 'On');
1395
1396     RingSetOrbit = getappdata(0, 'RingSetOrbit');
1397     if isfield(RingSetOrbit,'RunFlag') && RingSetOrbit.RunFlag == 1
1398         % If orbit correction is running, ask setorbit to change the display
1399         RingSetOrbit.Display = 1;
1400         RingSetOrbit.FigureHandles = [handles.axes1; handles.axes2; handles.axes3;];
1401         setappdata(0, 'RingSetOrbit', RingSetOrbit);
1402     else
1403         % Update plots
1404         OCS = getappdata(handles.figure1, 'OCS');
1405         if isfield(OCS, 'BPM')
1406             UpdatePlots(handles);
1407         end
1408     end
1409 end
1410
1411
1412 % --------------------------------------------------------------------
1413 function Plots6_Callback(hObject, eventdata, handles)
1414
1415 if strcmpi(get(handles.Plots6,'Checked'),'Off')
1416     if strcmpi(get(handles.Plots0,'Checked'),'On')
1417         ChangeWidthFlag = 1;
1418     else
1419         ChangeWidthFlag = 0;
1420     end
1421
1422     set(handles.Plots0, 'Checked', 'Off');
1423     set(handles.Plots3, 'Checked', 'Off');
1424     set(handles.Plots6, 'Checked', 'On');
1425     set(handles.Graph_1, 'Enable', 'On');
1426     set(handles.Graph_2, 'Enable', 'On');
1427     set(handles.Graph_3, 'Enable', 'On');
1428     set(handles.Graph_4, 'Enable', 'On');
1429     set(handles.Graph_5, 'Enable', 'On');
1430     set(handles.Graph_6, 'Enable', 'On');
1431
1432     if ChangeWidthFlag
1433         % This also forces a FigResize_Callback
1434         FigurePositionOld = getappdata(handles.figure1, 'FigurePosition');
1435         set(handles.figure1, 'Units', 'Characters');
1436         Pcharacters = get(handles.figure1, 'Position');
1437         set(handles.figure1, 'Position', [Pcharacters(1) Pcharacters(2) FigurePositionOld(3) Pcharacters(4)]);
1438     else
1439         FigResize_Callback(hObject, eventdata, handles);
1440     end
1441
1442     % Figure resize on
1443     set(handles.figure1, 'Resize', 'On');
1444
1445     RingSetOrbit = getappdata(0, 'RingSetOrbit');
1446     if isfield(RingSetOrbit,'RunFlag') && RingSetOrbit.RunFlag == 1
1447         % If orbit correction is running, ask setorbit to change the display
1448         RingSetOrbit.Display = 1;
1449         RingSetOrbit.FigureHandles = [handles.axes1; handles.axes2; handles.axes3; handles.axes4; handles.axes5; handles.axes6;];
1450         setappdata(0, 'RingSetOrbit', RingSetOrbit);
1451     else
1452         % Update plots
1453         OCS = getappdata(handles.figure1, 'OCS');
1454         if isfield(OCS, 'BPM')
1455             UpdatePlots(handles);
1456         end
1457     end
1458 end
1459
1460
1461 % --------------------------------------------------------------------
1462 function FigResize_Callback(hObject, eventdata, handles)
1463
1464 if ~isempty(handles)
1465     % Minimum figure width
1466     if ~strcmpi(get(handles.Plots0, 'Checked'), 'On')
1467         FigureMinWidth = 130;
1468         set(handles.figure1, 'Units', 'Characters');
1469         Pcharacters = get(handles.figure1,'Position');
1470         if Pcharacters(3) < FigureMinWidth
1471             set(handles.figure1, 'Position', [Pcharacters(1) Pcharacters(2) FigureMinWidth Pcharacters(4)]);
1472         end
1473     end
1474
1475     set(handles.axes1, 'Units', 'Normalized');
1476     set(handles.axes2, 'Units', 'Normalized');
1477     set(handles.axes3, 'Units', 'Normalized');
1478     set(handles.axes4, 'Units', 'Normalized');
1479     set(handles.axes5, 'Units', 'Normalized');
1480     set(handles.axes6, 'Units', 'Normalized');
1481
1482     set(handles.figure1, 'Units', 'Normalized');
1483     P = get(handles.figure1,'Position');
1484
1485     Units = get(handles.PanelGoalOrbit, 'Units');
1486     set(handles.PanelGoalOrbit, 'Units', 'Normalized');
1487     pPanal = get(handles.PanelGoalOrbit, 'Position');
1488     set(handles.PanelGoalOrbit, 'Units', Units);
1489
1490     Width = 1 - (pPanal(1) + pPanal(3));
1491
1492     XBuffer1 = .075;
1493
1494
1495     if strcmpi(get(handles.Plots0,'Checked'),'On')
1496
1497         % No plots
1498         set(handles.Graph_1, 'Visible', 'Off');
1499         set(handles.Graph_2, 'Visible', 'Off');
1500         set(handles.Graph_2, 'Visible', 'Off');
1501         set(handles.Graph_4, 'Visible', 'Off');
1502         set(handles.Graph_5, 'Visible', 'Off');
1503         set(handles.Graph_6, 'Visible', 'Off');
1504
1505         set(handles.axes1,'Visible','Off');
1506         h = get(handles.axes1,'Children');
1507         for i = 1:length(h)
1508             set(h(i), 'Visible', 'Off');
1509         end
1510
1511         set(handles.axes2,'Visible','Off');
1512         h = get(handles.axes2,'Children');
1513         for i = 1:length(h)
1514             set(h(i), 'Visible', 'Off');
1515         end
1516
1517         set(handles.axes3,'Visible','Off');
1518         h = get(handles.axes3,'Children');
1519         for i = 1:length(h)
1520             set(h(i), 'Visible', 'Off');
1521         end
1522
1523         set(handles.axes4,'Visible','Off');
1524         h = get(handles.axes4,'Children');
1525         for i = 1:length(h)
1526             set(h(i), 'Visible', 'Off');
1527         end
1528
1529         set(handles.axes5,'Visible','Off');
1530         h = get(handles.axes5,'Children');
1531         for i = 1:length(h)
1532             set(h(i), 'Visible', 'Off');
1533         end
1534
1535         set(handles.axes6,'Visible','Off');
1536         h = get(handles.axes6,'Children');
1537         for i = 1:length(h)
1538             set(h(i), 'Visible', 'Off');
1539         end
1540
1541         % Legends
1542         h = findobj(handles.figure1,'tag','legend');
1543         for i = 1:length(h)
1544             set(h(i), 'Visible', 'Off');
1545         end
1546
1547     elseif strcmpi(get(handles.Plots6,'Checked'),'On')
1548
1549         % Find the RF plot if it exists
1550         if get(handles.RadioButton_RF,'Value') == 1
1551             XBuffer2 = .05;
1552         else
1553             XBuffer2 = .02;
1554         end
1555
1556         % Find the RF plot if it exists
1557         hyy = [];
1558         if get(handles.RadioButton_RF,'Value') == 1
1559             h = get(handles.figure1,'children');
1560
1561             for i = 1:length(h);
1562                 try
1563                     if findstr(get(get(h(i),'ylabel'),'string'),'RF');
1564                         hyy = h(i);
1565                         break;
1566                     end
1567                 catch
1568                 end
1569             end
1570         end
1571
1572         if (Width/2-XBuffer1-XBuffer2) < 0
1573             return;
1574         end
1575
1576         a = [pPanal(1)+pPanal(3)+XBuffer1                    .075 (Width/2-XBuffer1-XBuffer2/2) .25];
1577         set(handles.axes1, 'Position', a + [0 .6 0 0]);
1578         set(handles.axes2, 'Position', a + [0 .3 0 0]);
1579         set(handles.axes3, 'Position', a);
1580
1581         a = [pPanal(1)+pPanal(3)+XBuffer1+Width/2-XBuffer2/2 .075 (Width/2-XBuffer1-XBuffer2/2) .25];
1582         set(handles.axes4, 'Position', a + [0 .6 0 0]);
1583         set(handles.axes5, 'Position', a + [0 .3 0 0]);
1584         set(handles.axes6, 'Position', a);
1585
1586         if ~isempty(hyy)
1587             set(hyy, 'Position', a + [0 .6 0 0]);
1588         end
1589
1590         set(handles.Graph_1, 'Visible', 'On');
1591         set(handles.Graph_2, 'Visible', 'On');
1592         set(handles.Graph_2, 'Visible', 'On');
1593         set(handles.Graph_4, 'Visible', 'On');
1594         set(handles.Graph_5, 'Visible', 'On');
1595         set(handles.Graph_6, 'Visible', 'On');
1596
1597         set(handles.axes1,'Visible','On');
1598         h = get(handles.axes1,'Children');
1599         for i = 1:length(h)
1600             set(h(i), 'Visible', 'On');
1601         end
1602
1603         set(handles.axes2,'Visible','On');
1604         h = get(handles.axes2,'Children');
1605         for i = 1:length(h)
1606             set(h(i), 'Visible', 'On');
1607         end
1608
1609         set(handles.axes3,'Visible','On');
1610         h = get(handles.axes3,'Children');
1611         for i = 1:length(h)
1612             set(h(i), 'Visible', 'On');
1613         end
1614
1615         set(handles.axes4,'Visible','On');
1616         h = get(handles.axes4,'Children');
1617         for i = 1:length(h)
1618             set(h(i), 'Visible', 'On');
1619         end
1620
1621         set(handles.axes5,'Visible','On');
1622         h = get(handles.axes5,'Children');
1623         for i = 1:length(h)
1624             set(h(i), 'Visible', 'On');
1625         end
1626
1627         set(handles.axes6,'Visible','On');
1628         h = get(handles.axes6,'Children');
1629         for i = 1:length(h)
1630             set(h(i), 'Visible', 'On');
1631         end
1632
1633
1634         % Legends
1635         h = findobj(handles.figure1,'tag','legend');
1636         for i = 1:length(h)
1637             set(h(i), 'Visible', 'On');
1638         end
1639
1640     else
1641
1642         % 3 Plots
1643         XBuffer2 = .02;
1644
1645         set(handles.Graph_1, 'Visible', 'On');
1646         set(handles.Graph_2, 'Visible', 'On');
1647         set(handles.Graph_2, 'Visible', 'On');
1648         set(handles.Graph_4, 'Visible', 'Off');
1649         set(handles.Graph_5, 'Visible', 'Off');
1650         set(handles.Graph_6, 'Visible', 'Off');
1651
1652         set(handles.axes1,'Visible','On');
1653         h = get(handles.axes1,'Children');
1654         for i = 1:length(h)
1655             set(h(i), 'Visible', 'On');
1656         end
1657
1658         set(handles.axes2,'Visible','On');
1659         h = get(handles.axes2,'Children');
1660         for i = 1:length(h)
1661             set(h(i), 'Visible', 'On');
1662         end
1663
1664         set(handles.axes3,'Visible','On');
1665         h = get(handles.axes3,'Children');
1666         for i = 1:length(h)
1667             set(h(i), 'Visible', 'On');
1668         end
1669
1670         set(handles.axes4,'Visible','Off');
1671         h = get(handles.axes4,'Children');
1672         for i = 1:length(h)
1673             set(h(i), 'Visible', 'Off');
1674         end
1675
1676         set(handles.axes5,'Visible','Off');
1677         h = get(handles.axes5,'Children');
1678         for i = 1:length(h)
1679             set(h(i), 'Visible', 'Off');
1680         end
1681
1682         set(handles.axes6,'Visible','Off');
1683         h = get(handles.axes6,'Children');
1684         for i = 1:length(h)
1685             set(h(i), 'Visible', 'Off');
1686         end
1687
1688
1689         % Legends
1690         h = findobj(handles.figure1,'tag','legend');
1691         for i = 1:length(h)
1692             UserData = get(h(i),'UserData');
1693             if isstruct(UserData)
1694                 if any(strcmpi(UserData, {'Axes1','Axes2','Axes3'}))
1695                     set(h(i), 'Visible', 'On');
1696                 else
1697                     set(h(i), 'Visible', 'Off');
1698                 end
1699             end
1700         end
1701
1702
1703         if (Width-XBuffer1-XBuffer2) < 0
1704             return;
1705         end
1706         a = [pPanal(1)+pPanal(3)+XBuffer1 .075 (Width-XBuffer1-XBuffer2) .25];
1707         set(handles.axes1, 'Position', a + [0 .6 0 0]);
1708         set(handles.axes2, 'Position', a + [0 .3 0 0]);
1709         set(handles.axes3, 'Position', a);
1710     end
1711 end
1712
1713 drawnow;
1714
1715 %cla(handles.axes4, 'reset');
1716 %cla(handles.axes5, 'reset');
1717 %cla(handles.axes6, 'reset');
1718
1719
1720
1721 % --------------------------------------------------------------------
1722 function UpdatePlots(handles)
1723
1724 set(handles.figure1, 'HandleVisibility','On');
1725
1726 OCS = getappdata(handles.figure1,'OCS');
1727
1728 if strcmpi(get(handles.Plots6,'Checked'), 'On')
1729     OCS = setorbit(OCS, 'NoSetSP', 'NoGetPV', 'FigureHandles', [handles.axes1;handles.axes2;handles.axes3;handles.axes4;handles.axes5;handles.axes6;]);
1730 elseif strcmpi(get(handles.Plots3,'Checked'), 'On')
1731     OCS = setorbit(OCS, 'NoSetSP', 'NoGetPV', 'FigureHandles', [handles.axes1;handles.axes2;handles.axes3;]);
1732 elseif strcmpi(get(handles.Plots0,'Checked'), 'On')
1733     OCS = setorbit(OCS, 'NoSetSP', 'NoGetPV', 'NoDisplay', 'FigureHandles', [handles.axes1;handles.axes2;handles.axes3;]);
1734 end
1735
1736 setappdata(handles.figure1,'OCS',OCS);
1737
1738 set(handles.figure1, 'HandleVisibility','Off');
1739
1740
1741
1742 % --------------------------------------------------------------------
1743 function MinimumPeriod_Callback(hObject, eventdata, handles)
1744
1745 MinimumPeriodString = get(handles.MinimumPeriod, 'String');
1746 if isempty(MinimumPeriodString)
1747     MinimumPeriod = [];
1748 else
1749     MinimumPeriod = str2num(MinimumPeriodString);
1750     if MinimumPeriod < 0
1751         MinimumPeriod = 0;
1752     end
1753 end
1754 set(handles.MinimumPeriod, 'String', num2str(MinimumPeriod));
1755
1756
1757 RingSetOrbit = getappdata(0, 'RingSetOrbit');
1758 if isfield(RingSetOrbit,'RunFlag') && RingSetOrbit.RunFlag == 1
1759     % Orbit correction is running.  Request an MinimumPeriod change.
1760     RingSetOrbit.MinimumPeriod = MinimumPeriod;
1761     setappdata(0, 'RingSetOrbit', RingSetOrbit);
1762 else
1763     OCS = getappdata(handles.figure1, 'OCS');
1764     OCS.MinimumPeriod = MinimumPeriod;
1765     setappdata(handles.figure1, 'OCS', OCS);
1766 end
1767
1768
1769
1770 % --------------------------------------------------------------------
1771 function CorrectorGain_Callback(hObject, eventdata, handles)
1772
1773 CorrectorGain = str2num(get(handles.CorrectorGain,'String'));
1774 if isnumeric(CorrectorGain) && length(CorrectorGain)==1 && CorrectorGain >= 0 && CorrectorGain <= 100
1775     set(handles.CorrectorGain, 'Value', CorrectorGain);
1776 else
1777     set(handles.CorrectorGain, 'String', '100');
1778 end
1779
1780 RingSetOrbit = getappdata(0, 'RingSetOrbit');
1781 if isfield(RingSetOrbit,'RunFlag') && RingSetOrbit.RunFlag == 1
1782     % Orbit correction is running.  Request an CorrectorGain change.
1783     RingSetOrbit.CorrectorGain = CorrectorGain/100;
1784     setappdata(0, 'RingSetOrbit', RingSetOrbit);
1785 else
1786     OCS = getappdata(handles.figure1, 'OCS');
1787     OCS.CorrectorGain = CorrectorGain/100;
1788     setappdata(handles.figure1, 'OCS', OCS);
1789 end
1790
1791
1792
1793