Description of setpathmml
Home > mml > setpathmml.m
setpathmml
PURPOSE
SETPATHMML - Initialize the Matlab MiddleLayer (MML) path
SYNOPSIS
function [MachineName, SubMachineName, LinkFlag, MMLROOT] = setpathmml(varargin)
DESCRIPTION
SETPATHMML -  Initialize the Matlab MiddleLayer (MML) path
  [MachineName, SubMachineName, OnlineLinkMethod, MMLROOT]  = setpathmml(MachineName, SubMachineName, MachineType, OnlineLinkMethod, MMLROOT)
  INPUTS
  1. MachineName -
  2. SubMachineName -
  3. MachineType - 'StorageRing' {Default}, 'Booster', 'Linac', or 'Transport'
  4. OnlineLinkMethod - 'MCA', 'LabCA', 'SCA', 'Tango', 'SLC', 'UCODE', ... {Default: 'LabCA'}
  5. MMLROOT - Directory path to the MML root directory
CROSS-REFERENCE INFORMATION
This function calls:
getmachinelist GETMACHINELIST - Returns a cell array list of accelerators available to the Matlab MiddleLayer (MML)
getmmlroot GETMMLROOT - Returns root directory of the Matlab Middle Layer
setad SETAD - Sets the MML AcceleratorData cell array to appdata
setpathat SETPATHAT - Sets the AT Toolbox path
This function is called by:
setpathalba SETPATHALBA - Initializes the Matlab Middle Layer (MML) for ALBA
setpathals SETPATHALS - Initializes the Matlab Middle Layer (MML) for ALS
setpathasp SETPATHASP - Initializes the Matlab Middle Layer (MML) for ASP
setpathbfactory SETPATHBFACTORY - Initializes the Matlab Middle Layer (MML) for the B-Factory
setpathcamd SETPATHCAMD - Initializes the Matlab Middle Layer (MML) for CAMD
setpathcls SETPATHCLS - Initializes the Matlab Middle Layer (MML) for CLS
setpathdiamond SETPATHDIAMOND - Initializes the Matlab Middle Layer (MML) for DIAMOND
setpathdsr SETPATHDSR - Initializes the Matlab Middle Layer (MML) for DSR
setpathelsa SETPATHELSA - Initializes the Matlab Middle Layer (MML) for ELSA
setpathlcls SETPATHLCLS - Initializes the Matlab Middle Layer (MML) for LCLS
setpathnsls2 SETPATHNSLS2 - Initializes the Matlab Middle Layer (MML) for NSLS-II
setpathnsrrc SETPATHNSRRC - Initializes the Matlab Middle Layer (MML) for NSRRC
setpathpls SETPATHPLS - Initializes the Matlab Middle Layer (MML) for PLS
setpathsns SETPATHSNS - Initializes the Matlab Middle Layer (MML) for SNS
setpathsoleil SETPATHSOLEIL - Initializes the Matlab Middle Layer (MML) for Soleil
setpathspear3 SETPATHSPEAR3 - Initializes the Matlab Middle Layer (MML) for Spear3
setpathsps SETPATHSPS - Initializes the Matlab Middle Layer (MML) for SPS
setpathssrf SETPATHSSRF - Initializes the Matlab Middle Layer (MML) for SSRF
setpathvuv SETPATHVUV - Initializes the Matlab Middle Layer (MML) for the VUV ring at NSLS
setpathxray SETPATHXRAY - Initializes the Matlab Middle Layer (MML) for the X-Ray ring at NSLS
SUBFUNCTIONS
function RunTimeFlag = isdeployed_local
SOURCE CODE
function [MachineName, SubMachineName, LinkFlag, MMLROOT] = setpathmml(varargin)
%SETPATHMML -  Initialize the Matlab MiddleLayer (MML) path
%  [MachineName, SubMachineName, OnlineLinkMethod, MMLROOT]  = setpathmml(MachineName, SubMachineName, MachineType, OnlineLinkMethod, MMLROOT)
%
%  INPUTS
%  1. MachineName -
%  2. SubMachineName -
%  3. MachineType - 'StorageRing' {Default}, 'Booster', 'Linac', or 'Transport'
%  4. OnlineLinkMethod - 'MCA', 'LabCA', 'SCA', 'Tango', 'SLC', 'UCODE', ... {Default: 'LabCA'}
%  5. MMLROOT - Directory path to the MML root directory
%  Written by Greg Portmann
%  Updated by Igor Pinayev
% Inputs:  MachineName, SubMachineName, MachineType, LinkFlag, MMLROOT
% First strip-out the link method
LinkFlag = '';
for i = length(varargin):-1:1
    if ~ischar(varargin{i})
        % Ignor input
    elseif strcmpi(varargin{i},'LabCA')
        LinkFlag = 'LabCA';
        varargin(i) = [];
    elseif strcmpi(varargin{i},'MCA')
        LinkFlag = 'MCA';
        varargin(i) = [];
    elseif strcmpi(varargin{i},'SCA')
        LinkFlag = 'SCA';
        varargin(i) = [];
    elseif strcmpi(varargin{i},'OPC')
        LinkFlag = 'OPC';
        varargin(i) = [];
    elseif strcmpi(varargin{i},'SLC')
        LinkFlag = 'SLC';
        varargin(i) = [];
    elseif strcmpi(varargin{i},'Tango')
        LinkFlag = 'Tango';
        varargin(i) = [];
    elseif strcmpi(varargin{i},'UCODE')
        LinkFlag = 'UCODE';
        varargin(i) = [];
    end
end
% Get the machine name
if length(varargin) >= 1
    MachineName = varargin{1};
else
    MachineName = '';
end
if isempty(MachineName)
    [MachineListCell, SubMachineListCell] = getmachinelist;
    [i, iok] = listdlg('Name','SETPATHMML', 'ListString',MachineListCell, 'Name','MML Init', 'PromptString',{'Select a facility:'}, 'SelectionMode','Single');
    %[MachineNameCell, i] = editlist(MachineListCell,'',zeros(size(MachineListCell,1),1));
    drawnow;
    if iok
        MachineName = MachineListCell{i};
    else
        fprintf('   No path change.\n');
        MachineName=''; SubMachineName=''; LinkFlag=''; MMLROOT='';
        return;
    end
else
    SubMachineListCell = {};
end
% Get the submachine name
if length(varargin) >= 2
    SubMachineName = varargin{2};
else
    SubMachineName = '';
end
if isempty(SubMachineName)
    if isempty(SubMachineListCell)
        [MachineListCell, SubMachineListCell] = getmachinelist;
    end
    i = strmatch(MachineName, MachineListCell, 'exact');
    SubMachineListCell = SubMachineListCell{i}(:);
    if length(SubMachineListCell) == 1
        SubMachineName = SubMachineListCell{1};
    else
        [i, iok] = listdlg('Name','SETPATHMML', 'ListString',SubMachineListCell, 'Name','MML Init', 'PromptString',{'Select an accelerator:'}, 'SelectionMode','Single');
        drawnow;
        if iok
            SubMachineName = SubMachineListCell{i};
        else
            fprintf('   No path change.\n');
            MachineName=''; SubMachineName=''; LinkFlag=''; MMLROOT='';
            return;
        end
    end
end
% Find the machine type
if length(varargin) >= 3
    MachineType = varargin{3};
else
    MachineType = '';
end
if isempty(MachineType)
    switch upper(SubMachineName)
        case {'LTB', 'LB', 'BTS', 'BS', 'LT1', 'LT2', 'INJECTOR', 'LINAC', 'GUN'}
            MachineType = 'Transport';
        case {'BOOSTER', 'BOOSTER RING', 'BR'}
            MachineType = 'Booster';
        case {'SR', 'STORAGERING', 'STORAGE RING', 'HER', 'LER', '800MEV'}
            MachineType = 'StorageRing';
        otherwise
            MachineType = 'StorageRing';
    end
end
%if all(strcmpi(MachineType, {'StorageRing','Booster','Linac','Transport'}) == 0)
%    error('MachineType must be storagering, booster, linac, or transport.');
%end
MatlabVersion = ver('Matlab');
MatlabVersion = str2num(MatlabVersion.Version);
% LinkFlag if empty
if isempty(LinkFlag)
    switch upper(MachineName)
        case 'ALS'
            if strncmp(computer,'PC',2)
                LinkFlag = 'LABCA';
                %LinkFlag = 'MCA';
            elseif isunix
                if strncmp(computer,'GLNX',4) || MatlabVersion >= 7.4
                    LinkFlag = 'LABCA';
                    %LinkFlag = 'SCA';
                else
                    %LinkFlag = 'LABCA';
                    LinkFlag = 'SCA';
                end
            else
                LinkFlag = 'LABCA';
            end
        case {'ASP'}
            LinkFlag = 'LABCA';
        case {'NSRRC','PLS','SPEAR','SPEAR3','SSRF'}
            LinkFlag = 'MCA';
        case 'BFACTORY'
            LinkFlag = 'SLC';
        case 'LCLS'
            LinkFlag = 'LABCA';
        case {'NSRC','SPS'}
            LinkFlag = 'OPC';
        case {'VUV','XRAY'}
            LinkFlag = 'UCODE';
        case {'ALBA','SOLEIL'}
            LinkFlag = 'Tango';
        otherwise
            % Other
            if strncmp(computer,'PC',2)
                LinkFlag = 'LABCA';
                %LinkFlag = 'MCA';
            elseif isunix
                LinkFlag = 'LABCA';
            else
                LinkFlag = 'LABCA';
                %LinkFlag = 'MCA';
            end
    end
end
% Find the MML root directory
if length(varargin) >= 4
    MMLROOT = varargin{4};
else
    MMLROOT = '';
end
if isempty(MMLROOT)
    MMLROOT = getmmlroot;
end
% The path does not needs to be set in Standalone mode
if ~isdeployed_local
    % Jeff's orbit GUI
    if any(strcmpi(MachineName,{'Spear3','cls','diamond','asp','alba','camd'}))
        %addpath(fullfile(MMLROOT, 'applications', 'orbit'), '-begin');
        addpath(fullfile(MMLROOT, 'applications', 'orbit', 'lib'), '-begin');
        addpath(fullfile(MMLROOT, 'applications', 'orbit', lower(MachineName)), '-begin');
    end
    % N A F F (files not distributed with MML)
    Directory = fullfile(MMLROOT, 'applications', 'naff');
    if exist(Directory, 'dir')
        addpath(fullfile(MMLROOT, 'applications', 'naff'), '-begin');
    end
    % m2html generation program
    addpath(fullfile(MMLROOT, 'applications', 'm2html'), '-begin');
    % MySQL
    %addpath(fullfile(MMLROOT, 'applications', 'database', 'mysql'), '-begin');
    addpath(fullfile(MMLROOT, 'applications', 'database', 'mym'), '-begin');
    % XML
    addpath(fullfile(MMLROOT, 'applications', 'xml', 'geodise'), '-begin');
    %addpath(fullfile(MMLROOT, 'applications', 'xml', 'xmltree'), '-begin');
    % AT root
    setpathat(fullfile(MMLROOT,'at'));
    % Connection MML to simulator
    addpath(fullfile(MMLROOT, 'mml', 'at'),'-begin');
    % LOCO
    addpath(fullfile(MMLROOT, 'applications', 'loco'),'-begin');
    % Link method
    switch upper(LinkFlag)
        case 'MCA'
            % R3.14.4 and Andrei's MCA
            %fprintf('   Appending MATLAB path control using MCA and EPICS R3.13.4\n');
            %addpath(fullfile(MMLROOT, 'links', 'mca', 'win32', 'R3.14.4'),'-begin');
            %addpath(fullfile(MMLROOT, 'mml', 'links', 'mca'),'-begin');
            % R3.14.4 and Australian MCA
            fprintf('   Appending MATLAB path control using MCA (Australian)\n');
            addpath(fullfile(MMLROOT, 'links', 'mca_asp'),'-begin');
            addpath(fullfile(MMLROOT, 'mml', 'links', 'mca_asp'),'-begin');
        case 'LABCA'
            fprintf('   Appending MATLAB path control using LabCA \n');
            switch computer
                case 'PCWIN'
                    addpath(fullfile(MMLROOT,'links','labca', 'bin','win32-x86','labca'),'-begin');
                    %addpath(fullfile(MMLROOT,'links','labca', 'bin','win32-x86_3_0','labca'),'-begin');
                case 'SOL2'
                    addpath(fullfile(MMLROOT,'links','labca', 'bin','solaris-sparc','labca'),'-begin');
                case 'SOL64'
                    addpath(fullfile(MMLROOT,'links','labca', 'bin','solaris-sparc64','labca'),'-begin');
                case 'GLNX86'
                    addpath(fullfile(MMLROOT,'links','labca', 'bin','linux-x86','labca'),'-begin');
                case 'GLNXA64'
                    addpath(fullfile(MMLROOT,'links','labca', 'bin','linux-x86_64','labca'),'-begin');
                otherwise
                    fprintf('Computer not recognized for LabCA path.\n');
            end
            addpath(fullfile(MMLROOT,'mml', 'links', 'labca'),'-begin');
        case 'SCA'
            fprintf('   Appending MATLAB path control using Simple-CA Version 3\n');
            switch computer
                case 'PCWIN'
                    fprintf('\n   WARNING:  SCAIII is not working with PC''s yet\n\n');
                    addpath(fullfile(MMLROOT,'links','sca', 'bin','win32-x86','sca'),'-begin');
                case 'SOL2'
                    addpath(fullfile(MMLROOT,'links','sca', 'bin','solaris-sparc','sca'),'-begin');
                case 'SOL64'
                    addpath(fullfile(MMLROOT,'links','sca', 'bin','solaris-sparc64','sca'),'-begin');
                case 'GLNX86'
                    addpath(fullfile(MMLROOT,'links','sca', 'bin','linux-x86','sca'),'-begin');
                case 'GLNXA64'
                    addpath(fullfile(MMLROOT,'links','sca', 'bin','linux-x86_64','sca'),'-begin');
                otherwise
                    fprintf('Computer not recognized for SCA path.\n');
            end
            addpath(fullfile(MMLROOT, 'mml', 'links', 'sca'),'-begin');
        case 'TANGO'
            fprintf('   Appending MATLAB path control using Tango\n');
            addpath(fullfile(MMLROOT,'links','tango'),'-begin');
            addpath(fullfile(MMLROOT, 'mml', 'links', 'tango'),'-begin');
        case 'UCODE'
            fprintf('   Appending MATLAB path control using UCODE \n');
            %addpath(fullfile(MMLROOT,'links','ucode'),'-begin');
            addpath(fullfile(MMLROOT,'mml','links','ucode'),'-begin');
        case 'SLC'
            fprintf('   Appending MATLAB path for SLC control \n');
            addpath(fullfile(MMLROOT,'links','slc'),'-begin');
            addpath(fullfile(MMLROOT,'mml', 'links', 'slc'),'-begin');
        case 'OPC'
            fprintf('   Appending MATLAB path for OPC control \n');
            addpath(fullfile(MMLROOT,'links','opc'),'-begin');
            addpath(fullfile(MMLROOT,'mml', 'links', 'opc'),'-begin');
        otherwise
            fprintf('   Unknown type for the Online connection method.  Only simulator mode will work.\n');
    end
    % Common files
    addpath(fullfile(MMLROOT, 'applications', 'common'),'-begin');
    % MML path
    addpath(fullfile(MMLROOT, 'mml'),'-begin');
    % Machine directory
    if ~isempty(MachineName) && ~isempty(SubMachineName)
        % Sometimes there is a common directory that all submachines share
        Directory = fullfile(MMLROOT, 'machine', MachineName, 'common');
        if exist(Directory, 'dir')
            addpath(Directory,'-begin');
        end
        Directory = fullfile(MMLROOT, 'machine', MachineName, 'Common');
        if exist(Directory, 'dir')
            addpath(Directory,'-begin');
        end
        % New MML path
        addpath(fullfile(MMLROOT, 'machine', MachineName, SubMachineName),'-begin');
    end
end
% Start the AD with machine and submachine
setad([]);
AD.Machine = MachineName;
AD.SubMachine = SubMachineName;
AD.MachineType = MachineType;
AD.OperationalMode = '';    % Gets filled in later
setad(AD);
% Initialize the AO & AD
aoinit(SubMachineName);
function RunTimeFlag = isdeployed_local
% isdeployed is not in matlab 6.5
V = version;
if str2num(V(1,1)) < 7
    RunTimeFlag = 0;
else
    RunTimeFlag = isdeployed;
end