Description of setsp
Home > mml > setsp.m
setsp
PURPOSE
SETSP - Makes an absolute setpoint change to the 'Setpoint' field
SYNOPSIS
function ErrorFlag = setsp(Family, varargin)
DESCRIPTION
SETSP - Makes an absolute setpoint change to the 'Setpoint' field
  If using family name, device list method,
  ErrorFlag = setsp(Family, newSP, DeviceList, WaitFlag)
  ErrorFlag = setsp(DataStructure, WaitFlag)
  If using common name method,
  ErrorFlag = setsp(Family, newSP, CommonNames, WaitFlag)
  If using channel name method,
  ErrorFlag = setsp('ChannelName', newSP)
  INPUTS & OUTPUTS
  See setpv.  Setsp is an alias to setpv with the Field='Setpoint'.
  EXAMPLES
  setsp('HCM',1.23) sets the entire HCM family to 1.23
  setsp({'HCM','VCM'},{10.4,5.3}) sets the entire HCM family to 10.4 and VCM family to 5.3
  setsp(AccData, 1.5, [1 2]) if AccData is a properly formated Accelerator Data Structure
                             then the 1st sector, 2nd element is set to 1.5
  See also stepsp, getam, getsp, getpv, setpv, steppv
CROSS-REFERENCE INFORMATION
This function calls:
isfamily ISFAMILY - True for family names
setpv SETPV - Setpoint change of the online system or model
This function is called by:
finddispquad FINDDISPQUAD - Find the optimal setting for the dispersion correction quadrupole family
golden2sim GOLDEN2SIM - loads online machine configuration to AT configuration
hcm2golden HCM2GOLDEN - Set horizontal corrector strengths to golden values
hcm2zero HCM2ZERO - Set horizontal corrector strengths to zero
machine2sim MACHINE2SIM - loads online machine configuration to AT configuration
magstep MAGSTEP - Script for testing the time responce of a magnet
measbpmresplinearity MEASBPMRESPLINEARITY - Compute BPMlinearity
measchro MEASCHRO - measures the chromaticity function emperically
measchroresp MEASCHRORESP - measures the response from sextupoles to chromaticity
meascmhysteresis MEASCMHYSTERESIS - Measure corrector magnet hysteresis
measdispresp MEASDISPRESP - Measures Amman TERMs in response matrix
measidfftable MEASIDFFTABLE - Measures an insertion device feed forward table for the vertical gap
measrespmat MEASRESPMAT - Measure a response matrix
quadcenter QUADCENTER - Measure the magnet center of a quadrupole magnet
quadcenterfit QUADCENTERFIT OR BBASEARCH - Model search method to find a quarupole center
scanorbit SCANORBIT - Scans 2 correctors 90 degrees out of phase
stepchro STEPCHRO - Incremental change in the chromaticity (Delta Tune / Delta RF)
steptune STEPTUNE - Step the tune
vcm2golden VCM2GOLDEN - Set vertical corrector strengths to golden values
vcm2zero VCM2ZERO - Set vertical corrector strengths to zero
SOURCE CODE
function ErrorFlag = setsp(Family, varargin)
%SETSP - Makes an absolute setpoint change to the 'Setpoint' field
%  If using family name, device list method,
%  ErrorFlag = setsp(Family, newSP, DeviceList, WaitFlag)
%  ErrorFlag = setsp(DataStructure, WaitFlag)
%
%  If using common name method,
%  ErrorFlag = setsp(Family, newSP, CommonNames, WaitFlag)
%
%  If using channel name method,
%  ErrorFlag = setsp('ChannelName', newSP)
%
%
%  INPUTS & OUTPUTS
%  See setpv.  Setsp is an alias to setpv with the Field='Setpoint'.
%
%
%  EXAMPLES
%  setsp('HCM',1.23) sets the entire HCM family to 1.23
%  setsp({'HCM','VCM'},{10.4,5.3}) sets the entire HCM family to 10.4 and VCM family to 5.3
%  setsp(AccData, 1.5, [1 2]) if AccData is a properly formated Accelerator Data Structure
%                             then the 1st sector, 2nd element is set to 1.5
%
%  See also stepsp, getam, getsp, getpv, setpv, steppv
%  Written by Greg Portmann
%ErrorFlag = setpv(varargin{:});
if nargin == 0
    error('Must have at least one input (Family, Data Structure or Channel Name).');
end
if iscell(Family)
    ErrorFlag = setpv(Family, 'Setpoint', varargin{:});
else
    FamilyIndex = isfamily(Family);
    if FamilyIndex
        % Family name method
        % Cannot send the AO because the AO method needs the setpoint on the input line
        ErrorFlag = setpv(Family, 'Setpoint', varargin{:});
    else
        % ChannelName method
        ErrorFlag = setpv(Family, '', varargin{:});
    end
end