Description of switchmode
Home > mml > switchmode.m
switchmode
PURPOSE
SWITCHMODE - Change the mode field for all families in the MML
SYNOPSIS
function Mode = switchmode(varargin)
DESCRIPTION
SWITCHMODE - Change the mode field for all families in the MML
  Mode = switchmode(Command)
  INPUTS
  1. Command - 'Online' - Switches to online
               'Simulator' - Switches to simulator
               'Model' - Switches to model
               'Manual' - Switches manual mode
  OUTPUTS
  1. Mode - Mode selected
  See also switchunits, switch2online, switch2sim, switch2manual, switch2model
CROSS-REFERENCE INFORMATION
This function calls:
switch2manual SWITCH2MANUAL - Switch family to manual mode
switch2online SWITCH2ONLINE - Switch family to online mode
switch2sim SWITCH2SIM - Switch family to simulator mode if the family is in online mode.
This function is called by:
SOURCE CODE
function Mode = switchmode(varargin)
%SWITCHMODE - Change the mode field for all families in the MML
%  Mode = switchmode(Command)
%
%  INPUTS
%  1. Command - 'Online' - Switches to online
%               'Simulator' - Switches to simulator
%               'Model' - Switches to model
%               'Manual' - Switches manual mode
%
%  OUTPUTS
%  1. Mode - Mode selected
%
%  See also switchunits, switch2online, switch2sim, switch2manual, switch2model
%  Written by Greg Portmann
Mode = '';
if isempty(varargin)
    ButtonName = questdlg('Matlab MiddleLayer Mode?','Middle Layer','Online', 'Simulator', 'Online');
    switch ButtonName
        case 'Online'
            switch2online;
            Mode = 'Online';
        case 'Simulator'
            switch2sim;
            Mode = 'Simulator';
    end
else
    if strcmpi(varargin{1},'online')
        switch2online;
        Mode = 'Online';
    elseif strcmpi(varargin{1},'simulator') || strcmpi(varargin{1},'model')
        switch2sim;
        Mode = 'Simulator';
    elseif strcmpi(varargin{1},'manual')
        switch2manual;
        Mode = 'Manual';
    else
        error('Mode type unknown.');
    end
end