Description of switch2hw
Home > mml > switch2hw.m
switch2hw
PURPOSE
SWITCH2HW - Switch a family to hardware units
SYNOPSIS
function ErrorFlag = switch2hw(varargin)
DESCRIPTION
SWITCH2HW - Switch a family to hardware units
  Alias for switch2hardware
CROSS-REFERENCE INFORMATION
This function calls:
switch2hardware SWITCH2HARDWARE - Switch family to hardware units
This function is called by:
plotfamily PLOTFAMILY - Plots by middle layer family name
switchunits SWITCHUNITS - Change the units field for all families in the MML
SOURCE CODE
function ErrorFlag = switch2hw(varargin)
%SWITCH2HW - Switch a family to hardware units
%
%  Alias for switch2hardware
ErrorFlag = switch2hardware(varargin{:});