fp = fopen('COD_AF_wo_correction.txt','w');
fprintf(fp,'%-10s | %-14s| %36s| %36s\n','Family','Position [m]', 'Horizontal     ','Vertical     ');
fprintf(fp,'%-10s | %-14s| %8s %8s %8s %8s | %8s %8s %8s %8s \n',...
             ' ',     ' ', 'all','mia','mib','mc',   'all','mia','mib','mc');
pr = res.mags.before;
for i=1:length(res.mags.pos)
    fprintf(fp,'%-10s   %14.4f  %8.2g %8.2g %8.2g %8.2g   %8.2g %8.2g %8.2g %8.2g \n', ...
        the_ring{res.mags.indcs(i)}.FamName, res.mags.pos(i), ...
        pr.misx.orb(1,i),pr.misx.orb(3,i),pr.misx.orb(5,i),pr.misx.orb(7,i),...
        pr.misy.orb(2,i),pr.misy.orb(4,i),pr.misy.orb(6,i),pr.misy.orb(8,i));
end
fclose(fp);

fp = fopen('COD_AF_fast_correction.txt','w');
fprintf(fp,'%-10s | %-14s| %76s| %76s\n',' ',' ','BPMs on girder', 'BPMs off girders');
fprintf(fp,'%-10s | %-14s| %27s| %27s| %18s| %27s| %27s| %18s\n',...
          'Family','Position [m]', 'Horizontal','Vertical', 'COR [rad/m]',...
                                   'Horizontal','Vertical', 'COR [rad/m]');
fprintf(fp,'%-10s | %-14s| %8s %8s %8s | %8s %8s %8s | %8s %8s | %8s %8s %8s | %8s %8s %8s | %8s %8s\n',...
             ' ',     ' ','mia','mib','mc','mia','mib','mc', 'CH','CV',...
                          'mia','mib','mc','mia','mib','mc', 'CH','CV');
pr = res.mags;
for i=1:length(pr.pos)
    fprintf(fp,'%10s   %14.4f  %8.2g %8.2g %8.2g   %8.2g %8.2g %8.2g   %8.2g %8.2g   %8.2g %8.2g %8.2g   %8.2g %8.2g %8.2g   %8.2g %8.2g\n', ...
        the_ring{pr.indcs(i)}.FamName, pr.pos(i), ...
        pr.fast.misx.orb(1,i),pr.fast.misx.orb(3,i),pr.fast.misx.orb(5,i),...
        pr.fast.misy.orb(2,i),pr.fast.misy.orb(4,i),pr.fast.misy.orb(6,i),...
        pr.fast.misx.cor(1,i),pr.fast.misy.cor(2,i),...
        pr.fast.misx.orb(1,i),pr.fast.misx.orb(3,i),pr.fast.misx.orb(5,i),...
        pr.fast.misy.orb(2,i),pr.fast.misy.orb(4,i),pr.fast.misy.orb(6,i),...
        pr.fast.misx.cor(1,i),pr.fast.misy.cor(2,i));
end
pr = res.bpm.fast;
for i=1:length(pr.pos)
    fprintf(fp,'%10s   %14.4f  %8.2g %8.2g %8.2g   %8.2g %8.2g %8.2g   %8.2g %8.2g  %8.2g %8.2g %8.2g   %8.2g %8.2g %8.2g   %8.2g %8.2g\n', ...
        the_ring{pr.indcs(i)}.FamName, pr.pos(i), ...
        pr.misx.orb(1,i),pr.misx.orb(3,i),pr.misx.orb(5,i),...
        pr.misy.orb(2,i),pr.misy.orb(4,i),pr.misy.orb(6,i),...
        pr.misx.cor(1,i),pr.misy.cor(2,i), ...
        pr.misx.orb(1,i),pr.misx.orb(3,i),pr.misx.orb(5,i),...
        pr.misy.orb(2,i),pr.misy.orb(4,i),pr.misy.orb(6,i),...
        pr.misx.cor(1,i),pr.misy.cor(2,i));
end
fclose(fp);

fp = fopen('AF_slow_correction.txt','w');
fprintf(fp,'%-10s | %-14s| %65s| %65s\n',' ',' ','BPMs on girder', 'BPMs off girders');
fprintf(fp,'%-10s | %-14s| %36s| %27s| %36s| %27s\n',...
          'Family','Position [m]', 'Horizontal','Vertical','Horizontal','Vertical');
fprintf(fp,'%-10s | %-14s| %8s %8s %8s %8s | %8s %8s %8s | %8s %8s %8s %8s | %8s %8s %8s\n',...
             ' ',     ' ','codx','corx','betax','betay','cody','cory','coup',...
                          'codx','corx','betax','betay','cody','cory','coup');
pr = res.mags;
for i=1:length(pr.pos)
    fprintf(fp,'%10s   %14.4f  %8.2g %8.2g %8.2g %8.2g   %8.2g %8.2g %8.2g   %8.2g %8.2g %8.2g %8.2g   %8.2g %8.2g %8.2g\n', ...
        the_ring{pr.indcs(i)}.FamName, pr.pos(i), ...
        pr.slow.misx.orb(1,i),pr.slow.misx.cor(1,i),pr.slow.misx.opt(1,i),pr.slow.misx.opt(2,i),...
        pr.slow.misy.orb(2,i),pr.slow.misy.cor(2,i),pr.slow.misy.opt(3,i),...
        pr.slow.misx.orb(1,i),pr.slow.misx.cor(1,i),pr.slow.misx.opt(1,i),pr.slow.misx.opt(2,i),...
        pr.slow.misy.orb(2,i),pr.slow.misy.cor(2,i),pr.slow.misy.opt(3,i));
end
pr = res.bpm.slow;
for i=1:length(pr.pos)
    fprintf(fp,'%10s   %14.4f  %8.2g %8.2g %8.2g %8.2g   %8.2g %8.2g %8.2g   %8.2g %8.2g %8.2g %8.2g   %8.2g %8.2g %8.2g\n', ...
        the_ring{pr.indcs(i)}.FamName, pr.pos(i), ...
        pr.misx.orb(1,i),pr.misx.cor(1,i),pr.misx.opt(1,i),pr.misx.opt(2,i),...
        pr.misy.orb(2,i),pr.misy.cor(2,i),pr.misy.opt(3,i),...
        pr.misx.orb(1,i),pr.misx.cor(1,i),pr.misx.opt(1,i),pr.misx.opt(2,i),...
        pr.misy.orb(2,i),pr.misy.cor(2,i),pr.misy.opt(3,i));
end
fclose(fp);

cd('../');