function RING = DEF_RING(TYPES)


C0 = 2.99792458e8;   % speed of light [m/s]

RING.HARMNUMBER  = 54;
RING.RFFREQUENCY = 476065680;
RING.LENGTH      = C0 / (RING.RFFREQUENCY/RING.HARMNUMBER);
RING.ENERGY      = 500e6;
RING.NRSECTORS   = 2;
RING.NRDIPSECTOR = 6;


DIP = eval(TYPES.S12DI.LENGTH);
SSS = 1.55747;
LSS = (RING.LENGTH - RING.NRSECTORS * RING.NRDIPSECTOR * DIP -  10 * SSS)/2;

RING.CELLS.TR01  = struct('FILE', 'TR01.txt',  'LENGTH', LSS);
RING.CELLS.SDI01 = struct('FILE', 'SDI01.txt', 'LENGTH', DIP);
RING.CELLS.TR02  = struct('FILE', 'TR02.txt',  'LENGTH', SSS);
RING.CELLS.SDI02 = struct('FILE', 'SDI02.txt', 'LENGTH', DIP);
RING.CELLS.TR03  = struct('FILE', 'TR03.txt',  'LENGTH', SSS);
RING.CELLS.SDI03 = struct('FILE', 'SDI03.txt', 'LENGTH', DIP);
RING.CELLS.TR04  = struct('FILE', 'TR04.txt',  'LENGTH', SSS);
RING.CELLS.SDI04 = struct('FILE', 'SDI04.txt', 'LENGTH', DIP);
RING.CELLS.TR05  = struct('FILE', 'TR05.txt',  'LENGTH', SSS);
RING.CELLS.SDI05 = struct('FILE', 'SDI05.txt', 'LENGTH', DIP);
RING.CELLS.TR06  = struct('FILE', 'TR06.txt',  'LENGTH', SSS);
RING.CELLS.SDI06 = struct('FILE', 'SDI06.txt', 'LENGTH', DIP);
RING.CELLS.TR07  = struct('FILE', 'TR07.txt',  'LENGTH', LSS);
RING.CELLS.SDI07 = struct('FILE', 'SDI07.txt', 'LENGTH', DIP);
RING.CELLS.TR08  = struct('FILE', 'TR08.txt',  'LENGTH', SSS);
RING.CELLS.SDI08 = struct('FILE', 'SDI08.txt', 'LENGTH', DIP);
RING.CELLS.TR09  = struct('FILE', 'TR09.txt',  'LENGTH', SSS);
RING.CELLS.SDI09 = struct('FILE', 'SDI09.txt', 'LENGTH', DIP);
RING.CELLS.TR10  = struct('FILE', 'TR10.txt',  'LENGTH', SSS);
RING.CELLS.SDI10 = struct('FILE', 'SDI10.txt', 'LENGTH', DIP);
RING.CELLS.TR11  = struct('FILE', 'TR11.txt',  'LENGTH', SSS);
RING.CELLS.SDI11 = struct('FILE', 'SDI11.txt', 'LENGTH', DIP);
RING.CELLS.TR12  = struct('FILE', 'TR12.txt',  'LENGTH', SSS);
RING.CELLS.SDI12 = struct('FILE', 'SDI12.txt', 'LENGTH', DIP);
