function TYPES = DEF_TYPES

 



QUAD.LENGTH     = '0.2';
QUAD.PASSMETHOD = 'QuadLinearPass';
QUAD.TEMPLATE_ELEMENT = { ...
    'e1 = quadrupole(''FAMNAME'', LENGTH, STRENGTH, ''PASSMETHOD'');'; ...
    'TYPENAME_element = [e1];'; ...
    };


TYPES.MBEGIN.TYPENAME   = 'BEGIN';
TYPES.MBEGIN.FAMNAME    = 'BEGIN';
TYPES.MBEGIN.LENGTH     = '0';
TYPES.MBEGIN.PASSMETHOD = 'IdentityPass';
TYPES.MBEGIN.TEMPLATE_ELEMENT = { ...
    'e1 = marker(''FAMNAME'', ''PASSMETHOD'');'; ...
    'TYPENAME_element = [e1];'; ...
    };
	
TYPES.MARKER.TYPENAME   = 'MARKER';
TYPES.MARKER.FAMNAME    = 'MARKER';
TYPES.MARKER.LENGTH     = '0';
TYPES.MARKER.PASSMETHOD = 'IdentityPass';
TYPES.MARKER.TEMPLATE_ELEMENT = { ...
    'e1 = marker(''FAMNAME'', ''PASSMETHOD'');'; ...
    'TYPENAME_element = [e1];'; ...
    };

%% QUADRUPOLE FAMILIES %%

TYPES.S2QF01 = QUAD;
TYPES.S2QF01.TYPENAME = 'S2QF01';
TYPES.S2QF01.FAMNAME  = 'S2QF01';
TYPES.S2QF01.STRENGTH = '2.943934403269779';

TYPES.S2QF07 = QUAD;
TYPES.S2QF07.TYPENAME = 'S2QF07';
TYPES.S2QF07.FAMNAME  = 'S2QF07';
TYPES.S2QF07.STRENGTH = '2.943934403269779';

TYPES.S2QD01 = QUAD;
TYPES.S2QD01.TYPENAME = 'S2QD01';
TYPES.S2QD01.FAMNAME  = 'S2QD01';
TYPES.S2QD01.STRENGTH = '-2.050960154943163';

TYPES.S2QD07 = QUAD;
TYPES.S2QD07.TYPENAME = 'S2QD07';
TYPES.S2QD07.FAMNAME  = 'S2QD07';
TYPES.S2QD07.STRENGTH = '-2.050960154943163';


TYPES.S2QF02 = QUAD;
TYPES.S2QF02.TYPENAME = 'S2QF02';
TYPES.S2QF02.FAMNAME  = 'S2QF02';
TYPES.S2QF02.STRENGTH = '3.23603188474';

TYPES.S2QF03 = QUAD;
TYPES.S2QF03.TYPENAME = 'S2QF03';
TYPES.S2QF03.FAMNAME  = 'S2QF03';
TYPES.S2QF03.STRENGTH = '3.166907854112';

TYPES.S2QF04 = QUAD;
TYPES.S2QF04.TYPENAME = 'S2QF04';
TYPES.S2QF04.FAMNAME  = 'S2QF04';
TYPES.S2QF04.STRENGTH = '2.407269293516';

TYPES.S2QF08 = QUAD;
TYPES.S2QF08.TYPENAME = 'S2QF08';
TYPES.S2QF08.FAMNAME  = 'S2QF08';
TYPES.S2QF08.STRENGTH = '3.23603188474';

TYPES.S2QF09 = QUAD;
TYPES.S2QF09.TYPENAME = 'S2QF09';
TYPES.S2QF09.FAMNAME  = 'S2QF09';
TYPES.S2QF09.STRENGTH = '3.166907854112';


TYPES.S2QS07 = QUAD;
TYPES.S2QS07.TYPENAME = 'S2QS07';
TYPES.S2QS07.FAMNAME  = 'SKEWQUAD';
TYPES.S2QS07.STRENGTH = '0';


%% DIPOLES

TYPES.S12DI.TYPENAME   = 'S12DI';
TYPES.S12DI.FAMNAME    = 'BEND';
TYPES.S12DI.LENGTH     = '0.54253';
TYPES.S12DI.KSTRENGTH  = '-0.098122104639';
TYPES.S12DI.PASSMETHOD = 'BndMPoleSymplectic4Pass';
TYPES.S12DI.FULLGAP    = '0.032';
TYPES.S12DI.FINT1      = '0.6512';
TYPES.S12DI.FINT2      = '0.6512';
TYPES.S12DI.TEMPLATE_ELEMENT = { ...
    'e1 = rbend2(''FAMNAME'', LENGTH,  (2*pi/12), (2*pi/12)/2, (2*pi/12)/2, KSTRENGTH, FULLGAP, FINT1, FINT2, ''PASSMETHOD'');'; ...
    'TYPENAME_element = [e1];'; ...
    };


%% SEXTUPOLES %%

TYPES.S4SF.TYPENAME   = 'S4SF';
TYPES.S4SF.FAMNAME    = 'S4SF';
TYPES.S4SF.LENGTH     = '0.1';
TYPES.S4SF.STRENGTH   = '0';
TYPES.S4SF.PASSMETHOD = 'StrMPoleSymplectic4Pass';
TYPES.S4SF.TEMPLATE_ELEMENT = { ...
    'e1 = sextupole(''FAMNAME'', LENGTH, STRENGTH, ''PASSMETHOD'');'; ...
    'TYPENAME_element = [e1];'; ...
    };


TYPES.S4SD.TYPENAME   = 'S4SD';
TYPES.S4SD.FAMNAME    = 'S4SD';
TYPES.S4SD.LENGTH     = '0.1';
TYPES.S4SD.STRENGTH   = '0';
TYPES.S4SD.PASSMETHOD = 'StrMPoleSymplectic4Pass';
TYPES.S4SD.TEMPLATE_ELEMENT = { ...
    'e1 = sextupole(''FAMNAME'', LENGTH, STRENGTH, ''PASSMETHOD'');'; ...
    'TYPENAME_element = [e1];'; ...
    };


%% MARKERS

TYPES.MBEGIN.TYPENAME   = 'MBEGIN';
TYPES.MBEGIN.FAMNAME    = 'BEGIN';
TYPES.MBEGIN.LENGTH     = '0';
TYPES.MBEGIN.PASSMETHOD = 'IdentityPass';
TYPES.MBEGIN.TEMPLATE_ELEMENT = { ...
    'e1 = marker(''FAMNAME'', ''PASSMETHOD'');'; ...
    'TYPENAME_element = [e1];'; ...
    };

TYPES.ATR.TYPENAME   = 'ATR';
TYPES.ATR.FAMNAME    = 'ATR';
TYPES.ATR.LENGTH     = '0';
TYPES.ATR.PASSMETHOD = 'DriftPass';
TYPES.ATR.TEMPLATE_ELEMENT = {'drift(''FAMNAME'', LENGTH, ''PASSMETHOD'');';};

%% RF

TYPES.RF.TYPENAME   = 'RF';
TYPES.RF.FAMNAME    = 'RF';
TYPES.RF.LENGTH     = '0';
TYPES.RF.VOLTAGE    = '0.3e+6';
TYPES.RF.FREQUENCY  = '476065680';
TYPES.RF.HARMNUMBER = '54';
TYPES.RF.PASSMETHOD = 'CavityPass';
TYPES.RF.TEMPLATE_ELEMENT = { ...
    'e1 = rfcavity(''FAMNAME'', LENGTH, VOLTAGE, FREQUENCY, HARMNUMBER, ''PASSMETHOD'');'; ...
    'TYPENAME_element = [e1];'; ...
    };



%% BPMS

TYPES.BPM.TYPENAME   = 'BPM';
TYPES.BPM.FAMNAME    = 'BPM';
TYPES.BPM.LENGTH     = '0';
TYPES.BPM.PASSMETHOD = 'IdentityPass';
TYPES.BPM.TEMPLATE_ELEMENT = { ...
    'e1 = marker(''FAMNAME'', ''PASSMETHOD'');'; ...
    'TYPENAME_element = [e1];'; ...
    };


%% CORRECTORS

TYPES.SCH.TYPENAME   = 'SCH';
TYPES.SCH.FAMNAME    = 'HCM';
TYPES.SCH.LENGTH     = '0*0.081';
TYPES.SCH.PASSMETHOD = 'CorrectorPass';
TYPES.SCH.TEMPLATE_ELEMENT = { ...
    'e1 = corrector(''FAMNAME'', LENGTH, [0 0], ''PASSMETHOD'');'; ...
    'TYPENAME_element = [e1];'; ...
    };

TYPES.SCV.TYPENAME   = 'SCV';
TYPES.SCV.FAMNAME    = 'VCM';
TYPES.SCV.LENGTH     = '0*0.081';
TYPES.SCV.PASSMETHOD = 'CorrectorPass';
TYPES.SCV.TEMPLATE_ELEMENT = { ...
    'e1 = corrector(''FAMNAME'', LENGTH, [0 0], ''PASSMETHOD'');'; ...
    'TYPENAME_element = [e1];'; ...
    };

%% EJECTION KICKERS

TYPES.KICKER.TYPENAME   = 'KICKER';
TYPES.KICKER.FAMNAME    = 'KICKER';
TYPES.KICKER.LENGTH     = '0';
TYPES.KICKER.PASSMETHOD = 'CorrectorPass';
TYPES.KICKER.TEMPLATE_ELEMENT = { ...
    'e1 = corrector(''FAMNAME'', LENGTH, [0 0], ''PASSMETHOD'');'; ...
    'TYPENAME_element = [e1];'; ...
    };

