Description of rampgentableload
Home > ALS > Booster > rampgentableload.m
rampgentableload
PURPOSE
rampgentableload(Waveform, IOCName, Channel, Comment, egul, eguf)
SYNOPSIS
This is a script file.
DESCRIPTION
 rampgentableload(Waveform, IOCName, Channel, Comment, egul, eguf)
 compile: >> mex rampgentableload.c
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
setboosterramprf SETBOOSTERRAMPRF - Set the booster RF ramp table
setboosterrampsd SETBOOSTERRAMPSD - Set the booster SD ramp table
setboosterrampsf SETBOOSTERRAMPSF - Set the booster SF ramp table
SOURCE CODE
% rampgentableload(Waveform, IOCName, Channel, Comment, egul, eguf)
%
% compile: >> mex rampgentableload.c