function the_ring = sirius_bo_sort_quadrupoles_qf(the_ring0)

% sorting taken from
% '<root>/bo-quadrupoles-qf/model-06/analysis/rotcoil/production/magnet_sorting/result.txt'
% 
sorting = [
    'BQF-23'; ...
    'BQF-07'; ...
    'BQF-44'; ...
    'BQF-34'; ...
    'BQF-43'; ...
    'BQF-32'; ...
    'BQF-29'; ...
    'BQF-48'; ...
    'BQF-56'; ...
    'BQF-42'; ...
    'BQF-37'; ...
    'BQF-33'; ...
    'BQF-57'; ...
    'BQF-54'; ...
    'BQF-45'; ...
    'BQF-31'; ...
    'BQF-55'; ...
    'BQF-50'; ...
    'BQF-35'; ...
    'BQF-41'; ...
    'BQF-36'; ...
    'BQF-40'; ...
    'BQF-38'; ...
    'BQF-52'; ...
    'BQF-09'; ...
    'BQF-39'; ...
    'BQF-58'; ...
    'BQF-53'; ...
    'BQF-25'; ...
    'BQF-19'; ...
    'BQF-28'; ...
    'BQF-51'; ...
    'BQF-46'; ...
    'BQF-47'; ...
    'BQF-21'; ...
    'BQF-20'; ...
    'BQF-26'; ...
    'BQF-22'; ...
    'BQF-27'; ...
    'BQF-12'; ...
    'BQF-15'; ...
    'BQF-24'; ...
    'BQF-16'; ...
    'BQF-49'; ...
    'BQF-18'; ...
    'BQF-14'; ...
    'BQF-30'; ...
    'BQF-17'; ...
    'BQF-11'; ...
    'BQF-13'; ...
];


famdata = sirius_bo_family_data(the_ring0);
r = sorting;
