Description of arglobal
Home > ALS > StorageRing > arglobal.m
arglobal
PURPOSE
Just used to make archived variables global
SYNOPSIS
This is a script file.
DESCRIPTION
 Just used to make archived variables global
 global ARt ARData ARChanNames ARDate ARNumBinary ARNumAnalog
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
arfill_length arplot_sr(Month1 String, Days1, Year1, Month2 String, Days2, Year2)
arplot_boosterRF arplot_boosterRF(Month1 String, Days1, Year1, Month2 String, Days2, Year2)
arplot_channel arplot_channel(channel,Month1 String, Days1, Year1, Month2 String, Days2, Year2)
arplot_diagbl arplot_diagbl(Month1 String, Days1, Year1, Month2 String, Days2, Year2)
arplot_ff function arplot_ff(Sector, StartTime [Hours], EndTime [Hours]);
arplot_flexbandtc arplot_flexbandtc(Month1 String, Days1, Year1, Month2 String, Days2, Year2)
arplot_girdertc mean = arplot_girdertc(Month1 String, Days1, Year1, Month2 String, Days2, Year2)
arplot_id arplot_id(Month1 String, Days1, Year1, Month2 String, Days2, Year2)
arplot_idbpm arplot_idbpm(Month1 String, Days1, Year1, Month2 String, Days2, Year2)
arplot_ig arplot_ig(Month1 String, Days1, Year1, Month2 String, Days2, Year2)
arplot_orbitfb arplot_orbitfb(Month1 String, Days1, Year1, Month2 String, Days2, Year2)
arplot_orbitfb2 arplot_orbitfb2(Month1 String, Days1, Year1, Month2 String, Days2, Year2)
arplot_pbpm arplot_pbpm(Month1 String, Days1, Year1, Month2 String, Days2, Year2)
arplot_sbm arplot_sbm(Month1 String, Days1, Year1, Month2 String, Days2, Year2)
arplot_sr ARPLOT_SR - Plots various performance data from the ALS archiver
arplot_sr_mmaligned arplot_sr_mmaligned(Month1 String, Days1, Year1, Month2 String, Days2, Year2)
arplot_sr_with_shutters arplot_sr(Month1 String, Days1, Year1, Month2 String, Days2, Year2)
arplot_vacuum arplot_ig(Month1 String, Days1, Year1, Month2 String, Days2, Year2)
SOURCE CODE
% Just used to make archived variables global
%
% global ARt ARData ARChanNames ARDate ARNumBinary ARNumAnalog
%
global ARt ARData ARChanNames ARDate ARNumBinary ARNumAnalog ARChanNamesCell