Description of family2archive
Home > ALS > StorageRing > family2archive.m
family2archive
PURPOSE
FAMILY2ARCHIVE - Converts the family name to a database column name in the archiver
SYNOPSIS
function [ColumnName, ErrorFlag] = family2archive(varargin)
DESCRIPTION
FAMILY2ARCHIVE - Converts the family name to a database column name in the archiver
  ColumnName = family2archive(Family, Field, DeviceList)
  ColumnName = family2archive(Family, DeviceList)
  INPUTS
  1. Family - Family Name
              Data Structure
              Accelerator Object
              or Cell Array of Families
  2. Field = Accelerator Object field name ('Monitor', 'Setpoint', etc) {Default: 'Monitor'}
  3. DeviceList ([Sector Device #] or [element #]) {Default: whole family}
  OUTPUTS
  1. ColumnName - database column name corresponding to the Family, Field, and DeviceList
  Written by Greg Portmann
CROSS-REFERENCE INFORMATION
This function calls:
family2archive FAMILY2ARCHIVE - Converts the family name to a database column name in the archiver
This function is called by:
family2archive FAMILY2ARCHIVE - Converts the family name to a database column name in the archiver
plotmysqlorbit function arplotorbit
plotsofb function plotsofb
SOURCE CODE
function [ColumnName, ErrorFlag] = family2archive(varargin)
%FAMILY2ARCHIVE - Converts the family name to a database column name in the archiver
%  ColumnName = family2archive(Family, Field, DeviceList)
%  ColumnName = family2archive(Family, DeviceList)
%
%  INPUTS
%  1. Family - Family Name
%              Data Structure
%              Accelerator Object
%              or Cell Array of Families
%  2. Field = Accelerator Object field name ('Monitor', 'Setpoint', etc) {Default: 'Monitor'}
%  3. DeviceList ([Sector Device #] or [element #]) {Default: whole family}
%
%  OUTPUTS
%  1. ColumnName - database column name corresponding to the Family, Field, and DeviceList
%
%  Written by Greg Portmann
if nargin == 0
    error('Must have at least one input (''Family'')!');
end
ErrorFlag = 0;
%%%%%%%%%%%%%%%%%%%%%
% Cell Array Inputs %
%%%%%%%%%%%%%%%%%%%%%
if iscell(varargin{1})
    if length(varargin) >= 3 && iscell(varargin{3})
        if length(varargin{1}) ~= length(varargin{3})
            error('Family and DeviceList must be the same size cell arrays.');
        end
    end
    if length(varargin) >= 2 && iscell(varargin{2})
        if length(varargin{1}) ~= length(varargin{2})
            error('If Field is a cell array, then must be the same size as Family.');
        end
    end
    for i = 1:length(varargin{1})
        if length(varargin) == 1
            [ColumnName{i}, ErrorTmp] = family2archive(varargin{1}{i});
        elseif length(varargin) == 2
            if iscell(varargin{2})
                [ColumnName{i}, ErrorTmp] = family2archive(varargin{1}{i}, varargin{2}{i});
            else
                [ColumnName{i}, ErrorTmp] = family2archive(varargin{1}{i}, varargin{2});
            end
        else
            if iscell(varargin{2})
                if iscell(varargin{3})
                    [ColumnName{i}, ErrorTmp] = family2archive(varargin{1}{i}, varargin{2}{i}, varargin{3}{i});
                else
                    [ColumnName{i}, ErrorTmp] = family2archive(varargin{1}{i}, varargin{2}{i}, varargin{3});
                end
            else
                if iscell(varargin{3})
                    [ColumnName{i}, ErrorTmp] = family2archive(varargin{1}{i}, varargin{2}, varargin{3}{i});
                else
                    [ColumnName{i}, ErrorTmp] = family2archive(varargin{1}{i}, varargin{2}, varargin{3});
                end
            end
        end
        ErrorFlag = ErrorFlag | ErrorTmp;
    end
    return
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Family or data structure inputs beyond this point %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if isstruct(varargin{1})
    if isfield(varargin{1},'FamilyName') && isfield(varargin{1},'Field')
        % Data structure inputs
        Family = varargin{1}.FamilyName;
        Field = varargin{1}.Field;
        if length(varargin) >= 2
            if ischar(varargin{2})
                Field = varargin{2};
                varargin(2) = [];
            end
        end
        if length(varargin) >= 2
            DeviceList = varargin{2};
        else
            DeviceList = varargin{1}.DeviceList;
        end
    else
        % AO input
        Family = varargin(1).FamilyName;
        Field = '';
        if length(varargin) >= 2
            if ischar(varargin{2})
                Field = varargin{2};
                varargin(2) = [];
            end
        end
        if length(varargin) >= 2
            DeviceList = varargin{2};
        else
            DeviceList = varargin{1}.DeviceList;
        end
        if isempty(Field)
            Field = 'Monitor';
        end
        if isempty(DeviceList)
            DeviceList = varargin{1}.DeviceList;
        end
        if isempty(DeviceList)
            DeviceList = family2dev(Family);
        end
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % CommonName Input:  Convert common names to a varargin{3} %
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        if ischar(DeviceList) && ~isempty(DeviceList)
            DeviceList = common2dev(DeviceList, Family);
            if isempty(DeviceList)
                error('DeviceList was a string but common names could not be found.');
            end
        end
        [i,iNotFound] = findrowindex(DeviceList, varargin{1}.DeviceList);
        if ~isempty(iNotFound)
            error('Device at found in the input structure');
        end
        ColumnName = varargin{1}.(Field).ColumnName(i,:);
        ErrorFlag = 0;
        return;
    end
else
    % Family input
    Family = varargin{1};
    Field = '';
    if length(varargin) >= 2
        if ischar(varargin{2})
            Field = varargin{2};
            varargin(2) = [];
        end
    end
    if length(varargin) >= 2
        DeviceList = varargin{2};
    else
        DeviceList = [];
    end
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Check DeviceList or Family is a common name list %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    [Family, DeviceList] = checkforcommonnames(Family, DeviceList);
end
%%%%%%%%%%%%%%%%%
% Special cases %
%%%%%%%%%%%%%%%%%
switch Family
    case 'LCW'
        ColumnName = 'LCW';
    case 'DCCT'
        ColumnName = 'DCCT';
    case {'Energy', 'ENERGY'}
        ColumnName = 'Energy';
    case {'UserBeam', 'UserBeam'}
        ColumnName = 'UserBeam';
    otherwise
        % Use the channel name
        if isempty(Field)
            Field = 'Monitor';
        end
        if isempty(DeviceList)
            DeviceList = family2dev(Family);
        end
        [ColumnName, ErrorFlag] = getfamilydata(Family, Field, 'ChannelNames', DeviceList);
        % Convert '.' to '_'
        [i,j] = find(ColumnName == '.');
        ColumnName(i,j) = '_';
end