Description of gaplimit
Home > ALS > StorageRing > gaplimit.m
gaplimit
PURPOSE
[GapMin, GapMax] = gaplimit(ID_Number);
SYNOPSIS
function [GAPmin, GAPmax] = gaplimit(Dev);
DESCRIPTION
 [GapMin, GapMax] = gaplimit(ID_Number);
   ID_Number = insertion device sector number
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
srcontrol5 srcontrol5
srcontrol5_20070325 srcontrol5
srcontrol5_20070403 srcontrol5
srcontrol5_before_20070409 srcontrol5
srcontrol5_before_20070413 srcontrol5
srcontrol5_includingEPUtuneFF srcontrol5
srcontrol5_including_FOFB_indicators srcontrol5
srcontrol5_including_vectorized_EPU_FF srcontrol5
srcontrol5_new_but_broken_EPUtuneFF_20070723 srcontrol5
srcontrol5_pre20070507 srcontrol5
srcontrol5_with_BPM_timeconstant_reset srcontrol5
srcontrol5_with_IVIDskewFF srcontrol5
srcontrol5_with_chicane_checks srcontrol5
srcontrol5_without_FOFB_indicators srcontrol5
srcontrol5_without_chicane_trim_checks_pre20070730 srcontrol5
SOURCE CODE
function [GAPmin, GAPmax] = gaplimit(Dev);
% [GapMin, GapMax] = gaplimit(ID_Number);
%
%   ID_Number = insertion device sector number
if nargin == 0
    error('GAPLIMIT: one input required.');
elseif nargin == 1
    if isempty(Dev)
        error('GAPLIMIT: ID_Number is empty.');
    end
end
for i = 1:size(Dev,1)
    if length(Dev(i,:)) == 1
        SectorList = [Dev(i,:),1];
    else
        SectorList = Dev(i,:);
    end
    GAPmin(i,1) = minsp('ID', SectorList);
    GAPmax(i,1) = maxsp('ID', SectorList);
end