Description of getff
Home > ALS > StorageRing > getff.m
getff
PURPOSE
function [FFEnableBM, FFEnableBC, GapEnableBM, GapEnableBC, Sector] = getff(Sector)
SYNOPSIS
function [FFEnableBM, FFEnableBC, GapEnableBM, GapEnableBC, Sector] = getff(Sector)
DESCRIPTION
 function [FFEnableBM, FFEnableBC, GapEnableBM, GapEnableBC, Sector] = getff(Sector)
 2005-02-23, C. Steier, modified to allow Sector to be devicelist
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
siglabgetdata
siglabgetdataweb
srcontrol5 srcontrol5
srcontrol5_20070325 srcontrol5
srcontrol5_20070403 srcontrol5
srcontrol5_before_20070409 srcontrol5
srcontrol5_before_20070413 srcontrol5
srcontrol5_includingEPUtuneFF srcontrol5
srcontrol5_including_FOFB_indicators srcontrol5
srcontrol5_including_vectorized_EPU_FF srcontrol5
srcontrol5_new_but_broken_EPUtuneFF_20070723 srcontrol5
srcontrol5_pre20070507 srcontrol5
srcontrol5_with_BPM_timeconstant_reset srcontrol5
srcontrol5_with_IVIDskewFF srcontrol5
srcontrol5_with_chicane_checks srcontrol5
srcontrol5_without_FOFB_indicators srcontrol5
srcontrol5_without_chicane_trim_checks_pre20070730 srcontrol5
SOURCE CODE
function [FFEnableBM, FFEnableBC, GapEnableBM, GapEnableBC, Sector] = getff(Sector)
% function [FFEnableBM, FFEnableBC, GapEnableBM, GapEnableBC, Sector] = getff(Sector)
%
% 2005-02-23, C. Steier, modified to allow Sector to be devicelist
if nargin < 1
    tmp = getlist('ID');
    Sector = tmp(:,1);
    Device = tmp(:,2);
else
    if size(Sector,2)==2
        Device = Sector(:,2);
        Sector = Sector(:,1);
    else
        Device = zeros(size(Sector));
        for loop = 1:length(Sector)
            if Sector(loop) == 11
                Device(loop,1) = 2;
            else
                Device(loop,1) = 1;
            end
        end
    end
end
Mode = getmode('HCM');
if strcmpi(Mode,'Simulator')
    FFEnableBM = zeros(size(Sector,1));
    FFEnableBC = zeros(size(Sector,1));
    GapEnableBM = zeros(size(Sector,1));
    GapEnableBC = zeros(size(Sector,1));
else
    if isempty(Sector)
        tmp = getlist('ID');
        Sector = tmp(:,1);
        Device = tmp(:,2);
    end
    for i = 1:length(Sector)
        if Sector(i) == 5
            IDName = 'w';
        else
            IDName = 'u';
        end
        % EPICs Only Channels
        if Sector(i) == 11
            ChanName = sprintf('sr%02d%c%1i:FFEnable:bo', Sector(i), IDName, Device(i));
        else
            ChanName = sprintf('sr%02d%c:FFEnable:bo', Sector(i), IDName);
        end
        FFEnableBC(i,1) = getam(ChanName);
        if Sector(i) == 11
            ChanName = sprintf('sr%02d%c%1i:FFEnable:bi', Sector(i), IDName, Device(i));
        else
            ChanName = sprintf('sr%02d%c:FFEnable:bi', Sector(i), IDName);
        end
        FFEnableBM(i,1) = getam(ChanName);
        if Sector(i) == 11
            ChanName = sprintf('sr%02d%c%1i:opr_grant', Sector(i), IDName, Device(i));
        else
            ChanName = sprintf('cmm:ID%d_opr_grant', Sector(i));
        end
        %ChanName = sprintf('sr%02d%c:GapEnable:bo', Sector(i), IDName);
        GapEnableBC(i,1) = getam(ChanName);
        if Sector(i) == 11
            ChanName = sprintf('sr%02d%c%1i:GapEnable:bi', Sector(i), IDName, Device(i));
        else
            ChanName = sprintf('sr%02d%c:GapEnable:bi', Sector(i), IDName);
        end
        GapEnableBM(i,1) = getam(ChanName);
    end
end