Description of getid
Home > ALS > StorageRing > getid.m
getid
PURPOSE
GETID - Get the insertion device position, velocity, run flag, and user requested gap
SYNOPSIS
function [Position, Velocity, RunFlag, UserGap] = getid(DeviceList, ChanType)
DESCRIPTION
GETID - Get the insertion device position, velocity, run flag, and user requested gap
 [Position, Velocity, RunFlag, UserGap] = getid(DeviceList, ChanType)
   DeviceList - DeviceList Number
   Position  - Insertion device position [mm]
   Velocity  - Insertion device velocity [mm/sec]
   RunFlag   - Run count number -> .5 if running
                                -> negative if error occurred
   UserGap   - Insertion device user requested position [mm]
   ChanType  - 0 -> monitor for position and velocity {Default}
                 -> setpoint for position and velocity
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
getidinfo function [FFEnableBM, FFEnableBC, GapEnableBM, GapEnableBC, Sector] = getidinfo(Sector)
setid SETID - Set the insertion device vertical gap
siglabgetdata
siglabgetdataweb
srcontrol5 srcontrol5
srcontrol5_20070325 srcontrol5
srcontrol5_20070403 srcontrol5
srcontrol5_before_20070409 srcontrol5
srcontrol5_before_20070413 srcontrol5
srcontrol5_includingEPUtuneFF srcontrol5
srcontrol5_including_FOFB_indicators srcontrol5
srcontrol5_including_vectorized_EPU_FF srcontrol5
srcontrol5_new_but_broken_EPUtuneFF_20070723 srcontrol5
srcontrol5_pre20070507 srcontrol5
srcontrol5_with_BPM_timeconstant_reset srcontrol5
srcontrol5_with_IVIDskewFF srcontrol5
srcontrol5_with_chicane_checks srcontrol5
srcontrol5_without_FOFB_indicators srcontrol5
srcontrol5_without_chicane_trim_checks_pre20070730 srcontrol5
SOURCE CODE
function [Position, Velocity, RunFlag, UserGap] = getid(DeviceList, ChanType)
%GETID - Get the insertion device position, velocity, run flag, and user requested gap
% [Position, Velocity, RunFlag, UserGap] = getid(DeviceList, ChanType)
%   DeviceList - DeviceList Number
%   Position  - Insertion device position [mm]
%   Velocity  - Insertion device velocity [mm/sec]
%   RunFlag   - Run count number -> .5 if running
%                                -> negative if error occurred
%   UserGap   - Insertion device user requested position [mm]
%
%   ChanType  - 0 -> monitor for position and velocity {Default}
%                 -> setpoint for position and velocity
%
if nargin == 0
    DeviceList = [];
end
if isempty(DeviceList)
    DeviceList = family2dev('ID');
end
if size(DeviceList,2) == 1
    DeviceList = elem2dev('ID', DeviceList);
end
if nargin < 2
    ChanType = [];
end
if isempty(ChanType)
    ChanType= 0;
end
if ChanType
    Position = getsp('ID', DeviceList);
    if nargout >= 2
        Velocity = getpv('ID', 'VelocitySP', DeviceList);
    end
else
    Position = getam('ID', DeviceList);
    if nargout >= 2
        Velocity = getpv('ID', 'Velocity', DeviceList);
    end
end
if nargout >= 3
    RunFlag = getpv('ID', 'RunFlag', DeviceList);
end
if nargout >= 4
    UserGap = getpv('ID', 'UserGap', DeviceList);
end