Description of getpbpm
Home > ALS > StorageRing > getpbpm.m
getpbpm
PURPOSE
SYNOPSIS
function p = getpbpm
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
pbpm_scanbiasvoltage
pbpm_scanbump
pbpm_scandcct
SOURCE CODE
function p = getpbpm
if 1
    p(1,1) = getpv('Physics1');
    p(2,1) = getpv('Physics2');
    p(3) = getpv('Physics3');
    p(4) = getpv('Physics4');
    p(5) = getpv('Physics5');
    p(6) = getpv('Physics6');
    p(7) = getpv('Physics7');
    p(8) = getpv('Physics8');
    p(9) = getpv('Physics9');
    p(10) = getpv('Physics10');
else
    load siglabdata;
    p = Data;
end