Description of getsuperbendtemperatures
Home > ALS > StorageRing > getsuperbendtemperatures.m
getsuperbendtemperatures
PURPOSE
SYNOPSIS
function [BSCcoiltemps, BSCcoilnames] = getsuperbendtemperatures
DESCRIPTION
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
srcycle SRCYCLE - Storage ring cycle
srramp SRRAMP - Ramp the storage ring energy
srramp_old SRRAMP - Ramp the storage ring energy
SOURCE CODE
function [BSCcoiltemps, BSCcoilnames] = getsuperbendtemperatures
BSC4uppercoiltemp = getpv('SR04C___BSC_T2_AM01');
BSC4lowercoiltemp = getpv('SR04C___BSC_T6_AM05');
BSC8uppercoiltemp = getpv('SR08C___BSC_T2_AM01');
BSC8lowercoiltemp = getpv('SR08C___BSC_T6_AM05');
BSC12uppercoiltemp = getpv('SR12C___BSC_T2_AM01');
BSC12lowercoiltemp = getpv('SR12C___BSC_T6_AM05');
BSCcoiltemps = [BSC4uppercoiltemp BSC4lowercoiltemp BSC8uppercoiltemp BSC8lowercoiltemp BSC12uppercoiltemp BSC12lowercoiltemp];
BSCcoilnames = {'BSC4 Upper Coil','BSC4 Lower Coil','BSC8 Upper Coil','BSC8 Lower Coil','BSC12 Upper Coil','BSC12 Lower Coil'};
return