Description of getsrstate
Home > ALS > StorageRing > getsrstate.m
getsrstate
PURPOSE
[StateNumber, StateString] = getsrstate
SYNOPSIS
function [StateNumber, StateString] = getsrstate
DESCRIPTION
 [StateNumber, StateString] = getsrstate
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
srcontrol5 srcontrol5
srcontrol5_20070325 srcontrol5
srcontrol5_20070403 srcontrol5
srcontrol5_before_20070409 srcontrol5
srcontrol5_before_20070413 srcontrol5
srcontrol5_includingEPUtuneFF srcontrol5
srcontrol5_including_FOFB_indicators srcontrol5
srcontrol5_including_vectorized_EPU_FF srcontrol5
srcontrol5_new_but_broken_EPUtuneFF_20070723 srcontrol5
srcontrol5_pre20070507 srcontrol5
srcontrol5_with_BPM_timeconstant_reset srcontrol5
srcontrol5_with_IVIDskewFF srcontrol5
srcontrol5_with_chicane_checks srcontrol5
srcontrol5_without_FOFB_indicators srcontrol5
srcontrol5_without_chicane_trim_checks_pre20070730 srcontrol5
SOURCE CODE
function [StateNumber, StateString] = getsrstate
% [StateNumber, StateString] = getsrstate
%
StateNumber = getpv('SR_STATE');
if StateNumber == 0
   StateString = 'Unknown';
elseif StateNumber == 1
   StateString = 'Lattice cycled, ready for injection';
elseif StateNumber == -1
   StateString = 'Problem cycling lattice';
elseif StateNumber == 2
   StateString = 'Ready for injection';
elseif StateNumber == -2
   StateString = 'Problems setting up injection';
elseif StateNumber == 3
   StateString = 'User lattice';
elseif StateNumber == -3
   StateString = 'Problems setting up user lattice';
elseif StateNumber == 4
   StateString = 'Correcting the orbit';
elseif StateNumber == 4.1
   StateString = 'Orbit correction complete';
elseif StateNumber == -4
   StateString = 'Problems correcting the orbit';
elseif StateNumber == 5
   StateString = 'Orbit feedback running';
elseif StateNumber == 5.1
   StateString = 'Orbit feedback stopped';
elseif StateNumber == -5
   StateString = 'Problems with orbit feedback';
else
   StateString = 'Unknown';
   StateNumber = 0;
   setpv('SR_STATE',0)
end