Description of ocsinit
Home > ALS > StorageRing > ocsinit.m
ocsinit
PURPOSE
OCSINIT - Corrector and BPM
SYNOPSIS
function [HBPM, VBPM, HCM, VCM, HSV, VSV] = ocsinit(MethodName)
DESCRIPTION
OCSINIT - Corrector and BPM
 [HBPM, VBPM, HCM, VCM, HSV, VSV] = ocsinit(MethodName)
  INPUTS
  1. MethodName = 'TopOfFill'
                  'SOFB'
                  'FOFB'
                  'Injection_TopOfFill'
                  'Offset Orbit'
  NOTE
  1. This is a user operational file
  See also setorbit, setorbitgui, setorbitsetup
CROSS-REFERENCE INFORMATION
This function calls:
getbpmlist GETBPMLIST - Return a BPM list based on key words and sector numbers
getcmlist GETBPMLIST - Return a corrector magnet list based on key words and sector numbers
ocsinit OCSINIT - Corrector and BPM
This function is called by:
ocsinit OCSINIT - Corrector and BPM
setorbitsetup SETORBITSETUP - BPM & CM setup function for setorbitgui
srcontrol5 srcontrol5
srcontrol5_new_but_broken_EPUtuneFF_20070723 srcontrol5
srcontrol5_with_chicane_checks srcontrol5
srcontrol5_without_chicane_trim_checks_pre20070730 srcontrol5
SOURCE CODE
function [HBPM, VBPM, HCM, VCM, HSV, VSV] = ocsinit(MethodName)
%OCSINIT - Corrector and BPM
% [HBPM, VBPM, HCM, VCM, HSV, VSV] = ocsinit(MethodName)
%
%  INPUTS
%  1. MethodName = 'TopOfFill'
%                  'SOFB'
%                  'FOFB'
%                  'Injection_TopOfFill'
%                  'Offset Orbit'
%
%  NOTE
%  1. This is a user operational file
%
%  See also setorbit, setorbitgui, setorbitsetup
if nargin == 0
    MethodName = 'TopOfFill';
end
switch(MethodName)
    case 'TopOfFill'
        % RemoveHBPMDeviceList = [];
        RemoveHBPMDeviceList = [
            9 5;    % this BPM showed strange jumps/drifts on 2007-07-14
        %    3 6;   % this BPM has not been used in old ML OC for a while - suspect it's drifting
        %    3 12;  % this BPM broke during the 11/28-29 maintenance - there was maintenance on the motor chicane...
            ];
        RemoveVBPMDeviceList = RemoveHBPMDeviceList;
        HCMList = getcmlist('HCM', '2 3 6 7 10');
        VCMList = getcmlist('VCM', '1 4 5 8 10');
        VCMList = [1 2; VCMList; 12 7];  % Replacement for missing magnets in sectors 1 & 12
        HBPMList = getbpmlist('Bergoz');
        VBPMList = getbpmlist('Bergoz');
        i = findrowindex(RemoveHBPMDeviceList, HBPMList);
        if ~isempty(i)
            HBPMList(i,:) = [];
        end
        i = findrowindex(RemoveVBPMDeviceList, VBPMList);
        if ~isempty(i)
            VBPMList(i,:) = [];
        end
        HBPM = family2datastruct('BPMx', 'Monitor', HBPMList);
        VBPM = family2datastruct('BPMy', 'Monitor', VBPMList);
        HCM = family2datastruct('HCM', 'Setpoint', HCMList);
        VCM = family2datastruct('VCM', 'Setpoint', VCMList);
        % SVD orbit correction
        HSV = min([size(HCMList,1) size(HBPMList,1)])-4;
        VSV = min([size(VCMList,1) size(VBPMList,1)]);
    case 'SOFB'
        RemoveHBPMDeviceList = [];
        RemoveHBPMDeviceList = [
        %    3 6;   % this BPM has not been used in old ML OC for a while - suspect it's drifting
        %    3 12;  % this BPM broke during the 11/28-29 maintenance - there was maintenance on the motor chicane...
        1 6;
        2 6;
        6 5;   % BPM showed larger (1 mum rms with FFB on) noise than other ones 7/16/2007
        9 5;   % BPM showed stranged drift behavior on 7/15/2007
            ];
        % Remove Bergoz BPMs in SR01 and SR03 for 2-bunch (noisy at low currents) and drop singular values
        if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
            RemoveHBPMDeviceList = [RemoveHBPMDeviceList;
                1 2
                2 9
                3 2
                12 9];
        end
        RemoveVBPMDeviceList = RemoveHBPMDeviceList;
        HCMList = getcmlist('HCM', '1 8 10');
        HCMList = [1 2; HCMList; 12 7];  % Replacement for missing magnets in sectors 1 & 12
        %VCMList = getcmlist('VCM', '1 8 10');
        %VCMList = [1 2; VCMList; 12 7];  % Replacement for missing magnets in sectors 1 & 12
        VCMList = [
            1 2;
            1 8;
            2 1;
            2 8;
            3 1;
            3 7;
            3 8;
            3 10; %SR04U_VHCM2 (chicane trim)
            4 1;
            4 7;
            4 8;
            5 1;
            5 8;
            5 10; %SR06U_VHCM2 (chicane trim)
            6 1;
            6 8;
            7 1;
            7 8;
            8 1;
            8 8;
            9 1;
            9 8;
            10 1;
            10 2;
            10 7;
            10 8;
            10 10; %SR11U_VHCM2 (chicane trim)
            11 1;
            11 7;
            11 8;
            12 1;
            12 7];
        % BPMs
%         HBPMList = getbpmlist('Bergoz', '1 2 5 6 9 10 11 12');  % Don't use new Bergoz for now
%         VBPMList = getbpmlist('Bergoz', '1 2 5 6 9 10 11 12');  % Don't use new Bergoz for now
        HBPMList = getbpmlist('Bergoz');  % 2007-07-16 - start including new bergoz BPMs
        VBPMList = getbpmlist('Bergoz');  % looked overall fine on archivewr data
        i = findrowindex(RemoveHBPMDeviceList, HBPMList);
        if ~isempty(i)
            HBPMList(i,:) = [];
        end
        i = findrowindex(RemoveVBPMDeviceList, VBPMList);
        if ~isempty(i)
            VBPMList(i,:) = [];
        end
        HBPM = family2datastruct('BPMx', 'Monitor', HBPMList);
        VBPM = family2datastruct('BPMy', 'Monitor', VBPMList);
        HCM = family2datastruct('HCM', 'Setpoint', HCMList);
        VCM = family2datastruct('VCM', 'Setpoint', VCMList);
        % SVD orbit correction
        if size(HBPMList,1) < 78
            HSV = 27;
        else
            HSV = 28;
        end
        VSV = 32;
        % Remove Bergoz BPMs in SR01 and SR03 for 2-bunch (noisy at low currents) and drop singular values
        if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
            HBPMList = HBPMList(find(HBPMList(:,1)~=1),:);
            HBPMList = HBPMList(find(HBPMList(:,1)~=3),:);
            Xivec = HSV - 4;
            VBPMList = VBPMList(find(VBPMList(:,1)~=1),:);
            VBPMList = VBPMList(find(VBPMList(:,1)~=3),:);
            Yivec = VSV - 4;
        end
    case 'FOFB'
        RemoveHBPMDeviceList = [
            6 5;   % BPM showed larger (1 mum rms with FFB on) noise than other ones 7/16/2007
                9 5;   % BPM showed stranged drift behavior on 7/15/2007
                ];
          %RemoveHBPMDeviceList = [
        %    3 6;   % this BPM has not been used in old ML OC for a while - suspect it's drifting
        %    3 12;  % this BPM broke during the 11/28-29 maintenance - there was maintenance on the motor chicane...
        %    ];
        RemoveVBPMDeviceList = RemoveHBPMDeviceList;
        % Corrector magnets
        HCMList = [
            1 8;
            2 1;
            2 8;
            3 1;
            3 8;
            4 1;
            4 8;
            5 1;
            5 8;
            6 1;
            6 8;
            7 1;
            7 8;
            8 1;
            8 8;
            9 1;
            9 8;
            10 1;
            10 8;
            11 1;
            11 8;
            12 1];
        VCMList = [
            1 8;
            2 1;
            2 8;
            3 1;
            3 8;
            4 1;
            4 8;
            5 1;
            5 8;
            6 1;
            6 8;
            7 1;
            7 8;
            8 1;
            8 8;
            9 1;
            9 8;
            10 1;
            10 8;
            11 1;
            11 8;
            12 1];
        % BPMs
        HBPMList = getbpmlist('OldBergoz');
        VBPMList = getbpmlist('OldBergoz');
        i = findrowindex(RemoveHBPMDeviceList, HBPMList);
        if ~isempty(i)
            HBPMList(i,:) = [];
        end
        i = findrowindex(RemoveVBPMDeviceList, VBPMList);
        if ~isempty(i)
            VBPMList(i,:) = [];
        end
        HBPM = family2datastruct('BPMx', 'Monitor', HBPMList);
        VBPM = family2datastruct('BPMy', 'Monitor', VBPMList);
        HCM = family2datastruct('HCM', 'Setpoint', HCMList);
        VCM = family2datastruct('VCM', 'Setpoint', VCMList);
        % SVD orbit correction
        HSV = 11;
        VSV = 12;
        % Remove Bergoz BPMs in SR01 and SR03 for 2-bunch (noisy at low currents) and drop singular values
        if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
            HBPMList = HBPMList(find(HBPMList(:,1)~=1),:);
            HBPMList = HBPMList(find(HBPMList(:,1)~=3),:);
            Xivec = HSV - 4;
            VBPMList = VBPMList(find(VBPMList(:,1)~=1),:);
            VBPMList = VBPMList(find(VBPMList(:,1)~=3),:);
            Yivec = VSV - 4;
        end
        HBPM = family2datastruct('BPMx', 'Monitor', HBPMList);
        VBPM = family2datastruct('BPMy', 'Monitor', VBPMList);
        HCM = family2datastruct('HCM', 'Setpoint', HCMList);
        VCM = family2datastruct('VCM', 'Setpoint', VCMList);
    case 'Measured Offsets'
        HBPMList = getbpmlist('HOffset');
        VBPMList = getbpmlist('VOffset');
        HBPM = family2datastruct('BPMx', 'Monitor', HBPMList);
        VBPM = family2datastruct('BPMy', 'Monitor', VBPMList);
        HCMList = getcmlist('HCM','1 2 3 4 5 6 7 8');
        VCMList = getcmlist('VCM','1 2 3 4 5 6 7 8');
        HCM = family2datastruct('HCM', 'Setpoint', HCMList);
        VCM = family2datastruct('VCM', 'Setpoint', VCMList);
        % SVD orbit correction
        HSV = 24;
        VSV = 24;
    case 'Injection'
        % Remove BPMs inside chicane (except a few)
        RemoveHBPMDeviceList = [
            3 11;
            3 12;
            5 11;
            5 12;
            6 1;
            10 10;
            10 11;
            10 12;
            11  1;
            ];
        RemoveVBPMDeviceList = RemoveHBPMDeviceList;
        HBPMList = getbpmlist('BPMx');
        VBPMList = getbpmlist('BPMy');
        i = findrowindex(RemoveHBPMDeviceList, HBPMList);
        if ~isempty(i)
            HBPMList(i,:) = [];
        end
        i = findrowindex(RemoveVBPMDeviceList, VBPMList);
        if ~isempty(i)
            VBPMList(i,:) = [];
        end
        HBPM = family2datastruct('BPMx', 'Monitor', HBPMList);
        VBPM = family2datastruct('BPMy', 'Monitor', VBPMList);
        HCMList = getcmlist('HCM','1 2 3 4 5 6 7 8');
        VCMList = getcmlist('VCM','1 2 3 4 5 6 7 8');
        HCM = family2datastruct('HCM', 'Setpoint', HCMList);
        VCM = family2datastruct('VCM', 'Setpoint', VCMList);
        % SVD orbit correction
        HSV = 24;
        VSV = 24;
    case 'Injection_TopOfFill'
        % Remove BPMs inside chicane (except a few)
        RemoveHBPMDeviceList = [
            3 11;
            3 12;
            5 11;
            5 12;
            6 1;
            10 10;
            10 11;
            10 12;
            11  1;
            ];
        RemoveVBPMDeviceList = RemoveHBPMDeviceList;
        [HBPM, VBPM, HCM, VCM, HSV, VSV] = ocsinit('TopOfFill');
        i = findrowindex(RemoveHBPMDeviceList, HBPM.DeviceList);
        if ~isempty(i)
            HBPM.Data(i,:) = [];
            HBPM.DeviceList(i,:) = [];
            HBPM.Status(i,:) = [];
        end
        i = findrowindex(RemoveVBPMDeviceList, VBPM.DeviceList);
        if ~isempty(i)
            VBPM.Data(i,:) = [];
            VBPM.DeviceList(i,:) = [];
            VBPM.Status(i,:) = [];
        end
        % SVD orbit correction
        HSV = HSV - 8;
        VSV = VSV - 8;
    otherwise
        fprintf('   Orbit correction set unknown.\n');
end
% HCMList = [];
% VCMList = [];
% for Sector = 1:12
%     if Sector == 1
%         VCMList = [VCMList;Sector 2;Sector 4;Sector 5;Sector 8];
%         HCMList = [HCMList;Sector 2;Sector 7];
%     elseif Sector == 3
%         VCMList = [VCMList;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
%         HCMList = [HCMList;Sector 2;Sector 7;Sector 10];
%     elseif Sector == 5
%         VCMList = [VCMList;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
%         HCMList = [HCMList;Sector 2;Sector 7;Sector 10];
%     elseif Sector == 10
%         VCMList = [VCMList;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
%         HCMList = [HCMList;Sector 2;Sector 7;Sector 10];
%     elseif Sector == 12
%         VCMList = [VCMList;Sector 1;Sector 4;Sector 5;Sector 7];
%         HCMList = [HCMList;Sector 2;Sector 7];
%     else
%         VCMList = [VCMList;Sector 1;Sector 4;Sector 5;Sector 8];
%         HCMList = [HCMList;Sector 2;Sector 7];
%     end
% end