Description of plotmysqlorbit
Home > ALS > StorageRing > plotmysqlorbit.m
plotmysqlorbit
PURPOSE
function arplotorbit
SYNOPSIS
This is a script file.
DESCRIPTION
function arplotorbit
CROSS-REFERENCE INFORMATION
This function calls:
family2archive FAMILY2ARCHIVE - Converts the family name to a database column name in the archiver
getbpmlist GETBPMLIST - Return a BPM list based on key words and sector numbers
getmysqldata GETMYSQLDA - Returns data from a mysql database
This function is called by:
SOURCE CODE
%function arplotorbit
%     plot(24*(t-floor(t(1))), d); xlabel(sprintf('Time in Hours Starting at %s', StartTime));
%
%  2. Get all the BPMx and DCCT data in the table
%     Note: if the start and end time is not included in the second call
%           the data and time vectors may not match.
%     [d, t, StartTime, EndTime] = getmysqldata(family2channel('BPMx'));
%     [d, t] = getmysqldata('DCCT', StartTime, EndTime);
%
%  3. For data valid only during user beam
%     [i,t] = getmysqldata('UserBeam', StartTime, EndTime);
%     d(:,find(i==0)) = NaN;
if 1
    % Orbit Feedback glitch
    StartTime = [2007 3 7 14 00 00];
    EndTime   = [2007 3 7 15 45 00];
    %StartTime = [2007 3 7 15 02 00];
    %EndTime   = [2007 3 7 15 12 00];
else
    % Top of the fill
    StartTime = [2007 3 7 17 37 00];
    EndTime   = [2007 3 7 17 42 00];
end
StartTime = [2007 3 8  13 15 00];
EndTime   = [2007 3 8  14 15 00];
[DCCT, t, StartTime, EndTime] = getmysqldata(family2archive('DCCT'), StartTime, EndTime);
[x, t, StartTime, EndTime] = getmysqldata(family2archive('BPMx', getbpmlist('Bergoz')), StartTime, EndTime);
x = rmgolden('BPMx', x, getbpmlist('Bergoz'));
[y, t, StartTime, EndTime] = getmysqldata(family2archive('BPMy', getbpmlist('Bergoz')), StartTime, EndTime);
y = rmgolden('BPMy', y, getbpmlist('Bergoz'));
[RFam, t, StartTime, EndTime] = getmysqldata(family2archive('RF','Monitor'),  StartTime, EndTime);
[RFsp, t, StartTime, EndTime] = getmysqldata(family2archive('RF','Setpoint'), StartTime, EndTime);
DevList = family2dev('HCM','Trim',1,1);
[HCMtrim, t, StartTime, EndTime] = getmysqldata(family2archive('HCM', 'Trim', DevList), StartTime, EndTime);
[HCMsp, t, StartTime, EndTime] = getmysqldata(family2archive('HCM', 'Setpoint'), StartTime, EndTime);
[HCMam, t, StartTime, EndTime] = getmysqldata(family2archive('HCM', 'Monitor'),  StartTime, EndTime);
for i = 1:size(HCMam,1)
    HCMsp(i,:) = HCMsp(i,:) - HCMsp(i,1);
    HCMam(i,:) = HCMam(i,:) - HCMam(i,1);
end
[HCM10sp, t, StartTime, EndTime] = getmysqldata(family2archive('HCM', 'Setpoint', [3 10; 5 10; 10 10]), StartTime, EndTime);
[HCM10am, t, StartTime, EndTime] = getmysqldata(family2archive('HCM', 'Monitor',  [3 10; 5 10; 10 10]),  StartTime, EndTime);
for i = 1:size(HCM10am,1)
    HCM10sp(i,:) = HCM10sp(i,:) - HCM10sp(i,1);
    HCM10am(i,:) = HCM10am(i,:) - HCM10am(i,1);
end
DevList = family2dev('HCM','FF1',1,1);
[HCMff1, t, StartTime, EndTime] = getmysqldata(family2archive('HCM', 'FF1', DevList), StartTime, EndTime);
DevList = family2dev('HCM','FF2',1,1);
[HCMff2, t, StartTime, EndTime] = getmysqldata(family2archive('HCM', 'FF2', DevList), StartTime, EndTime);
[QFsp, t, StartTime, EndTime] = getmysqldata(family2archive('QF', 'Setpoint'), StartTime, EndTime);
[QFam, t, StartTime, EndTime] = getmysqldata(family2archive('QF', 'Monitor'),  StartTime, EndTime);
for i = 1:size(QFam,1)
    QFsp(i,:) = QFsp(i,:) - QFsp(i,1);
    QFam(i,:) = QFam(i,:) - QFam(i,1);
end
[ID,  t, StartTime, EndTime] = getmysqldata(family2archive('ID',  'Monitor'), StartTime, EndTime);
[EPU, t, StartTime, EndTime] = getmysqldata(family2archive('EPU', 'Monitor'),  StartTime, EndTime);
[HCMCHICANEM, t, StartTime, EndTime] = getmysqldata(family2archive('HCMCHICANEM', 'Monitor'),  StartTime, EndTime);
for i = 1:size(HCMCHICANEM,1)
    HCMCHICANEM(i,:) = HCMCHICANEM(i,:) - HCMCHICANEM(i,1);
end
figure(1);
clf reset
subplot(2,1,1);
plot(t, x);
datetick('x');
ylabel('Horizontal [mm]');
subplot(2,1,2);
plot(t, y);
ylabel('Vertical [mm]');
datetick('x');
figure(2);
clf reset
subplot(3,1,1);
plot(t, HCMsp);
datetick('x');
ylabel('\DeltaHCM.Setpoint [Amps]');
subplot(3,1,2);
plot(t, HCMtrim);
datetick('x');
ylabel('HCM.Trim [Amps]');
subplot(3,1,3);
plot(t, HCMam);
datetick('x');
ylabel('\DeltaHCM.Monitor [Amps]');
figure(8);
clf reset
subplot(2,1,1);
plot(t, HCM10sp);
datetick('x');
ylabel('\DeltaHCM10.Setpoint [Amps]');
subplot(2,1,2);
plot(t, HCM10am);
datetick('x');
ylabel('\DeltaHCM10.Monitor [Amps]');
figure(4);
clf reset
subplot(2,1,1);
plot(t,HCMff1);
datetick('x');
ylabel('HCM.FF1');
subplot(2,1,2);
plot(t, HCMff2);
datetick('x');
ylabel('HCM.FF2 [Amps]');
figure(5);
clf reset
subplot(2,1,1);
plot(t, QFsp);
datetick('x');
ylabel('\DeltaQF.Setpoint [Amps]');
subplot(2,1,2);
plot(t, QFam);
datetick('x');
ylabel('\DeltaQF.Monitor [Amps]');
figure(6);
clf reset
subplot(2,1,1);
plot(t, ID);
datetick('x');
ylabel('ID.Monitor [mm]');
subplot(2,1,2);
plot(t, EPU);
datetick('x');
ylabel('EPU.Monitor [mm]');
figure(7);
clf reset
subplot(3,1,1);
plot(t, DCCT);
datetick('x');
ylabel('DCCT [mA]');
subplot(3,1,2);
plot(t, RFsp);
datetick('x');
ylabel('RF Setpoint [MHz]');
subplot(3,1,3);
plot(t, HCMCHICANEM);
datetick('x');
ylabel('\DeltaHCMCHICANEM.Monitor');