Description of set_alarmhandler_AHU_thresholds_inject
Home > ALS > StorageRing > set_alarmhandler_AHU_thresholds_inject.m
set_alarmhandler_AHU_thresholds_inject
PURPOSE
function set_alarmhandler_AHU_thresholds_inject
SYNOPSIS
function set_alarmhandler_AHU_thresholds_inject
DESCRIPTION
 function set_alarmhandler_AHU_thresholds_inject
 This function changes some EPICS PV limit fields (.LOLO, .LOW, .HIGH, .HIHI)
 so that the alarm handler behaves properly (read: does not incessantly alarm!)
 2006-03-24 created by T.Scarvie
 2007-02-20 modified by C. Steier
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
srcontrol5 srcontrol5
srcontrol5_20070325 srcontrol5
srcontrol5_20070403 srcontrol5
srcontrol5_before_20070409 srcontrol5
srcontrol5_before_20070413 srcontrol5
srcontrol5_includingEPUtuneFF srcontrol5
srcontrol5_including_FOFB_indicators srcontrol5
srcontrol5_including_vectorized_EPU_FF srcontrol5
srcontrol5_new_but_broken_EPUtuneFF_20070723 srcontrol5
srcontrol5_pre20070507 srcontrol5
srcontrol5_with_BPM_timeconstant_reset srcontrol5
srcontrol5_with_IVIDskewFF srcontrol5
srcontrol5_with_chicane_checks srcontrol5
srcontrol5_without_FOFB_indicators srcontrol5
srcontrol5_without_chicane_trim_checks_pre20070730 srcontrol5
SOURCE CODE
function set_alarmhandler_AHU_thresholds_inject
% function set_alarmhandler_AHU_thresholds_inject
%
% This function changes some EPICS PV limit fields (.LOLO, .LOW, .HIGH, .HIHI)
% so that the alarm handler behaves properly (read: does not incessantly alarm!)
%
% 2006-03-24 created by T.Scarvie
%
% 2007-02-20 modified by C. Steier
%AHU Temps
try
    disp('   Setting AHU Temperature limits so that no false alarms happen during injection');
    scaput('SR01C___AHUT___AM00.HIGH', 23); scaput('SR01C___AHUT___AM00.HIHI', 24);
    scaput('SR03C___AHUT___AM00.HIGH', 23); scaput('SR03C___AHUT___AM00.HIHI', 24);
    scaput('SR04C___AHUT___AM00.HIGH', 23); scaput('SR04C___AHUT___AM00.HIHI', 24);
    scaput('SR06C___AHUT___AM00.HIGH', 23); scaput('SR06C___AHUT___AM00.HIHI', 24);
    scaput('SR07C___AHUT___AM00.HIGH', 23); scaput('SR07C___AHUT___AM00.HIHI', 24);
    scaput('SR08C___AHUT___AM00.HIGH', 23); scaput('SR08C___AHUT___AM00.HIHI', 24);
    scaput('SR09C___AHUT___AM00.HIGH', 24); scaput('SR09C___AHUT___AM00.HIHI', 25);
    scaput('SR11C___AHUT___AM00.HIGH', 25); scaput('SR11C___AHUT___AM00.HIHI', 26);
catch
    disp('   Trouble Setting AHU temp limits!');
end