Description of setbpmtimeconstant
Home > ALS > StorageRing > setbpmtimeconstant.m
setbpmtimeconstant
PURPOSE
SETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
SYNOPSIS
function setbpmtimeconstant(BPMTimeConstant, DeviceList)
DESCRIPTION
SETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
 setbpmtimeconstant(BPMTimeConstant, DeviceList)
  INPUTS
  1. BPMTimeConstant - Time constant [seconds]  {Default: .25}
  2. DeviceList - BPM device list {Default: getbpmlist('Bergoz')}
  See also: getbpmaverages, setbpmaverages, getbpmtimeconstant
  Written by Tom Scarvie
CROSS-REFERENCE INFORMATION
This function calls:
getbpmlist GETBPMLIST - Return a BPM list based on key words and sector numbers
This function is called by:
srcontrol5 srcontrol5
srcontrol5_20070325 srcontrol5
srcontrol5_20070403 srcontrol5
srcontrol5_before_20070409 srcontrol5
srcontrol5_before_20070413 srcontrol5
srcontrol5_includingEPUtuneFF srcontrol5
srcontrol5_including_FOFB_indicators srcontrol5
srcontrol5_including_vectorized_EPU_FF srcontrol5
srcontrol5_new_but_broken_EPUtuneFF_20070723 srcontrol5
srcontrol5_pre20070507 srcontrol5
srcontrol5_with_BPM_timeconstant_reset srcontrol5
srcontrol5_with_IVIDskewFF srcontrol5
srcontrol5_with_chicane_checks srcontrol5
srcontrol5_without_FOFB_indicators srcontrol5
srcontrol5_without_chicane_trim_checks_pre20070730 srcontrol5
SOURCE CODE
function setbpmtimeconstant(BPMTimeConstant, DeviceList)
%SETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
% setbpmtimeconstant(BPMTimeConstant, DeviceList)
%
%  INPUTS
%  1. BPMTimeConstant - Time constant [seconds]  {Default: .25}
%  2. DeviceList - BPM device list {Default: getbpmlist('Bergoz')}
%
%  See also: getbpmaverages, setbpmaverages, getbpmtimeconstant
%
%  Written by Tom Scarvie
%  NOTE
%  1. This function is called by all orbit correction routines.
%  2. The time constant channel for Bergoz style BPMs in the arcs live in the "ffbsecxx" Fast
%     Feedback cPCI crates and are set via the corresponding SRxxS___IBPM___AC00 channels.
%      The sector 4, 8, and 12 BPMs have separate crates and the  time constant channel
%     is set via the SRxxC___BPM__T_AC00 channels.
if nargin < 1
   BPMTimeConstant = 0.25;
end
if nargin < 2
    DeviceList = getbpmlist('Bergoz');
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Set the Bergoz BPM Time Constant %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Can't set a non-Bergoz style time constant
[tmp1, tmp2, i] = findrowindex(DeviceList, getbpmlist('nonBergoz'));
if ~isempty(i)
    fprintf('   Removing non-Bergoz style BPMs.\n');
    DeviceList(i,:) = [];
    if length(BPMTimeConstant) > 1
        BPMTimeConstant(i) = [];
    end
end
setpv('BPMx', 'TimeConstant', BPMTimeConstant, DeviceList);