Description of setff
Home > ALS > StorageRing > setff.m
setff
PURPOSE
function setff(Sector, FFEnableBC, GapEnableBC)
SYNOPSIS
function setff(Sector, FFEnableBC, GapEnableBC)
DESCRIPTION
 function setff(Sector, FFEnableBC, GapEnableBC)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
setbumps SETBUMPS - Make a straight section bump
srcontrol5 srcontrol5
srcontrol5_20070325 srcontrol5
srcontrol5_20070403 srcontrol5
srcontrol5_before_20070409 srcontrol5
srcontrol5_before_20070413 srcontrol5
srcontrol5_includingEPUtuneFF srcontrol5
srcontrol5_including_FOFB_indicators srcontrol5
srcontrol5_including_vectorized_EPU_FF srcontrol5
srcontrol5_new_but_broken_EPUtuneFF_20070723 srcontrol5
srcontrol5_pre20070507 srcontrol5
srcontrol5_with_BPM_timeconstant_reset srcontrol5
srcontrol5_with_IVIDskewFF srcontrol5
srcontrol5_with_chicane_checks srcontrol5
srcontrol5_without_FOFB_indicators srcontrol5
srcontrol5_without_chicane_trim_checks_pre20070730 srcontrol5
SOURCE CODE
function setff(Sector, FFEnableBC, GapEnableBC)
% function setff(Sector, FFEnableBC, GapEnableBC)
Mode = getmode('HCM');
if ~strcmpi(Mode,'Simulator')
    if nargin < 2
        error('Need atleast two inputs.');
    end
    if isempty(Sector)
        Sector = family2dev('ID');
    end
    setpv('ID', 'FFEnableControl', FFEnableBC, Sector);
    if nargin >= 3
        setpv('ID', 'GapEnableControl', GapEnableBC, Sector);
    end
    sleep(.1);
end