Description of setoperationalmode
Home > ALS > StorageRing > setoperationalmode.m
setoperationalmode
PURPOSE
SETOPERATIONALMODE - Switches between the various operational modes
SYNOPSIS
function setoperationalmode(ModeNumber)
DESCRIPTION
SETOPERATIONALMODE - Switches between the various operational modes
  setoperationalmode(ModeNumber)
  ModeNumber = 1. 1.9 GeV, Top Off
               2. 1.9 GeV, Ramping from 1.23 GeV
               3. 1.9 GeV, High Tune
               4. 1.9 GeV, Low  Tune
               5. 1.9 GeV, 2-Bunch
               6. 1.5 GeV, High Tune
               7. 1.5 GeV, Isochronous Sections
               8. 1.5 GeV, Ramping from 1.23 GeV
             101. 1.9 GeV, Model
             999. Greg's Mode
            9999. Tom's Mode
             100. Christoph's Mode
             200. Walter's Mode
  See also aoinit, updateatindex, alsinit
CROSS-REFERENCE INFORMATION
This function calls:
alslat_MultipleRings Lattice definition file
alslat_isochronous_sections_122bpms Lattice definition file
alslat_loco_3sb_disp_nuy9_122bpms Lattice definition file
alslat_loco_3sb_disp_nuy9_122bpms_splitdipole Lattice definition file
getbpmlist GETBPMLIST - Return a BPM list based on key words and sector numbers
setgainsandoffsets
setlocodata SETLOCODATA - Applies the LOCO calibration data to both the middle layer & the accelerator
updateatindex UPDATEATINDEX - Updates the AT indices in the MiddleLayer with the present AT lattice (THERING)
This function is called by:
alsinit ALSINIT
pbpm_plotscanbump if abs(y(1,1)-y(1,end)) < .1
SUBFUNCTIONS
function BuildOffsetAndGoldenOrbits
SOURCE CODE
function setoperationalmode(ModeNumber)
%SETOPERATIONALMODE - Switches between the various operational modes
%  setoperationalmode(ModeNumber)
%
%  ModeNumber = 1. 1.9 GeV, Top Off
%               2. 1.9 GeV, Ramping from 1.23 GeV
%               3. 1.9 GeV, High Tune
%               4. 1.9 GeV, Low  Tune
%               5. 1.9 GeV, 2-Bunch
%               6. 1.5 GeV, High Tune
%               7. 1.5 GeV, Isochronous Sections
%               8. 1.5 GeV, Ramping from 1.23 GeV
%             101. 1.9 GeV, Model
%
%             999. Greg's Mode
%            9999. Tom's Mode
%             100. Christoph's Mode
%             200. Walter's Mode
%
%  See also aoinit, updateatindex, alsinit
global THERING
% Check if the AO exists
checkforao;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Accelerator Dependent Modes %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if nargin < 1
    ModeNumber = [];
end
if isempty(ModeNumber)
    ModeCell = {'1.9 GeV, Top Off', '1.9 GeV, Inject at 1.23 GeV', '1.9 Gev, High Tune', '1.9 Gev, Low Tune', '1.9 Gev, 2-Bunch','1.5 Gev, High Tune', '1.5 GeV, Isochronous Sections', '1.5 GeV, Inject at 1.23 GeV', '1.9 GeV, Model', 'Greg''s Mode', 'Tom''s Mode', 'Christoph''s Mode', 'Walter''s Mode'};
    [ModeNumber, OKFlag] = listdlg('Name','ALS','PromptString','Select the Operational Mode:', 'SelectionMode','single', 'ListString', ModeCell, 'ListSize', [450 200]);
    if OKFlag ~= 1
        fprintf('   Operational mode not changed\n');
        return
    end
    if ModeNumber == 9
        ModeNumber = 101;  % Model
    elseif ModeNumber == 10
        ModeNumber = 999;  % Greg
    elseif ModeNumber == 11
        ModeNumber = 9999; % Tom
    elseif ModeNumber == 12
        ModeNumber = 100;  % Christoph
    elseif ModeNumber == 13
        ModeNumber = 200;  % Walter
    end
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Accelerator Data Structure %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
AD = getad;
AD.Machine = 'ALS';               % Will already be defined if setpathmml was used
AD.SubMachine = 'StorageRing';    % Will already be defined if setpathmml was used
AD.OperationalMode = '';          % Gets filled in later
AD.HarmonicNumber = 328;
AD.BSCRampRate = 0.8;
% Defaults RF for disperion and chromaticity measurements (must be in Hardware units)
AD.DeltaRFDisp = 1000e-6;
AD.DeltaRFChro = [-2000 -1000 0 1000 2000] * 1e-6;
% Tune processor delay: delay required to wait
% to have a fresh tune measurement after changing
% a variable like the RF frequency.  Setpv will wait
% 2.2 * TuneDelay to be guaranteed a fresh data point.
AD.TuneDelay = 5.0;
% The offset and golden orbits are stored at the end of this file
BuildOffsetAndGoldenOrbits;  % Local function
% SP-AM Error level
% AD.ErrorWarningLevel = 0 -> SP-AM errors are Matlab errors {Default}
%                       -1 -> SP-AM errors are Matlab warnings
%                       -2 -> SP-AM errors prompt a dialog box
%                       -3 -> SP-AM errors are ignored (ErrorFlag=-1 is returned)
AD.ErrorWarningLevel = 0;
% Set the status of all the corrector on
% This is needed because some operational modes may have changed the .Status field
%setfamilydata(ones(size(family2dev('HCM',0),1),1),'HCM','Status');   Remove the HCM converted to skew quad before uncommenting this.
%setfamilydata(ones(size(family2dev('VCM',0),1),1),'VCM','Status');
%i = findrowindex([3 10; 5 10; 10 10], HCMlist);
% i = findrowindex([5 10], HCMlist);
% AO.HCM.Status(i) = 0;
% i = findrowindex([10 10], HCMlist);
% AO.HCM.Status(i) = 0;
%i = findrowindex([3 10; 5 10; 10 10], VCMlist);
% i = findrowindex([5 10], VCMlist);
% AO.VCM.Status(i) = 0;
% i = findrowindex([10 10], VCMlist);
% AO.VCM.Status(i) = 0;
%%%%%%%%%%%%%%%%%%%%%
% Operational Modes %
%%%%%%%%%%%%%%%%%%%%%
% Mode setup variables (mostly path and file names)
% AD.OperationalMode - String used in titles
% ModeName - String used for mode directory name off DataRoot/MachineName
% OpsFileExtension - string add to default file names
MachineName = lower(AD.Machine);
if ModeNumber == 1
    % User mode - High Tune, Top Off injection
    AD.OperationalMode = '1.9 GeV, TopOff';
    AD.Energy = 1.89086196873342;     % Make sure this is the same as bend2gev at the production lattice!
    AD.InjectionEnergy = 1.522;
    ModeName = 'TopOff';
    OpsFileExtension = '_TopOff';
    % AT lattice
    AD.ATModel = 'alslat_loco_3sb_disp_nuy9_122bpms';
    alslat_loco_3sb_disp_nuy9_122bpms;
    % Golden TUNE is with the TUNE family
    % 14.25 / 9.20
    AO = getao;
    AO.TUNE.Monitor.Golden = [
        0.25
        0.20
        NaN];
    setao(AO);
    % Golden chromaticity is in the AD (Physics units)
    AD.Chromaticity.Golden = [.4; 1];   % approx.  [-.6;-1.5] in hardware units
    % Hysteresis branch
    AD.HysteresisBranch = 'Lower';
    switch2hw;
    % Turn off chicane correctors when getting a response matrix
    %setfamilydata(0, 'HCM', 'Status', [6 1;10 8; 11 1]);
elseif ModeNumber == 2
    % High Tune, 1.23 Injection
    AD.Energy = 1.89086196873342;     % Make sure this is the same as bend2gev at the production lattice!
    AD.InjectionEnergy = 1.23;
    AD.OperationalMode = '1.9 GeV, Inject at 1.23';
    ModeName = 'HighTuneLowEnergyInj';
    OpsFileExtension = '_LowEnergyInj';
    % AT lattice
    AD.ATModel = 'alslat_loco_3sb_disp_nuy9_122bpms';
    alslat_loco_3sb_disp_nuy9_122bpms;
    % Golden TUNE is with the TUNE family
    % 14.25 / 9.20
    AO = getao;
    AO.TUNE.Monitor.Golden = [
        0.25
        0.20
        NaN];
    setao(AO);
    % Golden chromaticity is in the AD (Physics units)
    AD.Chromaticity.Golden = [.4; 1];   % approx.  [-.6;-1.5] in hardware units
    % Hysteresis branch
    AD.HysteresisBranch = 'Lower';
    switch2hw;
    % Turn off chicane correctors when getting a response matrix
    %setfamilydata(0, 'HCM', 'Status', [6 1;10 8; 11 1]);
elseif ModeNumber == 3
    % High Tune, 1.522 Injection
    AD.OperationalMode = '1.9 GeV, High Tune';
    AD.Energy = 1.89086196873342;     % Make sure this is the same as bend2gev at the production lattice!
    AD.InjectionEnergy = 1.522;
    ModeName = 'HighTune';
    OpsFileExtension = '_HighTune';
    % AT lattice
    AD.ATModel = 'alslat_loco_3sb_disp_nuy9_122bpms';
    alslat_loco_3sb_disp_nuy9_122bpms;
    %AD.ATModel = 'alslat_122bpmsInQuads';
    %alslat_122bpmsInQuads;
    % Golden TUNE is with the TUNE family
    % 14.25 / 9.20
    AO = getao;
    AO.TUNE.Monitor.Golden = [
        0.25
        0.20
        NaN];
    setao(AO);
    % Golden chromaticity is in the AD (Physics units)
    AD.Chromaticity.Golden = [.4; 1];   % approx.  [-.6;-1.5] in hardware units
    % Hysteresis branch
    AD.HysteresisBranch = 'Lower';
    switch2hw;
    % Turn off chicane correctors when getting a response matrix
    %setfamilydata(0, 'HCM', 'Status', [6 1;10 8; 11 1]);
elseif ModeNumber == 4
    % 1.9 GeV - Low Tune
    AD.OperationalMode = '1.9 GeV, Low Tune';
    AD.Energy = 1.89086196873342;     % Make sure this is the same as bend2gev at the production lattice!
    AD.InjectionEnergy = 1.522;
    ModeName = 'LowTune';
    OpsFileExtension = '_LowTune';
    % AT lattice
    AD.ATModel = 'alslat_loco_3sb_disp_nuy9_122bpms';
    alslat_loco_3sb_disp_nuy9_122bpms;
    % Golden TUNE is with the TUNE family (This could have been in alsphysdata)
    % 14.25 / 8.20
    AO = getao;
    AO.TUNE.Monitor.Golden = [
        0.25
        0.20
        NaN];
    setao(AO);
    % Golden chromaticity is in the AD (Physics units)
    AD.Chromaticity.Golden = [.4; 1];   % approx.  [-.6;-1.5] in hardware units
    % Hysteresis branch
    AD.HysteresisBranch = 'Lower';
    switch2hw;
elseif ModeNumber == 5
    % 1.9 GeV, 2-Bunch
    AD.OperationalMode = '1.9 GeV, Two-Bunch';
    AD.Energy = 1.89086196873342;     % Make sure this is the same as bend2gev at the production lattice!
    AD.InjectionEnergy = 1.23;
    ModeName = 'TwoBunch';
    OpsFileExtension = '_TwoBunch';
    % AT lattice
    AD.ATModel = 'alslat_loco_3sb_disp_nuy9_122bpms';
    alslat_loco_3sb_disp_nuy9_122bpms;
    % Golden TUNE is with the TUNE family
    % 14.25 / 9.20
    AO = getao;
    AO.TUNE.Monitor.Golden = [
        0.25
        0.20
        NaN];
    setao(AO);
    % Golden chromaticity is in the AD (Physics units)
    AD.Chromaticity.Golden = [.4; 1];   % approx.  [-.6;-1.5] in hardware units
    % Hysteresis branch
    AD.HysteresisBranch = 'Lower';
    switch2hw;
elseif ModeNumber == 6
    % 1.5 - High Tune
    AD.OperationalMode = '1.5 GeV, High Tune';
    AD.Energy = 1.522;     % Make sure this is the same as bend2gev at the production lattice!
    AD.InjectionEnergy = 1.522;
    ModeName = '1_5HighTune';
    OpsFileExtension = '_15HighTune';
    % AT lattice
    AD.ATModel = 'alslat_loco_3sb_disp_nuy9_122bpms';
    alslat_loco_3sb_disp_nuy9_122bpms;
    % Golden TUNE is with the TUNE family
    % 14.25 / 9.20
    AO = getao;
    AO.TUNE.Monitor.Golden = [
        0.25
        0.20
        NaN];
    setao(AO);
    % Golden chromaticity is in the AD (Physics units)
    AD.Chromaticity.Golden = [.4; 1];   % approx.  [-.6;-1.5] in hardware units
    % Hysteresis branch
    AD.HysteresisBranch = 'Upper';
    switch2hw;
elseif ModeNumber == 7
    % 1.522 GeV, Isochronous Sections
    AD.OperationalMode = '1.5 GeV, Isochronous Sections';
    AD.Energy = 1.89086196873342;     % Make sure this is the same as bend2gev at the production lattice!
    AD.InjectionEnergy = 1.522;
    ModeName = 'IsochronousSections';
    OpsFileExtension = '_IsochronousSections';
    if 1
        % AT lattice
        AD.ATModel = 'alslat_isochronous_sections_122bpms';
        alslat_isochronous_sections_122bpms;
        % Golden TUNE is with the TUNE family
        % 8.39 / 7.15
        AO = getao;
        AO.TUNE.Monitor.Golden = [
            0.39
            0.15
            NaN];
        setao(AO);
    else
        AD.ATModel = 'alslat_isochronous_sections_122bpms_2520tune';
        alslat_isochronous_sections_122bpms_2520tune;
        % Golden TUNE is with the TUNE family
        % 8.25 / 7.20
        AO = getao;
        AO.TUNE.Monitor.Golden = [
            0.25
            0.20
            NaN];
        setao(AO);
    end
    AD.Energy = 1.522;
    AD.InjectionEnergy = 1.522;
    % Golden chromaticity is in the AD (Physics units)
    AD.Chromaticity.Golden = [.4; 1];
    % Hysteresis branch
    AD.HysteresisBranch = 'Upper';
    switch2hw;
elseif ModeNumber == 8
    % 1.5 GeV High Tune, 1.23 Injection
    AD.Energy = 1.52322;     % Make sure this is the same as bend2gev at the production lattice!
    AD.InjectionEnergy = 1.23;
    AD.OperationalMode = '1.5 GeV, Inject at 1.23';
    ModeName = '15_HighTuneLowEnergyInj';
    OpsFileExtension = '_15LowEnergyInj';
    % AT lattice
    AD.ATModel = 'alslat_loco_3sb_disp_nuy9_122bpms';
    alslat_loco_3sb_disp_nuy9_122bpms;
    % Golden TUNE is with the TUNE family
    % 14.25 / 9.20
    AO = getao;
    AO.TUNE.Monitor.Golden = [
        0.25
        0.20
        NaN];
    setao(AO);
    % Golden chromaticity is in the AD (Physics units)
    AD.Chromaticity.Golden = [.4; 1];   % approx.  [-.6;-1.5] in hardware units
    % Hysteresis branch
    AD.HysteresisBranch = 'Lower';
    switch2hw;
    % Turn off chicane correctors when getting a response matrix
    %setfamilydata(0, 'HCM', 'Status', [6 1;10 8; 11 1]);
elseif ModeNumber == 101
    % Model mode
    AD.OperationalMode = '1.9 GeV, Model';
    AD.Energy = 1.89086196873342;     % Make sure this is the same as bend2gev at the production lattice!
    AD.InjectionEnergy = 1.522;
    ModeName = 'Model';
    OpsFileExtension = '';
    % AT lattice
    %AD.ATModel = 'alslat_loco_3sb_disp_nuy9_122bpms';
    %alslat_loco_3sb_disp_nuy9_122bpms;
    AD.ATModel = 'alslat_loco_3sb_disp_nuy9_122bpms_splitdipole';
    alslat_loco_3sb_disp_nuy9_122bpms_splitdipole;
    % Golden TUNE is with the TUNE family
    % 14.25 / 9.20
    AO = getao;
    AO.TUNE.Monitor.Golden = [
        0.25
        0.20
        NaN];
    setao(AO);
    % Golden chromaticity is in the AD (Physics units)
    AD.Chromaticity.Golden = [.4; 1];   % approx.  [-.6;-1.5] in hardware units
    % Hysteresis branch
    AD.HysteresisBranch = 'Lower';
    AD.TuneDelay = 0.0;
    switch2hw;
elseif ModeNumber == 999
    % Greg's mode
    AD.OperationalMode = '1.9 GeV, Greg Mode';
    AD.Energy = 1.89086196873342;     % Make sure this is the same as bend2gev at the production lattice!
    AD.InjectionEnergy = 1.522;
    ModeName = 'Greg';
    OpsFileExtension = '';
    % AT lattice
    %AD.ATModel = 'alslat_loco_3sb_disp_nuy9_122bpms';
    %alslat_loco_3sb_disp_nuy9_122bpms;
    AD.ATModel = 'alslat_MultipleRings';
    alslat_MultipleRings;
    %AD.ATModel = 'alslat_symp_3sb_disp_ID';
    %alslat_symp_3sb_disp_ID
    % Golden TUNE is with the TUNE family
    AO = getao;
    AO.TUNE.Monitor.Golden = [
        0.25
        0.20
        NaN];
    setao(AO);
    % Golden chromaticity is in the AD (Physics units)
    AD.Chromaticity.Golden = [.4; 1];   % approx.  [-.6;-1.5] in hardware units
    % Hysteresis branch
    AD.HysteresisBranch = 'Lower';
    AD.TuneDelay = 0.0;
    switch2hw;
    % SP-AM Error level
    % AD.ErrorWarningLevel = 0 -> SP-AM errors are Matlab errors {Default}
    %                       -1 -> SP-AM errors are Matlab warnings
    %                       -2 -> SP-AM errors prompt a dialog box
    %                       -3 -> SP-AM errors are ignored
    AD.ErrorWarningLevel = 0;
elseif ModeNumber == 9999
    % Tom's mode
    AD.OperationalMode = '1.9 GeV, Tom Mode';
    AD.Energy = 1.89086196873342;     % Make sure this is the same as bend2gev at the production lattice!
    AD.InjectionEnergy = 1.522;
    ModeName = 'Tom';
    OpsFileExtension = '';
    % AT lattice
    AD.ATModel = 'alslat_loco_3sb_disp_nuy9_122bpms';
    alslat_loco_3sb_disp_nuy9_122bpms;
    % Golden TUNE is with the TUNE family
    AO = getao;
    AO.TUNE.Monitor.Golden = [
        0.25
        0.20
        NaN];
    setao(AO);
    % Golden chromaticity is in the AD (Physics units)
    AD.Chromaticity.Golden = [.4; 1];   % approx.  [-.6;-1.5] in hardware units
    % Hysteresis branch
    AD.HysteresisBranch = 'Lower';
    AD.TuneDelay = 0.0;
    switch2hw;
elseif ModeNumber == 100
    % Christoph's mode
    AD.OperationalMode = '1.9 GeV, Christoph Mode';
    AD.Energy = 1.89086196873342;     % Make sure this is the same as bend2gev at the production lattice!
    AD.InjectionEnergy = 1.522;
    ModeName = 'Christoph';
    OpsFileExtension = '';
    % AT lattice
    AD.ATModel = 'alslat_loco_3sb_disp_nuy9_122bpms';
    alslat_loco_3sb_disp_nuy9_122bpms;
    % Golden TUNE is with the TUNE family
    AO = getao;
    AO.TUNE.Monitor.Golden = [
        0.25
        0.20
        NaN];
    setao(AO);
    % Golden chromaticity is in the AD (Physics units)
    AD.Chromaticity.Golden = [.4; 1];   % approx.  [-.6;-1.5] in hardware units
    % Hysteresis branch
    AD.HysteresisBranch = 'Lower';
    AD.TuneDelay = 0.0;
    switch2hw;
elseif ModeNumber == 200
    % Walter's mode
    disp('   This mode switches HCM(5,4) & HCM(6,4) to SQSF(5,1) & SQSF(6,1)');
    AD.OperationalMode = '1.9 GeV, Walter Mode';
    AD.Energy = 1.89086196873342;     % Make sure this is the same as bend2gev at the production lattice!
    AD.InjectionEnergy = 1.522;
    ModeName = 'Walter';
    OpsFileExtension = '_HighTune';
    % AT lattice
    AD.ATModel = 'alslat_loco_3sb_disp_nuy9_122bpms';
    alslat_loco_3sb_disp_nuy9_122bpms;
    % Golden TUNE is with the TUNE family
    AO = getao;
    AO.TUNE.Monitor.Golden = [
        0.25
        0.20
        NaN];
    setao(AO);
    % Golden chromaticity is in the AD (Physics units)
    AD.Chromaticity.Golden = [.4; 1];  % approx.  [-.6;-1.5] in hardware units
    % Hysteresis branch
    AD.HysteresisBranch = 'Lower';
    AD.TuneDelay = 0.0;
    switch2hw;
else
    error('Operational mode unknown');
end
% Set the AD directory path
setad(AD);
MMLROOT = setmmldirectories(AD.Machine, AD.SubMachine, ModeName, OpsFileExtension);
AD = getad;
% ALS specific path changes
% Hysteresis loop files
AD.OpsData.HysteresisLoopUpperLattice = [MMLROOT, 'machine', filesep, AD.Machine, filesep, AD.SubMachine, 'OpsData', filesep, ModeName, filesep, AD.OpsData.LatticeFile];
AD.OpsData.HysteresisLoopLowerLattice = [MMLROOT, 'machine', filesep, AD.Machine, filesep, AD.SubMachine, 'OpsData', filesep, ModeName, filesep, AD.OpsData.InjectionFile];
AD.Default.ChicaneRespFile  = 'ChicaneRespMat'; % File in AD.Directory.BPMResponse    BPM/Chicane response matrice
AD.OpsData.ChicaneRespFile = ['GoldenChicaneResp', OpsFileExtension];
AD.OpsData.RespFiles{length(AD.OpsData.RespFiles)+1} = {[AD.Directory.OpsData, AD.OpsData.ChicaneRespFile]};
% DataRoot Location
% This is a bit of a cluge to know if the user is on the ALS filer
% If so, the location of DataRoot will be different from the middle layer default
if isempty(findstr(lower(MMLROOT),'physbase')) & isempty(findstr(lower(MMLROOT),'n:\'))
    % Keep the normal middle layer directory structure
    switch2sim;
else
    % Use MMLROOT and DataRoot on the ALS filer
    if strcmp(computer,'PCWIN') == 1
        AD.Directory.DataRoot = ['\\Als-filer\physdata\matlab\', AD.SubMachine, 'Data', filesep, ModeName, filesep];
    else
        AD.Directory.DataRoot = ['/home/als/physdata/matlab/', AD.SubMachine, 'Data', filesep, ModeName, filesep];
    end
    % Data Archive Directories
    AD.Directory.BPMData        = [AD.Directory.DataRoot 'BPM', filesep];
    AD.Directory.TuneData       = [AD.Directory.DataRoot 'Tune', filesep];
    AD.Directory.ChroData       = [AD.Directory.DataRoot 'Chromaticity', filesep];
    AD.Directory.DispData       = [AD.Directory.DataRoot 'Dispersion', filesep];
    AD.Directory.ConfigData     = [AD.Directory.DataRoot 'MachineConfig', filesep];
    % Response Matrix Directories
    AD.Directory.BPMResponse    = [AD.Directory.DataRoot 'Response', filesep, 'BPM', filesep];
    AD.Directory.TuneResponse   = [AD.Directory.DataRoot 'Response', filesep, 'Tune', filesep];
    AD.Directory.ChroResponse   = [AD.Directory.DataRoot 'Response', filesep, 'Chromaticity', filesep];
    AD.Directory.DispResponse   = [AD.Directory.DataRoot 'Response', filesep, 'Dispersion', filesep];
    AD.Directory.SkewResponse   = [AD.Directory.DataRoot 'Response', filesep, 'Skew', filesep];
    % If using the ALS filer, I'm assuming you want to be online
    switch2online;
    % Change defaults for LabCA if using it
    try
        if exist('lcaSetRetryCount','file')
            % read dummy pv to initialize labca
            % ChannelName = family2channel('BPMx');
            % lcaGet(family2channel(ChannelName(1,:));
            % Retry count
            RetryCountNew = 1000;  % Default: 599-old labca, 299-labca_2_1_beta
            RetryCount = lcaGetRetryCount;
            lcaSetRetryCount(RetryCountNew);
            if RetryCount ~= RetryCountNew
                fprintf('   Setting LabCA retry count to %d (was %d) (LabCA)\n', RetryCountNew, RetryCount);
            end
            % Timeout
            TimeoutNew = .005;  % Default: .05-old labca, .1-labca_2_1_beta
            Timeout = lcaGetTimeout;
            lcaSetTimeout(TimeoutNew);
            if abs(Timeout - TimeoutNew) > 1e-5
                fprintf('   Setting LabCA TimeOut to %f (was %f) (LabCA)\n', TimeoutNew, Timeout);
            end
            % To avoid UDF errors, set the WarnLevel to 4 (Default is 3)
            lcaSetSeverityWarnLevel(4);
            fprintf('   Setting lcaSetSeverityWarnLevel to 4 to avoid annoying UDF errors (LabCA).\n');
        end
    catch
        fprintf('   LabCA Timeout not set, need to run lcaSetRetryCount(1000), lcaSetTimeout(.01).\n');
    end
end
% Circumference
AD.Circumference = findspos(THERING,length(THERING)+1);
setad(AD);
% Updates the AT indices in the MiddleLayer with the present AT lattice
updateatindex;
% Set the model energy
setenergymodel(AD.Energy);
% Cavity and radiation
setcavity off;
setradiation off;
fprintf('   Radiation and cavities are off.  Use setradiation / setcavity to modify. \n');
% Momentum compaction factor
try
    %AD.MCF = 0.00137038;  % was 0.0013884;
    MCF = getmcf('Model');
    if isnan(MCF)
        AD.MCF = 0.00137038;  % was 0.0013884;
        fprintf('   Model alpha calculation failed, middlelayer alpha set to  %f\n', AD.MCF);
    else
        AD.MCF = MCF;
        fprintf('   Middlelayer alpha set to %f (AT model).\n', AD.MCF);
    end
catch
    AD.MCF = 0.00137038;  % was 0.0013884;
    fprintf('   Model alpha calculation failed, middlelayer alpha set to  %f\n', AD.MCF);
end
setad(AD);
% Add Gain & Offsets for magnet family
fprintf('   Magnet gains set based on the production lattice settings.\n');
setgainsandoffsets;
%%%%%%%%%%%%%%%%%%%%%%
% Final mode changes %
%%%%%%%%%%%%%%%%%%%%%%
if any(ModeNumber == [1 2 3])
    % User mode - 1.9 GeV, High Tune
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Add LOCO Parameters to AO and AT-Model %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %     'Nominal'    - Sets nominal gains (1) / rolls (0) to the model.
    %     'SetGains'   - Set gains/coupling from a LOCO file.
    %     'SetModel'   - Set the model from a LOCO file.  But it only changes
    %                    the part of the model that does not get corrected
    %                    in 'Symmetrize' (also does a SetGains).
    %     'LOCO2Model' - Set the model from a LOCO file (also does a SetGains).
    %                    This sets all lattice machines fit in the LOCO run to the model.
    %
    % Basically, use 'SetGains' or 'SetModel' if the LOCO run was applied to the accelerator
    %            use 'LOCO2Model' if the LOCO run was made after the final setup
    % Store the LOCO file in the opsdata directory
    %AD.OpsData.LOCOFile = [getfamilydata('Directory','OpsData'),'LOCO_Production_72SkewQuads_1Bend'];
    AD.OpsData.LOCOFile = [getfamilydata('Directory','OpsData'),'LOCO_Production_72SkewQuads_4Bends'];
    setad(AD);
    try
        %setlocodata('SetGains', AD.OpsData.LOCOFile);
        %setlocodata('SetModel', AD.OpsData.LOCOFile);
        setlocodata('LOCO2Model', AD.OpsData.LOCOFile);
        %buildramptable;
        % setsp('SQSF', 0, 'Simulator', 'Physics');
        % setsp('SQSD', 0, 'Simulator', 'Physics');
        %
        % setsp('HCM', 0, 'Simulator', 'Physics');
        % setsp('VCM', 0, 'Simulator', 'Physics');
    catch
        fprintf('\n%s\n\n', lasterr);
        fprintf('   WARNING: there was a problem calibrating the model based on LOCO file %s.\n', AD.OpsData.LOCOFile);
    end
elseif ModeNumber == 4
    % 1.9 GeV, Low Tune
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Add LOCO Parameters to AO and AT-Model %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    %setlocodata('Nominal');
    %LocoFileDirectory = getfamilydata('Directory','OpsData');
    %setlocodata('SetModel',[LocoFileDirectory,'LocoData']);
    %setsp('SQSF', 0, 'Simulator', 'Physics');
    %setsp('SQSD', 0, 'Simulator', 'Physics');
    %setsp('HCM',  0, 'Simulator', 'Physics');
    %setsp('VCM',  0, 'Simulator', 'Physics');
elseif ModeNumber == 5
    % 1.9 GeV, 2-Bunch
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Add LOCO Parameters to AO and AT-Model %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    LocoFileDirectory = getfamilydata('Directory','OpsData');
    %setlocodata('SetModel',[LocoFileDirectory,'LocoData_PostSymmetrize']);
    setlocodata('SetModel',[LocoFileDirectory,'LocoData']);
    %buildramptable;
    %setsp('SQSF', 0, 'Simulator', 'Physics');
    %setsp('SQSD', 0, 'Simulator', 'Physics');
    %setsp('HCM',  0, 'Simulator', 'Physics');
    %setsp('VCM',  0, 'Simulator', 'Physics');
elseif ModeNumber == 6
    % 1.5 GeV, High Tune
    % Hysteresis loop files: 1.5 GeV modes use the 1.9 High Tune upper lattice
    AD = getad;
    AD.OpsData.HysteresisLoopUpperLattice = [MMLROOT, 'machine', filesep, MachineName, 'opsdata', filesep, 'HighTune', filesep, 'GoldenConfig_HighTune'];
    setad(AD);
    %SP = getinjectionlattice;
    %SP = rmfield(SP, 'BEND');
    %setmachineconfig(SP, 'Simulator');
    % Set energy in the model
    setenergymodel(1.522);
    setfamilydata(1.522, 'Energy');
    %setsp('SQSF', 0, 'Simulator', 'Physics');
    %setsp('SQSD', 0, 'Simulator', 'Physics');
    setsp('HCM', 0, 'Simulator', 'Physics');
    setsp('VCM', 0, 'Simulator', 'Physics');
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Add LOCO Parameters to AO and AT-Model %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    LocoFileDirectory = getfamilydata('Directory','OpsData');
    %setlocodata('SetModel',[LocoFileDirectory,'LocoData_PostSymmetrize']);
    %setlocodata('SetModel',[LocoFileDirectory,'LocoData']);
    %buildramptable;
elseif ModeNumber == 7
    % Isochronous Sections
    % Hysteresis loop files: 1.5 GeV modes use the 1.9 High Tune upper lattice
    AD = getad;
    AD.OpsData.HysteresisLoopUpperLattice = [MMLROOT, 'machine', filesep, MachineName, 'opsdata', filesep, 'HighTune', filesep, 'GoldenConfig_HighTune'];
    setad(AD);
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Add LOCO Parameters to AO and AT-Model %
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % Change the response matrix kicks
    % Start with nominal gains
    setlocodata('Nominal');
    AO = getao;
    AO.HCM.Setpoint.DeltaRespMat = physics2hw('HCM','Setpoint', .15e-3 / 3 / 1, AO.HCM.DeviceList);
    AO.VCM.Setpoint.DeltaRespMat = physics2hw('VCM','Setpoint', .15e-3 / 3 / 2, AO.VCM.DeviceList);
    %AO.HCM.Setpoint.DeltaRespMat = AO.HCM.Setpoint.DeltaRespMat/4;
    %AO.VCM.Setpoint.DeltaRespMat = AO.VCM.Setpoint.DeltaRespMat/4;
    setao(AO);
    setfamilydata(200e-6,'DeltaRFDisp');
    % Set the gains from LOCO data
    LocoFileDirectory = getfamilydata('Directory','OpsData');
    setlocodata('SetGains',[LocoFileDirectory,'LocoData_IsochronousSections']);
    %     %setenergy(1.522,'Simulator');
    %     %setsp('BEND', gev2bend(1.522), 'Simulator');
    %     SP = getinjectionlattice;
    %     SP = rmfield(SP, 'BEND');
    % Set energy in the model
    setenergymodel(1.522);
    setfamilydata(1.522, 'Energy');
    %     setmachineconfig(SP, 'Simulator');
    %
    %     %setsp('SQSF', 0, 'Simulator', 'Physics');
    %     %setsp('SQSD', 0, 'Simulator', 'Physics');
    %     setsp('HCM', 0, 'Simulator', 'Physics');
    %     setsp('VCM', 0, 'Simulator', 'Physics');
elseif ModeNumber == 101
    % Model mode
    % Activate all HCMs
    Status = getfamilydata('HCM', 'Status');
    setfamilydata(ones(size(Status)), 'HCM', 'Status');
    % Set gains, offsets, and golden values
    setlocodata('Nominal');
    setfamilydata(0,'BPMx','Offset');
    setfamilydata(0,'BPMy','Offset');
    setfamilydata(0,'BPMx','Golden');
    setfamilydata(0,'BPMy','Golden');
    setfamilydata(0,'TuneDelay');
    setsp('SQSF', 0, 'Simulator', 'Physics');
    setsp('SQSD', 0, 'Simulator', 'Physics');
    setsp('HCM',  0, 'Simulator', 'Physics');
    setsp('VCM',  0, 'Simulator', 'Physics');
    % Default to simulator mode
    switch2sim;
elseif ModeNumber == 999
    % Greg's mode
    % SP = getproductionlattice;
    % SP = rmfield(SP, 'BEND');
    % SP = rmfield(SP, 'RF');
    % SP = rmfield(SP, 'HCMCHICANE');
    % SP = rmfield(SP, 'VCMCHICANE');
    % SP = rmfield(SP, 'HCMCHICANEM');
    % setmachineconfig(SP, 'Simulator');
elseif ModeNumber == 200
    % Walter's mode
    LocoFileDirectory = getfamilydata('Directory','OpsData');
    setlocodata('SetGains',[LocoFileDirectory,'LocoData']);
else
    setlocodata('Nominal');
    %LocoFileDirectory = getfamilydata('Directory','OpsData');
    %setlocodata('SetModel',[LocoFileDirectory,'LocoData_PostSymmetrize']);
    %setlocodata('SetModel',[LocoFileDirectory,'LocoData']);
end
% Build a new ramp table to force the present AT-model
% to be matched to the production and injection lattice files
%buildramptable;
fprintf('   Remember to run buildramptable if the production and/or injection\n');
fprintf('   lattice files have changed or if the AT lattice has changed.\n');
fprintf('   Middlelayer setup for operational mode: %s\n', AD.OperationalMode);
function BuildOffsetAndGoldenOrbits
%  2005-07-27 Changed the [5 11] & [5 12] offset and golden orbits to values during a user run. (GJP)
%             The offsets were zero and the golden values were:
%             5  11   -2.371746    0.318056
%             5  12   -1.915190    0.482681
%
%             The golden orbit agreement with the old middle layer is not as good as
%             it needs to be.  For instance, [6 1] horizontal is .67 new and 1.016 old.
%
%  2006-01-06 New offsets measured.  The large difference in location 4 and 7 is due to new buttons.
%
% Note: you can view this by >> help setoperationalmode>BuildOffsetAndGoldenOrbits
%                           2007-06-15           2007-01-06       2005-05-12
%      DeviceList        Xnew      Ynew      Xold      Yold     Xoldold   Yoldold
Offset = [
    1.0000    2.0000   -0.1540    1.0386   -0.3029    0.9601   -0.3332    0.9621
    1.0000    3.0000   -0.1214   -0.3793   -0.0804   -0.1250   -0.0213   -0.1887
    1.0000    4.0000    0.1899   -0.2022    0.6410   -0.2695    0.6410   -0.7228
    1.0000    5.0000       NaN       NaN   -0.3117    1.2317   -0.3117    1.2317
    1.0000    6.0000       NaN       NaN    0.2868    0.1347    0.2868    0.1347
    1.0000    7.0000   -0.0219   -0.0720    0.1294   -0.3856    0.1294    0.2557
    1.0000    8.0000   -0.1808   -0.2673   -0.2606   -0.3423   -0.2235   -0.1922
    1.0000    9.0000    0.0986    0.2805   -0.0144    0.3451   -0.0639    0.3583
    1.0000   10.0000       NaN       NaN    1.4372   -0.1518    1.4372   -0.1518
    2.0000    1.0000       NaN       NaN    0.3365    0.0489    0.3365    0.0489
    2.0000    2.0000    0.3321   -0.6269    0.3349   -0.4719    0.3029   -0.4988
    2.0000    3.0000    0.2252    0.2625    0.3260    0.2452    0.2920    0.1946
    2.0000    4.0000    0.0382   -0.1314    0.3743   -0.1043    0.3743    0.5221
    2.0000    5.0000       NaN       NaN   -0.0128   -0.0542   -0.0128   -0.0542
    2.0000    6.0000       NaN       NaN    1.0025   -1.0075    1.0025   -1.0075
    2.0000    7.0000    0.1653   -0.2635   -0.0173   -0.2703   -0.0173    0.5229
    2.0000    8.0000    0.0736   -0.3550    0.1902   -0.2211    0.2433   -0.1423
    2.0000    9.0000   -0.0113    0.3960   -0.2460    0.3486   -0.1620    0.2160
    3.0000    2.0000   -0.2045    0.1067   -0.3086    0.0952   -0.2826    0.1080
    3.0000    3.0000    0.2871    0.2895    0.3677    0.3745    0.3313    0.3497
    3.0000    4.0000    0.3965   -0.3447   -0.3568   -0.8973   -0.3568    0.2155
    3.0000    5.0000       NaN       NaN   -0.0402    0.0603   -0.0402    0.0603
    3.0000    6.0000       NaN       NaN    0.2722    0.0824    0.2722    0.0824
    3.0000    7.0000    0.7024   -0.1234    0.3131   -0.3190    0.3131    0.7647
    3.0000    8.0000   -0.0985    0.4559   -0.1004    0.5151    0.0275    0.5267
    3.0000    9.0000    0.5186   -0.0231    0.4228    0.1727    0.4782    0.0919
    3.0000   10.0000       NaN       NaN    0.7001    0.2774    0.7001    0.2774
    3.0000   11.0000       NaN       NaN   -0.5243   -0.4578   -0.5243   -0.4578
    3.0000   12.0000       NaN       NaN   -0.1391    0.0454   -0.1391    0.0454
    4.0000    1.0000       NaN       NaN    0.9000    0.8040    0.9000    0.8040
    4.0000    2.0000   -0.2236    0.9806   -0.2389    0.9517   -0.2736    1.0024
    4.0000    3.0000    0.6484   -0.3606    0.5399   -0.3708    0.5481   -0.3316
    4.0000    4.0000    0.2514    0.2447   -0.6150    0.4217   -0.6150    0.2945
    4.0000    5.0000   -0.0899   -0.1984    0.1066   -0.1455   -0.1270    0.1668
    4.0000    6.0000    0.9420    0.4485    1.0549    0.5268    0.8027    0.7899
    4.0000    7.0000   -0.0272   -0.8070   -0.5092   -0.2730   -0.5092    0.1823
    4.0000    8.0000   -0.6642    0.3888   -0.6119    0.6313   -0.4890    0.5291
    4.0000    9.0000   -0.6090   -0.3532   -0.5624   -0.3060   -0.4998   -0.3415
    4.0000   10.0000       NaN       NaN   -0.4352    1.3991   -0.4352    1.3991
    5.0000    1.0000       NaN       NaN    0.6527    0.2707    0.6527    0.2707
    5.0000    2.0000   -0.0489    0.6029    0.0368    0.6351   -0.0318    0.6071
    5.0000    3.0000    0.1164    0.5500    0.2613    0.5279    0.1690    0.4812
    5.0000    4.0000   -0.0824    0.4140   -0.2422    0.1545   -0.2422    0.6403
    5.0000    5.0000       NaN       NaN   -0.3649    0.5744   -0.3649    0.5744
    5.0000    6.0000       NaN       NaN   -0.3961    0.5409   -0.3961    0.5409
    5.0000    7.0000   -0.2576   -0.8496    0.1861   -0.6341    0.1861    0.4875
    5.0000    8.0000   -0.5953    0.6480   -0.4308    0.6563   -0.4611    0.5928
    5.0000    9.0000    0.3942    0.7882    0.2031    0.9099    0.4392    0.7018
    5.0000   10.0000       NaN       NaN    0.4052    0.9371    0.4052    0.9371
    5.0000   11.0000       NaN       NaN    0.2860    0.4667    0.2860    0.4667
    5.0000   12.0000       NaN       NaN    0.7625    0.4750    0.7625    0.4750
    6.0000    1.0000       NaN       NaN   -0.1765    0.4277   -0.1765    0.4277
    6.0000    2.0000       NaN       NaN   -0.5470    0.1162   -0.4925    0.1608
    6.0000    3.0000    0.6580   -0.0962    0.5579   -0.0764    0.4926   -0.0228
    6.0000    4.0000    0.0950    0.2593    0.1200    0.1259    0.1200    0.9682
    6.0000    5.0000       NaN       NaN    0.0815   -0.2318    0.0815   -0.2318
    6.0000    6.0000       NaN       NaN   -0.5071    0.4360   -0.5071    0.4360
    6.0000    7.0000    0.3660   -0.1818   -0.0400   -0.3844   -0.0400    0.5079
    6.0000    8.0000   -0.0038    0.8238    0.0326    0.8366    0.0851    0.7527
    6.0000    9.0000   -0.3228    0.6993   -0.3196    0.7598   -0.2962    0.7587
    6.0000   10.0000       NaN       NaN    0.4473   -0.1545    0.4473   -0.1545
    7.0000    1.0000       NaN       NaN    0.6227    0.3264    0.6227    0.3264
    7.0000    2.0000   -0.1331    0.5823   -0.1306    0.5463   -0.1513    0.6347
    7.0000    3.0000    0.4716    0.6017    0.4098    0.6411    0.2288    0.5024
    7.0000    4.0000   -0.1470    0.3133   -0.2808    0.0358   -0.2808    0.5664
    7.0000    5.0000       NaN       NaN    0.2972    0.3924    0.2972    0.3924
    7.0000    6.0000       NaN       NaN   -0.1378    0.6702   -0.1378    0.6702
    7.0000    7.0000    0.0756    0.4459    0.0613    0.5088    0.0613    0.8434
    7.0000    8.0000   -0.1205    0.6658    0.0291    0.6676   -0.0196    0.6397
    7.0000    9.0000   -1.4073   -0.6661   -1.3782   -0.6406    0.1663    0.8314
    7.0000   10.0000       NaN       NaN    0.4593    0.2569    0.4593    0.2569
    8.0000    1.0000       NaN       NaN    0.2270    0.4960    0.2270    0.4960
    8.0000    2.0000   -0.1114    0.0405   -0.1231    0.0635   -0.1059    0.0297
    8.0000    3.0000    0.0862    1.4383    0.2116    1.3395    0.1908    1.0542
    8.0000    4.0000   -0.8683   -0.1559    0.0812   -0.5635    0.0812    0.6840
    8.0000    5.0000   -0.1542    0.3089   -0.1798    0.4131   -0.0830    0.6125
1000     8.0000    6.0000   -0.1743    0.3894   -0.1083    0.3420   -0.2474    0.8791
1001     8.0000    7.0000    0.6952    0.2835    0.3828    0.0519    0.3828    1.7969
1002     8.0000    8.0000   -0.2045    1.5762   -0.0812    1.6180   -0.0460    1.7202
1003     8.0000    9.0000   -1.8191   -0.3515   -1.6868   -0.3611   -1.5201   -0.3296
1004     8.0000   10.0000       NaN       NaN    0.5377   -0.0202    0.5377   -0.0202
1005     9.0000    1.0000       NaN       NaN    0.1161   -0.0240    0.1161   -0.0240
1006     9.0000    2.0000    1.4939    1.0447    1.7898    1.3374    0.4622    0.0734
1007     9.0000    3.0000    0.2326    0.4554    0.4083    0.5453    0.3516    0.4305
1008     9.0000    4.0000    0.1507    0.1189    0.1929   -0.3953    0.1929   -0.0981
1009     9.0000    5.0000       NaN       NaN   -0.3339    0.0797   -0.3339    0.0797
1010     9.0000    6.0000       NaN       NaN    0.1332   -0.0086    0.1332   -0.0086
1011     9.0000    7.0000    0.1835    0.6688    0.3534    0.5847    0.3534   -0.0021
1012     9.0000    8.0000    0.9189    0.2861    1.0863    0.2838    1.0286    0.2349
1013     9.0000    9.0000    0.7994    0.1987    0.9717    0.2159    0.8841    0.3314
1014     9.0000   10.0000       NaN       NaN    0.3272   -0.0581    0.3272   -0.0581
1015    10.0000    1.0000       NaN       NaN    0.4990    0.4044    0.4990    0.4044
1016    10.0000    2.0000    0.2261   -1.3064    0.3332   -1.2594    0.3588   -1.2207
1017    10.0000    3.0000   -0.1474    0.1990   -0.0812    0.2540    0.0714    0.1528
1018    10.0000    4.0000    0.0750    0.0609   -0.2064    0.1349   -0.2064    0.9781
1019    10.0000    5.0000       NaN       NaN   -0.5240    0.7222   -0.5240    0.7222
1020    10.0000    6.0000       NaN       NaN    0.4499    0.7862    0.4499    0.7862
1021    10.0000    7.0000    0.7592   -0.3641    0.3624   -0.2649    0.3624    0.5027
1022    10.0000    8.0000    0.5239    0.4681    0.7216    0.4301    0.7240    0.5122
1023    10.0000    9.0000    0.7038    0.4284    0.8702    0.4267    0.7826    0.4394
1024    10.0000   10.0000       NaN       NaN    0.4979   -0.1694    0.4979   -0.1694
1025    10.0000   11.0000       NaN       NaN    0.6556   -0.4005    0.6556   -0.4005
1026    10.0000   12.0000       NaN       NaN    0.7335   -0.2444    0.7335   -0.2444
1027    11.0000    1.0000       NaN       NaN    0.6382   -0.2382    0.6382   -0.2382
1028    11.0000    2.0000    0.7680   -0.0261    0.8438   -0.1025    0.8078   -0.1432
1029    11.0000    3.0000    0.0039    0.9302    0.1660    0.7432    0.2741    0.7241
1030    11.0000    4.0000    0.9590   -0.8161   -0.2598   -0.6969   -0.2598    0.3842
1031    11.0000    5.0000       NaN       NaN    0.0997    0.5364    0.0997    0.5364
1032    11.0000    6.0000       NaN       NaN    0.7115    0.5330    0.7115    0.5330
1033    11.0000    7.0000    0.5438   -0.2171    0.5070   -0.2151    0.5070    0.5740
1034    11.0000    8.0000    0.0503   -0.1881   -0.1281   -0.0106   -0.0038   -0.0113
1035    11.0000    9.0000    0.1907   -0.3105    0.0638   -0.5505   -0.0390   -0.5956
1036    11.0000   10.0000       NaN       NaN    0.7015   -0.2305    0.7015   -0.2305
1037    12.0000    1.0000       NaN       NaN   -0.2370   -0.4183   -0.2370   -0.4183
1038    12.0000    2.0000    0.1341   -1.2611    0.1376   -1.0998    0.3036   -1.1286
1039    12.0000    3.0000    0.1835   -0.0610    0.1754    0.0098    0.3032   -0.0342
1040    12.0000    4.0000    0.9430   -1.8453   -0.0736   -1.7539   -0.0736   -0.7078
1041    12.0000    5.0000   -0.7679   -0.6057   -0.6584   -0.5037   -0.6623   -0.1190
1042    12.0000    6.0000    0.3659   -0.0725    0.4741    0.0259    0.2439    0.4729
1043    12.0000    7.0000    0.2231   -0.1530   -0.0655   -0.1893   -0.0655   -0.0279
1044    12.0000    8.0000   -0.0373   -0.5285    0.0293   -0.1884   -0.0317   -0.1047
1045    12.0000    9.0000    0.2502   -0.2326    0.2470   -0.2015    0.2964   -0.0672];
1046
1047
1048 % iNoOffset = find(isnan(Offset(:,3)));
1049 % Offset(iNoOffset,3) = Offset(iNoOffset,5);
1050 %
1051 % iNoOffset = find(isnan(Offset(:,4)));
1052 % Offset(iNoOffset,4) = Offset(iNoOffset,6);
1053
1054
1055 % L = getfamilydata('Circumference');
1056 % figure;
1057 % subplot(2,2,1);
1058 % plot(getspos('BPMx', Offset(:,1:2)), [Offset(:,3) Offset(:,5) Offset(:,7)]);
1059 % ylabel('Horizontal [mm]');
1060 % xaxis([0 L]);
1061 % title('BPM Offset');
1062 %
1063 % subplot(2,2,2);
1064 % plot(getspos('BPMx', Offset(:,1:2)), [Offset(:,3)-Offset(:,5) Offset(:,3)-Offset(:,7)]);
1065 % ylabel('Horizontal Difference[mm]');
1066 % xaxis([0 L]);
1067 % title('BPM Offset');
1068 %
1069 % subplot(2,2,3);
1070 % plot(getspos('BPMy', Offset(:,1:2)), [Offset(:,4) Offset(:,6) Offset(:,8)]);
1071 % xlabel('BPM Position [meters]');
1072 % ylabel('Vertical [mm]');
1073 % xaxis([0 L]);
1074 %
1075 % subplot(2,2,4);
1076 % plot(getspos('BPMy', Offset(:,1:2)), [Offset(:,4)-Offset(:,6) Offset(:,4)-Offset(:,8)]);
1077 % xlabel('BPM Position [meters]');
1078 % ylabel('Vertical Difference [mm]');
1079 % xaxis([0 L]);
1080 %
1081 % addlabel(0,0,'Blue->2007-06-15   Green->2007-01-06   Red->2005-05-12');
1082 % addlabel(1,0,'Blue->(2007-06-15)-(2007-01-06)   Green->(2007-06-15)-(2005-05-12');
1083 % orient landscape
1084
1085
1086 %                          2007-06-15           2007-01-06
1087 %      DeviceList        Xnew      Ynew      Xold      Yold
1088 Golden = [
1089     1.0000    2.0000   -0.1164    1.1118   -0.0905    0.9270
1090     1.0000    3.0000   -0.3206   -0.2798   -0.1560   -0.1728
1091     1.0000    4.0000   -0.2206    0.1521   -0.0075   -0.0597
1092     1.0000    5.0000   -0.3231    0.6461   -0.3723    1.4058
1093     1.0000    6.0000    0.0209    0.0860    0.1567    0.3048 % three broken BPM cables fixed 7-23-07 - T.Scarvie Xold=0.0235, Yold=0.0991
1094     1.0000    7.0000   -0.6995    0.0287   -0.3353   -0.0694
1095     1.0000    8.0000   -0.2767   -0.7159   -0.3620   -0.4516
1096     1.0000    9.0000    0.1418    0.2101    0.2470    0.3653
1097     1.0000   10.0000   -1.2077    6.6760    1.4424   -0.2583
1098     2.0000    1.0000    0.1813    0.1247    0.3866   -0.1324
1099     2.0000    2.0000    0.3349   -0.5164    0.5617   -0.5684
1100     2.0000    3.0000    0.2200    0.4180    0.2629    0.1806
1101     2.0000    4.0000   -0.4819    0.0637   -0.1558    0.1406
1102     2.0000    5.0000    0.0124   -0.0094   -0.0634    0.1124
1103     2.0000    6.0000    0.8025   -0.9006    1.0105   -0.8803 % one broken BPM cable fixed 7-23-07 - T.Scarvie Xold=0.8090, Yold=-1.0049
1104     2.0000    7.0000   -0.4425    0.0289   -0.2299    0.2139
1105     2.0000    8.0000    0.0140   -0.5773    0.1148   -0.2362
1106     2.0000    9.0000   -0.0024    0.0779   -0.1342    0.0144
1107     3.0000    2.0000   -0.1644    0.0590   -0.1886    0.0369
1108     3.0000    3.0000    0.1728    0.0144    0.1387    0.1647
1109     3.0000    4.0000   -0.2566   -0.1845   -0.0843   -0.3441
1110     3.0000    5.0000   -0.2174   -0.2986   -0.1278   -0.1503
1111     3.0000    6.0000   -0.0498   -0.1577    0.0638    0.0034
1112     3.0000    7.0000    0.1708    0.0183    0.5082   -0.3062
1113     3.0000    8.0000   -0.0608    0.7555   -0.1019    0.6271
1114     3.0000    9.0000    0.5188   -0.0548    0.4280   -0.0073
1115     3.0000   10.0000    0.6894    0.1611    0.6763    0.1403
1116     3.0000   11.0000    0.0267   -0.3336    0.0245   -0.4586
1117     3.0000   12.0000    0.1506    0.0429    0.1478   -0.0725
1118     4.0000    1.0000    0.8131    0.0974    0.7799    0.0331
1119     4.0000    2.0000   -0.1926    0.8527   -0.2336    0.9362
1120     4.0000    3.0000    0.5383   -0.7841    0.5620   -0.4577
1121     4.0000    4.0000    0.1399    0.2569   -0.1769    0.5789
1122     4.0000    5.0000   -0.0579   -0.1571    0.1013   -0.0718
1123     4.0000    6.0000    0.6769    0.4766    1.0632    0.6690
1124     4.0000    7.0000   -0.3127   -0.1996    0.0751    0.3001
1125     4.0000    8.0000   -0.8090    0.2218   -0.6185    0.3929
1126     4.0000    9.0000   -0.5722   -0.3312   -0.5918   -0.4112
1127     4.0000   10.0000   -0.3650    1.1224   -0.4259    1.2825
1128     5.0000    1.0000    0.5914    0.2199    1.0252    0.1134
1129     5.0000    2.0000   -0.0654    0.7898    0.1353    0.6211
1130     5.0000    3.0000    0.0109    0.6031   -0.0297    0.4792
1131     5.0000    4.0000   -0.6197    0.3611   -0.7689    0.3487
1132     5.0000    5.0000   -0.2871    0.3102   -0.6357    0.7139
1133     5.0000    6.0000   -0.8664    0.2819   -0.2995    0.6825
1134     5.0000    7.0000   -1.4360   -0.1984   -0.2062   -0.1643
1135     5.0000    8.0000   -0.6783   -0.0500   -0.5811    0.4796
1136     5.0000    9.0000    0.4560    0.5540    0.2395    0.7904
1137     5.0000   10.0000    0.0030    1.0187   -0.0983    1.1972
1138     5.0000   11.0000    0.8074    0.6420    0.3662    0.2982
1139     5.0000   12.0000    1.2291    0.6390    0.8378    0.2751
1140     6.0000    1.0000    1.2242    0.3311    1.1062    0.3945
1141     6.0000    2.0000    0.7337   -0.6179   -0.4532    0.1640
1142     6.0000    3.0000    0.6009   -0.1658    0.4640   -0.2254
1143     6.0000    4.0000   -0.3989    0.4334    0.0279    0.4018
1144     6.0000    5.0000   -0.0950   -0.4062   -0.0122   -0.4458
1145     6.0000    6.0000   -0.3644    0.1094   -0.4341    0.3551
1146     6.0000    7.0000   -0.3061    0.2173    0.0505    0.0695
1147     6.0000    8.0000   -0.0087    0.6355    0.0724    0.6455
1148     6.0000    9.0000   -0.3327    0.7777   -0.2040    0.6862
1149     6.0000   10.0000    0.4036   -0.4307    0.5751   -0.3754
1150     7.0000    1.0000    0.7321    0.0467    0.9940    0.1602
1151     7.0000    2.0000   -0.0733    0.4845    0.1602    0.5734
1152     7.0000    3.0000    0.3613    0.2853    0.3448    0.5149
1153     7.0000    4.0000   -0.5473    0.3019   -0.2024    0.2997
1154     7.0000    5.0000    0.4386    0.3786    0.3256    0.4723
1155     7.0000    6.0000   -0.1010    0.7061   -0.2265    0.7548
1156     7.0000    7.0000   -0.4437    0.6924   -0.2314    0.4434
1157     7.0000    8.0000   -0.1459    0.8676    0.0055    0.7587
1158     7.0000    9.0000   -1.4295   -0.5051   -1.0471   -0.6419
1159     7.0000   10.0000    0.5307    0.0572    0.7784    0.0477
1160     8.0000    1.0000    0.1367    0.3429    0.4653    0.3253
1161     8.0000    2.0000   -0.1248    0.1270    0.2355    0.0610
1162     8.0000    3.0000    0.0487    0.9742    0.1225    1.0581
1163     8.0000    4.0000   -1.5810    0.0980   -1.2181   -0.2084
1164     8.0000    5.0000   -0.3341    0.2824   -0.2268    0.5857
1165     8.0000    6.0000   -0.3421    0.7272   -0.1818    0.8391
1166     8.0000    7.0000    0.3349    0.3401    0.5672   -0.0758
1167     8.0000    8.0000   -0.2651    1.4210   -0.0246    1.6463
1168     8.0000    9.0000   -1.8364   -0.4120   -1.5009   -0.4652
1169     8.0000   10.0000    0.2715   -0.2286    0.6915   -0.3086
1170     9.0000    1.0000   -0.0777   -0.0662    0.3128   -0.0750
1171     9.0000    2.0000    1.5025    1.2110    2.0458    1.3817
1172     9.0000    3.0000    0.1389    0.5968    0.3151    0.5734
1173     9.0000    4.0000   -0.3410    0.3957   -0.1206   -0.2816
1174     9.0000    5.0000   -1.2782    0.8355   -0.3879    0.1111
1175     9.0000    6.0000    0.1340   -0.0589    0.0292   -0.0051
1176     9.0000    7.0000   -0.3855    0.4947   -0.3161    0.4980
1177     9.0000    8.0000    0.9610    0.0456    1.0139    0.2976
1178     9.0000    9.0000    0.7791    0.0588    1.0325    0.3200
1179     9.0000   10.0000    0.0948   -0.0164    0.4193   -0.0683
1180    10.0000    1.0000    0.3913    0.4174    0.4968    0.1272
1181    10.0000    2.0000    0.2516   -1.2953    0.3301   -1.3297
1182    10.0000    3.0000   -0.1787    0.2017   -0.2107    0.0034
1183    10.0000    4.0000   -0.3542    0.3949   -0.2981    0.6957
1184    10.0000    5.0000   -0.5252    0.3975   -0.5290    0.7303
1185    10.0000    6.0000   -0.2114    0.3008    0.3664    0.6748
1186    10.0000    7.0000   -0.0283   -0.2467    0.4620   -0.1321
1187    10.0000    8.0000    0.4726    0.3341    0.6358    0.3907
1188    10.0000    9.0000    0.7135    0.3762    0.8666    0.3835
1189    10.0000   10.0000    0.6035   -0.1710    0.6846   -0.1846
1190    10.0000   11.0000    0.7857   -0.3919    0.7601   -0.3101
1191    10.0000   12.0000    0.9208   -0.3487    0.8949   -0.2490
1192    11.0000    1.0000    0.5366   -0.4139    0.5186   -0.2121
1193    11.0000    2.0000    0.8223   -0.1215    0.8820   -0.0889
1194    11.0000    3.0000   -0.0889    0.5780    0.1352    0.5922
1195    11.0000    4.0000    0.3019   -0.6016    0.4249   -0.4161
1196    11.0000    5.0000    0.0179    0.2657   -0.0124    0.8161
1197    11.0000    6.0000    0.6549    0.2317    0.6921    0.6852
1198    11.0000    7.0000    0.2079    0.2648    0.0476    0.2143
1199    11.0000    8.0000    0.0910   -0.1828   -0.0686   -0.1559
1200    11.0000    9.0000    0.2325   -0.0519    0.1918   -0.5955
1201    11.0000   10.0000    0.6873   -0.0136    0.7356   -0.3074
1202    12.0000    1.0000   -0.6645   -0.3193   -0.3790   -0.4959
1203    12.0000    2.0000    0.1340   -1.4477    0.3250   -1.1212
1204    12.0000    3.0000    0.1950   -0.4437    0.2516   -0.0820
1205    12.0000    4.0000    0.5128   -1.8074    0.5054   -1.7032
1206    12.0000    5.0000   -0.5833   -0.4367   -0.6323   -0.2853
1207    12.0000    6.0000    0.2588    0.1180    0.2759    0.3523
1208    12.0000    7.0000   -0.3140    0.3242   -0.2178    0.0293
1209    12.0000    8.0000    0.0463   -0.8258    0.0065   -0.9847
1210    12.0000    9.0000    0.2396   -0.2649    0.5101   -0.5973];
1211
1212
1213 % Golden = [
1214 %   1   2   -0.040511-0.05    1.006040-0.079 %adjusted values for (1 2,1 5,1 6,1 10,11 10,12 1,11 10,12 1,12 5,12 6,12 9) due to tightening BPM fittings 2-25-07, T.Scarvie
1215 %   1   3   -0.155995   -0.172802
1216 %   1   4   -0.007489   -0.059690
1217 %   1   5   -0.382271+0.01    1.420774-0.015
1218 %   1   6    0.132685+0.024    0.319805-0.015
1219 %   1   7   -0.335328   -0.069386
1220 %   1   8   -0.361984   -0.451644
1221 %   1   9    0.247050    0.365270
1222 %   1  10    1.448368-0.006   -0.186320-0.072
1223 %   2   1    0.386556   -0.132429
1224 %   2   2    0.561730   -0.568448
1225 %   2   3    0.262944    0.180594
1226 %   2   4   -0.155815    0.140550
1227 %   2   5   -0.063373    0.112443
1228 %   2   6    1.010452   -0.880251
1229 %   2   7   -0.229883    0.213915
1230 %   2   8    0.114837   -0.236195
1231 %   2   9   -0.134172    0.014436
1232 %   3   2   -0.188554    0.036926
1233 %   3   3    0.138737    0.164742
1234 %   3   4   -0.084294   -0.344108
1235 %   3   5   -0.127760   -0.150261
1236 %   3   6    0.063810    0.003429
1237 %   3   7    0.508240   -0.306222
1238 %   3   8   -0.101938    0.627142
1239 %   3   9    0.427999   -0.007273
1240 %   3  10    0.676310    0.140286
1241 %   3  11    0.024469   -0.458603
1242 %   3  12    0.147821   -0.072459
1243 %   4   1    0.779875    0.033131
1244 %   4   2   -0.233599    0.936216
1245 %   4   3    0.562033   -0.457749
1246 %   4   4   -0.176911    0.578941
1247 %   4   5    0.101312   -0.071837
1248 %   4   6    1.063168    0.668993
1249 %   4   7    0.075097    0.300069
1250 %   4   8   -0.618454    0.392932
1251 %   4   9   -0.591781   -0.411174
1252 %   4  10   -0.425909    1.282475
1253 %   5   1    1.025209    0.113385
1254 %   5   2    0.135306    0.621053
1255 %   5   3   -0.029729    0.479160
1256 %   5   4   -0.768940    0.348716
1257 %   5   5   -0.635675    0.713942
1258 %   5   6   -0.299507    0.682519
1259 %   5   7   -0.206233   -0.164313
1260 %   5   8   -0.581095    0.479630
1261 %   5   9    0.239507    0.790378
1262 %   5  10   -0.098328    1.197237
1263 %   5  11    0.366152    0.298180
1264 %   5  12    0.837822    0.275068
1265 %   6   1    1.106152    0.394482
1266 %   6   2   -0.453220    0.163968
1267 %   6   3    0.464006   -0.225373
1268 %   6   4    0.027866    0.401828
1269 %   6   5   -0.012178   -0.445797
1270 %   6   6   -0.434149    0.355110
1271 %   6   7    0.050542    0.069546
1272 %   6   8    0.072386    0.645455
1273 %   6   9   -0.204027    0.686178
1274 %   6  10    0.575066   -0.375350
1275 %   7   1    0.993970    0.160223
1276 %   7   2    0.160180    0.573360
1277 %   7   3    0.344765    0.514882
1278 %   7   4   -0.202377    0.299711
1279 %   7   5    0.325589    0.472323
1280 %   7   6   -0.226487    0.754825
1281 %   7   7   -0.231378    0.443379
1282 %   7   8    0.005455    0.758709
1283 %   7   9   -1.047132   -0.641851
1284 %   7  10    0.778378    0.047654
1285 %   8   1    0.465304    0.325339
1286 %   8   2    0.235478    0.060970
1287 %   8   3    0.122504    1.058132
1288 %   8   4   -1.218061   -0.208418
1289 %   8   5   -0.226804    0.585689
1290 %   8   6   -0.181759    0.839125
1291 %   8   7    0.567193   -0.075760
1292 %   8   8   -0.024555    1.646280
1293 %   8   9   -1.500939   -0.465201
1294 %   8  10    0.691539   -0.308552
1295 %   9   1    0.312845   -0.074984
1296 %   9   2    2.045828    1.381672
1297 %   9   3    0.315071    0.573403
1298 %   9   4   -0.120628   -0.281603
1299 %   9   5   -0.387893    0.111066
1300 %   9   6    0.029225   -0.005092
1301 %   9   7   -0.316135    0.498034
1302 %   9   8    1.013853    0.297556
1303 %   9   9    1.032522    0.320033
1304 %   9  10    0.419298   -0.068294
1305 %  10   1    0.496764    0.127194
1306 %  10   2    0.330079   -1.329703
1307 %  10   3   -0.210684    0.003378
1308 %  10   4   -0.298091    0.695728
1309 %  10   5   -0.528987    0.730280
1310 %  10   6    0.366418    0.674756
1311 %  10   7    0.462025   -0.132051
1312 %  10   8    0.635811    0.390677
1313 %  10   9    0.866625    0.383491
1314 %  10  10    0.684558   -0.184594
1315 %  10  11    0.760086   -0.310084
1316 %  10  12    0.894935   -0.249016
1317 %  11   1    0.518637   -0.212083
1318 %  11   2    0.881954   -0.088936
1319 %  11   3    0.135216    0.592178
1320 %  11   4    0.424927   -0.416077
1321 %  11   5   -0.012425    0.816148
1322 %  11   6    0.692062    0.685239
1323 %  11   7    0.047561    0.214277
1324 %  11   8   -0.068567   -0.155911
1325 %  11   9    0.191816   -0.595530
1326 %  11  10    0.770551-0.035   -0.363433+0.056
1327 %  12   1   -0.348044-0.031   -0.484946-0.011
1328 %  12   2    0.324973   -1.121244
1329 %  12   3    0.251555   -0.081986
1330 %  12   4    0.505429   -1.703241
1331 %  12   5   -0.620302-0.012   -0.268309-0.017
1332 %  12   6    0.243871+0.032    0.352266
1333 %  12   7   -0.217819    0.029310
1334 %  12   8    0.006538   -0.9847 %-0.133392 looks like this BPM took a jump - changed value to prevent orbit correction from distorting 12,9 orbit
1335 %  12   9    0.535114-0.025   -0.570344-0.027
1336 %  ];
1337
1338
1339 % Make the offset equal to the golden for BPMs without an offset measurement
1340 Dev = getbpmlist('BPMx','NoXoffset', 'IgnoreStatus');
1341 i = findrowindex(Dev, Offset(:,1:2));
1342 Offset(i,3) = Golden(i,3);
1343
1344 Dev = getbpmlist('BPMy','NoYoffset', 'IgnoreStatus');
1345 i = findrowindex(Dev, Offset(:,1:2));
1346 Offset(i,4) = Golden(i,4);
1347
1348 % Convert NaN to zeroes
1349 Offset(isnan(Offset(:,3)),3) = 0;
1350 Offset(isnan(Offset(:,4)),4) = 0;
1351
1352
1353
1354 % fprintf('%3d %3d  %10.6f  %10.6f\n', [family2dev('BPMx'), getgolden('BPMx'), getgolden('BPMy')]');
1355 % Golden = [
1356 %     1   2   -0.2896      0.9742    %-0.0318      0.5181
1357 %     1   3   -0.152378   -0.241254  %-0.152484   -0.241162
1358 %     1   4    0.579553   -0.643002  % 0.579841   -0.643067
1359 %     1   5   -0.2628      1.1619    %-0.264224    1.161546
1360 %     1   6    0.3215      0.2230    % 0.323280    0.223281
1361 %     1   7    0.083640    0.196757  % 0.082737    0.196420
1362 %     1   8   -0.368952   -0.196831  %-0.368819   -0.196855
1363 %     1   9   -0.003805    0.407082  %-0.003357    0.406456
1364 %     1  10    1.3079     -0.1676    % 1.309478   -0.167377
1365 %     2   1    0.1588      0.1513    % 0.160261    0.151036
1366 %     2   2    0.344356   -0.520547  % 0.345754   -0.518623
1367 %     2   3    0.187703    0.164975  % 0.187703    0.166062
1368 %     2   4    0.352522    0.222951  % 0.351916    0.223096
1369 %     2   5   -0.0208      0.1188    %-0.019400    0.119447
1370 %     2   6    1.0050     -0.9880    % 1.007835   -0.988796
1371 %     2   7   -0.030978    0.423587  %-0.030932    0.423312
1372 %     2   8    0.133789   -0.6375    % 0.133789   -0.027414  % 0.135450   -0.027403
1373 %     2   9   -0.2203     -0.1107    %-0.1255     -0.0075
1374 %     3   2   -0.2273      0.1911    %-0.2273      0.1911
1375 %     3   3    0.165441    0.436316  % 0.165322    0.434830
1376 %     3   4   -0.343977    0.091995  %-0.344303    0.091896
1377 %     3   5    0.0739     -0.0736    %-0.051844   -0.073605
1378 %     3   6    0.2514      0.0204    % 0.6153      0.1983    % 0.614787    0.197967
1379 %     3   7    0.304507    0.697537  % 0.305512    0.697387
1380 %     3   8   -0.069038    0.528654  %-0.069111    0.528689
1381 %     3   9    0.517497    0.228419  % 0.516663    0.229043
1382 %     3  10    0.7444      0.2539    % 0.744410    0.253550
1383 %     3  11    0.0840     -0.3383    % 0.082091   -0.337858
1384 %     3  12    0.2215      0.0236    % 0.3156     -0.1570    % 0.313468   -0.156351
1385 %     4   1    0.8042      0.2195    % 0.803902    0.219844
1386 %     4   2   -0.240661    0.988501  %-0.242393    0.988339
1387 %     4   3    0.454354   -0.226890  % 0.453473   -0.226213
1388 %     4   4   -0.601477    0.102367  %-0.602129    0.102499
1389 %     4   5   -0.2014     -0.0041    %-0.202549   -0.004284
1390 %     4   6    0.8830      0.7256    % 0.882781    0.725510
1391 %     4   7   -0.387219    0.086077  %-0.587016    0.426245
1392 %     4   8   -0.545459    0.480851  %-0.547100    0.420096
1393 %     4   9   -0.479635   -0.288631  %-0.480664   -0.288543
1394 %     4  10   -0.4402      1.3105    %-0.440489    1.310593
1395 %     5   1    0.8685      0.1611    % 0.868568    0.161346
1396 %     5   2    0.021439    0.674611  % 0.021244    0.674683
1397 %     5   3    0.047640    0.440063  % 0.047743    0.439180
1398 %     5   4    0.190253    0.186037  % 0.190435    0.186583
1399 %     5   5   -0.3593      0.5678    %-0.359901    0.567948
1400 %     5   6   -0.3847      0.5690    %-0.383517    0.569024
1401 %     5   7    0.171261    0.457279  % 0.170336    0.455384
1402 %     5   8   -0.519706    0.591800  %-0.519345    0.591021
1403 %     5   9    0.465190    0.700225  % 0.465078    0.700237
1404 %     5  10   -0.2465      1.3429    %-0.2465      1.3429
1405 %     5  11    0.2855      0.4594    % 0.2855      0.4594
1406 %     5  12    0.7634      0.4516    % 0.7634      0.4516
1407 %     6   1    1.0160      0.5698    % 1.0160      0.5698
1408 %     6   2   -0.476022    0.231231  %-0.472465    0.231270
1409 %     6   3    0.397318    0.004102  % 0.398645    0.004417
1410 %     6   4    0.094072    0.862693  % 0.093460    0.862800
1411 %     6   5    0.0295     -0.2916    % 0.030714   -0.291520
1412 %     6   6   -0.4953      0.4451    %-0.494434    0.445159
1413 %     6   7   -0.089162    0.484128  %-0.089119    0.484474
1414 %     6   8    0.019608    0.759533  % 0.020663    0.759064
1415 %     6   9   -0.271687    0.768308  %-0.269637    0.767830
1416 %     6  10    0.4992     -0.4132    % 0.4992     -0.4132
1417 %     7   1    0.6804      0.2674    % 0.681440    0.267552
1418 %     7   2   -0.159098    0.658741  %-0.158171    0.658387
1419 %     7   3    0.228716    0.502839  % 0.228906    0.502007
1420 %     7   4   -0.295639    0.529897  %-0.295833    0.528664
1421 %     7   5    0.3000      0.3931    % 0.300789    0.393356
1422 %     7   6   -0.1463      0.6520    %-0.146880    0.651975
1423 %     7   7    0.060125    0.793967  % 0.060168    0.794162
1424 %     7   8   -0.086876    0.650777  %-0.087694    0.650625
1425 %     7   9   -1.325525   -0.647836  %-0.0869      0.6508
1426 %     7  10    0.4586      0.0892    % 0.458855    0.089469
1427 %     8   1    0.1198      0.3707    % 0.119673    0.370762
1428 %     8   2   -0.050046    0.096356  %-0.053612    0.096084
1429 %     8   3    0.073770    0.994688  % 0.071804    0.994555
1430 %     8   4    0.080614    0.692844  % 0.080223    0.692561
1431 %     8   5   -0.0318      0.5181    %-0.083167    0.645776
1432 %     8   6   -0.2839      0.9567    %-0.284171    0.956662
1433 %     8   7    0.391907    1.953947  % 0.391689    1.951550
1434 %     8   8   -0.140246    1.639606  %-0.140449    1.639649
1435 %     8   9   -1.502310   -0.207432  %-1.504134   -0.207754
1436 %     8  10    0.6255     -0.1201    % 0.625154   -0.120320
1437 %     9   1    0.1121     -0.0814    % 0.111942   -0.081206
1438 %     9   2    1.786463    1.335916  % 1.8313      1.3063
1439 %     9   3    0.215602    0.387373  % 0.214896    0.387126
1440 %     9   4    0.158785   -0.031891  % 0.159954   -0.031512
1441 %     9   5   -0.3181      0.0526    %-0.318482    0.051950
1442 %     9   6    0.1714     -0.0078    % 0.172962   -0.007577
1443 %     9   7    0.316691   -0.006804  % 0.316407   -0.006569
1444 %     9   8    0.880731    0.214732  % 0.880147    0.215338
1445 %     9   9    0.949231    0.310896  % 0.950156    0.311014
1446 %     9  10    0.2967     -0.0239    % 0.2967     -0.0239
1447 %     10   1    0.5232      0.1526    % 0.523894    0.152474
1448 %     10   2    0.437599   -1.142640  % 0.439782   -1.142138
1449 %     10   3   -0.113803    0.135020  %-0.113791    0.135007
1450 %     10   4   -0.199668    0.928557  %-0.199348    0.928702
1451 %     10   5   -0.5163      0.7165    %-0.514913    0.715788
1452 %     10   6    0.4600      0.7018    % 0.461318    0.702045
1453 %     10   7    0.344444    0.464383  % 0.344225    0.464196
1454 %     10   8    0.634820    0.560750  % 0.638157    0.563323
1455 %     10   9    0.829263    0.420337  % 0.828490    0.420643
1456 %     10  10    0.6593     -0.0171    % 0.659822   -0.017003
1457 %     10  11    0.6464     -0.1530    % 0.647259   -0.152731
1458 %     10  12    0.7818     -0.0988    % 0.782518   -0.098612
1459 %     11   1    0.5147     -0.0634    % 0.515164   -0.063664
1460 %     11   2    0.865802   -0.047039  % 0.865700   -0.047061
1461 %     11   3    0.129104    0.657485  % 0.129908    0.656617
1462 %     11   4   -0.245201    0.492669  %-0.246788    0.492489
1463 %     11   5    0.0853      0.7688    % 0.0853      0.5688 % Y raised when fittings were tightened    % 0.086654    0.568875
1464 %     11   6    0.7299      0.5752    % 0.729126    0.575185
1465 %     11   7    0.488272    0.561293  % 0.489058    0.561000
1466 %     11   8   -0.123974   -0.074137  %-0.124343   -0.072658
1467 %     11   9    0.009679   -0.533941  % 0.010739   -0.533760
1468 %     11  10    0.6304     -0.2759    % 0.630879   -0.275475
1469 %     12   1   -0.3235     -0.3509    %-0.323108   -0.351090
1470 %     12   2    0.315783   -1.050641  % 0.312953   -1.050924
1471 %     12   3    0.262078   -0.018282  % 0.261234   -0.018941
1472 %     12   4   -0.169038   -0.768199  %-0.168877   -0.767095
1473 %     12   5   -0.6095     -0.2389    %-0.610702   -0.238594
1474 %     12   6    0.2802      0.4385    % 0.279390    0.438482
1475 %     12   7   -0.146203   -0.021551  %-0.146113   -0.020954
1476 %     12   8   -0.133978   -0.059753  %-0.134942   -0.059710
1477 %     12   9    0.3541     -0.1237
1478 %     ];
1479
1480
1481 % Save the data
1482 AO = getao;
1483
1484
1485 % Offset orbits
1486 [i, iNotFound, iFoundList] = findrowindex(Offset(:,1:2), AO.BPMx.DeviceList);
1487 if ~isempty(iNotFound)
1488     fprintf('\n   Warning:  BPMx offsets are specified that are not in the family (setoperationalmode)\n');
1489 end
1490 if size(AO.BPMx.DeviceList,1) ~= length(i)
1491     fprintf('\n   Warning:  Not all the offsets in the BPMx family are being specified (setoperationalmode)\n');
1492 end
1493 AO.BPMx.Offset = zeros(size(AO.BPMx.DeviceList,1),1);
1494 AO.BPMx.Offset(i) = Offset(iFoundList,3);
1495
1496 [i, iNotFound, iFoundList] = findrowindex(Offset(:,1:2), AO.BPMy.DeviceList);
1497 if ~isempty(iNotFound)
1498     fprintf('\n   Warning:  BPMy offsets are specified that are not in the family (setoperationalmode)\n');
1499 end
1500 if size(AO.BPMy.DeviceList,1) ~= length(i)
1501     fprintf('\n   Warning:  Not all the offsets in the BPMy family are being specified (setoperationalmode)\n');
1502 end
1503 AO.BPMy.Offset = zeros(size(AO.BPMy.DeviceList,1),1);
1504 AO.BPMy.Offset(i) = Offset(iFoundList,4);
1505
1506
1507 % Golden orbits
1508 [i, iNotFound, iFoundList] = findrowindex(Golden(:,1:2), AO.BPMx.DeviceList);
1509 if ~isempty(iNotFound)
1510     fprintf('\n   Warning:  BPMx golden values are specified that are not in the family (setoperationalmode)\n');
1511 end
1512 if size(AO.BPMx.DeviceList,1) ~= length(i)
1513     fprintf('\n   Warning:  Not all the golden orbits in the BPMx family are being specified (setoperationalmode)\n');
1514 end
1515 AO.BPMx.Golden = zeros(size(AO.BPMx.DeviceList,1),1);
1516 AO.BPMx.Golden(i) = Golden(iFoundList,3);
1517
1518 [i, iNotFound, iFoundList] = findrowindex(Golden(:,1:2), AO.BPMy.DeviceList);
1519 if ~isempty(iNotFound)
1520     fprintf('\n   Warning:  BPMy golden values are specified that are not in the family (setoperationalmode)\n');
1521 end
1522 if size(AO.BPMy.DeviceList,1) ~= length(i)
1523     fprintf('\n   Warning:  Not all the golden orbits in the BPMy family are being specified (setoperationalmode)\n');
1524 end
1525 AO.BPMy.Golden = zeros(size(AO.BPMy.DeviceList,1),1);
1526 AO.BPMy.Golden(i) = Golden(iFoundList,4);
1527
1528 setao(AO);