Description of srcontrol5_with_BPM_timeconstant_reset
Home > ALS > StorageRing > srcontrol5_with_BPM_timeconstant_reset.m
srcontrol5_with_BPM_timeconstant_reset
PURPOSE
srcontrol5
SYNOPSIS
function srcontrol5(action, Input2, Input3)
DESCRIPTION
 srcontrol5
 Storage ring control program
 This program controls all storage ring magnets, performs orbit feedback and
 tune feedforward and helps to diagnose problems in routine user operation
 of the ALS storage ring. It includes a gui to simplify the use of this
 program.
 It was originally programmed by Greg Portmann (until December 2000) with input
 from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
 and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
 The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
 Christoph Steier, July 2002
 SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
 Tom Scarvie, April 2005
CROSS-REFERENCE INFORMATION
This function calls:
bend2gev BEND2GEV - Compute the energy based on the ramp tables
checksrmags CHECKSRMAGS - Check SR power supplies against a lattice file
checksrorbit ErrorNums =checksrorbit(Sector, BPMxtolerance [.015 mm], [BPMytolerance [.015 mm]])
gap2tune GAP2TUNE - Computes the vertical tune shift for a insertion device gap change.
gaplimit [GapMin, GapMax] = gaplimit(ID_Number);
getbpmtimeconstant GETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
getff function [FFEnableBM, FFEnableBC, GapEnableBM, GapEnableBC, Sector] = getff(Sector)
getid GETID - Get the insertion device position, velocity, run flag, and user requested gap
getsrstate [StateNumber, StateString] = getsrstate
set_alarmhandler_AHU_thresholds_inject function set_alarmhandler_AHU_thresholds_inject
set_alarmhandler_thresholds set_alarmhandler_thresholds
set_alarmhandler_thresholds_new set_alarmhandler_thresholds_new
setbpmtimeconstant SETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
setbumps SETBUMPS - Make a straight section bump
setff function setff(Sector, FFEnableBC, GapEnableBC)
setid SETID - Set the insertion device vertical gap
setsrstatechannels
shift2tune SHIFT2TUNE - Computes the horizontal tune shift for a EPU gap and horizontal shift
srcycle SRCYCLE - Storage ring cycle
srramp SRRAMP - Ramp the storage ring energy
write_goldenorbit_ffb function write_goldenorbit_ffb
write_goldenorbit_ffb_2planes WRITE_GOLDENORBIT_FFTB_2PLANES - Sets the BPM setpoints which are used by the fast feedback system
This function is called by:
SOURCE CODE
function srcontrol5(action, Input2, Input3)
% srcontrol5
% Storage ring control program
%
% This program controls all storage ring magnets, performs orbit feedback and
% tune feedforward and helps to diagnose problems in routine user operation
% of the ALS storage ring. It includes a gui to simplify the use of this
% program.
%
% It was originally programmed by Greg Portmann (until December 2000) with input
% from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
% and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
%
% The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
%
% Christoph Steier, July 2002
%
% SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
%
% Tom Scarvie, April 2005
% known bugs/problems (May 2001):
% - IDBPM averaging might be a bit too long for orbit feedback
%        solved after Superbend shutdown ... Instead of averaging, digital low pass filters are used
% - gap2tune does not give correct answers for wiggler and potentially other IDs -> orbit feedback
%        seems to be OK for other IDs, has been corrected for wiggler (fit to insertion device
%        compensation table)
% - chicanes do not work in orbit feedback
%        solved. One problem was that orbit response matrizes were mis-scaled by factor of two.
%        Second problem was different time constant of power supply control. Solved by moving controls
%        of center chicanes to cPCI (and magnets are fast, hysteresis free, aircore coils).
%        Center chicane in sector 4 is now routinely used in orbit feedback. Sector 11 to follow soon.
% - zero reading of ID gap dumps beam
%        solved in srcontrol5, still a problem in srcontrol5_hightune (but that routine has to be completely
%        rewritten because of all recent changes to srcontrol5, anyhow). For gap readings below the minimum
%        allowed gap for a device, the tune feedforward disables itself.
% - cycling of lattice causes frequent power supply failures
%        solved by changing the cycling procedure. 1.5 GeV operation is now on the upper hysteresis branch
%        as was the 1.9 GeV injection lattice before.
% - frequently stalled data in IDBPM readout
%        solved with new BPM readouts and digital filtering. Seems to have been a resolution problem
%        of the digital averaging algorithm.
% - magnet ramp tables are not in perfect agreement with magnetic measurements
%        Does not appear to be a serious problem. Superbends are slightly out of sync with other magnets,
%        but this does not cause any negative effects while ramping.
% - no good way to operate with injection at 1.5 GeV and storage energy below that
%        There now is a reasonable way to inject at 1.5 GeV and ramp down to lower storage energy. But
%        it has to be tested again after implementing new (and more) chicanes ...
% revision history
% 2001-05-10, Christoph Steier
% check whether readback from insertion device is significantly (more than 1 mm) below minimum
% gap, to avoid false zero readings of insertion device gaps to cause the tune feed forward
% to implement false huge correction (and dump the beam). If the insertion device gap readbacks
% gets more than 1 mm below the nominal minimum gap, the routine now assumes the insertion device
% to be open.
%
% 2001-08-30 and during Superbend commissioning, Christoph Steier, Tom Scarvie, Winni Decking
% various changes have been made to incorporate the Superbends and some other new equipment
% installed in the Superbend shutdown. This included some changes to programs being called by srcontrol
% (like srload, srsave, srcycle, srramp, ...). The main changes within srcontrol were in the orbit
% correction and slow orbit feedback routines (incorporating frequency feedback, ...)
%
% 2002-05-04, Christoph Steier
% added new IDBPMs, modified orbit feedback to use trim DACs, removed LSB toggling in vertical
% orbit feedback, ...
%
% 2002-07-29, T.Scarvie
% added check of CM trim currents to warn of problems that might rail the orbit feedback
%
% 2002-07-31, Christoph Steier
% increased the gain of the RF frequency feedback from 1/50 of the gain of the horizontal
% orbit feedback to 1/20. Reason was that the frequency feedback was reacting a bit too slow if all
% insertion device gaps are closed at once at high speed at the beginning of a fill.
%
% 2002-08-05, C.Steier, T.Scarvie
% Added conditional to reduce orbit feedback gain if running in two-bunch mode
%
% 2003-06-02, T.Scarvie
% Added loop inside orbit feedback to reset the SR11 chicane M1 and M2 motors every 20s to combat drift problem
%
% 2003-06-18, C. Steier
% Disabled loop to periodically reset chicane in SR11. Al Robb replaced power supply, seems to be no problem anymore.
%
% 2004-05-10, C. Steier
% The list of all BBPMs is now set up automatically be calling getlist('BBPMx'). This way, new BBPMs have to be added
% at fewer places in the software. It should now be sufficient to modify getlist and run the orbit response matrix
% rountine (getsmat) once to enable use of the new BBPMs.
%
% 2004-05-14, C. Steier
% Modified parameters for ramprate reduction (in srramp and here). Previous parameters were slightly too
% cautious. Increased initial slow ramprate to 0.4 A/s.
%
% 2004-05-14, C. Steier
% Incorporated insertion device compensation schemes for nu_y = 9.2 lattice.
%
% 2004-06-14, T.Scarvie
% Added controls for fast orbit feedback
%
% 2004-06-21, C. Steier
% Added tune feedforward (in the global tune compensation scheme for the nu_y=9.2 lattice) for the shift
% dependent tune shift of the EPUs, as well as a skew quadrupole feedforward for the EPU im sector 11
% (both only active in parallel mode so far).
%
% 2005-02-13, T.Scarvie
% Separated horizontal and vertical planes for setting Fast Feedback PIDs
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NOTES for conversion to new Middle Layer %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% We never use the gap and bump control flags - the radio buttons have been disabled -
%        should we try to keep the functionality?
%
% remove handle globals
% set(0,'showhiddenhandles','on'); what does this do?
% grampbsc -> should be handled by new srramp (which uses k-values)
% checksrmags
% checksrorbit(...)
% getdcct
% setbpmtimeconstant
% getsmatelements
% Chicane trims are now part of the corrector family
% getname('IDrunflag',...) family name change
% write_goldenorbit_ffb, write_goldenorbit_ffb2
% For the compiler
%#function goldenpage
%#function setoperationalmode
% Check if the AO exists
checkforao;
%%%%%%%%%%%%%%
% Initialize %
%%%%%%%%%%%%%%
global FEEDBACK_STOP_FLAG
SR_Mode = getfamilydata('OperationalMode');
SR_GEV = getfamilydata('Energy');
BSCramprate = getfamilydata('BSCRampRate');
if isnan(BSCramprate) | isempty(BSCramprate)
    BSCramprate = 0.4;
    setfamilydata(BSCramprate, 'BSCRampRate');
end
if nargin < 1
    action = 'Initialize';
end
if nargin < 2
    Input2 = 0;
end
if nargin < 3
    Input3 = 0;
end
if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
    FOFBcheckboxVal = 0;
else
    FOFBcheckboxVal = 1;
end
%%%%%%%%%%%%%%%%
% Main Program %
%%%%%%%%%%%%%%%%
switch(action)
    case 'StopOrbitFeedback'
        FEEDBACK_STOP_FLAG = 1;
    case 'Initialize'
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % GUI
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        ButtonWidth = 200;
        ButtonHeight  = 25;
        Offset1 = 8*25+12 + 47 + 25+25;
        Offset2 = 47+25+25;
        Offset3 = 45+25;
        Offset4 = 1;
        Offset5 = 30;
        FigWidth = ButtonWidth+6;
        FigHeight  = 3+9*(ButtonHeight+6)+24+Offset1;
        ButtonWidth = 200-6;
        % Change figure position
        set(0,'Units','pixels');
        p=get(0,'screensize');
        h0 = figure( ...
            'Color',[0.8 0.8 0.8], ...
            'HandleVisibility','Off', ...
            'Interruptible', 'on', ...
            'MenuBar','none', ...
            'Name','ALS SR CONTROL', ...
            'NumberTitle','off', ...
            'Units','pixels', ...
            'Position',[30 p(4)-FigHeight-40 FigWidth FigHeight+Offset5], ...
            'Resize','off', ...
            'Tag','SRCTRLFig1');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'FontWeight','Bold', ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+8*(ButtonHeight+3)+19+19+8+Offset1  ButtonWidth 20+Offset5], ...
            'Style','text', ...
            'String','', ...
            'Tag','SRCTRLTitle');
        % Frame Box I
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+3*(ButtonHeight+3)+Offset1-3+Offset5 ButtonWidth+6 7*ButtonHeight+18], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+9*(ButtonHeight+3)+Offset1  ButtonWidth 15+Offset5], ...
            'Style','text', ...
            'String','Lattice Setup Functions');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Cycle'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+8*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Cycle SR Lattice', ...
            'Tag','SRCTRLButton1');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Injection'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+7*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Injection', ...
            'Tag','SRCTRLButton2');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Production'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+6*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String',['Production'], ...
            'Tag','SRCTRLButton3');
        h1 = uicontrol('Parent',h0, ...
            'Callback',[...
            'fprintf(''\n'');' ...
            'disp([''   **********************************************'']);', ...
            'disp([''   **  Changing Storage Ring Operational Mode  **'']);', ...
            'disp([''   **********************************************'']);', ...
            'setoperationalmode;', ...
            'srcontrol5(''CheckInputs'');', ...
            'disp([''   ****************************'']);', ...
            'disp([''   **  Mode Change Complete  **'']);', ...
            'disp([''   ****************************'']);', ...
            'fprintf(''\n'');'], ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+5*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'Value',1, ...
            'String','Change Operational Mode', ...
            'Tag','SRCTRLButtonChangeMode');
        h1 = uicontrol(...
            'Parent',h0, ...
            'Callback', [...
            'srcontrol5(''CheckInputs'');',...
            'srcontrol5(''SRState'');'], ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+4*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Check For Problems', ...
            'Tag','SRCTRLButtonSRState');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs''); goldenpage;', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+3*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Golden Page', ...
            'Tag','SRCTRLButtonGoldenPage');
        % Frame Box II
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+9*(ButtonHeight+3)-29+Offset2+Offset5 ButtonWidth+6 2*ButtonHeight+15], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+10*(ButtonHeight+3)-10+Offset2 ButtonWidth .6*ButtonHeight+Offset5], ...
            'String','Global/Local Orbit Correction', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''OrbitCorrection'');', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+9*(ButtonHeight+3)-6+Offset2+Offset5 ButtonWidth ButtonHeight], ...
            'String','Correct Global Orbit w/ IDBPMs', ...
            'Tag','SRCTRLButtonOrbitCorrection');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''OrbitCorrectionSetup'',1);', ...
            'callback','srcontrol5(''OrbitCorrectionSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[6 9*(ButtonHeight+3)-22+Offset2+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Edit IDBPM, CM, & Local Bump Lists', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonOrbitCorrectionSetup');
        % Frame Box III
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 1*(ButtonHeight)+Offset3+Offset5-38 ButtonWidth+6 8*ButtonHeight+61], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+9*(ButtonHeight+3)+Offset3-25 ButtonWidth .55*ButtonHeight+Offset5], ...
            'String','Orbit Feedback', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+8*(ButtonHeight+3)+Offset3-18+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Slow Orbit Correction', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxSOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+7*(ButtonHeight+3)+Offset3-9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Fast Orbit Correction', ...
            'Style','checkbox', ...
            'Value',FOFBcheckboxVal,...
            'Tag','SRCTRLCheckboxFOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+6*(ButtonHeight+3)+Offset3+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct ID Tune Shift  ', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxTune');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+5*(ButtonHeight+3)+Offset3+9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct RF Frequency', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxRF');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''Feedback'');', ...
            'Enable','on', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[8 3+5*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Start FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStart');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''StopOrbitFeedback'');pause(0);', ...
            'Enable','off', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[.5*FigWidth+3 3+5*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Stop FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStop');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[14 4*(ButtonHeight)+Offset3+Offset5-3 ButtonWidth-14 .75*ButtonHeight], ...
            'String','Horizontal RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHorizontal');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[26 3+3.5*(ButtonHeight)+16+Offset3-25+Offset5 ButtonWidth-26 .75*ButtonHeight], ...
            'String','Vertical RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextVertical');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FeedbackSetup'',1);', ...
            'callback','srcontrol5(''FeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 3+3.5*(ButtonHeight)+.5+Offset3-25+Offset5 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit SOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFeedbackSetup');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','01 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB01');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','02 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB02');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','03 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB03');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','04 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB04');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','05 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB05');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','06 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB06');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','07 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB07');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','08 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB08');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','09 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB09');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','10 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB10');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','11 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB11');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','12 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB12');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FastFeedbackSetup'',1);', ...
            'callback','srcontrol5(''FastFeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 1*(ButtonHeight)+Offset3-3 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit FOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFastFeedbackSetup');
        % Frame Box IV
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+ButtonHeight+Offset4-14+Offset5 ButtonWidth+6 ButtonHeight+12], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+1.75*ButtonHeight+5+Offset4-21+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Storage Ring State', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHeader');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''CheckInputs'');', ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ForegroundColor','b', ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+ButtonHeight+6+3+2+Offset4-22+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','   ', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextInformation');
        % Frame Box "Close"
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 8 ButtonWidth+6 ButtonHeight+8], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'Callback','close(gcbf);', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 13 ButtonWidth ButtonHeight], ...
            'String','Close', ...
            'Tag','SRCTRLClose');
        % Update database channels
        setsrstatechannels;
        if nargout > 0
            fig = h0;
        end
    case 'Cycle'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        disp('   **************************');
        disp('   **  Storage Ring Cycle  **');
        disp('   **************************');
        a = clock; fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        BSCFlag = questdlg(sprintf('Cycle Superbend Magnets?'),'SR Cycle','Yes','No','No');
        %if strcmp(BSCFlag,'No')
        %    disp(['   ** Superbends will not be cycled. **']);
        %else
        %    disp(['   ** Superbends will be cycled during the second mini-cycle only. **']);
        %end
        ChicSQFlag = questdlg(sprintf('Cycle chicanes and skew quads and home motor chicanes?'),'SR Cycle','Yes','No','No');
        %if strcmp(ChicSQFlag,'No')
        %    disp(['   ** Chicanes and skew quads will not be cycled; motor chicanes will not be homed. **']);
        %else
        %    disp(['   ** Chicanes and skew quads will be cycled; motor chicanes will be homed. **']);
        %end
        StartFlag = questdlg(sprintf('Start %.1f GeV Cycle?',SR_GEV),'SR Cycle','Yes','No','No');
        if strcmp(StartFlag,'No')
            disp(['   ***************************']);
            disp(['   **    Cycle  Canceled    **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        end
        try
            if GapFlag
                % Make sure that the gaps are open with FF off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open.');
                    disp('   Opening all gaps at maximum speed.');
                    setff([], 1, 0);
                    disp('   Gap control disabled.');
                    disp('   Feed forward enabled.');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened.');
                    disp('   Feed forward and gap control disabled.');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled.');
                end
            else
                disp('   Feed forward and gap control disabled.');
            end
            setff([], 0, 0);
            pause(1);
            srcycle(BSCFlag, ChicSQFlag);
            setpv('SR_STATE',1);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Cycle failed due to error condition! \n\n');
            setpv('SR_STATE',-1);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp('   **********************************************');
            disp('   **  SR Cycle complete, ready for injection  **');
            disp('   **********************************************'); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp('   **********************************');
            disp('   **  Problem cycling SR lattice  **');
            disp('   **********************************'); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
    case 'Injection'
        AD = getad;
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            fprintf('   ***************************************************\n');
            fprintf('   **  Setup For %.2f GeV Injection (with ramping)  **\n', getfamilydata('InjectionEnergy'));
            fprintf('   ***************************************************\n');
            set_alarmhandler_AHU_thresholds_inject;
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',getfamilydata('InjectionEnergy')),'Injection Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            fprintf('   *************************************************\n');
            fprintf('   **  Setup For On Energy Injection at %.2f GeV  **\n', SR_GEV);
            fprintf('   *************************************************\n');
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',SR_GEV),'Injection Setup','Yes','Cancel','Cancel');
        end
        if strcmp(StartFlag,'Cancel')
            disp(['   ********************************']);
            disp(['   **  Injection Setup Canceled  **']);
            disp(['   ********************************']);
            set_alarmhandler_thresholds;
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                setff([],1,0);
                disp('   Gap control disabled');
                disp('   Feed forward enabled');
                pause(1);
                % Set IDs at max velocity w/ velocity profile off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    disp('   Opening all gaps');
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                end
                disp('   Gaps are open');
                disp('   Feed forward and gap control disabled');
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            if (AD.Energy-AD.InjectionEnergy) > 0.05
                % Ramp down to Injection Energy
                ErrorFlag = srramp('Injection');
                if ErrorFlag
                    error('Superbends over temperature.');
                end
                a = clock; fprintf('   %s %d:%d:%.0f\n\n',date, a(4), a(5), a(6));
            elseif (AD.Energy-AD.InjectionEnergy) < -0.05
                % first load injection lattice, then ramp to 1.9 GeV and back to 1.5 GeV to get onto same hysteresis branch
                srload('Injection');
                % load 1.9 GeV lattice
                tempfilename = sprintf('%s19nuy9prod.mat', getfamilydata('Directory','OpsData'));
                srload(tempfilename);
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                pause(5);
            end
            srload('Injection');
            setpv('SR_STATE',2);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Injection lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-2);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            if AD.Energy <= 1.5
                disp(['   *******************************************************************************']);
                disp(['   **  Function complete:  the storage ring is setup for injection at ',sprintf('%.2f',SR_GEV),' GeV  **']);
                disp(['   *******************************************************************************']);
                fprintf('\n');
            else
                fprintf('   **********************************************************************************************\n');
                fprintf('   **  Function complete:  the storage ring is setup for injection at %.2f GeV (upper branch)  **\n', getfamilydata('InjectionEnergy'));
                fprintf('   **********************************************************************************************\n');
                fprintf('\n');
            end
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   ************************************']);
            disp(['   **  Problem with injection setup  **']);
            disp(['   ************************************']);
            fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        %soundchord;
        setfamilydata(0.8, 'BSCRampRate');
    case 'Production'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        AD=getad;
        fprintf('\n');
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            disp('   ********************************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation (with ramping)  **',SR_GEV));
            disp('   ********************************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            disp('   *****************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation  **',SR_GEV));
            disp('   *****************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Yes','Cancel','Cancel');
        end
        if strcmp(StartFlag,'Cancel')
            disp(['   ***************************']);
            disp(['   **  User Setup Canceled  **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                % Make sure that the gaps are open
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open');
                    disp('   Opening all gaps at maximum speed');
                    setff([], 1, 0);
                    disp('   Gap control disabled');
                    disp('   Feed forward enabled');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened');
                    disp('   Feed forward and gap control disabled');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled');
                end
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            % Ramp up to the production lattice
            ErrorFlag = srramp('Production');
            if ErrorFlag
                error('Superbends over temperature.');
            end
            a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            srload('Production');
            if GapFlag
                setff([], 1, 0);
                disp('   Gap control disabled');
                disp('   Feed forward enable');
                pause(1);
                disp('   Insertion device velocity profile boolean control off');
                disp('   Closing all gaps at maximum speed');
                % Set IDs at max velocity w/ velocity profile off
                [Position, Velocity, RunFlag, UserGap] = getid;
                setid([], UserGap, maxsp('IDvel'), 1, 0, 1);
                % Turn velocity profile on
                disp('   Insertion device velocity profile boolean control is on');
                setid([], [], maxsp('IDvel'), 1, 1, 0);
                disp('   Gaps are closed');
                setff([4;7;8;9;10;12], 1, 1);
                setff(5, 1, 0);
                disp('   Gap control enabled (except sector 5 (W16))');
            end
            set_alarmhandler_thresholds_new;
            setpv('SR_STATE',3);
        catch
            fprintf('   %s \n', lasterr);
            fprintf('   User lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-3);
        end
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp(['   **************************************************************************']);
            disp(['   **  Function complete:  the storage ring is setup for users at ',sprintf('%.1f',SR_GEV),' GeV  **']);
            disp(['   **************************************************************************']); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   *************************************']);
            disp(['   **  Problem with production setup  **']);
            disp(['   *************************************']); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        setfamilydata(0.8, 'BSCRampRate');
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        %set lower setpoint limit for IVID to 7mm until beamline is scrubbed - 4-18-07 - T.Scarvie
        try
            scaput('SR06U___GDS1PS_AC00.DRVL',7)
        catch
            disp('  Trouble setting lower limit for IVID to 7mm!');
        end
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    case 'CheckInputs'
        SR_GEV = getfamilydata('Energy');
        AD=getad;
        setsrstatechannels;
        set(0,'showhiddenhandles','on');
        if AD.Energy > 1.55
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Down)']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users (Ramp Up)']);
        elseif AD.Energy < 1.45
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Up+cycle)']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV (Ramp Down)']);
        else
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV']);
        end
        set(findobj('Tag','SRCTRLTitle'),'String',SR_Mode);
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
        else
            set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
        end
        set(0,'showhiddenhandles','off');
1000
1001
1002     case 'SRState'
1003         NumErrors = 0;
1004         fprintf('\n');
1005         disp('   ***********************************');
1006         disp('   **  Checking Storage Ring State  **');
1007         disp('   ***********************************');
1008         a = clock;
1009         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1010
1011         %       FileName = getpv('SR_LATTICE_FILE','String');   % Last srload file name (in OLD MIDDLE LAYER nomenclature!!)
1012
1013         GeVnow = bend2gev;
1014         if GeVnow == getfamilydata('Energy')
1015             [ConfigSetpoint, ConfigMonitor, FileName] = getproductionlattice;
1016         elseif GeVnow == getfamilydata('InjectionEnergy')
1017             [ConfigSetpoint, ConfigMonitor, FileName] = getinjectionlattice;
1018         else
1019             FileName = '';
1020         end
1021
1022         [StateNumber, StateString] = getsrstate;
1023         fprintf('   Storage ring operational mode: %s\n', SR_Mode);
1024         if StateNumber < 0
1025             fprintf('   Storage ring state error: %s\n', StateString);
1026             NumErrors = NumErrors + 1;
1027         else
1028             fprintf('   Storage ring state: %s\n', StateString);
1029         end
1030         if StateNumber==0
1031             % Storage ring state unknown
1032             NumErrors = NumErrors + 1;
1033         elseif abs(StateNumber)==1 || abs(StateNumber)==2
1034             FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','InjectionFile') '.mat'];
1035             if ~strcmp(FileName, FileNameGoal)
1036                 fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','InjectionFile'), FileName);
1037                 NumErrors = NumErrors + 1;
1038             end
1039         else
1040             FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile') '.mat'];
1041             if ~strcmp(FileName, FileNameGoal)
1042                 fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','LatticeFile'), FileName);
1043                 NumErrors = NumErrors + 1;
1044             end
1045         end
1046
1047
1048         % Check all SR magnets
1049         if isempty(FileName)
1050             fprintf('   Goal setpoints will not be checked since the last lattice load is unknown.\n');
1051             NumErrors1 = checksrmags('');
1052         else
1053 %            NumErrors1 = checksrmags([getfamilydata('Directory','OpsData') FileName]);
1054             NumErrors1 = checksrmags(FileName);
1055         end
1056         if NumErrors1 == 0
1057             fprintf('   SR magnets power supplies are OK.\n');
1058         end
1059         NumErrors = NumErrors + NumErrors1;
1060
1061
1062         % Check RF frequency
1063         if isempty(FileName)
1064             fprintf('   RF frequency will not be checked since the last lattice load is unknown.\n');
1065         else
1066 %            load([getfamilydata('Directory','OpsData'), FileName]);
1067             load(FileName);
1068             [tmp, RFHPCounterPresent] = getrf;
1069             if abs(RFHPCounterPresent-ConfigSetpoint.RF.Setpoint.Data) > .002
1070                 NumErrors = NumErrors + 1;
1071                 fprintf('   RF frequency should be %f, presently it is %f MHz (as measured by the HP counter).\n', ConfigSetpoint.RF.Setpoint.Data, RFHPCounterPresent);
1072             else
1073                 fprintf('   RF frequency is OK (HP counter is %f MHz, at the time of the lattice save it was %f MHz).\n', RFHPCounterPresent, ConfigSetpoint.RF.Setpoint.Data);
1074             end
1075         end
1076
1077
1078         % Check for orbit problems
1079         if (StateNumber >= 3) & (getdcct > 2)   % Production lattice is loaded with beam in the machine
1080             Xtol = 0.070;
1081             Ytol = 0.010;
1082             NumErrors1 = checksrorbit([],Xtol,Ytol);
1083             if NumErrors1
1084                 fprintf('   SR orbit in the ID straight sections or at Bergoz BPMs deviates more than allowed from the golden orbit.\n');
1085             else
1086                 fprintf('   SR orbit in the ID straight sections and at Bergoz BPMs is OK.\n');
1087                 fprintf('   The orbit is within %.3f mm horizontally and %.3f mm vertically', Xtol, Ytol);
1088             end
1089             NumErrors = NumErrors + NumErrors1;
1090         else
1091             fprintf('   Storage ring orbit was not checked.\n');
1092         end
1093
1094
1095         a = clock;
1096         datestr1=date;
1097         fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
1098         if NumErrors
1099             disp('   *********************************');
1100             disp('   **  Storage Ring Has Problems  **');
1101             disp('   *********************************');
1102         else
1103             disp('   **********************************');
1104             disp('   **  Storage Ring Lattice is OK  **');
1105             disp('   **********************************');
1106         end
1107         fprintf('   \n');
1108
1109         set(0,'showhiddenhandles','on');
1110         [StateNumber, StateString] = getsrstate;
1111         if StateNumber >= 0
1112             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1113         else
1114             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1115         end
1116         set(0,'showhiddenhandles','off');
1117
1118
1119     case 'OrbitCorrection'
1120         fprintf('\n');
1121         fprintf('   *********************************\n');
1122         fprintf('   **  Starting Orbit Correction  **\n');
1123         fprintf('   *********************************\n');
1124         a = clock;
1125         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1126
1127         StartFlag = questdlg(sprintf('Start orbit correction, %.1f GeV?',SR_GEV),'Orbit Correction','Yes','No','No');
1128         if strcmp(StartFlag,'No')
1129             disp(['   ********************************']);
1130             disp(['   **  Orbit Correction Aborted  **']);
1131             disp(['   ********************************']);
1132             fprintf('\n');
1133             return
1134         end
1135
1136         if getdcct < 5     % Don't correct the orbit if the current is too small
1137             fprintf('   Orbit not corrected due to small current.\n');
1138             return
1139         end
1140
1141         if abs(SR_GEV-bend2gev(getpv('BEND',[1 1])))>  0.05     % Don't use this routine for the injection lattice
1142             fprintf('   This routine should only be used for the production energy: Correction aborted\n');
1143             return
1144         end
1145
1146         SR_STATE_OLD = scaget('SR_STATE');
1147         set(0,'showhiddenhandles','on');
1148         setpv('SR_STATE',4);
1149         [StateNumber, StateString] = getsrstate;
1150         if StateNumber >= 0
1151             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1152         else
1153             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1154         end
1155         set(0,'showhiddenhandles','off');
1156
1157
1158         try
1159                 % save current BPM timeconstant - will reset to this after correction
1160                 BPMtimeconstantOC = getbpmtimeconstant;
1161                 fprintf('   Current Bergoz BPM time constant is %.1fs\n', BPMtimeconstantOC);
1162
1163             % 2 Hz update rate on IDBPMs
1164             disp('   Bergoz BPM time constant set to 0.5s.')
1165             setbpmtimeconstant(0.5)
1166             pause(2);
1167
1168
1169             % Turn off feed forward
1170             fprintf('   Turning feed forward off.\n');
1171             [FFEnableBM, FFEnableBC] = getff;
1172             setff([], 0);
1173             scasleep(.2);
1174
1175
1176             % Get vectors
1177             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1178             LocalBumplist = FB.LocalBumplist;
1179
1180         catch
1181
1182             fprintf('   %s \n',lasterr);
1183             fprintf('   Orbit correction setup failed due to error condition! \n\n');
1184             setpv('SR_STATE',-4);
1185             set(0,'showhiddenhandles','on');
1186             [StateNumber, StateString] = getsrstate;
1187             if StateNumber >= 0
1188                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1189             else
1190                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1191             end
1192             set(0,'showhiddenhandles','off');
1193             return
1194
1195         end
1196
1197         iNotHCMChicane = find(FB.HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
1198         iHCMChicane = find(FB.HCMlist1(:,2) == 10);
1199         iNotVCMChicane = find(FB.VCMlist1(:,2) < 10);
1200         iVCMChicane = find(FB.VCMlist1(:,2) == 10);
1201
1202         fprintf('   Starting horizontal and vertical global orbit correction (SVD method).\n');
1203
1204         for iloop = 1:3
1205             try
1206                 % use the following to get corrector settings in OCS without setting them, so the values can be checked
1207                 FB.OCSx = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
1208                 FB.OCSy = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
1209                 if any(abs(FB.OCSx.CM.Delta(iNotHCMChicane)) > 5)
1210                   disp('   Orbit Correction is changing some horizontal corrector(s) > 5A!!');
1211                 end
1212                 if any(abs(FB.OCSy.CM.Delta(iNotVCMChicane)) > 5)
1213                   disp('   Orbit Correction is changing some vertical corrector(s) > 5A!!');
1214                 end
1215                 if any(abs(FB.OCSx.CM.Delta(iHCMChicane)) > 10)
1216                   disp('   Orbit Correction is changing some horizontal chicane corrector(s) > 10A!!');
1217                 end
1218                 if any(abs(FB.OCSy.CM.Delta(iVCMChicane)) > 10)
1219                   disp('   Orbit Correction is changing some vertical chicane corrector(s) > 10A!!');
1220                 end
1221
1222
1223                 % Correct horizontal orbit
1224                 FB.OCSx = setorbit(FB.OCSx,'NoDisplay');
1225                 % Correct vertical orbit
1226                 FB.OCSy = setorbit(FB.OCSy,'NoDisplay');
1227
1228
1229                 % Check for current in machine - stop orbit correction if DCCT < 5mA
1230                 if (getdcct < 4.5)
1231                     error('**There is less than 5mA in the machine! Stopping orbit correction.');
1232                 end
1233
1234                 % Check state of gaps - stop orbit correction if any are moving
1235                 GAPrunflag = getpv('ID','RunFlag');
1236                 if any(GAPrunflag-round(GAPrunflag))
1237                     error('**One or more of the gaps are moving! Stopping orbit correction.');
1238                 end
1239
1240                 x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
1241                 y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
1242                 fprintf('   %d. Horizontal RMS = %.3f mm\n', iloop, norm(x)/sqrt(length(x)));
1243                 fprintf('   %d.   Vertical RMS = %.3f mm\n', iloop, norm(y)/sqrt(length(y)));
1244
1245             catch
1246                 % fprintf('   %s \n',lasterr);
1247                 fprintf('   Orbit correction failed due to error condition!\n  Fix the problem, reload the lattice (srload), and try again.  \n\n');
1248                 setpv('SR_STATE',-4);
1249                 set(0,'showhiddenhandles','on');
1250                 [StateNumber, StateString] = getsrstate;
1251                 if StateNumber >= 0
1252                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1253                 else
1254                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1255                 end
1256                 set(0,'showhiddenhandles','off');
1257                 return
1258             end
1259         end
1260
1261
1262         % Set user bumps w/o sextupole correctors
1263         try
1264
1265             %turn up corrector speed here to quicken setting bumps
1266             HCMramprate = getpv('HCM', 'RampRate');
1267             VCMramprate = getpv('VCM', 'RampRate');
1268             setpv('HCM', 'RampRate', 10, [], 0);
1269             setpv('VCM', 'RampRate', 10, [], 0);
1270
1271             if ~isempty(LocalBumplist)
1272                 fprintf('   Setting local bumps in the straight sections.\n');
1273                 for loop = 1:size(LocalBumplist,1)
1274
1275                     % Check for current in machine - stop orbit correction if DCCT < 5mA
1276                     if (getdcct < 5)
1277                         error('** There is less than 5mA in the machine! Stopping local bumps.');
1278                     end
1279
1280                     % Check state of gaps - stop setting bumps if any are moving
1281                     GAPrunflag = getpv('ID','RunFlag');
1282                     if any(GAPrunflag-round(GAPrunflag))
1283                         error('** One or more of the gaps are moving! Stopping local bumps.');
1284                     end
1285
1286                     HCMoldsp = getsp('HCM', FB.HCMlist1);
1287                     VCMoldsp = getsp('VCM', FB.VCMlist1);
1288
1289                     if any(LocalBumplist(loop,1) == [4 6 11])
1290                         if LocalBumplist(loop,2) == 0
1291                             % Upstream bump
1292                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1293                             if isempty(iRemove)
1294                                 setbumps(LocalBumplist(loop,:), 1);
1295                             else
1296                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1297                             end
1298                         elseif LocalBumplist(loop,2) == 1
1299                             % Upstream bump
1300                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;],FB.OCSx.BPM.DeviceList);
1301                             if isempty(iRemove)
1302                                 setbumps(LocalBumplist(loop,:), 1);
1303                             else
1304                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1305                             end
1306                         else
1307                             % Downstream bump
1308                             [i, iRemove] = findrowindex([LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1309                             if isempty(iRemove)
1310                                 setbumps(LocalBumplist(loop,:), 1);
1311                             else
1312                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1313                             end
1314                         end
1315                     else
1316                         [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1317                         if isempty(iRemove)
1318                             setbumps(LocalBumplist(loop,:), 1);
1319                         else
1320                             fprintf('\n   BPMs missing from Sector %02d - skipping local bump for that sector.\n\n', LocalBumplist(loop,1));
1321                         end
1322                     end
1323
1324                     HCMnewsp = getsp('HCM', FB.HCMlist1);
1325                     VCMnewsp = getsp('VCM', FB.VCMlist1);
1326                     % Remove center chicane trim from corrector check
1327                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 5) | (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 10)
1328                         error('**Setbumps caused some corrector magnet currents to change by more than 5(Horiz)/10(Vert) A!');
1329                     end
1330                     % Now check center chicane trims
1331                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 10) | (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 15)
1332                         error('**Setbumps caused some chicane trim magnet currents to change by more than 10(Horiz)/15(Vert) A!');
1333                     end
1334                 end
1335             end
1336
1337             %restore corrector speeds
1338             setpv('HCM', 'RampRate', HCMramprate, [], 0);
1339             setpv('VCM', 'RampRate', VCMramprate, [], 0);
1340
1341         catch
1342             fprintf('   %s \n',lasterr);
1343             fprintf('   Setbumps failed due to error condition!  Fix the problem, reload the lattice (srload), and try again.\n\n');
1344             setpv('SR_STATE',-4);
1345             set(0,'showhiddenhandles','on');
1346             [StateNumber, StateString] = getsrstate;
1347             if StateNumber >= 0
1348                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1349             else
1350                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1351             end
1352             set(0,'showhiddenhandles','off');
1353             return
1354         end
1355
1356             % Reset BPM timeconstant to whatever it was before correction
1357             setbpmtimeconstant(BPMtimeconstantOC);
1358             fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1359
1360         % Turn feed forward back to it's original state
1361         if any(FFEnableBC)
1362             fprintf('   Turning feed forward back on.\n');
1363             setff([], FFEnableBC);
1364         end
1365
1366
1367         a = clock;
1368         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1369         [StateNumber, StateString] = getsrstate;
1370         set(0,'showhiddenhandles','on');
1371         if StateNumber >= 0
1372             setpv('SR_STATE',4.1);
1373             [StateNumber, StateString] = getsrstate;
1374             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1375             fprintf('   *********************************\n');
1376             fprintf('   **  Orbit Correction Complete  **\n');
1377             fprintf('   *********************************\n\n');
1378         else
1379             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1380             fprintf('   *************************************\n');
1381             fprintf('   **  Problem With Orbit Correction  **\n');
1382             fprintf('   *************************************\n\n');
1383         end
1384         set(0,'showhiddenhandles','off');
1385         pause(0);
1386
1387
1388     case 'OrbitCorrectionSetup'
1389         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
1390
1391         if InitFlag
1392             % Setup feedback elements
1393             % disp('Orbit correction condition: InitFlag=1 -- debugging message');
1394
1395             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1396             % Edit the following lists to change default configuration of Orbit Correction %
1397             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1398             hlist=[];vlist=[];
1399             for Sector =1:12
1400                 if Sector == 1
1401                     vlist = [vlist;Sector 2;Sector 4;Sector 5;Sector 8];
1402                     hlist = [hlist;Sector 2;Sector 7];
1403                 elseif Sector == 3
1404                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1405                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1406                 elseif Sector == 5
1407                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1408                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1409 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8]; %remove HCM and VCM(5,10) since corrector is not controlling starting 4-6-07
1410 %                     hlist = [hlist;Sector 2;Sector 7];
1411                 elseif Sector == 10
1412                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1413                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1414                 elseif Sector == 12
1415                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 7];
1416                     hlist = [hlist;Sector 2;Sector 7];
1417                 else
1418                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8];
1419                     hlist = [hlist;Sector 2;Sector 7];
1420                 end
1421             end
1422             HCMlist1 = hlist;
1423             VCMlist1 = vlist;
1424
1425             BPMlist1 = [
1426                 1 2
1427                 1 5
1428                 1 6
1429                 1 10
1430                 2 1
1431                 2 5
1432                 2 6
1433                 2 9
1434                 3 2
1435                 3 5
1436                 3 6
1437                 3 10
1438                 3 11
1439                 3 12
1440                 4 1
1441                 4 5
1442                 4 6
1443                 4 10
1444                 5 1
1445                 5 5
1446                 5 6
1447                 5 10
1448                 5 11
1449                 5 12
1450                 6 1
1451                 6 5
1452                 6 6
1453                 6 10
1454                 7 1
1455                 7 5
1456                 7 6
1457                 7 10
1458                 8 1
1459                 8 5
1460                 8 6
1461                 8 10
1462                 9 1
1463                 9 5
1464                 9 6
1465                 9 10
1466                 10 1
1467                 10 5
1468                 10 6
1469                 10 10
1470                 10 11
1471                 10 12
1472                 11 1
1473                 11 5
1474                 11 6
1475                 11 10
1476                 12 1
1477                 12 5
1478                 12 6
1479                 12 9];
1480
1481             % SVD orbit correction
1482             Xivec = [1:28];
1483             Yivec = [1:51];
1484
1485
1486             LocalBumplist = [
1487               % 1 1
1488               % 2 1
1489               % 3 1
1490                 4 1
1491               % 4 2
1492                 5 1
1493               % 6 1
1494               % 6 2
1495                 7 1
1496                 8 1
1497                 9 1
1498                 10 1
1499                 11 1
1500                 11 2
1501                 12 1
1502 ];
1503             %LocalBumplist = []
1504
1505             % initialize RFCorrFlag
1506             RFCorrFlag = 'Yes';
1507         else
1508
1509             % Get vectors
1510             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1511             BPMlist1 = FB.BPMlist1;
1512             HCMlist1 = FB.HCMlist1;
1513             VCMlist1 = FB.VCMlist1;
1514             Xivec = FB.Xivec;
1515             Yivec = FB.Yivec;
1516             LocalBumplist = FB.LocalBumplist;
1517             Xgoal = FB.Xgoal;
1518             Ygoal = FB.Ygoal;
1519             RFCorrFlag = FB.RFCorrFlag;
1520
1521             % Add button to change #ivectors, CMs, IDBPMs,
1522             EditFlag = 0;
1523             h_fig1 = figure;
1524             while EditFlag ~= 8
1525
1526                 % Sensitivity matrix
1527                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
1528                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
1529
1530                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1531                 % Can the call below work for setting FOFB RF parameter? %
1532                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1533                 if strcmpi(RFCorrFlag, 'Yes')
1534                     Sx = [Sx getdisp('BPMx',BPMlist1)];
1535                 end
1536
1537                 [Ux, SVx, Vx] = svd(Sx);
1538                 [Uy, SVy, Vy] = svd(Sy);
1539
1540
1541                 % Remove singular values greater than the actual number of singular values
1542                 i = find(Xivec>length(diag(SVx)));
1543                 if ~isempty(i)
1544                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
1545                     pause(0);
1546                     Xivec(i) = [];
1547                 end
1548                 i = find(Yivec>length(diag(SVy)));
1549                 if ~isempty(i)
1550                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
1551                     pause(0);
1552                     Yivec(i) = [];
1553                 end
1554
1555
1556                 Ax = Sx*Vx(:,Xivec);
1557                 Tx = inv(Ax'*Ax)*Ax';
1558
1559                 Ay = Sy*Vy(:,Yivec);
1560                 Ty = inv(Ay'*Ay)*Ay';
1561
1562
1563                 figure(h_fig1);
1564                 subplot(2,1,1);
1565                 semilogy(diag(SVx),'b');
1566                 hold on;
1567                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
1568                 ylabel('Horizontal');
1569                 title('Response Matrix Singular Values');
1570                 hold off;
1571                 subplot(2,1,2);
1572                 semilogy(diag(SVy),'b');
1573                 hold on;
1574                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
1575                 xlabel('Singular Value Number');
1576                 ylabel('Vertical');
1577                 hold off;
1578                 drawnow;
1579
1580                 if strcmp(RFCorrFlag,'No')
1581                     RFCorrState = 'NOT CORRECTED';
1582                 elseif strcmp(RFCorrFlag,'Yes')
1583                     RFCorrState = 'CORRECTED';
1584                 else
1585                     RFCorrState = '???';
1586                 end
1587
1588                 %         EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','HCM Chicane List','VCM Chicane List','IDBPM List','BBPM List','Change Golden Orbit',...
1589                 %            'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1590                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','BPM List','Change Golden Orbit',...
1591                     'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1592
1593                 if EditFlag == 1
1594                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
1595                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
1596                     titlestr='SVD Orbit Feedback';
1597                     lineNo=1;
1598                     answer=inputdlg(prompt,titlestr,lineNo,def);
1599                     if ~isempty(answer)
1600                         XivecNew = fix(str2num(answer{1}));
1601                         if isempty(XivecNew)
1602                             disp('   Horizontal E-vector cannot be empty.  No change made.');
1603                         else
1604                             if any(XivecNew<=0) | max(XivecNew)>length(diag(SVx))
1605                                 disp('   Error reading horizontal E-vector.  No change made.');
1606                             else
1607                                 Xivec = XivecNew;
1608                             end
1609                         end
1610                         YivecNew = fix(str2num(answer{2}));
1611                         if isempty(YivecNew)
1612                             disp('   Vertical E-vector cannot be empty.  No change made.');
1613                         else
1614                             if any(YivecNew<=0) | max(YivecNew)>length(diag(SVy))
1615                                 disp('   Error reading vertical E-vector.  No change made.');
1616                             else
1617                                 Yivec = YivecNew;
1618                             end
1619                         end
1620                     end
1621                 end
1622
1623                 if EditFlag == 2
1624                     List = getlist('HCM');
1625                     CheckList = zeros(size(List,1));
1626                     Elem = dev2elem('HCM', HCMlist1);
1627                     CheckList(Elem) = ones(size(Elem));
1628                     CheckList = CheckList(dev2elem('HCM',List));
1629                     newList = editlist(List, 'HCM', CheckList);
1630                     if isempty(newList)
1631                         fprintf('   Horizontal corrector magnet list cannot be empty.  No change made.\n');
1632                     else
1633                         HCMlist1 = newList;
1634                     end
1635                 end
1636
1637                 if EditFlag == 3
1638                     List = getlist('VCM');
1639                     CheckList = zeros(size(List,1));
1640                     Elem = dev2elem('VCM', VCMlist1);
1641                     CheckList(Elem) = ones(size(Elem));
1642                     CheckList = CheckList(dev2elem('VCM',List));
1643                     newList = editlist(List, 'VCM', CheckList);
1644                     if isempty(newList)
1645                         fprintf('   Vertical corrector magnet cannot be empty.  No change made.\n');
1646                     else
1647                         VCMlist1 = newList;
1648                     end
1649                 end
1650
1651                 if EditFlag == 4
1652                     ListOld = BPMlist1;
1653                     XgoalOld = Xgoal;
1654                     YgoalOld = Ygoal;
1655
1656                     % Full BPM list
1657                     List = [
1658                         1 2
1659                         1 5
1660                         1 6
1661                         1 10
1662                         2 1
1663                         2 5
1664                         2 6
1665                         2 9
1666                         3 2
1667                         3 5
1668                         3 6
1669                         3 10
1670                         3 11
1671                         3 12
1672                         4 1
1673                         4 5
1674                         4 6
1675                         4 10
1676                         5 1
1677                         5 5
1678                         5 6
1679                         5 10
1680                         5 11
1681                         5 12
1682                         6 1
1683                         6 5
1684                         6 6
1685                         6 10
1686                         7 1
1687                         7 5
1688                         7 6
1689                         7 10
1690                         8 1
1691                         8 5
1692                         8 6
1693                         8 10
1694                         9 1
1695                         9 5
1696                         9 6
1697                         9 10
1698                         10 1
1699                         10 5
1700                         10 6
1701                         10 10
1702                         10 11
1703                         10 12
1704                         11 1
1705                         11 5
1706                         11 6
1707                         11 10
1708                         12 1
1709                         12 5
1710                         12 6
1711                         12 9
1712                         ];
1713
1714                     CheckList = zeros(size(List,1),1);
1715                     if ~isempty(BPMlist1)
1716                         for i = 1:size(List,1)
1717                             k = find(List(i,1)==BPMlist1(:,1));
1718                             l = find(List(i,2)==BPMlist1(k,2));
1719
1720                             if isempty(k) | isempty(l)
1721                                 % Item not in list
1722                             else
1723                                 CheckList(i) = 1;
1724                             end
1725                         end
1726                     end
1727
1728                     newList = editlist(List, 'BPM', CheckList);
1729                     if isempty(newList)
1730                         fprintf('   BPM list cannot be empty.  No change made.\n');
1731                     else
1732                         BPMlist1 = newList;
1733                     end
1734
1735                     % Set the goal orbit to the golden orbit
1736                     Xgoal = getgolden('BPMx', BPMlist1);
1737                     Ygoal = getgolden('BPMy', BPMlist1);
1738
1739
1740                     % If a new BPM is added, then set the goal orbit to the golden orbit
1741                     for i = 1:size(BPMlist1,1)
1742
1743                         % Is it a new BPM?
1744                         k = find(BPMlist1(i,1)==ListOld(:,1));
1745                         l = find(BPMlist1(i,2)==ListOld(k,2));
1746
1747                         if isempty(k) | isempty(l)
1748                             % New BPM
1749                         else
1750                             % Use the old value for old BPM
1751                             Xgoal(i) = XgoalOld(k(l));
1752                             Ygoal(i) = YgoalOld(k(l));
1753                         end
1754                     end
1755                 end
1756
1757                 if EditFlag == 5
1758
1759                     ChangeList = editlist(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
1760                     for i = 1:size(ChangeList,1)
1761
1762                         k = find(ChangeList(i,1)==BPMlist1(:,1));
1763                         l = find(ChangeList(i,2)==BPMlist1(k,2));
1764
1765                         prompt = {sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
1766                         def = {sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
1767                         titlestr = 'CHANGE THE GOAL ORBIT';
1768                         lineNo = 1;
1769                         answer = inputdlg(prompt, titlestr, lineNo, def);
1770
1771                         if isempty(answer)
1772                             % No change
1773                             fprintf('   No change was made to the golden orbit.\n');
1774                         else
1775                             Xgoalnew = str2num(answer{1});
1776                             if isempty(Xgoalnew)
1777                                 fprintf('   No change was made to the horizontal golden orbit.\n');
1778                             else
1779                                 Xgoal(k(l)) = Xgoalnew;
1780                             end
1781
1782                             Ygoalnew = str2num(answer{2});
1783                             if isempty(Ygoalnew)
1784                                 fprintf('   No change was made to the vertical golden orbit.\n');
1785                             else
1786                                 Ygoal(k(l)) = Ygoalnew;
1787                             end
1788                         end
1789                     end
1790                     if ~isempty(ChangeList)
1791                         fprintf('   Note:  changing the goal orbit for "Orbit Correction" does not change the goal orbit for "Slow Orbit Feedback."\n');
1792                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
1793                     end
1794                 end
1795
1796                 if EditFlag == 6
1797                     List = [
1798                         1 1
1799                         2 1
1800                         3 1
1801                         4 1
1802                         4 2
1803                         5 1
1804                         6 1
1805                         6 2
1806                         7 1
1807                         8 1
1808                         9 1
1809                         10 1
1810                         11 1
1811                         11 2
1812                         12 1];
1813                     CheckList = zeros(size(List,1),1);
1814                     if ~isempty(LocalBumplist)
1815                         for i = 1:size(List,1)
1816                             k = find(List(i,1)==LocalBumplist(:,1));
1817                             l = find(List(i,2)==LocalBumplist(k,2));
1818
1819                             if isempty(k) | isempty(l)
1820                                 % Item not in list
1821                             else
1822                                 CheckList(i) = 1;
1823                             end
1824                         end
1825                     end
1826                     LocalBumplist = editlist2(List, 'Sector', CheckList);
1827                 end
1828
1829                 if EditFlag == 7
1830                     RFCorrFlag = questdlg(sprintf('Set RF Frequency during Orbit Correction?'),'RF Frequency','Yes','No', 'No');
1831                     if strcmp(RFCorrFlag,'No')
1832                         disp(['   RF Frequency will not be included in global orbit correction.']);
1833                     elseif strcmp(RFCorrFlag,'Yes')
1834                         disp(['   RF Frequency will be included in global orbit correction.']);
1835                     end
1836
1837                 end
1838             end
1839             close(h_fig1);
1840         end
1841
1842 %  ORBIT CORRECTION STRUCTURE (OCS)
1843 %    OCS.BPM (data structure)
1844 %    OCS.CM  (data structure)
1845 %    OCS.GoalOrbit
1846 %    OCS.NIter
1847 %    OCS.SVDIndex
1848 %    OCS.IncrementalFlag = 'Yes'/'No'
1849 %    OCS.BPMWeight
1850 %    OCS.Flags = { 'FitRF' , etc.  }
1851         OCSx.BPM = getx(BPMlist1, 'struct');
1852         OCSx.CM = getsp('HCM', HCMlist1, 'struct');
1853         OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
1854         OCSx.NIter = 1;
1855         OCSx.SVDIndex = Xivec;
1856         OCSx.IncrementalFlag = 'No';
1857         OCSx.FitRF = 1;
1858         OCSy.BPM = gety(BPMlist1, 'struct');
1859         OCSy.CM = getsp('VCM', VCMlist1, 'struct');
1860         OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
1861         OCSy.NIter = 1;
1862         OCSy.SVDIndex = Yivec;
1863         OCSy.IncrementalFlag = 'No';
1864         OCSy.FitRF = 0;
1865
1866         % Save vectors
1867         FB.OCSx = OCSx;
1868         FB.OCSy = OCSy;
1869
1870         FB.BPMlist1 = BPMlist1;
1871         FB.HCMlist1 = HCMlist1;
1872         FB.VCMlist1 = VCMlist1;
1873         FB.Xivec = Xivec;
1874         FB.Yivec = Yivec;
1875         FB.Xgoal = OCSx.GoalOrbit;
1876         FB.Ygoal = OCSy.GoalOrbit;
1877         FB.RFCorrFlag = RFCorrFlag;
1878         FB.LocalBumplist = LocalBumplist;
1879         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata',FB);
1880
1881
1882     case 'Feedback'
1883
1884         FBloopIter = 1;
1885         if get(findobj(gcbf,'Tag','SRCTRLCheckboxFOFB'),'Value') == 1
1886             StartFOFBFlag = 1;
1887         else
1888             StartFOFBFlag = 0;
1889         end
1890
1891         FEEDBACK_STOP_FLAG = 0;
1892         HWarnNum=0;
1893         VWarnNum=0;
1894
1895         SR_GeV = getenergy;
1896         % Feedback loop setup
1897         PlotInfoFlag = 0;           % Plot micado stuff
1898         LoopDelay = 1.0;           % Period of feedback loop [seconds], make sure the BPM averaging is correct
1899         VCM_LSB = .00366211;
1900         VCMCHICANE_LSB = .002441;   % 80 max?,  Note: not fully implemented
1901
1902         if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
1903             Xgain  = 0.2;
1904             Ygain  = 0.1;
1905         else
1906             Xgain  = 0.8; % raised 0.5->0.8 at 17:20, 3-2-05 to more quickly correct EPU4 fast switching orbit distortions
1907             Ygain  = 0.8;
1908         end
1909
1910         % Load lattice set for tune feed forward
1911         ConfigSetpoint = getproductionlattice;
1912         %load([getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile')]);
1913         QFsp = ConfigSetpoint.QF.Setpoint.Data;
1914         QDsp = ConfigSetpoint.QD.Setpoint.Data;
1915         TuneW16Min = gap2tune(5, 13.23, 1.8909);
1916         % Tune response matrix
1917         SR_TUNE_MATRIX = gettuneresp({'QF','QD'}, {[],[]}, getenergy('Production'));    % Approx. [0.1944 -0.0286;-0.1182 0.1526];
1918         %SR_TUNE_MATRIX = [0.1641 -0.0245
1919         %                 -0.1149 0.1477];
1920
1921         % ID tune compensation does not work in the injection lattice, so ...
1922         if abs(SR_GEV - bend2gev)>  0.05     % Don't use this routine for the injection lattice
1923             fprintf('   This routine should only be used for the production energy: Orbit feedback aborted\n');
1924             return
1925         end
1926
1927         set(0,'showhiddenhandles','on');
1928
1929         try
1930             fprintf('\n');
1931             fprintf('   *******************************\n');
1932             fprintf('   **  Starting Orbit Feedback  **\n');
1933             fprintf('   *******************************\n');
1934             a = clock;
1935             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1936             fprintf('   Note: the Matlab command window will be used to display status information.\n');
1937             fprintf('         It cannot be used to enter commands during slow orbit feedback.\n');
1938
1939
1940                 % save current BPM timeconstant - will reset to this when feedback stops
1941                 BPMtimeconstantOFB = getbpmtimeconstant;
1942                 fprintf('   Current Bergoz BPM time constant is %.1fs\n', BPMtimeconstantOFB);
1943
1944             % >= 2 Hz update rate on IDBPMs
1945             disp('   Bergoz BPM time constant set to 0.2s.')
1946             setbpmtimeconstant(0.2)
1947             pause(1.1);
1948
1949             % Check whether bumps and kickers are on and warn to turn off before starting feedback if necessary
1950             try
1951                 if (getsp('SR01S___BUMP1__BC21')==1 & getsp('SR01S___BUMP1P_BC22')==1) | (getsp('SR01S___SEK____BC21')==1 & getsp('SR01S___SEK_P__BC23')==1) | (getsp('SR01S___SEN____BC20')==1 & getsp('SR01S___SEN_P__BC22')==1)
1952                     soundtada;
1953                     fprintf('   \n');
1954                     fprintf('   *********************************************************************************\n');
1955                     fprintf('   ** One or more of the pulsed SR injection magnets is still on!  Turn them off! **\n');
1956                     fprintf('   *********************************************************************************\n');
1957                     fprintf('   \n');
1958                 end
1959             catch
1960                 disp('**Problem checking the state of the bumps and kickers - please check that they are not pulsing.');
1961             end
1962
1963             % Get vectors
1964
1965             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
1966
1967             BPMlist1 = FB.OCSx.BPM.DeviceList;
1968             % FOFB_BPMlist =
1969             HCMlist1 = FB.HCMlist1;
1970             VCMlist1 = FB.VCMlist1;
1971             Xivec = FB.Xivec;
1972             Yivec = FB.Yivec;
1973             Xgoal = FB.OCSx.GoalOrbit;
1974             Ygoal = FB.OCSy.GoalOrbit;
1975             FFTypeFlag = FB.FFTypeFlag;   %local or global tune correction
1976
1977             iNotHCMChicane = find(HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
1978             iHCMChicane = find(HCMlist1(:,2) == 10);
1979             iNotVCMChicane = find(VCMlist1(:,2) < 10);
1980             iVCMChicane = find(VCMlist1(:,2) == 10);
1981
1982             % Sensitivity matrix for setting fast feedback setpoints
1983             Sx1 = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
1984             Sy1 = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
1985
1986         catch
1987             fprintf('\n  %s \n',lasterr);
1988
1989             % Reset Bergoz BPM time constant to whatever it was before feedback started
1990             fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
1991             setbpmtimeconstant(BPMtimeconstantOFB);
1992
1993
1994             a = clock;
1995             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1996             fprintf('   *************************************************************\n');
1997             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
1998             fprintf('   *************************************************************\n\n');
1999             set(0,'showhiddenhandles','off');
2000             pause(0);
2001
2002             return
2003         end
2004
2005         StartFlag = questdlg(strvcat('','Is it OK to start orbit feedback?'),'Orbit Feedback','Yes','No','No');
2006         if strcmp(StartFlag,'No')
2007             % Reset Bergoz BPM time constant to whatever it was before feedback started
2008             fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
2009             setbpmtimeconstant(BPMtimeconstantOFB);
2010
2011             a = clock;
2012             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2013             fprintf('   ***************************\n');
2014             fprintf('   **  Orbit Feedback Exit  **\n');
2015             fprintf('   ***************************\n\n');
2016             pause(0);
2017             return
2018         end
2019
2020         SR_STATE_OLD = scaget('SR_STATE');
2021         setpv('SR_STATE', 5);
2022         set(0,'showhiddenhandles','on');
2023         [StateNumber, StateString] = getsrstate;
2024         if StateNumber >= 0
2025             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2026         else
2027             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2028         end
2029         fprintf('   Using %d E-vectors horizontally.\n', length(Xivec));
2030         fprintf('   Using %d E-vectors vertically.\n',   length(Yivec));
2031         fprintf('   Starting slow orbit correction every %.1f seconds.\n', LoopDelay);
2032         %  fprintf('   Resetting SR11 chicane motors every 20 seconds to fix drift problem.\n');
2033
2034         IDSector = getlist('ID');
2035         EPUlist = find((IDSector(:,1)==4) | (IDSector(:,1)==11));
2036         oldgap=210*ones(size(IDSector,1),1);
2037         oldShift=zeros(size(oldgap));
2038
2039         try
2040
2041             % Get and display data
2042             x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
2043             y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
2044             STDx = norm(x)/sqrt(length(x));
2045             STDy = norm(y)/sqrt(length(y));
2046             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
2047             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
2048
2049             % write goldenorbit values to Fast Orbit Feedback
2050             try
2051                 write_goldenorbit_ffb;
2052             catch
2053                 disp('write_goldenorbit_ffb did not work!');
2054             end
2055             setpv('SR01____FFBON__BC00',2);
2056             %pause(0);
2057
2058             %display state of FOFB system
2059             FOFBStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2060                 getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2061                 getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2062                 getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2063             FOFBStatusStr = ['    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    '];
2064             for loop = 1:size(FOFBStatus,2)
2065                 if FOFBStatus(loop)==0
2066                     FOFBStatusStr(loop,:) = 'OFF ';
2067                 elseif FOFBStatus(loop)==1
2068                     FOFBStatusStr(loop,:) = 'ON  ';
2069                 elseif FOFBStatus(loop)==2
2070                     FOFBStatusStr(loop,:) = 'OPEN';
2071                 else
2072                     FOFBStatusStr(loop,:) = 'BAD ';
2073                 end
2074             end
2075             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 %s',FOFBStatusStr(1,:)),'ForegroundColor',[0 0 0]);
2076             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 %s',FOFBStatusStr(2,:)),'ForegroundColor',[0 0 0]);
2077             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 %s',FOFBStatusStr(3,:)),'ForegroundColor',[0 0 0]);
2078             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 %s',FOFBStatusStr(4,:)),'ForegroundColor',[0 0 0]);
2079             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 %s',FOFBStatusStr(5,:)),'ForegroundColor',[0 0 0]);
2080             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 %s',FOFBStatusStr(6,:)),'ForegroundColor',[0 0 0]);
2081             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 %s',FOFBStatusStr(7,:)),'ForegroundColor',[0 0 0]);
2082             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 %s',FOFBStatusStr(8,:)),'ForegroundColor',[0 0 0]);
2083             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 %s',FOFBStatusStr(9,:)),'ForegroundColor',[0 0 0]);
2084             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 %s',FOFBStatusStr(10,:)),'ForegroundColor',[0 0 0]);
2085             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 %s',FOFBStatusStr(11,:)),'ForegroundColor',[0 0 0]);
2086             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 %s',FOFBStatusStr(12,:)),'ForegroundColor',[0 0 0]);
2087
2088         catch
2089
2090             fprintf('\n  %s \n',lasterr);
2091
2092             % Reset Bergoz BPM time constant to whatever it was before feedback started
2093             fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
2094             setbpmtimeconstant(BPMtimeconstantOFB);
2095
2096
2097             a = clock;
2098             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2099             fprintf('   *************************************************************\n');
2100             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
2101             fprintf('   *************************************************************\n\n');
2102
2103             setpv('SR_STATE',SR_STATE_OLD);
2104             [StateNumber, StateString] = getsrstate;
2105             if StateNumber >= 0
2106                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2107             else
2108                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2109             end
2110             set(0,'showhiddenhandles','off');
2111             pause(0);
2112
2113             return
2114
2115         end
2116
2117
2118         % Disable buttons
2119         set(0,'showhiddenhandles','on');
2120         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','off');
2121         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','on');
2122         set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','off');
2123         set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','off');
2124         set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','off');
2125         set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','off');
2126         set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','off');
2127         set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','off');
2128         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','off');
2129         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','off');
2130         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','off');
2131         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','off');
2132         set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','off');
2133         pause(0);
2134
2135
2136         % Initialize feedback loop
2137         StartTime = gettime;
2138         StartErrorTime = gettime;
2139         Xold = getx(FB.OCSx.BPM.DeviceList);
2140         Yold = gety(FB.OCSy.BPM.DeviceList);
2141         HQMOFM_stalenum = 0;
2142         pause(LoopDelay);
2143
2144         N_HCM = size(HCMlist1,1);
2145         N_VCM = size(VCMlist1,1);
2146
2147         N_RFMO = 1;
2148
2149         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2150             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'SetRF','Nodisplay','Nosetsp');
2151         else
2152             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
2153         end
2154         [FB.OCSx, Smatx, Sx, Ux, Vx] = orbitcorrectionmethods(FB.OCSx);
2155
2156         [FB.OCSy, junk, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
2157         [FB.OCSy, Smaty, Sy, Uy, Vy] = orbitcorrectionmethods(FB.OCSy);
2158
2159
2160         %%%%%%%%%%%%%%%%%%%%%%%
2161         % Start feedback loop %
2162         %%%%%%%%%%%%%%%%%%%%%%%
2163
2164         % chicaneloop=1;  % loop variable for resetting drifting chicanes (see a few lines below)
2165         % fftest=figure;
2166
2167         setpv('SR01____FFBON__BC00',2); % put FOFB in open loop so beamnoise gets recorded even if FOFB is not enabled
2168
2169         while 1
2170             try
2171                 t00 = gettime;
2172
2173                 %          if chicaneloop==20 % reset SR11 motor chicane setpoints every 20s due to drifting positions
2174                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(6),[11 1],0);
2175                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(7),[11 2],0);
2176                 %             chicaneloop = 1;
2177                 %          else
2178                 %             chicaneloop = chicaneloop + 1;
2179                 %          end
2180
2181                 % Check if GUI has been closed
2182                 if isempty(gcbf)
2183                     FEEDBACK_STOP_FLAG = 1;
2184                     lasterr('SRCONTROL GUI DISAPPEARED!');
2185                     error('SRCONTROL GUI DISAPPEARED!');
2186                 end
2187
2188                 %%%%%%%%%%%%%%%%%%%%%%%
2189                 % Fast orbit feedback %
2190                 %%%%%%%%%%%%%%%%%%%%%%%
2191                 if StartFOFBFlag == 1 & FBloopIter > 3
2192                     setpv('SR01____FFBON__BC00',2);
2193                     pause(0.5);
2194                     setpv('SR01____FFBON__BC00',1);
2195                     StartFOFBFlag = 0;
2196                     pause(1);
2197                     FOFBOnStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2198                         getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2199                         getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2200                         getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2201                     if any(FOFBOnStatus==0) | any(FOFBOnStatus==2)
2202                         setpv('SR01____FFBON__BC00',2); % open FOFB loop
2203                         disp('************************************************************************************************************');
2204                         disp('** Problem turning on Fast Orbit Feedback system...                                                       **');
2205                         disp('** Check status of ffbsecXX crates - but remember that a crate reboot will turn off Quads in that sector! **');
2206                         disp('** Suggest disabling the "Fast Orbit Correction" checkbox and starting Orbit Feedback again.              **');
2207                         disp('************************************************************************************************************');
2208                     else
2209                         fprintf('   Starting Fast Orbit Feedback at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
2210                     end
2211                 end
2212
2213
2214                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2215                 % Horizontal plane "feedback" %
2216                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2217
2218                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxSOFB'),'Value') == 1
2219
2220                     % Get orbit and check that the BPMs are different from the last update
2221                     Xnew = getx(FB.OCSx.BPM.DeviceList);
2222
2223                     % Don't feedback if the current is too small
2224                     if getdcct < 5
2225                         FEEDBACK_STOP_FLAG = 1;
2226                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2227                         break;
2228                     end
2229
2230                     x = Xgoal - Xnew;
2231                     STDx = norm(x)/sqrt(length(x));
2232
2233                     if any(Xold == Xnew)
2234                         a = clock;
2235                         N_Stale_Data_Points = find((Xold==Xnew)==1);
2236                         for loop = N_Stale_Data_Points'
2237                             fprintf('   Stale data: BPMx(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSx.BPM.DeviceList(loop,1), FB.OCSx.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2238                         end
2239                     else
2240                         % Compute horizontal correction
2241                         %%%OCSx0 = FB.OCSx;
2242                         FB.OCSx.BPM.Data = Xnew;
2243                         FB.OCSx = orbitcorrectionmethods(FB.OCSx, Smatx, Sx, Ux, Vx);
2244
2245                         %%%[FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
2246
2247                         % reduced feedback gain (implemented by Greg Portmann, December 2000)
2248                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2249                         % increased back to 0.8 C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2250                         % increased to 1.0, C. Steier, 2002-05-04, trim DACs
2251                         X = Xgain .* FB.OCSx.CM.Delta;
2252                         X(N_HCM+1) = 0.3*FB.OCSx.DeltaRF/4.988e-3;
2253                         %%%X = Xgain .* (FB.OCSx.CM.Data - OCSx0.CM.Data);
2254
2255                         % check for trim values+next step values, warn or stop FB as necessary
2256                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2257                         % need to extract Chicanes from this comparison or maybe check them first for range %
2258                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2259                         HCMtrimSP=getpv('HCM','Trim',HCMlist1);
2260                         HCMtrimSP_next = HCMtrimSP + X(1:N_HCM);
2261                         if max(abs(HCMtrimSP_next)) > 4
2262                             HCMtrimnum=find(abs(HCMtrimSP_next) > 4);
2263
2264                             % print message to screen
2265                             fprintf('**One or more of the horizontal correctors is at its maximum!! Stopping orbit feedback. \n');
2266                             fprintf('%s\n',datestr(now));
2267                             for loop = HCMtrimnum'
2268                                 fprintf('**%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2269                             end
2270
2271                             % send alphapage to operator pager
2272                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2273                             FEEDBACK_STOP_FLAG = 1;
2274
2275                             setpv('SR_STATE', -5);
2276                             [StateNumber, StateString] = getsrstate;
2277                             if StateNumber >= 0
2278                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2279                             else
2280                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2281                             end
2282                         end
2283
2284                         if FEEDBACK_STOP_FLAG == 1
2285                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2286                             if getpv('SR01____FFBON__BC00')==1
2287                                 disp('   Stopping Fast Orbit Feedback.');
2288                             end
2289                             setpv('SR01____FFBON__BC00',0);
2290                             pause(0.5);
2291                             setpv('SR01____FFBON__BC00',2);
2292                             break;
2293                         end
2294
2295                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2296                         pause(0);
2297
2298                         if max(abs(HCMtrimSP_next) > 3)
2299                             HCMtrimnum=find(abs(HCMtrimSP_next) > 3);
2300                             HWarnNum=HWarnNum+1;
2301                             if (HWarnNum==1 | rem(HWarnNum,120)==0)
2302
2303                                 % print message to screen every two minutes
2304                                 fprintf('**One or more of the horizontal corrector trims is above 3A or below -3A! \n');
2305                                 fprintf('%s\n',datestr(now));
2306                                 for loop = HCMtrimnum'
2307                                     fprintf('**%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2308                                 end
2309                                 fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2310
2311                                 %send alphapage to operator pager the first time then at 10 minutes
2312                                 if (HWarnNum==1 | HWarnNum==600)
2313                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageHCM.txt
2314                                 end
2315                             end
2316                         else
2317                             HWarnNum=0;
2318                         end
2319
2320                         % Don't feedback if the current is too small
2321                         if getdcct < 5
2322                             FEEDBACK_STOP_FLAG = 1;
2323                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2324                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2325                             break;
2326                         end
2327
2328                         if N_HCM > 0
2329                             steppv('HCM','Trim', X(iNotHCMChicane), HCMlist1(iNotHCMChicane,:), 0);
2330                             steppv('HCM','Setpoint', X(iHCMChicane), HCMlist1(iHCMChicane,:), 0);
2331                         end
2332
2333                         % write fast orbit feedback setpoints
2334                         if 1
2335                             %write_goldenorbit_ffb_2planes(1, Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM)+Sx3*X(length(X))/20, BPMlist1);
2336                             % should be corrected to include result of next frequency step ...
2337                             write_goldenorbit_ffb_2planes(1,Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM),BPMlist1);
2338                         end
2339
2340                         %fprintf('Horizontal Done: %f \n',gettime-t00);
2341
2342                         % RF feedback
2343                         HQMOFMsp_last = getpv('EG______HQMOFM_AC01');
2344
2345                         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2346                             if N_RFMO > 0
2347                                 if abs(X(end)/3) < .01
2348                                     % if abs(FB.OCSx.DeltaRF/3) < .01
2349                                     steppv('EG______HQMOFM_AC01', X(end));
2350                                 else
2351                                     steppv('EG______HQMOFM_AC01', 0.01*sign(X(end)));
2352                                 end
2353                             end
2354
2355                             HQMOFMsp_now = getpv('EG______HQMOFM_AC01');
2356
2357                             % Check for stale RF feedback
2358                             if HQMOFMsp_last == HQMOFMsp_now
2359                                 HQMOFM_stalenum = HQMOFM_stalenum + 1;
2360                                 if HQMOFM_stalenum == 30 % warn and message to pager if stale for 30 secs
2361                                     fprintf('**The RF is not responding to orbit feedback changes! \n');
2362                                     fprintf('%s\n',datestr(now));
2363                                     fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2364                                     fprintf('**ILC 73 controls the EG______HQMOFM_AC01 channel, which sets the RF frequency. \n');
2365                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstaleRFmessage.txt
2366                                 end
2367                                 if rem(HQMOFM_stalenum,120)==0 % message to screen every 2 minutes
2368                                     fprintf('**The RF is not responding to orbit feedback changes! (%s)\n',datestr(now));
2369                                 end
2370                             else
2371                                 HQMOFM_stalenum = 0;
2372                             end
2373
2374                         end
2375
2376                         %fprintf('RF Done: %f \n',gettime-t00);
2377
2378                         Xold = Xnew;
2379                     end % End horizontal correction
2380
2381
2382                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2383                     % Vertical plane "feedback" %
2384                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2385
2386                     % Get orbit and check that the BPMs are different from the last update
2387                     Ynew = gety(FB.OCSy.BPM.DeviceList);
2388
2389                     % Don't feedback if the current is too small
2390                     if getdcct < 5
2391                         FEEDBACK_STOP_FLAG = 1;
2392                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2393                         break;
2394                     end
2395
2396                     y = Ygoal - Ynew;
2397                     STDy = norm(y)/sqrt(length(y));
2398
2399                     if any(Yold == Ynew)
2400                         a = clock;
2401                         N_Stale_Data_Points = find((Yold==Ynew)==1);
2402                         for loop = N_Stale_Data_Points'
2403                             fprintf('   Stale data: BPMy(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSy.BPM.DeviceList(loop,1), FB.OCSy.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2404                         end
2405
2406                     else
2407
2408                         % Compute vertical correction
2409                         %%%OCSy0 = FB.OCSy;
2410                         FB.OCSy.BPM.Data = Ynew;
2411                         FB.OCSy = orbitcorrectionmethods(FB.OCSy, Smaty, Sy, Uy, Vy);
2412
2413                         %%%[FB.OCSy, RF, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
2414
2415                         % reduced feedback gain, C. Steier, 2001-03-25
2416                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2417                         % increased back to 0.8, C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2418                         % set to unity gain, C. Steier, 2002-05-04, trim DACs
2419                         Y = Ygain .* FB.OCSy.CM.Delta;
2420                         %%%Y = Ygain .* (FB.OCSy.CM.Data - OCSy0.CM.Data);
2421
2422                         % Just SVD correction
2423                         % warning('Not using "micado" correction in the vertical plane.');
2424
2425                         % check for trim values+next step values, warn or stop FB as necessary
2426                         VCMtrimSP = getpv('VCM','Trim',VCMlist1);
2427                         VCMtrimSP_next = VCMtrimSP + Y(1:N_VCM);
2428                         if max(abs(VCMtrimSP_next)) > 12
2429                             VCMtrimnum=find(abs(VCMtrimSP_next) > 12);
2430
2431                             % print message to screen
2432                             fprintf('**One or more of the vertical correctors is at its maximum!! Stopping orbit feedback. \n');
2433                             fprintf('%s\n',datestr(now));
2434                             for loop = VCMtrimnum'
2435                                 fprintf('**%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2436                             end
2437
2438                             % send alphapage to operator pager
2439                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2440                             FEEDBACK_STOP_FLAG = 1;
2441
2442                             setpv('SR_STATE', -5);
2443                             [StateNumber, StateString] = getsrstate;
2444                             if StateNumber >= 0
2445                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2446                             else
2447                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2448                             end
2449                         end
2450
2451                         if FEEDBACK_STOP_FLAG == 1
2452                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2453                             if getpv('SR01____FFBON__BC00')==1
2454                                 disp('   Stopping Fast Orbit Feedback.');
2455                             end
2456                             setpv('SR01____FFBON__BC00',0);
2457                             pause(0.5);
2458                             setpv('SR01____FFBON__BC00',2);
2459                             break;
2460                         end
2461
2462                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2463                         % pause(0);
2464
2465                         if max(abs(VCMtrimSP_next) > 4)
2466                             VCMtrimnum=find(abs(VCMtrimSP_next) > 4);
2467                             VWarnNum=VWarnNum+1;
2468                             if (VWarnNum==1 | rem(VWarnNum,120)==0)
2469
2470                                 % print message to screen every two minutes
2471                                 fprintf('**One or more of the vertical corrector trims is above 4A or below -4A! \n');
2472                                 fprintf('%s\n',datestr(now));
2473                                 for loop = VCMtrimnum'
2474                                     fprintf('**%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2475                                 end
2476                                 fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2477
2478                                 %send alphapage to operator pager the first time then at 10 minutes
2479                                 if (VWarnNum==1 | VWarnNum==600)
2480                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageVCM.txt
2481                                 end
2482                             end
2483                         else
2484                             VWarnNum=0;
2485                         end
2486
2487                         % Don't feedback if the current is too small
2488                         if getdcct < 5
2489                             FEEDBACK_STOP_FLAG = 1;
2490                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2491                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2492                             break;
2493                         end
2494
2495                         if N_VCM > 0
2496                             steppv('VCM','Trim', Y(iNotVCMChicane), VCMlist1(iNotVCMChicane,:), 0);
2497                             steppv('VCM','Setpoint', Y(iVCMChicane), VCMlist1(iVCMChicane,:), 0);
2498                         end
2499
2500                         % write fast orbit feedback setpoints
2501                         if 1
2502                             write_goldenorbit_ffb_2planes(2,Ynew(1:size(BPMlist1,1))+Sy1*Y(1:N_VCM),BPMlist1);
2503                         end
2504
2505                     end
2506
2507                     Yold = Ynew;
2508
2509                     %fprintf('Vertical Done: %f \n',gettime-t00);
2510                 end % End vertical correction
2511
2512
2513                 %%%%%%%%%%%%%%%%%%%%%
2514                 % Tune feed forward %
2515                 %%%%%%%%%%%%%%%%%%%%%
2516                 % We should do a Sector limit check
2517
2518                 tic;
2519                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxTune'),'Value') == 1
2520
2521                     if strcmp(SR_Mode, '1.9 GeV, High Tune') || strcmp(SR_Mode, '1.9 GeV, Inject at 1.23') || strcmp(SR_Mode, '1.9 GeV, Two-Bunch')
2522
2523                         addQFsp = zeros(24,1);
2524                         addQDsp = zeros(24,1);
2525
2526                         if strcmp(FFTypeFlag,'Local')
2527                             disp('  No local tune compensation available - global is the default now.');
2528                         elseif strcmp(FFTypeFlag,'Global')
2529
2530                             % The vectorized gets were put outside of loop for speed reasons
2531                             %
2532                             % should also set up QFfac, Quadelem, Quadlist structures outside loop
2533                             actualgap = getid(IDSector);
2534                             [gapmin,gapmax] = gaplimit(IDSector);
2535                             corrind = find(actualgap<(gapmin-1));
2536                             actualgap(corrind)=gapmax(corrind);
2537                             Shift=zeros(size(actualgap));
2538                             Shift(EPUlist)=getpv('EPU');
2539
2540                             IDchangedList=find((abs(actualgap-oldgap)>0.005) | (abs(Shift-oldShift)>0.005));
2541
2542                             if ~isempty(IDchangedList)
2543
2544                                 oldgap=actualgap;
2545                                 oldShift=Shift;
2546
2547                                 % EPUs excite nux = .25 resonance in vertical linear polarization mode!
2548                                 % therefore with EPU tune feedforward
2549                                 % running, we want to move our nominal working point away (just below) the .25 resonance.
2550                                 %
2551                                 % The following tune correction moves nominal
2552                                 % nu_x from .25 to .245 - this should be enough for well set up lattices.
2553                                 %
2554                                 % 24 QF+ 24 QD
2555                                 DeltaAmps = inv(SR_TUNE_MATRIX) * [-0.005;0];    %  DelAmps =  [QF; QD];
2556                                 addQFsp = addQFsp + DeltaAmps(1,:);
2557                                 addQDsp = addQDsp + DeltaAmps(2,:);
2558
2559                                 for gapnum = 1:length(actualgap)
2560
2561                                     % Change in tune and [QF;QD] from maximum gap
2562
2563                                     if (IDSector(gapnum,1) == 4) | (IDSector(gapnum,1) == 11)
2564                                         if IDSector(gapnum,2) == 1
2565                                             modenamestr = sprintf('SR%02dU___ODS1M__DC00',IDSector(gapnum,1));
2566                                         else % if IDSector(gapnum,2) == 2
2567                                             modenamestr = sprintf('SR%02dU___ODS2M__DC00',IDSector(gapnum,1));
2568                                         end
2569                                         epumode = getpvonline(modenamestr);
2570                                         if IDSector(gapnum,2)==2
2571                                             longshift=3;
2572                                         else
2573                                             longshift=0;
2574                                         end
2575                                         if (epumode==0) & (any(IDSector(gapnum,:)~=[11 1]))      % antiparallel tables need to be fit to data so that they could be used here
2576                                             DeltaNuX = shift2tune(IDSector(gapnum,1),actualgap(gapnum),Shift(gapnum)+longshift,SR_GeV);
2577                                             DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);   % variation of vertical tune shift with phase is small for EPUs
2578                                         else
2579                                             DeltaNuX = 0;
2580                                             DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);   % variation of vertical tune shift with phase is small for EPUs
2581                                         end
2582
2583                                     else
2584                                         DeltaNuX = 0;
2585                                         DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);
2586                                     end
2587
2588                                     DelQF = zeros(length(QFsp),1);
2589                                     DelQD = zeros(length(QFsp),1);
2590
2591                                     fraccorr = 0.8*DeltaNuY ./ TuneW16Min;
2592
2593                                     % Find which quads to change (local beta beating correction
2594                                     % (horizontal for EPU, vertical otherwise)
2595                                     QuadList = [IDSector(gapnum,1)-1 2; IDSector(gapnum,1) 1];
2596                                     QuadElem = dev2elem('QF',QuadList); % in reality use QF and QD ...
2597
2598                                     % global vertical tune correction
2599                                     % 24 QF+ 24 QD
2600                                     DeltaAmps = inv(SR_TUNE_MATRIX) * [(fraccorr*6.23e-4); fraccorr*(-0.05301)];    %  DelAmps =  [QF; QD];
2601                                     DelQF = DelQF + DeltaAmps(1,:);
2602                                     DelQD = DelQD + DeltaAmps(2,:);
2603
2604                                     % local horizontal tune correction (is also nearly a beta beating correction) only nonzero for EPUs!
2605                                     % 2 QF + 2 QD
2606                                     DeltaAmpsLocal = 12*inv(SR_TUNE_MATRIX) * [-DeltaNuX;0];                       %  DelAmps =  [QF; QD];
2607                                     DelQF(QuadElem) = DelQF(QuadElem)+DeltaAmpsLocal(1,1);
2608                                     DelQD(QuadElem) = DelQD(QuadElem)+DeltaAmpsLocal(2,1);
2609
2610                                     % local vertical beta beating correction (should be used together with above global tune correction)
2611                                     % set to zero for EPUs, since their vertical tune shift is small
2612                                     % 2 QF + 2QD
2613                                     if (IDSector(gapnum,1)==6) | (IDSector(gapnum,1)==7) | (IDSector(gapnum,1)==10) | (IDSector(gapnum,1)==11)
2614                                         QFfac = ([2.243127/2.237111; 2.243127/2.237111]-1) * fraccorr;
2615                                         QDfac = ([2.556392/2.511045; 2.556392/2.511045]-1) * fraccorr;
2616                                     elseif (IDSector(gapnum,1)==5) | (IDSector(gapnum,1)==9)
2617                                         QFfac = ([2.225965/2.219784; 2.243096/2.237111]-1) * fraccorr;
2618                                         QDfac = ([2.528950/2.483259; 2.556345/2.511045]-1) * fraccorr;
2619                                     elseif (IDSector(gapnum,1)==4) | (IDSector(gapnum,1)==8) | (IDSector(gapnum,1)==12)
2620                                         QFfac = ([2.243096/2.237111; 2.225965/2.219784]-1) * fraccorr;
2621                                         QDfac = ([2.556345/2.511045; 2.528950/2.483259]-1) * fraccorr;
2622                                     else
2623                                         QFfac = zeros(2,1);
2624                                         QDfac = zeros(2,1);
2625                                     end
2626
2627                                     DelQF(QuadElem,:) = DelQF(QuadElem,:) + QFfac.*QFsp(QuadElem,:);
2628                                     DelQD(QuadElem,:) = DelQD(QuadElem,:) + QDfac.*QDsp(QuadElem,:);
2629
2630                                     % add all tune and beta beating corrections for this one ID to the summed up correction vectors for all IDs
2631                                     addQFsp = addQFsp+DelQF;
2632                                     addQDsp = addQDsp+DelQD;
2633
2634                                 end
2635
2636                                 % Set quadrupoles using main setpoint channels
2637                                 setpv('QF', QFsp+addQFsp,[], 0);
2638                                 setpv('QD', QDsp+addQDsp,[], 0);
2639                                 % % Set quadrupoles using FF setpoint channels
2640                                 % setpv('QF', 'FF', addQFsp, [], 0);
2641                                 % setpv('QD', 'FF', addQDsp, [], 0);
2642                             end
2643
2644                         else
2645                             error('Unknown type selected for tune FF');
2646                         end
2647
2648                     else
2649                         disp('  No tune FF algorithm for non-production modes yet...');
2650                     end
2651                 end
2652
2653                 ffdeltaquad_delay = toc;
2654                 %fprintf('tune FF delay = %.1f seconds\n',ffdeltaquad_delay);
2655                 % fprintf('Tune Done: %f \n',gettime-t00);
2656
2657                 % Output info to screen
2658                 set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
2659                 set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
2660                 %pause(0);
2661
2662                 FOFBStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2663                     getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2664                     getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2665                     getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2666                 for loop = 1:size(FOFBStatus,2)
2667                     if FOFBStatus(loop)==0
2668                         FOFBStatusStr(loop,:) = 'OFF ';
2669                     elseif FOFBStatus(loop)==1
2670                         FOFBStatusStr(loop,:) = 'ON  ';
2671                     elseif FOFBStatus(loop)==2
2672                         FOFBStatusStr(loop,:) = 'OPEN';
2673                     else
2674                         FOFBStatusStr(loop,:) = 'BAD ';
2675                     end
2676                 end
2677                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 %s',FOFBStatusStr(1,:)),'ForegroundColor',[0 0 0]);
2678                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 %s',FOFBStatusStr(2,:)),'ForegroundColor',[0 0 0]);
2679                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 %s',FOFBStatusStr(3,:)),'ForegroundColor',[0 0 0]);
2680                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 %s',FOFBStatusStr(4,:)),'ForegroundColor',[0 0 0]);
2681                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 %s',FOFBStatusStr(5,:)),'ForegroundColor',[0 0 0]);
2682                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 %s',FOFBStatusStr(6,:)),'ForegroundColor',[0 0 0]);
2683                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 %s',FOFBStatusStr(7,:)),'ForegroundColor',[0 0 0]);
2684                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 %s',FOFBStatusStr(8,:)),'ForegroundColor',[0 0 0]);
2685                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 %s',FOFBStatusStr(9,:)),'ForegroundColor',[0 0 0]);
2686                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 %s',FOFBStatusStr(10,:)),'ForegroundColor',[0 0 0]);
2687                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 %s',FOFBStatusStr(11,:)),'ForegroundColor',[0 0 0]);
2688                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 %s',FOFBStatusStr(12,:)),'ForegroundColor',[0 0 0]);
2689
2690
2691                 %fprintf('End of feedback operations: %f \n\n',gettime-t00);
2692
2693                 % Wait for next update time or stop request
2694                 while (gettime-t00) < LoopDelay
2695                     %disp('interval could be shorter')
2696                     pause(.05);
2697                     % Check if GUI has been closed
2698                     if isempty(gcbf)
2699                         FEEDBACK_STOP_FLAG = 1;
2700                         lasterr('SRCONTROL GUI DISAPPEARED!');
2701                         error('SRCONTROL GUI DISAPPEARED!');
2702                     end
2703
2704                     % Check if Stop button was pressed
2705                     if FEEDBACK_STOP_FLAG == 1
2706                         % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2707                         if getpv('SR01____FFBON__BC00')==1
2708                             disp('   Stopping Fast Orbit Feedback.');
2709                         end
2710                         setpv('SR01____FFBON__BC00',0);
2711                         pause(0.5);
2712                         setpv('SR01____FFBON__BC00',2);
2713                         break;
2714                     end
2715                 end
2716
2717
2718                 if FEEDBACK_STOP_FLAG == 1
2719                     % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2720                     if getpv('SR01____FFBON__BC00')==1
2721                         disp('   Stopping Fast Orbit Feedback.');
2722                     end
2723                     setpv('SR01____FFBON__BC00',0);
2724                     pause(0.5);
2725                     setpv('SR01____FFBON__BC00',2);
2726                     break;
2727                 end
2728
2729                 StartErrorTime = gettime;
2730
2731             catch
2732
2733                 fprintf('\n  %s \n',lasterr);
2734
2735                 % Quit if error exists for more than 20 seconds
2736                 if gettime-StartErrorTime>20 | FEEDBACK_STOP_FLAG==1
2737                     fprintf('%s  Orbit feedback stopped due to error condition. \n\n',datestr(now));
2738
2739                     %send alphapage to operator pager
2740                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2741                     FEEDBACK_STOP_FLAG = 1;
2742
2743                     setpv('SR_STATE', -5);
2744                     [StateNumber, StateString] = getsrstate;
2745                     if StateNumber >= 0
2746                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2747                     else
2748                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2749                     end
2750                 else
2751                     a = clock;
2752                     fprintf('   Orbit feedback was paused due to error condition (%s %d:%d:%.0f). \n', date, a(4), a(5), a(6));
2753                     fprintf('   Orbit feedback has automatically restarted and is running. \n\n');
2754                 end
2755
2756             end
2757
2758             if FEEDBACK_STOP_FLAG == 1
2759                 % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2760                 if getpv('SR01____FFBON__BC00')==1
2761                     disp('   Stopping Fast Orbit Feedback.');
2762                 end
2763                 setpv('SR01____FFBON__BC00',0);
2764                 pause(0.5);
2765                 setpv('SR01____FFBON__BC00',2);
2766                 break;
2767             end
2768
2769             %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2770
2771             %pause(0);
2772
2773             % this loop delays turn on of Fast Feedback system
2774             if FBloopIter < 5
2775                 FBloopIter = FBloopIter + 1;
2776             end
2777
2778         end  % End of feedback loop
2779
2780
2781         % End feedback, reset all parameters
2782         try
2783
2784             % Enable buttons
2785             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','on');
2786             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','off');
2787             set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','on');
2788             set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','on');
2789             set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','on');
2790             set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','on');
2791             set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','on');
2792             set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','on');
2793             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','on');
2794             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','on');
2795             set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','on');
2796             set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','on');
2797             set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','on');
2798
2799             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = _____ mm'),'ForegroundColor',[0 0 0]);
2800             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = _____ mm'),'ForegroundColor',[0 0 0]);
2801
2802             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 ____'),'ForegroundColor',[0 0 0]);
2803             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 ____'),'ForegroundColor',[0 0 0]);
2804             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 ____'),'ForegroundColor',[0 0 0]);
2805             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 ____'),'ForegroundColor',[0 0 0]);
2806             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 ____'),'ForegroundColor',[0 0 0]);
2807             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 ____'),'ForegroundColor',[0 0 0]);
2808             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 ____'),'ForegroundColor',[0 0 0]);
2809             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 ____'),'ForegroundColor',[0 0 0]);
2810             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 ____'),'ForegroundColor',[0 0 0]);
2811             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 ____'),'ForegroundColor',[0 0 0]);
2812             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 ____'),'ForegroundColor',[0 0 0]);
2813             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 ____'),'ForegroundColor',[0 0 0]);
2814
2815             %pause(0);
2816
2817         catch
2818
2819             % GUI must have been closed
2820
2821         end
2822
2823
2824         % Reset Bergoz BPM time constant to whatever it was before feedback started
2825         fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
2826         setbpmtimeconstant(BPMtimeconstantOFB);
2827
2828
2829         a = clock;
2830         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2831         [StateNumber, StateString] = getsrstate;
2832         if StateNumber >= 0
2833             setpv('SR_STATE',5.1);
2834             [StateNumber, StateString] = getsrstate;
2835             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2836             fprintf('   ******************************\n');
2837             fprintf('   **  Orbit Feedback Stopped  **\n');
2838             fprintf('   ******************************\n\n');
2839         else
2840             [StateNumber, StateString] = getsrstate;
2841             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2842             fprintf('   ****************************************\n');
2843             fprintf('   **  Problem With Slow Orbit Feedback  **\n');
2844             fprintf('   ****************************************\n\n');
2845         end
2846         set(0,'showhiddenhandles','off');
2847         pause(0);
2848
2849
2850     case 'FeedbackSetup'
2851         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
2852
2853         if InitFlag
2854             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2855             % Edit the following lists to change default configuration of Orbit Correction %
2856             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2857
2858             % Corrector magnets
2859             listh=[
2860                 1 2;
2861                 1 8;
2862                 2 1;
2863                 2 8;
2864                 3 1;
2865                 3 8;
2866                 3 10; %SR04U_HCM2 (chicane trim)
2867                 4 1;
2868                 4 8;
2869                 5 1;
2870                 5 8;
2871                 5 10; %SR06U_HCM2 (chicane trim)
2872                 6 1;
2873                 6 8;
2874                 7 1;
2875                 7 8;
2876                 8 1;
2877                 8 8;
2878                 9 1;
2879                 9 8;
2880                 10 1;
2881                 10 8;
2882                 10 10; %SR11U_HCM2 (chicane trim)
2883                 11 1;
2884                 11 8;
2885                 12 1;
2886                 12 7];
2887             listv=[
2888                 1 2;
2889                 1 8;
2890                 2 1;
2891                 2 8;
2892                 3 1;
2893                 3 7;
2894                 3 8;
2895                 3 10; %SR04U_VHCM2 (chicane trim)
2896                 4 1;
2897                 4 7;
2898                 4 8;
2899                 5 1;
2900                 5 8;
2901                 5 10; %SR06U_VHCM2 (chicane trim)
2902                 6 1;
2903                 6 8;
2904                 7 1;
2905                 7 8;
2906                 8 1;
2907                 8 8;
2908                 9 1;
2909                 9 8;
2910                 10 1;
2911                 10 2;
2912                 10 7;
2913                 10 8;
2914                 10 10; %SR11U_VHCM2 (chicane trim)
2915                 11 1;
2916                 11 7;
2917                 11 8;
2918                 12 1;
2919                 12 7];
2920
2921             Xivec = [1:28];
2922             Yivec = [1:31];
2923             HCMlist1 = listh;
2924             VCMlist1 = listv;
2925
2926             % Full BPM list
2927             BPMlist1 = [
2928                 1 2
2929                 1 5
2930                 1 6
2931                 1 10
2932                 2 1
2933                 2 5
2934                 2 6
2935                 2 9
2936                 3 2
2937                 3 5
2938                 3 6
2939                 3 10
2940                 3 11
2941                 3 12
2942                 4 1
2943                 4 5
2944                 4 6
2945                 4 10
2946                 5 1
2947                 5 5
2948                 5 6
2949                 5 10
2950                 5 11
2951                 5 12
2952                 6 1
2953                 6 5
2954                 6 6
2955                 6 10
2956                 7 1
2957                 7 5
2958                 7 6
2959                 7 10
2960                 8 1
2961                 8 5
2962                 8 6
2963                 8 10
2964                 9 1
2965                 9 5
2966                 9 6
2967                 9 10
2968                 10 1
2969                 10 5
2970                 10 6
2971                 10 10
2972                 10 11
2973                 10 12
2974                 11 1
2975                 11 5
2976                 11 6
2977                 11 10
2978                 12 1
2979                 12 5
2980                 12 6
2981                 12 9
2982                 ];
2983
2984             % remove Bergoz BPMs in SR01 and SR03 for 2-bunch (noisy at low currents) and drop singular values
2985             if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
2986                     BPMlist1 = [
2987                          %1 2
2988                          1 5
2989                          1 6
2990                          1 10
2991                          2 1
2992                          2 5
2993                          2 6
2994                          %2 9
2995                          %3 2
2996                          3 5
2997                          3 6
2998                          3 10
2999                          3 11
3000                          3 12
3001                          4 1
3002                          4 5
3003                          4 6
3004                          4 10
3005                          5 1
3006                          5 5
3007                          5 6
3008                          5 10
3009                          5 11
3010                          5 12
3011                          6 1
3012                          6 5
3013                          6 6
3014                          6 10
3015                          7 1
3016                          7 5
3017                          7 6
3018                          7 10
3019                          8 1
3020                          8 5
3021                          8 6
3022                          8 10
3023                          9 1
3024                          9 5
3025                          9 6
3026                          9 10
3027                          10 1
3028                          10 5
3029                          10 6
3030                          10 10
3031                          10 11
3032                          10 12
3033                          11 1
3034                          11 5
3035                          11 6
3036                          11 10
3037                          12 1
3038                          12 5
3039                          12 6
3040                          %12 9
3041                          ];
3042             end
3043
3044             OCSx.BPM = getx(BPMlist1, 'struct');
3045             OCSx.CM = getsp('HCM', HCMlist1, 'struct');
3046             OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
3047             OCSx.NIter = 1;
3048             OCSx.SVDIndex = Xivec;
3049             OCSx.IncrementalFlag = 'No';
3050             OCSx.BPMWeight = {[]};
3051             OCSx.FitRF = 0;
3052             OCSy.BPM = gety(BPMlist1, 'struct');
3053             OCSy.CM = getsp('VCM', VCMlist1, 'struct');
3054             OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
3055             OCSy.NIter = 1;
3056             OCSy.SVDIndex = Yivec;
3057             OCSy.IncrementalFlag = 'No';
3058             OCSy.BPMWeight = {[]};
3059             OCSy.FitRF = 0;
3060             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
3061             % do we need these Smat calls? %
3062             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
3063             SXmat = getrespmat(OCSx.BPM, OCSx.CM, 'numeric');
3064             SYmat = getrespmat(OCSy.BPM, OCSy.CM, 'numeric');
3065             % [OCSx, Sx, Ux, Vx] = orbitcorrectionmethods(OCSx, SXmat);
3066             % [OCSy, Sy, Uy, Vy] = orbitcorrectionmethods(OCSy, SYmat);
3067
3068             % initialize FFTypeFlag
3069             FFTypeFlag = 'Global';
3070
3071         else
3072
3073             % Get vectors
3074             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
3075             % the two lines below seem to fix BPMlist editing problem
3076             OCSx = FB.OCSx;
3077             OCSy = FB.OCSy;
3078             BPMlist1 = FB.BPMlist1;
3079             HCMlist1 = FB.HCMlist1;
3080             VCMlist1 = FB.VCMlist1;
3081             Xivec = FB.Xivec;
3082             Yivec = FB.Yivec;
3083             Xgoal = FB.OCSx.GoalOrbit;
3084             OCSx.GoalOrbit = Xgoal;
3085             Ygoal = FB.OCSy.GoalOrbit;
3086             OCSy.GoalOrbit = Ygoal;
3087             FFTypeFlag = FB.FFTypeFlag;
3088
3089
3090             % FF corrector magnet list
3091             ListFF = [
3092                 4     2
3093                 4     8
3094                 5     1
3095                 5     7
3096 %               5     8 % why are these out???
3097 %               6     1 % why are these out???
3098                 6     8
3099                 7     1
3100                 7     8
3101                 8     1
3102                 8     8
3103                 9     1
3104                 9     8
3105                 10    1
3106                 11    8
3107                 12    1];
3108             ElemFF = dev2elem('HCM',ListFF);
3109
3110
3111             % Add button to change #ivectors, cm, IDBPMs,
3112             EditFlag = 0;
3113             h_fig1 = figure;
3114             while EditFlag ~= 6
3115
3116                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
3117                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
3118
3119                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
3120                     DispOrbit = getdisp('BPMx', BPMlist1);
3121                     Sx = [Sx DispOrbit];
3122                 end
3123
3124                 [Ux, SVx, Vx] = svd(Sx);
3125                 [Uy, SVy, Vy] = svd(Sy);
3126
3127
3128                 % Remove singular values greater than the actual number of singular values
3129                 i = find(Xivec>length(diag(SVx)));
3130                 if ~isempty(i)
3131                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
3132                     pause(0);
3133                     Xivec(i) = [];
3134                 end
3135                 i = find(Yivec>length(diag(SVy)));
3136                 if ~isempty(i)
3137                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
3138                     pause(0);
3139                     Yivec(i) = [];
3140                 end
3141
3142
3143                 Ax = Sx*Vx(:,Xivec);
3144                 Tx = inv(Ax'*Ax)*Ax';
3145
3146                 Ay = Sy*Vy(:,Yivec);
3147                 Ty = inv(Ay'*Ay)*Ay';
3148
3149                 figure(h_fig1);
3150                 subplot(2,1,1);
3151                 semilogy(diag(SVx),'b');
3152                 hold on;
3153                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
3154                 ylabel('Horizontal');
3155                 title('Response Matrix Singular Values');
3156                 hold off;
3157                 subplot(2,1,2);
3158                 semilogy(diag(SVy),'b');
3159                 hold on;
3160                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
3161                 xlabel('Singular Value Number');
3162                 ylabel('Vertical');
3163                 hold off;
3164                 drawnow;
3165
3166                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List', ...
3167                     'BPM List','Change the Goal Orbit','Continue');
3168
3169                 if EditFlag == 1
3170                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
3171                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
3172                     titlestr='SVD Orbit Feedback';
3173                     lineNo=1;
3174                     answer=inputdlg(prompt,titlestr,lineNo,def);
3175                     if ~isempty(answer)
3176                         XivecNew = fix(str2num(answer{1}));
3177                         if isempty(XivecNew)
3178                             disp('   Horizontal E-vector cannot be empty.  No change made.');
3179                         else
3180                             if any(XivecNew<=0) | max(XivecNew)>length(diag(SVx))
3181                                 disp('   Error reading horizontal E-vector.  No change made.');
3182                             else
3183                                 Xivec = XivecNew;
3184                             end
3185                         end
3186                         YivecNew = fix(str2num(answer{2}));
3187                         if isempty(YivecNew)
3188                             disp('   Vertical E-vector cannot be empty.  No change made.');
3189                         else
3190                             if any(YivecNew<=0) | max(YivecNew)>length(diag(SVy))
3191                                 disp('   Error reading vertical E-vector.  No change made.');
3192                             else
3193                                 Yivec = YivecNew;
3194                             end
3195                         end
3196                     end
3197                 end
3198
3199                 if EditFlag == 2
3200                     List= getlist('HCM','Trim');
3201                     CheckList = zeros(96,1);
3202                     Elem = dev2elem('HCM', HCMlist1);
3203                     CheckList(Elem) = ones(size(Elem));
3204                     CheckList = CheckList(dev2elem('HCM',List));
3205
3206                     % Remove FF corrrectors
3207                     %           Elem = dev2elem('HCM',List);
3208                     %           for j = length(ElemFF):-1:1
3209                     %              i = find(Elem==ElemFF(j));
3210                     %              Elem(i,:) = [];
3211                     %              List(i,:) = [];
3212                     %              CheckList(i,:) = [];
3213                     %           end
3214
3215                     newList = editlist(List, 'HCMtrim', CheckList);
3216
3217                     if isempty(newList)
3218                         fprintf('   WARNING: Horizontal corrector magnet list is empty!\n');
3219                         HCMlist1 = newList;
3220                     else
3221                         HCMlist1 = newList;
3222                     end
3223                     OCSx.CM.DeviceList = HCMlist1;
3224                 end
3225
3226                 if EditFlag == 3
3227                     List = getlist('VCM','Trim');
3228                     CheckList = zeros(96,1);
3229                     Elem = dev2elem('VCM', VCMlist1);
3230                     CheckList(Elem) = ones(size(Elem));
3231                     CheckList = CheckList(dev2elem('VCM',List));
3232
3233                     % Remove FF corrrectors
3234                     %           Elem = dev2elem('VCM',List);
3235                     %           for j = length(ElemFF):-1:1
3236                     %              i = find(Elem==ElemFF(j));
3237                     %              Elem(i,:) = [];
3238                     %              List(i,:) = [];
3239                     %              CheckList(i,:) = [];
3240                     %           end
3241
3242                     newList = editlist(List, 'VCMtrim', CheckList);
3243
3244                     if isempty(newList)
3245                         fprintf('   WARNING: Vertical corrector magnet list is empty!\n');
3246                         VCMlist1 = newList;
3247                     else
3248                         VCMlist1 = newList;
3249                     end
3250                     OCSy.CM.DeviceList = VCMlist1;
3251                 end
3252
3253                 if EditFlag == 4
3254                     ListOld = BPMlist1;
3255                     XgoalOld = Xgoal;
3256                     YgoalOld = Ygoal;
3257
3258                     % Full BPM list
3259                     List = [
3260                         1 2
3261                         1 5
3262                         1 6
3263                         1 10
3264                         2 1
3265                         2 5
3266                         2 6
3267                         2 9
3268                         3 2
3269                         3 5
3270                         3 6
3271                         3 10
3272                         3 11
3273                         3 12
3274                         4 1
3275                         4 5
3276                         4 6
3277                         4 10
3278                         5 1
3279                         5 5
3280                         5 6
3281                         5 10
3282                         5 11
3283                         5 12
3284                         6 1
3285                         6 5
3286                         6 6
3287                         6 10
3288                         7 1
3289                         7 5
3290                         7 6
3291                         7 10
3292                         8 1
3293                         8 5
3294                         8 6
3295                         8 10
3296                         9 1
3297                         9 5
3298                         9 6
3299                         9 10
3300                         10 1
3301                         10 5
3302                         10 6
3303                         10 10
3304                         10 11
3305                         10 12
3306                         11 1
3307                         11 5
3308                         11 6
3309                         11 10
3310                         12 1
3311                         12 5
3312                         12 6
3313                         12 9
3314                         ];
3315
3316
3317                     CheckList = zeros(size(List,1),1);
3318                     if ~isempty(BPMlist1)
3319                         for i = 1:size(List,1)
3320                             k = find(List(i,1)==BPMlist1(:,1));
3321                             l = find(List(i,2)==BPMlist1(k,2));
3322
3323                             if isempty(k) | isempty(l)
3324                                 % Item not in list
3325                             else
3326                                 CheckList(i) = 1;
3327                             end
3328                         end
3329                     end
3330
3331                     newList = editlist(List, 'BPM', CheckList);
3332                     if isempty(newList)
3333                         fprintf('   BPM list cannot be empty.  No change made.\n');
3334                     else
3335                         BPMlist1 = newList;
3336                     end
3337
3338                     % Set the goal orbit to the golden orbit
3339                     Xgoal = getgolden('BPMx', BPMlist1);
3340                     Ygoal = getgolden('BPMy', BPMlist1);
3341
3342
3343                     % If a new BPM is added, then set the goal orbit to the golden orbit
3344                     for i = 1:size(BPMlist1,1)
3345
3346                         % Is it a new BPM?
3347                         k = find(BPMlist1(i,1)==ListOld(:,1));
3348                         l = find(BPMlist1(i,2)==ListOld(k,2));
3349
3350                         if isempty(k) | isempty(l)
3351                             % New BPM
3352                         else
3353                             % Use the old value for old BPM
3354                             Xgoal(i) = XgoalOld(k(l));
3355                             Ygoal(i) = YgoalOld(k(l));
3356                         end
3357                     end
3358                     OCSx.BPM.DeviceList = BPMlist1;
3359                     OCSy.BPM.DeviceList = BPMlist1;
3360                     OCSx.GoalOrbit = Xgoal;
3361                     OCSy.GoalOrbit = Ygoal;
3362                 end
3363
3364                 if EditFlag == 5
3365                     ChangeList = editlist2(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
3366
3367                     for i = 1:size(ChangeList,1)
3368
3369                         k = find(ChangeList(i,1)==BPMlist1(:,1));
3370                         l = find(ChangeList(i,2)==BPMlist1(k,2));
3371
3372                         prompt={sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
3373                         def={sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
3374                         titlestr='CHANGE THE GOAL ORBIT';
3375                         lineNo=1;
3376                         answer = inputdlg(prompt, titlestr, lineNo, def);
3377
3378                         if isempty(answer)
3379                             % No change
3380                             fprintf('   No change was made to the golden orbit.\n');
3381                         else
3382                             Xgoalnew = str2num(answer{1});
3383                             if isempty(Xgoalnew)
3384                                 fprintf('   No change was made to the horizontal golden orbit.\n');
3385                             else
3386                                 Xgoal(k(l)) = Xgoalnew;
3387                             end
3388
3389                             Ygoalnew = str2num(answer{2});
3390                             if isempty(Ygoalnew)
3391                                 fprintf('   No change was made to the vertical golden orbit.\n');
3392                             else
3393                                 Ygoal(k(l)) = Ygoalnew;
3394                             end
3395                         end
3396                     end
3397                     if ~isempty(ChangeList)
3398                         fprintf('   Note:  Changing the goal orbit for "Slow Orbit Feedback" does not change the goal orbit for "Orbit Correction."\n');
3399                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
3400                     end
3401                     OCSx.GoalOrbit = Xgoal;
3402                     OCSy.GoalOrbit = Ygoal;
3403                 end
3404
3405 %                 if EditFlag == 6
3406 %                     FFTypeFlag = questdlg(sprintf('Do you want to use a fully local or a combined local/global compensation of IDs? (nuy=9.2 only)'),'Tune FF','Local','Global', 'Global');
3407 %                     if strcmp(FFTypeFlag,'Local')
3408 %                         disp(['   The tune FF will use 8 local quadrupoles to compensate beta beating and tune shift']);
3409 %                         disp(['   from each ID.']);
3410 %                     elseif strcmp(FFTypeFlag,'Global')
3411 %                         disp(['   The tune FF will use 4 local quadrupoles to compensate beta beating and all QF+QD']);
3412 %                         disp(['   to compensate tune shift from each ID.']);
3413 %                     end
3414 %                 end
3415
3416             end
3417             close(h_fig1);
3418         end
3419
3420         % Save vectors
3421         FB.Xivec = Xivec;
3422         FB.Yivec = Yivec;
3423         FB.HCMlist1 = HCMlist1;
3424         FB.VCMlist1 = VCMlist1;
3425         FB.BPMlist1 = BPMlist1;
3426
3427         OCSx.SVDIndex = Xivec;
3428         OCSy.SVDIndex = Yivec;
3429         FB.OCSx = OCSx;
3430         FB.OCSy = OCSy;
3431
3432         FB.FFTypeFlag = FFTypeFlag;
3433         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata',FB);
3434
3435
3436     case 'FastFeedbackSetup'
3437
3438         InitFlag = Input2;
3439
3440         if InitFlag
3441             FOFBFreq = 1000;
3442             % user operations 9/14-10/17/04: P=0.5, I=120, D=0.0015 (for both planes)
3443             % below are known good values for user ops as of 8-1-05
3444             HorP = 2;
3445             HorI = 300;
3446             HorD = 0.002;
3447             VertP = 1;
3448             VertI = 100;
3449             VertD = 0.0015;
3450
3451             % this initial set is now done in hwinit.m because it's not a good idea to set anything when srcontrol is launched
3452             % try
3453             %     setsp('SR01____FFBFREQAC00', FOFBFreq); % set freq
3454             %     write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3455             % catch
3456             %     disp('   Trouble setting Fast Orbit Feedback parameters!');
3457             % end
3458
3459         else
3460             % Get vectors
3461             FOFB = get(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata');
3462             FOFBFreq = FOFB.FOFBFreq;
3463             HorP  = FOFB.HorP;
3464             HorI  = FOFB.HorI;
3465             HorD  = FOFB.HorD;
3466             VertP = FOFB.VertP;
3467             VertI = FOFB.VertI;
3468             VertD = FOFB.VertD;
3469
3470             % Add button to change #ivectors, CMs, IDBPMs,
3471             EditFlag = 0;
3472             %h_fig1 = figure;
3473             while EditFlag ~= 3
3474
3475                 %EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'HCM List', 'VCM List', ...
3476                 %   'IDBPM List', 'BBPM List', 'Continue');
3477                 % Use menu below until other FFB config routines work (then also uncomment options 3,4,5,6 below)
3478                 EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'Continue');
3479
3480                 if EditFlag == 1
3481                     % change rate
3482
3483                     prompt={'Enter the desired Fast Feedback Frequency (1-1000 Hz)'};
3484                     def={num2str(FOFBFreq)};
3485                     titlestr='Fast Feedback Setup';
3486                     lineNo=1;
3487                     answer=inputdlg(prompt,titlestr,lineNo,def);
3488                     if ~isempty(answer)
3489                         FOFBFreq = fix(str2num(answer{1}));
3490                         if isempty(FOFBFreq)
3491                             disp('   Frequency value cannot be empty.  No change made.');
3492                             FOFBFreq = getsp('SR01____FFBFREQAC00');
3493                         else
3494                             if FOFBFreq < 1 | FOFBFreq > 1000
3495                                 disp('   Frequency must be between 1 and 1000 Hz.  No change made.');
3496                                 FOFBFreq = getsp('SR01____FFBFREQAC00');
3497                             end
3498                         end
3499                         setsp('SR01____FFBFREQAC00',FOFBFreq); % change freq
3500                         pause(0.5);
3501                         fprintf('   Fast orbit feedback frequency is running at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
3502                     else
3503                         FOFBFreq = getsp('SR01____FFBFREQAC00');
3504                     end
3505                 end
3506
3507                 if EditFlag == 2
3508                     % edit  PIDs
3509                     % User defaults are HorP=2, HorI=300, HorD=0.002, VertP=1, VertI=100, VertD=0.0015
3510                     prompt={'P horizontal', 'I horizontal', 'D horizontal', 'P vertical', 'I vertical', 'D vertical'};
3511                     def={num2str(HorP), num2str(HorI), num2str(HorD), num2str(VertP), num2str(VertI), num2str(VertD)};
3512                     titlestr='Fast Feedback PID Setup';
3513                     lineNo=1;
3514                     answer=inputdlg(prompt,titlestr,lineNo,def);
3515                     if ~isempty(answer)
3516                         HorPnewnum = str2num(answer{1});
3517                         if isempty(HorPnewnum)
3518                             disp('   HorP value cannot be empty.  No change made.');
3519                         else
3520                             HorP = HorPnewnum;
3521                         end
3522                         HorInewnum = str2num(answer{2});
3523                         if isempty(HorInewnum)
3524                             disp('   HorI value cannot be empty.  No change made.');
3525                         else
3526                             HorI = HorInewnum;
3527                         end
3528                         HorDnewnum = str2num(answer{3});
3529                         if isempty(HorDnewnum)
3530                             disp('   HorD value cannot be empty.  No change made.');
3531                         else
3532                             HorD = HorDnewnum;
3533                         end
3534                         VertPnewnum = str2num(answer{4});
3535                         if isempty(VertPnewnum)
3536                             disp('   VertP value cannot be empty.  No change made.');
3537                         else
3538                             VertP = VertPnewnum;
3539                         end
3540                         VertInewnum = str2num(answer{5});
3541                         if isempty(VertInewnum)
3542                             disp('   VertI value cannot be empty.  No change made.');
3543                         else
3544                             VertI = VertInewnum;
3545                         end
3546                         VertDnewnum = str2num(answer{6});
3547                         if isempty(VertDnewnum)
3548                             disp('   VertD value cannot be empty.  No change made.');
3549                         else
3550                             VertD = VertDnewnum;
3551                         end
3552
3553                         try
3554                             write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3555                             fprintf('   Setting FFB gains to Horizontal P=%.2f, I=%.1f, D=%.4f;  Vertical P=%.2f, I=%.1f, D=%.4f\n', HorP, HorI, HorD, VertP, VertI, VertD);
3556                         catch
3557                             disp('   Trouble setting Fast Orbit Feedback parameters!');
3558                         end
3559                     end
3560                 end
3561
3562                 %if EditFlag == 3
3563                 %   disp('   This function not yet available.');
3564                 %   % change HCM List
3565                 %end
3566                 %
3567                 %if EditFlag == 4
3568                 %   disp('   This function not yet available.');
3569                 %   % change VCM List
3570                 %end
3571                 %
3572                 %if EditFlag == 5
3573                 %   disp('   This function not yet available.');
3574                 %   % change IDBPM List
3575                 %end
3576                 %
3577                 %if EditFlag == 6
3578                 %   disp('   This function not yet available.');
3579                 %   % change BBPM List
3580                 %end
3581
3582             end
3583             %close(h_fig1);
3584         end
3585
3586         % Save vectors
3587         FOFB.FOFBFreq = FOFBFreq;
3588         FOFB.HorP = HorP;
3589         FOFB.HorI = HorI;
3590         FOFB.HorD = HorD;
3591         FOFB.VertP = VertP;
3592         FOFB.VertI = VertI;
3593         FOFB.VertD = VertD;
3594         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata',FOFB);
3595
3596     otherwise
3597         fprintf('   No action for %s.\n', action);
3598 end   % end case