Description of srcontrol5_before_20070413
Home > ALS > StorageRing > srcontrol5_before_20070413.m
srcontrol5_before_20070413
PURPOSE
srcontrol5
SYNOPSIS
function srcontrol5(action, Input2, Input3)
DESCRIPTION
 srcontrol5
 Storage ring control program
 This program controls all storage ring magnets, performs orbit feedback and
 tune feedforward and helps to diagnose problems in routine user operation
 of the ALS storage ring. It includes a gui to simplify the use of this
 program.
 It was originally programmed by Greg Portmann (until December 2000) with input
 from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
 and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
 The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
 Christoph Steier, July 2002
 SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
 Tom Scarvie, April 2005
CROSS-REFERENCE INFORMATION
This function calls:
bend2gev BEND2GEV - Compute the energy based on the ramp tables
checksrmags CHECKSRMAGS - Check SR power supplies against a lattice file
checksrorbit ErrorNums =checksrorbit(Sector, BPMxtolerance [.015 mm], [BPMytolerance [.015 mm]])
gap2tune GAP2TUNE - Computes the vertical tune shift for a insertion device gap change.
gaplimit [GapMin, GapMax] = gaplimit(ID_Number);
getff function [FFEnableBM, FFEnableBC, GapEnableBM, GapEnableBC, Sector] = getff(Sector)
getid GETID - Get the insertion device position, velocity, run flag, and user requested gap
getsrstate [StateNumber, StateString] = getsrstate
set_alarmhandler_AHU_thresholds_inject function set_alarmhandler_AHU_thresholds_inject
set_alarmhandler_thresholds set_alarmhandler_thresholds
set_alarmhandler_thresholds_new set_alarmhandler_thresholds_new
setbpmtimeconstant SETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
setbumps SETBUMPS - Make a straight section bump
setff function setff(Sector, FFEnableBC, GapEnableBC)
setid SETID - Set the insertion device vertical gap
setsrstatechannels
shift2tune SHIFT2TUNE - Computes the horizontal tune shift for a EPU gap and horizontal shift
srcycle SRCYCLE - Storage ring cycle
srramp SRRAMP - Ramp the storage ring energy
write_goldenorbit_ffb function write_goldenorbit_ffb
write_goldenorbit_ffb_2planes WRITE_GOLDENORBIT_FFTB_2PLANES - Sets the BPM setpoints which are used by the fast feedback system
This function is called by:
SOURCE CODE
function srcontrol5(action, Input2, Input3)
% srcontrol5
% Storage ring control program
%
% This program controls all storage ring magnets, performs orbit feedback and
% tune feedforward and helps to diagnose problems in routine user operation
% of the ALS storage ring. It includes a gui to simplify the use of this
% program.
%
% It was originally programmed by Greg Portmann (until December 2000) with input
% from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
% and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
%
% The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
%
% Christoph Steier, July 2002
%
% SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
%
% Tom Scarvie, April 2005
% known bugs/problems (May 2001):
% - IDBPM averaging might be a bit too long for orbit feedback
%        solved after Superbend shutdown ... Instead of averaging, digital low pass filters are used
% - gap2tune does not give correct answers for wiggler and potentially other IDs -> orbit feedback
%        seems to be OK for other IDs, has been corrected for wiggler (fit to insertion device
%        compensation table)
% - chicanes do not work in orbit feedback
%        solved. One problem was that orbit response matrizes were mis-scaled by factor of two.
%        Second problem was different time constant of power supply control. Solved by moving controls
%        of center chicanes to cPCI (and magnets are fast, hysteresis free, aircore coils).
%        Center chicane in sector 4 is now routinely used in orbit feedback. Sector 11 to follow soon.
% - zero reading of ID gap dumps beam
%        solved in srcontrol5, still a problem in srcontrol5_hightune (but that routine has to be completely
%        rewritten because of all recent changes to srcontrol5, anyhow). For gap readings below the minimum
%        allowed gap for a device, the tune feedforward disables itself.
% - cycling of lattice causes frequent power supply failures
%        solved by changing the cycling procedure. 1.5 GeV operation is now on the upper hysteresis branch
%        as was the 1.9 GeV injection lattice before.
% - frequently stalled data in IDBPM readout
%        solved with new BPM readouts and digital filtering. Seems to have been a resolution problem
%        of the digital averaging algorithm.
% - magnet ramp tables are not in perfect agreement with magnetic measurements
%        Does not appear to be a serious problem. Superbends are slightly out of sync with other magnets,
%        but this does not cause any negative effects while ramping.
% - no good way to operate with injection at 1.5 GeV and storage energy below that
%        There now is a reasonable way to inject at 1.5 GeV and ramp down to lower storage energy. But
%        it has to be tested again after implementing new (and more) chicanes ...
% revision history
% 2001-05-10, Christoph Steier
% check whether readback from insertion device is significantly (more than 1 mm) below minimum
% gap, to avoid false zero readings of insertion device gaps to cause the tune feed forward
% to implement false huge correction (and dump the beam). If the insertion device gap readbacks
% gets more than 1 mm below the nominal minimum gap, the routine now assumes the insertion device
% to be open.
%
% 2001-08-30 and during Superbend commissioning, Christoph Steier, Tom Scarvie, Winni Decking
% various changes have been made to incorporate the Superbends and some other new equipment
% installed in the Superbend shutdown. This included some changes to programs being called by srcontrol
% (like srload, srsave, srcycle, srramp, ...). The main changes within srcontrol were in the orbit
% correction and slow orbit feedback routines (incorporating frequency feedback, ...)
%
% 2002-05-04, Christoph Steier
% added new IDBPMs, modified orbit feedback to use trim DACs, removed LSB toggling in vertical
% orbit feedback, ...
%
% 2002-07-29, T.Scarvie
% added check of CM trim currents to warn of problems that might rail the orbit feedback
%
% 2002-07-31, Christoph Steier
% increased the gain of the RF frequency feedback from 1/50 of the gain of the horizontal
% orbit feedback to 1/20. Reason was that the frequency feedback was reacting a bit too slow if all
% insertion device gaps are closed at once at high speed at the beginning of a fill.
%
% 2002-08-05, C.Steier, T.Scarvie
% Added conditional to reduce orbit feedback gain if running in two-bunch mode
%
% 2003-06-02, T.Scarvie
% Added loop inside orbit feedback to reset the SR11 chicane M1 and M2 motors every 20s to combat drift problem
%
% 2003-06-18, C. Steier
% Disabled loop to periodically reset chicane in SR11. Al Robb replaced power supply, seems to be no problem anymore.
%
% 2004-05-10, C. Steier
% The list of all BBPMs is now set up automatically be calling getlist('BBPMx'). This way, new BBPMs have to be added
% at fewer places in the software. It should now be sufficient to modify getlist and run the orbit response matrix
% rountine (getsmat) once to enable use of the new BBPMs.
%
% 2004-05-14, C. Steier
% Modified parameters for ramprate reduction (in srramp and here). Previous parameters were slightly too
% cautious. Increased initial slow ramprate to 0.4 A/s.
%
% 2004-05-14, C. Steier
% Incorporated insertion device compensation schemes for nu_y = 9.2 lattice.
%
% 2004-06-14, T.Scarvie
% Added controls for fast orbit feedback
%
% 2004-06-21, C. Steier
% Added tune feedforward (in the global tune compensation scheme for the nu_y=9.2 lattice) for the shift
% dependent tune shift of the EPUs, as well as a skew quadrupole feedforward for the EPU im sector 11
% (both only active in parallel mode so far).
%
% 2005-02-13, T.Scarvie
% Separated horizontal and vertical planes for setting Fast Feedback PIDs
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NOTES for conversion to new Middle Layer %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% We never use the gap and bump control flags - the radio buttons have been disabled -
%        should we try to keep the functionality?
%
% remove handle globals
% set(0,'showhiddenhandles','on'); what does this do?
% grampbsc -> should be handled by new srramp (which uses k-values)
% checksrmags
% checksrorbit(...)
% getdcct
% setbpmtimeconstant
% getsmatelements
% Chicane trims are now part of the corrector family
% getname('IDrunflag',...) family name change
% write_goldenorbit_ffb, write_goldenorbit_ffb2
% For the compiler
%#function goldenpage
%#function setoperationalmode
% Check if the AO exists
checkforao;
%%%%%%%%%%%%%%
% Initialize %
%%%%%%%%%%%%%%
global FEEDBACK_STOP_FLAG
SR_Mode = getfamilydata('OperationalMode');
SR_GEV = getfamilydata('Energy');
BSCramprate = getfamilydata('BSCRampRate');
if isnan(BSCramprate) | isempty(BSCramprate)
    BSCramprate = 0.4;
    setfamilydata(BSCramprate, 'BSCRampRate');
end
if nargin < 1
    action = 'Initialize';
end
if nargin < 2
    Input2 = 0;
end
if nargin < 3
    Input3 = 0;
end
if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
    FOFBcheckboxVal = 0;
else
    FOFBcheckboxVal = 1;
end
%%%%%%%%%%%%%%%%
% Main Program %
%%%%%%%%%%%%%%%%
switch(action)
    case 'StopOrbitFeedback'
        FEEDBACK_STOP_FLAG = 1;
    case 'Initialize'
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % GUI
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        ButtonWidth = 200;
        ButtonHeight  = 25;
        Offset1 = 8*25+12 + 47 + 25+25;
        Offset2 = 47+25+25;
        Offset3 = 45+25;
        Offset4 = 1;
        Offset5 = 30;
        FigWidth = ButtonWidth+6;
        FigHeight  = 3+7*(ButtonHeight+6)+24+Offset1;
        ButtonWidth = 200-6;
        % Change figure position
        set(0,'Units','pixels');
        p=get(0,'screensize');
        h0 = figure( ...
            'Color',[0.8 0.8 0.8], ...
            'HandleVisibility','Off', ...
            'Interruptible', 'on', ...
            'MenuBar','none', ...
            'Name','ALS SR CONTROL', ...
            'NumberTitle','off', ...
            'Units','pixels', ...
            'Position',[30 p(4)-FigHeight-40 FigWidth FigHeight+Offset5], ...
            'Resize','off', ...
            'Tag','SRCTRLFig1');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'FontWeight','Bold', ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+6*(ButtonHeight+3)+19+19+8+Offset1  ButtonWidth 20+Offset5], ...
            'Style','text', ...
            'String','', ...
            'Tag','SRCTRLTitle');
        % Frame Box I
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+1*(ButtonHeight+3)+Offset1-3+Offset5 ButtonWidth+6 7*ButtonHeight+18], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+7*(ButtonHeight+3)+Offset1  ButtonWidth 15+Offset5], ...
            'Style','text', ...
            'String','Lattice Setup Functions');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Cycle'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+6*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Cycle SR Lattice', ...
            'Tag','SRCTRLButton1');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Injection'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+5*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Injection', ...
            'Tag','SRCTRLButton2');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Production'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+4*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String',['Production'], ...
            'Tag','SRCTRLButton3');
        h1 = uicontrol('Parent',h0, ...
            'Callback',[...
            'fprintf(''\n'');' ...
            'disp([''   **********************************************'']);', ...
            'disp([''   **  Changing Storage Ring Operational Mode  **'']);', ...
            'disp([''   **********************************************'']);', ...
            'setoperationalmode;', ...
            'srcontrol5(''CheckInputs'');', ...
            'disp([''   ****************************'']);', ...
            'disp([''   **  Mode Change Complete  **'']);', ...
            'disp([''   ****************************'']);', ...
            'fprintf(''\n'');'], ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+3*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'Value',1, ...
            'String','Change Operational Mode', ...
            'Tag','SRCTRLButtonChangeMode');
        h1 = uicontrol(...
            'Parent',h0, ...
            'Callback', [...
            'srcontrol5(''CheckInputs'');',...
            'srcontrol5(''SRState'');'], ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+2*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Check For Problems', ...
            'Tag','SRCTRLButtonSRState');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs''); goldenpage;', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+1*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Golden Page', ...
            'Tag','SRCTRLButtonGoldenPage');
        % Frame Box II
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+7*(ButtonHeight+3)-29+Offset2+Offset5 ButtonWidth+6 2*ButtonHeight+15], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+8*(ButtonHeight+3)-10+Offset2 ButtonWidth .6*ButtonHeight+Offset5], ...
            'String','Global/Local Orbit Correction', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''OrbitCorrection'');', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+7*(ButtonHeight+3)-6+Offset2+Offset5 ButtonWidth ButtonHeight], ...
            'String','Correct Global Orbit w/ IDBPMs', ...
            'Tag','SRCTRLButtonOrbitCorrection');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''OrbitCorrectionSetup'',1);', ...
            'callback','srcontrol5(''OrbitCorrectionSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[6 7*(ButtonHeight+3)-22+Offset2+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Edit IDBPM, CM, & Local Bump Lists', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonOrbitCorrectionSetup');
        % Frame Box III
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 1.25*(ButtonHeight)+Offset3-45+Offset5 ButtonWidth+6 8*ButtonHeight+5], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+7*(ButtonHeight+3)+Offset3-25 ButtonWidth .55*ButtonHeight+Offset5], ...
            'String','Orbit Feedback', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+6*(ButtonHeight+3)+Offset3-18+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Slow Orbit Correction', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxSOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+5*(ButtonHeight+3)+Offset3-9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Fast Orbit Correction', ...
            'Style','checkbox', ...
            'Value',FOFBcheckboxVal,...
            'Tag','SRCTRLCheckboxFOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+4*(ButtonHeight+3)+Offset3+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct ID Tune Shift  ', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxTune');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+3*(ButtonHeight+3)+Offset3+9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct RF Frequency', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxRF');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''Feedback'');', ...
            'Enable','on', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[8 3+3*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Start FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStart');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''StopOrbitFeedback'');pause(0);', ...
            'Enable','off', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[.5*FigWidth+3 3+3*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Stop FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStop');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[14 3+2*(ButtonHeight)+14+Offset3-25+Offset5 ButtonWidth-14 .75*ButtonHeight], ...
            'String','Horizontal RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHorizontal');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[26 3+1.25*(ButtonHeight)+16+Offset3-25+Offset5 ButtonWidth-26 .75*ButtonHeight], ...
            'String','Vertical RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextVertical');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FeedbackSetup'',1);', ...
            'callback','srcontrol5(''FeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 3+1.25*(ButtonHeight)+.5+Offset3-25+Offset5 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit SOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFeedbackSetup');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FastFeedbackSetup'',1);', ...
            'callback','srcontrol5(''FastFeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 3+1.25*(ButtonHeight)+.5+Offset3-45+Offset5 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit FOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFastFeedbackSetup');
        % Frame Box IV
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+ButtonHeight+Offset4-14+Offset5 ButtonWidth+6 ButtonHeight+12], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+1.75*ButtonHeight+5+Offset4-21+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Storage Ring State', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHeader');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''CheckInputs'');', ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ForegroundColor','b', ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+ButtonHeight+6+3+2+Offset4-22+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','   ', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextInformation');
        % Frame Box "Close"
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 8 ButtonWidth+6 ButtonHeight+8], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'Callback','close(gcbf);', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 13 ButtonWidth ButtonHeight], ...
            'String','Close', ...
            'Tag','SRCTRLClose');
        % Update database channels
        setsrstatechannels;
        if nargout > 0
            fig = h0;
        end
    case 'Cycle'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        disp('   **************************');
        disp('   **  Storage Ring Cycle  **');
        disp('   **************************');
        a = clock; fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        BSCFlag = questdlg(sprintf('Cycle Superbend Magnets?'),'SR Cycle','Yes','No','No');
        %if strcmp(BSCFlag,'No')
        %    disp(['   ** Superbends will not be cycled. **']);
        %else
        %    disp(['   ** Superbends will be cycled during the second mini-cycle only. **']);
        %end
        ChicSQFlag = questdlg(sprintf('Cycle chicanes and skew quads and home motor chicanes?'),'SR Cycle','Yes','No','No');
        %if strcmp(ChicSQFlag,'No')
        %    disp(['   ** Chicanes and skew quads will not be cycled; motor chicanes will not be homed. **']);
        %else
        %    disp(['   ** Chicanes and skew quads will be cycled; motor chicanes will be homed. **']);
        %end
        StartFlag = questdlg(sprintf('Start %.1f GeV Cycle?',SR_GEV),'SR Cycle','Yes','No','No');
        if strcmp(StartFlag,'No')
            disp(['   ***************************']);
            disp(['   **    Cycle  Canceled    **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        end
        try
            if GapFlag
                % Make sure that the gaps are open with FF off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open.');
                    disp('   Opening all gaps at maximum speed.');
                    setff([], 1, 0);
                    disp('   Gap control disabled.');
                    disp('   Feed forward enabled.');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened.');
                    disp('   Feed forward and gap control disabled.');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled.');
                end
            else
                disp('   Feed forward and gap control disabled.');
            end
            setff([], 0, 0);
            pause(1);
            srcycle(BSCFlag, ChicSQFlag);
            setpv('SR_STATE',1);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Cycle failed due to error condition! \n\n');
            setpv('SR_STATE',-1);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp('   **********************************************');
            disp('   **  SR Cycle complete, ready for injection  **');
            disp('   **********************************************'); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp('   **********************************');
            disp('   **  Problem cycling SR lattice  **');
            disp('   **********************************'); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
    case 'Injection'
        AD = getad;
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            fprintf('   ***************************************************\n');
            fprintf('   **  Setup For %.2f GeV Injection (with ramping)  **\n', getfamilydata('InjectionEnergy'));
            fprintf('   ***************************************************\n');
            set_alarmhandler_AHU_thresholds_inject;
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',getfamilydata('InjectionEnergy')),'Injection Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            fprintf('   *************************************************\n');
            fprintf('   **  Setup For On Energy Injection at %.2f GeV  **\n', SR_GEV);
            fprintf('   *************************************************\n');
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',SR_GEV),'Injection Setup','Yes','Cancel','Cancel');
        end
        if strcmp(StartFlag,'Cancel')
            disp(['   ********************************']);
            disp(['   **  Injection Setup Canceled  **']);
            disp(['   ********************************']);
            set_alarmhandler_thresholds;
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                setff([],1,0);
                disp('   Gap control disabled');
                disp('   Feed forward enabled');
                pause(1);
                % Set IDs at max velocity w/ velocity profile off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    disp('   Opening all gaps');
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                end
                disp('   Gaps are open');
                disp('   Feed forward and gap control disabled');
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            if (AD.Energy-AD.InjectionEnergy) > 0.05
                % Ramp down to Injection Energy
                ErrorFlag = srramp('Injection');
                if ErrorFlag
                    error('Superbends over temperature.');
                end
                a = clock; fprintf('   %s %d:%d:%.0f\n\n',date, a(4), a(5), a(6));
            elseif (AD.Energy-AD.InjectionEnergy) < -0.05
                % first load injection lattice, then ramp to 1.9 GeV and back to 1.5 GeV to get onto same hysteresis branch
                srload('Injection');
                % load 1.9 GeV lattice
                tempfilename = sprintf('%s19nuy9prod.mat', getfamilydata('Directory','OpsData'));
                srload(tempfilename);
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                pause(5);
            end
            srload('Injection');
            setpv('SR_STATE',2);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Injection lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-2);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            if AD.Energy <= 1.5
                disp(['   *******************************************************************************']);
                disp(['   **  Function complete:  the storage ring is setup for injection at ',sprintf('%.2f',SR_GEV),' GeV  **']);
                disp(['   *******************************************************************************']);
                fprintf('\n');
            else
                fprintf('   **********************************************************************************************\n');
                fprintf('   **  Function complete:  the storage ring is setup for injection at %.2f GeV (upper branch)  **\n', getfamilydata('InjectionEnergy'));
                fprintf('   **********************************************************************************************\n');
                fprintf('\n');
            end
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   ************************************']);
            disp(['   **  Problem with injection setup  **']);
            disp(['   ************************************']);
            fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        %soundchord;
        setfamilydata(0.8, 'BSCRampRate');
    case 'Production'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        AD=getad;
        fprintf('\n');
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            disp('   ********************************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation (with ramping)  **',SR_GEV));
            disp('   ********************************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            disp('   *****************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation  **',SR_GEV));
            disp('   *****************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Yes','Cancel','Cancel');
        end
        if strcmp(StartFlag,'Cancel')
            disp(['   ***************************']);
            disp(['   **  User Setup Canceled  **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                % Make sure that the gaps are open
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open');
                    disp('   Opening all gaps at maximum speed');
                    setff([], 1, 0);
                    disp('   Gap control disabled');
                    disp('   Feed forward enabled');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened');
                    disp('   Feed forward and gap control disabled');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled');
                end
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            % Ramp up to the production lattice
            ErrorFlag = srramp('Production');
            if ErrorFlag
                error('Superbends over temperature.');
            end
            a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            srload('Production');
            if GapFlag
                setff([], 1, 0);
                disp('   Gap control disabled');
                disp('   Feed forward enable');
                pause(1);
                disp('   Insertion device velocity profile boolean control off');
                disp('   Closing all gaps at maximum speed');
                % Set IDs at max velocity w/ velocity profile off
                [Position, Velocity, RunFlag, UserGap] = getid;
                setid([], UserGap, maxsp('IDvel'), 1, 0, 1);
                % Turn velocity profile on
                disp('   Insertion device velocity profile boolean control is on');
                setid([], [], maxsp('IDvel'), 1, 1, 0);
                disp('   Gaps are closed');
                setff([4;7;8;9;10;12], 1, 1);
                setff(5, 1, 0);
                disp('   Gap control enabled (except sector 5 (W16))');
            end
            set_alarmhandler_thresholds_new;
            setpv('SR_STATE',3);
        catch
            fprintf('   %s \n', lasterr);
            fprintf('   User lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-3);
        end
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp(['   **************************************************************************']);
            disp(['   **  Function complete:  the storage ring is setup for users at ',sprintf('%.1f',SR_GEV),' GeV  **']);
            disp(['   **************************************************************************']); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   *************************************']);
            disp(['   **  Problem with production setup  **']);
            disp(['   *************************************']); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        setfamilydata(0.8, 'BSCRampRate');
    case 'CheckInputs'
        SR_GEV = getfamilydata('Energy');
        AD=getad;
        setsrstatechannels;
        set(0,'showhiddenhandles','on');
        if AD.Energy > 1.55
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Down)']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users (Ramp Up)']);
        elseif AD.Energy < 1.45
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Up+cycle)']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV (Ramp Down)']);
        else
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV']);
        end
        set(findobj('Tag','SRCTRLTitle'),'String',SR_Mode);
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
        else
            set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
        end
        set(0,'showhiddenhandles','off');
    case 'SRState'
        NumErrors = 0;
        fprintf('\n');
        disp('   ***********************************');
        disp('   **  Checking Storage Ring State  **');
        disp('   ***********************************');
        a = clock;
        fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        %       FileName = getpv('SR_LATTICE_FILE','String');   % Last srload file name (in OLD MIDDLE LAYER nomenclature!!)
        GeVnow = bend2gev;
        if GeVnow == getfamilydata('Energy')
            [ConfigSetpoint, ConfigMonitor, FileName] = getproductionlattice;
        elseif GeVnow == getfamilydata('InjectionEnergy')
            [ConfigSetpoint, ConfigMonitor, FileName] = getinjectionlattice;
        else
            FileName = '';
        end
        [StateNumber, StateString] = getsrstate;
        fprintf('   Storage ring operational mode: %s\n', SR_Mode);
        if StateNumber < 0
            fprintf('   Storage ring state error: %s\n', StateString);
            NumErrors = NumErrors + 1;
        else
            fprintf('   Storage ring state: %s\n', StateString);
        end
        if StateNumber==0
            % Storage ring state unknown
            NumErrors = NumErrors + 1;
        elseif abs(StateNumber)==1 || abs(StateNumber)==2
            FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','InjectionFile') '.mat'];
            if ~strcmp(FileName, FileNameGoal)
                fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','InjectionFile'), FileName);
                NumErrors = NumErrors + 1;
            end
        else
            FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile') '.mat'];
            if ~strcmp(FileName, FileNameGoal)
                fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','LatticeFile'), FileName);
                NumErrors = NumErrors + 1;
            end
        end
        % Check all SR magnets
        if isempty(FileName)
            fprintf('   Goal setpoints will not be checked since the last lattice load is unknown.\n');
            NumErrors1 = checksrmags('');
        else
%            NumErrors1 = checksrmags([getfamilydata('Directory','OpsData') FileName]);
            NumErrors1 = checksrmags(FileName);
        end
        if NumErrors1 == 0
            fprintf('   SR magnets power supplies are OK.\n');
        end
        NumErrors = NumErrors + NumErrors1;
        % Check RF frequency
        if isempty(FileName)
            fprintf('   RF frequency will not be checked since the last lattice load is unknown.\n');
        else
%            load([getfamilydata('Directory','OpsData'), FileName]);
            load(FileName);
            [tmp, RFHPCounterPresent] = getrf;
            if abs(RFHPCounterPresent-ConfigSetpoint.RF.Setpoint.Data) > .002
                NumErrors = NumErrors + 1;
                fprintf('   RF frequency should be %f, presently it is %f MHz (as measured by the HP counter).\n', ConfigSetpoint.RF.Setpoint.Data, RFHPCounterPresent);
            else
                fprintf('   RF frequency is OK (HP counter is %f MHz, at the time of the lattice save it was %f MHz).\n', RFHPCounterPresent, ConfigSetpoint.RF.Setpoint.Data);
            end
        end
        % Check for orbit problems
        if (StateNumber >= 3) & (getdcct > 2)   % Production lattice is loaded with beam in the machine
            Xtol = 0.070;
            Ytol = 0.010;
            NumErrors1 = checksrorbit([],Xtol,Ytol);
            if NumErrors1
                fprintf('   SR orbit in the ID straight sections or at Bergoz BPMs deviates more than allowed from the golden orbit.\n');
            else
                fprintf('   SR orbit in the ID straight sections and at Bergoz BPMs is OK.\n');
                fprintf('   The orbit is within %.3f mm horizontally and %.3f mm vertically', Xtol, Ytol);
            end
            NumErrors = NumErrors + NumErrors1;
        else
            fprintf('   Storage ring orbit was not checked.\n');
        end
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        if NumErrors
            disp('   *********************************');
            disp('   **  Storage Ring Has Problems  **');
            disp('   *********************************');
        else
            disp('   **********************************');
            disp('   **  Storage Ring Lattice is OK  **');
            disp('   **********************************');
        end
        fprintf('   \n');
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
        end
        set(0,'showhiddenhandles','off');
    case 'OrbitCorrection'
        fprintf('\n');
        fprintf('   *********************************\n');
        fprintf('   **  Starting Orbit Correction  **\n');
        fprintf('   *********************************\n');
        a = clock;
        fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        StartFlag = questdlg(sprintf('Start orbit correction, %.1f GeV?',SR_GEV),'Orbit Correction','Yes','No','No');
        if strcmp(StartFlag,'No')
            disp(['   ********************************']);
1000             disp(['   **  Orbit Correction Aborted  **']);
1001             disp(['   ********************************']);
1002             fprintf('\n');
1003             return
1004         end
1005
1006         if getdcct < 5     % Don't correct the orbit if the current is too small
1007             fprintf('   Orbit not corrected due to small current.\n');
1008             return
1009         end
1010
1011         if abs(SR_GEV-bend2gev(getpv('BEND',[1 1])))>  0.05     % Don't use this routine for the injection lattice
1012             fprintf('   This routine should only be used for the production energy: Correction aborted\n');
1013             return
1014         end
1015
1016         SR_STATE_OLD = scaget('SR_STATE');
1017         set(0,'showhiddenhandles','on');
1018         setpv('SR_STATE',4);
1019         [StateNumber, StateString] = getsrstate;
1020         if StateNumber >= 0
1021             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1022         else
1023             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1024         end
1025         set(0,'showhiddenhandles','off');
1026
1027
1028         try
1029
1030             % 2 Hz update rate on IDBPMs
1031             disp('   IDBPM time constant set to 0.5s.')
1032             setbpmtimeconstant(0.5)
1033             pause(2);
1034
1035
1036             % Turn off feed forward
1037             fprintf('   Turning feed forward off.\n');
1038             [FFEnableBM, FFEnableBC] = getff;
1039             setff([], 0);
1040             scasleep(.2);
1041
1042
1043             % Get vectors
1044             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1045             LocalBumplist = FB.LocalBumplist;
1046
1047         catch
1048
1049             fprintf('   %s \n',lasterr);
1050             fprintf('   Orbit correction setup failed due to error condition! \n\n');
1051             setpv('SR_STATE',-4);
1052             set(0,'showhiddenhandles','on');
1053             [StateNumber, StateString] = getsrstate;
1054             if StateNumber >= 0
1055                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1056             else
1057                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1058             end
1059             set(0,'showhiddenhandles','off');
1060             return
1061
1062         end
1063
1064         iNotHCMChicane = find(FB.HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
1065         iHCMChicane = find(FB.HCMlist1(:,2) == 10);
1066         iNotVCMChicane = find(FB.VCMlist1(:,2) < 10);
1067         iVCMChicane = find(FB.VCMlist1(:,2) == 10);
1068
1069         fprintf('   Starting horizontal and vertical global orbit correction (SVD method).\n');
1070
1071         for iloop = 1:3
1072             try
1073                 % use the following to get corrector settings in OCS without setting them, so the values can be checked
1074                 FB.OCSx = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
1075                 FB.OCSy = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
1076                 if any(abs(FB.OCSx.CM.Delta(iNotHCMChicane)) > 5)
1077                   disp('   Orbit Correction is changing some horizontal corrector(s) > 5A!!');
1078                 end
1079                 if any(abs(FB.OCSy.CM.Delta(iNotVCMChicane)) > 5)
1080                   disp('   Orbit Correction is changing some vertical corrector(s) > 5A!!');
1081                 end
1082                 if any(abs(FB.OCSx.CM.Delta(iHCMChicane)) > 10)
1083                   disp('   Orbit Correction is changing some horizontal chicane corrector(s) > 10A!!');
1084                 end
1085                 if any(abs(FB.OCSy.CM.Delta(iVCMChicane)) > 10)
1086                   disp('   Orbit Correction is changing some vertical chicane corrector(s) > 10A!!');
1087                 end
1088
1089
1090                 % Correct horizontal orbit
1091                 FB.OCSx = setorbit(FB.OCSx,'NoDisplay');
1092                 % Correct vertical orbit
1093                 FB.OCSy = setorbit(FB.OCSy,'NoDisplay');
1094
1095
1096                 % Check for current in machine - stop orbit correction if DCCT < 5mA
1097                 if (getdcct < 4.5)
1098                     error('**There is less than 5mA in the machine! Stopping orbit correction.');
1099                 end
1100
1101                 % Check state of gaps - stop orbit correction if any are moving
1102                 GAPrunflag = getpv('ID','RunFlag');
1103                 if any(GAPrunflag-round(GAPrunflag))
1104                     error('**One or more of the gaps are moving! Stopping orbit correction.');
1105                 end
1106
1107                 x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
1108                 y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
1109                 fprintf('   %d. Horizontal RMS = %.3f mm\n', iloop, norm(x)/sqrt(length(x)));
1110                 fprintf('   %d.   Vertical RMS = %.3f mm\n', iloop, norm(y)/sqrt(length(y)));
1111
1112             catch
1113                 % fprintf('   %s \n',lasterr);
1114                 fprintf('   Orbit correction failed due to error condition!\n  Fix the problem, reload the lattice (srload), and try again.  \n\n');
1115                 setpv('SR_STATE',-4);
1116                 set(0,'showhiddenhandles','on');
1117                 [StateNumber, StateString] = getsrstate;
1118                 if StateNumber >= 0
1119                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1120                 else
1121                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1122                 end
1123                 set(0,'showhiddenhandles','off');
1124                 return
1125             end
1126         end
1127
1128
1129         % Set user bumps w/o sextupole correctors
1130         try
1131
1132             %turn up corrector speed here to quicken setting bumps
1133             HCMramprate = getpv('HCM', 'RampRate');
1134             VCMramprate = getpv('VCM', 'RampRate');
1135             setpv('HCM', 'RampRate', 10, [], 0);
1136             setpv('VCM', 'RampRate', 10, [], 0);
1137
1138             if ~isempty(LocalBumplist)
1139                 fprintf('   Setting local bumps in the straight sections.\n');
1140                 for loop = 1:size(LocalBumplist,1)
1141
1142                     % Check for current in machine - stop orbit correction if DCCT < 5mA
1143                     if (getdcct < 5)
1144                         error('** There is less than 5mA in the machine! Stopping local bumps.');
1145                     end
1146
1147                     % Check state of gaps - stop setting bumps if any are moving
1148                     GAPrunflag = getpv('ID','RunFlag');
1149                     if any(GAPrunflag-round(GAPrunflag))
1150                         error('** One or more of the gaps are moving! Stopping local bumps.');
1151                     end
1152
1153                     HCMoldsp = getsp('HCM', FB.HCMlist1);
1154                     VCMoldsp = getsp('VCM', FB.VCMlist1);
1155
1156                     if any(LocalBumplist(loop,1) == [4 6 11])
1157                         if LocalBumplist(loop,2) == 0
1158                             % Upstream bump
1159                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1160                             if isempty(iRemove)
1161                                 setbumps(LocalBumplist(loop,:), 1);
1162                             else
1163                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1164                             end
1165                         elseif LocalBumplist(loop,2) == 1
1166                             % Upstream bump
1167                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;],FB.OCSx.BPM.DeviceList);
1168                             if isempty(iRemove)
1169                                 setbumps(LocalBumplist(loop,:), 1);
1170                             else
1171                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1172                             end
1173                         else
1174                             % Downstream bump
1175                             [i, iRemove] = findrowindex([LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1176                             if isempty(iRemove)
1177                                 setbumps(LocalBumplist(loop,:), 1);
1178                             else
1179                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1180                             end
1181                         end
1182                     else
1183                         [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1184                         if isempty(iRemove)
1185                             setbumps(LocalBumplist(loop,:), 1);
1186                         else
1187                             fprintf('\n   BPMs missing from Sector %02d - skipping local bump for that sector.\n\n', LocalBumplist(loop,1));
1188                         end
1189                     end
1190
1191                     HCMnewsp = getsp('HCM', FB.HCMlist1);
1192                     VCMnewsp = getsp('VCM', FB.VCMlist1);
1193                     % Remove center chicane trim from corrector check
1194                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 5) | (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 10)
1195                         error('**Setbumps caused some corrector magnet currents to change by more than 5(Horiz)/10(Vert) A!');
1196                     end
1197                     % Now check center chicane trims
1198                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 10) | (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 15)
1199                         error('**Setbumps caused some chicane trim magnet currents to change by more than 10(Horiz)/15(Vert) A!');
1200                     end
1201                 end
1202             end
1203
1204             %restore corrector speeds
1205             setpv('HCM', 'RampRate', HCMramprate, [], 0);
1206             setpv('VCM', 'RampRate', VCMramprate, [], 0);
1207
1208         catch
1209             fprintf('   %s \n',lasterr);
1210             fprintf('   Setbumps failed due to error condition!  Fix the problem, reload the lattice (srload), and try again.\n\n');
1211             setpv('SR_STATE',-4);
1212             set(0,'showhiddenhandles','on');
1213             [StateNumber, StateString] = getsrstate;
1214             if StateNumber >= 0
1215                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1216             else
1217                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1218             end
1219             set(0,'showhiddenhandles','off');
1220             return
1221         end
1222
1223
1224         % Turn feed forward back to it's original state
1225         if any(FFEnableBC)
1226             fprintf('   Turning feed forward back on.\n');
1227             setff([], FFEnableBC);
1228         end
1229
1230
1231         a = clock;
1232         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1233         [StateNumber, StateString] = getsrstate;
1234         set(0,'showhiddenhandles','on');
1235         if StateNumber >= 0
1236             setpv('SR_STATE',4.1);
1237             [StateNumber, StateString] = getsrstate;
1238             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1239             fprintf('   *********************************\n');
1240             fprintf('   **  Orbit Correction Complete  **\n');
1241             fprintf('   *********************************\n\n');
1242         else
1243             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1244             fprintf('   *************************************\n');
1245             fprintf('   **  Problem With Orbit Correction  **\n');
1246             fprintf('   *************************************\n\n');
1247         end
1248         set(0,'showhiddenhandles','off');
1249         pause(0);
1250
1251
1252     case 'OrbitCorrectionSetup'
1253         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
1254
1255         if InitFlag
1256             % Setup feedback elements
1257             % disp('Orbit correction condition: InitFlag=1 -- debugging message');
1258
1259             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1260             % Edit the following lists to change default configuration of Orbit Correction %
1261             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1262             hlist=[];vlist=[];
1263             for Sector =1:12
1264                 if Sector == 1
1265                     vlist = [vlist;Sector 2;Sector 4;Sector 5;Sector 8];
1266                     hlist = [hlist;Sector 2;Sector 7];
1267                 elseif Sector == 3
1268                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1269                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1270                 elseif Sector == 5
1271 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1272 %                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1273                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8]; %remove HCM and VCM(5,10) since corrector is not controlling starting 4-6-07
1274                     hlist = [hlist;Sector 2;Sector 7];
1275                 elseif Sector == 10
1276                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1277                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1278                 elseif Sector == 12
1279                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 7];
1280                     hlist = [hlist;Sector 2;Sector 7];
1281                 else
1282                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8];
1283                     hlist = [hlist;Sector 2;Sector 7];
1284                 end
1285             end
1286             HCMlist1 = hlist;
1287             VCMlist1 = vlist;
1288
1289             BPMlist1 = [
1290                 1 2
1291                 1 5
1292                 1 6
1293                 1 10
1294                 2 1
1295                 2 5
1296                 2 6
1297                 2 9
1298                 3 2
1299                 3 5
1300                 3 6
1301                 3 10
1302                 3 11
1303                 3 12
1304                 4 1
1305                 4 5
1306                 4 6
1307                 4 10
1308                 5 1
1309                 5 5
1310                 5 6
1311                 5 10
1312 %                 5 11
1313 %                 5 12
1314                 6 1
1315                 6 5
1316                 6 6
1317                 6 10
1318                 7 1
1319                 7 5
1320                 7 6
1321                 7 10
1322                 8 1
1323                 8 5
1324                 8 6
1325                 8 10
1326                 9 1
1327                 9 5
1328                 9 6
1329                 9 10
1330                 10 1
1331                 10 5
1332                 10 6
1333                 10 10
1334                 10 11
1335                 10 12
1336                 11 1
1337                 11 5
1338                 11 6
1339                 11 10
1340                 12 1
1341                 12 5
1342                 12 6
1343                 12 9];
1344
1345             % SVD orbit correction
1346             Xivec = [1:27];
1347             Yivec = [1:48];
1348
1349
1350             LocalBumplist = [
1351               % 1 1
1352               % 2 1
1353               % 3 1
1354                 4 1
1355               % 4 2
1356                 5 1
1357               % 6 1
1358               % 6 2
1359                 7 1
1360                 8 1
1361                 9 1
1362                 10 1
1363                 11 1
1364                 11 2
1365                 12 1
1366 ];
1367             %LocalBumplist = []
1368
1369             % initialize RFCorrFlag
1370             RFCorrFlag = 'Yes';
1371         else
1372
1373             % Get vectors
1374             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1375             BPMlist1 = FB.BPMlist1;
1376             HCMlist1 = FB.HCMlist1;
1377             VCMlist1 = FB.VCMlist1;
1378             Xivec = FB.Xivec;
1379             Yivec = FB.Yivec;
1380             LocalBumplist = FB.LocalBumplist;
1381             Xgoal = FB.Xgoal;
1382             Ygoal = FB.Ygoal;
1383             RFCorrFlag = FB.RFCorrFlag;
1384
1385             % Add button to change #ivectors, CMs, IDBPMs,
1386             EditFlag = 0;
1387             h_fig1 = figure;
1388             while EditFlag ~= 8
1389
1390                 % Sensitivity matrix
1391                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
1392                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
1393
1394                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1395                 % Can the call below work for setting FOFB RF parameter? %
1396                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1397                 if strcmpi(RFCorrFlag, 'Yes')
1398                     Sx = [Sx getdisp('BPMx',BPMlist1)];
1399                 end
1400
1401                 [Ux, SVx, Vx] = svd(Sx);
1402                 [Uy, SVy, Vy] = svd(Sy);
1403
1404
1405                 % Remove singular values greater than the actual number of singular values
1406                 i = find(Xivec>length(diag(SVx)));
1407                 if ~isempty(i)
1408                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
1409                     pause(0);
1410                     Xivec(i) = [];
1411                 end
1412                 i = find(Yivec>length(diag(SVy)));
1413                 if ~isempty(i)
1414                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
1415                     pause(0);
1416                     Yivec(i) = [];
1417                 end
1418
1419
1420                 Ax = Sx*Vx(:,Xivec);
1421                 Tx = inv(Ax'*Ax)*Ax';
1422
1423                 Ay = Sy*Vy(:,Yivec);
1424                 Ty = inv(Ay'*Ay)*Ay';
1425
1426
1427                 figure(h_fig1);
1428                 subplot(2,1,1);
1429                 semilogy(diag(SVx),'b');
1430                 hold on;
1431                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
1432                 ylabel('Horizontal');
1433                 title('Response Matrix Singular Values');
1434                 hold off;
1435                 subplot(2,1,2);
1436                 semilogy(diag(SVy),'b');
1437                 hold on;
1438                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
1439                 xlabel('Singular Value Number');
1440                 ylabel('Vertical');
1441                 hold off;
1442                 drawnow;
1443
1444                 if strcmp(RFCorrFlag,'No')
1445                     RFCorrState = 'NOT CORRECTED';
1446                 elseif strcmp(RFCorrFlag,'Yes')
1447                     RFCorrState = 'CORRECTED';
1448                 else
1449                     RFCorrState = '???';
1450                 end
1451
1452                 %         EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','HCM Chicane List','VCM Chicane List','IDBPM List','BBPM List','Change Golden Orbit',...
1453                 %            'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1454                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','BPM List','Change Golden Orbit',...
1455                     'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1456
1457                 if EditFlag == 1
1458                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
1459                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
1460                     titlestr='SVD Orbit Feedback';
1461                     lineNo=1;
1462                     answer=inputdlg(prompt,titlestr,lineNo,def);
1463                     if ~isempty(answer)
1464                         XivecNew = fix(str2num(answer{1}));
1465                         if isempty(XivecNew)
1466                             disp('   Horizontal E-vector cannot be empty.  No change made.');
1467                         else
1468                             if any(XivecNew<=0) | max(XivecNew)>length(diag(SVx))
1469                                 disp('   Error reading horizontal E-vector.  No change made.');
1470                             else
1471                                 Xivec = XivecNew;
1472                             end
1473                         end
1474                         YivecNew = fix(str2num(answer{2}));
1475                         if isempty(YivecNew)
1476                             disp('   Vertical E-vector cannot be empty.  No change made.');
1477                         else
1478                             if any(YivecNew<=0) | max(YivecNew)>length(diag(SVy))
1479                                 disp('   Error reading vertical E-vector.  No change made.');
1480                             else
1481                                 Yivec = YivecNew;
1482                             end
1483                         end
1484                     end
1485                 end
1486
1487                 if EditFlag == 2
1488                     List = getlist('HCM');
1489                     CheckList = zeros(size(List,1));
1490                     Elem = dev2elem('HCM', HCMlist1);
1491                     CheckList(Elem) = ones(size(Elem));
1492                     CheckList = CheckList(dev2elem('HCM',List));
1493                     newList = editlist(List, 'HCM', CheckList);
1494                     if isempty(newList)
1495                         fprintf('   Horizontal corrector magnet list cannot be empty.  No change made.\n');
1496                     else
1497                         HCMlist1 = newList;
1498                     end
1499                 end
1500
1501                 if EditFlag == 3
1502                     List = getlist('VCM');
1503                     CheckList = zeros(size(List,1));
1504                     Elem = dev2elem('VCM', VCMlist1);
1505                     CheckList(Elem) = ones(size(Elem));
1506                     CheckList = CheckList(dev2elem('VCM',List));
1507                     newList = editlist(List, 'VCM', CheckList);
1508                     if isempty(newList)
1509                         fprintf('   Vertical corrector magnet cannot be empty.  No change made.\n');
1510                     else
1511                         VCMlist1 = newList;
1512                     end
1513                 end
1514
1515                 if EditFlag == 4
1516                     ListOld = BPMlist1;
1517                     XgoalOld = Xgoal;
1518                     YgoalOld = Ygoal;
1519
1520                     % Full BPM list
1521                     List = [
1522                         1 2
1523                         1 5
1524                         1 6
1525                         1 10
1526                         2 1
1527                         2 5
1528                         2 6
1529                         2 9
1530                         3 2
1531                         3 5
1532                         3 6
1533                         3 10
1534                         3 11
1535                         3 12
1536                         4 1
1537                         4 5
1538                         4 6
1539                         4 10
1540                         5 1
1541                         5 5
1542                         5 6
1543                         5 10
1544                         5 11
1545                         5 12
1546                         6 1
1547                         6 5
1548                         6 6
1549                         6 10
1550                         7 1
1551                         7 5
1552                         7 6
1553                         7 10
1554                         8 1
1555                         8 5
1556                         8 6
1557                         8 10
1558                         9 1
1559                         9 5
1560                         9 6
1561                         9 10
1562                         10 1
1563                         10 5
1564                         10 6
1565                         10 10
1566                         10 11
1567                         10 12
1568                         11 1
1569                         11 5
1570                         11 6
1571                         11 10
1572                         12 1
1573                         12 5
1574                         12 6
1575                         12 9
1576                         ];
1577
1578                     CheckList = zeros(size(List,1),1);
1579                     if ~isempty(BPMlist1)
1580                         for i = 1:size(List,1)
1581                             k = find(List(i,1)==BPMlist1(:,1));
1582                             l = find(List(i,2)==BPMlist1(k,2));
1583
1584                             if isempty(k) | isempty(l)
1585                                 % Item not in list
1586                             else
1587                                 CheckList(i) = 1;
1588                             end
1589                         end
1590                     end
1591
1592                     newList = editlist(List, 'BPM', CheckList);
1593                     if isempty(newList)
1594                         fprintf('   BPM list cannot be empty.  No change made.\n');
1595                     else
1596                         BPMlist1 = newList;
1597                     end
1598
1599                     % Set the goal orbit to the golden orbit
1600                     Xgoal = getgolden('BPMx', BPMlist1);
1601                     Ygoal = getgolden('BPMy', BPMlist1);
1602
1603
1604                     % If a new BPM is added, then set the goal orbit to the golden orbit
1605                     for i = 1:size(BPMlist1,1)
1606
1607                         % Is it a new BPM?
1608                         k = find(BPMlist1(i,1)==ListOld(:,1));
1609                         l = find(BPMlist1(i,2)==ListOld(k,2));
1610
1611                         if isempty(k) | isempty(l)
1612                             % New BPM
1613                         else
1614                             % Use the old value for old BPM
1615                             Xgoal(i) = XgoalOld(k(l));
1616                             Ygoal(i) = YgoalOld(k(l));
1617                         end
1618                     end
1619                 end
1620
1621                 if EditFlag == 5
1622
1623                     ChangeList = editlist(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
1624                     for i = 1:size(ChangeList,1)
1625
1626                         k = find(ChangeList(i,1)==BPMlist1(:,1));
1627                         l = find(ChangeList(i,2)==BPMlist1(k,2));
1628
1629                         prompt = {sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
1630                         def = {sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
1631                         titlestr = 'CHANGE THE GOAL ORBIT';
1632                         lineNo = 1;
1633                         answer = inputdlg(prompt, titlestr, lineNo, def);
1634
1635                         if isempty(answer)
1636                             % No change
1637                             fprintf('   No change was made to the golden orbit.\n');
1638                         else
1639                             Xgoalnew = str2num(answer{1});
1640                             if isempty(Xgoalnew)
1641                                 fprintf('   No change was made to the horizontal golden orbit.\n');
1642                             else
1643                                 Xgoal(k(l)) = Xgoalnew;
1644                             end
1645
1646                             Ygoalnew = str2num(answer{2});
1647                             if isempty(Ygoalnew)
1648                                 fprintf('   No change was made to the vertical golden orbit.\n');
1649                             else
1650                                 Ygoal(k(l)) = Ygoalnew;
1651                             end
1652                         end
1653                     end
1654                     if ~isempty(ChangeList)
1655                         fprintf('   Note:  changing the goal orbit for "Orbit Correction" does not change the goal orbit for "Slow Orbit Feedback."\n');
1656                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
1657                     end
1658                 end
1659
1660                 if EditFlag == 6
1661                     List = [
1662                         1 1
1663                         2 1
1664                         3 1
1665                         4 1
1666                         4 2
1667                         5 1
1668                         6 1
1669                         6 2
1670                         7 1
1671                         8 1
1672                         9 1
1673                         10 1
1674                         11 1
1675                         11 2
1676                         12 1];
1677                     CheckList = zeros(size(List,1),1);
1678                     if ~isempty(LocalBumplist)
1679                         for i = 1:size(List,1)
1680                             k = find(List(i,1)==LocalBumplist(:,1));
1681                             l = find(List(i,2)==LocalBumplist(k,2));
1682
1683                             if isempty(k) | isempty(l)
1684                                 % Item not in list
1685                             else
1686                                 CheckList(i) = 1;
1687                             end
1688                         end
1689                     end
1690                     LocalBumplist = editlist2(List, 'Sector', CheckList);
1691                 end
1692
1693                 if EditFlag == 7
1694                     RFCorrFlag = questdlg(sprintf('Set RF Frequency during Orbit Correction?'),'RF Frequency','Yes','No', 'No');
1695                     if strcmp(RFCorrFlag,'No')
1696                         disp(['   RF Frequency will not be included in global orbit correction.']);
1697                     elseif strcmp(RFCorrFlag,'Yes')
1698                         disp(['   RF Frequency will be included in global orbit correction.']);
1699                     end
1700
1701                 end
1702             end
1703             close(h_fig1);
1704         end
1705
1706 %  ORBIT CORRECTION STRUCTURE (OCS)
1707 %    OCS.BPM (data structure)
1708 %    OCS.CM  (data structure)
1709 %    OCS.GoalOrbit
1710 %    OCS.NIter
1711 %    OCS.SVDIndex
1712 %    OCS.IncrementalFlag = 'Yes'/'No'
1713 %    OCS.BPMWeight
1714 %    OCS.Flags = { 'FitRF' , etc.  }
1715         OCSx.BPM = getx(BPMlist1, 'struct');
1716         OCSx.CM = getsp('HCM', HCMlist1, 'struct');
1717         OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
1718         OCSx.NIter = 1;
1719         OCSx.SVDIndex = Xivec;
1720         OCSx.IncrementalFlag = 'No';
1721         OCSx.FitRF = 1;
1722         OCSy.BPM = gety(BPMlist1, 'struct');
1723         OCSy.CM = getsp('VCM', VCMlist1, 'struct');
1724         OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
1725         OCSy.NIter = 1;
1726         OCSy.SVDIndex = Yivec;
1727         OCSy.IncrementalFlag = 'No';
1728         OCSy.FitRF = 0;
1729
1730         % Save vectors
1731         FB.OCSx = OCSx;
1732         FB.OCSy = OCSy;
1733
1734         FB.BPMlist1 = BPMlist1;
1735         FB.HCMlist1 = HCMlist1;
1736         FB.VCMlist1 = VCMlist1;
1737         FB.Xivec = Xivec;
1738         FB.Yivec = Yivec;
1739         FB.Xgoal = OCSx.GoalOrbit;
1740         FB.Ygoal = OCSy.GoalOrbit;
1741         FB.RFCorrFlag = RFCorrFlag;
1742         FB.LocalBumplist = LocalBumplist;
1743         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata',FB);
1744
1745
1746     case 'Feedback'
1747
1748         FBloopIter = 1;
1749         if get(findobj(gcbf,'Tag','SRCTRLCheckboxFOFB'),'Value') == 1
1750             StartFOFBFlag = 1;
1751         else
1752             StartFOFBFlag = 0;
1753         end
1754
1755         FEEDBACK_STOP_FLAG = 0;
1756         HWarnNum=0;
1757         VWarnNum=0;
1758
1759         SR_GeV = getenergy;
1760         % Feedback loop setup
1761         PlotInfoFlag = 0;           % Plot micado stuff
1762         LoopDelay = 1.0;           % Period of feedback loop [seconds], make sure the BPM averaging is correct
1763         VCM_LSB = .00366211;
1764         VCMCHICANE_LSB = .002441;   % 80 max?,  Note: not fully implemented
1765
1766         if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
1767             Xgain  = 0.2;
1768             Ygain  = 0.1;
1769         else
1770             Xgain  = 0.8; % raised 0.5->0.8 at 17:20, 3-2-05 to more quickly correct EPU4 fast switching orbit distortions
1771             Ygain  = 0.8;
1772         end
1773
1774         % Load lattice set for tune feed forward
1775         ConfigSetpoint = getproductionlattice;
1776         %load([getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile')]);
1777         QFsp = ConfigSetpoint.QF.Setpoint.Data;
1778         QDsp = ConfigSetpoint.QD.Setpoint.Data;
1779         TuneW16Min = gap2tune(5, 13.23, 1.8909);
1780         % Tune response matrix
1781         SR_TUNE_MATRIX = gettuneresp({'QF','QD'}, {[],[]}, getenergy('Production'));    % Approx. [0.1944 -0.0286;-0.1182 0.1526];
1782         %SR_TUNE_MATRIX = [0.1641 -0.0245
1783         %                 -0.1149 0.1477];
1784
1785         % ID tune compensation does not work in the injection lattice, so ...
1786         if abs(SR_GEV - bend2gev)>  0.05     % Don't use this routine for the injection lattice
1787             fprintf('   This routine should only be used for the production energy: Orbit feedback aborted\n');
1788             return
1789         end
1790
1791         set(0,'showhiddenhandles','on');
1792
1793         try
1794             fprintf('\n');
1795             fprintf('   *******************************\n');
1796             fprintf('   **  Starting Orbit Feedback  **\n');
1797             fprintf('   *******************************\n');
1798             a = clock;
1799             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1800             fprintf('   Note: the Matlab command window will be used to display status information.\n');
1801             fprintf('         It cannot be used to enter commands during slow orbit feedback.\n');
1802
1803
1804             % >= 2 Hz update rate on IDBPMs
1805             disp('   IDBPM time constant set to 0.2s.')
1806             setbpmtimeconstant(0.2)
1807             pause(1.1);
1808
1809             % Check whether bumps and kickers are on and warn to turn off before starting feedback if necessary
1810             try
1811                 if (getsp('SR01S___BUMP1__BC21')==1 & getsp('SR01S___BUMP1P_BC22')==1) | (getsp('SR01S___SEK____BC21')==1 & getsp('SR01S___SEK_P__BC23')==1) | (getsp('SR01S___SEN____BC20')==1 & getsp('SR01S___SEN_P__BC22')==1)
1812                     soundtada;
1813                     fprintf('   \n');
1814                     fprintf('   *********************************************************************************\n');
1815                     fprintf('   ** One or more of the pulsed SR injection magnets is still on!  Turn them off! **\n');
1816                     fprintf('   *********************************************************************************\n');
1817                     fprintf('   \n');
1818                 end
1819             catch
1820                 disp('**Problem checking the state of the bumps and kickers - please check that they are not pulsing.');
1821             end
1822
1823             % Get vectors
1824
1825             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
1826
1827             BPMlist1 = FB.OCSx.BPM.DeviceList;
1828             % FOFB_BPMlist =
1829             HCMlist1 = FB.HCMlist1;
1830             VCMlist1 = FB.VCMlist1;
1831             Xivec = FB.Xivec;
1832             Yivec = FB.Yivec;
1833             Xgoal = FB.OCSx.GoalOrbit;
1834             Ygoal = FB.OCSy.GoalOrbit;
1835             FFTypeFlag = FB.FFTypeFlag;   %local or global tune correction
1836
1837             iNotHCMChicane = find(HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
1838             iHCMChicane = find(HCMlist1(:,2) == 10);
1839             iNotVCMChicane = find(VCMlist1(:,2) < 10);
1840             iVCMChicane = find(VCMlist1(:,2) == 10);
1841
1842             % Sensitivity matrix for setting fast feedback setpoints
1843             Sx1 = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
1844             Sy1 = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
1845
1846         catch
1847             fprintf('\n  %s \n',lasterr);
1848
1849             % >= 2 Hz update rate on IDBPMs
1850             disp('   IDBPM time constant set to 0.25s.')
1851             setbpmtimeconstant(0.25)
1852
1853
1854             a = clock;
1855             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1856             fprintf('   *************************************************************\n');
1857             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
1858             fprintf('   *************************************************************\n\n');
1859             set(0,'showhiddenhandles','off');
1860             pause(0);
1861
1862             return
1863         end
1864
1865         StartFlag = questdlg(strvcat('','Is it OK to start orbit feedback?'),'Orbit Feedback','Yes','No','No');
1866         if strcmp(StartFlag,'No')
1867             % >= 2 Hz update rate on IDBPMs
1868             disp('   IDBPM time constant set to 0.25s.')
1869             setbpmtimeconstant(0.25)
1870
1871             a = clock;
1872             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1873             fprintf('   ***************************\n');
1874             fprintf('   **  Orbit Feedback Exit  **\n');
1875             fprintf('   ***************************\n\n');
1876             pause(0);
1877             return
1878         end
1879
1880         SR_STATE_OLD = scaget('SR_STATE');
1881         setpv('SR_STATE', 5);
1882         set(0,'showhiddenhandles','on');
1883         [StateNumber, StateString] = getsrstate;
1884         if StateNumber >= 0
1885             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1886         else
1887             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1888         end
1889         fprintf('   Using %d E-vectors horizontally.\n', length(Xivec));
1890         fprintf('   Using %d E-vectors vertically.\n',   length(Yivec));
1891         fprintf('   Starting slow orbit correction every %.1f seconds.\n', LoopDelay);
1892         %  fprintf('   Resetting SR11 chicane motors every 20 seconds to fix drift problem.\n');
1893
1894         IDSector = getlist('ID');
1895         EPUlist = find((IDSector(:,1)==4) | (IDSector(:,1)==11));
1896         oldgap=210*ones(size(IDSector,1),1);
1897         oldShift=zeros(size(oldgap));
1898
1899         try
1900
1901             % Get and display data
1902             x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
1903             y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
1904             STDx = norm(x)/sqrt(length(x));
1905             STDy = norm(y)/sqrt(length(y));
1906             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
1907             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
1908
1909             % write goldenorbit values to Fast Orbit Feedback
1910             try
1911                 write_goldenorbit_ffb;
1912             catch
1913                 disp('write_goldenorbit_ffb did not work!');
1914             end
1915             setpv('SR01____FFBON__BC00',2);
1916             pause(0);
1917
1918         catch
1919
1920             fprintf('\n  %s \n',lasterr);
1921
1922             % >= 2 Hz update rate on IDBPMs
1923             disp('   IDBPM time constant set to 0.25s.')
1924             setbpmtimeconstant(0.25);
1925
1926
1927             a = clock;
1928             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1929             fprintf('   *************************************************************\n');
1930             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
1931             fprintf('   *************************************************************\n\n');
1932
1933             setpv('SR_STATE',SR_STATE_OLD);
1934             [StateNumber, StateString] = getsrstate;
1935             if StateNumber >= 0
1936                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1937             else
1938                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1939             end
1940             set(0,'showhiddenhandles','off');
1941             pause(0);
1942
1943             return
1944
1945         end
1946
1947
1948         % Disable buttons
1949         set(0,'showhiddenhandles','on');
1950         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','off');
1951         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','on');
1952         set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','off');
1953         set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','off');
1954         set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','off');
1955         set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','off');
1956         set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','off');
1957         set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','off');
1958         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','off');
1959         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','off');
1960         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','off');
1961         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','off');
1962         set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','off');
1963         pause(0);
1964
1965
1966         % Initialize feedback loop
1967         StartTime = gettime;
1968         StartErrorTime = gettime;
1969         Xold = getx(FB.OCSx.BPM.DeviceList);
1970         Yold = gety(FB.OCSy.BPM.DeviceList);
1971         HQMOFM_stalenum = 0;
1972         pause(LoopDelay);
1973
1974         N_HCM = size(HCMlist1,1);
1975         N_VCM = size(VCMlist1,1);
1976
1977         N_RFMO = 1;
1978
1979         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
1980             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'SetRF','Nodisplay','Nosetsp');
1981         else
1982             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
1983         end
1984         [FB.OCSx, Smatx, Sx, Ux, Vx] = orbitcorrectionmethods(FB.OCSx);
1985
1986         [FB.OCSy, junk, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
1987         [FB.OCSy, Smaty, Sy, Uy, Vy] = orbitcorrectionmethods(FB.OCSy);
1988
1989
1990         %%%%%%%%%%%%%%%%%%%%%%%
1991         % Start feedback loop %
1992         %%%%%%%%%%%%%%%%%%%%%%%
1993
1994         % chicaneloop=1;  % loop variable for resetting drifting chicanes (see a few lines below)
1995         % fftest=figure;
1996
1997         setpv('SR01____FFBON__BC00',2); % put FOFB in open loop so beamnoise gets recorded even if FOFB is not enabled
1998
1999         while 1
2000             try
2001                 t00 = gettime;
2002
2003                 %          if chicaneloop==20 % reset SR11 motor chicane setpoints every 20s due to drifting positions
2004                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(6),[11 1],0);
2005                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(7),[11 2],0);
2006                 %             chicaneloop = 1;
2007                 %          else
2008                 %             chicaneloop = chicaneloop + 1;
2009                 %          end
2010
2011                 % Check if GUI has been closed
2012                 if isempty(gcbf)
2013                     FEEDBACK_STOP_FLAG = 1;
2014                     lasterr('SRCONTROL GUI DISAPPEARED!');
2015                     error('SRCONTROL GUI DISAPPEARED!');
2016                 end
2017
2018                 %%%%%%%%%%%%%%%%%%%%%%%
2019                 % Fast orbit feedback %
2020                 %%%%%%%%%%%%%%%%%%%%%%%
2021                 if StartFOFBFlag == 1 & FBloopIter > 3
2022                     setpv('SR01____FFBON__BC00',2);
2023                     pause(0.5);
2024                     setpv('SR01____FFBON__BC00',1);
2025                     StartFOFBFlag = 0;
2026                     pause(1);
2027                     FOFBOnStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2028                         getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2029                         getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2030                         getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2031                     if any(FOFBOnStatus==0) | any(FOFBOnStatus==2)
2032                         setpv('SR01____FFBON__BC00',2); % open FOFB loop
2033                         disp('************************************************************************************************************');
2034                         disp('** Problem turning on Fast Orbit Feedback system...                                                       **');
2035                         disp('** Check status of ffbsecXX crates - but remember that a crate reboot will turn off Quads in that sector! **');
2036                         disp('** Suggest disabling the "Fast Orbit Correction" checkbox and starting Orbit Feedback again.              **');
2037                         disp('************************************************************************************************************');
2038                     else
2039                         fprintf('   Starting Fast Orbit Feedback at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
2040                     end
2041                 end
2042
2043
2044                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2045                 % Horizontal plane "feedback" %
2046                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2047
2048                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxSOFB'),'Value') == 1
2049
2050                     % Get orbit and check that the BPMs are different from the last update
2051                     Xnew = getx(FB.OCSx.BPM.DeviceList);
2052
2053                     % Don't feedback if the current is too small
2054                     if getdcct < 5
2055                         FEEDBACK_STOP_FLAG = 1;
2056                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2057                         break;
2058                     end
2059
2060                     x = Xgoal - Xnew;
2061                     STDx = norm(x)/sqrt(length(x));
2062
2063                     if any(Xold == Xnew)
2064                         a = clock;
2065                         N_Stale_Data_Points = find((Xold==Xnew)==1);
2066                         for loop = N_Stale_Data_Points'
2067                             fprintf('   Stale data: BPMx(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSx.BPM.DeviceList(loop,1), FB.OCSx.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2068                         end
2069                     else
2070                         % Compute horizontal correction
2071                         %%%OCSx0 = FB.OCSx;
2072                         FB.OCSx.BPM.Data = Xnew;
2073                         FB.OCSx = orbitcorrectionmethods(FB.OCSx, Smatx, Sx, Ux, Vx);
2074
2075                         %%%[FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
2076
2077                         % reduced feedback gain (implemented by Greg Portmann, December 2000)
2078                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2079                         % increased back to 0.8 C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2080                         % increased to 1.0, C. Steier, 2002-05-04, trim DACs
2081                         X = Xgain .* FB.OCSx.CM.Delta;
2082                         X(N_HCM+1) = 0.3*FB.OCSx.DeltaRF/4.988e-3;
2083                         %%%X = Xgain .* (FB.OCSx.CM.Data - OCSx0.CM.Data);
2084
2085                         % check for trim values+next step values, warn or stop FB as necessary
2086                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2087                         % need to extract Chicanes from this comparison or maybe check them first for range %
2088                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2089                         HCMtrimSP=getpv('HCM','Trim',HCMlist1);
2090                         HCMtrimSP_next = HCMtrimSP + X(1:N_HCM);
2091                         if max(abs(HCMtrimSP_next)) > 4
2092                             HCMtrimnum=find(abs(HCMtrimSP_next) > 4);
2093
2094                             % print message to screen
2095                             fprintf('**One or more of the horizontal correctors is at its maximum!! Stopping orbit feedback. \n');
2096                             fprintf('%s\n',datestr(now));
2097                             for loop = HCMtrimnum'
2098                                 fprintf('**%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2099                             end
2100
2101                             % send alphapage to operator pager
2102                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2103                             FEEDBACK_STOP_FLAG = 1;
2104
2105                             setpv('SR_STATE', -5);
2106                             [StateNumber, StateString] = getsrstate;
2107                             if StateNumber >= 0
2108                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2109                             else
2110                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2111                             end
2112                         end
2113
2114                         if FEEDBACK_STOP_FLAG == 1
2115                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2116                             if getpv('SR01____FFBON__BC00')==1
2117                                 disp('   Stopping Fast Orbit Feedback.');
2118                             end
2119                             setpv('SR01____FFBON__BC00',0);
2120                             pause(0.5);
2121                             setpv('SR01____FFBON__BC00',2);
2122                             break;
2123                         end
2124
2125                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2126                         pause(0);
2127
2128                         if max(abs(HCMtrimSP_next) > 3)
2129                             HCMtrimnum=find(abs(HCMtrimSP_next) > 3);
2130                             HWarnNum=HWarnNum+1;
2131                             if (HWarnNum==1 | rem(HWarnNum,120)==0)
2132
2133                                 % print message to screen every two minutes
2134                                 fprintf('**One or more of the horizontal corrector trims is above 3A or below -3A! \n');
2135                                 fprintf('%s\n',datestr(now));
2136                                 for loop = HCMtrimnum'
2137                                     fprintf('**%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2138                                 end
2139                                 fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2140
2141                                 %send alphapage to operator pager the first time then at 10 minutes
2142                                 if (HWarnNum==1 | HWarnNum==600)
2143                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageHCM.txt
2144                                 end
2145                             end
2146                         else
2147                             HWarnNum=0;
2148                         end
2149
2150                         % Don't feedback if the current is too small
2151                         if getdcct < 5
2152                             FEEDBACK_STOP_FLAG = 1;
2153                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2154                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2155                             break;
2156                         end
2157
2158                         if N_HCM > 0
2159                             steppv('HCM','Trim', X(iNotHCMChicane), HCMlist1(iNotHCMChicane,:), 0);
2160                             steppv('HCM','Setpoint', X(iHCMChicane), HCMlist1(iHCMChicane,:), 0);
2161                         end
2162
2163                         % write fast orbit feedback setpoints
2164                         if 1
2165                             %write_goldenorbit_ffb_2planes(1, Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM)+Sx3*X(length(X))/20, BPMlist1);
2166                             % should be corrected to include result of next frequency step ...
2167                             write_goldenorbit_ffb_2planes(1,Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM),BPMlist1);
2168                         end
2169
2170                         %fprintf('Horizontal Done: %f \n',gettime-t00);
2171
2172                         % RF feedback
2173                         HQMOFMsp_last = getpv('EG______HQMOFM_AC01');
2174
2175                         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2176                             if N_RFMO > 0
2177                                 if abs(X(end)/3) < .01
2178                                 % if abs(FB.OCSx.DeltaRF/3) < .01
2179                                     steppv('EG______HQMOFM_AC01', X(end));
2180                                 else
2181                                     steppv('EG______HQMOFM_AC01', 0.01*sign(X(end)));
2182                                 end
2183                             end
2184
2185                             HQMOFMsp_now = getpv('EG______HQMOFM_AC01');
2186
2187                             % Check for stale RF feedback
2188                             if HQMOFMsp_last == HQMOFMsp_now
2189                                 HQMOFM_stalenum = HQMOFM_stalenum + 1;
2190                                 if HQMOFM_stalenum == 30 % warn and message to pager if stale for 30 secs
2191                                     fprintf('**The RF is not responding to orbit feedback changes! \n');
2192                                     fprintf('%s\n',datestr(now));
2193                                     fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2194                                     fprintf('**ILC 73 controls the EG______HQMOFM_AC01 channel, which sets the RF frequency. \n');
2195                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstaleRFmessage.txt
2196                                 end
2197                                 if rem(HQMOFM_stalenum,120)==0 % message to screen every 2 minutes
2198                                     fprintf('**The RF is not responding to orbit feedback changes! (%s)\n',datestr(now));
2199                                 end
2200                             else
2201                                 HQMOFM_stalenum = 0;
2202                             end
2203
2204                         end
2205
2206                         %fprintf('RF Done: %f \n',gettime-t00);
2207
2208                         Xold = Xnew;
2209                     end % End horizontal correction
2210
2211
2212                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2213                     % Vertical plane "feedback" %
2214                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2215
2216                     % Get orbit and check that the BPMs are different from the last update
2217                     Ynew = gety(FB.OCSy.BPM.DeviceList);
2218
2219                     % Don't feedback if the current is too small
2220                     if getdcct < 5
2221                         FEEDBACK_STOP_FLAG = 1;
2222                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2223                         break;
2224                     end
2225
2226                     y = Ygoal - Ynew;
2227                     STDy = norm(y)/sqrt(length(y));
2228
2229                     if any(Yold == Ynew)
2230                         a = clock;
2231                         N_Stale_Data_Points = find((Yold==Ynew)==1);
2232                         for loop = N_Stale_Data_Points'
2233                             fprintf('   Stale data: BPMy(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSy.BPM.DeviceList(loop,1), FB.OCSy.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2234                         end
2235
2236                     else
2237
2238                         % Compute vertical correction
2239                         %%%OCSy0 = FB.OCSy;
2240                         FB.OCSy.BPM.Data = Ynew;
2241                         FB.OCSy = orbitcorrectionmethods(FB.OCSy, Smaty, Sy, Uy, Vy);
2242
2243                         %%%[FB.OCSy, RF, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
2244
2245                         % reduced feedback gain, C. Steier, 2001-03-25
2246                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2247                         % increased back to 0.8, C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2248                         % set to unity gain, C. Steier, 2002-05-04, trim DACs
2249                         Y = Ygain .* FB.OCSy.CM.Delta;
2250                         %%%Y = Ygain .* (FB.OCSy.CM.Data - OCSy0.CM.Data);
2251
2252                         % Just SVD correction
2253                         % warning('Not using "micado" correction in the vertical plane.');
2254
2255                         % check for trim values+next step values, warn or stop FB as necessary
2256                         VCMtrimSP = getpv('VCM','Trim',VCMlist1);
2257                         VCMtrimSP_next = VCMtrimSP + Y(1:N_VCM);
2258                         if max(abs(VCMtrimSP_next)) > 12
2259                             VCMtrimnum=find(abs(VCMtrimSP_next) > 12);
2260
2261                             % print message to screen
2262                             fprintf('**One or more of the vertical correctors is at its maximum!! Stopping orbit feedback. \n');
2263                             fprintf('%s\n',datestr(now));
2264                             for loop = VCMtrimnum'
2265                                 fprintf('**%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2266                             end
2267
2268                             % send alphapage to operator pager
2269                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2270                             FEEDBACK_STOP_FLAG = 1;
2271
2272                             setpv('SR_STATE', -5);
2273                             [StateNumber, StateString] = getsrstate;
2274                             if StateNumber >= 0
2275                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2276                             else
2277                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2278                             end
2279                         end
2280
2281                         if FEEDBACK_STOP_FLAG == 1
2282                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2283                             if getpv('SR01____FFBON__BC00')==1
2284                                 disp('   Stopping Fast Orbit Feedback.');
2285                             end
2286                             setpv('SR01____FFBON__BC00',0);
2287                             pause(0.5);
2288                             setpv('SR01____FFBON__BC00',2);
2289                             break;
2290                         end
2291
2292                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2293                         % pause(0);
2294
2295                         if max(abs(VCMtrimSP_next) > 4)
2296                             VCMtrimnum=find(abs(VCMtrimSP_next) > 4);
2297                             VWarnNum=VWarnNum+1;
2298                             if (VWarnNum==1 | rem(VWarnNum,120)==0)
2299
2300                                 % print message to screen every two minutes
2301                                 fprintf('**One or more of the vertical corrector trims is above 4A or below -4A! \n');
2302                                 fprintf('%s\n',datestr(now));
2303                                 for loop = VCMtrimnum'
2304                                     fprintf('**%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2305                                 end
2306                                 fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2307
2308                                 %send alphapage to operator pager the first time then at 10 minutes
2309                                 if (VWarnNum==1 | VWarnNum==600)
2310                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageVCM.txt
2311                                 end
2312                             end
2313                         else
2314                             VWarnNum=0;
2315                         end
2316
2317                         % Don't feedback if the current is too small
2318                         if getdcct < 5
2319                             FEEDBACK_STOP_FLAG = 1;
2320                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2321                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2322                             break;
2323                         end
2324
2325                         if N_VCM > 0
2326                             steppv('VCM','Trim', Y(iNotVCMChicane), VCMlist1(iNotVCMChicane,:), 0);
2327                             steppv('VCM','Setpoint', Y(iVCMChicane), VCMlist1(iVCMChicane,:), 0);
2328                         end
2329
2330                         % write fast orbit feedback setpoints
2331                         if 1
2332                             write_goldenorbit_ffb_2planes(2,Ynew(1:size(BPMlist1,1))+Sy1*Y(1:N_VCM),BPMlist1);
2333                         end
2334
2335                     end
2336
2337                     Yold = Ynew;
2338
2339                     %fprintf('Vertical Done: %f \n',gettime-t00);
2340                 end % End vertical correction
2341
2342
2343                 %%%%%%%%%%%%%%%%%%%%%
2344                 % Tune feed forward %
2345                 %%%%%%%%%%%%%%%%%%%%%
2346                 % We should do a Sector limit check
2347
2348                 tic;
2349                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxTune'),'Value') == 1
2350
2351                     if strcmp(SR_Mode, '1.9 GeV, High Tune') || strcmp(SR_Mode, '1.9 GeV, Inject at 1.23') || strcmp(SR_Mode, '1.9 GeV, Two-Bunch')
2352
2353                         addQFsp = zeros(24,1);
2354                         addQDsp = zeros(24,1);
2355
2356                         if strcmp(FFTypeFlag,'Local')
2357                             disp('  No local tune compensation available - global is the default now.');
2358                         elseif strcmp(FFTypeFlag,'Global')
2359
2360                             % The vectorized gets were put outside of loop for speed reasons
2361                             %
2362                             % should also set up QFfac, Quadelem, Quadlist structures outside loop
2363                             actualgap = getid(IDSector);
2364                             [gapmin,gapmax] = gaplimit(IDSector);
2365                             corrind = find(actualgap<(gapmin-1));
2366                             actualgap(corrind)=gapmax(corrind);
2367                             Shift=zeros(size(actualgap));
2368                             Shift(EPUlist)=getpv('EPU');
2369
2370                             IDchangedList=find((abs(actualgap-oldgap)>0.005) | (abs(Shift-oldShift)>0.005));
2371
2372                             if ~isempty(IDchangedList)
2373
2374                                 oldgap=actualgap;
2375                                 oldShift=Shift;
2376
2377                                 % EPUs excite nux = .25 resonance in vertical linear polarization mode!
2378                                 % therefore with EPU tune feedforward
2379                                 % running, we want to move our nominal working point away (just below) the .25 resonance.
2380                                 %
2381                                 % The following tune correction moves nominal
2382                                 % nu_x from .25 to .245 - this should be enough for well set up lattices.
2383                                 %
2384                                 % 24 QF+ 24 QD
2385                                 DeltaAmps = inv(SR_TUNE_MATRIX) * [-0.005;0];    %  DelAmps =  [QF; QD];
2386                                 addQFsp = addQFsp + DeltaAmps(1,:);
2387                                 addQDsp = addQDsp + DeltaAmps(2,:);
2388
2389                                 for gapnum = 1:length(actualgap)
2390
2391                                     % Change in tune and [QF;QD] from maximum gap
2392
2393                                     if (IDSector(gapnum,1) == 4) | (IDSector(gapnum,1) == 11)
2394                                         if IDSector(gapnum,2) == 1
2395                                             modenamestr = sprintf('SR%02dU___ODS1M__DC00',IDSector(gapnum,1));
2396                                         else % if IDSector(gapnum,2) == 2
2397                                             modenamestr = sprintf('SR%02dU___ODS2M__DC00',IDSector(gapnum,1));
2398                                         end
2399                                         epumode = getpvonline(modenamestr);
2400                                         if IDSector(gapnum,2)==2
2401                                             longshift=3;
2402                                         else
2403                                             longshift=0;
2404                                         end
2405                                         if (epumode==0) & (any(IDSector(gapnum,:)~=[11 1]))      % antiparallel tables need to be fit to data so that they could be used here
2406                                             DeltaNuX = shift2tune(IDSector(gapnum,1),actualgap(gapnum),Shift(gapnum)+longshift,SR_GeV);
2407                                             DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);   % variation of vertical tune shift with phase is small for EPUs
2408                                         else
2409                                             DeltaNuX = 0;
2410                                             DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);   % variation of vertical tune shift with phase is small for EPUs
2411                                         end
2412
2413                                     else
2414                                         DeltaNuX = 0;
2415                                         DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);
2416                                     end
2417
2418                                     DelQF = zeros(length(QFsp),1);
2419                                     DelQD = zeros(length(QFsp),1);
2420
2421                                     fraccorr = 0.8*DeltaNuY ./ TuneW16Min;
2422
2423                                     % Find which quads to change (local beta beating correction
2424                                     % (horizontal for EPU, vertical otherwise)
2425                                     QuadList = [IDSector(gapnum,1)-1 2; IDSector(gapnum,1) 1];
2426                                     QuadElem = dev2elem('QF',QuadList); % in reality use QF and QD ...
2427
2428                                     % global vertical tune correction
2429                                     % 24 QF+ 24 QD
2430                                     DeltaAmps = inv(SR_TUNE_MATRIX) * [(fraccorr*6.23e-4); fraccorr*(-0.05301)];    %  DelAmps =  [QF; QD];
2431                                     DelQF = DelQF + DeltaAmps(1,:);
2432                                     DelQD = DelQD + DeltaAmps(2,:);
2433
2434                                     % local horizontal tune correction (is also nearly a beta beating correction) only nonzero for EPUs!
2435                                     % 2 QF + 2 QD
2436                                     DeltaAmpsLocal = 12*inv(SR_TUNE_MATRIX) * [-DeltaNuX;0];                       %  DelAmps =  [QF; QD];
2437                                     DelQF(QuadElem) = DelQF(QuadElem)+DeltaAmpsLocal(1,1);
2438                                     DelQD(QuadElem) = DelQD(QuadElem)+DeltaAmpsLocal(2,1);
2439
2440                                     % local vertical beta beating correction (should be used together with above global tune correction)
2441                                     % set to zero for EPUs, since their vertical tune shift is small
2442                                     % 2 QF + 2QD
2443                                     if (IDSector(gapnum,1)==6) | (IDSector(gapnum,1)==7) | (IDSector(gapnum,1)==10) | (IDSector(gapnum,1)==11)
2444                                         QFfac = ([2.243127/2.237111; 2.243127/2.237111]-1) * fraccorr;
2445                                         QDfac = ([2.556392/2.511045; 2.556392/2.511045]-1) * fraccorr;
2446                                     elseif (IDSector(gapnum,1)==5) | (IDSector(gapnum,1)==9)
2447                                         QFfac = ([2.225965/2.219784; 2.243096/2.237111]-1) * fraccorr;
2448                                         QDfac = ([2.528950/2.483259; 2.556345/2.511045]-1) * fraccorr;
2449                                     elseif (IDSector(gapnum,1)==4) | (IDSector(gapnum,1)==8) | (IDSector(gapnum,1)==12)
2450                                         QFfac = ([2.243096/2.237111; 2.225965/2.219784]-1) * fraccorr;
2451                                         QDfac = ([2.556345/2.511045; 2.528950/2.483259]-1) * fraccorr;
2452                                     else
2453                                         QFfac = zeros(2,1);
2454                                         QDfac = zeros(2,1);
2455                                     end
2456
2457                                     DelQF(QuadElem,:) = DelQF(QuadElem,:) + QFfac.*QFsp(QuadElem,:);
2458                                     DelQD(QuadElem,:) = DelQD(QuadElem,:) + QDfac.*QDsp(QuadElem,:);
2459
2460                                     % add all tune and beta beating corrections for this one ID to the summed up correction vectors for all IDs
2461                                     addQFsp = addQFsp+DelQF;
2462                                     addQDsp = addQDsp+DelQD;
2463
2464                                 end
2465
2466                                 % Set quadrupoles using main setpoint channels
2467                                 setpv('QF', QFsp+addQFsp,[], 0);
2468                                 setpv('QD', QDsp+addQDsp,[], 0);
2469                                 % % Set quadrupoles using FF setpoint channels
2470                                 % setpv('QF', 'FF', addQFsp, [], 0);
2471                                 % setpv('QD', 'FF', addQDsp, [], 0);
2472                             end
2473
2474                         else
2475                             error('Unknown type selected for tune FF');
2476                         end
2477
2478
2479
2480                     else
2481                         disp('  No tune FF algorithm for non-production modes yet...');
2482                     end
2483                 end
2484
2485                 ffdeltaquad_delay = toc;
2486                 %fprintf('tune FF delay = %.1f seconds\n',ffdeltaquad_delay);
2487                 % fprintf('Tune Done: %f \n',gettime-t00);
2488
2489                 % Output info to screen
2490                 set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
2491                 set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
2492                 pause(0);
2493
2494
2495                 %fprintf('End of feedback operations: %f \n\n',gettime-t00);
2496
2497                 % Wait for next update time or stop request
2498                 while (gettime-t00) < LoopDelay
2499                     %disp('interval could be shorter')
2500                     pause(.05);
2501                     % Check if GUI has been closed
2502                     if isempty(gcbf)
2503                         FEEDBACK_STOP_FLAG = 1;
2504                         lasterr('SRCONTROL GUI DISAPPEARED!');
2505                         error('SRCONTROL GUI DISAPPEARED!');
2506                     end
2507
2508                     % Check if Stop button was pressed
2509                     if FEEDBACK_STOP_FLAG == 1
2510                         % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2511                         if getpv('SR01____FFBON__BC00')==1
2512                             disp('   Stopping Fast Orbit Feedback.');
2513                         end
2514                         setpv('SR01____FFBON__BC00',0);
2515                         pause(0.5);
2516                         setpv('SR01____FFBON__BC00',2);
2517                         break;
2518                     end
2519                 end
2520
2521
2522                 if FEEDBACK_STOP_FLAG == 1
2523                     % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2524                     if getpv('SR01____FFBON__BC00')==1
2525                         disp('   Stopping Fast Orbit Feedback.');
2526                     end
2527                     setpv('SR01____FFBON__BC00',0);
2528                     pause(0.5);
2529                     setpv('SR01____FFBON__BC00',2);
2530                     break;
2531                 end
2532
2533                 StartErrorTime = gettime;
2534
2535             catch
2536
2537                 fprintf('\n  %s \n',lasterr);
2538
2539                 % Quit if error exists for more than 20 seconds
2540                 if gettime-StartErrorTime>20 | FEEDBACK_STOP_FLAG==1
2541                     fprintf('%s  Orbit feedback stopped due to error condition. \n\n',datestr(now));
2542
2543                     %send alphapage to operator pager
2544                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2545                     FEEDBACK_STOP_FLAG = 1;
2546
2547                     setpv('SR_STATE', -5);
2548                     [StateNumber, StateString] = getsrstate;
2549                     if StateNumber >= 0
2550                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2551                     else
2552                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2553                     end
2554                 else
2555                     a = clock;
2556                     fprintf('   Orbit feedback was paused due to error condition (%s %d:%d:%.0f). \n', date, a(4), a(5), a(6));
2557                     fprintf('   Orbit feedback has automatically restarted and is running. \n\n');
2558                 end
2559
2560             end
2561
2562             if FEEDBACK_STOP_FLAG == 1
2563                 % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2564                 if getpv('SR01____FFBON__BC00')==1
2565                     disp('   Stopping Fast Orbit Feedback.');
2566                 end
2567                 setpv('SR01____FFBON__BC00',0);
2568                 pause(0.5);
2569                 setpv('SR01____FFBON__BC00',2);
2570                 break;
2571             end
2572
2573             %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2574
2575             %pause(0);
2576
2577             % this loop delays turn on of Fast Feedback system
2578             if FBloopIter < 5
2579                 FBloopIter = FBloopIter + 1;
2580             end
2581
2582         end  % End of feedback loop
2583
2584
2585         % End feedback, reset all parameters
2586         try
2587
2588             % Enable buttons
2589             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','on');
2590             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','off');
2591             set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','on');
2592             set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','on');
2593             set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','on');
2594             set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','on');
2595             set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','on');
2596             set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','on');
2597             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','on');
2598             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','on');
2599             set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','on');
2600             set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','on');
2601             set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','on');
2602
2603             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = _____ mm'),'ForegroundColor',[0 0 0]);
2604             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = _____ mm'),'ForegroundColor',[0 0 0]);
2605             pause(0);
2606
2607         catch
2608
2609             % GUI must have been closed
2610
2611         end
2612
2613
2614         % >= 2 Hz update rate on IDBPMs
2615         disp('   IDBPM time constant set to 0.25s.');
2616         setbpmtimeconstant(0.25);
2617
2618
2619         a = clock;
2620         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2621         [StateNumber, StateString] = getsrstate;
2622         if StateNumber >= 0
2623             setpv('SR_STATE',5.1);
2624             [StateNumber, StateString] = getsrstate;
2625             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2626             fprintf('   ******************************\n');
2627             fprintf('   **  Orbit Feedback Stopped  **\n');
2628             fprintf('   ******************************\n\n');
2629         else
2630             [StateNumber, StateString] = getsrstate;
2631             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2632             fprintf('   ****************************************\n');
2633             fprintf('   **  Problem With Slow Orbit Feedback  **\n');
2634             fprintf('   ****************************************\n\n');
2635         end
2636         set(0,'showhiddenhandles','off');
2637         pause(0);
2638
2639
2640     case 'FeedbackSetup'
2641         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
2642
2643         if InitFlag
2644             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2645             % Edit the following lists to change default configuration of Orbit Correction %
2646             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2647
2648             % Corrector magnets
2649             listh=[
2650                 1 2;
2651                 1 8;
2652                 2 1;
2653                 2 8;
2654                 3 1;
2655                 3 8;
2656                 3 10; %SR04U_HCM2 (chicane trim)
2657                 4 1;
2658                 4 8;
2659                 5 1;
2660                 5 8;
2661 %                 5 10; %SR06U_HCM2 (chicane trim)
2662                 6 1;
2663                 6 8;
2664                 7 1;
2665                 7 8;
2666                 8 1;
2667                 8 8;
2668                 9 1;
2669                 9 8;
2670                 10 1;
2671                 10 8;
2672                 10 10; %SR11U_HCM2 (chicane trim)
2673                 11 1;
2674                 11 8;
2675                 12 1;
2676                 12 7];
2677             listv=[
2678                 1 2;
2679                 1 8;
2680                 2 1;
2681                 2 8;
2682                 3 1;
2683                 3 7;
2684                 3 8;
2685                 3 10; %SR04U_VHCM2 (chicane trim)
2686                 4 1;
2687                 4 7;
2688                 4 8;
2689                 5 1;
2690                 5 8;
2691 %                 5 10; %SR06U_VHCM2 (chicane trim)
2692                 6 1;
2693                 6 8;
2694                 7 1;
2695                 7 8;
2696                 8 1;
2697                 8 8;
2698                 9 1;
2699                 9 8;
2700                 10 1;
2701                 10 2;
2702                 10 7;
2703                 10 8;
2704                 10 10; %SR11U_VHCM2 (chicane trim)
2705                 11 1;
2706                 11 7;
2707                 11 8;
2708                 12 1;
2709                 12 7];
2710
2711             Xivec = [1:27];
2712             Yivec = [1:31];
2713             HCMlist1 = listh;
2714             VCMlist1 = listv;
2715
2716             % Full BPM list
2717             BPMlist1 = [
2718                 1 2
2719                 1 5
2720                 1 6
2721                 1 10
2722                 2 1
2723                 2 5
2724                 2 6
2725                 2 9
2726                 3 2
2727                 3 5
2728                 3 6
2729                 3 10
2730                 3 11
2731                 3 12
2732                 4 1
2733                 4 5
2734                 4 6
2735                 4 10
2736                 5 1
2737                 5 5
2738                 5 6
2739                 5 10
2740 %                 5 11
2741 %                 5 12
2742                 6 1
2743                 6 5
2744                 6 6
2745                 6 10
2746                 7 1
2747                 7 5
2748                 7 6
2749                 7 10
2750                 8 1
2751                 8 5
2752                 8 6
2753                 8 10
2754                 9 1
2755                 9 5
2756                 9 6
2757                 9 10
2758                 10 1
2759                 10 5
2760                 10 6
2761                 10 10
2762                 10 11
2763                 10 12
2764                 11 1
2765                 11 5
2766                 11 6
2767                 11 10
2768                 12 1
2769                 12 5
2770                 12 6
2771                 12 9
2772                 ];
2773
2774             % remove Bergoz BPMs in SR01 and SR03 for 2-bunch (noisy at low currents) and drop singular values
2775             if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
2776                     BPMlist1 = [
2777                          %1 2
2778                          1 5
2779                          1 6
2780                          1 10
2781                          2 1
2782                          2 5
2783                          2 6
2784                          %2 9
2785                          %3 2
2786                          3 5
2787                          3 6
2788                          3 10
2789                          3 11
2790                          3 12
2791                          4 1
2792                          4 5
2793                          4 6
2794                          4 10
2795                          5 1
2796                          5 5
2797                          5 6
2798                          5 10
2799                          5 11
2800                          5 12
2801                          6 1
2802                          6 5
2803                          6 6
2804                          6 10
2805                          7 1
2806                          7 5
2807                          7 6
2808                          7 10
2809                          8 1
2810                          8 5
2811                          8 6
2812                          8 10
2813                          9 1
2814                          9 5
2815                          9 6
2816                          9 10
2817                          10 1
2818                          10 5
2819                          10 6
2820                          10 10
2821                          10 11
2822                          10 12
2823                          11 1
2824                          11 5
2825                          11 6
2826                          11 10
2827                          12 1
2828                          12 5
2829                          12 6
2830                          %12 9
2831                          ];
2832             end
2833
2834             OCSx.BPM = getx(BPMlist1, 'struct');
2835             OCSx.CM = getsp('HCM', HCMlist1, 'struct');
2836             OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
2837             OCSx.NIter = 1;
2838             OCSx.SVDIndex = Xivec;
2839             OCSx.IncrementalFlag = 'No';
2840             OCSx.BPMWeight = {[]};
2841             OCSx.FitRF = 0;
2842             OCSy.BPM = gety(BPMlist1, 'struct');
2843             OCSy.CM = getsp('VCM', VCMlist1, 'struct');
2844             OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
2845             OCSy.NIter = 1;
2846             OCSy.SVDIndex = Yivec;
2847             OCSy.IncrementalFlag = 'No';
2848             OCSy.BPMWeight = {[]};
2849             OCSy.FitRF = 0;
2850             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2851             % do we need these Smat calls? %
2852             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2853             SXmat = getrespmat(OCSx.BPM, OCSx.CM, 'numeric');
2854             SYmat = getrespmat(OCSy.BPM, OCSy.CM, 'numeric');
2855             % [OCSx, Sx, Ux, Vx] = orbitcorrectionmethods(OCSx, SXmat);
2856             % [OCSy, Sy, Uy, Vy] = orbitcorrectionmethods(OCSy, SYmat);
2857
2858             % initialize FFTypeFlag
2859             FFTypeFlag = 'Global';
2860
2861         else
2862
2863             % Get vectors
2864             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
2865             % the two lines below seem to fix BPMlist editing problem
2866             OCSx = FB.OCSx;
2867             OCSy = FB.OCSy;
2868             BPMlist1 = FB.BPMlist1;
2869             HCMlist1 = FB.HCMlist1;
2870             VCMlist1 = FB.VCMlist1;
2871             Xivec = FB.Xivec;
2872             Yivec = FB.Yivec;
2873             Xgoal = FB.OCSx.GoalOrbit;
2874             OCSx.GoalOrbit = Xgoal;
2875             Ygoal = FB.OCSy.GoalOrbit;
2876             OCSy.GoalOrbit = Ygoal;
2877             FFTypeFlag = FB.FFTypeFlag;
2878
2879
2880             % FF corrector magnet list
2881             ListFF = [
2882                 4     2
2883                 4     8
2884                 5     1
2885                 5     7
2886 %               5     8 % why are these out???
2887 %               6     1 % why are these out???
2888                 6     8
2889                 7     1
2890                 7     8
2891                 8     1
2892                 8     8
2893                 9     1
2894                 9     8
2895                 10    1
2896                 11    8
2897                 12    1];
2898             ElemFF = dev2elem('HCM',ListFF);
2899
2900
2901             % Add button to change #ivectors, cm, IDBPMs,
2902             EditFlag = 0;
2903             h_fig1 = figure;
2904             while EditFlag ~= 6
2905
2906                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
2907                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
2908
2909                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2910                     DispOrbit = getdisp('BPMx', BPMlist1);
2911                     Sx = [Sx DispOrbit];
2912                 end
2913
2914                 [Ux, SVx, Vx] = svd(Sx);
2915                 [Uy, SVy, Vy] = svd(Sy);
2916
2917
2918                 % Remove singular values greater than the actual number of singular values
2919                 i = find(Xivec>length(diag(SVx)));
2920                 if ~isempty(i)
2921                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
2922                     pause(0);
2923                     Xivec(i) = [];
2924                 end
2925                 i = find(Yivec>length(diag(SVy)));
2926                 if ~isempty(i)
2927                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
2928                     pause(0);
2929                     Yivec(i) = [];
2930                 end
2931
2932
2933                 Ax = Sx*Vx(:,Xivec);
2934                 Tx = inv(Ax'*Ax)*Ax';
2935
2936                 Ay = Sy*Vy(:,Yivec);
2937                 Ty = inv(Ay'*Ay)*Ay';
2938
2939                 figure(h_fig1);
2940                 subplot(2,1,1);
2941                 semilogy(diag(SVx),'b');
2942                 hold on;
2943                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
2944                 ylabel('Horizontal');
2945                 title('Response Matrix Singular Values');
2946                 hold off;
2947                 subplot(2,1,2);
2948                 semilogy(diag(SVy),'b');
2949                 hold on;
2950                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
2951                 xlabel('Singular Value Number');
2952                 ylabel('Vertical');
2953                 hold off;
2954                 drawnow;
2955
2956                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List', ...
2957                     'BPM List','Change the Goal Orbit','Continue');
2958
2959                 if EditFlag == 1
2960                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
2961                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
2962                     titlestr='SVD Orbit Feedback';
2963                     lineNo=1;
2964                     answer=inputdlg(prompt,titlestr,lineNo,def);
2965                     if ~isempty(answer)
2966                         XivecNew = fix(str2num(answer{1}));
2967                         if isempty(XivecNew)
2968                             disp('   Horizontal E-vector cannot be empty.  No change made.');
2969                         else
2970                             if any(XivecNew<=0) | max(XivecNew)>length(diag(SVx))
2971                                 disp('   Error reading horizontal E-vector.  No change made.');
2972                             else
2973                                 Xivec = XivecNew;
2974                             end
2975                         end
2976                         YivecNew = fix(str2num(answer{2}));
2977                         if isempty(YivecNew)
2978                             disp('   Vertical E-vector cannot be empty.  No change made.');
2979                         else
2980                             if any(YivecNew<=0) | max(YivecNew)>length(diag(SVy))
2981                                 disp('   Error reading vertical E-vector.  No change made.');
2982                             else
2983                                 Yivec = YivecNew;
2984                             end
2985                         end
2986                     end
2987                 end
2988
2989                 if EditFlag == 2
2990                     List= getlist('HCM','Trim');
2991                     CheckList = zeros(96,1);
2992                     Elem = dev2elem('HCM', HCMlist1);
2993                     CheckList(Elem) = ones(size(Elem));
2994                     CheckList = CheckList(dev2elem('HCM',List));
2995
2996                     % Remove FF corrrectors
2997                     %           Elem = dev2elem('HCM',List);
2998                     %           for j = length(ElemFF):-1:1
2999                     %              i = find(Elem==ElemFF(j));
3000                     %              Elem(i,:) = [];
3001                     %              List(i,:) = [];
3002                     %              CheckList(i,:) = [];
3003                     %           end
3004
3005                     newList = editlist(List, 'HCMtrim', CheckList);
3006
3007                     if isempty(newList)
3008                         fprintf('   WARNING: Horizontal corrector magnet list is empty!\n');
3009                         HCMlist1 = newList;
3010                     else
3011                         HCMlist1 = newList;
3012                     end
3013                     OCSx.CM.DeviceList = HCMlist1;
3014                 end
3015
3016                 if EditFlag == 3
3017                     List = getlist('VCM','Trim');
3018                     CheckList = zeros(96,1);
3019                     Elem = dev2elem('VCM', VCMlist1);
3020                     CheckList(Elem) = ones(size(Elem));
3021                     CheckList = CheckList(dev2elem('VCM',List));
3022
3023                     % Remove FF corrrectors
3024                     %           Elem = dev2elem('VCM',List);
3025                     %           for j = length(ElemFF):-1:1
3026                     %              i = find(Elem==ElemFF(j));
3027                     %              Elem(i,:) = [];
3028                     %              List(i,:) = [];
3029                     %              CheckList(i,:) = [];
3030                     %           end
3031
3032                     newList = editlist(List, 'VCMtrim', CheckList);
3033
3034                     if isempty(newList)
3035                         fprintf('   WARNING: Vertical corrector magnet list is empty!\n');
3036                         VCMlist1 = newList;
3037                     else
3038                         VCMlist1 = newList;
3039                     end
3040                     OCSy.CM.DeviceList = VCMlist1;
3041                 end
3042
3043                 if EditFlag == 4
3044                     ListOld = BPMlist1;
3045                     XgoalOld = Xgoal;
3046                     YgoalOld = Ygoal;
3047
3048                     % Full BPM list
3049                     List = [
3050                         1 2
3051                         1 5
3052                         1 6
3053                         1 10
3054                         2 1
3055                         2 5
3056                         2 6
3057                         2 9
3058                         3 2
3059                         3 5
3060                         3 6
3061                         3 10
3062                         3 11
3063                         3 12
3064                         4 1
3065                         4 5
3066                         4 6
3067                         4 10
3068                         5 1
3069                         5 5
3070                         5 6
3071                         5 10
3072                         5 11
3073                         5 12
3074                         6 1
3075                         6 5
3076                         6 6
3077                         6 10
3078                         7 1
3079                         7 5
3080                         7 6
3081                         7 10
3082                         8 1
3083                         8 5
3084                         8 6
3085                         8 10
3086                         9 1
3087                         9 5
3088                         9 6
3089                         9 10
3090                         10 1
3091                         10 5
3092                         10 6
3093                         10 10
3094                         10 11
3095                         10 12
3096                         11 1
3097                         11 5
3098                         11 6
3099                         11 10
3100                         12 1
3101                         12 5
3102                         12 6
3103                         12 9
3104                         ];
3105
3106
3107                     CheckList = zeros(size(List,1),1);
3108                     if ~isempty(BPMlist1)
3109                         for i = 1:size(List,1)
3110                             k = find(List(i,1)==BPMlist1(:,1));
3111                             l = find(List(i,2)==BPMlist1(k,2));
3112
3113                             if isempty(k) | isempty(l)
3114                                 % Item not in list
3115                             else
3116                                 CheckList(i) = 1;
3117                             end
3118                         end
3119                     end
3120
3121                     newList = editlist(List, 'BPM', CheckList);
3122                     if isempty(newList)
3123                         fprintf('   BPM list cannot be empty.  No change made.\n');
3124                     else
3125                         BPMlist1 = newList;
3126                     end
3127
3128                     % Set the goal orbit to the golden orbit
3129                     Xgoal = getgolden('BPMx', BPMlist1);
3130                     Ygoal = getgolden('BPMy', BPMlist1);
3131
3132
3133                     % If a new BPM is added, then set the goal orbit to the golden orbit
3134                     for i = 1:size(BPMlist1,1)
3135
3136                         % Is it a new BPM?
3137                         k = find(BPMlist1(i,1)==ListOld(:,1));
3138                         l = find(BPMlist1(i,2)==ListOld(k,2));
3139
3140                         if isempty(k) | isempty(l)
3141                             % New BPM
3142                         else
3143                             % Use the old value for old BPM
3144                             Xgoal(i) = XgoalOld(k(l));
3145                             Ygoal(i) = YgoalOld(k(l));
3146                         end
3147                     end
3148                     OCSx.BPM.DeviceList = BPMlist1;
3149                     OCSy.BPM.DeviceList = BPMlist1;
3150                     OCSx.GoalOrbit = Xgoal;
3151                     OCSy.GoalOrbit = Ygoal;
3152                 end
3153
3154                 if EditFlag == 5
3155                     ChangeList = editlist2(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
3156
3157                     for i = 1:size(ChangeList,1)
3158
3159                         k = find(ChangeList(i,1)==BPMlist1(:,1));
3160                         l = find(ChangeList(i,2)==BPMlist1(k,2));
3161
3162                         prompt={sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
3163                         def={sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
3164                         titlestr='CHANGE THE GOAL ORBIT';
3165                         lineNo=1;
3166                         answer = inputdlg(prompt, titlestr, lineNo, def);
3167
3168                         if isempty(answer)
3169                             % No change
3170                             fprintf('   No change was made to the golden orbit.\n');
3171                         else
3172                             Xgoalnew = str2num(answer{1});
3173                             if isempty(Xgoalnew)
3174                                 fprintf('   No change was made to the horizontal golden orbit.\n');
3175                             else
3176                                 Xgoal(k(l)) = Xgoalnew;
3177                             end
3178
3179                             Ygoalnew = str2num(answer{2});
3180                             if isempty(Ygoalnew)
3181                                 fprintf('   No change was made to the vertical golden orbit.\n');
3182                             else
3183                                 Ygoal(k(l)) = Ygoalnew;
3184                             end
3185                         end
3186                     end
3187                     if ~isempty(ChangeList)
3188                         fprintf('   Note:  Changing the goal orbit for "Slow Orbit Feedback" does not change the goal orbit for "Orbit Correction."\n');
3189                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
3190                     end
3191                     OCSx.GoalOrbit = Xgoal;
3192                     OCSy.GoalOrbit = Ygoal;
3193                 end
3194
3195 %                 if EditFlag == 6
3196 %                     FFTypeFlag = questdlg(sprintf('Do you want to use a fully local or a combined local/global compensation of IDs? (nuy=9.2 only)'),'Tune FF','Local','Global', 'Global');
3197 %                     if strcmp(FFTypeFlag,'Local')
3198 %                         disp(['   The tune FF will use 8 local quadrupoles to compensate beta beating and tune shift']);
3199 %                         disp(['   from each ID.']);
3200 %                     elseif strcmp(FFTypeFlag,'Global')
3201 %                         disp(['   The tune FF will use 4 local quadrupoles to compensate beta beating and all QF+QD']);
3202 %                         disp(['   to compensate tune shift from each ID.']);
3203 %                     end
3204 %                 end
3205
3206             end
3207             close(h_fig1);
3208         end
3209
3210         % Save vectors
3211         FB.Xivec = Xivec;
3212         FB.Yivec = Yivec;
3213         FB.HCMlist1 = HCMlist1;
3214         FB.VCMlist1 = VCMlist1;
3215         FB.BPMlist1 = BPMlist1;
3216
3217         OCSx.SVDIndex = Xivec;
3218         OCSy.SVDIndex = Yivec;
3219         FB.OCSx = OCSx;
3220         FB.OCSy = OCSy;
3221
3222         FB.FFTypeFlag = FFTypeFlag;
3223         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata',FB);
3224
3225
3226     case 'FastFeedbackSetup'
3227
3228         InitFlag = Input2;
3229
3230         if InitFlag
3231             FOFBFreq = 1000;
3232             % user operations 9/14-10/17/04: P=0.5, I=120, D=0.0015 (for both planes)
3233             % below are known good values for user ops as of 8-1-05
3234             HorP = 2;
3235             HorI = 300;
3236             HorD = 0.002;
3237             VertP = 1;
3238             VertI = 100;
3239             VertD = 0.0015;
3240
3241             % this initial set is now done in hwinit.m because it's not a good idea to set anything when srcontrol is launched
3242             % try
3243             %     setsp('SR01____FFBFREQAC00', FOFBFreq); % set freq
3244             %     write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3245             % catch
3246             %     disp('   Trouble setting Fast Orbit Feedback parameters!');
3247             % end
3248
3249         else
3250             % Get vectors
3251             FOFB = get(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata');
3252             FOFBFreq = FOFB.FOFBFreq;
3253             HorP  = FOFB.HorP;
3254             HorI  = FOFB.HorI;
3255             HorD  = FOFB.HorD;
3256             VertP = FOFB.VertP;
3257             VertI = FOFB.VertI;
3258             VertD = FOFB.VertD;
3259
3260             % Add button to change #ivectors, CMs, IDBPMs,
3261             EditFlag = 0;
3262             %h_fig1 = figure;
3263             while EditFlag ~= 3
3264
3265                 %EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'HCM List', 'VCM List', ...
3266                 %   'IDBPM List', 'BBPM List', 'Continue');
3267                 % Use menu below until other FFB config routines work (then also uncomment options 3,4,5,6 below)
3268                 EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'Continue');
3269
3270                 if EditFlag == 1
3271                     % change rate
3272
3273                     prompt={'Enter the desired Fast Feedback Frequency (1-1000 Hz)'};
3274                     def={num2str(FOFBFreq)};
3275                     titlestr='Fast Feedback Setup';
3276                     lineNo=1;
3277                     answer=inputdlg(prompt,titlestr,lineNo,def);
3278                     if ~isempty(answer)
3279                         FOFBFreq = fix(str2num(answer{1}));
3280                         if isempty(FOFBFreq)
3281                             disp('   Frequency value cannot be empty.  No change made.');
3282                             FOFBFreq = getsp('SR01____FFBFREQAC00');
3283                         else
3284                             if FOFBFreq < 1 | FOFBFreq > 1000
3285                                 disp('   Frequency must be between 1 and 1000 Hz.  No change made.');
3286                                 FOFBFreq = getsp('SR01____FFBFREQAC00');
3287                             end
3288                         end
3289                         setsp('SR01____FFBFREQAC00',FOFBFreq); % change freq
3290                         pause(0.5);
3291                         fprintf('   Fast orbit feedback frequency is running at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
3292                     else
3293                         FOFBFreq = getsp('SR01____FFBFREQAC00');
3294                     end
3295                 end
3296
3297                 if EditFlag == 2
3298                     % edit  PIDs
3299                     % User defaults are HorP=2, HorI=300, HorD=0.002, VertP=1, VertI=100, VertD=0.0015
3300                     prompt={'P horizontal', 'I horizontal', 'D horizontal', 'P vertical', 'I vertical', 'D vertical'};
3301                     def={num2str(HorP), num2str(HorI), num2str(HorD), num2str(VertP), num2str(VertI), num2str(VertD)};
3302                     titlestr='Fast Feedback PID Setup';
3303                     lineNo=1;
3304                     answer=inputdlg(prompt,titlestr,lineNo,def);
3305                     if ~isempty(answer)
3306                         HorPnewnum = str2num(answer{1});
3307                         if isempty(HorPnewnum)
3308                             disp('   HorP value cannot be empty.  No change made.');
3309                         else
3310                             HorP = HorPnewnum;
3311                         end
3312                         HorInewnum = str2num(answer{2});
3313                         if isempty(HorInewnum)
3314                             disp('   HorI value cannot be empty.  No change made.');
3315                         else
3316                             HorI = HorInewnum;
3317                         end
3318                         HorDnewnum = str2num(answer{3});
3319                         if isempty(HorDnewnum)
3320                             disp('   HorD value cannot be empty.  No change made.');
3321                         else
3322                             HorD = HorDnewnum;
3323                         end
3324                         VertPnewnum = str2num(answer{4});
3325                         if isempty(VertPnewnum)
3326                             disp('   VertP value cannot be empty.  No change made.');
3327                         else
3328                             VertP = VertPnewnum;
3329                         end
3330                         VertInewnum = str2num(answer{5});
3331                         if isempty(VertInewnum)
3332                             disp('   VertI value cannot be empty.  No change made.');
3333                         else
3334                             VertI = VertInewnum;
3335                         end
3336                         VertDnewnum = str2num(answer{6});
3337                         if isempty(VertDnewnum)
3338                             disp('   VertD value cannot be empty.  No change made.');
3339                         else
3340                             VertD = VertDnewnum;
3341                         end
3342
3343                         try
3344                             write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3345                             fprintf('   Setting FFB gains to Horizontal P=%.2f, I=%.1f, D=%.4f;  Vertical P=%.2f, I=%.1f, D=%.4f\n', HorP, HorI, HorD, VertP, VertI, VertD);
3346                         catch
3347                             disp('   Trouble setting Fast Orbit Feedback parameters!');
3348                         end
3349                     end
3350                 end
3351
3352                 %if EditFlag == 3
3353                 %   disp('   This function not yet available.');
3354                 %   % change HCM List
3355                 %end
3356                 %
3357                 %if EditFlag == 4
3358                 %   disp('   This function not yet available.');
3359                 %   % change VCM List
3360                 %end
3361                 %
3362                 %if EditFlag == 5
3363                 %   disp('   This function not yet available.');
3364                 %   % change IDBPM List
3365                 %end
3366                 %
3367                 %if EditFlag == 6
3368                 %   disp('   This function not yet available.');
3369                 %   % change BBPM List
3370                 %end
3371
3372             end
3373             %close(h_fig1);
3374         end
3375
3376         % Save vectors
3377         FOFB.FOFBFreq = FOFBFreq;
3378         FOFB.HorP = HorP;
3379         FOFB.HorI = HorI;
3380         FOFB.HorD = HorD;
3381         FOFB.VertP = VertP;
3382         FOFB.VertI = VertI;
3383         FOFB.VertD = VertD;
3384         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata',FOFB);
3385
3386     otherwise
3387         fprintf('   No action for %s.\n', action);
3388 end   % end case