Description of srcontrol5_before_20070409
Home > ALS > StorageRing > srcontrol5_before_20070409.m
srcontrol5_before_20070409
PURPOSE
srcontrol5
SYNOPSIS
function srcontrol5(action, Input2, Input3)
DESCRIPTION
 srcontrol5
 Storage ring control program
 This program controls all storage ring magnets, performs orbit feedback and
 tune feedforward and helps to diagnose problems in routine user operation
 of the ALS storage ring. It includes a gui to simplify the use of this
 program.
 It was originally programmed by Greg Portmann (until December 2000) with input
 from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
 and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
 The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
 Christoph Steier, July 2002
 SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
 Tom Scarvie, April 2005
CROSS-REFERENCE INFORMATION
This function calls:
bend2gev BEND2GEV - Compute the energy based on the ramp tables
checksrmags CHECKSRMAGS - Check SR power supplies against a lattice file
checksrorbit ErrorNums =checksrorbit(Sector, BPMxtolerance [.015 mm], [BPMytolerance [.015 mm]])
gap2tune GAP2TUNE - Computes the vertical tune shift for a insertion device gap change.
gaplimit [GapMin, GapMax] = gaplimit(ID_Number);
getff function [FFEnableBM, FFEnableBC, GapEnableBM, GapEnableBC, Sector] = getff(Sector)
getid GETID - Get the insertion device position, velocity, run flag, and user requested gap
getsrstate [StateNumber, StateString] = getsrstate
set_alarmhandler_AHU_thresholds_inject function set_alarmhandler_AHU_thresholds_inject
set_alarmhandler_thresholds set_alarmhandler_thresholds
set_alarmhandler_thresholds_new set_alarmhandler_thresholds_new
setbpmtimeconstant SETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
setbumps SETBUMPS - Make a straight section bump
setff function setff(Sector, FFEnableBC, GapEnableBC)
setid SETID - Set the insertion device vertical gap
setsrstatechannels
srcycle SRCYCLE - Storage ring cycle
srramp SRRAMP - Ramp the storage ring energy
write_goldenorbit_ffb function write_goldenorbit_ffb
write_goldenorbit_ffb_2planes WRITE_GOLDENORBIT_FFTB_2PLANES - Sets the BPM setpoints which are used by the fast feedback system
This function is called by:
SOURCE CODE
function srcontrol5(action, Input2, Input3)
% srcontrol5
% Storage ring control program
%
% This program controls all storage ring magnets, performs orbit feedback and
% tune feedforward and helps to diagnose problems in routine user operation
% of the ALS storage ring. It includes a gui to simplify the use of this
% program.
%
% It was originally programmed by Greg Portmann (until December 2000) with input
% from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
% and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
%
% The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
%
% Christoph Steier, July 2002
%
% SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
%
% Tom Scarvie, April 2005
% known bugs/problems (May 2001):
% - IDBPM averaging might be a bit too long for orbit feedback
%        solved after Superbend shutdown ... Instead of averaging, digital low pass filters are used
% - gap2tune does not give correct answers for wiggler and potentially other IDs -> orbit feedback
%        seems to be OK for other IDs, has been corrected for wiggler (fit to insertion device
%        compensation table)
% - chicanes do not work in orbit feedback
%        solved. One problem was that orbit response matrizes were mis-scaled by factor of two.
%        Second problem was different time constant of power supply control. Solved by moving controls
%        of center chicanes to cPCI (and magnets are fast, hysteresis free, aircore coils).
%        Center chicane in sector 4 is now routinely used in orbit feedback. Sector 11 to follow soon.
% - zero reading of ID gap dumps beam
%        solved in srcontrol5, still a problem in srcontrol5_hightune (but that routine has to be completely
%        rewritten because of all recent changes to srcontrol5, anyhow). For gap readings below the minimum
%        allowed gap for a device, the tune feedforward disables itself.
% - cycling of lattice causes frequent power supply failures
%        solved by changing the cycling procedure. 1.5 GeV operation is now on the upper hysteresis branch
%        as was the 1.9 GeV injection lattice before.
% - frequently stalled data in IDBPM readout
%        solved with new BPM readouts and digital filtering. Seems to have been a resolution problem
%        of the digital averaging algorithm.
% - magnet ramp tables are not in perfect agreement with magnetic measurements
%        Does not appear to be a serious problem. Superbends are slightly out of sync with other magnets,
%        but this does not cause any negative effects while ramping.
% - no good way to operate with injection at 1.5 GeV and storage energy below that
%        There now is a reasonable way to inject at 1.5 GeV and ramp down to lower storage energy. But
%        it has to be tested again after implementing new (and more) chicanes ...
% revision history
% 2001-05-10, Christoph Steier
% check whether readback from insertion device is significantly (more than 1 mm) below minimum
% gap, to avoid false zero readings of insertion device gaps to cause the tune feed forward
% to implement false huge correction (and dump the beam). If the insertion device gap readbacks
% gets more than 1 mm below the nominal minimum gap, the routine now assumes the insertion device
% to be open.
%
% 2001-08-30 and during Superbend commissioning, Christoph Steier, Tom Scarvie, Winni Decking
% various changes have been made to incorporate the Superbends and some other new equipment
% installed in the Superbend shutdown. This included some changes to programs being called by srcontrol
% (like srload, srsave, srcycle, srramp, ...). The main changes within srcontrol were in the orbit
% correction and slow orbit feedback routines (incorporating frequency feedback, ...)
%
% 2002-05-04, Christoph Steier
% added new IDBPMs, modified orbit feedback to use trim DACs, removed LSB toggling in vertical
% orbit feedback, ...
%
% 2002-07-29, T.Scarvie
% added check of CM trim currents to warn of problems that might rail the orbit feedback
%
% 2002-07-31, Christoph Steier
% increased the gain of the RF frequency feedback from 1/50 of the gain of the horizontal
% orbit feedback to 1/20. Reason was that the frequency feedback was reacting a bit too slow if all
% insertion device gaps are closed at once at high speed at the beginning of a fill.
%
% 2002-08-05, C.Steier, T.Scarvie
% Added conditional to reduce orbit feedback gain if running in two-bunch mode
%
% 2003-06-02, T.Scarvie
% Added loop inside orbit feedback to reset the SR11 chicane M1 and M2 motors every 20s to combat drift problem
%
% 2003-06-18, C. Steier
% Disabled loop to periodically reset chicane in SR11. Al Robb replaced power supply, seems to be no problem anymore.
%
% 2004-05-10, C. Steier
% The list of all BBPMs is now set up automatically be calling getlist('BBPMx'). This way, new BBPMs have to be added
% at fewer places in the software. It should now be sufficient to modify getlist and run the orbit response matrix
% rountine (getsmat) once to enable use of the new BBPMs.
%
% 2004-05-14, C. Steier
% Modified parameters for ramprate reduction (in srramp and here). Previous parameters were slightly too
% cautious. Increased initial slow ramprate to 0.4 A/s.
%
% 2004-05-14, C. Steier
% Incorporated insertion device compensation schemes for nu_y = 9.2 lattice.
%
% 2004-06-14, T.Scarvie
% Added controls for fast orbit feedback
%
% 2004-06-21, C. Steier
% Added tune feedforward (in the global tune compensation scheme for the nu_y=9.2 lattice) for the shift
% dependent tune shift of the EPUs, as well as a skew quadrupole feedforward for the EPU im sector 11
% (both only active in parallel mode so far).
%
% 2005-02-13, T.Scarvie
% Separated horizontal and vertical planes for setting Fast Feedback PIDs
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NOTES for conversion to new Middle Layer %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% We never use the gap and bump control flags - the radio buttons have been disabled -
%        should we try to keep the functionality?
%
% remove handle globals
% set(0,'showhiddenhandles','on'); what does this do?
% grampbsc -> should be handled by new srramp (which uses k-values)
% checksrmags
% checksrorbit(...)
% getdcct
% setbpmtimeconstant
% getsmatelements
% Chicane trims are now part of the corrector family
% getname('IDrunflag',...) family name change
% write_goldenorbit_ffb, write_goldenorbit_ffb2
% For the compiler
%#function goldenpage
%#function setoperationalmode
% Check if the AO exists
checkforao;
%%%%%%%%%%%%%%
% Initialize %
%%%%%%%%%%%%%%
global FEEDBACK_STOP_FLAG
SR_Mode = getfamilydata('OperationalMode');
SR_GEV = getfamilydata('Energy');
BSCramprate = getfamilydata('BSCRampRate');
if isnan(BSCramprate) | isempty(BSCramprate)
    BSCramprate = 0.4;
    setfamilydata(BSCramprate, 'BSCRampRate');
end
if nargin < 1
    action = 'Initialize';
end
if nargin < 2
    Input2 = 0;
end
if nargin < 3
    Input3 = 0;
end
if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
    FOFBcheckboxVal = 0;
else
    FOFBcheckboxVal = 1;
end
%%%%%%%%%%%%%%%%
% Main Program %
%%%%%%%%%%%%%%%%
switch(action)
    case 'StopOrbitFeedback'
        FEEDBACK_STOP_FLAG = 1;
    case 'Initialize'
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % GUI
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        ButtonWidth = 200;
        ButtonHeight  = 25;
        Offset1 = 8*25+12 + 47 + 25+25;
        Offset2 = 47+25+25;
        Offset3 = 45+25;
        Offset4 = 1;
        Offset5 = 30;
        FigWidth = ButtonWidth+6;
        FigHeight  = 3+7*(ButtonHeight+6)+24+Offset1;
        ButtonWidth = 200-6;
        % Change figure position
        set(0,'Units','pixels');
        p=get(0,'screensize');
        h0 = figure( ...
            'Color',[0.8 0.8 0.8], ...
            'HandleVisibility','Off', ...
            'Interruptible', 'on', ...
            'MenuBar','none', ...
            'Name','ALS SR CONTROL', ...
            'NumberTitle','off', ...
            'Units','pixels', ...
            'Position',[30 p(4)-FigHeight-40 FigWidth FigHeight+Offset5], ...
            'Resize','off', ...
            'Tag','SRCTRLFig1');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'FontWeight','Bold', ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+6*(ButtonHeight+3)+19+19+8+Offset1  ButtonWidth 20+Offset5], ...
            'Style','text', ...
            'String','', ...
            'Tag','SRCTRLTitle');
        % Frame Box I
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+1*(ButtonHeight+3)+Offset1-3+Offset5 ButtonWidth+6 7*ButtonHeight+18], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+7*(ButtonHeight+3)+Offset1  ButtonWidth 15+Offset5], ...
            'Style','text', ...
            'String','Lattice Setup Functions');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Cycle'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+6*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Cycle SR Lattice', ...
            'Tag','SRCTRLButton1');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Injection'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+5*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Injection', ...
            'Tag','SRCTRLButton2');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Production'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+4*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String',['Production'], ...
            'Tag','SRCTRLButton3');
        h1 = uicontrol('Parent',h0, ...
            'Callback',[...
            'fprintf(''\n'');' ...
            'disp([''   **********************************************'']);', ...
            'disp([''   **  Changing Storage Ring Operational Mode  **'']);', ...
            'disp([''   **********************************************'']);', ...
            'setoperationalmode;', ...
            'srcontrol5(''CheckInputs'');', ...
            'disp([''   ****************************'']);', ...
            'disp([''   **  Mode Change Complete  **'']);', ...
            'disp([''   ****************************'']);', ...
            'fprintf(''\n'');'], ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+3*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'Value',1, ...
            'String','Change Operational Mode', ...
            'Tag','SRCTRLButtonChangeMode');
        h1 = uicontrol(...
            'Parent',h0, ...
            'Callback', [...
            'srcontrol5(''CheckInputs'');',...
            'srcontrol5(''SRState'');'], ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+2*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Check For Problems', ...
            'Tag','SRCTRLButtonSRState');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs''); goldenpage;', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+1*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Golden Page', ...
            'Tag','SRCTRLButtonGoldenPage');
        % Frame Box II
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+7*(ButtonHeight+3)-29+Offset2+Offset5 ButtonWidth+6 2*ButtonHeight+15], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+8*(ButtonHeight+3)-10+Offset2 ButtonWidth .6*ButtonHeight+Offset5], ...
            'String','Global/Local Orbit Correction', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''OrbitCorrection'');', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+7*(ButtonHeight+3)-6+Offset2+Offset5 ButtonWidth ButtonHeight], ...
            'String','Correct Global Orbit w/ IDBPMs', ...
            'Tag','SRCTRLButtonOrbitCorrection');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''OrbitCorrectionSetup'',1);', ...
            'callback','srcontrol5(''OrbitCorrectionSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[6 7*(ButtonHeight+3)-22+Offset2+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Edit IDBPM, CM, & Local Bump Lists', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonOrbitCorrectionSetup');
        % Frame Box III
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 1.25*(ButtonHeight)+Offset3-45+Offset5 ButtonWidth+6 8*ButtonHeight+5], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+7*(ButtonHeight+3)+Offset3-25 ButtonWidth .55*ButtonHeight+Offset5], ...
            'String','Orbit Feedback', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+6*(ButtonHeight+3)+Offset3-18+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Slow Orbit Correction', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxSOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+5*(ButtonHeight+3)+Offset3-9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Fast Orbit Correction', ...
            'Style','checkbox', ...
            'Value',FOFBcheckboxVal,...
            'Tag','SRCTRLCheckboxFOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+4*(ButtonHeight+3)+Offset3+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct ID Tune Shift  ', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxTune');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+3*(ButtonHeight+3)+Offset3+9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct RF Frequency', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxRF');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''Feedback'');', ...
            'Enable','on', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[8 3+3*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Start FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStart');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''StopOrbitFeedback'');pause(0);', ...
            'Enable','off', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[.5*FigWidth+3 3+3*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Stop FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStop');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[14 3+2*(ButtonHeight)+14+Offset3-25+Offset5 ButtonWidth-14 .75*ButtonHeight], ...
            'String','Horizontal RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHorizontal');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[26 3+1.25*(ButtonHeight)+16+Offset3-25+Offset5 ButtonWidth-26 .75*ButtonHeight], ...
            'String','Vertical RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextVertical');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FeedbackSetup'',1);', ...
            'callback','srcontrol5(''FeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 3+1.25*(ButtonHeight)+.5+Offset3-25+Offset5 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit SOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFeedbackSetup');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FastFeedbackSetup'',1);', ...
            'callback','srcontrol5(''FastFeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 3+1.25*(ButtonHeight)+.5+Offset3-45+Offset5 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit FOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFastFeedbackSetup');
        % Frame Box IV
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+ButtonHeight+Offset4-14+Offset5 ButtonWidth+6 ButtonHeight+12], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+1.75*ButtonHeight+5+Offset4-21+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Storage Ring State', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHeader');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''CheckInputs'');', ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ForegroundColor','b', ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+ButtonHeight+6+3+2+Offset4-22+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','   ', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextInformation');
        % Frame Box "Close"
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 8 ButtonWidth+6 ButtonHeight+8], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'Callback','close(gcbf);', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 13 ButtonWidth ButtonHeight], ...
            'String','Close', ...
            'Tag','SRCTRLClose');
        % Update database channels
        setsrstatechannels;
        if nargout > 0
            fig = h0;
        end
    case 'Cycle'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        disp('   **************************');
        disp('   **  Storage Ring Cycle  **');
        disp('   **************************');
        a = clock; fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        BSCFlag = questdlg(sprintf('Cycle Superbend Magnets?'),'SR Cycle','Yes','No','No');
        %if strcmp(BSCFlag,'No')
        %    disp(['   ** Superbends will not be cycled. **']);
        %else
        %    disp(['   ** Superbends will be cycled during the second mini-cycle only. **']);
        %end
        ChicSQFlag = questdlg(sprintf('Cycle chicanes and skew quads and home motor chicanes?'),'SR Cycle','Yes','No','No');
        %if strcmp(ChicSQFlag,'No')
        %    disp(['   ** Chicanes and skew quads will not be cycled; motor chicanes will not be homed. **']);
        %else
        %    disp(['   ** Chicanes and skew quads will be cycled; motor chicanes will be homed. **']);
        %end
        StartFlag = questdlg(sprintf('Start %.1f GeV Cycle?',SR_GEV),'SR Cycle','Yes','No','No');
        if strcmp(StartFlag,'No')
            disp(['   ***************************']);
            disp(['   **    Cycle  Canceled    **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        end
        try
            if GapFlag
                % Make sure that the gaps are open with FF off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open.');
                    disp('   Opening all gaps at maximum speed.');
                    setff([], 1, 0);
                    disp('   Gap control disabled.');
                    disp('   Feed forward enabled.');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened.');
                    disp('   Feed forward and gap control disabled.');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled.');
                end
            else
                disp('   Feed forward and gap control disabled.');
            end
            setff([], 0, 0);
            pause(1);
            srcycle(BSCFlag, ChicSQFlag);
            setpv('SR_STATE',1);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Cycle failed due to error condition! \n\n');
            setpv('SR_STATE',-1);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp('   **********************************************');
            disp('   **  SR Cycle complete, ready for injection  **');
            disp('   **********************************************'); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp('   **********************************');
            disp('   **  Problem cycling SR lattice  **');
            disp('   **********************************'); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
    case 'Injection'
        AD = getad;
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            fprintf('   ***************************************************\n');
            fprintf('   **  Setup For %.2f GeV Injection (with ramping)  **\n', getfamilydata('InjectionEnergy'));
            fprintf('   ***************************************************\n');
            set_alarmhandler_AHU_thresholds_inject;
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',getfamilydata('InjectionEnergy')),'Injection Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            fprintf('   *************************************************\n');
            fprintf('   **  Setup For On Energy Injection at %.2f GeV  **\n', SR_GEV);
            fprintf('   *************************************************\n');
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',SR_GEV),'Injection Setup','Yes','Cancel','Cancel');
        end
        if strcmp(StartFlag,'Cancel')
            disp(['   ********************************']);
            disp(['   **  Injection Setup Canceled  **']);
            disp(['   ********************************']);
            set_alarmhandler_thresholds;
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                setff([],1,0);
                disp('   Gap control disabled');
                disp('   Feed forward enabled');
                pause(1);
                % Set IDs at max velocity w/ velocity profile off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    disp('   Opening all gaps');
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                end
                disp('   Gaps are open');
                disp('   Feed forward and gap control disabled');
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            if (AD.Energy-AD.InjectionEnergy) > 0.05
                % Ramp down to Injection Energy
                ErrorFlag = srramp('Injection');
                if ErrorFlag
                    error('Superbends over temperature.');
                end
                a = clock; fprintf('   %s %d:%d:%.0f\n\n',date, a(4), a(5), a(6));
            elseif (AD.Energy-AD.InjectionEnergy) < -0.05
                % first load injection lattice, then ramp to 1.9 GeV and back to 1.5 GeV to get onto same hysteresis branch
                srload('Injection');
                % load 1.9 GeV lattice
                tempfilename = sprintf('%s19nuy9prod.mat', getfamilydata('Directory','OpsData'));
                srload(tempfilename);
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                pause(5);
            end
            srload('Injection');
            setpv('SR_STATE',2);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Injection lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-2);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            if AD.Energy <= 1.5
                disp(['   *******************************************************************************']);
                disp(['   **  Function complete:  the storage ring is setup for injection at ',sprintf('%.2f',SR_GEV),' GeV  **']);
                disp(['   *******************************************************************************']);
                fprintf('\n');
            else
                fprintf('   **********************************************************************************************\n');
                fprintf('   **  Function complete:  the storage ring is setup for injection at %.2f GeV (upper branch)  **\n', getfamilydata('InjectionEnergy'));
                fprintf('   **********************************************************************************************\n');
                fprintf('\n');
            end
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   ************************************']);
            disp(['   **  Problem with injection setup  **']);
            disp(['   ************************************']);
            fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        %soundchord;
        setfamilydata(0.8, 'BSCRampRate');
    case 'Production'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        AD=getad;
        fprintf('\n');
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            disp('   ********************************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation (with ramping)  **',SR_GEV));
            disp('   ********************************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            disp('   *****************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation  **',SR_GEV));
            disp('   *****************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Yes','Cancel','Cancel');
        end
        if strcmp(StartFlag,'Cancel')
            disp(['   ***************************']);
            disp(['   **  User Setup Canceled  **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                % Make sure that the gaps are open
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open');
                    disp('   Opening all gaps at maximum speed');
                    setff([], 1, 0);
                    disp('   Gap control disabled');
                    disp('   Feed forward enabled');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened');
                    disp('   Feed forward and gap control disabled');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled');
                end
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            % Ramp up to the production lattice
            ErrorFlag = srramp('Production');
            if ErrorFlag
                error('Superbends over temperature.');
            end
            a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            srload('Production');
            if GapFlag
                setff([], 1, 0);
                disp('   Gap control disabled');
                disp('   Feed forward enable');
                pause(1);
                disp('   Insertion device velocity profile boolean control off');
                disp('   Closing all gaps at maximum speed');
                % Set IDs at max velocity w/ velocity profile off
                [Position, Velocity, RunFlag, UserGap] = getid;
                setid([], UserGap, maxsp('IDvel'), 1, 0, 1);
                % Turn velocity profile on
                disp('   Insertion device velocity profile boolean control is on');
                setid([], [], maxsp('IDvel'), 1, 1, 0);
                disp('   Gaps are closed');
                setff([4;7;8;9;10;12], 1, 1);
                setff(5, 1, 0);
                disp('   Gap control enabled (except sector 5 (W16))');
            end
            set_alarmhandler_thresholds_new;
            setpv('SR_STATE',3);
        catch
            fprintf('   %s \n', lasterr);
            fprintf('   User lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-3);
        end
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp(['   **************************************************************************']);
            disp(['   **  Function complete:  the storage ring is setup for users at ',sprintf('%.1f',SR_GEV),' GeV  **']);
            disp(['   **************************************************************************']); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   *************************************']);
            disp(['   **  Problem with production setup  **']);
            disp(['   *************************************']); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        setfamilydata(0.8, 'BSCRampRate');
    case 'CheckInputs'
        SR_GEV = getfamilydata('Energy');
        AD=getad;
        setsrstatechannels;
        set(0,'showhiddenhandles','on');
        if AD.Energy > 1.55
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Down)']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users (Ramp Up)']);
        elseif AD.Energy < 1.45
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Up+cycle)']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV (Ramp Down)']);
        else
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV']);
        end
        set(findobj('Tag','SRCTRLTitle'),'String',SR_Mode);
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
        else
            set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
        end
        set(0,'showhiddenhandles','off');
    case 'SRState'
        NumErrors = 0;
        fprintf('\n');
        disp('   ***********************************');
        disp('   **  Checking Storage Ring State  **');
        disp('   ***********************************');
        a = clock;
        fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        %       FileName = getpv('SR_LATTICE_FILE','String');   % Last srload file name (in OLD MIDDLE LAYER nomenclature!!)
        GeVnow = bend2gev;
        if GeVnow == getfamilydata('Energy')
            [ConfigSetpoint, ConfigMonitor, FileName] = getproductionlattice;
        elseif GeVnow == getfamilydata('InjectionEnergy')
            [ConfigSetpoint, ConfigMonitor, FileName] = getinjectionlattice;
        else
            FileName = '';
        end
        [StateNumber, StateString] = getsrstate;
        fprintf('   Storage ring operational mode: %s\n', SR_Mode);
        if StateNumber < 0
            fprintf('   Storage ring state error: %s\n', StateString);
            NumErrors = NumErrors + 1;
        else
            fprintf('   Storage ring state: %s\n', StateString);
        end
        if StateNumber==0
            % Storage ring state unknown
            NumErrors = NumErrors + 1;
        elseif abs(StateNumber)==1 || abs(StateNumber)==2
            FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','InjectionFile') '.mat'];
            if ~strcmp(FileName, FileNameGoal)
                fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','InjectionFile'), FileName);
                NumErrors = NumErrors + 1;
            end
        else
            FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile') '.mat'];
            if ~strcmp(FileName, FileNameGoal)
                fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','LatticeFile'), FileName);
                NumErrors = NumErrors + 1;
            end
        end
        % Check all SR magnets
        if isempty(FileName)
            fprintf('   Goal setpoints will not be checked since the last lattice load is unknown.\n');
            NumErrors1 = checksrmags('');
        else
%            NumErrors1 = checksrmags([getfamilydata('Directory','OpsData') FileName]);
            NumErrors1 = checksrmags(FileName);
        end
        if NumErrors1 == 0
            fprintf('   SR magnets power supplies are OK.\n');
        end
        NumErrors = NumErrors + NumErrors1;
        % Check RF frequency
        if isempty(FileName)
            fprintf('   RF frequency will not be checked since the last lattice load is unknown.\n');
        else
%            load([getfamilydata('Directory','OpsData'), FileName]);
            load(FileName);
            [tmp, RFHPCounterPresent] = getrf;
            if abs(RFHPCounterPresent-ConfigSetpoint.RF.Setpoint.Data) > .002
                NumErrors = NumErrors + 1;
                fprintf('   RF frequency should be %f, presently it is %f MHz (as measured by the HP counter).\n', ConfigSetpoint.RF.Setpoint.Data, RFHPCounterPresent);
            else
                fprintf('   RF frequency is OK (HP counter is %f MHz, at the time of the lattice save it was %f MHz).\n', RFHPCounterPresent, ConfigSetpoint.RF.Setpoint.Data);
            end
        end
        % Check for orbit problems
        if (StateNumber >= 3) & (getdcct > 2)   % Production lattice is loaded with beam in the machine
            Xtol = 0.070;
            Ytol = 0.010;
            NumErrors1 = checksrorbit([],Xtol,Ytol);
            if NumErrors1
                fprintf('   SR orbit in the ID straight sections or at Bergoz BPMs deviates more than allowed from the golden orbit.\n');
            else
                fprintf('   SR orbit in the ID straight sections and at Bergoz BPMs is OK.\n');
                fprintf('   The orbit is within %.3f mm horizontally and %.3f mm vertically', Xtol, Ytol);
            end
            NumErrors = NumErrors + NumErrors1;
        else
            fprintf('   Storage ring orbit was not checked.\n');
        end
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        if NumErrors
            disp('   *********************************');
            disp('   **  Storage Ring Has Problems  **');
            disp('   *********************************');
        else
            disp('   **********************************');
            disp('   **  Storage Ring Lattice is OK  **');
            disp('   **********************************');
        end
        fprintf('   \n');
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
        end
        set(0,'showhiddenhandles','off');
    case 'OrbitCorrection'
        fprintf('\n');
        fprintf('   *********************************\n');
        fprintf('   **  Starting Orbit Correction  **\n');
        fprintf('   *********************************\n');
        a = clock;
        fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        StartFlag = questdlg(sprintf('Start orbit correction, %.1f GeV?',SR_GEV),'Orbit Correction','Yes','No','No');
        if strcmp(StartFlag,'No')
1000             disp(['   ********************************']);
1001             disp(['   **  Orbit Correction Aborted  **']);
1002             disp(['   ********************************']);
1003             fprintf('\n');
1004             return
1005         end
1006
1007         if getdcct < 5     % Don't correct the orbit if the current is too small
1008             fprintf('   Orbit not corrected due to small current.\n');
1009             return
1010         end
1011
1012         if abs(SR_GEV-bend2gev(getpv('BEND',[1 1])))>  0.05     % Don't use this routine for the injection lattice
1013             fprintf('   This routine should only be used for the production energy: Correction aborted\n');
1014             return
1015         end
1016
1017         SR_STATE_OLD = scaget('SR_STATE');
1018         set(0,'showhiddenhandles','on');
1019         setpv('SR_STATE',4);
1020         [StateNumber, StateString] = getsrstate;
1021         if StateNumber >= 0
1022             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1023         else
1024             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1025         end
1026         set(0,'showhiddenhandles','off');
1027
1028
1029         try
1030
1031             % 2 Hz update rate on IDBPMs
1032             disp('   IDBPM time constant set to 0.5s.')
1033             setbpmtimeconstant(0.5)
1034             pause(2);
1035
1036
1037             % Turn off feed forward
1038             fprintf('   Turning feed forward off.\n');
1039             [FFEnableBM, FFEnableBC] = getff;
1040             setff([], 0);
1041             scasleep(.2);
1042
1043
1044             % Get vectors
1045             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1046             LocalBumplist = FB.LocalBumplist;
1047
1048         catch
1049
1050             fprintf('   %s \n',lasterr);
1051             fprintf('   Orbit correction setup failed due to error condition! \n\n');
1052             setpv('SR_STATE',-4);
1053             set(0,'showhiddenhandles','on');
1054             [StateNumber, StateString] = getsrstate;
1055             if StateNumber >= 0
1056                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1057             else
1058                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1059             end
1060             set(0,'showhiddenhandles','off');
1061             return
1062
1063         end
1064
1065         iNotHCMChicane = find(FB.HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
1066         iHCMChicane = find(FB.HCMlist1(:,2) == 10);
1067         iNotVCMChicane = find(FB.VCMlist1(:,2) < 10);
1068         iVCMChicane = find(FB.VCMlist1(:,2) == 10);
1069
1070         fprintf('   Starting horizontal and vertical global orbit correction (SVD method).\n');
1071
1072         for iloop = 1:3
1073             try
1074                 % use the following to get corrector settings in OCS without setting them, so the values can be checked
1075                 FB.OCSx = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
1076                 FB.OCSy = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
1077                 if any(abs(FB.OCSx.CM.Delta(iNotHCMChicane)) > 5)
1078                   disp('   Orbit Correction is changing some horizontal corrector(s) > 5A!!');
1079                 end
1080                 if any(abs(FB.OCSy.CM.Delta(iNotVCMChicane)) > 5)
1081                   disp('   Orbit Correction is changing some vertical corrector(s) > 5A!!');
1082                 end
1083                 if any(abs(FB.OCSx.CM.Delta(iHCMChicane)) > 10)
1084                   disp('   Orbit Correction is changing some horizontal chicane corrector(s) > 10A!!');
1085                 end
1086                 if any(abs(FB.OCSy.CM.Delta(iVCMChicane)) > 10)
1087                   disp('   Orbit Correction is changing some vertical chicane corrector(s) > 10A!!');
1088                 end
1089
1090
1091                 % Correct horizontal orbit
1092                 FB.OCSx = setorbit(FB.OCSx,'NoDisplay');
1093                 % Correct vertical orbit
1094                 FB.OCSy = setorbit(FB.OCSy,'NoDisplay');
1095
1096
1097                 % Check for current in machine - stop orbit correction if DCCT < 5mA
1098                 if (getdcct < 4.5)
1099                     error('**There is less than 5mA in the machine! Stopping orbit correction.');
1100                 end
1101
1102                 % Check state of gaps - stop orbit correction if any are moving
1103                 GAPrunflag = getpv('ID','RunFlag');
1104                 if any(GAPrunflag-round(GAPrunflag))
1105                     error('**One or more of the gaps are moving! Stopping orbit correction.');
1106                 end
1107
1108                 x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
1109                 y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
1110                 fprintf('   %d. Horizontal RMS = %.3f mm\n', iloop, norm(x)/sqrt(length(x)));
1111                 fprintf('   %d.   Vertical RMS = %.3f mm\n', iloop, norm(y)/sqrt(length(y)));
1112
1113             catch
1114                 % fprintf('   %s \n',lasterr);
1115                 fprintf('   Orbit correction failed due to error condition!\n  Fix the problem, reload the lattice (srload), and try again.  \n\n');
1116                 setpv('SR_STATE',-4);
1117                 set(0,'showhiddenhandles','on');
1118                 [StateNumber, StateString] = getsrstate;
1119                 if StateNumber >= 0
1120                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1121                 else
1122                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1123                 end
1124                 set(0,'showhiddenhandles','off');
1125                 return
1126             end
1127         end
1128
1129
1130         % Set user bumps w/o sextupole correctors
1131         try
1132
1133             %turn up corrector speed here to quicken setting bumps
1134             HCMramprate = getpv('HCM', 'RampRate');
1135             VCMramprate = getpv('VCM', 'RampRate');
1136             setpv('HCM', 'RampRate', 10, [], 0);
1137             setpv('VCM', 'RampRate', 10, [], 0);
1138
1139             if ~isempty(LocalBumplist)
1140                 fprintf('   Setting local bumps in the straight sections.\n');
1141                 for loop = 1:size(LocalBumplist,1)
1142
1143                     % Check for current in machine - stop orbit correction if DCCT < 5mA
1144                     if (getdcct < 5)
1145                         error('** There is less than 5mA in the machine! Stopping local bumps.');
1146                     end
1147
1148                     % Check state of gaps - stop setting bumps if any are moving
1149                     GAPrunflag = getpv('ID','RunFlag');
1150                     if any(GAPrunflag-round(GAPrunflag))
1151                         error('** One or more of the gaps are moving! Stopping local bumps.');
1152                     end
1153
1154                     HCMoldsp = getsp('HCM', FB.HCMlist1);
1155                     VCMoldsp = getsp('VCM', FB.VCMlist1);
1156
1157                     if any(LocalBumplist(loop,1) == [4 6 11])
1158                         if LocalBumplist(loop,2) == 0
1159                             % Upstream bump
1160                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1161                             if isempty(iRemove)
1162                                 setbumps(LocalBumplist(loop,:), 1);
1163                             else
1164                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1165                             end
1166                         elseif LocalBumplist(loop,2) == 1
1167                             % Upstream bump
1168                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;],FB.OCSx.BPM.DeviceList);
1169                             if isempty(iRemove)
1170                                 setbumps(LocalBumplist(loop,:), 1);
1171                             else
1172                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1173                             end
1174                         else
1175                             % Downstream bump
1176                             [i, iRemove] = findrowindex([LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1177                             if isempty(iRemove)
1178                                 setbumps(LocalBumplist(loop,:), 1);
1179                             else
1180                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1181                             end
1182                         end
1183                     else
1184                         [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1185                         if isempty(iRemove)
1186                             setbumps(LocalBumplist(loop,:), 1);
1187                         else
1188                             fprintf('\n   BPMs missing from Sector %02d - skipping local bump for that sector.\n\n', LocalBumplist(loop,1));
1189                         end
1190                     end
1191
1192                     HCMnewsp = getsp('HCM', FB.HCMlist1);
1193                     VCMnewsp = getsp('VCM', FB.VCMlist1);
1194                     % Remove center chicane trim from corrector check
1195                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 5) | (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 10)
1196                         error('**Setbumps caused some corrector magnet currents to change by more than 5(Horiz)/10(Vert) A!');
1197                     end
1198                     % Now check center chicane trims
1199                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 10) | (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 15)
1200                         error('**Setbumps caused some chicane trim magnet currents to change by more than 10(Horiz)/15(Vert) A!');
1201                     end
1202                 end
1203             end
1204
1205             %restore corrector speeds
1206             setpv('HCM', 'RampRate', HCMramprate, [], 0);
1207             setpv('VCM', 'RampRate', VCMramprate, [], 0);
1208
1209         catch
1210             fprintf('   %s \n',lasterr);
1211             fprintf('   Setbumps failed due to error condition!  Fix the problem, reload the lattice (srload), and try again.\n\n');
1212             setpv('SR_STATE',-4);
1213             set(0,'showhiddenhandles','on');
1214             [StateNumber, StateString] = getsrstate;
1215             if StateNumber >= 0
1216                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1217             else
1218                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1219             end
1220             set(0,'showhiddenhandles','off');
1221             return
1222         end
1223
1224
1225         % Turn feed forward back to it's original state
1226         if any(FFEnableBC)
1227             fprintf('   Turning feed forward back on.\n');
1228             setff([], FFEnableBC);
1229         end
1230
1231
1232         a = clock;
1233         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1234         [StateNumber, StateString] = getsrstate;
1235         set(0,'showhiddenhandles','on');
1236         if StateNumber >= 0
1237             setpv('SR_STATE',4.1);
1238             [StateNumber, StateString] = getsrstate;
1239             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1240             fprintf('   *********************************\n');
1241             fprintf('   **  Orbit Correction Complete  **\n');
1242             fprintf('   *********************************\n\n');
1243         else
1244             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1245             fprintf('   *************************************\n');
1246             fprintf('   **  Problem With Orbit Correction  **\n');
1247             fprintf('   *************************************\n\n');
1248         end
1249         set(0,'showhiddenhandles','off');
1250         pause(0);
1251
1252
1253     case 'OrbitCorrectionSetup'
1254         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
1255
1256         if InitFlag
1257             % Setup feedback elements
1258             % disp('Orbit correction condition: InitFlag=1 -- debugging message');
1259
1260             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1261             % Edit the following lists to change default configuration of Orbit Correction %
1262             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1263             hlist=[];vlist=[];
1264             for Sector =1:12
1265                 if Sector == 1
1266                     vlist = [vlist;Sector 2;Sector 4;Sector 5;Sector 8];
1267                     hlist = [hlist;Sector 2;Sector 7];
1268                 elseif Sector == 3
1269                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1270                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1271                 elseif Sector == 5
1272                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1273                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1274                 elseif Sector == 10
1275                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1276                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1277                 elseif Sector == 12
1278                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 7];
1279                     hlist = [hlist;Sector 2;Sector 7];
1280                 else
1281                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8];
1282                     hlist = [hlist;Sector 2;Sector 7];
1283                 end
1284             end
1285             HCMlist1 = hlist;
1286             VCMlist1 = vlist;
1287
1288             BPMlist1 = [
1289                 1 2
1290                 1 5
1291                 1 6
1292                 1 10
1293                 2 1
1294                 2 5
1295                 2 6
1296                 2 9
1297                 3 2
1298                 3 5
1299                 3 6
1300                 3 10
1301                 3 11
1302                 3 12
1303                 4 1
1304                 4 5
1305                 4 6
1306                 4 10
1307                 5 1
1308                 5 5
1309                 5 6
1310                 5 10
1311                 5 11
1312                 5 12
1313                 6 1
1314                 6 5
1315                 6 6
1316                 6 10
1317                 7 1
1318                 7 5
1319                 7 6
1320                 7 10
1321                 8 1
1322                 8 5
1323                 8 6
1324                 8 10
1325                 9 1
1326                 9 5
1327                 9 6
1328                 9 10
1329                 10 1
1330                 10 5
1331                 10 6
1332                 10 10
1333                 10 11
1334                 10 12
1335                 11 1
1336                 11 5
1337                 11 6
1338                 11 10
1339                 12 1
1340                 12 5
1341                 12 6
1342                 12 9];
1343
1344             % SVD orbit correction
1345             Xivec = [1:28];
1346             Yivec = [1:48];
1347
1348
1349             LocalBumplist = [
1350               % 1 1
1351               % 2 1
1352               % 3 1
1353                 4 1
1354               % 4 2
1355                 5 1
1356                 6 1
1357               % 6 2
1358                 7 1
1359                 8 1
1360                 9 1
1361                 10 1
1362                 11 1
1363                 11 2
1364                 12 1
1365 ];
1366             %LocalBumplist = []
1367
1368             % initialize RFCorrFlag
1369             RFCorrFlag = 'Yes';
1370         else
1371
1372             % Get vectors
1373             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1374             BPMlist1 = FB.BPMlist1;
1375             HCMlist1 = FB.HCMlist1;
1376             VCMlist1 = FB.VCMlist1;
1377             Xivec = FB.Xivec;
1378             Yivec = FB.Yivec;
1379             LocalBumplist = FB.LocalBumplist;
1380             Xgoal = FB.Xgoal;
1381             Ygoal = FB.Ygoal;
1382             RFCorrFlag = FB.RFCorrFlag;
1383
1384             % Add button to change #ivectors, CMs, IDBPMs,
1385             EditFlag = 0;
1386             h_fig1 = figure;
1387             while EditFlag ~= 8
1388
1389                 % Sensitivity matrix
1390                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
1391                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
1392
1393                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1394                 % Can the call below work for setting FOFB RF parameter? %
1395                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1396                 if strcmpi(RFCorrFlag, 'Yes')
1397                     Sx = [Sx getdisp('BPMx',BPMlist1)];
1398                 end
1399
1400                 [Ux, SVx, Vx] = svd(Sx);
1401                 [Uy, SVy, Vy] = svd(Sy);
1402
1403
1404                 % Remove singular values greater than the actual number of singular values
1405                 i = find(Xivec>length(diag(SVx)));
1406                 if ~isempty(i)
1407                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
1408                     pause(0);
1409                     Xivec(i) = [];
1410                 end
1411                 i = find(Yivec>length(diag(SVy)));
1412                 if ~isempty(i)
1413                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
1414                     pause(0);
1415                     Yivec(i) = [];
1416                 end
1417
1418
1419                 Ax = Sx*Vx(:,Xivec);
1420                 Tx = inv(Ax'*Ax)*Ax';
1421
1422                 Ay = Sy*Vy(:,Yivec);
1423                 Ty = inv(Ay'*Ay)*Ay';
1424
1425
1426                 figure(h_fig1);
1427                 subplot(2,1,1);
1428                 semilogy(diag(SVx),'b');
1429                 hold on;
1430                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
1431                 ylabel('Horizontal');
1432                 title('Response Matrix Singular Values');
1433                 hold off;
1434                 subplot(2,1,2);
1435                 semilogy(diag(SVy),'b');
1436                 hold on;
1437                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
1438                 xlabel('Singular Value Number');
1439                 ylabel('Vertical');
1440                 hold off;
1441                 drawnow;
1442
1443                 if strcmp(RFCorrFlag,'No')
1444                     RFCorrState = 'NOT CORRECTED';
1445                 elseif strcmp(RFCorrFlag,'Yes')
1446                     RFCorrState = 'CORRECTED';
1447                 else
1448                     RFCorrState = '???';
1449                 end
1450
1451                 %         EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','HCM Chicane List','VCM Chicane List','IDBPM List','BBPM List','Change Golden Orbit',...
1452                 %            'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1453                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','BPM List','Change Golden Orbit',...
1454                     'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1455
1456                 if EditFlag == 1
1457                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
1458                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
1459                     titlestr='SVD Orbit Feedback';
1460                     lineNo=1;
1461                     answer=inputdlg(prompt,titlestr,lineNo,def);
1462                     if ~isempty(answer)
1463                         XivecNew = fix(str2num(answer{1}));
1464                         if isempty(XivecNew)
1465                             disp('   Horizontal E-vector cannot be empty.  No change made.');
1466                         else
1467                             if any(XivecNew<=0) | max(XivecNew)>length(diag(SVx))
1468                                 disp('   Error reading horizontal E-vector.  No change made.');
1469                             else
1470                                 Xivec = XivecNew;
1471                             end
1472                         end
1473                         YivecNew = fix(str2num(answer{2}));
1474                         if isempty(YivecNew)
1475                             disp('   Vertical E-vector cannot be empty.  No change made.');
1476                         else
1477                             if any(YivecNew<=0) | max(YivecNew)>length(diag(SVy))
1478                                 disp('   Error reading vertical E-vector.  No change made.');
1479                             else
1480                                 Yivec = YivecNew;
1481                             end
1482                         end
1483                     end
1484                 end
1485
1486                 if EditFlag == 2
1487                     List = getlist('HCM');
1488                     CheckList = zeros(size(List,1));
1489                     Elem = dev2elem('HCM', HCMlist1);
1490                     CheckList(Elem) = ones(size(Elem));
1491                     CheckList = CheckList(dev2elem('HCM',List));
1492                     newList = editlist(List, 'HCM', CheckList);
1493                     if isempty(newList)
1494                         fprintf('   Horizontal corrector magnet list cannot be empty.  No change made.\n');
1495                     else
1496                         HCMlist1 = newList;
1497                     end
1498                 end
1499
1500                 if EditFlag == 3
1501                     List = getlist('VCM');
1502                     CheckList = zeros(size(List,1));
1503                     Elem = dev2elem('VCM', VCMlist1);
1504                     CheckList(Elem) = ones(size(Elem));
1505                     CheckList = CheckList(dev2elem('VCM',List));
1506                     newList = editlist(List, 'VCM', CheckList);
1507                     if isempty(newList)
1508                         fprintf('   Vertical corrector magnet cannot be empty.  No change made.\n');
1509                     else
1510                         VCMlist1 = newList;
1511                     end
1512                 end
1513
1514                 if EditFlag == 4
1515                     ListOld = BPMlist1;
1516                     XgoalOld = Xgoal;
1517                     YgoalOld = Ygoal;
1518
1519                     % Full BPM list
1520                     List = [
1521                         1 2
1522                         1 5
1523                         1 6
1524                         1 10
1525                         2 1
1526                         2 5
1527                         2 6
1528                         2 9
1529                         3 2
1530                         3 5
1531                         3 6
1532                         3 10
1533                         3 11
1534                         3 12
1535                         4 1
1536                         4 5
1537                         4 6
1538                         4 10
1539                         5 1
1540                         5 5
1541                         5 6
1542                         5 10
1543                         5 11
1544                         5 12
1545                         6 1
1546                         6 5
1547                         6 6
1548                         6 10
1549                         7 1
1550                         7 5
1551                         7 6
1552                         7 10
1553                         8 1
1554                         8 5
1555                         8 6
1556                         8 10
1557                         9 1
1558                         9 5
1559                         9 6
1560                         9 10
1561                         10 1
1562                         10 5
1563                         10 6
1564                         10 10
1565                         10 11
1566                         10 12
1567                         11 1
1568                         11 5
1569                         11 6
1570                         11 10
1571                         12 1
1572                         12 5
1573                         12 6
1574                         12 9
1575                         ];
1576
1577                     CheckList = zeros(size(List,1),1);
1578                     if ~isempty(BPMlist1)
1579                         for i = 1:size(List,1)
1580                             k = find(List(i,1)==BPMlist1(:,1));
1581                             l = find(List(i,2)==BPMlist1(k,2));
1582
1583                             if isempty(k) | isempty(l)
1584                                 % Item not in list
1585                             else
1586                                 CheckList(i) = 1;
1587                             end
1588                         end
1589                     end
1590
1591                     newList = editlist(List, 'BPM', CheckList);
1592                     if isempty(newList)
1593                         fprintf('   BPM list cannot be empty.  No change made.\n');
1594                     else
1595                         BPMlist1 = newList;
1596                     end
1597
1598                     % Set the goal orbit to the golden orbit
1599                     Xgoal = getgolden('BPMx', BPMlist1);
1600                     Ygoal = getgolden('BPMy', BPMlist1);
1601
1602
1603                     % If a new BPM is added, then set the goal orbit to the golden orbit
1604                     for i = 1:size(BPMlist1,1)
1605
1606                         % Is it a new BPM?
1607                         k = find(BPMlist1(i,1)==ListOld(:,1));
1608                         l = find(BPMlist1(i,2)==ListOld(k,2));
1609
1610                         if isempty(k) | isempty(l)
1611                             % New BPM
1612                         else
1613                             % Use the old value for old BPM
1614                             Xgoal(i) = XgoalOld(k(l));
1615                             Ygoal(i) = YgoalOld(k(l));
1616                         end
1617                     end
1618                 end
1619
1620                 if EditFlag == 5
1621
1622                     ChangeList = editlist(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
1623                     for i = 1:size(ChangeList,1)
1624
1625                         k = find(ChangeList(i,1)==BPMlist1(:,1));
1626                         l = find(ChangeList(i,2)==BPMlist1(k,2));
1627
1628                         prompt = {sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
1629                         def = {sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
1630                         titlestr = 'CHANGE THE GOAL ORBIT';
1631                         lineNo = 1;
1632                         answer = inputdlg(prompt, titlestr, lineNo, def);
1633
1634                         if isempty(answer)
1635                             % No change
1636                             fprintf('   No change was made to the golden orbit.\n');
1637                         else
1638                             Xgoalnew = str2num(answer{1});
1639                             if isempty(Xgoalnew)
1640                                 fprintf('   No change was made to the horizontal golden orbit.\n');
1641                             else
1642                                 Xgoal(k(l)) = Xgoalnew;
1643                             end
1644
1645                             Ygoalnew = str2num(answer{2});
1646                             if isempty(Ygoalnew)
1647                                 fprintf('   No change was made to the vertical golden orbit.\n');
1648                             else
1649                                 Ygoal(k(l)) = Ygoalnew;
1650                             end
1651                         end
1652                     end
1653                     if ~isempty(ChangeList)
1654                         fprintf('   Note:  changing the goal orbit for "Orbit Correction" does not change the goal orbit for "Slow Orbit Feedback."\n');
1655                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
1656                     end
1657                 end
1658
1659                 if EditFlag == 6
1660                     List = [
1661                         1 1
1662                         2 1
1663                         3 1
1664                         4 1
1665                         4 2
1666                         5 1
1667                         6 1
1668                         6 2
1669                         7 1
1670                         8 1
1671                         9 1
1672                         10 1
1673                         11 1
1674                         11 2
1675                         12 1];
1676                     CheckList = zeros(size(List,1),1);
1677                     if ~isempty(LocalBumplist)
1678                         for i = 1:size(List,1)
1679                             k = find(List(i,1)==LocalBumplist(:,1));
1680                             l = find(List(i,2)==LocalBumplist(k,2));
1681
1682                             if isempty(k) | isempty(l)
1683                                 % Item not in list
1684                             else
1685                                 CheckList(i) = 1;
1686                             end
1687                         end
1688                     end
1689                     LocalBumplist = editlist2(List, 'Sector', CheckList);
1690                 end
1691
1692                 if EditFlag == 7
1693                     RFCorrFlag = questdlg(sprintf('Set RF Frequency during Orbit Correction?'),'RF Frequency','Yes','No', 'No');
1694                     if strcmp(RFCorrFlag,'No')
1695                         disp(['   RF Frequency will not be included in global orbit correction.']);
1696                     elseif strcmp(RFCorrFlag,'Yes')
1697                         disp(['   RF Frequency will be included in global orbit correction.']);
1698                     end
1699
1700                 end
1701             end
1702             close(h_fig1);
1703         end
1704
1705 %  ORBIT CORRECTION STRUCTURE (OCS)
1706 %    OCS.BPM (data structure)
1707 %    OCS.CM  (data structure)
1708 %    OCS.GoalOrbit
1709 %    OCS.NIter
1710 %    OCS.SVDIndex
1711 %    OCS.IncrementalFlag = 'Yes'/'No'
1712 %    OCS.BPMWeight
1713 %    OCS.Flags = { 'FitRF' , etc.  }
1714         OCSx.BPM = getx(BPMlist1, 'struct');
1715         OCSx.CM = getsp('HCM', HCMlist1, 'struct');
1716         OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
1717         OCSx.NIter = 1;
1718         OCSx.SVDIndex = Xivec;
1719         OCSx.IncrementalFlag = 'No';
1720         OCSx.FitRF = 1;
1721         OCSy.BPM = gety(BPMlist1, 'struct');
1722         OCSy.CM = getsp('VCM', VCMlist1, 'struct');
1723         OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
1724         OCSy.NIter = 1;
1725         OCSy.SVDIndex = Yivec;
1726         OCSy.IncrementalFlag = 'No';
1727         OCSy.FitRF = 0;
1728
1729         % Save vectors
1730         FB.OCSx = OCSx;
1731         FB.OCSy = OCSy;
1732
1733         FB.BPMlist1 = BPMlist1;
1734         FB.HCMlist1 = HCMlist1;
1735         FB.VCMlist1 = VCMlist1;
1736         FB.Xivec = Xivec;
1737         FB.Yivec = Yivec;
1738         FB.Xgoal = OCSx.GoalOrbit;
1739         FB.Ygoal = OCSy.GoalOrbit;
1740         FB.RFCorrFlag = RFCorrFlag;
1741         FB.LocalBumplist = LocalBumplist;
1742         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata',FB);
1743
1744
1745     case 'Feedback'
1746
1747         FBloopIter = 1;
1748         if get(findobj(gcbf,'Tag','SRCTRLCheckboxFOFB'),'Value') == 1
1749             StartFOFBFlag = 1;
1750         else
1751             StartFOFBFlag = 0;
1752         end
1753
1754         FEEDBACK_STOP_FLAG = 0;
1755         HWarnNum=0;
1756         VWarnNum=0;
1757
1758         SR_GeV = getenergy;
1759         % Feedback loop setup
1760         PlotInfoFlag = 0;           % Plot micado stuff
1761         LoopDelay = 1.0;           % Period of feedback loop [seconds], make sure the BPM averaging is correct
1762         VCM_LSB = .00366211;
1763         VCMCHICANE_LSB = .002441;   % 80 max?,  Note: not fully implemented
1764
1765         if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
1766             Xgain  = 0.2;
1767             Ygain  = 0.1;
1768         else
1769             Xgain  = 0.8; % raised 0.5->0.8 at 17:20, 3-2-05 to more quickly correct EPU4 fast switching orbit distortions
1770             Ygain  = 0.8;
1771         end
1772
1773         % Load lattice set for tune feed forward
1774         ConfigSetpoint = getproductionlattice;
1775         %load([getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile')]);
1776         QFsp = ConfigSetpoint.QF.Setpoint.Data;
1777         QDsp = ConfigSetpoint.QD.Setpoint.Data;
1778         TuneW16Min = gap2tune(5, 13.23, 1.8909);
1779         % Tune response matrix
1780         SR_TUNE_MATRIX = gettuneresp({'QF','QD'}, {[],[]}, getenergy('Production'));    % Approx. [0.1944 -0.0286;-0.1182 0.1526];
1781         %SR_TUNE_MATRIX = [0.1641 -0.0245
1782         %                 -0.1149 0.1477];
1783
1784         % ID tune compensation does not work in the injection lattice, so ...
1785         if abs(SR_GEV - bend2gev)>  0.05     % Don't use this routine for the injection lattice
1786             fprintf('   This routine should only be used for the production energy: Orbit feedback aborted\n');
1787             return
1788         end
1789
1790         set(0,'showhiddenhandles','on');
1791
1792         try
1793             fprintf('\n');
1794             fprintf('   *******************************\n');
1795             fprintf('   **  Starting Orbit Feedback  **\n');
1796             fprintf('   *******************************\n');
1797             a = clock;
1798             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1799             fprintf('   Note: the Matlab command window will be used to display status information.\n');
1800             fprintf('         It cannot be used to enter commands during slow orbit feedback.\n');
1801
1802
1803             % >= 2 Hz update rate on IDBPMs
1804             disp('   IDBPM time constant set to 0.2s.')
1805             setbpmtimeconstant(0.2)
1806             pause(1.1);
1807
1808             % Check whether bumps and kickers are on and warn to turn off before starting feedback if necessary
1809             try
1810                 if (getsp('SR01S___BUMP1__BC21')==1 & getsp('SR01S___BUMP1P_BC22')==1) | (getsp('SR01S___SEK____BC21')==1 & getsp('SR01S___SEK_P__BC23')==1) | (getsp('SR01S___SEN____BC20')==1 & getsp('SR01S___SEN_P__BC22')==1)
1811                     soundtada;
1812                     fprintf('   \n');
1813                     fprintf('   *********************************************************************************\n');
1814                     fprintf('   ** One or more of the pulsed SR injection magnets is still on!  Turn them off! **\n');
1815                     fprintf('   *********************************************************************************\n');
1816                     fprintf('   \n');
1817                 end
1818             catch
1819                 disp('**Problem checking the state of the bumps and kickers - please check that they are not pulsing.');
1820             end
1821
1822             % Get vectors
1823
1824             % is there a need to set these up? (we do later calls to FB.OCSx..., not the bare OCSx...) %
1825             %            OCSx = FB.OCSx;
1826             %            OCSy = FB.OCSy;
1827
1828             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
1829
1830             BPMlist1 = FB.OCSx.BPM.DeviceList;
1831             % FOFB_BPMlist =
1832             HCMlist1 = FB.HCMlist1;
1833             VCMlist1 = FB.VCMlist1;
1834             Xivec = FB.Xivec;
1835             Yivec = FB.Yivec;
1836             Xgoal = FB.OCSx.GoalOrbit;
1837             Ygoal = FB.OCSy.GoalOrbit;
1838             FFTypeFlag = FB.FFTypeFlag;   %local or global tune correction
1839
1840             iNotHCMChicane = find(HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
1841             iHCMChicane = find(HCMlist1(:,2) == 10);
1842             iNotVCMChicane = find(VCMlist1(:,2) < 10);
1843             iVCMChicane = find(VCMlist1(:,2) == 10);
1844
1845             % Sensitivity matrix for setting fast feedback setpoints
1846             Sx1 = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
1847             Sy1 = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
1848
1849             % Sx3 = getrespmat('BPMx', BPMlist1, 'HQMOFM', [1 1], [], SR_GEV);
1850             % Sy3 = getrespmat('BPMy', BPMlist1, 'HQMOFM', [1 1], [], SR_GEV);
1851
1852         catch
1853             fprintf('\n  %s \n',lasterr);
1854
1855             % >= 2 Hz update rate on IDBPMs
1856             disp('   IDBPM time constant set to 0.25s.')
1857             setbpmtimeconstant(0.25)
1858
1859
1860             a = clock;
1861             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1862             fprintf('   *************************************************************\n');
1863             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
1864             fprintf('   *************************************************************\n\n');
1865             set(0,'showhiddenhandles','off');
1866             pause(0);
1867
1868             return
1869         end
1870
1871         StartFlag = questdlg(strvcat('','Is it OK to start orbit feedback?'),'Orbit Feedback','Yes','No','No');
1872         if strcmp(StartFlag,'No')
1873             % >= 2 Hz update rate on IDBPMs
1874             disp('   IDBPM time constant set to 0.25s.')
1875             setbpmtimeconstant(0.25)
1876
1877             a = clock;
1878             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1879             fprintf('   ***************************\n');
1880             fprintf('   **  Orbit Feedback Exit  **\n');
1881             fprintf('   ***************************\n\n');
1882             pause(0);
1883             return
1884         end
1885
1886         SR_STATE_OLD = scaget('SR_STATE');
1887         setpv('SR_STATE', 5);
1888         set(0,'showhiddenhandles','on');
1889         [StateNumber, StateString] = getsrstate;
1890         if StateNumber >= 0
1891             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1892         else
1893             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1894         end
1895         fprintf('   Using %d E-vectors horizontally.\n', length(Xivec));
1896         fprintf('   Using %d E-vectors vertically.\n',   length(Yivec));
1897         fprintf('   Starting slow orbit correction every %.1f seconds.\n', LoopDelay);
1898         %  fprintf('   Resetting SR11 chicane motors every 20 seconds to fix drift problem.\n');
1899
1900         IDSector = getlist('ID');
1901
1902         try
1903
1904             % Get and display data
1905             x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
1906             y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
1907             STDx = norm(x)/sqrt(length(x));
1908             STDy = norm(y)/sqrt(length(y));
1909             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
1910             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
1911
1912             % write goldenorbit values to Fast Orbit Feedback
1913             try
1914                 write_goldenorbit_ffb;
1915             catch
1916                 disp('write_goldenorbit_ffb did not work!');
1917             end
1918             setpv('SR01____FFBON__BC00',2);
1919             pause(0);
1920
1921         catch
1922
1923             fprintf('\n  %s \n',lasterr);
1924
1925             % >= 2 Hz update rate on IDBPMs
1926             disp('   IDBPM time constant set to 0.25s.')
1927             setbpmtimeconstant(0.25);
1928
1929
1930             a = clock;
1931             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1932             fprintf('   *************************************************************\n');
1933             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
1934             fprintf('   *************************************************************\n\n');
1935
1936             setpv('SR_STATE',SR_STATE_OLD);
1937             [StateNumber, StateString] = getsrstate;
1938             if StateNumber >= 0
1939                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1940             else
1941                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1942             end
1943             set(0,'showhiddenhandles','off');
1944             pause(0);
1945
1946             return
1947
1948         end
1949
1950
1951         % Disable buttons
1952         set(0,'showhiddenhandles','on');
1953         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','off');
1954         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','on');
1955         set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','off');
1956         set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','off');
1957         set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','off');
1958         set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','off');
1959         set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','off');
1960         set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','off');
1961         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','off');
1962         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','off');
1963         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','off');
1964         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','off');
1965         set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','off');
1966         pause(0);
1967
1968
1969         % Initialize feedback loop
1970         StartTime = gettime;
1971         StartErrorTime = gettime;
1972         Xold = getx(FB.OCSx.BPM.DeviceList);
1973         Yold = gety(FB.OCSy.BPM.DeviceList);
1974         HQMOFM_stalenum = 0;
1975         pause(LoopDelay);
1976
1977         N_HCM = size(HCMlist1,1);
1978         N_VCM = size(VCMlist1,1);
1979
1980         N_RFMO = 1;
1981
1982         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
1983             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'SetRF','Nodisplay','Nosetsp');
1984         else
1985             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
1986         end
1987         [FB.OCSx, Smatx, Sx, Ux, Vx] = orbitcorrectionmethods(FB.OCSx);
1988
1989         [FB.OCSy, junk, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
1990         [FB.OCSy, Smaty, Sy, Uy, Vy] = orbitcorrectionmethods(FB.OCSy);
1991
1992
1993         %%%%%%%%%%%%%%%%%%%%%%%
1994         % Start feedback loop %
1995         %%%%%%%%%%%%%%%%%%%%%%%
1996
1997         % chicaneloop=1;  % loop variable for resetting drifting chicanes (see a few lines below)
1998         % fftest=figure;
1999
2000         setpv('SR01____FFBON__BC00',2); % put FOFB in open loop so beamnoise gets recorded even if FOFB is not enabled
2001
2002         while 1
2003             try
2004                 t00 = gettime;
2005
2006                 %          if chicaneloop==20 % reset SR11 motor chicane setpoints every 20s due to drifting positions
2007                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(6),[11 1],0);
2008                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(7),[11 2],0);
2009                 %             chicaneloop = 1;
2010                 %          else
2011                 %             chicaneloop = chicaneloop + 1;
2012                 %          end
2013
2014                 % Check if GUI has been closed
2015                 if isempty(gcbf)
2016                     FEEDBACK_STOP_FLAG = 1;
2017                     lasterr('SRCONTROL GUI DISAPPEARED!');
2018                     error('SRCONTROL GUI DISAPPEARED!');
2019                 end
2020
2021                 %%%%%%%%%%%%%%%%%%%%%%%
2022                 % Fast orbit feedback %
2023                 %%%%%%%%%%%%%%%%%%%%%%%
2024                 if StartFOFBFlag == 1 & FBloopIter > 3
2025                     setpv('SR01____FFBON__BC00',2);
2026                     pause(0.5);
2027                     setpv('SR01____FFBON__BC00',1);
2028                     StartFOFBFlag = 0;
2029                     pause(1);
2030                     FOFBOnStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2031                         getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2032                         getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2033                         getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2034                     if any(FOFBOnStatus==0) | any(FOFBOnStatus==2)
2035                         setpv('SR01____FFBON__BC00',2); % open FOFB loop
2036                         disp('************************************************************************************************************');
2037                         disp('** Problem turning on Fast Orbit Feedback system...                                                       **');
2038                         disp('** Check status of ffbsecXX crates - but remember that a crate reboot will turn off Quads in that sector! **');
2039                         disp('** Suggest disabling the "Fast Orbit Correction" checkbox and starting Orbit Feedback again.              **');
2040                         disp('************************************************************************************************************');
2041                     else
2042                         fprintf('   Starting Fast Orbit Feedback at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
2043                     end
2044                 end
2045
2046
2047                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2048                 % Horizontal plane "feedback" %
2049                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2050
2051                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxSOFB'),'Value') == 1
2052
2053                     % Get orbit and check that the BPMs are different from the last update
2054                     Xnew = getx(FB.OCSx.BPM.DeviceList);
2055
2056                     % Don't feedback if the current is too small
2057                     if getdcct < 5
2058                         FEEDBACK_STOP_FLAG = 1;
2059                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2060                         break;
2061                     end
2062
2063                     x = Xgoal - Xnew;
2064                     STDx = norm(x)/sqrt(length(x));
2065
2066                     if any(Xold == Xnew)
2067                         a = clock;
2068                         N_Stale_Data_Points = find((Xold==Xnew)==1);
2069                         for loop = N_Stale_Data_Points'
2070                             fprintf('   Stale data: BPMx(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSx.BPM.DeviceList(loop,1), FB.OCSx.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2071                         end
2072                     else
2073                         % Compute horizontal correction
2074
2075                         %%%OCSx0 = FB.OCSx;
2076                         FB.OCSx.BPM.Data = Xnew;
2077                         FB.OCSx = orbitcorrectionmethods(FB.OCSx, Smatx, Sx, Ux, Vx);
2078
2079                         %%%[FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
2080
2081                         % reduced feedback gain (implemented by Greg Portmann, December 2000)
2082                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2083                         % increased back to 0.8 C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2084                         % increased to 1.0, C. Steier, 2002-05-04, trim DACs
2085                         X = Xgain .* FB.OCSx.CM.Delta;
2086                         X(N_HCM+1) = 0.3*FB.OCSx.DeltaRF/4.988e-3;
2087                         %%%X = Xgain .* (FB.OCSx.CM.Data - OCSx0.CM.Data);
2088
2089                         % check for trim values+next step values, warn or stop FB as necessary
2090                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2091                         % need to extract Chicanes from this comparison or maybe check them first for range %
2092                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2093                         HCMtrimSP=getpv('HCM','Trim',HCMlist1);
2094                         HCMtrimSP_next = HCMtrimSP + X(1:N_HCM);
2095                         if max(abs(HCMtrimSP_next)) > 4
2096                             HCMtrimnum=find(abs(HCMtrimSP_next) > 4);
2097
2098                             % print message to screen
2099                             fprintf('**One or more of the horizontal correctors is at its maximum!! Stopping orbit feedback. \n');
2100                             fprintf('%s\n',datestr(now));
2101                             for loop = HCMtrimnum'
2102                                 fprintf('**%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2103                             end
2104
2105                             % send alphapage to operator pager
2106                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2107                             FEEDBACK_STOP_FLAG = 1;
2108
2109                             setpv('SR_STATE', -5);
2110                             [StateNumber, StateString] = getsrstate;
2111                             if StateNumber >= 0
2112                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2113                             else
2114                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2115                             end
2116                         end
2117
2118                         if FEEDBACK_STOP_FLAG == 1
2119                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2120                             if getpv('SR01____FFBON__BC00')==1
2121                                 disp('   Stopping Fast Orbit Feedback.');
2122                             end
2123                             setpv('SR01____FFBON__BC00',0);
2124                             pause(0.5);
2125                             setpv('SR01____FFBON__BC00',2);
2126                             break;
2127                         end
2128
2129                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2130                         pause(0);
2131
2132                         if max(abs(HCMtrimSP_next) > 3)
2133                             HCMtrimnum=find(abs(HCMtrimSP_next) > 3);
2134                             HWarnNum=HWarnNum+1;
2135                             if (HWarnNum==1 | rem(HWarnNum,120)==0)
2136
2137                                 % print message to screen every two minutes
2138                                 fprintf('**One or more of the horizontal corrector trims is above 3A or below -3A! \n');
2139                                 fprintf('%s\n',datestr(now));
2140                                 for loop = HCMtrimnum'
2141                                     fprintf('**%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2142                                 end
2143                                 fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2144
2145                                 %send alphapage to operator pager the first time then at 10 minutes
2146                                 if (HWarnNum==1 | HWarnNum==600)
2147                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageHCM.txt
2148                                 end
2149                             end
2150                         else
2151                             HWarnNum=0;
2152                         end
2153
2154                         % Don't feedback if the current is too small
2155                         if getdcct < 5
2156                             FEEDBACK_STOP_FLAG = 1;
2157                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2158                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2159                             break;
2160                         end
2161
2162                         if N_HCM > 0
2163                             steppv('HCM','Trim', X(iNotHCMChicane), HCMlist1(iNotHCMChicane,:), 0);
2164                             steppv('HCM','Setpoint', X(iHCMChicane), HCMlist1(iHCMChicane,:), 0);
2165                         end
2166
2167                         % write fast orbit feedback setpoints
2168                         if 1
2169                             %write_goldenorbit_ffb_2planes(1, Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM)+Sx3*X(length(X))/20, BPMlist1);
2170                             % should be corrected to include result of next frequency step ...
2171                             write_goldenorbit_ffb_2planes(1,Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM),BPMlist1);
2172                         end
2173
2174                         %fprintf('Horizontal Done: %f \n',gettime-t00);
2175
2176                         % RF feedback
2177                         HQMOFMsp_last = getpv('EG______HQMOFM_AC01');
2178
2179                         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2180                             if N_RFMO > 0
2181                                 if abs(X(end)/3) < .01
2182                                 % if abs(FB.OCSx.DeltaRF/3) < .01
2183                                     steppv('EG______HQMOFM_AC01', X(end));
2184                                 else
2185                                     steppv('EG______HQMOFM_AC01', 0.01*sign(X(end)));
2186                                 end
2187                             end
2188
2189                             HQMOFMsp_now = getpv('EG______HQMOFM_AC01');
2190
2191                             % Check for stale RF feedback
2192                             if HQMOFMsp_last == HQMOFMsp_now
2193                                 HQMOFM_stalenum = HQMOFM_stalenum + 1;
2194                                 if HQMOFM_stalenum == 30 % warn and message to pager if stale for 30 secs
2195                                     fprintf('**The RF is not responding to orbit feedback changes! \n');
2196                                     fprintf('%s\n',datestr(now));
2197                                     fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2198                                     fprintf('**ILC 73 controls the EG______HQMOFM_AC01 channel, which sets the RF frequency. \n');
2199                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstaleRFmessage.txt
2200                                 end
2201                                 if rem(HQMOFM_stalenum,120)==0 % message to screen every 2 minutes
2202                                     fprintf('**The RF is not responding to orbit feedback changes! (%s)\n',datestr(now));
2203                                 end
2204                             else
2205                                 HQMOFM_stalenum = 0;
2206                             end
2207
2208                         end
2209
2210                         %fprintf('RF Done: %f \n',gettime-t00);
2211
2212                         Xold = Xnew;
2213                     end % End horizontal correction
2214
2215
2216                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2217                     % Vertical plane "feedback" %
2218                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2219
2220                     % Get orbit and check that the BPMs are different from the last update
2221                     Ynew = gety(FB.OCSy.BPM.DeviceList);
2222
2223                     % Don't feedback if the current is too small
2224                     if getdcct < 5
2225                         FEEDBACK_STOP_FLAG = 1;
2226                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2227                         break;
2228                     end
2229
2230                     y = Ygoal - Ynew;
2231                     STDy = norm(y)/sqrt(length(y));
2232
2233                     if any(Yold == Ynew)
2234                         a = clock;
2235                         N_Stale_Data_Points = find((Yold==Ynew)==1);
2236                         for loop = N_Stale_Data_Points'
2237                             fprintf('   Stale data: BPMy(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSy.BPM.DeviceList(loop,1), FB.OCSy.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2238                         end
2239
2240                     else
2241
2242                         % Compute vertical correction
2243                         %%%OCSy0 = FB.OCSy;
2244                         FB.OCSy.BPM.Data = Ynew;
2245                         FB.OCSy = orbitcorrectionmethods(FB.OCSy, Smaty, Sy, Uy, Vy);
2246
2247                         %%%[FB.OCSy, RF, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
2248
2249                         % reduced feedback gain, C. Steier, 2001-03-25
2250                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2251                         % increased back to 0.8, C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2252                         % set to unity gain, C. Steier, 2002-05-04, trim DACs
2253                         Y = Ygain .* FB.OCSy.CM.Delta;
2254                         %%%Y = Ygain .* (FB.OCSy.CM.Data - OCSy0.CM.Data);
2255
2256                         % Just SVD correction
2257                         % warning('Not using "micado" correction in the vertical plane.');
2258
2259                         % check for trim values+next step values, warn or stop FB as necessary
2260                         VCMtrimSP = getpv('VCM','Trim',VCMlist1);
2261                         VCMtrimSP_next = VCMtrimSP + Y(1:N_VCM);
2262                         if max(abs(VCMtrimSP_next)) > 12
2263                             VCMtrimnum=find(abs(VCMtrimSP_next) > 12);
2264
2265                             % print message to screen
2266                             fprintf('**One or more of the vertical correctors is at its maximum!! Stopping orbit feedback. \n');
2267                             fprintf('%s\n',datestr(now));
2268                             for loop = VCMtrimnum'
2269                                 fprintf('**%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2270                             end
2271
2272                             % send alphapage to operator pager
2273                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2274                             FEEDBACK_STOP_FLAG = 1;
2275
2276                             setpv('SR_STATE', -5);
2277                             [StateNumber, StateString] = getsrstate;
2278                             if StateNumber >= 0
2279                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2280                             else
2281                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2282                             end
2283                         end
2284
2285                         if FEEDBACK_STOP_FLAG == 1
2286                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2287                             if getpv('SR01____FFBON__BC00')==1
2288                                 disp('   Stopping Fast Orbit Feedback.');
2289                             end
2290                             setpv('SR01____FFBON__BC00',0);
2291                             pause(0.5);
2292                             setpv('SR01____FFBON__BC00',2);
2293                             break;
2294                         end
2295
2296                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2297                         % pause(0);
2298
2299                         if max(abs(VCMtrimSP_next) > 4)
2300                             VCMtrimnum=find(abs(VCMtrimSP_next) > 4);
2301                             VWarnNum=VWarnNum+1;
2302                             if (VWarnNum==1 | rem(VWarnNum,120)==0)
2303
2304                                 % print message to screen every two minutes
2305                                 fprintf('**One or more of the vertical corrector trims is above 4A or below -4A! \n');
2306                                 fprintf('%s\n',datestr(now));
2307                                 for loop = VCMtrimnum'
2308                                     fprintf('**%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2309                                 end
2310                                 fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2311
2312                                 %send alphapage to operator pager the first time then at 10 minutes
2313                                 if (VWarnNum==1 | VWarnNum==600)
2314                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageVCM.txt
2315                                 end
2316                             end
2317                         else
2318                             VWarnNum=0;
2319                         end
2320
2321                         % Don't feedback if the current is too small
2322                         if getdcct < 5
2323                             FEEDBACK_STOP_FLAG = 1;
2324                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2325                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2326                             break;
2327                         end
2328
2329                         if N_VCM > 0
2330                             steppv('VCM','Trim', Y(iNotVCMChicane), VCMlist1(iNotVCMChicane,:), 0);
2331                             steppv('VCM','Setpoint', Y(iVCMChicane), VCMlist1(iVCMChicane,:), 0);
2332                         end
2333
2334                         % write fast orbit feedback setpoints
2335                         if 1
2336                             write_goldenorbit_ffb_2planes(2,Ynew(1:size(BPMlist1,1))+Sy1*Y(1:N_VCM),BPMlist1);
2337                         end
2338
2339                     end
2340
2341                     Yold = Ynew;
2342
2343                     %fprintf('Vertical Done: %f \n',gettime-t00);
2344                 end % End vertical correction
2345
2346
2347                 %%%%%%%%%%%%%%%%%%%%%
2348                 % Tune feed forward %
2349                 %%%%%%%%%%%%%%%%%%%%%
2350                 % We should do a Sector limit check
2351
2352
2353                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxTune'),'Value') == 1
2354
2355                     if strcmp(SR_Mode, '1.9 GeV, High Tune') || strcmp(SR_Mode, '1.9 GeV, Inject at 1.23') || strcmp(SR_Mode, '1.9 GeV, Two-Bunch')
2356
2357                         if strcmp(FFTypeFlag,'Local')
2358                             disp('  No local tune compensation available - global is the default now.');
2359                         elseif strcmp(FFTypeFlag,'Global')
2360
2361                             addQFsp = zeros(24,1);
2362                             addQDsp = zeros(24,1);
2363                             %The line below is for vectorized version of TuneFF code - other changes below not made yet
2364                             %actualgap = getid(IDSector);
2365                             for gapnum = 1:size(IDSector,1)
2366                                 % Change in tune and [QF;QD] from maximum gap
2367                                 actualgap = getid(IDSector(gapnum,:));
2368                                 [gapmin,gapmax] = gaplimit(IDSector(gapnum,:));
2369                                 if actualgap < (gapmin-1)
2370                                     actualgap = gapmax;
2371                                 end
2372
2373                                 if (IDSector(gapnum,1) == 4) | (IDSector(gapnum,1) == 11)
2374                                     if IDSector(gapnum,2) == 1
2375                                         modenamestr = sprintf('SR%02dU___ODS1M__DC00',IDSector(gapnum,1));
2376                                     else % if IDSector(gapnum,2) == 2
2377                                         modenamestr = sprintf('SR%02dU___ODS2M__DC00',IDSector(gapnum,1));
2378                                     end
2379                                     epumode = getpv(modenamestr);
2380
2381                                     DelQF = zeros(24,1);
2382                                     DelQD = zeros(24,1);
2383
2384                                     % [DelQF, DelQD] = ...
2385                                     %      ffdeltaquadepu(IDSector(gapnum,:), actualgap, getepu(IDSector(gapnum,:)), epumode, SR_GeV);
2386                                 else
2387                                     %[DelQF, DelQD] = ...
2388                                     %    ffdeltaquad(IDSector(gapnum,:), actualgap, SR_GeV);
2389                                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2390                                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2391
2392                                     % Tune response matrix
2393                                     % gettuneresp is too slow for orbit feedback
2394                                     %TuneResponseMat = [0.1641 -0.0245
2395                                     %    -0.1149 0.1477];
2396                                     %TuneResponseMat = gettuneresp({'QF','QD'}, {[],[]}, GeV);
2397                                     %TuneResponseMat = gettuneresp;  %('NoEnergyScaling'); or scale at the operational energy
2398
2399
2400                                     % Initialize
2401                                     DelQF  = zeros(length(QFsp), 1);
2402                                     DelQD  = zeros(length(QDsp), 1);
2403
2404                                     if strcmp(SR_Mode, '1.9 GeV, High Tune') ||  strcmp(SR_Mode, '1.9 GeV, Inject at 1.23') || strcmp(SR_Mode, '1.9 GeV, Two-Bunch')
2405
2406                                         % SR11 epu skew quadrupole feed forward
2407                                         % scale= -0.06;    % for nu_y = 8.20 lattice
2408                                         %               scale = -0.063;
2409                                         %               mid = ceil(length(epu_shift5)/2);
2410
2411                                         %               if getsp('SR11U___ODS1M__DC00')==0
2412                                         %                  gap=getid(11);
2413                                         %                  shift=getepu(11);
2414                                         %                  [gapmin,gapmax] = gaplimit(11);
2415                                         %                  if gap < (gapmin-1)
2416                                         %                     gap = gapmax;
2417                                         %                  end
2418                                         %                  corrval=sqrt(shift2tune(11,gap,25)/shift2tune(11,15.67,25))* ...
2419                                         %                     scale*interp1(epu_shift5,int_epu_grad5-int_epu_grad5(mid),shift,'spline');
2420                                         %                  setsp('SR11U___Q______AC01',corrval);
2421                                         %               end
2422
2423                                         if strcmp(FFTypeFlag,'Local')
2424                                             % Change in tune and [QF;QD] from maximum gap
2425                                             DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap, SR_GeV);
2426                                             fraccorr = 1.15 * DeltaNuY / TuneW16Min;
2427
2428                                             % Find which quads to change
2429                                             QuadList = [IDSector(gapnum,1)-1 1;IDSector(gapnum,1)-1 2;IDSector(gapnum,1) 1;IDSector(gapnum,1) 2];
2430                                             QuadElem = dev2elem('QF', QuadList);
2431
2432                                             if (IDSector(gapnum,1)==7) | (IDSector(gapnum,1)==10) | (IDSector(gapnum,1)==11)
2433                                                 QFfac = ([2.227520/2.237111; 2.239570/2.237111; 2.239570/2.237111; 2.227520/2.237111]-1) * fraccorr;
2434                                                 QDfac = ([2.432264/2.511045; 2.543089/2.511045; 2.543080/2.511045; 2.432264/2.511045]-1) * fraccorr;
2435                                             elseif (IDSector(gapnum,1)==5) | (IDSector(gapnum,1)==9)
2436                                                 QFfac = ([2.208418/2.219784; 2.225926/2.219784; 2.231777/2.237111; 2.233775/2.237111]-1) * fraccorr;
2437                                                 QDfac = ([2.386512/2.483259; 2.545907/2.483259; 2.474571/2.511045; 2.491079/2.511045]-1) * fraccorr;
2438                                             elseif (IDSector(gapnum,1)==4) | (IDSector(gapnum,1)==8) | (IDSector(gapnum,1)==12)
2439                                                 QFfac = ([2.233775/2.237111; 2.231777/2.237111; 2.225926/2.219784; 2.208418/2.219784]-1) * fraccorr;
2440                                                 QDfac = ([2.491079/2.511045; 2.474571/2.511045; 2.545907/2.483259; 2.386512/2.483259]-1) * fraccorr;
2441                                             else
2442                                                 QFfac = zeros(4,size(actualgap,2));
2443                                                 QDfac = zeros(4,size(actualgap,2));
2444                                             end
2445
2446                                             DelQF(QuadElem,:) = DelQF(QuadElem,:) + QFfac.*QFsp(QuadElem,:);
2447                                             DelQD(QuadElem,:) = DelQD(QuadElem,:) + QDfac.*QDsp(QuadElem,:);
2448
2449                                         elseif strcmp(FFTypeFlag,'Global')
2450                                             % Change in tune and [QF;QD] from maximum gap
2451
2452                                             DeltaNuX = 0;
2453                                             DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap, SR_GeV);
2454
2455                                             if (IDSector(gapnum,1) == 4) | (IDSector(gapnum,1) == 11)
2456                                                 % Remove sector 4 and 11 tune correction
2457                                                 DeltaNuY = 0;
2458                                             end
2459                                             % if (IDSector(gapnum,1) == 4) | (IDSector(gapnum,1) == 11)
2460                                             %     if IDSector(i,:) == [11 1]
2461                                             %         modenamestr = sprintf('SR%02dU___ODS1M__DC00',IDSector(gapnum,1));
2462                                             %         longshift=3;
2463                                             %     elseif IDSector(i,:) == [11 2]
2464                                             %         modenamestr = sprintf('SR%02dU___ODS2M__DC00',IDSector(gapnum,1));
2465                                             %         longshift=3;
2466                                             %     else
2467                                             %         modenamestr = sprintf('SR%02dU___ODS1M__DC00',IDSector(gapnum,1));
2468                                             %         longshift=0;
2469                                             %     end
2470                                             %     if getsp(modenamestr)==0
2471                                             %         % DeltaNuX = shift2tune(IDSector,actualgap(i,:),getepu(IDSector)+longshift)+0.005;
2472                                             %         DeltaNuX = 0;   % problem with beam stability (instability/resonance?) with nu_x = 14.25 for EPU shift at 25 mm
2473                                             %         DeltaNuY = 0;   % correct vertical tune shift of EPUs is very small
2474                                             %     else
2475                                             %         DeltaNuX = 0;
2476                                             %         DeltaNuY = 0;
2477                                             %     end
2478                                             % else
2479                                             %     DeltaNuX = 0;
2480                                             % end
2481
2482
2483                                             fraccorr = DeltaNuY ./ TuneW16Min;
2484
2485                                             % Find which quads to change
2486                                             QuadList = [IDSector(gapnum,1)-1 2; IDSector(gapnum,1) 1];
2487                                             QuadElem = dev2elem('QF',QuadList);
2488
2489                                             DeltaAmps = inv(SR_TUNE_MATRIX) * [(fraccorr*6.23e-4)-DeltaNuX; fraccorr*(-0.05301)];    %  DelAmps =  [QF; QD];
2490                                             %             if IDSector(gapnum,1)==5
2491                                             %                 DeltaAmps
2492                                             %             end
2493                                             DelQF = DelQF + DeltaAmps(1,:);
2494                                             DelQD = DelQD + DeltaAmps(2,:);
2495                                             %DelQF = DelQF + (DeltaAmps(1,:)' * ones(1,size(DelQF,1)))';  % Not any faster
2496                                             %DelQD = DelQD + (DeltaAmps(2,:)' * ones(1,size(DelQD,1)))';
2497
2498                                             DeltaAmpsLocal = 12*inv(SR_TUNE_MATRIX) * [-DeltaNuX;0];                       %  DelAmps =  [QF; QD];
2499                                             DelQF(QuadElem) = DelQF(QuadElem)+DeltaAmpsLocal(1,1);
2500                                             DelQD(QuadElem) = DelQD(QuadElem)+DeltaAmpsLocal(2,1);
2501
2502                                             if (IDSector(gapnum,1)==6) | (IDSector(gapnum,1)==7) | (IDSector(gapnum,1)==10) | (IDSector(gapnum,1)==11)
2503                                                 QFfac = ([2.243127/2.237111; 2.243127/2.237111]-1) * fraccorr;
2504                                                 QDfac = ([2.556392/2.511045; 2.556392/2.511045]-1) * fraccorr;
2505                                             elseif (IDSector(gapnum,1)==5) | (IDSector(gapnum,1)==9)
2506                                                 QFfac = ([2.225965/2.219784; 2.243096/2.237111]-1) * fraccorr;
2507                                                 QDfac = ([2.528950/2.483259; 2.556345/2.511045]-1) * fraccorr;
2508                                             elseif (IDSector(gapnum,1)==4) | (IDSector(gapnum,1)==8) | (IDSector(gapnum,1)==12)
2509                                                 QFfac = ([2.243096/2.237111; 2.225965/2.219784]-1) * fraccorr;
2510                                                 QDfac = ([2.556345/2.511045; 2.528950/2.483259]-1) * fraccorr;
2511                                             else
2512                                                 QFfac = zeros(2,size(actualgap,2));
2513                                                 QDfac = zeros(2,size(actualgap,2));
2514                                             end
2515
2516                                             DelQF(QuadElem,:) = DelQF(QuadElem,:) + QFfac.*QFsp(QuadElem,:);
2517                                             DelQD(QuadElem,:) = DelQD(QuadElem,:) + QDfac.*QDsp(QuadElem,:);
2518
2519                                         else
2520                                             error('Unknown type selected for tune FF');
2521                                         end
2522
2523                                     else
2524
2525                                         % SR11 epu skew quadrupole feed forward
2526
2527                                         %               scale= -0.06;  % for nu_y = 8.20 lattice
2528                                         % scale = -0.063;  % for nu_y = 9.20 lattice
2529                                         %               mid = ceil(length(epu_shift5)/2);
2530
2531                                         %               if getsp('SR11U___ODS1M__DC00')==0
2532                                         %                  gap=getid(11);
2533                                         %                  shift=getepu(11);
2534                                         %                  corrval=shift2tune(11,gap,25)/shift2tune(11,15.67,25)* ...
2535                                         %                     scale*interp1(epu_shift5,int_epu_grad5-int_epu_grad5(mid),shift,'spline');
2536                                         %                  setsp('SR11U___Q______AC01',corrval);
2537                                         %               end
2538
2539                                         % Change in tune and [QF;QD] from maximum gap
2540                                         DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap, SR_GeV);
2541
2542                                         if (IDSector(gapnum,1)==7) | (IDSector(gapnum,1)==10) | (IDSector(gapnum,1)==11)
2543                                             DeltaAmps = inv(SR_TUNE_MATRIX/12) * [zeros(size(DeltaNuY)); -DeltaNuY];    %  DelAmps =  [QF; QD];
2544                                             DeltaAmpsQF = [DeltaAmps(1,:); DeltaAmps(1,:)];
2545                                             DeltaAmpsQD = [DeltaAmps(2,:); DeltaAmps(2,:)];
2546                                         elseif (IDSector(gapnum,1)==5) | (IDSector(gapnum,1)==9)
2547                                             DeltaAmpsQF = [-1.0637; -0.5132] * DeltaNuY / 0.0181 * 0.37;
2548                                             DeltaAmpsQD = [-6.6328; -3.3434] * DeltaNuY / 0.0181 * 0.37;
2549                                         elseif (IDSector(gapnum,1)==4) | (IDSector(gapnum,1)==8) | (IDSector(gapnum,1)==12)
2550                                             DeltaAmpsQF = [-0.5132; -1.0637] * DeltaNuY / 0.0181 * 0.37;
2551                                             DeltaAmpsQD = [-3.3434; -6.6328] * DeltaNuY / 0.0181 * 0.37;
2552                                         else
2553                                             DeltaAmpsQF = zeros(2,size(actualgap,2));
2554                                             DeltaAmpsQD = zeros(2,size(actualgap,2));
2555                                         end
2556
2557                                         % Find which quads to change
2558                                         QuadList = [IDSector(gapnum,1)-1 1;IDSector(gapnum,1) 2];
2559                                         QuadElem = dev2elem('QF', QuadList);
2560
2561                                         DelQF(QuadElem,:) = DelQF(QuadElem,:) + DeltaAmpsQF;
2562                                         DelQD(QuadElem,:) = DelQD(QuadElem,:) + DeltaAmpsQD;
2563                                     end
2564                                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2565                                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2566                                 end
2567
2568                                 % if IDSector(gapnum,1)==5
2569                                 %     DelQF
2570                                 %     DelQD
2571                                 % end
2572
2573                                 addQFsp = addQFsp+DelQF;
2574                                 addQDsp = addQDsp+DelQD;
2575                             end
2576                         else
2577                             error('Unknown type selected for tune FF');
2578                         end
2579
2580                         % Set quadrupoles using main setpoint channels
2581                         setpv('QF', QFsp+addQFsp,[], 0);
2582                         setpv('QD', QDsp+addQDsp,[], 0);
2583
2584                         %                         % Set quadrupoles using FF setpoint channels
2585                         %                         setpv('QF', 'FF', addQFsp, [], 0);
2586                         %                         setpv('QD', 'FF', addQDsp, [], 0);
2587
2588                     else
2589                         disp('  No tune FF algorithm for non-production modes yet...');
2590                     end
2591                 end
2592                 ffdeltaquad_delay = toc;
2593                 %fprintf('tune FF delay = %.1f seconds\n',ffdeltaquad_delay);
2594                 % fprintf('Tune Done: %f \n',gettime-t00);
2595
2596                 % Output info to screen
2597                 set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
2598                 set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
2599                 pause(0);
2600
2601
2602                 %fprintf('End of feedback operations: %f \n\n',gettime-t00);
2603
2604                 % Wait for next update time or stop request
2605                 while (gettime-t00) < LoopDelay
2606                     %disp('interval could be shorter')
2607                     pause(.05);
2608                     % Check if GUI has been closed
2609                     if isempty(gcbf)
2610                         FEEDBACK_STOP_FLAG = 1;
2611                         lasterr('SRCONTROL GUI DISAPPEARED!');
2612                         error('SRCONTROL GUI DISAPPEARED!');
2613                     end
2614
2615                     % Check if Stop button was pressed
2616                     if FEEDBACK_STOP_FLAG == 1
2617                         % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2618                         if getpv('SR01____FFBON__BC00')==1
2619                             disp('   Stopping Fast Orbit Feedback.');
2620                         end
2621                         setpv('SR01____FFBON__BC00',0);
2622                         pause(0.5);
2623                         setpv('SR01____FFBON__BC00',2);
2624                         break;
2625                     end
2626                 end
2627
2628
2629                 if FEEDBACK_STOP_FLAG == 1
2630                     % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2631                     if getpv('SR01____FFBON__BC00')==1
2632                         disp('   Stopping Fast Orbit Feedback.');
2633                     end
2634                     setpv('SR01____FFBON__BC00',0);
2635                     pause(0.5);
2636                     setpv('SR01____FFBON__BC00',2);
2637                     break;
2638                 end
2639
2640                 StartErrorTime = gettime;
2641
2642             catch
2643
2644                 fprintf('\n  %s \n',lasterr);
2645
2646                 % Quit if error exists for more than 20 seconds
2647                 if gettime-StartErrorTime>20 | FEEDBACK_STOP_FLAG==1
2648                     fprintf('%s  Orbit feedback stopped due to error condition. \n\n',datestr(now));
2649
2650                     %send alphapage to operator pager
2651                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2652                     FEEDBACK_STOP_FLAG = 1;
2653
2654                     setpv('SR_STATE', -5);
2655                     [StateNumber, StateString] = getsrstate;
2656                     if StateNumber >= 0
2657                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2658                     else
2659                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2660                     end
2661                 else
2662                     a = clock;
2663                     fprintf('   Orbit feedback was paused due to error condition (%s %d:%d:%.0f). \n', date, a(4), a(5), a(6));
2664                     fprintf('   Orbit feedback has automatically restarted and is running. \n\n');
2665                 end
2666
2667             end
2668
2669             if FEEDBACK_STOP_FLAG == 1
2670                 % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2671                 if getpv('SR01____FFBON__BC00')==1
2672                     disp('   Stopping Fast Orbit Feedback.');
2673                 end
2674                 setpv('SR01____FFBON__BC00',0);
2675                 pause(0.5);
2676                 setpv('SR01____FFBON__BC00',2);
2677                 break;
2678             end
2679
2680             %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2681
2682             %pause(0);
2683
2684             % this loop delays turn on of Fast Feedback system
2685             if FBloopIter < 5
2686                 FBloopIter = FBloopIter + 1;
2687             end
2688
2689         end  % End of feedback loop
2690
2691
2692         % End feedback, reset all parameters
2693         try
2694
2695             % Enable buttons
2696             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','on');
2697             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','off');
2698             set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','on');
2699             set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','on');
2700             set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','on');
2701             set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','on');
2702             set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','on');
2703             set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','on');
2704             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','on');
2705             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','on');
2706             set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','on');
2707             set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','on');
2708             set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','on');
2709
2710             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = _____ mm'),'ForegroundColor',[0 0 0]);
2711             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = _____ mm'),'ForegroundColor',[0 0 0]);
2712             pause(0);
2713
2714         catch
2715
2716             % GUI must have been closed
2717
2718         end
2719
2720
2721         % >= 2 Hz update rate on IDBPMs
2722         disp('   IDBPM time constant set to 0.25s.');
2723         setbpmtimeconstant(0.25);
2724
2725
2726         a = clock;
2727         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2728         [StateNumber, StateString] = getsrstate;
2729         if StateNumber >= 0
2730             setpv('SR_STATE',5.1);
2731             [StateNumber, StateString] = getsrstate;
2732             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2733             fprintf('   ******************************\n');
2734             fprintf('   **  Orbit Feedback Stopped  **\n');
2735             fprintf('   ******************************\n\n');
2736         else
2737             [StateNumber, StateString] = getsrstate;
2738             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2739             fprintf('   ****************************************\n');
2740             fprintf('   **  Problem With Slow Orbit Feedback  **\n');
2741             fprintf('   ****************************************\n\n');
2742         end
2743         set(0,'showhiddenhandles','off');
2744         pause(0);
2745
2746
2747     case 'FeedbackSetup'
2748         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
2749
2750         if InitFlag
2751             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2752             % Edit the following lists to change default configuration of Orbit Correction %
2753             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2754
2755             % Corrector magnets
2756             listh=[
2757                 1 2;
2758                 1 8;
2759                 2 1;
2760                 2 8;
2761                 3 1;
2762                 3 8;
2763                 3 10; %SR04U_HCM2 (chicane trim)
2764                 4 1;
2765                 4 8;
2766                 5 1;
2767                 5 8;
2768                % 5 10; %SR06U_HCM2 (chicane trim)
2769                 6 1;
2770                 6 8;
2771                 7 1;
2772                 7 8;
2773                 8 1;
2774                 8 8;
2775                 9 1;
2776                 9 8;
2777                 10 1;
2778                 10 8;
2779                 10 10; %SR11U_HCM2 (chicane trim)
2780                 11 1;
2781                 11 8;
2782                 12 1;
2783                 12 7];
2784             listv=[
2785                 1 2;
2786                 1 8;
2787                 2 1;
2788                 2 8;
2789                 3 1;
2790                 3 7;
2791                 3 8;
2792                 3 10; %SR04U_VHCM2 (chicane trim)
2793                 4 1;
2794                 4 7;
2795                 4 8;
2796                 5 1;
2797                 5 8;
2798                % 5 10; %SR06U_VHCM2 (chicane trim)
2799                 6 1;
2800                 6 8;
2801                 7 1;
2802                 7 8;
2803                 8 1;
2804                 8 8;
2805                 9 1;
2806                 9 8;
2807                 10 1;
2808                 10 2;
2809                 10 7;
2810                 10 8;
2811                 10 10; %SR11U_VHCM2 (chicane trim)
2812                 11 1;
2813                 11 7;
2814                 11 8;
2815                 12 1;
2816                 12 7];
2817
2818             Xivec = [1:27];
2819             Yivec = [1:31];
2820             HCMlist1 = listh;
2821             VCMlist1 = listv;
2822
2823             % Full BPM list
2824             BPMlist1 = [
2825                 1 2
2826                 1 5
2827                 1 6
2828                 1 10
2829                 2 1
2830                 2 5
2831                 2 6
2832                 2 9
2833                 3 2
2834                 3 5
2835                 3 6
2836                 3 10
2837                 3 11
2838                 3 12
2839                 4 1
2840                 4 5
2841                 4 6
2842                 4 10
2843                 5 1
2844                 5 5
2845                 5 6
2846                 5 10
2847 %                5 11
2848 %                5 12
2849                 6 1
2850                 6 5
2851                 6 6
2852                 6 10
2853                 7 1
2854                 7 5
2855                 7 6
2856                 7 10
2857                 8 1
2858                 8 5
2859                 8 6
2860                 8 10
2861                 9 1
2862                 9 5
2863                 9 6
2864                 9 10
2865                 10 1
2866                 10 5
2867                 10 6
2868                 10 10
2869                 10 11
2870                 10 12
2871                 11 1
2872                 11 5
2873                 11 6
2874                 11 10
2875                 12 1
2876                 12 5
2877                 12 6
2878                 12 9
2879                 ];
2880
2881             % remove Bergoz BPMs in SR01 and SR03 for 2-bunch (noisy at low currents) and drop singular values
2882             if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
2883                     BPMlist1 = [
2884                          %1 2
2885                          1 5
2886                          1 6
2887                          1 10
2888                          2 1
2889                          2 5
2890                          2 6
2891                          %2 9
2892                          %3 2
2893                          3 5
2894                          3 6
2895                          3 10
2896                          3 11
2897                          3 12
2898                          4 1
2899                          4 5
2900                          4 6
2901                          4 10
2902                          5 1
2903                          5 5
2904                          5 6
2905                          5 10
2906                          5 11
2907                          5 12
2908                          6 1
2909                          6 5
2910                          6 6
2911                          6 10
2912                          7 1
2913                          7 5
2914                          7 6
2915                          7 10
2916                          8 1
2917                          8 5
2918                          8 6
2919                          8 10
2920                          9 1
2921                          9 5
2922                          9 6
2923                          9 10
2924                          10 1
2925                          10 5
2926                          10 6
2927                          10 10
2928                          10 11
2929                          10 12
2930                          11 1
2931                          11 5
2932                          11 6
2933                          11 10
2934                          12 1
2935                          12 5
2936                          12 6
2937                          %12 9
2938                          ];
2939             end
2940
2941             OCSx.BPM = getx(BPMlist1, 'struct');
2942             OCSx.CM = getsp('HCM', HCMlist1, 'struct');
2943             OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
2944             OCSx.NIter = 1;
2945             OCSx.SVDIndex = Xivec;
2946             OCSx.IncrementalFlag = 'No';
2947             OCSx.BPMWeight = {[]};
2948             OCSx.FitRF = 0;
2949             OCSy.BPM = gety(BPMlist1, 'struct');
2950             OCSy.CM = getsp('VCM', VCMlist1, 'struct');
2951             OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
2952             OCSy.NIter = 1;
2953             OCSy.SVDIndex = Yivec;
2954             OCSy.IncrementalFlag = 'No';
2955             OCSy.BPMWeight = {[]};
2956             OCSy.FitRF = 0;
2957             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2958             % do we need these Smat calls? %
2959             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2960             SXmat = getrespmat(OCSx.BPM, OCSx.CM, 'numeric');
2961             SYmat = getrespmat(OCSy.BPM, OCSy.CM, 'numeric');
2962             % [OCSx, Sx, Ux, Vx] = orbitcorrectionmethods(OCSx, SXmat);
2963             % [OCSy, Sy, Uy, Vy] = orbitcorrectionmethods(OCSy, SYmat);
2964
2965             % initialize FFTypeFlag
2966             FFTypeFlag = 'Global';
2967
2968         else
2969
2970             % Get vectors
2971             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
2972             % the two lines below seem to fix BPMlist editing problem
2973             OCSx = FB.OCSx;
2974             OCSy = FB.OCSy;
2975             BPMlist1 = FB.BPMlist1;
2976             HCMlist1 = FB.HCMlist1;
2977             VCMlist1 = FB.VCMlist1;
2978             Xivec = FB.Xivec;
2979             Yivec = FB.Yivec;
2980             Xgoal = FB.OCSx.GoalOrbit;
2981             OCSx.GoalOrbit = Xgoal;
2982             Ygoal = FB.OCSy.GoalOrbit;
2983             OCSy.GoalOrbit = Ygoal;
2984             FFTypeFlag = FB.FFTypeFlag;
2985
2986
2987             % FF corrector magnet list
2988             ListFF = [
2989                 4     2
2990                 4     8
2991                 5     1
2992                 5     7
2993 %               5     8 % why are these out???
2994 %               6     1 % why are these out???
2995                 6     8
2996                 7     1
2997                 7     8
2998                 8     1
2999                 8     8
3000                 9     1
3001                 9     8
3002                 10    1
3003                 11    8
3004                 12    1];
3005             ElemFF = dev2elem('HCM',ListFF);
3006
3007
3008             % Add button to change #ivectors, cm, IDBPMs,
3009             EditFlag = 0;
3010             h_fig1 = figure;
3011             while EditFlag ~= 7
3012
3013                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
3014                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
3015
3016                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
3017                     DispOrbit = getdisp('BPMx', BPMlist1);
3018                     Sx = [Sx DispOrbit];
3019                 end
3020
3021                 [Ux, SVx, Vx] = svd(Sx);
3022                 [Uy, SVy, Vy] = svd(Sy);
3023
3024
3025                 % Remove singular values greater than the actual number of singular values
3026                 i = find(Xivec>length(diag(SVx)));
3027                 if ~isempty(i)
3028                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
3029                     pause(0);
3030                     Xivec(i) = [];
3031                 end
3032                 i = find(Yivec>length(diag(SVy)));
3033                 if ~isempty(i)
3034                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
3035                     pause(0);
3036                     Yivec(i) = [];
3037                 end
3038
3039
3040                 Ax = Sx*Vx(:,Xivec);
3041                 Tx = inv(Ax'*Ax)*Ax';
3042
3043                 Ay = Sy*Vy(:,Yivec);
3044                 Ty = inv(Ay'*Ay)*Ay';
3045
3046                 figure(h_fig1);
3047                 subplot(2,1,1);
3048                 semilogy(diag(SVx),'b');
3049                 hold on;
3050                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
3051                 ylabel('Horizontal');
3052                 title('Response Matrix Singular Values');
3053                 hold off;
3054                 subplot(2,1,2);
3055                 semilogy(diag(SVy),'b');
3056                 hold on;
3057                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
3058                 xlabel('Singular Value Number');
3059                 ylabel('Vertical');
3060                 hold off;
3061                 drawnow;
3062
3063                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List', ...
3064                     'BPM List','Change the Goal Orbit', ...
3065                     'Change Tune FF Method (nuy=9.2 only)','Continue');
3066
3067                 if EditFlag == 1
3068                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
3069                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
3070                     titlestr='SVD Orbit Feedback';
3071                     lineNo=1;
3072                     answer=inputdlg(prompt,titlestr,lineNo,def);
3073                     if ~isempty(answer)
3074                         XivecNew = fix(str2num(answer{1}));
3075                         if isempty(XivecNew)
3076                             disp('   Horizontal E-vector cannot be empty.  No change made.');
3077                         else
3078                             if any(XivecNew<=0) | max(XivecNew)>length(diag(SVx))
3079                                 disp('   Error reading horizontal E-vector.  No change made.');
3080                             else
3081                                 Xivec = XivecNew;
3082                             end
3083                         end
3084                         YivecNew = fix(str2num(answer{2}));
3085                         if isempty(YivecNew)
3086                             disp('   Vertical E-vector cannot be empty.  No change made.');
3087                         else
3088                             if any(YivecNew<=0) | max(YivecNew)>length(diag(SVy))
3089                                 disp('   Error reading vertical E-vector.  No change made.');
3090                             else
3091                                 Yivec = YivecNew;
3092                             end
3093                         end
3094                     end
3095                 end
3096
3097                 if EditFlag == 2
3098                     List= getlist('HCM','Trim');
3099                     CheckList = zeros(96,1);
3100                     Elem = dev2elem('HCM', HCMlist1);
3101                     CheckList(Elem) = ones(size(Elem));
3102                     CheckList = CheckList(dev2elem('HCM',List));
3103
3104                     % Remove FF corrrectors
3105                     %           Elem = dev2elem('HCM',List);
3106                     %           for j = length(ElemFF):-1:1
3107                     %              i = find(Elem==ElemFF(j));
3108                     %              Elem(i,:) = [];
3109                     %              List(i,:) = [];
3110                     %              CheckList(i,:) = [];
3111                     %           end
3112
3113                     newList = editlist(List, 'HCMtrim', CheckList);
3114
3115                     if isempty(newList)
3116                         fprintf('   WARNING: Horizontal corrector magnet list is empty!\n');
3117                         HCMlist1 = newList;
3118                     else
3119                         HCMlist1 = newList;
3120                     end
3121                 end
3122
3123                 if EditFlag == 3
3124                     List = getlist('VCM','Trim');
3125                     CheckList = zeros(96,1);
3126                     Elem = dev2elem('VCM', VCMlist1);
3127                     CheckList(Elem) = ones(size(Elem));
3128                     CheckList = CheckList(dev2elem('VCM',List));
3129
3130                     % Remove FF corrrectors
3131                     %           Elem = dev2elem('VCM',List);
3132                     %           for j = length(ElemFF):-1:1
3133                     %              i = find(Elem==ElemFF(j));
3134                     %              Elem(i,:) = [];
3135                     %              List(i,:) = [];
3136                     %              CheckList(i,:) = [];
3137                     %           end
3138
3139                     newList = editlist(List, 'VCMtrim', CheckList);
3140
3141                     if isempty(newList)
3142                         fprintf('   WARNING: Vertical corrector magnet list is empty!\n');
3143                         VCMlist1 = newList;
3144                     else
3145                         VCMlist1 = newList;
3146                     end
3147                 end
3148
3149                 if EditFlag == 4
3150                     ListOld = BPMlist1;
3151                     XgoalOld = Xgoal;
3152                     YgoalOld = Ygoal;
3153
3154                     % Full BPM list
3155                     List = [
3156                         1 2
3157                         1 5
3158                         1 6
3159                         1 10
3160                         2 1
3161                         2 5
3162                         2 6
3163                         2 9
3164                         3 2
3165                         3 5
3166                         3 6
3167                         3 10
3168                         3 11
3169                         3 12
3170                         4 1
3171                         4 5
3172                         4 6
3173                         4 10
3174                         5 1
3175                         5 5
3176                         5 6
3177                         5 10
3178                         5 11
3179                         5 12
3180                         6 1
3181                         6 5
3182                         6 6
3183                         6 10
3184                         7 1
3185                         7 5
3186                         7 6
3187                         7 10
3188                         8 1
3189                         8 5
3190                         8 6
3191                         8 10
3192                         9 1
3193                         9 5
3194                         9 6
3195                         9 10
3196                         10 1
3197                         10 5
3198                         10 6
3199                         10 10
3200                         10 11
3201                         10 12
3202                         11 1
3203                         11 5
3204                         11 6
3205                         11 10
3206                         12 1
3207                         12 5
3208                         12 6
3209                         12 9
3210                         ];
3211
3212
3213                     CheckList = zeros(size(List,1),1);
3214                     if ~isempty(BPMlist1)
3215                         for i = 1:size(List,1)
3216                             k = find(List(i,1)==BPMlist1(:,1));
3217                             l = find(List(i,2)==BPMlist1(k,2));
3218
3219                             if isempty(k) | isempty(l)
3220                                 % Item not in list
3221                             else
3222                                 CheckList(i) = 1;
3223                             end
3224                         end
3225                     end
3226
3227                     newList = editlist(List, 'BPM', CheckList);
3228                     if isempty(newList)
3229                         fprintf('   BPM list cannot be empty.  No change made.\n');
3230                     else
3231                         BPMlist1 = newList;
3232                     end
3233
3234                     % Set the goal orbit to the golden orbit
3235                     Xgoal = getgolden('BPMx', BPMlist1);
3236                     Ygoal = getgolden('BPMy', BPMlist1);
3237
3238
3239                     % If a new BPM is added, then set the goal orbit to the golden orbit
3240                     for i = 1:size(BPMlist1,1)
3241
3242                         % Is it a new BPM?
3243                         k = find(BPMlist1(i,1)==ListOld(:,1));
3244                         l = find(BPMlist1(i,2)==ListOld(k,2));
3245
3246                         if isempty(k) | isempty(l)
3247                             % New BPM
3248                         else
3249                             % Use the old value for old BPM
3250                             Xgoal(i) = XgoalOld(k(l));
3251                             Ygoal(i) = YgoalOld(k(l));
3252                         end
3253                     end
3254                     OCSx.BPM.DeviceList = BPMlist1;
3255                     OCSy.BPM.DeviceList = BPMlist1;
3256                     OCSx.GoalOrbit = Xgoal;
3257                     OCSy.GoalOrbit = Ygoal;
3258                 end
3259
3260                 if EditFlag == 5
3261                     ChangeList = editlist2(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
3262
3263                     for i = 1:size(ChangeList,1)
3264
3265                         k = find(ChangeList(i,1)==BPMlist1(:,1));
3266                         l = find(ChangeList(i,2)==BPMlist1(k,2));
3267
3268                         prompt={sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
3269                         def={sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
3270                         titlestr='CHANGE THE GOAL ORBIT';
3271                         lineNo=1;
3272                         answer = inputdlg(prompt, titlestr, lineNo, def);
3273
3274                         if isempty(answer)
3275                             % No change
3276                             fprintf('   No change was made to the golden orbit.\n');
3277                         else
3278                             Xgoalnew = str2num(answer{1});
3279                             if isempty(Xgoalnew)
3280                                 fprintf('   No change was made to the horizontal golden orbit.\n');
3281                             else
3282                                 Xgoal(k(l)) = Xgoalnew;
3283                             end
3284
3285                             Ygoalnew = str2num(answer{2});
3286                             if isempty(Ygoalnew)
3287                                 fprintf('   No change was made to the vertical golden orbit.\n');
3288                             else
3289                                 Ygoal(k(l)) = Ygoalnew;
3290                             end
3291                         end
3292                     end
3293                     if ~isempty(ChangeList)
3294                         fprintf('   Note:  Changing the goal orbit for "Slow Orbit Feedback" does not change the goal orbit for "Orbit Correction."\n');
3295                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
3296                     end
3297                     OCSx.GoalOrbit = Xgoal;
3298                     OCSy.GoalOrbit = Ygoal;
3299                 end
3300
3301                 if EditFlag == 6
3302                     FFTypeFlag = questdlg(sprintf('Do you want to use a fully local or a combined local/global compensation of IDs? (nuy=9.2 only)'),'Tune FF','Local','Global', 'Global');
3303                     if strcmp(FFTypeFlag,'Local')
3304                         disp(['   The tune FF will use 8 local quadrupoles to compensate beta beating and tune shift']);
3305                         disp(['   from each ID.']);
3306                     elseif strcmp(FFTypeFlag,'Global')
3307                         disp(['   The tune FF will use 4 local quadrupoles to compensate beta beating and all QF+QD']);
3308                         disp(['   to compensate tune shift from each ID.']);
3309                     end
3310
3311                 end
3312
3313             end
3314             close(h_fig1);
3315         end
3316
3317         % Save vectors
3318         FB.Xivec = Xivec;
3319         FB.Yivec = Yivec;
3320         FB.HCMlist1 = HCMlist1;
3321         FB.VCMlist1 = VCMlist1;
3322         FB.BPMlist1 = BPMlist1;
3323
3324         OCSx.SVDIndex = Xivec;
3325         OCSy.SVDIndex = Yivec;
3326         FB.OCSx = OCSx;
3327         FB.OCSy = OCSy;
3328
3329         FB.FFTypeFlag = FFTypeFlag;
3330         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata',FB);
3331
3332
3333     case 'FastFeedbackSetup'
3334
3335         InitFlag = Input2;
3336
3337         if InitFlag
3338             FOFBFreq = 1000;
3339             % user operations 9/14-10/17/04: P=0.5, I=120, D=0.0015 (for both planes)
3340             % below are known good values for user ops as of 8-1-05
3341             HorP = 2;
3342             HorI = 300;
3343             HorD = 0.002;
3344             VertP = 1;
3345             VertI = 100;
3346             VertD = 0.0015;
3347
3348             % this initial set is now done in hwinit.m because it's not a good idea to set anything when srcontrol is launched
3349             % try
3350             %     setsp('SR01____FFBFREQAC00', FOFBFreq); % set freq
3351             %     write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3352             % catch
3353             %     disp('   Trouble setting Fast Orbit Feedback parameters!');
3354             % end
3355
3356         else
3357             % Get vectors
3358             FOFB = get(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata');
3359             FOFBFreq = FOFB.FOFBFreq;
3360             HorP  = FOFB.HorP;
3361             HorI  = FOFB.HorI;
3362             HorD  = FOFB.HorD;
3363             VertP = FOFB.VertP;
3364             VertI = FOFB.VertI;
3365             VertD = FOFB.VertD;
3366
3367             % Add button to change #ivectors, CMs, IDBPMs,
3368             EditFlag = 0;
3369             %h_fig1 = figure;
3370             while EditFlag ~= 3
3371
3372                 %EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'HCM List', 'VCM List', ...
3373                 %   'IDBPM List', 'BBPM List', 'Continue');
3374                 % Use menu below until other FFB config routines work (then also uncomment options 3,4,5,6 below)
3375                 EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'Continue');
3376
3377                 if EditFlag == 1
3378                     % change rate
3379
3380                     prompt={'Enter the desired Fast Feedback Frequency (1-1000 Hz)'};
3381                     def={num2str(FOFBFreq)};
3382                     titlestr='Fast Feedback Setup';
3383                     lineNo=1;
3384                     answer=inputdlg(prompt,titlestr,lineNo,def);
3385                     if ~isempty(answer)
3386                         FOFBFreq = fix(str2num(answer{1}));
3387                         if isempty(FOFBFreq)
3388                             disp('   Frequency value cannot be empty.  No change made.');
3389                             FOFBFreq = getsp('SR01____FFBFREQAC00');
3390                         else
3391                             if FOFBFreq < 1 | FOFBFreq > 1000
3392                                 disp('   Frequency must be between 1 and 1000 Hz.  No change made.');
3393                                 FOFBFreq = getsp('SR01____FFBFREQAC00');
3394                             end
3395                         end
3396                         setsp('SR01____FFBFREQAC00',FOFBFreq); % change freq
3397                         pause(0.5);
3398                         fprintf('   Fast orbit feedback frequency is running at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
3399                     else
3400                         FOFBFreq = getsp('SR01____FFBFREQAC00');
3401                     end
3402                 end
3403
3404                 if EditFlag == 2
3405                     % edit  PIDs
3406                     % User defaults are HorP=2, HorI=300, HorD=0.002, VertP=1, VertI=100, VertD=0.0015
3407                     prompt={'P horizontal', 'I horizontal', 'D horizontal', 'P vertical', 'I vertical', 'D vertical'};
3408                     def={num2str(HorP), num2str(HorI), num2str(HorD), num2str(VertP), num2str(VertI), num2str(VertD)};
3409                     titlestr='Fast Feedback PID Setup';
3410                     lineNo=1;
3411                     answer=inputdlg(prompt,titlestr,lineNo,def);
3412                     if ~isempty(answer)
3413                         HorPnewnum = str2num(answer{1});
3414                         if isempty(HorPnewnum)
3415                             disp('   HorP value cannot be empty.  No change made.');
3416                         else
3417                             HorP = HorPnewnum;
3418                         end
3419                         HorInewnum = str2num(answer{2});
3420                         if isempty(HorInewnum)
3421                             disp('   HorI value cannot be empty.  No change made.');
3422                         else
3423                             HorI = HorInewnum;
3424                         end
3425                         HorDnewnum = str2num(answer{3});
3426                         if isempty(HorDnewnum)
3427                             disp('   HorD value cannot be empty.  No change made.');
3428                         else
3429                             HorD = HorDnewnum;
3430                         end
3431                         VertPnewnum = str2num(answer{4});
3432                         if isempty(VertPnewnum)
3433                             disp('   VertP value cannot be empty.  No change made.');
3434                         else
3435                             VertP = VertPnewnum;
3436                         end
3437                         VertInewnum = str2num(answer{5});
3438                         if isempty(VertInewnum)
3439                             disp('   VertI value cannot be empty.  No change made.');
3440                         else
3441                             VertI = VertInewnum;
3442                         end
3443                         VertDnewnum = str2num(answer{6});
3444                         if isempty(VertDnewnum)
3445                             disp('   VertD value cannot be empty.  No change made.');
3446                         else
3447                             VertD = VertDnewnum;
3448                         end
3449
3450                         try
3451                             write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3452                             fprintf('   Setting FFB gains to Horizontal P=%.2f, I=%.1f, D=%.4f;  Vertical P=%.2f, I=%.1f, D=%.4f\n', HorP, HorI, HorD, VertP, VertI, VertD);
3453                         catch
3454                             disp('   Trouble setting Fast Orbit Feedback parameters!');
3455                         end
3456                     end
3457                 end
3458
3459                 %if EditFlag == 3
3460                 %   disp('   This function not yet available.');
3461                 %   % change HCM List
3462                 %end
3463                 %
3464                 %if EditFlag == 4
3465                 %   disp('   This function not yet available.');
3466                 %   % change VCM List
3467                 %end
3468                 %
3469                 %if EditFlag == 5
3470                 %   disp('   This function not yet available.');
3471                 %   % change IDBPM List
3472                 %end
3473                 %
3474                 %if EditFlag == 6
3475                 %   disp('   This function not yet available.');
3476                 %   % change BBPM List
3477                 %end
3478
3479             end
3480             %close(h_fig1);
3481         end
3482
3483         % Save vectors
3484         FOFB.FOFBFreq = FOFBFreq;
3485         FOFB.HorP = HorP;
3486         FOFB.HorI = HorI;
3487         FOFB.HorD = HorD;
3488         FOFB.VertP = VertP;
3489         FOFB.VertI = VertI;
3490         FOFB.VertD = VertD;
3491         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata',FOFB);
3492
3493     otherwise
3494         fprintf('   No action for %s.\n', action);
3495 end   % end case