Description of srcontrol5_with_chicane_checks
Home > ALS > StorageRing > srcontrol5_with_chicane_checks.m
srcontrol5_with_chicane_checks
PURPOSE
srcontrol5
SYNOPSIS
function srcontrol5(action, Input2, Input3)
DESCRIPTION
 srcontrol5
 Storage ring control program
 This program controls all storage ring magnets, performs orbit feedback and
 tune feedforward and helps to diagnose problems in routine user operation
 of the ALS storage ring. It includes a gui to simplify the use of this
 program.
 It was originally programmed by Greg Portmann (until December 2000) with input
 from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
 and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
 The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
 Christoph Steier, July 2002
 SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
 Tom Scarvie, April 2005
CROSS-REFERENCE INFORMATION
This function calls:
amp2k AMP2K - Converts amperes to simulator values
bend2gev BEND2GEV - Compute the energy based on the ramp tables
checksrmags CHECKSRMAGS - Check SR power supplies against a lattice file
checksrorbit ErrorNums =checksrorbit(Sector, BPMxtolerance [.015 mm], [BPMytolerance [.015 mm]])
gap2tune GAP2TUNE - Computes the vertical tune shift for a insertion device gap change.
gaplimit [GapMin, GapMax] = gaplimit(ID_Number);
getbpmlist GETBPMLIST - Return a BPM list based on key words and sector numbers
getbpmtimeconstant GETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
getff function [FFEnableBM, FFEnableBC, GapEnableBM, GapEnableBC, Sector] = getff(Sector)
getid GETID - Get the insertion device position, velocity, run flag, and user requested gap
getsrstate [StateNumber, StateString] = getsrstate
ocsinit OCSINIT - Corrector and BPM
set_alarmhandler_AHU_thresholds_inject function set_alarmhandler_AHU_thresholds_inject
set_alarmhandler_thresholds set_alarmhandler_thresholds
set_alarmhandler_thresholds_new set_alarmhandler_thresholds_new
set_etaywave_nuy9_20skews_skewFF function [SQSFincr, SQSDincr] = set_etaywave_nuy9_20skews_skewFF(scale);
setbpmtimeconstant SETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
setbumps SETBUMPS - Make a straight section bump
setff function setff(Sector, FFEnableBC, GapEnableBC)
setid SETID - Set the insertion device vertical gap
setsrstatechannels
srcycle SRCYCLE - Storage ring cycle
srramp SRRAMP - Ramp the storage ring energy
write_goldenorbit_ffb function write_goldenorbit_ffb
write_goldenorbit_ffb_2planes WRITE_GOLDENORBIT_FFTB_2PLANES - Sets the BPM setpoints which are used by the fast feedback system
This function is called by:
SOURCE CODE
function srcontrol5(action, Input2, Input3)
% srcontrol5
% Storage ring control program
%
% This program controls all storage ring magnets, performs orbit feedback and
% tune feedforward and helps to diagnose problems in routine user operation
% of the ALS storage ring. It includes a gui to simplify the use of this
% program.
%
% It was originally programmed by Greg Portmann (until December 2000) with input
% from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
% and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
%
% The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
%
% Christoph Steier, July 2002
%
% SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
%
% Tom Scarvie, April 2005
% known bugs/problems (May 2001):
% - IDBPM averaging might be a bit too long for orbit feedback
%        solved after Superbend shutdown ... Instead of averaging, digital low pass filters are used
% - gap2tune does not give correct answers for wiggler and potentially other IDs -> orbit feedback
%        seems to be OK for other IDs, has been corrected for wiggler (fit to insertion device
%        compensation table)
% - chicanes do not work in orbit feedback
%        solved. One problem was that orbit response matrizes were mis-scaled by factor of two.
%        Second problem was different time constant of power supply control. Solved by moving controls
%        of center chicanes to cPCI (and magnets are fast, hysteresis free, aircore coils).
%        Center chicane in sector 4 is now routinely used in orbit feedback. Sector 11 to follow soon.
% - zero reading of ID gap dumps beam
%        solved in srcontrol5, still a problem in srcontrol5_hightune (but that routine has to be completely
%        rewritten because of all recent changes to srcontrol5, anyhow). For gap readings below the minimum
%        allowed gap for a device, the tune feedforward disables itself.
% - cycling of lattice causes frequent power supply failures
%        solved by changing the cycling procedure. 1.5 GeV operation is now on the upper hysteresis branch
%        as was the 1.9 GeV injection lattice before.
% - frequently stalled data in IDBPM readout
%        solved with new BPM readouts and digital filtering. Seems to have been a resolution problem
%        of the digital averaging algorithm.
% - magnet ramp tables are not in perfect agreement with magnetic measurements
%        Does not appear to be a serious problem. Superbends are slightly out of sync with other magnets,
%        but this does not cause any negative effects while ramping.
% - no good way to operate with injection at 1.5 GeV and storage energy below that
%        There now is a reasonable way to inject at 1.5 GeV and ramp down to lower storage energy. But
%        it has to be tested again after implementing new (and more) chicanes ...
% revision history
% 2001-05-10, Christoph Steier
% check whether readback from insertion device is significantly (more than 1 mm) below minimum
% gap, to avoid false zero readings of insertion device gaps to cause the tune feed forward
% to implement false huge correction (and dump the beam). If the insertion device gap readbacks
% gets more than 1 mm below the nominal minimum gap, the routine now assumes the insertion device
% to be open.
%
% 2001-08-30 and during Superbend commissioning, Christoph Steier, Tom Scarvie, Winni Decking
% various changes have been made to incorporate the Superbends and some other new equipment
% installed in the Superbend shutdown. This included some changes to programs being called by srcontrol
% (like srload, srsave, srcycle, srramp, ...). The main changes within srcontrol were in the orbit
% correction and slow orbit feedback routines (incorporating frequency feedback, ...)
%
% 2002-05-04, Christoph Steier
% added new IDBPMs, modified orbit feedback to use trim DACs, removed LSB toggling in vertical
% orbit feedback, ...
%
% 2002-07-29, T.Scarvie
% added check of CM trim currents to warn of problems that might rail the orbit feedback
%
% 2002-07-31, Christoph Steier
% increased the gain of the RF frequency feedback from 1/50 of the gain of the horizontal
% orbit feedback to 1/20. Reason was that the frequency feedback was reacting a bit too slow if all
% insertion device gaps are closed at once at high speed at the beginning of a fill.
%
% 2002-08-05, C.Steier, T.Scarvie
% Added conditional to reduce orbit feedback gain if running in two-bunch mode
%
% 2003-06-02, T.Scarvie
% Added loop inside orbit feedback to reset the SR11 chicane M1 and M2 motors every 20s to combat drift problem
%
% 2003-06-18, C. Steier
% Disabled loop to periodically reset chicane in SR11. Al Robb replaced power supply, seems to be no problem anymore.
%
% 2004-05-10, C. Steier
% The list of all BBPMs is now set up automatically be calling getlist('BBPMx'). This way, new BBPMs have to be added
% at fewer places in the software. It should now be sufficient to modify getlist and run the orbit response matrix
% rountine (getsmat) once to enable use of the new BBPMs.
%
% 2004-05-14, C. Steier
% Modified parameters for ramprate reduction (in srramp and here). Previous parameters were slightly too
% cautious. Increased initial slow ramprate to 0.4 A/s.
%
% 2004-05-14, C. Steier
% Incorporated insertion device compensation schemes for nu_y = 9.2 lattice.
%
% 2004-06-14, T.Scarvie
% Added controls for fast orbit feedback
%
% 2004-06-21, C. Steier
% Added tune feedforward (in the global tune compensation scheme for the nu_y=9.2 lattice) for the shift
% dependent tune shift of the EPUs, as well as a skew quadrupole feedforward for the EPU im sector 11
% (both only active in parallel mode so far).
%
% 2005-02-13, T.Scarvie
% Separated horizontal and vertical planes for setting Fast Feedback PIDs
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NOTES for conversion to new Middle Layer %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% We never use the gap and bump control flags - the radio buttons have been disabled -
%        should we try to keep the functionality?
%
% checksrmags
% checksrorbit(...)
% For the compiler
%#function goldenpage
%#function setoperationalmode
% Check if the AO exists
checkforao;
%%%%%%%%%%%%%%
% Initialize %
%%%%%%%%%%%%%%
global FEEDBACK_STOP_FLAG
SR_Mode = getfamilydata('OperationalMode');
SR_GEV = getfamilydata('Energy');
BSCramprate = getfamilydata('BSCRampRate');
if isnan(BSCramprate) | isempty(BSCramprate)
    BSCramprate = 0.4;
    setfamilydata(BSCramprate, 'BSCRampRate');
end
if nargin < 1
    action = 'Initialize';
end
if nargin < 2
    Input2 = 0;
end
if nargin < 3
    Input3 = 0;
end
if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
    FOFBcheckboxVal = 0;
else
    FOFBcheckboxVal = 1;
end
%%%%%%%%%%%%%%%%
% Main Program %
%%%%%%%%%%%%%%%%
switch(action)
    case 'StopOrbitFeedback'
        FEEDBACK_STOP_FLAG = 1;
    case 'Initialize'
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % GUI
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        ButtonWidth = 200;
        ButtonHeight  = 25;
        Offset1 = 8*25+12 + 47 + 25+25;
        Offset2 = 47+25+25;
        Offset3 = 45+25;
        Offset4 = 1;
        Offset5 = 30;
        FigWidth = ButtonWidth+6;
        FigHeight  = 3+9*(ButtonHeight+6)+24+Offset1;
        ButtonWidth = 200-6;
        % Change figure position
        set(0,'Units','pixels');
        p=get(0,'screensize');
        h0 = figure( ...
            'Color',[0.8 0.8 0.8], ...
            'HandleVisibility','Off', ...
            'Interruptible', 'on', ...
            'MenuBar','none', ...
            'Name','ALS SR CONTROL', ...
            'NumberTitle','off', ...
            'Units','pixels', ...
            'Position',[30 p(4)-FigHeight-40 FigWidth FigHeight+Offset5], ...
            'Resize','off', ...
            'Tag','SRCTRLFig1');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'FontWeight','Bold', ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+8*(ButtonHeight+3)+19+19+8+Offset1  ButtonWidth 20+Offset5], ...
            'Style','text', ...
            'String','', ...
            'Tag','SRCTRLTitle');
        % Frame Box I
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+3*(ButtonHeight+3)+Offset1-3+Offset5 ButtonWidth+6 7*ButtonHeight+18], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+9*(ButtonHeight+3)+Offset1  ButtonWidth 15+Offset5], ...
            'Style','text', ...
            'String','Lattice Setup Functions');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Cycle'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+8*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Cycle SR Lattice', ...
            'Tag','SRCTRLButton1');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Injection'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+7*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Injection', ...
            'Tag','SRCTRLButton2');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Production'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+6*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String',['Production'], ...
            'Tag','SRCTRLButton3');
        h1 = uicontrol('Parent',h0, ...
            'Callback',[...
            'fprintf(''\n'');' ...
            'disp([''   **********************************************'']);', ...
            'disp([''   **  Changing Storage Ring Operational Mode  **'']);', ...
            'disp([''   **********************************************'']);', ...
            'setoperationalmode;', ...
            'srcontrol5(''CheckInputs'');', ...
            'disp([''   ****************************'']);', ...
            'disp([''   **  Mode Change Complete  **'']);', ...
            'disp([''   ****************************'']);', ...
            'fprintf(''\n'');'], ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+5*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'Value',1, ...
            'String','Change Operational Mode', ...
            'Tag','SRCTRLButtonChangeMode');
        h1 = uicontrol(...
            'Parent',h0, ...
            'Callback', [...
            'srcontrol5(''CheckInputs'');',...
            'srcontrol5(''SRState'');'], ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+4*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Check For Problems', ...
            'Tag','SRCTRLButtonSRState');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs''); goldenpage;', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+3*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Golden Page', ...
            'Tag','SRCTRLButtonGoldenPage');
        % Frame Box II
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+9*(ButtonHeight+3)-29+Offset2+Offset5 ButtonWidth+6 2*ButtonHeight+15], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+10*(ButtonHeight+3)-10+Offset2 ButtonWidth .6*ButtonHeight+Offset5], ...
            'String','Global/Local Orbit Correction', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''OrbitCorrection'');', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+9*(ButtonHeight+3)-6+Offset2+Offset5 ButtonWidth ButtonHeight], ...
            'String','Correct Global Orbit w/ IDBPMs', ...
            'Tag','SRCTRLButtonOrbitCorrection');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''OrbitCorrectionSetup'',1);', ...
            'callback','srcontrol5(''OrbitCorrectionSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[6 9*(ButtonHeight+3)-22+Offset2+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Edit IDBPM, CM, & Local Bump Lists', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonOrbitCorrectionSetup');
        % Frame Box III
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 1*(ButtonHeight)+Offset3+Offset5-38 ButtonWidth+6 8*ButtonHeight+61], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+9*(ButtonHeight+3)+Offset3-25 ButtonWidth .55*ButtonHeight+Offset5], ...
            'String','Orbit Feedback', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+8*(ButtonHeight+3)+Offset3-18+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Slow Orbit Correction', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxSOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+7*(ButtonHeight+3)+Offset3-9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Fast Orbit Correction', ...
            'Style','checkbox', ...
            'Value',FOFBcheckboxVal,...
            'Tag','SRCTRLCheckboxFOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+6*(ButtonHeight+3)+Offset3+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct ID Tune Shift  ', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxTune');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+5*(ButtonHeight+3)+Offset3+9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct RF Frequency', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxRF');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''Feedback'');', ...
            'Enable','on', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[8 3+5*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Start FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStart');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''StopOrbitFeedback'');pause(0);', ...
            'Enable','off', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[.5*FigWidth+3 3+5*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Stop FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStop');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[14 4*(ButtonHeight)+Offset3+Offset5-3 ButtonWidth-14 .75*ButtonHeight], ...
            'String','Horizontal RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHorizontal');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[26 3+3.5*(ButtonHeight)+16+Offset3-25+Offset5 ButtonWidth-26 .75*ButtonHeight], ...
            'String','Vertical RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextVertical');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FeedbackSetup'',1);', ...
            'callback','srcontrol5(''FeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 3+3.5*(ButtonHeight)+.5+Offset3-25+Offset5 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit SOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFeedbackSetup');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','01 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB01');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','02 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB02');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','03 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB03');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','04 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB04');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','05 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB05');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','06 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB06');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','07 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB07');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','08 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB08');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','09 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB09');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','10 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB10');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','11 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB11');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','12 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB12');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FastFeedbackSetup'',1);', ...
            'callback','srcontrol5(''FastFeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 1*(ButtonHeight)+Offset3-3 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit FOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFastFeedbackSetup');
        % Frame Box IV
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+ButtonHeight+Offset4-14+Offset5 ButtonWidth+6 ButtonHeight+12], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+1.75*ButtonHeight+5+Offset4-21+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Storage Ring State', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHeader');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''CheckInputs'');', ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ForegroundColor','b', ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+ButtonHeight+6+3+2+Offset4-22+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','   ', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextInformation');
        % Frame Box "Close"
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 8 ButtonWidth+6 ButtonHeight+8], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'Callback','close(gcbf);', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 13 ButtonWidth ButtonHeight], ...
            'String','Close', ...
            'Tag','SRCTRLClose');
        % Update database channels
        setsrstatechannels;
        if nargout > 0
            fig = h0;
        end
    case 'Cycle'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        disp('   **************************');
        disp('   **  Storage Ring Cycle  **');
        disp('   **************************');
        a = clock; fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        BSCFlag = questdlg(sprintf('Cycle Superbend Magnets?'),'SR Cycle','Yes','No','No');
        %if strcmp(BSCFlag,'No')
        %    disp(['   ** Superbends will not be cycled. **']);
        %else
        %    disp(['   ** Superbends will be cycled during the second mini-cycle only. **']);
        %end
        ChicSQFlag = questdlg(sprintf('Cycle chicanes and skew quads and home motor chicanes?'),'SR Cycle','Yes','No','No');
        %if strcmp(ChicSQFlag,'No')
        %    disp(['   ** Chicanes and skew quads will not be cycled; motor chicanes will not be homed. **']);
        %else
        %    disp(['   ** Chicanes and skew quads will be cycled; motor chicanes will be homed. **']);
        %end
        StartFlag = questdlg(sprintf('Start %.1f GeV Cycle?',SR_GEV),'SR Cycle','Yes','No','No');
        if strcmp(StartFlag,'No')
            disp(['   ***************************']);
            disp(['   **    Cycle  Canceled    **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        end
        try
            if GapFlag
                % Make sure that the gaps are open with FF off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open.');
                    disp('   Opening all gaps at maximum speed.');
                    setff([], 1, 0);
                    disp('   Gap control disabled.');
                    disp('   Feed forward enabled.');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened.');
                    disp('   Feed forward and gap control disabled.');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled.');
                end
            else
                disp('   Feed forward and gap control disabled.');
            end
            setff([], 0, 0);
            pause(1);
            srcycle(BSCFlag, ChicSQFlag);
            setpv('SR_STATE',1);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Cycle failed due to error condition! \n\n');
            setpv('SR_STATE',-1);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp('   **********************************************');
            disp('   **  SR Cycle complete, ready for injection  **');
            disp('   **********************************************'); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp('   **********************************');
            disp('   **  Problem cycling SR lattice  **');
            disp('   **********************************'); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
    case 'Injection'
        AD = getad;
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            fprintf('   ***************************************************\n');
            fprintf('   **  Setup For %.2f GeV Injection (with ramping)  **\n', getfamilydata('InjectionEnergy'));
            fprintf('   ***************************************************\n');
            set_alarmhandler_AHU_thresholds_inject;
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',getfamilydata('InjectionEnergy')),'Injection Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            fprintf('   *************************************************\n');
            fprintf('   **  Setup For On Energy Injection at %.2f GeV  **\n', SR_GEV);
            fprintf('   *************************************************\n');
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',SR_GEV),'Injection Setup','Yes','Cancel','Cancel');
        end
        if strcmp(StartFlag,'Cancel')
            disp(['   ********************************']);
            disp(['   **  Injection Setup Canceled  **']);
            disp(['   ********************************']);
            set_alarmhandler_thresholds;
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                setff([],1,0);
                disp('   Gap control disabled');
                disp('   Feed forward enabled');
                pause(1);
                % Set IDs at max velocity w/ velocity profile off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    disp('   Opening all gaps');
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                end
                disp('   Gaps are open');
                disp('   Feed forward and gap control disabled');
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            if (AD.Energy-AD.InjectionEnergy) > 0.05
                % Ramp down to Injection Energy
                set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String','Ramping Down','ForegroundColor','b');
                drawnow;
                ErrorFlag = srramp('Injection');
                if ErrorFlag
                    error('Superbends over temperature.');
                end
                a = clock; fprintf('   %s %d:%d:%.0f\n\n',date, a(4), a(5), a(6));
            elseif (AD.Energy-AD.InjectionEnergy) < -0.05
                % first load injection lattice, then ramp to 1.9 GeV and back to 1.5 GeV to get onto same hysteresis branch
                srload('Injection');
                % load 1.9 GeV lattice
                tempfilename = sprintf('%s19nuy9prod.mat', getfamilydata('Directory','OpsData'));
                srload(tempfilename);
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                pause(5);
            end
            srload('Injection');
            setpv('SR_STATE',2);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Injection lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-2);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            if AD.Energy <= 1.5
                disp(['   *******************************************************************************']);
                disp(['   **  Function complete:  the storage ring is setup for injection at ',sprintf('%.2f',SR_GEV),' GeV  **']);
                disp(['   *******************************************************************************']);
                fprintf('\n');
            else
                fprintf('   **********************************************************************************************\n');
                fprintf('   **  Function complete:  the storage ring is setup for injection at %.2f GeV (upper branch)  **\n', getfamilydata('InjectionEnergy'));
                fprintf('   **********************************************************************************************\n');
                fprintf('\n');
            end
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   ************************************']);
            disp(['   **  Problem with injection setup  **']);
            disp(['   ************************************']);
            fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        %soundchord;
        setfamilydata(0.8, 'BSCRampRate');
    case 'Production'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        AD=getad;
        fprintf('\n');
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            disp('   ********************************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation (with ramping)  **',SR_GEV));
            disp('   ********************************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            disp('   *****************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation  **',SR_GEV));
            disp('   *****************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Yes','Cancel','Cancel');
        end
        if strcmp(StartFlag,'Cancel')
            disp(['   ***************************']);
            disp(['   **  User Setup Canceled  **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                % Make sure that the gaps are open
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open');
                    disp('   Opening all gaps at maximum speed');
                    setff([], 1, 0);
                    disp('   Gap control disabled');
                    disp('   Feed forward enabled');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened');
                    disp('   Feed forward and gap control disabled');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled');
                end
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            % Ramp up to the production lattice
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String','Ramping Up','ForegroundColor','b');
            drawnow;
            ErrorFlag = srramp('Production');
            if ErrorFlag
                error('Superbends over temperature.');
            end
            a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            srload('Production');
            if GapFlag
                setff([], 1, 0);
                disp('   Gap control disabled');
                disp('   Feed forward enable');
                pause(1);
                disp('   Insertion device velocity profile boolean control off');
                disp('   Closing all gaps at maximum speed');
                % Set IDs at max velocity w/ velocity profile off
                [Position, Velocity, RunFlag, UserGap] = getid;
                setid([], UserGap, maxsp('IDvel'), 1, 0, 1);
                % Turn velocity profile on
                disp('   Insertion device velocity profile boolean control is on');
                setid([], [], maxsp('IDvel'), 1, 1, 0);
                disp('   Gaps are closed');
                setff([4;7;8;9;10;12], 1, 1);
                setff(5, 1, 0);
                disp('   Gap control enabled (except sector 5 (W16))');
            end
            set_alarmhandler_thresholds_new;
            setpv('SR_STATE',3);
        catch
            fprintf('   %s \n', lasterr);
            fprintf('   User lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-3);
        end
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp(['   **************************************************************************']);
            disp(['   **  Function complete:  the storage ring is setup for users at ',sprintf('%.1f',SR_GEV),' GeV  **']);
            disp(['   **************************************************************************']); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   *************************************']);
            disp(['   **  Problem with production setup  **']);
            disp(['   *************************************']); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        setfamilydata(0.8, 'BSCRampRate');
%         % for BL6.0.x, set lower setpoint limit for IVID to 12.5mm until beamlines are surveyed below that value
%         try
%             scaput('SR06U___GDS1PS_AC00.DRVL',12.5);
%             disp('  Setting SR06U___GDS1PS_AC00.DRVL to 12.5mm (lower limit for IVID');
%         catch
%             disp('  Trouble setting lower limit for IVID to 12.5mm!');
%         end
    case 'CheckInputs'
        SR_GEV = getfamilydata('Energy');
        AD=getad;
        setsrstatechannels;
        set(0,'showhiddenhandles','on');
        if AD.Energy > 1.55
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Down)']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users (Ramp Up)']);
        elseif AD.Energy < 1.45
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Up+cycle)']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV (Ramp Down)']);
        else
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV']);
        end
        set(findobj('Tag','SRCTRLTitle'),'String',SR_Mode);
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
        else
            set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
        end
        set(0,'showhiddenhandles','off');
    case 'SRState'
        NumErrors = 0;
        fprintf('\n');
1000         disp('   ***********************************');
1001         disp('   **  Checking Storage Ring State  **');
1002         disp('   ***********************************');
1003         a = clock;
1004         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1005
1006         %       FileName = getpv('SR_LATTICE_FILE','String');   % Last srload file name (in OLD MIDDLE LAYER nomenclature!!)
1007
1008         GeVnow = bend2gev;
1009         if GeVnow == getfamilydata('Energy')
1010             [ConfigSetpoint, ConfigMonitor, FileName] = getproductionlattice;
1011         elseif GeVnow == getfamilydata('InjectionEnergy')
1012             [ConfigSetpoint, ConfigMonitor, FileName] = getinjectionlattice;
1013         else
1014             FileName = '';
1015         end
1016
1017         [StateNumber, StateString] = getsrstate;
1018         fprintf('   Storage ring operational mode: %s\n', SR_Mode);
1019         if StateNumber < 0
1020             fprintf('   Storage ring state error: %s\n', StateString);
1021             NumErrors = NumErrors + 1;
1022         else
1023             fprintf('   Storage ring state: %s\n', StateString);
1024         end
1025         if StateNumber==0
1026             % Storage ring state unknown
1027             NumErrors = NumErrors + 1;
1028         elseif abs(StateNumber)==1 || abs(StateNumber)==2
1029             FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','InjectionFile') '.mat'];
1030             if ~strcmp(FileName, FileNameGoal)
1031                 fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','InjectionFile'), FileName);
1032                 NumErrors = NumErrors + 1;
1033             end
1034         else
1035             FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile') '.mat'];
1036             if ~strcmp(FileName, FileNameGoal)
1037                 fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','LatticeFile'), FileName);
1038                 NumErrors = NumErrors + 1;
1039             end
1040         end
1041
1042
1043         % Check all SR magnets
1044         if isempty(FileName)
1045             fprintf('   Goal setpoints will not be checked since the last lattice load is unknown.\n');
1046             NumErrors1 = checksrmags('');
1047         else
1048 %            NumErrors1 = checksrmags([getfamilydata('Directory','OpsData') FileName]);
1049             NumErrors1 = checksrmags(FileName);
1050         end
1051         if NumErrors1 == 0
1052             fprintf('   SR magnets power supplies are OK.\n');
1053         end
1054         NumErrors = NumErrors + NumErrors1;
1055
1056
1057         % Check RF frequency
1058         if isempty(FileName)
1059             fprintf('   RF frequency will not be checked since the last lattice load is unknown.\n');
1060         else
1061 %            load([getfamilydata('Directory','OpsData'), FileName]);
1062             load(FileName);
1063             [tmp, RFHPCounterPresent] = getrf;
1064             if abs(RFHPCounterPresent-ConfigSetpoint.RF.Setpoint.Data) > .002
1065                 NumErrors = NumErrors + 1;
1066                 fprintf('   RF frequency should be %f, presently it is %f MHz (as measured by the HP counter).\n', ConfigSetpoint.RF.Setpoint.Data, RFHPCounterPresent);
1067             else
1068                 fprintf('   RF frequency is OK (HP counter is %f MHz, at the time of the lattice save it was %f MHz).\n', RFHPCounterPresent, ConfigSetpoint.RF.Setpoint.Data);
1069             end
1070         end
1071
1072
1073         % Check for orbit problems
1074         if (StateNumber >= 3) & (getdcct > 2)   % Production lattice is loaded with beam in the machine
1075             Xtol = 0.070;
1076             Ytol = 0.010;
1077             NumErrors1 = checksrorbit([],Xtol,Ytol);
1078             if NumErrors1
1079                 fprintf('   SR orbit in the ID straight sections or at Bergoz BPMs deviates more than allowed from the golden orbit.\n');
1080             else
1081                 fprintf('   SR orbit in the ID straight sections and at Bergoz BPMs is OK.\n');
1082                 fprintf('   The orbit is within %.3f mm horizontally and %.3f mm vertically', Xtol, Ytol);
1083             end
1084             NumErrors = NumErrors + NumErrors1;
1085         else
1086             fprintf('   Storage ring orbit was not checked.\n');
1087         end
1088
1089
1090         a = clock;
1091         datestr1=date;
1092         fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
1093         if NumErrors
1094             disp('   *********************************');
1095             disp('   **  Storage Ring Has Problems  **');
1096             disp('   *********************************');
1097         else
1098             disp('   **********************************');
1099             disp('   **  Storage Ring Lattice is OK  **');
1100             disp('   **********************************');
1101         end
1102         fprintf('   \n');
1103
1104         set(0,'showhiddenhandles','on');
1105         [StateNumber, StateString] = getsrstate;
1106         if StateNumber >= 0
1107             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1108         else
1109             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1110         end
1111         set(0,'showhiddenhandles','off');
1112
1113
1114     case 'OrbitCorrection'
1115         fprintf('\n');
1116         fprintf('   *********************************\n');
1117         fprintf('   **  Starting Orbit Correction  **\n');
1118         fprintf('   *********************************\n');
1119         a = clock;
1120         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1121
1122         StartFlag = questdlg(sprintf('Start orbit correction, %.1f GeV?',SR_GEV),'Orbit Correction','Yes','No','No');
1123         if strcmp(StartFlag,'No')
1124             disp(['   ********************************']);
1125             disp(['   **  Orbit Correction Aborted  **']);
1126             disp(['   ********************************']);
1127             fprintf('\n');
1128             return
1129         end
1130
1131         if getdcct < 5     % Don't correct the orbit if the current is too small
1132             fprintf('   Orbit not corrected due to small current.\n');
1133             return
1134         end
1135
1136         if abs(SR_GEV-bend2gev(getpv('BEND',[1 1])))>  0.05     % Don't use this routine for the injection lattice
1137             fprintf('   This routine should only be used for the production energy: Correction aborted\n');
1138             return
1139         end
1140
1141         SR_STATE_OLD = scaget('SR_STATE');
1142         set(0,'showhiddenhandles','on');
1143         setpv('SR_STATE',4);
1144         [StateNumber, StateString] = getsrstate;
1145         if StateNumber >= 0
1146             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1147         else
1148             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1149         end
1150         set(0,'showhiddenhandles','off');
1151
1152
1153         try
1154             % save current BPM timeconstant - will reset to this after correction
1155             BPMtimeconstantOC = getbpmtimeconstant;
1156             fprintf('   Current Bergoz BPM time constant is %.1fs\n', BPMtimeconstantOC);
1157
1158             % 2 Hz update rate on IDBPMs
1159             disp('   Bergoz BPM time constant set to 0.5s.')
1160             setbpmtimeconstant(0.5)
1161             pause(2);
1162
1163
1164             % Turn off feed forward
1165             fprintf('   Turning feed forward off.\n');
1166             [FFEnableBM, FFEnableBC] = getff;
1167             setff([], 0);
1168             scasleep(.2);
1169
1170
1171             % Get vectors
1172             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1173             LocalBumplist = FB.LocalBumplist;
1174
1175         catch
1176
1177             fprintf('   %s \n',lasterr);
1178             fprintf('   Orbit correction setup failed due to error condition! \n\n');
1179             setpv('SR_STATE',-4);
1180             set(0,'showhiddenhandles','on');
1181             [StateNumber, StateString] = getsrstate;
1182             if StateNumber >= 0
1183                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1184             else
1185                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1186             end
1187             set(0,'showhiddenhandles','off');
1188
1189             % Reset BPM timeconstant to whatever it was before correction
1190             setbpmtimeconstant(BPMtimeconstantOC);
1191             fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1192             return
1193         end
1194
1195         iNotHCMChicane = find(FB.HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
1196         iHCMChicane = find(FB.HCMlist1(:,2) == 10);
1197         iNotVCMChicane = find(FB.VCMlist1(:,2) < 10);
1198         iVCMChicane = find(FB.VCMlist1(:,2) == 10);
1199
1200         fprintf('   Starting horizontal and vertical global orbit correction (SVD method).\n');
1201
1202         for iloop = 1:3
1203             try
1204                 % use the following to get corrector settings in OCS without setting them, so the values can be checked
1205                 FB.OCSx = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
1206                 FB.OCSy = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
1207                 if any(abs(FB.OCSx.CM.Delta(iNotHCMChicane)) > 5)
1208                   disp('   Orbit Correction is changing some horizontal corrector(s) > 5A!!');
1209                 end
1210                 if any(abs(FB.OCSy.CM.Delta(iNotVCMChicane)) > 5)
1211                   disp('   Orbit Correction is changing some vertical corrector(s) > 5A!!');
1212                 end
1213                 if any(abs(FB.OCSx.CM.Delta(iHCMChicane)) > 10)
1214                   disp('   Orbit Correction is changing some horizontal chicane corrector(s) > 10A!!');
1215                 end
1216                 if any(abs(FB.OCSy.CM.Delta(iVCMChicane)) > 10)
1217                   disp('   Orbit Correction is changing some vertical chicane corrector(s) > 10A!!');
1218                 end
1219
1220
1221                 % Correct horizontal orbit
1222                 FB.OCSx = setorbit(FB.OCSx,'NoDisplay');
1223                 % Correct vertical orbit
1224                 FB.OCSy = setorbit(FB.OCSy,'NoDisplay');
1225
1226
1227                 % Check for current in machine - stop orbit correction if DCCT < 5mA
1228                 if (getdcct < 4.5)
1229                     error('**There is less than 5mA in the machine! Stopping orbit correction.');
1230                 end
1231
1232                 % Check state of gaps - stop orbit correction if any are moving
1233                 GAPrunflag = getpv('ID','RunFlag');
1234                 if any(GAPrunflag-round(GAPrunflag))
1235                     error('**One or more of the gaps are moving! Stopping orbit correction.');
1236                 end
1237
1238                 x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
1239                 y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
1240                 fprintf('   %d. Horizontal RMS = %.3f mm\n', iloop, norm(x)/sqrt(length(x)));
1241                 fprintf('   %d.   Vertical RMS = %.3f mm\n', iloop, norm(y)/sqrt(length(y)));
1242
1243             catch
1244                 % fprintf('   %s \n',lasterr);
1245                 fprintf('   Orbit correction failed due to error condition!\n  Fix the problem, reload the lattice (srload), and try again.  \n\n');
1246                 setpv('SR_STATE',-4);
1247                 set(0,'showhiddenhandles','on');
1248                 [StateNumber, StateString] = getsrstate;
1249                 if StateNumber >= 0
1250                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1251                 else
1252                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1253                 end
1254                 set(0,'showhiddenhandles','off');
1255
1256                 % Reset BPM timeconstant to whatever it was before correction
1257                 setbpmtimeconstant(BPMtimeconstantOC);
1258                 fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1259                 return
1260             end
1261         end
1262
1263
1264         % Set user bumps w/o sextupole correctors
1265         try
1266
1267             %turn up corrector speed here to quicken setting bumps
1268             HCMramprate = getpv('HCM', 'RampRate');
1269             VCMramprate = getpv('VCM', 'RampRate');
1270             setpv('HCM', 'RampRate', 10, [], 0);
1271             setpv('VCM', 'RampRate', 10, [], 0);
1272
1273             if ~isempty(LocalBumplist)
1274                 fprintf('   Setting local bumps in the straight sections.\n');
1275                 for loop = 1:size(LocalBumplist,1)
1276
1277                     % Check for current in machine - stop orbit correction if DCCT < 5mA
1278                     if (getdcct < 5)
1279                         error('** There is less than 5mA in the machine! Stopping local bumps.');
1280                     end
1281
1282                     % Check state of gaps - stop setting bumps if any are moving
1283                     GAPrunflag = getpv('ID','RunFlag');
1284                     if any(GAPrunflag-round(GAPrunflag))
1285                         error('** One or more of the gaps are moving! Stopping local bumps.');
1286                     end
1287
1288                     HCMoldsp = getsp('HCM', FB.HCMlist1);
1289                     VCMoldsp = getsp('VCM', FB.VCMlist1);
1290
1291                     if any(LocalBumplist(loop,1) == [4 6 11])
1292                         if LocalBumplist(loop,2) == 0
1293                             % Upstream bump
1294                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1295                             if isempty(iRemove)
1296                                 setbumps(LocalBumplist(loop,:), 1);
1297                             else
1298                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1299                             end
1300                         elseif LocalBumplist(loop,2) == 1
1301                             % Upstream bump
1302                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;],FB.OCSx.BPM.DeviceList);
1303                             if isempty(iRemove)
1304                                 setbumps(LocalBumplist(loop,:), 1);
1305                             else
1306                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1307                             end
1308                         else
1309                             % Downstream bump
1310                             [i, iRemove] = findrowindex([LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1311                             if isempty(iRemove)
1312                                 setbumps(LocalBumplist(loop,:), 1);
1313                             else
1314                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1315                             end
1316                         end
1317                     else
1318                         [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1319                         if isempty(iRemove)
1320                             setbumps(LocalBumplist(loop,:), 1);
1321                         else
1322                             fprintf('\n   BPMs missing from Sector %02d - skipping local bump for that sector.\n\n', LocalBumplist(loop,1));
1323                         end
1324                     end
1325
1326                     HCMnewsp = getsp('HCM', FB.HCMlist1);
1327                     VCMnewsp = getsp('VCM', FB.VCMlist1);
1328                     % Remove center chicane trim from corrector check
1329                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 5) | (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 10)
1330                         error('**Setbumps caused some corrector magnet currents to change by more than 5(Horiz)/10(Vert) A!');
1331                     end
1332                     % Now check center chicane trims
1333                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 10) | (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 15)
1334                         error('**Setbumps caused some chicane trim magnet currents to change by more than 10(Horiz)/15(Vert) A!');
1335                     end
1336                 end
1337             end
1338
1339             %restore corrector speeds
1340             setpv('HCM', 'RampRate', HCMramprate, [], 0);
1341             setpv('VCM', 'RampRate', VCMramprate, [], 0);
1342
1343         catch
1344             fprintf('   %s \n',lasterr);
1345             fprintf('   Setbumps failed due to error condition!  Fix the problem, reload the lattice (srload), and try again.\n\n');
1346             setpv('SR_STATE',-4);
1347             set(0,'showhiddenhandles','on');
1348             [StateNumber, StateString] = getsrstate;
1349             if StateNumber >= 0
1350                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1351             else
1352                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1353             end
1354             set(0,'showhiddenhandles','off');
1355
1356             % Reset BPM timeconstant to whatever it was before correction
1357             setbpmtimeconstant(BPMtimeconstantOC);
1358             fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1359             return
1360         end
1361
1362         % Reset BPM timeconstant to whatever it was before correction
1363         setbpmtimeconstant(BPMtimeconstantOC);
1364         fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1365
1366         % Turn feed forward back to it's original state
1367         if any(FFEnableBC)
1368             fprintf('   Turning feed forward back on.\n');
1369             setff([], FFEnableBC);
1370         end
1371
1372
1373         a = clock;
1374         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1375         [StateNumber, StateString] = getsrstate;
1376         set(0,'showhiddenhandles','on');
1377         if StateNumber >= 0
1378             setpv('SR_STATE',4.1);
1379             [StateNumber, StateString] = getsrstate;
1380             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1381             fprintf('   *********************************\n');
1382             fprintf('   **  Orbit Correction Complete  **\n');
1383             fprintf('   *********************************\n\n');
1384         else
1385             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1386             fprintf('   *************************************\n');
1387             fprintf('   **  Problem With Orbit Correction  **\n');
1388             fprintf('   *************************************\n\n');
1389         end
1390         set(0,'showhiddenhandles','off');
1391         pause(0);
1392
1393
1394     case 'OrbitCorrectionSetup'
1395         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
1396
1397         if InitFlag
1398             % Setup feedback elements
1399             % disp('Orbit correction condition: InitFlag=1 -- debugging message');
1400
1401             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1402             % Edit the following lists to change default configuration of Orbit Correction %
1403             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1404 %             hlist=[];vlist=[];
1405 %             for Sector =1:12
1406 %                 if Sector == 1
1407 %                     vlist = [vlist;Sector 2;Sector 4;Sector 5;Sector 8];
1408 %                     hlist = [hlist;Sector 2;Sector 7];
1409 %                 elseif Sector == 3
1410 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1411 %                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1412 %                 elseif Sector == 5
1413 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1414 %                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1415 % %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8]; %remove HCM and VCM(5,10) since corrector is not controlling starting 4-6-07
1416 % %                     hlist = [hlist;Sector 2;Sector 7];
1417 %                 elseif Sector == 10
1418 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1419 %                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1420 %                 elseif Sector == 12
1421 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 7];
1422 %                     hlist = [hlist;Sector 2;Sector 7];
1423 %                 else
1424 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8];
1425 %                     hlist = [hlist;Sector 2;Sector 7];
1426 %                 end
1427 %             end
1428 %             HCMlist1 = hlist;
1429 %             VCMlist1 = vlist;
1430 %
1431 %             BPMlist1 = [
1432 %                 1 2
1433 %                 1 5
1434 %                 1 6
1435 %                 1 10
1436 %                 2 1
1437 %                 2 5
1438 %                 2 6
1439 %                 2 9
1440 %                 3 2
1441 %                 3 5
1442 %                 3 6
1443 %                 3 10
1444 %                 3 11
1445 %                 3 12
1446 %                 4 1
1447 %                 4 5
1448 %                 4 6
1449 %                 4 10
1450 %                 5 1
1451 %                 5 5
1452 %                 5 6
1453 %                 5 10
1454 %                 5 11
1455 %                 5 12
1456 %                 6 1
1457 %                 6 5
1458 %                 6 6
1459 %                 6 10
1460 %                 7 1
1461 %                 7 5
1462 %                 7 6
1463 %                 7 10
1464 %                 8 1
1465 %                 8 5
1466 %                 8 6
1467 %                 8 10
1468 %                 9 1
1469 %                 9 5
1470 %                 9 6
1471 %                 9 10
1472 %                 10 1
1473 %                 10 5
1474 %                 10 6
1475 %                 10 10
1476 %                 10 11
1477 %                 10 12
1478 %                 11 1
1479 %                 11 5
1480 %                 11 6
1481 %                 11 10
1482 %                 12 1
1483 %                 12 5
1484 %                 12 6
1485 %                 12 9];
1486 %
1487 %             % SVD orbit correction
1488 %             Xivec = [1:28];
1489 %             Yivec = [1:51];
1490 %
1491 %
1492 %             % Look for bad status BPMs
1493 %             iStatus = family2status('BPMx', BPMlist1);
1494 %             iBad = find(~iStatus);
1495 %             BPMlist1 = BPMlist1(find(iStatus),:);
1496 %             if length(iBad)
1497 %                 fprintf('   Global Orbit Correction: %d BPMs removed for bad status\n', length(iBad));
1498 %                 Yivec = Yivec(1:end-length(iBad));
1499 %             end
1500 %
1501 %             iStatus = family2status('HCM', HCMlist1);
1502 %             iBad = find(~iStatus);
1503 %             HCMlist1 = HCMlist1(find(iStatus),:);
1504 %             if length(iBad)
1505 %                 fprintf('   Global Orbit Correction: %d HCMs removed for bad status\n', length(iBad));
1506 %             end
1507 %
1508 %             iStatus = family2status('VCM', VCMlist1);
1509 %             iBad = find(~iStatus);
1510 %             VCMlist1 = VCMlist1(find(iStatus),:);
1511 %             if length(iBad)
1512 %                 fprintf('   Global Orbit Correction: %d VCMs removed for bad status\n', length(iBad));
1513 %             end
1514
1515             % Initialize RFCorrFlag
1516             RFCorrFlag = 'Yes';
1517
1518             % Get the device lists from oscsinit and convert to srcontrol variables
1519             [HBPM, VBPM, HCM, VCM, HSV, VSV] = ocsinit('TopOfFill');
1520             if strcmpi(RFCorrFlag, 'Yes')
1521                 Xivec = 1:HSV+1;
1522             else
1523                 Xivec = 1:HSV;
1524             end
1525             Yivec = 1:VSV;
1526             BPMlist1 = HBPM.DeviceList;
1527             HCMlist1 = HCM.DeviceList;
1528             VCMlist1 = VCM.DeviceList;
1529
1530
1531             LocalBumplist = [
1532               % 1 1
1533               % 2 1
1534               % 3 1
1535                 4 1
1536               % 4 2
1537                 5 1
1538               % 6 1
1539               % 6 2
1540                 7 1
1541                 8 1
1542                 9 1
1543                 10 1
1544                 11 1
1545                 11 2
1546                 12 1
1547                 ];
1548             %LocalBumplist = []
1549
1550
1551         else
1552
1553             % Get vectors
1554             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1555             BPMlist1 = FB.BPMlist1;
1556             HCMlist1 = FB.HCMlist1;
1557             VCMlist1 = FB.VCMlist1;
1558             Xivec = FB.Xivec;
1559             Yivec = FB.Yivec;
1560             LocalBumplist = FB.LocalBumplist;
1561             Xgoal = FB.Xgoal;
1562             Ygoal = FB.Ygoal;
1563             RFCorrFlag = FB.RFCorrFlag;
1564
1565             % Add button to change #ivectors, CMs, IDBPMs,
1566             EditFlag = 0;
1567             h_fig1 = figure;
1568             while EditFlag ~= 8
1569
1570                 % Sensitivity matrix
1571                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
1572                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
1573
1574                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1575                 % Can the call below work for setting FOFB RF parameter? %
1576                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1577                 if strcmpi(RFCorrFlag, 'Yes')
1578                     Sx = [Sx getdisp('BPMx',BPMlist1)];
1579                 end
1580
1581                 Sx(isnan(Sx)) = 0;
1582                 Sy(isnan(Sy)) = 0;
1583
1584                 [Ux, SVx, Vx] = svd(Sx);
1585                 [Uy, SVy, Vy] = svd(Sy);
1586
1587
1588                 % Remove singular values greater than the actual number of singular values
1589                 i = find(Xivec>length(diag(SVx)));
1590                 if ~isempty(i)
1591                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
1592                     pause(0);
1593                     Xivec(i) = [];
1594                 end
1595                 i = find(Yivec>length(diag(SVy)));
1596                 if ~isempty(i)
1597                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
1598                     pause(0);
1599                     Yivec(i) = [];
1600                 end
1601
1602
1603                 Ax = Sx*Vx(:,Xivec);
1604                 Tx = inv(Ax'*Ax)*Ax';
1605
1606                 Ay = Sy*Vy(:,Yivec);
1607                 Ty = inv(Ay'*Ay)*Ay';
1608
1609
1610                 figure(h_fig1);
1611                 subplot(2,1,1);
1612                 semilogy(diag(SVx),'b');
1613                 hold on;
1614                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
1615                 ylabel('Horizontal');
1616                 title('Response Matrix Singular Values');
1617                 hold off;
1618                 subplot(2,1,2);
1619                 semilogy(diag(SVy),'b');
1620                 hold on;
1621                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
1622                 xlabel('Singular Value Number');
1623                 ylabel('Vertical');
1624                 hold off;
1625                 drawnow;
1626
1627                 if strcmp(RFCorrFlag,'No')
1628                     RFCorrState = 'NOT CORRECTED';
1629                 elseif strcmp(RFCorrFlag,'Yes')
1630                     RFCorrState = 'CORRECTED';
1631                 else
1632                     RFCorrState = '???';
1633                 end
1634
1635                 %         EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','HCM Chicane List','VCM Chicane List','IDBPM List','BBPM List','Change Golden Orbit',...
1636                 %            'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1637                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','BPM List','Change Golden Orbit',...
1638                     'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1639
1640                 if EditFlag == 1
1641                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
1642                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
1643                     titlestr='SVD Orbit Feedback';
1644                     lineNo=1;
1645                     answer=inputdlg(prompt,titlestr,lineNo,def);
1646                     if ~isempty(answer)
1647                         XivecNew = fix(str2num(answer{1}));
1648                         if isempty(XivecNew)
1649                             disp('   Horizontal E-vector cannot be empty.  No change made.');
1650                         else
1651                             if any(XivecNew<=0) | max(XivecNew)>length(diag(SVx))
1652                                 disp('   Error reading horizontal E-vector.  No change made.');
1653                             else
1654                                 Xivec = XivecNew;
1655                             end
1656                         end
1657                         YivecNew = fix(str2num(answer{2}));
1658                         if isempty(YivecNew)
1659                             disp('   Vertical E-vector cannot be empty.  No change made.');
1660                         else
1661                             if any(YivecNew<=0) | max(YivecNew)>length(diag(SVy))
1662                                 disp('   Error reading vertical E-vector.  No change made.');
1663                             else
1664                                 Yivec = YivecNew;
1665                             end
1666                         end
1667                     end
1668                 end
1669
1670                 if EditFlag == 2
1671                     List = getlist('HCM');
1672                     CheckList = zeros(size(List,1));
1673                     Elem = dev2elem('HCM', HCMlist1);
1674                     CheckList(Elem) = ones(size(Elem));
1675                     CheckList = CheckList(dev2elem('HCM',List));
1676                     newList = editlist(List, 'HCM', CheckList);
1677                     if isempty(newList)
1678                         fprintf('   Horizontal corrector magnet list cannot be empty.  No change made.\n');
1679                     else
1680                         HCMlist1 = newList;
1681                     end
1682                 end
1683
1684                 if EditFlag == 3
1685                     List = getlist('VCM');
1686                     CheckList = zeros(size(List,1));
1687                     Elem = dev2elem('VCM', VCMlist1);
1688                     CheckList(Elem) = ones(size(Elem));
1689                     CheckList = CheckList(dev2elem('VCM',List));
1690                     newList = editlist(List, 'VCM', CheckList);
1691                     if isempty(newList)
1692                         fprintf('   Vertical corrector magnet cannot be empty.  No change made.\n');
1693                     else
1694                         VCMlist1 = newList;
1695                     end
1696                 end
1697
1698                 if EditFlag == 4
1699                     ListOld = BPMlist1;
1700                     XgoalOld = Xgoal;
1701                     YgoalOld = Ygoal;
1702
1703                     % Full BPM list
1704                     List = getbpmlist('Bergoz');
1705 %                     List = [
1706 %                         1 2
1707 %                         1 5
1708 %                         1 6
1709 %                         1 10
1710 %                         2 1
1711 %                         2 5
1712 %                         2 6
1713 %                         2 9
1714 %                         3 2
1715 %                         3 5
1716 %                         3 6
1717 %                         3 10
1718 %                         3 11
1719 %                         3 12
1720 %                         4 1
1721 %                         4 5
1722 %                         4 6
1723 %                         4 10
1724 %                         5 1
1725 %                         5 5
1726 %                         5 6
1727 %                         5 10
1728 %                         5 11
1729 %                         5 12
1730 %                         6 1
1731 %                         6 5
1732 %                         6 6
1733 %                         6 10
1734 %                         7 1
1735 %                         7 5
1736 %                         7 6
1737 %                         7 10
1738 %                         8 1
1739 %                         8 5
1740 %                         8 6
1741 %                         8 10
1742 %                         9 1
1743 %                         9 5
1744 %                         9 6
1745 %                         9 10
1746 %                         10 1
1747 %                         10 5
1748 %                         10 6
1749 %                         10 10
1750 %                         10 11
1751 %                         10 12
1752 %                         11 1
1753 %                         11 5
1754 %                         11 6
1755 %                         11 10
1756 %                         12 1
1757 %                         12 5
1758 %                         12 6
1759 %                         12 9
1760 %                         ];
1761
1762                     CheckList = zeros(size(List,1),1);
1763                     if ~isempty(BPMlist1)
1764                         for i = 1:size(List,1)
1765                             k = find(List(i,1)==BPMlist1(:,1));
1766                             l = find(List(i,2)==BPMlist1(k,2));
1767
1768                             if isempty(k) | isempty(l)
1769                                 % Item not in list
1770                             else
1771                                 CheckList(i) = 1;
1772                             end
1773                         end
1774                     end
1775
1776                     newList = editlist(List, 'BPM', CheckList);
1777                     if isempty(newList)
1778                         fprintf('   BPM list cannot be empty.  No change made.\n');
1779                     else
1780                         BPMlist1 = newList;
1781                     end
1782
1783                     % Set the goal orbit to the golden orbit
1784                     Xgoal = getgolden('BPMx', BPMlist1);
1785                     Ygoal = getgolden('BPMy', BPMlist1);
1786
1787
1788                     % If a new BPM is added, then set the goal orbit to the golden orbit
1789                     for i = 1:size(BPMlist1,1)
1790
1791                         % Is it a new BPM?
1792                         k = find(BPMlist1(i,1)==ListOld(:,1));
1793                         l = find(BPMlist1(i,2)==ListOld(k,2));
1794
1795                         if isempty(k) | isempty(l)
1796                             % New BPM
1797                         else
1798                             % Use the old value for old BPM
1799                             Xgoal(i) = XgoalOld(k(l));
1800                             Ygoal(i) = YgoalOld(k(l));
1801                         end
1802                     end
1803                 end
1804
1805                 if EditFlag == 5
1806
1807                     ChangeList = editlist(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
1808                     for i = 1:size(ChangeList,1)
1809
1810                         k = find(ChangeList(i,1)==BPMlist1(:,1));
1811                         l = find(ChangeList(i,2)==BPMlist1(k,2));
1812
1813                         prompt = {sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
1814                         def = {sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
1815                         titlestr = 'CHANGE THE GOAL ORBIT';
1816                         lineNo = 1;
1817                         answer = inputdlg(prompt, titlestr, lineNo, def);
1818
1819                         if isempty(answer)
1820                             % No change
1821                             fprintf('   No change was made to the golden orbit.\n');
1822                         else
1823                             Xgoalnew = str2num(answer{1});
1824                             if isempty(Xgoalnew)
1825                                 fprintf('   No change was made to the horizontal golden orbit.\n');
1826                             else
1827                                 Xgoal(k(l)) = Xgoalnew;
1828                             end
1829
1830                             Ygoalnew = str2num(answer{2});
1831                             if isempty(Ygoalnew)
1832                                 fprintf('   No change was made to the vertical golden orbit.\n');
1833                             else
1834                                 Ygoal(k(l)) = Ygoalnew;
1835                             end
1836                         end
1837                     end
1838                     if ~isempty(ChangeList)
1839                         fprintf('   Note:  changing the goal orbit for "Orbit Correction" does not change the goal orbit for "Slow Orbit Feedback."\n');
1840                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
1841                     end
1842                 end
1843
1844                 if EditFlag == 6
1845                     List = [
1846                         1 1
1847                         2 1
1848                         3 1
1849                         4 1
1850                         4 2
1851                         5 1
1852                         6 1
1853                         6 2
1854                         7 1
1855                         8 1
1856                         9 1
1857                         10 1
1858                         11 1
1859                         11 2
1860                         12 1];
1861                     CheckList = zeros(size(List,1),1);
1862                     if ~isempty(LocalBumplist)
1863                         for i = 1:size(List,1)
1864                             k = find(List(i,1)==LocalBumplist(:,1));
1865                             l = find(List(i,2)==LocalBumplist(k,2));
1866
1867                             if isempty(k) | isempty(l)
1868                                 % Item not in list
1869                             else
1870                                 CheckList(i) = 1;
1871                             end
1872                         end
1873                     end
1874                     LocalBumplist = editlist2(List, 'Sector', CheckList);
1875                 end
1876
1877                 if EditFlag == 7
1878                     RFCorrFlag = questdlg(sprintf('Set RF Frequency during Orbit Correction?'),'RF Frequency','Yes','No', 'No');
1879                     if strcmp(RFCorrFlag,'No')
1880                         disp(['   RF Frequency will not be included in global orbit correction.']);
1881                     elseif strcmp(RFCorrFlag,'Yes')
1882                         disp(['   RF Frequency will be included in global orbit correction.']);
1883                     end
1884
1885                 end
1886             end
1887             close(h_fig1);
1888         end
1889
1890         %  ORBIT CORRECTION STRUCTURE (OCS)
1891         %    OCS.BPM (data structure)
1892         %    OCS.CM  (data structure)
1893         %    OCS.GoalOrbit
1894         %    OCS.NIter
1895         %    OCS.SVDIndex
1896         %    OCS.IncrementalFlag = 'Yes'/'No'
1897         %    OCS.BPMWeight
1898         %    OCS.Flags = { 'FitRF' , etc. }
1899         OCSx.BPM = getx(BPMlist1, 'struct');
1900         OCSx.CM = getsp('HCM', HCMlist1, 'struct');
1901         OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
1902         OCSx.NIter = 1;
1903         OCSx.SVDIndex = Xivec;
1904         OCSx.IncrementalFlag = 'No';
1905         OCSx.FitRF = 1;
1906         OCSy.BPM = gety(BPMlist1, 'struct');
1907         OCSy.CM = getsp('VCM', VCMlist1, 'struct');
1908         OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
1909         OCSy.NIter = 1;
1910         OCSy.SVDIndex = Yivec;
1911         OCSy.IncrementalFlag = 'No';
1912         OCSy.FitRF = 0;
1913
1914         % Save vectors
1915         FB.OCSx = OCSx;
1916         FB.OCSy = OCSy;
1917
1918         FB.BPMlist1 = BPMlist1;
1919         FB.HCMlist1 = HCMlist1;
1920         FB.VCMlist1 = VCMlist1;
1921         FB.Xivec = Xivec;
1922         FB.Yivec = Yivec;
1923         FB.Xgoal = OCSx.GoalOrbit;
1924         FB.Ygoal = OCSy.GoalOrbit;
1925         FB.RFCorrFlag = RFCorrFlag;
1926         FB.LocalBumplist = LocalBumplist;
1927         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata',FB);
1928
1929
1930     case 'Feedback'
1931
1932         FBloopIter = 1;
1933         if get(findobj(gcbf,'Tag','SRCTRLCheckboxFOFB'),'Value') == 1
1934             StartFOFBFlag = 1;
1935         else
1936             StartFOFBFlag = 0;
1937         end
1938
1939         FEEDBACK_STOP_FLAG = 0;
1940         HWarnNum=0;
1941         VWarnNum=0;
1942
1943         SR_GeV = getenergy;
1944         % Feedback loop setup
1945         PlotInfoFlag = 0;           % Plot micado stuff
1946         LoopDelay = 1.0;           % Period of feedback loop [seconds], make sure the BPM averaging is correct
1947         VCM_LSB = .00366211;
1948         VCMCHICANE_LSB = .002441;   % 80 max?,  Note: not fully implemented
1949
1950         if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
1951             Xgain  = 0.2;
1952             Ygain  = 0.1;
1953         else
1954             Xgain  = 0.8; % raised 0.5->0.8 at 17:20, 3-2-05 to more quickly correct EPU4 fast switching orbit distortions
1955             Ygain  = 0.8;
1956         end
1957
1958         % Load lattice set for tune feed forward
1959         ConfigSetpoint = getproductionlattice;
1960         %load([getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile')]);
1961         QFsp = ConfigSetpoint.QF.Setpoint.Data;
1962         QDsp = ConfigSetpoint.QD.Setpoint.Data;
1963         TuneW16Min = gap2tune(5, 13.23, 1.8909);
1964         % Tune response matrix
1965         SR_TUNE_MATRIX = gettuneresp({'QF','QD'}, {[],[]}, getenergy('Production'));    % Approx. [0.1944 -0.0286;-0.1182 0.1526];
1966         %SR_TUNE_MATRIX = [0.1641 -0.0245
1967         %                 -0.1149 0.1477];
1968
1969         SQSFsp = amp2k('SQSF','Setpoint',ConfigSetpoint.SQSF.Setpoint.Data);
1970         SQSDsp = amp2k('SQSD','Setpoint',ConfigSetpoint.SQSD.Setpoint.Data);
1971
1972 %         % tune FF for EPUs (data exist for 4 1 parallel, 11 1 parallel and antiparallel
1973 %         load '/home/als/physdata/matlab/srdata/gaptrack/EPU4-1_tunecomp/after_shimming/nux_map_withgaps.mat'
1974 %         dnux_epu_41_m0 = tunexmap(2:end,2:end)-tunexmap(2,12);
1975 %         [gap_epu_41,shift_epu_41]=meshgrid(tunexmap(2:end,1),tunexmap(1,2:end));
1976 %         load '/home/als/physdata/matlab/srdata/gaptrack/EPU4-1_tunecomp/after_shimming/nuy_map_withgaps.mat'
1977 %         dnuy_epu_41_m0 = tuneymap(2:end,2:end)-tuneymap(2,12);
1978 %
1979 %         load '/home/als/physdata/matlab/srdata/gaptrack/archive/epu11d1m0e19_2007-01-28.mat' tune_x tune_y Gaps GapsLongitudinal
1980 %         dnux_epu_111_m0 = tune_x-tune_x(1,11);
1981 %         [gap_epu_111,shift_epu_111]=meshgrid(Gaps,GapsLongitudinal);
1982 %         dnuy_epu_111_m0 = tune_y-tune_y(1,11);
1983 %         load '/home/als/physdata/matlab/srdata/gaptrack/archive/epu11d1m1e19_2007-01-28.mat' tune_x tune_y Gaps GapsLongitudinal
1984 %         dnux_epu_111_m1 = tune_x-tune_x(1,11);
1985 %         dnuy_epu_111_m1 = tune_y-tune_y(1,11);
1986
1987         % tune FF for EPUs (data exist for 4 1 parallel, 11 1 parallel and antiparallel
1988         load '/home/als/physdata/matlab/srdata/epu/tuneshift_2d_tables/epu_tunetables_2d_20070723.mat'
1989         dnux41p = nux41p-nux41p(1,11);
1990         dnuy41p = nuy41p-nuy41p(1,11);
1991         dnux41a = nux41a-nux41a(1,11);
1992         dnuy41a = nuy41a-nuy41a(1,11);
1993         dnux111p = nux111p-nux111p(1,11);
1994         dnuy111p = nuy111p-nuy111p(1,11);
1995         dnux111a = nux111a-nux111a(1,11);
1996         dnuy111a = nuy111a-nuy111a(1,11);
1997         dnux112p = nux112p-nux112p(1,11);
1998         dnuy112p = nuy112p-nuy112p(1,11);
1999         dnux112a = nux112a-nux112a(1,11);
2000         dnuy112a = nuy112a-nuy112a(1,11);
2001
2002         % ID tune compensation does not work in the injection lattice, so ...
2003         if abs(SR_GEV - bend2gev)>  0.05     % Don't use this routine for the injection lattice
2004             fprintf('   This routine should only be used for the production energy: Orbit feedback aborted\n');
2005             return
2006         end
2007
2008         set(0,'showhiddenhandles','on');
2009
2010         try
2011             fprintf('\n');
2012             fprintf('   *******************************\n');
2013             fprintf('   **  Starting Orbit Feedback  **\n');
2014             fprintf('   *******************************\n');
2015             a = clock;
2016             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2017             fprintf('   Note: the Matlab command window will be used to display status information.\n');
2018             fprintf('         It cannot be used to enter commands during slow orbit feedback.\n');
2019
2020
2021                 % save current BPM timeconstant - will reset to this when feedback stops
2022                 BPMtimeconstantOFB = getbpmtimeconstant;
2023                 fprintf('   Current Bergoz BPM time constant is %.1fs\n', BPMtimeconstantOFB);
2024
2025             % >= 2 Hz update rate on IDBPMs
2026             disp('   Bergoz BPM time constant set to 0.2s.')
2027             setbpmtimeconstant(0.2)
2028             pause(1.1);
2029
2030             % Check whether bumps and kickers are on and warn to turn off before starting feedback if necessary
2031             try
2032                 if (getsp('SR01S___BUMP1__BC21')==1 & getsp('SR01S___BUMP1P_BC22')==1) | (getsp('SR01S___SEK____BC21')==1 & getsp('SR01S___SEK_P__BC23')==1) | (getsp('SR01S___SEN____BC20')==1 & getsp('SR01S___SEN_P__BC22')==1)
2033                     soundtada;
2034                     fprintf('   \n');
2035                     fprintf('   *********************************************************************************\n');
2036                     fprintf('   ** One or more of the pulsed SR injection magnets is still on!  Turn them off! **\n');
2037                     fprintf('   *********************************************************************************\n');
2038                     fprintf('   \n');
2039                 end
2040             catch
2041                 disp('**Problem checking the state of the bumps and kickers - please check that they are not pulsing.');
2042             end
2043
2044             % Get vectors
2045
2046             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
2047
2048             BPMlist1 = FB.OCSx.BPM.DeviceList;
2049             % FOFB_BPMlist =
2050             HCMlist1 = FB.HCMlist1;
2051             VCMlist1 = FB.VCMlist1;
2052             Xivec = FB.Xivec;
2053             Yivec = FB.Yivec;
2054             Xgoal = FB.OCSx.GoalOrbit;
2055             Ygoal = FB.OCSy.GoalOrbit;
2056             FFTypeFlag = FB.FFTypeFlag;   %local or global tune correction
2057
2058             iNotHCMChicane = find(HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
2059             iHCMChicane = find(HCMlist1(:,2) == 10);
2060             iNotVCMChicane = find(VCMlist1(:,2) < 10);
2061             iVCMChicane = find(VCMlist1(:,2) == 10);
2062
2063             % Sensitivity matrix for setting fast feedback setpoints
2064             Sx1 = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
2065             Sy1 = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
2066
2067         catch
2068             fprintf('\n  %s \n',lasterr);
2069
2070             % Reset Bergoz BPM time constant to whatever it was before feedback started
2071             fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
2072             setbpmtimeconstant(BPMtimeconstantOFB);
2073
2074
2075             a = clock;
2076             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2077             fprintf('   *************************************************************\n');
2078             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
2079             fprintf('   *************************************************************\n\n');
2080             set(0,'showhiddenhandles','off');
2081             pause(0);
2082
2083             return
2084         end
2085
2086         StartFlag = questdlg(strvcat('','Is it OK to start orbit feedback?'),'Orbit Feedback','Yes','No','No');
2087         if strcmp(StartFlag,'No')
2088             % Reset Bergoz BPM time constant to whatever it was before feedback started
2089             fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
2090             setbpmtimeconstant(BPMtimeconstantOFB);
2091
2092             a = clock;
2093             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2094             fprintf('   ***************************\n');
2095             fprintf('   **  Orbit Feedback Exit  **\n');
2096             fprintf('   ***************************\n\n');
2097             pause(0);
2098             return
2099         end
2100
2101         SR_STATE_OLD = scaget('SR_STATE');
2102         setpv('SR_STATE', 5);
2103         set(0,'showhiddenhandles','on');
2104         [StateNumber, StateString] = getsrstate;
2105         if StateNumber >= 0
2106             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2107         else
2108             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2109         end
2110         fprintf('   Using %d E-vectors horizontally.\n', length(Xivec));
2111         fprintf('   Using %d E-vectors vertically.\n',   length(Yivec));
2112         fprintf('   Starting slow orbit correction every %.1f seconds.\n', LoopDelay);
2113         %  fprintf('   Resetting SR11 chicane motors every 20 seconds to fix drift problem.\n');
2114
2115         IDSector = getlist('ID');
2116         EPUlist = find((IDSector(:,1)==4) | (IDSector(:,1)==11));
2117         oldgap=210*ones(size(IDSector,1),1);
2118         oldShift=zeros(size(oldgap));
2119
2120         try
2121
2122             % Get and display data
2123             x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
2124             y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
2125             STDx = norm(x)/sqrt(length(x));
2126             STDy = norm(y)/sqrt(length(y));
2127             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
2128             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
2129
2130             % write goldenorbit values to Fast Orbit Feedback
2131             try
2132                 write_goldenorbit_ffb;
2133             catch
2134                 disp('write_goldenorbit_ffb did not work!');
2135             end
2136             setpv('SR01____FFBON__BC00',2);
2137             %pause(0);
2138
2139             %display state of FOFB system
2140             FOFBStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2141                 getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2142                 getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2143                 getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2144             FOFBStatusStr = ['    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    '];
2145             for loop = 1:size(FOFBStatus,2)
2146                 if FOFBStatus(loop)==0
2147                     FOFBStatusStr(loop,:) = 'OFF ';
2148                 elseif FOFBStatus(loop)==1
2149                     FOFBStatusStr(loop,:) = 'ON  ';
2150                 elseif FOFBStatus(loop)==2
2151                     FOFBStatusStr(loop,:) = 'OPEN';
2152                 else
2153                     FOFBStatusStr(loop,:) = 'BAD ';
2154                 end
2155             end
2156             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 %s',FOFBStatusStr(1,:)),'ForegroundColor',[0 0 0]);
2157             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 %s',FOFBStatusStr(2,:)),'ForegroundColor',[0 0 0]);
2158             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 %s',FOFBStatusStr(3,:)),'ForegroundColor',[0 0 0]);
2159             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 %s',FOFBStatusStr(4,:)),'ForegroundColor',[0 0 0]);
2160             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 %s',FOFBStatusStr(5,:)),'ForegroundColor',[0 0 0]);
2161             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 %s',FOFBStatusStr(6,:)),'ForegroundColor',[0 0 0]);
2162             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 %s',FOFBStatusStr(7,:)),'ForegroundColor',[0 0 0]);
2163             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 %s',FOFBStatusStr(8,:)),'ForegroundColor',[0 0 0]);
2164             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 %s',FOFBStatusStr(9,:)),'ForegroundColor',[0 0 0]);
2165             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 %s',FOFBStatusStr(10,:)),'ForegroundColor',[0 0 0]);
2166             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 %s',FOFBStatusStr(11,:)),'ForegroundColor',[0 0 0]);
2167             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 %s',FOFBStatusStr(12,:)),'ForegroundColor',[0 0 0]);
2168
2169         catch
2170
2171             fprintf('\n  %s \n',lasterr);
2172
2173             % Reset Bergoz BPM time constant to whatever it was before feedback started
2174             fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
2175             setbpmtimeconstant(BPMtimeconstantOFB);
2176
2177
2178             a = clock;
2179             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2180             fprintf('   *************************************************************\n');
2181             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
2182             fprintf('   *************************************************************\n\n');
2183
2184             setpv('SR_STATE',SR_STATE_OLD);
2185             [StateNumber, StateString] = getsrstate;
2186             if StateNumber >= 0
2187                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2188             else
2189                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2190             end
2191             set(0,'showhiddenhandles','off');
2192             pause(0);
2193
2194             return
2195
2196         end
2197
2198
2199         % Disable buttons
2200         set(0,'showhiddenhandles','on');
2201         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','off');
2202         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','on');
2203         set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','off');
2204         set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','off');
2205         set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','off');
2206         set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','off');
2207         set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','off');
2208         set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','off');
2209         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','off');
2210         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','off');
2211         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','off');
2212         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','off');
2213         set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','off');
2214         pause(0);
2215
2216
2217         % Initialize feedback loop
2218         StartTime = gettime;
2219         StartErrorTime = gettime;
2220         Xold = getx(FB.OCSx.BPM.DeviceList);
2221         Yold = gety(FB.OCSy.BPM.DeviceList);
2222         HQMOFM_stalenum = 0;
2223         pause(LoopDelay);
2224
2225         N_HCM = size(HCMlist1,1);
2226         N_VCM = size(VCMlist1,1);
2227
2228         N_RFMO = 1;
2229
2230         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2231             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'SetRF','Nodisplay','Nosetsp');
2232         else
2233             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
2234         end
2235         [FB.OCSx, Smatx, Sx, Ux, Vx] = orbitcorrectionmethods(FB.OCSx);
2236
2237         [FB.OCSy, junk, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
2238         [FB.OCSy, Smaty, Sy, Uy, Vy] = orbitcorrectionmethods(FB.OCSy);
2239
2240
2241         %%%%%%%%%%%%%%%%%%%%%%%
2242         % Start feedback loop %
2243         %%%%%%%%%%%%%%%%%%%%%%%
2244
2245         % chicaneloop=1;  % loop variable for resetting drifting chicanes (see a few lines below)
2246         % fftest=figure;
2247
2248         setpv('SR01____FFBON__BC00',2); % put FOFB in open loop so beamnoise gets recorded even if FOFB is not enabled
2249
2250         while 1
2251             try
2252                 t00 = gettime;
2253
2254                 %          if chicaneloop==20 % reset SR11 motor chicane setpoints every 20s due to drifting positions
2255                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(6),[11 1],0);
2256                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(7),[11 2],0);
2257                 %             chicaneloop = 1;
2258                 %          else
2259                 %             chicaneloop = chicaneloop + 1;
2260                 %          end
2261
2262                 % Check if GUI has been closed
2263                 if isempty(gcbf)
2264                     FEEDBACK_STOP_FLAG = 1;
2265                     lasterr('SRCONTROL GUI DISAPPEARED!');
2266                     error('SRCONTROL GUI DISAPPEARED!');
2267                 end
2268
2269                 %%%%%%%%%%%%%%%%%%%%%%%
2270                 % Fast orbit feedback %
2271                 %%%%%%%%%%%%%%%%%%%%%%%
2272                 if StartFOFBFlag == 1 & FBloopIter > 3
2273                     setpv('SR01____FFBON__BC00',2);
2274                     pause(0.5);
2275                     setpv('SR01____FFBON__BC00',1);
2276                     StartFOFBFlag = 0;
2277                     pause(1);
2278                     FOFBOnStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2279                         getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2280                         getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2281                         getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2282                     if any(FOFBOnStatus==0) | any(FOFBOnStatus==2)
2283                         setpv('SR01____FFBON__BC00',2); % open FOFB loop
2284                         disp('************************************************************************************************************');
2285                         disp('** Problem turning on Fast Orbit Feedback system...                                                       **');
2286                         disp('** Check status of ffbsecXX crates - but remember that a crate reboot will turn off Quads in that sector! **');
2287                         disp('** Suggest disabling the "Fast Orbit Correction" checkbox and starting Orbit Feedback again.              **');
2288                         disp('************************************************************************************************************');
2289                     else
2290                         fprintf('   Starting Fast Orbit Feedback at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
2291                     end
2292                 end
2293
2294
2295                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2296                 % Horizontal plane "feedback" %
2297                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2298
2299                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxSOFB'),'Value') == 1
2300
2301                     % Get orbit and check that the BPMs are different from the last update
2302                     Xnew = getx(FB.OCSx.BPM.DeviceList);
2303
2304                     % Don't feedback if the current is too small
2305                     if getdcct < 5
2306                         FEEDBACK_STOP_FLAG = 1;
2307                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2308                         break;
2309                     end
2310
2311                     x = Xgoal - Xnew;
2312                     STDx = norm(x)/sqrt(length(x));
2313
2314                     if any(Xold == Xnew)
2315                         a = clock;
2316                         N_Stale_Data_Points = find((Xold==Xnew)==1);
2317                         for loop = N_Stale_Data_Points'
2318                             fprintf('   Stale data: BPMx(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSx.BPM.DeviceList(loop,1), FB.OCSx.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2319                         end
2320                     else
2321                         % Compute horizontal correction
2322                         %%%OCSx0 = FB.OCSx;
2323                         FB.OCSx.BPM.Data = Xnew;
2324                         FB.OCSx = orbitcorrectionmethods(FB.OCSx, Smatx, Sx, Ux, Vx);
2325
2326                         %%%[FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
2327
2328                         % reduced feedback gain (implemented by Greg Portmann, December 2000)
2329                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2330                         % increased back to 0.8 C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2331                         % increased to 1.0, C. Steier, 2002-05-04, trim DACs
2332                         X = Xgain .* FB.OCSx.CM.Delta;
2333                         X(N_HCM+1) = 0.3*FB.OCSx.DeltaRF/4.988e-3;
2334                         %%%X = Xgain .* (FB.OCSx.CM.Data - OCSx0.CM.Data);
2335
2336                         % check corrector trim values + next step values, warn or stop FB as necessary
2337                         HCMtrimSP=getpv('HCM','Trim',HCMlist1);
2338                         HCMtrimSP_next = HCMtrimSP + X(1:N_HCM);
2339                         if max(abs(HCMtrimSP_next)) > 4
2340                             HCMtrimnum=find(abs(HCMtrimSP_next) > 4);
2341
2342                             % print message to screen
2343                             fprintf('**One or more of the horizontal correctors is at its maximum!! Stopping orbit feedback. \n');
2344                             fprintf('%s\n',datestr(now));
2345                             for loop = HCMtrimnum'
2346                                 fprintf('**%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2347                             end
2348
2349                             % send alphapage to operator pager
2350                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2351                             FEEDBACK_STOP_FLAG = 1;
2352
2353                             setpv('SR_STATE', -5);
2354                             [StateNumber, StateString] = getsrstate;
2355                             if StateNumber >= 0
2356                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2357                             else
2358                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2359                             end
2360                         end
2361
2362                         % check chicane trim coil values + next step values, warn or stop FB as necessary
2363                         HCMCHICANEtrimSP=getpv('HCM','Setpoint',HCMlist1(iHCMChicane,:));
2364                         HCMCHICANEtrimSP_next = HCMCHICANEtrimSP + X(iHCMChicane);
2365                         if max(abs(HCMCHICANEtrimSP_next)) > 20
2366                             HCMCHICANEtrimnum=find(abs(HCMCHICANEtrimSP_next) > 20);
2367
2368                             % print message to screen
2369                             fprintf('**One or more of the horizontal chicane trim coil correctors is at its maximum!! Stopping orbit feedback. \n');
2370                             fprintf('%s\n',datestr(now));
2371                             for loop = HCMCHICANEtrimnum'
2372                                 fprintf('**%s is one of the problem correctors.\n',getname('HCM','Setpoint',HCMlist1(loop,:)));
2373                             end
2374                             fprintf('**Maybe try resetting the setpoints of the motor chicanes in case they are drifting...\n');
2375
2376                             % send alphapage to operator pager
2377                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2378                             FEEDBACK_STOP_FLAG = 1;
2379
2380                             setpv('SR_STATE', -5);
2381                             [StateNumber, StateString] = getsrstate;
2382                             if StateNumber >= 0
2383                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2384                             else
2385                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2386                             end
2387                         end
2388
2389                         if FEEDBACK_STOP_FLAG == 1
2390                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2391                             if getpv('SR01____FFBON__BC00')==1
2392                                 disp('   Stopping Fast Orbit Feedback.');
2393                             end
2394                             setpv('SR01____FFBON__BC00',0);
2395                             pause(0.5);
2396                             setpv('SR01____FFBON__BC00',2);
2397                             break;
2398                         end
2399
2400                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2401                         pause(0);
2402
2403                         if max(abs(HCMtrimSP_next) > 3)
2404                             HCMtrimnum=find(abs(HCMtrimSP_next) > 3);
2405                             HWarnNum=HWarnNum+1;
2406                             if (HWarnNum==1 | rem(HWarnNum,120)==0)
2407
2408                                 % print message to screen every two minutes
2409                                 fprintf('**One or more of the horizontal corrector trims is above 3A or below -3A! \n');
2410                                 fprintf('%s\n',datestr(now));
2411                                 for loop = HCMtrimnum'
2412                                     fprintf('**%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2413                                 end
2414                                 fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2415
2416                                 %send alphapage to operator pager the first time then at 10 minutes
2417                                 if (HWarnNum==1 | HWarnNum==600)
2418                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageHCM.txt
2419                                 end
2420                             end
2421                         elseif max(abs(HCMCHICANEtrimSP_next) > 15)
2422                             HCMCHICANEtrimnum=find(abs(HCMCHICANEtrimSP_next) > 15);
2423                             HWarnNum=HWarnNum+1;
2424                             if (HWarnNum==1 | rem(HWarnNum,120)==0)
2425
2426                                 % print message to screen every two minutes
2427                                 fprintf('**One or more of the horizontal chicane corrector trim coils is above 15A or below -15A! \n');
2428                                 fprintf('%s\n',datestr(now));
2429                                 for loop = HCMCHICANEtrimnum'
2430                                     fprintf('**%s is one of the problem correctors.\n',getname('HCM','Setpoint',HCMlist1(loop,:)));
2431                                 end
2432                                 fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2433
2434                                 %reset motor chicanes in case they are drifting
2435                                 %try
2436                                 %        fprintf(' Resetting the setpoints of the motor chicanes in case they are drifting...\n');
2437                                           %        setpv('HCMCHICANEM','Setpoint',[],ConfigSetpoint.Setpoint.Data,0);
2438                                           %catch
2439                                           %end
2440
2441                                 %send alphapage to operator pager the first time then at 10 minutes
2442                                 if (HWarnNum==1 | HWarnNum==600)
2443                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageHCMCHICANE.txt
2444                                 end
2445                             end
2446                         else
2447                             HWarnNum=0;
2448                         end
2449
2450                         % Don't feedback if the current is too small
2451                         if getdcct < 5
2452                             FEEDBACK_STOP_FLAG = 1;
2453                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2454                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2455                             break;
2456                         end
2457
2458                         if N_HCM > 0
2459                             steppv('HCM','Trim', X(iNotHCMChicane), HCMlist1(iNotHCMChicane,:), 0);
2460                             steppv('HCM','Setpoint', X(iHCMChicane), HCMlist1(iHCMChicane,:), 0);
2461                         end
2462
2463                         % write fast orbit feedback setpoints
2464                         if 1
2465                             %write_goldenorbit_ffb_2planes(1, Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM)+Sx3*X(length(X))/20, BPMlist1);
2466                             % should be corrected to include result of next frequency step ...
2467                             write_goldenorbit_ffb_2planes(1,Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM),BPMlist1);
2468                         end
2469
2470                         %fprintf('Horizontal Done: %f \n',gettime-t00);
2471
2472                         % RF feedback
2473                         HQMOFMsp_last = getpv('EG______HQMOFM_AC01');
2474
2475                         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2476                             if N_RFMO > 0
2477                                 if abs(X(end)) < .01
2478                                     % if abs(FB.OCSx.DeltaRF/3) < .01
2479                                     steppv('EG______HQMOFM_AC01', X(end));
2480                                 else
2481                                     steppv('EG______HQMOFM_AC01', 0.01*sign(X(end)));
2482                                 end
2483                             end
2484
2485                             HQMOFMsp_now = getpv('EG______HQMOFM_AC01');
2486
2487                             % Check for stale RF feedback
2488                             if HQMOFMsp_last == HQMOFMsp_now
2489                                 HQMOFM_stalenum = HQMOFM_stalenum + 1;
2490                                 if HQMOFM_stalenum == 30 % warn and message to pager if stale for 30 secs
2491                                     fprintf('**The RF is not responding to orbit feedback changes! \n');
2492                                     fprintf('%s\n',datestr(now));
2493                                     fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2494                                     fprintf('**ILC 73 controls the EG______HQMOFM_AC01 channel, which sets the RF frequency. \n');
2495                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstaleRFmessage.txt
2496                                 end
2497                                 if rem(HQMOFM_stalenum,120)==0 % message to screen every 2 minutes
2498                                     fprintf('**The RF is not responding to orbit feedback changes! (%s)\n',datestr(now));
2499                                 end
2500                             else
2501                                 HQMOFM_stalenum = 0;
2502                             end
2503
2504                         end
2505
2506                         %fprintf('RF Done: %f \n',gettime-t00);
2507
2508                         Xold = Xnew;
2509                     end % End horizontal correction
2510
2511
2512                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2513                     % Vertical plane "feedback" %
2514                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2515
2516                     % Get orbit and check that the BPMs are different from the last update
2517                     Ynew = gety(FB.OCSy.BPM.DeviceList);
2518
2519                     % Don't feedback if the current is too small
2520                     if getdcct < 5
2521                         FEEDBACK_STOP_FLAG = 1;
2522                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2523                         break;
2524                     end
2525
2526                     y = Ygoal - Ynew;
2527                     STDy = norm(y)/sqrt(length(y));
2528
2529                     if any(Yold == Ynew)
2530                         a = clock;
2531                         N_Stale_Data_Points = find((Yold==Ynew)==1);
2532                         for loop = N_Stale_Data_Points'
2533                             fprintf('   Stale data: BPMy(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSy.BPM.DeviceList(loop,1), FB.OCSy.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2534                         end
2535
2536                     else
2537
2538                         % Compute vertical correction
2539                         %%%OCSy0 = FB.OCSy;
2540                         FB.OCSy.BPM.Data = Ynew;
2541                         FB.OCSy = orbitcorrectionmethods(FB.OCSy, Smaty, Sy, Uy, Vy);
2542
2543                         %%%[FB.OCSy, RF, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
2544
2545                         % reduced feedback gain, C. Steier, 2001-03-25
2546                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2547                         % increased back to 0.8, C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2548                         % set to unity gain, C. Steier, 2002-05-04, trim DACs
2549                         Y = Ygain .* FB.OCSy.CM.Delta;
2550                         %%%Y = Ygain .* (FB.OCSy.CM.Data - OCSy0.CM.Data);
2551
2552                         % Just SVD correction
2553                         % warning('Not using "micado" correction in the vertical plane.');
2554
2555                         % check for trim values+next step values, warn or stop FB as necessary
2556                         VCMtrimSP = getpv('VCM','Trim',VCMlist1);
2557                         VCMtrimSP_next = VCMtrimSP + Y(1:N_VCM);
2558                         if max(abs(VCMtrimSP_next)) > 12
2559                             VCMtrimnum=find(abs(VCMtrimSP_next) > 12);
2560
2561                             % print message to screen
2562                             fprintf('**One or more of the vertical correctors is at its maximum!! Stopping orbit feedback. \n');
2563                             fprintf('%s\n',datestr(now));
2564                             for loop = VCMtrimnum'
2565                                 fprintf('**%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2566                             end
2567
2568                             % send alphapage to operator pager
2569                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2570                             FEEDBACK_STOP_FLAG = 1;
2571
2572                             setpv('SR_STATE', -5);
2573                             [StateNumber, StateString] = getsrstate;
2574                             if StateNumber >= 0
2575                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2576                             else
2577                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2578                             end
2579                         end
2580
2581                         % check chicane trim coil values + next step values, warn or stop FB as necessary
2582                         VCMCHICANEtrimSP=getpv('VCM','Setpoint',VCMlist1(iVCMChicane,:));
2583                         VCMCHICANEtrimSP_next = VCMCHICANEtrimSP + X(iVCMChicane);
2584                         if max(abs(VCMCHICANEtrimSP_next)) > 20
2585                             VCMCHICANEtrimnum=find(abs(VCMCHICANEtrimSP_next) > 20);
2586
2587                             % print message to screen
2588                             fprintf('**One or more of the vertical chicane trim coil correctors is at its maximum!! Stopping orbit feedback. \n');
2589                             fprintf('%s\n',datestr(now));
2590                             for loop = VCMCHICANEtrimnum'
2591                                 fprintf('**%s is one of the problem correctors.\n',getname('VCM','Setpoint',VCMlist1(loop,:)));
2592                             end
2593                             fprintf('**Maybe try resetting the setpoints of the motor chicanes in case they are drifting...\n');
2594
2595                             % send alphapage to operator pager
2596                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2597                             FEEDBACK_STOP_FLAG = 1;
2598
2599                             setpv('SR_STATE', -5);
2600                             [StateNumber, StateString] = getsrstate;
2601                             if StateNumber >= 0
2602                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2603                             else
2604                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2605                             end
2606                         end
2607
2608                         if FEEDBACK_STOP_FLAG == 1
2609                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2610                             if getpv('SR01____FFBON__BC00')==1
2611                                 disp('   Stopping Fast Orbit Feedback.');
2612                             end
2613                             setpv('SR01____FFBON__BC00',0);
2614                             pause(0.5);
2615                             setpv('SR01____FFBON__BC00',2);
2616                             break;
2617                         end
2618
2619                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2620                         % pause(0);
2621
2622                         if max(abs(VCMtrimSP_next) > 4)
2623                             VCMtrimnum=find(abs(VCMtrimSP_next) > 4);
2624                             VWarnNum=VWarnNum+1;
2625                             if (VWarnNum==1 | rem(VWarnNum,120)==0)
2626
2627                                 % print message to screen every two minutes
2628                                 fprintf('**One or more of the vertical corrector trims is above 4A or below -4A! \n');
2629                                 fprintf('%s\n',datestr(now));
2630                                 for loop = VCMtrimnum'
2631                                     fprintf('**%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2632                                 end
2633                                 fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2634
2635                                 %send alphapage to operator pager the first time then at 10 minutes
2636                                 if (VWarnNum==1 | VWarnNum==600)
2637                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageVCM.txt
2638                                 end
2639                             end
2640                         elseif max(abs(VCMCHICANEtrimSP_next) > 15)
2641                             VCMCHICANEtrimnum=find(abs(VCMCHICANEtrimSP_next) > 15);
2642                             VWarnNum=VWarnNum+1;
2643                             if (HWarnNum==1 | rem(HWarnNum,120)==0)
2644
2645                                 % print message to screen every two minutes
2646                                 fprintf('**One or more of the vertical chicane corrector trim coils is above 15A or below -15A! \n');
2647                                 fprintf('%s\n',datestr(now));
2648                                 for loop = VCMCHICANEtrimnum'
2649                                     fprintf('**%s is one of the problem correctors.\n',getname('VCM','Setpoint',VCMlist1(loop,:)));
2650                                 end
2651                                 fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2652
2653                                 %reset motor chicanes in case they are drifting
2654                                 %try
2655                                 %        fprintf(' Resetting the setpoints of the motor chicanes in case they are drifting...\n');
2656                                           %        setpv('HCMCHICANEM','Setpoint',[],ConfigSetpoint.Setpoint.Data,0);
2657                                           %catch
2658                                           %end
2659
2660                                 %send alphapage to operator pager the first time then at 10 minutes
2661                                 if (VWarnNum==1 | VWarnNum==600)
2662                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageVCMCHICANE.txt
2663                                 end
2664                             end
2665                         else
2666                             VWarnNum=0;
2667                         end
2668
2669                         % Don't feedback if the current is too small
2670                         if getdcct < 5
2671                             FEEDBACK_STOP_FLAG = 1;
2672                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2673                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2674                             break;
2675                         end
2676
2677                         if N_VCM > 0
2678                             steppv('VCM','Trim', Y(iNotVCMChicane), VCMlist1(iNotVCMChicane,:), 0);
2679                             steppv('VCM','Setpoint', Y(iVCMChicane), VCMlist1(iVCMChicane,:), 0);
2680                         end
2681
2682                         % write fast orbit feedback setpoints
2683                         if 1
2684                             write_goldenorbit_ffb_2planes(2,Ynew(1:size(BPMlist1,1))+Sy1*Y(1:N_VCM),BPMlist1);
2685                         end
2686
2687                     end
2688
2689                     Yold = Ynew;
2690
2691                     %fprintf('Vertical Done: %f \n',gettime-t00);
2692                 end % End vertical correction
2693
2694
2695                 %%%%%%%%%%%%%%%%%%%%%
2696                 % Tune feed forward %
2697                 %%%%%%%%%%%%%%%%%%%%%
2698                 % We should do a Sector limit check
2699
2700                 tic;
2701                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxTune'),'Value') == 1
2702
2703                     if strcmp(SR_Mode, '1.9 GeV, High Tune') || strcmp(SR_Mode, '1.9 GeV, Inject at 1.23') || strcmp(SR_Mode, '1.9 GeV, Two-Bunch')
2704
2705                         addQFsp = zeros(24,1);
2706                         addQDsp = zeros(24,1);
2707
2708                         if strcmp(FFTypeFlag,'Local')
2709                             disp('  No local tune compensation available - global is the default now.');
2710                         elseif strcmp(FFTypeFlag,'Global')
2711
2712                             % The vectorized gets were put outside of loop for speed reasons
2713                             %
2714                             % should also set up QFfac, Quadelem, Quadlist structures outside loop
2715                             actualgap = getid(IDSector);
2716                             [gapmin,gapmax] = gaplimit(IDSector);
2717                             corrind = find(actualgap<(gapmin-1));
2718                             actualgap(corrind)=gapmax(corrind);
2719                             Shift=zeros(size(actualgap));
2720                             Shift(EPUlist)=getpv('EPU');
2721
2722                             IDchangedList=find((abs(actualgap-oldgap)>0.005) | (abs(Shift-oldShift)>0.005));
2723
2724                             if ~isempty(IDchangedList)
2725
2726                                 oldgap=actualgap;
2727                                 oldShift=Shift;
2728
2729                                 % EPUs excite nux = .25 resonance in vertical linear polarization mode!
2730                                 % therefore with EPU tune feedforward
2731                                 % running, we want to move our nominal working point away (just below) the .25 resonance.
2732                                 %
2733                                 % The following tune correction moves nominal
2734                                 % nu_x from .25 to .245 - this should be enough for well set up lattices.
2735                                 %
2736                                 % 24 QF+ 24 QD
2737                                 DeltaAmps = inv(SR_TUNE_MATRIX) * [-0.005;0];    %  DelAmps =  [QF; QD];
2738                                 addQFsp = addQFsp + DeltaAmps(1,:);
2739                                 addQDsp = addQDsp + DeltaAmps(2,:);
2740
2741                                 for gapnum = 1:length(actualgap)
2742
2743                                     % Change in tune and [QF;QD] from maximum gap
2744
2745                                     if (IDSector(gapnum,1) == 4) || (IDSector(gapnum,1) == 11)
2746                                         if IDSector(gapnum,2) == 1
2747                                             modenamestr = sprintf('SR%02dU___ODS1M__DC00',IDSector(gapnum,1));
2748                                         else % if IDSector(gapnum,2) == 2
2749                                             modenamestr = sprintf('SR%02dU___ODS2M__DC00',IDSector(gapnum,1));
2750                                         end
2751                                         epumode = getpv(modenamestr);
2752                                         if (IDSector(gapnum,1) == 4) && (IDSector(gapnum,2) == 1)
2753                                             if (epumode == 0)
2754 %                                                 DeltaNuX = interp2(gap_epu_41,shift_epu_41,dnux_epu_41_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2755 %                                                 DeltaNuY = interp2(gap_epu_41,shift_epu_41,dnuy_epu_41_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2756                                                 DeltaNuX = interp2(gap41p',shift41p',dnux41p',actualgap(gapnum),Shift(gapnum),'linear',0);
2757                                                 DeltaNuY = interp2(gap41p',shift41p',dnuy41p',actualgap(gapnum),Shift(gapnum),'linear',0);
2758                                             elseif (epumode == 1)
2759 %                                                 DeltaNux = 0;
2760 %                                                 DeltaNuY = gap2tune(IDSector(gapnum, :), actualgap(gapnum), SR_GeV);
2761                                                 DeltaNuX = interp2(gap41a',shift41a',dnux41a',actualgap(gapnum),Shift(gapnum),'linear',0);
2762                                                 DeltaNuY = interp2(gap41a',shift41a',dnuy41a',actualgap(gapnum),Shift(gapnum),'linear',0);
2763                                             else
2764                                                 DeltaNux = 0;
2765                                                 DeltaNuY = gap2tune(IDSector(gapnum, :), actualgap(gapnum), SR_GeV);
2766                                             end
2767                                         elseif (IDSector(gapnum,1) == 11) && (IDSector(gapnum,2) == 1)
2768                                             if (epumode == 0)
2769 %                                                 DeltaNuX = interp2(gap_epu_111,shift_epu_111,dnux_epu_111_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2770 %                                                 DeltaNuY = interp2(gap_epu_111,shift_epu_111,dnuy_epu_111_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2771                                                 DeltaNuX = interp2(gap111p',shift111p',dnux111p',actualgap(gapnum),Shift(gapnum),'linear',0);
2772                                                 DeltaNuY = interp2(gap111p',shift111p',dnuy111p',actualgap(gapnum),Shift(gapnum),'linear',0);
2773                                             elseif (epumode == 1)
2774 %                                                 DeltaNuX = interp2(gap_epu_111,shift_epu_111,dnux_epu_111_m1',actualgap(gapnum),Shift(gapnum),'linear',0);
2775 %                                                 DeltaNuY = interp2(gap_epu_111,shift_epu_111,dnuy_epu_111_m1',actualgap(gapnum),Shift(gapnum),'linear',0);
2776                                                 DeltaNuX = interp2(gap111a',shift111a',dnux111a',actualgap(gapnum),Shift(gapnum),'linear',0);
2777                                                 DeltaNuY = interp2(gap111a',shift111a',dnuy111a',actualgap(gapnum),Shift(gapnum),'linear',0);
2778                                             else
2779                                                 DeltaNuX = 0;
2780                                                 DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);   % variation of vertical tune shift with phase is small for EPUs
2781                                             end
2782                                         elseif (IDSector(gapnum,1) == 11) && (IDSector(gapnum,2) == 2)
2783                                             if (epumode == 0)
2784 %                                                 DeltaNuX = interp2(gap_epu_111,shift_epu_111,dnux_epu_111_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2785 %                                                 DeltaNuY = interp2(gap_epu_111,shift_epu_111,dnuy_epu_111_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2786                                                 DeltaNuX = interp2(gap112p',shift112p',dnux112p',actualgap(gapnum),Shift(gapnum),'linear',0);
2787                                                 DeltaNuY = interp2(gap112p',shift112p',dnuy112p',actualgap(gapnum),Shift(gapnum),'linear',0);
2788                                             elseif (epumode == 1)
2789 %                                                 DeltaNuX = interp2(gap_epu_111,shift_epu_111,dnux_epu_111_m1',actualgap(gapnum),Shift(gapnum),'linear',0);
2790 %                                                 DeltaNuY = interp2(gap_epu_111,shift_epu_111,dnuy_epu_111_m1',actualgap(gapnum),Shift(gapnum),'linear',0);
2791                                                 DeltaNuX = interp2(gap112a',shift112a',dnux112a',actualgap(gapnum),Shift(gapnum),'linear',0);
2792                                                 DeltaNuY = interp2(gap112a',shift112a',dnuy112a',actualgap(gapnum),Shift(gapnum),'linear',0);
2793                                             else
2794                                                 DeltaNuX = 0;
2795                                                 DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);   % variation of vertical tune shift with phase is small for EPUs
2796                                             end
2797                                         else
2798                                             DeltaNuX = 0;
2799                                             DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);
2800                                         end
2801
2802                                     else
2803                                         DeltaNuX = 0;
2804                                         DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);
2805                                     end
2806
2807                                     DelQF = zeros(length(QFsp),1);
2808                                     DelQD = zeros(length(QFsp),1);
2809
2810                                     fraccorr = 0.8*DeltaNuY ./ TuneW16Min;
2811
2812                                     % Find which quads to change (local beta beating correction
2813                                     % (horizontal for EPU, vertical otherwise)
2814                                     QuadList = [IDSector(gapnum,1)-1 2; IDSector(gapnum,1) 1];
2815                                     QuadElem = dev2elem('QF',QuadList); % in reality use QF and QD ...
2816
2817                                     % global vertical tune correction
2818                                     % 24 QF+ 24 QD
2819                                     DeltaAmps = inv(SR_TUNE_MATRIX) * [(fraccorr*6.23e-4); fraccorr*(-0.05301)];    %  DelAmps =  [QF; QD];
2820                                     DelQF = DelQF + DeltaAmps(1,:);
2821                                     DelQD = DelQD + DeltaAmps(2,:);
2822
2823                                     % local horizontal tune correction (is also nearly a beta beating correction) only nonzero for EPUs!
2824                                     % 2 QF + 2 QD
2825                                     DeltaAmpsLocal = 12*inv(SR_TUNE_MATRIX) * [-DeltaNuX;0];                       %  DelAmps =  [QF; QD];
2826                                     DelQF(QuadElem) = DelQF(QuadElem)+DeltaAmpsLocal(1,1);
2827                                     DelQD(QuadElem) = DelQD(QuadElem)+DeltaAmpsLocal(2,1);
2828
2829                                     % local vertical beta beating correction (should be used together with above global tune correction)
2830                                     % set to zero for EPUs, since their vertical tune shift is small
2831                                     % 2 QF + 2QD
2832                                     if (IDSector(gapnum,1)==6) | (IDSector(gapnum,1)==7) | (IDSector(gapnum,1)==10) | (IDSector(gapnum,1)==11)
2833                                         QFfac = ([2.243127/2.237111; 2.243127/2.237111]-1) * fraccorr;
2834                                         QDfac = ([2.556392/2.511045; 2.556392/2.511045]-1) * fraccorr;
2835                                     elseif (IDSector(gapnum,1)==5) | (IDSector(gapnum,1)==9)
2836                                         QFfac = ([2.225965/2.219784; 2.243096/2.237111]-1) * fraccorr;
2837                                         QDfac = ([2.528950/2.483259; 2.556345/2.511045]-1) * fraccorr;
2838                                     elseif (IDSector(gapnum,1)==4) | (IDSector(gapnum,1)==8) | (IDSector(gapnum,1)==12)
2839                                         QFfac = ([2.243096/2.237111; 2.225965/2.219784]-1) * fraccorr;
2840                                         QDfac = ([2.556345/2.511045; 2.528950/2.483259]-1) * fraccorr;
2841                                     else
2842                                         QFfac = zeros(2,1);
2843                                         QDfac = zeros(2,1);
2844                                     end
2845
2846                                     DelQF(QuadElem,:) = DelQF(QuadElem,:) + QFfac.*QFsp(QuadElem,:);
2847                                     DelQD(QuadElem,:) = DelQD(QuadElem,:) + QDfac.*QDsp(QuadElem,:);
2848
2849                                     % add all tune and beta beating corrections for this one ID to the summed up correction vectors for all IDs
2850                                     addQFsp = addQFsp+DelQF;
2851                                     addQDsp = addQDsp+DelQD;
2852
2853
2854                                     % Skew FF for IVID
2855                                     if (IDSector(gapnum,1)==6)
2856                                         scale=(gap2tune(6)/0.005)^(3/4)*0.16;
2857                                         [SQSFincr, SQSDincr] = set_etaywave_nuy9_20skews_skewFF(scale);
2858                                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2859                                         % should add a limit check here %
2860                                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2861                                         setpv('SQSF', 'Setpoint', SQSFsp+SQSFincr, [], 0, 'Physics');
2862                                         setpv('SQSD', 'Setpoint', SQSDsp+SQSDincr, [], 0, 'Physics');
2863                                     end
2864
2865                                 end
2866
2867                                 % Set quadrupoles using main setpoint channels
2868                                 setpv('QF', QFsp+addQFsp,[], 0);
2869                                 setpv('QD', QDsp+addQDsp,[], 0);
2870                                 % % Set quadrupoles using FF setpoint channels
2871                                 % setpv('QF', 'FF', addQFsp, [], 0);
2872                                 % setpv('QD', 'FF', addQDsp, [], 0);
2873
2874                             end
2875
2876                         else
2877                             error('Unknown type selected for tune FF');
2878                         end
2879
2880                     else
2881                         disp('  No tune FF algorithm for non-production modes yet...');
2882                     end
2883                 end
2884
2885                 ffdeltaquad_delay = toc;
2886                 %fprintf('tune FF delay = %.1f seconds\n',ffdeltaquad_delay);
2887                 % fprintf('Tune Done: %f \n',gettime-t00);
2888
2889                 % Output info to screen
2890                 set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
2891                 set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
2892                 %pause(0);
2893
2894                 FOFBStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2895                     getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2896                     getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2897                     getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2898                 for loop = 1:size(FOFBStatus,2)
2899                     if FOFBStatus(loop)==0
2900                         FOFBStatusStr(loop,:) = 'OFF ';
2901                     elseif FOFBStatus(loop)==1
2902                         FOFBStatusStr(loop,:) = 'ON  ';
2903                     elseif FOFBStatus(loop)==2
2904                         FOFBStatusStr(loop,:) = 'OPEN';
2905                     else
2906                         FOFBStatusStr(loop,:) = 'BAD ';
2907                     end
2908                 end
2909                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 %s',FOFBStatusStr(1,:)),'ForegroundColor',[0 0 0]);
2910                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 %s',FOFBStatusStr(2,:)),'ForegroundColor',[0 0 0]);
2911                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 %s',FOFBStatusStr(3,:)),'ForegroundColor',[0 0 0]);
2912                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 %s',FOFBStatusStr(4,:)),'ForegroundColor',[0 0 0]);
2913                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 %s',FOFBStatusStr(5,:)),'ForegroundColor',[0 0 0]);
2914                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 %s',FOFBStatusStr(6,:)),'ForegroundColor',[0 0 0]);
2915                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 %s',FOFBStatusStr(7,:)),'ForegroundColor',[0 0 0]);
2916                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 %s',FOFBStatusStr(8,:)),'ForegroundColor',[0 0 0]);
2917                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 %s',FOFBStatusStr(9,:)),'ForegroundColor',[0 0 0]);
2918                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 %s',FOFBStatusStr(10,:)),'ForegroundColor',[0 0 0]);
2919                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 %s',FOFBStatusStr(11,:)),'ForegroundColor',[0 0 0]);
2920                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 %s',FOFBStatusStr(12,:)),'ForegroundColor',[0 0 0]);
2921
2922
2923                 %fprintf('End of feedback operations: %f \n\n',gettime-t00);
2924
2925                 % Wait for next update time or stop request
2926                 while (gettime-t00) < LoopDelay
2927                     %disp('interval could be shorter')
2928                     pause(.05);
2929                     % Check if GUI has been closed
2930                     if isempty(gcbf)
2931                         FEEDBACK_STOP_FLAG = 1;
2932                         lasterr('SRCONTROL GUI DISAPPEARED!');
2933                         error('SRCONTROL GUI DISAPPEARED!');
2934                     end
2935
2936                     % Check if Stop button was pressed
2937                     if FEEDBACK_STOP_FLAG == 1
2938                         % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2939                         if getpv('SR01____FFBON__BC00')==1
2940                             disp('   Stopping Fast Orbit Feedback.');
2941                         end
2942                         setpv('SR01____FFBON__BC00',0);
2943                         pause(0.5);
2944                         setpv('SR01____FFBON__BC00',2);
2945                         break;
2946                     end
2947                 end
2948
2949
2950                 if FEEDBACK_STOP_FLAG == 1
2951                     % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2952                     if getpv('SR01____FFBON__BC00')==1
2953                         disp('   Stopping Fast Orbit Feedback.');
2954                     end
2955                     setpv('SR01____FFBON__BC00',0);
2956                     pause(0.5);
2957                     setpv('SR01____FFBON__BC00',2);
2958                     break;
2959                 end
2960
2961                 StartErrorTime = gettime;
2962
2963             catch
2964
2965                 fprintf('\n  %s \n',lasterr);
2966
2967                 % Quit if error exists for more than 20 seconds
2968                 if gettime-StartErrorTime>20 | FEEDBACK_STOP_FLAG==1
2969                     fprintf('%s  Orbit feedback stopped due to error condition. \n\n',datestr(now));
2970
2971                     %send alphapage to operator pager
2972                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2973                     FEEDBACK_STOP_FLAG = 1;
2974
2975                     setpv('SR_STATE', -5);
2976                     [StateNumber, StateString] = getsrstate;
2977                     if StateNumber >= 0
2978                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2979                     else
2980                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2981                     end
2982                 else
2983                     a = clock;
2984                     fprintf('   Orbit feedback was paused due to error condition (%s %d:%d:%.0f). \n', date, a(4), a(5), a(6));
2985                     fprintf('   Orbit feedback has automatically restarted and is running. \n\n');
2986                 end
2987
2988             end
2989
2990             if FEEDBACK_STOP_FLAG == 1
2991                 % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2992                 if getpv('SR01____FFBON__BC00')==1
2993                     disp('   Stopping Fast Orbit Feedback.');
2994                 end
2995                 setpv('SR01____FFBON__BC00',0);
2996                 pause(0.5);
2997                 setpv('SR01____FFBON__BC00',2);
2998                 break;
2999             end
3000
3001             %fprintf('End of feedback loop: %f \n\n',gettime-t00);
3002
3003             %pause(0);
3004
3005             % this loop delays turn on of Fast Feedback system
3006             if FBloopIter < 5
3007                 FBloopIter = FBloopIter + 1;
3008             end
3009
3010         end  % End of feedback loop
3011
3012
3013         % End feedback, reset all parameters
3014         try
3015
3016             % Enable buttons
3017             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','on');
3018             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','off');
3019             set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','on');
3020             set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','on');
3021             set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','on');
3022             set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','on');
3023             set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','on');
3024             set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','on');
3025             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','on');
3026             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','on');
3027             set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','on');
3028             set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','on');
3029             set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','on');
3030
3031             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = _____ mm'),'ForegroundColor',[0 0 0]);
3032             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = _____ mm'),'ForegroundColor',[0 0 0]);
3033
3034             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 ____'),'ForegroundColor',[0 0 0]);
3035             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 ____'),'ForegroundColor',[0 0 0]);
3036             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 ____'),'ForegroundColor',[0 0 0]);
3037             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 ____'),'ForegroundColor',[0 0 0]);
3038             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 ____'),'ForegroundColor',[0 0 0]);
3039             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 ____'),'ForegroundColor',[0 0 0]);
3040             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 ____'),'ForegroundColor',[0 0 0]);
3041             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 ____'),'ForegroundColor',[0 0 0]);
3042             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 ____'),'ForegroundColor',[0 0 0]);
3043             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 ____'),'ForegroundColor',[0 0 0]);
3044             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 ____'),'ForegroundColor',[0 0 0]);
3045             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 ____'),'ForegroundColor',[0 0 0]);
3046
3047             %pause(0);
3048
3049         catch
3050
3051             % GUI must have been closed
3052
3053         end
3054
3055
3056         % Reset Bergoz BPM time constant to whatever it was before feedback started
3057         fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
3058         setbpmtimeconstant(BPMtimeconstantOFB);
3059
3060
3061         a = clock;
3062         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
3063         [StateNumber, StateString] = getsrstate;
3064         if StateNumber >= 0
3065             setpv('SR_STATE',5.1);
3066             [StateNumber, StateString] = getsrstate;
3067             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
3068             fprintf('   ******************************\n');
3069             fprintf('   **  Orbit Feedback Stopped  **\n');
3070             fprintf('   ******************************\n\n');
3071         else
3072             [StateNumber, StateString] = getsrstate;
3073             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
3074             fprintf('   ****************************************\n');
3075             fprintf('   **  Problem With Slow Orbit Feedback  **\n');
3076             fprintf('   ****************************************\n\n');
3077         end
3078         set(0,'showhiddenhandles','off');
3079         pause(0);
3080
3081
3082     case 'FeedbackSetup'
3083         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
3084
3085         if InitFlag
3086
3087
3088             % Get the device lists from oscsinit and convert to srcontrol variables
3089             [HBPM, VBPM, HCM, VCM, HSV, VSV] = ocsinit('SOFB');
3090             Xivec = 1:HSV;
3091             Yivec = 1:VSV;
3092             BPMlist1 = HBPM.DeviceList;
3093             HCMlist1 = HCM.DeviceList;
3094             VCMlist1 = VCM.DeviceList;
3095
3096
3097             OCSx.BPM = getx(BPMlist1, 'struct');
3098             OCSx.CM = getsp('HCM', HCMlist1, 'struct');
3099             OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
3100             OCSx.NIter = 1;
3101             OCSx.SVDIndex = Xivec;
3102             OCSx.IncrementalFlag = 'No';
3103             OCSx.BPMWeight = {[]};
3104             OCSx.FitRF = 0;
3105             OCSy.BPM = gety(BPMlist1, 'struct');
3106             OCSy.CM = getsp('VCM', VCMlist1, 'struct');
3107             OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
3108             OCSy.NIter = 1;
3109             OCSy.SVDIndex = Yivec;
3110             OCSy.IncrementalFlag = 'No';
3111             OCSy.BPMWeight = {[]};
3112             OCSy.FitRF = 0;
3113
3114             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
3115             % do we need these Smat calls? %
3116             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
3117             SXmat = getrespmat(OCSx.BPM, OCSx.CM, 'numeric');
3118             SYmat = getrespmat(OCSy.BPM, OCSy.CM, 'numeric');
3119             % [OCSx, Sx, Ux, Vx] = orbitcorrectionmethods(OCSx, SXmat);
3120             % [OCSy, Sy, Uy, Vy] = orbitcorrectionmethods(OCSy, SYmat);
3121
3122             % initialize FFTypeFlag
3123             FFTypeFlag = 'Global';
3124
3125             % Fit decision comes from check box
3126             if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
3127                 OCSx.FitRF = 1;
3128                 Xivec = 1:HSV+1;
3129             end
3130
3131         else
3132
3133             % Get vectors
3134             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
3135             % the two lines below seem to fix BPMlist editing problem
3136             OCSx = FB.OCSx;
3137             OCSy = FB.OCSy;
3138             BPMlist1 = FB.BPMlist1;
3139             HCMlist1 = FB.HCMlist1;
3140             VCMlist1 = FB.VCMlist1;
3141             Xivec = FB.Xivec;
3142             Yivec = FB.Yivec;
3143             Xgoal = FB.OCSx.GoalOrbit;
3144             OCSx.GoalOrbit = Xgoal;
3145             Ygoal = FB.OCSy.GoalOrbit;
3146             OCSy.GoalOrbit = Ygoal;
3147             FFTypeFlag = FB.FFTypeFlag;
3148
3149
3150             % FF corrector magnet list - only channels which are blocked when FF is running should be
3151             % listed
3152             ListFF = [
3153                 4     2
3154                 4     8
3155                 5     1
3156                 5     7
3157 %               5     8 % IVID is using digital FF, i.e. FF algorithm does not block
3158 %               6     1 % other access to PVs
3159                 6     8
3160                 7     1
3161                 7     8
3162                 8     1
3163                 8     8
3164                 9     1
3165                 9     8
3166                 10    1
3167                 11    8
3168                 12    1];
3169             ElemFF = dev2elem('HCM',ListFF);
3170
3171
3172             % Add button to change #ivectors, cm, IDBPMs,
3173             EditFlag = 0;
3174             h_fig1 = figure;
3175             while EditFlag ~= 6
3176
3177                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
3178                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
3179
3180                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
3181                     DispOrbit = getdisp('BPMx', BPMlist1);
3182                     Sx = [Sx DispOrbit];
3183                 end
3184
3185                 Sx(isnan(Sx)) = 0;
3186                 Sy(isnan(Sy)) = 0;
3187
3188                 [Ux, SVx, Vx] = svd(Sx);
3189                 [Uy, SVy, Vy] = svd(Sy);
3190
3191
3192                 % Remove singular values greater than the actual number of singular values
3193                 i = find(Xivec>length(diag(SVx)));
3194                 if ~isempty(i)
3195                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
3196                     pause(0);
3197                     Xivec(i) = [];
3198                 end
3199                 i = find(Yivec>length(diag(SVy)));
3200                 if ~isempty(i)
3201                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
3202                     pause(0);
3203                     Yivec(i) = [];
3204                 end
3205
3206
3207                 Ax = Sx*Vx(:,Xivec);
3208                 Tx = inv(Ax'*Ax)*Ax';
3209
3210                 Ay = Sy*Vy(:,Yivec);
3211                 Ty = inv(Ay'*Ay)*Ay';
3212
3213                 figure(h_fig1);
3214                 subplot(2,1,1);
3215                 semilogy(diag(SVx),'b');
3216                 hold on;
3217                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
3218                 ylabel('Horizontal');
3219                 title('Response Matrix Singular Values');
3220                 hold off;
3221                 subplot(2,1,2);
3222                 semilogy(diag(SVy),'b');
3223                 hold on;
3224                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
3225                 xlabel('Singular Value Number');
3226                 ylabel('Vertical');
3227                 hold off;
3228                 drawnow;
3229
3230                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List', ...
3231                     'BPM List','Change the Goal Orbit','Continue');
3232
3233                 if EditFlag == 1
3234                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
3235                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
3236                     titlestr='SVD Orbit Feedback';
3237                     lineNo=1;
3238                     answer=inputdlg(prompt,titlestr,lineNo,def);
3239                     if ~isempty(answer)
3240                         XivecNew = fix(str2num(answer{1}));
3241                         if isempty(XivecNew)
3242                             disp('   Horizontal E-vector cannot be empty.  No change made.');
3243                         else
3244                             if any(XivecNew<=0) | max(XivecNew)>length(diag(SVx))
3245                                 disp('   Error reading horizontal E-vector.  No change made.');
3246                             else
3247                                 Xivec = XivecNew;
3248                             end
3249                         end
3250                         YivecNew = fix(str2num(answer{2}));
3251                         if isempty(YivecNew)
3252                             disp('   Vertical E-vector cannot be empty.  No change made.');
3253                         else
3254                             if any(YivecNew<=0) | max(YivecNew)>length(diag(SVy))
3255                                 disp('   Error reading vertical E-vector.  No change made.');
3256                             else
3257                                 Yivec = YivecNew;
3258                             end
3259                         end
3260                     end
3261                 end
3262
3263                 if EditFlag == 2
3264                     List= getlist('HCM','Trim');
3265                     CheckList = zeros(96,1);
3266                     Elem = dev2elem('HCM', HCMlist1);
3267                     CheckList(Elem) = ones(size(Elem));
3268                     CheckList = CheckList(dev2elem('HCM',List));
3269
3270                     % Remove FF corrrectors
3271                     %           Elem = dev2elem('HCM',List);
3272                     %           for j = length(ElemFF):-1:1
3273                     %              i = find(Elem==ElemFF(j));
3274                     %              Elem(i,:) = [];
3275                     %              List(i,:) = [];
3276                     %              CheckList(i,:) = [];
3277                     %           end
3278
3279                     newList = editlist(List, 'HCMtrim', CheckList);
3280
3281                     if isempty(newList)
3282                         fprintf('   WARNING: Horizontal corrector magnet list is empty!\n');
3283                         HCMlist1 = newList;
3284                     else
3285                         HCMlist1 = newList;
3286                     end
3287                     OCSx.CM.DeviceList = HCMlist1;
3288                 end
3289
3290                 if EditFlag == 3
3291                     List = getlist('VCM','Trim');
3292                     CheckList = zeros(96,1);
3293                     Elem = dev2elem('VCM', VCMlist1);
3294                     CheckList(Elem) = ones(size(Elem));
3295                     CheckList = CheckList(dev2elem('VCM',List));
3296
3297                     % Remove FF corrrectors
3298                     %           Elem = dev2elem('VCM',List);
3299                     %           for j = length(ElemFF):-1:1
3300                     %              i = find(Elem==ElemFF(j));
3301                     %              Elem(i,:) = [];
3302                     %              List(i,:) = [];
3303                     %              CheckList(i,:) = [];
3304                     %           end
3305
3306                     newList = editlist(List, 'VCMtrim', CheckList);
3307
3308                     if isempty(newList)
3309                         fprintf('   WARNING: Vertical corrector magnet list is empty!\n');
3310                         VCMlist1 = newList;
3311                     else
3312                         VCMlist1 = newList;
3313                     end
3314                     OCSy.CM.DeviceList = VCMlist1;
3315                 end
3316
3317                 if EditFlag == 4
3318                     ListOld = BPMlist1;
3319                     XgoalOld = Xgoal;
3320                     YgoalOld = Ygoal;
3321
3322                     % Full BPM list
3323                     List = getbpmlist('Bergoz');
3324
3325                     CheckList = zeros(size(List,1),1);
3326                     if ~isempty(BPMlist1)
3327                         for i = 1:size(List,1)
3328                             k = find(List(i,1)==BPMlist1(:,1));
3329                             l = find(List(i,2)==BPMlist1(k,2));
3330
3331                             if isempty(k) || isempty(l)
3332                                 % Item not in list
3333                             else
3334                                 CheckList(i) = 1;
3335                             end
3336                         end
3337                     end
3338
3339                     newList = editlist(List, 'BPM', CheckList);
3340                     if isempty(newList)
3341                         fprintf('   BPM list cannot be empty.  No change made.\n');
3342                     else
3343                         BPMlist1 = newList;
3344                     end
3345
3346                     % Set the goal orbit to the golden orbit
3347                     Xgoal = getgolden('BPMx', BPMlist1);
3348                     Ygoal = getgolden('BPMy', BPMlist1);
3349
3350
3351                     % If a new BPM is added, then set the goal orbit to the golden orbit
3352                     for i = 1:size(BPMlist1,1)
3353
3354                         % Is it a new BPM?
3355                         k = find(BPMlist1(i,1)==ListOld(:,1));
3356                         l = find(BPMlist1(i,2)==ListOld(k,2));
3357
3358                         if isempty(k) || isempty(l)
3359                             % New BPM
3360                         else
3361                             % Use the old value for old BPM
3362                             Xgoal(i) = XgoalOld(k(l));
3363                             Ygoal(i) = YgoalOld(k(l));
3364                         end
3365                     end
3366                     OCSx.BPM.DeviceList = BPMlist1;
3367                     OCSy.BPM.DeviceList = BPMlist1;
3368                     OCSx.GoalOrbit = Xgoal;
3369                     OCSy.GoalOrbit = Ygoal;
3370                 end
3371
3372                 if EditFlag == 5
3373                     ChangeList = editlist2(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
3374
3375                     for i = 1:size(ChangeList,1)
3376
3377                         k = find(ChangeList(i,1)==BPMlist1(:,1));
3378                         l = find(ChangeList(i,2)==BPMlist1(k,2));
3379
3380                         prompt={sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
3381                         def={sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
3382                         titlestr='CHANGE THE GOAL ORBIT';
3383                         lineNo=1;
3384                         answer = inputdlg(prompt, titlestr, lineNo, def);
3385
3386                         if isempty(answer)
3387                             % No change
3388                             fprintf('   No change was made to the golden orbit.\n');
3389                         else
3390                             Xgoalnew = str2num(answer{1});
3391                             if isempty(Xgoalnew)
3392                                 fprintf('   No change was made to the horizontal golden orbit.\n');
3393                             else
3394                                 Xgoal(k(l)) = Xgoalnew;
3395                             end
3396
3397                             Ygoalnew = str2num(answer{2});
3398                             if isempty(Ygoalnew)
3399                                 fprintf('   No change was made to the vertical golden orbit.\n');
3400                             else
3401                                 Ygoal(k(l)) = Ygoalnew;
3402                             end
3403                         end
3404                     end
3405                     if ~isempty(ChangeList)
3406                         fprintf('   Note:  Changing the goal orbit for "Slow Orbit Feedback" does not change the goal orbit for "Orbit Correction."\n');
3407                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
3408                     end
3409                     OCSx.GoalOrbit = Xgoal;
3410                     OCSy.GoalOrbit = Ygoal;
3411                 end
3412
3413 %                 if EditFlag == 6
3414 %                     FFTypeFlag = questdlg(sprintf('Do you want to use a fully local or a combined local/global compensation of IDs? (nuy=9.2 only)'),'Tune FF','Local','Global', 'Global');
3415 %                     if strcmp(FFTypeFlag,'Local')
3416 %                         disp(['   The tune FF will use 8 local quadrupoles to compensate beta beating and tune shift']);
3417 %                         disp(['   from each ID.']);
3418 %                     elseif strcmp(FFTypeFlag,'Global')
3419 %                         disp(['   The tune FF will use 4 local quadrupoles to compensate beta beating and all QF+QD']);
3420 %                         disp(['   to compensate tune shift from each ID.']);
3421 %                     end
3422 %                 end
3423
3424             end
3425             close(h_fig1);
3426         end
3427
3428         % Save vectors
3429         FB.Xivec = Xivec;
3430         FB.Yivec = Yivec;
3431         FB.HCMlist1 = HCMlist1;
3432         FB.VCMlist1 = VCMlist1;
3433         FB.BPMlist1 = BPMlist1;
3434
3435         OCSx.SVDIndex = Xivec;
3436         OCSy.SVDIndex = Yivec;
3437         FB.OCSx = OCSx;
3438         FB.OCSy = OCSy;
3439
3440         FB.FFTypeFlag = FFTypeFlag;
3441         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata',FB);
3442
3443
3444     case 'FastFeedbackSetup'
3445
3446         InitFlag = Input2;
3447
3448         if InitFlag
3449             FOFBFreq = 1000;
3450             % user operations 9/14-10/17/04: P=0.5, I=120, D=0.0015 (for both planes)
3451             % below are known good values for user ops as of 8-1-05
3452             HorP = 2;
3453             HorI = 300;
3454             HorD = 0.002;
3455             VertP = 1;
3456             VertI = 100;
3457             VertD = 0.0015;
3458
3459             % this initial set is now done in hwinit.m because it's not a good idea to set anything when srcontrol is launched
3460             % try
3461             %     setsp('SR01____FFBFREQAC00', FOFBFreq); % set freq
3462             %     write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3463             % catch
3464             %     disp('   Trouble setting Fast Orbit Feedback parameters!');
3465             % end
3466
3467         else
3468             % Get vectors
3469             FOFB = get(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata');
3470             FOFBFreq = FOFB.FOFBFreq;
3471             HorP  = FOFB.HorP;
3472             HorI  = FOFB.HorI;
3473             HorD  = FOFB.HorD;
3474             VertP = FOFB.VertP;
3475             VertI = FOFB.VertI;
3476             VertD = FOFB.VertD;
3477
3478             % Add button to change #ivectors, CMs, IDBPMs,
3479             EditFlag = 0;
3480             %h_fig1 = figure;
3481             while EditFlag ~= 3
3482
3483                 %EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'HCM List', 'VCM List', ...
3484                 %   'IDBPM List', 'BBPM List', 'Continue');
3485                 % Use menu below until other FFB config routines work (then also uncomment options 3,4,5,6 below)
3486                 EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'Continue');
3487
3488                 if EditFlag == 1
3489                     % change rate
3490
3491                     prompt={'Enter the desired Fast Feedback Frequency (1-1000 Hz)'};
3492                     def={num2str(FOFBFreq)};
3493                     titlestr='Fast Feedback Setup';
3494                     lineNo=1;
3495                     answer=inputdlg(prompt,titlestr,lineNo,def);
3496                     if ~isempty(answer)
3497                         FOFBFreq = fix(str2num(answer{1}));
3498                         if isempty(FOFBFreq)
3499                             disp('   Frequency value cannot be empty.  No change made.');
3500                             FOFBFreq = getsp('SR01____FFBFREQAC00');
3501                         else
3502                             if FOFBFreq < 1 | FOFBFreq > 1000
3503                                 disp('   Frequency must be between 1 and 1000 Hz.  No change made.');
3504                                 FOFBFreq = getsp('SR01____FFBFREQAC00');
3505                             end
3506                         end
3507                         setsp('SR01____FFBFREQAC00',FOFBFreq); % change freq
3508                         pause(0.5);
3509                         fprintf('   Fast orbit feedback frequency is running at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
3510                     else
3511                         FOFBFreq = getsp('SR01____FFBFREQAC00');
3512                     end
3513                 end
3514
3515                 if EditFlag == 2
3516                     % edit  PIDs
3517                     % User defaults are HorP=2, HorI=300, HorD=0.002, VertP=1, VertI=100, VertD=0.0015
3518                     prompt={'P horizontal', 'I horizontal', 'D horizontal', 'P vertical', 'I vertical', 'D vertical'};
3519                     def={num2str(HorP), num2str(HorI), num2str(HorD), num2str(VertP), num2str(VertI), num2str(VertD)};
3520                     titlestr='Fast Feedback PID Setup';
3521                     lineNo=1;
3522                     answer=inputdlg(prompt,titlestr,lineNo,def);
3523                     if ~isempty(answer)
3524                         HorPnewnum = str2num(answer{1});
3525                         if isempty(HorPnewnum)
3526                             disp('   HorP value cannot be empty.  No change made.');
3527                         else
3528                             HorP = HorPnewnum;
3529                         end
3530                         HorInewnum = str2num(answer{2});
3531                         if isempty(HorInewnum)
3532                             disp('   HorI value cannot be empty.  No change made.');
3533                         else
3534                             HorI = HorInewnum;
3535                         end
3536                         HorDnewnum = str2num(answer{3});
3537                         if isempty(HorDnewnum)
3538                             disp('   HorD value cannot be empty.  No change made.');
3539                         else
3540                             HorD = HorDnewnum;
3541                         end
3542                         VertPnewnum = str2num(answer{4});
3543                         if isempty(VertPnewnum)
3544                             disp('   VertP value cannot be empty.  No change made.');
3545                         else
3546                             VertP = VertPnewnum;
3547                         end
3548                         VertInewnum = str2num(answer{5});
3549                         if isempty(VertInewnum)
3550                             disp('   VertI value cannot be empty.  No change made.');
3551                         else
3552                             VertI = VertInewnum;
3553                         end
3554                         VertDnewnum = str2num(answer{6});
3555                         if isempty(VertDnewnum)
3556                             disp('   VertD value cannot be empty.  No change made.');
3557                         else
3558                             VertD = VertDnewnum;
3559                         end
3560
3561                         try
3562                             write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3563                             fprintf('   Setting FFB gains to Horizontal P=%.2f, I=%.1f, D=%.4f;  Vertical P=%.2f, I=%.1f, D=%.4f\n', HorP, HorI, HorD, VertP, VertI, VertD);
3564                         catch
3565                             disp('   Trouble setting Fast Orbit Feedback parameters!');
3566                         end
3567                     end
3568                 end
3569
3570                 %if EditFlag == 3
3571                 %   disp('   This function not yet available.');
3572                 %   % change HCM List
3573                 %end
3574                 %
3575                 %if EditFlag == 4
3576                 %   disp('   This function not yet available.');
3577                 %   % change VCM List
3578                 %end
3579                 %
3580                 %if EditFlag == 5
3581                 %   disp('   This function not yet available.');
3582                 %   % change IDBPM List
3583                 %end
3584                 %
3585                 %if EditFlag == 6
3586                 %   disp('   This function not yet available.');
3587                 %   % change BBPM List
3588                 %end
3589
3590             end
3591             %close(h_fig1);
3592         end
3593
3594         % Save vectors
3595         FOFB.FOFBFreq = FOFBFreq;
3596         FOFB.HorP = HorP;
3597         FOFB.HorI = HorI;
3598         FOFB.HorD = HorD;
3599         FOFB.VertP = VertP;
3600         FOFB.VertI = VertI;
3601         FOFB.VertD = VertD;
3602         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata',FOFB);
3603
3604     otherwise
3605         fprintf('   No action for %s.\n', action);
3606 end   % end case