Description of srcontrol5_including_FOFB_indicators
Home > ALS > StorageRing > srcontrol5_including_FOFB_indicators.m
srcontrol5_including_FOFB_indicators
PURPOSE
srcontrol5
SYNOPSIS
function srcontrol5(action, Input2, Input3)
DESCRIPTION
 srcontrol5
 Storage ring control program
 This program controls all storage ring magnets, performs orbit feedback and
 tune feedforward and helps to diagnose problems in routine user operation
 of the ALS storage ring. It includes a gui to simplify the use of this
 program.
 It was originally programmed by Greg Portmann (until December 2000) with input
 from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
 and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
 The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
 Christoph Steier, July 2002
 SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
 Tom Scarvie, April 2005
CROSS-REFERENCE INFORMATION
This function calls:
bend2gev BEND2GEV - Compute the energy based on the ramp tables
checksrmags CHECKSRMAGS - Check SR power supplies against a lattice file
checksrorbit ErrorNums =checksrorbit(Sector, BPMxtolerance [.015 mm], [BPMytolerance [.015 mm]])
gap2tune GAP2TUNE - Computes the vertical tune shift for a insertion device gap change.
gaplimit [GapMin, GapMax] = gaplimit(ID_Number);
getff function [FFEnableBM, FFEnableBC, GapEnableBM, GapEnableBC, Sector] = getff(Sector)
getid GETID - Get the insertion device position, velocity, run flag, and user requested gap
getsrstate [StateNumber, StateString] = getsrstate
set_alarmhandler_AHU_thresholds_inject function set_alarmhandler_AHU_thresholds_inject
set_alarmhandler_thresholds set_alarmhandler_thresholds
set_alarmhandler_thresholds_new set_alarmhandler_thresholds_new
setbpmtimeconstant SETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
setbumps SETBUMPS - Make a straight section bump
setff function setff(Sector, FFEnableBC, GapEnableBC)
setid SETID - Set the insertion device vertical gap
setsrstatechannels
shift2tune SHIFT2TUNE - Computes the horizontal tune shift for a EPU gap and horizontal shift
srcycle SRCYCLE - Storage ring cycle
srramp SRRAMP - Ramp the storage ring energy
write_goldenorbit_ffb function write_goldenorbit_ffb
write_goldenorbit_ffb_2planes WRITE_GOLDENORBIT_FFTB_2PLANES - Sets the BPM setpoints which are used by the fast feedback system
This function is called by:
SOURCE CODE
function srcontrol5(action, Input2, Input3)
% srcontrol5
% Storage ring control program
%
% This program controls all storage ring magnets, performs orbit feedback and
% tune feedforward and helps to diagnose problems in routine user operation
% of the ALS storage ring. It includes a gui to simplify the use of this
% program.
%
% It was originally programmed by Greg Portmann (until December 2000) with input
% from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
% and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
%
% The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
%
% Christoph Steier, July 2002
%
% SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
%
% Tom Scarvie, April 2005
% known bugs/problems (May 2001):
% - IDBPM averaging might be a bit too long for orbit feedback
%        solved after Superbend shutdown ... Instead of averaging, digital low pass filters are used
% - gap2tune does not give correct answers for wiggler and potentially other IDs -> orbit feedback
%        seems to be OK for other IDs, has been corrected for wiggler (fit to insertion device
%        compensation table)
% - chicanes do not work in orbit feedback
%        solved. One problem was that orbit response matrizes were mis-scaled by factor of two.
%        Second problem was different time constant of power supply control. Solved by moving controls
%        of center chicanes to cPCI (and magnets are fast, hysteresis free, aircore coils).
%        Center chicane in sector 4 is now routinely used in orbit feedback. Sector 11 to follow soon.
% - zero reading of ID gap dumps beam
%        solved in srcontrol5, still a problem in srcontrol5_hightune (but that routine has to be completely
%        rewritten because of all recent changes to srcontrol5, anyhow). For gap readings below the minimum
%        allowed gap for a device, the tune feedforward disables itself.
% - cycling of lattice causes frequent power supply failures
%        solved by changing the cycling procedure. 1.5 GeV operation is now on the upper hysteresis branch
%        as was the 1.9 GeV injection lattice before.
% - frequently stalled data in IDBPM readout
%        solved with new BPM readouts and digital filtering. Seems to have been a resolution problem
%        of the digital averaging algorithm.
% - magnet ramp tables are not in perfect agreement with magnetic measurements
%        Does not appear to be a serious problem. Superbends are slightly out of sync with other magnets,
%        but this does not cause any negative effects while ramping.
% - no good way to operate with injection at 1.5 GeV and storage energy below that
%        There now is a reasonable way to inject at 1.5 GeV and ramp down to lower storage energy. But
%        it has to be tested again after implementing new (and more) chicanes ...
% revision history
% 2001-05-10, Christoph Steier
% check whether readback from insertion device is significantly (more than 1 mm) below minimum
% gap, to avoid false zero readings of insertion device gaps to cause the tune feed forward
% to implement false huge correction (and dump the beam). If the insertion device gap readbacks
% gets more than 1 mm below the nominal minimum gap, the routine now assumes the insertion device
% to be open.
%
% 2001-08-30 and during Superbend commissioning, Christoph Steier, Tom Scarvie, Winni Decking
% various changes have been made to incorporate the Superbends and some other new equipment
% installed in the Superbend shutdown. This included some changes to programs being called by srcontrol
% (like srload, srsave, srcycle, srramp, ...). The main changes within srcontrol were in the orbit
% correction and slow orbit feedback routines (incorporating frequency feedback, ...)
%
% 2002-05-04, Christoph Steier
% added new IDBPMs, modified orbit feedback to use trim DACs, removed LSB toggling in vertical
% orbit feedback, ...
%
% 2002-07-29, T.Scarvie
% added check of CM trim currents to warn of problems that might rail the orbit feedback
%
% 2002-07-31, Christoph Steier
% increased the gain of the RF frequency feedback from 1/50 of the gain of the horizontal
% orbit feedback to 1/20. Reason was that the frequency feedback was reacting a bit too slow if all
% insertion device gaps are closed at once at high speed at the beginning of a fill.
%
% 2002-08-05, C.Steier, T.Scarvie
% Added conditional to reduce orbit feedback gain if running in two-bunch mode
%
% 2003-06-02, T.Scarvie
% Added loop inside orbit feedback to reset the SR11 chicane M1 and M2 motors every 20s to combat drift problem
%
% 2003-06-18, C. Steier
% Disabled loop to periodically reset chicane in SR11. Al Robb replaced power supply, seems to be no problem anymore.
%
% 2004-05-10, C. Steier
% The list of all BBPMs is now set up automatically be calling getlist('BBPMx'). This way, new BBPMs have to be added
% at fewer places in the software. It should now be sufficient to modify getlist and run the orbit response matrix
% rountine (getsmat) once to enable use of the new BBPMs.
%
% 2004-05-14, C. Steier
% Modified parameters for ramprate reduction (in srramp and here). Previous parameters were slightly too
% cautious. Increased initial slow ramprate to 0.4 A/s.
%
% 2004-05-14, C. Steier
% Incorporated insertion device compensation schemes for nu_y = 9.2 lattice.
%
% 2004-06-14, T.Scarvie
% Added controls for fast orbit feedback
%
% 2004-06-21, C. Steier
% Added tune feedforward (in the global tune compensation scheme for the nu_y=9.2 lattice) for the shift
% dependent tune shift of the EPUs, as well as a skew quadrupole feedforward for the EPU im sector 11
% (both only active in parallel mode so far).
%
% 2005-02-13, T.Scarvie
% Separated horizontal and vertical planes for setting Fast Feedback PIDs
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NOTES for conversion to new Middle Layer %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% We never use the gap and bump control flags - the radio buttons have been disabled -
%        should we try to keep the functionality?
%
% remove handle globals
% set(0,'showhiddenhandles','on'); what does this do?
% grampbsc -> should be handled by new srramp (which uses k-values)
% checksrmags
% checksrorbit(...)
% getdcct
% setbpmtimeconstant
% getsmatelements
% Chicane trims are now part of the corrector family
% getname('IDrunflag',...) family name change
% write_goldenorbit_ffb, write_goldenorbit_ffb2
% For the compiler
%#function goldenpage
%#function setoperationalmode
% Check if the AO exists
checkforao;
%%%%%%%%%%%%%%
% Initialize %
%%%%%%%%%%%%%%
global FEEDBACK_STOP_FLAG
SR_Mode = getfamilydata('OperationalMode');
SR_GEV = getfamilydata('Energy');
BSCramprate = getfamilydata('BSCRampRate');
if isnan(BSCramprate) | isempty(BSCramprate)
    BSCramprate = 0.4;
    setfamilydata(BSCramprate, 'BSCRampRate');
end
if nargin < 1
    action = 'Initialize';
end
if nargin < 2
    Input2 = 0;
end
if nargin < 3
    Input3 = 0;
end
if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
    FOFBcheckboxVal = 0;
else
    FOFBcheckboxVal = 1;
end
%%%%%%%%%%%%%%%%
% Main Program %
%%%%%%%%%%%%%%%%
switch(action)
    case 'StopOrbitFeedback'
        FEEDBACK_STOP_FLAG = 1;
    case 'Initialize'
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % GUI
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        ButtonWidth = 200;
        ButtonHeight  = 25;
        Offset1 = 8*25+12 + 47 + 25+25;
        Offset2 = 47+25+25;
        Offset3 = 45+25;
        Offset4 = 1;
        Offset5 = 30;
        FigWidth = ButtonWidth+6;
        FigHeight  = 3+9*(ButtonHeight+6)+24+Offset1;
        ButtonWidth = 200-6;
        % Change figure position
        set(0,'Units','pixels');
        p=get(0,'screensize');
        h0 = figure( ...
            'Color',[0.8 0.8 0.8], ...
            'HandleVisibility','Off', ...
            'Interruptible', 'on', ...
            'MenuBar','none', ...
            'Name','ALS SR CONTROL', ...
            'NumberTitle','off', ...
            'Units','pixels', ...
            'Position',[30 p(4)-FigHeight-40 FigWidth FigHeight+Offset5], ...
            'Resize','off', ...
            'Tag','SRCTRLFig1');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'FontWeight','Bold', ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+8*(ButtonHeight+3)+19+19+8+Offset1  ButtonWidth 20+Offset5], ...
            'Style','text', ...
            'String','', ...
            'Tag','SRCTRLTitle');
        % Frame Box I
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+3*(ButtonHeight+3)+Offset1-3+Offset5 ButtonWidth+6 7*ButtonHeight+18], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+9*(ButtonHeight+3)+Offset1  ButtonWidth 15+Offset5], ...
            'Style','text', ...
            'String','Lattice Setup Functions');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Cycle'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+8*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Cycle SR Lattice', ...
            'Tag','SRCTRLButton1');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Injection'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+7*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Injection', ...
            'Tag','SRCTRLButton2');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Production'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+6*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String',['Production'], ...
            'Tag','SRCTRLButton3');
        h1 = uicontrol('Parent',h0, ...
            'Callback',[...
            'fprintf(''\n'');' ...
            'disp([''   **********************************************'']);', ...
            'disp([''   **  Changing Storage Ring Operational Mode  **'']);', ...
            'disp([''   **********************************************'']);', ...
            'setoperationalmode;', ...
            'srcontrol5(''CheckInputs'');', ...
            'disp([''   ****************************'']);', ...
            'disp([''   **  Mode Change Complete  **'']);', ...
            'disp([''   ****************************'']);', ...
            'fprintf(''\n'');'], ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+5*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'Value',1, ...
            'String','Change Operational Mode', ...
            'Tag','SRCTRLButtonChangeMode');
        h1 = uicontrol(...
            'Parent',h0, ...
            'Callback', [...
            'srcontrol5(''CheckInputs'');',...
            'srcontrol5(''SRState'');'], ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+4*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Check For Problems', ...
            'Tag','SRCTRLButtonSRState');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs''); goldenpage;', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+3*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Golden Page', ...
            'Tag','SRCTRLButtonGoldenPage');
        % Frame Box II
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+9*(ButtonHeight+3)-29+Offset2+Offset5 ButtonWidth+6 2*ButtonHeight+15], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+10*(ButtonHeight+3)-10+Offset2 ButtonWidth .6*ButtonHeight+Offset5], ...
            'String','Global/Local Orbit Correction', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''OrbitCorrection'');', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+9*(ButtonHeight+3)-6+Offset2+Offset5 ButtonWidth ButtonHeight], ...
            'String','Correct Global Orbit w/ IDBPMs', ...
            'Tag','SRCTRLButtonOrbitCorrection');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''OrbitCorrectionSetup'',1);', ...
            'callback','srcontrol5(''OrbitCorrectionSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[6 9*(ButtonHeight+3)-22+Offset2+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Edit IDBPM, CM, & Local Bump Lists', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonOrbitCorrectionSetup');
        % Frame Box III
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 1*(ButtonHeight)+Offset3+Offset5-38 ButtonWidth+6 8*ButtonHeight+61], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+9*(ButtonHeight+3)+Offset3-25 ButtonWidth .55*ButtonHeight+Offset5], ...
            'String','Orbit Feedback', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+8*(ButtonHeight+3)+Offset3-18+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Slow Orbit Correction', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxSOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+7*(ButtonHeight+3)+Offset3-9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Fast Orbit Correction', ...
            'Style','checkbox', ...
            'Value',FOFBcheckboxVal,...
            'Tag','SRCTRLCheckboxFOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+6*(ButtonHeight+3)+Offset3+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct ID Tune Shift  ', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxTune');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+5*(ButtonHeight+3)+Offset3+9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct RF Frequency', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxRF');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''Feedback'');', ...
            'Enable','on', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[8 3+5*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Start FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStart');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''StopOrbitFeedback'');pause(0);', ...
            'Enable','off', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[.5*FigWidth+3 3+5*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Stop FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStop');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[14 4*(ButtonHeight)+Offset3+Offset5-3 ButtonWidth-14 .75*ButtonHeight], ...
            'String','Horizontal RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHorizontal');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[26 3+3.5*(ButtonHeight)+16+Offset3-25+Offset5 ButtonWidth-26 .75*ButtonHeight], ...
            'String','Vertical RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextVertical');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FeedbackSetup'',1);', ...
            'callback','srcontrol5(''FeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 3+3.5*(ButtonHeight)+.5+Offset3-25+Offset5 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit SOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFeedbackSetup');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','01 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB01');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','02 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB02');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','03 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB03');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','04 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB04');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','05 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB05');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','06 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB06');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','07 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB07');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','08 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB08');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','09 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB09');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','10 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB10');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','11 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB11');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','12 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB12');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FastFeedbackSetup'',1);', ...
            'callback','srcontrol5(''FastFeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 1*(ButtonHeight)+Offset3-3 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit FOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFastFeedbackSetup');
        % Frame Box IV
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+ButtonHeight+Offset4-14+Offset5 ButtonWidth+6 ButtonHeight+12], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+1.75*ButtonHeight+5+Offset4-21+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Storage Ring State', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHeader');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''CheckInputs'');', ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ForegroundColor','b', ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+ButtonHeight+6+3+2+Offset4-22+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','   ', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextInformation');
        % Frame Box "Close"
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 8 ButtonWidth+6 ButtonHeight+8], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'Callback','close(gcbf);', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 13 ButtonWidth ButtonHeight], ...
            'String','Close', ...
            'Tag','SRCTRLClose');
        % Update database channels
        setsrstatechannels;
        if nargout > 0
            fig = h0;
        end
    case 'Cycle'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        disp('   **************************');
        disp('   **  Storage Ring Cycle  **');
        disp('   **************************');
        a = clock; fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        BSCFlag = questdlg(sprintf('Cycle Superbend Magnets?'),'SR Cycle','Yes','No','No');
        %if strcmp(BSCFlag,'No')
        %    disp(['   ** Superbends will not be cycled. **']);
        %else
        %    disp(['   ** Superbends will be cycled during the second mini-cycle only. **']);
        %end
        ChicSQFlag = questdlg(sprintf('Cycle chicanes and skew quads and home motor chicanes?'),'SR Cycle','Yes','No','No');
        %if strcmp(ChicSQFlag,'No')
        %    disp(['   ** Chicanes and skew quads will not be cycled; motor chicanes will not be homed. **']);
        %else
        %    disp(['   ** Chicanes and skew quads will be cycled; motor chicanes will be homed. **']);
        %end
        StartFlag = questdlg(sprintf('Start %.1f GeV Cycle?',SR_GEV),'SR Cycle','Yes','No','No');
        if strcmp(StartFlag,'No')
            disp(['   ***************************']);
            disp(['   **    Cycle  Canceled    **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        end
        try
            if GapFlag
                % Make sure that the gaps are open with FF off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open.');
                    disp('   Opening all gaps at maximum speed.');
                    setff([], 1, 0);
                    disp('   Gap control disabled.');
                    disp('   Feed forward enabled.');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened.');
                    disp('   Feed forward and gap control disabled.');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled.');
                end
            else
                disp('   Feed forward and gap control disabled.');
            end
            setff([], 0, 0);
            pause(1);
            srcycle(BSCFlag, ChicSQFlag);
            setpv('SR_STATE',1);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Cycle failed due to error condition! \n\n');
            setpv('SR_STATE',-1);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp('   **********************************************');
            disp('   **  SR Cycle complete, ready for injection  **');
            disp('   **********************************************'); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp('   **********************************');
            disp('   **  Problem cycling SR lattice  **');
            disp('   **********************************'); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
    case 'Injection'
        AD = getad;
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            fprintf('   ***************************************************\n');
            fprintf('   **  Setup For %.2f GeV Injection (with ramping)  **\n', getfamilydata('InjectionEnergy'));
            fprintf('   ***************************************************\n');
            set_alarmhandler_AHU_thresholds_inject;
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',getfamilydata('InjectionEnergy')),'Injection Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            fprintf('   *************************************************\n');
            fprintf('   **  Setup For On Energy Injection at %.2f GeV  **\n', SR_GEV);
            fprintf('   *************************************************\n');
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',SR_GEV),'Injection Setup','Yes','Cancel','Cancel');
        end
        if strcmp(StartFlag,'Cancel')
            disp(['   ********************************']);
            disp(['   **  Injection Setup Canceled  **']);
            disp(['   ********************************']);
            set_alarmhandler_thresholds;
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                setff([],1,0);
                disp('   Gap control disabled');
                disp('   Feed forward enabled');
                pause(1);
                % Set IDs at max velocity w/ velocity profile off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    disp('   Opening all gaps');
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                end
                disp('   Gaps are open');
                disp('   Feed forward and gap control disabled');
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            if (AD.Energy-AD.InjectionEnergy) > 0.05
                % Ramp down to Injection Energy
                ErrorFlag = srramp('Injection');
                if ErrorFlag
                    error('Superbends over temperature.');
                end
                a = clock; fprintf('   %s %d:%d:%.0f\n\n',date, a(4), a(5), a(6));
            elseif (AD.Energy-AD.InjectionEnergy) < -0.05
                % first load injection lattice, then ramp to 1.9 GeV and back to 1.5 GeV to get onto same hysteresis branch
                srload('Injection');
                % load 1.9 GeV lattice
                tempfilename = sprintf('%s19nuy9prod.mat', getfamilydata('Directory','OpsData'));
                srload(tempfilename);
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                pause(5);
            end
            srload('Injection');
            setpv('SR_STATE',2);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Injection lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-2);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            if AD.Energy <= 1.5
                disp(['   *******************************************************************************']);
                disp(['   **  Function complete:  the storage ring is setup for injection at ',sprintf('%.2f',SR_GEV),' GeV  **']);
                disp(['   *******************************************************************************']);
                fprintf('\n');
            else
                fprintf('   **********************************************************************************************\n');
                fprintf('   **  Function complete:  the storage ring is setup for injection at %.2f GeV (upper branch)  **\n', getfamilydata('InjectionEnergy'));
                fprintf('   **********************************************************************************************\n');
                fprintf('\n');
            end
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   ************************************']);
            disp(['   **  Problem with injection setup  **']);
            disp(['   ************************************']);
            fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        %soundchord;
        setfamilydata(0.8, 'BSCRampRate');
    case 'Production'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        AD=getad;
        fprintf('\n');
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            disp('   ********************************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation (with ramping)  **',SR_GEV));
            disp('   ********************************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            disp('   *****************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation  **',SR_GEV));
            disp('   *****************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Yes','Cancel','Cancel');
        end
        if strcmp(StartFlag,'Cancel')
            disp(['   ***************************']);
            disp(['   **  User Setup Canceled  **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                % Make sure that the gaps are open
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open');
                    disp('   Opening all gaps at maximum speed');
                    setff([], 1, 0);
                    disp('   Gap control disabled');
                    disp('   Feed forward enabled');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened');
                    disp('   Feed forward and gap control disabled');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled');
                end
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            % Ramp up to the production lattice
            ErrorFlag = srramp('Production');
            if ErrorFlag
                error('Superbends over temperature.');
            end
            a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            srload('Production');
            if GapFlag
                setff([], 1, 0);
                disp('   Gap control disabled');
                disp('   Feed forward enable');
                pause(1);
                disp('   Insertion device velocity profile boolean control off');
                disp('   Closing all gaps at maximum speed');
                % Set IDs at max velocity w/ velocity profile off
                [Position, Velocity, RunFlag, UserGap] = getid;
                setid([], UserGap, maxsp('IDvel'), 1, 0, 1);
                % Turn velocity profile on
                disp('   Insertion device velocity profile boolean control is on');
                setid([], [], maxsp('IDvel'), 1, 1, 0);
                disp('   Gaps are closed');
                setff([4;7;8;9;10;12], 1, 1);
                setff(5, 1, 0);
                disp('   Gap control enabled (except sector 5 (W16))');
            end
            set_alarmhandler_thresholds_new;
            setpv('SR_STATE',3);
        catch
            fprintf('   %s \n', lasterr);
            fprintf('   User lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-3);
        end
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp(['   **************************************************************************']);
            disp(['   **  Function complete:  the storage ring is setup for users at ',sprintf('%.1f',SR_GEV),' GeV  **']);
            disp(['   **************************************************************************']); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   *************************************']);
            disp(['   **  Problem with production setup  **']);
            disp(['   *************************************']); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        setfamilydata(0.8, 'BSCRampRate');
    case 'CheckInputs'
        SR_GEV = getfamilydata('Energy');
        AD=getad;
        setsrstatechannels;
        set(0,'showhiddenhandles','on');
        if AD.Energy > 1.55
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Down)']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users (Ramp Up)']);
        elseif AD.Energy < 1.45
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Up+cycle)']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV (Ramp Down)']);
        else
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV']);
        end
        set(findobj('Tag','SRCTRLTitle'),'String',SR_Mode);
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
        else
            set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
        end
        set(0,'showhiddenhandles','off');
    case 'SRState'
        NumErrors = 0;
        fprintf('\n');
        disp('   ***********************************');
        disp('   **  Checking Storage Ring State  **');
        disp('   ***********************************');
        a = clock;
        fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1000
1001         %       FileName = getpv('SR_LATTICE_FILE','String');   % Last srload file name (in OLD MIDDLE LAYER nomenclature!!)
1002
1003         GeVnow = bend2gev;
1004         if GeVnow == getfamilydata('Energy')
1005             [ConfigSetpoint, ConfigMonitor, FileName] = getproductionlattice;
1006         elseif GeVnow == getfamilydata('InjectionEnergy')
1007             [ConfigSetpoint, ConfigMonitor, FileName] = getinjectionlattice;
1008         else
1009             FileName = '';
1010         end
1011
1012         [StateNumber, StateString] = getsrstate;
1013         fprintf('   Storage ring operational mode: %s\n', SR_Mode);
1014         if StateNumber < 0
1015             fprintf('   Storage ring state error: %s\n', StateString);
1016             NumErrors = NumErrors + 1;
1017         else
1018             fprintf('   Storage ring state: %s\n', StateString);
1019         end
1020         if StateNumber==0
1021             % Storage ring state unknown
1022             NumErrors = NumErrors + 1;
1023         elseif abs(StateNumber)==1 || abs(StateNumber)==2
1024             FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','InjectionFile') '.mat'];
1025             if ~strcmp(FileName, FileNameGoal)
1026                 fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','InjectionFile'), FileName);
1027                 NumErrors = NumErrors + 1;
1028             end
1029         else
1030             FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile') '.mat'];
1031             if ~strcmp(FileName, FileNameGoal)
1032                 fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','LatticeFile'), FileName);
1033                 NumErrors = NumErrors + 1;
1034             end
1035         end
1036
1037
1038         % Check all SR magnets
1039         if isempty(FileName)
1040             fprintf('   Goal setpoints will not be checked since the last lattice load is unknown.\n');
1041             NumErrors1 = checksrmags('');
1042         else
1043 %            NumErrors1 = checksrmags([getfamilydata('Directory','OpsData') FileName]);
1044             NumErrors1 = checksrmags(FileName);
1045         end
1046         if NumErrors1 == 0
1047             fprintf('   SR magnets power supplies are OK.\n');
1048         end
1049         NumErrors = NumErrors + NumErrors1;
1050
1051
1052         % Check RF frequency
1053         if isempty(FileName)
1054             fprintf('   RF frequency will not be checked since the last lattice load is unknown.\n');
1055         else
1056 %            load([getfamilydata('Directory','OpsData'), FileName]);
1057             load(FileName);
1058             [tmp, RFHPCounterPresent] = getrf;
1059             if abs(RFHPCounterPresent-ConfigSetpoint.RF.Setpoint.Data) > .002
1060                 NumErrors = NumErrors + 1;
1061                 fprintf('   RF frequency should be %f, presently it is %f MHz (as measured by the HP counter).\n', ConfigSetpoint.RF.Setpoint.Data, RFHPCounterPresent);
1062             else
1063                 fprintf('   RF frequency is OK (HP counter is %f MHz, at the time of the lattice save it was %f MHz).\n', RFHPCounterPresent, ConfigSetpoint.RF.Setpoint.Data);
1064             end
1065         end
1066
1067
1068         % Check for orbit problems
1069         if (StateNumber >= 3) & (getdcct > 2)   % Production lattice is loaded with beam in the machine
1070             Xtol = 0.070;
1071             Ytol = 0.010;
1072             NumErrors1 = checksrorbit([],Xtol,Ytol);
1073             if NumErrors1
1074                 fprintf('   SR orbit in the ID straight sections or at Bergoz BPMs deviates more than allowed from the golden orbit.\n');
1075             else
1076                 fprintf('   SR orbit in the ID straight sections and at Bergoz BPMs is OK.\n');
1077                 fprintf('   The orbit is within %.3f mm horizontally and %.3f mm vertically', Xtol, Ytol);
1078             end
1079             NumErrors = NumErrors + NumErrors1;
1080         else
1081             fprintf('   Storage ring orbit was not checked.\n');
1082         end
1083
1084
1085         a = clock;
1086         datestr1=date;
1087         fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
1088         if NumErrors
1089             disp('   *********************************');
1090             disp('   **  Storage Ring Has Problems  **');
1091             disp('   *********************************');
1092         else
1093             disp('   **********************************');
1094             disp('   **  Storage Ring Lattice is OK  **');
1095             disp('   **********************************');
1096         end
1097         fprintf('   \n');
1098
1099         set(0,'showhiddenhandles','on');
1100         [StateNumber, StateString] = getsrstate;
1101         if StateNumber >= 0
1102             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1103         else
1104             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1105         end
1106         set(0,'showhiddenhandles','off');
1107
1108
1109     case 'OrbitCorrection'
1110         fprintf('\n');
1111         fprintf('   *********************************\n');
1112         fprintf('   **  Starting Orbit Correction  **\n');
1113         fprintf('   *********************************\n');
1114         a = clock;
1115         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1116
1117         StartFlag = questdlg(sprintf('Start orbit correction, %.1f GeV?',SR_GEV),'Orbit Correction','Yes','No','No');
1118         if strcmp(StartFlag,'No')
1119             disp(['   ********************************']);
1120             disp(['   **  Orbit Correction Aborted  **']);
1121             disp(['   ********************************']);
1122             fprintf('\n');
1123             return
1124         end
1125
1126         if getdcct < 5     % Don't correct the orbit if the current is too small
1127             fprintf('   Orbit not corrected due to small current.\n');
1128             return
1129         end
1130
1131         if abs(SR_GEV-bend2gev(getpv('BEND',[1 1])))>  0.05     % Don't use this routine for the injection lattice
1132             fprintf('   This routine should only be used for the production energy: Correction aborted\n');
1133             return
1134         end
1135
1136         SR_STATE_OLD = scaget('SR_STATE');
1137         set(0,'showhiddenhandles','on');
1138         setpv('SR_STATE',4);
1139         [StateNumber, StateString] = getsrstate;
1140         if StateNumber >= 0
1141             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1142         else
1143             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1144         end
1145         set(0,'showhiddenhandles','off');
1146
1147
1148         try
1149
1150             % 2 Hz update rate on IDBPMs
1151             disp('   IDBPM time constant set to 0.5s.')
1152             setbpmtimeconstant(0.5)
1153             pause(2);
1154
1155
1156             % Turn off feed forward
1157             fprintf('   Turning feed forward off.\n');
1158             [FFEnableBM, FFEnableBC] = getff;
1159             setff([], 0);
1160             scasleep(.2);
1161
1162
1163             % Get vectors
1164             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1165             LocalBumplist = FB.LocalBumplist;
1166
1167         catch
1168
1169             fprintf('   %s \n',lasterr);
1170             fprintf('   Orbit correction setup failed due to error condition! \n\n');
1171             setpv('SR_STATE',-4);
1172             set(0,'showhiddenhandles','on');
1173             [StateNumber, StateString] = getsrstate;
1174             if StateNumber >= 0
1175                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1176             else
1177                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1178             end
1179             set(0,'showhiddenhandles','off');
1180             return
1181
1182         end
1183
1184         iNotHCMChicane = find(FB.HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
1185         iHCMChicane = find(FB.HCMlist1(:,2) == 10);
1186         iNotVCMChicane = find(FB.VCMlist1(:,2) < 10);
1187         iVCMChicane = find(FB.VCMlist1(:,2) == 10);
1188
1189         fprintf('   Starting horizontal and vertical global orbit correction (SVD method).\n');
1190
1191         for iloop = 1:3
1192             try
1193                 % use the following to get corrector settings in OCS without setting them, so the values can be checked
1194                 FB.OCSx = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
1195                 FB.OCSy = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
1196                 if any(abs(FB.OCSx.CM.Delta(iNotHCMChicane)) > 5)
1197                   disp('   Orbit Correction is changing some horizontal corrector(s) > 5A!!');
1198                 end
1199                 if any(abs(FB.OCSy.CM.Delta(iNotVCMChicane)) > 5)
1200                   disp('   Orbit Correction is changing some vertical corrector(s) > 5A!!');
1201                 end
1202                 if any(abs(FB.OCSx.CM.Delta(iHCMChicane)) > 10)
1203                   disp('   Orbit Correction is changing some horizontal chicane corrector(s) > 10A!!');
1204                 end
1205                 if any(abs(FB.OCSy.CM.Delta(iVCMChicane)) > 10)
1206                   disp('   Orbit Correction is changing some vertical chicane corrector(s) > 10A!!');
1207                 end
1208
1209
1210                 % Correct horizontal orbit
1211                 FB.OCSx = setorbit(FB.OCSx,'NoDisplay');
1212                 % Correct vertical orbit
1213                 FB.OCSy = setorbit(FB.OCSy,'NoDisplay');
1214
1215
1216                 % Check for current in machine - stop orbit correction if DCCT < 5mA
1217                 if (getdcct < 4.5)
1218                     error('**There is less than 5mA in the machine! Stopping orbit correction.');
1219                 end
1220
1221                 % Check state of gaps - stop orbit correction if any are moving
1222                 GAPrunflag = getpv('ID','RunFlag');
1223                 if any(GAPrunflag-round(GAPrunflag))
1224                     error('**One or more of the gaps are moving! Stopping orbit correction.');
1225                 end
1226
1227                 x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
1228                 y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
1229                 fprintf('   %d. Horizontal RMS = %.3f mm\n', iloop, norm(x)/sqrt(length(x)));
1230                 fprintf('   %d.   Vertical RMS = %.3f mm\n', iloop, norm(y)/sqrt(length(y)));
1231
1232             catch
1233                 % fprintf('   %s \n',lasterr);
1234                 fprintf('   Orbit correction failed due to error condition!\n  Fix the problem, reload the lattice (srload), and try again.  \n\n');
1235                 setpv('SR_STATE',-4);
1236                 set(0,'showhiddenhandles','on');
1237                 [StateNumber, StateString] = getsrstate;
1238                 if StateNumber >= 0
1239                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1240                 else
1241                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1242                 end
1243                 set(0,'showhiddenhandles','off');
1244                 return
1245             end
1246         end
1247
1248
1249         % Set user bumps w/o sextupole correctors
1250         try
1251
1252             %turn up corrector speed here to quicken setting bumps
1253             HCMramprate = getpv('HCM', 'RampRate');
1254             VCMramprate = getpv('VCM', 'RampRate');
1255             setpv('HCM', 'RampRate', 10, [], 0);
1256             setpv('VCM', 'RampRate', 10, [], 0);
1257
1258             if ~isempty(LocalBumplist)
1259                 fprintf('   Setting local bumps in the straight sections.\n');
1260                 for loop = 1:size(LocalBumplist,1)
1261
1262                     % Check for current in machine - stop orbit correction if DCCT < 5mA
1263                     if (getdcct < 5)
1264                         error('** There is less than 5mA in the machine! Stopping local bumps.');
1265                     end
1266
1267                     % Check state of gaps - stop setting bumps if any are moving
1268                     GAPrunflag = getpv('ID','RunFlag');
1269                     if any(GAPrunflag-round(GAPrunflag))
1270                         error('** One or more of the gaps are moving! Stopping local bumps.');
1271                     end
1272
1273                     HCMoldsp = getsp('HCM', FB.HCMlist1);
1274                     VCMoldsp = getsp('VCM', FB.VCMlist1);
1275
1276                     if any(LocalBumplist(loop,1) == [4 6 11])
1277                         if LocalBumplist(loop,2) == 0
1278                             % Upstream bump
1279                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1280                             if isempty(iRemove)
1281                                 setbumps(LocalBumplist(loop,:), 1);
1282                             else
1283                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1284                             end
1285                         elseif LocalBumplist(loop,2) == 1
1286                             % Upstream bump
1287                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;],FB.OCSx.BPM.DeviceList);
1288                             if isempty(iRemove)
1289                                 setbumps(LocalBumplist(loop,:), 1);
1290                             else
1291                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1292                             end
1293                         else
1294                             % Downstream bump
1295                             [i, iRemove] = findrowindex([LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1296                             if isempty(iRemove)
1297                                 setbumps(LocalBumplist(loop,:), 1);
1298                             else
1299                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1300                             end
1301                         end
1302                     else
1303                         [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1304                         if isempty(iRemove)
1305                             setbumps(LocalBumplist(loop,:), 1);
1306                         else
1307                             fprintf('\n   BPMs missing from Sector %02d - skipping local bump for that sector.\n\n', LocalBumplist(loop,1));
1308                         end
1309                     end
1310
1311                     HCMnewsp = getsp('HCM', FB.HCMlist1);
1312                     VCMnewsp = getsp('VCM', FB.VCMlist1);
1313                     % Remove center chicane trim from corrector check
1314                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 5) | (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 10)
1315                         error('**Setbumps caused some corrector magnet currents to change by more than 5(Horiz)/10(Vert) A!');
1316                     end
1317                     % Now check center chicane trims
1318                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 10) | (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 15)
1319                         error('**Setbumps caused some chicane trim magnet currents to change by more than 10(Horiz)/15(Vert) A!');
1320                     end
1321                 end
1322             end
1323
1324             %restore corrector speeds
1325             setpv('HCM', 'RampRate', HCMramprate, [], 0);
1326             setpv('VCM', 'RampRate', VCMramprate, [], 0);
1327
1328         catch
1329             fprintf('   %s \n',lasterr);
1330             fprintf('   Setbumps failed due to error condition!  Fix the problem, reload the lattice (srload), and try again.\n\n');
1331             setpv('SR_STATE',-4);
1332             set(0,'showhiddenhandles','on');
1333             [StateNumber, StateString] = getsrstate;
1334             if StateNumber >= 0
1335                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1336             else
1337                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1338             end
1339             set(0,'showhiddenhandles','off');
1340             return
1341         end
1342
1343
1344         % Turn feed forward back to it's original state
1345         if any(FFEnableBC)
1346             fprintf('   Turning feed forward back on.\n');
1347             setff([], FFEnableBC);
1348         end
1349
1350
1351         a = clock;
1352         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1353         [StateNumber, StateString] = getsrstate;
1354         set(0,'showhiddenhandles','on');
1355         if StateNumber >= 0
1356             setpv('SR_STATE',4.1);
1357             [StateNumber, StateString] = getsrstate;
1358             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1359             fprintf('   *********************************\n');
1360             fprintf('   **  Orbit Correction Complete  **\n');
1361             fprintf('   *********************************\n\n');
1362         else
1363             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1364             fprintf('   *************************************\n');
1365             fprintf('   **  Problem With Orbit Correction  **\n');
1366             fprintf('   *************************************\n\n');
1367         end
1368         set(0,'showhiddenhandles','off');
1369         pause(0);
1370
1371
1372     case 'OrbitCorrectionSetup'
1373         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
1374
1375         if InitFlag
1376             % Setup feedback elements
1377             % disp('Orbit correction condition: InitFlag=1 -- debugging message');
1378
1379             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1380             % Edit the following lists to change default configuration of Orbit Correction %
1381             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1382             hlist=[];vlist=[];
1383             for Sector =1:12
1384                 if Sector == 1
1385                     vlist = [vlist;Sector 2;Sector 4;Sector 5;Sector 8];
1386                     hlist = [hlist;Sector 2;Sector 7];
1387                 elseif Sector == 3
1388                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1389                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1390                 elseif Sector == 5
1391 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1392 %                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1393                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8]; %remove HCM and VCM(5,10) since corrector is not controlling starting 4-6-07
1394                     hlist = [hlist;Sector 2;Sector 7];
1395                 elseif Sector == 10
1396                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1397                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1398                 elseif Sector == 12
1399                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 7];
1400                     hlist = [hlist;Sector 2;Sector 7];
1401                 else
1402                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8];
1403                     hlist = [hlist;Sector 2;Sector 7];
1404                 end
1405             end
1406             HCMlist1 = hlist;
1407             VCMlist1 = vlist;
1408
1409             BPMlist1 = [
1410                 1 2
1411                 1 5
1412                 1 6
1413                 1 10
1414                 2 1
1415                 2 5
1416                 2 6
1417                 2 9
1418                 3 2
1419                 3 5
1420                 3 6
1421                 3 10
1422                 3 11
1423                 3 12
1424                 4 1
1425                 4 5
1426                 4 6
1427                 4 10
1428                 5 1
1429                 5 5
1430                 5 6
1431                 5 10
1432 %                 5 11
1433 %                 5 12
1434                 6 1
1435                 6 5
1436                 6 6
1437                 6 10
1438                 7 1
1439                 7 5
1440                 7 6
1441                 7 10
1442                 8 1
1443                 8 5
1444                 8 6
1445                 8 10
1446                 9 1
1447                 9 5
1448                 9 6
1449                 9 10
1450                 10 1
1451                 10 5
1452                 10 6
1453                 10 10
1454                 10 11
1455                 10 12
1456                 11 1
1457                 11 5
1458                 11 6
1459                 11 10
1460                 12 1
1461                 12 5
1462                 12 6
1463                 12 9];
1464
1465             % SVD orbit correction
1466             Xivec = [1:27];
1467             Yivec = [1:48];
1468
1469
1470             LocalBumplist = [
1471               % 1 1
1472               % 2 1
1473               % 3 1
1474                 4 1
1475               % 4 2
1476                 5 1
1477               % 6 1
1478               % 6 2
1479                 7 1
1480                 8 1
1481                 9 1
1482                 10 1
1483                 11 1
1484                 11 2
1485                 12 1
1486 ];
1487             %LocalBumplist = []
1488
1489             % initialize RFCorrFlag
1490             RFCorrFlag = 'Yes';
1491         else
1492
1493             % Get vectors
1494             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1495             BPMlist1 = FB.BPMlist1;
1496             HCMlist1 = FB.HCMlist1;
1497             VCMlist1 = FB.VCMlist1;
1498             Xivec = FB.Xivec;
1499             Yivec = FB.Yivec;
1500             LocalBumplist = FB.LocalBumplist;
1501             Xgoal = FB.Xgoal;
1502             Ygoal = FB.Ygoal;
1503             RFCorrFlag = FB.RFCorrFlag;
1504
1505             % Add button to change #ivectors, CMs, IDBPMs,
1506             EditFlag = 0;
1507             h_fig1 = figure;
1508             while EditFlag ~= 8
1509
1510                 % Sensitivity matrix
1511                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
1512                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
1513
1514                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1515                 % Can the call below work for setting FOFB RF parameter? %
1516                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1517                 if strcmpi(RFCorrFlag, 'Yes')
1518                     Sx = [Sx getdisp('BPMx',BPMlist1)];
1519                 end
1520
1521                 [Ux, SVx, Vx] = svd(Sx);
1522                 [Uy, SVy, Vy] = svd(Sy);
1523
1524
1525                 % Remove singular values greater than the actual number of singular values
1526                 i = find(Xivec>length(diag(SVx)));
1527                 if ~isempty(i)
1528                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
1529                     pause(0);
1530                     Xivec(i) = [];
1531                 end
1532                 i = find(Yivec>length(diag(SVy)));
1533                 if ~isempty(i)
1534                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
1535                     pause(0);
1536                     Yivec(i) = [];
1537                 end
1538
1539
1540                 Ax = Sx*Vx(:,Xivec);
1541                 Tx = inv(Ax'*Ax)*Ax';
1542
1543                 Ay = Sy*Vy(:,Yivec);
1544                 Ty = inv(Ay'*Ay)*Ay';
1545
1546
1547                 figure(h_fig1);
1548                 subplot(2,1,1);
1549                 semilogy(diag(SVx),'b');
1550                 hold on;
1551                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
1552                 ylabel('Horizontal');
1553                 title('Response Matrix Singular Values');
1554                 hold off;
1555                 subplot(2,1,2);
1556                 semilogy(diag(SVy),'b');
1557                 hold on;
1558                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
1559                 xlabel('Singular Value Number');
1560                 ylabel('Vertical');
1561                 hold off;
1562                 drawnow;
1563
1564                 if strcmp(RFCorrFlag,'No')
1565                     RFCorrState = 'NOT CORRECTED';
1566                 elseif strcmp(RFCorrFlag,'Yes')
1567                     RFCorrState = 'CORRECTED';
1568                 else
1569                     RFCorrState = '???';
1570                 end
1571
1572                 %         EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','HCM Chicane List','VCM Chicane List','IDBPM List','BBPM List','Change Golden Orbit',...
1573                 %            'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1574                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','BPM List','Change Golden Orbit',...
1575                     'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1576
1577                 if EditFlag == 1
1578                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
1579                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
1580                     titlestr='SVD Orbit Feedback';
1581                     lineNo=1;
1582                     answer=inputdlg(prompt,titlestr,lineNo,def);
1583                     if ~isempty(answer)
1584                         XivecNew = fix(str2num(answer{1}));
1585                         if isempty(XivecNew)
1586                             disp('   Horizontal E-vector cannot be empty.  No change made.');
1587                         else
1588                             if any(XivecNew<=0) | max(XivecNew)>length(diag(SVx))
1589                                 disp('   Error reading horizontal E-vector.  No change made.');
1590                             else
1591                                 Xivec = XivecNew;
1592                             end
1593                         end
1594                         YivecNew = fix(str2num(answer{2}));
1595                         if isempty(YivecNew)
1596                             disp('   Vertical E-vector cannot be empty.  No change made.');
1597                         else
1598                             if any(YivecNew<=0) | max(YivecNew)>length(diag(SVy))
1599                                 disp('   Error reading vertical E-vector.  No change made.');
1600                             else
1601                                 Yivec = YivecNew;
1602                             end
1603                         end
1604                     end
1605                 end
1606
1607                 if EditFlag == 2
1608                     List = getlist('HCM');
1609                     CheckList = zeros(size(List,1));
1610                     Elem = dev2elem('HCM', HCMlist1);
1611                     CheckList(Elem) = ones(size(Elem));
1612                     CheckList = CheckList(dev2elem('HCM',List));
1613                     newList = editlist(List, 'HCM', CheckList);
1614                     if isempty(newList)
1615                         fprintf('   Horizontal corrector magnet list cannot be empty.  No change made.\n');
1616                     else
1617                         HCMlist1 = newList;
1618                     end
1619                 end
1620
1621                 if EditFlag == 3
1622                     List = getlist('VCM');
1623                     CheckList = zeros(size(List,1));
1624                     Elem = dev2elem('VCM', VCMlist1);
1625                     CheckList(Elem) = ones(size(Elem));
1626                     CheckList = CheckList(dev2elem('VCM',List));
1627                     newList = editlist(List, 'VCM', CheckList);
1628                     if isempty(newList)
1629                         fprintf('   Vertical corrector magnet cannot be empty.  No change made.\n');
1630                     else
1631                         VCMlist1 = newList;
1632                     end
1633                 end
1634
1635                 if EditFlag == 4
1636                     ListOld = BPMlist1;
1637                     XgoalOld = Xgoal;
1638                     YgoalOld = Ygoal;
1639
1640                     % Full BPM list
1641                     List = [
1642                         1 2
1643                         1 5
1644                         1 6
1645                         1 10
1646                         2 1
1647                         2 5
1648                         2 6
1649                         2 9
1650                         3 2
1651                         3 5
1652                         3 6
1653                         3 10
1654                         3 11
1655                         3 12
1656                         4 1
1657                         4 5
1658                         4 6
1659                         4 10
1660                         5 1
1661                         5 5
1662                         5 6
1663                         5 10
1664                         5 11
1665                         5 12
1666                         6 1
1667                         6 5
1668                         6 6
1669                         6 10
1670                         7 1
1671                         7 5
1672                         7 6
1673                         7 10
1674                         8 1
1675                         8 5
1676                         8 6
1677                         8 10
1678                         9 1
1679                         9 5
1680                         9 6
1681                         9 10
1682                         10 1
1683                         10 5
1684                         10 6
1685                         10 10
1686                         10 11
1687                         10 12
1688                         11 1
1689                         11 5
1690                         11 6
1691                         11 10
1692                         12 1
1693                         12 5
1694                         12 6
1695                         12 9
1696                         ];
1697
1698                     CheckList = zeros(size(List,1),1);
1699                     if ~isempty(BPMlist1)
1700                         for i = 1:size(List,1)
1701                             k = find(List(i,1)==BPMlist1(:,1));
1702                             l = find(List(i,2)==BPMlist1(k,2));
1703
1704                             if isempty(k) | isempty(l)
1705                                 % Item not in list
1706                             else
1707                                 CheckList(i) = 1;
1708                             end
1709                         end
1710                     end
1711
1712                     newList = editlist(List, 'BPM', CheckList);
1713                     if isempty(newList)
1714                         fprintf('   BPM list cannot be empty.  No change made.\n');
1715                     else
1716                         BPMlist1 = newList;
1717                     end
1718
1719                     % Set the goal orbit to the golden orbit
1720                     Xgoal = getgolden('BPMx', BPMlist1);
1721                     Ygoal = getgolden('BPMy', BPMlist1);
1722
1723
1724                     % If a new BPM is added, then set the goal orbit to the golden orbit
1725                     for i = 1:size(BPMlist1,1)
1726
1727                         % Is it a new BPM?
1728                         k = find(BPMlist1(i,1)==ListOld(:,1));
1729                         l = find(BPMlist1(i,2)==ListOld(k,2));
1730
1731                         if isempty(k) | isempty(l)
1732                             % New BPM
1733                         else
1734                             % Use the old value for old BPM
1735                             Xgoal(i) = XgoalOld(k(l));
1736                             Ygoal(i) = YgoalOld(k(l));
1737                         end
1738                     end
1739                 end
1740
1741                 if EditFlag == 5
1742
1743                     ChangeList = editlist(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
1744                     for i = 1:size(ChangeList,1)
1745
1746                         k = find(ChangeList(i,1)==BPMlist1(:,1));
1747                         l = find(ChangeList(i,2)==BPMlist1(k,2));
1748
1749                         prompt = {sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
1750                         def = {sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
1751                         titlestr = 'CHANGE THE GOAL ORBIT';
1752                         lineNo = 1;
1753                         answer = inputdlg(prompt, titlestr, lineNo, def);
1754
1755                         if isempty(answer)
1756                             % No change
1757                             fprintf('   No change was made to the golden orbit.\n');
1758                         else
1759                             Xgoalnew = str2num(answer{1});
1760                             if isempty(Xgoalnew)
1761                                 fprintf('   No change was made to the horizontal golden orbit.\n');
1762                             else
1763                                 Xgoal(k(l)) = Xgoalnew;
1764                             end
1765
1766                             Ygoalnew = str2num(answer{2});
1767                             if isempty(Ygoalnew)
1768                                 fprintf('   No change was made to the vertical golden orbit.\n');
1769                             else
1770                                 Ygoal(k(l)) = Ygoalnew;
1771                             end
1772                         end
1773                     end
1774                     if ~isempty(ChangeList)
1775                         fprintf('   Note:  changing the goal orbit for "Orbit Correction" does not change the goal orbit for "Slow Orbit Feedback."\n');
1776                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
1777                     end
1778                 end
1779
1780                 if EditFlag == 6
1781                     List = [
1782                         1 1
1783                         2 1
1784                         3 1
1785                         4 1
1786                         4 2
1787                         5 1
1788                         6 1
1789                         6 2
1790                         7 1
1791                         8 1
1792                         9 1
1793                         10 1
1794                         11 1
1795                         11 2
1796                         12 1];
1797                     CheckList = zeros(size(List,1),1);
1798                     if ~isempty(LocalBumplist)
1799                         for i = 1:size(List,1)
1800                             k = find(List(i,1)==LocalBumplist(:,1));
1801                             l = find(List(i,2)==LocalBumplist(k,2));
1802
1803                             if isempty(k) | isempty(l)
1804                                 % Item not in list
1805                             else
1806                                 CheckList(i) = 1;
1807                             end
1808                         end
1809                     end
1810                     LocalBumplist = editlist2(List, 'Sector', CheckList);
1811                 end
1812
1813                 if EditFlag == 7
1814                     RFCorrFlag = questdlg(sprintf('Set RF Frequency during Orbit Correction?'),'RF Frequency','Yes','No', 'No');
1815                     if strcmp(RFCorrFlag,'No')
1816                         disp(['   RF Frequency will not be included in global orbit correction.']);
1817                     elseif strcmp(RFCorrFlag,'Yes')
1818                         disp(['   RF Frequency will be included in global orbit correction.']);
1819                     end
1820
1821                 end
1822             end
1823             close(h_fig1);
1824         end
1825
1826 %  ORBIT CORRECTION STRUCTURE (OCS)
1827 %    OCS.BPM (data structure)
1828 %    OCS.CM  (data structure)
1829 %    OCS.GoalOrbit
1830 %    OCS.NIter
1831 %    OCS.SVDIndex
1832 %    OCS.IncrementalFlag = 'Yes'/'No'
1833 %    OCS.BPMWeight
1834 %    OCS.Flags = { 'FitRF' , etc.  }
1835         OCSx.BPM = getx(BPMlist1, 'struct');
1836         OCSx.CM = getsp('HCM', HCMlist1, 'struct');
1837         OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
1838         OCSx.NIter = 1;
1839         OCSx.SVDIndex = Xivec;
1840         OCSx.IncrementalFlag = 'No';
1841         OCSx.FitRF = 1;
1842         OCSy.BPM = gety(BPMlist1, 'struct');
1843         OCSy.CM = getsp('VCM', VCMlist1, 'struct');
1844         OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
1845         OCSy.NIter = 1;
1846         OCSy.SVDIndex = Yivec;
1847         OCSy.IncrementalFlag = 'No';
1848         OCSy.FitRF = 0;
1849
1850         % Save vectors
1851         FB.OCSx = OCSx;
1852         FB.OCSy = OCSy;
1853
1854         FB.BPMlist1 = BPMlist1;
1855         FB.HCMlist1 = HCMlist1;
1856         FB.VCMlist1 = VCMlist1;
1857         FB.Xivec = Xivec;
1858         FB.Yivec = Yivec;
1859         FB.Xgoal = OCSx.GoalOrbit;
1860         FB.Ygoal = OCSy.GoalOrbit;
1861         FB.RFCorrFlag = RFCorrFlag;
1862         FB.LocalBumplist = LocalBumplist;
1863         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata',FB);
1864
1865
1866     case 'Feedback'
1867
1868         FBloopIter = 1;
1869         if get(findobj(gcbf,'Tag','SRCTRLCheckboxFOFB'),'Value') == 1
1870             StartFOFBFlag = 1;
1871         else
1872             StartFOFBFlag = 0;
1873         end
1874
1875         FEEDBACK_STOP_FLAG = 0;
1876         HWarnNum=0;
1877         VWarnNum=0;
1878
1879         SR_GeV = getenergy;
1880         % Feedback loop setup
1881         PlotInfoFlag = 0;           % Plot micado stuff
1882         LoopDelay = 1.0;           % Period of feedback loop [seconds], make sure the BPM averaging is correct
1883         VCM_LSB = .00366211;
1884         VCMCHICANE_LSB = .002441;   % 80 max?,  Note: not fully implemented
1885
1886         if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
1887             Xgain  = 0.2;
1888             Ygain  = 0.1;
1889         else
1890             Xgain  = 0.8; % raised 0.5->0.8 at 17:20, 3-2-05 to more quickly correct EPU4 fast switching orbit distortions
1891             Ygain  = 0.8;
1892         end
1893
1894         % Load lattice set for tune feed forward
1895         ConfigSetpoint = getproductionlattice;
1896         %load([getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile')]);
1897         QFsp = ConfigSetpoint.QF.Setpoint.Data;
1898         QDsp = ConfigSetpoint.QD.Setpoint.Data;
1899         TuneW16Min = gap2tune(5, 13.23, 1.8909);
1900         % Tune response matrix
1901         SR_TUNE_MATRIX = gettuneresp({'QF','QD'}, {[],[]}, getenergy('Production'));    % Approx. [0.1944 -0.0286;-0.1182 0.1526];
1902         %SR_TUNE_MATRIX = [0.1641 -0.0245
1903         %                 -0.1149 0.1477];
1904
1905         % ID tune compensation does not work in the injection lattice, so ...
1906         if abs(SR_GEV - bend2gev)>  0.05     % Don't use this routine for the injection lattice
1907             fprintf('   This routine should only be used for the production energy: Orbit feedback aborted\n');
1908             return
1909         end
1910
1911         set(0,'showhiddenhandles','on');
1912
1913         try
1914             fprintf('\n');
1915             fprintf('   *******************************\n');
1916             fprintf('   **  Starting Orbit Feedback  **\n');
1917             fprintf('   *******************************\n');
1918             a = clock;
1919             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1920             fprintf('   Note: the Matlab command window will be used to display status information.\n');
1921             fprintf('         It cannot be used to enter commands during slow orbit feedback.\n');
1922
1923
1924             % >= 2 Hz update rate on IDBPMs
1925             disp('   IDBPM time constant set to 0.2s.')
1926             setbpmtimeconstant(0.2)
1927             pause(1.1);
1928
1929             % Check whether bumps and kickers are on and warn to turn off before starting feedback if necessary
1930             try
1931                 if (getsp('SR01S___BUMP1__BC21')==1 & getsp('SR01S___BUMP1P_BC22')==1) | (getsp('SR01S___SEK____BC21')==1 & getsp('SR01S___SEK_P__BC23')==1) | (getsp('SR01S___SEN____BC20')==1 & getsp('SR01S___SEN_P__BC22')==1)
1932                     soundtada;
1933                     fprintf('   \n');
1934                     fprintf('   *********************************************************************************\n');
1935                     fprintf('   ** One or more of the pulsed SR injection magnets is still on!  Turn them off! **\n');
1936                     fprintf('   *********************************************************************************\n');
1937                     fprintf('   \n');
1938                 end
1939             catch
1940                 disp('**Problem checking the state of the bumps and kickers - please check that they are not pulsing.');
1941             end
1942
1943             % Get vectors
1944
1945             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
1946
1947             BPMlist1 = FB.OCSx.BPM.DeviceList;
1948             % FOFB_BPMlist =
1949             HCMlist1 = FB.HCMlist1;
1950             VCMlist1 = FB.VCMlist1;
1951             Xivec = FB.Xivec;
1952             Yivec = FB.Yivec;
1953             Xgoal = FB.OCSx.GoalOrbit;
1954             Ygoal = FB.OCSy.GoalOrbit;
1955             FFTypeFlag = FB.FFTypeFlag;   %local or global tune correction
1956
1957             iNotHCMChicane = find(HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
1958             iHCMChicane = find(HCMlist1(:,2) == 10);
1959             iNotVCMChicane = find(VCMlist1(:,2) < 10);
1960             iVCMChicane = find(VCMlist1(:,2) == 10);
1961
1962             % Sensitivity matrix for setting fast feedback setpoints
1963             Sx1 = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
1964             Sy1 = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
1965
1966         catch
1967             fprintf('\n  %s \n',lasterr);
1968
1969             % >= 2 Hz update rate on IDBPMs
1970             disp('   IDBPM time constant set to 0.25s.')
1971             setbpmtimeconstant(0.25)
1972
1973
1974             a = clock;
1975             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1976             fprintf('   *************************************************************\n');
1977             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
1978             fprintf('   *************************************************************\n\n');
1979             set(0,'showhiddenhandles','off');
1980             pause(0);
1981
1982             return
1983         end
1984
1985         StartFlag = questdlg(strvcat('','Is it OK to start orbit feedback?'),'Orbit Feedback','Yes','No','No');
1986         if strcmp(StartFlag,'No')
1987             % >= 2 Hz update rate on IDBPMs
1988             disp('   IDBPM time constant set to 0.25s.')
1989             setbpmtimeconstant(0.25)
1990
1991             a = clock;
1992             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1993             fprintf('   ***************************\n');
1994             fprintf('   **  Orbit Feedback Exit  **\n');
1995             fprintf('   ***************************\n\n');
1996             pause(0);
1997             return
1998         end
1999
2000         SR_STATE_OLD = scaget('SR_STATE');
2001         setpv('SR_STATE', 5);
2002         set(0,'showhiddenhandles','on');
2003         [StateNumber, StateString] = getsrstate;
2004         if StateNumber >= 0
2005             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2006         else
2007             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2008         end
2009         fprintf('   Using %d E-vectors horizontally.\n', length(Xivec));
2010         fprintf('   Using %d E-vectors vertically.\n',   length(Yivec));
2011         fprintf('   Starting slow orbit correction every %.1f seconds.\n', LoopDelay);
2012         %  fprintf('   Resetting SR11 chicane motors every 20 seconds to fix drift problem.\n');
2013
2014         IDSector = getlist('ID');
2015         EPUlist = find((IDSector(:,1)==4) | (IDSector(:,1)==11));
2016         oldgap=210*ones(size(IDSector,1),1);
2017         oldShift=zeros(size(oldgap));
2018
2019         try
2020
2021             % Get and display data
2022             x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
2023             y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
2024             STDx = norm(x)/sqrt(length(x));
2025             STDy = norm(y)/sqrt(length(y));
2026             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
2027             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
2028
2029             % write goldenorbit values to Fast Orbit Feedback
2030             try
2031                 write_goldenorbit_ffb;
2032             catch
2033                 disp('write_goldenorbit_ffb did not work!');
2034             end
2035             setpv('SR01____FFBON__BC00',2);
2036             %pause(0);
2037
2038             %display state of FOFB system
2039             FOFBStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2040                 getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2041                 getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2042                 getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2043             FOFBStatusStr = ['    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    '];
2044             for loop = 1:size(FOFBStatus,2)
2045                 if FOFBStatus(loop)==0
2046                     FOFBStatusStr(loop,:) = 'OFF ';
2047                 elseif FOFBStatus(loop)==1
2048                     FOFBStatusStr(loop,:) = 'ON  ';
2049                 elseif FOFBStatus(loop)==2
2050                     FOFBStatusStr(loop,:) = 'OPEN';
2051                 else
2052                     FOFBStatusStr(loop,:) = 'BAD ';
2053                 end
2054             end
2055             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 %s',FOFBStatusStr(1,:)),'ForegroundColor',[0 0 0]);
2056             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 %s',FOFBStatusStr(2,:)),'ForegroundColor',[0 0 0]);
2057             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 %s',FOFBStatusStr(3,:)),'ForegroundColor',[0 0 0]);
2058             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 %s',FOFBStatusStr(4,:)),'ForegroundColor',[0 0 0]);
2059             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 %s',FOFBStatusStr(5,:)),'ForegroundColor',[0 0 0]);
2060             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 %s',FOFBStatusStr(6,:)),'ForegroundColor',[0 0 0]);
2061             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 %s',FOFBStatusStr(7,:)),'ForegroundColor',[0 0 0]);
2062             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 %s',FOFBStatusStr(8,:)),'ForegroundColor',[0 0 0]);
2063             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 %s',FOFBStatusStr(9,:)),'ForegroundColor',[0 0 0]);
2064             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 %s',FOFBStatusStr(10,:)),'ForegroundColor',[0 0 0]);
2065             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 %s',FOFBStatusStr(11,:)),'ForegroundColor',[0 0 0]);
2066             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 %s',FOFBStatusStr(12,:)),'ForegroundColor',[0 0 0]);
2067
2068         catch
2069
2070             fprintf('\n  %s \n',lasterr);
2071
2072             % >= 2 Hz update rate on IDBPMs
2073             disp('   IDBPM time constant set to 0.25s.')
2074             setbpmtimeconstant(0.25);
2075
2076
2077             a = clock;
2078             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2079             fprintf('   *************************************************************\n');
2080             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
2081             fprintf('   *************************************************************\n\n');
2082
2083             setpv('SR_STATE',SR_STATE_OLD);
2084             [StateNumber, StateString] = getsrstate;
2085             if StateNumber >= 0
2086                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2087             else
2088                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2089             end
2090             set(0,'showhiddenhandles','off');
2091             pause(0);
2092
2093             return
2094
2095         end
2096
2097
2098         % Disable buttons
2099         set(0,'showhiddenhandles','on');
2100         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','off');
2101         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','on');
2102         set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','off');
2103         set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','off');
2104         set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','off');
2105         set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','off');
2106         set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','off');
2107         set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','off');
2108         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','off');
2109         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','off');
2110         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','off');
2111         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','off');
2112         set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','off');
2113         pause(0);
2114
2115
2116         % Initialize feedback loop
2117         StartTime = gettime;
2118         StartErrorTime = gettime;
2119         Xold = getx(FB.OCSx.BPM.DeviceList);
2120         Yold = gety(FB.OCSy.BPM.DeviceList);
2121         HQMOFM_stalenum = 0;
2122         pause(LoopDelay);
2123
2124         N_HCM = size(HCMlist1,1);
2125         N_VCM = size(VCMlist1,1);
2126
2127         N_RFMO = 1;
2128
2129         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2130             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'SetRF','Nodisplay','Nosetsp');
2131         else
2132             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
2133         end
2134         [FB.OCSx, Smatx, Sx, Ux, Vx] = orbitcorrectionmethods(FB.OCSx);
2135
2136         [FB.OCSy, junk, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
2137         [FB.OCSy, Smaty, Sy, Uy, Vy] = orbitcorrectionmethods(FB.OCSy);
2138
2139
2140         %%%%%%%%%%%%%%%%%%%%%%%
2141         % Start feedback loop %
2142         %%%%%%%%%%%%%%%%%%%%%%%
2143
2144         % chicaneloop=1;  % loop variable for resetting drifting chicanes (see a few lines below)
2145         % fftest=figure;
2146
2147         setpv('SR01____FFBON__BC00',2); % put FOFB in open loop so beamnoise gets recorded even if FOFB is not enabled
2148
2149         while 1
2150             try
2151                 t00 = gettime;
2152
2153                 %          if chicaneloop==20 % reset SR11 motor chicane setpoints every 20s due to drifting positions
2154                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(6),[11 1],0);
2155                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(7),[11 2],0);
2156                 %             chicaneloop = 1;
2157                 %          else
2158                 %             chicaneloop = chicaneloop + 1;
2159                 %          end
2160
2161                 % Check if GUI has been closed
2162                 if isempty(gcbf)
2163                     FEEDBACK_STOP_FLAG = 1;
2164                     lasterr('SRCONTROL GUI DISAPPEARED!');
2165                     error('SRCONTROL GUI DISAPPEARED!');
2166                 end
2167
2168                 %%%%%%%%%%%%%%%%%%%%%%%
2169                 % Fast orbit feedback %
2170                 %%%%%%%%%%%%%%%%%%%%%%%
2171                 if StartFOFBFlag == 1 & FBloopIter > 3
2172                     setpv('SR01____FFBON__BC00',2);
2173                     pause(0.5);
2174                     setpv('SR01____FFBON__BC00',1);
2175                     StartFOFBFlag = 0;
2176                     pause(1);
2177                     FOFBOnStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2178                         getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2179                         getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2180                         getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2181                     if any(FOFBOnStatus==0) | any(FOFBOnStatus==2)
2182                         setpv('SR01____FFBON__BC00',2); % open FOFB loop
2183                         disp('************************************************************************************************************');
2184                         disp('** Problem turning on Fast Orbit Feedback system...                                                       **');
2185                         disp('** Check status of ffbsecXX crates - but remember that a crate reboot will turn off Quads in that sector! **');
2186                         disp('** Suggest disabling the "Fast Orbit Correction" checkbox and starting Orbit Feedback again.              **');
2187                         disp('************************************************************************************************************');
2188                     else
2189                         fprintf('   Starting Fast Orbit Feedback at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
2190                     end
2191                 end
2192
2193
2194                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2195                 % Horizontal plane "feedback" %
2196                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2197
2198                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxSOFB'),'Value') == 1
2199
2200                     % Get orbit and check that the BPMs are different from the last update
2201                     Xnew = getx(FB.OCSx.BPM.DeviceList);
2202
2203                     % Don't feedback if the current is too small
2204                     if getdcct < 5
2205                         FEEDBACK_STOP_FLAG = 1;
2206                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2207                         break;
2208                     end
2209
2210                     x = Xgoal - Xnew;
2211                     STDx = norm(x)/sqrt(length(x));
2212
2213                     if any(Xold == Xnew)
2214                         a = clock;
2215                         N_Stale_Data_Points = find((Xold==Xnew)==1);
2216                         for loop = N_Stale_Data_Points'
2217                             fprintf('   Stale data: BPMx(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSx.BPM.DeviceList(loop,1), FB.OCSx.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2218                         end
2219                     else
2220                         % Compute horizontal correction
2221                         %%%OCSx0 = FB.OCSx;
2222                         FB.OCSx.BPM.Data = Xnew;
2223                         FB.OCSx = orbitcorrectionmethods(FB.OCSx, Smatx, Sx, Ux, Vx);
2224
2225                         %%%[FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
2226
2227                         % reduced feedback gain (implemented by Greg Portmann, December 2000)
2228                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2229                         % increased back to 0.8 C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2230                         % increased to 1.0, C. Steier, 2002-05-04, trim DACs
2231                         X = Xgain .* FB.OCSx.CM.Delta;
2232                         X(N_HCM+1) = 0.3*FB.OCSx.DeltaRF/4.988e-3;
2233                         %%%X = Xgain .* (FB.OCSx.CM.Data - OCSx0.CM.Data);
2234
2235                         % check for trim values+next step values, warn or stop FB as necessary
2236                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2237                         % need to extract Chicanes from this comparison or maybe check them first for range %
2238                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2239                         HCMtrimSP=getpv('HCM','Trim',HCMlist1);
2240                         HCMtrimSP_next = HCMtrimSP + X(1:N_HCM);
2241                         if max(abs(HCMtrimSP_next)) > 4
2242                             HCMtrimnum=find(abs(HCMtrimSP_next) > 4);
2243
2244                             % print message to screen
2245                             fprintf('**One or more of the horizontal correctors is at its maximum!! Stopping orbit feedback. \n');
2246                             fprintf('%s\n',datestr(now));
2247                             for loop = HCMtrimnum'
2248                                 fprintf('**%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2249                             end
2250
2251                             % send alphapage to operator pager
2252                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2253                             FEEDBACK_STOP_FLAG = 1;
2254
2255                             setpv('SR_STATE', -5);
2256                             [StateNumber, StateString] = getsrstate;
2257                             if StateNumber >= 0
2258                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2259                             else
2260                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2261                             end
2262                         end
2263
2264                         if FEEDBACK_STOP_FLAG == 1
2265                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2266                             if getpv('SR01____FFBON__BC00')==1
2267                                 disp('   Stopping Fast Orbit Feedback.');
2268                             end
2269                             setpv('SR01____FFBON__BC00',0);
2270                             pause(0.5);
2271                             setpv('SR01____FFBON__BC00',2);
2272                             break;
2273                         end
2274
2275                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2276                         pause(0);
2277
2278                         if max(abs(HCMtrimSP_next) > 3)
2279                             HCMtrimnum=find(abs(HCMtrimSP_next) > 3);
2280                             HWarnNum=HWarnNum+1;
2281                             if (HWarnNum==1 | rem(HWarnNum,120)==0)
2282
2283                                 % print message to screen every two minutes
2284                                 fprintf('**One or more of the horizontal corrector trims is above 3A or below -3A! \n');
2285                                 fprintf('%s\n',datestr(now));
2286                                 for loop = HCMtrimnum'
2287                                     fprintf('**%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2288                                 end
2289                                 fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2290
2291                                 %send alphapage to operator pager the first time then at 10 minutes
2292                                 if (HWarnNum==1 | HWarnNum==600)
2293                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageHCM.txt
2294                                 end
2295                             end
2296                         else
2297                             HWarnNum=0;
2298                         end
2299
2300                         % Don't feedback if the current is too small
2301                         if getdcct < 5
2302                             FEEDBACK_STOP_FLAG = 1;
2303                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2304                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2305                             break;
2306                         end
2307
2308                         if N_HCM > 0
2309                             steppv('HCM','Trim', X(iNotHCMChicane), HCMlist1(iNotHCMChicane,:), 0);
2310                             steppv('HCM','Setpoint', X(iHCMChicane), HCMlist1(iHCMChicane,:), 0);
2311                         end
2312
2313                         % write fast orbit feedback setpoints
2314                         if 1
2315                             %write_goldenorbit_ffb_2planes(1, Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM)+Sx3*X(length(X))/20, BPMlist1);
2316                             % should be corrected to include result of next frequency step ...
2317                             write_goldenorbit_ffb_2planes(1,Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM),BPMlist1);
2318                         end
2319
2320                         %fprintf('Horizontal Done: %f \n',gettime-t00);
2321
2322                         % RF feedback
2323                         HQMOFMsp_last = getpv('EG______HQMOFM_AC01');
2324
2325                         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2326                             if N_RFMO > 0
2327                                 if abs(X(end)/3) < .01
2328                                     % if abs(FB.OCSx.DeltaRF/3) < .01
2329                                     steppv('EG______HQMOFM_AC01', X(end));
2330                                 else
2331                                     steppv('EG______HQMOFM_AC01', 0.01*sign(X(end)));
2332                                 end
2333                             end
2334
2335                             HQMOFMsp_now = getpv('EG______HQMOFM_AC01');
2336
2337                             % Check for stale RF feedback
2338                             if HQMOFMsp_last == HQMOFMsp_now
2339                                 HQMOFM_stalenum = HQMOFM_stalenum + 1;
2340                                 if HQMOFM_stalenum == 30 % warn and message to pager if stale for 30 secs
2341                                     fprintf('**The RF is not responding to orbit feedback changes! \n');
2342                                     fprintf('%s\n',datestr(now));
2343                                     fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2344                                     fprintf('**ILC 73 controls the EG______HQMOFM_AC01 channel, which sets the RF frequency. \n');
2345                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstaleRFmessage.txt
2346                                 end
2347                                 if rem(HQMOFM_stalenum,120)==0 % message to screen every 2 minutes
2348                                     fprintf('**The RF is not responding to orbit feedback changes! (%s)\n',datestr(now));
2349                                 end
2350                             else
2351                                 HQMOFM_stalenum = 0;
2352                             end
2353
2354                         end
2355
2356                         %fprintf('RF Done: %f \n',gettime-t00);
2357
2358                         Xold = Xnew;
2359                     end % End horizontal correction
2360
2361
2362                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2363                     % Vertical plane "feedback" %
2364                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2365
2366                     % Get orbit and check that the BPMs are different from the last update
2367                     Ynew = gety(FB.OCSy.BPM.DeviceList);
2368
2369                     % Don't feedback if the current is too small
2370                     if getdcct < 5
2371                         FEEDBACK_STOP_FLAG = 1;
2372                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2373                         break;
2374                     end
2375
2376                     y = Ygoal - Ynew;
2377                     STDy = norm(y)/sqrt(length(y));
2378
2379                     if any(Yold == Ynew)
2380                         a = clock;
2381                         N_Stale_Data_Points = find((Yold==Ynew)==1);
2382                         for loop = N_Stale_Data_Points'
2383                             fprintf('   Stale data: BPMy(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSy.BPM.DeviceList(loop,1), FB.OCSy.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2384                         end
2385
2386                     else
2387
2388                         % Compute vertical correction
2389                         %%%OCSy0 = FB.OCSy;
2390                         FB.OCSy.BPM.Data = Ynew;
2391                         FB.OCSy = orbitcorrectionmethods(FB.OCSy, Smaty, Sy, Uy, Vy);
2392
2393                         %%%[FB.OCSy, RF, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
2394
2395                         % reduced feedback gain, C. Steier, 2001-03-25
2396                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2397                         % increased back to 0.8, C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2398                         % set to unity gain, C. Steier, 2002-05-04, trim DACs
2399                         Y = Ygain .* FB.OCSy.CM.Delta;
2400                         %%%Y = Ygain .* (FB.OCSy.CM.Data - OCSy0.CM.Data);
2401
2402                         % Just SVD correction
2403                         % warning('Not using "micado" correction in the vertical plane.');
2404
2405                         % check for trim values+next step values, warn or stop FB as necessary
2406                         VCMtrimSP = getpv('VCM','Trim',VCMlist1);
2407                         VCMtrimSP_next = VCMtrimSP + Y(1:N_VCM);
2408                         if max(abs(VCMtrimSP_next)) > 12
2409                             VCMtrimnum=find(abs(VCMtrimSP_next) > 12);
2410
2411                             % print message to screen
2412                             fprintf('**One or more of the vertical correctors is at its maximum!! Stopping orbit feedback. \n');
2413                             fprintf('%s\n',datestr(now));
2414                             for loop = VCMtrimnum'
2415                                 fprintf('**%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2416                             end
2417
2418                             % send alphapage to operator pager
2419                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2420                             FEEDBACK_STOP_FLAG = 1;
2421
2422                             setpv('SR_STATE', -5);
2423                             [StateNumber, StateString] = getsrstate;
2424                             if StateNumber >= 0
2425                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2426                             else
2427                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2428                             end
2429                         end
2430
2431                         if FEEDBACK_STOP_FLAG == 1
2432                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2433                             if getpv('SR01____FFBON__BC00')==1
2434                                 disp('   Stopping Fast Orbit Feedback.');
2435                             end
2436                             setpv('SR01____FFBON__BC00',0);
2437                             pause(0.5);
2438                             setpv('SR01____FFBON__BC00',2);
2439                             break;
2440                         end
2441
2442                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2443                         % pause(0);
2444
2445                         if max(abs(VCMtrimSP_next) > 4)
2446                             VCMtrimnum=find(abs(VCMtrimSP_next) > 4);
2447                             VWarnNum=VWarnNum+1;
2448                             if (VWarnNum==1 | rem(VWarnNum,120)==0)
2449
2450                                 % print message to screen every two minutes
2451                                 fprintf('**One or more of the vertical corrector trims is above 4A or below -4A! \n');
2452                                 fprintf('%s\n',datestr(now));
2453                                 for loop = VCMtrimnum'
2454                                     fprintf('**%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2455                                 end
2456                                 fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2457
2458                                 %send alphapage to operator pager the first time then at 10 minutes
2459                                 if (VWarnNum==1 | VWarnNum==600)
2460                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageVCM.txt
2461                                 end
2462                             end
2463                         else
2464                             VWarnNum=0;
2465                         end
2466
2467                         % Don't feedback if the current is too small
2468                         if getdcct < 5
2469                             FEEDBACK_STOP_FLAG = 1;
2470                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2471                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2472                             break;
2473                         end
2474
2475                         if N_VCM > 0
2476                             steppv('VCM','Trim', Y(iNotVCMChicane), VCMlist1(iNotVCMChicane,:), 0);
2477                             steppv('VCM','Setpoint', Y(iVCMChicane), VCMlist1(iVCMChicane,:), 0);
2478                         end
2479
2480                         % write fast orbit feedback setpoints
2481                         if 1
2482                             write_goldenorbit_ffb_2planes(2,Ynew(1:size(BPMlist1,1))+Sy1*Y(1:N_VCM),BPMlist1);
2483                         end
2484
2485                     end
2486
2487                     Yold = Ynew;
2488
2489                     %fprintf('Vertical Done: %f \n',gettime-t00);
2490                 end % End vertical correction
2491
2492
2493                 %%%%%%%%%%%%%%%%%%%%%
2494                 % Tune feed forward %
2495                 %%%%%%%%%%%%%%%%%%%%%
2496                 % We should do a Sector limit check
2497
2498                 tic;
2499                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxTune'),'Value') == 1
2500
2501                     if strcmp(SR_Mode, '1.9 GeV, High Tune') || strcmp(SR_Mode, '1.9 GeV, Inject at 1.23') || strcmp(SR_Mode, '1.9 GeV, Two-Bunch')
2502
2503                         addQFsp = zeros(24,1);
2504                         addQDsp = zeros(24,1);
2505
2506                         if strcmp(FFTypeFlag,'Local')
2507                             disp('  No local tune compensation available - global is the default now.');
2508                         elseif strcmp(FFTypeFlag,'Global')
2509
2510                             % The vectorized gets were put outside of loop for speed reasons
2511                             %
2512                             % should also set up QFfac, Quadelem, Quadlist structures outside loop
2513                             actualgap = getid(IDSector);
2514                             [gapmin,gapmax] = gaplimit(IDSector);
2515                             corrind = find(actualgap<(gapmin-1));
2516                             actualgap(corrind)=gapmax(corrind);
2517                             Shift=zeros(size(actualgap));
2518                             Shift(EPUlist)=getpv('EPU');
2519
2520                             IDchangedList=find((abs(actualgap-oldgap)>0.005) | (abs(Shift-oldShift)>0.005));
2521
2522                             if ~isempty(IDchangedList)
2523
2524                                 oldgap=actualgap;
2525                                 oldShift=Shift;
2526
2527                                 % EPUs excite nux = .25 resonance in vertical linear polarization mode!
2528                                 % therefore with EPU tune feedforward
2529                                 % running, we want to move our nominal working point away (just below) the .25 resonance.
2530                                 %
2531                                 % The following tune correction moves nominal
2532                                 % nu_x from .25 to .245 - this should be enough for well set up lattices.
2533                                 %
2534                                 % 24 QF+ 24 QD
2535                                 DeltaAmps = inv(SR_TUNE_MATRIX) * [-0.005;0];    %  DelAmps =  [QF; QD];
2536                                 addQFsp = addQFsp + DeltaAmps(1,:);
2537                                 addQDsp = addQDsp + DeltaAmps(2,:);
2538
2539                                 for gapnum = 1:length(actualgap)
2540
2541                                     % Change in tune and [QF;QD] from maximum gap
2542
2543                                     if (IDSector(gapnum,1) == 4) | (IDSector(gapnum,1) == 11)
2544                                         if IDSector(gapnum,2) == 1
2545                                             modenamestr = sprintf('SR%02dU___ODS1M__DC00',IDSector(gapnum,1));
2546                                         else % if IDSector(gapnum,2) == 2
2547                                             modenamestr = sprintf('SR%02dU___ODS2M__DC00',IDSector(gapnum,1));
2548                                         end
2549                                         epumode = getpvonline(modenamestr);
2550                                         if IDSector(gapnum,2)==2
2551                                             longshift=3;
2552                                         else
2553                                             longshift=0;
2554                                         end
2555                                         if (epumode==0) & (any(IDSector(gapnum,:)~=[11 1]))      % antiparallel tables need to be fit to data so that they could be used here
2556                                             DeltaNuX = shift2tune(IDSector(gapnum,1),actualgap(gapnum),Shift(gapnum)+longshift,SR_GeV);
2557                                             DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);   % variation of vertical tune shift with phase is small for EPUs
2558                                         else
2559                                             DeltaNuX = 0;
2560                                             DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);   % variation of vertical tune shift with phase is small for EPUs
2561                                         end
2562
2563                                     else
2564                                         DeltaNuX = 0;
2565                                         DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);
2566                                     end
2567
2568                                     DelQF = zeros(length(QFsp),1);
2569                                     DelQD = zeros(length(QFsp),1);
2570
2571                                     fraccorr = 0.8*DeltaNuY ./ TuneW16Min;
2572
2573                                     % Find which quads to change (local beta beating correction
2574                                     % (horizontal for EPU, vertical otherwise)
2575                                     QuadList = [IDSector(gapnum,1)-1 2; IDSector(gapnum,1) 1];
2576                                     QuadElem = dev2elem('QF',QuadList); % in reality use QF and QD ...
2577
2578                                     % global vertical tune correction
2579                                     % 24 QF+ 24 QD
2580                                     DeltaAmps = inv(SR_TUNE_MATRIX) * [(fraccorr*6.23e-4); fraccorr*(-0.05301)];    %  DelAmps =  [QF; QD];
2581                                     DelQF = DelQF + DeltaAmps(1,:);
2582                                     DelQD = DelQD + DeltaAmps(2,:);
2583
2584                                     % local horizontal tune correction (is also nearly a beta beating correction) only nonzero for EPUs!
2585                                     % 2 QF + 2 QD
2586                                     DeltaAmpsLocal = 12*inv(SR_TUNE_MATRIX) * [-DeltaNuX;0];                       %  DelAmps =  [QF; QD];
2587                                     DelQF(QuadElem) = DelQF(QuadElem)+DeltaAmpsLocal(1,1);
2588                                     DelQD(QuadElem) = DelQD(QuadElem)+DeltaAmpsLocal(2,1);
2589
2590                                     % local vertical beta beating correction (should be used together with above global tune correction)
2591                                     % set to zero for EPUs, since their vertical tune shift is small
2592                                     % 2 QF + 2QD
2593                                     if (IDSector(gapnum,1)==6) | (IDSector(gapnum,1)==7) | (IDSector(gapnum,1)==10) | (IDSector(gapnum,1)==11)
2594                                         QFfac = ([2.243127/2.237111; 2.243127/2.237111]-1) * fraccorr;
2595                                         QDfac = ([2.556392/2.511045; 2.556392/2.511045]-1) * fraccorr;
2596                                     elseif (IDSector(gapnum,1)==5) | (IDSector(gapnum,1)==9)
2597                                         QFfac = ([2.225965/2.219784; 2.243096/2.237111]-1) * fraccorr;
2598                                         QDfac = ([2.528950/2.483259; 2.556345/2.511045]-1) * fraccorr;
2599                                     elseif (IDSector(gapnum,1)==4) | (IDSector(gapnum,1)==8) | (IDSector(gapnum,1)==12)
2600                                         QFfac = ([2.243096/2.237111; 2.225965/2.219784]-1) * fraccorr;
2601                                         QDfac = ([2.556345/2.511045; 2.528950/2.483259]-1) * fraccorr;
2602                                     else
2603                                         QFfac = zeros(2,1);
2604                                         QDfac = zeros(2,1);
2605                                     end
2606
2607                                     DelQF(QuadElem,:) = DelQF(QuadElem,:) + QFfac.*QFsp(QuadElem,:);
2608                                     DelQD(QuadElem,:) = DelQD(QuadElem,:) + QDfac.*QDsp(QuadElem,:);
2609
2610                                     % add all tune and beta beating corrections for this one ID to the summed up correction vectors for all IDs
2611                                     addQFsp = addQFsp+DelQF;
2612                                     addQDsp = addQDsp+DelQD;
2613
2614                                 end
2615
2616                                 % Set quadrupoles using main setpoint channels
2617                                 setpv('QF', QFsp+addQFsp,[], 0);
2618                                 setpv('QD', QDsp+addQDsp,[], 0);
2619                                 % % Set quadrupoles using FF setpoint channels
2620                                 % setpv('QF', 'FF', addQFsp, [], 0);
2621                                 % setpv('QD', 'FF', addQDsp, [], 0);
2622                             end
2623
2624                         else
2625                             error('Unknown type selected for tune FF');
2626                         end
2627
2628                     else
2629                         disp('  No tune FF algorithm for non-production modes yet...');
2630                     end
2631                 end
2632
2633                 ffdeltaquad_delay = toc;
2634                 %fprintf('tune FF delay = %.1f seconds\n',ffdeltaquad_delay);
2635                 % fprintf('Tune Done: %f \n',gettime-t00);
2636
2637                 % Output info to screen
2638                 set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
2639                 set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
2640                 %pause(0);
2641
2642                 FOFBStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2643                     getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2644                     getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2645                     getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2646                 for loop = 1:size(FOFBStatus,2)
2647                     if FOFBStatus(loop)==0
2648                         FOFBStatusStr(loop,:) = 'OFF ';
2649                     elseif FOFBStatus(loop)==1
2650                         FOFBStatusStr(loop,:) = 'ON  ';
2651                     elseif FOFBStatus(loop)==2
2652                         FOFBStatusStr(loop,:) = 'OPEN';
2653                     else
2654                         FOFBStatusStr(loop,:) = 'BAD ';
2655                     end
2656                 end
2657                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 %s',FOFBStatusStr(1,:)),'ForegroundColor',[0 0 0]);
2658                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 %s',FOFBStatusStr(2,:)),'ForegroundColor',[0 0 0]);
2659                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 %s',FOFBStatusStr(3,:)),'ForegroundColor',[0 0 0]);
2660                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 %s',FOFBStatusStr(4,:)),'ForegroundColor',[0 0 0]);
2661                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 %s',FOFBStatusStr(5,:)),'ForegroundColor',[0 0 0]);
2662                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 %s',FOFBStatusStr(6,:)),'ForegroundColor',[0 0 0]);
2663                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 %s',FOFBStatusStr(7,:)),'ForegroundColor',[0 0 0]);
2664                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 %s',FOFBStatusStr(8,:)),'ForegroundColor',[0 0 0]);
2665                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 %s',FOFBStatusStr(9,:)),'ForegroundColor',[0 0 0]);
2666                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 %s',FOFBStatusStr(10,:)),'ForegroundColor',[0 0 0]);
2667                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 %s',FOFBStatusStr(11,:)),'ForegroundColor',[0 0 0]);
2668                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 %s',FOFBStatusStr(12,:)),'ForegroundColor',[0 0 0]);
2669
2670
2671                 %fprintf('End of feedback operations: %f \n\n',gettime-t00);
2672
2673                 % Wait for next update time or stop request
2674                 while (gettime-t00) < LoopDelay
2675                     %disp('interval could be shorter')
2676                     pause(.05);
2677                     % Check if GUI has been closed
2678                     if isempty(gcbf)
2679                         FEEDBACK_STOP_FLAG = 1;
2680                         lasterr('SRCONTROL GUI DISAPPEARED!');
2681                         error('SRCONTROL GUI DISAPPEARED!');
2682                     end
2683
2684                     % Check if Stop button was pressed
2685                     if FEEDBACK_STOP_FLAG == 1
2686                         % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2687                         if getpv('SR01____FFBON__BC00')==1
2688                             disp('   Stopping Fast Orbit Feedback.');
2689                         end
2690                         setpv('SR01____FFBON__BC00',0);
2691                         pause(0.5);
2692                         setpv('SR01____FFBON__BC00',2);
2693                         break;
2694                     end
2695                 end
2696
2697
2698                 if FEEDBACK_STOP_FLAG == 1
2699                     % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2700                     if getpv('SR01____FFBON__BC00')==1
2701                         disp('   Stopping Fast Orbit Feedback.');
2702                     end
2703                     setpv('SR01____FFBON__BC00',0);
2704                     pause(0.5);
2705                     setpv('SR01____FFBON__BC00',2);
2706                     break;
2707                 end
2708
2709                 StartErrorTime = gettime;
2710
2711             catch
2712
2713                 fprintf('\n  %s \n',lasterr);
2714
2715                 % Quit if error exists for more than 20 seconds
2716                 if gettime-StartErrorTime>20 | FEEDBACK_STOP_FLAG==1
2717                     fprintf('%s  Orbit feedback stopped due to error condition. \n\n',datestr(now));
2718
2719                     %send alphapage to operator pager
2720                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2721                     FEEDBACK_STOP_FLAG = 1;
2722
2723                     setpv('SR_STATE', -5);
2724                     [StateNumber, StateString] = getsrstate;
2725                     if StateNumber >= 0
2726                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2727                     else
2728                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2729                     end
2730                 else
2731                     a = clock;
2732                     fprintf('   Orbit feedback was paused due to error condition (%s %d:%d:%.0f). \n', date, a(4), a(5), a(6));
2733                     fprintf('   Orbit feedback has automatically restarted and is running. \n\n');
2734                 end
2735
2736             end
2737
2738             if FEEDBACK_STOP_FLAG == 1
2739                 % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2740                 if getpv('SR01____FFBON__BC00')==1
2741                     disp('   Stopping Fast Orbit Feedback.');
2742                 end
2743                 setpv('SR01____FFBON__BC00',0);
2744                 pause(0.5);
2745                 setpv('SR01____FFBON__BC00',2);
2746                 break;
2747             end
2748
2749             %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2750
2751             %pause(0);
2752
2753             % this loop delays turn on of Fast Feedback system
2754             if FBloopIter < 5
2755                 FBloopIter = FBloopIter + 1;
2756             end
2757
2758         end  % End of feedback loop
2759
2760
2761         % End feedback, reset all parameters
2762         try
2763
2764             % Enable buttons
2765             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','on');
2766             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','off');
2767             set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','on');
2768             set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','on');
2769             set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','on');
2770             set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','on');
2771             set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','on');
2772             set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','on');
2773             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','on');
2774             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','on');
2775             set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','on');
2776             set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','on');
2777             set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','on');
2778
2779             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = _____ mm'),'ForegroundColor',[0 0 0]);
2780             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = _____ mm'),'ForegroundColor',[0 0 0]);
2781
2782             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 ____'),'ForegroundColor',[0 0 0]);
2783             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 ____'),'ForegroundColor',[0 0 0]);
2784             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 ____'),'ForegroundColor',[0 0 0]);
2785             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 ____'),'ForegroundColor',[0 0 0]);
2786             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 ____'),'ForegroundColor',[0 0 0]);
2787             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 ____'),'ForegroundColor',[0 0 0]);
2788             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 ____'),'ForegroundColor',[0 0 0]);
2789             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 ____'),'ForegroundColor',[0 0 0]);
2790             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 ____'),'ForegroundColor',[0 0 0]);
2791             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 ____'),'ForegroundColor',[0 0 0]);
2792             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 ____'),'ForegroundColor',[0 0 0]);
2793             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 ____'),'ForegroundColor',[0 0 0]);
2794
2795             %pause(0);
2796
2797         catch
2798
2799             % GUI must have been closed
2800
2801         end
2802
2803
2804         % >= 2 Hz update rate on IDBPMs
2805         disp('   IDBPM time constant set to 0.25s.');
2806         setbpmtimeconstant(0.25);
2807
2808
2809         a = clock;
2810         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2811         [StateNumber, StateString] = getsrstate;
2812         if StateNumber >= 0
2813             setpv('SR_STATE',5.1);
2814             [StateNumber, StateString] = getsrstate;
2815             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2816             fprintf('   ******************************\n');
2817             fprintf('   **  Orbit Feedback Stopped  **\n');
2818             fprintf('   ******************************\n\n');
2819         else
2820             [StateNumber, StateString] = getsrstate;
2821             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2822             fprintf('   ****************************************\n');
2823             fprintf('   **  Problem With Slow Orbit Feedback  **\n');
2824             fprintf('   ****************************************\n\n');
2825         end
2826         set(0,'showhiddenhandles','off');
2827         pause(0);
2828
2829
2830     case 'FeedbackSetup'
2831         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
2832
2833         if InitFlag
2834             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2835             % Edit the following lists to change default configuration of Orbit Correction %
2836             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2837
2838             % Corrector magnets
2839             listh=[
2840                 1 2;
2841                 1 8;
2842                 2 1;
2843                 2 8;
2844                 3 1;
2845                 3 8;
2846                 3 10; %SR04U_HCM2 (chicane trim)
2847                 4 1;
2848                 4 8;
2849                 5 1;
2850                 5 8;
2851                 %                 5 10; %SR06U_HCM2 (chicane trim)
2852                 6 1;
2853                 6 8;
2854                 7 1;
2855                 7 8;
2856                 8 1;
2857                 8 8;
2858                 9 1;
2859                 9 8;
2860                 10 1;
2861                 10 8;
2862                 10 10; %SR11U_HCM2 (chicane trim)
2863                 11 1;
2864                 11 8;
2865                 12 1;
2866                 12 7];
2867             listv=[
2868                 1 2;
2869                 1 8;
2870                 2 1;
2871                 2 8;
2872                 3 1;
2873                 3 7;
2874                 3 8;
2875                 3 10; %SR04U_VHCM2 (chicane trim)
2876                 4 1;
2877                 4 7;
2878                 4 8;
2879                 5 1;
2880                 5 8;
2881 %                 5 10; %SR06U_VHCM2 (chicane trim)
2882                 6 1;
2883                 6 8;
2884                 7 1;
2885                 7 8;
2886                 8 1;
2887                 8 8;
2888                 9 1;
2889                 9 8;
2890                 10 1;
2891                 10 2;
2892                 10 7;
2893                 10 8;
2894                 10 10; %SR11U_VHCM2 (chicane trim)
2895                 11 1;
2896                 11 7;
2897                 11 8;
2898                 12 1;
2899                 12 7];
2900
2901             Xivec = [1:27];
2902             Yivec = [1:31];
2903             HCMlist1 = listh;
2904             VCMlist1 = listv;
2905
2906             % Full BPM list
2907             BPMlist1 = [
2908                 1 2
2909                 1 5
2910                 1 6
2911                 1 10
2912                 2 1
2913                 2 5
2914                 2 6
2915                 2 9
2916                 3 2
2917                 3 5
2918                 3 6
2919                 3 10
2920                 3 11
2921                 3 12
2922                 4 1
2923                 4 5
2924                 4 6
2925                 4 10
2926                 5 1
2927                 5 5
2928                 5 6
2929                 5 10
2930 %                 5 11
2931 %                 5 12
2932                 6 1
2933                 6 5
2934                 6 6
2935                 6 10
2936                 7 1
2937                 7 5
2938                 7 6
2939                 7 10
2940                 8 1
2941                 8 5
2942                 8 6
2943                 8 10
2944                 9 1
2945                 9 5
2946                 9 6
2947                 9 10
2948                 10 1
2949                 10 5
2950                 10 6
2951                 10 10
2952                 10 11
2953                 10 12
2954                 11 1
2955                 11 5
2956                 11 6
2957                 11 10
2958                 12 1
2959                 12 5
2960                 12 6
2961                 12 9
2962                 ];
2963
2964             % remove Bergoz BPMs in SR01 and SR03 for 2-bunch (noisy at low currents) and drop singular values
2965             if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
2966                     BPMlist1 = [
2967                          %1 2
2968                          1 5
2969                          1 6
2970                          1 10
2971                          2 1
2972                          2 5
2973                          2 6
2974                          %2 9
2975                          %3 2
2976                          3 5
2977                          3 6
2978                          3 10
2979                          3 11
2980                          3 12
2981                          4 1
2982                          4 5
2983                          4 6
2984                          4 10
2985                          5 1
2986                          5 5
2987                          5 6
2988                          5 10
2989                          5 11
2990                          5 12
2991                          6 1
2992                          6 5
2993                          6 6
2994                          6 10
2995                          7 1
2996                          7 5
2997                          7 6
2998                          7 10
2999                          8 1
3000                          8 5
3001                          8 6
3002                          8 10
3003                          9 1
3004                          9 5
3005                          9 6
3006                          9 10
3007                          10 1
3008                          10 5
3009                          10 6
3010                          10 10
3011                          10 11
3012                          10 12
3013                          11 1
3014                          11 5
3015                          11 6
3016                          11 10
3017                          12 1
3018                          12 5
3019                          12 6
3020                          %12 9
3021                          ];
3022             end
3023
3024             OCSx.BPM = getx(BPMlist1, 'struct');
3025             OCSx.CM = getsp('HCM', HCMlist1, 'struct');
3026             OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
3027             OCSx.NIter = 1;
3028             OCSx.SVDIndex = Xivec;
3029             OCSx.IncrementalFlag = 'No';
3030             OCSx.BPMWeight = {[]};
3031             OCSx.FitRF = 0;
3032             OCSy.BPM = gety(BPMlist1, 'struct');
3033             OCSy.CM = getsp('VCM', VCMlist1, 'struct');
3034             OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
3035             OCSy.NIter = 1;
3036             OCSy.SVDIndex = Yivec;
3037             OCSy.IncrementalFlag = 'No';
3038             OCSy.BPMWeight = {[]};
3039             OCSy.FitRF = 0;
3040             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
3041             % do we need these Smat calls? %
3042             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
3043             SXmat = getrespmat(OCSx.BPM, OCSx.CM, 'numeric');
3044             SYmat = getrespmat(OCSy.BPM, OCSy.CM, 'numeric');
3045             % [OCSx, Sx, Ux, Vx] = orbitcorrectionmethods(OCSx, SXmat);
3046             % [OCSy, Sy, Uy, Vy] = orbitcorrectionmethods(OCSy, SYmat);
3047
3048             % initialize FFTypeFlag
3049             FFTypeFlag = 'Global';
3050
3051         else
3052
3053             % Get vectors
3054             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
3055             % the two lines below seem to fix BPMlist editing problem
3056             OCSx = FB.OCSx;
3057             OCSy = FB.OCSy;
3058             BPMlist1 = FB.BPMlist1;
3059             HCMlist1 = FB.HCMlist1;
3060             VCMlist1 = FB.VCMlist1;
3061             Xivec = FB.Xivec;
3062             Yivec = FB.Yivec;
3063             Xgoal = FB.OCSx.GoalOrbit;
3064             OCSx.GoalOrbit = Xgoal;
3065             Ygoal = FB.OCSy.GoalOrbit;
3066             OCSy.GoalOrbit = Ygoal;
3067             FFTypeFlag = FB.FFTypeFlag;
3068
3069
3070             % FF corrector magnet list
3071             ListFF = [
3072                 4     2
3073                 4     8
3074                 5     1
3075                 5     7
3076 %               5     8 % why are these out???
3077 %               6     1 % why are these out???
3078                 6     8
3079                 7     1
3080                 7     8
3081                 8     1
3082                 8     8
3083                 9     1
3084                 9     8
3085                 10    1
3086                 11    8
3087                 12    1];
3088             ElemFF = dev2elem('HCM',ListFF);
3089
3090
3091             % Add button to change #ivectors, cm, IDBPMs,
3092             EditFlag = 0;
3093             h_fig1 = figure;
3094             while EditFlag ~= 6
3095
3096                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
3097                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
3098
3099                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
3100                     DispOrbit = getdisp('BPMx', BPMlist1);
3101                     Sx = [Sx DispOrbit];
3102                 end
3103
3104                 [Ux, SVx, Vx] = svd(Sx);
3105                 [Uy, SVy, Vy] = svd(Sy);
3106
3107
3108                 % Remove singular values greater than the actual number of singular values
3109                 i = find(Xivec>length(diag(SVx)));
3110                 if ~isempty(i)
3111                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
3112                     pause(0);
3113                     Xivec(i) = [];
3114                 end
3115                 i = find(Yivec>length(diag(SVy)));
3116                 if ~isempty(i)
3117                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
3118                     pause(0);
3119                     Yivec(i) = [];
3120                 end
3121
3122
3123                 Ax = Sx*Vx(:,Xivec);
3124                 Tx = inv(Ax'*Ax)*Ax';
3125
3126                 Ay = Sy*Vy(:,Yivec);
3127                 Ty = inv(Ay'*Ay)*Ay';
3128
3129                 figure(h_fig1);
3130                 subplot(2,1,1);
3131                 semilogy(diag(SVx),'b');
3132                 hold on;
3133                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
3134                 ylabel('Horizontal');
3135                 title('Response Matrix Singular Values');
3136                 hold off;
3137                 subplot(2,1,2);
3138                 semilogy(diag(SVy),'b');
3139                 hold on;
3140                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
3141                 xlabel('Singular Value Number');
3142                 ylabel('Vertical');
3143                 hold off;
3144                 drawnow;
3145
3146                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List', ...
3147                     'BPM List','Change the Goal Orbit','Continue');
3148
3149                 if EditFlag == 1
3150                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
3151                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
3152                     titlestr='SVD Orbit Feedback';
3153                     lineNo=1;
3154                     answer=inputdlg(prompt,titlestr,lineNo,def);
3155                     if ~isempty(answer)
3156                         XivecNew = fix(str2num(answer{1}));
3157                         if isempty(XivecNew)
3158                             disp('   Horizontal E-vector cannot be empty.  No change made.');
3159                         else
3160                             if any(XivecNew<=0) | max(XivecNew)>length(diag(SVx))
3161                                 disp('   Error reading horizontal E-vector.  No change made.');
3162                             else
3163                                 Xivec = XivecNew;
3164                             end
3165                         end
3166                         YivecNew = fix(str2num(answer{2}));
3167                         if isempty(YivecNew)
3168                             disp('   Vertical E-vector cannot be empty.  No change made.');
3169                         else
3170                             if any(YivecNew<=0) | max(YivecNew)>length(diag(SVy))
3171                                 disp('   Error reading vertical E-vector.  No change made.');
3172                             else
3173                                 Yivec = YivecNew;
3174                             end
3175                         end
3176                     end
3177                 end
3178
3179                 if EditFlag == 2
3180                     List= getlist('HCM','Trim');
3181                     CheckList = zeros(96,1);
3182                     Elem = dev2elem('HCM', HCMlist1);
3183                     CheckList(Elem) = ones(size(Elem));
3184                     CheckList = CheckList(dev2elem('HCM',List));
3185
3186                     % Remove FF corrrectors
3187                     %           Elem = dev2elem('HCM',List);
3188                     %           for j = length(ElemFF):-1:1
3189                     %              i = find(Elem==ElemFF(j));
3190                     %              Elem(i,:) = [];
3191                     %              List(i,:) = [];
3192                     %              CheckList(i,:) = [];
3193                     %           end
3194
3195                     newList = editlist(List, 'HCMtrim', CheckList);
3196
3197                     if isempty(newList)
3198                         fprintf('   WARNING: Horizontal corrector magnet list is empty!\n');
3199                         HCMlist1 = newList;
3200                     else
3201                         HCMlist1 = newList;
3202                     end
3203                     OCSx.CM.DeviceList = HCMlist1;
3204                 end
3205
3206                 if EditFlag == 3
3207                     List = getlist('VCM','Trim');
3208                     CheckList = zeros(96,1);
3209                     Elem = dev2elem('VCM', VCMlist1);
3210                     CheckList(Elem) = ones(size(Elem));
3211                     CheckList = CheckList(dev2elem('VCM',List));
3212
3213                     % Remove FF corrrectors
3214                     %           Elem = dev2elem('VCM',List);
3215                     %           for j = length(ElemFF):-1:1
3216                     %              i = find(Elem==ElemFF(j));
3217                     %              Elem(i,:) = [];
3218                     %              List(i,:) = [];
3219                     %              CheckList(i,:) = [];
3220                     %           end
3221
3222                     newList = editlist(List, 'VCMtrim', CheckList);
3223
3224                     if isempty(newList)
3225                         fprintf('   WARNING: Vertical corrector magnet list is empty!\n');
3226                         VCMlist1 = newList;
3227                     else
3228                         VCMlist1 = newList;
3229                     end
3230                     OCSy.CM.DeviceList = VCMlist1;
3231                 end
3232
3233                 if EditFlag == 4
3234                     ListOld = BPMlist1;
3235                     XgoalOld = Xgoal;
3236                     YgoalOld = Ygoal;
3237
3238                     % Full BPM list
3239                     List = [
3240                         1 2
3241                         1 5
3242                         1 6
3243                         1 10
3244                         2 1
3245                         2 5
3246                         2 6
3247                         2 9
3248                         3 2
3249                         3 5
3250                         3 6
3251                         3 10
3252                         3 11
3253                         3 12
3254                         4 1
3255                         4 5
3256                         4 6
3257                         4 10
3258                         5 1
3259                         5 5
3260                         5 6
3261                         5 10
3262                         5 11
3263                         5 12
3264                         6 1
3265                         6 5
3266                         6 6
3267                         6 10
3268                         7 1
3269                         7 5
3270                         7 6
3271                         7 10
3272                         8 1
3273                         8 5
3274                         8 6
3275                         8 10
3276                         9 1
3277                         9 5
3278                         9 6
3279                         9 10
3280                         10 1
3281                         10 5
3282                         10 6
3283                         10 10
3284                         10 11
3285                         10 12
3286                         11 1
3287                         11 5
3288                         11 6
3289                         11 10
3290                         12 1
3291                         12 5
3292                         12 6
3293                         12 9
3294                         ];
3295
3296
3297                     CheckList = zeros(size(List,1),1);
3298                     if ~isempty(BPMlist1)
3299                         for i = 1:size(List,1)
3300                             k = find(List(i,1)==BPMlist1(:,1));
3301                             l = find(List(i,2)==BPMlist1(k,2));
3302
3303                             if isempty(k) | isempty(l)
3304                                 % Item not in list
3305                             else
3306                                 CheckList(i) = 1;
3307                             end
3308                         end
3309                     end
3310
3311                     newList = editlist(List, 'BPM', CheckList);
3312                     if isempty(newList)
3313                         fprintf('   BPM list cannot be empty.  No change made.\n');
3314                     else
3315                         BPMlist1 = newList;
3316                     end
3317
3318                     % Set the goal orbit to the golden orbit
3319                     Xgoal = getgolden('BPMx', BPMlist1);
3320                     Ygoal = getgolden('BPMy', BPMlist1);
3321
3322
3323                     % If a new BPM is added, then set the goal orbit to the golden orbit
3324                     for i = 1:size(BPMlist1,1)
3325
3326                         % Is it a new BPM?
3327                         k = find(BPMlist1(i,1)==ListOld(:,1));
3328                         l = find(BPMlist1(i,2)==ListOld(k,2));
3329
3330                         if isempty(k) | isempty(l)
3331                             % New BPM
3332                         else
3333                             % Use the old value for old BPM
3334                             Xgoal(i) = XgoalOld(k(l));
3335                             Ygoal(i) = YgoalOld(k(l));
3336                         end
3337                     end
3338                     OCSx.BPM.DeviceList = BPMlist1;
3339                     OCSy.BPM.DeviceList = BPMlist1;
3340                     OCSx.GoalOrbit = Xgoal;
3341                     OCSy.GoalOrbit = Ygoal;
3342                 end
3343
3344                 if EditFlag == 5
3345                     ChangeList = editlist2(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
3346
3347                     for i = 1:size(ChangeList,1)
3348
3349                         k = find(ChangeList(i,1)==BPMlist1(:,1));
3350                         l = find(ChangeList(i,2)==BPMlist1(k,2));
3351
3352                         prompt={sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
3353                         def={sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
3354                         titlestr='CHANGE THE GOAL ORBIT';
3355                         lineNo=1;
3356                         answer = inputdlg(prompt, titlestr, lineNo, def);
3357
3358                         if isempty(answer)
3359                             % No change
3360                             fprintf('   No change was made to the golden orbit.\n');
3361                         else
3362                             Xgoalnew = str2num(answer{1});
3363                             if isempty(Xgoalnew)
3364                                 fprintf('   No change was made to the horizontal golden orbit.\n');
3365                             else
3366                                 Xgoal(k(l)) = Xgoalnew;
3367                             end
3368
3369                             Ygoalnew = str2num(answer{2});
3370                             if isempty(Ygoalnew)
3371                                 fprintf('   No change was made to the vertical golden orbit.\n');
3372                             else
3373                                 Ygoal(k(l)) = Ygoalnew;
3374                             end
3375                         end
3376                     end
3377                     if ~isempty(ChangeList)
3378                         fprintf('   Note:  Changing the goal orbit for "Slow Orbit Feedback" does not change the goal orbit for "Orbit Correction."\n');
3379                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
3380                     end
3381                     OCSx.GoalOrbit = Xgoal;
3382                     OCSy.GoalOrbit = Ygoal;
3383                 end
3384
3385 %                 if EditFlag == 6
3386 %                     FFTypeFlag = questdlg(sprintf('Do you want to use a fully local or a combined local/global compensation of IDs? (nuy=9.2 only)'),'Tune FF','Local','Global', 'Global');
3387 %                     if strcmp(FFTypeFlag,'Local')
3388 %                         disp(['   The tune FF will use 8 local quadrupoles to compensate beta beating and tune shift']);
3389 %                         disp(['   from each ID.']);
3390 %                     elseif strcmp(FFTypeFlag,'Global')
3391 %                         disp(['   The tune FF will use 4 local quadrupoles to compensate beta beating and all QF+QD']);
3392 %                         disp(['   to compensate tune shift from each ID.']);
3393 %                     end
3394 %                 end
3395
3396             end
3397             close(h_fig1);
3398         end
3399
3400         % Save vectors
3401         FB.Xivec = Xivec;
3402         FB.Yivec = Yivec;
3403         FB.HCMlist1 = HCMlist1;
3404         FB.VCMlist1 = VCMlist1;
3405         FB.BPMlist1 = BPMlist1;
3406
3407         OCSx.SVDIndex = Xivec;
3408         OCSy.SVDIndex = Yivec;
3409         FB.OCSx = OCSx;
3410         FB.OCSy = OCSy;
3411
3412         FB.FFTypeFlag = FFTypeFlag;
3413         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata',FB);
3414
3415
3416     case 'FastFeedbackSetup'
3417
3418         InitFlag = Input2;
3419
3420         if InitFlag
3421             FOFBFreq = 1000;
3422             % user operations 9/14-10/17/04: P=0.5, I=120, D=0.0015 (for both planes)
3423             % below are known good values for user ops as of 8-1-05
3424             HorP = 2;
3425             HorI = 300;
3426             HorD = 0.002;
3427             VertP = 1;
3428             VertI = 100;
3429             VertD = 0.0015;
3430
3431             % this initial set is now done in hwinit.m because it's not a good idea to set anything when srcontrol is launched
3432             % try
3433             %     setsp('SR01____FFBFREQAC00', FOFBFreq); % set freq
3434             %     write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3435             % catch
3436             %     disp('   Trouble setting Fast Orbit Feedback parameters!');
3437             % end
3438
3439         else
3440             % Get vectors
3441             FOFB = get(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata');
3442             FOFBFreq = FOFB.FOFBFreq;
3443             HorP  = FOFB.HorP;
3444             HorI  = FOFB.HorI;
3445             HorD  = FOFB.HorD;
3446             VertP = FOFB.VertP;
3447             VertI = FOFB.VertI;
3448             VertD = FOFB.VertD;
3449
3450             % Add button to change #ivectors, CMs, IDBPMs,
3451             EditFlag = 0;
3452             %h_fig1 = figure;
3453             while EditFlag ~= 3
3454
3455                 %EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'HCM List', 'VCM List', ...
3456                 %   'IDBPM List', 'BBPM List', 'Continue');
3457                 % Use menu below until other FFB config routines work (then also uncomment options 3,4,5,6 below)
3458                 EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'Continue');
3459
3460                 if EditFlag == 1
3461                     % change rate
3462
3463                     prompt={'Enter the desired Fast Feedback Frequency (1-1000 Hz)'};
3464                     def={num2str(FOFBFreq)};
3465                     titlestr='Fast Feedback Setup';
3466                     lineNo=1;
3467                     answer=inputdlg(prompt,titlestr,lineNo,def);
3468                     if ~isempty(answer)
3469                         FOFBFreq = fix(str2num(answer{1}));
3470                         if isempty(FOFBFreq)
3471                             disp('   Frequency value cannot be empty.  No change made.');
3472                             FOFBFreq = getsp('SR01____FFBFREQAC00');
3473                         else
3474                             if FOFBFreq < 1 | FOFBFreq > 1000
3475                                 disp('   Frequency must be between 1 and 1000 Hz.  No change made.');
3476                                 FOFBFreq = getsp('SR01____FFBFREQAC00');
3477                             end
3478                         end
3479                         setsp('SR01____FFBFREQAC00',FOFBFreq); % change freq
3480                         pause(0.5);
3481                         fprintf('   Fast orbit feedback frequency is running at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
3482                     else
3483                         FOFBFreq = getsp('SR01____FFBFREQAC00');
3484                     end
3485                 end
3486
3487                 if EditFlag == 2
3488                     % edit  PIDs
3489                     % User defaults are HorP=2, HorI=300, HorD=0.002, VertP=1, VertI=100, VertD=0.0015
3490                     prompt={'P horizontal', 'I horizontal', 'D horizontal', 'P vertical', 'I vertical', 'D vertical'};
3491                     def={num2str(HorP), num2str(HorI), num2str(HorD), num2str(VertP), num2str(VertI), num2str(VertD)};
3492                     titlestr='Fast Feedback PID Setup';
3493                     lineNo=1;
3494                     answer=inputdlg(prompt,titlestr,lineNo,def);
3495                     if ~isempty(answer)
3496                         HorPnewnum = str2num(answer{1});
3497                         if isempty(HorPnewnum)
3498                             disp('   HorP value cannot be empty.  No change made.');
3499                         else
3500                             HorP = HorPnewnum;
3501                         end
3502                         HorInewnum = str2num(answer{2});
3503                         if isempty(HorInewnum)
3504                             disp('   HorI value cannot be empty.  No change made.');
3505                         else
3506                             HorI = HorInewnum;
3507                         end
3508                         HorDnewnum = str2num(answer{3});
3509                         if isempty(HorDnewnum)
3510                             disp('   HorD value cannot be empty.  No change made.');
3511                         else
3512                             HorD = HorDnewnum;
3513                         end
3514                         VertPnewnum = str2num(answer{4});
3515                         if isempty(VertPnewnum)
3516                             disp('   VertP value cannot be empty.  No change made.');
3517                         else
3518                             VertP = VertPnewnum;
3519                         end
3520                         VertInewnum = str2num(answer{5});
3521                         if isempty(VertInewnum)
3522                             disp('   VertI value cannot be empty.  No change made.');
3523                         else
3524                             VertI = VertInewnum;
3525                         end
3526                         VertDnewnum = str2num(answer{6});
3527                         if isempty(VertDnewnum)
3528                             disp('   VertD value cannot be empty.  No change made.');
3529                         else
3530                             VertD = VertDnewnum;
3531                         end
3532
3533                         try
3534                             write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3535                             fprintf('   Setting FFB gains to Horizontal P=%.2f, I=%.1f, D=%.4f;  Vertical P=%.2f, I=%.1f, D=%.4f\n', HorP, HorI, HorD, VertP, VertI, VertD);
3536                         catch
3537                             disp('   Trouble setting Fast Orbit Feedback parameters!');
3538                         end
3539                     end
3540                 end
3541
3542                 %if EditFlag == 3
3543                 %   disp('   This function not yet available.');
3544                 %   % change HCM List
3545                 %end
3546                 %
3547                 %if EditFlag == 4
3548                 %   disp('   This function not yet available.');
3549                 %   % change VCM List
3550                 %end
3551                 %
3552                 %if EditFlag == 5
3553                 %   disp('   This function not yet available.');
3554                 %   % change IDBPM List
3555                 %end
3556                 %
3557                 %if EditFlag == 6
3558                 %   disp('   This function not yet available.');
3559                 %   % change BBPM List
3560                 %end
3561
3562             end
3563             %close(h_fig1);
3564         end
3565
3566         % Save vectors
3567         FOFB.FOFBFreq = FOFBFreq;
3568         FOFB.HorP = HorP;
3569         FOFB.HorI = HorI;
3570         FOFB.HorD = HorD;
3571         FOFB.VertP = VertP;
3572         FOFB.VertI = VertI;
3573         FOFB.VertD = VertD;
3574         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata',FOFB);
3575
3576     otherwise
3577         fprintf('   No action for %s.\n', action);
3578 end   % end case