Description of srcontrol5_20070325
Home > ALS > StorageRing > srcontrol5_20070325.m
srcontrol5_20070325
PURPOSE
srcontrol5
SYNOPSIS
function srcontrol5(action, Input2, Input3)
DESCRIPTION
 srcontrol5
 Storage ring control program
 This program controls all storage ring magnets, performs orbit feedback and
 tune feedforward and helps to diagnose problems in routine user operation
 of the ALS storage ring. It includes a gui to simplify the use of this
 program.
 It was originally programmed by Greg Portmann (until December 2000) with input
 from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
 and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
 The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
 Christoph Steier, July 2002
 SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
 Tom Scarvie, April 2005
CROSS-REFERENCE INFORMATION
This function calls:
bend2gev BEND2GEV - Compute the energy based on the ramp tables
checksrmags CHECKSRMAGS - Check SR power supplies against a lattice file
checksrorbit ErrorNums =checksrorbit(Sector, BPMxtolerance [.015 mm], [BPMytolerance [.015 mm]])
ffdeltaquad Sector
gaplimit [GapMin, GapMax] = gaplimit(ID_Number);
getff function [FFEnableBM, FFEnableBC, GapEnableBM, GapEnableBC, Sector] = getff(Sector)
getid GETID - Get the insertion device position, velocity, run flag, and user requested gap
getsrstate [StateNumber, StateString] = getsrstate
set_alarmhandler_AHU_thresholds_inject function set_alarmhandler_AHU_thresholds_inject
set_alarmhandler_thresholds set_alarmhandler_thresholds
set_alarmhandler_thresholds_new set_alarmhandler_thresholds_new
setbpmtimeconstant SETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
setbumps SETBUMPS - Make a straight section bump
setff function setff(Sector, FFEnableBC, GapEnableBC)
setid SETID - Set the insertion device vertical gap
setsrstatechannels
srcycle SRCYCLE - Storage ring cycle
srramp SRRAMP - Ramp the storage ring energy
write_goldenorbit_ffb function write_goldenorbit_ffb
write_goldenorbit_ffb_2planes WRITE_GOLDENORBIT_FFTB_2PLANES - Sets the BPM setpoints which are used by the fast feedback system
This function is called by:
SOURCE CODE
function srcontrol5(action, Input2, Input3)
% srcontrol5
% Storage ring control program
%
% This program controls all storage ring magnets, performs orbit feedback and
% tune feedforward and helps to diagnose problems in routine user operation
% of the ALS storage ring. It includes a gui to simplify the use of this
% program.
%
% It was originally programmed by Greg Portmann (until December 2000) with input
% from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
% and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
%
% The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
%
% Christoph Steier, July 2002
%
% SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
%
% Tom Scarvie, April 2005
% known bugs/problems (May 2001):
% - IDBPM averaging might be a bit too long for orbit feedback
%        solved after Superbend shutdown ... Instead of averaging, digital low pass filters are used
% - gap2tune does not give correct answers for wiggler and potentially other IDs -> orbit feedback
%        seems to be OK for other IDs, has been corrected for wiggler (fit to insertion device
%        compensation table)
% - chicanes do not work in orbit feedback
%        solved. One problem was that orbit response matrizes were mis-scaled by factor of two.
%        Second problem was different time constant of power supply control. Solved by moving controls
%        of center chicanes to cPCI (and magnets are fast, hysteresis free, aircore coils).
%        Center chicane in sector 4 is now routinely used in orbit feedback. Sector 11 to follow soon.
% - zero reading of ID gap dumps beam
%        solved in srcontrol5, still a problem in srcontrol5_hightune (but that routine has to be completely
%        rewritten because of all recent changes to srcontrol5, anyhow). For gap readings below the minimum
%        allowed gap for a device, the tune feedforward disables itself.
% - cycling of lattice causes frequent power supply failures
%        solved by changing the cycling procedure. 1.5 GeV operation is now on the upper hysteresis branch
%        as was the 1.9 GeV injection lattice before.
% - frequently stalled data in IDBPM readout
%        solved with new BPM readouts and digital filtering. Seems to have been a resolution problem
%        of the digital averaging algorithm.
% - magnet ramp tables are not in perfect agreement with magnetic measurements
%        Does not appear to be a serious problem. Superbends are slightly out of sync with other magnets,
%        but this does not cause any negative effects while ramping.
% - no good way to operate with injection at 1.5 GeV and storage energy below that
%        There now is a reasonable way to inject at 1.5 GeV and ramp down to lower storage energy. But
%        it has to be tested again after implementing new (and more) chicanes ...
% revision history
% 2001-05-10, Christoph Steier
% check whether readback from insertion device is significantly (more than 1 mm) below minimum
% gap, to avoid false zero readings of insertion device gaps to cause the tune feed forward
% to implement false huge correction (and dump the beam). If the insertion device gap readbacks
% gets more than 1 mm below the nominal minimum gap, the routine now assumes the insertion device
% to be open.
%
% 2001-08-30 and during Superbend commissioning, Christoph Steier, Tom Scarvie, Winni Decking
% various changes have been made to incorporate the Superbends and some other new equipment
% installed in the Superbend shutdown. This included some changes to programs being called by srcontrol
% (like srload, srsave, srcycle, srramp, ...). The main changes within srcontrol were in the orbit
% correction and slow orbit feedback routines (incorporating frequency feedback, ...)
%
% 2002-05-04, Christoph Steier
% added new IDBPMs, modified orbit feedback to use trim DACs, removed LSB toggling in vertical
% orbit feedback, ...
%
% 2002-07-29, T.Scarvie
% added check of CM trim currents to warn of problems that might rail the orbit feedback
%
% 2002-07-31, Christoph Steier
% increased the gain of the RF frequency feedback from 1/50 of the gain of the horizontal
% orbit feedback to 1/20. Reason was that the frequency feedback was reacting a bit too slow if all
% insertion device gaps are closed at once at high speed at the beginning of a fill.
%
% 2002-08-05, C.Steier, T.Scarvie
% Added conditional to reduce orbit feedback gain if running in two-bunch mode
%
% 2003-06-02, T.Scarvie
% Added loop inside orbit feedback to reset the SR11 chicane M1 and M2 motors every 20s to combat drift problem
%
% 2003-06-18, C. Steier
% Disabled loop to periodically reset chicane in SR11. Al Robb replaced power supply, seems to be no problem anymore.
%
% 2004-05-10, C. Steier
% The list of all BBPMs is now set up automatically be calling getlist('BBPMx'). This way, new BBPMs have to be added
% at fewer places in the software. It should now be sufficient to modify getlist and run the orbit response matrix
% rountine (getsmat) once to enable use of the new BBPMs.
%
% 2004-05-14, C. Steier
% Modified parameters for ramprate reduction (in srramp and here). Previous parameters were slightly too
% cautious. Increased initial slow ramprate to 0.4 A/s.
%
% 2004-05-14, C. Steier
% Incorporated insertion device compensation schemes for nu_y = 9.2 lattice.
%
% 2004-06-14, T.Scarvie
% Added controls for fast orbit feedback
%
% 2004-06-21, C. Steier
% Added tune feedforward (in the global tune compensation scheme for the nu_y=9.2 lattice) for the shift
% dependent tune shift of the EPUs, as well as a skew quadrupole feedforward for the EPU im sector 11
% (both only active in parallel mode so far).
%
% 2005-02-13, T.Scarvie
% Separated horizontal and vertical planes for setting Fast Feedback PIDs
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NOTES for conversion to new Middle Layer %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% We never use the gap and bump control flags - the radio buttons have been disabled -
%        should we try to keep the functionality?
%
% remove handle globals
% set(0,'showhiddenhandles','on'); what does this do?
% grampbsc -> should be handled by new srramp (which uses k-values)
% checksrmags
% checksrorbit(...)
% getdcct
% setbpmtimeconstant
% getsmatelements
% Chicane trims are now part of the corrector family
% getname('IDrunflag',...) family name change
% write_goldenorbit_ffb, write_goldenorbit_ffb2
% For the compiler
%#function goldenpage
%#function setoperationalmode
% Check if the AO exists
checkforao;
%%%%%%%%%%%%%%
% Initialize %
%%%%%%%%%%%%%%
global FEEDBACK_STOP_FLAG
SR_Mode = getfamilydata('OperationalMode');
SR_GEV = getfamilydata('Energy');
BSCramprate = getfamilydata('BSCRampRate');
if isnan(BSCramprate) | isempty(BSCramprate)
    BSCramprate = 0.4;
    setfamilydata(BSCramprate, 'BSCRampRate');
end
if nargin < 1
    action = 'Initialize';
end
if nargin < 2
    Input2 = 0;
end
if nargin < 3
    Input3 = 0;
end
if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
    FOFBcheckboxVal = 0;
else
    FOFBcheckboxVal = 1;
end
%%%%%%%%%%%%%%%%
% Main Program %
%%%%%%%%%%%%%%%%
switch(action)
    case 'StopOrbitFeedback'
        FEEDBACK_STOP_FLAG = 1;
    case 'Initialize'
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % GUI
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        ButtonWidth = 200;
        ButtonHeight  = 25;
        Offset1 = 8*25+12 + 47 + 25+25;
        Offset2 = 47+25+25;
        Offset3 = 45+25;
        Offset4 = 1;
        Offset5 = 30;
        FigWidth = ButtonWidth+6;
        FigHeight  = 3+7*(ButtonHeight+6)+24+Offset1;
        ButtonWidth = 200-6;
        % Change figure position
        set(0,'Units','pixels');
        p=get(0,'screensize');
        h0 = figure( ...
            'Color',[0.8 0.8 0.8], ...
            'HandleVisibility','Off', ...
            'Interruptible', 'on', ...
            'MenuBar','none', ...
            'Name','ALS SR CONTROL', ...
            'NumberTitle','off', ...
            'Units','pixels', ...
            'Position',[30 p(4)-FigHeight-40 FigWidth FigHeight+Offset5], ...
            'Resize','off', ...
            'Tag','SRCTRLFig1');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'FontWeight','Bold', ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+6*(ButtonHeight+3)+19+19+8+Offset1  ButtonWidth 20+Offset5], ...
            'Style','text', ...
            'String','', ...
            'Tag','SRCTRLTitle');
        % Frame Box I
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+1*(ButtonHeight+3)+Offset1-3+Offset5 ButtonWidth+6 7*ButtonHeight+18], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+7*(ButtonHeight+3)+Offset1  ButtonWidth 15+Offset5], ...
            'Style','text', ...
            'String','Lattice Setup Functions');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Cycle'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+6*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Cycle SR Lattice', ...
            'Tag','SRCTRLButton1');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Injection'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+5*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Injection', ...
            'Tag','SRCTRLButton2');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Production'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+4*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String',['Production'], ...
            'Tag','SRCTRLButton3');
        h1 = uicontrol('Parent',h0, ...
            'Callback',[...
            'fprintf(''\n'');' ...
            'disp([''   **********************************************'']);', ...
            'disp([''   **  Changing Storage Ring Operational Mode  **'']);', ...
            'disp([''   **********************************************'']);', ...
            'setoperationalmode;', ...
            'srcontrol5(''CheckInputs'');', ...
            'disp([''   ****************************'']);', ...
            'disp([''   **  Mode Change Complete  **'']);', ...
            'disp([''   ****************************'']);', ...
            'fprintf(''\n'');'], ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+3*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'Value',1, ...
            'String','Change Operational Mode', ...
            'Tag','SRCTRLButtonChangeMode');
        h1 = uicontrol(...
            'Parent',h0, ...
            'Callback', [...
            'srcontrol5(''CheckInputs'');',...
            'srcontrol5(''SRState'');'], ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+2*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Check For Problems', ...
            'Tag','SRCTRLButtonSRState');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs''); goldenpage;', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+1*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Golden Page', ...
            'Tag','SRCTRLButtonGoldenPage');
        % Frame Box II
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+7*(ButtonHeight+3)-29+Offset2+Offset5 ButtonWidth+6 2*ButtonHeight+15], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+8*(ButtonHeight+3)-10+Offset2 ButtonWidth .6*ButtonHeight+Offset5], ...
            'String','Global/Local Orbit Correction', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''OrbitCorrection'');', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+7*(ButtonHeight+3)-6+Offset2+Offset5 ButtonWidth ButtonHeight], ...
            'String','Correct Global Orbit w/ IDBPMs', ...
            'Tag','SRCTRLButtonOrbitCorrection');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''OrbitCorrectionSetup'',1);', ...
            'callback','srcontrol5(''OrbitCorrectionSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[6 7*(ButtonHeight+3)-22+Offset2+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Edit IDBPM, CM, & Local Bump Lists', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonOrbitCorrectionSetup');
        % Frame Box III
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 1.25*(ButtonHeight)+Offset3-45+Offset5 ButtonWidth+6 8*ButtonHeight+5], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+7*(ButtonHeight+3)+Offset3-25 ButtonWidth .55*ButtonHeight+Offset5], ...
            'String','Orbit Feedback', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+6*(ButtonHeight+3)+Offset3-18+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Slow Orbit Correction', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxSOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+5*(ButtonHeight+3)+Offset3-9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Fast Orbit Correction', ...
            'Style','checkbox', ...
            'Value',FOFBcheckboxVal,...
            'Tag','SRCTRLCheckboxFOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+4*(ButtonHeight+3)+Offset3+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct ID Tune Shift  ', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxTune');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+3*(ButtonHeight+3)+Offset3+9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct RF Frequency', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxRF');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''Feedback'');', ...
            'Enable','on', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[8 3+3*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Start FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStart');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''StopOrbitFeedback'');pause(0);', ...
            'Enable','off', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[.5*FigWidth+3 3+3*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Stop FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStop');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[14 3+2*(ButtonHeight)+14+Offset3-25+Offset5 ButtonWidth-14 .75*ButtonHeight], ...
            'String','Horizontal RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHorizontal');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[26 3+1.25*(ButtonHeight)+16+Offset3-25+Offset5 ButtonWidth-26 .75*ButtonHeight], ...
            'String','Vertical RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextVertical');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FeedbackSetup'',1);', ...
            'callback','srcontrol5(''FeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 3+1.25*(ButtonHeight)+.5+Offset3-25+Offset5 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit SOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFeedbackSetup');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FastFeedbackSetup'',1);', ...
            'callback','srcontrol5(''FastFeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 3+1.25*(ButtonHeight)+.5+Offset3-45+Offset5 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit FOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFastFeedbackSetup');
        % Frame Box IV
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+ButtonHeight+Offset4-14+Offset5 ButtonWidth+6 ButtonHeight+12], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+1.75*ButtonHeight+5+Offset4-21+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Storage Ring State', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHeader');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''CheckInputs'');', ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ForegroundColor','b', ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+ButtonHeight+6+3+2+Offset4-22+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','   ', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextInformation');
        % Frame Box "Close"
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 8 ButtonWidth+6 ButtonHeight+8], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'Callback','close(gcbf);', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 13 ButtonWidth ButtonHeight], ...
            'String','Close', ...
            'Tag','SRCTRLClose');
        % Update database channels
        setsrstatechannels;
        if nargout > 0
            fig = h0;
        end
    case 'Cycle'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        disp('   **************************');
        disp('   **  Storage Ring Cycle  **');
        disp('   **************************');
        a = clock; fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        BSCFlag = questdlg(sprintf('Cycle Superbend Magnets?'),'SR Cycle','Yes','No','No');
        %if strcmp(BSCFlag,'No')
        %    disp(['   ** Superbends will not be cycled. **']);
        %else
        %    disp(['   ** Superbends will be cycled during the second mini-cycle only. **']);
        %end
        ChicSQFlag = questdlg(sprintf('Cycle chicanes and skew quads and home motor chicanes?'),'SR Cycle','Yes','No','No');
        %if strcmp(ChicSQFlag,'No')
        %    disp(['   ** Chicanes and skew quads will not be cycled; motor chicanes will not be homed. **']);
        %else
        %    disp(['   ** Chicanes and skew quads will be cycled; motor chicanes will be homed. **']);
        %end
        StartFlag = questdlg(sprintf('Start %.1f GeV Cycle?',SR_GEV),'SR Cycle','Yes','No','No');
        if strcmp(StartFlag,'No')
            disp(['   ***************************']);
            disp(['   **    Cycle  Canceled    **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        end
        try
            if GapFlag
                % Make sure that the gaps are open with FF off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open.');
                    disp('   Opening all gaps at maximum speed.');
                    setff([], 1, 0);
                    disp('   Gap control disabled.');
                    disp('   Feed forward enabled.');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened.');
                    disp('   Feed forward and gap control disabled.');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled.');
                end
            else
                disp('   Feed forward and gap control disabled.');
            end
            setff([], 0, 0);
            pause(1);
            srcycle(BSCFlag, ChicSQFlag);
            setpv('SR_STATE',1);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Cycle failed due to error condition! \n\n');
            setpv('SR_STATE',-1);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp('   **********************************************');
            disp('   **  SR Cycle complete, ready for injection  **');
            disp('   **********************************************'); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp('   **********************************');
            disp('   **  Problem cycling SR lattice  **');
            disp('   **********************************'); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
    case 'Injection'
        AD = getad;
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            fprintf('   ***************************************************\n');
            fprintf('   **  Setup For %.2f GeV Injection (with ramping)  **\n', getfamilydata('InjectionEnergy'));
            fprintf('   ***************************************************\n');
            set_alarmhandler_AHU_thresholds_inject;
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',getfamilydata('InjectionEnergy')),'Injection Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            fprintf('   *************************************************\n');
            fprintf('   **  Setup For On Energy Injection at %.2f GeV  **\n', SR_GEV);
            fprintf('   *************************************************\n');
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',SR_GEV),'Injection Setup','Yes','Cancel','Cancel');
        end
        if strcmp(StartFlag,'Cancel')
            disp(['   ********************************']);
            disp(['   **  Injection Setup Canceled  **']);
            disp(['   ********************************']);
            set_alarmhandler_thresholds;
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                setff([],1,0);
                disp('   Gap control disabled');
                disp('   Feed forward enabled');
                pause(1);
                % Set IDs at max velocity w/ velocity profile off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    disp('   Opening all gaps');
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                end
                disp('   Gaps are open');
                disp('   Feed forward and gap control disabled');
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            if (AD.Energy-AD.InjectionEnergy) > 0.05
                % Ramp down to Injection Energy
                ErrorFlag = srramp('Injection');
                if ErrorFlag
                    error('Superbends over temperature.');
                end
                a = clock; fprintf('   %s %d:%d:%.0f\n\n',date, a(4), a(5), a(6));
            elseif (AD.Energy-AD.InjectionEnergy) < -0.05
                % first load injection lattice, then ramp to 1.9 GeV and back to 1.5 GeV to get onto same hysteresis branch
                srload('Injection');
                % load 1.9 GeV lattice
                tempfilename = sprintf('%s19nuy9prod.mat', getfamilydata('Directory','OpsData'));
                srload(tempfilename);
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                pause(5);
            end
            srload('Injection');
            setpv('SR_STATE',2);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Injection lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-2);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            if AD.Energy <= 1.5
                disp(['   *******************************************************************************']);
                disp(['   **  Function complete:  the storage ring is setup for injection at ',sprintf('%.2f',SR_GEV),' GeV  **']);
                disp(['   *******************************************************************************']);
                fprintf('\n');
            else
                fprintf('   **********************************************************************************************\n');
                fprintf('   **  Function complete:  the storage ring is setup for injection at %.2f GeV (upper branch)  **\n', getfamilydata('InjectionEnergy'));
                fprintf('   **********************************************************************************************\n');
                fprintf('\n');
            end
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   ************************************']);
            disp(['   **  Problem with injection setup  **']);
            disp(['   ************************************']);
            fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        %soundchord;
        setfamilydata(0.8, 'BSCRampRate');
    case 'Production'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        AD=getad;
        fprintf('\n');
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            disp('   ********************************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation (with ramping)  **',SR_GEV));
            disp('   ********************************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            disp('   *****************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation  **',SR_GEV));
            disp('   *****************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Yes','Cancel','Cancel');
        end
        if strcmp(StartFlag,'Cancel')
            disp(['   ***************************']);
            disp(['   **  User Setup Canceled  **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                % Make sure that the gaps are open
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open');
                    disp('   Opening all gaps at maximum speed');
                    setff([], 1, 0);
                    disp('   Gap control disabled');
                    disp('   Feed forward enabled');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened');
                    disp('   Feed forward and gap control disabled');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled');
                end
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            % Ramp up to the production lattice
            ErrorFlag = srramp('Production');
            if ErrorFlag
                error('Superbends over temperature.');
            end
            a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            srload('Production');
            if GapFlag
                setff([], 1, 0);
                disp('   Gap control disabled');
                disp('   Feed forward enable');
                pause(1);
                disp('   Insertion device velocity profile boolean control off');
                disp('   Closing all gaps at maximum speed');
                % Set IDs at max velocity w/ velocity profile off
                [Position, Velocity, RunFlag, UserGap] = getid;
                setid([], UserGap, maxsp('IDvel'), 1, 0, 1);
                % Turn velocity profile on
                disp('   Insertion device velocity profile boolean control is on');
                setid([], [], maxsp('IDvel'), 1, 1, 0);
                disp('   Gaps are closed');
                setff([4;7;8;9;10;12], 1, 1);
                setff(5, 1, 0);
                disp('   Gap control enabled (except sector 5 (W16))');
            end
            set_alarmhandler_thresholds_new;
            setpv('SR_STATE',3);
        catch
            fprintf('   %s \n', lasterr);
            fprintf('   User lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-3);
        end
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp(['   **************************************************************************']);
            disp(['   **  Function complete:  the storage ring is setup for users at ',sprintf('%.1f',SR_GEV),' GeV  **']);
            disp(['   **************************************************************************']); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   *************************************']);
            disp(['   **  Problem with production setup  **']);
            disp(['   *************************************']); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        setfamilydata(0.8, 'BSCRampRate');
    case 'CheckInputs'
        SR_GEV = getfamilydata('Energy');
        AD=getad;
        setsrstatechannels;
        set(0,'showhiddenhandles','on');
        if AD.Energy > 1.55
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Down)']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users (Ramp Up)']);
        elseif AD.Energy < 1.45
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Up+cycle)']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV (Ramp Down)']);
        else
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV']);
        end
        set(findobj('Tag','SRCTRLTitle'),'String',SR_Mode);
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
        else
            set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
        end
        set(0,'showhiddenhandles','off');
    case 'SRState'
        NumErrors = 0;
        fprintf('\n');
        disp('   ***********************************');
        disp('   **  Checking Storage Ring State  **');
        disp('   ***********************************');
        a = clock;
        fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        %       FileName = getpv('SR_LATTICE_FILE','String');   % Last srload file name (in OLD MIDDLE LAYER nomenclature!!)
        GeVnow = bend2gev;
        if GeVnow == getfamilydata('Energy')
            [ConfigSetpoint, ConfigMonitor, FileName] = getproductionlattice;
        elseif GeVnow == getfamilydata('InjectionEnergy')
            [ConfigSetpoint, ConfigMonitor, FileName] = getinjectionlattice;
        else
            FileName = '';
        end
        [StateNumber, StateString] = getsrstate;
        fprintf('   Storage ring operational mode: %s\n', SR_Mode);
        if StateNumber < 0
            fprintf('   Storage ring state error: %s\n', StateString);
            NumErrors = NumErrors + 1;
        else
            fprintf('   Storage ring state: %s\n', StateString);
        end
        if StateNumber==0
            % Storage ring state unknown
            NumErrors = NumErrors + 1;
        elseif abs(StateNumber)==1 || abs(StateNumber)==2
            FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','InjectionFile') '.mat'];
            if ~strcmp(FileName, FileNameGoal)
                fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','InjectionFile'), FileName);
                NumErrors = NumErrors + 1;
            end
        else
            FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile') '.mat'];
            if ~strcmp(FileName, FileNameGoal)
                fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','LatticeFile'), FileName);
                NumErrors = NumErrors + 1;
            end
        end
        % Check all SR magnets
        if isempty(FileName)
            fprintf('   Goal setpoints will not be checked since the last lattice load is unknown.\n');
            NumErrors1 = checksrmags('');
        else
%            NumErrors1 = checksrmags([getfamilydata('Directory','OpsData') FileName]);
            NumErrors1 = checksrmags(FileName);
        end
        if NumErrors1 == 0
            fprintf('   SR magnets power supplies are OK.\n');
        end
        NumErrors = NumErrors + NumErrors1;
        % Check RF frequency
        if isempty(FileName)
            fprintf('   RF frequency will not be checked since the last lattice load is unknown.\n');
        else
%            load([getfamilydata('Directory','OpsData'), FileName]);
            load(FileName);
            [tmp, RFHPCounterPresent] = getrf;
            if abs(RFHPCounterPresent-ConfigSetpoint.RF.Setpoint.Data) > .002
                NumErrors = NumErrors + 1;
                fprintf('   RF frequency should be %f, presently it is %f MHz (as measured by the HP counter).\n', ConfigSetpoint.RF.Setpoint.Data, RFHPCounterPresent);
            else
                fprintf('   RF frequency is OK (HP counter is %f MHz, at the time of the lattice save it was %f MHz).\n', RFHPCounterPresent, ConfigSetpoint.RF.Setpoint.Data);
            end
        end
        % Check for orbit problems
        if (StateNumber >= 3) & (getdcct > 2)   % Production lattice is loaded with beam in the machine
            Xtol = 0.070;
            Ytol = 0.010;
            NumErrors1 = checksrorbit([],Xtol,Ytol);
            if NumErrors1
                fprintf('   SR orbit in the ID straight sections or at Bergoz BPMs deviates more than allowed from the golden orbit.\n');
            else
                fprintf('   SR orbit in the ID straight sections and at Bergoz BPMs is OK.\n');
                fprintf('   The orbit is within %.3f mm horizontally and %.3f mm vertically', Xtol, Ytol);
            end
            NumErrors = NumErrors + NumErrors1;
        else
            fprintf('   Storage ring orbit was not checked.\n');
        end
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        if NumErrors
            disp('   *********************************');
            disp('   **  Storage Ring Has Problems  **');
            disp('   *********************************');
        else
            disp('   **********************************');
            disp('   **  Storage Ring Lattice is OK  **');
            disp('   **********************************');
        end
        fprintf('   \n');
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
        end
        set(0,'showhiddenhandles','off');
    case 'OrbitCorrection'
        fprintf('\n');
        fprintf('   *********************************\n');
        fprintf('   **  Starting Orbit Correction  **\n');
        fprintf('   *********************************\n');
        a = clock;
        fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        StartFlag = questdlg(sprintf('Start orbit correction, %.1f GeV?',SR_GEV),'Orbit Correction','Yes','No','No');
        if strcmp(StartFlag,'No')
            disp(['   ********************************']);
1000             disp(['   **  Orbit Correction Aborted  **']);
1001             disp(['   ********************************']);
1002             fprintf('\n');
1003             return
1004         end
1005
1006         if getdcct < 5     % Don't correct the orbit if the current is too small
1007             fprintf('   Orbit not corrected due to small current.\n');
1008             return
1009         end
1010
1011         if abs(SR_GEV-bend2gev(getpv('BEND',[1 1])))>  0.05     % Don't use this routine for the injection lattice
1012             fprintf('   This routine should only be used for the production energy: Correction aborted\n');
1013             return
1014         end
1015
1016         SR_STATE_OLD = scaget('SR_STATE');
1017         set(0,'showhiddenhandles','on');
1018         setpv('SR_STATE',4);
1019         [StateNumber, StateString] = getsrstate;
1020         if StateNumber >= 0
1021             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1022         else
1023             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1024         end
1025         set(0,'showhiddenhandles','off');
1026
1027
1028         try
1029
1030             % 2 Hz update rate on IDBPMs
1031             disp('   IDBPM time constant set to 0.5s.')
1032             setbpmtimeconstant(0.5)
1033             pause(2);
1034
1035
1036             % Turn off feed forward
1037             fprintf('   Turning feed forward off.\n');
1038             [FFEnableBM, FFEnableBC] = getff;
1039             setff([], 0);
1040             scasleep(.2);
1041
1042
1043             % Get vectors
1044             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1045             LocalBumplist = FB.LocalBumplist;
1046
1047         catch
1048
1049             fprintf('   %s \n',lasterr);
1050             fprintf('   Orbit correction setup failed due to error condition! \n\n');
1051             setpv('SR_STATE',-4);
1052             set(0,'showhiddenhandles','on');
1053             [StateNumber, StateString] = getsrstate;
1054             if StateNumber >= 0
1055                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1056             else
1057                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1058             end
1059             set(0,'showhiddenhandles','off');
1060             return
1061
1062         end
1063
1064         iNotHCMChicane = find(FB.HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
1065         iHCMChicane = find(FB.HCMlist1(:,2) == 10);
1066         iNotVCMChicane = find(FB.VCMlist1(:,2) < 10);
1067         iVCMChicane = find(FB.VCMlist1(:,2) == 10);
1068
1069         fprintf('   Starting horizontal and vertical global orbit correction (SVD method).\n');
1070
1071         for iloop = 1:3
1072             try
1073                 % use the following to get corrector settings in OCS without setting them, so the values can be checked
1074                 FB.OCSx = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
1075                 FB.OCSy = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
1076                 if any(abs(FB.OCSx.CM.Delta(iNotHCMChicane)) > 5)
1077                   disp('   Orbit Correction is changing some horizontal corrector(s) > 5A!!');
1078                 end
1079                 if any(abs(FB.OCSy.CM.Delta(iNotVCMChicane)) > 5)
1080                   disp('   Orbit Correction is changing some vertical corrector(s) > 5A!!');
1081                 end
1082                 if any(abs(FB.OCSx.CM.Delta(iHCMChicane)) > 10)
1083                   disp('   Orbit Correction is changing some horizontal chicane corrector(s) > 10A!!');
1084                 end
1085                 if any(abs(FB.OCSy.CM.Delta(iVCMChicane)) > 10)
1086                   disp('   Orbit Correction is changing some vertical chicane corrector(s) > 10A!!');
1087                 end
1088
1089
1090                 % Correct horizontal orbit
1091                 FB.OCSx = setorbit(FB.OCSx,'NoDisplay');
1092                 % Correct vertical orbit
1093                 FB.OCSy = setorbit(FB.OCSy,'NoDisplay');
1094
1095
1096                 % Check for current in machine - stop orbit correction if DCCT < 5mA
1097                 if (getdcct < 4.5)
1098                     error('**There is less than 5mA in the machine! Stopping orbit correction.');
1099                 end
1100
1101                 % Check state of gaps - stop orbit correction if any are moving
1102                 GAPrunflag = getpv('ID','RunFlag');
1103                 if any(GAPrunflag-round(GAPrunflag))
1104                     error('**One or more of the gaps are moving! Stopping orbit correction.');
1105                 end
1106
1107                 x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
1108                 y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
1109                 fprintf('   %d. Horizontal RMS = %.3f mm\n', iloop, norm(x)/sqrt(length(x)));
1110                 fprintf('   %d.   Vertical RMS = %.3f mm\n', iloop, norm(y)/sqrt(length(y)));
1111
1112             catch
1113                 % fprintf('   %s \n',lasterr);
1114                 fprintf('   Orbit correction failed due to error condition!\n  Fix the problem, reload the lattice (srload), and try again.  \n\n');
1115                 setpv('SR_STATE',-4);
1116                 set(0,'showhiddenhandles','on');
1117                 [StateNumber, StateString] = getsrstate;
1118                 if StateNumber >= 0
1119                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1120                 else
1121                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1122                 end
1123                 set(0,'showhiddenhandles','off');
1124                 return
1125             end
1126         end
1127
1128
1129         % Set user bumps w/o sextupole correctors
1130         try
1131
1132             %turn up corrector speed here to quicken setting bumps
1133             HCMramprate = getpv('HCM', 'RampRate');
1134             VCMramprate = getpv('VCM', 'RampRate');
1135             setpv('HCM', 'RampRate', 10, [], 0);
1136             setpv('VCM', 'RampRate', 10, [], 0);
1137
1138             if ~isempty(LocalBumplist)
1139                 fprintf('   Setting local bumps in the straight sections.\n');
1140                 for loop = 1:size(LocalBumplist,1)
1141
1142                     % Check for current in machine - stop orbit correction if DCCT < 5mA
1143                     if (getdcct < 5)
1144                         error('** There is less than 5mA in the machine! Stopping local bumps.');
1145                     end
1146
1147                     % Check state of gaps - stop setting bumps if any are moving
1148                     GAPrunflag = getpv('ID','RunFlag');
1149                     if any(GAPrunflag-round(GAPrunflag))
1150                         error('** One or more of the gaps are moving! Stopping local bumps.');
1151                     end
1152
1153                     HCMoldsp = getsp('HCM', FB.HCMlist1);
1154                     VCMoldsp = getsp('VCM', FB.VCMlist1);
1155
1156                     if any(LocalBumplist(loop,1) == [4 6 11])
1157                         if LocalBumplist(loop,2) == 0
1158                             % Upstream bump
1159                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1160                             if isempty(iRemove)
1161                                 setbumps(LocalBumplist(loop,:), 1);
1162                             else
1163                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1164                             end
1165                         elseif LocalBumplist(loop,2) == 1
1166                             % Upstream bump
1167                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;],FB.OCSx.BPM.DeviceList);
1168                             if isempty(iRemove)
1169                                 setbumps(LocalBumplist(loop,:), 1);
1170                             else
1171                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1172                             end
1173                         else
1174                             % Downstream bump
1175                             [i, iRemove] = findrowindex([LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1176                             if isempty(iRemove)
1177                                 setbumps(LocalBumplist(loop,:), 1);
1178                             else
1179                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1180                             end
1181                         end
1182                     else
1183                         [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1184                         if isempty(iRemove)
1185                             setbumps(LocalBumplist(loop,:), 1);
1186                         else
1187                             fprintf('\n   BPMs missing from Sector %02d - skipping local bump for that sector.\n\n', LocalBumplist(loop,1));
1188                         end
1189                     end
1190
1191                     HCMnewsp = getsp('HCM', FB.HCMlist1);
1192                     VCMnewsp = getsp('VCM', FB.VCMlist1);
1193                     % Remove center chicane trim from corrector check
1194                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 5) | (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 10)
1195                         error('**Setbumps caused some corrector magnet currents to change by more than 5(Horiz)/10(Vert) A!');
1196                     end
1197                     % Now check center chicane trims
1198                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 10) | (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 15)
1199                         error('**Setbumps caused some chicane trim magnet currents to change by more than 10(Horiz)/15(Vert) A!');
1200                     end
1201                 end
1202             end
1203
1204             %restore corrector speeds
1205             setpv('HCM', 'RampRate', HCMramprate, [], 0);
1206             setpv('VCM', 'RampRate', VCMramprate, [], 0);
1207
1208         catch
1209             fprintf('   %s \n',lasterr);
1210             fprintf('   Setbumps failed due to error condition!  Fix the problem, reload the lattice (srload), and try again.\n\n');
1211             setpv('SR_STATE',-4);
1212             set(0,'showhiddenhandles','on');
1213             [StateNumber, StateString] = getsrstate;
1214             if StateNumber >= 0
1215                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1216             else
1217                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1218             end
1219             set(0,'showhiddenhandles','off');
1220             return
1221         end
1222
1223
1224         % Turn feed forward back to it's original state
1225         if any(FFEnableBC)
1226             fprintf('   Turning feed forward back on.\n');
1227             setff([], FFEnableBC);
1228         end
1229
1230
1231         a = clock;
1232         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1233         [StateNumber, StateString] = getsrstate;
1234         set(0,'showhiddenhandles','on');
1235         if StateNumber >= 0
1236             setpv('SR_STATE',4.1);
1237             [StateNumber, StateString] = getsrstate;
1238             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1239             fprintf('   *********************************\n');
1240             fprintf('   **  Orbit Correction Complete  **\n');
1241             fprintf('   *********************************\n\n');
1242         else
1243             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1244             fprintf('   *************************************\n');
1245             fprintf('   **  Problem With Orbit Correction  **\n');
1246             fprintf('   *************************************\n\n');
1247         end
1248         set(0,'showhiddenhandles','off');
1249         pause(0);
1250
1251
1252     case 'OrbitCorrectionSetup'
1253         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
1254
1255         if InitFlag
1256             % Setup feedback elements
1257             % disp('Orbit correction condition: InitFlag=1 -- debugging message');
1258
1259             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1260             % Edit the following lists to change default configuration of Orbit Correction %
1261             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1262             hlist=[];vlist=[];
1263             for Sector =1:12
1264                 if Sector == 1
1265                     vlist = [vlist;Sector 2;Sector 4;Sector 5;Sector 8];
1266                     hlist = [hlist;Sector 2;Sector 7];
1267                 elseif Sector == 3
1268                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1269                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1270                 elseif Sector == 5
1271                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1272                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1273                 elseif Sector == 10
1274                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1275                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1276                 elseif Sector == 12
1277                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 7];
1278                     hlist = [hlist;Sector 2;Sector 7];
1279                 else
1280                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8];
1281                     hlist = [hlist;Sector 2;Sector 7];
1282                 end
1283             end
1284             HCMlist1 = hlist;
1285             VCMlist1 = vlist;
1286
1287             BPMlist1 = [
1288                 1 2
1289                 1 5
1290                 1 6
1291                 1 10
1292                 2 1
1293                 2 5
1294                 2 6
1295                 2 9
1296                 3 2
1297                 3 5
1298                 3 6
1299                 3 10
1300                 3 11
1301                 3 12
1302                 4 1
1303                 4 5
1304                 4 6
1305                 4 10
1306                 5 1
1307                 5 5
1308                 5 6
1309                 5 10
1310                 5 11
1311                 5 12
1312                 6 1
1313                 6 5
1314                 6 6
1315                 6 10
1316                 7 1
1317                 7 5
1318                 7 6
1319                 7 10
1320                 8 1
1321                 8 5
1322                 8 6
1323                 8 10
1324                 9 1
1325                 9 5
1326                 9 6
1327                 9 10
1328                 10 1
1329                 10 5
1330                 10 6
1331                 10 10
1332                 10 11
1333                 10 12
1334                 11 1
1335                 11 5
1336                 11 6
1337                 11 10
1338                 12 1
1339                 12 5
1340                 12 6
1341                 12 9];
1342
1343             % SVD orbit correction
1344             Xivec = [1:28];
1345             Yivec = [1:48];
1346
1347
1348             LocalBumplist = [
1349               % 1 1
1350               % 2 1
1351               % 3 1
1352                 4 1
1353               % 4 2
1354                 5 1
1355                 6 1
1356               % 6 2
1357                 7 1
1358                 8 1
1359                 9 1
1360                 10 1
1361                 11 1
1362                 11 2
1363                 12 1
1364 ];
1365             %LocalBumplist = []
1366
1367             % initialize RFCorrFlag
1368             RFCorrFlag = 'Yes';
1369         else
1370
1371             % Get vectors
1372             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1373             BPMlist1 = FB.BPMlist1;
1374             HCMlist1 = FB.HCMlist1;
1375             VCMlist1 = FB.VCMlist1;
1376             Xivec = FB.Xivec;
1377             Yivec = FB.Yivec;
1378             LocalBumplist = FB.LocalBumplist;
1379             Xgoal = FB.Xgoal;
1380             Ygoal = FB.Ygoal;
1381             RFCorrFlag = FB.RFCorrFlag;
1382
1383             % Add button to change #ivectors, CMs, IDBPMs,
1384             EditFlag = 0;
1385             h_fig1 = figure;
1386             while EditFlag ~= 8
1387
1388                 % Sensitivity matrix
1389                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
1390                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
1391
1392                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1393                 % Can the call below work for setting FOFB RF parameter? %
1394                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1395                 if strcmpi(RFCorrFlag, 'Yes')
1396                     Sx = [Sx getdisp('BPMx',BPMlist1)];
1397                 end
1398
1399                 [Ux, SVx, Vx] = svd(Sx);
1400                 [Uy, SVy, Vy] = svd(Sy);
1401
1402
1403                 % Remove singular values greater than the actual number of singular values
1404                 i = find(Xivec>length(diag(SVx)));
1405                 if ~isempty(i)
1406                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
1407                     pause(0);
1408                     Xivec(i) = [];
1409                 end
1410                 i = find(Yivec>length(diag(SVy)));
1411                 if ~isempty(i)
1412                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
1413                     pause(0);
1414                     Yivec(i) = [];
1415                 end
1416
1417
1418                 Ax = Sx*Vx(:,Xivec);
1419                 Tx = inv(Ax'*Ax)*Ax';
1420
1421                 Ay = Sy*Vy(:,Yivec);
1422                 Ty = inv(Ay'*Ay)*Ay';
1423
1424
1425                 figure(h_fig1);
1426                 subplot(2,1,1);
1427                 semilogy(diag(SVx),'b');
1428                 hold on;
1429                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
1430                 ylabel('Horizontal');
1431                 title('Response Matrix Singular Values');
1432                 hold off;
1433                 subplot(2,1,2);
1434                 semilogy(diag(SVy),'b');
1435                 hold on;
1436                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
1437                 xlabel('Singular Value Number');
1438                 ylabel('Vertical');
1439                 hold off;
1440                 drawnow;
1441
1442                 if strcmp(RFCorrFlag,'No')
1443                     RFCorrState = 'NOT CORRECTED';
1444                 elseif strcmp(RFCorrFlag,'Yes')
1445                     RFCorrState = 'CORRECTED';
1446                 else
1447                     RFCorrState = '???';
1448                 end
1449
1450                 %         EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','HCM Chicane List','VCM Chicane List','IDBPM List','BBPM List','Change Golden Orbit',...
1451                 %            'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1452                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','BPM List','Change Golden Orbit',...
1453                     'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1454
1455                 if EditFlag == 1
1456                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
1457                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
1458                     titlestr='SVD Orbit Feedback';
1459                     lineNo=1;
1460                     answer=inputdlg(prompt,titlestr,lineNo,def);
1461                     if ~isempty(answer)
1462                         XivecNew = fix(str2num(answer{1}));
1463                         if isempty(XivecNew)
1464                             disp('   Horizontal E-vector cannot be empty.  No change made.');
1465                         else
1466                             if any(XivecNew<=0) | max(XivecNew)>length(diag(SVx))
1467                                 disp('   Error reading horizontal E-vector.  No change made.');
1468                             else
1469                                 Xivec = XivecNew;
1470                             end
1471                         end
1472                         YivecNew = fix(str2num(answer{2}));
1473                         if isempty(YivecNew)
1474                             disp('   Vertical E-vector cannot be empty.  No change made.');
1475                         else
1476                             if any(YivecNew<=0) | max(YivecNew)>length(diag(SVy))
1477                                 disp('   Error reading vertical E-vector.  No change made.');
1478                             else
1479                                 Yivec = YivecNew;
1480                             end
1481                         end
1482                     end
1483                 end
1484
1485                 if EditFlag == 2
1486                     List = getlist('HCM');
1487                     CheckList = zeros(size(List,1));
1488                     Elem = dev2elem('HCM', HCMlist1);
1489                     CheckList(Elem) = ones(size(Elem));
1490                     CheckList = CheckList(dev2elem('HCM',List));
1491                     newList = editlist(List, 'HCM', CheckList);
1492                     if isempty(newList)
1493                         fprintf('   Horizontal corrector magnet list cannot be empty.  No change made.\n');
1494                     else
1495                         HCMlist1 = newList;
1496                     end
1497                 end
1498
1499                 if EditFlag == 3
1500                     List = getlist('VCM');
1501                     CheckList = zeros(size(List,1));
1502                     Elem = dev2elem('VCM', VCMlist1);
1503                     CheckList(Elem) = ones(size(Elem));
1504                     CheckList = CheckList(dev2elem('VCM',List));
1505                     newList = editlist(List, 'VCM', CheckList);
1506                     if isempty(newList)
1507                         fprintf('   Vertical corrector magnet cannot be empty.  No change made.\n');
1508                     else
1509                         VCMlist1 = newList;
1510                     end
1511                 end
1512
1513                 if EditFlag == 4
1514                     ListOld = BPMlist1;
1515                     XgoalOld = Xgoal;
1516                     YgoalOld = Ygoal;
1517
1518                     % Full BPM list
1519                     List = [
1520                         1 2
1521                         1 5
1522                         1 6
1523                         1 10
1524                         2 1
1525                         2 5
1526                         2 6
1527                         2 9
1528                         3 2
1529                         3 5
1530                         3 6
1531                         3 10
1532                         3 11
1533                         3 12
1534                         4 1
1535                         4 5
1536                         4 6
1537                         4 10
1538                         5 1
1539                         5 5
1540                         5 6
1541                         5 10
1542                         5 11
1543                         5 12
1544                         6 1
1545                         6 5
1546                         6 6
1547                         6 10
1548                         7 1
1549                         7 5
1550                         7 6
1551                         7 10
1552                         8 1
1553                         8 5
1554                         8 6
1555                         8 10
1556                         9 1
1557                         9 5
1558                         9 6
1559                         9 10
1560                         10 1
1561                         10 5
1562                         10 6
1563                         10 10
1564                         10 11
1565                         10 12
1566                         11 1
1567                         11 5
1568                         11 6
1569                         11 10
1570                         12 1
1571                         12 5
1572                         12 6
1573                         12 9
1574                         ];
1575
1576                     CheckList = zeros(size(List,1),1);
1577                     if ~isempty(BPMlist1)
1578                         for i = 1:size(List,1)
1579                             k = find(List(i,1)==BPMlist1(:,1));
1580                             l = find(List(i,2)==BPMlist1(k,2));
1581
1582                             if isempty(k) | isempty(l)
1583                                 % Item not in list
1584                             else
1585                                 CheckList(i) = 1;
1586                             end
1587                         end
1588                     end
1589
1590                     newList = editlist(List, 'BPM', CheckList);
1591                     if isempty(newList)
1592                         fprintf('   BPM list cannot be empty.  No change made.\n');
1593                     else
1594                         BPMlist1 = newList;
1595                     end
1596
1597                     % Set the goal orbit to the golden orbit
1598                     Xgoal = getgolden('BPMx', BPMlist1);
1599                     Ygoal = getgolden('BPMy', BPMlist1);
1600
1601
1602                     % If a new BPM is added, then set the goal orbit to the golden orbit
1603                     for i = 1:size(BPMlist1,1)
1604
1605                         % Is it a new BPM?
1606                         k = find(BPMlist1(i,1)==ListOld(:,1));
1607                         l = find(BPMlist1(i,2)==ListOld(k,2));
1608
1609                         if isempty(k) | isempty(l)
1610                             % New BPM
1611                         else
1612                             % Use the old value for old BPM
1613                             Xgoal(i) = XgoalOld(k(l));
1614                             Ygoal(i) = YgoalOld(k(l));
1615                         end
1616                     end
1617                 end
1618
1619                 if EditFlag == 5
1620
1621                     ChangeList = editlist(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
1622                     for i = 1:size(ChangeList,1)
1623
1624                         k = find(ChangeList(i,1)==BPMlist1(:,1));
1625                         l = find(ChangeList(i,2)==BPMlist1(k,2));
1626
1627                         prompt = {sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
1628                         def = {sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
1629                         titlestr = 'CHANGE THE GOAL ORBIT';
1630                         lineNo = 1;
1631                         answer = inputdlg(prompt, titlestr, lineNo, def);
1632
1633                         if isempty(answer)
1634                             % No change
1635                             fprintf('   No change was made to the golden orbit.\n');
1636                         else
1637                             Xgoalnew = str2num(answer{1});
1638                             if isempty(Xgoalnew)
1639                                 fprintf('   No change was made to the horizontal golden orbit.\n');
1640                             else
1641                                 Xgoal(k(l)) = Xgoalnew;
1642                             end
1643
1644                             Ygoalnew = str2num(answer{2});
1645                             if isempty(Ygoalnew)
1646                                 fprintf('   No change was made to the vertical golden orbit.\n');
1647                             else
1648                                 Ygoal(k(l)) = Ygoalnew;
1649                             end
1650                         end
1651                     end
1652                     if ~isempty(ChangeList)
1653                         fprintf('   Note:  changing the goal orbit for "Orbit Correction" does not change the goal orbit for "Slow Orbit Feedback."\n');
1654                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
1655                     end
1656                 end
1657
1658                 if EditFlag == 6
1659                     List = [
1660                         1 1
1661                         2 1
1662                         3 1
1663                         4 1
1664                         4 2
1665                         5 1
1666                         6 1
1667                         6 2
1668                         7 1
1669                         8 1
1670                         9 1
1671                         10 1
1672                         11 1
1673                         11 2
1674                         12 1];
1675                     CheckList = zeros(size(List,1),1);
1676                     if ~isempty(LocalBumplist)
1677                         for i = 1:size(List,1)
1678                             k = find(List(i,1)==LocalBumplist(:,1));
1679                             l = find(List(i,2)==LocalBumplist(k,2));
1680
1681                             if isempty(k) | isempty(l)
1682                                 % Item not in list
1683                             else
1684                                 CheckList(i) = 1;
1685                             end
1686                         end
1687                     end
1688                     LocalBumplist = editlist2(List, 'Sector', CheckList);
1689                 end
1690
1691                 if EditFlag == 7
1692                     RFCorrFlag = questdlg(sprintf('Set RF Frequency during Orbit Correction?'),'RF Frequency','Yes','No', 'No');
1693                     if strcmp(RFCorrFlag,'No')
1694                         disp(['   RF Frequency will not be included in global orbit correction.']);
1695                     elseif strcmp(RFCorrFlag,'Yes')
1696                         disp(['   RF Frequency will be included in global orbit correction.']);
1697                     end
1698
1699                 end
1700             end
1701             close(h_fig1);
1702         end
1703
1704 %  ORBIT CORRECTION STRUCTURE (OCS)
1705 %    OCS.BPM (data structure)
1706 %    OCS.CM  (data structure)
1707 %    OCS.GoalOrbit
1708 %    OCS.NIter
1709 %    OCS.SVDIndex
1710 %    OCS.IncrementalFlag = 'Yes'/'No'
1711 %    OCS.BPMWeight
1712 %    OCS.Flags = { 'FitRF' , etc.  }
1713         OCSx.BPM = getx(BPMlist1, 'struct');
1714         OCSx.CM = getsp('HCM', HCMlist1, 'struct');
1715         OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
1716         OCSx.NIter = 1;
1717         OCSx.SVDIndex = Xivec;
1718         OCSx.IncrementalFlag = 'No';
1719         OCSx.FitRF = 1;
1720         OCSy.BPM = gety(BPMlist1, 'struct');
1721         OCSy.CM = getsp('VCM', VCMlist1, 'struct');
1722         OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
1723         OCSy.NIter = 1;
1724         OCSy.SVDIndex = Yivec;
1725         OCSy.IncrementalFlag = 'No';
1726         OCSy.FitRF = 0;
1727
1728         % Save vectors
1729         FB.OCSx = OCSx;
1730         FB.OCSy = OCSy;
1731
1732         FB.BPMlist1 = BPMlist1;
1733         FB.HCMlist1 = HCMlist1;
1734         FB.VCMlist1 = VCMlist1;
1735         FB.Xivec = Xivec;
1736         FB.Yivec = Yivec;
1737         FB.Xgoal = OCSx.GoalOrbit;
1738         FB.Ygoal = OCSy.GoalOrbit;
1739         FB.RFCorrFlag = RFCorrFlag;
1740         FB.LocalBumplist = LocalBumplist;
1741         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata',FB);
1742
1743
1744     case 'Feedback'
1745
1746         FBloopIter = 1;
1747         if get(findobj(gcbf,'Tag','SRCTRLCheckboxFOFB'),'Value') == 1
1748             StartFOFBFlag = 1;
1749         else
1750             StartFOFBFlag = 0;
1751         end
1752
1753         FEEDBACK_STOP_FLAG = 0;
1754         HWarnNum=0;
1755         VWarnNum=0;
1756
1757         SR_GeV = getenergy;
1758         % Feedback loop setup
1759         PlotInfoFlag = 0;           % Plot micado stuff
1760         LoopDelay = 1.5;           % Period of feedback loop [seconds], make sure the BPM averaging is correct
1761         VCM_LSB = .00366211;
1762         VCMCHICANE_LSB = .002441;   % 80 max?,  Note: not fully implemented
1763
1764         if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
1765             Xgain  = 0.2;
1766             Ygain  = 0.1;
1767         else
1768             Xgain  = 0.8; % raised 0.5->0.8 at 17:20, 3-2-05 to more quickly correct EPU4 fast switching orbit distortions
1769             Ygain  = 0.8;
1770         end
1771
1772         % Load lattice set for tune feed forward
1773         load([getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile')]);
1774         QFsp = ConfigSetpoint.QF.Setpoint.Data;
1775         QDsp = ConfigSetpoint.QD.Setpoint.Data;
1776
1777         % ID tune compensation does not work in the injection lattice, so ...
1778         if abs(SR_GEV - bend2gev)>  0.05     % Don't use this routine for the injection lattice
1779             fprintf('   This routine should only be used for the production energy: Orbit feedback aborted\n');
1780             return
1781         end
1782
1783         set(0,'showhiddenhandles','on');
1784
1785         try
1786             fprintf('\n');
1787             fprintf('   *******************************\n');
1788             fprintf('   **  Starting Orbit Feedback  **\n');
1789             fprintf('   *******************************\n');
1790             a = clock;
1791             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1792             fprintf('   Note: the Matlab command window will be used to display status information.\n');
1793             fprintf('         It cannot be used to enter commands during slow orbit feedback.\n');
1794
1795
1796             % Tune response matrix
1797             SR_TUNE_MATRIX = gettuneresp({'QF','QD'}, {[],[]}, getenergy('Production'));    % Approx. [0.1944 -0.0286;-0.1182 0.1526];
1798
1799             % >= 2 Hz update rate on IDBPMs
1800             disp('   IDBPM time constant set to 0.2s.')
1801             setbpmtimeconstant(0.2)
1802             pause(1.1);
1803
1804             % Check whether bumps and kickers are on and warn to turn off before starting feedback if necessary
1805             try
1806                 if (getsp('SR01S___BUMP1__BC21')==1 & getsp('SR01S___BUMP1P_BC22')==1) | (getsp('SR01S___SEK____BC21')==1 & getsp('SR01S___SEK_P__BC23')==1) | (getsp('SR01S___SEN____BC20')==1 & getsp('SR01S___SEN_P__BC22')==1)
1807                     soundtada;
1808                     fprintf('   \n');
1809                     fprintf('   *********************************************************************************\n');
1810                     fprintf('   ** One or more of the pulsed SR injection magnets is still on!  Turn them off! **\n');
1811                     fprintf('   *********************************************************************************\n');
1812                     fprintf('   \n');
1813                 end
1814             catch
1815                 disp('**Problem checking the state of the bumps and kickers - please check that they are not pulsing.');
1816             end
1817
1818             % Get vectors
1819
1820             % is there a need to set these up? (we do later calls to FB.OCSx..., not the bare OCSx...) %
1821             %            OCSx = FB.OCSx;
1822             %            OCSy = FB.OCSy;
1823
1824             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
1825
1826             BPMlist1 = FB.OCSx.BPM.DeviceList;
1827             % FOFB_BPMlist =
1828             HCMlist1 = FB.HCMlist1;
1829             VCMlist1 = FB.VCMlist1;
1830             Xivec = FB.Xivec;
1831             Yivec = FB.Yivec;
1832             Xgoal = FB.OCSx.GoalOrbit;
1833             Ygoal = FB.OCSy.GoalOrbit;
1834             FFTypeFlag = FB.FFTypeFlag;   %local or global tune correction
1835
1836             iNotHCMChicane = find(HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
1837             iHCMChicane = find(HCMlist1(:,2) == 10);
1838             iNotVCMChicane = find(VCMlist1(:,2) < 10);
1839             iVCMChicane = find(VCMlist1(:,2) == 10);
1840
1841             % Sensitivity matrix for setting fast feedback setpoints
1842             Sx1 = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
1843             Sy1 = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
1844
1845             % Sx3 = getrespmat('BPMx', BPMlist1, 'HQMOFM', [1 1], [], SR_GEV);
1846             % Sy3 = getrespmat('BPMy', BPMlist1, 'HQMOFM', [1 1], [], SR_GEV);
1847
1848         catch
1849             fprintf('\n  %s \n',lasterr);
1850
1851             % >= 2 Hz update rate on IDBPMs
1852             disp('   IDBPM time constant set to 0.25s.')
1853             setbpmtimeconstant(0.25)
1854
1855
1856             a = clock;
1857             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1858             fprintf('   *************************************************************\n');
1859             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
1860             fprintf('   *************************************************************\n\n');
1861             set(0,'showhiddenhandles','off');
1862             pause(0);
1863
1864             return
1865         end
1866
1867         StartFlag = questdlg(strvcat('','Is it OK to start orbit feedback?'),'Orbit Feedback','Yes','No','No');
1868         if strcmp(StartFlag,'No')
1869             % >= 2 Hz update rate on IDBPMs
1870             disp('   IDBPM time constant set to 0.25s.')
1871             setbpmtimeconstant(0.25)
1872
1873             a = clock;
1874             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1875             fprintf('   ***************************\n');
1876             fprintf('   **  Orbit Feedback Exit  **\n');
1877             fprintf('   ***************************\n\n');
1878             pause(0);
1879             return
1880         end
1881
1882         SR_STATE_OLD = scaget('SR_STATE');
1883         setpv('SR_STATE', 5);
1884         set(0,'showhiddenhandles','on');
1885         [StateNumber, StateString] = getsrstate;
1886         if StateNumber >= 0
1887             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1888         else
1889             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1890         end
1891         fprintf('   Using %d E-vectors horizontally.\n', length(Xivec));
1892         fprintf('   Using %d E-vectors vertically.\n',   length(Yivec));
1893         fprintf('   Starting slow orbit correction every %.1f seconds.\n', LoopDelay);
1894         %  fprintf('   Resetting SR11 chicane motors every 20 seconds to fix drift problem.\n');
1895
1896
1897         try
1898
1899             % Get and display data
1900             x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
1901             y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
1902             STDx = norm(x)/sqrt(length(x));
1903             STDy = norm(y)/sqrt(length(y));
1904             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
1905             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
1906
1907             % write goldenorbit values to Fast Orbit Feedback
1908             try
1909                 write_goldenorbit_ffb;
1910             catch
1911                 disp('write_goldenorbit_ffb did not work!');
1912             end
1913             setpv('SR01____FFBON__BC00',2);
1914             pause(0);
1915
1916         catch
1917
1918             fprintf('\n  %s \n',lasterr);
1919
1920             % >= 2 Hz update rate on IDBPMs
1921             disp('   IDBPM time constant set to 0.25s.')
1922             setbpmtimeconstant(0.25);
1923
1924
1925             a = clock;
1926             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1927             fprintf('   *************************************************************\n');
1928             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
1929             fprintf('   *************************************************************\n\n');
1930
1931             setpv('SR_STATE',SR_STATE_OLD);
1932             [StateNumber, StateString] = getsrstate;
1933             if StateNumber >= 0
1934                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1935             else
1936                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1937             end
1938             set(0,'showhiddenhandles','off');
1939             pause(0);
1940
1941             return
1942
1943         end
1944
1945
1946         % Disable buttons
1947         set(0,'showhiddenhandles','on');
1948         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','off');
1949         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','on');
1950         set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','off');
1951         set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','off');
1952         set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','off');
1953         set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','off');
1954         set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','off');
1955         set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','off');
1956         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','off');
1957         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','off');
1958         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','off');
1959         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','off');
1960         set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','off');
1961         pause(0);
1962
1963
1964         % Initialize feedback loop
1965         StartTime = gettime;
1966         StartErrorTime = gettime;
1967         Xold = getx(FB.OCSx.BPM.DeviceList);
1968         Yold = gety(FB.OCSy.BPM.DeviceList);
1969         HQMOFM_stalenum = 0;
1970         pause(LoopDelay);
1971
1972         N_HCM = size(HCMlist1,1);
1973         N_VCM = size(VCMlist1,1);
1974
1975         N_RFMO = 1;
1976
1977         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
1978             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'SetRF','Nodisplay','Nosetsp');
1979         else
1980             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
1981         end
1982         [FB.OCSx, Smatx, Sx, Ux, Vx] = orbitcorrectionmethods(FB.OCSx);
1983
1984         [FB.OCSy, junk, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
1985         [FB.OCSy, Smaty, Sy, Uy, Vy] = orbitcorrectionmethods(FB.OCSy);
1986
1987         % Load lattice set for tune feed forward
1988         ConfigSetpoint = getproductionlattice;
1989         QFsp = ConfigSetpoint.QF.Setpoint.Data;
1990         QDsp = ConfigSetpoint.QD.Setpoint.Data;
1991
1992         %%%%%%%%%%%%%%%%%%%%%%%
1993         % Start feedback loop %
1994         %%%%%%%%%%%%%%%%%%%%%%%
1995
1996         % chicaneloop=1;  % loop variable for resetting drifting chicanes (see a few lines below)
1997         % fftest=figure;
1998
1999         setpv('SR01____FFBON__BC00',2); % put FOFB in open loop so beamnoise gets recorded even if FOFB is not enabled
2000
2001         while 1
2002             try
2003                 t00 = gettime;
2004
2005                 %          if chicaneloop==20 % reset SR11 motor chicane setpoints every 20s due to drifting positions
2006                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(6),[11 1],0);
2007                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(7),[11 2],0);
2008                 %             chicaneloop = 1;
2009                 %          else
2010                 %             chicaneloop = chicaneloop + 1;
2011                 %          end
2012
2013                 % Check if GUI has been closed
2014                 if isempty(gcbf)
2015                     FEEDBACK_STOP_FLAG = 1;
2016                     lasterr('SRCONTROL GUI DISAPPEARED!');
2017                     error('SRCONTROL GUI DISAPPEARED!');
2018                 end
2019
2020                 %%%%%%%%%%%%%%%%%%%%%%%
2021                 % Fast orbit feedback %
2022                 %%%%%%%%%%%%%%%%%%%%%%%
2023                 if StartFOFBFlag == 1 & FBloopIter > 3
2024                     setpv('SR01____FFBON__BC00',2);
2025                     pause(0.5);
2026                     setpv('SR01____FFBON__BC00',1);
2027                     StartFOFBFlag = 0;
2028                     pause(1);
2029                     FOFBOnStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2030                         getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2031                         getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2032                         getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2033                     if any(FOFBOnStatus==0) | any(FOFBOnStatus==2)
2034                         setpv('SR01____FFBON__BC00',2); % open FOFB loop
2035                         disp('************************************************************************************************************');
2036                         disp('** Problem turning on Fast Orbit Feedback system...                                                       **');
2037                         disp('** Check status of ffbsecXX crates - but remember that a crate reboot will turn off Quads in that sector! **');
2038                         disp('** Suggest disabling the "Fast Orbit Correction" checkbox and starting Orbit Feedback again.              **');
2039                         disp('************************************************************************************************************');
2040                     else
2041                         fprintf('   Starting Fast Orbit Feedback at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
2042                     end
2043                 end
2044
2045
2046                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2047                 % Horizontal plane "feedback" %
2048                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2049
2050                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxSOFB'),'Value') == 1
2051
2052                     % Get orbit and check that the BPMs are different from the last update
2053                     Xnew = getx(FB.OCSx.BPM.DeviceList);
2054
2055                     % Don't feedback if the current is too small
2056                     if getdcct < 5
2057                         FEEDBACK_STOP_FLAG = 1;
2058                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2059                         break;
2060                     end
2061
2062                     x = Xgoal - Xnew;
2063                     STDx = norm(x)/sqrt(length(x));
2064
2065                     if any(Xold == Xnew)
2066                         a = clock;
2067                         N_Stale_Data_Points = find((Xold==Xnew)==1);
2068                         for loop = N_Stale_Data_Points'
2069                             fprintf('   Stale data: BPMx(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSx.BPM.DeviceList(loop,1), FB.OCSx.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2070                         end
2071                     else
2072                         % Compute horizontal correction
2073                         %%%OCSx0 = FB.OCSx;
2074                         FB.OCSx.BPM.Data = Xnew;
2075                         FB.OCSx = orbitcorrectionmethods(FB.OCSx, Smatx, Sx, Ux, Vx);
2076
2077                         %%%[FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
2078
2079                         % reduced feedback gain (implemented by Greg Portmann, December 2000)
2080                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2081                         % increased back to 0.8 C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2082                         % increased to 1.0, C. Steier, 2002-05-04, trim DACs
2083                         X = Xgain .* FB.OCSx.CM.Delta;
2084                         X(N_HCM+1) = 0.3*FB.OCSx.DeltaRF/4.988e-3;
2085                         %%%X = Xgain .* (FB.OCSx.CM.Data - OCSx0.CM.Data);
2086
2087                         % check for trim values+next step values, warn or stop FB as necessary
2088                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2089                         % need to extract Chicanes from this comparison or maybe check them first for range %
2090                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2091                         HCMtrimSP=getpv('HCM','Trim',HCMlist1);
2092                         HCMtrimSP_next = HCMtrimSP + X(1:N_HCM);
2093                         if max(abs(HCMtrimSP_next)) > 4
2094                             HCMtrimnum=find(abs(HCMtrimSP_next) > 4);
2095
2096                             % print message to screen
2097                             fprintf('**One or more of the horizontal correctors is at its maximum!! Stopping orbit feedback. \n');
2098                             fprintf('%s\n',datestr(now));
2099                             for loop = HCMtrimnum'
2100                                 fprintf('**%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2101                             end
2102
2103                             % send alphapage to operator pager
2104                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2105                             FEEDBACK_STOP_FLAG = 1;
2106
2107                             setpv('SR_STATE', -5);
2108                             [StateNumber, StateString] = getsrstate;
2109                             if StateNumber >= 0
2110                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2111                             else
2112                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2113                             end
2114                         end
2115
2116                         if FEEDBACK_STOP_FLAG == 1
2117                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2118                             disp('   Stopping Fast Orbit Feedback.');
2119                             setpv('SR01____FFBON__BC00',0);
2120                             pause(0.5);
2121                             setpv('SR01____FFBON__BC00',2);
2122                             break;
2123                         end
2124
2125                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2126                         pause(0);
2127
2128                         if max(abs(HCMtrimSP_next) > 3)
2129                             HCMtrimnum=find(abs(HCMtrimSP_next) > 3);
2130                             HWarnNum=HWarnNum+1;
2131                             if (HWarnNum==1 | rem(HWarnNum,120)==0)
2132
2133                                 % print message to screen every two minutes
2134                                 fprintf('**One or more of the horizontal corrector trims is above 3A or below -3A! \n');
2135                                 fprintf('%s\n',datestr(now));
2136                                 for loop = HCMtrimnum'
2137                                     fprintf('**%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2138                                 end
2139                                 fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2140
2141                                 %send alphapage to operator pager the first time then at 10 minutes
2142                                 if (HWarnNum==1 | HWarnNum==600)
2143                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageHCM.txt
2144                                 end
2145                             end
2146                         else
2147                             HWarnNum=0;
2148                         end
2149
2150                         % Don't feedback if the current is too small
2151                         if getdcct < 5
2152                             FEEDBACK_STOP_FLAG = 1;
2153                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2154                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2155                             break;
2156                         end
2157
2158                         if N_HCM > 0
2159                             steppv('HCM','Trim', X(iNotHCMChicane), HCMlist1(iNotHCMChicane,:), 0);
2160                             steppv('HCM','Setpoint', X(iHCMChicane), HCMlist1(iHCMChicane,:), 0);
2161                         end
2162
2163                         % write fast orbit feedback setpoints
2164                         if 1
2165                             %write_goldenorbit_ffb_2planes(1, Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM)+Sx3*X(length(X))/20, BPMlist1);
2166                             % should be corrected to include result of next frequency step ...
2167                             write_goldenorbit_ffb_2planes(1,Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM),BPMlist1);
2168                         end
2169
2170                         %fprintf('Horizontal Done: %f \n',gettime-t00);
2171
2172                         % RF feedback
2173                         HQMOFMsp_last = getpv('EG______HQMOFM_AC01');
2174
2175                         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2176                             if N_RFMO > 0
2177                                 if abs(X(end)/3) < .01
2178                                 % if abs(FB.OCSx.DeltaRF/3) < .01
2179                                     steppv('EG______HQMOFM_AC01', X(end));
2180                                 else
2181                                     steppv('EG______HQMOFM_AC01', 0.01*sign(X(end)));
2182                                 end
2183                             end
2184
2185                             HQMOFMsp_now = getpv('EG______HQMOFM_AC01');
2186
2187                             % Check for stale RF feedback
2188                             if HQMOFMsp_last == HQMOFMsp_now
2189                                 HQMOFM_stalenum = HQMOFM_stalenum + 1;
2190                                 if HQMOFM_stalenum == 30 % warn and message to pager if stale for 30 secs
2191                                     fprintf('**The RF is not responding to orbit feedback changes! \n');
2192                                     fprintf('%s\n',datestr(now));
2193                                     fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2194                                     fprintf('**ILC 73 controls the EG______HQMOFM_AC01 channel, which sets the RF frequency. \n');
2195                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstaleRFmessage.txt
2196                                 end
2197                                 if rem(HQMOFM_stalenum,120)==0 % message to screen every 2 minutes
2198                                     fprintf('**The RF is not responding to orbit feedback changes! (%s)\n',datestr(now));
2199                                 end
2200                             else
2201                                 HQMOFM_stalenum = 0;
2202                             end
2203
2204                         end
2205
2206                         %fprintf('RF Done: %f \n',gettime-t00);
2207
2208                         Xold = Xnew;
2209                     end % End horizontal correction
2210
2211
2212                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2213                     % Vertical plane "feedback" %
2214                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2215
2216                     % Get orbit and check that the BPMs are different from the last update
2217                     Ynew = gety(FB.OCSy.BPM.DeviceList);
2218
2219                     % Don't feedback if the current is too small
2220                     if getdcct < 5
2221                         FEEDBACK_STOP_FLAG = 1;
2222                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2223                         break;
2224                     end
2225
2226                     y = Ygoal - Ynew;
2227                     STDy = norm(y)/sqrt(length(y));
2228
2229                     if any(Yold == Ynew)
2230                         a = clock;
2231                         N_Stale_Data_Points = find((Yold==Ynew)==1);
2232                         for loop = N_Stale_Data_Points'
2233                             fprintf('   Stale data: BPMy(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSy.BPM.DeviceList(loop,1), FB.OCSy.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2234                         end
2235
2236                     else
2237
2238                         % Compute vertical correction
2239                         %%%OCSy0 = FB.OCSy;
2240                         FB.OCSy.BPM.Data = Ynew;
2241                         FB.OCSy = orbitcorrectionmethods(FB.OCSy, Smaty, Sy, Uy, Vy);
2242
2243                         %%%[FB.OCSy, RF, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
2244
2245                         % reduced feedback gain, C. Steier, 2001-03-25
2246                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2247                         % increased back to 0.8, C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2248                         % set to unity gain, C. Steier, 2002-05-04, trim DACs
2249                         Y = Ygain .* FB.OCSy.CM.Delta;
2250                         %%%Y = Ygain .* (FB.OCSy.CM.Data - OCSy0.CM.Data);
2251
2252                         % Just SVD correction
2253                         % warning('Not using "micado" correction in the vertical plane.');
2254
2255                         % check for trim values+next step values, warn or stop FB as necessary
2256                         VCMtrimSP = getpv('VCM','Trim',VCMlist1);
2257                         VCMtrimSP_next = VCMtrimSP + Y(1:N_VCM);
2258                         if max(abs(VCMtrimSP_next)) > 12
2259                             VCMtrimnum=find(abs(VCMtrimSP_next) > 12);
2260
2261                             % print message to screen
2262                             fprintf('**One or more of the vertical correctors is at its maximum!! Stopping orbit feedback. \n');
2263                             fprintf('%s\n',datestr(now));
2264                             for loop = VCMtrimnum'
2265                                 fprintf('**%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2266                             end
2267
2268                             % send alphapage to operator pager
2269                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2270                             FEEDBACK_STOP_FLAG = 1;
2271
2272                             setpv('SR_STATE', -5);
2273                             [StateNumber, StateString] = getsrstate;
2274                             if StateNumber >= 0
2275                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2276                             else
2277                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2278                             end
2279                         end
2280
2281                         if FEEDBACK_STOP_FLAG == 1
2282                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2283                             disp('   Stopping Fast Orbit Feedback.');
2284                             setpv('SR01____FFBON__BC00',0);
2285                             pause(0.5);
2286                             setpv('SR01____FFBON__BC00',2);
2287                             break;
2288                         end
2289
2290                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2291                         % pause(0);
2292
2293                         if max(abs(VCMtrimSP_next) > 4)
2294                             VCMtrimnum=find(abs(VCMtrimSP_next) > 4);
2295                             VWarnNum=VWarnNum+1;
2296                             if (VWarnNum==1 | rem(VWarnNum,120)==0)
2297
2298                                 % print message to screen every two minutes
2299                                 fprintf('**One or more of the vertical corrector trims is above 4A or below -4A! \n');
2300                                 fprintf('%s\n',datestr(now));
2301                                 for loop = VCMtrimnum'
2302                                     fprintf('**%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2303                                 end
2304                                 fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2305
2306                                 %send alphapage to operator pager the first time then at 10 minutes
2307                                 if (VWarnNum==1 | VWarnNum==600)
2308                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageVCM.txt
2309                                 end
2310                             end
2311                         else
2312                             VWarnNum=0;
2313                         end
2314
2315                         % Don't feedback if the current is too small
2316                         if getdcct < 5
2317                             FEEDBACK_STOP_FLAG = 1;
2318                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2319                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2320                             break;
2321                         end
2322
2323                         if N_VCM > 0
2324                             steppv('VCM','Trim', Y(iNotVCMChicane), VCMlist1(iNotVCMChicane,:), 0);
2325                             steppv('VCM','Setpoint', Y(iVCMChicane), VCMlist1(iVCMChicane,:), 0);
2326                         end
2327
2328                         % write fast orbit feedback setpoints
2329                         if 1
2330                             write_goldenorbit_ffb_2planes(2,Ynew(1:size(BPMlist1,1))+Sy1*Y(1:N_VCM),BPMlist1);
2331                         end
2332
2333                     end
2334
2335                     Yold = Ynew;
2336
2337                     %fprintf('Vertical Done: %f \n',gettime-t00);
2338                 end % End vertical correction
2339
2340
2341                 %%%%%%%%%%%%%%%%%%%%%
2342                 % Tune feed forward %
2343                 %%%%%%%%%%%%%%%%%%%%%
2344                 % We should do a Sector limit check
2345
2346                 tic;
2347                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxTune'),'Value') == 1
2348
2349                     if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, High Tune') || strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Inject at 1.23') || strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
2350
2351                         if strcmp(FFTypeFlag,'Local')
2352                             disp('  No local tune compensation available - global is the default now.');
2353                         elseif strcmp(FFTypeFlag,'Global')
2354
2355                             addQFsp = zeros(24,1);
2356                             addQDsp = zeros(24,1);
2357                             Sector = getlist('ID');
2358                             for gapnum = 1:size(Sector,1)
2359                                 % Change in tune and [QF;QD] from maximum gap
2360                                 actualgap = getid(Sector(gapnum,:));
2361                                 [gapmin,gapmax] = gaplimit(Sector(gapnum,:));
2362                                 if actualgap < (gapmin-1)
2363                                     actualgap = gapmax;
2364                                 end
2365
2366                                 if (Sector(gapnum,1) == 4) | (Sector(gapnum,1) == 11)
2367                                     if Sector(gapnum,2) == 1
2368                                         modenamestr = sprintf('SR%02dU___ODS1M__DC00',Sector(gapnum,1));
2369                                     else % if Sector(gapnum,2) == 2
2370                                         modenamestr = sprintf('SR%02dU___ODS2M__DC00',Sector(gapnum,1));
2371                                     end
2372                                     epumode = getpv(modenamestr);
2373
2374                                     DelQF = zeros(24,1);
2375                                     DelQD = zeros(24,1);
2376
2377                                     % [DelQF, DelQD] =
2378                                         % ffdeltaquadepu(Sector(gapnum,:), actualgap, getepu(Sector(gapnum,:)), epumode, SR_GeV);
2379                                 else
2380                                     [DelQF, DelQD] = ...
2381                                         ffdeltaquad(Sector(gapnum,:), actualgap, SR_GeV);
2382                                 end
2383
2384                                 % if Sector(gapnum,1)==5
2385                                 %     DelQF
2386                                 %     DelQD
2387                                 % end
2388
2389                                 addQFsp = addQFsp+DelQF;
2390                                 addQDsp = addQDsp+DelQD;
2391                             end
2392                         else
2393                             error('Unknown type selected for tune FF');
2394                         end
2395
2396                         % Set quadrupoles using main setpoint channels
2397                         setpv('QF', QFsp+addQFsp,[], 0);
2398                         setpv('QD', QDsp+addQDsp,[], 0);
2399
2400 %                         % Set quadrupoles using FF setpoint channels
2401 %                         setpv('QF', 'FF', addQFsp, [], 0);
2402 %                         setpv('QD', 'FF', addQDsp, [], 0);
2403
2404                     else
2405                         disp('  No tune FF algorithm for non-production modes yet...');
2406                     end
2407                 end
2408                 ffdeltaquad_delay = toc;
2409                 fprintf('tune FF delay = %.1f seconds\n',ffdeltaquad_delay);
2410                 % fprintf('Tune Done: %f \n',gettime-t00);
2411
2412                 % Output info to screen
2413                 set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
2414                 set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
2415                 pause(0);
2416
2417
2418                 fprintf('End of feedback operations: %f \n\n',gettime-t00);
2419
2420                 % Wait for next update time or stop request
2421                 while (gettime-t00) < LoopDelay
2422                     %disp('interval could be shorter')
2423                     pause(.05);
2424                     % Check if GUI has been closed
2425                     if isempty(gcbf)
2426                         FEEDBACK_STOP_FLAG = 1;
2427                         lasterr('SRCONTROL GUI DISAPPEARED!');
2428                         error('SRCONTROL GUI DISAPPEARED!');
2429                     end
2430
2431                     % Check if Stop button was pressed
2432                     if FEEDBACK_STOP_FLAG == 1
2433                         % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2434                         disp('   Stopping Fast Orbit Feedback.');
2435                         setpv('SR01____FFBON__BC00',0);
2436                         pause(0.5);
2437                         setpv('SR01____FFBON__BC00',2);
2438                         break;
2439                     end
2440                 end
2441
2442
2443                 if FEEDBACK_STOP_FLAG == 1
2444                     % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2445                     disp('   Stopping Fast Orbit Feedback.');
2446                     setpv('SR01____FFBON__BC00',0);
2447                     pause(0.5);
2448                     setpv('SR01____FFBON__BC00',2);
2449                     break;
2450                 end
2451
2452                 StartErrorTime = gettime;
2453
2454             catch
2455
2456                 fprintf('\n  %s \n',lasterr);
2457
2458                 % Quit if error exists for more than 20 seconds
2459                 if gettime-StartErrorTime>20 | FEEDBACK_STOP_FLAG==1
2460                     fprintf('%s  Orbit feedback stopped due to error condition. \n\n',datestr(now));
2461
2462                     %send alphapage to operator pager
2463                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2464                     FEEDBACK_STOP_FLAG = 1;
2465
2466                     setpv('SR_STATE', -5);
2467                     [StateNumber, StateString] = getsrstate;
2468                     if StateNumber >= 0
2469                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2470                     else
2471                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2472                     end
2473                 else
2474                     a = clock;
2475                     fprintf('   Orbit feedback was paused due to error condition (%s %d:%d:%.0f). \n', date, a(4), a(5), a(6));
2476                     fprintf('   Orbit feedback has automatically restarted and is running. \n\n');
2477                 end
2478
2479             end
2480
2481             if FEEDBACK_STOP_FLAG == 1
2482                 % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2483                 disp('   Stopping Fast Orbit Feedback.');
2484                 setpv('SR01____FFBON__BC00',0);
2485                 pause(0.5);
2486                 setpv('SR01____FFBON__BC00',2);
2487                 break;
2488             end
2489
2490             %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2491
2492             %pause(0);
2493
2494             % this loop delays turn on of Fast Feedback system
2495             if FBloopIter < 5
2496                 FBloopIter = FBloopIter + 1;
2497             end
2498
2499         end  % End of feedback loop
2500
2501
2502         % End feedback, reset all parameters
2503         try
2504
2505             % Enable buttons
2506             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','on');
2507             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','off');
2508             set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','on');
2509             set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','on');
2510             set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','on');
2511             set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','on');
2512             set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','on');
2513             set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','on');
2514             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','on');
2515             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','on');
2516             set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','on');
2517             set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','on');
2518             set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','on');
2519
2520             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = _____ mm'),'ForegroundColor',[0 0 0]);
2521             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = _____ mm'),'ForegroundColor',[0 0 0]);
2522             pause(0);
2523
2524         catch
2525
2526             % GUI must have been closed
2527
2528         end
2529
2530
2531         % >= 2 Hz update rate on IDBPMs
2532         disp('   IDBPM time constant set to 0.25s.');
2533         setbpmtimeconstant(0.25);
2534
2535
2536         a = clock;
2537         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2538         [StateNumber, StateString] = getsrstate;
2539         if StateNumber >= 0
2540             setpv('SR_STATE',5.1);
2541             [StateNumber, StateString] = getsrstate;
2542             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2543             fprintf('   ******************************\n');
2544             fprintf('   **  Orbit Feedback Stopped  **\n');
2545             fprintf('   ******************************\n\n');
2546         else
2547             [StateNumber, StateString] = getsrstate;
2548             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2549             fprintf('   ****************************************\n');
2550             fprintf('   **  Problem With Slow Orbit Feedback  **\n');
2551             fprintf('   ****************************************\n\n');
2552         end
2553         set(0,'showhiddenhandles','off');
2554         pause(0);
2555
2556
2557     case 'FeedbackSetup'
2558         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
2559
2560         if InitFlag
2561             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2562             % Edit the following lists to change default configuration of Orbit Correction %
2563             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2564
2565             % Corrector magnets
2566             listh=[
2567                 1 2;
2568                 1 8;
2569                 2 1;
2570                 2 8;
2571                 3 1;
2572                 3 8;
2573                 3 10; %SR04U_HCM2 (chicane trim)
2574                 4 1;
2575                 4 8;
2576                 5 1;
2577                 5 8;
2578                 5 10; %SR06U_HCM2 (chicane trim)
2579                 6 1;
2580                 6 8;
2581                 7 1;
2582                 7 8;
2583                 8 1;
2584                 8 8;
2585                 9 1;
2586                 9 8;
2587                 10 1;
2588                 10 8;
2589                 10 10; %SR11U_HCM2 (chicane trim)
2590                 11 1;
2591                 11 8;
2592                 12 1;
2593                 12 7];
2594             listv=[
2595                 1 2;
2596                 1 8;
2597                 2 1;
2598                 2 8;
2599                 3 1;
2600                 3 7;
2601                 3 8;
2602                 3 10; %SR04U_VHCM2 (chicane trim)
2603                 4 1;
2604                 4 7;
2605                 4 8;
2606                 5 1;
2607                 5 8;
2608                 5 10; %SR06U_VHCM2 (chicane trim)
2609                 6 1;
2610                 6 8;
2611                 7 1;
2612                 7 8;
2613                 8 1;
2614                 8 8;
2615                 9 1;
2616                 9 8;
2617                 10 1;
2618                 10 2;
2619                 10 7;
2620                 10 8;
2621                 10 10; %SR11U_VHCM2 (chicane trim)
2622                 11 1;
2623                 11 7;
2624                 11 8;
2625                 12 1;
2626                 12 7];
2627
2628             Xivec = [1:28];
2629             Yivec = [1:32];
2630             HCMlist1 = listh;
2631             VCMlist1 = listv;
2632
2633             % Full BPM list
2634             BPMlist1 = [
2635                 1 2
2636                 1 5
2637                 1 6
2638                 1 10
2639                 2 1
2640                 2 5
2641                 2 6
2642                 2 9
2643                 3 2
2644                 3 5
2645                 3 6
2646                 3 10
2647                 3 11
2648                 3 12
2649                 4 1
2650                 4 5
2651                 4 6
2652                 4 10
2653                 5 1
2654                 5 5
2655                 5 6
2656                 5 10
2657                 5 11
2658                 5 12
2659                 6 1
2660                 6 5
2661                 6 6
2662                 6 10
2663                 7 1
2664                 7 5
2665                 7 6
2666                 7 10
2667                 8 1
2668                 8 5
2669                 8 6
2670                 8 10
2671                 9 1
2672                 9 5
2673                 9 6
2674                 9 10
2675                 10 1
2676                 10 5
2677                 10 6
2678                 10 10
2679                 10 11
2680                 10 12
2681                 11 1
2682                 11 5
2683                 11 6
2684                 11 10
2685                 12 1
2686                 12 5
2687                 12 6
2688                 12 9
2689                 ];
2690
2691             % remove Bergoz BPMs in SR01 and SR03 for 2-bunch (noisy at low currents) and drop singular values
2692             if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
2693                     BPMlist1 = [
2694                          %1 2
2695                          1 5
2696                          1 6
2697                          1 10
2698                          2 1
2699                          2 5
2700                          2 6
2701                          %2 9
2702                          %3 2
2703                          3 5
2704                          3 6
2705                          3 10
2706                          3 11
2707                          3 12
2708                          4 1
2709                          4 5
2710                          4 6
2711                          4 10
2712                          5 1
2713                          5 5
2714                          5 6
2715                          5 10
2716                          5 11
2717                          5 12
2718                          6 1
2719                          6 5
2720                          6 6
2721                          6 10
2722                          7 1
2723                          7 5
2724                          7 6
2725                          7 10
2726                          8 1
2727                          8 5
2728                          8 6
2729                          8 10
2730                          9 1
2731                          9 5
2732                          9 6
2733                          9 10
2734                          10 1
2735                          10 5
2736                          10 6
2737                          10 10
2738                          10 11
2739                          10 12
2740                          11 1
2741                          11 5
2742                          11 6
2743                          11 10
2744                          12 1
2745                          12 5
2746                          12 6
2747                          %12 9
2748                          ];
2749             end
2750
2751             OCSx.BPM = getx(BPMlist1, 'struct');
2752             OCSx.CM = getsp('HCM', HCMlist1, 'struct');
2753             OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
2754             OCSx.NIter = 1;
2755             OCSx.SVDIndex = Xivec;
2756             OCSx.IncrementalFlag = 'No';
2757             OCSx.BPMWeight = {[]};
2758             OCSx.FitRF = 0;
2759             OCSy.BPM = gety(BPMlist1, 'struct');
2760             OCSy.CM = getsp('VCM', VCMlist1, 'struct');
2761             OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
2762             OCSy.NIter = 1;
2763             OCSy.SVDIndex = Yivec;
2764             OCSy.IncrementalFlag = 'No';
2765             OCSy.BPMWeight = {[]};
2766             OCSy.FitRF = 0;
2767             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2768             % do we need these Smat calls? %
2769             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2770             SXmat = getrespmat(OCSx.BPM, OCSx.CM, 'numeric');
2771             SYmat = getrespmat(OCSy.BPM, OCSy.CM, 'numeric');
2772             % [OCSx, Sx, Ux, Vx] = orbitcorrectionmethods(OCSx, SXmat);
2773             % [OCSy, Sy, Uy, Vy] = orbitcorrectionmethods(OCSy, SYmat);
2774
2775             % initialize FFTypeFlag
2776             FFTypeFlag = 'Global';
2777
2778         else
2779
2780             % Get vectors
2781             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
2782             % the two lines below seem to fix BPMlist editing problem
2783             OCSx = FB.OCSx;
2784             OCSy = FB.OCSy;
2785             BPMlist1 = FB.BPMlist1;
2786             HCMlist1 = FB.HCMlist1;
2787             VCMlist1 = FB.VCMlist1;
2788             Xivec = FB.Xivec;
2789             Yivec = FB.Yivec;
2790             Xgoal = FB.OCSx.GoalOrbit;
2791             OCSx.GoalOrbit = Xgoal;
2792             Ygoal = FB.OCSy.GoalOrbit;
2793             OCSy.GoalOrbit = Ygoal;
2794             FFTypeFlag = FB.FFTypeFlag;
2795
2796
2797             % FF corrector magnet list
2798             ListFF = [
2799                 4     2
2800                 4     8
2801                 5     1
2802                 5     7
2803 %               5     8 % why are these out???
2804 %               6     1 % why are these out???
2805                 6     8
2806                 7     1
2807                 7     8
2808                 8     1
2809                 8     8
2810                 9     1
2811                 9     8
2812                 10    1
2813                 11    8
2814                 12    1];
2815             ElemFF = dev2elem('HCM',ListFF);
2816
2817
2818             % Add button to change #ivectors, cm, IDBPMs,
2819             EditFlag = 0;
2820             h_fig1 = figure;
2821             while EditFlag ~= 7
2822
2823                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
2824                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
2825
2826                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2827                     DispOrbit = getdisp('BPMx', BPMlist1);
2828                     Sx = [Sx DispOrbit];
2829                 end
2830
2831                 [Ux, SVx, Vx] = svd(Sx);
2832                 [Uy, SVy, Vy] = svd(Sy);
2833
2834
2835                 % Remove singular values greater than the actual number of singular values
2836                 i = find(Xivec>length(diag(SVx)));
2837                 if ~isempty(i)
2838                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
2839                     pause(0);
2840                     Xivec(i) = [];
2841                 end
2842                 i = find(Yivec>length(diag(SVy)));
2843                 if ~isempty(i)
2844                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
2845                     pause(0);
2846                     Yivec(i) = [];
2847                 end
2848
2849
2850                 Ax = Sx*Vx(:,Xivec);
2851                 Tx = inv(Ax'*Ax)*Ax';
2852
2853                 Ay = Sy*Vy(:,Yivec);
2854                 Ty = inv(Ay'*Ay)*Ay';
2855
2856                 figure(h_fig1);
2857                 subplot(2,1,1);
2858                 semilogy(diag(SVx),'b');
2859                 hold on;
2860                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
2861                 ylabel('Horizontal');
2862                 title('Response Matrix Singular Values');
2863                 hold off;
2864                 subplot(2,1,2);
2865                 semilogy(diag(SVy),'b');
2866                 hold on;
2867                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
2868                 xlabel('Singular Value Number');
2869                 ylabel('Vertical');
2870                 hold off;
2871                 drawnow;
2872
2873                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List', ...
2874                     'BPM List','Change the Goal Orbit', ...
2875                     'Change Tune FF Method (nuy=9.2 only)','Continue');
2876
2877                 if EditFlag == 1
2878                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
2879                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
2880                     titlestr='SVD Orbit Feedback';
2881                     lineNo=1;
2882                     answer=inputdlg(prompt,titlestr,lineNo,def);
2883                     if ~isempty(answer)
2884                         XivecNew = fix(str2num(answer{1}));
2885                         if isempty(XivecNew)
2886                             disp('   Horizontal E-vector cannot be empty.  No change made.');
2887                         else
2888                             if any(XivecNew<=0) | max(XivecNew)>length(diag(SVx))
2889                                 disp('   Error reading horizontal E-vector.  No change made.');
2890                             else
2891                                 Xivec = XivecNew;
2892                             end
2893                         end
2894                         YivecNew = fix(str2num(answer{2}));
2895                         if isempty(YivecNew)
2896                             disp('   Vertical E-vector cannot be empty.  No change made.');
2897                         else
2898                             if any(YivecNew<=0) | max(YivecNew)>length(diag(SVy))
2899                                 disp('   Error reading vertical E-vector.  No change made.');
2900                             else
2901                                 Yivec = YivecNew;
2902                             end
2903                         end
2904                     end
2905                 end
2906
2907                 if EditFlag == 2
2908                     List= getlist('HCM','Trim');
2909                     CheckList = zeros(96,1);
2910                     Elem = dev2elem('HCM', HCMlist1);
2911                     CheckList(Elem) = ones(size(Elem));
2912                     CheckList = CheckList(dev2elem('HCM',List));
2913
2914                     % Remove FF corrrectors
2915                     %           Elem = dev2elem('HCM',List);
2916                     %           for j = length(ElemFF):-1:1
2917                     %              i = find(Elem==ElemFF(j));
2918                     %              Elem(i,:) = [];
2919                     %              List(i,:) = [];
2920                     %              CheckList(i,:) = [];
2921                     %           end
2922
2923                     newList = editlist(List, 'HCMtrim', CheckList);
2924
2925                     if isempty(newList)
2926                         fprintf('   WARNING: Horizontal corrector magnet list is empty!\n');
2927                         HCMlist1 = newList;
2928                     else
2929                         HCMlist1 = newList;
2930                     end
2931                 end
2932
2933                 if EditFlag == 3
2934                     List = getlist('VCM','Trim');
2935                     CheckList = zeros(96,1);
2936                     Elem = dev2elem('VCM', VCMlist1);
2937                     CheckList(Elem) = ones(size(Elem));
2938                     CheckList = CheckList(dev2elem('VCM',List));
2939
2940                     % Remove FF corrrectors
2941                     %           Elem = dev2elem('VCM',List);
2942                     %           for j = length(ElemFF):-1:1
2943                     %              i = find(Elem==ElemFF(j));
2944                     %              Elem(i,:) = [];
2945                     %              List(i,:) = [];
2946                     %              CheckList(i,:) = [];
2947                     %           end
2948
2949                     newList = editlist(List, 'VCMtrim', CheckList);
2950
2951                     if isempty(newList)
2952                         fprintf('   WARNING: Vertical corrector magnet list is empty!\n');
2953                         VCMlist1 = newList;
2954                     else
2955                         VCMlist1 = newList;
2956                     end
2957                 end
2958
2959                 if EditFlag == 4
2960                     ListOld = BPMlist1;
2961                     XgoalOld = Xgoal;
2962                     YgoalOld = Ygoal;
2963
2964                     % Full BPM list
2965                     List = [
2966                         1 2
2967                         1 5
2968                         1 6
2969                         1 10
2970                         2 1
2971                         2 5
2972                         2 6
2973                         2 9
2974                         3 2
2975                         3 5
2976                         3 6
2977                         3 10
2978                         3 11
2979                         3 12
2980                         4 1
2981                         4 5
2982                         4 6
2983                         4 10
2984                         5 1
2985                         5 5
2986                         5 6
2987                         5 10
2988                         5 11
2989                         5 12
2990                         6 1
2991                         6 5
2992                         6 6
2993                         6 10
2994                         7 1
2995                         7 5
2996                         7 6
2997                         7 10
2998                         8 1
2999                         8 5
3000                         8 6
3001                         8 10
3002                         9 1
3003                         9 5
3004                         9 6
3005                         9 10
3006                         10 1
3007                         10 5
3008                         10 6
3009                         10 10
3010                         10 11
3011                         10 12
3012                         11 1
3013                         11 5
3014                         11 6
3015                         11 10
3016                         12 1
3017                         12 5
3018                         12 6
3019                         12 9
3020                         ];
3021
3022
3023                     CheckList = zeros(size(List,1),1);
3024                     if ~isempty(BPMlist1)
3025                         for i = 1:size(List,1)
3026                             k = find(List(i,1)==BPMlist1(:,1));
3027                             l = find(List(i,2)==BPMlist1(k,2));
3028
3029                             if isempty(k) | isempty(l)
3030                                 % Item not in list
3031                             else
3032                                 CheckList(i) = 1;
3033                             end
3034                         end
3035                     end
3036
3037                     newList = editlist(List, 'BPM', CheckList);
3038                     if isempty(newList)
3039                         fprintf('   BPM list cannot be empty.  No change made.\n');
3040                     else
3041                         BPMlist1 = newList;
3042                     end
3043
3044                     % Set the goal orbit to the golden orbit
3045                     Xgoal = getgolden('BPMx', BPMlist1);
3046                     Ygoal = getgolden('BPMy', BPMlist1);
3047
3048
3049                     % If a new BPM is added, then set the goal orbit to the golden orbit
3050                     for i = 1:size(BPMlist1,1)
3051
3052                         % Is it a new BPM?
3053                         k = find(BPMlist1(i,1)==ListOld(:,1));
3054                         l = find(BPMlist1(i,2)==ListOld(k,2));
3055
3056                         if isempty(k) | isempty(l)
3057                             % New BPM
3058                         else
3059                             % Use the old value for old BPM
3060                             Xgoal(i) = XgoalOld(k(l));
3061                             Ygoal(i) = YgoalOld(k(l));
3062                         end
3063                     end
3064                     OCSx.BPM.DeviceList = BPMlist1;
3065                     OCSy.BPM.DeviceList = BPMlist1;
3066                     OCSx.GoalOrbit = Xgoal;
3067                     OCSy.GoalOrbit = Ygoal;
3068                 end
3069
3070                 if EditFlag == 5
3071                     ChangeList = editlist2(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
3072
3073                     for i = 1:size(ChangeList,1)
3074
3075                         k = find(ChangeList(i,1)==BPMlist1(:,1));
3076                         l = find(ChangeList(i,2)==BPMlist1(k,2));
3077
3078                         prompt={sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
3079                         def={sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
3080                         titlestr='CHANGE THE GOAL ORBIT';
3081                         lineNo=1;
3082                         answer = inputdlg(prompt, titlestr, lineNo, def);
3083
3084                         if isempty(answer)
3085                             % No change
3086                             fprintf('   No change was made to the golden orbit.\n');
3087                         else
3088                             Xgoalnew = str2num(answer{1});
3089                             if isempty(Xgoalnew)
3090                                 fprintf('   No change was made to the horizontal golden orbit.\n');
3091                             else
3092                                 Xgoal(k(l)) = Xgoalnew;
3093                             end
3094
3095                             Ygoalnew = str2num(answer{2});
3096                             if isempty(Ygoalnew)
3097                                 fprintf('   No change was made to the vertical golden orbit.\n');
3098                             else
3099                                 Ygoal(k(l)) = Ygoalnew;
3100                             end
3101                         end
3102                     end
3103                     if ~isempty(ChangeList)
3104                         fprintf('   Note:  Changing the goal orbit for "Slow Orbit Feedback" does not change the goal orbit for "Orbit Correction."\n');
3105                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
3106                     end
3107                     OCSx.GoalOrbit = Xgoal;
3108                     OCSy.GoalOrbit = Ygoal;
3109                 end
3110
3111                 if EditFlag == 6
3112                     FFTypeFlag = questdlg(sprintf('Do you want to use a fully local or a combined local/global compensation of IDs? (nuy=9.2 only)'),'Tune FF','Local','Global', 'Global');
3113                     if strcmp(FFTypeFlag,'Local')
3114                         disp(['   The tune FF will use 8 local quadrupoles to compensate beta beating and tune shift']);
3115                         disp(['   from each ID.']);
3116                     elseif strcmp(FFTypeFlag,'Global')
3117                         disp(['   The tune FF will use 4 local quadrupoles to compensate beta beating and all QF+QD']);
3118                         disp(['   to compensate tune shift from each ID.']);
3119                     end
3120
3121                 end
3122
3123             end
3124             close(h_fig1);
3125         end
3126
3127         % Save vectors
3128         FB.Xivec = Xivec;
3129         FB.Yivec = Yivec;
3130         FB.HCMlist1 = HCMlist1;
3131         FB.VCMlist1 = VCMlist1;
3132         FB.BPMlist1 = BPMlist1;
3133
3134         OCSx.SVDIndex = Xivec;
3135         OCSy.SVDIndex = Yivec;
3136         FB.OCSx = OCSx;
3137         FB.OCSy = OCSy;
3138
3139         FB.FFTypeFlag = FFTypeFlag;
3140         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata',FB);
3141
3142
3143     case 'FastFeedbackSetup'
3144
3145         InitFlag = Input2;
3146
3147         if InitFlag
3148             FOFBFreq = 1000;
3149             % user operations 9/14-10/17/04: P=0.5, I=120, D=0.0015 (for both planes)
3150             % below are known good values for user ops as of 8-1-05
3151             HorP = 2;
3152             HorI = 300;
3153             HorD = 0.002;
3154             VertP = 1;
3155             VertI = 100;
3156             VertD = 0.0015;
3157
3158             % this initial set is now done in hwinit.m because it's not a good idea to set anything when srcontrol is launched
3159             % try
3160             %     setsp('SR01____FFBFREQAC00', FOFBFreq); % set freq
3161             %     write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3162             % catch
3163             %     disp('   Trouble setting Fast Orbit Feedback parameters!');
3164             % end
3165
3166         else
3167             % Get vectors
3168             FOFB = get(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata');
3169             FOFBFreq = FOFB.FOFBFreq;
3170             HorP  = FOFB.HorP;
3171             HorI  = FOFB.HorI;
3172             HorD  = FOFB.HorD;
3173             VertP = FOFB.VertP;
3174             VertI = FOFB.VertI;
3175             VertD = FOFB.VertD;
3176
3177             % Add button to change #ivectors, CMs, IDBPMs,
3178             EditFlag = 0;
3179             %h_fig1 = figure;
3180             while EditFlag ~= 3
3181
3182                 %EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'HCM List', 'VCM List', ...
3183                 %   'IDBPM List', 'BBPM List', 'Continue');
3184                 % Use menu below until other FFB config routines work (then also uncomment options 3,4,5,6 below)
3185                 EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'Continue');
3186
3187                 if EditFlag == 1
3188                     % change rate
3189
3190                     prompt={'Enter the desired Fast Feedback Frequency (1-1000 Hz)'};
3191                     def={num2str(FOFBFreq)};
3192                     titlestr='Fast Feedback Setup';
3193                     lineNo=1;
3194                     answer=inputdlg(prompt,titlestr,lineNo,def);
3195                     if ~isempty(answer)
3196                         FOFBFreq = fix(str2num(answer{1}));
3197                         if isempty(FOFBFreq)
3198                             disp('   Frequency value cannot be empty.  No change made.');
3199                             FOFBFreq = getsp('SR01____FFBFREQAC00');
3200                         else
3201                             if FOFBFreq < 1 | FOFBFreq > 1000
3202                                 disp('   Frequency must be between 1 and 1000 Hz.  No change made.');
3203                                 FOFBFreq = getsp('SR01____FFBFREQAC00');
3204                             end
3205                         end
3206                         setsp('SR01____FFBFREQAC00',FOFBFreq); % change freq
3207                         pause(0.5);
3208                         fprintf('   Fast orbit feedback frequency is running at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
3209                     else
3210                         FOFBFreq = getsp('SR01____FFBFREQAC00');
3211                     end
3212                 end
3213
3214                 if EditFlag == 2
3215                     % edit  PIDs
3216                     % User defaults are HorP=2, HorI=300, HorD=0.002, VertP=1, VertI=100, VertD=0.0015
3217                     prompt={'P horizontal', 'I horizontal', 'D horizontal', 'P vertical', 'I vertical', 'D vertical'};
3218                     def={num2str(HorP), num2str(HorI), num2str(HorD), num2str(VertP), num2str(VertI), num2str(VertD)};
3219                     titlestr='Fast Feedback PID Setup';
3220                     lineNo=1;
3221                     answer=inputdlg(prompt,titlestr,lineNo,def);
3222                     if ~isempty(answer)
3223                         HorPnewnum = str2num(answer{1});
3224                         if isempty(HorPnewnum)
3225                             disp('   HorP value cannot be empty.  No change made.');
3226                         else
3227                             HorP = HorPnewnum;
3228                         end
3229                         HorInewnum = str2num(answer{2});
3230                         if isempty(HorInewnum)
3231                             disp('   HorI value cannot be empty.  No change made.');
3232                         else
3233                             HorI = HorInewnum;
3234                         end
3235                         HorDnewnum = str2num(answer{3});
3236                         if isempty(HorDnewnum)
3237                             disp('   HorD value cannot be empty.  No change made.');
3238                         else
3239                             HorD = HorDnewnum;
3240                         end
3241                         VertPnewnum = str2num(answer{4});
3242                         if isempty(VertPnewnum)
3243                             disp('   VertP value cannot be empty.  No change made.');
3244                         else
3245                             VertP = VertPnewnum;
3246                         end
3247                         VertInewnum = str2num(answer{5});
3248                         if isempty(VertInewnum)
3249                             disp('   VertI value cannot be empty.  No change made.');
3250                         else
3251                             VertI = VertInewnum;
3252                         end
3253                         VertDnewnum = str2num(answer{6});
3254                         if isempty(VertDnewnum)
3255                             disp('   VertD value cannot be empty.  No change made.');
3256                         else
3257                             VertD = VertDnewnum;
3258                         end
3259
3260                         try
3261                             write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3262                             fprintf('   Setting FFB gains to Horizontal P=%.2f, I=%.1f, D=%.4f;  Vertical P=%.2f, I=%.1f, D=%.4f\n', HorP, HorI, HorD, VertP, VertI, VertD);
3263                         catch
3264                             disp('   Trouble setting Fast Orbit Feedback parameters!');
3265                         end
3266                     end
3267                 end
3268
3269                 %if EditFlag == 3
3270                 %   disp('   This function not yet available.');
3271                 %   % change HCM List
3272                 %end
3273                 %
3274                 %if EditFlag == 4
3275                 %   disp('   This function not yet available.');
3276                 %   % change VCM List
3277                 %end
3278                 %
3279                 %if EditFlag == 5
3280                 %   disp('   This function not yet available.');
3281                 %   % change IDBPM List
3282                 %end
3283                 %
3284                 %if EditFlag == 6
3285                 %   disp('   This function not yet available.');
3286                 %   % change BBPM List
3287                 %end
3288
3289             end
3290             %close(h_fig1);
3291         end
3292
3293         % Save vectors
3294         FOFB.FOFBFreq = FOFBFreq;
3295         FOFB.HorP = HorP;
3296         FOFB.HorI = HorI;
3297         FOFB.HorD = HorD;
3298         FOFB.VertP = VertP;
3299         FOFB.VertI = VertI;
3300         FOFB.VertD = VertD;
3301         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata',FOFB);
3302
3303     otherwise
3304         fprintf('   No action for %s.\n', action);
3305 end   % end case