Description of srcontrol5_with_IVIDskewFF
Home > ALS > StorageRing > srcontrol5_with_IVIDskewFF.m
srcontrol5_with_IVIDskewFF
PURPOSE
srcontrol5
SYNOPSIS
function srcontrol5(action, Input2, Input3)
DESCRIPTION
 srcontrol5
 Storage ring control program
 This program controls all storage ring magnets, performs orbit feedback and
 tune feedforward and helps to diagnose problems in routine user operation
 of the ALS storage ring. It includes a gui to simplify the use of this
 program.
 It was originally programmed by Greg Portmann (until December 2000) with input
 from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
 and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
 The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
 Christoph Steier, July 2002
 SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
 Tom Scarvie, April 2005
CROSS-REFERENCE INFORMATION
This function calls:
bend2gev BEND2GEV - Compute the energy based on the ramp tables
checksrmags CHECKSRMAGS - Check SR power supplies against a lattice file
checksrorbit ErrorNums =checksrorbit(Sector, BPMxtolerance [.015 mm], [BPMytolerance [.015 mm]])
gap2tune GAP2TUNE - Computes the vertical tune shift for a insertion device gap change.
gaplimit [GapMin, GapMax] = gaplimit(ID_Number);
getbpmtimeconstant GETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
getff function [FFEnableBM, FFEnableBC, GapEnableBM, GapEnableBC, Sector] = getff(Sector)
getid GETID - Get the insertion device position, velocity, run flag, and user requested gap
getsrstate [StateNumber, StateString] = getsrstate
set_alarmhandler_AHU_thresholds_inject function set_alarmhandler_AHU_thresholds_inject
set_alarmhandler_thresholds set_alarmhandler_thresholds
set_alarmhandler_thresholds_new set_alarmhandler_thresholds_new
set_etaywave_nuy9_20skews_skewFF function [SQSFincr, SQSDincr] = set_etaywave_nuy9_20skews_skewFF(scale);
setbpmtimeconstant SETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
setbumps SETBUMPS - Make a straight section bump
setff function setff(Sector, FFEnableBC, GapEnableBC)
setid SETID - Set the insertion device vertical gap
setsrstatechannels
shift2tune SHIFT2TUNE - Computes the horizontal tune shift for a EPU gap and horizontal shift
srcycle SRCYCLE - Storage ring cycle
srramp SRRAMP - Ramp the storage ring energy
write_goldenorbit_ffb function write_goldenorbit_ffb
write_goldenorbit_ffb_2planes WRITE_GOLDENORBIT_FFTB_2PLANES - Sets the BPM setpoints which are used by the fast feedback system
This function is called by:
SOURCE CODE
function srcontrol5(action, Input2, Input3)
% srcontrol5
% Storage ring control program
%
% This program controls all storage ring magnets, performs orbit feedback and
% tune feedforward and helps to diagnose problems in routine user operation
% of the ALS storage ring. It includes a gui to simplify the use of this
% program.
%
% It was originally programmed by Greg Portmann (until December 2000) with input
% from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
% and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
%
% The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
%
% Christoph Steier, July 2002
%
% SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
%
% Tom Scarvie, April 2005
% known bugs/problems (May 2001):
% - IDBPM averaging might be a bit too long for orbit feedback
%        solved after Superbend shutdown ... Instead of averaging, digital low pass filters are used
% - gap2tune does not give correct answers for wiggler and potentially other IDs -> orbit feedback
%        seems to be OK for other IDs, has been corrected for wiggler (fit to insertion device
%        compensation table)
% - chicanes do not work in orbit feedback
%        solved. One problem was that orbit response matrizes were mis-scaled by factor of two.
%        Second problem was different time constant of power supply control. Solved by moving controls
%        of center chicanes to cPCI (and magnets are fast, hysteresis free, aircore coils).
%        Center chicane in sector 4 is now routinely used in orbit feedback. Sector 11 to follow soon.
% - zero reading of ID gap dumps beam
%        solved in srcontrol5, still a problem in srcontrol5_hightune (but that routine has to be completely
%        rewritten because of all recent changes to srcontrol5, anyhow). For gap readings below the minimum
%        allowed gap for a device, the tune feedforward disables itself.
% - cycling of lattice causes frequent power supply failures
%        solved by changing the cycling procedure. 1.5 GeV operation is now on the upper hysteresis branch
%        as was the 1.9 GeV injection lattice before.
% - frequently stalled data in IDBPM readout
%        solved with new BPM readouts and digital filtering. Seems to have been a resolution problem
%        of the digital averaging algorithm.
% - magnet ramp tables are not in perfect agreement with magnetic measurements
%        Does not appear to be a serious problem. Superbends are slightly out of sync with other magnets,
%        but this does not cause any negative effects while ramping.
% - no good way to operate with injection at 1.5 GeV and storage energy below that
%        There now is a reasonable way to inject at 1.5 GeV and ramp down to lower storage energy. But
%        it has to be tested again after implementing new (and more) chicanes ...
% revision history
% 2001-05-10, Christoph Steier
% check whether readback from insertion device is significantly (more than 1 mm) below minimum
% gap, to avoid false zero readings of insertion device gaps to cause the tune feed forward
% to implement false huge correction (and dump the beam). If the insertion device gap readbacks
% gets more than 1 mm below the nominal minimum gap, the routine now assumes the insertion device
% to be open.
%
% 2001-08-30 and during Superbend commissioning, Christoph Steier, Tom Scarvie, Winni Decking
% various changes have been made to incorporate the Superbends and some other new equipment
% installed in the Superbend shutdown. This included some changes to programs being called by srcontrol
% (like srload, srsave, srcycle, srramp, ...). The main changes within srcontrol were in the orbit
% correction and slow orbit feedback routines (incorporating frequency feedback, ...)
%
% 2002-05-04, Christoph Steier
% added new IDBPMs, modified orbit feedback to use trim DACs, removed LSB toggling in vertical
% orbit feedback, ...
%
% 2002-07-29, T.Scarvie
% added check of CM trim currents to warn of problems that might rail the orbit feedback
%
% 2002-07-31, Christoph Steier
% increased the gain of the RF frequency feedback from 1/50 of the gain of the horizontal
% orbit feedback to 1/20. Reason was that the frequency feedback was reacting a bit too slow if all
% insertion device gaps are closed at once at high speed at the beginning of a fill.
%
% 2002-08-05, C.Steier, T.Scarvie
% Added conditional to reduce orbit feedback gain if running in two-bunch mode
%
% 2003-06-02, T.Scarvie
% Added loop inside orbit feedback to reset the SR11 chicane M1 and M2 motors every 20s to combat drift problem
%
% 2003-06-18, C. Steier
% Disabled loop to periodically reset chicane in SR11. Al Robb replaced power supply, seems to be no problem anymore.
%
% 2004-05-10, C. Steier
% The list of all BBPMs is now set up automatically be calling getlist('BBPMx'). This way, new BBPMs have to be added
% at fewer places in the software. It should now be sufficient to modify getlist and run the orbit response matrix
% rountine (getsmat) once to enable use of the new BBPMs.
%
% 2004-05-14, C. Steier
% Modified parameters for ramprate reduction (in srramp and here). Previous parameters were slightly too
% cautious. Increased initial slow ramprate to 0.4 A/s.
%
% 2004-05-14, C. Steier
% Incorporated insertion device compensation schemes for nu_y = 9.2 lattice.
%
% 2004-06-14, T.Scarvie
% Added controls for fast orbit feedback
%
% 2004-06-21, C. Steier
% Added tune feedforward (in the global tune compensation scheme for the nu_y=9.2 lattice) for the shift
% dependent tune shift of the EPUs, as well as a skew quadrupole feedforward for the EPU im sector 11
% (both only active in parallel mode so far).
%
% 2005-02-13, T.Scarvie
% Separated horizontal and vertical planes for setting Fast Feedback PIDs
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NOTES for conversion to new Middle Layer %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% We never use the gap and bump control flags - the radio buttons have been disabled -
%        should we try to keep the functionality?
%
% checksrmags
% checksrorbit(...)
% For the compiler
%#function goldenpage
%#function setoperationalmode
% Check if the AO exists
checkforao;
%%%%%%%%%%%%%%
% Initialize %
%%%%%%%%%%%%%%
global FEEDBACK_STOP_FLAG
SR_Mode = getfamilydata('OperationalMode');
SR_GEV = getfamilydata('Energy');
BSCramprate = getfamilydata('BSCRampRate');
if isnan(BSCramprate) | isempty(BSCramprate)
    BSCramprate = 0.4;
    setfamilydata(BSCramprate, 'BSCRampRate');
end
if nargin < 1
    action = 'Initialize';
end
if nargin < 2
    Input2 = 0;
end
if nargin < 3
    Input3 = 0;
end
if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
    FOFBcheckboxVal = 0;
else
    FOFBcheckboxVal = 1;
end
%%%%%%%%%%%%%%%%
% Main Program %
%%%%%%%%%%%%%%%%
switch(action)
    case 'StopOrbitFeedback'
        FEEDBACK_STOP_FLAG = 1;
    case 'Initialize'
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % GUI
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        ButtonWidth = 200;
        ButtonHeight  = 25;
        Offset1 = 8*25+12 + 47 + 25+25;
        Offset2 = 47+25+25;
        Offset3 = 45+25;
        Offset4 = 1;
        Offset5 = 30;
        FigWidth = ButtonWidth+6;
        FigHeight  = 3+9*(ButtonHeight+6)+24+Offset1;
        ButtonWidth = 200-6;
        % Change figure position
        set(0,'Units','pixels');
        p=get(0,'screensize');
        h0 = figure( ...
            'Color',[0.8 0.8 0.8], ...
            'HandleVisibility','Off', ...
            'Interruptible', 'on', ...
            'MenuBar','none', ...
            'Name','ALS SR CONTROL', ...
            'NumberTitle','off', ...
            'Units','pixels', ...
            'Position',[30 p(4)-FigHeight-40 FigWidth FigHeight+Offset5], ...
            'Resize','off', ...
            'Tag','SRCTRLFig1');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'FontWeight','Bold', ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+8*(ButtonHeight+3)+19+19+8+Offset1  ButtonWidth 20+Offset5], ...
            'Style','text', ...
            'String','', ...
            'Tag','SRCTRLTitle');
        % Frame Box I
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+3*(ButtonHeight+3)+Offset1-3+Offset5 ButtonWidth+6 7*ButtonHeight+18], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+9*(ButtonHeight+3)+Offset1  ButtonWidth 15+Offset5], ...
            'Style','text', ...
            'String','Lattice Setup Functions');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Cycle'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+8*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Cycle SR Lattice', ...
            'Tag','SRCTRLButton1');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Injection'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+7*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Injection', ...
            'Tag','SRCTRLButton2');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Production'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+6*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String',['Production'], ...
            'Tag','SRCTRLButton3');
        h1 = uicontrol('Parent',h0, ...
            'Callback',[...
            'fprintf(''\n'');' ...
            'disp([''   **********************************************'']);', ...
            'disp([''   **  Changing Storage Ring Operational Mode  **'']);', ...
            'disp([''   **********************************************'']);', ...
            'setoperationalmode;', ...
            'srcontrol5(''CheckInputs'');', ...
            'disp([''   ****************************'']);', ...
            'disp([''   **  Mode Change Complete  **'']);', ...
            'disp([''   ****************************'']);', ...
            'fprintf(''\n'');'], ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+5*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'Value',1, ...
            'String','Change Operational Mode', ...
            'Tag','SRCTRLButtonChangeMode');
        h1 = uicontrol(...
            'Parent',h0, ...
            'Callback', [...
            'srcontrol5(''CheckInputs'');',...
            'srcontrol5(''SRState'');'], ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+4*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Check For Problems', ...
            'Tag','SRCTRLButtonSRState');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs''); goldenpage;', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+3*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Golden Page', ...
            'Tag','SRCTRLButtonGoldenPage');
        % Frame Box II
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+9*(ButtonHeight+3)-29+Offset2+Offset5 ButtonWidth+6 2*ButtonHeight+15], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+10*(ButtonHeight+3)-10+Offset2 ButtonWidth .6*ButtonHeight+Offset5], ...
            'String','Global/Local Orbit Correction', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''OrbitCorrection'');', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+9*(ButtonHeight+3)-6+Offset2+Offset5 ButtonWidth ButtonHeight], ...
            'String','Correct Global Orbit w/ IDBPMs', ...
            'Tag','SRCTRLButtonOrbitCorrection');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''OrbitCorrectionSetup'',1);', ...
            'callback','srcontrol5(''OrbitCorrectionSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[6 9*(ButtonHeight+3)-22+Offset2+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Edit IDBPM, CM, & Local Bump Lists', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonOrbitCorrectionSetup');
        % Frame Box III
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 1*(ButtonHeight)+Offset3+Offset5-38 ButtonWidth+6 8*ButtonHeight+61], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+9*(ButtonHeight+3)+Offset3-25 ButtonWidth .55*ButtonHeight+Offset5], ...
            'String','Orbit Feedback', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+8*(ButtonHeight+3)+Offset3-18+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Slow Orbit Correction', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxSOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+7*(ButtonHeight+3)+Offset3-9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Fast Orbit Correction', ...
            'Style','checkbox', ...
            'Value',FOFBcheckboxVal,...
            'Tag','SRCTRLCheckboxFOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+6*(ButtonHeight+3)+Offset3+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct ID Tune Shift  ', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxTune');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+5*(ButtonHeight+3)+Offset3+9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct RF Frequency', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxRF');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''Feedback'');', ...
            'Enable','on', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[8 3+5*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Start FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStart');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''StopOrbitFeedback'');pause(0);', ...
            'Enable','off', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[.5*FigWidth+3 3+5*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Stop FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStop');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[14 4*(ButtonHeight)+Offset3+Offset5-3 ButtonWidth-14 .75*ButtonHeight], ...
            'String','Horizontal RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHorizontal');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[26 3+3.5*(ButtonHeight)+16+Offset3-25+Offset5 ButtonWidth-26 .75*ButtonHeight], ...
            'String','Vertical RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextVertical');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FeedbackSetup'',1);', ...
            'callback','srcontrol5(''FeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 3+3.5*(ButtonHeight)+.5+Offset3-25+Offset5 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit SOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFeedbackSetup');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','01 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB01');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','02 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB02');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','03 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB03');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','04 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB04');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','05 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB05');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','06 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB06');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','07 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB07');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','08 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB08');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','09 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB09');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','10 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB10');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','11 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB11');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','12 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB12');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FastFeedbackSetup'',1);', ...
            'callback','srcontrol5(''FastFeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 1*(ButtonHeight)+Offset3-3 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit FOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFastFeedbackSetup');
        % Frame Box IV
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+ButtonHeight+Offset4-14+Offset5 ButtonWidth+6 ButtonHeight+12], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+1.75*ButtonHeight+5+Offset4-21+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Storage Ring State', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHeader');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''CheckInputs'');', ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ForegroundColor','b', ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+ButtonHeight+6+3+2+Offset4-22+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','   ', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextInformation');
        % Frame Box "Close"
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 8 ButtonWidth+6 ButtonHeight+8], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'Callback','close(gcbf);', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 13 ButtonWidth ButtonHeight], ...
            'String','Close', ...
            'Tag','SRCTRLClose');
        % Update database channels
        setsrstatechannels;
        if nargout > 0
            fig = h0;
        end
    case 'Cycle'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        disp('   **************************');
        disp('   **  Storage Ring Cycle  **');
        disp('   **************************');
        a = clock; fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        BSCFlag = questdlg(sprintf('Cycle Superbend Magnets?'),'SR Cycle','Yes','No','No');
        %if strcmp(BSCFlag,'No')
        %    disp(['   ** Superbends will not be cycled. **']);
        %else
        %    disp(['   ** Superbends will be cycled during the second mini-cycle only. **']);
        %end
        ChicSQFlag = questdlg(sprintf('Cycle chicanes and skew quads and home motor chicanes?'),'SR Cycle','Yes','No','No');
        %if strcmp(ChicSQFlag,'No')
        %    disp(['   ** Chicanes and skew quads will not be cycled; motor chicanes will not be homed. **']);
        %else
        %    disp(['   ** Chicanes and skew quads will be cycled; motor chicanes will be homed. **']);
        %end
        StartFlag = questdlg(sprintf('Start %.1f GeV Cycle?',SR_GEV),'SR Cycle','Yes','No','No');
        if strcmp(StartFlag,'No')
            disp(['   ***************************']);
            disp(['   **    Cycle  Canceled    **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        end
        try
            if GapFlag
                % Make sure that the gaps are open with FF off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open.');
                    disp('   Opening all gaps at maximum speed.');
                    setff([], 1, 0);
                    disp('   Gap control disabled.');
                    disp('   Feed forward enabled.');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened.');
                    disp('   Feed forward and gap control disabled.');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled.');
                end
            else
                disp('   Feed forward and gap control disabled.');
            end
            setff([], 0, 0);
            pause(1);
            srcycle(BSCFlag, ChicSQFlag);
            setpv('SR_STATE',1);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Cycle failed due to error condition! \n\n');
            setpv('SR_STATE',-1);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp('   **********************************************');
            disp('   **  SR Cycle complete, ready for injection  **');
            disp('   **********************************************'); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp('   **********************************');
            disp('   **  Problem cycling SR lattice  **');
            disp('   **********************************'); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
    case 'Injection'
        AD = getad;
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            fprintf('   ***************************************************\n');
            fprintf('   **  Setup For %.2f GeV Injection (with ramping)  **\n', getfamilydata('InjectionEnergy'));
            fprintf('   ***************************************************\n');
            set_alarmhandler_AHU_thresholds_inject;
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',getfamilydata('InjectionEnergy')),'Injection Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            fprintf('   *************************************************\n');
            fprintf('   **  Setup For On Energy Injection at %.2f GeV  **\n', SR_GEV);
            fprintf('   *************************************************\n');
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',SR_GEV),'Injection Setup','Yes','Cancel','Cancel');
        end
        if strcmp(StartFlag,'Cancel')
            disp(['   ********************************']);
            disp(['   **  Injection Setup Canceled  **']);
            disp(['   ********************************']);
            set_alarmhandler_thresholds;
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                setff([],1,0);
                disp('   Gap control disabled');
                disp('   Feed forward enabled');
                pause(1);
                % Set IDs at max velocity w/ velocity profile off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    disp('   Opening all gaps');
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                end
                disp('   Gaps are open');
                disp('   Feed forward and gap control disabled');
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            if (AD.Energy-AD.InjectionEnergy) > 0.05
                % Ramp down to Injection Energy
                ErrorFlag = srramp('Injection');
                if ErrorFlag
                    error('Superbends over temperature.');
                end
                a = clock; fprintf('   %s %d:%d:%.0f\n\n',date, a(4), a(5), a(6));
            elseif (AD.Energy-AD.InjectionEnergy) < -0.05
                % first load injection lattice, then ramp to 1.9 GeV and back to 1.5 GeV to get onto same hysteresis branch
                srload('Injection');
                % load 1.9 GeV lattice
                tempfilename = sprintf('%s19nuy9prod.mat', getfamilydata('Directory','OpsData'));
                srload(tempfilename);
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                pause(5);
            end
            srload('Injection');
            setpv('SR_STATE',2);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Injection lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-2);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            if AD.Energy <= 1.5
                disp(['   *******************************************************************************']);
                disp(['   **  Function complete:  the storage ring is setup for injection at ',sprintf('%.2f',SR_GEV),' GeV  **']);
                disp(['   *******************************************************************************']);
                fprintf('\n');
            else
                fprintf('   **********************************************************************************************\n');
                fprintf('   **  Function complete:  the storage ring is setup for injection at %.2f GeV (upper branch)  **\n', getfamilydata('InjectionEnergy'));
                fprintf('   **********************************************************************************************\n');
                fprintf('\n');
            end
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   ************************************']);
            disp(['   **  Problem with injection setup  **']);
            disp(['   ************************************']);
            fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        %soundchord;
        setfamilydata(0.8, 'BSCRampRate');
    case 'Production'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        AD=getad;
        fprintf('\n');
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            disp('   ********************************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation (with ramping)  **',SR_GEV));
            disp('   ********************************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            disp('   *****************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation  **',SR_GEV));
            disp('   *****************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Yes','Cancel','Cancel');
        end
        if strcmp(StartFlag,'Cancel')
            disp(['   ***************************']);
            disp(['   **  User Setup Canceled  **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                % Make sure that the gaps are open
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open');
                    disp('   Opening all gaps at maximum speed');
                    setff([], 1, 0);
                    disp('   Gap control disabled');
                    disp('   Feed forward enabled');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened');
                    disp('   Feed forward and gap control disabled');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled');
                end
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            % Ramp up to the production lattice
            ErrorFlag = srramp('Production');
            if ErrorFlag
                error('Superbends over temperature.');
            end
            a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            srload('Production');
            if GapFlag
                setff([], 1, 0);
                disp('   Gap control disabled');
                disp('   Feed forward enable');
                pause(1);
                disp('   Insertion device velocity profile boolean control off');
                disp('   Closing all gaps at maximum speed');
                % Set IDs at max velocity w/ velocity profile off
                [Position, Velocity, RunFlag, UserGap] = getid;
                setid([], UserGap, maxsp('IDvel'), 1, 0, 1);
                % Turn velocity profile on
                disp('   Insertion device velocity profile boolean control is on');
                setid([], [], maxsp('IDvel'), 1, 1, 0);
                disp('   Gaps are closed');
                setff([4;7;8;9;10;12], 1, 1);
                setff(5, 1, 0);
                disp('   Gap control enabled (except sector 5 (W16))');
            end
            set_alarmhandler_thresholds_new;
            setpv('SR_STATE',3);
        catch
            fprintf('   %s \n', lasterr);
            fprintf('   User lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-3);
        end
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp(['   **************************************************************************']);
            disp(['   **  Function complete:  the storage ring is setup for users at ',sprintf('%.1f',SR_GEV),' GeV  **']);
            disp(['   **************************************************************************']); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   *************************************']);
            disp(['   **  Problem with production setup  **']);
            disp(['   *************************************']); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        setfamilydata(0.8, 'BSCRampRate');
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % for BL6.0.x, set lower setpoint limit for IVID to 7mm until beamlines are surveyed below that value
        % if 6.0.1 hard x-ray beamline is running the gap will be admin locked at 30mm - 5-02-07 - T.Scarvie
        try
            scaput('SR06U___GDS1PS_AC00.DRVL',12.5);
            disp('  Setting SR06U___GDS1PS_AC00.DRVL to 12.5mm (lower limit for IVID');
        catch
            disp('  Trouble setting lower limit for IVID to 12.5mm!');
        end
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    case 'CheckInputs'
        SR_GEV = getfamilydata('Energy');
        AD=getad;
        setsrstatechannels;
        set(0,'showhiddenhandles','on');
        if AD.Energy > 1.55
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Down)']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users (Ramp Up)']);
        elseif AD.Energy < 1.45
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Up+cycle)']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV (Ramp Down)']);
        else
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV']);
        end
        set(findobj('Tag','SRCTRLTitle'),'String',SR_Mode);
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
        else
            set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
        end
        set(0,'showhiddenhandles','off');
    case 'SRState'
        NumErrors = 0;
        fprintf('\n');
        disp('   ***********************************');
        disp('   **  Checking Storage Ring State  **');
1000         disp('   ***********************************');
1001         a = clock;
1002         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1003
1004         %       FileName = getpv('SR_LATTICE_FILE','String');   % Last srload file name (in OLD MIDDLE LAYER nomenclature!!)
1005
1006         GeVnow = bend2gev;
1007         if GeVnow == getfamilydata('Energy')
1008             [ConfigSetpoint, ConfigMonitor, FileName] = getproductionlattice;
1009         elseif GeVnow == getfamilydata('InjectionEnergy')
1010             [ConfigSetpoint, ConfigMonitor, FileName] = getinjectionlattice;
1011         else
1012             FileName = '';
1013         end
1014
1015         [StateNumber, StateString] = getsrstate;
1016         fprintf('   Storage ring operational mode: %s\n', SR_Mode);
1017         if StateNumber < 0
1018             fprintf('   Storage ring state error: %s\n', StateString);
1019             NumErrors = NumErrors + 1;
1020         else
1021             fprintf('   Storage ring state: %s\n', StateString);
1022         end
1023         if StateNumber==0
1024             % Storage ring state unknown
1025             NumErrors = NumErrors + 1;
1026         elseif abs(StateNumber)==1 || abs(StateNumber)==2
1027             FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','InjectionFile') '.mat'];
1028             if ~strcmp(FileName, FileNameGoal)
1029                 fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','InjectionFile'), FileName);
1030                 NumErrors = NumErrors + 1;
1031             end
1032         else
1033             FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile') '.mat'];
1034             if ~strcmp(FileName, FileNameGoal)
1035                 fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','LatticeFile'), FileName);
1036                 NumErrors = NumErrors + 1;
1037             end
1038         end
1039
1040
1041         % Check all SR magnets
1042         if isempty(FileName)
1043             fprintf('   Goal setpoints will not be checked since the last lattice load is unknown.\n');
1044             NumErrors1 = checksrmags('');
1045         else
1046 %            NumErrors1 = checksrmags([getfamilydata('Directory','OpsData') FileName]);
1047             NumErrors1 = checksrmags(FileName);
1048         end
1049         if NumErrors1 == 0
1050             fprintf('   SR magnets power supplies are OK.\n');
1051         end
1052         NumErrors = NumErrors + NumErrors1;
1053
1054
1055         % Check RF frequency
1056         if isempty(FileName)
1057             fprintf('   RF frequency will not be checked since the last lattice load is unknown.\n');
1058         else
1059 %            load([getfamilydata('Directory','OpsData'), FileName]);
1060             load(FileName);
1061             [tmp, RFHPCounterPresent] = getrf;
1062             if abs(RFHPCounterPresent-ConfigSetpoint.RF.Setpoint.Data) > .002
1063                 NumErrors = NumErrors + 1;
1064                 fprintf('   RF frequency should be %f, presently it is %f MHz (as measured by the HP counter).\n', ConfigSetpoint.RF.Setpoint.Data, RFHPCounterPresent);
1065             else
1066                 fprintf('   RF frequency is OK (HP counter is %f MHz, at the time of the lattice save it was %f MHz).\n', RFHPCounterPresent, ConfigSetpoint.RF.Setpoint.Data);
1067             end
1068         end
1069
1070
1071         % Check for orbit problems
1072         if (StateNumber >= 3) & (getdcct > 2)   % Production lattice is loaded with beam in the machine
1073             Xtol = 0.070;
1074             Ytol = 0.010;
1075             NumErrors1 = checksrorbit([],Xtol,Ytol);
1076             if NumErrors1
1077                 fprintf('   SR orbit in the ID straight sections or at Bergoz BPMs deviates more than allowed from the golden orbit.\n');
1078             else
1079                 fprintf('   SR orbit in the ID straight sections and at Bergoz BPMs is OK.\n');
1080                 fprintf('   The orbit is within %.3f mm horizontally and %.3f mm vertically', Xtol, Ytol);
1081             end
1082             NumErrors = NumErrors + NumErrors1;
1083         else
1084             fprintf('   Storage ring orbit was not checked.\n');
1085         end
1086
1087
1088         a = clock;
1089         datestr1=date;
1090         fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
1091         if NumErrors
1092             disp('   *********************************');
1093             disp('   **  Storage Ring Has Problems  **');
1094             disp('   *********************************');
1095         else
1096             disp('   **********************************');
1097             disp('   **  Storage Ring Lattice is OK  **');
1098             disp('   **********************************');
1099         end
1100         fprintf('   \n');
1101
1102         set(0,'showhiddenhandles','on');
1103         [StateNumber, StateString] = getsrstate;
1104         if StateNumber >= 0
1105             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1106         else
1107             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1108         end
1109         set(0,'showhiddenhandles','off');
1110
1111
1112     case 'OrbitCorrection'
1113         fprintf('\n');
1114         fprintf('   *********************************\n');
1115         fprintf('   **  Starting Orbit Correction  **\n');
1116         fprintf('   *********************************\n');
1117         a = clock;
1118         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1119
1120         StartFlag = questdlg(sprintf('Start orbit correction, %.1f GeV?',SR_GEV),'Orbit Correction','Yes','No','No');
1121         if strcmp(StartFlag,'No')
1122             disp(['   ********************************']);
1123             disp(['   **  Orbit Correction Aborted  **']);
1124             disp(['   ********************************']);
1125             fprintf('\n');
1126             return
1127         end
1128
1129         if getdcct < 5     % Don't correct the orbit if the current is too small
1130             fprintf('   Orbit not corrected due to small current.\n');
1131             return
1132         end
1133
1134         if abs(SR_GEV-bend2gev(getpv('BEND',[1 1])))>  0.05     % Don't use this routine for the injection lattice
1135             fprintf('   This routine should only be used for the production energy: Correction aborted\n');
1136             return
1137         end
1138
1139         SR_STATE_OLD = scaget('SR_STATE');
1140         set(0,'showhiddenhandles','on');
1141         setpv('SR_STATE',4);
1142         [StateNumber, StateString] = getsrstate;
1143         if StateNumber >= 0
1144             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1145         else
1146             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1147         end
1148         set(0,'showhiddenhandles','off');
1149
1150
1151         try
1152             % save current BPM timeconstant - will reset to this after correction
1153             BPMtimeconstantOC = getbpmtimeconstant;
1154             fprintf('   Current Bergoz BPM time constant is %.1fs\n', BPMtimeconstantOC);
1155
1156             % 2 Hz update rate on IDBPMs
1157             disp('   Bergoz BPM time constant set to 0.5s.')
1158             setbpmtimeconstant(0.5)
1159             pause(2);
1160
1161
1162             % Turn off feed forward
1163             fprintf('   Turning feed forward off.\n');
1164             [FFEnableBM, FFEnableBC] = getff;
1165             setff([], 0);
1166             scasleep(.2);
1167
1168
1169             % Get vectors
1170             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1171             LocalBumplist = FB.LocalBumplist;
1172
1173         catch
1174
1175             fprintf('   %s \n',lasterr);
1176             fprintf('   Orbit correction setup failed due to error condition! \n\n');
1177             setpv('SR_STATE',-4);
1178             set(0,'showhiddenhandles','on');
1179             [StateNumber, StateString] = getsrstate;
1180             if StateNumber >= 0
1181                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1182             else
1183                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1184             end
1185             set(0,'showhiddenhandles','off');
1186
1187             % Reset BPM timeconstant to whatever it was before correction
1188             setbpmtimeconstant(BPMtimeconstantOC);
1189             fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1190             return
1191         end
1192
1193         iNotHCMChicane = find(FB.HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
1194         iHCMChicane = find(FB.HCMlist1(:,2) == 10);
1195         iNotVCMChicane = find(FB.VCMlist1(:,2) < 10);
1196         iVCMChicane = find(FB.VCMlist1(:,2) == 10);
1197
1198         fprintf('   Starting horizontal and vertical global orbit correction (SVD method).\n');
1199
1200         for iloop = 1:3
1201             try
1202                 % use the following to get corrector settings in OCS without setting them, so the values can be checked
1203                 FB.OCSx = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
1204                 FB.OCSy = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
1205                 if any(abs(FB.OCSx.CM.Delta(iNotHCMChicane)) > 5)
1206                   disp('   Orbit Correction is changing some horizontal corrector(s) > 5A!!');
1207                 end
1208                 if any(abs(FB.OCSy.CM.Delta(iNotVCMChicane)) > 5)
1209                   disp('   Orbit Correction is changing some vertical corrector(s) > 5A!!');
1210                 end
1211                 if any(abs(FB.OCSx.CM.Delta(iHCMChicane)) > 10)
1212                   disp('   Orbit Correction is changing some horizontal chicane corrector(s) > 10A!!');
1213                 end
1214                 if any(abs(FB.OCSy.CM.Delta(iVCMChicane)) > 10)
1215                   disp('   Orbit Correction is changing some vertical chicane corrector(s) > 10A!!');
1216                 end
1217
1218
1219                 % Correct horizontal orbit
1220                 FB.OCSx = setorbit(FB.OCSx,'NoDisplay');
1221                 % Correct vertical orbit
1222                 FB.OCSy = setorbit(FB.OCSy,'NoDisplay');
1223
1224
1225                 % Check for current in machine - stop orbit correction if DCCT < 5mA
1226                 if (getdcct < 4.5)
1227                     error('**There is less than 5mA in the machine! Stopping orbit correction.');
1228                 end
1229
1230                 % Check state of gaps - stop orbit correction if any are moving
1231                 GAPrunflag = getpv('ID','RunFlag');
1232                 if any(GAPrunflag-round(GAPrunflag))
1233                     error('**One or more of the gaps are moving! Stopping orbit correction.');
1234                 end
1235
1236                 x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
1237                 y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
1238                 fprintf('   %d. Horizontal RMS = %.3f mm\n', iloop, norm(x)/sqrt(length(x)));
1239                 fprintf('   %d.   Vertical RMS = %.3f mm\n', iloop, norm(y)/sqrt(length(y)));
1240
1241             catch
1242                 % fprintf('   %s \n',lasterr);
1243                 fprintf('   Orbit correction failed due to error condition!\n  Fix the problem, reload the lattice (srload), and try again.  \n\n');
1244                 setpv('SR_STATE',-4);
1245                 set(0,'showhiddenhandles','on');
1246                 [StateNumber, StateString] = getsrstate;
1247                 if StateNumber >= 0
1248                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1249                 else
1250                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1251                 end
1252                 set(0,'showhiddenhandles','off');
1253
1254                 % Reset BPM timeconstant to whatever it was before correction
1255                 setbpmtimeconstant(BPMtimeconstantOC);
1256                 fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1257                 return
1258             end
1259         end
1260
1261
1262         % Set user bumps w/o sextupole correctors
1263         try
1264
1265             %turn up corrector speed here to quicken setting bumps
1266             HCMramprate = getpv('HCM', 'RampRate');
1267             VCMramprate = getpv('VCM', 'RampRate');
1268             setpv('HCM', 'RampRate', 10, [], 0);
1269             setpv('VCM', 'RampRate', 10, [], 0);
1270
1271             if ~isempty(LocalBumplist)
1272                 fprintf('   Setting local bumps in the straight sections.\n');
1273                 for loop = 1:size(LocalBumplist,1)
1274
1275                     % Check for current in machine - stop orbit correction if DCCT < 5mA
1276                     if (getdcct < 5)
1277                         error('** There is less than 5mA in the machine! Stopping local bumps.');
1278                     end
1279
1280                     % Check state of gaps - stop setting bumps if any are moving
1281                     GAPrunflag = getpv('ID','RunFlag');
1282                     if any(GAPrunflag-round(GAPrunflag))
1283                         error('** One or more of the gaps are moving! Stopping local bumps.');
1284                     end
1285
1286                     HCMoldsp = getsp('HCM', FB.HCMlist1);
1287                     VCMoldsp = getsp('VCM', FB.VCMlist1);
1288
1289                     if any(LocalBumplist(loop,1) == [4 6 11])
1290                         if LocalBumplist(loop,2) == 0
1291                             % Upstream bump
1292                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1293                             if isempty(iRemove)
1294                                 setbumps(LocalBumplist(loop,:), 1);
1295                             else
1296                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1297                             end
1298                         elseif LocalBumplist(loop,2) == 1
1299                             % Upstream bump
1300                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;],FB.OCSx.BPM.DeviceList);
1301                             if isempty(iRemove)
1302                                 setbumps(LocalBumplist(loop,:), 1);
1303                             else
1304                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1305                             end
1306                         else
1307                             % Downstream bump
1308                             [i, iRemove] = findrowindex([LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1309                             if isempty(iRemove)
1310                                 setbumps(LocalBumplist(loop,:), 1);
1311                             else
1312                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1313                             end
1314                         end
1315                     else
1316                         [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1317                         if isempty(iRemove)
1318                             setbumps(LocalBumplist(loop,:), 1);
1319                         else
1320                             fprintf('\n   BPMs missing from Sector %02d - skipping local bump for that sector.\n\n', LocalBumplist(loop,1));
1321                         end
1322                     end
1323
1324                     HCMnewsp = getsp('HCM', FB.HCMlist1);
1325                     VCMnewsp = getsp('VCM', FB.VCMlist1);
1326                     % Remove center chicane trim from corrector check
1327                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 5) | (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 10)
1328                         error('**Setbumps caused some corrector magnet currents to change by more than 5(Horiz)/10(Vert) A!');
1329                     end
1330                     % Now check center chicane trims
1331                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 10) | (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 15)
1332                         error('**Setbumps caused some chicane trim magnet currents to change by more than 10(Horiz)/15(Vert) A!');
1333                     end
1334                 end
1335             end
1336
1337             %restore corrector speeds
1338             setpv('HCM', 'RampRate', HCMramprate, [], 0);
1339             setpv('VCM', 'RampRate', VCMramprate, [], 0);
1340
1341         catch
1342             fprintf('   %s \n',lasterr);
1343             fprintf('   Setbumps failed due to error condition!  Fix the problem, reload the lattice (srload), and try again.\n\n');
1344             setpv('SR_STATE',-4);
1345             set(0,'showhiddenhandles','on');
1346             [StateNumber, StateString] = getsrstate;
1347             if StateNumber >= 0
1348                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1349             else
1350                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1351             end
1352             set(0,'showhiddenhandles','off');
1353
1354             % Reset BPM timeconstant to whatever it was before correction
1355             setbpmtimeconstant(BPMtimeconstantOC);
1356             fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1357             return
1358         end
1359
1360         % Reset BPM timeconstant to whatever it was before correction
1361         setbpmtimeconstant(BPMtimeconstantOC);
1362         fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1363
1364         % Turn feed forward back to it's original state
1365         if any(FFEnableBC)
1366             fprintf('   Turning feed forward back on.\n');
1367             setff([], FFEnableBC);
1368         end
1369
1370
1371         a = clock;
1372         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1373         [StateNumber, StateString] = getsrstate;
1374         set(0,'showhiddenhandles','on');
1375         if StateNumber >= 0
1376             setpv('SR_STATE',4.1);
1377             [StateNumber, StateString] = getsrstate;
1378             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1379             fprintf('   *********************************\n');
1380             fprintf('   **  Orbit Correction Complete  **\n');
1381             fprintf('   *********************************\n\n');
1382         else
1383             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1384             fprintf('   *************************************\n');
1385             fprintf('   **  Problem With Orbit Correction  **\n');
1386             fprintf('   *************************************\n\n');
1387         end
1388         set(0,'showhiddenhandles','off');
1389         pause(0);
1390
1391
1392     case 'OrbitCorrectionSetup'
1393         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
1394
1395         if InitFlag
1396             % Setup feedback elements
1397             % disp('Orbit correction condition: InitFlag=1 -- debugging message');
1398
1399             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1400             % Edit the following lists to change default configuration of Orbit Correction %
1401             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1402             hlist=[];vlist=[];
1403             for Sector =1:12
1404                 if Sector == 1
1405                     vlist = [vlist;Sector 2;Sector 4;Sector 5;Sector 8];
1406                     hlist = [hlist;Sector 2;Sector 7];
1407                 elseif Sector == 3
1408                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1409                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1410                 elseif Sector == 5
1411                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1412                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1413 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8]; %remove HCM and VCM(5,10) since corrector is not controlling starting 4-6-07
1414 %                     hlist = [hlist;Sector 2;Sector 7];
1415                 elseif Sector == 10
1416                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1417                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1418                 elseif Sector == 12
1419                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 7];
1420                     hlist = [hlist;Sector 2;Sector 7];
1421                 else
1422                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8];
1423                     hlist = [hlist;Sector 2;Sector 7];
1424                 end
1425             end
1426             HCMlist1 = hlist;
1427             VCMlist1 = vlist;
1428
1429             BPMlist1 = [
1430                 1 2
1431                 1 5
1432                 1 6
1433                 1 10
1434                 2 1
1435                 2 5
1436                 2 6
1437                 2 9
1438                 3 2
1439                 3 5
1440                 3 6
1441                 3 10
1442                 3 11
1443                 3 12
1444                 4 1
1445                 4 5
1446                 4 6
1447                 4 10
1448                 5 1
1449                 5 5
1450                 5 6
1451                 5 10
1452                 5 11
1453                 5 12
1454                 6 1
1455                 6 5
1456                 6 6
1457                 6 10
1458                 7 1
1459                 7 5
1460                 7 6
1461                 7 10
1462                 8 1
1463                 8 5
1464                 8 6
1465                 8 10
1466                 9 1
1467                 9 5
1468                 9 6
1469                 9 10
1470                 10 1
1471                 10 5
1472                 10 6
1473                 10 10
1474                 10 11
1475                 10 12
1476                 11 1
1477                 11 5
1478                 11 6
1479                 11 10
1480                 12 1
1481                 12 5
1482                 12 6
1483                 12 9];
1484
1485             % SVD orbit correction
1486             Xivec = [1:28];
1487             Yivec = [1:51];
1488
1489
1490             LocalBumplist = [
1491               % 1 1
1492               % 2 1
1493               % 3 1
1494                 4 1
1495               % 4 2
1496                 5 1
1497               % 6 1
1498               % 6 2
1499                 7 1
1500                 8 1
1501                 9 1
1502                 10 1
1503                 11 1
1504                 11 2
1505                 12 1
1506 ];
1507             %LocalBumplist = []
1508
1509             % initialize RFCorrFlag
1510             RFCorrFlag = 'Yes';
1511         else
1512
1513             % Get vectors
1514             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1515             BPMlist1 = FB.BPMlist1;
1516             HCMlist1 = FB.HCMlist1;
1517             VCMlist1 = FB.VCMlist1;
1518             Xivec = FB.Xivec;
1519             Yivec = FB.Yivec;
1520             LocalBumplist = FB.LocalBumplist;
1521             Xgoal = FB.Xgoal;
1522             Ygoal = FB.Ygoal;
1523             RFCorrFlag = FB.RFCorrFlag;
1524
1525             % Add button to change #ivectors, CMs, IDBPMs,
1526             EditFlag = 0;
1527             h_fig1 = figure;
1528             while EditFlag ~= 8
1529
1530                 % Sensitivity matrix
1531                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
1532                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
1533
1534                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1535                 % Can the call below work for setting FOFB RF parameter? %
1536                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1537                 if strcmpi(RFCorrFlag, 'Yes')
1538                     Sx = [Sx getdisp('BPMx',BPMlist1)];
1539                 end
1540
1541                 [Ux, SVx, Vx] = svd(Sx);
1542                 [Uy, SVy, Vy] = svd(Sy);
1543
1544
1545                 % Remove singular values greater than the actual number of singular values
1546                 i = find(Xivec>length(diag(SVx)));
1547                 if ~isempty(i)
1548                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
1549                     pause(0);
1550                     Xivec(i) = [];
1551                 end
1552                 i = find(Yivec>length(diag(SVy)));
1553                 if ~isempty(i)
1554                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
1555                     pause(0);
1556                     Yivec(i) = [];
1557                 end
1558
1559
1560                 Ax = Sx*Vx(:,Xivec);
1561                 Tx = inv(Ax'*Ax)*Ax';
1562
1563                 Ay = Sy*Vy(:,Yivec);
1564                 Ty = inv(Ay'*Ay)*Ay';
1565
1566
1567                 figure(h_fig1);
1568                 subplot(2,1,1);
1569                 semilogy(diag(SVx),'b');
1570                 hold on;
1571                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
1572                 ylabel('Horizontal');
1573                 title('Response Matrix Singular Values');
1574                 hold off;
1575                 subplot(2,1,2);
1576                 semilogy(diag(SVy),'b');
1577                 hold on;
1578                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
1579                 xlabel('Singular Value Number');
1580                 ylabel('Vertical');
1581                 hold off;
1582                 drawnow;
1583
1584                 if strcmp(RFCorrFlag,'No')
1585                     RFCorrState = 'NOT CORRECTED';
1586                 elseif strcmp(RFCorrFlag,'Yes')
1587                     RFCorrState = 'CORRECTED';
1588                 else
1589                     RFCorrState = '???';
1590                 end
1591
1592                 %         EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','HCM Chicane List','VCM Chicane List','IDBPM List','BBPM List','Change Golden Orbit',...
1593                 %            'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1594                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','BPM List','Change Golden Orbit',...
1595                     'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1596
1597                 if EditFlag == 1
1598                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
1599                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
1600                     titlestr='SVD Orbit Feedback';
1601                     lineNo=1;
1602                     answer=inputdlg(prompt,titlestr,lineNo,def);
1603                     if ~isempty(answer)
1604                         XivecNew = fix(str2num(answer{1}));
1605                         if isempty(XivecNew)
1606                             disp('   Horizontal E-vector cannot be empty.  No change made.');
1607                         else
1608                             if any(XivecNew<=0) | max(XivecNew)>length(diag(SVx))
1609                                 disp('   Error reading horizontal E-vector.  No change made.');
1610                             else
1611                                 Xivec = XivecNew;
1612                             end
1613                         end
1614                         YivecNew = fix(str2num(answer{2}));
1615                         if isempty(YivecNew)
1616                             disp('   Vertical E-vector cannot be empty.  No change made.');
1617                         else
1618                             if any(YivecNew<=0) | max(YivecNew)>length(diag(SVy))
1619                                 disp('   Error reading vertical E-vector.  No change made.');
1620                             else
1621                                 Yivec = YivecNew;
1622                             end
1623                         end
1624                     end
1625                 end
1626
1627                 if EditFlag == 2
1628                     List = getlist('HCM');
1629                     CheckList = zeros(size(List,1));
1630                     Elem = dev2elem('HCM', HCMlist1);
1631                     CheckList(Elem) = ones(size(Elem));
1632                     CheckList = CheckList(dev2elem('HCM',List));
1633                     newList = editlist(List, 'HCM', CheckList);
1634                     if isempty(newList)
1635                         fprintf('   Horizontal corrector magnet list cannot be empty.  No change made.\n');
1636                     else
1637                         HCMlist1 = newList;
1638                     end
1639                 end
1640
1641                 if EditFlag == 3
1642                     List = getlist('VCM');
1643                     CheckList = zeros(size(List,1));
1644                     Elem = dev2elem('VCM', VCMlist1);
1645                     CheckList(Elem) = ones(size(Elem));
1646                     CheckList = CheckList(dev2elem('VCM',List));
1647                     newList = editlist(List, 'VCM', CheckList);
1648                     if isempty(newList)
1649                         fprintf('   Vertical corrector magnet cannot be empty.  No change made.\n');
1650                     else
1651                         VCMlist1 = newList;
1652                     end
1653                 end
1654
1655                 if EditFlag == 4
1656                     ListOld = BPMlist1;
1657                     XgoalOld = Xgoal;
1658                     YgoalOld = Ygoal;
1659
1660                     % Full BPM list
1661                     List = [
1662                         1 2
1663                         1 5
1664                         1 6
1665                         1 10
1666                         2 1
1667                         2 5
1668                         2 6
1669                         2 9
1670                         3 2
1671                         3 5
1672                         3 6
1673                         3 10
1674                         3 11
1675                         3 12
1676                         4 1
1677                         4 5
1678                         4 6
1679                         4 10
1680                         5 1
1681                         5 5
1682                         5 6
1683                         5 10
1684                         5 11
1685                         5 12
1686                         6 1
1687                         6 5
1688                         6 6
1689                         6 10
1690                         7 1
1691                         7 5
1692                         7 6
1693                         7 10
1694                         8 1
1695                         8 5
1696                         8 6
1697                         8 10
1698                         9 1
1699                         9 5
1700                         9 6
1701                         9 10
1702                         10 1
1703                         10 5
1704                         10 6
1705                         10 10
1706                         10 11
1707                         10 12
1708                         11 1
1709                         11 5
1710                         11 6
1711                         11 10
1712                         12 1
1713                         12 5
1714                         12 6
1715                         12 9
1716                         ];
1717
1718                     CheckList = zeros(size(List,1),1);
1719                     if ~isempty(BPMlist1)
1720                         for i = 1:size(List,1)
1721                             k = find(List(i,1)==BPMlist1(:,1));
1722                             l = find(List(i,2)==BPMlist1(k,2));
1723
1724                             if isempty(k) | isempty(l)
1725                                 % Item not in list
1726                             else
1727                                 CheckList(i) = 1;
1728                             end
1729                         end
1730                     end
1731
1732                     newList = editlist(List, 'BPM', CheckList);
1733                     if isempty(newList)
1734                         fprintf('   BPM list cannot be empty.  No change made.\n');
1735                     else
1736                         BPMlist1 = newList;
1737                     end
1738
1739                     % Set the goal orbit to the golden orbit
1740                     Xgoal = getgolden('BPMx', BPMlist1);
1741                     Ygoal = getgolden('BPMy', BPMlist1);
1742
1743
1744                     % If a new BPM is added, then set the goal orbit to the golden orbit
1745                     for i = 1:size(BPMlist1,1)
1746
1747                         % Is it a new BPM?
1748                         k = find(BPMlist1(i,1)==ListOld(:,1));
1749                         l = find(BPMlist1(i,2)==ListOld(k,2));
1750
1751                         if isempty(k) | isempty(l)
1752                             % New BPM
1753                         else
1754                             % Use the old value for old BPM
1755                             Xgoal(i) = XgoalOld(k(l));
1756                             Ygoal(i) = YgoalOld(k(l));
1757                         end
1758                     end
1759                 end
1760
1761                 if EditFlag == 5
1762
1763                     ChangeList = editlist(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
1764                     for i = 1:size(ChangeList,1)
1765
1766                         k = find(ChangeList(i,1)==BPMlist1(:,1));
1767                         l = find(ChangeList(i,2)==BPMlist1(k,2));
1768
1769                         prompt = {sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
1770                         def = {sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
1771                         titlestr = 'CHANGE THE GOAL ORBIT';
1772                         lineNo = 1;
1773                         answer = inputdlg(prompt, titlestr, lineNo, def);
1774
1775                         if isempty(answer)
1776                             % No change
1777                             fprintf('   No change was made to the golden orbit.\n');
1778                         else
1779                             Xgoalnew = str2num(answer{1});
1780                             if isempty(Xgoalnew)
1781                                 fprintf('   No change was made to the horizontal golden orbit.\n');
1782                             else
1783                                 Xgoal(k(l)) = Xgoalnew;
1784                             end
1785
1786                             Ygoalnew = str2num(answer{2});
1787                             if isempty(Ygoalnew)
1788                                 fprintf('   No change was made to the vertical golden orbit.\n');
1789                             else
1790                                 Ygoal(k(l)) = Ygoalnew;
1791                             end
1792                         end
1793                     end
1794                     if ~isempty(ChangeList)
1795                         fprintf('   Note:  changing the goal orbit for "Orbit Correction" does not change the goal orbit for "Slow Orbit Feedback."\n');
1796                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
1797                     end
1798                 end
1799
1800                 if EditFlag == 6
1801                     List = [
1802                         1 1
1803                         2 1
1804                         3 1
1805                         4 1
1806                         4 2
1807                         5 1
1808                         6 1
1809                         6 2
1810                         7 1
1811                         8 1
1812                         9 1
1813                         10 1
1814                         11 1
1815                         11 2
1816                         12 1];
1817                     CheckList = zeros(size(List,1),1);
1818                     if ~isempty(LocalBumplist)
1819                         for i = 1:size(List,1)
1820                             k = find(List(i,1)==LocalBumplist(:,1));
1821                             l = find(List(i,2)==LocalBumplist(k,2));
1822
1823                             if isempty(k) | isempty(l)
1824                                 % Item not in list
1825                             else
1826                                 CheckList(i) = 1;
1827                             end
1828                         end
1829                     end
1830                     LocalBumplist = editlist2(List, 'Sector', CheckList);
1831                 end
1832
1833                 if EditFlag == 7
1834                     RFCorrFlag = questdlg(sprintf('Set RF Frequency during Orbit Correction?'),'RF Frequency','Yes','No', 'No');
1835                     if strcmp(RFCorrFlag,'No')
1836                         disp(['   RF Frequency will not be included in global orbit correction.']);
1837                     elseif strcmp(RFCorrFlag,'Yes')
1838                         disp(['   RF Frequency will be included in global orbit correction.']);
1839                     end
1840
1841                 end
1842             end
1843             close(h_fig1);
1844         end
1845
1846 %  ORBIT CORRECTION STRUCTURE (OCS)
1847 %    OCS.BPM (data structure)
1848 %    OCS.CM  (data structure)
1849 %    OCS.GoalOrbit
1850 %    OCS.NIter
1851 %    OCS.SVDIndex
1852 %    OCS.IncrementalFlag = 'Yes'/'No'
1853 %    OCS.BPMWeight
1854 %    OCS.Flags = { 'FitRF' , etc.  }
1855         OCSx.BPM = getx(BPMlist1, 'struct');
1856         OCSx.CM = getsp('HCM', HCMlist1, 'struct');
1857         OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
1858         OCSx.NIter = 1;
1859         OCSx.SVDIndex = Xivec;
1860         OCSx.IncrementalFlag = 'No';
1861         OCSx.FitRF = 1;
1862         OCSy.BPM = gety(BPMlist1, 'struct');
1863         OCSy.CM = getsp('VCM', VCMlist1, 'struct');
1864         OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
1865         OCSy.NIter = 1;
1866         OCSy.SVDIndex = Yivec;
1867         OCSy.IncrementalFlag = 'No';
1868         OCSy.FitRF = 0;
1869
1870         % Save vectors
1871         FB.OCSx = OCSx;
1872         FB.OCSy = OCSy;
1873
1874         FB.BPMlist1 = BPMlist1;
1875         FB.HCMlist1 = HCMlist1;
1876         FB.VCMlist1 = VCMlist1;
1877         FB.Xivec = Xivec;
1878         FB.Yivec = Yivec;
1879         FB.Xgoal = OCSx.GoalOrbit;
1880         FB.Ygoal = OCSy.GoalOrbit;
1881         FB.RFCorrFlag = RFCorrFlag;
1882         FB.LocalBumplist = LocalBumplist;
1883         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata',FB);
1884
1885
1886     case 'Feedback'
1887
1888         FBloopIter = 1;
1889         if get(findobj(gcbf,'Tag','SRCTRLCheckboxFOFB'),'Value') == 1
1890             StartFOFBFlag = 1;
1891         else
1892             StartFOFBFlag = 0;
1893         end
1894
1895         FEEDBACK_STOP_FLAG = 0;
1896         HWarnNum=0;
1897         VWarnNum=0;
1898
1899         SR_GeV = getenergy;
1900         % Feedback loop setup
1901         PlotInfoFlag = 0;           % Plot micado stuff
1902         LoopDelay = 1.0;           % Period of feedback loop [seconds], make sure the BPM averaging is correct
1903         VCM_LSB = .00366211;
1904         VCMCHICANE_LSB = .002441;   % 80 max?,  Note: not fully implemented
1905
1906         if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
1907             Xgain  = 0.2;
1908             Ygain  = 0.1;
1909         else
1910             Xgain  = 0.8; % raised 0.5->0.8 at 17:20, 3-2-05 to more quickly correct EPU4 fast switching orbit distortions
1911             Ygain  = 0.8;
1912         end
1913
1914         % Load lattice set for tune feed forward
1915         ConfigSetpoint = getproductionlattice;
1916         %load([getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile')]);
1917         QFsp = ConfigSetpoint.QF.Setpoint.Data;
1918         QDsp = ConfigSetpoint.QD.Setpoint.Data;
1919         TuneW16Min = gap2tune(5, 13.23, 1.8909);
1920         % Tune response matrix
1921         SR_TUNE_MATRIX = gettuneresp({'QF','QD'}, {[],[]}, getenergy('Production'));    % Approx. [0.1944 -0.0286;-0.1182 0.1526];
1922         %SR_TUNE_MATRIX = [0.1641 -0.0245
1923         %                 -0.1149 0.1477];
1924
1925         %SQSFindex = [1 1; 3 1; 3 2; 5 1; 6 1; 6 2; 7 2; 9 1; 11 1];
1926           %SQSFind = [1 2 3 4 6 7 9 10 11];
1927           HCSFindex = [5 2;7 1];
1928           HCSFind = [33 48];
1929           %SQSDindex = [2 1; 3 1; 3 2; 4 1; 6 1; 6 2; 7 1; 7 2; 8 1; 10 1; 12 1];
1930           %SQSDind = [12 13 14 15 18 19 20 21 22 23 24];
1931           HCSDindex = [5 1;5 2];
1932         HCSDind = [32 33];
1933         SQSFsp = ConfigSetpoint.SQSF.Setpoint.Data;
1934         SQSDsp = ConfigSetpoint.SQSD.Setpoint.Data;
1935         HCSFsp = ConfigSetpoint.HCM.Setpoint.Data(HCSFind);
1936         HCSDsp = ConfigSetpoint.HCM.Setpoint.Data(HCSDind);
1937
1938         % ID tune compensation does not work in the injection lattice, so ...
1939         if abs(SR_GEV - bend2gev)>  0.05     % Don't use this routine for the injection lattice
1940             fprintf('   This routine should only be used for the production energy: Orbit feedback aborted\n');
1941             return
1942         end
1943
1944         set(0,'showhiddenhandles','on');
1945
1946         try
1947             fprintf('\n');
1948             fprintf('   *******************************\n');
1949             fprintf('   **  Starting Orbit Feedback  **\n');
1950             fprintf('   *******************************\n');
1951             a = clock;
1952             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1953             fprintf('   Note: the Matlab command window will be used to display status information.\n');
1954             fprintf('         It cannot be used to enter commands during slow orbit feedback.\n');
1955
1956
1957                 % save current BPM timeconstant - will reset to this when feedback stops
1958                 BPMtimeconstantOFB = getbpmtimeconstant;
1959                 fprintf('   Current Bergoz BPM time constant is %.1fs\n', BPMtimeconstantOFB);
1960
1961             % >= 2 Hz update rate on IDBPMs
1962             disp('   Bergoz BPM time constant set to 0.2s.')
1963             setbpmtimeconstant(0.2)
1964             pause(1.1);
1965
1966             % Check whether bumps and kickers are on and warn to turn off before starting feedback if necessary
1967             try
1968                 if (getsp('SR01S___BUMP1__BC21')==1 & getsp('SR01S___BUMP1P_BC22')==1) | (getsp('SR01S___SEK____BC21')==1 & getsp('SR01S___SEK_P__BC23')==1) | (getsp('SR01S___SEN____BC20')==1 & getsp('SR01S___SEN_P__BC22')==1)
1969                     soundtada;
1970                     fprintf('   \n');
1971                     fprintf('   *********************************************************************************\n');
1972                     fprintf('   ** One or more of the pulsed SR injection magnets is still on!  Turn them off! **\n');
1973                     fprintf('   *********************************************************************************\n');
1974                     fprintf('   \n');
1975                 end
1976             catch
1977                 disp('**Problem checking the state of the bumps and kickers - please check that they are not pulsing.');
1978             end
1979
1980             % Get vectors
1981
1982             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
1983
1984             BPMlist1 = FB.OCSx.BPM.DeviceList;
1985             % FOFB_BPMlist =
1986             HCMlist1 = FB.HCMlist1;
1987             VCMlist1 = FB.VCMlist1;
1988             Xivec = FB.Xivec;
1989             Yivec = FB.Yivec;
1990             Xgoal = FB.OCSx.GoalOrbit;
1991             Ygoal = FB.OCSy.GoalOrbit;
1992             FFTypeFlag = FB.FFTypeFlag;   %local or global tune correction
1993
1994             iNotHCMChicane = find(HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
1995             iHCMChicane = find(HCMlist1(:,2) == 10);
1996             iNotVCMChicane = find(VCMlist1(:,2) < 10);
1997             iVCMChicane = find(VCMlist1(:,2) == 10);
1998
1999             % Sensitivity matrix for setting fast feedback setpoints
2000             Sx1 = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
2001             Sy1 = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
2002
2003         catch
2004             fprintf('\n  %s \n',lasterr);
2005
2006             % Reset Bergoz BPM time constant to whatever it was before feedback started
2007             fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
2008             setbpmtimeconstant(BPMtimeconstantOFB);
2009
2010
2011             a = clock;
2012             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2013             fprintf('   *************************************************************\n');
2014             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
2015             fprintf('   *************************************************************\n\n');
2016             set(0,'showhiddenhandles','off');
2017             pause(0);
2018
2019             return
2020         end
2021
2022         StartFlag = questdlg(strvcat('','Is it OK to start orbit feedback?'),'Orbit Feedback','Yes','No','No');
2023         if strcmp(StartFlag,'No')
2024             % Reset Bergoz BPM time constant to whatever it was before feedback started
2025             fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
2026             setbpmtimeconstant(BPMtimeconstantOFB);
2027
2028             a = clock;
2029             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2030             fprintf('   ***************************\n');
2031             fprintf('   **  Orbit Feedback Exit  **\n');
2032             fprintf('   ***************************\n\n');
2033             pause(0);
2034             return
2035         end
2036
2037         SR_STATE_OLD = scaget('SR_STATE');
2038         setpv('SR_STATE', 5);
2039         set(0,'showhiddenhandles','on');
2040         [StateNumber, StateString] = getsrstate;
2041         if StateNumber >= 0
2042             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2043         else
2044             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2045         end
2046         fprintf('   Using %d E-vectors horizontally.\n', length(Xivec));
2047         fprintf('   Using %d E-vectors vertically.\n',   length(Yivec));
2048         fprintf('   Starting slow orbit correction every %.1f seconds.\n', LoopDelay);
2049         %  fprintf('   Resetting SR11 chicane motors every 20 seconds to fix drift problem.\n');
2050
2051         IDSector = getlist('ID');
2052         EPUlist = find((IDSector(:,1)==4) | (IDSector(:,1)==11));
2053         oldgap=210*ones(size(IDSector,1),1);
2054         oldShift=zeros(size(oldgap));
2055
2056         try
2057
2058             % Get and display data
2059             x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
2060             y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
2061             STDx = norm(x)/sqrt(length(x));
2062             STDy = norm(y)/sqrt(length(y));
2063             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
2064             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
2065
2066             % write goldenorbit values to Fast Orbit Feedback
2067             try
2068                 write_goldenorbit_ffb;
2069             catch
2070                 disp('write_goldenorbit_ffb did not work!');
2071             end
2072             setpv('SR01____FFBON__BC00',2);
2073             %pause(0);
2074
2075             %display state of FOFB system
2076             FOFBStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2077                 getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2078                 getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2079                 getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2080             FOFBStatusStr = ['    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    '];
2081             for loop = 1:size(FOFBStatus,2)
2082                 if FOFBStatus(loop)==0
2083                     FOFBStatusStr(loop,:) = 'OFF ';
2084                 elseif FOFBStatus(loop)==1
2085                     FOFBStatusStr(loop,:) = 'ON  ';
2086                 elseif FOFBStatus(loop)==2
2087                     FOFBStatusStr(loop,:) = 'OPEN';
2088                 else
2089                     FOFBStatusStr(loop,:) = 'BAD ';
2090                 end
2091             end
2092             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 %s',FOFBStatusStr(1,:)),'ForegroundColor',[0 0 0]);
2093             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 %s',FOFBStatusStr(2,:)),'ForegroundColor',[0 0 0]);
2094             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 %s',FOFBStatusStr(3,:)),'ForegroundColor',[0 0 0]);
2095             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 %s',FOFBStatusStr(4,:)),'ForegroundColor',[0 0 0]);
2096             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 %s',FOFBStatusStr(5,:)),'ForegroundColor',[0 0 0]);
2097             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 %s',FOFBStatusStr(6,:)),'ForegroundColor',[0 0 0]);
2098             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 %s',FOFBStatusStr(7,:)),'ForegroundColor',[0 0 0]);
2099             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 %s',FOFBStatusStr(8,:)),'ForegroundColor',[0 0 0]);
2100             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 %s',FOFBStatusStr(9,:)),'ForegroundColor',[0 0 0]);
2101             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 %s',FOFBStatusStr(10,:)),'ForegroundColor',[0 0 0]);
2102             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 %s',FOFBStatusStr(11,:)),'ForegroundColor',[0 0 0]);
2103             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 %s',FOFBStatusStr(12,:)),'ForegroundColor',[0 0 0]);
2104
2105         catch
2106
2107             fprintf('\n  %s \n',lasterr);
2108
2109             % Reset Bergoz BPM time constant to whatever it was before feedback started
2110             fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
2111             setbpmtimeconstant(BPMtimeconstantOFB);
2112
2113
2114             a = clock;
2115             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2116             fprintf('   *************************************************************\n');
2117             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
2118             fprintf('   *************************************************************\n\n');
2119
2120             setpv('SR_STATE',SR_STATE_OLD);
2121             [StateNumber, StateString] = getsrstate;
2122             if StateNumber >= 0
2123                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2124             else
2125                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2126             end
2127             set(0,'showhiddenhandles','off');
2128             pause(0);
2129
2130             return
2131
2132         end
2133
2134
2135         % Disable buttons
2136         set(0,'showhiddenhandles','on');
2137         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','off');
2138         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','on');
2139         set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','off');
2140         set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','off');
2141         set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','off');
2142         set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','off');
2143         set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','off');
2144         set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','off');
2145         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','off');
2146         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','off');
2147         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','off');
2148         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','off');
2149         set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','off');
2150         pause(0);
2151
2152
2153         % Initialize feedback loop
2154         StartTime = gettime;
2155         StartErrorTime = gettime;
2156         Xold = getx(FB.OCSx.BPM.DeviceList);
2157         Yold = gety(FB.OCSy.BPM.DeviceList);
2158         HQMOFM_stalenum = 0;
2159         pause(LoopDelay);
2160
2161         N_HCM = size(HCMlist1,1);
2162         N_VCM = size(VCMlist1,1);
2163
2164         N_RFMO = 1;
2165
2166         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2167             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'SetRF','Nodisplay','Nosetsp');
2168         else
2169             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
2170         end
2171         [FB.OCSx, Smatx, Sx, Ux, Vx] = orbitcorrectionmethods(FB.OCSx);
2172
2173         [FB.OCSy, junk, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
2174         [FB.OCSy, Smaty, Sy, Uy, Vy] = orbitcorrectionmethods(FB.OCSy);
2175
2176
2177         %%%%%%%%%%%%%%%%%%%%%%%
2178         % Start feedback loop %
2179         %%%%%%%%%%%%%%%%%%%%%%%
2180
2181         % chicaneloop=1;  % loop variable for resetting drifting chicanes (see a few lines below)
2182         % fftest=figure;
2183
2184         setpv('SR01____FFBON__BC00',2); % put FOFB in open loop so beamnoise gets recorded even if FOFB is not enabled
2185
2186         while 1
2187             try
2188                 t00 = gettime;
2189
2190                 %          if chicaneloop==20 % reset SR11 motor chicane setpoints every 20s due to drifting positions
2191                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(6),[11 1],0);
2192                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(7),[11 2],0);
2193                 %             chicaneloop = 1;
2194                 %          else
2195                 %             chicaneloop = chicaneloop + 1;
2196                 %          end
2197
2198                 % Check if GUI has been closed
2199                 if isempty(gcbf)
2200                     FEEDBACK_STOP_FLAG = 1;
2201                     lasterr('SRCONTROL GUI DISAPPEARED!');
2202                     error('SRCONTROL GUI DISAPPEARED!');
2203                 end
2204
2205                 %%%%%%%%%%%%%%%%%%%%%%%
2206                 % Fast orbit feedback %
2207                 %%%%%%%%%%%%%%%%%%%%%%%
2208                 if StartFOFBFlag == 1 & FBloopIter > 3
2209                     setpv('SR01____FFBON__BC00',2);
2210                     pause(0.5);
2211                     setpv('SR01____FFBON__BC00',1);
2212                     StartFOFBFlag = 0;
2213                     pause(1);
2214                     FOFBOnStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2215                         getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2216                         getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2217                         getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2218                     if any(FOFBOnStatus==0) | any(FOFBOnStatus==2)
2219                         setpv('SR01____FFBON__BC00',2); % open FOFB loop
2220                         disp('************************************************************************************************************');
2221                         disp('** Problem turning on Fast Orbit Feedback system...                                                       **');
2222                         disp('** Check status of ffbsecXX crates - but remember that a crate reboot will turn off Quads in that sector! **');
2223                         disp('** Suggest disabling the "Fast Orbit Correction" checkbox and starting Orbit Feedback again.              **');
2224                         disp('************************************************************************************************************');
2225                     else
2226                         fprintf('   Starting Fast Orbit Feedback at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
2227                     end
2228                 end
2229
2230
2231                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2232                 % Horizontal plane "feedback" %
2233                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2234
2235                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxSOFB'),'Value') == 1
2236
2237                     % Get orbit and check that the BPMs are different from the last update
2238                     Xnew = getx(FB.OCSx.BPM.DeviceList);
2239
2240                     % Don't feedback if the current is too small
2241                     if getdcct < 5
2242                         FEEDBACK_STOP_FLAG = 1;
2243                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2244                         break;
2245                     end
2246
2247                     x = Xgoal - Xnew;
2248                     STDx = norm(x)/sqrt(length(x));
2249
2250                     if any(Xold == Xnew)
2251                         a = clock;
2252                         N_Stale_Data_Points = find((Xold==Xnew)==1);
2253                         for loop = N_Stale_Data_Points'
2254                             fprintf('   Stale data: BPMx(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSx.BPM.DeviceList(loop,1), FB.OCSx.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2255                         end
2256                     else
2257                         % Compute horizontal correction
2258                         %%%OCSx0 = FB.OCSx;
2259                         FB.OCSx.BPM.Data = Xnew;
2260                         FB.OCSx = orbitcorrectionmethods(FB.OCSx, Smatx, Sx, Ux, Vx);
2261
2262                         %%%[FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
2263
2264                         % reduced feedback gain (implemented by Greg Portmann, December 2000)
2265                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2266                         % increased back to 0.8 C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2267                         % increased to 1.0, C. Steier, 2002-05-04, trim DACs
2268                         X = Xgain .* FB.OCSx.CM.Delta;
2269                         X(N_HCM+1) = 0.3*FB.OCSx.DeltaRF/4.988e-3;
2270                         %%%X = Xgain .* (FB.OCSx.CM.Data - OCSx0.CM.Data);
2271
2272                         % check for trim values+next step values, warn or stop FB as necessary
2273                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2274                         % need to extract Chicanes from this comparison or maybe check them first for range %
2275                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2276                         HCMtrimSP=getpv('HCM','Trim',HCMlist1);
2277                         HCMtrimSP_next = HCMtrimSP + X(1:N_HCM);
2278                         if max(abs(HCMtrimSP_next)) > 4
2279                             HCMtrimnum=find(abs(HCMtrimSP_next) > 4);
2280
2281                             % print message to screen
2282                             fprintf('**One or more of the horizontal correctors is at its maximum!! Stopping orbit feedback. \n');
2283                             fprintf('%s\n',datestr(now));
2284                             for loop = HCMtrimnum'
2285                                 fprintf('**%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2286                             end
2287
2288                             % send alphapage to operator pager
2289                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2290                             FEEDBACK_STOP_FLAG = 1;
2291
2292                             setpv('SR_STATE', -5);
2293                             [StateNumber, StateString] = getsrstate;
2294                             if StateNumber >= 0
2295                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2296                             else
2297                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2298                             end
2299                         end
2300
2301                         if FEEDBACK_STOP_FLAG == 1
2302                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2303                             if getpv('SR01____FFBON__BC00')==1
2304                                 disp('   Stopping Fast Orbit Feedback.');
2305                             end
2306                             setpv('SR01____FFBON__BC00',0);
2307                             pause(0.5);
2308                             setpv('SR01____FFBON__BC00',2);
2309                             break;
2310                         end
2311
2312                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2313                         pause(0);
2314
2315                         if max(abs(HCMtrimSP_next) > 3)
2316                             HCMtrimnum=find(abs(HCMtrimSP_next) > 3);
2317                             HWarnNum=HWarnNum+1;
2318                             if (HWarnNum==1 | rem(HWarnNum,120)==0)
2319
2320                                 % print message to screen every two minutes
2321                                 fprintf('**One or more of the horizontal corrector trims is above 3A or below -3A! \n');
2322                                 fprintf('%s\n',datestr(now));
2323                                 for loop = HCMtrimnum'
2324                                     fprintf('**%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2325                                 end
2326                                 fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2327
2328                                 %send alphapage to operator pager the first time then at 10 minutes
2329                                 if (HWarnNum==1 | HWarnNum==600)
2330                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageHCM.txt
2331                                 end
2332                             end
2333                         else
2334                             HWarnNum=0;
2335                         end
2336
2337                         % Don't feedback if the current is too small
2338                         if getdcct < 5
2339                             FEEDBACK_STOP_FLAG = 1;
2340                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2341                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2342                             break;
2343                         end
2344
2345                         if N_HCM > 0
2346                             steppv('HCM','Trim', X(iNotHCMChicane), HCMlist1(iNotHCMChicane,:), 0);
2347                             steppv('HCM','Setpoint', X(iHCMChicane), HCMlist1(iHCMChicane,:), 0);
2348                         end
2349
2350                         % write fast orbit feedback setpoints
2351                         if 1
2352                             %write_goldenorbit_ffb_2planes(1, Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM)+Sx3*X(length(X))/20, BPMlist1);
2353                             % should be corrected to include result of next frequency step ...
2354                             write_goldenorbit_ffb_2planes(1,Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM),BPMlist1);
2355                         end
2356
2357                         %fprintf('Horizontal Done: %f \n',gettime-t00);
2358
2359                         % RF feedback
2360                         HQMOFMsp_last = getpv('EG______HQMOFM_AC01');
2361
2362                         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2363                             if N_RFMO > 0
2364                                 if abs(X(end)/3) < .01
2365                                     % if abs(FB.OCSx.DeltaRF/3) < .01
2366                                     steppv('EG______HQMOFM_AC01', X(end));
2367                                 else
2368                                     steppv('EG______HQMOFM_AC01', 0.01*sign(X(end)));
2369                                 end
2370                             end
2371
2372                             HQMOFMsp_now = getpv('EG______HQMOFM_AC01');
2373
2374                             % Check for stale RF feedback
2375                             if HQMOFMsp_last == HQMOFMsp_now
2376                                 HQMOFM_stalenum = HQMOFM_stalenum + 1;
2377                                 if HQMOFM_stalenum == 30 % warn and message to pager if stale for 30 secs
2378                                     fprintf('**The RF is not responding to orbit feedback changes! \n');
2379                                     fprintf('%s\n',datestr(now));
2380                                     fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2381                                     fprintf('**ILC 73 controls the EG______HQMOFM_AC01 channel, which sets the RF frequency. \n');
2382                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstaleRFmessage.txt
2383                                 end
2384                                 if rem(HQMOFM_stalenum,120)==0 % message to screen every 2 minutes
2385                                     fprintf('**The RF is not responding to orbit feedback changes! (%s)\n',datestr(now));
2386                                 end
2387                             else
2388                                 HQMOFM_stalenum = 0;
2389                             end
2390
2391                         end
2392
2393                         %fprintf('RF Done: %f \n',gettime-t00);
2394
2395                         Xold = Xnew;
2396                     end % End horizontal correction
2397
2398
2399                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2400                     % Vertical plane "feedback" %
2401                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2402
2403                     % Get orbit and check that the BPMs are different from the last update
2404                     Ynew = gety(FB.OCSy.BPM.DeviceList);
2405
2406                     % Don't feedback if the current is too small
2407                     if getdcct < 5
2408                         FEEDBACK_STOP_FLAG = 1;
2409                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2410                         break;
2411                     end
2412
2413                     y = Ygoal - Ynew;
2414                     STDy = norm(y)/sqrt(length(y));
2415
2416                     if any(Yold == Ynew)
2417                         a = clock;
2418                         N_Stale_Data_Points = find((Yold==Ynew)==1);
2419                         for loop = N_Stale_Data_Points'
2420                             fprintf('   Stale data: BPMy(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSy.BPM.DeviceList(loop,1), FB.OCSy.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2421                         end
2422
2423                     else
2424
2425                         % Compute vertical correction
2426                         %%%OCSy0 = FB.OCSy;
2427                         FB.OCSy.BPM.Data = Ynew;
2428                         FB.OCSy = orbitcorrectionmethods(FB.OCSy, Smaty, Sy, Uy, Vy);
2429
2430                         %%%[FB.OCSy, RF, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
2431
2432                         % reduced feedback gain, C. Steier, 2001-03-25
2433                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2434                         % increased back to 0.8, C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2435                         % set to unity gain, C. Steier, 2002-05-04, trim DACs
2436                         Y = Ygain .* FB.OCSy.CM.Delta;
2437                         %%%Y = Ygain .* (FB.OCSy.CM.Data - OCSy0.CM.Data);
2438
2439                         % Just SVD correction
2440                         % warning('Not using "micado" correction in the vertical plane.');
2441
2442                         % check for trim values+next step values, warn or stop FB as necessary
2443                         VCMtrimSP = getpv('VCM','Trim',VCMlist1);
2444                         VCMtrimSP_next = VCMtrimSP + Y(1:N_VCM);
2445                         if max(abs(VCMtrimSP_next)) > 12
2446                             VCMtrimnum=find(abs(VCMtrimSP_next) > 12);
2447
2448                             % print message to screen
2449                             fprintf('**One or more of the vertical correctors is at its maximum!! Stopping orbit feedback. \n');
2450                             fprintf('%s\n',datestr(now));
2451                             for loop = VCMtrimnum'
2452                                 fprintf('**%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2453                             end
2454
2455                             % send alphapage to operator pager
2456                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2457                             FEEDBACK_STOP_FLAG = 1;
2458
2459                             setpv('SR_STATE', -5);
2460                             [StateNumber, StateString] = getsrstate;
2461                             if StateNumber >= 0
2462                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2463                             else
2464                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2465                             end
2466                         end
2467
2468                         if FEEDBACK_STOP_FLAG == 1
2469                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2470                             if getpv('SR01____FFBON__BC00')==1
2471                                 disp('   Stopping Fast Orbit Feedback.');
2472                             end
2473                             setpv('SR01____FFBON__BC00',0);
2474                             pause(0.5);
2475                             setpv('SR01____FFBON__BC00',2);
2476                             break;
2477                         end
2478
2479                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2480                         % pause(0);
2481
2482                         if max(abs(VCMtrimSP_next) > 4)
2483                             VCMtrimnum=find(abs(VCMtrimSP_next) > 4);
2484                             VWarnNum=VWarnNum+1;
2485                             if (VWarnNum==1 | rem(VWarnNum,120)==0)
2486
2487                                 % print message to screen every two minutes
2488                                 fprintf('**One or more of the vertical corrector trims is above 4A or below -4A! \n');
2489                                 fprintf('%s\n',datestr(now));
2490                                 for loop = VCMtrimnum'
2491                                     fprintf('**%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2492                                 end
2493                                 fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2494
2495                                 %send alphapage to operator pager the first time then at 10 minutes
2496                                 if (VWarnNum==1 | VWarnNum==600)
2497                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageVCM.txt
2498                                 end
2499                             end
2500                         else
2501                             VWarnNum=0;
2502                         end
2503
2504                         % Don't feedback if the current is too small
2505                         if getdcct < 5
2506                             FEEDBACK_STOP_FLAG = 1;
2507                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2508                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2509                             break;
2510                         end
2511
2512                         if N_VCM > 0
2513                             steppv('VCM','Trim', Y(iNotVCMChicane), VCMlist1(iNotVCMChicane,:), 0);
2514                             steppv('VCM','Setpoint', Y(iVCMChicane), VCMlist1(iVCMChicane,:), 0);
2515                         end
2516
2517                         % write fast orbit feedback setpoints
2518                         if 1
2519                             write_goldenorbit_ffb_2planes(2,Ynew(1:size(BPMlist1,1))+Sy1*Y(1:N_VCM),BPMlist1);
2520                         end
2521
2522                     end
2523
2524                     Yold = Ynew;
2525
2526                     %fprintf('Vertical Done: %f \n',gettime-t00);
2527                 end % End vertical correction
2528
2529
2530                 %%%%%%%%%%%%%%%%%%%%%
2531                 % Tune feed forward %
2532                 %%%%%%%%%%%%%%%%%%%%%
2533                 % We should do a Sector limit check
2534
2535                 tic;
2536                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxTune'),'Value') == 1
2537
2538                     if strcmp(SR_Mode, '1.9 GeV, High Tune') || strcmp(SR_Mode, '1.9 GeV, Inject at 1.23') || strcmp(SR_Mode, '1.9 GeV, Two-Bunch')
2539
2540                         addQFsp = zeros(24,1);
2541                         addQDsp = zeros(24,1);
2542
2543                         if strcmp(FFTypeFlag,'Local')
2544                             disp('  No local tune compensation available - global is the default now.');
2545                         elseif strcmp(FFTypeFlag,'Global')
2546
2547                             % The vectorized gets were put outside of loop for speed reasons
2548                             %
2549                             % should also set up QFfac, Quadelem, Quadlist structures outside loop
2550                             actualgap = getid(IDSector);
2551                             [gapmin,gapmax] = gaplimit(IDSector);
2552                             corrind = find(actualgap<(gapmin-1));
2553                             actualgap(corrind)=gapmax(corrind);
2554                             Shift=zeros(size(actualgap));
2555                             Shift(EPUlist)=getpv('EPU');
2556
2557                             IDchangedList=find((abs(actualgap-oldgap)>0.005) | (abs(Shift-oldShift)>0.005));
2558
2559                             if ~isempty(IDchangedList)
2560
2561                                 oldgap=actualgap;
2562                                 oldShift=Shift;
2563
2564                                 % EPUs excite nux = .25 resonance in vertical linear polarization mode!
2565                                 % therefore with EPU tune feedforward
2566                                 % running, we want to move our nominal working point away (just below) the .25 resonance.
2567                                 %
2568                                 % The following tune correction moves nominal
2569                                 % nu_x from .25 to .245 - this should be enough for well set up lattices.
2570                                 %
2571                                 % 24 QF+ 24 QD
2572                                 DeltaAmps = inv(SR_TUNE_MATRIX) * [-0.005;0];    %  DelAmps =  [QF; QD];
2573                                 addQFsp = addQFsp + DeltaAmps(1,:);
2574                                 addQDsp = addQDsp + DeltaAmps(2,:);
2575
2576                                 for gapnum = 1:length(actualgap)
2577
2578                                     % Change in tune and [QF;QD] from maximum gap
2579
2580                                     if (IDSector(gapnum,1) == 4) | (IDSector(gapnum,1) == 11)
2581                                         if IDSector(gapnum,2) == 1
2582                                             modenamestr = sprintf('SR%02dU___ODS1M__DC00',IDSector(gapnum,1));
2583                                         else % if IDSector(gapnum,2) == 2
2584                                             modenamestr = sprintf('SR%02dU___ODS2M__DC00',IDSector(gapnum,1));
2585                                         end
2586                                         epumode = getpvonline(modenamestr);
2587                                         if IDSector(gapnum,2)==2
2588                                             longshift=3;
2589                                         else
2590                                             longshift=0;
2591                                         end
2592                                         if (epumode==0) & (any(IDSector(gapnum,:)~=[11 1]))      % antiparallel tables need to be fit to data so that they could be used here
2593                                             DeltaNuX = shift2tune(IDSector(gapnum,1),actualgap(gapnum),Shift(gapnum)+longshift,SR_GeV);
2594                                             DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);   % variation of vertical tune shift with phase is small for EPUs
2595                                         else
2596                                             DeltaNuX = 0;
2597                                             DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);   % variation of vertical tune shift with phase is small for EPUs
2598                                         end
2599
2600                                     else
2601                                         DeltaNuX = 0;
2602                                         DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);
2603                                     end
2604
2605                                     DelQF = zeros(length(QFsp),1);
2606                                     DelQD = zeros(length(QFsp),1);
2607
2608                                     fraccorr = 0.8*DeltaNuY ./ TuneW16Min;
2609
2610                                     % Find which quads to change (local beta beating correction
2611                                     % (horizontal for EPU, vertical otherwise)
2612                                     QuadList = [IDSector(gapnum,1)-1 2; IDSector(gapnum,1) 1];
2613                                     QuadElem = dev2elem('QF',QuadList); % in reality use QF and QD ...
2614
2615                                     % global vertical tune correction
2616                                     % 24 QF+ 24 QD
2617                                     DeltaAmps = inv(SR_TUNE_MATRIX) * [(fraccorr*6.23e-4); fraccorr*(-0.05301)];    %  DelAmps =  [QF; QD];
2618                                     DelQF = DelQF + DeltaAmps(1,:);
2619                                     DelQD = DelQD + DeltaAmps(2,:);
2620
2621                                     % local horizontal tune correction (is also nearly a beta beating correction) only nonzero for EPUs!
2622                                     % 2 QF + 2 QD
2623                                     DeltaAmpsLocal = 12*inv(SR_TUNE_MATRIX) * [-DeltaNuX;0];                       %  DelAmps =  [QF; QD];
2624                                     DelQF(QuadElem) = DelQF(QuadElem)+DeltaAmpsLocal(1,1);
2625                                     DelQD(QuadElem) = DelQD(QuadElem)+DeltaAmpsLocal(2,1);
2626
2627                                     % local vertical beta beating correction (should be used together with above global tune correction)
2628                                     % set to zero for EPUs, since their vertical tune shift is small
2629                                     % 2 QF + 2QD
2630                                     if (IDSector(gapnum,1)==6) | (IDSector(gapnum,1)==7) | (IDSector(gapnum,1)==10) | (IDSector(gapnum,1)==11)
2631                                         QFfac = ([2.243127/2.237111; 2.243127/2.237111]-1) * fraccorr;
2632                                         QDfac = ([2.556392/2.511045; 2.556392/2.511045]-1) * fraccorr;
2633                                     elseif (IDSector(gapnum,1)==5) | (IDSector(gapnum,1)==9)
2634                                         QFfac = ([2.225965/2.219784; 2.243096/2.237111]-1) * fraccorr;
2635                                         QDfac = ([2.528950/2.483259; 2.556345/2.511045]-1) * fraccorr;
2636                                     elseif (IDSector(gapnum,1)==4) | (IDSector(gapnum,1)==8) | (IDSector(gapnum,1)==12)
2637                                         QFfac = ([2.243096/2.237111; 2.225965/2.219784]-1) * fraccorr;
2638                                         QDfac = ([2.556345/2.511045; 2.528950/2.483259]-1) * fraccorr;
2639                                     else
2640                                         QFfac = zeros(2,1);
2641                                         QDfac = zeros(2,1);
2642                                     end
2643
2644                                     DelQF(QuadElem,:) = DelQF(QuadElem,:) + QFfac.*QFsp(QuadElem,:);
2645                                     DelQD(QuadElem,:) = DelQD(QuadElem,:) + QDfac.*QDsp(QuadElem,:);
2646
2647                                     % add all tune and beta beating corrections for this one ID to the summed up correction vectors for all IDs
2648                                     addQFsp = addQFsp+DelQF;
2649                                     addQDsp = addQDsp+DelQD;
2650
2651
2652                                     % Skew FF for IVID
2653                                     if (IDSector(gapnum,1)==6)
2654                                         % what input argument do we use below???
2655                                         [SQSFincr, HCSFincr, SQSDincr, HCSDincr] = set_etaywave_nuy9_20skews_skewFF(scale);
2656                                     end
2657
2658                                 end
2659
2660                                 % Set quadrupoles using main setpoint channels
2661                                 setpv('QF', QFsp+addQFsp,[], 0);
2662                                 setpv('QD', QDsp+addQDsp,[], 0);
2663                                 % % Set quadrupoles using FF setpoint channels
2664                                 % setpv('QF', 'FF', addQFsp, [], 0);
2665                                 % setpv('QD', 'FF', addQDsp, [], 0);
2666
2667                                 % Set skew quadrupoles to compensate for IVID skew effect
2668                                 setpv('SQSF', SQSFsp+SQSFincr, [], 0);
2669                                 setpv('SQSD', SQSDsp+SQSDincr, [], 0);
2670                                 setpv('HCM', HCSFsp+HCSFincr, [HCSFindex], 0);
2671                                 setpv('HCM', HCSDsp+HCSDincr, [HCSDindex], 0);
2672                             end
2673
2674                         else
2675                             error('Unknown type selected for tune FF');
2676                         end
2677
2678                     else
2679                         disp('  No tune FF algorithm for non-production modes yet...');
2680                     end
2681                 end
2682
2683                 ffdeltaquad_delay = toc;
2684                 %fprintf('tune FF delay = %.1f seconds\n',ffdeltaquad_delay);
2685                 % fprintf('Tune Done: %f \n',gettime-t00);
2686
2687                 % Output info to screen
2688                 set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
2689                 set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
2690                 %pause(0);
2691
2692                 FOFBStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2693                     getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2694                     getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2695                     getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2696                 for loop = 1:size(FOFBStatus,2)
2697                     if FOFBStatus(loop)==0
2698                         FOFBStatusStr(loop,:) = 'OFF ';
2699                     elseif FOFBStatus(loop)==1
2700                         FOFBStatusStr(loop,:) = 'ON  ';
2701                     elseif FOFBStatus(loop)==2
2702                         FOFBStatusStr(loop,:) = 'OPEN';
2703                     else
2704                         FOFBStatusStr(loop,:) = 'BAD ';
2705                     end
2706                 end
2707                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 %s',FOFBStatusStr(1,:)),'ForegroundColor',[0 0 0]);
2708                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 %s',FOFBStatusStr(2,:)),'ForegroundColor',[0 0 0]);
2709                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 %s',FOFBStatusStr(3,:)),'ForegroundColor',[0 0 0]);
2710                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 %s',FOFBStatusStr(4,:)),'ForegroundColor',[0 0 0]);
2711                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 %s',FOFBStatusStr(5,:)),'ForegroundColor',[0 0 0]);
2712                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 %s',FOFBStatusStr(6,:)),'ForegroundColor',[0 0 0]);
2713                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 %s',FOFBStatusStr(7,:)),'ForegroundColor',[0 0 0]);
2714                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 %s',FOFBStatusStr(8,:)),'ForegroundColor',[0 0 0]);
2715                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 %s',FOFBStatusStr(9,:)),'ForegroundColor',[0 0 0]);
2716                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 %s',FOFBStatusStr(10,:)),'ForegroundColor',[0 0 0]);
2717                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 %s',FOFBStatusStr(11,:)),'ForegroundColor',[0 0 0]);
2718                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 %s',FOFBStatusStr(12,:)),'ForegroundColor',[0 0 0]);
2719
2720
2721                 %fprintf('End of feedback operations: %f \n\n',gettime-t00);
2722
2723                 % Wait for next update time or stop request
2724                 while (gettime-t00) < LoopDelay
2725                     %disp('interval could be shorter')
2726                     pause(.05);
2727                     % Check if GUI has been closed
2728                     if isempty(gcbf)
2729                         FEEDBACK_STOP_FLAG = 1;
2730                         lasterr('SRCONTROL GUI DISAPPEARED!');
2731                         error('SRCONTROL GUI DISAPPEARED!');
2732                     end
2733
2734                     % Check if Stop button was pressed
2735                     if FEEDBACK_STOP_FLAG == 1
2736                         % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2737                         if getpv('SR01____FFBON__BC00')==1
2738                             disp('   Stopping Fast Orbit Feedback.');
2739                         end
2740                         setpv('SR01____FFBON__BC00',0);
2741                         pause(0.5);
2742                         setpv('SR01____FFBON__BC00',2);
2743                         break;
2744                     end
2745                 end
2746
2747
2748                 if FEEDBACK_STOP_FLAG == 1
2749                     % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2750                     if getpv('SR01____FFBON__BC00')==1
2751                         disp('   Stopping Fast Orbit Feedback.');
2752                     end
2753                     setpv('SR01____FFBON__BC00',0);
2754                     pause(0.5);
2755                     setpv('SR01____FFBON__BC00',2);
2756                     break;
2757                 end
2758
2759                 StartErrorTime = gettime;
2760
2761             catch
2762
2763                 fprintf('\n  %s \n',lasterr);
2764
2765                 % Quit if error exists for more than 20 seconds
2766                 if gettime-StartErrorTime>20 | FEEDBACK_STOP_FLAG==1
2767                     fprintf('%s  Orbit feedback stopped due to error condition. \n\n',datestr(now));
2768
2769                     %send alphapage to operator pager
2770                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2771                     FEEDBACK_STOP_FLAG = 1;
2772
2773                     setpv('SR_STATE', -5);
2774                     [StateNumber, StateString] = getsrstate;
2775                     if StateNumber >= 0
2776                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2777                     else
2778                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2779                     end
2780                 else
2781                     a = clock;
2782                     fprintf('   Orbit feedback was paused due to error condition (%s %d:%d:%.0f). \n', date, a(4), a(5), a(6));
2783                     fprintf('   Orbit feedback has automatically restarted and is running. \n\n');
2784                 end
2785
2786             end
2787
2788             if FEEDBACK_STOP_FLAG == 1
2789                 % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2790                 if getpv('SR01____FFBON__BC00')==1
2791                     disp('   Stopping Fast Orbit Feedback.');
2792                 end
2793                 setpv('SR01____FFBON__BC00',0);
2794                 pause(0.5);
2795                 setpv('SR01____FFBON__BC00',2);
2796                 break;
2797             end
2798
2799             %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2800
2801             %pause(0);
2802
2803             % this loop delays turn on of Fast Feedback system
2804             if FBloopIter < 5
2805                 FBloopIter = FBloopIter + 1;
2806             end
2807
2808         end  % End of feedback loop
2809
2810
2811         % End feedback, reset all parameters
2812         try
2813
2814             % Enable buttons
2815             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','on');
2816             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','off');
2817             set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','on');
2818             set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','on');
2819             set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','on');
2820             set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','on');
2821             set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','on');
2822             set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','on');
2823             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','on');
2824             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','on');
2825             set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','on');
2826             set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','on');
2827             set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','on');
2828
2829             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = _____ mm'),'ForegroundColor',[0 0 0]);
2830             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = _____ mm'),'ForegroundColor',[0 0 0]);
2831
2832             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 ____'),'ForegroundColor',[0 0 0]);
2833             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 ____'),'ForegroundColor',[0 0 0]);
2834             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 ____'),'ForegroundColor',[0 0 0]);
2835             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 ____'),'ForegroundColor',[0 0 0]);
2836             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 ____'),'ForegroundColor',[0 0 0]);
2837             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 ____'),'ForegroundColor',[0 0 0]);
2838             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 ____'),'ForegroundColor',[0 0 0]);
2839             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 ____'),'ForegroundColor',[0 0 0]);
2840             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 ____'),'ForegroundColor',[0 0 0]);
2841             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 ____'),'ForegroundColor',[0 0 0]);
2842             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 ____'),'ForegroundColor',[0 0 0]);
2843             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 ____'),'ForegroundColor',[0 0 0]);
2844
2845             %pause(0);
2846
2847         catch
2848
2849             % GUI must have been closed
2850
2851         end
2852
2853
2854         % Reset Bergoz BPM time constant to whatever it was before feedback started
2855         fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
2856         setbpmtimeconstant(BPMtimeconstantOFB);
2857
2858
2859         a = clock;
2860         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2861         [StateNumber, StateString] = getsrstate;
2862         if StateNumber >= 0
2863             setpv('SR_STATE',5.1);
2864             [StateNumber, StateString] = getsrstate;
2865             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2866             fprintf('   ******************************\n');
2867             fprintf('   **  Orbit Feedback Stopped  **\n');
2868             fprintf('   ******************************\n\n');
2869         else
2870             [StateNumber, StateString] = getsrstate;
2871             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2872             fprintf('   ****************************************\n');
2873             fprintf('   **  Problem With Slow Orbit Feedback  **\n');
2874             fprintf('   ****************************************\n\n');
2875         end
2876         set(0,'showhiddenhandles','off');
2877         pause(0);
2878
2879
2880     case 'FeedbackSetup'
2881         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
2882
2883         if InitFlag
2884             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2885             % Edit the following lists to change default configuration of Orbit Correction %
2886             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2887
2888             % Corrector magnets
2889             listh=[
2890                 1 2;
2891                 1 8;
2892                 2 1;
2893                 2 8;
2894                 3 1;
2895                 3 8;
2896                 3 10; %SR04U_HCM2 (chicane trim)
2897                 4 1;
2898                 4 8;
2899                 5 1;
2900                 5 8;
2901                 5 10; %SR06U_HCM2 (chicane trim)
2902                 6 1;
2903                 6 8;
2904                 7 1;
2905                 7 8;
2906                 8 1;
2907                 8 8;
2908                 9 1;
2909                 9 8;
2910                 10 1;
2911                 10 8;
2912                 10 10; %SR11U_HCM2 (chicane trim)
2913                 11 1;
2914                 11 8;
2915                 12 1;
2916                 12 7];
2917             listv=[
2918                 1 2;
2919                 1 8;
2920                 2 1;
2921                 2 8;
2922                 3 1;
2923                 3 7;
2924                 3 8;
2925                 3 10; %SR04U_VHCM2 (chicane trim)
2926                 4 1;
2927                 4 7;
2928                 4 8;
2929                 5 1;
2930                 5 8;
2931                 5 10; %SR06U_VHCM2 (chicane trim)
2932                 6 1;
2933                 6 8;
2934                 7 1;
2935                 7 8;
2936                 8 1;
2937                 8 8;
2938                 9 1;
2939                 9 8;
2940                 10 1;
2941                 10 2;
2942                 10 7;
2943                 10 8;
2944                 10 10; %SR11U_VHCM2 (chicane trim)
2945                 11 1;
2946                 11 7;
2947                 11 8;
2948                 12 1;
2949                 12 7];
2950
2951             Xivec = [1:28];
2952             Yivec = [1:32];
2953             HCMlist1 = listh;
2954             VCMlist1 = listv;
2955
2956             % Full BPM list
2957             BPMlist1 = [
2958                 1 2
2959                 1 5
2960                 1 6
2961                 1 10
2962                 2 1
2963                 2 5
2964                 2 6
2965                 2 9
2966                 3 2
2967                 3 5
2968                 3 6
2969                 3 10
2970                 3 11
2971                 3 12
2972                 4 1
2973                 4 5
2974                 4 6
2975                 4 10
2976                 5 1
2977                 5 5
2978                 5 6
2979                 5 10
2980                 5 11
2981                 5 12
2982                 6 1
2983                 6 5
2984                 6 6
2985                 6 10
2986                 7 1
2987                 7 5
2988                 7 6
2989                 7 10
2990                 8 1
2991                 8 5
2992                 8 6
2993                 8 10
2994                 9 1
2995                 9 5
2996                 9 6
2997                 9 10
2998                 10 1
2999                 10 5
3000                 10 6
3001                 10 10
3002                 10 11
3003                 10 12
3004                 11 1
3005                 11 5
3006                 11 6
3007                 11 10
3008                 12 1
3009                 12 5
3010                 12 6
3011                 12 9
3012                 ];
3013
3014             % remove Bergoz BPMs in SR01 and SR03 for 2-bunch (noisy at low currents) and drop singular values
3015             if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
3016                     BPMlist1 = [
3017                          %1 2
3018                          1 5
3019                          1 6
3020                          1 10
3021                          2 1
3022                          2 5
3023                          2 6
3024                          %2 9
3025                          %3 2
3026                          3 5
3027                          3 6
3028                          3 10
3029                          3 11
3030                          3 12
3031                          4 1
3032                          4 5
3033                          4 6
3034                          4 10
3035                          5 1
3036                          5 5
3037                          5 6
3038                          5 10
3039                          5 11
3040                          5 12
3041                          6 1
3042                          6 5
3043                          6 6
3044                          6 10
3045                          7 1
3046                          7 5
3047                          7 6
3048                          7 10
3049                          8 1
3050                          8 5
3051                          8 6
3052                          8 10
3053                          9 1
3054                          9 5
3055                          9 6
3056                          9 10
3057                          10 1
3058                          10 5
3059                          10 6
3060                          10 10
3061                          10 11
3062                          10 12
3063                          11 1
3064                          11 5
3065                          11 6
3066                          11 10
3067                          12 1
3068                          12 5
3069                          12 6
3070                          %12 9
3071                          ];
3072             end
3073
3074             OCSx.BPM = getx(BPMlist1, 'struct');
3075             OCSx.CM = getsp('HCM', HCMlist1, 'struct');
3076             OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
3077             OCSx.NIter = 1;
3078             OCSx.SVDIndex = Xivec;
3079             OCSx.IncrementalFlag = 'No';
3080             OCSx.BPMWeight = {[]};
3081             OCSx.FitRF = 0;
3082             OCSy.BPM = gety(BPMlist1, 'struct');
3083             OCSy.CM = getsp('VCM', VCMlist1, 'struct');
3084             OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
3085             OCSy.NIter = 1;
3086             OCSy.SVDIndex = Yivec;
3087             OCSy.IncrementalFlag = 'No';
3088             OCSy.BPMWeight = {[]};
3089             OCSy.FitRF = 0;
3090             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
3091             % do we need these Smat calls? %
3092             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
3093             SXmat = getrespmat(OCSx.BPM, OCSx.CM, 'numeric');
3094             SYmat = getrespmat(OCSy.BPM, OCSy.CM, 'numeric');
3095             % [OCSx, Sx, Ux, Vx] = orbitcorrectionmethods(OCSx, SXmat);
3096             % [OCSy, Sy, Uy, Vy] = orbitcorrectionmethods(OCSy, SYmat);
3097
3098             % initialize FFTypeFlag
3099             FFTypeFlag = 'Global';
3100
3101         else
3102
3103             % Get vectors
3104             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
3105             % the two lines below seem to fix BPMlist editing problem
3106             OCSx = FB.OCSx;
3107             OCSy = FB.OCSy;
3108             BPMlist1 = FB.BPMlist1;
3109             HCMlist1 = FB.HCMlist1;
3110             VCMlist1 = FB.VCMlist1;
3111             Xivec = FB.Xivec;
3112             Yivec = FB.Yivec;
3113             Xgoal = FB.OCSx.GoalOrbit;
3114             OCSx.GoalOrbit = Xgoal;
3115             Ygoal = FB.OCSy.GoalOrbit;
3116             OCSy.GoalOrbit = Ygoal;
3117             FFTypeFlag = FB.FFTypeFlag;
3118
3119
3120             % FF corrector magnet list
3121             ListFF = [
3122                 4     2
3123                 4     8
3124                 5     1
3125                 5     7
3126 %               5     8 % why are these out???
3127 %               6     1 % why are these out???
3128                 6     8
3129                 7     1
3130                 7     8
3131                 8     1
3132                 8     8
3133                 9     1
3134                 9     8
3135                 10    1
3136                 11    8
3137                 12    1];
3138             ElemFF = dev2elem('HCM',ListFF);
3139
3140
3141             % Add button to change #ivectors, cm, IDBPMs,
3142             EditFlag = 0;
3143             h_fig1 = figure;
3144             while EditFlag ~= 6
3145
3146                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
3147                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
3148
3149                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
3150                     DispOrbit = getdisp('BPMx', BPMlist1);
3151                     Sx = [Sx DispOrbit];
3152                 end
3153
3154                 [Ux, SVx, Vx] = svd(Sx);
3155                 [Uy, SVy, Vy] = svd(Sy);
3156
3157
3158                 % Remove singular values greater than the actual number of singular values
3159                 i = find(Xivec>length(diag(SVx)));
3160                 if ~isempty(i)
3161                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
3162                     pause(0);
3163                     Xivec(i) = [];
3164                 end
3165                 i = find(Yivec>length(diag(SVy)));
3166                 if ~isempty(i)
3167                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
3168                     pause(0);
3169                     Yivec(i) = [];
3170                 end
3171
3172
3173                 Ax = Sx*Vx(:,Xivec);
3174                 Tx = inv(Ax'*Ax)*Ax';
3175
3176                 Ay = Sy*Vy(:,Yivec);
3177                 Ty = inv(Ay'*Ay)*Ay';
3178
3179                 figure(h_fig1);
3180                 subplot(2,1,1);
3181                 semilogy(diag(SVx),'b');
3182                 hold on;
3183                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
3184                 ylabel('Horizontal');
3185                 title('Response Matrix Singular Values');
3186                 hold off;
3187                 subplot(2,1,2);
3188                 semilogy(diag(SVy),'b');
3189                 hold on;
3190                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
3191                 xlabel('Singular Value Number');
3192                 ylabel('Vertical');
3193                 hold off;
3194                 drawnow;
3195
3196                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List', ...
3197                     'BPM List','Change the Goal Orbit','Continue');
3198
3199                 if EditFlag == 1
3200                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
3201                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
3202                     titlestr='SVD Orbit Feedback';
3203                     lineNo=1;
3204                     answer=inputdlg(prompt,titlestr,lineNo,def);
3205                     if ~isempty(answer)
3206                         XivecNew = fix(str2num(answer{1}));
3207                         if isempty(XivecNew)
3208                             disp('   Horizontal E-vector cannot be empty.  No change made.');
3209                         else
3210                             if any(XivecNew<=0) | max(XivecNew)>length(diag(SVx))
3211                                 disp('   Error reading horizontal E-vector.  No change made.');
3212                             else
3213                                 Xivec = XivecNew;
3214                             end
3215                         end
3216                         YivecNew = fix(str2num(answer{2}));
3217                         if isempty(YivecNew)
3218                             disp('   Vertical E-vector cannot be empty.  No change made.');
3219                         else
3220                             if any(YivecNew<=0) | max(YivecNew)>length(diag(SVy))
3221                                 disp('   Error reading vertical E-vector.  No change made.');
3222                             else
3223                                 Yivec = YivecNew;
3224                             end
3225                         end
3226                     end
3227                 end
3228
3229                 if EditFlag == 2
3230                     List= getlist('HCM','Trim');
3231                     CheckList = zeros(96,1);
3232                     Elem = dev2elem('HCM', HCMlist1);
3233                     CheckList(Elem) = ones(size(Elem));
3234                     CheckList = CheckList(dev2elem('HCM',List));
3235
3236                     % Remove FF corrrectors
3237                     %           Elem = dev2elem('HCM',List);
3238                     %           for j = length(ElemFF):-1:1
3239                     %              i = find(Elem==ElemFF(j));
3240                     %              Elem(i,:) = [];
3241                     %              List(i,:) = [];
3242                     %              CheckList(i,:) = [];
3243                     %           end
3244
3245                     newList = editlist(List, 'HCMtrim', CheckList);
3246
3247                     if isempty(newList)
3248                         fprintf('   WARNING: Horizontal corrector magnet list is empty!\n');
3249                         HCMlist1 = newList;
3250                     else
3251                         HCMlist1 = newList;
3252                     end
3253                     OCSx.CM.DeviceList = HCMlist1;
3254                 end
3255
3256                 if EditFlag == 3
3257                     List = getlist('VCM','Trim');
3258                     CheckList = zeros(96,1);
3259                     Elem = dev2elem('VCM', VCMlist1);
3260                     CheckList(Elem) = ones(size(Elem));
3261                     CheckList = CheckList(dev2elem('VCM',List));
3262
3263                     % Remove FF corrrectors
3264                     %           Elem = dev2elem('VCM',List);
3265                     %           for j = length(ElemFF):-1:1
3266                     %              i = find(Elem==ElemFF(j));
3267                     %              Elem(i,:) = [];
3268                     %              List(i,:) = [];
3269                     %              CheckList(i,:) = [];
3270                     %           end
3271
3272                     newList = editlist(List, 'VCMtrim', CheckList);
3273
3274                     if isempty(newList)
3275                         fprintf('   WARNING: Vertical corrector magnet list is empty!\n');
3276                         VCMlist1 = newList;
3277                     else
3278                         VCMlist1 = newList;
3279                     end
3280                     OCSy.CM.DeviceList = VCMlist1;
3281                 end
3282
3283                 if EditFlag == 4
3284                     ListOld = BPMlist1;
3285                     XgoalOld = Xgoal;
3286                     YgoalOld = Ygoal;
3287
3288                     % Full BPM list
3289                     List = [
3290                         1 2
3291                         1 5
3292                         1 6
3293                         1 10
3294                         2 1
3295                         2 5
3296                         2 6
3297                         2 9
3298                         3 2
3299                         3 5
3300                         3 6
3301                         3 10
3302                         3 11
3303                         3 12
3304                         4 1
3305                         4 5
3306                         4 6
3307                         4 10
3308                         5 1
3309                         5 5
3310                         5 6
3311                         5 10
3312                         5 11
3313                         5 12
3314                         6 1
3315                         6 5
3316                         6 6
3317                         6 10
3318                         7 1
3319                         7 5
3320                         7 6
3321                         7 10
3322                         8 1
3323                         8 5
3324                         8 6
3325                         8 10
3326                         9 1
3327                         9 5
3328                         9 6
3329                         9 10
3330                         10 1
3331                         10 5
3332                         10 6
3333                         10 10
3334                         10 11
3335                         10 12
3336                         11 1
3337                         11 5
3338                         11 6
3339                         11 10
3340                         12 1
3341                         12 5
3342                         12 6
3343                         12 9
3344                         ];
3345
3346
3347                     CheckList = zeros(size(List,1),1);
3348                     if ~isempty(BPMlist1)
3349                         for i = 1:size(List,1)
3350                             k = find(List(i,1)==BPMlist1(:,1));
3351                             l = find(List(i,2)==BPMlist1(k,2));
3352
3353                             if isempty(k) | isempty(l)
3354                                 % Item not in list
3355                             else
3356                                 CheckList(i) = 1;
3357                             end
3358                         end
3359                     end
3360
3361                     newList = editlist(List, 'BPM', CheckList);
3362                     if isempty(newList)
3363                         fprintf('   BPM list cannot be empty.  No change made.\n');
3364                     else
3365                         BPMlist1 = newList;
3366                     end
3367
3368                     % Set the goal orbit to the golden orbit
3369                     Xgoal = getgolden('BPMx', BPMlist1);
3370                     Ygoal = getgolden('BPMy', BPMlist1);
3371
3372
3373                     % If a new BPM is added, then set the goal orbit to the golden orbit
3374                     for i = 1:size(BPMlist1,1)
3375
3376                         % Is it a new BPM?
3377                         k = find(BPMlist1(i,1)==ListOld(:,1));
3378                         l = find(BPMlist1(i,2)==ListOld(k,2));
3379
3380                         if isempty(k) | isempty(l)
3381                             % New BPM
3382                         else
3383                             % Use the old value for old BPM
3384                             Xgoal(i) = XgoalOld(k(l));
3385                             Ygoal(i) = YgoalOld(k(l));
3386                         end
3387                     end
3388                     OCSx.BPM.DeviceList = BPMlist1;
3389                     OCSy.BPM.DeviceList = BPMlist1;
3390                     OCSx.GoalOrbit = Xgoal;
3391                     OCSy.GoalOrbit = Ygoal;
3392                 end
3393
3394                 if EditFlag == 5
3395                     ChangeList = editlist2(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
3396
3397                     for i = 1:size(ChangeList,1)
3398
3399                         k = find(ChangeList(i,1)==BPMlist1(:,1));
3400                         l = find(ChangeList(i,2)==BPMlist1(k,2));
3401
3402                         prompt={sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
3403                         def={sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
3404                         titlestr='CHANGE THE GOAL ORBIT';
3405                         lineNo=1;
3406                         answer = inputdlg(prompt, titlestr, lineNo, def);
3407
3408                         if isempty(answer)
3409                             % No change
3410                             fprintf('   No change was made to the golden orbit.\n');
3411                         else
3412                             Xgoalnew = str2num(answer{1});
3413                             if isempty(Xgoalnew)
3414                                 fprintf('   No change was made to the horizontal golden orbit.\n');
3415                             else
3416                                 Xgoal(k(l)) = Xgoalnew;
3417                             end
3418
3419                             Ygoalnew = str2num(answer{2});
3420                             if isempty(Ygoalnew)
3421                                 fprintf('   No change was made to the vertical golden orbit.\n');
3422                             else
3423                                 Ygoal(k(l)) = Ygoalnew;
3424                             end
3425                         end
3426                     end
3427                     if ~isempty(ChangeList)
3428                         fprintf('   Note:  Changing the goal orbit for "Slow Orbit Feedback" does not change the goal orbit for "Orbit Correction."\n');
3429                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
3430                     end
3431                     OCSx.GoalOrbit = Xgoal;
3432                     OCSy.GoalOrbit = Ygoal;
3433                 end
3434
3435 %                 if EditFlag == 6
3436 %                     FFTypeFlag = questdlg(sprintf('Do you want to use a fully local or a combined local/global compensation of IDs? (nuy=9.2 only)'),'Tune FF','Local','Global', 'Global');
3437 %                     if strcmp(FFTypeFlag,'Local')
3438 %                         disp(['   The tune FF will use 8 local quadrupoles to compensate beta beating and tune shift']);
3439 %                         disp(['   from each ID.']);
3440 %                     elseif strcmp(FFTypeFlag,'Global')
3441 %                         disp(['   The tune FF will use 4 local quadrupoles to compensate beta beating and all QF+QD']);
3442 %                         disp(['   to compensate tune shift from each ID.']);
3443 %                     end
3444 %                 end
3445
3446             end
3447             close(h_fig1);
3448         end
3449
3450         % Save vectors
3451         FB.Xivec = Xivec;
3452         FB.Yivec = Yivec;
3453         FB.HCMlist1 = HCMlist1;
3454         FB.VCMlist1 = VCMlist1;
3455         FB.BPMlist1 = BPMlist1;
3456
3457         OCSx.SVDIndex = Xivec;
3458         OCSy.SVDIndex = Yivec;
3459         FB.OCSx = OCSx;
3460         FB.OCSy = OCSy;
3461
3462         FB.FFTypeFlag = FFTypeFlag;
3463         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata',FB);
3464
3465
3466     case 'FastFeedbackSetup'
3467
3468         InitFlag = Input2;
3469
3470         if InitFlag
3471             FOFBFreq = 1000;
3472             % user operations 9/14-10/17/04: P=0.5, I=120, D=0.0015 (for both planes)
3473             % below are known good values for user ops as of 8-1-05
3474             HorP = 2;
3475             HorI = 300;
3476             HorD = 0.002;
3477             VertP = 1;
3478             VertI = 100;
3479             VertD = 0.0015;
3480
3481             % this initial set is now done in hwinit.m because it's not a good idea to set anything when srcontrol is launched
3482             % try
3483             %     setsp('SR01____FFBFREQAC00', FOFBFreq); % set freq
3484             %     write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3485             % catch
3486             %     disp('   Trouble setting Fast Orbit Feedback parameters!');
3487             % end
3488
3489         else
3490             % Get vectors
3491             FOFB = get(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata');
3492             FOFBFreq = FOFB.FOFBFreq;
3493             HorP  = FOFB.HorP;
3494             HorI  = FOFB.HorI;
3495             HorD  = FOFB.HorD;
3496             VertP = FOFB.VertP;
3497             VertI = FOFB.VertI;
3498             VertD = FOFB.VertD;
3499
3500             % Add button to change #ivectors, CMs, IDBPMs,
3501             EditFlag = 0;
3502             %h_fig1 = figure;
3503             while EditFlag ~= 3
3504
3505                 %EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'HCM List', 'VCM List', ...
3506                 %   'IDBPM List', 'BBPM List', 'Continue');
3507                 % Use menu below until other FFB config routines work (then also uncomment options 3,4,5,6 below)
3508                 EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'Continue');
3509
3510                 if EditFlag == 1
3511                     % change rate
3512
3513                     prompt={'Enter the desired Fast Feedback Frequency (1-1000 Hz)'};
3514                     def={num2str(FOFBFreq)};
3515                     titlestr='Fast Feedback Setup';
3516                     lineNo=1;
3517                     answer=inputdlg(prompt,titlestr,lineNo,def);
3518                     if ~isempty(answer)
3519                         FOFBFreq = fix(str2num(answer{1}));
3520                         if isempty(FOFBFreq)
3521                             disp('   Frequency value cannot be empty.  No change made.');
3522                             FOFBFreq = getsp('SR01____FFBFREQAC00');
3523                         else
3524                             if FOFBFreq < 1 | FOFBFreq > 1000
3525                                 disp('   Frequency must be between 1 and 1000 Hz.  No change made.');
3526                                 FOFBFreq = getsp('SR01____FFBFREQAC00');
3527                             end
3528                         end
3529                         setsp('SR01____FFBFREQAC00',FOFBFreq); % change freq
3530                         pause(0.5);
3531                         fprintf('   Fast orbit feedback frequency is running at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
3532                     else
3533                         FOFBFreq = getsp('SR01____FFBFREQAC00');
3534                     end
3535                 end
3536
3537                 if EditFlag == 2
3538                     % edit  PIDs
3539                     % User defaults are HorP=2, HorI=300, HorD=0.002, VertP=1, VertI=100, VertD=0.0015
3540                     prompt={'P horizontal', 'I horizontal', 'D horizontal', 'P vertical', 'I vertical', 'D vertical'};
3541                     def={num2str(HorP), num2str(HorI), num2str(HorD), num2str(VertP), num2str(VertI), num2str(VertD)};
3542                     titlestr='Fast Feedback PID Setup';
3543                     lineNo=1;
3544                     answer=inputdlg(prompt,titlestr,lineNo,def);
3545                     if ~isempty(answer)
3546                         HorPnewnum = str2num(answer{1});
3547                         if isempty(HorPnewnum)
3548                             disp('   HorP value cannot be empty.  No change made.');
3549                         else
3550                             HorP = HorPnewnum;
3551                         end
3552                         HorInewnum = str2num(answer{2});
3553                         if isempty(HorInewnum)
3554                             disp('   HorI value cannot be empty.  No change made.');
3555                         else
3556                             HorI = HorInewnum;
3557                         end
3558                         HorDnewnum = str2num(answer{3});
3559                         if isempty(HorDnewnum)
3560                             disp('   HorD value cannot be empty.  No change made.');
3561                         else
3562                             HorD = HorDnewnum;
3563                         end
3564                         VertPnewnum = str2num(answer{4});
3565                         if isempty(VertPnewnum)
3566                             disp('   VertP value cannot be empty.  No change made.');
3567                         else
3568                             VertP = VertPnewnum;
3569                         end
3570                         VertInewnum = str2num(answer{5});
3571                         if isempty(VertInewnum)
3572                             disp('   VertI value cannot be empty.  No change made.');
3573                         else
3574                             VertI = VertInewnum;
3575                         end
3576                         VertDnewnum = str2num(answer{6});
3577                         if isempty(VertDnewnum)
3578                             disp('   VertD value cannot be empty.  No change made.');
3579                         else
3580                             VertD = VertDnewnum;
3581                         end
3582
3583                         try
3584                             write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3585                             fprintf('   Setting FFB gains to Horizontal P=%.2f, I=%.1f, D=%.4f;  Vertical P=%.2f, I=%.1f, D=%.4f\n', HorP, HorI, HorD, VertP, VertI, VertD);
3586                         catch
3587                             disp('   Trouble setting Fast Orbit Feedback parameters!');
3588                         end
3589                     end
3590                 end
3591
3592                 %if EditFlag == 3
3593                 %   disp('   This function not yet available.');
3594                 %   % change HCM List
3595                 %end
3596                 %
3597                 %if EditFlag == 4
3598                 %   disp('   This function not yet available.');
3599                 %   % change VCM List
3600                 %end
3601                 %
3602                 %if EditFlag == 5
3603                 %   disp('   This function not yet available.');
3604                 %   % change IDBPM List
3605                 %end
3606                 %
3607                 %if EditFlag == 6
3608                 %   disp('   This function not yet available.');
3609                 %   % change BBPM List
3610                 %end
3611
3612             end
3613             %close(h_fig1);
3614         end
3615
3616         % Save vectors
3617         FOFB.FOFBFreq = FOFBFreq;
3618         FOFB.HorP = HorP;
3619         FOFB.HorI = HorI;
3620         FOFB.HorD = HorD;
3621         FOFB.VertP = VertP;
3622         FOFB.VertI = VertI;
3623         FOFB.VertD = VertD;
3624         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata',FOFB);
3625
3626     otherwise
3627         fprintf('   No action for %s.\n', action);
3628 end   % end case