Description of srcontrol5
Home > ALS > StorageRing > srcontrol5.m
srcontrol5
PURPOSE
srcontrol5
SYNOPSIS
function srcontrol5(action, Input2, Input3)
DESCRIPTION
 srcontrol5
 Storage ring control program
 This program controls all storage ring magnets, performs orbit feedback and
 tune feedforward and helps to diagnose problems in routine user operation
 of the ALS storage ring. It includes a gui to simplify the use of this
 program.
 It was originally programmed by Greg Portmann (until December 2000) with input
 from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
 and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
 The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
 Christoph Steier, July 2002
 SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
 Tom Scarvie, April 2005
CROSS-REFERENCE INFORMATION
This function calls:
amp2k AMP2K - Converts amperes to simulator values
bend2gev BEND2GEV - Compute the energy based on the ramp tables
checksrmags CHECKSRMAGS - Check SR power supplies against a lattice file
checksrorbit ErrorNums =checksrorbit(Sector, BPMxtolerance [.015 mm], [BPMytolerance [.015 mm]])
gap2tune GAP2TUNE - Computes the vertical tune shift for a insertion device gap change.
gaplimit [GapMin, GapMax] = gaplimit(ID_Number);
getbpmlist GETBPMLIST - Return a BPM list based on key words and sector numbers
getbpmtimeconstant GETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
getff function [FFEnableBM, FFEnableBC, GapEnableBM, GapEnableBC, Sector] = getff(Sector)
getid GETID - Get the insertion device position, velocity, run flag, and user requested gap
getsrstate [StateNumber, StateString] = getsrstate
ocsinit OCSINIT - Corrector and BPM
set_alarmhandler_AHU_thresholds_inject function set_alarmhandler_AHU_thresholds_inject
set_alarmhandler_thresholds set_alarmhandler_thresholds
set_alarmhandler_thresholds_new set_alarmhandler_thresholds_new
set_etaywave_nuy9_20skews_skewFF function [SQSFincr, SQSDincr] = set_etaywave_nuy9_20skews_skewFF(scale);
setbpmtimeconstant SETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
setbumps SETBUMPS - Make a straight section bump
setff function setff(Sector, FFEnableBC, GapEnableBC)
setid SETID - Set the insertion device vertical gap
setsrstatechannels
srcycle SRCYCLE - Storage ring cycle
srramp SRRAMP - Ramp the storage ring energy
write_goldenorbit_ffb function write_goldenorbit_ffb
write_goldenorbit_ffb_2planes WRITE_GOLDENORBIT_FFTB_2PLANES - Sets the BPM setpoints which are used by the fast feedback system
This function is called by:
srcontrol Launch program for the default srcontrol version
SOURCE CODE
function srcontrol5(action, Input2, Input3)
% srcontrol5
% Storage ring control program
%
% This program controls all storage ring magnets, performs orbit feedback and
% tune feedforward and helps to diagnose problems in routine user operation
% of the ALS storage ring. It includes a gui to simplify the use of this
% program.
%
% It was originally programmed by Greg Portmann (until December 2000) with input
% from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
% and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
%
% The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
%
% Christoph Steier, July 2002
%
% SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
%
% Tom Scarvie, April 2005
% known bugs/problems (May 2001):
% - IDBPM averaging might be a bit too long for orbit feedback
%        solved after Superbend shutdown ... Instead of averaging, digital low pass filters are used
% - gap2tune does not give correct answers for wiggler and potentially other IDs -> orbit feedback
%        seems to be OK for other IDs, has been corrected for wiggler (fit to insertion device
%        compensation table)
% - chicanes do not work in orbit feedback
%        solved. One problem was that orbit response matrizes were mis-scaled by factor of two.
%        Second problem was different time constant of power supply control. Solved by moving controls
%        of center chicanes to cPCI (and magnets are fast, hysteresis free, aircore coils).
%        Center chicane in sector 4 is now routinely used in orbit feedback. Sector 11 to follow soon.
% - zero reading of ID gap dumps beam
%        solved in srcontrol5, still a problem in srcontrol5_hightune (but that routine has to be completely
%        rewritten because of all recent changes to srcontrol5, anyhow). For gap readings below the minimum
%        allowed gap for a device, the tune feedforward disables itself.
% - cycling of lattice causes frequent power supply failures
%        solved by changing the cycling procedure. 1.5 GeV operation is now on the upper hysteresis branch
%        as was the 1.9 GeV injection lattice before.
% - frequently stalled data in IDBPM readout
%        solved with new BPM readouts and digital filtering. Seems to have been a resolution problem
%        of the digital averaging algorithm.
% - magnet ramp tables are not in perfect agreement with magnetic measurements
%        Does not appear to be a serious problem. Superbends are slightly out of sync with other magnets,
%        but this does not cause any negative effects while ramping.
% - no good way to operate with injection at 1.5 GeV and storage energy below that
%        There now is a reasonable way to inject at 1.5 GeV and ramp down to lower storage energy. But
%        it has to be tested again after implementing new (and more) chicanes ...
% revision history
% 2001-05-10, Christoph Steier
% check whether readback from insertion device is significantly (more than 1 mm) below minimum
% gap, to avoid false zero readings of insertion device gaps to cause the tune feed forward
% to implement false huge correction (and dump the beam). If the insertion device gap readbacks
% gets more than 1 mm below the nominal minimum gap, the routine now assumes the insertion device
% to be open.
%
% 2001-08-30 and during Superbend commissioning, Christoph Steier, Tom Scarvie, Winni Decking
% various changes have been made to incorporate the Superbends and some other new equipment
% installed in the Superbend shutdown. This included some changes to programs being called by srcontrol
% (like srload, srsave, srcycle, srramp, ...). The main changes within srcontrol were in the orbit
% correction and slow orbit feedback routines (incorporating frequency feedback, ...)
%
% 2002-05-04, Christoph Steier
% added new IDBPMs, modified orbit feedback to use trim DACs, removed LSB toggling in vertical
% orbit feedback, ...
%
% 2002-07-29, T.Scarvie
% added check of CM trim currents to warn of problems that might rail the orbit feedback
%
% 2002-07-31, Christoph Steier
% increased the gain of the RF frequency feedback from 1/50 of the gain of the horizontal
% orbit feedback to 1/20. Reason was that the frequency feedback was reacting a bit too slow if all
% insertion device gaps are closed at once at high speed at the beginning of a fill.
%
% 2002-08-05, C.Steier, T.Scarvie
% Added conditional to reduce orbit feedback gain if running in two-bunch mode
%
% 2003-06-02, T.Scarvie
% Added loop inside orbit feedback to reset the SR11 chicane M1 and M2 motors every 20s to combat drift problem
%
% 2003-06-18, C. Steier
% Disabled loop to periodically reset chicane in SR11. Al Robb replaced power supply, seems to be no problem anymore.
%
% 2004-05-10, C. Steier
% The list of all BBPMs is now set up automatically be calling getlist('BBPMx'). This way, new BBPMs have to be added
% at fewer places in the software. It should now be sufficient to modify getlist and run the orbit response matrix
% rountine (getsmat) once to enable use of the new BBPMs.
%
% 2004-05-14, C. Steier
% Modified parameters for ramprate reduction (in srramp and here). Previous parameters were slightly too
% cautious. Increased initial slow ramprate to 0.4 A/s.
%
% 2004-05-14, C. Steier
% Incorporated insertion device compensation schemes for nu_y = 9.2 lattice.
%
% 2004-06-14, T.Scarvie
% Added controls for fast orbit feedback
%
% 2004-06-21, C. Steier
% Added tune feedforward (in the global tune compensation scheme for the nu_y=9.2 lattice) for the shift
% dependent tune shift of the EPUs, as well as a skew quadrupole feedforward for the EPU im sector 11
% (both only active in parallel mode so far).
%
% 2005-02-13, T.Scarvie
% Separated horizontal and vertical planes for setting Fast Feedback PIDs
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NOTES for conversion to new Middle Layer %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% We never use the gap and bump control flags - the radio buttons have been disabled -
%        should we try to keep the functionality?
%
% checksrmags
% checksrorbit(...)
% For the compiler
%#function goldenpage
%#function setoperationalmode
% Check if the AO exists
checkforao;
%%%%%%%%%%%%%%
% Initialize %
%%%%%%%%%%%%%%
global FEEDBACK_STOP_FLAG
SR_Mode = getfamilydata('OperationalMode');
SR_GEV = getfamilydata('Energy');
BSCramprate = getfamilydata('BSCRampRate');
if isnan(BSCramprate) || isempty(BSCramprate)
    BSCramprate = 0.4;
    setfamilydata(BSCramprate, 'BSCRampRate');
end
if nargin < 1
    action = 'Initialize';
end
if nargin < 2
    Input2 = 0;
end
if nargin < 3
    Input3 = 0;
end
if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
    FOFBcheckboxVal = 0;
else
    FOFBcheckboxVal = 1;
end
%%%%%%%%%%%%%%%%
% Main Program %
%%%%%%%%%%%%%%%%
switch(action)
    case 'StopOrbitFeedback'
        FEEDBACK_STOP_FLAG = 1;
    case 'Initialize'
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % GUI
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        ButtonWidth = 200;
        ButtonHeight  = 25;
        Offset1 = 8*25+12 + 47 + 25+25;
        Offset2 = 47+25+25;
        Offset3 = 45+25;
        Offset4 = 1;
        Offset5 = 30;
        FigWidth = ButtonWidth+6;
        FigHeight  = 3+9*(ButtonHeight+6)+24+Offset1;
        ButtonWidth = 200-6;
        % Change figure position
        set(0,'Units','pixels');
        p=get(0,'screensize');
        h0 = figure( ...
            'Color',[0.8 0.8 0.8], ...
            'HandleVisibility','Off', ...
            'Interruptible', 'on', ...
            'MenuBar','none', ...
            'Name','ALS SR CONTROL', ...
            'NumberTitle','off', ...
            'Units','pixels', ...
            'Position',[30 p(4)-FigHeight-40 FigWidth FigHeight+Offset5], ...
            'Resize','off', ...
            'Tag','SRCTRLFig1');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'FontWeight','Bold', ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+8*(ButtonHeight+3)+19+19+8+Offset1  ButtonWidth 20+Offset5], ...
            'Style','text', ...
            'String','', ...
            'Tag','SRCTRLTitle');
        % Frame Box I
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+3*(ButtonHeight+3)+Offset1-3+Offset5 ButtonWidth+6 7*ButtonHeight+18], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+9*(ButtonHeight+3)+Offset1  ButtonWidth 15+Offset5], ...
            'Style','text', ...
            'String','Lattice Setup Functions');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Cycle'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+8*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Cycle SR Lattice', ...
            'Tag','SRCTRLButton1');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Injection'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+7*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Injection', ...
            'Tag','SRCTRLButton2');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Production'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+6*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String',['Production'], ...
            'Tag','SRCTRLButton3');
        h1 = uicontrol('Parent',h0, ...
            'Callback',[...
            'fprintf(''\n'');' ...
            'disp([''   **********************************************'']);', ...
            'disp([''   **  Changing Storage Ring Operational Mode  **'']);', ...
            'disp([''   **********************************************'']);', ...
            'setoperationalmode;', ...
            'srcontrol5(''CheckInputs'');', ...
            'disp([''   ****************************'']);', ...
            'disp([''   **  Mode Change Complete  **'']);', ...
            'disp([''   ****************************'']);', ...
            'fprintf(''\n'');'], ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+5*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'Value',1, ...
            'String','Change Operational Mode', ...
            'Tag','SRCTRLButtonChangeMode');
        h1 = uicontrol(...
            'Parent',h0, ...
            'Callback', [...
            'srcontrol5(''CheckInputs'');',...
            'srcontrol5(''SRState'');'], ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+4*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Check For Problems', ...
            'Tag','SRCTRLButtonSRState');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs''); goldenpage;', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+3*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Golden Page', ...
            'Tag','SRCTRLButtonGoldenPage');
        % Frame Box II
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+9*(ButtonHeight+3)-29+Offset2+Offset5 ButtonWidth+6 2*ButtonHeight+15], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+10*(ButtonHeight+3)-10+Offset2 ButtonWidth .6*ButtonHeight+Offset5], ...
            'String','Global/Local Orbit Correction', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''OrbitCorrection'');', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+9*(ButtonHeight+3)-6+Offset2+Offset5 ButtonWidth ButtonHeight], ...
            'String','Correct Global Orbit w/ IDBPMs', ...
            'Tag','SRCTRLButtonOrbitCorrection');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''OrbitCorrectionSetup'',1);', ...
            'callback','srcontrol5(''OrbitCorrectionSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[6 9*(ButtonHeight+3)-22+Offset2+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Edit IDBPM, CM, & Local Bump Lists', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonOrbitCorrectionSetup');
        % Frame Box III
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 1*(ButtonHeight)+Offset3+Offset5-38 ButtonWidth+6 8*ButtonHeight+61], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+9*(ButtonHeight+3)+Offset3-25 ButtonWidth .55*ButtonHeight+Offset5], ...
            'String','Orbit Feedback', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+8*(ButtonHeight+3)+Offset3-18+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Slow Orbit Correction', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxSOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+7*(ButtonHeight+3)+Offset3-9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Fast Orbit Correction', ...
            'Style','checkbox', ...
            'Value',FOFBcheckboxVal,...
            'Tag','SRCTRLCheckboxFOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+6*(ButtonHeight+3)+Offset3+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct ID Tune Shift  ', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxTune');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+5*(ButtonHeight+3)+Offset3+9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct RF Frequency', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxRF');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''Feedback'');', ...
            'Enable','on', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[8 3+5*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Start FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStart');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''StopOrbitFeedback'');pause(0);', ...
            'Enable','off', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[.5*FigWidth+3 3+5*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Stop FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStop');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[14 4*(ButtonHeight)+Offset3+Offset5-3 ButtonWidth-14 .75*ButtonHeight], ...
            'String','Horizontal RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHorizontal');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[26 3+3.5*(ButtonHeight)+16+Offset3-25+Offset5 ButtonWidth-26 .75*ButtonHeight], ...
            'String','Vertical RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextVertical');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FeedbackSetup'',1);', ...
            'callback','srcontrol5(''FeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 3+3.5*(ButtonHeight)+.5+Offset3-25+Offset5 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit SOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFeedbackSetup');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','01 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB01');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','02 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB02');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','03 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB03');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','04 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB04');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','05 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB05');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','06 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB06');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','07 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB07');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','08 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB08');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','09 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB09');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','10 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB10');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','11 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB11');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','12 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB12');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FastFeedbackSetup'',1);', ...
            'callback','srcontrol5(''FastFeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 1*(ButtonHeight)+Offset3-3 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit FOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFastFeedbackSetup');
        % Frame Box IV
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+ButtonHeight+Offset4-14+Offset5 ButtonWidth+6 ButtonHeight+12], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+1.75*ButtonHeight+5+Offset4-21+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Storage Ring State', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHeader');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''CheckInputs'');', ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ForegroundColor','b', ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+ButtonHeight+6+3+2+Offset4-22+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','   ', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextInformation');
        % Frame Box "Close"
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 8 ButtonWidth+6 ButtonHeight+8], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'Callback','close(gcbf);', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 13 ButtonWidth ButtonHeight], ...
            'String','Close', ...
            'Tag','SRCTRLClose');
        % Update database channels
        setsrstatechannels;
        if nargout > 0
            fig = h0;
        end
    case 'Cycle'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        disp('   **************************');
        disp('   **  Storage Ring Cycle  **');
        disp('   **************************');
        a = clock; fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        BSCFlag = questdlg(sprintf('Cycle Superbend Magnets?'),'SR Cycle','Yes','No','No');
        %if strcmp(BSCFlag,'No')
        %    disp(['   ** Superbends will not be cycled. **']);
        %else
        %    disp(['   ** Superbends will be cycled during the second mini-cycle only. **']);
        %end
        ChicSQFlag = questdlg(sprintf('Cycle chicanes and skew quads and home motor chicanes?'),'SR Cycle','Yes','No','No');
        %if strcmp(ChicSQFlag,'No')
        %    disp(['   ** Chicanes and skew quads will not be cycled; motor chicanes will not be homed. **']);
        %else
        %    disp(['   ** Chicanes and skew quads will be cycled; motor chicanes will be homed. **']);
        %end
        StartFlag = questdlg(sprintf('Start %.1f GeV Cycle?',SR_GEV),'SR Cycle','Yes','No','No');
        if strcmp(StartFlag,'No')
            disp(['   ***************************']);
            disp(['   **    Cycle  Canceled    **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        end
        try
            if GapFlag
                % Make sure that the gaps are open with FF off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open.');
                    disp('   Opening all gaps at maximum speed.');
                    setff([], 1, 0);
                    disp('   Gap control disabled.');
                    disp('   Feed forward enabled.');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened.');
                    disp('   Feed forward and gap control disabled.');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled.');
                end
            else
                disp('   Feed forward and gap control disabled.');
            end
            setff([], 0, 0);
            pause(1);
            srcycle(BSCFlag, ChicSQFlag);
            setpv('SR_STATE',1);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Cycle failed due to error condition! \n\n');
            setpv('SR_STATE',-1);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp('   **********************************************');
            disp('   **  SR Cycle complete, ready for injection  **');
            disp('   **********************************************'); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp('   **********************************');
            disp('   **  Problem cycling SR lattice  **');
            disp('   **********************************'); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
    case 'Injection'
        AD = getad;
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            fprintf('   ***************************************************\n');
            fprintf('   **  Setup For %.2f GeV Injection (with ramping)  **\n', getfamilydata('InjectionEnergy'));
            fprintf('   ***************************************************\n');
            set_alarmhandler_AHU_thresholds_inject;
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',getfamilydata('InjectionEnergy')),'Injection Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            fprintf('   *************************************************\n');
            fprintf('   **  Setup For On Energy Injection at %.2f GeV  **\n', SR_GEV);
            fprintf('   *************************************************\n');
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',SR_GEV),'Injection Setup','Yes','Cancel','Cancel');
        end
        if strcmp(StartFlag,'Cancel')
            disp(['   ********************************']);
            disp(['   **  Injection Setup Canceled  **']);
            disp(['   ********************************']);
            set_alarmhandler_thresholds;
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                setff([],1,0);
                disp('   Gap control disabled');
                disp('   Feed forward enabled');
                pause(1);
                % Set IDs at max velocity w/ velocity profile off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    disp('   Opening all gaps');
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                end
                disp('   Gaps are open');
                disp('   Feed forward and gap control disabled');
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            if (AD.Energy-AD.InjectionEnergy) > 0.05
                % Ramp down to Injection Energy
                set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String','Ramping Down','ForegroundColor','b');
                drawnow;
                ErrorFlag = srramp('Injection');
                if ErrorFlag
                    error('Superbends over temperature.');
                end
                a = clock; fprintf('   %s %d:%d:%.0f\n\n',date, a(4), a(5), a(6));
            elseif (AD.Energy-AD.InjectionEnergy) < -0.05
                % first load injection lattice, then ramp to 1.9 GeV and back to 1.5 GeV to get onto same hysteresis branch
                srload('Injection');
                % load 1.9 GeV lattice
                tempfilename = sprintf('%s19nuy9prod.mat', getfamilydata('Directory','OpsData'));
                srload(tempfilename);
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                pause(5);
            end
            srload('Injection');
            setpv('SR_STATE',2);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Injection lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-2);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            if AD.Energy <= 1.5
                disp(['   *******************************************************************************']);
                disp(['   **  Function complete:  the storage ring is setup for injection at ',sprintf('%.2f',SR_GEV),' GeV  **']);
                disp(['   *******************************************************************************']);
                fprintf('\n');
            else
                fprintf('   **********************************************************************************************\n');
                fprintf('   **  Function complete:  the storage ring is setup for injection at %.2f GeV (upper branch)  **\n', getfamilydata('InjectionEnergy'));
                fprintf('   **********************************************************************************************\n');
                fprintf('\n');
            end
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   ************************************']);
            disp(['   **  Problem with injection setup  **']);
            disp(['   ************************************']);
            fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        %soundchord;
        setfamilydata(0.8, 'BSCRampRate');
    case 'Production'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        AD=getad;
        fprintf('\n');
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            disp('   ********************************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation (with ramping)  **',SR_GEV));
            disp('   ********************************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            disp('   *****************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation  **',SR_GEV));
            disp('   *****************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Yes','Cancel','Cancel');
        end
        if strcmp(StartFlag,'Cancel')
            disp(['   ***************************']);
            disp(['   **  User Setup Canceled  **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                % Make sure that the gaps are open
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open');
                    disp('   Opening all gaps at maximum speed');
                    setff([], 1, 0);
                    disp('   Gap control disabled');
                    disp('   Feed forward enabled');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened');
                    disp('   Feed forward and gap control disabled');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled');
                end
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            % Ramp up to the production lattice
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String','Ramping Up','ForegroundColor','b');
            drawnow;
            ErrorFlag = srramp('Production');
            if ErrorFlag
                error('Superbends over temperature.');
            end
            a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            srload('Production');
            if GapFlag
                setff([], 1, 0);
                disp('   Gap control disabled');
                disp('   Feed forward enable');
                pause(1);
                disp('   Insertion device velocity profile boolean control off');
                disp('   Closing all gaps at maximum speed');
                % Set IDs at max velocity w/ velocity profile off
                [Position, Velocity, RunFlag, UserGap] = getid;
                setid([], UserGap, maxsp('IDvel'), 1, 0, 1);
                % Turn velocity profile on
                disp('   Insertion device velocity profile boolean control is on');
                setid([], [], maxsp('IDvel'), 1, 1, 0);
                disp('   Gaps are closed');
                setff([4;7;8;9;10;12], 1, 1);
                setff(5, 1, 0);
                disp('   Gap control enabled (except sector 5 (W16))');
            end
            set_alarmhandler_thresholds_new;
            setpv('SR_STATE',3);
        catch
            fprintf('   %s \n', lasterr);
            fprintf('   User lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-3);
        end
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp(['   **************************************************************************']);
            disp(['   **  Function complete:  the storage ring is setup for users at ',sprintf('%.1f',SR_GEV),' GeV  **']);
            disp(['   **************************************************************************']); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   *************************************']);
            disp(['   **  Problem with production setup  **']);
            disp(['   *************************************']); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        setfamilydata(0.8, 'BSCRampRate');
%         % for BL6.0.x, set lower setpoint limit for IVID to 12.5mm until beamlines are surveyed below that value
%         try
%             scaput('SR06U___GDS1PS_AC00.DRVL',12.5);
%             disp('  Setting SR06U___GDS1PS_AC00.DRVL to 12.5mm (lower limit for IVID');
%         catch
%             disp('  Trouble setting lower limit for IVID to 12.5mm!');
%         end
    case 'CheckInputs'
        SR_GEV = getfamilydata('Energy');
        AD=getad;
        setsrstatechannels;
        set(0,'showhiddenhandles','on');
        if AD.Energy > 1.55
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Down)']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users (Ramp Up)']);
        elseif AD.Energy < 1.45
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Up+cycle)']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV (Ramp Down)']);
        else
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV']);
        end
        set(findobj('Tag','SRCTRLTitle'),'String',SR_Mode);
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
        else
            set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
        end
        set(0,'showhiddenhandles','off');
    case 'SRState'
        NumErrors = 0;
        fprintf('\n');
1000         disp('   ***********************************');
1001         disp('   **  Checking Storage Ring State  **');
1002         disp('   ***********************************');
1003         a = clock;
1004         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1005
1006         %       FileName = getpv('SR_LATTICE_FILE','String');   % Last srload file name (in OLD MIDDLE LAYER nomenclature!!)
1007
1008         GeVnow = bend2gev;
1009         if GeVnow == getfamilydata('Energy')
1010             [ConfigSetpoint, ConfigMonitor, FileName] = getproductionlattice;
1011         elseif GeVnow == getfamilydata('InjectionEnergy')
1012             [ConfigSetpoint, ConfigMonitor, FileName] = getinjectionlattice;
1013         else
1014             FileName = '';
1015         end
1016
1017         [StateNumber, StateString] = getsrstate;
1018         fprintf('   Storage ring operational mode: %s\n', SR_Mode);
1019         if StateNumber < 0
1020             fprintf('   Storage ring state error: %s\n', StateString);
1021             NumErrors = NumErrors + 1;
1022         else
1023             fprintf('   Storage ring state: %s\n', StateString);
1024         end
1025         if StateNumber==0
1026             % Storage ring state unknown
1027             NumErrors = NumErrors + 1;
1028         elseif abs(StateNumber)==1 || abs(StateNumber)==2
1029             FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','InjectionFile') '.mat'];
1030             if ~strcmp(FileName, FileNameGoal)
1031                 fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','InjectionFile'), FileName);
1032                 NumErrors = NumErrors + 1;
1033             end
1034         else
1035             FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile') '.mat'];
1036             if ~strcmp(FileName, FileNameGoal)
1037                 fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','LatticeFile'), FileName);
1038                 NumErrors = NumErrors + 1;
1039             end
1040         end
1041
1042
1043         % Check all SR magnets
1044         if isempty(FileName)
1045             fprintf('   Goal setpoints will not be checked since the last lattice load is unknown.\n');
1046             NumErrors1 = checksrmags('');
1047         else
1048 %            NumErrors1 = checksrmags([getfamilydata('Directory','OpsData') FileName]);
1049             NumErrors1 = checksrmags(FileName);
1050         end
1051         if NumErrors1 == 0
1052             fprintf('   SR magnets power supplies are OK.\n');
1053         end
1054         NumErrors = NumErrors + NumErrors1;
1055
1056
1057         % Check RF frequency
1058         if isempty(FileName)
1059             fprintf('   RF frequency will not be checked since the last lattice load is unknown.\n');
1060         else
1061 %            load([getfamilydata('Directory','OpsData'), FileName]);
1062             load(FileName);
1063             [tmp, RFHPCounterPresent] = getrf;
1064             if abs(RFHPCounterPresent-ConfigSetpoint.RF.Setpoint.Data) > .002
1065                 NumErrors = NumErrors + 1;
1066                 fprintf('   RF frequency should be %f, presently it is %f MHz (as measured by the HP counter).\n', ConfigSetpoint.RF.Setpoint.Data, RFHPCounterPresent);
1067             else
1068                 fprintf('   RF frequency is OK (HP counter is %f MHz, at the time of the lattice save it was %f MHz).\n', RFHPCounterPresent, ConfigSetpoint.RF.Setpoint.Data);
1069             end
1070         end
1071
1072
1073         % Check for orbit problems
1074         if (StateNumber >= 3) && (getdcct > 2)   % Production lattice is loaded with beam in the machine
1075             Xtol = 0.070;
1076             Ytol = 0.010;
1077             NumErrors1 = checksrorbit([],Xtol,Ytol);
1078             if NumErrors1
1079                 fprintf('   SR orbit in the ID straight sections or at Bergoz BPMs deviates more than allowed from the golden orbit.\n');
1080             else
1081                 fprintf('   SR orbit in the ID straight sections and at Bergoz BPMs is OK.\n');
1082                 fprintf('   The orbit is within %.3f mm horizontally and %.3f mm vertically', Xtol, Ytol);
1083             end
1084             NumErrors = NumErrors + NumErrors1;
1085         else
1086             fprintf('   Storage ring orbit was not checked.\n');
1087         end
1088
1089
1090         a = clock;
1091         datestr1=date;
1092         fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
1093         if NumErrors
1094             disp('   *********************************');
1095             disp('   **  Storage Ring Has Problems  **');
1096             disp('   *********************************');
1097         else
1098             disp('   **********************************');
1099             disp('   **  Storage Ring Lattice is OK  **');
1100             disp('   **********************************');
1101         end
1102         fprintf('   \n');
1103
1104         set(0,'showhiddenhandles','on');
1105         [StateNumber, StateString] = getsrstate;
1106         if StateNumber >= 0
1107             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1108         else
1109             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1110         end
1111         set(0,'showhiddenhandles','off');
1112
1113
1114     case 'OrbitCorrection'
1115         fprintf('\n');
1116         fprintf('   *********************************\n');
1117         fprintf('   **  Starting Orbit Correction  **\n');
1118         fprintf('   *********************************\n');
1119         a = clock;
1120         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1121
1122         StartFlag = questdlg(sprintf('Start orbit correction, %.1f GeV?',SR_GEV),'Orbit Correction','Yes','No','No');
1123         if strcmp(StartFlag,'No')
1124             disp(['   ********************************']);
1125             disp(['   **  Orbit Correction Aborted  **']);
1126             disp(['   ********************************']);
1127             fprintf('\n');
1128             return
1129         end
1130
1131         if getdcct < 5     % Don't correct the orbit if the current is too small
1132             fprintf('   Orbit not corrected due to small current.\n');
1133             return
1134         end
1135
1136         if abs(SR_GEV-bend2gev(getpv('BEND',[1 1])))>  0.05     % Don't use this routine for the injection lattice
1137             fprintf('   This routine should only be used for the production energy: Correction aborted\n');
1138             return
1139         end
1140
1141         SR_STATE_OLD = scaget('SR_STATE');
1142         set(0,'showhiddenhandles','on');
1143         setpv('SR_STATE',4);
1144         [StateNumber, StateString] = getsrstate;
1145         if StateNumber >= 0
1146             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1147         else
1148             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1149         end
1150         set(0,'showhiddenhandles','off');
1151
1152
1153         try
1154             % save current BPM timeconstant - will reset to this after correction
1155             BPMtimeconstantOC = getbpmtimeconstant;
1156             fprintf('   Current Bergoz BPM time constant is %.1fs\n', BPMtimeconstantOC);
1157
1158             % 2 Hz update rate on IDBPMs
1159             disp('   Bergoz BPM time constant set to 0.5s.')
1160             setbpmtimeconstant(0.5)
1161             pause(2);
1162
1163
1164             % Turn off feed forward
1165             fprintf('   Turning feed forward off.\n');
1166             [FFEnableBM, FFEnableBC] = getff;
1167             setff([], 0);
1168             scasleep(.2);
1169
1170
1171             % Get vectors
1172             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1173             LocalBumplist = FB.LocalBumplist;
1174
1175         catch
1176
1177             fprintf('   %s \n',lasterr);
1178             fprintf('   Orbit correction setup failed due to error condition! \n\n');
1179             setpv('SR_STATE',-4);
1180             set(0,'showhiddenhandles','on');
1181             [StateNumber, StateString] = getsrstate;
1182             if StateNumber >= 0
1183                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1184             else
1185                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1186             end
1187             set(0,'showhiddenhandles','off');
1188
1189             % Reset BPM timeconstant to whatever it was before correction
1190             setbpmtimeconstant(BPMtimeconstantOC);
1191             fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1192             return
1193         end
1194
1195         iNotHCMChicane = find(FB.HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
1196         iHCMChicane = find(FB.HCMlist1(:,2) == 10);
1197         iNotVCMChicane = find(FB.VCMlist1(:,2) < 10);
1198         iVCMChicane = find(FB.VCMlist1(:,2) == 10);
1199
1200         fprintf('   Starting horizontal and vertical global orbit correction (SVD method).\n');
1201
1202         for iloop = 1:3
1203             try
1204                 % use the following to get corrector settings in OCS without setting them, so the values can be checked
1205                 FB.OCSx = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
1206                 FB.OCSy = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
1207                 if any(abs(FB.OCSx.CM.Delta(iNotHCMChicane)) > 5)
1208                   disp('   Orbit Correction is changing some horizontal corrector(s) > 5A!!');
1209                 end
1210                 if any(abs(FB.OCSy.CM.Delta(iNotVCMChicane)) > 5)
1211                   disp('   Orbit Correction is changing some vertical corrector(s) > 5A!!');
1212                 end
1213                 if any(abs(FB.OCSx.CM.Delta(iHCMChicane)) > 10)
1214                   disp('   Orbit Correction is changing some horizontal chicane corrector(s) > 10A!!');
1215                 end
1216                 if any(abs(FB.OCSy.CM.Delta(iVCMChicane)) > 10)
1217                   disp('   Orbit Correction is changing some vertical chicane corrector(s) > 10A!!');
1218                 end
1219
1220
1221                 % Correct horizontal orbit
1222                 FB.OCSx = setorbit(FB.OCSx,'NoDisplay');
1223                 % Correct vertical orbit
1224                 FB.OCSy = setorbit(FB.OCSy,'NoDisplay');
1225
1226
1227                 % Check for current in machine - stop orbit correction if DCCT < 5mA
1228                 if (getdcct < 4.5)
1229                     error('**There is less than 5mA in the machine! Stopping orbit correction.');
1230                 end
1231
1232                 % Check state of gaps - stop orbit correction if any are moving
1233                 GAPrunflag = getpv('ID','RunFlag');
1234                 if any(GAPrunflag-round(GAPrunflag))
1235                     error('**One or more of the gaps are moving! Stopping orbit correction.');
1236                 end
1237
1238                 x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
1239                 y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
1240                 fprintf('   %d. Horizontal RMS = %.3f mm\n', iloop, norm(x)/sqrt(length(x)));
1241                 fprintf('   %d.   Vertical RMS = %.3f mm\n', iloop, norm(y)/sqrt(length(y)));
1242
1243             catch
1244                 % fprintf('   %s \n',lasterr);
1245                 fprintf('   Orbit correction failed due to error condition!\n  Fix the problem, reload the lattice (srload), and try again.  \n\n');
1246                 setpv('SR_STATE',-4);
1247                 set(0,'showhiddenhandles','on');
1248                 [StateNumber, StateString] = getsrstate;
1249                 if StateNumber >= 0
1250                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1251                 else
1252                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1253                 end
1254                 set(0,'showhiddenhandles','off');
1255
1256                 % Reset BPM timeconstant to whatever it was before correction
1257                 setbpmtimeconstant(BPMtimeconstantOC);
1258                 fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1259                 return
1260             end
1261         end
1262
1263
1264         % Set user bumps w/o sextupole correctors
1265         try
1266
1267             %turn up corrector speed here to quicken setting bumps
1268             HCMramprate = getpv('HCM', 'RampRate');
1269             VCMramprate = getpv('VCM', 'RampRate');
1270             setpv('HCM', 'RampRate', 10, [], 0);
1271             setpv('VCM', 'RampRate', 10, [], 0);
1272
1273             if ~isempty(LocalBumplist)
1274                 fprintf('   Setting local bumps in the straight sections.\n');
1275                 for loop = 1:size(LocalBumplist,1)
1276
1277                     % Check for current in machine - stop orbit correction if DCCT < 5mA
1278                     if (getdcct < 5)
1279                         error('** There is less than 5mA in the machine! Stopping local bumps.');
1280                     end
1281
1282                     % Check state of gaps - stop setting bumps if any are moving
1283                     GAPrunflag = getpv('ID','RunFlag');
1284                     if any(GAPrunflag-round(GAPrunflag))
1285                         error('** One or more of the gaps are moving! Stopping local bumps.');
1286                     end
1287
1288                     HCMoldsp = getsp('HCM', FB.HCMlist1);
1289                     VCMoldsp = getsp('VCM', FB.VCMlist1);
1290
1291                     if any(LocalBumplist(loop,1) == [4 6 11])
1292                         if LocalBumplist(loop,2) == 0
1293                             % Upstream bump
1294                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1295                             if isempty(iRemove)
1296                                 setbumps(LocalBumplist(loop,:), 1);
1297                             else
1298                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1299                             end
1300                         elseif LocalBumplist(loop,2) == 1
1301                             % Upstream bump
1302                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;],FB.OCSx.BPM.DeviceList);
1303                             if isempty(iRemove)
1304                                 setbumps(LocalBumplist(loop,:), 1);
1305                             else
1306                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1307                             end
1308                         else
1309                             % Downstream bump
1310                             [i, iRemove] = findrowindex([LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1311                             if isempty(iRemove)
1312                                 setbumps(LocalBumplist(loop,:), 1);
1313                             else
1314                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1315                             end
1316                         end
1317                     else
1318                         [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1319                         if isempty(iRemove)
1320                             setbumps(LocalBumplist(loop,:), 1);
1321                         else
1322                             fprintf('\n   BPMs missing from Sector %02d - skipping local bump for that sector.\n\n', LocalBumplist(loop,1));
1323                         end
1324                     end
1325
1326                     HCMnewsp = getsp('HCM', FB.HCMlist1);
1327                     VCMnewsp = getsp('VCM', FB.VCMlist1);
1328                     % Remove center chicane trim from corrector check
1329                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 5) || (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 10)
1330                         error('**Setbumps caused some corrector magnet currents to change by more than 5(Horiz)/10(Vert) A!');
1331                     end
1332                     % Now check center chicane trims
1333                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 10) || (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 15)
1334                         error('**Setbumps caused some chicane trim magnet currents to change by more than 10(Horiz)/15(Vert) A!');
1335                     end
1336                 end
1337             end
1338
1339             %restore corrector speeds
1340             setpv('HCM', 'RampRate', HCMramprate, [], 0);
1341             setpv('VCM', 'RampRate', VCMramprate, [], 0);
1342
1343         catch
1344             fprintf('   %s \n',lasterr);
1345             fprintf('   Setbumps failed due to error condition!  Fix the problem, reload the lattice (srload), and try again.\n\n');
1346             setpv('SR_STATE',-4);
1347             set(0,'showhiddenhandles','on');
1348             [StateNumber, StateString] = getsrstate;
1349             if StateNumber >= 0
1350                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1351             else
1352                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1353             end
1354             set(0,'showhiddenhandles','off');
1355
1356             % Reset BPM timeconstant to whatever it was before correction
1357             setbpmtimeconstant(BPMtimeconstantOC);
1358             fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1359             return
1360         end
1361
1362         % Reset BPM timeconstant to whatever it was before correction
1363         setbpmtimeconstant(BPMtimeconstantOC);
1364         fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1365
1366         % Turn feed forward back to it's original state
1367         if any(FFEnableBC)
1368             fprintf('   Turning feed forward back on.\n');
1369             setff([], FFEnableBC);
1370         end
1371
1372
1373         a = clock;
1374         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1375         [StateNumber, StateString] = getsrstate;
1376         set(0,'showhiddenhandles','on');
1377         if StateNumber >= 0
1378             setpv('SR_STATE',4.1);
1379             [StateNumber, StateString] = getsrstate;
1380             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1381             fprintf('   *********************************\n');
1382             fprintf('   **  Orbit Correction Complete  **\n');
1383             fprintf('   *********************************\n\n');
1384         else
1385             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1386             fprintf('   *************************************\n');
1387             fprintf('   **  Problem With Orbit Correction  **\n');
1388             fprintf('   *************************************\n\n');
1389         end
1390         set(0,'showhiddenhandles','off');
1391         pause(0);
1392
1393
1394     case 'OrbitCorrectionSetup'
1395         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
1396
1397         if InitFlag
1398             % Setup feedback elements
1399             % disp('Orbit correction condition: InitFlag=1 -- debugging message');
1400
1401             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1402             % Edit the following lists to change default configuration of Orbit Correction %
1403             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1404 %             hlist=[];vlist=[];
1405 %             for Sector =1:12
1406 %                 if Sector == 1
1407 %                     vlist = [vlist;Sector 2;Sector 4;Sector 5;Sector 8];
1408 %                     hlist = [hlist;Sector 2;Sector 7];
1409 %                 elseif Sector == 3
1410 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1411 %                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1412 %                 elseif Sector == 5
1413 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1414 %                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1415 % %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8]; %remove HCM and VCM(5,10) since corrector is not controlling starting 4-6-07
1416 % %                     hlist = [hlist;Sector 2;Sector 7];
1417 %                 elseif Sector == 10
1418 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1419 %                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1420 %                 elseif Sector == 12
1421 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 7];
1422 %                     hlist = [hlist;Sector 2;Sector 7];
1423 %                 else
1424 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8];
1425 %                     hlist = [hlist;Sector 2;Sector 7];
1426 %                 end
1427 %             end
1428 %             HCMlist1 = hlist;
1429 %             VCMlist1 = vlist;
1430 %
1431 %             BPMlist1 = [
1432 %                 1 2
1433 %                 1 5
1434 %                 1 6
1435 %                 1 10
1436 %                 2 1
1437 %                 2 5
1438 %                 2 6
1439 %                 2 9
1440 %                 3 2
1441 %                 3 5
1442 %                 3 6
1443 %                 3 10
1444 %                 3 11
1445 %                 3 12
1446 %                 4 1
1447 %                 4 5
1448 %                 4 6
1449 %                 4 10
1450 %                 5 1
1451 %                 5 5
1452 %                 5 6
1453 %                 5 10
1454 %                 5 11
1455 %                 5 12
1456 %                 6 1
1457 %                 6 5
1458 %                 6 6
1459 %                 6 10
1460 %                 7 1
1461 %                 7 5
1462 %                 7 6
1463 %                 7 10
1464 %                 8 1
1465 %                 8 5
1466 %                 8 6
1467 %                 8 10
1468 %                 9 1
1469 %                 9 5
1470 %                 9 6
1471 %                 9 10
1472 %                 10 1
1473 %                 10 5
1474 %                 10 6
1475 %                 10 10
1476 %                 10 11
1477 %                 10 12
1478 %                 11 1
1479 %                 11 5
1480 %                 11 6
1481 %                 11 10
1482 %                 12 1
1483 %                 12 5
1484 %                 12 6
1485 %                 12 9];
1486 %
1487 %             % SVD orbit correction
1488 %             Xivec = [1:28];
1489 %             Yivec = [1:51];
1490 %
1491 %
1492 %             % Look for bad status BPMs
1493 %             iStatus = family2status('BPMx', BPMlist1);
1494 %             iBad = find(~iStatus);
1495 %             BPMlist1 = BPMlist1(find(iStatus),:);
1496 %             if length(iBad)
1497 %                 fprintf('   Global Orbit Correction: %d BPMs removed for bad status\n', length(iBad));
1498 %                 Yivec = Yivec(1:end-length(iBad));
1499 %             end
1500 %
1501 %             iStatus = family2status('HCM', HCMlist1);
1502 %             iBad = find(~iStatus);
1503 %             HCMlist1 = HCMlist1(find(iStatus),:);
1504 %             if length(iBad)
1505 %                 fprintf('   Global Orbit Correction: %d HCMs removed for bad status\n', length(iBad));
1506 %             end
1507 %
1508 %             iStatus = family2status('VCM', VCMlist1);
1509 %             iBad = find(~iStatus);
1510 %             VCMlist1 = VCMlist1(find(iStatus),:);
1511 %             if length(iBad)
1512 %                 fprintf('   Global Orbit Correction: %d VCMs removed for bad status\n', length(iBad));
1513 %             end
1514
1515             % Initialize RFCorrFlag
1516             RFCorrFlag = 'Yes';
1517
1518             % Get the device lists from oscsinit and convert to srcontrol variables
1519             [HBPM, VBPM, HCM, VCM, HSV, VSV] = ocsinit('TopOfFill');
1520             if strcmpi(RFCorrFlag, 'Yes')
1521                 Xivec = 1:HSV+1;
1522             else
1523                 Xivec = 1:HSV;
1524             end
1525             Yivec = 1:VSV;
1526             BPMlist1 = HBPM.DeviceList;
1527             HCMlist1 = HCM.DeviceList;
1528             VCMlist1 = VCM.DeviceList;
1529
1530
1531             LocalBumplist = [
1532               % 1 1
1533               % 2 1
1534               % 3 1
1535                 4 1
1536               % 4 2
1537                 5 1
1538               % 6 1
1539               % 6 2
1540                 7 1
1541                 8 1
1542                 9 1
1543                 10 1
1544                 11 1
1545                 11 2
1546                 12 1
1547                 ];
1548             %LocalBumplist = []
1549
1550
1551         else
1552
1553             % Get vectors
1554             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1555             BPMlist1 = FB.BPMlist1;
1556             HCMlist1 = FB.HCMlist1;
1557             VCMlist1 = FB.VCMlist1;
1558             Xivec = FB.Xivec;
1559             Yivec = FB.Yivec;
1560             LocalBumplist = FB.LocalBumplist;
1561             Xgoal = FB.Xgoal;
1562             Ygoal = FB.Ygoal;
1563             RFCorrFlag = FB.RFCorrFlag;
1564
1565             % Add button to change #ivectors, CMs, IDBPMs,
1566             EditFlag = 0;
1567             h_fig1 = figure;
1568             while EditFlag ~= 8
1569
1570                 % Sensitivity matrix
1571                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
1572                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
1573
1574                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1575                 % Can the call below work for setting FOFB RF parameter? %
1576                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1577                 if strcmpi(RFCorrFlag, 'Yes')
1578                     Sx = [Sx getdisp('BPMx',BPMlist1)];
1579                 end
1580
1581                 Sx(isnan(Sx)) = 0;
1582                 Sy(isnan(Sy)) = 0;
1583
1584                 [Ux, SVx, Vx] = svd(Sx);
1585                 [Uy, SVy, Vy] = svd(Sy);
1586
1587
1588                 % Remove singular values greater than the actual number of singular values
1589                 i = find(Xivec>length(diag(SVx)));
1590                 if ~isempty(i)
1591                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
1592                     pause(0);
1593                     Xivec(i) = [];
1594                 end
1595                 i = find(Yivec>length(diag(SVy)));
1596                 if ~isempty(i)
1597                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
1598                     pause(0);
1599                     Yivec(i) = [];
1600                 end
1601
1602
1603                 Ax = Sx*Vx(:,Xivec);
1604                 Tx = inv(Ax'*Ax)*Ax';
1605
1606                 Ay = Sy*Vy(:,Yivec);
1607                 Ty = inv(Ay'*Ay)*Ay';
1608
1609
1610                 figure(h_fig1);
1611                 subplot(2,1,1);
1612                 semilogy(diag(SVx),'b');
1613                 hold on;
1614                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
1615                 ylabel('Horizontal');
1616                 title('Response Matrix Singular Values');
1617                 hold off;
1618                 subplot(2,1,2);
1619                 semilogy(diag(SVy),'b');
1620                 hold on;
1621                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
1622                 xlabel('Singular Value Number');
1623                 ylabel('Vertical');
1624                 hold off;
1625                 drawnow;
1626
1627                 if strcmp(RFCorrFlag,'No')
1628                     RFCorrState = 'NOT CORRECTED';
1629                 elseif strcmp(RFCorrFlag,'Yes')
1630                     RFCorrState = 'CORRECTED';
1631                 else
1632                     RFCorrState = '???';
1633                 end
1634
1635                 %         EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','HCM Chicane List','VCM Chicane List','IDBPM List','BBPM List','Change Golden Orbit',...
1636                 %            'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1637                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','BPM List','Change Golden Orbit',...
1638                     'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1639
1640                 if EditFlag == 1
1641                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
1642                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
1643                     titlestr='SVD Orbit Feedback';
1644                     lineNo=1;
1645                     answer=inputdlg(prompt,titlestr,lineNo,def);
1646                     if ~isempty(answer)
1647                         XivecNew = fix(str2num(answer{1}));
1648                         if isempty(XivecNew)
1649                             disp('   Horizontal E-vector cannot be empty.  No change made.');
1650                         else
1651                             if any(XivecNew<=0) || max(XivecNew)>length(diag(SVx))
1652                                 disp('   Error reading horizontal E-vector.  No change made.');
1653                             else
1654                                 Xivec = XivecNew;
1655                             end
1656                         end
1657                         YivecNew = fix(str2num(answer{2}));
1658                         if isempty(YivecNew)
1659                             disp('   Vertical E-vector cannot be empty.  No change made.');
1660                         else
1661                             if any(YivecNew<=0) || max(YivecNew)>length(diag(SVy))
1662                                 disp('   Error reading vertical E-vector.  No change made.');
1663                             else
1664                                 Yivec = YivecNew;
1665                             end
1666                         end
1667                     end
1668                 end
1669
1670                 if EditFlag == 2
1671                     List = getlist('HCM');
1672                     CheckList = zeros(size(List,1));
1673                     Elem = dev2elem('HCM', HCMlist1);
1674                     CheckList(Elem) = ones(size(Elem));
1675                     CheckList = CheckList(dev2elem('HCM',List));
1676                     newList = editlist(List, 'HCM', CheckList);
1677                     if isempty(newList)
1678                         fprintf('   Horizontal corrector magnet list cannot be empty.  No change made.\n');
1679                     else
1680                         HCMlist1 = newList;
1681                     end
1682                 end
1683
1684                 if EditFlag == 3
1685                     List = getlist('VCM');
1686                     CheckList = zeros(size(List,1));
1687                     Elem = dev2elem('VCM', VCMlist1);
1688                     CheckList(Elem) = ones(size(Elem));
1689                     CheckList = CheckList(dev2elem('VCM',List));
1690                     newList = editlist(List, 'VCM', CheckList);
1691                     if isempty(newList)
1692                         fprintf('   Vertical corrector magnet cannot be empty.  No change made.\n');
1693                     else
1694                         VCMlist1 = newList;
1695                     end
1696                 end
1697
1698                 if EditFlag == 4
1699                     ListOld = BPMlist1;
1700                     XgoalOld = Xgoal;
1701                     YgoalOld = Ygoal;
1702
1703                     % Full BPM list
1704                     List = getbpmlist('Bergoz');
1705 %                     List = [
1706 %                         1 2
1707 %                         1 5
1708 %                         1 6
1709 %                         1 10
1710 %                         2 1
1711 %                         2 5
1712 %                         2 6
1713 %                         2 9
1714 %                         3 2
1715 %                         3 5
1716 %                         3 6
1717 %                         3 10
1718 %                         3 11
1719 %                         3 12
1720 %                         4 1
1721 %                         4 5
1722 %                         4 6
1723 %                         4 10
1724 %                         5 1
1725 %                         5 5
1726 %                         5 6
1727 %                         5 10
1728 %                         5 11
1729 %                         5 12
1730 %                         6 1
1731 %                         6 5
1732 %                         6 6
1733 %                         6 10
1734 %                         7 1
1735 %                         7 5
1736 %                         7 6
1737 %                         7 10
1738 %                         8 1
1739 %                         8 5
1740 %                         8 6
1741 %                         8 10
1742 %                         9 1
1743 %                         9 5
1744 %                         9 6
1745 %                         9 10
1746 %                         10 1
1747 %                         10 5
1748 %                         10 6
1749 %                         10 10
1750 %                         10 11
1751 %                         10 12
1752 %                         11 1
1753 %                         11 5
1754 %                         11 6
1755 %                         11 10
1756 %                         12 1
1757 %                         12 5
1758 %                         12 6
1759 %                         12 9
1760 %                         ];
1761
1762                     CheckList = zeros(size(List,1),1);
1763                     if ~isempty(BPMlist1)
1764                         for i = 1:size(List,1)
1765                             k = find(List(i,1)==BPMlist1(:,1));
1766                             l = find(List(i,2)==BPMlist1(k,2));
1767
1768                             if isempty(k) || isempty(l)
1769                                 % Item not in list
1770                             else
1771                                 CheckList(i) = 1;
1772                             end
1773                         end
1774                     end
1775
1776                     newList = editlist(List, 'BPM', CheckList);
1777                     if isempty(newList)
1778                         fprintf('   BPM list cannot be empty.  No change made.\n');
1779                     else
1780                         BPMlist1 = newList;
1781                     end
1782
1783                     % Set the goal orbit to the golden orbit
1784                     Xgoal = getgolden('BPMx', BPMlist1);
1785                     Ygoal = getgolden('BPMy', BPMlist1);
1786
1787
1788                     % If a new BPM is added, then set the goal orbit to the golden orbit
1789                     for i = 1:size(BPMlist1,1)
1790
1791                         % Is it a new BPM?
1792                         k = find(BPMlist1(i,1)==ListOld(:,1));
1793                         l = find(BPMlist1(i,2)==ListOld(k,2));
1794
1795                         if isempty(k) || isempty(l)
1796                             % New BPM
1797                         else
1798                             % Use the old value for old BPM
1799                             Xgoal(i) = XgoalOld(k(l));
1800                             Ygoal(i) = YgoalOld(k(l));
1801                         end
1802                     end
1803                 end
1804
1805                 if EditFlag == 5
1806
1807                     ChangeList = editlist(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
1808                     for i = 1:size(ChangeList,1)
1809
1810                         k = find(ChangeList(i,1)==BPMlist1(:,1));
1811                         l = find(ChangeList(i,2)==BPMlist1(k,2));
1812
1813                         prompt = {sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
1814                         def = {sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
1815                         titlestr = 'CHANGE THE GOAL ORBIT';
1816                         lineNo = 1;
1817                         answer = inputdlg(prompt, titlestr, lineNo, def);
1818
1819                         if isempty(answer)
1820                             % No change
1821                             fprintf('   No change was made to the golden orbit.\n');
1822                         else
1823                             Xgoalnew = str2num(answer{1});
1824                             if isempty(Xgoalnew)
1825                                 fprintf('   No change was made to the horizontal golden orbit.\n');
1826                             else
1827                                 Xgoal(k(l)) = Xgoalnew;
1828                             end
1829
1830                             Ygoalnew = str2num(answer{2});
1831                             if isempty(Ygoalnew)
1832                                 fprintf('   No change was made to the vertical golden orbit.\n');
1833                             else
1834                                 Ygoal(k(l)) = Ygoalnew;
1835                             end
1836                         end
1837                     end
1838                     if ~isempty(ChangeList)
1839                         fprintf('   Note:  changing the goal orbit for "Orbit Correction" does not change the goal orbit for "Slow Orbit Feedback."\n');
1840                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
1841                     end
1842                 end
1843
1844                 if EditFlag == 6
1845                     List = [
1846                         1 1
1847                         2 1
1848                         3 1
1849                         4 1
1850                         4 2
1851                         5 1
1852                         6 1
1853                         6 2
1854                         7 1
1855                         8 1
1856                         9 1
1857                         10 1
1858                         11 1
1859                         11 2
1860                         12 1];
1861                     CheckList = zeros(size(List,1),1);
1862                     if ~isempty(LocalBumplist)
1863                         for i = 1:size(List,1)
1864                             k = find(List(i,1)==LocalBumplist(:,1));
1865                             l = find(List(i,2)==LocalBumplist(k,2));
1866
1867                             if isempty(k) || isempty(l)
1868                                 % Item not in list
1869                             else
1870                                 CheckList(i) = 1;
1871                             end
1872                         end
1873                     end
1874                     LocalBumplist = editlist2(List, 'Sector', CheckList);
1875                 end
1876
1877                 if EditFlag == 7
1878                     RFCorrFlag = questdlg(sprintf('Set RF Frequency during Orbit Correction?'),'RF Frequency','Yes','No', 'No');
1879                     if strcmp(RFCorrFlag,'No')
1880                         disp(['   RF Frequency will not be included in global orbit correction.']);
1881                     elseif strcmp(RFCorrFlag,'Yes')
1882                         disp(['   RF Frequency will be included in global orbit correction.']);
1883                     end
1884
1885                 end
1886             end
1887             close(h_fig1);
1888         end
1889
1890         %  ORBIT CORRECTION STRUCTURE (OCS)
1891         %    OCS.BPM (data structure)
1892         %    OCS.CM  (data structure)
1893         %    OCS.GoalOrbit
1894         %    OCS.NIter
1895         %    OCS.SVDIndex
1896         %    OCS.IncrementalFlag = 'Yes'/'No'
1897         %    OCS.BPMWeight
1898         %    OCS.Flags = { 'FitRF' , etc. }
1899         OCSx.BPM = getx(BPMlist1, 'struct');
1900         OCSx.CM = getsp('HCM', HCMlist1, 'struct');
1901         OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
1902         OCSx.NIter = 1;
1903         OCSx.SVDIndex = Xivec;
1904         OCSx.IncrementalFlag = 'No';
1905         OCSx.FitRF = 1;
1906         OCSy.BPM = gety(BPMlist1, 'struct');
1907         OCSy.CM = getsp('VCM', VCMlist1, 'struct');
1908         OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
1909         OCSy.NIter = 1;
1910         OCSy.SVDIndex = Yivec;
1911         OCSy.IncrementalFlag = 'No';
1912         OCSy.FitRF = 0;
1913
1914         % Save vectors
1915         FB.OCSx = OCSx;
1916         FB.OCSy = OCSy;
1917
1918         FB.BPMlist1 = BPMlist1;
1919         FB.HCMlist1 = HCMlist1;
1920         FB.VCMlist1 = VCMlist1;
1921         FB.Xivec = Xivec;
1922         FB.Yivec = Yivec;
1923         FB.Xgoal = OCSx.GoalOrbit;
1924         FB.Ygoal = OCSy.GoalOrbit;
1925         FB.RFCorrFlag = RFCorrFlag;
1926         FB.LocalBumplist = LocalBumplist;
1927         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata',FB);
1928
1929
1930     case 'Feedback'
1931
1932         FBloopIter = 1;
1933         if get(findobj(gcbf,'Tag','SRCTRLCheckboxFOFB'),'Value') == 1
1934             StartFOFBFlag = 1;
1935         else
1936             StartFOFBFlag = 0;
1937         end
1938
1939         FEEDBACK_STOP_FLAG = 0;
1940         HWarnNum=0;
1941         VWarnNum=0;
1942
1943         SR_GeV = getenergy;
1944         % Feedback loop setup
1945         PlotInfoFlag = 0;           % Plot micado stuff
1946         LoopDelay = 1.0;           % Period of feedback loop [seconds], make sure the BPM averaging is correct
1947         VCM_LSB = .00366211;
1948         VCMCHICANE_LSB = .002441;   % 80 max?,  Note: not fully implemented
1949
1950         if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
1951             Xgain  = 0.2;
1952             Ygain  = 0.1;
1953         else
1954             Xgain  = 0.8; % raised 0.5->0.8 at 17:20, 3-2-05 to more quickly correct EPU4 fast switching orbit distortions
1955             Ygain  = 0.8;
1956         end
1957
1958         % Load lattice set for tune feed forward
1959         ConfigSetpoint = getproductionlattice;
1960         %load([getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile')]);
1961         QFsp = ConfigSetpoint.QF.Setpoint.Data;
1962         QDsp = ConfigSetpoint.QD.Setpoint.Data;
1963         TuneW16Min = gap2tune(5, 13.23, 1.8909);
1964         % Tune response matrix
1965         SR_TUNE_MATRIX = gettuneresp({'QF','QD'}, {[],[]}, getenergy('Production'));    % Approx. [0.1944 -0.0286;-0.1182 0.1526];
1966         %SR_TUNE_MATRIX = [0.1641 -0.0245
1967         %                 -0.1149 0.1477];
1968
1969         SQSFsp = amp2k('SQSF','Setpoint',ConfigSetpoint.SQSF.Setpoint.Data);
1970         SQSDsp = amp2k('SQSD','Setpoint',ConfigSetpoint.SQSD.Setpoint.Data);
1971
1972 %         % tune FF for EPUs (data exist for 4 1 parallel, 11 1 parallel and antiparallel
1973 %         load '/home/als/physdata/matlab/srdata/gaptrack/EPU4-1_tunecomp/after_shimming/nux_map_withgaps.mat'
1974 %         dnux_epu_41_m0 = tunexmap(2:end,2:end)-tunexmap(2,12);
1975 %         [gap_epu_41,shift_epu_41]=meshgrid(tunexmap(2:end,1),tunexmap(1,2:end));
1976 %         load '/home/als/physdata/matlab/srdata/gaptrack/EPU4-1_tunecomp/after_shimming/nuy_map_withgaps.mat'
1977 %         dnuy_epu_41_m0 = tuneymap(2:end,2:end)-tuneymap(2,12);
1978 %
1979 %         load '/home/als/physdata/matlab/srdata/gaptrack/archive/epu11d1m0e19_2007-01-28.mat' tune_x tune_y Gaps GapsLongitudinal
1980 %         dnux_epu_111_m0 = tune_x-tune_x(1,11);
1981 %         [gap_epu_111,shift_epu_111]=meshgrid(Gaps,GapsLongitudinal);
1982 %         dnuy_epu_111_m0 = tune_y-tune_y(1,11);
1983 %         load '/home/als/physdata/matlab/srdata/gaptrack/archive/epu11d1m1e19_2007-01-28.mat' tune_x tune_y Gaps GapsLongitudinal
1984 %         dnux_epu_111_m1 = tune_x-tune_x(1,11);
1985 %         dnuy_epu_111_m1 = tune_y-tune_y(1,11);
1986
1987         % tune FF for EPUs (data exist for 4 1 parallel, 11 1 parallel and antiparallel
1988         load '/home/als/physdata/matlab/srdata/epu/tuneshift_2d_tables/epu_tunetables_2d_20070723.mat'
1989         dnux41p = nux41p-nux41p(1,11);
1990         dnuy41p = nuy41p-nuy41p(1,11);
1991         dnux41a = nux41a-nux41a(1,11);
1992         dnuy41a = nuy41a-nuy41a(1,11);
1993         dnux111p = nux111p-nux111p(1,11);
1994         dnuy111p = nuy111p-nuy111p(1,11);
1995         dnux111a = nux111a-nux111a(1,11);
1996         dnuy111a = nuy111a-nuy111a(1,11);
1997         dnux112p = nux112p-nux112p(1,11);
1998         dnuy112p = nuy112p-nuy112p(1,11);
1999         dnux112a = nux112a-nux112a(1,11);
2000         dnuy112a = nuy112a-nuy112a(1,11);
2001
2002         % ID tune compensation does not work in the injection lattice, so ...
2003         if abs(SR_GEV - bend2gev)>  0.05     % Don't use this routine for the injection lattice
2004             fprintf('   This routine should only be used for the production energy: Orbit feedback aborted\n');
2005             return
2006         end
2007
2008         set(0,'showhiddenhandles','on');
2009
2010         try
2011             fprintf('\n');
2012             fprintf('   *******************************\n');
2013             fprintf('   **  Starting Orbit Feedback  **\n');
2014             fprintf('   *******************************\n');
2015             a = clock;
2016             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2017             fprintf('   Note: the Matlab command window will be used to display status information.\n');
2018             fprintf('         It cannot be used to enter commands during slow orbit feedback.\n');
2019
2020
2021                 % save current BPM timeconstant - will reset to this when feedback stops
2022                 BPMtimeconstantOFB = getbpmtimeconstant;
2023                 fprintf('   Current Bergoz BPM time constant is %.1fs\n', BPMtimeconstantOFB);
2024
2025             % >= 2 Hz update rate on IDBPMs
2026             disp('   Bergoz BPM time constant set to 0.2s.')
2027             setbpmtimeconstant(0.2)
2028             pause(1.1);
2029
2030             % Check whether bumps and kickers are on and warn to turn off before starting feedback if necessary
2031             try
2032                 if (getsp('SR01S___BUMP1__BC21')==1 && getsp('SR01S___BUMP1P_BC22')==1) || (getsp('SR01S___SEK____BC21')==1 && getsp('SR01S___SEK_P__BC23')==1) || (getsp('SR01S___SEN____BC20')==1 && getsp('SR01S___SEN_P__BC22')==1)
2033                     soundtada;
2034                     fprintf('   \n');
2035                     fprintf('   *********************************************************************************\n');
2036                     fprintf('   ** One or more of the pulsed SR injection magnets is still on!  Turn them off! **\n');
2037                     fprintf('   *********************************************************************************\n');
2038                     fprintf('   \n');
2039                 end
2040             catch
2041                 disp('**Problem checking the state of the bumps and kickers - please check that they are not pulsing.');
2042             end
2043
2044             % Get vectors
2045
2046             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
2047
2048             BPMlist1 = FB.OCSx.BPM.DeviceList;
2049             % FOFB_BPMlist =
2050             HCMlist1 = FB.HCMlist1;
2051             VCMlist1 = FB.VCMlist1;
2052             Xivec = FB.Xivec;
2053             Yivec = FB.Yivec;
2054             Xgoal = FB.OCSx.GoalOrbit;
2055             Ygoal = FB.OCSy.GoalOrbit;
2056             FFTypeFlag = FB.FFTypeFlag;   %local or global tune correction
2057
2058             iNotHCMChicane = find(HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
2059             iHCMChicane = find(HCMlist1(:,2) == 10);
2060             iNotVCMChicane = find(VCMlist1(:,2) < 10);
2061             iVCMChicane = find(VCMlist1(:,2) == 10);
2062
2063             % Sensitivity matrix for setting fast feedback setpoints
2064             Sx1 = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
2065             Sy1 = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
2066
2067         catch
2068             fprintf('\n  %s \n',lasterr);
2069
2070             % Reset Bergoz BPM time constant to whatever it was before feedback started
2071             fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
2072             setbpmtimeconstant(BPMtimeconstantOFB);
2073
2074
2075             a = clock;
2076             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2077             fprintf('   *************************************************************\n');
2078             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
2079             fprintf('   *************************************************************\n\n');
2080             set(0,'showhiddenhandles','off');
2081             pause(0);
2082
2083             return
2084         end
2085
2086         StartFlag = questdlg(strvcat('','Is it OK to start orbit feedback?'),'Orbit Feedback','Yes','No','No');
2087         if strcmp(StartFlag,'No')
2088             % Reset Bergoz BPM time constant to whatever it was before feedback started
2089             fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
2090             setbpmtimeconstant(BPMtimeconstantOFB);
2091
2092             a = clock;
2093             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2094             fprintf('   ***************************\n');
2095             fprintf('   **  Orbit Feedback Exit  **\n');
2096             fprintf('   ***************************\n\n');
2097             pause(0);
2098             return
2099         end
2100
2101         SR_STATE_OLD = scaget('SR_STATE');
2102         setpv('SR_STATE', 5);
2103         set(0,'showhiddenhandles','on');
2104         [StateNumber, StateString] = getsrstate;
2105         if StateNumber >= 0
2106             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2107         else
2108             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2109         end
2110         fprintf('   Using %d E-vectors horizontally.\n', length(Xivec));
2111         fprintf('   Using %d E-vectors vertically.\n',   length(Yivec));
2112         fprintf('   Starting slow orbit correction every %.1f seconds.\n', LoopDelay);
2113         %  fprintf('   Resetting SR11 chicane motors every 20 seconds to fix drift problem.\n');
2114
2115         IDSector = getlist('ID');
2116         EPUlist = find((IDSector(:,1)==4) | (IDSector(:,1)==11));
2117         oldgap=210*ones(size(IDSector,1),1);
2118         oldShift=zeros(size(oldgap));
2119
2120         try
2121
2122             % Get and display data
2123             x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
2124             y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
2125             STDx = norm(x)/sqrt(length(x));
2126             STDy = norm(y)/sqrt(length(y));
2127             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
2128             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
2129
2130             % write goldenorbit values to Fast Orbit Feedback
2131             try
2132                 write_goldenorbit_ffb;
2133             catch
2134                 disp('write_goldenorbit_ffb did not work!');
2135             end
2136             setpv('SR01____FFBON__BC00',2);
2137             %pause(0);
2138
2139             %display state of FOFB system
2140             FOFBStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2141                 getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2142                 getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2143                 getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2144             FOFBStatusStr = ['    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    '];
2145             for loop = 1:size(FOFBStatus,2)
2146                 if FOFBStatus(loop)==0
2147                     FOFBStatusStr(loop,:) = 'OFF ';
2148                 elseif FOFBStatus(loop)==1
2149                     FOFBStatusStr(loop,:) = 'ON  ';
2150                 elseif FOFBStatus(loop)==2
2151                     FOFBStatusStr(loop,:) = 'OPEN';
2152                 else
2153                     FOFBStatusStr(loop,:) = 'BAD ';
2154                 end
2155             end
2156             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 %s',FOFBStatusStr(1,:)),'ForegroundColor',[0 0 0]);
2157             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 %s',FOFBStatusStr(2,:)),'ForegroundColor',[0 0 0]);
2158             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 %s',FOFBStatusStr(3,:)),'ForegroundColor',[0 0 0]);
2159             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 %s',FOFBStatusStr(4,:)),'ForegroundColor',[0 0 0]);
2160             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 %s',FOFBStatusStr(5,:)),'ForegroundColor',[0 0 0]);
2161             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 %s',FOFBStatusStr(6,:)),'ForegroundColor',[0 0 0]);
2162             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 %s',FOFBStatusStr(7,:)),'ForegroundColor',[0 0 0]);
2163             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 %s',FOFBStatusStr(8,:)),'ForegroundColor',[0 0 0]);
2164             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 %s',FOFBStatusStr(9,:)),'ForegroundColor',[0 0 0]);
2165             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 %s',FOFBStatusStr(10,:)),'ForegroundColor',[0 0 0]);
2166             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 %s',FOFBStatusStr(11,:)),'ForegroundColor',[0 0 0]);
2167             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 %s',FOFBStatusStr(12,:)),'ForegroundColor',[0 0 0]);
2168
2169         catch
2170
2171             fprintf('\n  %s \n',lasterr);
2172
2173             % Reset Bergoz BPM time constant to whatever it was before feedback started
2174             fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
2175             setbpmtimeconstant(BPMtimeconstantOFB);
2176
2177
2178             a = clock;
2179             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2180             fprintf('   *************************************************************\n');
2181             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
2182             fprintf('   *************************************************************\n\n');
2183
2184             setpv('SR_STATE',SR_STATE_OLD);
2185             [StateNumber, StateString] = getsrstate;
2186             if StateNumber >= 0
2187                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2188             else
2189                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2190             end
2191             set(0,'showhiddenhandles','off');
2192             pause(0);
2193
2194             return
2195
2196         end
2197
2198
2199         % Disable buttons
2200         set(0,'showhiddenhandles','on');
2201         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','off');
2202         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','on');
2203         set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','off');
2204         set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','off');
2205         set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','off');
2206         set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','off');
2207         set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','off');
2208         set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','off');
2209         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','off');
2210         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','off');
2211         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','off');
2212         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','off');
2213         set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','off');
2214         pause(0);
2215
2216
2217         % Initialize feedback loop
2218         StartTime = gettime;
2219         StartErrorTime = gettime;
2220         Xold = getx(FB.OCSx.BPM.DeviceList);
2221         Yold = gety(FB.OCSy.BPM.DeviceList);
2222         HQMOFM_stalenum = 0;
2223         pause(LoopDelay);
2224
2225         N_HCM = size(HCMlist1,1);
2226         N_VCM = size(VCMlist1,1);
2227
2228         N_RFMO = 1;
2229
2230         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2231             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'SetRF','Nodisplay','Nosetsp');
2232         else
2233             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
2234         end
2235         [FB.OCSx, Smatx, Sx, Ux, Vx] = orbitcorrectionmethods(FB.OCSx);
2236
2237         [FB.OCSy, junk, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
2238         [FB.OCSy, Smaty, Sy, Uy, Vy] = orbitcorrectionmethods(FB.OCSy);
2239
2240
2241         %%%%%%%%%%%%%%%%%%%%%%%
2242         % Start feedback loop %
2243         %%%%%%%%%%%%%%%%%%%%%%%
2244
2245         % chicaneloop=1;  % loop variable for resetting drifting chicanes (see a few lines below)
2246         % fftest=figure;
2247
2248         setpv('SR01____FFBON__BC00',2); % put FOFB in open loop so beamnoise gets recorded even if FOFB is not enabled
2249
2250         while 1
2251             try
2252                 t00 = gettime;
2253
2254                 %          if chicaneloop==20 % reset SR11 motor chicane setpoints every 20s due to drifting positions
2255                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(6),[11 1],0);
2256                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(7),[11 2],0);
2257                 %             chicaneloop = 1;
2258                 %          else
2259                 %             chicaneloop = chicaneloop + 1;
2260                 %          end
2261
2262                 % Check if GUI has been closed
2263                 if isempty(gcbf)
2264                     FEEDBACK_STOP_FLAG = 1;
2265                     lasterr('SRCONTROL GUI DISAPPEARED!');
2266                     error('SRCONTROL GUI DISAPPEARED!');
2267                 end
2268
2269                 %%%%%%%%%%%%%%%%%%%%%%%
2270                 % Fast orbit feedback %
2271                 %%%%%%%%%%%%%%%%%%%%%%%
2272                 if StartFOFBFlag == 1 && FBloopIter > 3
2273                     setpv('SR01____FFBON__BC00',2);
2274                     pause(0.5);
2275                     setpv('SR01____FFBON__BC00',1);
2276                     StartFOFBFlag = 0;
2277                     pause(1);
2278                     FOFBOnStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2279                         getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2280                         getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2281                         getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2282                     if any(FOFBOnStatus==0) || any(FOFBOnStatus==2)
2283                         setpv('SR01____FFBON__BC00',2); % open FOFB loop
2284                         disp('************************************************************************************************************');
2285                         disp('** Problem turning on Fast Orbit Feedback system...                                                       **');
2286                         disp('** Check status of ffbsecXX crates - but remember that a crate reboot will turn off Quads in that sector! **');
2287                         disp('** Suggest disabling the "Fast Orbit Correction" checkbox and starting Orbit Feedback again.              **');
2288                         disp('************************************************************************************************************');
2289                     else
2290                         fprintf('   Starting Fast Orbit Feedback at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
2291                     end
2292                 end
2293
2294
2295                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2296                 % Horizontal plane "feedback" %
2297                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2298
2299                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxSOFB'),'Value') == 1
2300
2301                     % Get orbit and check that the BPMs are different from the last update
2302                     Xnew = getx(FB.OCSx.BPM.DeviceList);
2303
2304                     % Don't feedback if the current is too small
2305                     if getdcct < 5
2306                         FEEDBACK_STOP_FLAG = 1;
2307                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2308                         break;
2309                     end
2310
2311                     x = Xgoal - Xnew;
2312                     STDx = norm(x)/sqrt(length(x));
2313
2314                     if any(Xold == Xnew)
2315                         a = clock;
2316                         N_Stale_Data_Points = find((Xold==Xnew)==1);
2317                         for loop = N_Stale_Data_Points'
2318                             fprintf('   Stale data: BPMx(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSx.BPM.DeviceList(loop,1), FB.OCSx.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2319                         end
2320                     else
2321                         % Compute horizontal correction
2322                         %%%OCSx0 = FB.OCSx;
2323                         FB.OCSx.BPM.Data = Xnew;
2324                         FB.OCSx = orbitcorrectionmethods(FB.OCSx, Smatx, Sx, Ux, Vx);
2325
2326                         %%%[FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
2327
2328                         % reduced feedback gain (implemented by Greg Portmann, December 2000)
2329                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2330                         % increased back to 0.8 C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2331                         % increased to 1.0, C. Steier, 2002-05-04, trim DACs
2332                         X = Xgain .* FB.OCSx.CM.Delta;
2333                         X(N_HCM+1) = 0.3*FB.OCSx.DeltaRF/4.988e-3;
2334                         %%%X = Xgain .* (FB.OCSx.CM.Data - OCSx0.CM.Data);
2335
2336                         % check corrector trim values + next step values, warn or stop FB as necessary
2337                         HCMtrimSP=getpv('HCM','Trim',HCMlist1);
2338                         HCMtrimSP_next = HCMtrimSP + X(1:N_HCM);
2339                         if max(abs(HCMtrimSP_next)) > 4
2340                             HCMtrimnum=find(abs(HCMtrimSP_next) > 4);
2341
2342                             % print message to screen
2343                             fprintf('\n');
2344                             fprintf('***One or more of the horizontal correctors is at its maximum!! Stopping orbit feedback. \n');
2345                             fprintf('   %s\n',datestr(now));
2346                             for loop = HCMtrimnum'
2347                                 fprintf('***%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2348                             end
2349
2350                             % send alphapage to operator pager
2351                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2352                             FEEDBACK_STOP_FLAG = 1;
2353
2354                             setpv('SR_STATE', -5);
2355                             [StateNumber, StateString] = getsrstate;
2356                             if StateNumber >= 0
2357                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2358                             else
2359                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2360                             end
2361                         end
2362
2363                         % check chicane trim coil values + next step values, warn or stop FB as necessary
2364                         HCMCHICANEtrimSP=getpv('HCM','Setpoint',HCMlist1(iHCMChicane,:));
2365                         HCMCHICANEtrimSP_next = HCMCHICANEtrimSP + X(iHCMChicane);
2366                         if max(abs(HCMCHICANEtrimSP_next)) > 19.9
2367                             HCMCHICANEtrimnum=find(abs(HCMCHICANEtrimSP_next) > 19.9);
2368
2369                             % print message to screen
2370                             fprintf('\n');
2371                             fprintf('***One or more of the horizontal chicane trim coil correctors is at its maximum!! Stopping orbit feedback. \n');
2372                             fprintf('   %s\n',datestr(now));
2373                             for loop = HCMCHICANEtrimnum'
2374                                 fprintf('***%s is one of the problem correctors.\n',getname('HCM','Setpoint',HCMlist1(iHCMChicane(loop,:),:)));
2375                             end
2376                             fprintf('***Maybe try resetting the setpoints of the motor chicanes in case they are drifting...\n');
2377
2378                             % send alphapage to operator pager
2379                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2380                             FEEDBACK_STOP_FLAG = 1;
2381
2382                             setpv('SR_STATE', -5);
2383                             [StateNumber, StateString] = getsrstate;
2384                             if StateNumber >= 0
2385                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2386                             else
2387                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2388                             end
2389                         end
2390
2391                         if FEEDBACK_STOP_FLAG == 1
2392                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2393                             if getpv('SR01____FFBON__BC00')==1
2394                                 disp('   Stopping Fast Orbit Feedback.');
2395                             end
2396                             setpv('SR01____FFBON__BC00',0);
2397                             pause(0.5);
2398                             setpv('SR01____FFBON__BC00',2);
2399                             break;
2400                         end
2401
2402                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2403                         pause(0);
2404
2405                         if max(abs(HCMtrimSP_next) > 3)
2406                             HCMtrimnum=find(abs(HCMtrimSP_next) > 3);
2407                             HWarnNum=HWarnNum+1;
2408                             if (HWarnNum==1 || rem(HWarnNum,120)==0)
2409
2410                                 % print message to screen every two minutes
2411                                 fprintf('\n');
2412                                 fprintf('***One or more of the horizontal corrector trims is above 3A or below -3A! \n');
2413                                 fprintf('   %s\n',datestr(now));
2414                                 for loop = HCMtrimnum'
2415                                     fprintf('***%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2416                                 end
2417                                 fprintf('***The orbit feedback is still working but this problem should be investigated. \n');
2418
2419                                 %send alphapage to operator pager the first time then at 10 minutes
2420                                 if (HWarnNum==1 || HWarnNum==600)
2421                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageHCM.txt
2422                                 end
2423                             end
2424                         elseif max(abs(HCMCHICANEtrimSP_next) > 15)
2425                             HCMCHICANEtrimnum=find(abs(HCMCHICANEtrimSP_next) > 15);
2426                             HWarnNum=HWarnNum+1;
2427                             if (HWarnNum==1 || rem(HWarnNum,120)==0)
2428
2429                                 % print message to screen every two minutes
2430                                 fprintf('\n');
2431                                 fprintf('***One or more of the horizontal chicane corrector trim coils is above 15A or below -15A! \n');
2432                                 fprintf('   %s\n',datestr(now));
2433                                 for loop = HCMCHICANEtrimnum'
2434                                     fprintf('***%s is one of the problem correctors.\n',getname('HCM','Setpoint',HCMlist1(iHCMChicane(loop,:),:)));
2435                                 end
2436                                 fprintf('***The orbit feedback is still working but this problem should be investigated. \n');
2437
2438                                 %reset motor chicanes in case they are drifting
2439                                 try
2440                                         fprintf('   Resetting the setpoints of the motor chicanes in case they are drifting...\n');
2441                                         setpv('HCMCHICANEM','Setpoint',ConfigSetpoint.HCMCHICANEM.Setpoint.Data,[],0);
2442                                 catch
2443                                 end
2444
2445                                 %send alphapage to operator pager the first time then at 10 minutes
2446                                 if (HWarnNum==1 || HWarnNum==600)
2447                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageHCMCHICANE.txt
2448                                 end
2449                             end
2450                         else
2451                             HWarnNum=0;
2452                         end
2453
2454                         % Don't feedback if the current is too small
2455                         if getdcct < 5
2456                             FEEDBACK_STOP_FLAG = 1;
2457                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2458                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2459                             break;
2460                         end
2461
2462                         if N_HCM > 0
2463                             steppv('HCM','Trim', X(iNotHCMChicane), HCMlist1(iNotHCMChicane,:), 0);
2464                             steppv('HCM','Setpoint', X(iHCMChicane), HCMlist1(iHCMChicane,:), 0);
2465                         end
2466
2467                         % write fast orbit feedback setpoints
2468                         if 1
2469                             %write_goldenorbit_ffb_2planes(1, Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM)+Sx3*X(length(X))/20, BPMlist1);
2470                             % should be corrected to include result of next frequency step ...
2471                             write_goldenorbit_ffb_2planes(1,Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM),BPMlist1);
2472                         end
2473
2474                         %fprintf('Horizontal Done: %f \n',gettime-t00);
2475
2476                         % RF feedback
2477                         HQMOFMsp_last = getpv('EG______HQMOFM_AC01');
2478
2479                         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2480                             if N_RFMO > 0
2481                                 if abs(X(end)) < .01
2482                                     % if abs(FB.OCSx.DeltaRF/3) < .01
2483                                     steppv('EG______HQMOFM_AC01', X(end));
2484                                 else
2485                                     steppv('EG______HQMOFM_AC01', 0.01*sign(X(end)));
2486                                 end
2487                             end
2488
2489                             HQMOFMsp_now = getpv('EG______HQMOFM_AC01');
2490
2491                             % Check for stale RF feedback
2492                             if HQMOFMsp_last == HQMOFMsp_now
2493                                 HQMOFM_stalenum = HQMOFM_stalenum + 1;
2494                                 if HQMOFM_stalenum == 30 % warn and message to pager if stale for 30 secs
2495                                     fprintf('\n');
2496                                     fprintf('***The RF is not responding to orbit feedback changes! \n');
2497                                     fprintf('   %s\n',datestr(now));
2498                                     fprintf('***The orbit feedback is still working but this problem should be investigated. \n');
2499                                     fprintf('***ILC 73 controls the EG______HQMOFM_AC01 channel, which sets the RF frequency. \n');
2500                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstaleRFmessage.txt
2501                                 end
2502                                 if rem(HQMOFM_stalenum,120)==0 % message to screen every 2 minutes
2503                                     fprintf('\n');
2504                                     fprintf('***The RF is not responding to orbit feedback changes! (%s)\n',datestr(now));
2505                                 end
2506                             else
2507                                 HQMOFM_stalenum = 0;
2508                             end
2509
2510                         end
2511
2512                         %fprintf('RF Done: %f \n',gettime-t00);
2513
2514                         Xold = Xnew;
2515                     end % End horizontal correction
2516
2517
2518                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2519                     % Vertical plane "feedback" %
2520                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2521
2522                     % Get orbit and check that the BPMs are different from the last update
2523                     Ynew = gety(FB.OCSy.BPM.DeviceList);
2524
2525                     % Don't feedback if the current is too small
2526                     if getdcct < 5
2527                         FEEDBACK_STOP_FLAG = 1;
2528                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2529                         break;
2530                     end
2531
2532                     y = Ygoal - Ynew;
2533                     STDy = norm(y)/sqrt(length(y));
2534
2535                     if any(Yold == Ynew)
2536                         a = clock;
2537                         N_Stale_Data_Points = find((Yold==Ynew)==1);
2538                         for loop = N_Stale_Data_Points'
2539                             fprintf('   Stale data: BPMy(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSy.BPM.DeviceList(loop,1), FB.OCSy.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2540                         end
2541
2542                     else
2543
2544                         % Compute vertical correction
2545                         %%%OCSy0 = FB.OCSy;
2546                         FB.OCSy.BPM.Data = Ynew;
2547                         FB.OCSy = orbitcorrectionmethods(FB.OCSy, Smaty, Sy, Uy, Vy);
2548
2549                         %%%[FB.OCSy, RF, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
2550
2551                         % reduced feedback gain, C. Steier, 2001-03-25
2552                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2553                         % increased back to 0.8, C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2554                         % set to unity gain, C. Steier, 2002-05-04, trim DACs
2555                         Y = Ygain .* FB.OCSy.CM.Delta;
2556                         %%%Y = Ygain .* (FB.OCSy.CM.Data - OCSy0.CM.Data);
2557
2558                         % Just SVD correction
2559                         % warning('Not using "micado" correction in the vertical plane.');
2560
2561                         % check for trim values+next step values, warn or stop FB as necessary
2562                         VCMtrimSP = getpv('VCM','Trim',VCMlist1);
2563                         VCMtrimSP_next = VCMtrimSP + Y(1:N_VCM);
2564                         if max(abs(VCMtrimSP_next)) > 12
2565                             VCMtrimnum=find(abs(VCMtrimSP_next) > 12);
2566
2567                             % print message to screen
2568                             fprintf('\n');
2569                             fprintf('***One or more of the vertical correctors is at its maximum!! Stopping orbit feedback. \n');
2570                             fprintf('   %s\n',datestr(now));
2571                             for loop = VCMtrimnum'
2572                                 fprintf('***%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2573                             end
2574
2575                             % send alphapage to operator pager
2576                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2577                             FEEDBACK_STOP_FLAG = 1;
2578
2579                             setpv('SR_STATE', -5);
2580                             [StateNumber, StateString] = getsrstate;
2581                             if StateNumber >= 0
2582                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2583                             else
2584                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2585                             end
2586                         end
2587
2588                         % check chicane trim coil values + next step values, warn or stop FB as necessary
2589                         VCMCHICANEtrimSP=getpv('VCM','Setpoint',VCMlist1(iVCMChicane,:));
2590                         VCMCHICANEtrimSP_next = VCMCHICANEtrimSP + X(iVCMChicane);
2591                         if max(abs(VCMCHICANEtrimSP_next)) > 19.9
2592                             VCMCHICANEtrimnum=find(abs(VCMCHICANEtrimSP_next) > 19.9);
2593
2594                             % print message to screen
2595                             fprintf('\n');
2596                             fprintf('***One or more of the vertical chicane trim coil correctors is at its maximum!! Stopping orbit feedback. \n');
2597                             fprintf('   %s\n',datestr(now));
2598                             for loop = VCMCHICANEtrimnum'
2599                                 fprintf('***%s is one of the problem correctors.\n',getname('VCM','Setpoint',VCMlist1(iVCMChicane(loop,:),:)));
2600                             end
2601                             fprintf('***Maybe try resetting the setpoints of the motor chicanes in case they are drifting...\n');
2602
2603                             % send alphapage to operator pager
2604                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2605                             FEEDBACK_STOP_FLAG = 1;
2606
2607                             setpv('SR_STATE', -5);
2608                             [StateNumber, StateString] = getsrstate;
2609                             if StateNumber >= 0
2610                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2611                             else
2612                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2613                             end
2614                         end
2615
2616                         if FEEDBACK_STOP_FLAG == 1
2617                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2618                             if getpv('SR01____FFBON__BC00')==1
2619                                 disp('   Stopping Fast Orbit Feedback.');
2620                             end
2621                             setpv('SR01____FFBON__BC00',0);
2622                             pause(0.5);
2623                             setpv('SR01____FFBON__BC00',2);
2624                             break;
2625                         end
2626
2627                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2628                         % pause(0);
2629
2630                         if max(abs(VCMtrimSP_next) > 4)
2631                             VCMtrimnum=find(abs(VCMtrimSP_next) > 4);
2632                             VWarnNum=VWarnNum+1;
2633                             if (VWarnNum==1 || rem(VWarnNum,120)==0)
2634
2635                                 % print message to screen every two minutes
2636                                 fprintf('\n');
2637                                 fprintf('***One or more of the vertical corrector trims is above 4A or below -4A! \n');
2638                                 fprintf('   %s\n',datestr(now));
2639                                 for loop = VCMtrimnum'
2640                                     fprintf('***%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2641                                 end
2642                                 fprintf('***The orbit feedback is still working but this problem should be investigated. \n');
2643
2644                                 %send alphapage to operator pager the first time then at 10 minutes
2645                                 if (VWarnNum==1 || VWarnNum==600)
2646                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageVCM.txt
2647                                 end
2648                             end
2649                         elseif max(abs(VCMCHICANEtrimSP_next) > 15)
2650                             VCMCHICANEtrimnum=find(abs(VCMCHICANEtrimSP_next) > 15);
2651                             VWarnNum=VWarnNum+1;
2652                             if (VWarnNum==1 || rem(VWarnNum,120)==0)
2653
2654                                 % print message to screen every two minutes
2655                                 fprintf('\n');
2656                                 fprintf('***One or more of the vertical chicane corrector trim coils is above 15A or below -15A! \n');
2657                                 fprintf('   %s\n',datestr(now));
2658                                 for loop = VCMCHICANEtrimnum'
2659                                     fprintf('***%s is one of the problem correctors.\n',getname('VCM','Setpoint',VCMlist1(iVCMChicane(loop,:),:)));
2660                                 end
2661                                 fprintf('***The orbit feedback is still working but this problem should be investigated. \n');
2662
2663                                 %reset motor chicanes in case they are drifting
2664                                 try
2665                                         fprintf('  Resetting the setpoints of the motor chicanes in case they are drifting...\n');
2666                                         setpv('HCMCHICANEM','Setpoint',ConfigSetpoint.HCMCHICANEM.Setpoint.Data,[],0);
2667                                 catch
2668                                 end
2669
2670                                 %send alphapage to operator pager the first time then at 10 minutes
2671                                 if (VWarnNum==1 || VWarnNum==600)
2672                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageVCMCHICANE.txt
2673                                 end
2674                             end
2675                         else
2676                             VWarnNum=0;
2677                         end
2678
2679                         % Don't feedback if the current is too small
2680                         if getdcct < 5
2681                             FEEDBACK_STOP_FLAG = 1;
2682                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2683                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2684                             break;
2685                         end
2686
2687                         if N_VCM > 0
2688                             steppv('VCM','Trim', Y(iNotVCMChicane), VCMlist1(iNotVCMChicane,:), 0);
2689                             steppv('VCM','Setpoint', Y(iVCMChicane), VCMlist1(iVCMChicane,:), 0);
2690                         end
2691
2692                         % write fast orbit feedback setpoints
2693                         if 1
2694                             write_goldenorbit_ffb_2planes(2,Ynew(1:size(BPMlist1,1))+Sy1*Y(1:N_VCM),BPMlist1);
2695                         end
2696
2697                     end
2698
2699                     Yold = Ynew;
2700
2701                     %fprintf('Vertical Done: %f \n',gettime-t00);
2702                 end % End vertical correction
2703
2704
2705                 %%%%%%%%%%%%%%%%%%%%%
2706                 % Tune feed forward %
2707                 %%%%%%%%%%%%%%%%%%%%%
2708                 % We should do a Sector limit check
2709
2710                 tic;
2711                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxTune'),'Value') == 1
2712
2713                     if strcmp(SR_Mode, '1.9 GeV, High Tune') || strcmp(SR_Mode, '1.9 GeV, Inject at 1.23') || strcmp(SR_Mode, '1.9 GeV, Two-Bunch')
2714
2715                         addQFsp = zeros(24,1);
2716                         addQDsp = zeros(24,1);
2717
2718                         if strcmp(FFTypeFlag,'Local')
2719                             disp('  No local tune compensation available - global is the default now.');
2720                         elseif strcmp(FFTypeFlag,'Global')
2721
2722                             % The vectorized gets were put outside of loop for speed reasons
2723                             %
2724                             % should also set up QFfac, Quadelem, Quadlist structures outside loop
2725                             actualgap = getid(IDSector);
2726                             [gapmin,gapmax] = gaplimit(IDSector);
2727                             corrind = find(actualgap<(gapmin-1));
2728                             actualgap(corrind)=gapmax(corrind);
2729                             Shift=zeros(size(actualgap));
2730                             Shift(EPUlist)=getpv('EPU');
2731
2732                             IDchangedList=find((abs(actualgap-oldgap)>0.005) | (abs(Shift-oldShift)>0.005));
2733
2734                             if ~isempty(IDchangedList)
2735
2736                                 oldgap=actualgap;
2737                                 oldShift=Shift;
2738
2739                                 % EPUs excite nux = .25 resonance in vertical linear polarization mode!
2740                                 % therefore with EPU tune feedforward
2741                                 % running, we want to move our nominal working point away (just below) the .25 resonance.
2742                                 %
2743                                 % The following tune correction moves nominal
2744                                 % nu_x from .25 to .245 - this should be enough for well set up lattices.
2745                                 %
2746                                 % 24 QF+ 24 QD
2747                                 DeltaAmps = inv(SR_TUNE_MATRIX) * [-0.005;0];    %  DelAmps =  [QF; QD];
2748                                 addQFsp = addQFsp + DeltaAmps(1,:);
2749                                 addQDsp = addQDsp + DeltaAmps(2,:);
2750
2751                                 for gapnum = 1:length(actualgap)
2752
2753                                     % Change in tune and [QF;QD] from maximum gap
2754
2755                                     if (IDSector(gapnum,1) == 4) || (IDSector(gapnum,1) == 11)
2756                                         if IDSector(gapnum,2) == 1
2757                                             modenamestr = sprintf('SR%02dU___ODS1M__DC00',IDSector(gapnum,1));
2758                                         else % if IDSector(gapnum,2) == 2
2759                                             modenamestr = sprintf('SR%02dU___ODS2M__DC00',IDSector(gapnum,1));
2760                                         end
2761                                         epumode = getpv(modenamestr);
2762                                         if (IDSector(gapnum,1) == 4) && (IDSector(gapnum,2) == 1)
2763                                             if (epumode == 0)
2764 %                                                 DeltaNuX = interp2(gap_epu_41,shift_epu_41,dnux_epu_41_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2765 %                                                 DeltaNuY = interp2(gap_epu_41,shift_epu_41,dnuy_epu_41_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2766                                                 DeltaNuX = interp2(gap41p',shift41p',dnux41p',actualgap(gapnum),Shift(gapnum),'linear',0);
2767                                                 DeltaNuY = interp2(gap41p',shift41p',dnuy41p',actualgap(gapnum),Shift(gapnum),'linear',0);
2768                                             elseif (epumode == 1)
2769 %                                                 DeltaNux = 0;
2770 %                                                 DeltaNuY = gap2tune(IDSector(gapnum, :), actualgap(gapnum), SR_GeV);
2771                                                 DeltaNuX = interp2(gap41a',shift41a',dnux41a',actualgap(gapnum),Shift(gapnum),'linear',0);
2772                                                 DeltaNuY = interp2(gap41a',shift41a',dnuy41a',actualgap(gapnum),Shift(gapnum),'linear',0);
2773                                             else
2774                                                 DeltaNux = 0;
2775                                                 DeltaNuY = gap2tune(IDSector(gapnum, :), actualgap(gapnum), SR_GeV);
2776                                             end
2777                                         elseif (IDSector(gapnum,1) == 11) && (IDSector(gapnum,2) == 1)
2778                                             if (epumode == 0)
2779 %                                                 DeltaNuX = interp2(gap_epu_111,shift_epu_111,dnux_epu_111_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2780 %                                                 DeltaNuY = interp2(gap_epu_111,shift_epu_111,dnuy_epu_111_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2781                                                 DeltaNuX = interp2(gap111p',shift111p',dnux111p',actualgap(gapnum),Shift(gapnum),'linear',0);
2782                                                 DeltaNuY = interp2(gap111p',shift111p',dnuy111p',actualgap(gapnum),Shift(gapnum),'linear',0);
2783                                             elseif (epumode == 1)
2784 %                                                 DeltaNuX = interp2(gap_epu_111,shift_epu_111,dnux_epu_111_m1',actualgap(gapnum),Shift(gapnum),'linear',0);
2785 %                                                 DeltaNuY = interp2(gap_epu_111,shift_epu_111,dnuy_epu_111_m1',actualgap(gapnum),Shift(gapnum),'linear',0);
2786                                                 DeltaNuX = interp2(gap111a',shift111a',dnux111a',actualgap(gapnum),Shift(gapnum),'linear',0);
2787                                                 DeltaNuY = interp2(gap111a',shift111a',dnuy111a',actualgap(gapnum),Shift(gapnum),'linear',0);
2788                                             else
2789                                                 DeltaNuX = 0;
2790                                                 DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);   % variation of vertical tune shift with phase is small for EPUs
2791                                             end
2792                                         elseif (IDSector(gapnum,1) == 11) && (IDSector(gapnum,2) == 2)
2793                                             if (epumode == 0)
2794 %                                                 DeltaNuX = interp2(gap_epu_111,shift_epu_111,dnux_epu_111_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2795 %                                                 DeltaNuY = interp2(gap_epu_111,shift_epu_111,dnuy_epu_111_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2796                                                 DeltaNuX = interp2(gap112p',shift112p',dnux112p',actualgap(gapnum),Shift(gapnum),'linear',0);
2797                                                 DeltaNuY = interp2(gap112p',shift112p',dnuy112p',actualgap(gapnum),Shift(gapnum),'linear',0);
2798                                             elseif (epumode == 1)
2799 %                                                 DeltaNuX = interp2(gap_epu_111,shift_epu_111,dnux_epu_111_m1',actualgap(gapnum),Shift(gapnum),'linear',0);
2800 %                                                 DeltaNuY = interp2(gap_epu_111,shift_epu_111,dnuy_epu_111_m1',actualgap(gapnum),Shift(gapnum),'linear',0);
2801                                                 DeltaNuX = interp2(gap112a',shift112a',dnux112a',actualgap(gapnum),Shift(gapnum),'linear',0);
2802                                                 DeltaNuY = interp2(gap112a',shift112a',dnuy112a',actualgap(gapnum),Shift(gapnum),'linear',0);
2803                                             else
2804                                                 DeltaNuX = 0;
2805                                                 DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);   % variation of vertical tune shift with phase is small for EPUs
2806                                             end
2807                                         else
2808                                             DeltaNuX = 0;
2809                                             DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);
2810                                         end
2811
2812                                     else
2813                                         DeltaNuX = 0;
2814                                         DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);
2815                                     end
2816
2817                                     DelQF = zeros(length(QFsp),1);
2818                                     DelQD = zeros(length(QFsp),1);
2819
2820                                     fraccorr = 0.8*DeltaNuY ./ TuneW16Min;
2821
2822                                     % Find which quads to change (local beta beating correction
2823                                     % (horizontal for EPU, vertical otherwise)
2824                                     QuadList = [IDSector(gapnum,1)-1 2; IDSector(gapnum,1) 1];
2825                                     QuadElem = dev2elem('QF',QuadList); % in reality use QF and QD ...
2826
2827                                     % global vertical tune correction
2828                                     % 24 QF+ 24 QD
2829                                     DeltaAmps = inv(SR_TUNE_MATRIX) * [(fraccorr*6.23e-4); fraccorr*(-0.05301)];    %  DelAmps =  [QF; QD];
2830                                     DelQF = DelQF + DeltaAmps(1,:);
2831                                     DelQD = DelQD + DeltaAmps(2,:);
2832
2833                                     % local horizontal tune correction (is also nearly a beta beating correction) only nonzero for EPUs!
2834                                     % 2 QF + 2 QD
2835                                     DeltaAmpsLocal = 12*inv(SR_TUNE_MATRIX) * [-DeltaNuX;0];                       %  DelAmps =  [QF; QD];
2836                                     DelQF(QuadElem) = DelQF(QuadElem)+DeltaAmpsLocal(1,1);
2837                                     DelQD(QuadElem) = DelQD(QuadElem)+DeltaAmpsLocal(2,1);
2838
2839                                     % local vertical beta beating correction (should be used together with above global tune correction)
2840                                     % set to zero for EPUs, since their vertical tune shift is small
2841                                     % 2 QF + 2QD
2842                                     if (IDSector(gapnum,1)==6) || (IDSector(gapnum,1)==7) || (IDSector(gapnum,1)==10) || (IDSector(gapnum,1)==11)
2843                                         QFfac = ([2.243127/2.237111; 2.243127/2.237111]-1) * fraccorr;
2844                                         QDfac = ([2.556392/2.511045; 2.556392/2.511045]-1) * fraccorr;
2845                                     elseif (IDSector(gapnum,1)==5) || (IDSector(gapnum,1)==9)
2846                                         QFfac = ([2.225965/2.219784; 2.243096/2.237111]-1) * fraccorr;
2847                                         QDfac = ([2.528950/2.483259; 2.556345/2.511045]-1) * fraccorr;
2848                                     elseif (IDSector(gapnum,1)==4) || (IDSector(gapnum,1)==8) || (IDSector(gapnum,1)==12)
2849                                         QFfac = ([2.243096/2.237111; 2.225965/2.219784]-1) * fraccorr;
2850                                         QDfac = ([2.556345/2.511045; 2.528950/2.483259]-1) * fraccorr;
2851                                     else
2852                                         QFfac = zeros(2,1);
2853                                         QDfac = zeros(2,1);
2854                                     end
2855
2856                                     DelQF(QuadElem,:) = DelQF(QuadElem,:) + QFfac.*QFsp(QuadElem,:);
2857                                     DelQD(QuadElem,:) = DelQD(QuadElem,:) + QDfac.*QDsp(QuadElem,:);
2858
2859                                     % add all tune and beta beating corrections for this one ID to the summed up correction vectors for all IDs
2860                                     addQFsp = addQFsp+DelQF;
2861                                     addQDsp = addQDsp+DelQD;
2862
2863
2864                                     % Skew FF for IVID
2865                                     if (IDSector(gapnum,1)==6)
2866                                         scale=(gap2tune(6)/0.005)^(3/4)*0.16;
2867                                         [SQSFincr, SQSDincr] = set_etaywave_nuy9_20skews_skewFF(scale);
2868                                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2869                                         % should add a limit check here %
2870                                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2871                                         setpv('SQSF', 'Setpoint', SQSFsp+SQSFincr, [], 0, 'Physics');
2872                                         setpv('SQSD', 'Setpoint', SQSDsp+SQSDincr, [], 0, 'Physics');
2873                                     end
2874
2875                                 end
2876
2877                                 % Set quadrupoles using main setpoint channels
2878                                 setpv('QF', QFsp+addQFsp,[], 0);
2879                                 setpv('QD', QDsp+addQDsp,[], 0);
2880                                 % % Set quadrupoles using FF setpoint channels
2881                                 % setpv('QF', 'FF', addQFsp, [], 0);
2882                                 % setpv('QD', 'FF', addQDsp, [], 0);
2883
2884                             end
2885
2886                         else
2887                             error('Unknown type selected for tune FF');
2888                         end
2889
2890                     else
2891                         disp('  No tune FF algorithm for non-production modes yet...');
2892                     end
2893                 end
2894
2895                 ffdeltaquad_delay = toc;
2896                 %fprintf('tune FF delay = %.1f seconds\n',ffdeltaquad_delay);
2897                 % fprintf('Tune Done: %f \n',gettime-t00);
2898
2899                 % Output info to screen
2900                 set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
2901                 set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
2902                 %pause(0);
2903
2904                 FOFBStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2905                     getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2906                     getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2907                     getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2908                 for loop = 1:size(FOFBStatus,2)
2909                     if FOFBStatus(loop)==0
2910                         FOFBStatusStr(loop,:) = 'OFF ';
2911                     elseif FOFBStatus(loop)==1
2912                         FOFBStatusStr(loop,:) = 'ON  ';
2913                     elseif FOFBStatus(loop)==2
2914                         FOFBStatusStr(loop,:) = 'OPEN';
2915                     else
2916                         FOFBStatusStr(loop,:) = 'BAD ';
2917                     end
2918                 end
2919                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 %s',FOFBStatusStr(1,:)),'ForegroundColor',[0 0 0]);
2920                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 %s',FOFBStatusStr(2,:)),'ForegroundColor',[0 0 0]);
2921                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 %s',FOFBStatusStr(3,:)),'ForegroundColor',[0 0 0]);
2922                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 %s',FOFBStatusStr(4,:)),'ForegroundColor',[0 0 0]);
2923                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 %s',FOFBStatusStr(5,:)),'ForegroundColor',[0 0 0]);
2924                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 %s',FOFBStatusStr(6,:)),'ForegroundColor',[0 0 0]);
2925                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 %s',FOFBStatusStr(7,:)),'ForegroundColor',[0 0 0]);
2926                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 %s',FOFBStatusStr(8,:)),'ForegroundColor',[0 0 0]);
2927                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 %s',FOFBStatusStr(9,:)),'ForegroundColor',[0 0 0]);
2928                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 %s',FOFBStatusStr(10,:)),'ForegroundColor',[0 0 0]);
2929                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 %s',FOFBStatusStr(11,:)),'ForegroundColor',[0 0 0]);
2930                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 %s',FOFBStatusStr(12,:)),'ForegroundColor',[0 0 0]);
2931
2932
2933                 %fprintf('End of feedback operations: %f \n\n',gettime-t00);
2934
2935                 % Wait for next update time or stop request
2936                 while (gettime-t00) < LoopDelay
2937                     %disp('interval could be shorter')
2938                     pause(.05);
2939                     % Check if GUI has been closed
2940                     if isempty(gcbf)
2941                         FEEDBACK_STOP_FLAG = 1;
2942                         lasterr('SRCONTROL GUI DISAPPEARED!');
2943                         error('SRCONTROL GUI DISAPPEARED!');
2944                     end
2945
2946                     % Check if Stop button was pressed
2947                     if FEEDBACK_STOP_FLAG == 1
2948                         % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2949                         if getpv('SR01____FFBON__BC00')==1
2950                             disp('   Stopping Fast Orbit Feedback.');
2951                         end
2952                         setpv('SR01____FFBON__BC00',0);
2953                         pause(0.5);
2954                         setpv('SR01____FFBON__BC00',2);
2955                         break;
2956                     end
2957                 end
2958
2959
2960                 if FEEDBACK_STOP_FLAG == 1
2961                     % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2962                     if getpv('SR01____FFBON__BC00')==1
2963                         disp('   Stopping Fast Orbit Feedback.');
2964                     end
2965                     setpv('SR01____FFBON__BC00',0);
2966                     pause(0.5);
2967                     setpv('SR01____FFBON__BC00',2);
2968                     break;
2969                 end
2970
2971                 StartErrorTime = gettime;
2972
2973             catch
2974
2975                 fprintf('\n  %s \n',lasterr);
2976
2977                 % Quit if error exists for more than 20 seconds
2978                 if gettime-StartErrorTime>20 || FEEDBACK_STOP_FLAG==1
2979                     fprintf('%s  Orbit feedback stopped due to error condition. \n\n',datestr(now));
2980
2981                     %send alphapage to operator pager
2982                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2983                     FEEDBACK_STOP_FLAG = 1;
2984
2985                     setpv('SR_STATE', -5);
2986                     [StateNumber, StateString] = getsrstate;
2987                     if StateNumber >= 0
2988                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2989                     else
2990                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2991                     end
2992                 else
2993                     a = clock;
2994                     fprintf('   Orbit feedback was paused due to error condition (%s %d:%d:%.0f). \n', date, a(4), a(5), a(6));
2995                     fprintf('   Orbit feedback has automatically restarted and is running. \n\n');
2996                 end
2997
2998             end
2999
3000             if FEEDBACK_STOP_FLAG == 1
3001                 % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
3002                 if getpv('SR01____FFBON__BC00')==1
3003                     disp('   Stopping Fast Orbit Feedback.');
3004                 end
3005                 setpv('SR01____FFBON__BC00',0);
3006                 pause(0.5);
3007                 setpv('SR01____FFBON__BC00',2);
3008                 break;
3009             end
3010
3011             %fprintf('End of feedback loop: %f \n\n',gettime-t00);
3012
3013             %pause(0);
3014
3015             % this loop delays turn on of Fast Feedback system
3016             if FBloopIter < 5
3017                 FBloopIter = FBloopIter + 1;
3018             end
3019
3020         end  % End of feedback loop
3021
3022
3023         % End feedback, reset all parameters
3024         try
3025
3026             % Enable buttons
3027             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','on');
3028             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','off');
3029             set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','on');
3030             set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','on');
3031             set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','on');
3032             set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','on');
3033             set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','on');
3034             set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','on');
3035             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','on');
3036             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','on');
3037             set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','on');
3038             set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','on');
3039             set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','on');
3040
3041             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = _____ mm'),'ForegroundColor',[0 0 0]);
3042             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = _____ mm'),'ForegroundColor',[0 0 0]);
3043
3044             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 ____'),'ForegroundColor',[0 0 0]);
3045             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 ____'),'ForegroundColor',[0 0 0]);
3046             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 ____'),'ForegroundColor',[0 0 0]);
3047             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 ____'),'ForegroundColor',[0 0 0]);
3048             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 ____'),'ForegroundColor',[0 0 0]);
3049             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 ____'),'ForegroundColor',[0 0 0]);
3050             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 ____'),'ForegroundColor',[0 0 0]);
3051             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 ____'),'ForegroundColor',[0 0 0]);
3052             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 ____'),'ForegroundColor',[0 0 0]);
3053             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 ____'),'ForegroundColor',[0 0 0]);
3054             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 ____'),'ForegroundColor',[0 0 0]);
3055             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 ____'),'ForegroundColor',[0 0 0]);
3056
3057             %pause(0);
3058
3059         catch
3060
3061             % GUI must have been closed
3062
3063         end
3064
3065
3066         % Reset Bergoz BPM time constant to whatever it was before feedback started
3067         fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
3068         setbpmtimeconstant(BPMtimeconstantOFB);
3069
3070
3071         a = clock;
3072         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
3073         [StateNumber, StateString] = getsrstate;
3074         if StateNumber >= 0
3075             setpv('SR_STATE',5.1);
3076             [StateNumber, StateString] = getsrstate;
3077             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
3078             fprintf('   ******************************\n');
3079             fprintf('   **  Orbit Feedback Stopped  **\n');
3080             fprintf('   ******************************\n\n');
3081         else
3082             [StateNumber, StateString] = getsrstate;
3083             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
3084             fprintf('   ****************************************\n');
3085             fprintf('   **  Problem With Slow Orbit Feedback  **\n');
3086             fprintf('   ****************************************\n\n');
3087         end
3088         set(0,'showhiddenhandles','off');
3089         pause(0);
3090
3091
3092     case 'FeedbackSetup'
3093         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
3094
3095         if InitFlag
3096
3097
3098             % Get the device lists from oscsinit and convert to srcontrol variables
3099             [HBPM, VBPM, HCM, VCM, HSV, VSV] = ocsinit('SOFB');
3100             Xivec = 1:HSV;
3101             Yivec = 1:VSV;
3102             BPMlist1 = HBPM.DeviceList;
3103             HCMlist1 = HCM.DeviceList;
3104             VCMlist1 = VCM.DeviceList;
3105
3106
3107             OCSx.BPM = getx(BPMlist1, 'struct');
3108             OCSx.CM = getsp('HCM', HCMlist1, 'struct');
3109             OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
3110             OCSx.NIter = 1;
3111             OCSx.SVDIndex = Xivec;
3112             OCSx.IncrementalFlag = 'No';
3113             OCSx.BPMWeight = {[]};
3114             OCSx.FitRF = 0;
3115             OCSy.BPM = gety(BPMlist1, 'struct');
3116             OCSy.CM = getsp('VCM', VCMlist1, 'struct');
3117             OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
3118             OCSy.NIter = 1;
3119             OCSy.SVDIndex = Yivec;
3120             OCSy.IncrementalFlag = 'No';
3121             OCSy.BPMWeight = {[]};
3122             OCSy.FitRF = 0;
3123
3124             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
3125             % do we need these Smat calls? %
3126             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
3127             SXmat = getrespmat(OCSx.BPM, OCSx.CM, 'numeric');
3128             SYmat = getrespmat(OCSy.BPM, OCSy.CM, 'numeric');
3129             % [OCSx, Sx, Ux, Vx] = orbitcorrectionmethods(OCSx, SXmat);
3130             % [OCSy, Sy, Uy, Vy] = orbitcorrectionmethods(OCSy, SYmat);
3131
3132             % initialize FFTypeFlag
3133             FFTypeFlag = 'Global';
3134
3135             % Fit decision comes from check box
3136             if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
3137                 OCSx.FitRF = 1;
3138                 Xivec = 1:HSV+1;
3139             end
3140
3141         else
3142
3143             % Get vectors
3144             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
3145             % the two lines below seem to fix BPMlist editing problem
3146             OCSx = FB.OCSx;
3147             OCSy = FB.OCSy;
3148             BPMlist1 = FB.BPMlist1;
3149             HCMlist1 = FB.HCMlist1;
3150             VCMlist1 = FB.VCMlist1;
3151             Xivec = FB.Xivec;
3152             Yivec = FB.Yivec;
3153             Xgoal = FB.OCSx.GoalOrbit;
3154             OCSx.GoalOrbit = Xgoal;
3155             Ygoal = FB.OCSy.GoalOrbit;
3156             OCSy.GoalOrbit = Ygoal;
3157             FFTypeFlag = FB.FFTypeFlag;
3158
3159
3160             % FF corrector magnet list - only channels which are blocked when FF is running should be
3161             % listed
3162             ListFF = [
3163                 4     2
3164                 4     8
3165                 5     1
3166                 5     7
3167 %               5     8 % IVID is using digital FF, i.e. FF algorithm does not block
3168 %               6     1 % other access to PVs
3169                 6     8
3170                 7     1
3171                 7     8
3172                 8     1
3173                 8     8
3174                 9     1
3175                 9     8
3176                 10    1
3177                 11    8
3178                 12    1];
3179             ElemFF = dev2elem('HCM',ListFF);
3180
3181
3182             % Add button to change #ivectors, cm, IDBPMs,
3183             EditFlag = 0;
3184             h_fig1 = figure;
3185             while EditFlag ~= 6
3186
3187                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
3188                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
3189
3190                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
3191                     DispOrbit = getdisp('BPMx', BPMlist1);
3192                     Sx = [Sx DispOrbit];
3193                 end
3194
3195                 Sx(isnan(Sx)) = 0;
3196                 Sy(isnan(Sy)) = 0;
3197
3198                 [Ux, SVx, Vx] = svd(Sx);
3199                 [Uy, SVy, Vy] = svd(Sy);
3200
3201
3202                 % Remove singular values greater than the actual number of singular values
3203                 i = find(Xivec>length(diag(SVx)));
3204                 if ~isempty(i)
3205                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
3206                     pause(0);
3207                     Xivec(i) = [];
3208                 end
3209                 i = find(Yivec>length(diag(SVy)));
3210                 if ~isempty(i)
3211                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
3212                     pause(0);
3213                     Yivec(i) = [];
3214                 end
3215
3216
3217                 Ax = Sx*Vx(:,Xivec);
3218                 Tx = inv(Ax'*Ax)*Ax';
3219
3220                 Ay = Sy*Vy(:,Yivec);
3221                 Ty = inv(Ay'*Ay)*Ay';
3222
3223                 figure(h_fig1);
3224                 subplot(2,1,1);
3225                 semilogy(diag(SVx),'b');
3226                 hold on;
3227                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
3228                 ylabel('Horizontal');
3229                 title('Response Matrix Singular Values');
3230                 hold off;
3231                 subplot(2,1,2);
3232                 semilogy(diag(SVy),'b');
3233                 hold on;
3234                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
3235                 xlabel('Singular Value Number');
3236                 ylabel('Vertical');
3237                 hold off;
3238                 drawnow;
3239
3240                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List', ...
3241                     'BPM List','Change the Goal Orbit','Continue');
3242
3243                 if EditFlag == 1
3244                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
3245                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
3246                     titlestr='SVD Orbit Feedback';
3247                     lineNo=1;
3248                     answer=inputdlg(prompt,titlestr,lineNo,def);
3249                     if ~isempty(answer)
3250                         XivecNew = fix(str2num(answer{1}));
3251                         if isempty(XivecNew)
3252                             disp('   Horizontal E-vector cannot be empty.  No change made.');
3253                         else
3254                             if any(XivecNew<=0) || max(XivecNew)>length(diag(SVx))
3255                                 disp('   Error reading horizontal E-vector.  No change made.');
3256                             else
3257                                 Xivec = XivecNew;
3258                             end
3259                         end
3260                         YivecNew = fix(str2num(answer{2}));
3261                         if isempty(YivecNew)
3262                             disp('   Vertical E-vector cannot be empty.  No change made.');
3263                         else
3264                             if any(YivecNew<=0) || max(YivecNew)>length(diag(SVy))
3265                                 disp('   Error reading vertical E-vector.  No change made.');
3266                             else
3267                                 Yivec = YivecNew;
3268                             end
3269                         end
3270                     end
3271                 end
3272
3273                 if EditFlag == 2
3274                     List= getlist('HCM','Trim');
3275                     CheckList = zeros(96,1);
3276                     Elem = dev2elem('HCM', HCMlist1);
3277                     CheckList(Elem) = ones(size(Elem));
3278                     CheckList = CheckList(dev2elem('HCM',List));
3279
3280                     % Remove FF corrrectors
3281                     %           Elem = dev2elem('HCM',List);
3282                     %           for j = length(ElemFF):-1:1
3283                     %              i = find(Elem==ElemFF(j));
3284                     %              Elem(i,:) = [];
3285                     %              List(i,:) = [];
3286                     %              CheckList(i,:) = [];
3287                     %           end
3288
3289                     newList = editlist(List, 'HCMtrim', CheckList);
3290
3291                     if isempty(newList)
3292                         fprintf('   WARNING: Horizontal corrector magnet list is empty!\n');
3293                         HCMlist1 = newList;
3294                     else
3295                         HCMlist1 = newList;
3296                     end
3297                     OCSx.CM.DeviceList = HCMlist1;
3298                 end
3299
3300                 if EditFlag == 3
3301                     List = getlist('VCM','Trim');
3302                     CheckList = zeros(96,1);
3303                     Elem = dev2elem('VCM', VCMlist1);
3304                     CheckList(Elem) = ones(size(Elem));
3305                     CheckList = CheckList(dev2elem('VCM',List));
3306
3307                     % Remove FF corrrectors
3308                     %           Elem = dev2elem('VCM',List);
3309                     %           for j = length(ElemFF):-1:1
3310                     %              i = find(Elem==ElemFF(j));
3311                     %              Elem(i,:) = [];
3312                     %              List(i,:) = [];
3313                     %              CheckList(i,:) = [];
3314                     %           end
3315
3316                     newList = editlist(List, 'VCMtrim', CheckList);
3317
3318                     if isempty(newList)
3319                         fprintf('   WARNING: Vertical corrector magnet list is empty!\n');
3320                         VCMlist1 = newList;
3321                     else
3322                         VCMlist1 = newList;
3323                     end
3324                     OCSy.CM.DeviceList = VCMlist1;
3325                 end
3326
3327                 if EditFlag == 4
3328                     ListOld = BPMlist1;
3329                     XgoalOld = Xgoal;
3330                     YgoalOld = Ygoal;
3331
3332                     % Full BPM list
3333                     List = getbpmlist('Bergoz');
3334
3335                     CheckList = zeros(size(List,1),1);
3336                     if ~isempty(BPMlist1)
3337                         for i = 1:size(List,1)
3338                             k = find(List(i,1)==BPMlist1(:,1));
3339                             l = find(List(i,2)==BPMlist1(k,2));
3340
3341                             if isempty(k) || isempty(l)
3342                                 % Item not in list
3343                             else
3344                                 CheckList(i) = 1;
3345                             end
3346                         end
3347                     end
3348
3349                     newList = editlist(List, 'BPM', CheckList);
3350                     if isempty(newList)
3351                         fprintf('   BPM list cannot be empty.  No change made.\n');
3352                     else
3353                         BPMlist1 = newList;
3354                     end
3355
3356                     % Set the goal orbit to the golden orbit
3357                     Xgoal = getgolden('BPMx', BPMlist1);
3358                     Ygoal = getgolden('BPMy', BPMlist1);
3359
3360
3361                     % If a new BPM is added, then set the goal orbit to the golden orbit
3362                     for i = 1:size(BPMlist1,1)
3363
3364                         % Is it a new BPM?
3365                         k = find(BPMlist1(i,1)==ListOld(:,1));
3366                         l = find(BPMlist1(i,2)==ListOld(k,2));
3367
3368                         if isempty(k) || isempty(l)
3369                             % New BPM
3370                         else
3371                             % Use the old value for old BPM
3372                             Xgoal(i) = XgoalOld(k(l));
3373                             Ygoal(i) = YgoalOld(k(l));
3374                         end
3375                     end
3376                     OCSx.BPM.DeviceList = BPMlist1;
3377                     OCSy.BPM.DeviceList = BPMlist1;
3378                     OCSx.GoalOrbit = Xgoal;
3379                     OCSy.GoalOrbit = Ygoal;
3380                 end
3381
3382                 if EditFlag == 5
3383                     ChangeList = editlist2(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
3384
3385                     for i = 1:size(ChangeList,1)
3386
3387                         k = find(ChangeList(i,1)==BPMlist1(:,1));
3388                         l = find(ChangeList(i,2)==BPMlist1(k,2));
3389
3390                         prompt={sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
3391                         def={sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
3392                         titlestr='CHANGE THE GOAL ORBIT';
3393                         lineNo=1;
3394                         answer = inputdlg(prompt, titlestr, lineNo, def);
3395
3396                         if isempty(answer)
3397                             % No change
3398                             fprintf('   No change was made to the golden orbit.\n');
3399                         else
3400                             Xgoalnew = str2num(answer{1});
3401                             if isempty(Xgoalnew)
3402                                 fprintf('   No change was made to the horizontal golden orbit.\n');
3403                             else
3404                                 Xgoal(k(l)) = Xgoalnew;
3405                             end
3406
3407                             Ygoalnew = str2num(answer{2});
3408                             if isempty(Ygoalnew)
3409                                 fprintf('   No change was made to the vertical golden orbit.\n');
3410                             else
3411                                 Ygoal(k(l)) = Ygoalnew;
3412                             end
3413                         end
3414                     end
3415                     if ~isempty(ChangeList)
3416                         fprintf('   Note:  Changing the goal orbit for "Slow Orbit Feedback" does not change the goal orbit for "Orbit Correction."\n');
3417                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
3418                     end
3419                     OCSx.GoalOrbit = Xgoal;
3420                     OCSy.GoalOrbit = Ygoal;
3421                 end
3422
3423 %                 if EditFlag == 6
3424 %                     FFTypeFlag = questdlg(sprintf('Do you want to use a fully local or a combined local/global compensation of IDs? (nuy=9.2 only)'),'Tune FF','Local','Global', 'Global');
3425 %                     if strcmp(FFTypeFlag,'Local')
3426 %                         disp(['   The tune FF will use 8 local quadrupoles to compensate beta beating and tune shift']);
3427 %                         disp(['   from each ID.']);
3428 %                     elseif strcmp(FFTypeFlag,'Global')
3429 %                         disp(['   The tune FF will use 4 local quadrupoles to compensate beta beating and all QF+QD']);
3430 %                         disp(['   to compensate tune shift from each ID.']);
3431 %                     end
3432 %                 end
3433
3434             end
3435             close(h_fig1);
3436         end
3437
3438         % Save vectors
3439         FB.Xivec = Xivec;
3440         FB.Yivec = Yivec;
3441         FB.HCMlist1 = HCMlist1;
3442         FB.VCMlist1 = VCMlist1;
3443         FB.BPMlist1 = BPMlist1;
3444
3445         OCSx.SVDIndex = Xivec;
3446         OCSy.SVDIndex = Yivec;
3447         FB.OCSx = OCSx;
3448         FB.OCSy = OCSy;
3449
3450         FB.FFTypeFlag = FFTypeFlag;
3451         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata',FB);
3452
3453
3454     case 'FastFeedbackSetup'
3455
3456         InitFlag = Input2;
3457
3458         if InitFlag
3459             FOFBFreq = 1000;
3460             % user operations 9/14-10/17/04: P=0.5, I=120, D=0.0015 (for both planes)
3461             % below are known good values for user ops as of 8-1-05
3462             HorP = 2;
3463             HorI = 300;
3464             HorD = 0.002;
3465             VertP = 1;
3466             VertI = 100;
3467             VertD = 0.0015;
3468
3469             % this initial set is now done in hwinit.m because it's not a good idea to set anything when srcontrol is launched
3470             % try
3471             %     setsp('SR01____FFBFREQAC00', FOFBFreq); % set freq
3472             %     write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3473             % catch
3474             %     disp('   Trouble setting Fast Orbit Feedback parameters!');
3475             % end
3476
3477         else
3478             % Get vectors
3479             FOFB = get(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata');
3480             FOFBFreq = FOFB.FOFBFreq;
3481             HorP  = FOFB.HorP;
3482             HorI  = FOFB.HorI;
3483             HorD  = FOFB.HorD;
3484             VertP = FOFB.VertP;
3485             VertI = FOFB.VertI;
3486             VertD = FOFB.VertD;
3487
3488             % Add button to change #ivectors, CMs, IDBPMs,
3489             EditFlag = 0;
3490             %h_fig1 = figure;
3491             while EditFlag ~= 3
3492
3493                 %EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'HCM List', 'VCM List', ...
3494                 %   'IDBPM List', 'BBPM List', 'Continue');
3495                 % Use menu below until other FFB config routines work (then also uncomment options 3,4,5,6 below)
3496                 EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'Continue');
3497
3498                 if EditFlag == 1
3499                     % change rate
3500
3501                     prompt={'Enter the desired Fast Feedback Frequency (1-1000 Hz)'};
3502                     def={num2str(FOFBFreq)};
3503                     titlestr='Fast Feedback Setup';
3504                     lineNo=1;
3505                     answer=inputdlg(prompt,titlestr,lineNo,def);
3506                     if ~isempty(answer)
3507                         FOFBFreq = fix(str2num(answer{1}));
3508                         if isempty(FOFBFreq)
3509                             disp('   Frequency value cannot be empty.  No change made.');
3510                             FOFBFreq = getsp('SR01____FFBFREQAC00');
3511                         else
3512                             if FOFBFreq < 1 || FOFBFreq > 1000
3513                                 disp('   Frequency must be between 1 and 1000 Hz.  No change made.');
3514                                 FOFBFreq = getsp('SR01____FFBFREQAC00');
3515                             end
3516                         end
3517                         setsp('SR01____FFBFREQAC00',FOFBFreq); % change freq
3518                         pause(0.5);
3519                         fprintf('   Fast orbit feedback frequency is running at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
3520                     else
3521                         FOFBFreq = getsp('SR01____FFBFREQAC00');
3522                     end
3523                 end
3524
3525                 if EditFlag == 2
3526                     % edit  PIDs
3527                     % User defaults are HorP=2, HorI=300, HorD=0.002, VertP=1, VertI=100, VertD=0.0015
3528                     prompt={'P horizontal', 'I horizontal', 'D horizontal', 'P vertical', 'I vertical', 'D vertical'};
3529                     def={num2str(HorP), num2str(HorI), num2str(HorD), num2str(VertP), num2str(VertI), num2str(VertD)};
3530                     titlestr='Fast Feedback PID Setup';
3531                     lineNo=1;
3532                     answer=inputdlg(prompt,titlestr,lineNo,def);
3533                     if ~isempty(answer)
3534                         HorPnewnum = str2num(answer{1});
3535                         if isempty(HorPnewnum)
3536                             disp('   HorP value cannot be empty.  No change made.');
3537                         else
3538                             HorP = HorPnewnum;
3539                         end
3540                         HorInewnum = str2num(answer{2});
3541                         if isempty(HorInewnum)
3542                             disp('   HorI value cannot be empty.  No change made.');
3543                         else
3544                             HorI = HorInewnum;
3545                         end
3546                         HorDnewnum = str2num(answer{3});
3547                         if isempty(HorDnewnum)
3548                             disp('   HorD value cannot be empty.  No change made.');
3549                         else
3550                             HorD = HorDnewnum;
3551                         end
3552                         VertPnewnum = str2num(answer{4});
3553                         if isempty(VertPnewnum)
3554                             disp('   VertP value cannot be empty.  No change made.');
3555                         else
3556                             VertP = VertPnewnum;
3557                         end
3558                         VertInewnum = str2num(answer{5});
3559                         if isempty(VertInewnum)
3560                             disp('   VertI value cannot be empty.  No change made.');
3561                         else
3562                             VertI = VertInewnum;
3563                         end
3564                         VertDnewnum = str2num(answer{6});
3565                         if isempty(VertDnewnum)
3566                             disp('   VertD value cannot be empty.  No change made.');
3567                         else
3568                             VertD = VertDnewnum;
3569                         end
3570
3571                         try
3572                             write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3573                             fprintf('   Setting FFB gains to Horizontal P=%.2f, I=%.1f, D=%.4f;  Vertical P=%.2f, I=%.1f, D=%.4f\n', HorP, HorI, HorD, VertP, VertI, VertD);
3574                         catch
3575                             disp('   Trouble setting Fast Orbit Feedback parameters!');
3576                         end
3577                     end
3578                 end
3579
3580                 %if EditFlag == 3
3581                 %   disp('   This function not yet available.');
3582                 %   % change HCM List
3583                 %end
3584                 %
3585                 %if EditFlag == 4
3586                 %   disp('   This function not yet available.');
3587                 %   % change VCM List
3588                 %end
3589                 %
3590                 %if EditFlag == 5
3591                 %   disp('   This function not yet available.');
3592                 %   % change IDBPM List
3593                 %end
3594                 %
3595                 %if EditFlag == 6
3596                 %   disp('   This function not yet available.');
3597                 %   % change BBPM List
3598                 %end
3599
3600             end
3601             %close(h_fig1);
3602         end
3603
3604         % Save vectors
3605         FOFB.FOFBFreq = FOFBFreq;
3606         FOFB.HorP = HorP;
3607         FOFB.HorI = HorI;
3608         FOFB.HorD = HorD;
3609         FOFB.VertP = VertP;
3610         FOFB.VertI = VertI;
3611         FOFB.VertD = VertD;
3612         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata',FOFB);
3613
3614     otherwise
3615         fprintf('   No action for %s.\n', action);
3616 end   % end case