Description of srcontrol5_pre20080731
Home > ALS > StorageRing > srcontrol5_pre20080731.m
srcontrol5_pre20080731
PURPOSE
srcontrol5
SYNOPSIS
function srcontrol5(action, Input2, Input3)
DESCRIPTION
 srcontrol5
 Storage ring control program
 This program controls all storage ring magnets, performs orbit feedback and
 tune feedforward and helps to diagnose problems in routine user operation
 of the ALS storage ring. It includes a gui to simplify the use of this
 program.
 It was originally programmed by Greg Portmann (until December 2000) with input
 from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
 and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
 The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
 Christoph Steier, July 2002
 SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
 Tom Scarvie, April 2005
CROSS-REFERENCE INFORMATION
This function calls:
amp2k AMP2K - Converts amperes to simulator values
bend2gev BEND2GEV - Compute the energy based on the ramp tables
checksrmags CHECKSRMAGS - Check SR power supplies against a lattice file
checksrorbit ErrorNums =checksrorbit(Sector, BPMxtolerance [.015 mm], [BPMytolerance [.015 mm]])
gap2tune GAP2TUNE - Computes the vertical tune shift for a insertion device gap change.
gaplimit [GapMin, GapMax] = gaplimit(DeviceList)
getbpmlist GETBPMLIST - Return a BPM list based on key words and sector numbers
getbpmtimeconstant GETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
getff GETFF - Get the state of insertion device feed forward and user gap contr5ol
getid GETID - Get the insertion device position, velocity, run flag, and user requested gap
getsrstate [StateNumber, StateString] = getsrstate
ocsinit OCSINIT - Corrector and BPM
set_alarmhandler_AHU_thresholds_inject function set_alarmhandler_AHU_thresholds_inject
set_etaywave_nuy9_20skews_skewFF function [SQSFincr, SQSDincr] = set_etaywave_nuy9_20skews_skewFF(scale);
setbpmtimeconstant SETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
setbumps SETBUMPS - Make a straight section bump
setff function setff(DeviceList, FFEnableBC, GapEnableBC)
setid SETID - Set the insertion device vertical gap
setsrstatechannels
shift2tune SHIFT2TUNE - Computes the horizontal tune shift for a EPU gap and horizontal shift
srcycle SRCYCLE - Storage ring cycle
srramp SRRAMP - Ramp the storage ring energy
write_goldenorbit_ffb function write_goldenorbit_ffb
write_goldenorbit_ffb_2planes WRITE_GOLDENORBIT_FFTB_2PLANES - Sets the BPM setpoints which are used by the fast feedback system
This function is called by:
SOURCE CODE
function srcontrol5(action, Input2, Input3)
% srcontrol5
% Storage ring control program
%
% This program controls all storage ring magnets, performs orbit feedback and
% tune feedforward and helps to diagnose problems in routine user operation
% of the ALS storage ring. It includes a gui to simplify the use of this
% program.
%
% It was originally programmed by Greg Portmann (until December 2000) with input
% from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
% and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
%
% The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
%
% Christoph Steier, July 2002
%
% SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
%
% Tom Scarvie, April 2005
% known bugs/problems (May 2001):
% - IDBPM averaging might be a bit too long for orbit feedback
%        solved after Superbend shutdown ... Instead of averaging, digital low pass filters are used
% - gap2tune does not give correct answers for wiggler and potentially other IDs -> orbit feedback
%        seems to be OK for other IDs, has been corrected for wiggler (fit to insertion device
%        compensation table)
% - chicanes do not work in orbit feedback
%        solved. One problem was that orbit response matrizes were mis-scaled by factor of two.
%        Second problem was different time constant of power supply control. Solved by moving controls
%        of center chicanes to cPCI (and magnets are fast, hysteresis free, aircore coils).
%        Center chicane in sector 4 is now routinely used in orbit feedback. Sector 11 to follow soon.
% - zero reading of ID gap dumps beam
%        solved in srcontrol5, still a problem in srcontrol5_hightune (but that routine has to be completely
%        rewritten because of all recent changes to srcontrol5, anyhow). For gap readings below the minimum
%        allowed gap for a device, the tune feedforward disables itself.
% - cycling of lattice causes frequent power supply failures
%        solved by changing the cycling procedure. 1.5 GeV operation is now on the upper hysteresis branch
%        as was the 1.9 GeV injection lattice before.
% - frequently stalled data in IDBPM readout
%        solved with new BPM readouts and digital filtering. Seems to have been a resolution problem
%        of the digital averaging algorithm.
% - magnet ramp tables are not in perfect agreement with magnetic measurements
%        Does not appear to be a serious problem. Superbends are slightly out of sync with other magnets,
%        but this does not cause any negative effects while ramping.
% - no good way to operate with injection at 1.5 GeV and storage energy below that
%        There now is a reasonable way to inject at 1.5 GeV and ramp down to lower storage energy. But
%        it has to be tested again after implementing new (and more) chicanes ...
% revision history
% 2001-05-10, Christoph Steier
% check whether readback from insertion device is significantly (more than 1 mm) below minimum
% gap, to avoid false zero readings of insertion device gaps to cause the tune feed forward
% to implement false huge correction (and dump the beam). If the insertion device gap readbacks
% gets more than 1 mm below the nominal minimum gap, the routine now assumes the insertion device
% to be open.
%
% 2001-08-30 and during Superbend commissioning, Christoph Steier, Tom Scarvie, Winni Decking
% various changes have been made to incorporate the Superbends and some other new equipment
% installed in the Superbend shutdown. This included some changes to programs being called by srcontrol
% (like srload, srsave, srcycle, srramp, ...). The main changes within srcontrol were in the orbit
% correction and slow orbit feedback routines (incorporating frequency feedback, ...)
%
% 2002-05-04, Christoph Steier
% added new IDBPMs, modified orbit feedback to use trim DACs, removed LSB toggling in vertical
% orbit feedback, ...
%
% 2002-07-29, T.Scarvie
% added check of CM trim currents to warn of problems that might rail the orbit feedback
%
% 2002-07-31, Christoph Steier
% increased the gain of the RF frequency feedback from 1/50 of the gain of the horizontal
% orbit feedback to 1/20. Reason was that the frequency feedback was reacting a bit too slow if all
% insertion device gaps are closed at once at high speed at the beginning of a fill.
%
% 2002-08-05, C.Steier, T.Scarvie
% Added conditional to reduce orbit feedback gain if running in two-bunch mode
%
% 2003-06-02, T.Scarvie
% Added loop inside orbit feedback to reset the SR11 chicane M1 and M2 motors every 20s to combat drift problem
%
% 2003-06-18, C. Steier
% Disabled loop to periodically reset chicane in SR11. Al Robb replaced power supply, seems to be no problem anymore.
%
% 2004-05-10, C. Steier
% The list of all BBPMs is now set up automatically be calling getlist('BBPMx'). This way, new BBPMs have to be added
% at fewer places in the software. It should now be sufficient to modify getlist and run the orbit response matrix
% rountine (getsmat) once to enable use of the new BBPMs.
%
% 2004-05-14, C. Steier
% Modified parameters for ramprate reduction (in srramp and here). Previous parameters were slightly too
% cautious. Increased initial slow ramprate to 0.4 A/s.
%
% 2004-05-14, C. Steier
% Incorporated insertion device compensation schemes for nu_y = 9.2 lattice.
%
% 2004-06-14, T.Scarvie
% Added controls for fast orbit feedback
%
% 2004-06-21, C. Steier
% Added tune feedforward (in the global tune compensation scheme for the nu_y=9.2 lattice) for the shift
% dependent tune shift of the EPUs, as well as a skew quadrupole feedforward for the EPU im sector 11
% (both only active in parallel mode so far).
%
% 2005-02-13, T.Scarvie
% Separated horizontal and vertical planes for setting Fast Feedback PIDs
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NOTES for conversion to new Middle Layer %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% We never use the gap and bump control flags - the radio buttons have been disabled -
%        should we try to keep the functionality?
%
% checksrmags
% checksrorbit(...)
% For the compiler
%#function goldenpage
%#function setoperationalmode
% Check if the AO exists
checkforao;
%%%%%%%%%%%%%%
% Initialize %
%%%%%%%%%%%%%%
global FEEDBACK_STOP_FLAG
SR_Mode = getfamilydata('OperationalMode');
SR_GEV = getfamilydata('Energy');
BSCramprate = getfamilydata('BSCRampRate');
if isnan(BSCramprate) || isempty(BSCramprate)
    BSCramprate = 0.4;
    setfamilydata(BSCramprate, 'BSCRampRate');
end
if nargin < 1
    action = 'Initialize';
end
if nargin < 2
    Input2 = 0;
end
if nargin < 3
    Input3 = 0;
end
if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
    FOFBcheckboxVal = 0;
else
    FOFBcheckboxVal = 1;
end
% if strcmp(getfamilydata('OperationalMode'), '1.5 GeV, Inject at 1.23') || strcmp(SR_Mode, '1.9 GeV, Inject at 1.353')
%     TUNEcheckboxVal = 0;
% else
TUNEcheckboxVal = 1;
% end
%%%%%%%%%%%%%%%%
% Main Program %
%%%%%%%%%%%%%%%%
switch(action)
    case 'StopOrbitFeedback'
        FEEDBACK_STOP_FLAG = 1;
    case 'Initialize'
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % GUI
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        ButtonWidth = 200;
        ButtonHeight  = 25;
        Offset1 = 8*25+12 + 47 + 25+25;
        Offset2 = 47+25+25;
        Offset3 = 45+25;
        Offset4 = 1;
        Offset5 = 30;
        FigWidth = ButtonWidth+6;
        FigHeight  = 3+9*(ButtonHeight+6)+24+Offset1;
        ButtonWidth = 200-6;
        % Change figure position
        set(0,'Units','pixels');
        p=get(0,'screensize');
        h0 = figure( ...
            'Color',[0.8 0.8 0.8], ...
            'HandleVisibility','Off', ...
            'Interruptible', 'on', ...
            'MenuBar','none', ...
            'Name','ALS SR CONTROL', ...
            'NumberTitle','off', ...
            'Units','pixels', ...
            'Position',[30 p(4)-FigHeight-40 FigWidth FigHeight+Offset5], ...
            'Resize','off', ...
            'Tag','SRCTRLFig1');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'FontWeight','Bold', ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+8*(ButtonHeight+3)+19+19+8+Offset1  ButtonWidth 20+Offset5], ...
            'Style','text', ...
            'String','', ...
            'Tag','SRCTRLTitle');
        % Frame Box I
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+3*(ButtonHeight+3)+Offset1-3+Offset5 ButtonWidth+6 7*ButtonHeight+18], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+9*(ButtonHeight+3)+Offset1  ButtonWidth 15+Offset5], ...
            'Style','text', ...
            'String','Lattice Setup Functions');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Cycle'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+8*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Cycle SR Lattice', ...
            'Tag','SRCTRLButton1');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Injection'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+7*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Injection', ...
            'Tag','SRCTRLButton2');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Production'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+6*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String',['Production'], ...
            'Tag','SRCTRLButton3');
        h1 = uicontrol('Parent',h0, ...
            'Callback',[...
            'fprintf(''\n'');' ...
            'disp([''   **********************************************'']);', ...
            'disp([''   **  Changing Storage Ring Operational Mode  **'']);', ...
            'disp([''   **********************************************'']);', ...
            'setoperationalmode;', ...
            'srcontrol5(''CheckInputs'');', ...
            'disp([''   ****************************'']);', ...
            'disp([''   **  Mode Change Complete  **'']);', ...
            'disp([''   ****************************'']);', ...
            'fprintf(''\n'');'], ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+5*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'Value',1, ...
            'String','Change Operational Mode', ...
            'Tag','SRCTRLButtonChangeMode');
        h1 = uicontrol(...
            'Parent',h0, ...
            'Callback', [...
            'srcontrol5(''CheckInputs'');',...
            'srcontrol5(''SRState'');'], ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+4*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Check For Problems', ...
            'Tag','SRCTRLButtonSRState');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs''); goldenpage;', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+3*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Golden Page', ...
            'Tag','SRCTRLButtonGoldenPage');
        % Frame Box II
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+9*(ButtonHeight+3)-29+Offset2+Offset5 ButtonWidth+6 2*ButtonHeight+15], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+10*(ButtonHeight+3)-10+Offset2 ButtonWidth .6*ButtonHeight+Offset5], ...
            'String','Global/Local Orbit Correction', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''OrbitCorrection'');', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+9*(ButtonHeight+3)-6+Offset2+Offset5 ButtonWidth ButtonHeight], ...
            'String','Correct Global Orbit w/ IDBPMs', ...
            'Tag','SRCTRLButtonOrbitCorrection');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''OrbitCorrectionSetup'',1);', ...
            'callback','srcontrol5(''OrbitCorrectionSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[6 9*(ButtonHeight+3)-22+Offset2+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Edit IDBPM, CM, & Local Bump Lists', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonOrbitCorrectionSetup');
        % Frame Box III
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 1*(ButtonHeight)+Offset3+Offset5-38 ButtonWidth+6 8*ButtonHeight+61], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+9*(ButtonHeight+3)+Offset3-25 ButtonWidth .55*ButtonHeight+Offset5], ...
            'String','Orbit Feedback', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+8*(ButtonHeight+3)+Offset3-18+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Slow Orbit Correction', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxSOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+7*(ButtonHeight+3)+Offset3-9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Fast Orbit Correction', ...
            'Style','checkbox', ...
            'Value',FOFBcheckboxVal,...
            'Tag','SRCTRLCheckboxFOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+6*(ButtonHeight+3)+Offset3+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct ID Tune Shift  ', ...
            'Style','checkbox', ...
            'Value',TUNEcheckboxVal,...
            'Tag','SRCTRLCheckboxTune');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+5*(ButtonHeight+3)+Offset3+9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct RF Frequency', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxRF');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''Feedback'');', ...
            'Enable','on', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[8 3+5*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Start FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStart');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''StopOrbitFeedback'');pause(0);', ...
            'Enable','off', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[.5*FigWidth+3 3+5*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Stop FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStop');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[14 4*(ButtonHeight)+Offset3+Offset5-3 ButtonWidth-14 .75*ButtonHeight], ...
            'String','Horizontal RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHorizontal');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[26 3+3.5*(ButtonHeight)+16+Offset3-25+Offset5 ButtonWidth-26 .75*ButtonHeight], ...
            'String','Vertical RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextVertical');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FeedbackSetup'',1);', ...
            'callback','srcontrol5(''FeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 3+3.5*(ButtonHeight)+.5+Offset3-25+Offset5 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit SOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFeedbackSetup');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','01 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB01');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','02 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB02');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','03 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB03');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','04 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB04');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','05 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB05');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','06 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB06');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','07 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB07');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','08 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB08');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','09 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB09');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','10 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB10');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','11 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB11');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','12 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB12');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FastFeedbackSetup'',1);', ...
            'callback','srcontrol5(''FastFeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 1*(ButtonHeight)+Offset3-3 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit FOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFastFeedbackSetup');
        % Frame Box IV
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+ButtonHeight+Offset4-14+Offset5 ButtonWidth+6 ButtonHeight+12], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+1.75*ButtonHeight+5+Offset4-21+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Storage Ring State', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHeader');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''CheckInputs'');', ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ForegroundColor','b', ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+ButtonHeight+6+3+2+Offset4-22+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','   ', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextInformation');
        % Frame Box "Close"
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 8 ButtonWidth+6 ButtonHeight+8], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'Callback','close(gcbf);', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 13 ButtonWidth ButtonHeight], ...
            'String','Close', ...
            'Tag','SRCTRLClose');
        % Update database channels
        setsrstatechannels;
        if nargout > 0
            fig = h0;
        end
    case 'Cycle'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        disp('   **************************');
        disp('   **  Storage Ring Cycle  **');
        disp('   **************************');
        a = clock; fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        BSCFlag = questdlg(sprintf('Cycle Superbend Magnets?'),'SR Cycle','Yes','No','No');
        %if strcmp(BSCFlag,'No')
        %    disp(['   ** Superbends will not be cycled. **']);
        %else
        %    disp(['   ** Superbends will be cycled during the second mini-cycle only. **']);
        %end
        ChicSQFlag = questdlg(sprintf('Cycle chicanes and skew quads and home motor chicanes?'),'SR Cycle','Yes','No','No');
        %if strcmp(ChicSQFlag,'No')
        %    disp(['   ** Chicanes and skew quads will not be cycled; motor chicanes will not be homed. **']);
        %else
        %    disp(['   ** Chicanes and skew quads will be cycled; motor chicanes will be homed. **']);
        %end
        StartFlag = questdlg(sprintf('Start %.1f GeV Cycle?',SR_GEV),'SR Cycle','Yes','No','No');
        if strcmp(StartFlag,'No')
            disp(['   ***************************']);
            disp(['   **    Cycle  Canceled    **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        end
        try
            if GapFlag
                % Make sure that the gaps are open with FF off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open.');
                    disp('   Opening all gaps at maximum speed.');
                    setff([], 1, 0);
                    disp('   Gap control disabled.');
                    disp('   Feed forward enabled.');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened.');
                    disp('   Feed forward and gap control disabled.');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled.');
                end
            else
                disp('   Feed forward and gap control disabled.');
            end
            setff([], 0, 0);
            pause(1);
            srcycle(BSCFlag, ChicSQFlag);
            setpv('SR_STATE',1);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Cycle failed due to error condition! \n\n');
            setpv('SR_STATE',-1);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp('   **********************************************');
            disp('   **  SR Cycle complete, ready for injection  **');
            disp('   **********************************************'); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp('   **********************************');
            disp('   **  Problem cycling SR lattice  **');
            disp('   **********************************'); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
    case 'Injection'
        AD = getad;
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            fprintf('   ***************************************************\n');
            fprintf('   **  Setup For %.2f GeV Injection (with ramping)  **\n', getfamilydata('InjectionEnergy'));
            fprintf('   ***************************************************\n');
            set_alarmhandler_AHU_thresholds_inject;
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',getfamilydata('InjectionEnergy')),'Injection Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            fprintf('   *************************************************\n');
            fprintf('   **  Setup For On Energy Injection at %.2f GeV  **\n', SR_GEV);
            fprintf('   *************************************************\n');
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',SR_GEV),'Injection Setup','Yes','Cancel','Cancel');
        end
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if strcmp(StartFlag,'Cancel')
            disp(['   ********************************']);
            disp(['   **  Injection Setup Canceled  **']);
            disp(['   ********************************']);
            %set_alarmhandler_thresholds_new;
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                setff([],1,0);
                disp('   Gap control disabled');
                disp('   Feed forward enabled');
                pause(1);
                % Set IDs at max velocity w/ velocity profile off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    disp('   Opening all gaps');
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                end
                disp('   Gaps are open');
                disp('   Feed forward and gap control disabled');
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            if (AD.Energy-AD.InjectionEnergy) > 0.05
                % Ramp down to Injection Energy
                set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String','Ramping Down','ForegroundColor','b');
                drawnow;
                ErrorFlag = srramp('Injection');
                if ErrorFlag
                    error('Superbends over temperature.');
                end
                a = clock; fprintf('   %s %d:%d:%.0f\n\n',date, a(4), a(5), a(6));
            elseif (AD.Energy-AD.InjectionEnergy) < -0.05
                % first load injection lattice, then ramp to 1.9 GeV and back to 1.5 GeV to get onto same hysteresis branch
                srload('Injection');
                % load 1.9 GeV lattice
                tempfilename = sprintf('%s19nuy9prod.mat', getfamilydata('Directory','OpsData'));
                srload(tempfilename);
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                pause(5);
            end
            srload('Injection');
            setpv('SR_STATE',2);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Injection lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-2);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            if AD.Energy <= 1.5
                disp(['   *******************************************************************************']);
                disp(['   **  Function complete:  the storage ring is setup for injection at ',sprintf('%.2f',SR_GEV),' GeV  **']);
                disp(['   *******************************************************************************']);
                fprintf('\n');
            else
                fprintf('   **********************************************************************************************\n');
                fprintf('   **  Function complete:  the storage ring is setup for injection at %.2f GeV (upper branch)  **\n', getfamilydata('InjectionEnergy'));
                fprintf('   **********************************************************************************************\n');
                fprintf('\n');
            end
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   ************************************']);
            disp(['   **  Problem with injection setup  **']);
            disp(['   ************************************']);
            fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        %soundchord;
        setfamilydata(0.8, 'BSCRampRate');
    case 'Production'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        AD=getad;
        fprintf('\n');
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            disp('   ********************************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation (with ramping)  **',SR_GEV));
            disp('   ********************************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            disp('   *****************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation  **',SR_GEV));
            disp('   *****************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Yes','Cancel','Cancel');
        end
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if strcmp(StartFlag,'Cancel')
            disp(['   ***************************']);
            disp(['   **  User Setup Canceled  **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                % Make sure that the gaps are open
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open');
                    disp('   Opening all gaps at maximum speed');
                    setff([], 1, 0);
                    disp('   Gap control disabled');
                    disp('   Feed forward enabled');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened');
                    disp('   Feed forward and gap control disabled');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled');
                end
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            %%%%%%%%%%%%%%%
            if (AD.Energy-AD.InjectionEnergy) > 0.05
                % Ramp up to the production lattice
                set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String','Ramping Up','ForegroundColor','b');
                drawnow;
                ErrorFlag = srramp('Production');
                if ErrorFlag
                    error('Superbends over temperature.');
                end
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                srload('Production');
            elseif abs(AD.Energy-AD.InjectionEnergy) < 0.05
                % load production lattice - no ramp required
                srload('Production');
                %a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                pause(1);
            end
            %%%%%%%%%%%%%%%
            if GapFlag
                setff([], 1, 0);
                disp('   Gap control disabled');
                disp('   Feed forward enable');
                pause(1);
                disp('   Insertion device velocity profile boolean control off');
                disp('   Closing all gaps at maximum speed');
                % Set IDs at max velocity w/ velocity profile off
                [Position, Velocity, RunFlag, UserGap] = getid;
                setid([], UserGap, maxsp('IDvel'), 1, 0, 1);
                % Turn velocity profile on
                disp('   Insertion device velocity profile boolean control is on');
                setid([], [], maxsp('IDvel'), 1, 1, 0);
                disp('   Gaps are closed');
                setff([4;7;8;9;10;12], 1, 1);
                setff(5, 1, 0);
                disp('   Gap control enabled (except sector 5 (W16))');
            end
            %set_alarmhandler_thresholds_new;
            setpv('SR_STATE',3);
        catch
            fprintf('   %s \n', lasterr);
            fprintf('   User lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-3);
        end
        %give JH scrapers a chance to move
        % pause(15);
        a = clock;
        datestr1 = date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp(['   **************************************************************************']);
            disp(['   **  Function complete:  the storage ring is setup for users at ',sprintf('%.1f',SR_GEV),' GeV  **']);
            disp(['   **************************************************************************']);
            fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   *************************************']);
            disp(['   **  Problem with production setup  **']);
            disp(['   *************************************']);
            fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        setfamilydata(0.8, 'BSCRampRate');
%         % for BL6.0.x, set lower setpoint limit for IVID to 12.5mm until beamlines are surveyed below that value
%         try
%             scaput('SR06U___GDS1PS_AC00.DRVL',12.5);
%             disp('  Setting SR06U___GDS1PS_AC00.DRVL to 12.5mm (lower limit for IVID');
%         catch
%             fprintf('   %s \n',lasterr);
%             disp('  Trouble setting lower limit for IVID to 12.5mm!');
%         end
    case 'CheckInputs'
        SR_GEV = getfamilydata('Energy');
        AD=getad;
        setsrstatechannels;
        set(0,'showhiddenhandles','on');
        if AD.Energy > 1.55 & AD.InjectionEnergy < 1.55
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Down)']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users (Ramp Up)']);
1000         elseif AD.Energy < 1.45
1001             set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Up+cycle)']);
1002             set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV (Ramp Down)']);
1003         else
1004             set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection']);
1005             set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV']);
1006         end
1007         set(findobj('Tag','SRCTRLTitle'),'String',SR_Mode);
1008
1009         [StateNumber, StateString] = getsrstate;
1010         if StateNumber >= 0
1011             set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1012         else
1013             set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1014         end
1015
1016         set(0,'showhiddenhandles','off');
1017
1018
1019     case 'SRState'
1020         NumErrors = 0;
1021         fprintf('\n');
1022         disp('   ***********************************');
1023         disp('   **  Checking Storage Ring State  **');
1024         disp('   ***********************************');
1025         a = clock;
1026         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1027
1028         %       FileName = getpv('SR_LATTICE_FILE','String');   % Last srload file name (in OLD MIDDLE LAYER nomenclature!!)
1029
1030         GeVnow = bend2gev;
1031         if GeVnow == getfamilydata('Energy')
1032             [ConfigSetpoint, ConfigMonitor, FileName] = getproductionlattice;
1033         elseif GeVnow == getfamilydata('InjectionEnergy')
1034             [ConfigSetpoint, ConfigMonitor, FileName] = getinjectionlattice;
1035         else
1036             FileName = '';
1037         end
1038
1039         [StateNumber, StateString] = getsrstate;
1040         fprintf('   Storage ring operational mode: %s\n', SR_Mode);
1041         if StateNumber < 0
1042             fprintf('   Storage ring state error: %s\n', StateString);
1043             NumErrors = NumErrors + 1;
1044         else
1045             fprintf('   Storage ring state: %s\n', StateString);
1046         end
1047         if StateNumber==0
1048             % Storage ring state unknown
1049             NumErrors = NumErrors + 1;
1050         elseif abs(StateNumber)==1 || abs(StateNumber)==2
1051             FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','InjectionFile') '.mat'];
1052             if ~strcmp(FileName, FileNameGoal)
1053                 fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','InjectionFile'), FileName);
1054                 NumErrors = NumErrors + 1;
1055             end
1056         else
1057             FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile') '.mat'];
1058             if ~strcmp(FileName, FileNameGoal)
1059                 fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','LatticeFile'), FileName);
1060                 NumErrors = NumErrors + 1;
1061             end
1062         end
1063
1064
1065         % Check all SR magnets
1066         if isempty(FileName)
1067             fprintf('   Goal setpoints will not be checked since the last lattice load is unknown.\n');
1068             NumErrors1 = checksrmags('');
1069         else
1070 %            NumErrors1 = checksrmags([getfamilydata('Directory','OpsData') FileName]);
1071             NumErrors1 = checksrmags(FileName);
1072         end
1073         if NumErrors1 == 0
1074             fprintf('   SR magnets power supplies are OK.\n');
1075         end
1076         NumErrors = NumErrors + NumErrors1;
1077
1078
1079         % Check RF frequency
1080         if isempty(FileName)
1081             fprintf('   RF frequency will not be checked since the last lattice load is unknown.\n');
1082         else
1083 %            load([getfamilydata('Directory','OpsData'), FileName]);
1084             load(FileName);
1085             [tmp, RFHPCounterPresent] = getrf;
1086             if abs(RFHPCounterPresent-ConfigSetpoint.RF.Setpoint.Data) > .002
1087                 NumErrors = NumErrors + 1;
1088                 fprintf('   RF frequency should be %f, presently it is %f MHz (as measured by the HP counter).\n', ConfigSetpoint.RF.Setpoint.Data, RFHPCounterPresent);
1089             else
1090                 fprintf('   RF frequency is OK (HP counter is %f MHz, at the time of the lattice save it was %f MHz).\n', RFHPCounterPresent, ConfigSetpoint.RF.Setpoint.Data);
1091             end
1092         end
1093
1094
1095         % Check for orbit problems
1096         if (StateNumber >= 3) && (getdcct > 2)   % Production lattice is loaded with beam in the machine
1097             Xtol = 0.070;
1098             Ytol = 0.010;
1099             NumErrors1 = checksrorbit([],Xtol,Ytol);
1100             if NumErrors1
1101                 fprintf('   SR orbit in the ID straight sections or at Bergoz BPMs deviates more than allowed from the golden orbit.\n');
1102             else
1103                 fprintf('   SR orbit in the ID straight sections and at Bergoz BPMs is OK.\n');
1104                 fprintf('   The orbit is within %.3f mm horizontally and %.3f mm vertically', Xtol, Ytol);
1105             end
1106             NumErrors = NumErrors + NumErrors1;
1107         else
1108             fprintf('   Storage ring orbit was not checked.\n');
1109         end
1110
1111
1112         a = clock;
1113         datestr1=date;
1114         fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
1115         if NumErrors
1116             disp('   *********************************');
1117             disp('   **  Storage Ring Has Problems  **');
1118             disp('   *********************************');
1119         else
1120             disp('   **********************************');
1121             disp('   **  Storage Ring Lattice is OK  **');
1122             disp('   **********************************');
1123         end
1124         fprintf('   \n');
1125
1126         set(0,'showhiddenhandles','on');
1127         [StateNumber, StateString] = getsrstate;
1128         if StateNumber >= 0
1129             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1130         else
1131             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1132         end
1133         set(0,'showhiddenhandles','off');
1134
1135
1136     case 'OrbitCorrection'
1137         fprintf('\n');
1138         fprintf('   *********************************\n');
1139         fprintf('   **  Starting Orbit Correction  **\n');
1140         fprintf('   *********************************\n');
1141         a = clock;
1142         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1143
1144         StartFlag = questdlg(sprintf('Start orbit correction, %.1f GeV?',SR_GEV),'Orbit Correction','Yes','No','No');
1145         if strcmp(StartFlag,'No')
1146             disp(['   ********************************']);
1147             disp(['   **  Orbit Correction Aborted  **']);
1148             disp(['   ********************************']);
1149             fprintf('\n');
1150             return
1151         end
1152
1153         if getdcct < 2     % Don't correct the orbit if the current is too small
1154             fprintf('   Orbit not corrected due to small current.\n');
1155             return
1156         end
1157
1158 %         if abs(SR_GEV-bend2gev(getpv('BEND','Setpoint',[1 1])))>  0.05     % Don't use this routine for the injection lattice
1159 %             fprintf('   This routine should only be used for the production energy: Correction aborted\n');
1160 %             return
1161 %         end
1162
1163         SR_STATE_OLD = scaget('SR_STATE');
1164         set(0,'showhiddenhandles','on');
1165         setpv('SR_STATE',4);
1166         [StateNumber, StateString] = getsrstate;
1167         if StateNumber >= 0
1168             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1169         else
1170             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1171         end
1172         set(0,'showhiddenhandles','off');
1173
1174
1175         try
1176             % save current BPM timeconstant - will reset to this after correction
1177             BPMtimeconstantOC = getbpmtimeconstant;
1178             fprintf('   Current Bergoz BPM time constant is %.1fs\n', BPMtimeconstantOC);
1179
1180             % 2 Hz update rate on IDBPMs
1181             disp('   Bergoz BPM time constant set to 0.5s.')
1182             setbpmtimeconstant(0.5)
1183             pause(2);
1184
1185
1186             % Turn off feed forward
1187             fprintf('   Turning feed forward off.\n');
1188             [FFEnableBM, FFEnableBC] = getff;
1189             setff([], 0);
1190             scasleep(.2);
1191
1192
1193             % Get vectors
1194             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1195             LocalBumplist = FB.LocalBumplist;
1196
1197         catch
1198
1199             fprintf('   %s \n',lasterr);
1200             fprintf('   Orbit correction setup failed due to error condition! \n\n');
1201             setpv('SR_STATE',-4);
1202             set(0,'showhiddenhandles','on');
1203             [StateNumber, StateString] = getsrstate;
1204             if StateNumber >= 0
1205                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1206             else
1207                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1208             end
1209             set(0,'showhiddenhandles','off');
1210
1211             % Reset BPM timeconstant to whatever it was before correction
1212             setbpmtimeconstant(BPMtimeconstantOC);
1213             fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1214             return
1215         end
1216
1217         iNotHCMChicane = find(FB.HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
1218         iHCMChicane = find(FB.HCMlist1(:,2) == 10);
1219         iNotVCMChicane = find(FB.VCMlist1(:,2) < 10);
1220         iVCMChicane = find(FB.VCMlist1(:,2) == 10);
1221
1222         fprintf('   Starting horizontal and vertical global orbit correction (SVD method).\n');
1223
1224         for iloop = 1:3
1225             try
1226                 % use the following to get corrector settings in OCS without setting them, so the values can be checked
1227                 FB.OCSx = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
1228                 FB.OCSy = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
1229                 if any(abs(FB.OCSx.CM.Delta(iNotHCMChicane)) > 5)
1230                   disp('   Orbit Correction is changing some horizontal corrector(s) > 5A!!');
1231                 end
1232                 if any(abs(FB.OCSy.CM.Delta(iNotVCMChicane)) > 5)
1233                   disp('   Orbit Correction is changing some vertical corrector(s) > 5A!!');
1234                 end
1235                 if any(abs(FB.OCSx.CM.Delta(iHCMChicane)) > 10)
1236                   disp('   Orbit Correction is changing some horizontal chicane corrector(s) > 10A!!');
1237                 end
1238                 if any(abs(FB.OCSy.CM.Delta(iVCMChicane)) > 10)
1239                     disp('   Orbit Correction is changing some vertical chicane corrector(s) > 10A!!');
1240                 end
1241
1242                 % Correct RF
1243                 rf0=getrf;
1244                 nRFsteps = 4*ceil(abs(FB.OCSx.DeltaRF/10e-6)); %added factor 4 to slow down change for laser-lock at BL11.0.1 - 3-14-08, T.Scarvie
1245                 if nRFsteps > 100
1246                     nRFsteps = 100;
1247                 end
1248                 for loop = 1:nRFsteps
1249                     steprf(FB.OCSx.DeltaRF/nRFsteps,0);
1250                 end
1251                 fprintf('   %d. nRFsteps = %d, RF change = %.1f Hz\n',iloop, nRFsteps, FB.OCSx.DeltaRF*1e6);
1252 %               fprintf('   %d. RF change = %.1f Hz, nRFsteps = %d, DelRF = %.1f Hz\n',iloop, (getrf-rf0)*1e6, nRFsteps, FB.OCSx.DeltaRF*1e6);
1253
1254                 % Correct horizontal and vertical orbits
1255                 % calculate corrections
1256                 FB.OCSx.CM.Data = FB.OCSx.CM.Data + FB.OCSx.CM.Delta;
1257                 FB.OCSy.CM.Data = FB.OCSy.CM.Data + FB.OCSy.CM.Delta;
1258                 % start vertical correctors moving
1259                 setpv(FB.OCSy.CM,0);
1260                 % Correct horizontal
1261                 setpv(FB.OCSx.CM,-1);
1262                 % Correct vertical
1263                 setpv(FB.OCSy.CM,-2);
1264
1265                 % Check for current in machine - stop orbit correction if DCCT < 5mA
1266                 if (getdcct < 2)
1267                     error('**There is less than 5mA in the machine! Stopping orbit correction.');
1268                 end
1269
1270                 % Check state of gaps - stop orbit correction if any are moving
1271                 GAPrunflag = getpv('ID','RunFlag');
1272                 if any(GAPrunflag-round(GAPrunflag))
1273                     error('**One or more of the gaps are moving! Stopping orbit correction.');
1274                 end
1275
1276                 x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
1277                 y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
1278                 fprintf('   %d. Horizontal RMS = %.3f mm\n', iloop, norm(x)/sqrt(length(x)));
1279                 fprintf('   %d.   Vertical RMS = %.3f mm\n', iloop, norm(y)/sqrt(length(y)));
1280
1281             catch
1282                 fprintf('   %s \n',lasterr);
1283                 fprintf('   Orbit correction failed due to error condition!\n  Fix the problem, reload the lattice (srload), and try again.  \n\n');
1284                 setpv('SR_STATE',-4);
1285                 set(0,'showhiddenhandles','on');
1286                 [StateNumber, StateString] = getsrstate;
1287                 if StateNumber >= 0
1288                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1289                 else
1290                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1291                 end
1292                 set(0,'showhiddenhandles','off');
1293
1294                 % Reset BPM timeconstant to whatever it was before correction
1295                 setbpmtimeconstant(BPMtimeconstantOC);
1296                 fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1297                 return
1298             end
1299         end
1300
1301
1302         % Set user bumps w/o sextupole correctors
1303         try
1304
1305             %turn up corrector speed here to quicken setting bumps
1306             HCMramprate = getpv('HCM', 'RampRate');
1307             VCMramprate = getpv('VCM', 'RampRate');
1308             setpv('HCM', 'RampRate', 10, [], 0);
1309             setpv('VCM', 'RampRate', 10, [], 0);
1310
1311             if ~isempty(LocalBumplist)
1312                 fprintf('   Setting local bumps in the straight sections.\n');
1313                 for loop = 1:size(LocalBumplist,1)
1314
1315                     % Check for current in machine - stop orbit correction if DCCT < 5mA
1316                     if (getdcct < 2)
1317                         error('** There is less than 5mA in the machine! Stopping local bumps.');
1318                     end
1319
1320                     % Check state of gaps - stop setting bumps if any are moving
1321                     GAPrunflag = getpv('ID','RunFlag');
1322                     if any(GAPrunflag-round(GAPrunflag))
1323                         error('** One or more of the gaps are moving! Stopping local bumps.');
1324                     end
1325
1326                     HCMoldsp = getsp('HCM', FB.HCMlist1);
1327                     VCMoldsp = getsp('VCM', FB.VCMlist1);
1328
1329                     if any(LocalBumplist(loop,1) == [4 6 11])
1330                         if LocalBumplist(loop,2) == 0
1331                             % Upstream bump
1332                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1333                             if isempty(iRemove)
1334                                 setbumps(LocalBumplist(loop,:), 1);
1335                             else
1336                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1337                             end
1338                         elseif LocalBumplist(loop,2) == 1
1339                             % Upstream bump
1340                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;],FB.OCSx.BPM.DeviceList);
1341                             if isempty(iRemove)
1342                                 setbumps(LocalBumplist(loop,:), 1);
1343                             else
1344                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1345                             end
1346                         else
1347                             % Downstream bump
1348                             [i, iRemove] = findrowindex([LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1349                             if isempty(iRemove)
1350                                 setbumps(LocalBumplist(loop,:), 1);
1351                             else
1352                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1353                             end
1354                         end
1355                     else
1356                         [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1357                         if isempty(iRemove)
1358                             setbumps(LocalBumplist(loop,:), 1);
1359                         else
1360                             fprintf('\n   BPMs missing from Sector %02d - skipping local bump for that sector.\n\n', LocalBumplist(loop,1));
1361                         end
1362                     end
1363
1364                     HCMnewsp = getsp('HCM', FB.HCMlist1);
1365                     VCMnewsp = getsp('VCM', FB.VCMlist1);
1366                     % Remove center chicane trim from corrector check
1367                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 5) || (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 10)
1368                         error('**Setbumps caused some corrector magnet currents to change by more than 5(Horiz)/10(Vert) A!');
1369                     end
1370                     % Now check center chicane trims
1371                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 10) || (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 15)
1372                         error('**Setbumps caused some chicane trim magnet currents to change by more than 10(Horiz)/15(Vert) A!');
1373                     end
1374                 end
1375             end
1376
1377             %restore corrector speeds
1378             setpv('HCM', 'RampRate', HCMramprate, [], 0);
1379             setpv('VCM', 'RampRate', VCMramprate, [], 0);
1380
1381         catch
1382             fprintf('   %s \n',lasterr);
1383             fprintf('   Setbumps failed due to error condition!  Fix the problem, reload the lattice (srload), and try again.\n\n');
1384             setpv('SR_STATE',-4);
1385             set(0,'showhiddenhandles','on');
1386             [StateNumber, StateString] = getsrstate;
1387             if StateNumber >= 0
1388                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1389             else
1390                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1391             end
1392             set(0,'showhiddenhandles','off');
1393
1394             % Reset BPM timeconstant to whatever it was before correction
1395             setbpmtimeconstant(BPMtimeconstantOC);
1396             fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1397             return
1398         end
1399
1400         % Reset BPM timeconstant to whatever it was before correction
1401         setbpmtimeconstant(BPMtimeconstantOC);
1402         fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1403
1404         % Turn feed forward back to it's original state
1405         if any(FFEnableBC)
1406             fprintf('   Turning feed forward back on.\n');
1407             setff([], FFEnableBC);
1408         end
1409
1410
1411         a = clock;
1412         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1413         [StateNumber, StateString] = getsrstate;
1414         set(0,'showhiddenhandles','on');
1415         if StateNumber >= 0
1416             setpv('SR_STATE',4.1);
1417             [StateNumber, StateString] = getsrstate;
1418             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1419             fprintf('   *********************************\n');
1420             fprintf('   **  Orbit Correction Complete  **\n');
1421             fprintf('   *********************************\n\n');
1422         else
1423             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1424             fprintf('   *************************************\n');
1425             fprintf('   **  Problem With Orbit Correction  **\n');
1426             fprintf('   *************************************\n\n');
1427         end
1428         set(0,'showhiddenhandles','off');
1429         pause(0);
1430
1431
1432     case 'OrbitCorrectionSetup'
1433         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
1434
1435         if InitFlag
1436             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1437             % This setup is now done in ocsinit.m %
1438             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1439             % Setup feedback elements
1440             % disp('Orbit correction condition: InitFlag=1 -- debugging message');
1441
1442             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1443             % Edit the following lists to change default configuration of Orbit Correction %
1444             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1445 %             hlist=[];vlist=[];
1446 %             for Sector =1:12
1447 %                 if Sector == 1
1448 %                     vlist = [vlist;Sector 2;Sector 4;Sector 5;Sector 8];
1449 %                     hlist = [hlist;Sector 2;Sector 7];
1450 %                 elseif Sector == 3
1451 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1452 %                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1453 %                 elseif Sector == 5
1454 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1455 %                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1456 % %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8]; %remove HCM and VCM(5,10) since corrector is not controlling starting 4-6-07
1457 % %                     hlist = [hlist;Sector 2;Sector 7];
1458 %                 elseif Sector == 10
1459 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1460 %                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1461 %                 elseif Sector == 12
1462 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 7];
1463 %                     hlist = [hlist;Sector 2;Sector 7];
1464 %                 else
1465 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8];
1466 %                     hlist = [hlist;Sector 2;Sector 7];
1467 %                 end
1468 %             end
1469 %             HCMlist1 = hlist;
1470 %             VCMlist1 = vlist;
1471 %
1472 %             BPMlist1 = [
1473 %                 1 2
1474 %                 1 5
1475 %                 1 6
1476 %                 1 10
1477 %                 2 1
1478 %                 2 5
1479 %                 2 6
1480 %                 2 9
1481 %                 3 2
1482 %                 3 5
1483 %                 3 6
1484 %                 3 10
1485 %                 3 11
1486 %                 3 12
1487 %                 4 1
1488 %                 4 5
1489 %                 4 6
1490 %                 4 10
1491 %                 5 1
1492 %                 5 5
1493 %                 5 6
1494 %                 5 10
1495 %                 5 11
1496 %                 5 12
1497 %                 6 1
1498 %                 6 5
1499 %                 6 6
1500 %                 6 10
1501 %                 7 1
1502 %                 7 5
1503 %                 7 6
1504 %                 7 10
1505 %                 8 1
1506 %                 8 5
1507 %                 8 6
1508 %                 8 10
1509 %                 9 1
1510 %                 9 5
1511 %                 9 6
1512 %                 9 10
1513 %                 10 1
1514 %                 10 5
1515 %                 10 6
1516 %                 10 10
1517 %                 10 11
1518 %                 10 12
1519 %                 11 1
1520 %                 11 5
1521 %                 11 6
1522 %                 11 10
1523 %                 12 1
1524 %                 12 5
1525 %                 12 6
1526 %                 12 9];
1527 %
1528 %             % SVD orbit correction
1529 %             Xivec = [1:28];
1530 %             Yivec = [1:51];
1531 %
1532 %
1533 %             % Look for bad status BPMs
1534 %             iStatus = family2status('BPMx', BPMlist1);
1535 %             iBad = find(~iStatus);
1536 %             BPMlist1 = BPMlist1(find(iStatus),:);
1537 %             if length(iBad)
1538 %                 fprintf('   Global Orbit Correction: %d BPMs removed for bad status\n', length(iBad));
1539 %                 Yivec = Yivec(1:end-length(iBad));
1540 %             end
1541 %
1542 %             iStatus = family2status('HCM', HCMlist1);
1543 %             iBad = find(~iStatus);
1544 %             HCMlist1 = HCMlist1(find(iStatus),:);
1545 %             if length(iBad)
1546 %                 fprintf('   Global Orbit Correction: %d HCMs removed for bad status\n', length(iBad));
1547 %             end
1548 %
1549 %             iStatus = family2status('VCM', VCMlist1);
1550 %             iBad = find(~iStatus);
1551 %             VCMlist1 = VCMlist1(find(iStatus),:);
1552 %             if length(iBad)
1553 %                 fprintf('   Global Orbit Correction: %d VCMs removed for bad status\n', length(iBad));
1554 %             end
1555
1556             % Initialize RFCorrFlag
1557             RFCorrFlag = 'Yes';
1558
1559             % Get the device lists from oscsinit and convert to srcontrol variables
1560             [HBPM, VBPM, HCM, VCM, HSV, VSV] = ocsinit('TopOfFill');
1561             if strcmpi(RFCorrFlag, 'Yes')
1562                 Xivec = 1:HSV+1;
1563             else
1564                 Xivec = 1:HSV;
1565             end
1566             Yivec = 1:VSV;
1567             BPMlist1 = HBPM.DeviceList;
1568             HCMlist1 = HCM.DeviceList;
1569             VCMlist1 = VCM.DeviceList;
1570
1571
1572             LocalBumplist = [
1573               % 1 1
1574               % 2 1
1575               % 3 1
1576                 4 1
1577               % 4 2
1578                 5 1
1579               % 6 1
1580               % 6 2
1581                 7 1
1582                 8 1
1583                 9 1
1584                 10 1
1585                 11 1
1586                 11 2
1587                 12 1
1588                 ];
1589             %LocalBumplist = []
1590
1591
1592         else
1593
1594             % Get vectors
1595             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1596             BPMlist1 = FB.BPMlist1;
1597             HCMlist1 = FB.HCMlist1;
1598             VCMlist1 = FB.VCMlist1;
1599             Xivec = FB.Xivec;
1600             Yivec = FB.Yivec;
1601             LocalBumplist = FB.LocalBumplist;
1602             Xgoal = FB.Xgoal;
1603             Ygoal = FB.Ygoal;
1604             RFCorrFlag = FB.RFCorrFlag;
1605
1606             % Add button to change #ivectors, CMs, IDBPMs,
1607             EditFlag = 0;
1608             h_fig1 = figure;
1609             while EditFlag ~= 8
1610
1611                 % Sensitivity matrix
1612                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
1613                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
1614
1615                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1616                 % Can the call below work for setting FOFB RF parameter? %
1617                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1618                 if strcmpi(RFCorrFlag, 'Yes')
1619                     Sx = [Sx getdisp('BPMx',BPMlist1)];
1620                 end
1621
1622                 Sx(isnan(Sx)) = 0;
1623                 Sy(isnan(Sy)) = 0;
1624
1625                 [Ux, SVx, Vx] = svd(Sx);
1626                 [Uy, SVy, Vy] = svd(Sy);
1627
1628
1629                 % Remove singular values greater than the actual number of singular values
1630                 i = find(Xivec>length(diag(SVx)));
1631                 if ~isempty(i)
1632                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
1633                     pause(0);
1634                     Xivec(i) = [];
1635                 end
1636                 i = find(Yivec>length(diag(SVy)));
1637                 if ~isempty(i)
1638                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
1639                     pause(0);
1640                     Yivec(i) = [];
1641                 end
1642
1643
1644                 Ax = Sx*Vx(:,Xivec);
1645                 Tx = inv(Ax'*Ax)*Ax';
1646
1647                 Ay = Sy*Vy(:,Yivec);
1648                 Ty = inv(Ay'*Ay)*Ay';
1649
1650
1651                 figure(h_fig1);
1652                 subplot(2,1,1);
1653                 semilogy(diag(SVx),'b');
1654                 hold on;
1655                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
1656                 ylabel('Horizontal');
1657                 title('Response Matrix Singular Values');
1658                 hold off;
1659                 subplot(2,1,2);
1660                 semilogy(diag(SVy),'b');
1661                 hold on;
1662                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
1663                 xlabel('Singular Value Number');
1664                 ylabel('Vertical');
1665                 hold off;
1666                 drawnow;
1667
1668                 if strcmp(RFCorrFlag,'No')
1669                     RFCorrState = 'NOT CORRECTED';
1670                 elseif strcmp(RFCorrFlag,'Yes')
1671                     RFCorrState = 'CORRECTED';
1672                 else
1673                     RFCorrState = '???';
1674                 end
1675
1676                 %         EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','HCM Chicane List','VCM Chicane List','IDBPM List','BBPM List','Change Golden Orbit',...
1677                 %            'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1678                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','BPM List','Change Golden Orbit',...
1679                     'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1680
1681                 if EditFlag == 1
1682                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
1683                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
1684                     titlestr='SVD Orbit Feedback';
1685                     lineNo=1;
1686                     answer=inputdlg(prompt,titlestr,lineNo,def);
1687                     if ~isempty(answer)
1688                         XivecNew = fix(str2num(answer{1}));
1689                         if isempty(XivecNew)
1690                             disp('   Horizontal E-vector cannot be empty.  No change made.');
1691                         else
1692                             if any(XivecNew<=0) || max(XivecNew)>length(diag(SVx))
1693                                 disp('   Error reading horizontal E-vector.  No change made.');
1694                             else
1695                                 Xivec = XivecNew;
1696                             end
1697                         end
1698                         YivecNew = fix(str2num(answer{2}));
1699                         if isempty(YivecNew)
1700                             disp('   Vertical E-vector cannot be empty.  No change made.');
1701                         else
1702                             if any(YivecNew<=0) || max(YivecNew)>length(diag(SVy))
1703                                 disp('   Error reading vertical E-vector.  No change made.');
1704                             else
1705                                 Yivec = YivecNew;
1706                             end
1707                         end
1708                     end
1709                 end
1710
1711                 if EditFlag == 2
1712                     List = getlist('HCM');
1713                     CheckList = zeros(size(List,1));
1714                     Elem = dev2elem('HCM', HCMlist1);
1715                     CheckList(Elem) = ones(size(Elem));
1716                     CheckList = CheckList(dev2elem('HCM',List));
1717                     newList = editlist(List, 'HCM', CheckList);
1718                     if isempty(newList)
1719                         fprintf('   Horizontal corrector magnet list cannot be empty.  No change made.\n');
1720                     else
1721                         HCMlist1 = newList;
1722                     end
1723                 end
1724
1725                 if EditFlag == 3
1726                     List = getlist('VCM');
1727                     CheckList = zeros(size(List,1));
1728                     Elem = dev2elem('VCM', VCMlist1);
1729                     CheckList(Elem) = ones(size(Elem));
1730                     CheckList = CheckList(dev2elem('VCM',List));
1731                     newList = editlist(List, 'VCM', CheckList);
1732                     if isempty(newList)
1733                         fprintf('   Vertical corrector magnet cannot be empty.  No change made.\n');
1734                     else
1735                         VCMlist1 = newList;
1736                     end
1737                 end
1738
1739                 if EditFlag == 4
1740                     ListOld = BPMlist1;
1741                     XgoalOld = Xgoal;
1742                     YgoalOld = Ygoal;
1743
1744                     % Full BPM list
1745                     List = getbpmlist('Bergoz');
1746 %                     List = [
1747 %                         1 2
1748 %                         1 5
1749 %                         1 6
1750 %                         1 10
1751 %                         2 1
1752 %                         2 5
1753 %                         2 6
1754 %                         2 9
1755 %                         3 2
1756 %                         3 5
1757 %                         3 6
1758 %                         3 10
1759 %                         3 11
1760 %                         3 12
1761 %                         4 1
1762 %                         4 5
1763 %                         4 6
1764 %                         4 10
1765 %                         5 1
1766 %                         5 5
1767 %                         5 6
1768 %                         5 10
1769 %                         5 11
1770 %                         5 12
1771 %                         6 1
1772 %                         6 5
1773 %                         6 6
1774 %                         6 10
1775 %                         7 1
1776 %                         7 5
1777 %                         7 6
1778 %                         7 10
1779 %                         8 1
1780 %                         8 5
1781 %                         8 6
1782 %                         8 10
1783 %                         9 1
1784 %                         9 5
1785 %                         9 6
1786 %                         9 10
1787 %                         10 1
1788 %                         10 5
1789 %                         10 6
1790 %                         10 10
1791 %                         10 11
1792 %                         10 12
1793 %                         11 1
1794 %                         11 5
1795 %                         11 6
1796 %                         11 10
1797 %                         12 1
1798 %                         12 5
1799 %                         12 6
1800 %                         12 9
1801 %                         ];
1802
1803                     CheckList = zeros(size(List,1),1);
1804                     if ~isempty(BPMlist1)
1805                         for i = 1:size(List,1)
1806                             k = find(List(i,1)==BPMlist1(:,1));
1807                             l = find(List(i,2)==BPMlist1(k,2));
1808
1809                             if isempty(k) || isempty(l)
1810                                 % Item not in list
1811                             else
1812                                 CheckList(i) = 1;
1813                             end
1814                         end
1815                     end
1816
1817                     newList = editlist(List, 'BPM', CheckList);
1818                     if isempty(newList)
1819                         fprintf('   BPM list cannot be empty.  No change made.\n');
1820                     else
1821                         BPMlist1 = newList;
1822                     end
1823
1824                     % Set the goal orbit to the golden orbit
1825                     Xgoal = getgolden('BPMx', BPMlist1);
1826                     Ygoal = getgolden('BPMy', BPMlist1);
1827
1828
1829                     % If a new BPM is added, then set the goal orbit to the golden orbit
1830                     for i = 1:size(BPMlist1,1)
1831
1832                         % Is it a new BPM?
1833                         k = find(BPMlist1(i,1)==ListOld(:,1));
1834                         l = find(BPMlist1(i,2)==ListOld(k,2));
1835
1836                         if isempty(k) || isempty(l)
1837                             % New BPM
1838                         else
1839                             % Use the old value for old BPM
1840                             Xgoal(i) = XgoalOld(k(l));
1841                             Ygoal(i) = YgoalOld(k(l));
1842                         end
1843                     end
1844                 end
1845
1846                 if EditFlag == 5
1847
1848                     ChangeList = editlist(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
1849                     for i = 1:size(ChangeList,1)
1850
1851                         k = find(ChangeList(i,1)==BPMlist1(:,1));
1852                         l = find(ChangeList(i,2)==BPMlist1(k,2));
1853
1854                         prompt = {sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
1855                         def = {sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
1856                         titlestr = 'CHANGE THE GOAL ORBIT';
1857                         lineNo = 1;
1858                         answer = inputdlg(prompt, titlestr, lineNo, def);
1859
1860                         if isempty(answer)
1861                             % No change
1862                             fprintf('   No change was made to the golden orbit.\n');
1863                         else
1864                             Xgoalnew = str2num(answer{1});
1865                             if isempty(Xgoalnew)
1866                                 fprintf('   No change was made to the horizontal golden orbit.\n');
1867                             else
1868                                 Xgoal(k(l)) = Xgoalnew;
1869                             end
1870
1871                             Ygoalnew = str2num(answer{2});
1872                             if isempty(Ygoalnew)
1873                                 fprintf('   No change was made to the vertical golden orbit.\n');
1874                             else
1875                                 Ygoal(k(l)) = Ygoalnew;
1876                             end
1877                         end
1878                     end
1879                     if ~isempty(ChangeList)
1880                         fprintf('   Note:  changing the goal orbit for "Orbit Correction" does not change the goal orbit for "Slow Orbit Feedback."\n');
1881                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
1882                     end
1883                 end
1884
1885                 if EditFlag == 6
1886                     List = [
1887                         1 1
1888                         2 1
1889                         3 1
1890                         4 1
1891                         4 2
1892                         5 1
1893                         6 1
1894                         6 2
1895                         7 1
1896                         8 1
1897                         9 1
1898                         10 1
1899                         11 1
1900                         11 2
1901                         12 1];
1902                     CheckList = zeros(size(List,1),1);
1903                     if ~isempty(LocalBumplist)
1904                         for i = 1:size(List,1)
1905                             k = find(List(i,1)==LocalBumplist(:,1));
1906                             l = find(List(i,2)==LocalBumplist(k,2));
1907
1908                             if isempty(k) || isempty(l)
1909                                 % Item not in list
1910                             else
1911                                 CheckList(i) = 1;
1912                             end
1913                         end
1914                     end
1915                     LocalBumplist = editlist2(List, 'Sector', CheckList);
1916                 end
1917
1918                 if EditFlag == 7
1919                     RFCorrFlag = questdlg(sprintf('Set RF Frequency during Orbit Correction?'),'RF Frequency','Yes','No', 'No');
1920                     if strcmp(RFCorrFlag,'No')
1921                         disp(['   RF Frequency will not be included in global orbit correction.']);
1922                     elseif strcmp(RFCorrFlag,'Yes')
1923                         disp(['   RF Frequency will be included in global orbit correction.']);
1924                     end
1925
1926                 end
1927             end
1928             close(h_fig1);
1929         end
1930
1931         %  ORBIT CORRECTION STRUCTURE (OCS)
1932         %    OCS.BPM (data structure)
1933         %    OCS.CM  (data structure)
1934         %    OCS.GoalOrbit
1935         %    OCS.NIter
1936         %    OCS.SVDIndex
1937         %    OCS.IncrementalFlag = 'Yes'/'No'
1938         %    OCS.BPMWeight
1939         %    OCS.Flags = { 'FitRF' , etc. }
1940         OCSx.BPM = getx(BPMlist1, 'struct');
1941         OCSx.CM = getsp('HCM', HCMlist1, 'struct');
1942         OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
1943         OCSx.NIter = 1;
1944         OCSx.SVDIndex = Xivec;
1945         OCSx.IncrementalFlag = 'No';
1946         OCSx.FitRF = 1;
1947         OCSy.BPM = gety(BPMlist1, 'struct');
1948         OCSy.CM = getsp('VCM', VCMlist1, 'struct');
1949         OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
1950         OCSy.NIter = 1;
1951         OCSy.SVDIndex = Yivec;
1952         OCSy.IncrementalFlag = 'No';
1953         OCSy.FitRF = 0;
1954
1955         % Save vectors
1956         FB.OCSx = OCSx;
1957         FB.OCSy = OCSy;
1958
1959         FB.BPMlist1 = BPMlist1;
1960         FB.HCMlist1 = HCMlist1;
1961         FB.VCMlist1 = VCMlist1;
1962         FB.Xivec = Xivec;
1963         FB.Yivec = Yivec;
1964         FB.Xgoal = OCSx.GoalOrbit;
1965         FB.Ygoal = OCSy.GoalOrbit;
1966         FB.RFCorrFlag = RFCorrFlag;
1967         FB.LocalBumplist = LocalBumplist;
1968         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata',FB);
1969
1970
1971     case 'Feedback'
1972
1973         FBloopIter = 1;
1974         if get(findobj(gcbf,'Tag','SRCTRLCheckboxFOFB'),'Value') == 1
1975             StartFOFBFlag = 1;
1976         else
1977             StartFOFBFlag = 0;
1978         end
1979
1980         FEEDBACK_STOP_FLAG = 0;
1981         HWarnNum=0;
1982         VWarnNum=0;
1983
1984         SR_GeV = getenergy;
1985         % Feedback loop setup
1986         PlotInfoFlag = 0;           % Plot micado stuff
1987         LoopDelay = 1.0;           % Period of feedback loop [seconds], make sure the BPM averaging is correct
1988         VCM_LSB = .00366211;
1989         VCMCHICANE_LSB = .002441;   % 80 max?,  Note: not fully implemented
1990
1991         if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
1992             Xgain  = 0.2;
1993             Ygain  = 0.1;
1994         else
1995             Xgain  = 0.8; % raised 0.5->0.8 at 17:20, 3-2-05 to more quickly correct EPU4 fast switching orbit distortions
1996             Ygain  = 0.8;
1997         end
1998
1999         % Load lattice set for tune feed forward
2000         ConfigSetpoint = getproductionlattice;
2001         %load([getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile')]);
2002         QFsp = ConfigSetpoint.QF.Setpoint.Data;
2003         QDsp = ConfigSetpoint.QD.Setpoint.Data;
2004         TuneW16Min = gap2tune([5 1], 13.23, 1.8909);
2005         % Tune response matrix
2006         SR_TUNE_MATRIX = gettuneresp({'QF','QD'}, {[],[]}, getenergy('Production'));    % Approx. [0.1944 -0.0286;-0.1182 0.1526];
2007         %SR_TUNE_MATRIX = [0.1641 -0.0245
2008         %                 -0.1149 0.1477];
2009
2010         SQSFsp = amp2k('SQSF','Setpoint',ConfigSetpoint.SQSF.Setpoint.Data);
2011         SQSDsp = amp2k('SQSD','Setpoint',ConfigSetpoint.SQSD.Setpoint.Data);
2012
2013 %         % tune FF for EPUs (data exist for 4 1 parallel, 11 1 parallel and antiparallel
2014 %         load '/home/als/physdata/matlab/srdata/gaptrack/EPU4-1_tunecomp/after_shimming/nux_map_withgaps.mat'
2015 %         dnux_epu_41_m0 = tunexmap(2:end,2:end)-tunexmap(2,12);
2016 %         [gap_epu_41,shift_epu_41]=meshgrid(tunexmap(2:end,1),tunexmap(1,2:end));
2017 %         load '/home/als/physdata/matlab/srdata/gaptrack/EPU4-1_tunecomp/after_shimming/nuy_map_withgaps.mat'
2018 %         dnuy_epu_41_m0 = tuneymap(2:end,2:end)-tuneymap(2,12);
2019 %
2020 %         load '/home/als/physdata/matlab/srdata/gaptrack/archive/epu11d1m0e19_2007-01-28.mat' tune_x tune_y Gaps GapsLongitudinal
2021 %         dnux_epu_111_m0 = tune_x-tune_x(1,11);
2022 %         [gap_epu_111,shift_epu_111]=meshgrid(Gaps,GapsLongitudinal);
2023 %         dnuy_epu_111_m0 = tune_y-tune_y(1,11);
2024 %         load '/home/als/physdata/matlab/srdata/gaptrack/archive/epu11d1m1e19_2007-01-28.mat' tune_x tune_y Gaps GapsLongitudinal
2025 %         dnux_epu_111_m1 = tune_x-tune_x(1,11);
2026 %         dnuy_epu_111_m1 = tune_y-tune_y(1,11);
2027
2028         % tune FF for EPUs (data exist for 4 1 parallel, 11 1 parallel and antiparallel
2029         load '/home/als/physdata/matlab/srdata/epu/tuneshift_2d_tables/epu_tunetables_2d_20070723.mat'
2030         dnux41p = nux41p-nux41p(1,11);
2031         dnuy41p = nuy41p-nuy41p(1,11);
2032         dnux41a = nux41a-nux41a(1,11);
2033         dnuy41a = nuy41a-nuy41a(1,11);
2034         dnux111p = nux111p-nux111p(1,11);
2035         dnuy111p = nuy111p-nuy111p(1,11);
2036         dnux111a = nux111a-nux111a(1,11);
2037         dnuy111a = nuy111a-nuy111a(1,11);
2038         dnux112p = nux112p-nux112p(1,11);
2039         dnuy112p = nuy112p-nuy112p(1,11);
2040         dnux112a = nux112a-nux112a(1,11);
2041         dnuy112a = nuy112a-nuy112a(1,11);
2042
2043         % ID tune compensation does not work in the injection lattice, so ...
2044         if abs(SR_GEV - bend2gev)>  0.05     % Don't use this routine for the injection lattice
2045             fprintf('   This routine should only be used for the production energy: Orbit feedback aborted\n');
2046             return
2047         end
2048
2049         set(0,'showhiddenhandles','on');
2050
2051         try
2052             fprintf('\n');
2053             fprintf('   *******************************\n');
2054             fprintf('   **  Starting Orbit Feedback  **\n');
2055             fprintf('   *******************************\n');
2056             a = clock;
2057             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2058             fprintf('   Note: the Matlab command window will be used to display status information.\n');
2059             fprintf('         It cannot be used to enter commands during slow orbit feedback.\n');
2060
2061
2062                 % save current BPM timeconstant - will reset to this when feedback stops
2063                 BPMtimeconstantOFB = getbpmtimeconstant;
2064                 fprintf('   Current Bergoz BPM time constant is %.1fs\n', BPMtimeconstantOFB);
2065
2066             % >= 2 Hz update rate on IDBPMs
2067             disp('   Bergoz BPM time constant set to 0.2s.')
2068             setbpmtimeconstant(0.2)
2069             pause(1.1);
2070
2071             % Check whether bumps and kickers are on and warn to turn off before starting feedback if necessary
2072             try
2073                 if (getsp('SR01S___BUMP1__BC21')==1 && getsp('SR01S___BUMP1P_BC22')==1) || (getsp('SR01S___SEK____BC21')==1 && getsp('SR01S___SEK_P__BC23')==1) || (getsp('SR01S___SEN____BC20')==1 && getsp('SR01S___SEN_P__BC22')==1)
2074                     soundtada;
2075                     fprintf('   \n');
2076                     fprintf('   *********************************************************************************\n');
2077                     fprintf('   ** One or more of the pulsed SR injection magnets is still on!  Turn them off! **\n');
2078                     fprintf('   *********************************************************************************\n');
2079                     fprintf('   \n');
2080                 end
2081             catch
2082                 fprintf('   %s \n',lasterr);
2083                 disp('**Problem checking the state of the bumps and kickers - please check that they are not pulsing.');
2084             end
2085
2086             % Get vectors
2087
2088             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
2089
2090             BPMlist1 = FB.OCSx.BPM.DeviceList;
2091             % FOFB_BPMlist =
2092             HCMlist1 = FB.HCMlist1;
2093             VCMlist1 = FB.VCMlist1;
2094             Xivec = FB.Xivec;
2095             Yivec = FB.Yivec;
2096             Xgoal = FB.OCSx.GoalOrbit;
2097             Ygoal = FB.OCSy.GoalOrbit;
2098             FFTypeFlag = FB.FFTypeFlag;   %local or global tune correction
2099
2100             iNotHCMChicane = find(HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
2101             iHCMChicane = find(HCMlist1(:,2) == 10);
2102             iNotVCMChicane = find(VCMlist1(:,2) < 10);
2103             iVCMChicane = find(VCMlist1(:,2) == 10);
2104
2105             % Sensitivity matrix for setting fast feedback setpoints
2106             Sx1 = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
2107             Sy1 = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
2108
2109         catch
2110             fprintf('\n  %s \n',lasterr);
2111
2112             % Reset Bergoz BPM time constant to whatever it was before feedback started
2113             fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
2114             setbpmtimeconstant(BPMtimeconstantOFB);
2115
2116
2117             a = clock;
2118             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2119             fprintf('   *************************************************************\n');
2120             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
2121             fprintf('   *************************************************************\n\n');
2122             set(0,'showhiddenhandles','off');
2123             pause(0);
2124
2125             return
2126         end
2127
2128         StartFlag = questdlg(strvcat('','Is it OK to start orbit feedback?'),'Orbit Feedback','Yes','No','No');
2129         if strcmp(StartFlag,'No')
2130             % Reset Bergoz BPM time constant to whatever it was before feedback started
2131             fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
2132             setbpmtimeconstant(BPMtimeconstantOFB);
2133
2134             a = clock;
2135             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2136             fprintf('   ***************************\n');
2137             fprintf('   **  Orbit Feedback Exit  **\n');
2138             fprintf('   ***************************\n\n');
2139             pause(0);
2140             return
2141         end
2142
2143         SR_STATE_OLD = scaget('SR_STATE');
2144         setpv('SR_STATE', 5);
2145         set(0,'showhiddenhandles','on');
2146         [StateNumber, StateString] = getsrstate;
2147         if StateNumber >= 0
2148             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2149         else
2150             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2151         end
2152         fprintf('   Using %d E-vectors horizontally.\n', length(Xivec));
2153         fprintf('   Using %d E-vectors vertically.\n',   length(Yivec));
2154         fprintf('   Starting slow orbit correction every %.1f seconds.\n', LoopDelay);
2155         %  fprintf('   Resetting SR11 chicane motors every 20 seconds to fix drift problem.\n');
2156
2157         IDSector = getlist('ID');
2158         EPUlist = find((IDSector(:,1)==4) | (IDSector(:,1)==11));
2159         oldgap=210*ones(size(IDSector,1),1);
2160         oldShift=zeros(size(oldgap));
2161
2162         try
2163
2164             % Get and display data
2165             x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
2166             y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
2167             STDx = norm(x)/sqrt(length(x));
2168             STDy = norm(y)/sqrt(length(y));
2169             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
2170             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
2171
2172             % write goldenorbit values to Fast Orbit Feedback
2173             try
2174                 write_goldenorbit_ffb;
2175             catch
2176                 fprintf('   %s \n',lasterr);
2177                 disp('write_goldenorbit_ffb did not work!');
2178             end
2179             setpv('SR01____FFBON__BC00',2);
2180             %pause(0);
2181
2182             %display state of FOFB system
2183             FOFBStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2184                 getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2185                 getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2186                 getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2187             FOFBStatusStr = ['    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    '];
2188             for loop = 1:size(FOFBStatus,2)
2189                 if FOFBStatus(loop)==0
2190                     FOFBStatusStr(loop,:) = 'OFF ';
2191                 elseif FOFBStatus(loop)==1
2192                     FOFBStatusStr(loop,:) = 'ON  ';
2193                 elseif FOFBStatus(loop)==2
2194                     FOFBStatusStr(loop,:) = 'OPEN';
2195                 else
2196                     FOFBStatusStr(loop,:) = 'BAD ';
2197                 end
2198             end
2199             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 %s',FOFBStatusStr(1,:)),'ForegroundColor',[0 0 0]);
2200             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 %s',FOFBStatusStr(2,:)),'ForegroundColor',[0 0 0]);
2201             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 %s',FOFBStatusStr(3,:)),'ForegroundColor',[0 0 0]);
2202             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 %s',FOFBStatusStr(4,:)),'ForegroundColor',[0 0 0]);
2203             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 %s',FOFBStatusStr(5,:)),'ForegroundColor',[0 0 0]);
2204             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 %s',FOFBStatusStr(6,:)),'ForegroundColor',[0 0 0]);
2205             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 %s',FOFBStatusStr(7,:)),'ForegroundColor',[0 0 0]);
2206             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 %s',FOFBStatusStr(8,:)),'ForegroundColor',[0 0 0]);
2207             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 %s',FOFBStatusStr(9,:)),'ForegroundColor',[0 0 0]);
2208             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 %s',FOFBStatusStr(10,:)),'ForegroundColor',[0 0 0]);
2209             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 %s',FOFBStatusStr(11,:)),'ForegroundColor',[0 0 0]);
2210             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 %s',FOFBStatusStr(12,:)),'ForegroundColor',[0 0 0]);
2211
2212         catch
2213
2214             fprintf('\n  %s \n',lasterr);
2215
2216             % Reset Bergoz BPM time constant to whatever it was before feedback started
2217             fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
2218             setbpmtimeconstant(BPMtimeconstantOFB);
2219
2220
2221             a = clock;
2222             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2223             fprintf('   *************************************************************\n');
2224             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
2225             fprintf('   *************************************************************\n\n');
2226
2227             setpv('SR_STATE',SR_STATE_OLD);
2228             [StateNumber, StateString] = getsrstate;
2229             if StateNumber >= 0
2230                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2231             else
2232                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2233             end
2234             set(0,'showhiddenhandles','off');
2235             pause(0);
2236
2237             return
2238
2239         end
2240
2241
2242         % Disable buttons
2243         set(0,'showhiddenhandles','on');
2244         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','off');
2245         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','on');
2246         set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','off');
2247         set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','off');
2248         set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','off');
2249         set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','off');
2250         set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','off');
2251         set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','off');
2252         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','off');
2253         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','off');
2254         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','off');
2255         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','off');
2256         set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','off');
2257         pause(0);
2258
2259
2260         % Initialize feedback loop
2261         StartTime = gettime;
2262         StartErrorTime = gettime;
2263         Xold = getx(FB.OCSx.BPM.DeviceList);
2264         Yold = gety(FB.OCSy.BPM.DeviceList);
2265         HQMOFM_stalenum = 0;
2266         pause(LoopDelay);
2267
2268         N_HCM = size(HCMlist1,1);
2269         N_VCM = size(VCMlist1,1);
2270
2271         N_RFMO = 1;
2272
2273         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2274             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'SetRF','Nodisplay','Nosetsp');
2275         else
2276             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
2277         end
2278         [FB.OCSx, Smatx, Sx, Ux, Vx] = orbitcorrectionmethods(FB.OCSx);
2279
2280         [FB.OCSy, junk, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
2281         [FB.OCSy, Smaty, Sy, Uy, Vy] = orbitcorrectionmethods(FB.OCSy);
2282
2283
2284         %%%%%%%%%%%%%%%%%%%%%%%
2285         % Start feedback loop %
2286         %%%%%%%%%%%%%%%%%%%%%%%
2287
2288         % chicaneloop=1;  % loop variable for resetting drifting chicanes (see a few lines below)
2289         % fftest=figure;
2290
2291         setpv('SR01____FFBON__BC00',2); % put FOFB in open loop so beamnoise gets recorded even if FOFB is not enabled
2292
2293         while 1
2294             try
2295                 t00 = gettime;
2296
2297                 %          if chicaneloop==20 % reset SR11 motor chicane setpoints every 20s due to drifting positions
2298                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(6),[11 1],0);
2299                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(7),[11 2],0);
2300                 %             chicaneloop = 1;
2301                 %          else
2302                 %             chicaneloop = chicaneloop + 1;
2303                 %          end
2304
2305                 % Check if GUI has been closed
2306                 if isempty(gcbf)
2307                     FEEDBACK_STOP_FLAG = 1;
2308                     lasterr('SRCONTROL GUI DISAPPEARED!');
2309                     error('SRCONTROL GUI DISAPPEARED!');
2310                 end
2311
2312                 %%%%%%%%%%%%%%%%%%%%%%%
2313                 % Fast orbit feedback %
2314                 %%%%%%%%%%%%%%%%%%%%%%%
2315                 if StartFOFBFlag == 1 && FBloopIter > 3
2316                     setpv('SR01____FFBON__BC00',2);
2317                     pause(0.5);
2318                     setpv('SR01____FFBON__BC00',1);
2319                     StartFOFBFlag = 0;
2320                     pause(1);
2321                     FOFBOnStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2322                         getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2323                         getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2324                         getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2325                     if any(FOFBOnStatus==0) || any(FOFBOnStatus==2)
2326                         setpv('SR01____FFBON__BC00',2); % open FOFB loop
2327                         disp('************************************************************************************************************');
2328                         disp('** Problem turning on Fast Orbit Feedback system...                                                       **');
2329                         disp('** Check status of ffbsecXX crates - but remember that a crate reboot will turn off Quads in that sector! **');
2330                         disp('** Suggest disabling the "Fast Orbit Correction" checkbox and starting Orbit Feedback again.              **');
2331                         disp('************************************************************************************************************');
2332                     else
2333                         fprintf('   Starting Fast Orbit Feedback at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
2334                     end
2335                 end
2336
2337
2338                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2339                 % Horizontal plane "feedback" %
2340                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2341
2342                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxSOFB'),'Value') == 1
2343
2344                     % Get orbit and check that the BPMs are different from the last update
2345                     Xnew = getx(FB.OCSx.BPM.DeviceList);
2346
2347                     % Don't feedback if the current is too small
2348                     if getdcct < 2
2349                         FEEDBACK_STOP_FLAG = 1;
2350                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2351                         break;
2352                     end
2353
2354                     x = Xgoal - Xnew;
2355                     STDx = norm(x)/sqrt(length(x));
2356
2357                     if any(Xold == Xnew)
2358                         a = clock;
2359                         N_Stale_Data_Points = find((Xold==Xnew)==1);
2360                         for loop = N_Stale_Data_Points'
2361                             fprintf('   Stale data: BPMx(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSx.BPM.DeviceList(loop,1), FB.OCSx.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2362                         end
2363                     else
2364                         % Compute horizontal correction
2365                         %%%OCSx0 = FB.OCSx;
2366                         FB.OCSx.BPM.Data = Xnew;
2367                         FB.OCSx = orbitcorrectionmethods(FB.OCSx, Smatx, Sx, Ux, Vx);
2368
2369                         %%%[FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
2370
2371                         % reduced feedback gain (implemented by Greg Portmann, December 2000)
2372                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2373                         % increased back to 0.8 C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2374                         % increased to 1.0, C. Steier, 2002-05-04, trim DACs
2375                                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2376                                 % should probably actively allocate X's size to prevent possible memory leak %
2377                                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2378                         X = [Xgain .* FB.OCSx.CM.Delta; 0.3*FB.OCSx.DeltaRF/4.988e-3];
2379
2380                         %%%X = Xgain .* (FB.OCSx.CM.Data - OCSx0.CM.Data);
2381
2382                         % check corrector trim values + next step values, warn or stop FB as necessary
2383                         HCMtrimSP=getpv('HCM','Trim',HCMlist1);
2384                         HCMtrimSP_next = HCMtrimSP + X(1:N_HCM);
2385                         if max(abs(HCMtrimSP_next)) > 4
2386                             HCMtrimnum=find(abs(HCMtrimSP_next) > 4);
2387
2388                             % print message to screen
2389                             fprintf('\n');
2390                             fprintf('***One or more of the horizontal correctors is at its maximum!! Stopping orbit feedback. \n');
2391                             fprintf('   %s\n',datestr(now));
2392                             for loop = HCMtrimnum'
2393                                 fprintf('***%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2394                             end
2395
2396                             % send alphapage to operator pager
2397                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2398                             FEEDBACK_STOP_FLAG = 1;
2399
2400                             setpv('SR_STATE', -5);
2401                             [StateNumber, StateString] = getsrstate;
2402                             if StateNumber >= 0
2403                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2404                             else
2405                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2406                             end
2407                         end
2408
2409                         % check chicane trim coil values + next step values, warn or stop FB as necessary
2410                         HCMCHICANEtrimSP=getpv('HCM','Setpoint',HCMlist1(iHCMChicane,:));
2411                         HCMCHICANEtrimSP_next = HCMCHICANEtrimSP + X(iHCMChicane);
2412                         if max(abs(HCMCHICANEtrimSP_next)) > 19.9
2413                             HCMCHICANEtrimnum=find(abs(HCMCHICANEtrimSP_next) > 19.9);
2414
2415                             % print message to screen
2416                             fprintf('\n');
2417                             fprintf('***One or more of the horizontal chicane trim coil correctors is at its maximum!! Stopping orbit feedback. \n');
2418                             fprintf('   %s\n',datestr(now));
2419                             for loop = HCMCHICANEtrimnum'
2420                                 fprintf('***%s is one of the problem correctors.\n',getname('HCM','Setpoint',HCMlist1(iHCMChicane(loop,:),:)));
2421                             end
2422                             %fprintf('***Maybe try resetting the setpoints of the motor chicanes in case they are drifting...\n');
2423
2424                             % send alphapage to operator pager
2425                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2426                             FEEDBACK_STOP_FLAG = 1;
2427
2428                             setpv('SR_STATE', -5);
2429                             [StateNumber, StateString] = getsrstate;
2430                             if StateNumber >= 0
2431                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2432                             else
2433                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2434                             end
2435                         end
2436
2437                         if FEEDBACK_STOP_FLAG == 1
2438                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2439                             if getpv('SR01____FFBON__BC00')==1
2440                                 disp('   Stopping Fast Orbit Feedback.');
2441                             end
2442                             setpv('SR01____FFBON__BC00',0);
2443                             pause(0.5);
2444                             setpv('SR01____FFBON__BC00',2);
2445                             break;
2446                         end
2447
2448                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2449                         pause(0);
2450
2451                         if max(abs(HCMtrimSP_next) > 3)
2452                             HCMtrimnum=find(abs(HCMtrimSP_next) > 3);
2453                             HWarnNum=HWarnNum+1;
2454                             if (HWarnNum==1 || rem(HWarnNum,120)==0)
2455
2456                                 % print message to screen every two minutes
2457                                 fprintf('\n');
2458                                 fprintf('***One or more of the horizontal corrector trims is above 3A or below -3A! \n');
2459                                 fprintf('   %s\n',datestr(now));
2460                                 for loop = HCMtrimnum'
2461                                     fprintf('***%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2462                                 end
2463                                 fprintf('***The orbit feedback is still working but this problem should be investigated. \n');
2464
2465                                 %send alphapage to operator pager the first time then at 10 minutes
2466                                 if (HWarnNum==1 || HWarnNum==600)
2467                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageHCM.txt
2468                                 end
2469                             end
2470                         elseif max(abs(HCMCHICANEtrimSP_next) > 15)
2471                             HCMCHICANEtrimnum=find(abs(HCMCHICANEtrimSP_next) > 15);
2472                             HWarnNum=HWarnNum+1;
2473                             if (HWarnNum==1 || rem(HWarnNum,120)==0)
2474
2475                                 % print message to screen every two minutes
2476                                 fprintf('\n');
2477                                 fprintf('***One or more of the horizontal chicane corrector trim coils is above 15A or below -15A! \n');
2478                                 fprintf('   %s\n',datestr(now));
2479                                 for loop = HCMCHICANEtrimnum'
2480                                     fprintf('***%s is one of the problem correctors.\n',getname('HCM','Setpoint',HCMlist1(iHCMChicane(loop,:),:)));
2481                                 end
2482                                 fprintf('***The orbit feedback is still working but this problem should be investigated. \n');
2483
2484 % All motor chicanes have harmonic drives now, so slipping should be impossible - 6-4-08 - T.Scarvie
2485 %                                 %reset motor chicanes in case they are drifting
2486 %                                 try
2487 %                                     %                                     if HCMCHICANEtrimnum(1)==1
2488 %                                     %                                         if HCMCHICANEtrimSP_next(1)>15
2489 %                                     %                                             steppv('HCMCHICANEM',-0.5,[4 1;4 2]);
2490 %                                     %                                         elseif HCMCHICANEtrimSP_next(1)<(-15)
2491 %                                     %                                             steppv('HCMCHICANEM',0.5,[4 1;4 2]);
2492 %                                     %                                         end
2493 %                                     %                                     end
2494 %                                     fprintf('   Resetting the setpoints of the motor chicanes in case they are drifting...\n');
2495 %                                     setpv('HCMCHICANEM','Setpoint',ConfigSetpoint.HCMCHICANEM.Setpoint.Data,[],0);
2496 %                                 catch
2497 %                                     fprintf('   %s \n',lasterr);
2498 %                                 end
2499
2500                                 %send alphapage to operator pager the first time then at 10 minutes
2501                                 if (HWarnNum==1 || HWarnNum==600)
2502                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageHCMCHICANE.txt
2503                                 end
2504                             end
2505                         else
2506                             HWarnNum=0;
2507                         end
2508
2509                         % Don't feedback if the current is too small
2510                         if getdcct < 2
2511                             FEEDBACK_STOP_FLAG = 1;
2512                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2513                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2514                             break;
2515                         end
2516
2517                         if N_HCM > 0
2518                             steppv('HCM','Trim', X(iNotHCMChicane), HCMlist1(iNotHCMChicane,:), 0);
2519                             steppv('HCM','Setpoint', X(iHCMChicane), HCMlist1(iHCMChicane,:), 0);
2520                         end
2521
2522                         % write fast orbit feedback setpoints
2523                         if 1
2524                             %write_goldenorbit_ffb_2planes(1, Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM)+Sx3*X(length(X))/20, BPMlist1);
2525                             % should be corrected to include result of next frequency step ...
2526                             write_goldenorbit_ffb_2planes(1,Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM),BPMlist1);
2527                         end
2528
2529                         %fprintf('Horizontal Done: %f \n',gettime-t00);
2530
2531                         % RF feedback
2532                         HQMOFMsp_last = getpv('EG______HQMOFM_AC01');
2533
2534                         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2535                             if N_RFMO > 0
2536                                 if abs(X(end)) < .01
2537                                     % if abs(FB.OCSx.DeltaRF/3) < .01
2538                                     steppv('EG______HQMOFM_AC01', X(end));
2539                                 else
2540                                     steppv('EG______HQMOFM_AC01', 0.01*sign(X(end)));
2541                                 end
2542                             end
2543
2544                             HQMOFMsp_now = getpv('EG______HQMOFM_AC01');
2545
2546                             % Check for stale RF feedback
2547                             if HQMOFMsp_last == HQMOFMsp_now
2548                                 HQMOFM_stalenum = HQMOFM_stalenum + 1;
2549                                 if HQMOFM_stalenum == 30 % warn and message to pager if stale for 30 secs
2550                                     fprintf('\n');
2551                                     fprintf('***The RF is not responding to orbit feedback changes! \n');
2552                                     fprintf('   %s\n',datestr(now));
2553                                     fprintf('***The orbit feedback is still working but this problem should be investigated. \n');
2554                                     fprintf('***ILC 73 controls the EG______HQMOFM_AC01 channel, which sets the RF frequency. \n');
2555                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstaleRFmessage.txt
2556                                 end
2557                                 if rem(HQMOFM_stalenum,120)==0 % message to screen every 2 minutes
2558                                     fprintf('\n');
2559                                     fprintf('***The RF is not responding to orbit feedback changes! (%s)\n',datestr(now));
2560                                 end
2561                             else
2562                                 HQMOFM_stalenum = 0;
2563                             end
2564
2565                         end
2566
2567                         %fprintf('RF Done: %f \n',gettime-t00);
2568
2569                         Xold = Xnew;
2570                     end % End horizontal correction
2571
2572
2573                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2574                     % Vertical plane "feedback" %
2575                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2576
2577                     % Get orbit and check that the BPMs are different from the last update
2578                     Ynew = gety(FB.OCSy.BPM.DeviceList);
2579
2580                     % Don't feedback if the current is too small
2581                     if getdcct < 2
2582                         FEEDBACK_STOP_FLAG = 1;
2583                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2584                         break;
2585                     end
2586
2587                     y = Ygoal - Ynew;
2588                     STDy = norm(y)/sqrt(length(y));
2589
2590                     if any(Yold == Ynew)
2591                         a = clock;
2592                         N_Stale_Data_Points = find((Yold==Ynew)==1);
2593                         for loop = N_Stale_Data_Points'
2594                             fprintf('   Stale data: BPMy(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSy.BPM.DeviceList(loop,1), FB.OCSy.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2595                         end
2596
2597                     else
2598
2599                         % Compute vertical correction
2600                         %%%OCSy0 = FB.OCSy;
2601                         FB.OCSy.BPM.Data = Ynew;
2602                         FB.OCSy = orbitcorrectionmethods(FB.OCSy, Smaty, Sy, Uy, Vy);
2603
2604                         %%%[FB.OCSy, RF, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
2605
2606                         % reduced feedback gain, C. Steier, 2001-03-25
2607                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2608                         % increased back to 0.8, C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2609                         % set to unity gain, C. Steier, 2002-05-04, trim DACs
2610                         Y = Ygain .* FB.OCSy.CM.Delta;
2611                         %%%Y = Ygain .* (FB.OCSy.CM.Data - OCSy0.CM.Data);
2612
2613                         % Just SVD correction
2614                         % warning('Not using "micado" correction in the vertical plane.');
2615
2616                         % check for trim values+next step values, warn or stop FB as necessary
2617                         VCMtrimSP = getpv('VCM','Trim',VCMlist1);
2618                         VCMtrimSP_next = VCMtrimSP + Y(1:N_VCM);
2619                         if max(abs(VCMtrimSP_next)) > 12
2620                             VCMtrimnum=find(abs(VCMtrimSP_next) > 12);
2621
2622                             % print message to screen
2623                             fprintf('\n');
2624                             fprintf('***One or more of the vertical correctors is at its maximum!! Stopping orbit feedback. \n');
2625                             fprintf('   %s\n',datestr(now));
2626                             for loop = VCMtrimnum'
2627                                 fprintf('***%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2628                             end
2629
2630                             % send alphapage to operator pager
2631                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2632                             FEEDBACK_STOP_FLAG = 1;
2633
2634                             setpv('SR_STATE', -5);
2635                             [StateNumber, StateString] = getsrstate;
2636                             if StateNumber >= 0
2637                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2638                             else
2639                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2640                             end
2641                         end
2642
2643                         % check chicane trim coil values + next step values, warn or stop FB as necessary
2644                         VCMCHICANEtrimSP=getpv('VCM','Setpoint',VCMlist1(iVCMChicane,:));
2645                         VCMCHICANEtrimSP_next = VCMCHICANEtrimSP + Y(iVCMChicane);
2646                         if max(abs(VCMCHICANEtrimSP_next)) > 19.9
2647                             VCMCHICANEtrimnum=find(abs(VCMCHICANEtrimSP_next) > 19.9);
2648
2649                             % print message to screen
2650                             fprintf('\n');
2651                             fprintf('***One or more of the vertical chicane trim coil correctors is at its maximum!! Stopping orbit feedback. \n');
2652                             fprintf('   %s\n',datestr(now));
2653                             for loop = VCMCHICANEtrimnum'
2654                                 fprintf('***%s is one of the problem correctors.\n',getname('VCM','Setpoint',VCMlist1(iVCMChicane(loop,:),:)));
2655                             end
2656                             %fprintf('***Maybe try resetting the setpoints of the motor chicanes in case they are drifting...\n');
2657
2658                             % send alphapage to operator pager
2659                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2660                             FEEDBACK_STOP_FLAG = 1;
2661
2662                             setpv('SR_STATE', -5);
2663                             [StateNumber, StateString] = getsrstate;
2664                             if StateNumber >= 0
2665                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2666                             else
2667                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2668                             end
2669                         end
2670
2671                         if FEEDBACK_STOP_FLAG == 1
2672                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2673                             if getpv('SR01____FFBON__BC00')==1
2674                                 disp('   Stopping Fast Orbit Feedback.');
2675                             end
2676                             setpv('SR01____FFBON__BC00',0);
2677                             pause(0.5);
2678                             setpv('SR01____FFBON__BC00',2);
2679                             break;
2680                         end
2681
2682                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2683                         % pause(0);
2684
2685                         if max(abs(VCMtrimSP_next) > 8) % changed from 6A ~12/1/07 since orbit FB is going past 6A
2686                             VCMtrimnum=find(abs(VCMtrimSP_next) > 8);
2687                             VWarnNum=VWarnNum+1;
2688                             if (VWarnNum==1 || rem(VWarnNum,120)==0)
2689
2690                                 % print message to screen every two minutes
2691                                 fprintf('\n');
2692                                 fprintf('***One or more of the vertical corrector trims is above 8A or below -8A! \n');
2693                                 fprintf('   %s\n',datestr(now));
2694                                 for loop = VCMtrimnum'
2695                                     fprintf('***%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2696                                 end
2697                                 fprintf('***The orbit feedback is still working but this problem should be investigated. \n');
2698
2699                                 %send alphapage to operator pager the first time then at 10 minutes
2700                                 if (VWarnNum==1 || VWarnNum==600)
2701                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageVCM.txt
2702                                 end
2703                             end
2704                         elseif max(abs(VCMCHICANEtrimSP_next) > 15)
2705                             VCMCHICANEtrimnum=find(abs(VCMCHICANEtrimSP_next) > 15);
2706                             VWarnNum=VWarnNum+1;
2707                             if (VWarnNum==1 || rem(VWarnNum,120)==0)
2708
2709                                 % print message to screen every two minutes
2710                                 fprintf('\n');
2711                                 fprintf('***One or more of the vertical chicane corrector trim coils is above 15A or below -15A! \n');
2712                                 fprintf('   %s\n',datestr(now));
2713                                 for loop = VCMCHICANEtrimnum'
2714                                     fprintf('***%s is one of the problem correctors.\n',getname('VCM','Setpoint',VCMlist1(iVCMChicane(loop,:),:)));
2715                                 end
2716                                 fprintf('***The orbit feedback is still working but this problem should be investigated. \n');
2717
2718 % All motor chicanes have harmonic drives now, so slipping should be impossible - 6-4-08 - T.Scarvie
2719 %                                 %reset motor chicanes in case they are drifting
2720 %                                 try
2721 %                                         fprintf('  Resetting the setpoints of the motor chicanes in case they are drifting...\n');
2722 %                                         setpv('HCMCHICANEM','Setpoint',ConfigSetpoint.HCMCHICANEM.Setpoint.Data,[],0);
2723 %                                 catch
2724 %                                       fprintf('   %s \n',lasterr);
2725 %                                 end
2726
2727                                 %send alphapage to operator pager the first time then at 10 minutes
2728                                 if (VWarnNum==1 || VWarnNum==600)
2729                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageVCMCHICANE.txt
2730                                 end
2731                             end
2732                         else
2733                             VWarnNum=0;
2734                         end
2735
2736                         % Don't feedback if the current is too small
2737                         if getdcct < 2
2738                             FEEDBACK_STOP_FLAG = 1;
2739                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2740                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2741                             break;
2742                         end
2743
2744                         if N_VCM > 0
2745                             steppv('VCM','Trim', Y(iNotVCMChicane), VCMlist1(iNotVCMChicane,:), 0);
2746                             steppv('VCM','Setpoint', Y(iVCMChicane), VCMlist1(iVCMChicane,:), 0);
2747                         end
2748
2749                         % write fast orbit feedback setpoints
2750                         if 1
2751                             write_goldenorbit_ffb_2planes(2,Ynew(1:size(BPMlist1,1))+Sy1*Y(1:N_VCM),BPMlist1);
2752                         end
2753
2754                     end
2755
2756                     Yold = Ynew;
2757
2758                     %fprintf('Vertical Done: %f \n',gettime-t00);
2759                 end % End vertical correction
2760
2761
2762                 %%%%%%%%%%%%%%%%%%%%%
2763                 % Tune feed forward %
2764                 %%%%%%%%%%%%%%%%%%%%%
2765                 % We should do a Sector limit check
2766
2767                 tic;
2768                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxTune'),'Value') == 1
2769
2770                     if strcmp(SR_Mode, '1.9 GeV, High Tune') || strcmp(SR_Mode, '1.9 GeV, Inject at 1.23') || strcmp(SR_Mode, '1.9 GeV, Inject at 1.353') ||...
2771                         strcmp(SR_Mode, '1.9 GeV, Two-Bunch')  || strcmp(SR_Mode, '1.5 GeV, Inject at 1.353')  || strcmp(SR_Mode, '1.9 GeV, TopOff')
2772
2773                         addQFsp = zeros(24,1);
2774                         addQDsp = zeros(24,1);
2775
2776                         if strcmp(FFTypeFlag,'Local')
2777                             disp('  No local tune compensation available - global is the default now.');
2778                         elseif strcmp(FFTypeFlag,'Global')
2779
2780                             % The vectorized gets were put outside of loop for speed reasons
2781                             %
2782                             % should also set up QFfac, Quadelem, Quadlist structures outside loop
2783                             actualgap = getid(IDSector);
2784                             [gapmin,gapmax] = gaplimit(IDSector);
2785                             corrind = find(actualgap<(gapmin-1));
2786                             actualgap(corrind)=gapmax(corrind);
2787                             Shift=zeros(size(actualgap));
2788                             Shift(EPUlist)=getpv('EPU');
2789
2790                             IDchangedList=find((abs(actualgap-oldgap)>0.005) | (abs(Shift-oldShift)>0.005));
2791
2792                             if ~isempty(IDchangedList)
2793
2794                                 oldgap=actualgap;
2795                                 oldShift=Shift;
2796
2797                                 % EPUs excite nux = .25 resonance in vertical linear polarization mode!
2798                                 % therefore with EPU tune feedforward
2799                                 % running, we want to move our nominal working point away (just below) the .25 resonance.
2800                                 %
2801                                 % The following tune correction moves nominal
2802                                 % nu_x from .25 to .245 - this should be enough for well set up lattices.
2803                                 %
2804                                 % 24 QF+ 24 QD
2805                                 DeltaAmps = inv(SR_TUNE_MATRIX) * [-0.005;0];    %  DelAmps =  [QF; QD];
2806                                 addQFsp = addQFsp + DeltaAmps(1,:);
2807                                 addQDsp = addQDsp + DeltaAmps(2,:);
2808
2809                                 for gapnum = 1:length(actualgap)
2810
2811                                     % Change in tune and [QF;QD] from maximum gap
2812
2813                                     if (IDSector(gapnum,1) == 4) || (IDSector(gapnum,1) == 11)
2814                                         if IDSector(gapnum,2) == 1
2815                                             modenamestr = sprintf('SR%02dU___ODS1M__DC00',IDSector(gapnum,1));
2816                                         else % if IDSector(gapnum,2) == 2
2817                                             modenamestr = sprintf('SR%02dU___ODS2M__DC00',IDSector(gapnum,1));
2818                                         end
2819                                         epumode = getpv(modenamestr);
2820                                         if (IDSector(gapnum,1) == 4) && (IDSector(gapnum,2) == 1)
2821                                             if 1   % temporary fix as long as we do not have good tune FF table without shims (2008-02-15)
2822                                                 if (epumode==0)
2823                                                     DeltaNuX = shift2tune(IDSector(gapnum,:),actualgap(gapnum),Shift(gapnum));
2824                                                     DeltaNuY = 0;
2825                                                 else
2826                                                     DeltaNuX = 0;
2827                                                     DeltaNuY = 0;
2828                                                 end
2829                                             elseif (epumode == 0)
2830 %                                                 DeltaNuX = interp2(gap_epu_41,shift_epu_41,dnux_epu_41_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2831 %                                                 DeltaNuY = interp2(gap_epu_41,shift_epu_41,dnuy_epu_41_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2832                                                 DeltaNuX = interp2(gap41p',shift41p',dnux41p',actualgap(gapnum),Shift(gapnum),'linear',0);
2833                                                 DeltaNuY = interp2(gap41p',shift41p',dnuy41p',actualgap(gapnum),Shift(gapnum),'linear',0);
2834                                             elseif (epumode == 1)
2835 %                                                 DeltaNux = 0;
2836 %                                                 DeltaNuY = gap2tune(IDSector(gapnum, :), actualgap(gapnum), SR_GeV);
2837                                                 DeltaNuX = interp2(gap41a',shift41a',dnux41a',actualgap(gapnum),Shift(gapnum),'linear',0);
2838                                                 DeltaNuY = interp2(gap41a',shift41a',dnuy41a',actualgap(gapnum),Shift(gapnum),'linear',0);
2839                                             else
2840                                                 DeltaNux = 0;
2841                                                 DeltaNuY = gap2tune(IDSector(gapnum, :), actualgap(gapnum), SR_GeV);
2842                                             end
2843                                         elseif (IDSector(gapnum,1) == 11) && (IDSector(gapnum,2) == 1)
2844                                             if (epumode == 0)
2845 %                                                 DeltaNuX = interp2(gap_epu_111,shift_epu_111,dnux_epu_111_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2846 %                                                 DeltaNuY = interp2(gap_epu_111,shift_epu_111,dnuy_epu_111_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2847                                                 DeltaNuX = interp2(gap111p',shift111p',dnux111p',actualgap(gapnum),Shift(gapnum),'linear',0);
2848                                                 DeltaNuY = interp2(gap111p',shift111p',dnuy111p',actualgap(gapnum),Shift(gapnum),'linear',0);
2849                                             elseif (epumode == 1)
2850 %                                                 DeltaNuX = interp2(gap_epu_111,shift_epu_111,dnux_epu_111_m1',actualgap(gapnum),Shift(gapnum),'linear',0);
2851 %                                                 DeltaNuY = interp2(gap_epu_111,shift_epu_111,dnuy_epu_111_m1',actualgap(gapnum),Shift(gapnum),'linear',0);
2852                                                 DeltaNuX = interp2(gap111a',shift111a',dnux111a',actualgap(gapnum),Shift(gapnum),'linear',0);
2853                                                 DeltaNuY = interp2(gap111a',shift111a',dnuy111a',actualgap(gapnum),Shift(gapnum),'linear',0);
2854                                             else
2855                                                 DeltaNuX = 0;
2856                                                 DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);   % variation of vertical tune shift with phase is small for EPUs
2857                                             end
2858                                         elseif (IDSector(gapnum,1) == 11) && (IDSector(gapnum,2) == 2)
2859                                             if (epumode == 0)
2860 %                                                 DeltaNuX = interp2(gap_epu_111,shift_epu_111,dnux_epu_111_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2861 %                                                 DeltaNuY = interp2(gap_epu_111,shift_epu_111,dnuy_epu_111_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2862                                                 DeltaNuX = interp2(gap112p',shift112p',dnux112p',actualgap(gapnum),Shift(gapnum),'linear',0);
2863                                                 DeltaNuY = interp2(gap112p',shift112p',dnuy112p',actualgap(gapnum),Shift(gapnum),'linear',0);
2864                                             elseif (epumode == 1)
2865 %                                                 DeltaNuX = interp2(gap_epu_111,shift_epu_111,dnux_epu_111_m1',actualgap(gapnum),Shift(gapnum),'linear',0);
2866 %                                                 DeltaNuY = interp2(gap_epu_111,shift_epu_111,dnuy_epu_111_m1',actualgap(gapnum),Shift(gapnum),'linear',0);
2867                                                 DeltaNuX = interp2(gap112a',shift112a',dnux112a',actualgap(gapnum),Shift(gapnum),'linear',0);
2868                                                 DeltaNuY = interp2(gap112a',shift112a',dnuy112a',actualgap(gapnum),Shift(gapnum),'linear',0);
2869                                             else
2870                                                 DeltaNuX = 0;
2871                                                 DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);   % variation of vertical tune shift with phase is small for EPUs
2872                                             end
2873                                         else
2874                                             DeltaNuX = 0;
2875                                             DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);
2876                                         end
2877
2878                                     else
2879                                         DeltaNuX = 0;
2880                                         DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);
2881                                     end
2882
2883                                     DelQF = zeros(length(QFsp),1);
2884                                     DelQD = zeros(length(QFsp),1);
2885
2886                                     fraccorr = 0.8*DeltaNuY ./ TuneW16Min;
2887
2888                                     % Find which quads to change (local beta beating correction
2889                                     % (horizontal for EPU, vertical otherwise)
2890                                     QuadList = [IDSector(gapnum,1)-1 2; IDSector(gapnum,1) 1];
2891                                     QuadElem = dev2elem('QF',QuadList); % in reality use QF and QD ...
2892
2893                                     % global vertical tune correction
2894                                     % 24 QF+ 24 QD
2895                                     DeltaAmps = inv(SR_TUNE_MATRIX) * [(fraccorr*6.23e-4); fraccorr*(-0.05301)];    %  DelAmps =  [QF; QD];
2896                                     DelQF = DelQF + DeltaAmps(1,:);
2897                                     DelQD = DelQD + DeltaAmps(2,:);
2898
2899                                     % local horizontal tune correction (is also nearly a beta beating correction) only nonzero for EPUs!
2900                                     % 2 QF + 2 QD
2901                                     DeltaAmpsLocal = 12*inv(SR_TUNE_MATRIX) * [-DeltaNuX;0];                       %  DelAmps =  [QF; QD];
2902                                     DelQF(QuadElem) = DelQF(QuadElem)+DeltaAmpsLocal(1,1);
2903                                     DelQD(QuadElem) = DelQD(QuadElem)+DeltaAmpsLocal(2,1);
2904
2905                                     % local vertical beta beating correction (should be used together with above global tune correction)
2906                                     % set to zero for EPUs, since their vertical tune shift is small
2907                                     % 2 QF + 2QD
2908                                     if (IDSector(gapnum,1)==6) || (IDSector(gapnum,1)==7) || (IDSector(gapnum,1)==10) || (IDSector(gapnum,1)==11)
2909                                         QFfac = ([2.243127/2.237111; 2.243127/2.237111]-1) * fraccorr;
2910                                         QDfac = ([2.556392/2.511045; 2.556392/2.511045]-1) * fraccorr;
2911                                     elseif (IDSector(gapnum,1)==5) || (IDSector(gapnum,1)==9)
2912                                         QFfac = ([2.225965/2.219784; 2.243096/2.237111]-1) * fraccorr;
2913                                         QDfac = ([2.528950/2.483259; 2.556345/2.511045]-1) * fraccorr;
2914                                     elseif (IDSector(gapnum,1)==4) || (IDSector(gapnum,1)==8) || (IDSector(gapnum,1)==12)
2915                                         QFfac = ([2.243096/2.237111; 2.225965/2.219784]-1) * fraccorr;
2916                                         QDfac = ([2.556345/2.511045; 2.528950/2.483259]-1) * fraccorr;
2917                                     else
2918                                         QFfac = zeros(2,1);
2919                                         QDfac = zeros(2,1);
2920                                     end
2921
2922                                     DelQF(QuadElem,:) = DelQF(QuadElem,:) + QFfac.*QFsp(QuadElem,:);
2923                                     DelQD(QuadElem,:) = DelQD(QuadElem,:) + QDfac.*QDsp(QuadElem,:);
2924
2925                                     % add all tune and beta beating corrections for this one ID to the summed up correction vectors for all IDs
2926                                     addQFsp = addQFsp+DelQF;
2927                                     addQDsp = addQDsp+DelQD;
2928
2929
2930                                     % Skew FF for IVID
2931                                     if (IDSector(gapnum,1)==6)
2932                                         scale=(gap2tune([6 1])/0.005)^(3/4)*0.16;
2933                                         [SQSFincr, SQSDincr] = set_etaywave_nuy9_20skews_skewFF(scale);
2934                                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2935                                         % should add a limit check here %
2936                                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2937                                         setpv('SQSF', 'Setpoint', SQSFsp+SQSFincr, [], 0, 'Physics');
2938                                         setpv('SQSD', 'Setpoint', SQSDsp+SQSDincr, [], 0, 'Physics');
2939                                     end
2940
2941                                 end
2942
2943                                 % Set quadrupoles using main setpoint channels
2944                                 setpv('QF', QFsp+addQFsp,[], 0);
2945                                 setpv('QD', QDsp+addQDsp,[], 0);
2946                                 % % Set quadrupoles using FF setpoint channels
2947                                 % setpv('QF', 'FF', addQFsp, [], 0);
2948                                 % setpv('QD', 'FF', addQDsp, [], 0);
2949
2950                             end
2951
2952                         else
2953                             error('Unknown type selected for tune FF');
2954                         end
2955
2956                     else
2957                         disp('  No tune FF algorithm for non-production modes yet...');
2958                     end
2959                 end
2960
2961                 ffdeltaquad_delay = toc;
2962                 %fprintf('tune FF delay = %.1f seconds\n',ffdeltaquad_delay);
2963                 % fprintf('Tune Done: %f \n',gettime-t00);
2964
2965                 % Output info to screen
2966                 set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
2967                 set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
2968                 %pause(0);
2969
2970                 FOFBStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2971                     getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2972                     getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2973                     getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2974                 for loop = 1:size(FOFBStatus,2)
2975                     if FOFBStatus(loop)==0
2976                         FOFBStatusStr(loop,:) = 'OFF ';
2977                     elseif FOFBStatus(loop)==1
2978                         FOFBStatusStr(loop,:) = 'ON  ';
2979                     elseif FOFBStatus(loop)==2
2980                         FOFBStatusStr(loop,:) = 'OPEN';
2981                     else
2982                         FOFBStatusStr(loop,:) = 'BAD ';
2983                     end
2984                 end
2985                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 %s',FOFBStatusStr(1,:)),'ForegroundColor',[0 0 0]);
2986                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 %s',FOFBStatusStr(2,:)),'ForegroundColor',[0 0 0]);
2987                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 %s',FOFBStatusStr(3,:)),'ForegroundColor',[0 0 0]);
2988                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 %s',FOFBStatusStr(4,:)),'ForegroundColor',[0 0 0]);
2989                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 %s',FOFBStatusStr(5,:)),'ForegroundColor',[0 0 0]);
2990                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 %s',FOFBStatusStr(6,:)),'ForegroundColor',[0 0 0]);
2991                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 %s',FOFBStatusStr(7,:)),'ForegroundColor',[0 0 0]);
2992                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 %s',FOFBStatusStr(8,:)),'ForegroundColor',[0 0 0]);
2993                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 %s',FOFBStatusStr(9,:)),'ForegroundColor',[0 0 0]);
2994                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 %s',FOFBStatusStr(10,:)),'ForegroundColor',[0 0 0]);
2995                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 %s',FOFBStatusStr(11,:)),'ForegroundColor',[0 0 0]);
2996                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 %s',FOFBStatusStr(12,:)),'ForegroundColor',[0 0 0]);
2997
2998
2999                 %fprintf('End of feedback operations: %f \n\n',gettime-t00);
3000
3001                 % Wait for next update time or stop request
3002                 while (gettime-t00) < LoopDelay
3003                     %disp('interval could be shorter')
3004                     pause(.05);
3005                     % Check if GUI has been closed
3006                     if isempty(gcbf)
3007                         FEEDBACK_STOP_FLAG = 1;
3008                         lasterr('SRCONTROL GUI DISAPPEARED!');
3009                         error('SRCONTROL GUI DISAPPEARED!');
3010                     end
3011
3012                     % Check if Stop button was pressed
3013                     if FEEDBACK_STOP_FLAG == 1
3014                         % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
3015                         if getpv('SR01____FFBON__BC00')==1
3016                             disp('   Stopping Fast Orbit Feedback.');
3017                         end
3018                         setpv('SR01____FFBON__BC00',0);
3019                         pause(0.5);
3020                         setpv('SR01____FFBON__BC00',2);
3021                         break;
3022                     end
3023                 end
3024
3025
3026                 if FEEDBACK_STOP_FLAG == 1
3027                     % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
3028                     if getpv('SR01____FFBON__BC00')==1
3029                         disp('   Stopping Fast Orbit Feedback.');
3030                     end
3031                     setpv('SR01____FFBON__BC00',0);
3032                     pause(0.5);
3033                     setpv('SR01____FFBON__BC00',2);
3034                     break;
3035                 end
3036
3037                 StartErrorTime = gettime;
3038
3039             catch
3040
3041                 fprintf('\n  %s \n',lasterr);
3042
3043                 % Quit if error exists for more than 20 seconds
3044                 if gettime-StartErrorTime>20 || FEEDBACK_STOP_FLAG==1
3045                     fprintf('%s  Orbit feedback stopped due to error condition. \n\n',datestr(now));
3046
3047                     %send alphapage to operator pager
3048                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
3049                     FEEDBACK_STOP_FLAG = 1;
3050
3051                     setpv('SR_STATE', -5);
3052                     [StateNumber, StateString] = getsrstate;
3053                     if StateNumber >= 0
3054                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
3055                     else
3056                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
3057                     end
3058                 else
3059                     a = clock;
3060                     fprintf('   Orbit feedback was paused due to error condition (%s %d:%d:%.0f). \n', date, a(4), a(5), a(6));
3061                     fprintf('   Orbit feedback has automatically restarted and is running. \n\n');
3062                 end
3063
3064             end
3065
3066             if FEEDBACK_STOP_FLAG == 1
3067                 % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
3068                 if getpv('SR01____FFBON__BC00')==1
3069                     disp('   Stopping Fast Orbit Feedback.');
3070                 end
3071                 setpv('SR01____FFBON__BC00',0);
3072                 pause(0.5);
3073                 setpv('SR01____FFBON__BC00',2);
3074                 break;
3075             end
3076
3077             %fprintf('End of feedback loop: %f \n\n',gettime-t00);
3078
3079             %pause(0);
3080
3081             % this loop delays turn on of Fast Feedback system
3082             if FBloopIter < 5
3083                 FBloopIter = FBloopIter + 1;
3084             end
3085
3086         end  % End of feedback loop
3087
3088
3089         % End feedback, reset all parameters
3090         try
3091
3092             % Enable buttons
3093             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','on');
3094             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','off');
3095             set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','on');
3096             set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','on');
3097             set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','on');
3098             set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','on');
3099             set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','on');
3100             set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','on');
3101             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','on');
3102             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','on');
3103             set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','on');
3104             set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','on');
3105             set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','on');
3106
3107             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = _____ mm'),'ForegroundColor',[0 0 0]);
3108             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = _____ mm'),'ForegroundColor',[0 0 0]);
3109
3110             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 ____'),'ForegroundColor',[0 0 0]);
3111             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 ____'),'ForegroundColor',[0 0 0]);
3112             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 ____'),'ForegroundColor',[0 0 0]);
3113             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 ____'),'ForegroundColor',[0 0 0]);
3114             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 ____'),'ForegroundColor',[0 0 0]);
3115             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 ____'),'ForegroundColor',[0 0 0]);
3116             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 ____'),'ForegroundColor',[0 0 0]);
3117             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 ____'),'ForegroundColor',[0 0 0]);
3118             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 ____'),'ForegroundColor',[0 0 0]);
3119             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 ____'),'ForegroundColor',[0 0 0]);
3120             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 ____'),'ForegroundColor',[0 0 0]);
3121             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 ____'),'ForegroundColor',[0 0 0]);
3122
3123             %pause(0);
3124
3125         catch
3126             fprintf('   %s \n',lasterr);
3127             % GUI must have been closed
3128
3129         end
3130
3131
3132         % Reset Bergoz BPM time constant to whatever it was before feedback started
3133         fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
3134         setbpmtimeconstant(BPMtimeconstantOFB);
3135
3136
3137         a = clock;
3138         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
3139         [StateNumber, StateString] = getsrstate;
3140         if StateNumber >= 0
3141             setpv('SR_STATE',5.1);
3142             [StateNumber, StateString] = getsrstate;
3143             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
3144             fprintf('   ******************************\n');
3145             fprintf('   **  Orbit Feedback Stopped  **\n');
3146             fprintf('   ******************************\n\n');
3147         else
3148             [StateNumber, StateString] = getsrstate;
3149             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
3150             fprintf('   ****************************************\n');
3151             fprintf('   **  Problem With Slow Orbit Feedback  **\n');
3152             fprintf('   ****************************************\n\n');
3153         end
3154         set(0,'showhiddenhandles','off');
3155         pause(0);
3156
3157
3158     case 'FeedbackSetup'
3159         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
3160
3161         if InitFlag
3162
3163
3164             % Get the device lists from oscsinit and convert to srcontrol variables
3165             [HBPM, VBPM, HCM, VCM, HSV, VSV] = ocsinit('SOFB');
3166             Xivec = 1:HSV;
3167             Yivec = 1:VSV;
3168             BPMlist1 = HBPM.DeviceList;
3169             HCMlist1 = HCM.DeviceList;
3170             VCMlist1 = VCM.DeviceList;
3171
3172
3173             OCSx.BPM = getx(BPMlist1, 'struct');
3174             OCSx.CM = getsp('HCM', HCMlist1, 'struct');
3175             OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
3176             OCSx.NIter = 1;
3177             OCSx.SVDIndex = Xivec;
3178             OCSx.IncrementalFlag = 'No';
3179             OCSx.BPMWeight = {[]};
3180             OCSx.FitRF = 0;
3181             OCSy.BPM = gety(BPMlist1, 'struct');
3182             OCSy.CM = getsp('VCM', VCMlist1, 'struct');
3183             OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
3184             OCSy.NIter = 1;
3185             OCSy.SVDIndex = Yivec;
3186             OCSy.IncrementalFlag = 'No';
3187             OCSy.BPMWeight = {[]};
3188             OCSy.FitRF = 0;
3189
3190             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
3191             % do we need these Smat calls? %
3192             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
3193             SXmat = getrespmat(OCSx.BPM, OCSx.CM, 'numeric');
3194             SYmat = getrespmat(OCSy.BPM, OCSy.CM, 'numeric');
3195             % [OCSx, Sx, Ux, Vx] = orbitcorrectionmethods(OCSx, SXmat);
3196             % [OCSy, Sy, Uy, Vy] = orbitcorrectionmethods(OCSy, SYmat);
3197
3198             % initialize FFTypeFlag
3199             FFTypeFlag = 'Global';
3200
3201             % Fit decision comes from check box
3202             if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
3203                 OCSx.FitRF = 1;
3204                 Xivec = 1:HSV+1;
3205             end
3206
3207         else
3208
3209             % Get vectors
3210             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
3211             % the two lines below seem to fix BPMlist editing problem
3212             OCSx = FB.OCSx;
3213             OCSy = FB.OCSy;
3214             BPMlist1 = FB.BPMlist1;
3215             HCMlist1 = FB.HCMlist1;
3216             VCMlist1 = FB.VCMlist1;
3217             Xivec = FB.Xivec;
3218             Yivec = FB.Yivec;
3219             Xgoal = FB.OCSx.GoalOrbit;
3220             OCSx.GoalOrbit = Xgoal;
3221             Ygoal = FB.OCSy.GoalOrbit;
3222             OCSy.GoalOrbit = Ygoal;
3223             FFTypeFlag = FB.FFTypeFlag;
3224
3225
3226             % FF corrector magnet list - only channels which are blocked when FF is running should be
3227             % listed
3228             ListFF = [
3229                 4     2
3230                 4     8
3231                 5     1
3232                 5     7
3233 %               5     8 % IVID is using digital FF, i.e. FF algorithm does not block
3234 %               6     1 % other access to PVs
3235                 6     8
3236                 7     1
3237                 7     8
3238                 8     1
3239                 8     8
3240                 9     1
3241                 9     8
3242                 10    1
3243                 11    8
3244                 12    1];
3245             ElemFF = dev2elem('HCM',ListFF);
3246
3247
3248             % Add button to change #ivectors, cm, IDBPMs,
3249             EditFlag = 0;
3250             h_fig1 = figure;
3251             while EditFlag ~= 6
3252
3253                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
3254                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
3255
3256                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
3257                     DispOrbit = getdisp('BPMx', BPMlist1);
3258                     Sx = [Sx DispOrbit];
3259                 end
3260
3261                 Sx(isnan(Sx)) = 0;
3262                 Sy(isnan(Sy)) = 0;
3263
3264                 [Ux, SVx, Vx] = svd(Sx);
3265                 [Uy, SVy, Vy] = svd(Sy);
3266
3267
3268                 % Remove singular values greater than the actual number of singular values
3269                 i = find(Xivec>length(diag(SVx)));
3270                 if ~isempty(i)
3271                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
3272                     pause(0);
3273                     Xivec(i) = [];
3274                 end
3275                 i = find(Yivec>length(diag(SVy)));
3276                 if ~isempty(i)
3277                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
3278                     pause(0);
3279                     Yivec(i) = [];
3280                 end
3281
3282
3283                 Ax = Sx*Vx(:,Xivec);
3284                 Tx = inv(Ax'*Ax)*Ax';
3285
3286                 Ay = Sy*Vy(:,Yivec);
3287                 Ty = inv(Ay'*Ay)*Ay';
3288
3289                 figure(h_fig1);
3290                 subplot(2,1,1);
3291                 semilogy(diag(SVx),'b');
3292                 hold on;
3293                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
3294                 ylabel('Horizontal');
3295                 title('Response Matrix Singular Values');
3296                 hold off;
3297                 subplot(2,1,2);
3298                 semilogy(diag(SVy),'b');
3299                 hold on;
3300                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
3301                 xlabel('Singular Value Number');
3302                 ylabel('Vertical');
3303                 hold off;
3304                 drawnow;
3305
3306                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List', ...
3307                     'BPM List','Change the Goal Orbit','Continue');
3308
3309                 if EditFlag == 1
3310                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
3311                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
3312                     titlestr='SVD Orbit Feedback';
3313                     lineNo=1;
3314                     answer=inputdlg(prompt,titlestr,lineNo,def);
3315                     if ~isempty(answer)
3316                         XivecNew = fix(str2num(answer{1}));
3317                         if isempty(XivecNew)
3318                             disp('   Horizontal E-vector cannot be empty.  No change made.');
3319                         else
3320                             if any(XivecNew<=0) || max(XivecNew)>length(diag(SVx))
3321                                 disp('   Error reading horizontal E-vector.  No change made.');
3322                             else
3323                                 Xivec = XivecNew;
3324                             end
3325                         end
3326                         YivecNew = fix(str2num(answer{2}));
3327                         if isempty(YivecNew)
3328                             disp('   Vertical E-vector cannot be empty.  No change made.');
3329                         else
3330                             if any(YivecNew<=0) || max(YivecNew)>length(diag(SVy))
3331                                 disp('   Error reading vertical E-vector.  No change made.');
3332                             else
3333                                 Yivec = YivecNew;
3334                             end
3335                         end
3336                     end
3337                 end
3338
3339                 if EditFlag == 2
3340                     List= getlist('HCM','Trim');
3341                     CheckList = zeros(96,1);
3342                     Elem = dev2elem('HCM', HCMlist1);
3343                     CheckList(Elem) = ones(size(Elem));
3344                     CheckList = CheckList(dev2elem('HCM',List));
3345
3346                     % Remove FF corrrectors
3347                     %           Elem = dev2elem('HCM',List);
3348                     %           for j = length(ElemFF):-1:1
3349                     %              i = find(Elem==ElemFF(j));
3350                     %              Elem(i,:) = [];
3351                     %              List(i,:) = [];
3352                     %              CheckList(i,:) = [];
3353                     %           end
3354
3355                     newList = editlist(List, 'HCMtrim', CheckList);
3356
3357                     if isempty(newList)
3358                         fprintf('   WARNING: Horizontal corrector magnet list is empty!\n');
3359                         HCMlist1 = newList;
3360                     else
3361                         HCMlist1 = newList;
3362                     end
3363                     OCSx.CM.DeviceList = HCMlist1;
3364                 end
3365
3366                 if EditFlag == 3
3367                     List = getlist('VCM','Trim');
3368                     CheckList = zeros(96,1);
3369                     Elem = dev2elem('VCM', VCMlist1);
3370                     CheckList(Elem) = ones(size(Elem));
3371                     CheckList = CheckList(dev2elem('VCM',List));
3372
3373                     % Remove FF corrrectors
3374                     %           Elem = dev2elem('VCM',List);
3375                     %           for j = length(ElemFF):-1:1
3376                     %              i = find(Elem==ElemFF(j));
3377                     %              Elem(i,:) = [];
3378                     %              List(i,:) = [];
3379                     %              CheckList(i,:) = [];
3380                     %           end
3381
3382                     newList = editlist(List, 'VCMtrim', CheckList);
3383
3384                     if isempty(newList)
3385                         fprintf('   WARNING: Vertical corrector magnet list is empty!\n');
3386                         VCMlist1 = newList;
3387                     else
3388                         VCMlist1 = newList;
3389                     end
3390                     OCSy.CM.DeviceList = VCMlist1;
3391                 end
3392
3393                 if EditFlag == 4
3394                     ListOld = BPMlist1;
3395                     XgoalOld = Xgoal;
3396                     YgoalOld = Ygoal;
3397
3398                     % Full BPM list
3399                     List = getbpmlist('Bergoz');
3400
3401                     CheckList = zeros(size(List,1),1);
3402                     if ~isempty(BPMlist1)
3403                         for i = 1:size(List,1)
3404                             k = find(List(i,1)==BPMlist1(:,1));
3405                             l = find(List(i,2)==BPMlist1(k,2));
3406
3407                             if isempty(k) || isempty(l)
3408                                 % Item not in list
3409                             else
3410                                 CheckList(i) = 1;
3411                             end
3412                         end
3413                     end
3414
3415                     newList = editlist(List, 'BPM', CheckList);
3416                     if isempty(newList)
3417                         fprintf('   BPM list cannot be empty.  No change made.\n');
3418                     else
3419                         BPMlist1 = newList;
3420                     end
3421
3422                     % Set the goal orbit to the golden orbit
3423                     Xgoal = getgolden('BPMx', BPMlist1);
3424                     Ygoal = getgolden('BPMy', BPMlist1);
3425
3426
3427                     % If a new BPM is added, then set the goal orbit to the golden orbit
3428                     for i = 1:size(BPMlist1,1)
3429
3430                         % Is it a new BPM?
3431                         k = find(BPMlist1(i,1)==ListOld(:,1));
3432                         l = find(BPMlist1(i,2)==ListOld(k,2));
3433
3434                         if isempty(k) || isempty(l)
3435                             % New BPM
3436                         else
3437                             % Use the old value for old BPM
3438                             Xgoal(i) = XgoalOld(k(l));
3439                             Ygoal(i) = YgoalOld(k(l));
3440                         end
3441                     end
3442                     OCSx.BPM.DeviceList = BPMlist1;
3443                     OCSy.BPM.DeviceList = BPMlist1;
3444                     OCSx.GoalOrbit = Xgoal;
3445                     OCSy.GoalOrbit = Ygoal;
3446                 end
3447
3448                 if EditFlag == 5
3449                     ChangeList = editlist2(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
3450
3451                     for i = 1:size(ChangeList,1)
3452
3453                         k = find(ChangeList(i,1)==BPMlist1(:,1));
3454                         l = find(ChangeList(i,2)==BPMlist1(k,2));
3455
3456                         prompt={sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
3457                         def={sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
3458                         titlestr='CHANGE THE GOAL ORBIT';
3459                         lineNo=1;
3460                         answer = inputdlg(prompt, titlestr, lineNo, def);
3461
3462                         if isempty(answer)
3463                             % No change
3464                             fprintf('   No change was made to the golden orbit.\n');
3465                         else
3466                             Xgoalnew = str2num(answer{1});
3467                             if isempty(Xgoalnew)
3468                                 fprintf('   No change was made to the horizontal golden orbit.\n');
3469                             else
3470                                 Xgoal(k(l)) = Xgoalnew;
3471                             end
3472
3473                             Ygoalnew = str2num(answer{2});
3474                             if isempty(Ygoalnew)
3475                                 fprintf('   No change was made to the vertical golden orbit.\n');
3476                             else
3477                                 Ygoal(k(l)) = Ygoalnew;
3478                             end
3479                         end
3480                     end
3481                     if ~isempty(ChangeList)
3482                         fprintf('   Note:  Changing the goal orbit for "Slow Orbit Feedback" does not change the goal orbit for "Orbit Correction."\n');
3483                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
3484                     end
3485                     OCSx.GoalOrbit = Xgoal;
3486                     OCSy.GoalOrbit = Ygoal;
3487                 end
3488
3489 %                 if EditFlag == 6
3490 %                     FFTypeFlag = questdlg(sprintf('Do you want to use a fully local or a combined local/global compensation of IDs? (nuy=9.2 only)'),'Tune FF','Local','Global', 'Global');
3491 %                     if strcmp(FFTypeFlag,'Local')
3492 %                         disp(['   The tune FF will use 8 local quadrupoles to compensate beta beating and tune shift']);
3493 %                         disp(['   from each ID.']);
3494 %                     elseif strcmp(FFTypeFlag,'Global')
3495 %                         disp(['   The tune FF will use 4 local quadrupoles to compensate beta beating and all QF+QD']);
3496 %                         disp(['   to compensate tune shift from each ID.']);
3497 %                     end
3498 %                 end
3499
3500             end
3501             close(h_fig1);
3502         end
3503
3504         % Save vectors
3505         FB.Xivec = Xivec;
3506         FB.Yivec = Yivec;
3507         FB.HCMlist1 = HCMlist1;
3508         FB.VCMlist1 = VCMlist1;
3509         FB.BPMlist1 = BPMlist1;
3510
3511         OCSx.SVDIndex = Xivec;
3512         OCSy.SVDIndex = Yivec;
3513         FB.OCSx = OCSx;
3514         FB.OCSy = OCSy;
3515
3516         FB.FFTypeFlag = FFTypeFlag;
3517         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata',FB);
3518
3519
3520     case 'FastFeedbackSetup'
3521
3522         InitFlag = Input2;
3523
3524         if InitFlag
3525             FOFBFreq = 1000;
3526             % user operations 9/14-10/17/04: P=0.5, I=120, D=0.0015 (for both planes)
3527             % below are known good values for user ops as of 8-1-05
3528             HorP = 2;
3529             HorI = 300;
3530             HorD = 0.002;
3531             VertP = 1;
3532             VertI = 100;
3533             VertD = 0.0015;
3534
3535             % this initial set is now done in hwinit.m because it's not a good idea to set anything when srcontrol is launched
3536             % try
3537             %     setsp('SR01____FFBFREQAC00', FOFBFreq); % set freq
3538             %     write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3539             % catch
3540             %     fprintf('   %s \n',lasterr);
3541             %     disp('   Trouble setting Fast Orbit Feedback parameters!');
3542             % end
3543
3544         else
3545             % Get vectors
3546             FOFB = get(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata');
3547             FOFBFreq = FOFB.FOFBFreq;
3548             HorP  = FOFB.HorP;
3549             HorI  = FOFB.HorI;
3550             HorD  = FOFB.HorD;
3551             VertP = FOFB.VertP;
3552             VertI = FOFB.VertI;
3553             VertD = FOFB.VertD;
3554
3555             % Add button to change #ivectors, CMs, IDBPMs,
3556             EditFlag = 0;
3557             %h_fig1 = figure;
3558             while EditFlag ~= 3
3559
3560                 %EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'HCM List', 'VCM List', ...
3561                 %   'IDBPM List', 'BBPM List', 'Continue');
3562                 % Use menu below until other FFB config routines work (then also uncomment options 3,4,5,6 below)
3563                 EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'Continue');
3564
3565                 if EditFlag == 1
3566                     % change rate
3567
3568                     prompt={'Enter the desired Fast Feedback Frequency (1-1000 Hz)'};
3569                     def={num2str(FOFBFreq)};
3570                     titlestr='Fast Feedback Setup';
3571                     lineNo=1;
3572                     answer=inputdlg(prompt,titlestr,lineNo,def);
3573                     if ~isempty(answer)
3574                         FOFBFreq = fix(str2num(answer{1}));
3575                         if isempty(FOFBFreq)
3576                             disp('   Frequency value cannot be empty.  No change made.');
3577                             FOFBFreq = getsp('SR01____FFBFREQAC00');
3578                         else
3579                             if FOFBFreq < 1 || FOFBFreq > 1000
3580                                 disp('   Frequency must be between 1 and 1000 Hz.  No change made.');
3581                                 FOFBFreq = getsp('SR01____FFBFREQAC00');
3582                             end
3583                         end
3584                         setsp('SR01____FFBFREQAC00',FOFBFreq); % change freq
3585                         pause(0.5);
3586                         fprintf('   Fast orbit feedback frequency is running at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
3587                     else
3588                         FOFBFreq = getsp('SR01____FFBFREQAC00');
3589                     end
3590                 end
3591
3592                 if EditFlag == 2
3593                     % edit  PIDs
3594                     % User defaults are HorP=2, HorI=300, HorD=0.002, VertP=1, VertI=100, VertD=0.0015
3595                     prompt={'P horizontal', 'I horizontal', 'D horizontal', 'P vertical', 'I vertical', 'D vertical'};
3596                     def={num2str(HorP), num2str(HorI), num2str(HorD), num2str(VertP), num2str(VertI), num2str(VertD)};
3597                     titlestr='Fast Feedback PID Setup';
3598                     lineNo=1;
3599                     answer=inputdlg(prompt,titlestr,lineNo,def);
3600                     if ~isempty(answer)
3601                         HorPnewnum = str2num(answer{1});
3602                         if isempty(HorPnewnum)
3603                             disp('   HorP value cannot be empty.  No change made.');
3604                         else
3605                             HorP = HorPnewnum;
3606                         end
3607                         HorInewnum = str2num(answer{2});
3608                         if isempty(HorInewnum)
3609                             disp('   HorI value cannot be empty.  No change made.');
3610                         else
3611                             HorI = HorInewnum;
3612                         end
3613                         HorDnewnum = str2num(answer{3});
3614                         if isempty(HorDnewnum)
3615                             disp('   HorD value cannot be empty.  No change made.');
3616                         else
3617                             HorD = HorDnewnum;
3618                         end
3619                         VertPnewnum = str2num(answer{4});
3620                         if isempty(VertPnewnum)
3621                             disp('   VertP value cannot be empty.  No change made.');
3622                         else
3623                             VertP = VertPnewnum;
3624                         end
3625                         VertInewnum = str2num(answer{5});
3626                         if isempty(VertInewnum)
3627                             disp('   VertI value cannot be empty.  No change made.');
3628                         else
3629                             VertI = VertInewnum;
3630                         end
3631                         VertDnewnum = str2num(answer{6});
3632                         if isempty(VertDnewnum)
3633                             disp('   VertD value cannot be empty.  No change made.');
3634                         else
3635                             VertD = VertDnewnum;
3636                         end
3637
3638                         try
3639                             write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3640                             fprintf('   Setting FFB gains to Horizontal P=%.2f, I=%.1f, D=%.4f;  Vertical P=%.2f, I=%.1f, D=%.4f\n', HorP, HorI, HorD, VertP, VertI, VertD);
3641                         catch
3642                             fprintf('   %s \n',lasterr);
3643                             disp('   Trouble setting Fast Orbit Feedback parameters!');
3644                         end
3645                     end
3646                 end
3647
3648                 %if EditFlag == 3
3649                 %   disp('   This function not yet available.');
3650                 %   % change HCM List
3651                 %end
3652                 %
3653                 %if EditFlag == 4
3654                 %   disp('   This function not yet available.');
3655                 %   % change VCM List
3656                 %end
3657                 %
3658                 %if EditFlag == 5
3659                 %   disp('   This function not yet available.');
3660                 %   % change IDBPM List
3661                 %end
3662                 %
3663                 %if EditFlag == 6
3664                 %   disp('   This function not yet available.');
3665                 %   % change BBPM List
3666                 %end
3667
3668             end
3669             %close(h_fig1);
3670         end
3671
3672         % Save vectors
3673         FOFB.FOFBFreq = FOFBFreq;
3674         FOFB.HorP = HorP;
3675         FOFB.HorI = HorI;
3676         FOFB.HorD = HorD;
3677         FOFB.VertP = VertP;
3678         FOFB.VertI = VertI;
3679         FOFB.VertD = VertD;
3680         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata',FOFB);
3681
3682     otherwise
3683         fprintf('   No action for %s.\n', action);
3684 end   % end case