Description of srcontrol5_topoff_no_loads
Home > ALS > StorageRing > srcontrol5_topoff_no_loads.m
srcontrol5_topoff_no_loads
PURPOSE
srcontrol5
SYNOPSIS
function srcontrol5(action, Input2, Input3)
DESCRIPTION
 srcontrol5
 Storage ring control program
 This program controls all storage ring magnets, performs orbit feedback and
 tune feedforward and helps to diagnose problems in routine user operation
 of the ALS storage ring. It includes a gui to simplify the use of this
 program.
 It was originally programmed by Greg Portmann (until December 2000) with input
 from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
 and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
 The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
 Christoph Steier, July 2002
 SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
 Tom Scarvie, April 2005
CROSS-REFERENCE INFORMATION
This function calls:
amp2k AMP2K - Converts amperes to simulator values
bend2gev BEND2GEV - Compute the energy based on the ramp tables
checksrmags CHECKSRMAGS - Check SR power supplies against a lattice file
checksrorbit ErrorNums =checksrorbit(Sector, BPMxtolerance [.015 mm], [BPMytolerance [.015 mm]])
gap2tune GAP2TUNE - Computes the vertical tune shift for a insertion device gap change.
gaplimit [GapMin, GapMax] = gaplimit(DeviceList)
getbpmlist GETBPMLIST - Return a BPM list based on key words and sector numbers
getbpmtimeconstant GETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
getff GETFF - Get the state of insertion device feed forward and user gap contr5ol
getid GETID - Get the insertion device position, velocity, run flag, and user requested gap
getsrstate [StateNumber, StateString] = getsrstate
ocsinit OCSINIT - Corrector and BPM
set_alarmhandler_AHU_thresholds_inject function set_alarmhandler_AHU_thresholds_inject
set_etaywave_nuy9_20skews_skewFF function [SQSFincr, SQSDincr] = set_etaywave_nuy9_20skews_skewFF(scale);
setbpmtimeconstant SETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
setbumps SETBUMPS - Make a straight section bump
setff function setff(DeviceList, FFEnableBC, GapEnableBC)
setid SETID - Set the insertion device vertical gap
setsrstatechannels
srcycle SRCYCLE - Storage ring cycle
srramp SRRAMP - Ramp the storage ring energy
write_goldenorbit_ffb function write_goldenorbit_ffb
write_goldenorbit_ffb_2planes WRITE_GOLDENORBIT_FFTB_2PLANES - Sets the BPM setpoints which are used by the fast feedback system
This function is called by:
SOURCE CODE
function srcontrol5(action, Input2, Input3)
% srcontrol5
% Storage ring control program
%
% This program controls all storage ring magnets, performs orbit feedback and
% tune feedforward and helps to diagnose problems in routine user operation
% of the ALS storage ring. It includes a gui to simplify the use of this
% program.
%
% It was originally programmed by Greg Portmann (until December 2000) with input
% from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
% and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
%
% The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
%
% Christoph Steier, July 2002
%
% SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
%
% Tom Scarvie, April 2005
% known bugs/problems (May 2001):
% - IDBPM averaging might be a bit too long for orbit feedback
%        solved after Superbend shutdown ... Instead of averaging, digital low pass filters are used
% - gap2tune does not give correct answers for wiggler and potentially other IDs -> orbit feedback
%        seems to be OK for other IDs, has been corrected for wiggler (fit to insertion device
%        compensation table)
% - chicanes do not work in orbit feedback
%        solved. One problem was that orbit response matrizes were mis-scaled by factor of two.
%        Second problem was different time constant of power supply control. Solved by moving controls
%        of center chicanes to cPCI (and magnets are fast, hysteresis free, aircore coils).
%        Center chicane in sector 4 is now routinely used in orbit feedback. Sector 11 to follow soon.
% - zero reading of ID gap dumps beam
%        solved in srcontrol5, still a problem in srcontrol5_hightune (but that routine has to be completely
%        rewritten because of all recent changes to srcontrol5, anyhow). For gap readings below the minimum
%        allowed gap for a device, the tune feedforward disables itself.
% - cycling of lattice causes frequent power supply failures
%        solved by changing the cycling procedure. 1.5 GeV operation is now on the upper hysteresis branch
%        as was the 1.9 GeV injection lattice before.
% - frequently stalled data in IDBPM readout
%        solved with new BPM readouts and digital filtering. Seems to have been a resolution problem
%        of the digital averaging algorithm.
% - magnet ramp tables are not in perfect agreement with magnetic measurements
%        Does not appear to be a serious problem. Superbends are slightly out of sync with other magnets,
%        but this does not cause any negative effects while ramping.
% - no good way to operate with injection at 1.5 GeV and storage energy below that
%        There now is a reasonable way to inject at 1.5 GeV and ramp down to lower storage energy. But
%        it has to be tested again after implementing new (and more) chicanes ...
% revision history
% 2001-05-10, Christoph Steier
% check whether readback from insertion device is significantly (more than 1 mm) below minimum
% gap, to avoid false zero readings of insertion device gaps to cause the tune feed forward
% to implement false huge correction (and dump the beam). If the insertion device gap readbacks
% gets more than 1 mm below the nominal minimum gap, the routine now assumes the insertion device
% to be open.
%
% 2001-08-30 and during Superbend commissioning, Christoph Steier, Tom Scarvie, Winni Decking
% various changes have been made to incorporate the Superbends and some other new equipment
% installed in the Superbend shutdown. This included some changes to programs being called by srcontrol
% (like srload, srsave, srcycle, srramp, ...). The main changes within srcontrol were in the orbit
% correction and slow orbit feedback routines (incorporating frequency feedback, ...)
%
% 2002-05-04, Christoph Steier
% added new IDBPMs, modified orbit feedback to use trim DACs, removed LSB toggling in vertical
% orbit feedback, ...
%
% 2002-07-29, T.Scarvie
% added check of CM trim currents to warn of problems that might rail the orbit feedback
%
% 2002-07-31, Christoph Steier
% increased the gain of the RF frequency feedback from 1/50 of the gain of the horizontal
% orbit feedback to 1/20. Reason was that the frequency feedback was reacting a bit too slow if all
% insertion device gaps are closed at once at high speed at the beginning of a fill.
%
% 2002-08-05, C.Steier, T.Scarvie
% Added conditional to reduce orbit feedback gain if running in two-bunch mode
%
% 2003-06-02, T.Scarvie
% Added loop inside orbit feedback to reset the SR11 chicane M1 and M2 motors every 20s to combat drift problem
%
% 2003-06-18, C. Steier
% Disabled loop to periodically reset chicane in SR11. Al Robb replaced power supply, seems to be no problem anymore.
%
% 2004-05-10, C. Steier
% The list of all BBPMs is now set up automatically be calling getlist('BBPMx'). This way, new BBPMs have to be added
% at fewer places in the software. It should now be sufficient to modify getlist and run the orbit response matrix
% rountine (getsmat) once to enable use of the new BBPMs.
%
% 2004-05-14, C. Steier
% Modified parameters for ramprate reduction (in srramp and here). Previous parameters were slightly too
% cautious. Increased initial slow ramprate to 0.4 A/s.
%
% 2004-05-14, C. Steier
% Incorporated insertion device compensation schemes for nu_y = 9.2 lattice.
%
% 2004-06-14, T.Scarvie
% Added controls for fast orbit feedback
%
% 2004-06-21, C. Steier
% Added tune feedforward (in the global tune compensation scheme for the nu_y=9.2 lattice) for the shift
% dependent tune shift of the EPUs, as well as a skew quadrupole feedforward for the EPU im sector 11
% (both only active in parallel mode so far).
%
% 2005-02-13, T.Scarvie
% Separated horizontal and vertical planes for setting Fast Feedback PIDs
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NOTES for conversion to new Middle Layer %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% We never use the gap and bump control flags - the radio buttons have been disabled -
%        should we try to keep the functionality?
%
% checksrmags
% checksrorbit(...)
% For the compiler
%#function goldenpage
%#function setoperationalmode
% Check if the AO exists
checkforao;
%%%%%%%%%%%%%%
% Initialize %
%%%%%%%%%%%%%%
global FEEDBACK_STOP_FLAG
SR_Mode = getfamilydata('OperationalMode');
SR_GEV = getfamilydata('Energy');
BSCramprate = getfamilydata('BSCRampRate');
if isnan(BSCramprate) || isempty(BSCramprate)
    BSCramprate = 0.4;
    setfamilydata(BSCramprate, 'BSCRampRate');
end
if nargin < 1
    action = 'Initialize';
end
if nargin < 2
    Input2 = 0;
end
if nargin < 3
    Input3 = 0;
end
if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
    FOFBcheckboxVal = 0;
else
    FOFBcheckboxVal = 1;
end
% if strcmp(getfamilydata('OperationalMode'), '1.5 GeV, Inject at 1.23') || strcmp(SR_Mode, '1.9 GeV, Inject at 1.353')
%     TUNEcheckboxVal = 0;
% else
TUNEcheckboxVal = 1;
% end
%%%%%%%%%%%%%%%%
% Main Program %
%%%%%%%%%%%%%%%%
switch(action)
    case 'StopOrbitFeedback'
        FEEDBACK_STOP_FLAG = 1;
    case 'Initialize'
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % GUI
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        ButtonWidth = 200;
        ButtonHeight  = 25;
        Offset1 = 8*25+12 + 47 + 25+25;
        Offset2 = 47+25+25;
        Offset3 = 45+25;
        Offset4 = 1;
        Offset5 = 30;
        FigWidth = ButtonWidth+6;
        FigHeight  = 3+9*(ButtonHeight+6)+24+Offset1;
        ButtonWidth = 200-6;
        % Change figure position
        set(0,'Units','pixels');
        p=get(0,'screensize');
        h0 = figure( ...
            'Color',[0.8 0.8 0.8], ...
            'HandleVisibility','Off', ...
            'Interruptible', 'on', ...
            'MenuBar','none', ...
            'Name','ALS SR CONTROL', ...
            'NumberTitle','off', ...
            'Units','pixels', ...
            'Position',[30 p(4)-FigHeight-40 FigWidth FigHeight+Offset5], ...
            'Resize','off', ...
            'Tag','SRCTRLFig1');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'FontWeight','Bold', ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+8*(ButtonHeight+3)+19+19+8+Offset1  ButtonWidth 20+Offset5], ...
            'Style','text', ...
            'String','', ...
            'Tag','SRCTRLTitle');
        % Frame Box I
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+3*(ButtonHeight+3)+Offset1-3+Offset5 ButtonWidth+6 7*ButtonHeight+18], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+9*(ButtonHeight+3)+Offset1  ButtonWidth 15+Offset5], ...
            'Style','text', ...
            'String','Lattice Setup Functions');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Cycle'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+8*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Cycle SR Lattice', ...
            'Tag','SRCTRLButton1');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Injection'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+7*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Injection', ...
            'Tag','SRCTRLButton2');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Production'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+6*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String',['Production'], ...
            'Tag','SRCTRLButton3');
        h1 = uicontrol('Parent',h0, ...
            'Callback',[...
            'fprintf(''\n'');' ...
            'disp([''   **********************************************'']);', ...
            'disp([''   **  Changing Storage Ring Operational Mode  **'']);', ...
            'disp([''   **********************************************'']);', ...
            'setoperationalmode;', ...
            'srcontrol5(''CheckInputs'');', ...
            'disp([''   ****************************'']);', ...
            'disp([''   **  Mode Change Complete  **'']);', ...
            'disp([''   ****************************'']);', ...
            'fprintf(''\n'');'], ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+5*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'Value',1, ...
            'String','Change Operational Mode', ...
            'Tag','SRCTRLButtonChangeMode');
        h1 = uicontrol(...
            'Parent',h0, ...
            'Callback', [...
            'srcontrol5(''CheckInputs'');',...
            'srcontrol5(''SRState'');'], ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+4*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Check For Problems', ...
            'Tag','SRCTRLButtonSRState');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs''); goldenpage;', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+3*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Golden Page', ...
            'Tag','SRCTRLButtonGoldenPage');
        % Frame Box II
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+9*(ButtonHeight+3)-29+Offset2+Offset5 ButtonWidth+6 2*ButtonHeight+15], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+10*(ButtonHeight+3)-10+Offset2 ButtonWidth .6*ButtonHeight+Offset5], ...
            'String','Global/Local Orbit Correction', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''OrbitCorrection'');', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+9*(ButtonHeight+3)-6+Offset2+Offset5 ButtonWidth ButtonHeight], ...
            'String','Correct Global Orbit w/ IDBPMs', ...
            'Tag','SRCTRLButtonOrbitCorrection');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''OrbitCorrectionSetup'',1);', ...
            'callback','srcontrol5(''OrbitCorrectionSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[6 9*(ButtonHeight+3)-22+Offset2+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Edit IDBPM, CM, & Local Bump Lists', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonOrbitCorrectionSetup');
        % Frame Box III
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 1*(ButtonHeight)+Offset3+Offset5-38 ButtonWidth+6 8*ButtonHeight+61], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+9*(ButtonHeight+3)+Offset3-25 ButtonWidth .55*ButtonHeight+Offset5], ...
            'String','Orbit Feedback', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+8*(ButtonHeight+3)+Offset3-18+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Slow Orbit Correction', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxSOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+7*(ButtonHeight+3)+Offset3-9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Fast Orbit Correction', ...
            'Style','checkbox', ...
            'Value',FOFBcheckboxVal,...
            'Tag','SRCTRLCheckboxFOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+6*(ButtonHeight+3)+Offset3+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct ID Tune Shift  ', ...
            'Style','checkbox', ...
            'Value',TUNEcheckboxVal,...
            'Tag','SRCTRLCheckboxTune');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+5*(ButtonHeight+3)+Offset3+9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct RF Frequency', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxRF');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''Feedback'');', ...
            'Enable','on', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[8 3+5*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Start FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStart');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''StopOrbitFeedback'');pause(0);', ...
            'Enable','off', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[.5*FigWidth+3 3+5*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Stop FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStop');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[14 4*(ButtonHeight)+Offset3+Offset5-3 ButtonWidth-14 .75*ButtonHeight], ...
            'String','Horizontal RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHorizontal');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[26 3+3.5*(ButtonHeight)+16+Offset3-25+Offset5 ButtonWidth-26 .75*ButtonHeight], ...
            'String','Vertical RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextVertical');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FeedbackSetup'',1);', ...
            'callback','srcontrol5(''FeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 3+3.5*(ButtonHeight)+.5+Offset3-25+Offset5 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit SOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFeedbackSetup');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','01 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB01');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','02 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB02');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','03 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB03');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','04 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB04');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','05 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB05');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','06 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB06');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','07 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB07');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','08 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB08');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','09 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB09');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','10 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB10');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','11 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB11');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','12 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB12');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FastFeedbackSetup'',1);', ...
            'callback','srcontrol5(''FastFeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 1*(ButtonHeight)+Offset3-3 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit FOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFastFeedbackSetup');
        % Frame Box IV
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+ButtonHeight+Offset4-14+Offset5 ButtonWidth+6 ButtonHeight+12], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+1.75*ButtonHeight+5+Offset4-21+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Storage Ring State', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHeader');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''CheckInputs'');', ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ForegroundColor','b', ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+ButtonHeight+6+3+2+Offset4-22+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','   ', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextInformation');
        % Frame Box "Close"
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 8 ButtonWidth+6 ButtonHeight+8], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'Callback','close(gcbf);', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 13 ButtonWidth ButtonHeight], ...
            'String','Close', ...
            'Tag','SRCTRLClose');
        % Update database channels
        setsrstatechannels;
        if nargout > 0
            fig = h0;
        end
    case 'Cycle'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        disp('   **************************');
        disp('   **  Storage Ring Cycle  **');
        disp('   **************************');
        a = clock; fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        BSCFlag = questdlg(sprintf('Cycle Superbend Magnets?'),'SR Cycle','Yes','No','No');
        %if strcmp(BSCFlag,'No')
        %    disp(['   ** Superbends will not be cycled. **']);
        %else
        %    disp(['   ** Superbends will be cycled during the second mini-cycle only. **']);
        %end
        ChicSQFlag = questdlg(sprintf('Cycle chicanes and skew quads and home motor chicanes?'),'SR Cycle','Yes','No','No');
        %if strcmp(ChicSQFlag,'No')
        %    disp(['   ** Chicanes and skew quads will not be cycled; motor chicanes will not be homed. **']);
        %else
        %    disp(['   ** Chicanes and skew quads will be cycled; motor chicanes will be homed. **']);
        %end
        StartFlag = questdlg(sprintf('Start %.1f GeV Cycle?',SR_GEV),'SR Cycle','Yes','No','No');
        if strcmp(StartFlag,'No')
            disp(['   ***************************']);
            disp(['   **    Cycle  Canceled    **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        end
        try
            if GapFlag
                % Make sure that the gaps are open with FF off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open.');
                    disp('   Opening all gaps at maximum speed.');
                    setff([], 1, 0);
                    disp('   Gap control disabled.');
                    disp('   Feed forward enabled.');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened.');
                    disp('   Feed forward and gap control disabled.');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled.');
                end
            else
                disp('   Feed forward and gap control disabled.');
            end
            setff([], 0, 0);
            pause(1);
            srcycle(BSCFlag, ChicSQFlag);
            setpv('SR_STATE',1);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Cycle failed due to error condition! \n\n');
            setpv('SR_STATE',-1);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp('   **********************************************');
            disp('   **  SR Cycle complete, ready for injection  **');
            disp('   **********************************************'); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp('   **********************************');
            disp('   **  Problem cycling SR lattice  **');
            disp('   **********************************'); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
    case 'Injection'
        AD = getad;
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            fprintf('   ***************************************************\n');
            fprintf('   **  Setup For %.2f GeV Injection (with ramping)  **\n', getfamilydata('InjectionEnergy'));
            fprintf('   ***************************************************\n');
            set_alarmhandler_AHU_thresholds_inject;
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',getfamilydata('InjectionEnergy')),'Injection Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            fprintf('   *************************************************\n');
            fprintf('   **  Setup For On Energy Injection at %.2f GeV  **\n', SR_GEV);
            fprintf('   *************************************************\n');
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',SR_GEV),'Injection Setup','Yes','Cancel','Cancel');
        end
        if strcmp(StartFlag,'Cancel')
            disp(['   ********************************']);
            disp(['   **  Injection Setup Canceled  **']);
            disp(['   ********************************']);
            %set_alarmhandler_thresholds_new;
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                setff([],1,0);
                disp('   Gap control disabled');
                disp('   Feed forward enabled');
                pause(1);
                % Set IDs at max velocity w/ velocity profile off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    disp('   Opening all gaps');
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                end
                disp('   Gaps are open');
                disp('   Feed forward and gap control disabled');
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            if (AD.Energy-AD.InjectionEnergy) > 0.05
                % Ramp down to Injection Energy
                set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String','Ramping Down','ForegroundColor','b');
                drawnow;
                ErrorFlag = srramp('Injection');
                if ErrorFlag
                    error('Superbends over temperature.');
                end
                a = clock; fprintf('   %s %d:%d:%.0f\n\n',date, a(4), a(5), a(6));
            elseif (AD.Energy-AD.InjectionEnergy) < -0.05
                % first load injection lattice, then ramp to 1.9 GeV and back to 1.5 GeV to get onto same hysteresis branch
                srload('Injection');
                % load 1.9 GeV lattice
                tempfilename = sprintf('%s19nuy9prod.mat', getfamilydata('Directory','OpsData'));
                srload(tempfilename);
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                pause(5);
            end
            srload('Injection');
            setpv('SR_STATE',2);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Injection lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-2);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            if AD.Energy <= 1.5
                disp(['   *******************************************************************************']);
                disp(['   **  Function complete:  the storage ring is setup for injection at ',sprintf('%.2f',SR_GEV),' GeV  **']);
                disp(['   *******************************************************************************']);
                fprintf('\n');
            else
                fprintf('   **********************************************************************************************\n');
                fprintf('   **  Function complete:  the storage ring is setup for injection at %.2f GeV (upper branch)  **\n', getfamilydata('InjectionEnergy'));
                fprintf('   **********************************************************************************************\n');
                fprintf('\n');
            end
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   ************************************']);
            disp(['   **  Problem with injection setup  **']);
            disp(['   ************************************']);
            fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        %soundchord;
        setfamilydata(0.8, 'BSCRampRate');
    case 'Production'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        AD=getad;
        fprintf('\n');
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            disp('   ********************************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation (with ramping)  **',SR_GEV));
            disp('   ********************************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            disp('   *****************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation  **',SR_GEV));
            disp('   *****************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Yes','Cancel','Cancel');
        end
        if strcmp(StartFlag,'Cancel')
            disp(['   ***************************']);
            disp(['   **  User Setup Canceled  **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                % Make sure that the gaps are open
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open');
                    disp('   Opening all gaps at maximum speed');
                    setff([], 1, 0);
                    disp('   Gap control disabled');
                    disp('   Feed forward enabled');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened');
                    disp('   Feed forward and gap control disabled');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled');
                end
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            %%%%%%%%%%%%%%%
            if (AD.Energy-AD.InjectionEnergy) > 0.05
                % Ramp up to the production lattice
                set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String','Ramping Up','ForegroundColor','b');
                drawnow;
                ErrorFlag = srramp('Production');
                if ErrorFlag
                    error('Superbends over temperature.');
                end
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                srload('Production');
            elseif abs(AD.Energy-AD.InjectionEnergy) < 0.05
                % load production lattice - no ramp required
                srload('Production');
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                pause(5);
            end
            %%%%%%%%%%%%%%%
            if GapFlag
                setff([], 1, 0);
                disp('   Gap control disabled');
                disp('   Feed forward enable');
                pause(1);
                disp('   Insertion device velocity profile boolean control off');
                disp('   Closing all gaps at maximum speed');
                % Set IDs at max velocity w/ velocity profile off
                [Position, Velocity, RunFlag, UserGap] = getid;
                setid([], UserGap, maxsp('IDvel'), 1, 0, 1);
                % Turn velocity profile on
                disp('   Insertion device velocity profile boolean control is on');
                setid([], [], maxsp('IDvel'), 1, 1, 0);
                disp('   Gaps are closed');
                setff([4;7;8;9;10;12], 1, 1);
                setff(5, 1, 0);
                disp('   Gap control enabled (except sector 5 (W16))');
            end
            %set_alarmhandler_thresholds_new;
            setpv('SR_STATE',3);
        catch
            fprintf('   %s \n', lasterr);
            fprintf('   User lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-3);
        end
        %give JH scrapers a chance to move
        pause(15);
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp(['   **************************************************************************']);
            disp(['   **  Function complete:  the storage ring is setup for users at ',sprintf('%.1f',SR_GEV),' GeV  **']);
            disp(['   **************************************************************************']); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   *************************************']);
            disp(['   **  Problem with production setup  **']);
            disp(['   *************************************']); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        setfamilydata(0.8, 'BSCRampRate');
%         % for BL6.0.x, set lower setpoint limit for IVID to 12.5mm until beamlines are surveyed below that value
%         try
%             scaput('SR06U___GDS1PS_AC00.DRVL',12.5);
%             disp('  Setting SR06U___GDS1PS_AC00.DRVL to 12.5mm (lower limit for IVID');
%         catch
%             disp('  Trouble setting lower limit for IVID to 12.5mm!');
%         end
    case 'CheckInputs'
        SR_GEV = getfamilydata('Energy');
        AD=getad;
        setsrstatechannels;
        set(0,'showhiddenhandles','on');
1000         if AD.Energy > 1.55 & AD.InjectionEnergy < 1.55
1001             set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Down)']);
1002             set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users (Ramp Up)']);
1003         elseif AD.Energy < 1.45
1004             set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Up+cycle)']);
1005             set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV (Ramp Down)']);
1006         else
1007             set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection']);
1008             set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV']);
1009         end
1010         set(findobj('Tag','SRCTRLTitle'),'String',SR_Mode);
1011
1012         [StateNumber, StateString] = getsrstate;
1013         if StateNumber >= 0
1014             set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1015         else
1016             set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1017         end
1018
1019         set(0,'showhiddenhandles','off');
1020
1021
1022     case 'SRState'
1023         NumErrors = 0;
1024         fprintf('\n');
1025         disp('   ***********************************');
1026         disp('   **  Checking Storage Ring State  **');
1027         disp('   ***********************************');
1028         a = clock;
1029         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1030
1031         %       FileName = getpv('SR_LATTICE_FILE','String');   % Last srload file name (in OLD MIDDLE LAYER nomenclature!!)
1032
1033         GeVnow = bend2gev;
1034         if GeVnow == getfamilydata('Energy')
1035             [ConfigSetpoint, ConfigMonitor, FileName] = getproductionlattice;
1036         elseif GeVnow == getfamilydata('InjectionEnergy')
1037             [ConfigSetpoint, ConfigMonitor, FileName] = getinjectionlattice;
1038         else
1039             FileName = '';
1040         end
1041
1042         [StateNumber, StateString] = getsrstate;
1043         fprintf('   Storage ring operational mode: %s\n', SR_Mode);
1044         if StateNumber < 0
1045             fprintf('   Storage ring state error: %s\n', StateString);
1046             NumErrors = NumErrors + 1;
1047         else
1048             fprintf('   Storage ring state: %s\n', StateString);
1049         end
1050         if StateNumber==0
1051             % Storage ring state unknown
1052             NumErrors = NumErrors + 1;
1053         elseif abs(StateNumber)==1 || abs(StateNumber)==2
1054             FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','InjectionFile') '.mat'];
1055             if ~strcmp(FileName, FileNameGoal)
1056                 fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','InjectionFile'), FileName);
1057                 NumErrors = NumErrors + 1;
1058             end
1059         else
1060             FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile') '.mat'];
1061             if ~strcmp(FileName, FileNameGoal)
1062                 fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','LatticeFile'), FileName);
1063                 NumErrors = NumErrors + 1;
1064             end
1065         end
1066
1067
1068         % Check all SR magnets
1069         if isempty(FileName)
1070             fprintf('   Goal setpoints will not be checked since the last lattice load is unknown.\n');
1071             NumErrors1 = checksrmags('');
1072         else
1073 %            NumErrors1 = checksrmags([getfamilydata('Directory','OpsData') FileName]);
1074             NumErrors1 = checksrmags(FileName);
1075         end
1076         if NumErrors1 == 0
1077             fprintf('   SR magnets power supplies are OK.\n');
1078         end
1079         NumErrors = NumErrors + NumErrors1;
1080
1081
1082         % Check RF frequency
1083         if isempty(FileName)
1084             fprintf('   RF frequency will not be checked since the last lattice load is unknown.\n');
1085         else
1086 %            load([getfamilydata('Directory','OpsData'), FileName]);
1087             load(FileName);
1088             [tmp, RFHPCounterPresent] = getrf;
1089             if abs(RFHPCounterPresent-ConfigSetpoint.RF.Setpoint.Data) > .002
1090                 NumErrors = NumErrors + 1;
1091                 fprintf('   RF frequency should be %f, presently it is %f MHz (as measured by the HP counter).\n', ConfigSetpoint.RF.Setpoint.Data, RFHPCounterPresent);
1092             else
1093                 fprintf('   RF frequency is OK (HP counter is %f MHz, at the time of the lattice save it was %f MHz).\n', RFHPCounterPresent, ConfigSetpoint.RF.Setpoint.Data);
1094             end
1095         end
1096
1097
1098         % Check for orbit problems
1099         if (StateNumber >= 3) && (getdcct > 2)   % Production lattice is loaded with beam in the machine
1100             Xtol = 0.070;
1101             Ytol = 0.010;
1102             NumErrors1 = checksrorbit([],Xtol,Ytol);
1103             if NumErrors1
1104                 fprintf('   SR orbit in the ID straight sections or at Bergoz BPMs deviates more than allowed from the golden orbit.\n');
1105             else
1106                 fprintf('   SR orbit in the ID straight sections and at Bergoz BPMs is OK.\n');
1107                 fprintf('   The orbit is within %.3f mm horizontally and %.3f mm vertically', Xtol, Ytol);
1108             end
1109             NumErrors = NumErrors + NumErrors1;
1110         else
1111             fprintf('   Storage ring orbit was not checked.\n');
1112         end
1113
1114
1115         a = clock;
1116         datestr1=date;
1117         fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
1118         if NumErrors
1119             disp('   *********************************');
1120             disp('   **  Storage Ring Has Problems  **');
1121             disp('   *********************************');
1122         else
1123             disp('   **********************************');
1124             disp('   **  Storage Ring Lattice is OK  **');
1125             disp('   **********************************');
1126         end
1127         fprintf('   \n');
1128
1129         set(0,'showhiddenhandles','on');
1130         [StateNumber, StateString] = getsrstate;
1131         if StateNumber >= 0
1132             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1133         else
1134             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1135         end
1136         set(0,'showhiddenhandles','off');
1137
1138
1139     case 'OrbitCorrection'
1140         fprintf('\n');
1141         fprintf('   *********************************\n');
1142         fprintf('   **  Starting Orbit Correction  **\n');
1143         fprintf('   *********************************\n');
1144         a = clock;
1145         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1146
1147         StartFlag = questdlg(sprintf('Start orbit correction, %.1f GeV?',SR_GEV),'Orbit Correction','Yes','No','No');
1148         if strcmp(StartFlag,'No')
1149             disp(['   ********************************']);
1150             disp(['   **  Orbit Correction Aborted  **']);
1151             disp(['   ********************************']);
1152             fprintf('\n');
1153             return
1154         end
1155
1156         if getdcct < 5     % Don't correct the orbit if the current is too small
1157             fprintf('   Orbit not corrected due to small current.\n');
1158             return
1159         end
1160
1161         if abs(SR_GEV-bend2gev(getpv('BEND','Setpoint',[1 1])))>  0.05     % Don't use this routine for the injection lattice
1162             fprintf('   This routine should only be used for the production energy: Correction aborted\n');
1163             return
1164         end
1165
1166         SR_STATE_OLD = scaget('SR_STATE');
1167         set(0,'showhiddenhandles','on');
1168         setpv('SR_STATE',4);
1169         [StateNumber, StateString] = getsrstate;
1170         if StateNumber >= 0
1171             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1172         else
1173             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1174         end
1175         set(0,'showhiddenhandles','off');
1176
1177
1178         try
1179             % save current BPM timeconstant - will reset to this after correction
1180             BPMtimeconstantOC = getbpmtimeconstant;
1181             fprintf('   Current Bergoz BPM time constant is %.1fs\n', BPMtimeconstantOC);
1182
1183             % 2 Hz update rate on IDBPMs
1184             disp('   Bergoz BPM time constant set to 0.5s.')
1185             setbpmtimeconstant(0.5)
1186             pause(2);
1187
1188
1189             % Turn off feed forward
1190             fprintf('   Turning feed forward off.\n');
1191             [FFEnableBM, FFEnableBC] = getff;
1192             setff([], 0);
1193             scasleep(.2);
1194
1195
1196             % Get vectors
1197             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1198             LocalBumplist = FB.LocalBumplist;
1199
1200         catch
1201
1202             fprintf('   %s \n',lasterr);
1203             fprintf('   Orbit correction setup failed due to error condition! \n\n');
1204             setpv('SR_STATE',-4);
1205             set(0,'showhiddenhandles','on');
1206             [StateNumber, StateString] = getsrstate;
1207             if StateNumber >= 0
1208                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1209             else
1210                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1211             end
1212             set(0,'showhiddenhandles','off');
1213
1214             % Reset BPM timeconstant to whatever it was before correction
1215             setbpmtimeconstant(BPMtimeconstantOC);
1216             fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1217             return
1218         end
1219
1220         iNotHCMChicane = find(FB.HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
1221         iHCMChicane = find(FB.HCMlist1(:,2) == 10);
1222         iNotVCMChicane = find(FB.VCMlist1(:,2) < 10);
1223         iVCMChicane = find(FB.VCMlist1(:,2) == 10);
1224
1225         fprintf('   Starting horizontal and vertical global orbit correction (SVD method).\n');
1226
1227         for iloop = 1:3
1228             try
1229                 % use the following to get corrector settings in OCS without setting them, so the values can be checked
1230                 FB.OCSx = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
1231                 FB.OCSy = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
1232                 if any(abs(FB.OCSx.CM.Delta(iNotHCMChicane)) > 5)
1233                   disp('   Orbit Correction is changing some horizontal corrector(s) > 5A!!');
1234                 end
1235                 if any(abs(FB.OCSy.CM.Delta(iNotVCMChicane)) > 5)
1236                   disp('   Orbit Correction is changing some vertical corrector(s) > 5A!!');
1237                 end
1238                 if any(abs(FB.OCSx.CM.Delta(iHCMChicane)) > 10)
1239                   disp('   Orbit Correction is changing some horizontal chicane corrector(s) > 10A!!');
1240                 end
1241                 if any(abs(FB.OCSy.CM.Delta(iVCMChicane)) > 10)
1242                     disp('   Orbit Correction is changing some vertical chicane corrector(s) > 10A!!');
1243                 end
1244
1245                 % Correct RF
1246                 rf0=getrf;
1247                 nRFsteps = ceil(abs(FB.OCSx.DeltaRF/10e-6));
1248                 if nRFsteps > 50
1249                     nRFsteps = 50;
1250                 end
1251                 for loop = 1:nRFsteps
1252                     steprf(FB.OCSx.DeltaRF/nRFsteps,0);
1253                 end
1254                 fprintf('   %d. nRFsteps = %d, DelRF = %.1f Hz\n',iloop, nRFsteps, FB.OCSx.DeltaRF*1e6);
1255 %               fprintf('   %d. RF change = %.1f Hz, nRFsteps = %d, DelRF = %.1f Hz\n',iloop, (getrf-rf0)*1e6, nRFsteps, FB.OCSx.DeltaRF*1e6);
1256
1257                 % Correct horizontal and vertical orbits
1258                 % calculate corrections
1259                 FB.OCSx.CM.Data = FB.OCSx.CM.Data + FB.OCSx.CM.Delta;
1260                 FB.OCSy.CM.Data = FB.OCSy.CM.Data + FB.OCSy.CM.Delta;
1261                 % start vertical correctors moving
1262                 setpv(FB.OCSy.CM,0);
1263                 % Correct horizontal
1264                 setpv(FB.OCSx.CM,-1);
1265                 % Correct vertical
1266                 setpv(FB.OCSy.CM,-2);
1267
1268                 % Check for current in machine - stop orbit correction if DCCT < 5mA
1269                 if (getdcct < 4.5)
1270                     error('**There is less than 5mA in the machine! Stopping orbit correction.');
1271                 end
1272
1273                 % Check state of gaps - stop orbit correction if any are moving
1274                 GAPrunflag = getpv('ID','RunFlag');
1275                 if any(GAPrunflag-round(GAPrunflag))
1276                     error('**One or more of the gaps are moving! Stopping orbit correction.');
1277                 end
1278
1279                 x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
1280                 y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
1281                 fprintf('   %d. Horizontal RMS = %.3f mm\n', iloop, norm(x)/sqrt(length(x)));
1282                 fprintf('   %d.   Vertical RMS = %.3f mm\n', iloop, norm(y)/sqrt(length(y)));
1283
1284             catch
1285                 % fprintf('   %s \n',lasterr);
1286                 fprintf('   Orbit correction failed due to error condition!\n  Fix the problem, reload the lattice (srload), and try again.  \n\n');
1287                 setpv('SR_STATE',-4);
1288                 set(0,'showhiddenhandles','on');
1289                 [StateNumber, StateString] = getsrstate;
1290                 if StateNumber >= 0
1291                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1292                 else
1293                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1294                 end
1295                 set(0,'showhiddenhandles','off');
1296
1297                 % Reset BPM timeconstant to whatever it was before correction
1298                 setbpmtimeconstant(BPMtimeconstantOC);
1299                 fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1300                 return
1301             end
1302         end
1303
1304
1305         % Set user bumps w/o sextupole correctors
1306         try
1307
1308             %turn up corrector speed here to quicken setting bumps
1309             HCMramprate = getpv('HCM', 'RampRate');
1310             VCMramprate = getpv('VCM', 'RampRate');
1311             setpv('HCM', 'RampRate', 10, [], 0);
1312             setpv('VCM', 'RampRate', 10, [], 0);
1313
1314             if ~isempty(LocalBumplist)
1315                 fprintf('   Setting local bumps in the straight sections.\n');
1316                 for loop = 1:size(LocalBumplist,1)
1317
1318                     % Check for current in machine - stop orbit correction if DCCT < 5mA
1319                     if (getdcct < 5)
1320                         error('** There is less than 5mA in the machine! Stopping local bumps.');
1321                     end
1322
1323                     % Check state of gaps - stop setting bumps if any are moving
1324                     GAPrunflag = getpv('ID','RunFlag');
1325                     if any(GAPrunflag-round(GAPrunflag))
1326                         error('** One or more of the gaps are moving! Stopping local bumps.');
1327                     end
1328
1329                     HCMoldsp = getsp('HCM', FB.HCMlist1);
1330                     VCMoldsp = getsp('VCM', FB.VCMlist1);
1331
1332                     if any(LocalBumplist(loop,1) == [4 6 11])
1333                         if LocalBumplist(loop,2) == 0
1334                             % Upstream bump
1335                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1336                             if isempty(iRemove)
1337                                 setbumps(LocalBumplist(loop,:), 1);
1338                             else
1339                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1340                             end
1341                         elseif LocalBumplist(loop,2) == 1
1342                             % Upstream bump
1343                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;],FB.OCSx.BPM.DeviceList);
1344                             if isempty(iRemove)
1345                                 setbumps(LocalBumplist(loop,:), 1);
1346                             else
1347                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1348                             end
1349                         else
1350                             % Downstream bump
1351                             [i, iRemove] = findrowindex([LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1352                             if isempty(iRemove)
1353                                 setbumps(LocalBumplist(loop,:), 1);
1354                             else
1355                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1356                             end
1357                         end
1358                     else
1359                         [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1360                         if isempty(iRemove)
1361                             setbumps(LocalBumplist(loop,:), 1);
1362                         else
1363                             fprintf('\n   BPMs missing from Sector %02d - skipping local bump for that sector.\n\n', LocalBumplist(loop,1));
1364                         end
1365                     end
1366
1367                     HCMnewsp = getsp('HCM', FB.HCMlist1);
1368                     VCMnewsp = getsp('VCM', FB.VCMlist1);
1369                     % Remove center chicane trim from corrector check
1370                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 5) || (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 10)
1371                         error('**Setbumps caused some corrector magnet currents to change by more than 5(Horiz)/10(Vert) A!');
1372                     end
1373                     % Now check center chicane trims
1374                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 10) || (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 15)
1375                         error('**Setbumps caused some chicane trim magnet currents to change by more than 10(Horiz)/15(Vert) A!');
1376                     end
1377                 end
1378             end
1379
1380             %restore corrector speeds
1381             setpv('HCM', 'RampRate', HCMramprate, [], 0);
1382             setpv('VCM', 'RampRate', VCMramprate, [], 0);
1383
1384         catch
1385             fprintf('   %s \n',lasterr);
1386             fprintf('   Setbumps failed due to error condition!  Fix the problem, reload the lattice (srload), and try again.\n\n');
1387             setpv('SR_STATE',-4);
1388             set(0,'showhiddenhandles','on');
1389             [StateNumber, StateString] = getsrstate;
1390             if StateNumber >= 0
1391                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1392             else
1393                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1394             end
1395             set(0,'showhiddenhandles','off');
1396
1397             % Reset BPM timeconstant to whatever it was before correction
1398             setbpmtimeconstant(BPMtimeconstantOC);
1399             fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1400             return
1401         end
1402
1403         % Reset BPM timeconstant to whatever it was before correction
1404         setbpmtimeconstant(BPMtimeconstantOC);
1405         fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1406
1407         % Turn feed forward back to it's original state
1408         if any(FFEnableBC)
1409             fprintf('   Turning feed forward back on.\n');
1410             setff([], FFEnableBC);
1411         end
1412
1413
1414         a = clock;
1415         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1416         [StateNumber, StateString] = getsrstate;
1417         set(0,'showhiddenhandles','on');
1418         if StateNumber >= 0
1419             setpv('SR_STATE',4.1);
1420             [StateNumber, StateString] = getsrstate;
1421             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1422             fprintf('   *********************************\n');
1423             fprintf('   **  Orbit Correction Complete  **\n');
1424             fprintf('   *********************************\n\n');
1425         else
1426             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1427             fprintf('   *************************************\n');
1428             fprintf('   **  Problem With Orbit Correction  **\n');
1429             fprintf('   *************************************\n\n');
1430         end
1431         set(0,'showhiddenhandles','off');
1432         pause(0);
1433
1434
1435     case 'OrbitCorrectionSetup'
1436         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
1437
1438         if InitFlag
1439             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1440             % This setup is now done in ocsinit.m %
1441             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1442             % Setup feedback elements
1443             % disp('Orbit correction condition: InitFlag=1 -- debugging message');
1444
1445             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1446             % Edit the following lists to change default configuration of Orbit Correction %
1447             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1448 %             hlist=[];vlist=[];
1449 %             for Sector =1:12
1450 %                 if Sector == 1
1451 %                     vlist = [vlist;Sector 2;Sector 4;Sector 5;Sector 8];
1452 %                     hlist = [hlist;Sector 2;Sector 7];
1453 %                 elseif Sector == 3
1454 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1455 %                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1456 %                 elseif Sector == 5
1457 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1458 %                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1459 % %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8]; %remove HCM and VCM(5,10) since corrector is not controlling starting 4-6-07
1460 % %                     hlist = [hlist;Sector 2;Sector 7];
1461 %                 elseif Sector == 10
1462 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1463 %                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1464 %                 elseif Sector == 12
1465 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 7];
1466 %                     hlist = [hlist;Sector 2;Sector 7];
1467 %                 else
1468 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8];
1469 %                     hlist = [hlist;Sector 2;Sector 7];
1470 %                 end
1471 %             end
1472 %             HCMlist1 = hlist;
1473 %             VCMlist1 = vlist;
1474 %
1475 %             BPMlist1 = [
1476 %                 1 2
1477 %                 1 5
1478 %                 1 6
1479 %                 1 10
1480 %                 2 1
1481 %                 2 5
1482 %                 2 6
1483 %                 2 9
1484 %                 3 2
1485 %                 3 5
1486 %                 3 6
1487 %                 3 10
1488 %                 3 11
1489 %                 3 12
1490 %                 4 1
1491 %                 4 5
1492 %                 4 6
1493 %                 4 10
1494 %                 5 1
1495 %                 5 5
1496 %                 5 6
1497 %                 5 10
1498 %                 5 11
1499 %                 5 12
1500 %                 6 1
1501 %                 6 5
1502 %                 6 6
1503 %                 6 10
1504 %                 7 1
1505 %                 7 5
1506 %                 7 6
1507 %                 7 10
1508 %                 8 1
1509 %                 8 5
1510 %                 8 6
1511 %                 8 10
1512 %                 9 1
1513 %                 9 5
1514 %                 9 6
1515 %                 9 10
1516 %                 10 1
1517 %                 10 5
1518 %                 10 6
1519 %                 10 10
1520 %                 10 11
1521 %                 10 12
1522 %                 11 1
1523 %                 11 5
1524 %                 11 6
1525 %                 11 10
1526 %                 12 1
1527 %                 12 5
1528 %                 12 6
1529 %                 12 9];
1530 %
1531 %             % SVD orbit correction
1532 %             Xivec = [1:28];
1533 %             Yivec = [1:51];
1534 %
1535 %
1536 %             % Look for bad status BPMs
1537 %             iStatus = family2status('BPMx', BPMlist1);
1538 %             iBad = find(~iStatus);
1539 %             BPMlist1 = BPMlist1(find(iStatus),:);
1540 %             if length(iBad)
1541 %                 fprintf('   Global Orbit Correction: %d BPMs removed for bad status\n', length(iBad));
1542 %                 Yivec = Yivec(1:end-length(iBad));
1543 %             end
1544 %
1545 %             iStatus = family2status('HCM', HCMlist1);
1546 %             iBad = find(~iStatus);
1547 %             HCMlist1 = HCMlist1(find(iStatus),:);
1548 %             if length(iBad)
1549 %                 fprintf('   Global Orbit Correction: %d HCMs removed for bad status\n', length(iBad));
1550 %             end
1551 %
1552 %             iStatus = family2status('VCM', VCMlist1);
1553 %             iBad = find(~iStatus);
1554 %             VCMlist1 = VCMlist1(find(iStatus),:);
1555 %             if length(iBad)
1556 %                 fprintf('   Global Orbit Correction: %d VCMs removed for bad status\n', length(iBad));
1557 %             end
1558
1559             % Initialize RFCorrFlag
1560             RFCorrFlag = 'Yes';
1561
1562             % Get the device lists from oscsinit and convert to srcontrol variables
1563             [HBPM, VBPM, HCM, VCM, HSV, VSV] = ocsinit('TopOfFill');
1564             if strcmpi(RFCorrFlag, 'Yes')
1565                 Xivec = 1:HSV+1;
1566             else
1567                 Xivec = 1:HSV;
1568             end
1569             Yivec = 1:VSV;
1570             BPMlist1 = HBPM.DeviceList;
1571             HCMlist1 = HCM.DeviceList;
1572             VCMlist1 = VCM.DeviceList;
1573
1574
1575             LocalBumplist = [
1576               % 1 1
1577               % 2 1
1578               % 3 1
1579                 4 1
1580               % 4 2
1581                 5 1
1582               % 6 1
1583               % 6 2
1584                 7 1
1585                 8 1
1586                 9 1
1587                 10 1
1588                 11 1
1589                 11 2
1590                 12 1
1591                 ];
1592             %LocalBumplist = []
1593
1594
1595         else
1596
1597             % Get vectors
1598             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1599             BPMlist1 = FB.BPMlist1;
1600             HCMlist1 = FB.HCMlist1;
1601             VCMlist1 = FB.VCMlist1;
1602             Xivec = FB.Xivec;
1603             Yivec = FB.Yivec;
1604             LocalBumplist = FB.LocalBumplist;
1605             Xgoal = FB.Xgoal;
1606             Ygoal = FB.Ygoal;
1607             RFCorrFlag = FB.RFCorrFlag;
1608
1609             % Add button to change #ivectors, CMs, IDBPMs,
1610             EditFlag = 0;
1611             h_fig1 = figure;
1612             while EditFlag ~= 8
1613
1614                 % Sensitivity matrix
1615                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
1616                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
1617
1618                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1619                 % Can the call below work for setting FOFB RF parameter? %
1620                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1621                 if strcmpi(RFCorrFlag, 'Yes')
1622                     Sx = [Sx getdisp('BPMx',BPMlist1)];
1623                 end
1624
1625                 Sx(isnan(Sx)) = 0;
1626                 Sy(isnan(Sy)) = 0;
1627
1628                 [Ux, SVx, Vx] = svd(Sx);
1629                 [Uy, SVy, Vy] = svd(Sy);
1630
1631
1632                 % Remove singular values greater than the actual number of singular values
1633                 i = find(Xivec>length(diag(SVx)));
1634                 if ~isempty(i)
1635                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
1636                     pause(0);
1637                     Xivec(i) = [];
1638                 end
1639                 i = find(Yivec>length(diag(SVy)));
1640                 if ~isempty(i)
1641                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
1642                     pause(0);
1643                     Yivec(i) = [];
1644                 end
1645
1646
1647                 Ax = Sx*Vx(:,Xivec);
1648                 Tx = inv(Ax'*Ax)*Ax';
1649
1650                 Ay = Sy*Vy(:,Yivec);
1651                 Ty = inv(Ay'*Ay)*Ay';
1652
1653
1654                 figure(h_fig1);
1655                 subplot(2,1,1);
1656                 semilogy(diag(SVx),'b');
1657                 hold on;
1658                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
1659                 ylabel('Horizontal');
1660                 title('Response Matrix Singular Values');
1661                 hold off;
1662                 subplot(2,1,2);
1663                 semilogy(diag(SVy),'b');
1664                 hold on;
1665                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
1666                 xlabel('Singular Value Number');
1667                 ylabel('Vertical');
1668                 hold off;
1669                 drawnow;
1670
1671                 if strcmp(RFCorrFlag,'No')
1672                     RFCorrState = 'NOT CORRECTED';
1673                 elseif strcmp(RFCorrFlag,'Yes')
1674                     RFCorrState = 'CORRECTED';
1675                 else
1676                     RFCorrState = '???';
1677                 end
1678
1679                 %         EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','HCM Chicane List','VCM Chicane List','IDBPM List','BBPM List','Change Golden Orbit',...
1680                 %            'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1681                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','BPM List','Change Golden Orbit',...
1682                     'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1683
1684                 if EditFlag == 1
1685                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
1686                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
1687                     titlestr='SVD Orbit Feedback';
1688                     lineNo=1;
1689                     answer=inputdlg(prompt,titlestr,lineNo,def);
1690                     if ~isempty(answer)
1691                         XivecNew = fix(str2num(answer{1}));
1692                         if isempty(XivecNew)
1693                             disp('   Horizontal E-vector cannot be empty.  No change made.');
1694                         else
1695                             if any(XivecNew<=0) || max(XivecNew)>length(diag(SVx))
1696                                 disp('   Error reading horizontal E-vector.  No change made.');
1697                             else
1698                                 Xivec = XivecNew;
1699                             end
1700                         end
1701                         YivecNew = fix(str2num(answer{2}));
1702                         if isempty(YivecNew)
1703                             disp('   Vertical E-vector cannot be empty.  No change made.');
1704                         else
1705                             if any(YivecNew<=0) || max(YivecNew)>length(diag(SVy))
1706                                 disp('   Error reading vertical E-vector.  No change made.');
1707                             else
1708                                 Yivec = YivecNew;
1709                             end
1710                         end
1711                     end
1712                 end
1713
1714                 if EditFlag == 2
1715                     List = getlist('HCM');
1716                     CheckList = zeros(size(List,1));
1717                     Elem = dev2elem('HCM', HCMlist1);
1718                     CheckList(Elem) = ones(size(Elem));
1719                     CheckList = CheckList(dev2elem('HCM',List));
1720                     newList = editlist(List, 'HCM', CheckList);
1721                     if isempty(newList)
1722                         fprintf('   Horizontal corrector magnet list cannot be empty.  No change made.\n');
1723                     else
1724                         HCMlist1 = newList;
1725                     end
1726                 end
1727
1728                 if EditFlag == 3
1729                     List = getlist('VCM');
1730                     CheckList = zeros(size(List,1));
1731                     Elem = dev2elem('VCM', VCMlist1);
1732                     CheckList(Elem) = ones(size(Elem));
1733                     CheckList = CheckList(dev2elem('VCM',List));
1734                     newList = editlist(List, 'VCM', CheckList);
1735                     if isempty(newList)
1736                         fprintf('   Vertical corrector magnet cannot be empty.  No change made.\n');
1737                     else
1738                         VCMlist1 = newList;
1739                     end
1740                 end
1741
1742                 if EditFlag == 4
1743                     ListOld = BPMlist1;
1744                     XgoalOld = Xgoal;
1745                     YgoalOld = Ygoal;
1746
1747                     % Full BPM list
1748                     List = getbpmlist('Bergoz');
1749 %                     List = [
1750 %                         1 2
1751 %                         1 5
1752 %                         1 6
1753 %                         1 10
1754 %                         2 1
1755 %                         2 5
1756 %                         2 6
1757 %                         2 9
1758 %                         3 2
1759 %                         3 5
1760 %                         3 6
1761 %                         3 10
1762 %                         3 11
1763 %                         3 12
1764 %                         4 1
1765 %                         4 5
1766 %                         4 6
1767 %                         4 10
1768 %                         5 1
1769 %                         5 5
1770 %                         5 6
1771 %                         5 10
1772 %                         5 11
1773 %                         5 12
1774 %                         6 1
1775 %                         6 5
1776 %                         6 6
1777 %                         6 10
1778 %                         7 1
1779 %                         7 5
1780 %                         7 6
1781 %                         7 10
1782 %                         8 1
1783 %                         8 5
1784 %                         8 6
1785 %                         8 10
1786 %                         9 1
1787 %                         9 5
1788 %                         9 6
1789 %                         9 10
1790 %                         10 1
1791 %                         10 5
1792 %                         10 6
1793 %                         10 10
1794 %                         10 11
1795 %                         10 12
1796 %                         11 1
1797 %                         11 5
1798 %                         11 6
1799 %                         11 10
1800 %                         12 1
1801 %                         12 5
1802 %                         12 6
1803 %                         12 9
1804 %                         ];
1805
1806                     CheckList = zeros(size(List,1),1);
1807                     if ~isempty(BPMlist1)
1808                         for i = 1:size(List,1)
1809                             k = find(List(i,1)==BPMlist1(:,1));
1810                             l = find(List(i,2)==BPMlist1(k,2));
1811
1812                             if isempty(k) || isempty(l)
1813                                 % Item not in list
1814                             else
1815                                 CheckList(i) = 1;
1816                             end
1817                         end
1818                     end
1819
1820                     newList = editlist(List, 'BPM', CheckList);
1821                     if isempty(newList)
1822                         fprintf('   BPM list cannot be empty.  No change made.\n');
1823                     else
1824                         BPMlist1 = newList;
1825                     end
1826
1827                     % Set the goal orbit to the golden orbit
1828                     Xgoal = getgolden('BPMx', BPMlist1);
1829                     Ygoal = getgolden('BPMy', BPMlist1);
1830
1831
1832                     % If a new BPM is added, then set the goal orbit to the golden orbit
1833                     for i = 1:size(BPMlist1,1)
1834
1835                         % Is it a new BPM?
1836                         k = find(BPMlist1(i,1)==ListOld(:,1));
1837                         l = find(BPMlist1(i,2)==ListOld(k,2));
1838
1839                         if isempty(k) || isempty(l)
1840                             % New BPM
1841                         else
1842                             % Use the old value for old BPM
1843                             Xgoal(i) = XgoalOld(k(l));
1844                             Ygoal(i) = YgoalOld(k(l));
1845                         end
1846                     end
1847                 end
1848
1849                 if EditFlag == 5
1850
1851                     ChangeList = editlist(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
1852                     for i = 1:size(ChangeList,1)
1853
1854                         k = find(ChangeList(i,1)==BPMlist1(:,1));
1855                         l = find(ChangeList(i,2)==BPMlist1(k,2));
1856
1857                         prompt = {sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
1858                         def = {sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
1859                         titlestr = 'CHANGE THE GOAL ORBIT';
1860                         lineNo = 1;
1861                         answer = inputdlg(prompt, titlestr, lineNo, def);
1862
1863                         if isempty(answer)
1864                             % No change
1865                             fprintf('   No change was made to the golden orbit.\n');
1866                         else
1867                             Xgoalnew = str2num(answer{1});
1868                             if isempty(Xgoalnew)
1869                                 fprintf('   No change was made to the horizontal golden orbit.\n');
1870                             else
1871                                 Xgoal(k(l)) = Xgoalnew;
1872                             end
1873
1874                             Ygoalnew = str2num(answer{2});
1875                             if isempty(Ygoalnew)
1876                                 fprintf('   No change was made to the vertical golden orbit.\n');
1877                             else
1878                                 Ygoal(k(l)) = Ygoalnew;
1879                             end
1880                         end
1881                     end
1882                     if ~isempty(ChangeList)
1883                         fprintf('   Note:  changing the goal orbit for "Orbit Correction" does not change the goal orbit for "Slow Orbit Feedback."\n');
1884                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
1885                     end
1886                 end
1887
1888                 if EditFlag == 6
1889                     List = [
1890                         1 1
1891                         2 1
1892                         3 1
1893                         4 1
1894                         4 2
1895                         5 1
1896                         6 1
1897                         6 2
1898                         7 1
1899                         8 1
1900                         9 1
1901                         10 1
1902                         11 1
1903                         11 2
1904                         12 1];
1905                     CheckList = zeros(size(List,1),1);
1906                     if ~isempty(LocalBumplist)
1907                         for i = 1:size(List,1)
1908                             k = find(List(i,1)==LocalBumplist(:,1));
1909                             l = find(List(i,2)==LocalBumplist(k,2));
1910
1911                             if isempty(k) || isempty(l)
1912                                 % Item not in list
1913                             else
1914                                 CheckList(i) = 1;
1915                             end
1916                         end
1917                     end
1918                     LocalBumplist = editlist2(List, 'Sector', CheckList);
1919                 end
1920
1921                 if EditFlag == 7
1922                     RFCorrFlag = questdlg(sprintf('Set RF Frequency during Orbit Correction?'),'RF Frequency','Yes','No', 'No');
1923                     if strcmp(RFCorrFlag,'No')
1924                         disp(['   RF Frequency will not be included in global orbit correction.']);
1925                     elseif strcmp(RFCorrFlag,'Yes')
1926                         disp(['   RF Frequency will be included in global orbit correction.']);
1927                     end
1928
1929                 end
1930             end
1931             close(h_fig1);
1932         end
1933
1934         %  ORBIT CORRECTION STRUCTURE (OCS)
1935         %    OCS.BPM (data structure)
1936         %    OCS.CM  (data structure)
1937         %    OCS.GoalOrbit
1938         %    OCS.NIter
1939         %    OCS.SVDIndex
1940         %    OCS.IncrementalFlag = 'Yes'/'No'
1941         %    OCS.BPMWeight
1942         %    OCS.Flags = { 'FitRF' , etc. }
1943         OCSx.BPM = getx(BPMlist1, 'struct');
1944         OCSx.CM = getsp('HCM', HCMlist1, 'struct');
1945         OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
1946         OCSx.NIter = 1;
1947         OCSx.SVDIndex = Xivec;
1948         OCSx.IncrementalFlag = 'No';
1949         OCSx.FitRF = 1;
1950         OCSy.BPM = gety(BPMlist1, 'struct');
1951         OCSy.CM = getsp('VCM', VCMlist1, 'struct');
1952         OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
1953         OCSy.NIter = 1;
1954         OCSy.SVDIndex = Yivec;
1955         OCSy.IncrementalFlag = 'No';
1956         OCSy.FitRF = 0;
1957
1958         % Save vectors
1959         FB.OCSx = OCSx;
1960         FB.OCSy = OCSy;
1961
1962         FB.BPMlist1 = BPMlist1;
1963         FB.HCMlist1 = HCMlist1;
1964         FB.VCMlist1 = VCMlist1;
1965         FB.Xivec = Xivec;
1966         FB.Yivec = Yivec;
1967         FB.Xgoal = OCSx.GoalOrbit;
1968         FB.Ygoal = OCSy.GoalOrbit;
1969         FB.RFCorrFlag = RFCorrFlag;
1970         FB.LocalBumplist = LocalBumplist;
1971         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata',FB);
1972
1973
1974     case 'Feedback'
1975
1976         FBloopIter = 1;
1977         if get(findobj(gcbf,'Tag','SRCTRLCheckboxFOFB'),'Value') == 1
1978             StartFOFBFlag = 1;
1979         else
1980             StartFOFBFlag = 0;
1981         end
1982
1983         FEEDBACK_STOP_FLAG = 0;
1984         HWarnNum=0;
1985         VWarnNum=0;
1986
1987         SR_GeV = getenergy;
1988         % Feedback loop setup
1989         PlotInfoFlag = 0;           % Plot micado stuff
1990         LoopDelay = 1.0;           % Period of feedback loop [seconds], make sure the BPM averaging is correct
1991         VCM_LSB = .00366211;
1992         VCMCHICANE_LSB = .002441;   % 80 max?,  Note: not fully implemented
1993
1994         if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
1995             Xgain  = 0.2;
1996             Ygain  = 0.1;
1997         else
1998             Xgain  = 0.8; % raised 0.5->0.8 at 17:20, 3-2-05 to more quickly correct EPU4 fast switching orbit distortions
1999             Ygain  = 0.8;
2000         end
2001
2002         % Load lattice set for tune feed forward
2003         ConfigSetpoint = getproductionlattice;
2004         %load([getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile')]);
2005         QFsp = ConfigSetpoint.QF.Setpoint.Data;
2006         QDsp = ConfigSetpoint.QD.Setpoint.Data;
2007         TuneW16Min = gap2tune(5, 13.23, 1.8909);
2008         % Tune response matrix
2009         SR_TUNE_MATRIX = gettuneresp({'QF','QD'}, {[],[]}, getenergy('Production'));    % Approx. [0.1944 -0.0286;-0.1182 0.1526];
2010         %SR_TUNE_MATRIX = [0.1641 -0.0245
2011         %                 -0.1149 0.1477];
2012
2013         SQSFsp = amp2k('SQSF','Setpoint',ConfigSetpoint.SQSF.Setpoint.Data);
2014         SQSDsp = amp2k('SQSD','Setpoint',ConfigSetpoint.SQSD.Setpoint.Data);
2015
2016 %         % tune FF for EPUs (data exist for 4 1 parallel, 11 1 parallel and antiparallel
2017 %         load '/home/als/physdata/matlab/srdata/gaptrack/EPU4-1_tunecomp/after_shimming/nux_map_withgaps.mat'
2018 %         dnux_epu_41_m0 = tunexmap(2:end,2:end)-tunexmap(2,12);
2019 %         [gap_epu_41,shift_epu_41]=meshgrid(tunexmap(2:end,1),tunexmap(1,2:end));
2020 %         load '/home/als/physdata/matlab/srdata/gaptrack/EPU4-1_tunecomp/after_shimming/nuy_map_withgaps.mat'
2021 %         dnuy_epu_41_m0 = tuneymap(2:end,2:end)-tuneymap(2,12);
2022 %
2023 %         load '/home/als/physdata/matlab/srdata/gaptrack/archive/epu11d1m0e19_2007-01-28.mat' tune_x tune_y Gaps GapsLongitudinal
2024 %         dnux_epu_111_m0 = tune_x-tune_x(1,11);
2025 %         [gap_epu_111,shift_epu_111]=meshgrid(Gaps,GapsLongitudinal);
2026 %         dnuy_epu_111_m0 = tune_y-tune_y(1,11);
2027 %         load '/home/als/physdata/matlab/srdata/gaptrack/archive/epu11d1m1e19_2007-01-28.mat' tune_x tune_y Gaps GapsLongitudinal
2028 %         dnux_epu_111_m1 = tune_x-tune_x(1,11);
2029 %         dnuy_epu_111_m1 = tune_y-tune_y(1,11);
2030
2031         % tune FF for EPUs (data exist for 4 1 parallel, 11 1 parallel and antiparallel
2032         load '/home/als/physdata/matlab/srdata/epu/tuneshift_2d_tables/epu_tunetables_2d_20070723.mat'
2033         dnux41p = nux41p-nux41p(1,11);
2034         dnuy41p = nuy41p-nuy41p(1,11);
2035         dnux41a = nux41a-nux41a(1,11);
2036         dnuy41a = nuy41a-nuy41a(1,11);
2037         dnux111p = nux111p-nux111p(1,11);
2038         dnuy111p = nuy111p-nuy111p(1,11);
2039         dnux111a = nux111a-nux111a(1,11);
2040         dnuy111a = nuy111a-nuy111a(1,11);
2041         dnux112p = nux112p-nux112p(1,11);
2042         dnuy112p = nuy112p-nuy112p(1,11);
2043         dnux112a = nux112a-nux112a(1,11);
2044         dnuy112a = nuy112a-nuy112a(1,11);
2045
2046         % ID tune compensation does not work in the injection lattice, so ...
2047         if abs(SR_GEV - bend2gev)>  0.05     % Don't use this routine for the injection lattice
2048             fprintf('   This routine should only be used for the production energy: Orbit feedback aborted\n');
2049             return
2050         end
2051
2052         set(0,'showhiddenhandles','on');
2053
2054         try
2055             fprintf('\n');
2056             fprintf('   *******************************\n');
2057             fprintf('   **  Starting Orbit Feedback  **\n');
2058             fprintf('   *******************************\n');
2059             a = clock;
2060             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2061             fprintf('   Note: the Matlab command window will be used to display status information.\n');
2062             fprintf('         It cannot be used to enter commands during slow orbit feedback.\n');
2063
2064
2065                 % save current BPM timeconstant - will reset to this when feedback stops
2066                 BPMtimeconstantOFB = getbpmtimeconstant;
2067                 fprintf('   Current Bergoz BPM time constant is %.1fs\n', BPMtimeconstantOFB);
2068
2069             % >= 2 Hz update rate on IDBPMs
2070             disp('   Bergoz BPM time constant set to 0.2s.')
2071             setbpmtimeconstant(0.2)
2072             pause(1.1);
2073
2074             % Check whether bumps and kickers are on and warn to turn off before starting feedback if necessary
2075             try
2076                 if (getsp('SR01S___BUMP1__BC21')==1 && getsp('SR01S___BUMP1P_BC22')==1) || (getsp('SR01S___SEK____BC21')==1 && getsp('SR01S___SEK_P__BC23')==1) || (getsp('SR01S___SEN____BC20')==1 && getsp('SR01S___SEN_P__BC22')==1)
2077                     soundtada;
2078                     fprintf('   \n');
2079                     fprintf('   *********************************************************************************\n');
2080                     fprintf('   ** One or more of the pulsed SR injection magnets is still on!  Turn them off! **\n');
2081                     fprintf('   *********************************************************************************\n');
2082                     fprintf('   \n');
2083                 end
2084             catch
2085                 disp('**Problem checking the state of the bumps and kickers - please check that they are not pulsing.');
2086             end
2087
2088             % Get vectors
2089
2090             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
2091
2092             BPMlist1 = FB.OCSx.BPM.DeviceList;
2093             % FOFB_BPMlist =
2094             HCMlist1 = FB.HCMlist1;
2095             VCMlist1 = FB.VCMlist1;
2096             Xivec = FB.Xivec;
2097             Yivec = FB.Yivec;
2098             Xgoal = FB.OCSx.GoalOrbit;
2099             Ygoal = FB.OCSy.GoalOrbit;
2100             FFTypeFlag = FB.FFTypeFlag;   %local or global tune correction
2101
2102             iNotHCMChicane = find(HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
2103             iHCMChicane = find(HCMlist1(:,2) == 10);
2104             iNotVCMChicane = find(VCMlist1(:,2) < 10);
2105             iVCMChicane = find(VCMlist1(:,2) == 10);
2106
2107             % Sensitivity matrix for setting fast feedback setpoints
2108             Sx1 = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
2109             Sy1 = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
2110
2111         catch
2112             fprintf('\n  %s \n',lasterr);
2113
2114             % Reset Bergoz BPM time constant to whatever it was before feedback started
2115             fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
2116             setbpmtimeconstant(BPMtimeconstantOFB);
2117
2118
2119             a = clock;
2120             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2121             fprintf('   *************************************************************\n');
2122             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
2123             fprintf('   *************************************************************\n\n');
2124             set(0,'showhiddenhandles','off');
2125             pause(0);
2126
2127             return
2128         end
2129
2130         StartFlag = questdlg(strvcat('','Is it OK to start orbit feedback?'),'Orbit Feedback','Yes','No','No');
2131         if strcmp(StartFlag,'No')
2132             % Reset Bergoz BPM time constant to whatever it was before feedback started
2133             fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
2134             setbpmtimeconstant(BPMtimeconstantOFB);
2135
2136             a = clock;
2137             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2138             fprintf('   ***************************\n');
2139             fprintf('   **  Orbit Feedback Exit  **\n');
2140             fprintf('   ***************************\n\n');
2141             pause(0);
2142             return
2143         end
2144
2145         SR_STATE_OLD = scaget('SR_STATE');
2146         setpv('SR_STATE', 5);
2147         set(0,'showhiddenhandles','on');
2148         [StateNumber, StateString] = getsrstate;
2149         if StateNumber >= 0
2150             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2151         else
2152             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2153         end
2154         fprintf('   Using %d E-vectors horizontally.\n', length(Xivec));
2155         fprintf('   Using %d E-vectors vertically.\n',   length(Yivec));
2156         fprintf('   Starting slow orbit correction every %.1f seconds.\n', LoopDelay);
2157         %  fprintf('   Resetting SR11 chicane motors every 20 seconds to fix drift problem.\n');
2158
2159         IDSector = getlist('ID');
2160         EPUlist = find((IDSector(:,1)==4) | (IDSector(:,1)==11));
2161         oldgap=210*ones(size(IDSector,1),1);
2162         oldShift=zeros(size(oldgap));
2163
2164         try
2165
2166             % Get and display data
2167             x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
2168             y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
2169             STDx = norm(x)/sqrt(length(x));
2170             STDy = norm(y)/sqrt(length(y));
2171             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
2172             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
2173
2174             % write goldenorbit values to Fast Orbit Feedback
2175             try
2176                 write_goldenorbit_ffb;
2177             catch
2178                 disp('write_goldenorbit_ffb did not work!');
2179             end
2180             setpv('SR01____FFBON__BC00',2);
2181             %pause(0);
2182
2183             %display state of FOFB system
2184             FOFBStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2185                 getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2186                 getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2187                 getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2188             FOFBStatusStr = ['    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    '];
2189             for loop = 1:size(FOFBStatus,2)
2190                 if FOFBStatus(loop)==0
2191                     FOFBStatusStr(loop,:) = 'OFF ';
2192                 elseif FOFBStatus(loop)==1
2193                     FOFBStatusStr(loop,:) = 'ON  ';
2194                 elseif FOFBStatus(loop)==2
2195                     FOFBStatusStr(loop,:) = 'OPEN';
2196                 else
2197                     FOFBStatusStr(loop,:) = 'BAD ';
2198                 end
2199             end
2200             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 %s',FOFBStatusStr(1,:)),'ForegroundColor',[0 0 0]);
2201             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 %s',FOFBStatusStr(2,:)),'ForegroundColor',[0 0 0]);
2202             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 %s',FOFBStatusStr(3,:)),'ForegroundColor',[0 0 0]);
2203             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 %s',FOFBStatusStr(4,:)),'ForegroundColor',[0 0 0]);
2204             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 %s',FOFBStatusStr(5,:)),'ForegroundColor',[0 0 0]);
2205             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 %s',FOFBStatusStr(6,:)),'ForegroundColor',[0 0 0]);
2206             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 %s',FOFBStatusStr(7,:)),'ForegroundColor',[0 0 0]);
2207             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 %s',FOFBStatusStr(8,:)),'ForegroundColor',[0 0 0]);
2208             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 %s',FOFBStatusStr(9,:)),'ForegroundColor',[0 0 0]);
2209             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 %s',FOFBStatusStr(10,:)),'ForegroundColor',[0 0 0]);
2210             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 %s',FOFBStatusStr(11,:)),'ForegroundColor',[0 0 0]);
2211             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 %s',FOFBStatusStr(12,:)),'ForegroundColor',[0 0 0]);
2212
2213         catch
2214
2215             fprintf('\n  %s \n',lasterr);
2216
2217             % Reset Bergoz BPM time constant to whatever it was before feedback started
2218             fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
2219             setbpmtimeconstant(BPMtimeconstantOFB);
2220
2221
2222             a = clock;
2223             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2224             fprintf('   *************************************************************\n');
2225             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
2226             fprintf('   *************************************************************\n\n');
2227
2228             setpv('SR_STATE',SR_STATE_OLD);
2229             [StateNumber, StateString] = getsrstate;
2230             if StateNumber >= 0
2231                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2232             else
2233                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2234             end
2235             set(0,'showhiddenhandles','off');
2236             pause(0);
2237
2238             return
2239
2240         end
2241
2242
2243         % Disable buttons
2244         set(0,'showhiddenhandles','on');
2245         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','off');
2246         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','on');
2247         set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','off');
2248         set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','off');
2249         set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','off');
2250         set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','off');
2251         set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','off');
2252         set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','off');
2253         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','off');
2254         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','off');
2255         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','off');
2256         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','off');
2257         set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','off');
2258         pause(0);
2259
2260
2261         % Initialize feedback loop
2262         StartTime = gettime;
2263         StartErrorTime = gettime;
2264         Xold = getx(FB.OCSx.BPM.DeviceList);
2265         Yold = gety(FB.OCSy.BPM.DeviceList);
2266         HQMOFM_stalenum = 0;
2267         pause(LoopDelay);
2268
2269         N_HCM = size(HCMlist1,1);
2270         N_VCM = size(VCMlist1,1);
2271
2272         N_RFMO = 1;
2273
2274         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2275             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'SetRF','Nodisplay','Nosetsp');
2276         else
2277             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
2278         end
2279         [FB.OCSx, Smatx, Sx, Ux, Vx] = orbitcorrectionmethods(FB.OCSx);
2280
2281         [FB.OCSy, junk, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
2282         [FB.OCSy, Smaty, Sy, Uy, Vy] = orbitcorrectionmethods(FB.OCSy);
2283
2284
2285         %%%%%%%%%%%%%%%%%%%%%%%
2286         % Start feedback loop %
2287         %%%%%%%%%%%%%%%%%%%%%%%
2288
2289         % chicaneloop=1;  % loop variable for resetting drifting chicanes (see a few lines below)
2290         % fftest=figure;
2291
2292         setpv('SR01____FFBON__BC00',2); % put FOFB in open loop so beamnoise gets recorded even if FOFB is not enabled
2293
2294         while 1
2295             try
2296                 t00 = gettime;
2297
2298                 %          if chicaneloop==20 % reset SR11 motor chicane setpoints every 20s due to drifting positions
2299                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(6),[11 1],0);
2300                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(7),[11 2],0);
2301                 %             chicaneloop = 1;
2302                 %          else
2303                 %             chicaneloop = chicaneloop + 1;
2304                 %          end
2305
2306                 % Check if GUI has been closed
2307                 if isempty(gcbf)
2308                     FEEDBACK_STOP_FLAG = 1;
2309                     lasterr('SRCONTROL GUI DISAPPEARED!');
2310                     error('SRCONTROL GUI DISAPPEARED!');
2311                 end
2312
2313                 %%%%%%%%%%%%%%%%%%%%%%%
2314                 % Fast orbit feedback %
2315                 %%%%%%%%%%%%%%%%%%%%%%%
2316                 if StartFOFBFlag == 1 && FBloopIter > 3
2317                     setpv('SR01____FFBON__BC00',2);
2318                     pause(0.5);
2319                     setpv('SR01____FFBON__BC00',1);
2320                     StartFOFBFlag = 0;
2321                     pause(1);
2322                     FOFBOnStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2323                         getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2324                         getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2325                         getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2326                     if any(FOFBOnStatus==0) || any(FOFBOnStatus==2)
2327                         setpv('SR01____FFBON__BC00',2); % open FOFB loop
2328                         disp('************************************************************************************************************');
2329                         disp('** Problem turning on Fast Orbit Feedback system...                                                       **');
2330                         disp('** Check status of ffbsecXX crates - but remember that a crate reboot will turn off Quads in that sector! **');
2331                         disp('** Suggest disabling the "Fast Orbit Correction" checkbox and starting Orbit Feedback again.              **');
2332                         disp('************************************************************************************************************');
2333                     else
2334                         fprintf('   Starting Fast Orbit Feedback at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
2335                     end
2336                 end
2337
2338
2339                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2340                 % Horizontal plane "feedback" %
2341                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2342
2343                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxSOFB'),'Value') == 1
2344
2345                     % Get orbit and check that the BPMs are different from the last update
2346                     Xnew = getx(FB.OCSx.BPM.DeviceList);
2347
2348                     % Don't feedback if the current is too small
2349                     if getdcct < 5
2350                         FEEDBACK_STOP_FLAG = 1;
2351                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2352                         break;
2353                     end
2354
2355                     x = Xgoal - Xnew;
2356                     STDx = norm(x)/sqrt(length(x));
2357
2358                     if any(Xold == Xnew)
2359                         a = clock;
2360                         N_Stale_Data_Points = find((Xold==Xnew)==1);
2361                         for loop = N_Stale_Data_Points'
2362                             fprintf('   Stale data: BPMx(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSx.BPM.DeviceList(loop,1), FB.OCSx.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2363                         end
2364                     else
2365                         % Compute horizontal correction
2366                         %%%OCSx0 = FB.OCSx;
2367                         FB.OCSx.BPM.Data = Xnew;
2368                         FB.OCSx = orbitcorrectionmethods(FB.OCSx, Smatx, Sx, Ux, Vx);
2369
2370                         %%%[FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
2371
2372                         % reduced feedback gain (implemented by Greg Portmann, December 2000)
2373                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2374                         % increased back to 0.8 C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2375                         % increased to 1.0, C. Steier, 2002-05-04, trim DACs
2376                                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2377                                 % should probably actively allocate X's size to prevent possible memory leak %
2378                                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2379                         X = [Xgain .* FB.OCSx.CM.Delta; 0.3*FB.OCSx.DeltaRF/4.988e-3];
2380
2381                         %%%X = Xgain .* (FB.OCSx.CM.Data - OCSx0.CM.Data);
2382
2383                         % check corrector trim values + next step values, warn or stop FB as necessary
2384                         HCMtrimSP=getpv('HCM','Trim',HCMlist1);
2385                         HCMtrimSP_next = HCMtrimSP + X(1:N_HCM);
2386                         if max(abs(HCMtrimSP_next)) > 4
2387                             HCMtrimnum=find(abs(HCMtrimSP_next) > 4);
2388
2389                             % print message to screen
2390                             fprintf('\n');
2391                             fprintf('***One or more of the horizontal correctors is at its maximum!! Stopping orbit feedback. \n');
2392                             fprintf('   %s\n',datestr(now));
2393                             for loop = HCMtrimnum'
2394                                 fprintf('***%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2395                             end
2396
2397                             % send alphapage to operator pager
2398                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2399                             FEEDBACK_STOP_FLAG = 1;
2400
2401                             setpv('SR_STATE', -5);
2402                             [StateNumber, StateString] = getsrstate;
2403                             if StateNumber >= 0
2404                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2405                             else
2406                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2407                             end
2408                         end
2409
2410                         % check chicane trim coil values + next step values, warn or stop FB as necessary
2411                         HCMCHICANEtrimSP=getpv('HCM','Setpoint',HCMlist1(iHCMChicane,:));
2412                         HCMCHICANEtrimSP_next = HCMCHICANEtrimSP + X(iHCMChicane);
2413                         if max(abs(HCMCHICANEtrimSP_next)) > 19.9
2414                             HCMCHICANEtrimnum=find(abs(HCMCHICANEtrimSP_next) > 19.9);
2415
2416                             % print message to screen
2417                             fprintf('\n');
2418                             fprintf('***One or more of the horizontal chicane trim coil correctors is at its maximum!! Stopping orbit feedback. \n');
2419                             fprintf('   %s\n',datestr(now));
2420                             for loop = HCMCHICANEtrimnum'
2421                                 fprintf('***%s is one of the problem correctors.\n',getname('HCM','Setpoint',HCMlist1(iHCMChicane(loop,:),:)));
2422                             end
2423                             fprintf('***Maybe try resetting the setpoints of the motor chicanes in case they are drifting...\n');
2424
2425                             % send alphapage to operator pager
2426                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2427                             FEEDBACK_STOP_FLAG = 1;
2428
2429                             setpv('SR_STATE', -5);
2430                             [StateNumber, StateString] = getsrstate;
2431                             if StateNumber >= 0
2432                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2433                             else
2434                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2435                             end
2436                         end
2437
2438                         if FEEDBACK_STOP_FLAG == 1
2439                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2440                             if getpv('SR01____FFBON__BC00')==1
2441                                 disp('   Stopping Fast Orbit Feedback.');
2442                             end
2443                             setpv('SR01____FFBON__BC00',0);
2444                             pause(0.5);
2445                             setpv('SR01____FFBON__BC00',2);
2446                             break;
2447                         end
2448
2449                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2450                         pause(0);
2451
2452                         if max(abs(HCMtrimSP_next) > 3)
2453                             HCMtrimnum=find(abs(HCMtrimSP_next) > 3);
2454                             HWarnNum=HWarnNum+1;
2455                             if (HWarnNum==1 || rem(HWarnNum,120)==0)
2456
2457                                 % print message to screen every two minutes
2458                                 fprintf('\n');
2459                                 fprintf('***One or more of the horizontal corrector trims is above 3A or below -3A! \n');
2460                                 fprintf('   %s\n',datestr(now));
2461                                 for loop = HCMtrimnum'
2462                                     fprintf('***%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2463                                 end
2464                                 fprintf('***The orbit feedback is still working but this problem should be investigated. \n');
2465
2466                                 %send alphapage to operator pager the first time then at 10 minutes
2467                                 if (HWarnNum==1 || HWarnNum==600)
2468                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageHCM.txt
2469                                 end
2470                             end
2471                         elseif max(abs(HCMCHICANEtrimSP_next) > 15)
2472                             HCMCHICANEtrimnum=find(abs(HCMCHICANEtrimSP_next) > 15);
2473                             HWarnNum=HWarnNum+1;
2474                             if (HWarnNum==1 || rem(HWarnNum,120)==0)
2475
2476                                 % print message to screen every two minutes
2477                                 fprintf('\n');
2478                                 fprintf('***One or more of the horizontal chicane corrector trim coils is above 15A or below -15A! \n');
2479                                 fprintf('   %s\n',datestr(now));
2480                                 for loop = HCMCHICANEtrimnum'
2481                                     fprintf('***%s is one of the problem correctors.\n',getname('HCM','Setpoint',HCMlist1(iHCMChicane(loop,:),:)));
2482                                 end
2483                                 fprintf('***The orbit feedback is still working but this problem should be investigated. \n');
2484
2485                                 %reset motor chicanes in case they are drifting
2486                                 try
2487                                         fprintf('   Resetting the setpoints of the motor chicanes in case they are drifting...\n');
2488                                         setpv('HCMCHICANEM','Setpoint',ConfigSetpoint.HCMCHICANEM.Setpoint.Data,[],0);
2489                                 catch
2490                                 end
2491
2492                                 %send alphapage to operator pager the first time then at 10 minutes
2493                                 if (HWarnNum==1 || HWarnNum==600)
2494                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageHCMCHICANE.txt
2495                                 end
2496                             end
2497                         else
2498                             HWarnNum=0;
2499                         end
2500
2501                         % Don't feedback if the current is too small
2502                         if getdcct < 5
2503                             FEEDBACK_STOP_FLAG = 1;
2504                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2505                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2506                             break;
2507                         end
2508
2509                         if N_HCM > 0
2510                             steppv('HCM','Trim', X(iNotHCMChicane), HCMlist1(iNotHCMChicane,:), 0);
2511                             steppv('HCM','Setpoint', X(iHCMChicane), HCMlist1(iHCMChicane,:), 0);
2512                         end
2513
2514                         % write fast orbit feedback setpoints
2515                         if 1
2516                             %write_goldenorbit_ffb_2planes(1, Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM)+Sx3*X(length(X))/20, BPMlist1);
2517                             % should be corrected to include result of next frequency step ...
2518                             write_goldenorbit_ffb_2planes(1,Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM),BPMlist1);
2519                         end
2520
2521                         %fprintf('Horizontal Done: %f \n',gettime-t00);
2522
2523                         % RF feedback
2524                         HQMOFMsp_last = getpv('EG______HQMOFM_AC01');
2525
2526                         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2527                             if N_RFMO > 0
2528                                 if abs(X(end)) < .01
2529                                     % if abs(FB.OCSx.DeltaRF/3) < .01
2530                                     steppv('EG______HQMOFM_AC01', X(end));
2531                                 else
2532                                     steppv('EG______HQMOFM_AC01', 0.01*sign(X(end)));
2533                                 end
2534                             end
2535
2536                             HQMOFMsp_now = getpv('EG______HQMOFM_AC01');
2537
2538                             % Check for stale RF feedback
2539                             if HQMOFMsp_last == HQMOFMsp_now
2540                                 HQMOFM_stalenum = HQMOFM_stalenum + 1;
2541                                 if HQMOFM_stalenum == 30 % warn and message to pager if stale for 30 secs
2542                                     fprintf('\n');
2543                                     fprintf('***The RF is not responding to orbit feedback changes! \n');
2544                                     fprintf('   %s\n',datestr(now));
2545                                     fprintf('***The orbit feedback is still working but this problem should be investigated. \n');
2546                                     fprintf('***ILC 73 controls the EG______HQMOFM_AC01 channel, which sets the RF frequency. \n');
2547                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstaleRFmessage.txt
2548                                 end
2549                                 if rem(HQMOFM_stalenum,120)==0 % message to screen every 2 minutes
2550                                     fprintf('\n');
2551                                     fprintf('***The RF is not responding to orbit feedback changes! (%s)\n',datestr(now));
2552                                 end
2553                             else
2554                                 HQMOFM_stalenum = 0;
2555                             end
2556
2557                         end
2558
2559                         %fprintf('RF Done: %f \n',gettime-t00);
2560
2561                         Xold = Xnew;
2562                     end % End horizontal correction
2563
2564
2565                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2566                     % Vertical plane "feedback" %
2567                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2568
2569                     % Get orbit and check that the BPMs are different from the last update
2570                     Ynew = gety(FB.OCSy.BPM.DeviceList);
2571
2572                     % Don't feedback if the current is too small
2573                     if getdcct < 5
2574                         FEEDBACK_STOP_FLAG = 1;
2575                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2576                         break;
2577                     end
2578
2579                     y = Ygoal - Ynew;
2580                     STDy = norm(y)/sqrt(length(y));
2581
2582                     if any(Yold == Ynew)
2583                         a = clock;
2584                         N_Stale_Data_Points = find((Yold==Ynew)==1);
2585                         for loop = N_Stale_Data_Points'
2586                             fprintf('   Stale data: BPMy(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSy.BPM.DeviceList(loop,1), FB.OCSy.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2587                         end
2588
2589                     else
2590
2591                         % Compute vertical correction
2592                         %%%OCSy0 = FB.OCSy;
2593                         FB.OCSy.BPM.Data = Ynew;
2594                         FB.OCSy = orbitcorrectionmethods(FB.OCSy, Smaty, Sy, Uy, Vy);
2595
2596                         %%%[FB.OCSy, RF, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
2597
2598                         % reduced feedback gain, C. Steier, 2001-03-25
2599                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2600                         % increased back to 0.8, C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2601                         % set to unity gain, C. Steier, 2002-05-04, trim DACs
2602                         Y = Ygain .* FB.OCSy.CM.Delta;
2603                         %%%Y = Ygain .* (FB.OCSy.CM.Data - OCSy0.CM.Data);
2604
2605                         % Just SVD correction
2606                         % warning('Not using "micado" correction in the vertical plane.');
2607
2608                         % check for trim values+next step values, warn or stop FB as necessary
2609                         VCMtrimSP = getpv('VCM','Trim',VCMlist1);
2610                         VCMtrimSP_next = VCMtrimSP + Y(1:N_VCM);
2611                         if max(abs(VCMtrimSP_next)) > 12
2612                             VCMtrimnum=find(abs(VCMtrimSP_next) > 12);
2613
2614                             % print message to screen
2615                             fprintf('\n');
2616                             fprintf('***One or more of the vertical correctors is at its maximum!! Stopping orbit feedback. \n');
2617                             fprintf('   %s\n',datestr(now));
2618                             for loop = VCMtrimnum'
2619                                 fprintf('***%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2620                             end
2621
2622                             % send alphapage to operator pager
2623                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2624                             FEEDBACK_STOP_FLAG = 1;
2625
2626                             setpv('SR_STATE', -5);
2627                             [StateNumber, StateString] = getsrstate;
2628                             if StateNumber >= 0
2629                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2630                             else
2631                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2632                             end
2633                         end
2634
2635                         % check chicane trim coil values + next step values, warn or stop FB as necessary
2636                         VCMCHICANEtrimSP=getpv('VCM','Setpoint',VCMlist1(iVCMChicane,:));
2637                         VCMCHICANEtrimSP_next = VCMCHICANEtrimSP + Y(iVCMChicane);
2638                         if max(abs(VCMCHICANEtrimSP_next)) > 19.9
2639                             VCMCHICANEtrimnum=find(abs(VCMCHICANEtrimSP_next) > 19.9);
2640
2641                             % print message to screen
2642                             fprintf('\n');
2643                             fprintf('***One or more of the vertical chicane trim coil correctors is at its maximum!! Stopping orbit feedback. \n');
2644                             fprintf('   %s\n',datestr(now));
2645                             for loop = VCMCHICANEtrimnum'
2646                                 fprintf('***%s is one of the problem correctors.\n',getname('VCM','Setpoint',VCMlist1(iVCMChicane(loop,:),:)));
2647                             end
2648                             fprintf('***Maybe try resetting the setpoints of the motor chicanes in case they are drifting...\n');
2649
2650                             % send alphapage to operator pager
2651                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2652                             FEEDBACK_STOP_FLAG = 1;
2653
2654                             setpv('SR_STATE', -5);
2655                             [StateNumber, StateString] = getsrstate;
2656                             if StateNumber >= 0
2657                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2658                             else
2659                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2660                             end
2661                         end
2662
2663                         if FEEDBACK_STOP_FLAG == 1
2664                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2665                             if getpv('SR01____FFBON__BC00')==1
2666                                 disp('   Stopping Fast Orbit Feedback.');
2667                             end
2668                             setpv('SR01____FFBON__BC00',0);
2669                             pause(0.5);
2670                             setpv('SR01____FFBON__BC00',2);
2671                             break;
2672                         end
2673
2674                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2675                         % pause(0);
2676
2677                         if max(abs(VCMtrimSP_next) > 8) % changed from 6A ~12/1/07 since orbit FB is going past 6A
2678                             VCMtrimnum=find(abs(VCMtrimSP_next) > 8);
2679                             VWarnNum=VWarnNum+1;
2680                             if (VWarnNum==1 || rem(VWarnNum,120)==0)
2681
2682                                 % print message to screen every two minutes
2683                                 fprintf('\n');
2684                                 fprintf('***One or more of the vertical corrector trims is above 8A or below -8A! \n');
2685                                 fprintf('   %s\n',datestr(now));
2686                                 for loop = VCMtrimnum'
2687                                     fprintf('***%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2688                                 end
2689                                 fprintf('***The orbit feedback is still working but this problem should be investigated. \n');
2690
2691                                 %send alphapage to operator pager the first time then at 10 minutes
2692                                 if (VWarnNum==1 || VWarnNum==600)
2693                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageVCM.txt
2694                                 end
2695                             end
2696                         elseif max(abs(VCMCHICANEtrimSP_next) > 15)
2697                             VCMCHICANEtrimnum=find(abs(VCMCHICANEtrimSP_next) > 15);
2698                             VWarnNum=VWarnNum+1;
2699                             if (VWarnNum==1 || rem(VWarnNum,120)==0)
2700
2701                                 % print message to screen every two minutes
2702                                 fprintf('\n');
2703                                 fprintf('***One or more of the vertical chicane corrector trim coils is above 15A or below -15A! \n');
2704                                 fprintf('   %s\n',datestr(now));
2705                                 for loop = VCMCHICANEtrimnum'
2706                                     fprintf('***%s is one of the problem correctors.\n',getname('VCM','Setpoint',VCMlist1(iVCMChicane(loop,:),:)));
2707                                 end
2708                                 fprintf('***The orbit feedback is still working but this problem should be investigated. \n');
2709
2710                                 %reset motor chicanes in case they are drifting
2711                                 try
2712                                         fprintf('  Resetting the setpoints of the motor chicanes in case they are drifting...\n');
2713                                         setpv('HCMCHICANEM','Setpoint',ConfigSetpoint.HCMCHICANEM.Setpoint.Data,[],0);
2714                                 catch
2715                                 end
2716
2717                                 %send alphapage to operator pager the first time then at 10 minutes
2718                                 if (VWarnNum==1 || VWarnNum==600)
2719                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageVCMCHICANE.txt
2720                                 end
2721                             end
2722                         else
2723                             VWarnNum=0;
2724                         end
2725
2726                         % Don't feedback if the current is too small
2727                         if getdcct < 5
2728                             FEEDBACK_STOP_FLAG = 1;
2729                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2730                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2731                             break;
2732                         end
2733
2734                         if N_VCM > 0
2735                             steppv('VCM','Trim', Y(iNotVCMChicane), VCMlist1(iNotVCMChicane,:), 0);
2736                             steppv('VCM','Setpoint', Y(iVCMChicane), VCMlist1(iVCMChicane,:), 0);
2737                         end
2738
2739                         % write fast orbit feedback setpoints
2740                         if 1
2741                             write_goldenorbit_ffb_2planes(2,Ynew(1:size(BPMlist1,1))+Sy1*Y(1:N_VCM),BPMlist1);
2742                         end
2743
2744                     end
2745
2746                     Yold = Ynew;
2747
2748                     %fprintf('Vertical Done: %f \n',gettime-t00);
2749                 end % End vertical correction
2750
2751
2752                 %%%%%%%%%%%%%%%%%%%%%
2753                 % Tune feed forward %
2754                 %%%%%%%%%%%%%%%%%%%%%
2755                 % We should do a Sector limit check
2756
2757                 tic;
2758                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxTune'),'Value') == 1
2759
2760                     if strcmp(SR_Mode, '1.9 GeV, High Tune') || strcmp(SR_Mode, '1.9 GeV, Inject at 1.23') || strcmp(SR_Mode, '1.9 GeV, Inject at 1.353') ||...
2761                         strcmp(SR_Mode, '1.9 GeV, Two-Bunch')  || strcmp(SR_Mode, '1.5 GeV, Inject at 1.353')  || strcmp(SR_Mode, '1.9 GeV, TopOff')
2762
2763                         addQFsp = zeros(24,1);
2764                         addQDsp = zeros(24,1);
2765
2766                         if strcmp(FFTypeFlag,'Local')
2767                             disp('  No local tune compensation available - global is the default now.');
2768                         elseif strcmp(FFTypeFlag,'Global')
2769
2770                             % The vectorized gets were put outside of loop for speed reasons
2771                             %
2772                             % should also set up QFfac, Quadelem, Quadlist structures outside loop
2773                             actualgap = getid(IDSector);
2774                             [gapmin,gapmax] = gaplimit(IDSector);
2775                             corrind = find(actualgap<(gapmin-1));
2776                             actualgap(corrind)=gapmax(corrind);
2777                             Shift=zeros(size(actualgap));
2778                             Shift(EPUlist)=getpv('EPU');
2779
2780                             IDchangedList=find((abs(actualgap-oldgap)>0.005) | (abs(Shift-oldShift)>0.005));
2781
2782                             if ~isempty(IDchangedList)
2783
2784                                 oldgap=actualgap;
2785                                 oldShift=Shift;
2786
2787                                 % EPUs excite nux = .25 resonance in vertical linear polarization mode!
2788                                 % therefore with EPU tune feedforward
2789                                 % running, we want to move our nominal working point away (just below) the .25 resonance.
2790                                 %
2791                                 % The following tune correction moves nominal
2792                                 % nu_x from .25 to .245 - this should be enough for well set up lattices.
2793                                 %
2794                                 % 24 QF+ 24 QD
2795                                 DeltaAmps = inv(SR_TUNE_MATRIX) * [-0.005;0];    %  DelAmps =  [QF; QD];
2796                                 addQFsp = addQFsp + DeltaAmps(1,:);
2797                                 addQDsp = addQDsp + DeltaAmps(2,:);
2798
2799                                 for gapnum = 1:length(actualgap)
2800
2801                                     % Change in tune and [QF;QD] from maximum gap
2802
2803                                     if (IDSector(gapnum,1) == 4) || (IDSector(gapnum,1) == 11)
2804                                         if IDSector(gapnum,2) == 1
2805                                             modenamestr = sprintf('SR%02dU___ODS1M__DC00',IDSector(gapnum,1));
2806                                         else % if IDSector(gapnum,2) == 2
2807                                             modenamestr = sprintf('SR%02dU___ODS2M__DC00',IDSector(gapnum,1));
2808                                         end
2809                                         epumode = getpv(modenamestr);
2810                                         if (IDSector(gapnum,1) == 4) && (IDSector(gapnum,2) == 1)
2811                                             if (epumode == 0)
2812 %                                                 DeltaNuX = interp2(gap_epu_41,shift_epu_41,dnux_epu_41_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2813 %                                                 DeltaNuY = interp2(gap_epu_41,shift_epu_41,dnuy_epu_41_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2814                                                 DeltaNuX = interp2(gap41p',shift41p',dnux41p',actualgap(gapnum),Shift(gapnum),'linear',0);
2815                                                 DeltaNuY = interp2(gap41p',shift41p',dnuy41p',actualgap(gapnum),Shift(gapnum),'linear',0);
2816                                             elseif (epumode == 1)
2817 %                                                 DeltaNux = 0;
2818 %                                                 DeltaNuY = gap2tune(IDSector(gapnum, :), actualgap(gapnum), SR_GeV);
2819                                                 DeltaNuX = interp2(gap41a',shift41a',dnux41a',actualgap(gapnum),Shift(gapnum),'linear',0);
2820                                                 DeltaNuY = interp2(gap41a',shift41a',dnuy41a',actualgap(gapnum),Shift(gapnum),'linear',0);
2821                                             else
2822                                                 DeltaNux = 0;
2823                                                 DeltaNuY = gap2tune(IDSector(gapnum, :), actualgap(gapnum), SR_GeV);
2824                                             end
2825                                         elseif (IDSector(gapnum,1) == 11) && (IDSector(gapnum,2) == 1)
2826                                             if (epumode == 0)
2827 %                                                 DeltaNuX = interp2(gap_epu_111,shift_epu_111,dnux_epu_111_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2828 %                                                 DeltaNuY = interp2(gap_epu_111,shift_epu_111,dnuy_epu_111_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2829                                                 DeltaNuX = interp2(gap111p',shift111p',dnux111p',actualgap(gapnum),Shift(gapnum),'linear',0);
2830                                                 DeltaNuY = interp2(gap111p',shift111p',dnuy111p',actualgap(gapnum),Shift(gapnum),'linear',0);
2831                                             elseif (epumode == 1)
2832 %                                                 DeltaNuX = interp2(gap_epu_111,shift_epu_111,dnux_epu_111_m1',actualgap(gapnum),Shift(gapnum),'linear',0);
2833 %                                                 DeltaNuY = interp2(gap_epu_111,shift_epu_111,dnuy_epu_111_m1',actualgap(gapnum),Shift(gapnum),'linear',0);
2834                                                 DeltaNuX = interp2(gap111a',shift111a',dnux111a',actualgap(gapnum),Shift(gapnum),'linear',0);
2835                                                 DeltaNuY = interp2(gap111a',shift111a',dnuy111a',actualgap(gapnum),Shift(gapnum),'linear',0);
2836                                             else
2837                                                 DeltaNuX = 0;
2838                                                 DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);   % variation of vertical tune shift with phase is small for EPUs
2839                                             end
2840                                         elseif (IDSector(gapnum,1) == 11) && (IDSector(gapnum,2) == 2)
2841                                             if (epumode == 0)
2842 %                                                 DeltaNuX = interp2(gap_epu_111,shift_epu_111,dnux_epu_111_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2843 %                                                 DeltaNuY = interp2(gap_epu_111,shift_epu_111,dnuy_epu_111_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2844                                                 DeltaNuX = interp2(gap112p',shift112p',dnux112p',actualgap(gapnum),Shift(gapnum),'linear',0);
2845                                                 DeltaNuY = interp2(gap112p',shift112p',dnuy112p',actualgap(gapnum),Shift(gapnum),'linear',0);
2846                                             elseif (epumode == 1)
2847 %                                                 DeltaNuX = interp2(gap_epu_111,shift_epu_111,dnux_epu_111_m1',actualgap(gapnum),Shift(gapnum),'linear',0);
2848 %                                                 DeltaNuY = interp2(gap_epu_111,shift_epu_111,dnuy_epu_111_m1',actualgap(gapnum),Shift(gapnum),'linear',0);
2849                                                 DeltaNuX = interp2(gap112a',shift112a',dnux112a',actualgap(gapnum),Shift(gapnum),'linear',0);
2850                                                 DeltaNuY = interp2(gap112a',shift112a',dnuy112a',actualgap(gapnum),Shift(gapnum),'linear',0);
2851                                             else
2852                                                 DeltaNuX = 0;
2853                                                 DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);   % variation of vertical tune shift with phase is small for EPUs
2854                                             end
2855                                         else
2856                                             DeltaNuX = 0;
2857                                             DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);
2858                                         end
2859
2860                                     else
2861                                         DeltaNuX = 0;
2862                                         DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);
2863                                     end
2864
2865                                     DelQF = zeros(length(QFsp),1);
2866                                     DelQD = zeros(length(QFsp),1);
2867
2868                                     fraccorr = 0.8*DeltaNuY ./ TuneW16Min;
2869
2870                                     % Find which quads to change (local beta beating correction
2871                                     % (horizontal for EPU, vertical otherwise)
2872                                     QuadList = [IDSector(gapnum,1)-1 2; IDSector(gapnum,1) 1];
2873                                     QuadElem = dev2elem('QF',QuadList); % in reality use QF and QD ...
2874
2875                                     % global vertical tune correction
2876                                     % 24 QF+ 24 QD
2877                                     DeltaAmps = inv(SR_TUNE_MATRIX) * [(fraccorr*6.23e-4); fraccorr*(-0.05301)];    %  DelAmps =  [QF; QD];
2878                                     DelQF = DelQF + DeltaAmps(1,:);
2879                                     DelQD = DelQD + DeltaAmps(2,:);
2880
2881                                     % local horizontal tune correction (is also nearly a beta beating correction) only nonzero for EPUs!
2882                                     % 2 QF + 2 QD
2883                                     DeltaAmpsLocal = 12*inv(SR_TUNE_MATRIX) * [-DeltaNuX;0];                       %  DelAmps =  [QF; QD];
2884                                     DelQF(QuadElem) = DelQF(QuadElem)+DeltaAmpsLocal(1,1);
2885                                     DelQD(QuadElem) = DelQD(QuadElem)+DeltaAmpsLocal(2,1);
2886
2887                                     % local vertical beta beating correction (should be used together with above global tune correction)
2888                                     % set to zero for EPUs, since their vertical tune shift is small
2889                                     % 2 QF + 2QD
2890                                     if (IDSector(gapnum,1)==6) || (IDSector(gapnum,1)==7) || (IDSector(gapnum,1)==10) || (IDSector(gapnum,1)==11)
2891                                         QFfac = ([2.243127/2.237111; 2.243127/2.237111]-1) * fraccorr;
2892                                         QDfac = ([2.556392/2.511045; 2.556392/2.511045]-1) * fraccorr;
2893                                     elseif (IDSector(gapnum,1)==5) || (IDSector(gapnum,1)==9)
2894                                         QFfac = ([2.225965/2.219784; 2.243096/2.237111]-1) * fraccorr;
2895                                         QDfac = ([2.528950/2.483259; 2.556345/2.511045]-1) * fraccorr;
2896                                     elseif (IDSector(gapnum,1)==4) || (IDSector(gapnum,1)==8) || (IDSector(gapnum,1)==12)
2897                                         QFfac = ([2.243096/2.237111; 2.225965/2.219784]-1) * fraccorr;
2898                                         QDfac = ([2.556345/2.511045; 2.528950/2.483259]-1) * fraccorr;
2899                                     else
2900                                         QFfac = zeros(2,1);
2901                                         QDfac = zeros(2,1);
2902                                     end
2903
2904                                     DelQF(QuadElem,:) = DelQF(QuadElem,:) + QFfac.*QFsp(QuadElem,:);
2905                                     DelQD(QuadElem,:) = DelQD(QuadElem,:) + QDfac.*QDsp(QuadElem,:);
2906
2907                                     % add all tune and beta beating corrections for this one ID to the summed up correction vectors for all IDs
2908                                     addQFsp = addQFsp+DelQF;
2909                                     addQDsp = addQDsp+DelQD;
2910
2911
2912                                     % Skew FF for IVID
2913                                     if (IDSector(gapnum,1)==6)
2914                                         scale=(gap2tune(6)/0.005)^(3/4)*0.16;
2915                                         [SQSFincr, SQSDincr] = set_etaywave_nuy9_20skews_skewFF(scale);
2916                                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2917                                         % should add a limit check here %
2918                                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2919                                         setpv('SQSF', 'Setpoint', SQSFsp+SQSFincr, [], 0, 'Physics');
2920                                         setpv('SQSD', 'Setpoint', SQSDsp+SQSDincr, [], 0, 'Physics');
2921                                     end
2922
2923                                 end
2924
2925                                 % Set quadrupoles using main setpoint channels
2926                                 setpv('QF', QFsp+addQFsp,[], 0);
2927                                 setpv('QD', QDsp+addQDsp,[], 0);
2928                                 % % Set quadrupoles using FF setpoint channels
2929                                 % setpv('QF', 'FF', addQFsp, [], 0);
2930                                 % setpv('QD', 'FF', addQDsp, [], 0);
2931
2932                             end
2933
2934                         else
2935                             error('Unknown type selected for tune FF');
2936                         end
2937
2938                     else
2939                         disp('  No tune FF algorithm for non-production modes yet...');
2940                     end
2941                 end
2942
2943                 ffdeltaquad_delay = toc;
2944                 %fprintf('tune FF delay = %.1f seconds\n',ffdeltaquad_delay);
2945                 % fprintf('Tune Done: %f \n',gettime-t00);
2946
2947                 % Output info to screen
2948                 set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
2949                 set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
2950                 %pause(0);
2951
2952                 FOFBStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2953                     getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2954                     getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2955                     getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2956                 for loop = 1:size(FOFBStatus,2)
2957                     if FOFBStatus(loop)==0
2958                         FOFBStatusStr(loop,:) = 'OFF ';
2959                     elseif FOFBStatus(loop)==1
2960                         FOFBStatusStr(loop,:) = 'ON  ';
2961                     elseif FOFBStatus(loop)==2
2962                         FOFBStatusStr(loop,:) = 'OPEN';
2963                     else
2964                         FOFBStatusStr(loop,:) = 'BAD ';
2965                     end
2966                 end
2967                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 %s',FOFBStatusStr(1,:)),'ForegroundColor',[0 0 0]);
2968                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 %s',FOFBStatusStr(2,:)),'ForegroundColor',[0 0 0]);
2969                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 %s',FOFBStatusStr(3,:)),'ForegroundColor',[0 0 0]);
2970                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 %s',FOFBStatusStr(4,:)),'ForegroundColor',[0 0 0]);
2971                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 %s',FOFBStatusStr(5,:)),'ForegroundColor',[0 0 0]);
2972                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 %s',FOFBStatusStr(6,:)),'ForegroundColor',[0 0 0]);
2973                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 %s',FOFBStatusStr(7,:)),'ForegroundColor',[0 0 0]);
2974                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 %s',FOFBStatusStr(8,:)),'ForegroundColor',[0 0 0]);
2975                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 %s',FOFBStatusStr(9,:)),'ForegroundColor',[0 0 0]);
2976                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 %s',FOFBStatusStr(10,:)),'ForegroundColor',[0 0 0]);
2977                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 %s',FOFBStatusStr(11,:)),'ForegroundColor',[0 0 0]);
2978                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 %s',FOFBStatusStr(12,:)),'ForegroundColor',[0 0 0]);
2979
2980
2981                 %fprintf('End of feedback operations: %f \n\n',gettime-t00);
2982
2983                 % Wait for next update time or stop request
2984                 while (gettime-t00) < LoopDelay
2985                     %disp('interval could be shorter')
2986                     pause(.05);
2987                     % Check if GUI has been closed
2988                     if isempty(gcbf)
2989                         FEEDBACK_STOP_FLAG = 1;
2990                         lasterr('SRCONTROL GUI DISAPPEARED!');
2991                         error('SRCONTROL GUI DISAPPEARED!');
2992                     end
2993
2994                     % Check if Stop button was pressed
2995                     if FEEDBACK_STOP_FLAG == 1
2996                         % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2997                         if getpv('SR01____FFBON__BC00')==1
2998                             disp('   Stopping Fast Orbit Feedback.');
2999                         end
3000                         setpv('SR01____FFBON__BC00',0);
3001                         pause(0.5);
3002                         setpv('SR01____FFBON__BC00',2);
3003                         break;
3004                     end
3005                 end
3006
3007
3008                 if FEEDBACK_STOP_FLAG == 1
3009                     % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
3010                     if getpv('SR01____FFBON__BC00')==1
3011                         disp('   Stopping Fast Orbit Feedback.');
3012                     end
3013                     setpv('SR01____FFBON__BC00',0);
3014                     pause(0.5);
3015                     setpv('SR01____FFBON__BC00',2);
3016                     break;
3017                 end
3018
3019                 StartErrorTime = gettime;
3020
3021             catch
3022
3023                 fprintf('\n  %s \n',lasterr);
3024
3025                 % Quit if error exists for more than 20 seconds
3026                 if gettime-StartErrorTime>20 || FEEDBACK_STOP_FLAG==1
3027                     fprintf('%s  Orbit feedback stopped due to error condition. \n\n',datestr(now));
3028
3029                     %send alphapage to operator pager
3030                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
3031                     FEEDBACK_STOP_FLAG = 1;
3032
3033                     setpv('SR_STATE', -5);
3034                     [StateNumber, StateString] = getsrstate;
3035                     if StateNumber >= 0
3036                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
3037                     else
3038                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
3039                     end
3040                 else
3041                     a = clock;
3042                     fprintf('   Orbit feedback was paused due to error condition (%s %d:%d:%.0f). \n', date, a(4), a(5), a(6));
3043                     fprintf('   Orbit feedback has automatically restarted and is running. \n\n');
3044                 end
3045
3046             end
3047
3048             if FEEDBACK_STOP_FLAG == 1
3049                 % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
3050                 if getpv('SR01____FFBON__BC00')==1
3051                     disp('   Stopping Fast Orbit Feedback.');
3052                 end
3053                 setpv('SR01____FFBON__BC00',0);
3054                 pause(0.5);
3055                 setpv('SR01____FFBON__BC00',2);
3056                 break;
3057             end
3058
3059             %fprintf('End of feedback loop: %f \n\n',gettime-t00);
3060
3061             %pause(0);
3062
3063             % this loop delays turn on of Fast Feedback system
3064             if FBloopIter < 5
3065                 FBloopIter = FBloopIter + 1;
3066             end
3067
3068         end  % End of feedback loop
3069
3070
3071         % End feedback, reset all parameters
3072         try
3073
3074             % Enable buttons
3075             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','on');
3076             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','off');
3077             set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','on');
3078             set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','on');
3079             set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','on');
3080             set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','on');
3081             set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','on');
3082             set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','on');
3083             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','on');
3084             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','on');
3085             set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','on');
3086             set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','on');
3087             set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','on');
3088
3089             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = _____ mm'),'ForegroundColor',[0 0 0]);
3090             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = _____ mm'),'ForegroundColor',[0 0 0]);
3091
3092             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 ____'),'ForegroundColor',[0 0 0]);
3093             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 ____'),'ForegroundColor',[0 0 0]);
3094             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 ____'),'ForegroundColor',[0 0 0]);
3095             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 ____'),'ForegroundColor',[0 0 0]);
3096             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 ____'),'ForegroundColor',[0 0 0]);
3097             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 ____'),'ForegroundColor',[0 0 0]);
3098             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 ____'),'ForegroundColor',[0 0 0]);
3099             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 ____'),'ForegroundColor',[0 0 0]);
3100             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 ____'),'ForegroundColor',[0 0 0]);
3101             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 ____'),'ForegroundColor',[0 0 0]);
3102             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 ____'),'ForegroundColor',[0 0 0]);
3103             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 ____'),'ForegroundColor',[0 0 0]);
3104
3105             %pause(0);
3106
3107         catch
3108
3109             % GUI must have been closed
3110
3111         end
3112
3113
3114         % Reset Bergoz BPM time constant to whatever it was before feedback started
3115         fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
3116         setbpmtimeconstant(BPMtimeconstantOFB);
3117
3118
3119         a = clock;
3120         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
3121         [StateNumber, StateString] = getsrstate;
3122         if StateNumber >= 0
3123             setpv('SR_STATE',5.1);
3124             [StateNumber, StateString] = getsrstate;
3125             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
3126             fprintf('   ******************************\n');
3127             fprintf('   **  Orbit Feedback Stopped  **\n');
3128             fprintf('   ******************************\n\n');
3129         else
3130             [StateNumber, StateString] = getsrstate;
3131             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
3132             fprintf('   ****************************************\n');
3133             fprintf('   **  Problem With Slow Orbit Feedback  **\n');
3134             fprintf('   ****************************************\n\n');
3135         end
3136         set(0,'showhiddenhandles','off');
3137         pause(0);
3138
3139
3140     case 'FeedbackSetup'
3141         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
3142
3143         if InitFlag
3144
3145
3146             % Get the device lists from oscsinit and convert to srcontrol variables
3147             [HBPM, VBPM, HCM, VCM, HSV, VSV] = ocsinit('SOFB');
3148             Xivec = 1:HSV;
3149             Yivec = 1:VSV;
3150             BPMlist1 = HBPM.DeviceList;
3151             HCMlist1 = HCM.DeviceList;
3152             VCMlist1 = VCM.DeviceList;
3153
3154
3155             OCSx.BPM = getx(BPMlist1, 'struct');
3156             OCSx.CM = getsp('HCM', HCMlist1, 'struct');
3157             OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
3158             OCSx.NIter = 1;
3159             OCSx.SVDIndex = Xivec;
3160             OCSx.IncrementalFlag = 'No';
3161             OCSx.BPMWeight = {[]};
3162             OCSx.FitRF = 0;
3163             OCSy.BPM = gety(BPMlist1, 'struct');
3164             OCSy.CM = getsp('VCM', VCMlist1, 'struct');
3165             OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
3166             OCSy.NIter = 1;
3167             OCSy.SVDIndex = Yivec;
3168             OCSy.IncrementalFlag = 'No';
3169             OCSy.BPMWeight = {[]};
3170             OCSy.FitRF = 0;
3171
3172             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
3173             % do we need these Smat calls? %
3174             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
3175             SXmat = getrespmat(OCSx.BPM, OCSx.CM, 'numeric');
3176             SYmat = getrespmat(OCSy.BPM, OCSy.CM, 'numeric');
3177             % [OCSx, Sx, Ux, Vx] = orbitcorrectionmethods(OCSx, SXmat);
3178             % [OCSy, Sy, Uy, Vy] = orbitcorrectionmethods(OCSy, SYmat);
3179
3180             % initialize FFTypeFlag
3181             FFTypeFlag = 'Global';
3182
3183             % Fit decision comes from check box
3184             if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
3185                 OCSx.FitRF = 1;
3186                 Xivec = 1:HSV+1;
3187             end
3188
3189         else
3190
3191             % Get vectors
3192             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
3193             % the two lines below seem to fix BPMlist editing problem
3194             OCSx = FB.OCSx;
3195             OCSy = FB.OCSy;
3196             BPMlist1 = FB.BPMlist1;
3197             HCMlist1 = FB.HCMlist1;
3198             VCMlist1 = FB.VCMlist1;
3199             Xivec = FB.Xivec;
3200             Yivec = FB.Yivec;
3201             Xgoal = FB.OCSx.GoalOrbit;
3202             OCSx.GoalOrbit = Xgoal;
3203             Ygoal = FB.OCSy.GoalOrbit;
3204             OCSy.GoalOrbit = Ygoal;
3205             FFTypeFlag = FB.FFTypeFlag;
3206
3207
3208             % FF corrector magnet list - only channels which are blocked when FF is running should be
3209             % listed
3210             ListFF = [
3211                 4     2
3212                 4     8
3213                 5     1
3214                 5     7
3215 %               5     8 % IVID is using digital FF, i.e. FF algorithm does not block
3216 %               6     1 % other access to PVs
3217                 6     8
3218                 7     1
3219                 7     8
3220                 8     1
3221                 8     8
3222                 9     1
3223                 9     8
3224                 10    1
3225                 11    8
3226                 12    1];
3227             ElemFF = dev2elem('HCM',ListFF);
3228
3229
3230             % Add button to change #ivectors, cm, IDBPMs,
3231             EditFlag = 0;
3232             h_fig1 = figure;
3233             while EditFlag ~= 6
3234
3235                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
3236                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
3237
3238                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
3239                     DispOrbit = getdisp('BPMx', BPMlist1);
3240                     Sx = [Sx DispOrbit];
3241                 end
3242
3243                 Sx(isnan(Sx)) = 0;
3244                 Sy(isnan(Sy)) = 0;
3245
3246                 [Ux, SVx, Vx] = svd(Sx);
3247                 [Uy, SVy, Vy] = svd(Sy);
3248
3249
3250                 % Remove singular values greater than the actual number of singular values
3251                 i = find(Xivec>length(diag(SVx)));
3252                 if ~isempty(i)
3253                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
3254                     pause(0);
3255                     Xivec(i) = [];
3256                 end
3257                 i = find(Yivec>length(diag(SVy)));
3258                 if ~isempty(i)
3259                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
3260                     pause(0);
3261                     Yivec(i) = [];
3262                 end
3263
3264
3265                 Ax = Sx*Vx(:,Xivec);
3266                 Tx = inv(Ax'*Ax)*Ax';
3267
3268                 Ay = Sy*Vy(:,Yivec);
3269                 Ty = inv(Ay'*Ay)*Ay';
3270
3271                 figure(h_fig1);
3272                 subplot(2,1,1);
3273                 semilogy(diag(SVx),'b');
3274                 hold on;
3275                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
3276                 ylabel('Horizontal');
3277                 title('Response Matrix Singular Values');
3278                 hold off;
3279                 subplot(2,1,2);
3280                 semilogy(diag(SVy),'b');
3281                 hold on;
3282                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
3283                 xlabel('Singular Value Number');
3284                 ylabel('Vertical');
3285                 hold off;
3286                 drawnow;
3287
3288                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List', ...
3289                     'BPM List','Change the Goal Orbit','Continue');
3290
3291                 if EditFlag == 1
3292                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
3293                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
3294                     titlestr='SVD Orbit Feedback';
3295                     lineNo=1;
3296                     answer=inputdlg(prompt,titlestr,lineNo,def);
3297                     if ~isempty(answer)
3298                         XivecNew = fix(str2num(answer{1}));
3299                         if isempty(XivecNew)
3300                             disp('   Horizontal E-vector cannot be empty.  No change made.');
3301                         else
3302                             if any(XivecNew<=0) || max(XivecNew)>length(diag(SVx))
3303                                 disp('   Error reading horizontal E-vector.  No change made.');
3304                             else
3305                                 Xivec = XivecNew;
3306                             end
3307                         end
3308                         YivecNew = fix(str2num(answer{2}));
3309                         if isempty(YivecNew)
3310                             disp('   Vertical E-vector cannot be empty.  No change made.');
3311                         else
3312                             if any(YivecNew<=0) || max(YivecNew)>length(diag(SVy))
3313                                 disp('   Error reading vertical E-vector.  No change made.');
3314                             else
3315                                 Yivec = YivecNew;
3316                             end
3317                         end
3318                     end
3319                 end
3320
3321                 if EditFlag == 2
3322                     List= getlist('HCM','Trim');
3323                     CheckList = zeros(96,1);
3324                     Elem = dev2elem('HCM', HCMlist1);
3325                     CheckList(Elem) = ones(size(Elem));
3326                     CheckList = CheckList(dev2elem('HCM',List));
3327
3328                     % Remove FF corrrectors
3329                     %           Elem = dev2elem('HCM',List);
3330                     %           for j = length(ElemFF):-1:1
3331                     %              i = find(Elem==ElemFF(j));
3332                     %              Elem(i,:) = [];
3333                     %              List(i,:) = [];
3334                     %              CheckList(i,:) = [];
3335                     %           end
3336
3337                     newList = editlist(List, 'HCMtrim', CheckList);
3338
3339                     if isempty(newList)
3340                         fprintf('   WARNING: Horizontal corrector magnet list is empty!\n');
3341                         HCMlist1 = newList;
3342                     else
3343                         HCMlist1 = newList;
3344                     end
3345                     OCSx.CM.DeviceList = HCMlist1;
3346                 end
3347
3348                 if EditFlag == 3
3349                     List = getlist('VCM','Trim');
3350                     CheckList = zeros(96,1);
3351                     Elem = dev2elem('VCM', VCMlist1);
3352                     CheckList(Elem) = ones(size(Elem));
3353                     CheckList = CheckList(dev2elem('VCM',List));
3354
3355                     % Remove FF corrrectors
3356                     %           Elem = dev2elem('VCM',List);
3357                     %           for j = length(ElemFF):-1:1
3358                     %              i = find(Elem==ElemFF(j));
3359                     %              Elem(i,:) = [];
3360                     %              List(i,:) = [];
3361                     %              CheckList(i,:) = [];
3362                     %           end
3363
3364                     newList = editlist(List, 'VCMtrim', CheckList);
3365
3366                     if isempty(newList)
3367                         fprintf('   WARNING: Vertical corrector magnet list is empty!\n');
3368                         VCMlist1 = newList;
3369                     else
3370                         VCMlist1 = newList;
3371                     end
3372                     OCSy.CM.DeviceList = VCMlist1;
3373                 end
3374
3375                 if EditFlag == 4
3376                     ListOld = BPMlist1;
3377                     XgoalOld = Xgoal;
3378                     YgoalOld = Ygoal;
3379
3380                     % Full BPM list
3381                     List = getbpmlist('Bergoz');
3382
3383                     CheckList = zeros(size(List,1),1);
3384                     if ~isempty(BPMlist1)
3385                         for i = 1:size(List,1)
3386                             k = find(List(i,1)==BPMlist1(:,1));
3387                             l = find(List(i,2)==BPMlist1(k,2));
3388
3389                             if isempty(k) || isempty(l)
3390                                 % Item not in list
3391                             else
3392                                 CheckList(i) = 1;
3393                             end
3394                         end
3395                     end
3396
3397                     newList = editlist(List, 'BPM', CheckList);
3398                     if isempty(newList)
3399                         fprintf('   BPM list cannot be empty.  No change made.\n');
3400                     else
3401                         BPMlist1 = newList;
3402                     end
3403
3404                     % Set the goal orbit to the golden orbit
3405                     Xgoal = getgolden('BPMx', BPMlist1);
3406                     Ygoal = getgolden('BPMy', BPMlist1);
3407
3408
3409                     % If a new BPM is added, then set the goal orbit to the golden orbit
3410                     for i = 1:size(BPMlist1,1)
3411
3412                         % Is it a new BPM?
3413                         k = find(BPMlist1(i,1)==ListOld(:,1));
3414                         l = find(BPMlist1(i,2)==ListOld(k,2));
3415
3416                         if isempty(k) || isempty(l)
3417                             % New BPM
3418                         else
3419                             % Use the old value for old BPM
3420                             Xgoal(i) = XgoalOld(k(l));
3421                             Ygoal(i) = YgoalOld(k(l));
3422                         end
3423                     end
3424                     OCSx.BPM.DeviceList = BPMlist1;
3425                     OCSy.BPM.DeviceList = BPMlist1;
3426                     OCSx.GoalOrbit = Xgoal;
3427                     OCSy.GoalOrbit = Ygoal;
3428                 end
3429
3430                 if EditFlag == 5
3431                     ChangeList = editlist2(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
3432
3433                     for i = 1:size(ChangeList,1)
3434
3435                         k = find(ChangeList(i,1)==BPMlist1(:,1));
3436                         l = find(ChangeList(i,2)==BPMlist1(k,2));
3437
3438                         prompt={sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
3439                         def={sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
3440                         titlestr='CHANGE THE GOAL ORBIT';
3441                         lineNo=1;
3442                         answer = inputdlg(prompt, titlestr, lineNo, def);
3443
3444                         if isempty(answer)
3445                             % No change
3446                             fprintf('   No change was made to the golden orbit.\n');
3447                         else
3448                             Xgoalnew = str2num(answer{1});
3449                             if isempty(Xgoalnew)
3450                                 fprintf('   No change was made to the horizontal golden orbit.\n');
3451                             else
3452                                 Xgoal(k(l)) = Xgoalnew;
3453                             end
3454
3455                             Ygoalnew = str2num(answer{2});
3456                             if isempty(Ygoalnew)
3457                                 fprintf('   No change was made to the vertical golden orbit.\n');
3458                             else
3459                                 Ygoal(k(l)) = Ygoalnew;
3460                             end
3461                         end
3462                     end
3463                     if ~isempty(ChangeList)
3464                         fprintf('   Note:  Changing the goal orbit for "Slow Orbit Feedback" does not change the goal orbit for "Orbit Correction."\n');
3465                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
3466                     end
3467                     OCSx.GoalOrbit = Xgoal;
3468                     OCSy.GoalOrbit = Ygoal;
3469                 end
3470
3471 %                 if EditFlag == 6
3472 %                     FFTypeFlag = questdlg(sprintf('Do you want to use a fully local or a combined local/global compensation of IDs? (nuy=9.2 only)'),'Tune FF','Local','Global', 'Global');
3473 %                     if strcmp(FFTypeFlag,'Local')
3474 %                         disp(['   The tune FF will use 8 local quadrupoles to compensate beta beating and tune shift']);
3475 %                         disp(['   from each ID.']);
3476 %                     elseif strcmp(FFTypeFlag,'Global')
3477 %                         disp(['   The tune FF will use 4 local quadrupoles to compensate beta beating and all QF+QD']);
3478 %                         disp(['   to compensate tune shift from each ID.']);
3479 %                     end
3480 %                 end
3481
3482             end
3483             close(h_fig1);
3484         end
3485
3486         % Save vectors
3487         FB.Xivec = Xivec;
3488         FB.Yivec = Yivec;
3489         FB.HCMlist1 = HCMlist1;
3490         FB.VCMlist1 = VCMlist1;
3491         FB.BPMlist1 = BPMlist1;
3492
3493         OCSx.SVDIndex = Xivec;
3494         OCSy.SVDIndex = Yivec;
3495         FB.OCSx = OCSx;
3496         FB.OCSy = OCSy;
3497
3498         FB.FFTypeFlag = FFTypeFlag;
3499         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata',FB);
3500
3501
3502     case 'FastFeedbackSetup'
3503
3504         InitFlag = Input2;
3505
3506         if InitFlag
3507             FOFBFreq = 1000;
3508             % user operations 9/14-10/17/04: P=0.5, I=120, D=0.0015 (for both planes)
3509             % below are known good values for user ops as of 8-1-05
3510             HorP = 2;
3511             HorI = 300;
3512             HorD = 0.002;
3513             VertP = 1;
3514             VertI = 100;
3515             VertD = 0.0015;
3516
3517             % this initial set is now done in hwinit.m because it's not a good idea to set anything when srcontrol is launched
3518             % try
3519             %     setsp('SR01____FFBFREQAC00', FOFBFreq); % set freq
3520             %     write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3521             % catch
3522             %     disp('   Trouble setting Fast Orbit Feedback parameters!');
3523             % end
3524
3525         else
3526             % Get vectors
3527             FOFB = get(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata');
3528             FOFBFreq = FOFB.FOFBFreq;
3529             HorP  = FOFB.HorP;
3530             HorI  = FOFB.HorI;
3531             HorD  = FOFB.HorD;
3532             VertP = FOFB.VertP;
3533             VertI = FOFB.VertI;
3534             VertD = FOFB.VertD;
3535
3536             % Add button to change #ivectors, CMs, IDBPMs,
3537             EditFlag = 0;
3538             %h_fig1 = figure;
3539             while EditFlag ~= 3
3540
3541                 %EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'HCM List', 'VCM List', ...
3542                 %   'IDBPM List', 'BBPM List', 'Continue');
3543                 % Use menu below until other FFB config routines work (then also uncomment options 3,4,5,6 below)
3544                 EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'Continue');
3545
3546                 if EditFlag == 1
3547                     % change rate
3548
3549                     prompt={'Enter the desired Fast Feedback Frequency (1-1000 Hz)'};
3550                     def={num2str(FOFBFreq)};
3551                     titlestr='Fast Feedback Setup';
3552                     lineNo=1;
3553                     answer=inputdlg(prompt,titlestr,lineNo,def);
3554                     if ~isempty(answer)
3555                         FOFBFreq = fix(str2num(answer{1}));
3556                         if isempty(FOFBFreq)
3557                             disp('   Frequency value cannot be empty.  No change made.');
3558                             FOFBFreq = getsp('SR01____FFBFREQAC00');
3559                         else
3560                             if FOFBFreq < 1 || FOFBFreq > 1000
3561                                 disp('   Frequency must be between 1 and 1000 Hz.  No change made.');
3562                                 FOFBFreq = getsp('SR01____FFBFREQAC00');
3563                             end
3564                         end
3565                         setsp('SR01____FFBFREQAC00',FOFBFreq); % change freq
3566                         pause(0.5);
3567                         fprintf('   Fast orbit feedback frequency is running at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
3568                     else
3569                         FOFBFreq = getsp('SR01____FFBFREQAC00');
3570                     end
3571                 end
3572
3573                 if EditFlag == 2
3574                     % edit  PIDs
3575                     % User defaults are HorP=2, HorI=300, HorD=0.002, VertP=1, VertI=100, VertD=0.0015
3576                     prompt={'P horizontal', 'I horizontal', 'D horizontal', 'P vertical', 'I vertical', 'D vertical'};
3577                     def={num2str(HorP), num2str(HorI), num2str(HorD), num2str(VertP), num2str(VertI), num2str(VertD)};
3578                     titlestr='Fast Feedback PID Setup';
3579                     lineNo=1;
3580                     answer=inputdlg(prompt,titlestr,lineNo,def);
3581                     if ~isempty(answer)
3582                         HorPnewnum = str2num(answer{1});
3583                         if isempty(HorPnewnum)
3584                             disp('   HorP value cannot be empty.  No change made.');
3585                         else
3586                             HorP = HorPnewnum;
3587                         end
3588                         HorInewnum = str2num(answer{2});
3589                         if isempty(HorInewnum)
3590                             disp('   HorI value cannot be empty.  No change made.');
3591                         else
3592                             HorI = HorInewnum;
3593                         end
3594                         HorDnewnum = str2num(answer{3});
3595                         if isempty(HorDnewnum)
3596                             disp('   HorD value cannot be empty.  No change made.');
3597                         else
3598                             HorD = HorDnewnum;
3599                         end
3600                         VertPnewnum = str2num(answer{4});
3601                         if isempty(VertPnewnum)
3602                             disp('   VertP value cannot be empty.  No change made.');
3603                         else
3604                             VertP = VertPnewnum;
3605                         end
3606                         VertInewnum = str2num(answer{5});
3607                         if isempty(VertInewnum)
3608                             disp('   VertI value cannot be empty.  No change made.');
3609                         else
3610                             VertI = VertInewnum;
3611                         end
3612                         VertDnewnum = str2num(answer{6});
3613                         if isempty(VertDnewnum)
3614                             disp('   VertD value cannot be empty.  No change made.');
3615                         else
3616                             VertD = VertDnewnum;
3617                         end
3618
3619                         try
3620                             write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3621                             fprintf('   Setting FFB gains to Horizontal P=%.2f, I=%.1f, D=%.4f;  Vertical P=%.2f, I=%.1f, D=%.4f\n', HorP, HorI, HorD, VertP, VertI, VertD);
3622                         catch
3623                             disp('   Trouble setting Fast Orbit Feedback parameters!');
3624                         end
3625                     end
3626                 end
3627
3628                 %if EditFlag == 3
3629                 %   disp('   This function not yet available.');
3630                 %   % change HCM List
3631                 %end
3632                 %
3633                 %if EditFlag == 4
3634                 %   disp('   This function not yet available.');
3635                 %   % change VCM List
3636                 %end
3637                 %
3638                 %if EditFlag == 5
3639                 %   disp('   This function not yet available.');
3640                 %   % change IDBPM List
3641                 %end
3642                 %
3643                 %if EditFlag == 6
3644                 %   disp('   This function not yet available.');
3645                 %   % change BBPM List
3646                 %end
3647
3648             end
3649             %close(h_fig1);
3650         end
3651
3652         % Save vectors
3653         FOFB.FOFBFreq = FOFBFreq;
3654         FOFB.HorP = HorP;
3655         FOFB.HorI = HorI;
3656         FOFB.HorD = HorD;
3657         FOFB.VertP = VertP;
3658         FOFB.VertI = VertI;
3659         FOFB.VertD = VertD;
3660         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata',FOFB);
3661
3662     otherwise
3663         fprintf('   No action for %s.\n', action);
3664 end   % end case