Description of srcontrol5_add_bump_checks_to_OC
Home > ALS > StorageRing > srcontrol5_add_bump_checks_to_OC.m
srcontrol5_add_bump_checks_to_OC
PURPOSE
srcontrol5
SYNOPSIS
function srcontrol5(action, Input2, Input3)
DESCRIPTION
 srcontrol5
 Storage ring control program
 This program controls all storage ring magnets, performs orbit feedback and
 tune feedforward and helps to diagnose problems in routine user operation
 of the ALS storage ring. It includes a gui to simplify the use of this
 program.
 It was originally programmed by Greg Portmann (until December 2000) with input
 from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
 and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
 The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
 Christoph Steier, July 2002
 SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
 Tom Scarvie, April 2005
CROSS-REFERENCE INFORMATION
This function calls:
amp2k AMP2K - Converts amperes to simulator values
bend2gev BEND2GEV - Compute the energy based on the ramp tables
checksrmags CHECKSRMAGS - Check SR power supplies against a lattice file
checksrorbit ErrorNums =checksrorbit(Sector, BPMxtolerance [.015 mm], [BPMytolerance [.015 mm]])
gap2tune GAP2TUNE - Computes the vertical tune shift for a insertion device gap change.
gaplimit [GapMin, GapMax] = gaplimit(DeviceList)
getbpmlist GETBPMLIST - Return a BPM list based on key words and sector numbers
getbpmtimeconstant GETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
getff GETFF - Get the state of insertion device feed forward and user gap contr5ol
getid GETID - Get the insertion device position, velocity, run flag, and user requested gap
getsrstate [StateNumber, StateString] = getsrstate
ocsinit OCSINIT - Corrector and BPM
set_alarmhandler_AHU_thresholds_inject function set_alarmhandler_AHU_thresholds_inject
set_etaywave_nuy9_20skews_skewFF function [SQSFincr, SQSDincr] = set_etaywave_nuy9_20skews_skewFF(scale);
setbpmtimeconstant SETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
setbumps SETBUMPS - Make a straight section bump
setff function setff(DeviceList, FFEnableBC, GapEnableBC)
setid SETID - Set the insertion device vertical gap
setsrstatechannels
shift2tune SHIFT2TUNE - Computes the horizontal tune shift for a EPU gap and horizontal shift
srcycle SRCYCLE - Storage ring cycle
srramp SRRAMP - Ramp the storage ring energy
write_goldenorbit_ffb function write_goldenorbit_ffb
write_goldenorbit_ffb_2planes WRITE_GOLDENORBIT_FFTB_2PLANES - Sets the BPM setpoints which are used by the fast feedback system
This function is called by:
SOURCE CODE
function srcontrol5(action, Input2, Input3)
% srcontrol5
% Storage ring control program
%
% This program controls all storage ring magnets, performs orbit feedback and
% tune feedforward and helps to diagnose problems in routine user operation
% of the ALS storage ring. It includes a gui to simplify the use of this
% program.
%
% It was originally programmed by Greg Portmann (until December 2000) with input
% from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
% and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
%
% The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
%
% Christoph Steier, July 2002
%
% SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
%
% Tom Scarvie, April 2005
% known bugs/problems (May 2001):
% - IDBPM averaging might be a bit too long for orbit feedback
%        solved after Superbend shutdown ... Instead of averaging, digital low pass filters are used
% - gap2tune does not give correct answers for wiggler and potentially other IDs -> orbit feedback
%        seems to be OK for other IDs, has been corrected for wiggler (fit to insertion device
%        compensation table)
% - chicanes do not work in orbit feedback
%        solved. One problem was that orbit response matrizes were mis-scaled by factor of two.
%        Second problem was different time constant of power supply control. Solved by moving controls
%        of center chicanes to cPCI (and magnets are fast, hysteresis free, aircore coils).
%        Center chicane in sector 4 is now routinely used in orbit feedback. Sector 11 to follow soon.
% - zero reading of ID gap dumps beam
%        solved in srcontrol5, still a problem in srcontrol5_hightune (but that routine has to be completely
%        rewritten because of all recent changes to srcontrol5, anyhow). For gap readings below the minimum
%        allowed gap for a device, the tune feedforward disables itself.
% - cycling of lattice causes frequent power supply failures
%        solved by changing the cycling procedure. 1.5 GeV operation is now on the upper hysteresis branch
%        as was the 1.9 GeV injection lattice before.
% - frequently stalled data in IDBPM readout
%        solved with new BPM readouts and digital filtering. Seems to have been a resolution problem
%        of the digital averaging algorithm.
% - magnet ramp tables are not in perfect agreement with magnetic measurements
%        Does not appear to be a serious problem. Superbends are slightly out of sync with other magnets,
%        but this does not cause any negative effects while ramping.
% - no good way to operate with injection at 1.5 GeV and storage energy below that
%        There now is a reasonable way to inject at 1.5 GeV and ramp down to lower storage energy. But
%        it has to be tested again after implementing new (and more) chicanes ...
% revision history
% 2001-05-10, Christoph Steier
% check whether readback from insertion device is significantly (more than 1 mm) below minimum
% gap, to avoid false zero readings of insertion device gaps to cause the tune feed forward
% to implement false huge correction (and dump the beam). If the insertion device gap readbacks
% gets more than 1 mm below the nominal minimum gap, the routine now assumes the insertion device
% to be open.
%
% 2001-08-30 and during Superbend commissioning, Christoph Steier, Tom Scarvie, Winni Decking
% various changes have been made to incorporate the Superbends and some other new equipment
% installed in the Superbend shutdown. This included some changes to programs being called by srcontrol
% (like srload, srsave, srcycle, srramp, ...). The main changes within srcontrol were in the orbit
% correction and slow orbit feedback routines (incorporating frequency feedback, ...)
%
% 2002-05-04, Christoph Steier
% added new IDBPMs, modified orbit feedback to use trim DACs, removed LSB toggling in vertical
% orbit feedback, ...
%
% 2002-07-29, T.Scarvie
% added check of CM trim currents to warn of problems that might rail the orbit feedback
%
% 2002-07-31, Christoph Steier
% increased the gain of the RF frequency feedback from 1/50 of the gain of the horizontal
% orbit feedback to 1/20. Reason was that the frequency feedback was reacting a bit too slow if all
% insertion device gaps are closed at once at high speed at the beginning of a fill.
%
% 2002-08-05, C.Steier, T.Scarvie
% Added conditional to reduce orbit feedback gain if running in two-bunch mode
%
% 2003-06-02, T.Scarvie
% Added loop inside orbit feedback to reset the SR11 chicane M1 and M2 motors every 20s to combat drift problem
%
% 2003-06-18, C. Steier
% Disabled loop to periodically reset chicane in SR11. Al Robb replaced power supply, seems to be no problem anymore.
%
% 2004-05-10, C. Steier
% The list of all BBPMs is now set up automatically be calling getlist('BBPMx'). This way, new BBPMs have to be added
% at fewer places in the software. It should now be sufficient to modify getlist and run the orbit response matrix
% rountine (getsmat) once to enable use of the new BBPMs.
%
% 2004-05-14, C. Steier
% Modified parameters for ramprate reduction (in srramp and here). Previous parameters were slightly too
% cautious. Increased initial slow ramprate to 0.4 A/s.
%
% 2004-05-14, C. Steier
% Incorporated insertion device compensation schemes for nu_y = 9.2 lattice.
%
% 2004-06-14, T.Scarvie
% Added controls for fast orbit feedback
%
% 2004-06-21, C. Steier
% Added tune feedforward (in the global tune compensation scheme for the nu_y=9.2 lattice) for the shift
% dependent tune shift of the EPUs, as well as a skew quadrupole feedforward for the EPU im sector 11
% (both only active in parallel mode so far).
%
% 2005-02-13, T.Scarvie
% Separated horizontal and vertical planes for setting Fast Feedback PIDs
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NOTES for conversion to new Middle Layer %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% We never use the gap and bump control flags - the radio buttons have been disabled -
%        should we try to keep the functionality?
%
% checksrmags
% checksrorbit(...)
% For the compiler
%#function goldenpage
%#function setoperationalmode
% Check if the AO exists
checkforao;
%%%%%%%%%%%%%%
% Initialize %
%%%%%%%%%%%%%%
global FEEDBACK_STOP_FLAG
SR_Mode = getfamilydata('OperationalMode');
SR_GEV = getfamilydata('Energy');
BSCramprate = getfamilydata('BSCRampRate');
if isnan(BSCramprate) || isempty(BSCramprate)
    BSCramprate = 0.4;
    setfamilydata(BSCramprate, 'BSCRampRate');
end
if nargin < 1
    action = 'Initialize';
end
if nargin < 2
    Input2 = 0;
end
if nargin < 3
    Input3 = 0;
end
if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
    FOFBcheckboxVal = 0;
else
    FOFBcheckboxVal = 1;
end
% if strcmp(getfamilydata('OperationalMode'), '1.5 GeV, Inject at 1.23') || strcmp(SR_Mode, '1.9 GeV, Inject at 1.353')
%     TUNEcheckboxVal = 0;
% else
TUNEcheckboxVal = 1;
% end
%%%%%%%%%%%%%%%%
% Main Program %
%%%%%%%%%%%%%%%%
switch(action)
    case 'StopOrbitFeedback'
        FEEDBACK_STOP_FLAG = 1;
    case 'Initialize'
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % GUI
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        ButtonWidth = 200;
        ButtonHeight  = 25;
        Offset1 = 8*25+12 + 47 + 25+25;
        Offset2 = 47+25+25;
        Offset3 = 45+25;
        Offset4 = 1;
        Offset5 = 30;
        FigWidth = ButtonWidth+6;
        FigHeight  = 3+9*(ButtonHeight+6)+24+Offset1;
        ButtonWidth = 200-6;
        % Change figure position
        set(0,'Units','pixels');
        p=get(0,'screensize');
        h0 = figure( ...
            'Color',[0.8 0.8 0.8], ...
            'HandleVisibility','Off', ...
            'Interruptible', 'on', ...
            'MenuBar','none', ...
            'Name','ALS SR CONTROL', ...
            'NumberTitle','off', ...
            'Units','pixels', ...
            'Position',[30 p(4)-FigHeight-40 FigWidth FigHeight+Offset5], ...
            'Resize','off', ...
            'Tag','SRCTRLFig1');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'FontWeight','Bold', ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+8*(ButtonHeight+3)+19+19+8+Offset1  ButtonWidth 20+Offset5], ...
            'Style','text', ...
            'String','', ...
            'Tag','SRCTRLTitle');
        % Frame Box I
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+3*(ButtonHeight+3)+Offset1-3+Offset5 ButtonWidth+6 7*ButtonHeight+18], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+9*(ButtonHeight+3)+Offset1  ButtonWidth 15+Offset5], ...
            'Style','text', ...
            'String','Lattice Setup Functions');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Cycle'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+8*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Cycle SR Lattice', ...
            'Tag','SRCTRLButton1');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Injection'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+7*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Injection', ...
            'Tag','SRCTRLButton2');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Production'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+6*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String',['Production'], ...
            'Tag','SRCTRLButton3');
        h1 = uicontrol('Parent',h0, ...
            'Callback',[...
            'fprintf(''\n'');' ...
            'disp([''   **********************************************'']);', ...
            'disp([''   **  Changing Storage Ring Operational Mode  **'']);', ...
            'disp([''   **********************************************'']);', ...
            'setoperationalmode;', ...
            'srcontrol5(''CheckInputs'');', ...
            'disp([''   ****************************'']);', ...
            'disp([''   **  Mode Change Complete  **'']);', ...
            'disp([''   ****************************'']);', ...
            'fprintf(''\n'');'], ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+5*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'Value',1, ...
            'String','Change Operational Mode', ...
            'Tag','SRCTRLButtonChangeMode');
        h1 = uicontrol(...
            'Parent',h0, ...
            'Callback', [...
            'srcontrol5(''CheckInputs'');',...
            'srcontrol5(''SRState'');'], ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+4*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Check For Problems', ...
            'Tag','SRCTRLButtonSRState');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs''); goldenpage;', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+3*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Golden Page', ...
            'Tag','SRCTRLButtonGoldenPage');
        % Frame Box II
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+9*(ButtonHeight+3)-29+Offset2+Offset5 ButtonWidth+6 2*ButtonHeight+15], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+10*(ButtonHeight+3)-10+Offset2 ButtonWidth .6*ButtonHeight+Offset5], ...
            'String','Global/Local Orbit Correction', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''OrbitCorrection'');', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+9*(ButtonHeight+3)-6+Offset2+Offset5 ButtonWidth ButtonHeight], ...
            'String','Correct Global Orbit w/ IDBPMs', ...
            'Tag','SRCTRLButtonOrbitCorrection');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''OrbitCorrectionSetup'',1);', ...
            'callback','srcontrol5(''OrbitCorrectionSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[6 9*(ButtonHeight+3)-22+Offset2+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Edit IDBPM, CM, & Local Bump Lists', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonOrbitCorrectionSetup');
        % Frame Box III
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 1*(ButtonHeight)+Offset3+Offset5-38 ButtonWidth+6 8*ButtonHeight+61], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+9*(ButtonHeight+3)+Offset3-25 ButtonWidth .55*ButtonHeight+Offset5], ...
            'String','Orbit Feedback', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+8*(ButtonHeight+3)+Offset3-18+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Slow Orbit Correction', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxSOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+7*(ButtonHeight+3)+Offset3-9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Fast Orbit Correction', ...
            'Style','checkbox', ...
            'Value',FOFBcheckboxVal,...
            'Tag','SRCTRLCheckboxFOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+6*(ButtonHeight+3)+Offset3+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct ID Tune Shift  ', ...
            'Style','checkbox', ...
            'Value',TUNEcheckboxVal,...
            'Tag','SRCTRLCheckboxTune');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+5*(ButtonHeight+3)+Offset3+9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct RF Frequency', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxRF');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''Feedback'');', ...
            'Enable','on', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[8 3+5*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Start FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStart');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''StopOrbitFeedback'');pause(0);', ...
            'Enable','off', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[.5*FigWidth+3 3+5*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Stop FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStop');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[14 4*(ButtonHeight)+Offset3+Offset5-3 ButtonWidth-14 .75*ButtonHeight], ...
            'String','Horizontal RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHorizontal');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[26 3+3.5*(ButtonHeight)+16+Offset3-25+Offset5 ButtonWidth-26 .75*ButtonHeight], ...
            'String','Vertical RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextVertical');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FeedbackSetup'',1);', ...
            'callback','srcontrol5(''FeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 3+3.5*(ButtonHeight)+.5+Offset3-25+Offset5 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit SOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFeedbackSetup');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','01 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB01');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','02 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB02');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','03 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB03');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-32 ButtonWidth-145 .75*ButtonHeight], ...
            'String','04 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB04');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','05 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB05');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','06 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB06');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','07 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB07');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-47 ButtonWidth-145 .75*ButtonHeight], ...
            'String','08 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB08');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[7 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','09 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB09');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[55 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','10 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB10');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[103 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','11 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB11');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[151 4*(ButtonHeight)+Offset3-62 ButtonWidth-145 .75*ButtonHeight], ...
            'String','12 ____', ...
            'Style','text', ...
            'FontSize', 8,...
            'Tag','SRCTRLStaticTextFOFB12');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FastFeedbackSetup'',1);', ...
            'callback','srcontrol5(''FastFeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 1*(ButtonHeight)+Offset3-3 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit FOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFastFeedbackSetup');
        % Frame Box IV
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+ButtonHeight+Offset4-14+Offset5 ButtonWidth+6 ButtonHeight+12], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+1.75*ButtonHeight+5+Offset4-21+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Storage Ring State', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHeader');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''CheckInputs'');', ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ForegroundColor','b', ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+ButtonHeight+6+3+2+Offset4-22+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','   ', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextInformation');
        % Frame Box "Close"
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 8 ButtonWidth+6 ButtonHeight+8], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'Callback','close(gcbf);', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 13 ButtonWidth ButtonHeight], ...
            'String','Close', ...
            'Tag','SRCTRLClose');
        % Update database channels
        setsrstatechannels;
        if nargout > 0
            fig = h0;
        end
    case 'Cycle'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        disp('   **************************');
        disp('   **  Storage Ring Cycle  **');
        disp('   **************************');
        a = clock; fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        BSCFlag = questdlg(sprintf('Cycle Superbend Magnets?'),'SR Cycle','Yes','No','No');
        %if strcmp(BSCFlag,'No')
        %    disp(['   ** Superbends will not be cycled. **']);
        %else
        %    disp(['   ** Superbends will be cycled during the second mini-cycle only. **']);
        %end
        ChicSQFlag = questdlg(sprintf('Cycle chicanes and skew quads and home motor chicanes?'),'SR Cycle','Yes','No','No');
        %if strcmp(ChicSQFlag,'No')
        %    disp(['   ** Chicanes and skew quads will not be cycled; motor chicanes will not be homed. **']);
        %else
        %    disp(['   ** Chicanes and skew quads will be cycled; motor chicanes will be homed. **']);
        %end
        StartFlag = questdlg(sprintf('Start %.1f GeV Cycle?',SR_GEV),'SR Cycle','Yes','No','No');
        if strcmp(StartFlag,'No')
            disp(['   ***************************']);
            disp(['   **    Cycle  Canceled    **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        end
        try
            if GapFlag
                % Make sure that the gaps are open with FF off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open.');
                    disp('   Opening all gaps at maximum speed.');
                    setff([], 1, 0);
                    disp('   Gap control disabled.');
                    disp('   Feed forward enabled.');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened.');
                    disp('   Feed forward and gap control disabled.');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled.');
                end
            else
                disp('   Feed forward and gap control disabled.');
            end
            setff([], 0, 0);
            pause(1);
            srcycle(BSCFlag, ChicSQFlag);
            setpv('SR_STATE',1);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Cycle failed due to error condition! \n\n');
            setpv('SR_STATE',-1);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp('   **********************************************');
            disp('   **  SR Cycle complete, ready for injection  **');
            disp('   **********************************************'); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp('   **********************************');
            disp('   **  Problem cycling SR lattice  **');
            disp('   **********************************'); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
    case 'Injection'
        AD = getad;
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            fprintf('   ***************************************************\n');
            fprintf('   **  Setup For %.2f GeV Injection (with ramping)  **\n', getfamilydata('InjectionEnergy'));
            fprintf('   ***************************************************\n');
            set_alarmhandler_AHU_thresholds_inject;
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',getfamilydata('InjectionEnergy')),'Injection Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            fprintf('   *************************************************\n');
            fprintf('   **  Setup For On Energy Injection at %.2f GeV  **\n', SR_GEV);
            fprintf('   *************************************************\n');
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',SR_GEV),'Injection Setup','Yes','Cancel','Cancel');
        end
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if strcmp(StartFlag,'Cancel')
            disp(['   ********************************']);
            disp(['   **  Injection Setup Canceled  **']);
            disp(['   ********************************']);
            %set_alarmhandler_thresholds_new;
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                setff([],1,0);
                disp('   Gap control disabled');
                disp('   Feed forward enabled');
                pause(1);
                % Set IDs at max velocity w/ velocity profile off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    disp('   Opening all gaps');
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                end
                disp('   Gaps are open');
                disp('   Feed forward and gap control disabled');
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            if (AD.Energy-AD.InjectionEnergy) > 0.05
                % Ramp down to Injection Energy
                set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String','Ramping Down','ForegroundColor','b');
                drawnow;
                ErrorFlag = srramp('Injection');
                if ErrorFlag
                    error('Superbends over temperature.');
                end
                a = clock; fprintf('   %s %d:%d:%.0f\n\n',date, a(4), a(5), a(6));
            elseif (AD.Energy-AD.InjectionEnergy) < -0.05
                % first load injection lattice, then ramp to 1.9 GeV and back to 1.5 GeV to get onto same hysteresis branch
                srload('Injection');
                % load 1.9 GeV lattice
                tempfilename = sprintf('%s19nuy9prod.mat', getfamilydata('Directory','OpsData'));
                srload(tempfilename);
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                pause(5);
            end
            srload('Injection');
            setpv('SR_STATE',2);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Injection lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-2);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            if AD.Energy <= 1.5
                disp(['   *******************************************************************************']);
                disp(['   **  Function complete:  the storage ring is setup for injection at ',sprintf('%.2f',SR_GEV),' GeV  **']);
                disp(['   *******************************************************************************']);
                fprintf('\n');
            else
                fprintf('   **********************************************************************************************\n');
                fprintf('   **  Function complete:  the storage ring is setup for injection at %.2f GeV (upper branch)  **\n', getfamilydata('InjectionEnergy'));
                fprintf('   **********************************************************************************************\n');
                fprintf('\n');
            end
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   ************************************']);
            disp(['   **  Problem with injection setup  **']);
            disp(['   ************************************']);
            fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        %soundchord;
        setfamilydata(0.8, 'BSCRampRate');
    case 'Production'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        AD=getad;
        fprintf('\n');
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            disp('   ********************************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation (with ramping)  **',SR_GEV));
            disp('   ********************************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            disp('   *****************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation  **',SR_GEV));
            disp('   *****************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Yes','Cancel','Cancel');
        end
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if strcmp(StartFlag,'Cancel')
            disp(['   ***************************']);
            disp(['   **  User Setup Canceled  **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                % Make sure that the gaps are open
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open');
                    disp('   Opening all gaps at maximum speed');
                    setff([], 1, 0);
                    disp('   Gap control disabled');
                    disp('   Feed forward enabled');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened');
                    disp('   Feed forward and gap control disabled');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled');
                end
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            %%%%%%%%%%%%%%%
            if (AD.Energy-AD.InjectionEnergy) > 0.05
                % Ramp up to the production lattice
                set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String','Ramping Up','ForegroundColor','b');
                drawnow;
                ErrorFlag = srramp('Production');
                if ErrorFlag
                    error('Superbends over temperature.');
                end
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                srload('Production');
            elseif abs(AD.Energy-AD.InjectionEnergy) < 0.05
                % load production lattice - no ramp required
                srload('Production');
                %a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                pause(1);
            end
            %%%%%%%%%%%%%%%
            if GapFlag
                setff([], 1, 0);
                disp('   Gap control disabled');
                disp('   Feed forward enable');
                pause(1);
                disp('   Insertion device velocity profile boolean control off');
                disp('   Closing all gaps at maximum speed');
                % Set IDs at max velocity w/ velocity profile off
                [Position, Velocity, RunFlag, UserGap] = getid;
                setid([], UserGap, maxsp('IDvel'), 1, 0, 1);
                % Turn velocity profile on
                disp('   Insertion device velocity profile boolean control is on');
                setid([], [], maxsp('IDvel'), 1, 1, 0);
                disp('   Gaps are closed');
                setff([4;7;8;9;10;12], 1, 1);
                setff(5, 1, 0);
                disp('   Gap control enabled (except sector 5 (W16))');
            end
            %set_alarmhandler_thresholds_new;
            setpv('SR_STATE',3);
        catch
            fprintf('   %s \n', lasterr);
            fprintf('   User lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-3);
        end
        %give JH scrapers a chance to move
        % pause(15);
        a = clock;
        datestr1 = date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp(['   **************************************************************************']);
            disp(['   **  Function complete:  the storage ring is setup for users at ',sprintf('%.1f',SR_GEV),' GeV  **']);
            disp(['   **************************************************************************']);
            fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   *************************************']);
            disp(['   **  Problem with production setup  **']);
            disp(['   *************************************']);
            fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        setfamilydata(0.8, 'BSCRampRate');
%         % for BL6.0.x, set lower setpoint limit for IVID to 12.5mm until beamlines are surveyed below that value
%         try
%             scaput('SR06U___GDS1PS_AC00.DRVL',12.5);
%             disp('  Setting SR06U___GDS1PS_AC00.DRVL to 12.5mm (lower limit for IVID');
%         catch
%             disp('  Trouble setting lower limit for IVID to 12.5mm!');
%         end
    case 'CheckInputs'
        SR_GEV = getfamilydata('Energy');
        AD=getad;
        setsrstatechannels;
        set(0,'showhiddenhandles','on');
        if AD.Energy > 1.55 & AD.InjectionEnergy < 1.55
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Down)']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users (Ramp Up)']);
1000         elseif AD.Energy < 1.45
1001             set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Up+cycle)']);
1002             set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV (Ramp Down)']);
1003         else
1004             set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection']);
1005             set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV']);
1006         end
1007         set(findobj('Tag','SRCTRLTitle'),'String',SR_Mode);
1008
1009         [StateNumber, StateString] = getsrstate;
1010         if StateNumber >= 0
1011             set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1012         else
1013             set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1014         end
1015
1016         set(0,'showhiddenhandles','off');
1017
1018
1019     case 'SRState'
1020         NumErrors = 0;
1021         fprintf('\n');
1022         disp('   ***********************************');
1023         disp('   **  Checking Storage Ring State  **');
1024         disp('   ***********************************');
1025         a = clock;
1026         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1027
1028         %       FileName = getpv('SR_LATTICE_FILE','String');   % Last srload file name (in OLD MIDDLE LAYER nomenclature!!)
1029
1030         GeVnow = bend2gev;
1031         if GeVnow == getfamilydata('Energy')
1032             [ConfigSetpoint, ConfigMonitor, FileName] = getproductionlattice;
1033         elseif GeVnow == getfamilydata('InjectionEnergy')
1034             [ConfigSetpoint, ConfigMonitor, FileName] = getinjectionlattice;
1035         else
1036             FileName = '';
1037         end
1038
1039         [StateNumber, StateString] = getsrstate;
1040         fprintf('   Storage ring operational mode: %s\n', SR_Mode);
1041         if StateNumber < 0
1042             fprintf('   Storage ring state error: %s\n', StateString);
1043             NumErrors = NumErrors + 1;
1044         else
1045             fprintf('   Storage ring state: %s\n', StateString);
1046         end
1047         if StateNumber==0
1048             % Storage ring state unknown
1049             NumErrors = NumErrors + 1;
1050         elseif abs(StateNumber)==1 || abs(StateNumber)==2
1051             FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','InjectionFile') '.mat'];
1052             if ~strcmp(FileName, FileNameGoal)
1053                 fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','InjectionFile'), FileName);
1054                 NumErrors = NumErrors + 1;
1055             end
1056         else
1057             FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile') '.mat'];
1058             if ~strcmp(FileName, FileNameGoal)
1059                 fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','LatticeFile'), FileName);
1060                 NumErrors = NumErrors + 1;
1061             end
1062         end
1063
1064
1065         % Check all SR magnets
1066         if isempty(FileName)
1067             fprintf('   Goal setpoints will not be checked since the last lattice load is unknown.\n');
1068             NumErrors1 = checksrmags('');
1069         else
1070 %            NumErrors1 = checksrmags([getfamilydata('Directory','OpsData') FileName]);
1071             NumErrors1 = checksrmags(FileName);
1072         end
1073         if NumErrors1 == 0
1074             fprintf('   SR magnets power supplies are OK.\n');
1075         end
1076         NumErrors = NumErrors + NumErrors1;
1077
1078
1079         % Check RF frequency
1080         if isempty(FileName)
1081             fprintf('   RF frequency will not be checked since the last lattice load is unknown.\n');
1082         else
1083 %            load([getfamilydata('Directory','OpsData'), FileName]);
1084             load(FileName);
1085             [tmp, RFHPCounterPresent] = getrf;
1086             if abs(RFHPCounterPresent-ConfigSetpoint.RF.Setpoint.Data) > .002
1087                 NumErrors = NumErrors + 1;
1088                 fprintf('   RF frequency should be %f, presently it is %f MHz (as measured by the HP counter).\n', ConfigSetpoint.RF.Setpoint.Data, RFHPCounterPresent);
1089             else
1090                 fprintf('   RF frequency is OK (HP counter is %f MHz, at the time of the lattice save it was %f MHz).\n', RFHPCounterPresent, ConfigSetpoint.RF.Setpoint.Data);
1091             end
1092         end
1093
1094
1095         % Check for orbit problems
1096         if (StateNumber >= 3) && (getdcct > 2)   % Production lattice is loaded with beam in the machine
1097             Xtol = 0.070;
1098             Ytol = 0.010;
1099             NumErrors1 = checksrorbit([],Xtol,Ytol);
1100             if NumErrors1
1101                 fprintf('   SR orbit in the ID straight sections or at Bergoz BPMs deviates more than allowed from the golden orbit.\n');
1102             else
1103                 fprintf('   SR orbit in the ID straight sections and at Bergoz BPMs is OK.\n');
1104                 fprintf('   The orbit is within %.3f mm horizontally and %.3f mm vertically', Xtol, Ytol);
1105             end
1106             NumErrors = NumErrors + NumErrors1;
1107         else
1108             fprintf('   Storage ring orbit was not checked.\n');
1109         end
1110
1111
1112         a = clock;
1113         datestr1=date;
1114         fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
1115         if NumErrors
1116             disp('   *********************************');
1117             disp('   **  Storage Ring Has Problems  **');
1118             disp('   *********************************');
1119         else
1120             disp('   **********************************');
1121             disp('   **  Storage Ring Lattice is OK  **');
1122             disp('   **********************************');
1123         end
1124         fprintf('   \n');
1125
1126         set(0,'showhiddenhandles','on');
1127         [StateNumber, StateString] = getsrstate;
1128         if StateNumber >= 0
1129             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1130         else
1131             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1132         end
1133         set(0,'showhiddenhandles','off');
1134
1135
1136     case 'OrbitCorrection'
1137         fprintf('\n');
1138         fprintf('   *********************************\n');
1139         fprintf('   **  Starting Orbit Correction  **\n');
1140         fprintf('   *********************************\n');
1141         a = clock;
1142         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1143
1144         StartFlag = questdlg(sprintf('Start orbit correction, %.1f GeV?',SR_GEV),'Orbit Correction','Yes','No','No');
1145         if strcmp(StartFlag,'No')
1146             disp(['   ********************************']);
1147             disp(['   **  Orbit Correction Aborted  **']);
1148             disp(['   ********************************']);
1149             fprintf('\n');
1150             return
1151         end
1152
1153         if getdcct < 2     % Don't correct the orbit if the current is too small
1154             fprintf('   Orbit not corrected due to small current.\n');
1155             return
1156         end
1157
1158         if abs(SR_GEV-bend2gev(getpv('BEND','Setpoint',[1 1])))>  0.05     % Don't use this routine for the injection lattice
1159             fprintf('   This routine should only be used for the production energy: Correction aborted\n');
1160             return
1161         end
1162
1163         SR_STATE_OLD = scaget('SR_STATE');
1164         set(0,'showhiddenhandles','on');
1165         setpv('SR_STATE',4);
1166         [StateNumber, StateString] = getsrstate;
1167         if StateNumber >= 0
1168             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1169         else
1170             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1171         end
1172         set(0,'showhiddenhandles','off');
1173
1174
1175         try
1176             % save current BPM timeconstant - will reset to this after correction
1177             BPMtimeconstantOC = getbpmtimeconstant;
1178             fprintf('   Current Bergoz BPM time constant is %.1fs\n', BPMtimeconstantOC);
1179
1180             % 2 Hz update rate on IDBPMs
1181             disp('   Bergoz BPM time constant set to 0.5s.')
1182             setbpmtimeconstant(0.5)
1183             pause(2);
1184
1185
1186             % Turn off feed forward
1187             fprintf('   Turning feed forward off.\n');
1188             [FFEnableBM, FFEnableBC] = getff;
1189             setff([], 0);
1190             scasleep(.2);
1191
1192
1193             % Check whether bumps and kickers are on and warn to turn off before starting feedback if necessary
1194             try
1195                 if (getsp('SR01S___BUMP1__BC21')==1 && getsp('SR01S___BUMP1P_BC22')==1) || (getsp('SR01S___SEK____BC21')==1 && getsp('SR01S___SEK_P__BC23')==1) || (getsp('SR01S___SEN____BC20')==1 && getsp('SR01S___SEN_P__BC22')==1)
1196                     soundtada;
1197                     fprintf('   \n');
1198                     fprintf('   *****************************************************************\n');
1199                     fprintf('   ** One or more of the pulsed SR injection magnets is still on! **\n');
1200                     fprintf('   **      Please turn them off then re-correct the orbit...      **\n');
1201                     fprintf('   *****************************************************************\n');
1202                     fprintf('   \n');
1203                 end
1204             catch
1205                 disp('**Problem checking the state of the bumps and kickers - please check that they are not pulsing.');
1206             end
1207
1208
1209             % Get vectors
1210             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1211             LocalBumplist = FB.LocalBumplist;
1212
1213         catch
1214
1215             fprintf('   %s \n',lasterr);
1216             fprintf('   Orbit correction setup failed due to error condition! \n\n');
1217             setpv('SR_STATE',-4);
1218             set(0,'showhiddenhandles','on');
1219             [StateNumber, StateString] = getsrstate;
1220             if StateNumber >= 0
1221                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1222             else
1223                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1224             end
1225             set(0,'showhiddenhandles','off');
1226
1227             % Reset BPM timeconstant to whatever it was before correction
1228             setbpmtimeconstant(BPMtimeconstantOC);
1229             fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1230             return
1231         end
1232
1233         iNotHCMChicane = find(FB.HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
1234         iHCMChicane = find(FB.HCMlist1(:,2) == 10);
1235         iNotVCMChicane = find(FB.VCMlist1(:,2) < 10);
1236         iVCMChicane = find(FB.VCMlist1(:,2) == 10);
1237
1238         fprintf('   Starting horizontal and vertical global orbit correction (SVD method).\n');
1239
1240         for iloop = 1:3
1241             try
1242                 % use the following to get corrector settings in OCS without setting them, so the values can be checked
1243                 FB.OCSx = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
1244                 FB.OCSy = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
1245                 if any(abs(FB.OCSx.CM.Delta(iNotHCMChicane)) > 5)
1246                   disp('   Orbit Correction is changing some horizontal corrector(s) > 5A!!');
1247                 end
1248                 if any(abs(FB.OCSy.CM.Delta(iNotVCMChicane)) > 5)
1249                   disp('   Orbit Correction is changing some vertical corrector(s) > 5A!!');
1250                 end
1251                 if any(abs(FB.OCSx.CM.Delta(iHCMChicane)) > 10)
1252                   disp('   Orbit Correction is changing some horizontal chicane corrector(s) > 10A!!');
1253                 end
1254                 if any(abs(FB.OCSy.CM.Delta(iVCMChicane)) > 10)
1255                     disp('   Orbit Correction is changing some vertical chicane corrector(s) > 10A!!');
1256                 end
1257
1258                 % Correct RF
1259                 rf0=getrf;
1260                 nRFsteps = 4*ceil(abs(FB.OCSx.DeltaRF/10e-6)); %added factor 4 to slow down change for laser-lock at BL11.0.1 - 3-14-08, T.Scarvie
1261                 if nRFsteps > 100
1262                     nRFsteps = 100;
1263                 end
1264                 for loop = 1:nRFsteps
1265                     steprf(FB.OCSx.DeltaRF/nRFsteps,0);
1266                 end
1267                 fprintf('   %d. nRFsteps = %d, RF change = %.1f Hz\n',iloop, nRFsteps, FB.OCSx.DeltaRF*1e6);
1268 %               fprintf('   %d. RF change = %.1f Hz, nRFsteps = %d, DelRF = %.1f Hz\n',iloop, (getrf-rf0)*1e6, nRFsteps, FB.OCSx.DeltaRF*1e6);
1269
1270                 % Correct horizontal and vertical orbits
1271                 % calculate corrections
1272                 FB.OCSx.CM.Data = FB.OCSx.CM.Data + FB.OCSx.CM.Delta;
1273                 FB.OCSy.CM.Data = FB.OCSy.CM.Data + FB.OCSy.CM.Delta;
1274                 % start vertical correctors moving
1275                 setpv(FB.OCSy.CM,0);
1276                 % Correct horizontal
1277                 setpv(FB.OCSx.CM,-1);
1278                 % Correct vertical
1279                 setpv(FB.OCSy.CM,-2);
1280
1281                 % Check for current in machine - stop orbit correction if DCCT < 5mA
1282                 if (getdcct < 2)
1283                     error('**There is less than 5mA in the machine! Stopping orbit correction.');
1284                 end
1285
1286                 % Check state of gaps - stop orbit correction if any are moving
1287                 GAPrunflag = getpv('ID','RunFlag');
1288                 if any(GAPrunflag-round(GAPrunflag))
1289                     error('**One or more of the gaps are moving! Stopping orbit correction.');
1290                 end
1291
1292                 x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
1293                 y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
1294                 fprintf('   %d. Horizontal RMS = %.3f mm\n', iloop, norm(x)/sqrt(length(x)));
1295                 fprintf('   %d.   Vertical RMS = %.3f mm\n', iloop, norm(y)/sqrt(length(y)));
1296
1297             catch
1298                 % fprintf('   %s \n',lasterr);
1299                 fprintf('   Orbit correction failed due to error condition!\n  Fix the problem, reload the lattice (srload), and try again.  \n\n');
1300                 setpv('SR_STATE',-4);
1301                 set(0,'showhiddenhandles','on');
1302                 [StateNumber, StateString] = getsrstate;
1303                 if StateNumber >= 0
1304                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1305                 else
1306                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1307                 end
1308                 set(0,'showhiddenhandles','off');
1309
1310                 % Reset BPM timeconstant to whatever it was before correction
1311                 setbpmtimeconstant(BPMtimeconstantOC);
1312                 fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1313                 return
1314             end
1315         end
1316
1317
1318         % Set user bumps w/o sextupole correctors
1319         try
1320
1321             %turn up corrector speed here to quicken setting bumps
1322             HCMramprate = getpv('HCM', 'RampRate');
1323             VCMramprate = getpv('VCM', 'RampRate');
1324             setpv('HCM', 'RampRate', 10, [], 0);
1325             setpv('VCM', 'RampRate', 10, [], 0);
1326
1327             if ~isempty(LocalBumplist)
1328                 fprintf('   Setting local bumps in the straight sections.\n');
1329                 for loop = 1:size(LocalBumplist,1)
1330
1331                     % Check for current in machine - stop orbit correction if DCCT < 5mA
1332                     if (getdcct < 2)
1333                         error('** There is less than 5mA in the machine! Stopping local bumps.');
1334                     end
1335
1336                     % Check state of gaps - stop setting bumps if any are moving
1337                     GAPrunflag = getpv('ID','RunFlag');
1338                     if any(GAPrunflag-round(GAPrunflag))
1339                         error('** One or more of the gaps are moving! Stopping local bumps.');
1340                     end
1341
1342                     HCMoldsp = getsp('HCM', FB.HCMlist1);
1343                     VCMoldsp = getsp('VCM', FB.VCMlist1);
1344
1345                     if any(LocalBumplist(loop,1) == [4 6 11])
1346                         if LocalBumplist(loop,2) == 0
1347                             % Upstream bump
1348                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1349                             if isempty(iRemove)
1350                                 setbumps(LocalBumplist(loop,:), 1);
1351                             else
1352                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1353                             end
1354                         elseif LocalBumplist(loop,2) == 1
1355                             % Upstream bump
1356                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;],FB.OCSx.BPM.DeviceList);
1357                             if isempty(iRemove)
1358                                 setbumps(LocalBumplist(loop,:), 1);
1359                             else
1360                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1361                             end
1362                         else
1363                             % Downstream bump
1364                             [i, iRemove] = findrowindex([LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1365                             if isempty(iRemove)
1366                                 setbumps(LocalBumplist(loop,:), 1);
1367                             else
1368                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1369                             end
1370                         end
1371                     else
1372                         [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1373                         if isempty(iRemove)
1374                             setbumps(LocalBumplist(loop,:), 1);
1375                         else
1376                             fprintf('\n   BPMs missing from Sector %02d - skipping local bump for that sector.\n\n', LocalBumplist(loop,1));
1377                         end
1378                     end
1379
1380                     HCMnewsp = getsp('HCM', FB.HCMlist1);
1381                     VCMnewsp = getsp('VCM', FB.VCMlist1);
1382                     % Remove center chicane trim from corrector check
1383                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 5) || (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 10)
1384                         error('**Setbumps caused some corrector magnet currents to change by more than 5(Horiz)/10(Vert) A!');
1385                     end
1386                     % Now check center chicane trims
1387                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 10) || (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 15)
1388                         error('**Setbumps caused some chicane trim magnet currents to change by more than 10(Horiz)/15(Vert) A!');
1389                     end
1390                 end
1391             end
1392
1393             %restore corrector speeds
1394             setpv('HCM', 'RampRate', HCMramprate, [], 0);
1395             setpv('VCM', 'RampRate', VCMramprate, [], 0);
1396
1397         catch
1398             fprintf('   %s \n',lasterr);
1399             fprintf('   Setbumps failed due to error condition!  Fix the problem, reload the lattice (srload), and try again.\n\n');
1400             setpv('SR_STATE',-4);
1401             set(0,'showhiddenhandles','on');
1402             [StateNumber, StateString] = getsrstate;
1403             if StateNumber >= 0
1404                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1405             else
1406                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1407             end
1408             set(0,'showhiddenhandles','off');
1409
1410             % Reset BPM timeconstant to whatever it was before correction
1411             setbpmtimeconstant(BPMtimeconstantOC);
1412             fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1413             return
1414         end
1415
1416         % Reset BPM timeconstant to whatever it was before correction
1417         setbpmtimeconstant(BPMtimeconstantOC);
1418         fprintf('   Bergoz BPM time constant set back to %.1fs\n', BPMtimeconstantOC);
1419
1420         % Turn feed forward back to it's original state
1421         if any(FFEnableBC)
1422             fprintf('   Turning feed forward back on.\n');
1423             setff([], FFEnableBC);
1424         end
1425
1426
1427         a = clock;
1428         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1429         [StateNumber, StateString] = getsrstate;
1430         set(0,'showhiddenhandles','on');
1431         if StateNumber >= 0
1432             setpv('SR_STATE',4.1);
1433             [StateNumber, StateString] = getsrstate;
1434             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1435             fprintf('   *********************************\n');
1436             fprintf('   **  Orbit Correction Complete  **\n');
1437             fprintf('   *********************************\n\n');
1438         else
1439             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1440             fprintf('   *************************************\n');
1441             fprintf('   **  Problem With Orbit Correction  **\n');
1442             fprintf('   *************************************\n\n');
1443         end
1444         set(0,'showhiddenhandles','off');
1445         pause(0);
1446
1447
1448     case 'OrbitCorrectionSetup'
1449         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
1450
1451         if InitFlag
1452             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1453             % This setup is now done in ocsinit.m %
1454             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1455             % Setup feedback elements
1456             % disp('Orbit correction condition: InitFlag=1 -- debugging message');
1457
1458             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1459             % Edit the following lists to change default configuration of Orbit Correction %
1460             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1461 %             hlist=[];vlist=[];
1462 %             for Sector =1:12
1463 %                 if Sector == 1
1464 %                     vlist = [vlist;Sector 2;Sector 4;Sector 5;Sector 8];
1465 %                     hlist = [hlist;Sector 2;Sector 7];
1466 %                 elseif Sector == 3
1467 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1468 %                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1469 %                 elseif Sector == 5
1470 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1471 %                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1472 % %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8]; %remove HCM and VCM(5,10) since corrector is not controlling starting 4-6-07
1473 % %                     hlist = [hlist;Sector 2;Sector 7];
1474 %                 elseif Sector == 10
1475 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1476 %                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1477 %                 elseif Sector == 12
1478 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 7];
1479 %                     hlist = [hlist;Sector 2;Sector 7];
1480 %                 else
1481 %                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8];
1482 %                     hlist = [hlist;Sector 2;Sector 7];
1483 %                 end
1484 %             end
1485 %             HCMlist1 = hlist;
1486 %             VCMlist1 = vlist;
1487 %
1488 %             BPMlist1 = [
1489 %                 1 2
1490 %                 1 5
1491 %                 1 6
1492 %                 1 10
1493 %                 2 1
1494 %                 2 5
1495 %                 2 6
1496 %                 2 9
1497 %                 3 2
1498 %                 3 5
1499 %                 3 6
1500 %                 3 10
1501 %                 3 11
1502 %                 3 12
1503 %                 4 1
1504 %                 4 5
1505 %                 4 6
1506 %                 4 10
1507 %                 5 1
1508 %                 5 5
1509 %                 5 6
1510 %                 5 10
1511 %                 5 11
1512 %                 5 12
1513 %                 6 1
1514 %                 6 5
1515 %                 6 6
1516 %                 6 10
1517 %                 7 1
1518 %                 7 5
1519 %                 7 6
1520 %                 7 10
1521 %                 8 1
1522 %                 8 5
1523 %                 8 6
1524 %                 8 10
1525 %                 9 1
1526 %                 9 5
1527 %                 9 6
1528 %                 9 10
1529 %                 10 1
1530 %                 10 5
1531 %                 10 6
1532 %                 10 10
1533 %                 10 11
1534 %                 10 12
1535 %                 11 1
1536 %                 11 5
1537 %                 11 6
1538 %                 11 10
1539 %                 12 1
1540 %                 12 5
1541 %                 12 6
1542 %                 12 9];
1543 %
1544 %             % SVD orbit correction
1545 %             Xivec = [1:28];
1546 %             Yivec = [1:51];
1547 %
1548 %
1549 %             % Look for bad status BPMs
1550 %             iStatus = family2status('BPMx', BPMlist1);
1551 %             iBad = find(~iStatus);
1552 %             BPMlist1 = BPMlist1(find(iStatus),:);
1553 %             if length(iBad)
1554 %                 fprintf('   Global Orbit Correction: %d BPMs removed for bad status\n', length(iBad));
1555 %                 Yivec = Yivec(1:end-length(iBad));
1556 %             end
1557 %
1558 %             iStatus = family2status('HCM', HCMlist1);
1559 %             iBad = find(~iStatus);
1560 %             HCMlist1 = HCMlist1(find(iStatus),:);
1561 %             if length(iBad)
1562 %                 fprintf('   Global Orbit Correction: %d HCMs removed for bad status\n', length(iBad));
1563 %             end
1564 %
1565 %             iStatus = family2status('VCM', VCMlist1);
1566 %             iBad = find(~iStatus);
1567 %             VCMlist1 = VCMlist1(find(iStatus),:);
1568 %             if length(iBad)
1569 %                 fprintf('   Global Orbit Correction: %d VCMs removed for bad status\n', length(iBad));
1570 %             end
1571
1572             % Initialize RFCorrFlag
1573             RFCorrFlag = 'Yes';
1574
1575             % Get the device lists from oscsinit and convert to srcontrol variables
1576             [HBPM, VBPM, HCM, VCM, HSV, VSV] = ocsinit('TopOfFill');
1577             if strcmpi(RFCorrFlag, 'Yes')
1578                 Xivec = 1:HSV+1;
1579             else
1580                 Xivec = 1:HSV;
1581             end
1582             Yivec = 1:VSV;
1583             BPMlist1 = HBPM.DeviceList;
1584             HCMlist1 = HCM.DeviceList;
1585             VCMlist1 = VCM.DeviceList;
1586
1587
1588             LocalBumplist = [
1589               % 1 1
1590               % 2 1
1591               % 3 1
1592                 4 1
1593               % 4 2
1594                 5 1
1595               % 6 1
1596               % 6 2
1597                 7 1
1598                 8 1
1599                 9 1
1600                 10 1
1601                 11 1
1602                 11 2
1603                 12 1
1604                 ];
1605             %LocalBumplist = []
1606
1607
1608         else
1609
1610             % Get vectors
1611             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1612             BPMlist1 = FB.BPMlist1;
1613             HCMlist1 = FB.HCMlist1;
1614             VCMlist1 = FB.VCMlist1;
1615             Xivec = FB.Xivec;
1616             Yivec = FB.Yivec;
1617             LocalBumplist = FB.LocalBumplist;
1618             Xgoal = FB.Xgoal;
1619             Ygoal = FB.Ygoal;
1620             RFCorrFlag = FB.RFCorrFlag;
1621
1622             % Add button to change #ivectors, CMs, IDBPMs,
1623             EditFlag = 0;
1624             h_fig1 = figure;
1625             while EditFlag ~= 8
1626
1627                 % Sensitivity matrix
1628                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
1629                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
1630
1631                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1632                 % Can the call below work for setting FOFB RF parameter? %
1633                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1634                 if strcmpi(RFCorrFlag, 'Yes')
1635                     Sx = [Sx getdisp('BPMx',BPMlist1)];
1636                 end
1637
1638                 Sx(isnan(Sx)) = 0;
1639                 Sy(isnan(Sy)) = 0;
1640
1641                 [Ux, SVx, Vx] = svd(Sx);
1642                 [Uy, SVy, Vy] = svd(Sy);
1643
1644
1645                 % Remove singular values greater than the actual number of singular values
1646                 i = find(Xivec>length(diag(SVx)));
1647                 if ~isempty(i)
1648                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
1649                     pause(0);
1650                     Xivec(i) = [];
1651                 end
1652                 i = find(Yivec>length(diag(SVy)));
1653                 if ~isempty(i)
1654                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
1655                     pause(0);
1656                     Yivec(i) = [];
1657                 end
1658
1659
1660                 Ax = Sx*Vx(:,Xivec);
1661                 Tx = inv(Ax'*Ax)*Ax';
1662
1663                 Ay = Sy*Vy(:,Yivec);
1664                 Ty = inv(Ay'*Ay)*Ay';
1665
1666
1667                 figure(h_fig1);
1668                 subplot(2,1,1);
1669                 semilogy(diag(SVx),'b');
1670                 hold on;
1671                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
1672                 ylabel('Horizontal');
1673                 title('Response Matrix Singular Values');
1674                 hold off;
1675                 subplot(2,1,2);
1676                 semilogy(diag(SVy),'b');
1677                 hold on;
1678                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
1679                 xlabel('Singular Value Number');
1680                 ylabel('Vertical');
1681                 hold off;
1682                 drawnow;
1683
1684                 if strcmp(RFCorrFlag,'No')
1685                     RFCorrState = 'NOT CORRECTED';
1686                 elseif strcmp(RFCorrFlag,'Yes')
1687                     RFCorrState = 'CORRECTED';
1688                 else
1689                     RFCorrState = '???';
1690                 end
1691
1692                 %         EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','HCM Chicane List','VCM Chicane List','IDBPM List','BBPM List','Change Golden Orbit',...
1693                 %            'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1694                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','BPM List','Change Golden Orbit',...
1695                     'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1696
1697                 if EditFlag == 1
1698                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
1699                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
1700                     titlestr='SVD Orbit Feedback';
1701                     lineNo=1;
1702                     answer=inputdlg(prompt,titlestr,lineNo,def);
1703                     if ~isempty(answer)
1704                         XivecNew = fix(str2num(answer{1}));
1705                         if isempty(XivecNew)
1706                             disp('   Horizontal E-vector cannot be empty.  No change made.');
1707                         else
1708                             if any(XivecNew<=0) || max(XivecNew)>length(diag(SVx))
1709                                 disp('   Error reading horizontal E-vector.  No change made.');
1710                             else
1711                                 Xivec = XivecNew;
1712                             end
1713                         end
1714                         YivecNew = fix(str2num(answer{2}));
1715                         if isempty(YivecNew)
1716                             disp('   Vertical E-vector cannot be empty.  No change made.');
1717                         else
1718                             if any(YivecNew<=0) || max(YivecNew)>length(diag(SVy))
1719                                 disp('   Error reading vertical E-vector.  No change made.');
1720                             else
1721                                 Yivec = YivecNew;
1722                             end
1723                         end
1724                     end
1725                 end
1726
1727                 if EditFlag == 2
1728                     List = getlist('HCM');
1729                     CheckList = zeros(size(List,1));
1730                     Elem = dev2elem('HCM', HCMlist1);
1731                     CheckList(Elem) = ones(size(Elem));
1732                     CheckList = CheckList(dev2elem('HCM',List));
1733                     newList = editlist(List, 'HCM', CheckList);
1734                     if isempty(newList)
1735                         fprintf('   Horizontal corrector magnet list cannot be empty.  No change made.\n');
1736                     else
1737                         HCMlist1 = newList;
1738                     end
1739                 end
1740
1741                 if EditFlag == 3
1742                     List = getlist('VCM');
1743                     CheckList = zeros(size(List,1));
1744                     Elem = dev2elem('VCM', VCMlist1);
1745                     CheckList(Elem) = ones(size(Elem));
1746                     CheckList = CheckList(dev2elem('VCM',List));
1747                     newList = editlist(List, 'VCM', CheckList);
1748                     if isempty(newList)
1749                         fprintf('   Vertical corrector magnet cannot be empty.  No change made.\n');
1750                     else
1751                         VCMlist1 = newList;
1752                     end
1753                 end
1754
1755                 if EditFlag == 4
1756                     ListOld = BPMlist1;
1757                     XgoalOld = Xgoal;
1758                     YgoalOld = Ygoal;
1759
1760                     % Full BPM list
1761                     List = getbpmlist('Bergoz');
1762 %                     List = [
1763 %                         1 2
1764 %                         1 5
1765 %                         1 6
1766 %                         1 10
1767 %                         2 1
1768 %                         2 5
1769 %                         2 6
1770 %                         2 9
1771 %                         3 2
1772 %                         3 5
1773 %                         3 6
1774 %                         3 10
1775 %                         3 11
1776 %                         3 12
1777 %                         4 1
1778 %                         4 5
1779 %                         4 6
1780 %                         4 10
1781 %                         5 1
1782 %                         5 5
1783 %                         5 6
1784 %                         5 10
1785 %                         5 11
1786 %                         5 12
1787 %                         6 1
1788 %                         6 5
1789 %                         6 6
1790 %                         6 10
1791 %                         7 1
1792 %                         7 5
1793 %                         7 6
1794 %                         7 10
1795 %                         8 1
1796 %                         8 5
1797 %                         8 6
1798 %                         8 10
1799 %                         9 1
1800 %                         9 5
1801 %                         9 6
1802 %                         9 10
1803 %                         10 1
1804 %                         10 5
1805 %                         10 6
1806 %                         10 10
1807 %                         10 11
1808 %                         10 12
1809 %                         11 1
1810 %                         11 5
1811 %                         11 6
1812 %                         11 10
1813 %                         12 1
1814 %                         12 5
1815 %                         12 6
1816 %                         12 9
1817 %                         ];
1818
1819                     CheckList = zeros(size(List,1),1);
1820                     if ~isempty(BPMlist1)
1821                         for i = 1:size(List,1)
1822                             k = find(List(i,1)==BPMlist1(:,1));
1823                             l = find(List(i,2)==BPMlist1(k,2));
1824
1825                             if isempty(k) || isempty(l)
1826                                 % Item not in list
1827                             else
1828                                 CheckList(i) = 1;
1829                             end
1830                         end
1831                     end
1832
1833                     newList = editlist(List, 'BPM', CheckList);
1834                     if isempty(newList)
1835                         fprintf('   BPM list cannot be empty.  No change made.\n');
1836                     else
1837                         BPMlist1 = newList;
1838                     end
1839
1840                     % Set the goal orbit to the golden orbit
1841                     Xgoal = getgolden('BPMx', BPMlist1);
1842                     Ygoal = getgolden('BPMy', BPMlist1);
1843
1844
1845                     % If a new BPM is added, then set the goal orbit to the golden orbit
1846                     for i = 1:size(BPMlist1,1)
1847
1848                         % Is it a new BPM?
1849                         k = find(BPMlist1(i,1)==ListOld(:,1));
1850                         l = find(BPMlist1(i,2)==ListOld(k,2));
1851
1852                         if isempty(k) || isempty(l)
1853                             % New BPM
1854                         else
1855                             % Use the old value for old BPM
1856                             Xgoal(i) = XgoalOld(k(l));
1857                             Ygoal(i) = YgoalOld(k(l));
1858                         end
1859                     end
1860                 end
1861
1862                 if EditFlag == 5
1863
1864                     ChangeList = editlist(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
1865                     for i = 1:size(ChangeList,1)
1866
1867                         k = find(ChangeList(i,1)==BPMlist1(:,1));
1868                         l = find(ChangeList(i,2)==BPMlist1(k,2));
1869
1870                         prompt = {sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
1871                         def = {sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
1872                         titlestr = 'CHANGE THE GOAL ORBIT';
1873                         lineNo = 1;
1874                         answer = inputdlg(prompt, titlestr, lineNo, def);
1875
1876                         if isempty(answer)
1877                             % No change
1878                             fprintf('   No change was made to the golden orbit.\n');
1879                         else
1880                             Xgoalnew = str2num(answer{1});
1881                             if isempty(Xgoalnew)
1882                                 fprintf('   No change was made to the horizontal golden orbit.\n');
1883                             else
1884                                 Xgoal(k(l)) = Xgoalnew;
1885                             end
1886
1887                             Ygoalnew = str2num(answer{2});
1888                             if isempty(Ygoalnew)
1889                                 fprintf('   No change was made to the vertical golden orbit.\n');
1890                             else
1891                                 Ygoal(k(l)) = Ygoalnew;
1892                             end
1893                         end
1894                     end
1895                     if ~isempty(ChangeList)
1896                         fprintf('   Note:  changing the goal orbit for "Orbit Correction" does not change the goal orbit for "Slow Orbit Feedback."\n');
1897                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
1898                     end
1899                 end
1900
1901                 if EditFlag == 6
1902                     List = [
1903                         1 1
1904                         2 1
1905                         3 1
1906                         4 1
1907                         4 2
1908                         5 1
1909                         6 1
1910                         6 2
1911                         7 1
1912                         8 1
1913                         9 1
1914                         10 1
1915                         11 1
1916                         11 2
1917                         12 1];
1918                     CheckList = zeros(size(List,1),1);
1919                     if ~isempty(LocalBumplist)
1920                         for i = 1:size(List,1)
1921                             k = find(List(i,1)==LocalBumplist(:,1));
1922                             l = find(List(i,2)==LocalBumplist(k,2));
1923
1924                             if isempty(k) || isempty(l)
1925                                 % Item not in list
1926                             else
1927                                 CheckList(i) = 1;
1928                             end
1929                         end
1930                     end
1931                     LocalBumplist = editlist2(List, 'Sector', CheckList);
1932                 end
1933
1934                 if EditFlag == 7
1935                     RFCorrFlag = questdlg(sprintf('Set RF Frequency during Orbit Correction?'),'RF Frequency','Yes','No', 'No');
1936                     if strcmp(RFCorrFlag,'No')
1937                         disp(['   RF Frequency will not be included in global orbit correction.']);
1938                     elseif strcmp(RFCorrFlag,'Yes')
1939                         disp(['   RF Frequency will be included in global orbit correction.']);
1940                     end
1941
1942                 end
1943             end
1944             close(h_fig1);
1945         end
1946
1947         %  ORBIT CORRECTION STRUCTURE (OCS)
1948         %    OCS.BPM (data structure)
1949         %    OCS.CM  (data structure)
1950         %    OCS.GoalOrbit
1951         %    OCS.NIter
1952         %    OCS.SVDIndex
1953         %    OCS.IncrementalFlag = 'Yes'/'No'
1954         %    OCS.BPMWeight
1955         %    OCS.Flags = { 'FitRF' , etc. }
1956         OCSx.BPM = getx(BPMlist1, 'struct');
1957         OCSx.CM = getsp('HCM', HCMlist1, 'struct');
1958         OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
1959         OCSx.NIter = 1;
1960         OCSx.SVDIndex = Xivec;
1961         OCSx.IncrementalFlag = 'No';
1962         OCSx.FitRF = 1;
1963         OCSy.BPM = gety(BPMlist1, 'struct');
1964         OCSy.CM = getsp('VCM', VCMlist1, 'struct');
1965         OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
1966         OCSy.NIter = 1;
1967         OCSy.SVDIndex = Yivec;
1968         OCSy.IncrementalFlag = 'No';
1969         OCSy.FitRF = 0;
1970
1971         % Save vectors
1972         FB.OCSx = OCSx;
1973         FB.OCSy = OCSy;
1974
1975         FB.BPMlist1 = BPMlist1;
1976         FB.HCMlist1 = HCMlist1;
1977         FB.VCMlist1 = VCMlist1;
1978         FB.Xivec = Xivec;
1979         FB.Yivec = Yivec;
1980         FB.Xgoal = OCSx.GoalOrbit;
1981         FB.Ygoal = OCSy.GoalOrbit;
1982         FB.RFCorrFlag = RFCorrFlag;
1983         FB.LocalBumplist = LocalBumplist;
1984         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata',FB);
1985
1986
1987     case 'Feedback'
1988
1989         FBloopIter = 1;
1990         if get(findobj(gcbf,'Tag','SRCTRLCheckboxFOFB'),'Value') == 1
1991             StartFOFBFlag = 1;
1992         else
1993             StartFOFBFlag = 0;
1994         end
1995
1996         FEEDBACK_STOP_FLAG = 0;
1997         HWarnNum=0;
1998         VWarnNum=0;
1999
2000         SR_GeV = getenergy;
2001         % Feedback loop setup
2002         PlotInfoFlag = 0;           % Plot micado stuff
2003         LoopDelay = 1.0;           % Period of feedback loop [seconds], make sure the BPM averaging is correct
2004         VCM_LSB = .00366211;
2005         VCMCHICANE_LSB = .002441;   % 80 max?,  Note: not fully implemented
2006
2007         if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
2008             Xgain  = 0.2;
2009             Ygain  = 0.1;
2010         else
2011             Xgain  = 0.8; % raised 0.5->0.8 at 17:20, 3-2-05 to more quickly correct EPU4 fast switching orbit distortions
2012             Ygain  = 0.8;
2013         end
2014
2015         % Load lattice set for tune feed forward
2016         ConfigSetpoint = getproductionlattice;
2017         %load([getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile')]);
2018         QFsp = ConfigSetpoint.QF.Setpoint.Data;
2019         QDsp = ConfigSetpoint.QD.Setpoint.Data;
2020         TuneW16Min = gap2tune([5 1], 13.23, 1.8909);
2021         % Tune response matrix
2022         SR_TUNE_MATRIX = gettuneresp({'QF','QD'}, {[],[]}, getenergy('Production'));    % Approx. [0.1944 -0.0286;-0.1182 0.1526];
2023         %SR_TUNE_MATRIX = [0.1641 -0.0245
2024         %                 -0.1149 0.1477];
2025
2026         SQSFsp = amp2k('SQSF','Setpoint',ConfigSetpoint.SQSF.Setpoint.Data);
2027         SQSDsp = amp2k('SQSD','Setpoint',ConfigSetpoint.SQSD.Setpoint.Data);
2028
2029 %         % tune FF for EPUs (data exist for 4 1 parallel, 11 1 parallel and antiparallel
2030 %         load '/home/als/physdata/matlab/srdata/gaptrack/EPU4-1_tunecomp/after_shimming/nux_map_withgaps.mat'
2031 %         dnux_epu_41_m0 = tunexmap(2:end,2:end)-tunexmap(2,12);
2032 %         [gap_epu_41,shift_epu_41]=meshgrid(tunexmap(2:end,1),tunexmap(1,2:end));
2033 %         load '/home/als/physdata/matlab/srdata/gaptrack/EPU4-1_tunecomp/after_shimming/nuy_map_withgaps.mat'
2034 %         dnuy_epu_41_m0 = tuneymap(2:end,2:end)-tuneymap(2,12);
2035 %
2036 %         load '/home/als/physdata/matlab/srdata/gaptrack/archive/epu11d1m0e19_2007-01-28.mat' tune_x tune_y Gaps GapsLongitudinal
2037 %         dnux_epu_111_m0 = tune_x-tune_x(1,11);
2038 %         [gap_epu_111,shift_epu_111]=meshgrid(Gaps,GapsLongitudinal);
2039 %         dnuy_epu_111_m0 = tune_y-tune_y(1,11);
2040 %         load '/home/als/physdata/matlab/srdata/gaptrack/archive/epu11d1m1e19_2007-01-28.mat' tune_x tune_y Gaps GapsLongitudinal
2041 %         dnux_epu_111_m1 = tune_x-tune_x(1,11);
2042 %         dnuy_epu_111_m1 = tune_y-tune_y(1,11);
2043
2044         % tune FF for EPUs (data exist for 4 1 parallel, 11 1 parallel and antiparallel
2045         load '/home/als/physdata/matlab/srdata/epu/tuneshift_2d_tables/epu_tunetables_2d_20070723.mat'
2046         dnux41p = nux41p-nux41p(1,11);
2047         dnuy41p = nuy41p-nuy41p(1,11);
2048         dnux41a = nux41a-nux41a(1,11);
2049         dnuy41a = nuy41a-nuy41a(1,11);
2050         dnux111p = nux111p-nux111p(1,11);
2051         dnuy111p = nuy111p-nuy111p(1,11);
2052         dnux111a = nux111a-nux111a(1,11);
2053         dnuy111a = nuy111a-nuy111a(1,11);
2054         dnux112p = nux112p-nux112p(1,11);
2055         dnuy112p = nuy112p-nuy112p(1,11);
2056         dnux112a = nux112a-nux112a(1,11);
2057         dnuy112a = nuy112a-nuy112a(1,11);
2058
2059         % ID tune compensation does not work in the injection lattice, so ...
2060         if abs(SR_GEV - bend2gev)>  0.05     % Don't use this routine for the injection lattice
2061             fprintf('   This routine should only be used for the production energy: Orbit feedback aborted\n');
2062             return
2063         end
2064
2065         set(0,'showhiddenhandles','on');
2066
2067         try
2068             fprintf('\n');
2069             fprintf('   *******************************\n');
2070             fprintf('   **  Starting Orbit Feedback  **\n');
2071             fprintf('   *******************************\n');
2072             a = clock;
2073             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2074             fprintf('   Note: the Matlab command window will be used to display status information.\n');
2075             fprintf('         It cannot be used to enter commands during slow orbit feedback.\n');
2076
2077
2078                 % save current BPM timeconstant - will reset to this when feedback stops
2079                 BPMtimeconstantOFB = getbpmtimeconstant;
2080                 fprintf('   Current Bergoz BPM time constant is %.1fs\n', BPMtimeconstantOFB);
2081
2082             % >= 2 Hz update rate on IDBPMs
2083             disp('   Bergoz BPM time constant set to 0.2s.')
2084             setbpmtimeconstant(0.2)
2085             pause(1.1);
2086
2087             % Check whether bumps and kickers are on and warn to turn off before starting feedback if necessary
2088             try
2089                 if (getsp('SR01S___BUMP1__BC21')==1 && getsp('SR01S___BUMP1P_BC22')==1) || (getsp('SR01S___SEK____BC21')==1 && getsp('SR01S___SEK_P__BC23')==1) || (getsp('SR01S___SEN____BC20')==1 && getsp('SR01S___SEN_P__BC22')==1)
2090                     soundtada;
2091                     fprintf('   \n');
2092                     fprintf('   *********************************************************************************\n');
2093                     fprintf('   ** One or more of the pulsed SR injection magnets is still on!  Turn them off! **\n');
2094                     fprintf('   *********************************************************************************\n');
2095                     fprintf('   \n');
2096                 end
2097             catch
2098                 disp('**Problem checking the state of the bumps and kickers - please check that they are not pulsing.');
2099             end
2100
2101             % Get vectors
2102
2103             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
2104
2105             BPMlist1 = FB.OCSx.BPM.DeviceList;
2106             % FOFB_BPMlist =
2107             HCMlist1 = FB.HCMlist1;
2108             VCMlist1 = FB.VCMlist1;
2109             Xivec = FB.Xivec;
2110             Yivec = FB.Yivec;
2111             Xgoal = FB.OCSx.GoalOrbit;
2112             Ygoal = FB.OCSy.GoalOrbit;
2113             FFTypeFlag = FB.FFTypeFlag;   %local or global tune correction
2114
2115             iNotHCMChicane = find(HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
2116             iHCMChicane = find(HCMlist1(:,2) == 10);
2117             iNotVCMChicane = find(VCMlist1(:,2) < 10);
2118             iVCMChicane = find(VCMlist1(:,2) == 10);
2119
2120             % Sensitivity matrix for setting fast feedback setpoints
2121             Sx1 = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
2122             Sy1 = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
2123
2124         catch
2125             fprintf('\n  %s \n',lasterr);
2126
2127             % Reset Bergoz BPM time constant to whatever it was before feedback started
2128             fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
2129             setbpmtimeconstant(BPMtimeconstantOFB);
2130
2131
2132             a = clock;
2133             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2134             fprintf('   *************************************************************\n');
2135             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
2136             fprintf('   *************************************************************\n\n');
2137             set(0,'showhiddenhandles','off');
2138             pause(0);
2139
2140             return
2141         end
2142
2143         StartFlag = questdlg(strvcat('','Is it OK to start orbit feedback?'),'Orbit Feedback','Yes','No','No');
2144         if strcmp(StartFlag,'No')
2145             % Reset Bergoz BPM time constant to whatever it was before feedback started
2146             fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
2147             setbpmtimeconstant(BPMtimeconstantOFB);
2148
2149             a = clock;
2150             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2151             fprintf('   ***************************\n');
2152             fprintf('   **  Orbit Feedback Exit  **\n');
2153             fprintf('   ***************************\n\n');
2154             pause(0);
2155             return
2156         end
2157
2158         SR_STATE_OLD = scaget('SR_STATE');
2159         setpv('SR_STATE', 5);
2160         set(0,'showhiddenhandles','on');
2161         [StateNumber, StateString] = getsrstate;
2162         if StateNumber >= 0
2163             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2164         else
2165             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2166         end
2167         fprintf('   Using %d E-vectors horizontally.\n', length(Xivec));
2168         fprintf('   Using %d E-vectors vertically.\n',   length(Yivec));
2169         fprintf('   Starting slow orbit correction every %.1f seconds.\n', LoopDelay);
2170         %  fprintf('   Resetting SR11 chicane motors every 20 seconds to fix drift problem.\n');
2171
2172         IDSector = getlist('ID');
2173         EPUlist = find((IDSector(:,1)==4) | (IDSector(:,1)==11));
2174         oldgap=210*ones(size(IDSector,1),1);
2175         oldShift=zeros(size(oldgap));
2176
2177         try
2178
2179             % Get and display data
2180             x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
2181             y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
2182             STDx = norm(x)/sqrt(length(x));
2183             STDy = norm(y)/sqrt(length(y));
2184             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
2185             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
2186
2187             % write goldenorbit values to Fast Orbit Feedback
2188             try
2189                 write_goldenorbit_ffb;
2190             catch
2191                 disp('write_goldenorbit_ffb did not work!');
2192             end
2193             setpv('SR01____FFBON__BC00',2);
2194             %pause(0);
2195
2196             %display state of FOFB system
2197             FOFBStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2198                 getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2199                 getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2200                 getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2201             FOFBStatusStr = ['    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    ';'    '];
2202             for loop = 1:size(FOFBStatus,2)
2203                 if FOFBStatus(loop)==0
2204                     FOFBStatusStr(loop,:) = 'OFF ';
2205                 elseif FOFBStatus(loop)==1
2206                     FOFBStatusStr(loop,:) = 'ON  ';
2207                 elseif FOFBStatus(loop)==2
2208                     FOFBStatusStr(loop,:) = 'OPEN';
2209                 else
2210                     FOFBStatusStr(loop,:) = 'BAD ';
2211                 end
2212             end
2213             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 %s',FOFBStatusStr(1,:)),'ForegroundColor',[0 0 0]);
2214             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 %s',FOFBStatusStr(2,:)),'ForegroundColor',[0 0 0]);
2215             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 %s',FOFBStatusStr(3,:)),'ForegroundColor',[0 0 0]);
2216             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 %s',FOFBStatusStr(4,:)),'ForegroundColor',[0 0 0]);
2217             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 %s',FOFBStatusStr(5,:)),'ForegroundColor',[0 0 0]);
2218             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 %s',FOFBStatusStr(6,:)),'ForegroundColor',[0 0 0]);
2219             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 %s',FOFBStatusStr(7,:)),'ForegroundColor',[0 0 0]);
2220             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 %s',FOFBStatusStr(8,:)),'ForegroundColor',[0 0 0]);
2221             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 %s',FOFBStatusStr(9,:)),'ForegroundColor',[0 0 0]);
2222             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 %s',FOFBStatusStr(10,:)),'ForegroundColor',[0 0 0]);
2223             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 %s',FOFBStatusStr(11,:)),'ForegroundColor',[0 0 0]);
2224             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 %s',FOFBStatusStr(12,:)),'ForegroundColor',[0 0 0]);
2225
2226         catch
2227
2228             fprintf('\n  %s \n',lasterr);
2229
2230             % Reset Bergoz BPM time constant to whatever it was before feedback started
2231             fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
2232             setbpmtimeconstant(BPMtimeconstantOFB);
2233
2234
2235             a = clock;
2236             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2237             fprintf('   *************************************************************\n');
2238             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
2239             fprintf('   *************************************************************\n\n');
2240
2241             setpv('SR_STATE',SR_STATE_OLD);
2242             [StateNumber, StateString] = getsrstate;
2243             if StateNumber >= 0
2244                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2245             else
2246                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2247             end
2248             set(0,'showhiddenhandles','off');
2249             pause(0);
2250
2251             return
2252
2253         end
2254
2255
2256         % Disable buttons
2257         set(0,'showhiddenhandles','on');
2258         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','off');
2259         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','on');
2260         set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','off');
2261         set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','off');
2262         set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','off');
2263         set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','off');
2264         set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','off');
2265         set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','off');
2266         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','off');
2267         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','off');
2268         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','off');
2269         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','off');
2270         set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','off');
2271         pause(0);
2272
2273
2274         % Initialize feedback loop
2275         StartTime = gettime;
2276         StartErrorTime = gettime;
2277         Xold = getx(FB.OCSx.BPM.DeviceList);
2278         Yold = gety(FB.OCSy.BPM.DeviceList);
2279         HQMOFM_stalenum = 0;
2280         pause(LoopDelay);
2281
2282         N_HCM = size(HCMlist1,1);
2283         N_VCM = size(VCMlist1,1);
2284
2285         N_RFMO = 1;
2286
2287         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2288             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'SetRF','Nodisplay','Nosetsp');
2289         else
2290             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
2291         end
2292         [FB.OCSx, Smatx, Sx, Ux, Vx] = orbitcorrectionmethods(FB.OCSx);
2293
2294         [FB.OCSy, junk, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
2295         [FB.OCSy, Smaty, Sy, Uy, Vy] = orbitcorrectionmethods(FB.OCSy);
2296
2297
2298         %%%%%%%%%%%%%%%%%%%%%%%
2299         % Start feedback loop %
2300         %%%%%%%%%%%%%%%%%%%%%%%
2301
2302         % chicaneloop=1;  % loop variable for resetting drifting chicanes (see a few lines below)
2303         % fftest=figure;
2304
2305         setpv('SR01____FFBON__BC00',2); % put FOFB in open loop so beamnoise gets recorded even if FOFB is not enabled
2306
2307         while 1
2308             try
2309                 t00 = gettime;
2310
2311                 %          if chicaneloop==20 % reset SR11 motor chicane setpoints every 20s due to drifting positions
2312                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(6),[11 1],0);
2313                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(7),[11 2],0);
2314                 %             chicaneloop = 1;
2315                 %          else
2316                 %             chicaneloop = chicaneloop + 1;
2317                 %          end
2318
2319                 % Check if GUI has been closed
2320                 if isempty(gcbf)
2321                     FEEDBACK_STOP_FLAG = 1;
2322                     lasterr('SRCONTROL GUI DISAPPEARED!');
2323                     error('SRCONTROL GUI DISAPPEARED!');
2324                 end
2325
2326                 %%%%%%%%%%%%%%%%%%%%%%%
2327                 % Fast orbit feedback %
2328                 %%%%%%%%%%%%%%%%%%%%%%%
2329                 if StartFOFBFlag == 1 && FBloopIter > 3
2330                     setpv('SR01____FFBON__BC00',2);
2331                     pause(0.5);
2332                     setpv('SR01____FFBON__BC00',1);
2333                     StartFOFBFlag = 0;
2334                     pause(1);
2335                     FOFBOnStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2336                         getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2337                         getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2338                         getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2339                     if any(FOFBOnStatus==0) || any(FOFBOnStatus==2)
2340                         setpv('SR01____FFBON__BC00',2); % open FOFB loop
2341                         disp('************************************************************************************************************');
2342                         disp('** Problem turning on Fast Orbit Feedback system...                                                       **');
2343                         disp('** Check status of ffbsecXX crates - but remember that a crate reboot will turn off Quads in that sector! **');
2344                         disp('** Suggest disabling the "Fast Orbit Correction" checkbox and starting Orbit Feedback again.              **');
2345                         disp('************************************************************************************************************');
2346                     else
2347                         fprintf('   Starting Fast Orbit Feedback at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
2348                     end
2349                 end
2350
2351
2352                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2353                 % Horizontal plane "feedback" %
2354                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2355
2356                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxSOFB'),'Value') == 1
2357
2358                     % Get orbit and check that the BPMs are different from the last update
2359                     Xnew = getx(FB.OCSx.BPM.DeviceList);
2360
2361                     % Don't feedback if the current is too small
2362                     if getdcct < 2
2363                         FEEDBACK_STOP_FLAG = 1;
2364                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2365                         break;
2366                     end
2367
2368                     x = Xgoal - Xnew;
2369                     STDx = norm(x)/sqrt(length(x));
2370
2371                     if any(Xold == Xnew)
2372                         a = clock;
2373                         N_Stale_Data_Points = find((Xold==Xnew)==1);
2374                         for loop = N_Stale_Data_Points'
2375                             fprintf('   Stale data: BPMx(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSx.BPM.DeviceList(loop,1), FB.OCSx.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2376                         end
2377                     else
2378                         % Compute horizontal correction
2379                         %%%OCSx0 = FB.OCSx;
2380                         FB.OCSx.BPM.Data = Xnew;
2381                         FB.OCSx = orbitcorrectionmethods(FB.OCSx, Smatx, Sx, Ux, Vx);
2382
2383                         %%%[FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
2384
2385                         % reduced feedback gain (implemented by Greg Portmann, December 2000)
2386                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2387                         % increased back to 0.8 C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2388                         % increased to 1.0, C. Steier, 2002-05-04, trim DACs
2389                                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2390                                 % should probably actively allocate X's size to prevent possible memory leak %
2391                                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2392                         X = [Xgain .* FB.OCSx.CM.Delta; 0.3*FB.OCSx.DeltaRF/4.988e-3];
2393
2394                         %%%X = Xgain .* (FB.OCSx.CM.Data - OCSx0.CM.Data);
2395
2396                         % check corrector trim values + next step values, warn or stop FB as necessary
2397                         HCMtrimSP=getpv('HCM','Trim',HCMlist1);
2398                         HCMtrimSP_next = HCMtrimSP + X(1:N_HCM);
2399                         if max(abs(HCMtrimSP_next)) > 4
2400                             HCMtrimnum=find(abs(HCMtrimSP_next) > 4);
2401
2402                             % print message to screen
2403                             fprintf('\n');
2404                             fprintf('***One or more of the horizontal correctors is at its maximum!! Stopping orbit feedback. \n');
2405                             fprintf('   %s\n',datestr(now));
2406                             for loop = HCMtrimnum'
2407                                 fprintf('***%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2408                             end
2409
2410                             % send alphapage to operator pager
2411                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2412                             FEEDBACK_STOP_FLAG = 1;
2413
2414                             setpv('SR_STATE', -5);
2415                             [StateNumber, StateString] = getsrstate;
2416                             if StateNumber >= 0
2417                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2418                             else
2419                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2420                             end
2421                         end
2422
2423                         % check chicane trim coil values + next step values, warn or stop FB as necessary
2424                         HCMCHICANEtrimSP=getpv('HCM','Setpoint',HCMlist1(iHCMChicane,:));
2425                         HCMCHICANEtrimSP_next = HCMCHICANEtrimSP + X(iHCMChicane);
2426                         if max(abs(HCMCHICANEtrimSP_next)) > 19.9
2427                             HCMCHICANEtrimnum=find(abs(HCMCHICANEtrimSP_next) > 19.9);
2428
2429                             % print message to screen
2430                             fprintf('\n');
2431                             fprintf('***One or more of the horizontal chicane trim coil correctors is at its maximum!! Stopping orbit feedback. \n');
2432                             fprintf('   %s\n',datestr(now));
2433                             for loop = HCMCHICANEtrimnum'
2434                                 fprintf('***%s is one of the problem correctors.\n',getname('HCM','Setpoint',HCMlist1(iHCMChicane(loop,:),:)));
2435                             end
2436                             fprintf('***Maybe try resetting the setpoints of the motor chicanes in case they are drifting...\n');
2437
2438                             % send alphapage to operator pager
2439                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2440                             FEEDBACK_STOP_FLAG = 1;
2441
2442                             setpv('SR_STATE', -5);
2443                             [StateNumber, StateString] = getsrstate;
2444                             if StateNumber >= 0
2445                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2446                             else
2447                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2448                             end
2449                         end
2450
2451                         if FEEDBACK_STOP_FLAG == 1
2452                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2453                             if getpv('SR01____FFBON__BC00')==1
2454                                 disp('   Stopping Fast Orbit Feedback.');
2455                             end
2456                             setpv('SR01____FFBON__BC00',0);
2457                             pause(0.5);
2458                             setpv('SR01____FFBON__BC00',2);
2459                             break;
2460                         end
2461
2462                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2463                         pause(0);
2464
2465                         if max(abs(HCMtrimSP_next) > 3)
2466                             HCMtrimnum=find(abs(HCMtrimSP_next) > 3);
2467                             HWarnNum=HWarnNum+1;
2468                             if (HWarnNum==1 || rem(HWarnNum,120)==0)
2469
2470                                 % print message to screen every two minutes
2471                                 fprintf('\n');
2472                                 fprintf('***One or more of the horizontal corrector trims is above 3A or below -3A! \n');
2473                                 fprintf('   %s\n',datestr(now));
2474                                 for loop = HCMtrimnum'
2475                                     fprintf('***%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2476                                 end
2477                                 fprintf('***The orbit feedback is still working but this problem should be investigated. \n');
2478
2479                                 %send alphapage to operator pager the first time then at 10 minutes
2480                                 if (HWarnNum==1 || HWarnNum==600)
2481                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageHCM.txt
2482                                 end
2483                             end
2484                         elseif max(abs(HCMCHICANEtrimSP_next) > 15)
2485                             HCMCHICANEtrimnum=find(abs(HCMCHICANEtrimSP_next) > 15);
2486                             HWarnNum=HWarnNum+1;
2487                             if (HWarnNum==1 || rem(HWarnNum,120)==0)
2488
2489                                 % print message to screen every two minutes
2490                                 fprintf('\n');
2491                                 fprintf('***One or more of the horizontal chicane corrector trim coils is above 15A or below -15A! \n');
2492                                 fprintf('   %s\n',datestr(now));
2493                                 for loop = HCMCHICANEtrimnum'
2494                                     fprintf('***%s is one of the problem correctors.\n',getname('HCM','Setpoint',HCMlist1(iHCMChicane(loop,:),:)));
2495                                 end
2496                                 fprintf('***The orbit feedback is still working but this problem should be investigated. \n');
2497
2498                                 %reset motor chicanes in case they are drifting
2499                                 try
2500                                     %                                     if HCMCHICANEtrimnum(1)==1
2501                                     %                                         if HCMCHICANEtrimSP_next(1)>15
2502                                     %                                             steppv('HCMCHICANEM',-0.5,[4 1;4 2]);
2503                                     %                                         elseif HCMCHICANEtrimSP_next(1)<(-15)
2504                                     %                                             steppv('HCMCHICANEM',0.5,[4 1;4 2]);
2505                                     %                                         end
2506                                     %                                     end
2507                                     fprintf('   Resetting the setpoints of the motor chicanes in case they are drifting...\n');
2508                                     setpv('HCMCHICANEM','Setpoint',ConfigSetpoint.HCMCHICANEM.Setpoint.Data,[],0);
2509                                 catch
2510                                 end
2511
2512                                 %send alphapage to operator pager the first time then at 10 minutes
2513                                 if (HWarnNum==1 || HWarnNum==600)
2514                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageHCMCHICANE.txt
2515                                 end
2516                             end
2517                         else
2518                             HWarnNum=0;
2519                         end
2520
2521                         % Don't feedback if the current is too small
2522                         if getdcct < 2
2523                             FEEDBACK_STOP_FLAG = 1;
2524                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2525                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2526                             break;
2527                         end
2528
2529                         if N_HCM > 0
2530                             steppv('HCM','Trim', X(iNotHCMChicane), HCMlist1(iNotHCMChicane,:), 0);
2531                             steppv('HCM','Setpoint', X(iHCMChicane), HCMlist1(iHCMChicane,:), 0);
2532                         end
2533
2534                         % write fast orbit feedback setpoints
2535                         if 1
2536                             %write_goldenorbit_ffb_2planes(1, Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM)+Sx3*X(length(X))/20, BPMlist1);
2537                             % should be corrected to include result of next frequency step ...
2538                             write_goldenorbit_ffb_2planes(1,Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM),BPMlist1);
2539                         end
2540
2541                         %fprintf('Horizontal Done: %f \n',gettime-t00);
2542
2543                         % RF feedback
2544                         HQMOFMsp_last = getpv('EG______HQMOFM_AC01');
2545
2546                         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2547                             if N_RFMO > 0
2548                                 if abs(X(end)) < .01
2549                                     % if abs(FB.OCSx.DeltaRF/3) < .01
2550                                     steppv('EG______HQMOFM_AC01', X(end));
2551                                 else
2552                                     steppv('EG______HQMOFM_AC01', 0.01*sign(X(end)));
2553                                 end
2554                             end
2555
2556                             HQMOFMsp_now = getpv('EG______HQMOFM_AC01');
2557
2558                             % Check for stale RF feedback
2559                             if HQMOFMsp_last == HQMOFMsp_now
2560                                 HQMOFM_stalenum = HQMOFM_stalenum + 1;
2561                                 if HQMOFM_stalenum == 30 % warn and message to pager if stale for 30 secs
2562                                     fprintf('\n');
2563                                     fprintf('***The RF is not responding to orbit feedback changes! \n');
2564                                     fprintf('   %s\n',datestr(now));
2565                                     fprintf('***The orbit feedback is still working but this problem should be investigated. \n');
2566                                     fprintf('***ILC 73 controls the EG______HQMOFM_AC01 channel, which sets the RF frequency. \n');
2567                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstaleRFmessage.txt
2568                                 end
2569                                 if rem(HQMOFM_stalenum,120)==0 % message to screen every 2 minutes
2570                                     fprintf('\n');
2571                                     fprintf('***The RF is not responding to orbit feedback changes! (%s)\n',datestr(now));
2572                                 end
2573                             else
2574                                 HQMOFM_stalenum = 0;
2575                             end
2576
2577                         end
2578
2579                         %fprintf('RF Done: %f \n',gettime-t00);
2580
2581                         Xold = Xnew;
2582                     end % End horizontal correction
2583
2584
2585                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2586                     % Vertical plane "feedback" %
2587                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2588
2589                     % Get orbit and check that the BPMs are different from the last update
2590                     Ynew = gety(FB.OCSy.BPM.DeviceList);
2591
2592                     % Don't feedback if the current is too small
2593                     if getdcct < 2
2594                         FEEDBACK_STOP_FLAG = 1;
2595                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2596                         break;
2597                     end
2598
2599                     y = Ygoal - Ynew;
2600                     STDy = norm(y)/sqrt(length(y));
2601
2602                     if any(Yold == Ynew)
2603                         a = clock;
2604                         N_Stale_Data_Points = find((Yold==Ynew)==1);
2605                         for loop = N_Stale_Data_Points'
2606                             fprintf('   Stale data: BPMy(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSy.BPM.DeviceList(loop,1), FB.OCSy.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2607                         end
2608
2609                     else
2610
2611                         % Compute vertical correction
2612                         %%%OCSy0 = FB.OCSy;
2613                         FB.OCSy.BPM.Data = Ynew;
2614                         FB.OCSy = orbitcorrectionmethods(FB.OCSy, Smaty, Sy, Uy, Vy);
2615
2616                         %%%[FB.OCSy, RF, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
2617
2618                         % reduced feedback gain, C. Steier, 2001-03-25
2619                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2620                         % increased back to 0.8, C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2621                         % set to unity gain, C. Steier, 2002-05-04, trim DACs
2622                         Y = Ygain .* FB.OCSy.CM.Delta;
2623                         %%%Y = Ygain .* (FB.OCSy.CM.Data - OCSy0.CM.Data);
2624
2625                         % Just SVD correction
2626                         % warning('Not using "micado" correction in the vertical plane.');
2627
2628                         % check for trim values+next step values, warn or stop FB as necessary
2629                         VCMtrimSP = getpv('VCM','Trim',VCMlist1);
2630                         VCMtrimSP_next = VCMtrimSP + Y(1:N_VCM);
2631                         if max(abs(VCMtrimSP_next)) > 12
2632                             VCMtrimnum=find(abs(VCMtrimSP_next) > 12);
2633
2634                             % print message to screen
2635                             fprintf('\n');
2636                             fprintf('***One or more of the vertical correctors is at its maximum!! Stopping orbit feedback. \n');
2637                             fprintf('   %s\n',datestr(now));
2638                             for loop = VCMtrimnum'
2639                                 fprintf('***%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2640                             end
2641
2642                             % send alphapage to operator pager
2643                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2644                             FEEDBACK_STOP_FLAG = 1;
2645
2646                             setpv('SR_STATE', -5);
2647                             [StateNumber, StateString] = getsrstate;
2648                             if StateNumber >= 0
2649                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2650                             else
2651                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2652                             end
2653                         end
2654
2655                         % check chicane trim coil values + next step values, warn or stop FB as necessary
2656                         VCMCHICANEtrimSP=getpv('VCM','Setpoint',VCMlist1(iVCMChicane,:));
2657                         VCMCHICANEtrimSP_next = VCMCHICANEtrimSP + Y(iVCMChicane);
2658                         if max(abs(VCMCHICANEtrimSP_next)) > 19.9
2659                             VCMCHICANEtrimnum=find(abs(VCMCHICANEtrimSP_next) > 19.9);
2660
2661                             % print message to screen
2662                             fprintf('\n');
2663                             fprintf('***One or more of the vertical chicane trim coil correctors is at its maximum!! Stopping orbit feedback. \n');
2664                             fprintf('   %s\n',datestr(now));
2665                             for loop = VCMCHICANEtrimnum'
2666                                 fprintf('***%s is one of the problem correctors.\n',getname('VCM','Setpoint',VCMlist1(iVCMChicane(loop,:),:)));
2667                             end
2668                             fprintf('***Maybe try resetting the setpoints of the motor chicanes in case they are drifting...\n');
2669
2670                             % send alphapage to operator pager
2671                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2672                             FEEDBACK_STOP_FLAG = 1;
2673
2674                             setpv('SR_STATE', -5);
2675                             [StateNumber, StateString] = getsrstate;
2676                             if StateNumber >= 0
2677                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2678                             else
2679                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2680                             end
2681                         end
2682
2683                         if FEEDBACK_STOP_FLAG == 1
2684                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2685                             if getpv('SR01____FFBON__BC00')==1
2686                                 disp('   Stopping Fast Orbit Feedback.');
2687                             end
2688                             setpv('SR01____FFBON__BC00',0);
2689                             pause(0.5);
2690                             setpv('SR01____FFBON__BC00',2);
2691                             break;
2692                         end
2693
2694                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2695                         % pause(0);
2696
2697                         if max(abs(VCMtrimSP_next) > 8) % changed from 6A ~12/1/07 since orbit FB is going past 6A
2698                             VCMtrimnum=find(abs(VCMtrimSP_next) > 8);
2699                             VWarnNum=VWarnNum+1;
2700                             if (VWarnNum==1 || rem(VWarnNum,120)==0)
2701
2702                                 % print message to screen every two minutes
2703                                 fprintf('\n');
2704                                 fprintf('***One or more of the vertical corrector trims is above 8A or below -8A! \n');
2705                                 fprintf('   %s\n',datestr(now));
2706                                 for loop = VCMtrimnum'
2707                                     fprintf('***%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2708                                 end
2709                                 fprintf('***The orbit feedback is still working but this problem should be investigated. \n');
2710
2711                                 %send alphapage to operator pager the first time then at 10 minutes
2712                                 if (VWarnNum==1 || VWarnNum==600)
2713                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageVCM.txt
2714                                 end
2715                             end
2716                         elseif max(abs(VCMCHICANEtrimSP_next) > 15)
2717                             VCMCHICANEtrimnum=find(abs(VCMCHICANEtrimSP_next) > 15);
2718                             VWarnNum=VWarnNum+1;
2719                             if (VWarnNum==1 || rem(VWarnNum,120)==0)
2720
2721                                 % print message to screen every two minutes
2722                                 fprintf('\n');
2723                                 fprintf('***One or more of the vertical chicane corrector trim coils is above 15A or below -15A! \n');
2724                                 fprintf('   %s\n',datestr(now));
2725                                 for loop = VCMCHICANEtrimnum'
2726                                     fprintf('***%s is one of the problem correctors.\n',getname('VCM','Setpoint',VCMlist1(iVCMChicane(loop,:),:)));
2727                                 end
2728                                 fprintf('***The orbit feedback is still working but this problem should be investigated. \n');
2729
2730                                 %reset motor chicanes in case they are drifting
2731                                 try
2732                                         fprintf('  Resetting the setpoints of the motor chicanes in case they are drifting...\n');
2733                                         setpv('HCMCHICANEM','Setpoint',ConfigSetpoint.HCMCHICANEM.Setpoint.Data,[],0);
2734                                 catch
2735                                 end
2736
2737                                 %send alphapage to operator pager the first time then at 10 minutes
2738                                 if (VWarnNum==1 || VWarnNum==600)
2739                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageVCMCHICANE.txt
2740                                 end
2741                             end
2742                         else
2743                             VWarnNum=0;
2744                         end
2745
2746                         % Don't feedback if the current is too small
2747                         if getdcct < 2
2748                             FEEDBACK_STOP_FLAG = 1;
2749                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2750                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2751                             break;
2752                         end
2753
2754                         if N_VCM > 0
2755                             steppv('VCM','Trim', Y(iNotVCMChicane), VCMlist1(iNotVCMChicane,:), 0);
2756                             steppv('VCM','Setpoint', Y(iVCMChicane), VCMlist1(iVCMChicane,:), 0);
2757                         end
2758
2759                         % write fast orbit feedback setpoints
2760                         if 1
2761                             write_goldenorbit_ffb_2planes(2,Ynew(1:size(BPMlist1,1))+Sy1*Y(1:N_VCM),BPMlist1);
2762                         end
2763
2764                     end
2765
2766                     Yold = Ynew;
2767
2768                     %fprintf('Vertical Done: %f \n',gettime-t00);
2769                 end % End vertical correction
2770
2771
2772                 %%%%%%%%%%%%%%%%%%%%%
2773                 % Tune feed forward %
2774                 %%%%%%%%%%%%%%%%%%%%%
2775                 % We should do a Sector limit check
2776
2777                 tic;
2778                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxTune'),'Value') == 1
2779
2780                     if strcmp(SR_Mode, '1.9 GeV, High Tune') || strcmp(SR_Mode, '1.9 GeV, Inject at 1.23') || strcmp(SR_Mode, '1.9 GeV, Inject at 1.353') ||...
2781                         strcmp(SR_Mode, '1.9 GeV, Two-Bunch')  || strcmp(SR_Mode, '1.5 GeV, Inject at 1.353')  || strcmp(SR_Mode, '1.9 GeV, TopOff')
2782
2783                         addQFsp = zeros(24,1);
2784                         addQDsp = zeros(24,1);
2785
2786                         if strcmp(FFTypeFlag,'Local')
2787                             disp('  No local tune compensation available - global is the default now.');
2788                         elseif strcmp(FFTypeFlag,'Global')
2789
2790                             % The vectorized gets were put outside of loop for speed reasons
2791                             %
2792                             % should also set up QFfac, Quadelem, Quadlist structures outside loop
2793                             actualgap = getid(IDSector);
2794                             [gapmin,gapmax] = gaplimit(IDSector);
2795                             corrind = find(actualgap<(gapmin-1));
2796                             actualgap(corrind)=gapmax(corrind);
2797                             Shift=zeros(size(actualgap));
2798                             Shift(EPUlist)=getpv('EPU');
2799
2800                             IDchangedList=find((abs(actualgap-oldgap)>0.005) | (abs(Shift-oldShift)>0.005));
2801
2802                             if ~isempty(IDchangedList)
2803
2804                                 oldgap=actualgap;
2805                                 oldShift=Shift;
2806
2807                                 % EPUs excite nux = .25 resonance in vertical linear polarization mode!
2808                                 % therefore with EPU tune feedforward
2809                                 % running, we want to move our nominal working point away (just below) the .25 resonance.
2810                                 %
2811                                 % The following tune correction moves nominal
2812                                 % nu_x from .25 to .245 - this should be enough for well set up lattices.
2813                                 %
2814                                 % 24 QF+ 24 QD
2815                                 DeltaAmps = inv(SR_TUNE_MATRIX) * [-0.005;0];    %  DelAmps =  [QF; QD];
2816                                 addQFsp = addQFsp + DeltaAmps(1,:);
2817                                 addQDsp = addQDsp + DeltaAmps(2,:);
2818
2819                                 for gapnum = 1:length(actualgap)
2820
2821                                     % Change in tune and [QF;QD] from maximum gap
2822
2823                                     if (IDSector(gapnum,1) == 4) || (IDSector(gapnum,1) == 11)
2824                                         if IDSector(gapnum,2) == 1
2825                                             modenamestr = sprintf('SR%02dU___ODS1M__DC00',IDSector(gapnum,1));
2826                                         else % if IDSector(gapnum,2) == 2
2827                                             modenamestr = sprintf('SR%02dU___ODS2M__DC00',IDSector(gapnum,1));
2828                                         end
2829                                         epumode = getpv(modenamestr);
2830                                         if (IDSector(gapnum,1) == 4) && (IDSector(gapnum,2) == 1)
2831                                             if 1   % temporary fix as long as we do not have good tune FF table without shims (2008-02-15)
2832                                                 if (epumode==0)
2833                                                     DeltaNuX = shift2tune(IDSector(gapnum,:),actualgap(gapnum),Shift(gapnum));
2834                                                     DeltaNuY = 0;
2835                                                 else
2836                                                     DeltaNuX = 0;
2837                                                     DeltaNuY = 0;
2838                                                 end
2839                                             elseif (epumode == 0)
2840 %                                                 DeltaNuX = interp2(gap_epu_41,shift_epu_41,dnux_epu_41_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2841 %                                                 DeltaNuY = interp2(gap_epu_41,shift_epu_41,dnuy_epu_41_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2842                                                 DeltaNuX = interp2(gap41p',shift41p',dnux41p',actualgap(gapnum),Shift(gapnum),'linear',0);
2843                                                 DeltaNuY = interp2(gap41p',shift41p',dnuy41p',actualgap(gapnum),Shift(gapnum),'linear',0);
2844                                             elseif (epumode == 1)
2845 %                                                 DeltaNux = 0;
2846 %                                                 DeltaNuY = gap2tune(IDSector(gapnum, :), actualgap(gapnum), SR_GeV);
2847                                                 DeltaNuX = interp2(gap41a',shift41a',dnux41a',actualgap(gapnum),Shift(gapnum),'linear',0);
2848                                                 DeltaNuY = interp2(gap41a',shift41a',dnuy41a',actualgap(gapnum),Shift(gapnum),'linear',0);
2849                                             else
2850                                                 DeltaNux = 0;
2851                                                 DeltaNuY = gap2tune(IDSector(gapnum, :), actualgap(gapnum), SR_GeV);
2852                                             end
2853                                         elseif (IDSector(gapnum,1) == 11) && (IDSector(gapnum,2) == 1)
2854                                             if (epumode == 0)
2855 %                                                 DeltaNuX = interp2(gap_epu_111,shift_epu_111,dnux_epu_111_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2856 %                                                 DeltaNuY = interp2(gap_epu_111,shift_epu_111,dnuy_epu_111_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2857                                                 DeltaNuX = interp2(gap111p',shift111p',dnux111p',actualgap(gapnum),Shift(gapnum),'linear',0);
2858                                                 DeltaNuY = interp2(gap111p',shift111p',dnuy111p',actualgap(gapnum),Shift(gapnum),'linear',0);
2859                                             elseif (epumode == 1)
2860 %                                                 DeltaNuX = interp2(gap_epu_111,shift_epu_111,dnux_epu_111_m1',actualgap(gapnum),Shift(gapnum),'linear',0);
2861 %                                                 DeltaNuY = interp2(gap_epu_111,shift_epu_111,dnuy_epu_111_m1',actualgap(gapnum),Shift(gapnum),'linear',0);
2862                                                 DeltaNuX = interp2(gap111a',shift111a',dnux111a',actualgap(gapnum),Shift(gapnum),'linear',0);
2863                                                 DeltaNuY = interp2(gap111a',shift111a',dnuy111a',actualgap(gapnum),Shift(gapnum),'linear',0);
2864                                             else
2865                                                 DeltaNuX = 0;
2866                                                 DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);   % variation of vertical tune shift with phase is small for EPUs
2867                                             end
2868                                         elseif (IDSector(gapnum,1) == 11) && (IDSector(gapnum,2) == 2)
2869                                             if (epumode == 0)
2870 %                                                 DeltaNuX = interp2(gap_epu_111,shift_epu_111,dnux_epu_111_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2871 %                                                 DeltaNuY = interp2(gap_epu_111,shift_epu_111,dnuy_epu_111_m0',actualgap(gapnum),Shift(gapnum),'linear',0);
2872                                                 DeltaNuX = interp2(gap112p',shift112p',dnux112p',actualgap(gapnum),Shift(gapnum),'linear',0);
2873                                                 DeltaNuY = interp2(gap112p',shift112p',dnuy112p',actualgap(gapnum),Shift(gapnum),'linear',0);
2874                                             elseif (epumode == 1)
2875 %                                                 DeltaNuX = interp2(gap_epu_111,shift_epu_111,dnux_epu_111_m1',actualgap(gapnum),Shift(gapnum),'linear',0);
2876 %                                                 DeltaNuY = interp2(gap_epu_111,shift_epu_111,dnuy_epu_111_m1',actualgap(gapnum),Shift(gapnum),'linear',0);
2877                                                 DeltaNuX = interp2(gap112a',shift112a',dnux112a',actualgap(gapnum),Shift(gapnum),'linear',0);
2878                                                 DeltaNuY = interp2(gap112a',shift112a',dnuy112a',actualgap(gapnum),Shift(gapnum),'linear',0);
2879                                             else
2880                                                 DeltaNuX = 0;
2881                                                 DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);   % variation of vertical tune shift with phase is small for EPUs
2882                                             end
2883                                         else
2884                                             DeltaNuX = 0;
2885                                             DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);
2886                                         end
2887
2888                                     else
2889                                         DeltaNuX = 0;
2890                                         DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);
2891                                     end
2892
2893                                     DelQF = zeros(length(QFsp),1);
2894                                     DelQD = zeros(length(QFsp),1);
2895
2896                                     fraccorr = 0.8*DeltaNuY ./ TuneW16Min;
2897
2898                                     % Find which quads to change (local beta beating correction
2899                                     % (horizontal for EPU, vertical otherwise)
2900                                     QuadList = [IDSector(gapnum,1)-1 2; IDSector(gapnum,1) 1];
2901                                     QuadElem = dev2elem('QF',QuadList); % in reality use QF and QD ...
2902
2903                                     % global vertical tune correction
2904                                     % 24 QF+ 24 QD
2905                                     DeltaAmps = inv(SR_TUNE_MATRIX) * [(fraccorr*6.23e-4); fraccorr*(-0.05301)];    %  DelAmps =  [QF; QD];
2906                                     DelQF = DelQF + DeltaAmps(1,:);
2907                                     DelQD = DelQD + DeltaAmps(2,:);
2908
2909                                     % local horizontal tune correction (is also nearly a beta beating correction) only nonzero for EPUs!
2910                                     % 2 QF + 2 QD
2911                                     DeltaAmpsLocal = 12*inv(SR_TUNE_MATRIX) * [-DeltaNuX;0];                       %  DelAmps =  [QF; QD];
2912                                     DelQF(QuadElem) = DelQF(QuadElem)+DeltaAmpsLocal(1,1);
2913                                     DelQD(QuadElem) = DelQD(QuadElem)+DeltaAmpsLocal(2,1);
2914
2915                                     % local vertical beta beating correction (should be used together with above global tune correction)
2916                                     % set to zero for EPUs, since their vertical tune shift is small
2917                                     % 2 QF + 2QD
2918                                     if (IDSector(gapnum,1)==6) || (IDSector(gapnum,1)==7) || (IDSector(gapnum,1)==10) || (IDSector(gapnum,1)==11)
2919                                         QFfac = ([2.243127/2.237111; 2.243127/2.237111]-1) * fraccorr;
2920                                         QDfac = ([2.556392/2.511045; 2.556392/2.511045]-1) * fraccorr;
2921                                     elseif (IDSector(gapnum,1)==5) || (IDSector(gapnum,1)==9)
2922                                         QFfac = ([2.225965/2.219784; 2.243096/2.237111]-1) * fraccorr;
2923                                         QDfac = ([2.528950/2.483259; 2.556345/2.511045]-1) * fraccorr;
2924                                     elseif (IDSector(gapnum,1)==4) || (IDSector(gapnum,1)==8) || (IDSector(gapnum,1)==12)
2925                                         QFfac = ([2.243096/2.237111; 2.225965/2.219784]-1) * fraccorr;
2926                                         QDfac = ([2.556345/2.511045; 2.528950/2.483259]-1) * fraccorr;
2927                                     else
2928                                         QFfac = zeros(2,1);
2929                                         QDfac = zeros(2,1);
2930                                     end
2931
2932                                     DelQF(QuadElem,:) = DelQF(QuadElem,:) + QFfac.*QFsp(QuadElem,:);
2933                                     DelQD(QuadElem,:) = DelQD(QuadElem,:) + QDfac.*QDsp(QuadElem,:);
2934
2935                                     % add all tune and beta beating corrections for this one ID to the summed up correction vectors for all IDs
2936                                     addQFsp = addQFsp+DelQF;
2937                                     addQDsp = addQDsp+DelQD;
2938
2939
2940                                     % Skew FF for IVID
2941                                     if (IDSector(gapnum,1)==6)
2942                                         scale=(gap2tune([6 1])/0.005)^(3/4)*0.16;
2943                                         [SQSFincr, SQSDincr] = set_etaywave_nuy9_20skews_skewFF(scale);
2944                                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2945                                         % should add a limit check here %
2946                                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2947                                         setpv('SQSF', 'Setpoint', SQSFsp+SQSFincr, [], 0, 'Physics');
2948                                         setpv('SQSD', 'Setpoint', SQSDsp+SQSDincr, [], 0, 'Physics');
2949                                     end
2950
2951                                 end
2952
2953                                 % Set quadrupoles using main setpoint channels
2954                                 setpv('QF', QFsp+addQFsp,[], 0);
2955                                 setpv('QD', QDsp+addQDsp,[], 0);
2956                                 % % Set quadrupoles using FF setpoint channels
2957                                 % setpv('QF', 'FF', addQFsp, [], 0);
2958                                 % setpv('QD', 'FF', addQDsp, [], 0);
2959
2960                             end
2961
2962                         else
2963                             error('Unknown type selected for tune FF');
2964                         end
2965
2966                     else
2967                         disp('  No tune FF algorithm for non-production modes yet...');
2968                     end
2969                 end
2970
2971                 ffdeltaquad_delay = toc;
2972                 %fprintf('tune FF delay = %.1f seconds\n',ffdeltaquad_delay);
2973                 % fprintf('Tune Done: %f \n',gettime-t00);
2974
2975                 % Output info to screen
2976                 set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
2977                 set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
2978                 %pause(0);
2979
2980                 FOFBStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2981                     getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2982                     getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2983                     getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2984                 for loop = 1:size(FOFBStatus,2)
2985                     if FOFBStatus(loop)==0
2986                         FOFBStatusStr(loop,:) = 'OFF ';
2987                     elseif FOFBStatus(loop)==1
2988                         FOFBStatusStr(loop,:) = 'ON  ';
2989                     elseif FOFBStatus(loop)==2
2990                         FOFBStatusStr(loop,:) = 'OPEN';
2991                     else
2992                         FOFBStatusStr(loop,:) = 'BAD ';
2993                     end
2994                 end
2995                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 %s',FOFBStatusStr(1,:)),'ForegroundColor',[0 0 0]);
2996                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 %s',FOFBStatusStr(2,:)),'ForegroundColor',[0 0 0]);
2997                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 %s',FOFBStatusStr(3,:)),'ForegroundColor',[0 0 0]);
2998                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 %s',FOFBStatusStr(4,:)),'ForegroundColor',[0 0 0]);
2999                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 %s',FOFBStatusStr(5,:)),'ForegroundColor',[0 0 0]);
3000                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 %s',FOFBStatusStr(6,:)),'ForegroundColor',[0 0 0]);
3001                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 %s',FOFBStatusStr(7,:)),'ForegroundColor',[0 0 0]);
3002                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 %s',FOFBStatusStr(8,:)),'ForegroundColor',[0 0 0]);
3003                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 %s',FOFBStatusStr(9,:)),'ForegroundColor',[0 0 0]);
3004                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 %s',FOFBStatusStr(10,:)),'ForegroundColor',[0 0 0]);
3005                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 %s',FOFBStatusStr(11,:)),'ForegroundColor',[0 0 0]);
3006                 set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 %s',FOFBStatusStr(12,:)),'ForegroundColor',[0 0 0]);
3007
3008
3009                 %fprintf('End of feedback operations: %f \n\n',gettime-t00);
3010
3011                 % Wait for next update time or stop request
3012                 while (gettime-t00) < LoopDelay
3013                     %disp('interval could be shorter')
3014                     pause(.05);
3015                     % Check if GUI has been closed
3016                     if isempty(gcbf)
3017                         FEEDBACK_STOP_FLAG = 1;
3018                         lasterr('SRCONTROL GUI DISAPPEARED!');
3019                         error('SRCONTROL GUI DISAPPEARED!');
3020                     end
3021
3022                     % Check if Stop button was pressed
3023                     if FEEDBACK_STOP_FLAG == 1
3024                         % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
3025                         if getpv('SR01____FFBON__BC00')==1
3026                             disp('   Stopping Fast Orbit Feedback.');
3027                         end
3028                         setpv('SR01____FFBON__BC00',0);
3029                         pause(0.5);
3030                         setpv('SR01____FFBON__BC00',2);
3031                         break;
3032                     end
3033                 end
3034
3035
3036                 if FEEDBACK_STOP_FLAG == 1
3037                     % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
3038                     if getpv('SR01____FFBON__BC00')==1
3039                         disp('   Stopping Fast Orbit Feedback.');
3040                     end
3041                     setpv('SR01____FFBON__BC00',0);
3042                     pause(0.5);
3043                     setpv('SR01____FFBON__BC00',2);
3044                     break;
3045                 end
3046
3047                 StartErrorTime = gettime;
3048
3049             catch
3050
3051                 fprintf('\n  %s \n',lasterr);
3052
3053                 % Quit if error exists for more than 20 seconds
3054                 if gettime-StartErrorTime>20 || FEEDBACK_STOP_FLAG==1
3055                     fprintf('%s  Orbit feedback stopped due to error condition. \n\n',datestr(now));
3056
3057                     %send alphapage to operator pager
3058                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
3059                     FEEDBACK_STOP_FLAG = 1;
3060
3061                     setpv('SR_STATE', -5);
3062                     [StateNumber, StateString] = getsrstate;
3063                     if StateNumber >= 0
3064                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
3065                     else
3066                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
3067                     end
3068                 else
3069                     a = clock;
3070                     fprintf('   Orbit feedback was paused due to error condition (%s %d:%d:%.0f). \n', date, a(4), a(5), a(6));
3071                     fprintf('   Orbit feedback has automatically restarted and is running. \n\n');
3072                 end
3073
3074             end
3075
3076             if FEEDBACK_STOP_FLAG == 1
3077                 % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
3078                 if getpv('SR01____FFBON__BC00')==1
3079                     disp('   Stopping Fast Orbit Feedback.');
3080                 end
3081                 setpv('SR01____FFBON__BC00',0);
3082                 pause(0.5);
3083                 setpv('SR01____FFBON__BC00',2);
3084                 break;
3085             end
3086
3087             %fprintf('End of feedback loop: %f \n\n',gettime-t00);
3088
3089             %pause(0);
3090
3091             % this loop delays turn on of Fast Feedback system
3092             if FBloopIter < 5
3093                 FBloopIter = FBloopIter + 1;
3094             end
3095
3096         end  % End of feedback loop
3097
3098
3099         % End feedback, reset all parameters
3100         try
3101
3102             % Enable buttons
3103             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','on');
3104             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','off');
3105             set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','on');
3106             set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','on');
3107             set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','on');
3108             set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','on');
3109             set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','on');
3110             set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','on');
3111             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','on');
3112             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','on');
3113             set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','on');
3114             set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','on');
3115             set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','on');
3116
3117             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = _____ mm'),'ForegroundColor',[0 0 0]);
3118             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = _____ mm'),'ForegroundColor',[0 0 0]);
3119
3120             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB01'),'String',sprintf('01 ____'),'ForegroundColor',[0 0 0]);
3121             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB02'),'String',sprintf('02 ____'),'ForegroundColor',[0 0 0]);
3122             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB03'),'String',sprintf('03 ____'),'ForegroundColor',[0 0 0]);
3123             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB04'),'String',sprintf('04 ____'),'ForegroundColor',[0 0 0]);
3124             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB05'),'String',sprintf('05 ____'),'ForegroundColor',[0 0 0]);
3125             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB06'),'String',sprintf('06 ____'),'ForegroundColor',[0 0 0]);
3126             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB07'),'String',sprintf('07 ____'),'ForegroundColor',[0 0 0]);
3127             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB08'),'String',sprintf('08 ____'),'ForegroundColor',[0 0 0]);
3128             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB09'),'String',sprintf('09 ____'),'ForegroundColor',[0 0 0]);
3129             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB10'),'String',sprintf('10 ____'),'ForegroundColor',[0 0 0]);
3130             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB11'),'String',sprintf('11 ____'),'ForegroundColor',[0 0 0]);
3131             set(findobj(gcbf,'Tag','SRCTRLStaticTextFOFB12'),'String',sprintf('12 ____'),'ForegroundColor',[0 0 0]);
3132
3133             %pause(0);
3134
3135         catch
3136
3137             % GUI must have been closed
3138
3139         end
3140
3141
3142         % Reset Bergoz BPM time constant to whatever it was before feedback started
3143         fprintf('   Bergoz BPM time constant set back to %.1f\n', BPMtimeconstantOFB);
3144         setbpmtimeconstant(BPMtimeconstantOFB);
3145
3146
3147         a = clock;
3148         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
3149         [StateNumber, StateString] = getsrstate;
3150         if StateNumber >= 0
3151             setpv('SR_STATE',5.1);
3152             [StateNumber, StateString] = getsrstate;
3153             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
3154             fprintf('   ******************************\n');
3155             fprintf('   **  Orbit Feedback Stopped  **\n');
3156             fprintf('   ******************************\n\n');
3157         else
3158             [StateNumber, StateString] = getsrstate;
3159             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
3160             fprintf('   ****************************************\n');
3161             fprintf('   **  Problem With Slow Orbit Feedback  **\n');
3162             fprintf('   ****************************************\n\n');
3163         end
3164         set(0,'showhiddenhandles','off');
3165         pause(0);
3166
3167
3168     case 'FeedbackSetup'
3169         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
3170
3171         if InitFlag
3172
3173
3174             % Get the device lists from oscsinit and convert to srcontrol variables
3175             [HBPM, VBPM, HCM, VCM, HSV, VSV] = ocsinit('SOFB');
3176             Xivec = 1:HSV;
3177             Yivec = 1:VSV;
3178             BPMlist1 = HBPM.DeviceList;
3179             HCMlist1 = HCM.DeviceList;
3180             VCMlist1 = VCM.DeviceList;
3181
3182
3183             OCSx.BPM = getx(BPMlist1, 'struct');
3184             OCSx.CM = getsp('HCM', HCMlist1, 'struct');
3185             OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
3186             OCSx.NIter = 1;
3187             OCSx.SVDIndex = Xivec;
3188             OCSx.IncrementalFlag = 'No';
3189             OCSx.BPMWeight = {[]};
3190             OCSx.FitRF = 0;
3191             OCSy.BPM = gety(BPMlist1, 'struct');
3192             OCSy.CM = getsp('VCM', VCMlist1, 'struct');
3193             OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
3194             OCSy.NIter = 1;
3195             OCSy.SVDIndex = Yivec;
3196             OCSy.IncrementalFlag = 'No';
3197             OCSy.BPMWeight = {[]};
3198             OCSy.FitRF = 0;
3199
3200             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
3201             % do we need these Smat calls? %
3202             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
3203             SXmat = getrespmat(OCSx.BPM, OCSx.CM, 'numeric');
3204             SYmat = getrespmat(OCSy.BPM, OCSy.CM, 'numeric');
3205             % [OCSx, Sx, Ux, Vx] = orbitcorrectionmethods(OCSx, SXmat);
3206             % [OCSy, Sy, Uy, Vy] = orbitcorrectionmethods(OCSy, SYmat);
3207
3208             % initialize FFTypeFlag
3209             FFTypeFlag = 'Global';
3210
3211             % Fit decision comes from check box
3212             if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
3213                 OCSx.FitRF = 1;
3214                 Xivec = 1:HSV+1;
3215             end
3216
3217         else
3218
3219             % Get vectors
3220             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
3221             % the two lines below seem to fix BPMlist editing problem
3222             OCSx = FB.OCSx;
3223             OCSy = FB.OCSy;
3224             BPMlist1 = FB.BPMlist1;
3225             HCMlist1 = FB.HCMlist1;
3226             VCMlist1 = FB.VCMlist1;
3227             Xivec = FB.Xivec;
3228             Yivec = FB.Yivec;
3229             Xgoal = FB.OCSx.GoalOrbit;
3230             OCSx.GoalOrbit = Xgoal;
3231             Ygoal = FB.OCSy.GoalOrbit;
3232             OCSy.GoalOrbit = Ygoal;
3233             FFTypeFlag = FB.FFTypeFlag;
3234
3235
3236             % FF corrector magnet list - only channels which are blocked when FF is running should be
3237             % listed
3238             ListFF = [
3239                 4     2
3240                 4     8
3241                 5     1
3242                 5     7
3243 %               5     8 % IVID is using digital FF, i.e. FF algorithm does not block
3244 %               6     1 % other access to PVs
3245                 6     8
3246                 7     1
3247                 7     8
3248                 8     1
3249                 8     8
3250                 9     1
3251                 9     8
3252                 10    1
3253                 11    8
3254                 12    1];
3255             ElemFF = dev2elem('HCM',ListFF);
3256
3257
3258             % Add button to change #ivectors, cm, IDBPMs,
3259             EditFlag = 0;
3260             h_fig1 = figure;
3261             while EditFlag ~= 6
3262
3263                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
3264                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
3265
3266                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
3267                     DispOrbit = getdisp('BPMx', BPMlist1);
3268                     Sx = [Sx DispOrbit];
3269                 end
3270
3271                 Sx(isnan(Sx)) = 0;
3272                 Sy(isnan(Sy)) = 0;
3273
3274                 [Ux, SVx, Vx] = svd(Sx);
3275                 [Uy, SVy, Vy] = svd(Sy);
3276
3277
3278                 % Remove singular values greater than the actual number of singular values
3279                 i = find(Xivec>length(diag(SVx)));
3280                 if ~isempty(i)
3281                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
3282                     pause(0);
3283                     Xivec(i) = [];
3284                 end
3285                 i = find(Yivec>length(diag(SVy)));
3286                 if ~isempty(i)
3287                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
3288                     pause(0);
3289                     Yivec(i) = [];
3290                 end
3291
3292
3293                 Ax = Sx*Vx(:,Xivec);
3294                 Tx = inv(Ax'*Ax)*Ax';
3295
3296                 Ay = Sy*Vy(:,Yivec);
3297                 Ty = inv(Ay'*Ay)*Ay';
3298
3299                 figure(h_fig1);
3300                 subplot(2,1,1);
3301                 semilogy(diag(SVx),'b');
3302                 hold on;
3303                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
3304                 ylabel('Horizontal');
3305                 title('Response Matrix Singular Values');
3306                 hold off;
3307                 subplot(2,1,2);
3308                 semilogy(diag(SVy),'b');
3309                 hold on;
3310                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
3311                 xlabel('Singular Value Number');
3312                 ylabel('Vertical');
3313                 hold off;
3314                 drawnow;
3315
3316                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List', ...
3317                     'BPM List','Change the Goal Orbit','Continue');
3318
3319                 if EditFlag == 1
3320                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
3321                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
3322                     titlestr='SVD Orbit Feedback';
3323                     lineNo=1;
3324                     answer=inputdlg(prompt,titlestr,lineNo,def);
3325                     if ~isempty(answer)
3326                         XivecNew = fix(str2num(answer{1}));
3327                         if isempty(XivecNew)
3328                             disp('   Horizontal E-vector cannot be empty.  No change made.');
3329                         else
3330                             if any(XivecNew<=0) || max(XivecNew)>length(diag(SVx))
3331                                 disp('   Error reading horizontal E-vector.  No change made.');
3332                             else
3333                                 Xivec = XivecNew;
3334                             end
3335                         end
3336                         YivecNew = fix(str2num(answer{2}));
3337                         if isempty(YivecNew)
3338                             disp('   Vertical E-vector cannot be empty.  No change made.');
3339                         else
3340                             if any(YivecNew<=0) || max(YivecNew)>length(diag(SVy))
3341                                 disp('   Error reading vertical E-vector.  No change made.');
3342                             else
3343                                 Yivec = YivecNew;
3344                             end
3345                         end
3346                     end
3347                 end
3348
3349                 if EditFlag == 2
3350                     List= getlist('HCM','Trim');
3351                     CheckList = zeros(96,1);
3352                     Elem = dev2elem('HCM', HCMlist1);
3353                     CheckList(Elem) = ones(size(Elem));
3354                     CheckList = CheckList(dev2elem('HCM',List));
3355
3356                     % Remove FF corrrectors
3357                     %           Elem = dev2elem('HCM',List);
3358                     %           for j = length(ElemFF):-1:1
3359                     %              i = find(Elem==ElemFF(j));
3360                     %              Elem(i,:) = [];
3361                     %              List(i,:) = [];
3362                     %              CheckList(i,:) = [];
3363                     %           end
3364
3365                     newList = editlist(List, 'HCMtrim', CheckList);
3366
3367                     if isempty(newList)
3368                         fprintf('   WARNING: Horizontal corrector magnet list is empty!\n');
3369                         HCMlist1 = newList;
3370                     else
3371                         HCMlist1 = newList;
3372                     end
3373                     OCSx.CM.DeviceList = HCMlist1;
3374                 end
3375
3376                 if EditFlag == 3
3377                     List = getlist('VCM','Trim');
3378                     CheckList = zeros(96,1);
3379                     Elem = dev2elem('VCM', VCMlist1);
3380                     CheckList(Elem) = ones(size(Elem));
3381                     CheckList = CheckList(dev2elem('VCM',List));
3382
3383                     % Remove FF corrrectors
3384                     %           Elem = dev2elem('VCM',List);
3385                     %           for j = length(ElemFF):-1:1
3386                     %              i = find(Elem==ElemFF(j));
3387                     %              Elem(i,:) = [];
3388                     %              List(i,:) = [];
3389                     %              CheckList(i,:) = [];
3390                     %           end
3391
3392                     newList = editlist(List, 'VCMtrim', CheckList);
3393
3394                     if isempty(newList)
3395                         fprintf('   WARNING: Vertical corrector magnet list is empty!\n');
3396                         VCMlist1 = newList;
3397                     else
3398                         VCMlist1 = newList;
3399                     end
3400                     OCSy.CM.DeviceList = VCMlist1;
3401                 end
3402
3403                 if EditFlag == 4
3404                     ListOld = BPMlist1;
3405                     XgoalOld = Xgoal;
3406                     YgoalOld = Ygoal;
3407
3408                     % Full BPM list
3409                     List = getbpmlist('Bergoz');
3410
3411                     CheckList = zeros(size(List,1),1);
3412                     if ~isempty(BPMlist1)
3413                         for i = 1:size(List,1)
3414                             k = find(List(i,1)==BPMlist1(:,1));
3415                             l = find(List(i,2)==BPMlist1(k,2));
3416
3417                             if isempty(k) || isempty(l)
3418                                 % Item not in list
3419                             else
3420                                 CheckList(i) = 1;
3421                             end
3422                         end
3423                     end
3424
3425                     newList = editlist(List, 'BPM', CheckList);
3426                     if isempty(newList)
3427                         fprintf('   BPM list cannot be empty.  No change made.\n');
3428                     else
3429                         BPMlist1 = newList;
3430                     end
3431
3432                     % Set the goal orbit to the golden orbit
3433                     Xgoal = getgolden('BPMx', BPMlist1);
3434                     Ygoal = getgolden('BPMy', BPMlist1);
3435
3436
3437                     % If a new BPM is added, then set the goal orbit to the golden orbit
3438                     for i = 1:size(BPMlist1,1)
3439
3440                         % Is it a new BPM?
3441                         k = find(BPMlist1(i,1)==ListOld(:,1));
3442                         l = find(BPMlist1(i,2)==ListOld(k,2));
3443
3444                         if isempty(k) || isempty(l)
3445                             % New BPM
3446                         else
3447                             % Use the old value for old BPM
3448                             Xgoal(i) = XgoalOld(k(l));
3449                             Ygoal(i) = YgoalOld(k(l));
3450                         end
3451                     end
3452                     OCSx.BPM.DeviceList = BPMlist1;
3453                     OCSy.BPM.DeviceList = BPMlist1;
3454                     OCSx.GoalOrbit = Xgoal;
3455                     OCSy.GoalOrbit = Ygoal;
3456                 end
3457
3458                 if EditFlag == 5
3459                     ChangeList = editlist2(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
3460
3461                     for i = 1:size(ChangeList,1)
3462
3463                         k = find(ChangeList(i,1)==BPMlist1(:,1));
3464                         l = find(ChangeList(i,2)==BPMlist1(k,2));
3465
3466                         prompt={sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
3467                         def={sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
3468                         titlestr='CHANGE THE GOAL ORBIT';
3469                         lineNo=1;
3470                         answer = inputdlg(prompt, titlestr, lineNo, def);
3471
3472                         if isempty(answer)
3473                             % No change
3474                             fprintf('   No change was made to the golden orbit.\n');
3475                         else
3476                             Xgoalnew = str2num(answer{1});
3477                             if isempty(Xgoalnew)
3478                                 fprintf('   No change was made to the horizontal golden orbit.\n');
3479                             else
3480                                 Xgoal(k(l)) = Xgoalnew;
3481                             end
3482
3483                             Ygoalnew = str2num(answer{2});
3484                             if isempty(Ygoalnew)
3485                                 fprintf('   No change was made to the vertical golden orbit.\n');
3486                             else
3487                                 Ygoal(k(l)) = Ygoalnew;
3488                             end
3489                         end
3490                     end
3491                     if ~isempty(ChangeList)
3492                         fprintf('   Note:  Changing the goal orbit for "Slow Orbit Feedback" does not change the goal orbit for "Orbit Correction."\n');
3493                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
3494                     end
3495                     OCSx.GoalOrbit = Xgoal;
3496                     OCSy.GoalOrbit = Ygoal;
3497                 end
3498
3499 %                 if EditFlag == 6
3500 %                     FFTypeFlag = questdlg(sprintf('Do you want to use a fully local or a combined local/global compensation of IDs? (nuy=9.2 only)'),'Tune FF','Local','Global', 'Global');
3501 %                     if strcmp(FFTypeFlag,'Local')
3502 %                         disp(['   The tune FF will use 8 local quadrupoles to compensate beta beating and tune shift']);
3503 %                         disp(['   from each ID.']);
3504 %                     elseif strcmp(FFTypeFlag,'Global')
3505 %                         disp(['   The tune FF will use 4 local quadrupoles to compensate beta beating and all QF+QD']);
3506 %                         disp(['   to compensate tune shift from each ID.']);
3507 %                     end
3508 %                 end
3509
3510             end
3511             close(h_fig1);
3512         end
3513
3514         % Save vectors
3515         FB.Xivec = Xivec;
3516         FB.Yivec = Yivec;
3517         FB.HCMlist1 = HCMlist1;
3518         FB.VCMlist1 = VCMlist1;
3519         FB.BPMlist1 = BPMlist1;
3520
3521         OCSx.SVDIndex = Xivec;
3522         OCSy.SVDIndex = Yivec;
3523         FB.OCSx = OCSx;
3524         FB.OCSy = OCSy;
3525
3526         FB.FFTypeFlag = FFTypeFlag;
3527         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata',FB);
3528
3529
3530     case 'FastFeedbackSetup'
3531
3532         InitFlag = Input2;
3533
3534         if InitFlag
3535             FOFBFreq = 1000;
3536             % user operations 9/14-10/17/04: P=0.5, I=120, D=0.0015 (for both planes)
3537             % below are known good values for user ops as of 8-1-05
3538             HorP = 2;
3539             HorI = 300;
3540             HorD = 0.002;
3541             VertP = 1;
3542             VertI = 100;
3543             VertD = 0.0015;
3544
3545             % this initial set is now done in hwinit.m because it's not a good idea to set anything when srcontrol is launched
3546             % try
3547             %     setsp('SR01____FFBFREQAC00', FOFBFreq); % set freq
3548             %     write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3549             % catch
3550             %     disp('   Trouble setting Fast Orbit Feedback parameters!');
3551             % end
3552
3553         else
3554             % Get vectors
3555             FOFB = get(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata');
3556             FOFBFreq = FOFB.FOFBFreq;
3557             HorP  = FOFB.HorP;
3558             HorI  = FOFB.HorI;
3559             HorD  = FOFB.HorD;
3560             VertP = FOFB.VertP;
3561             VertI = FOFB.VertI;
3562             VertD = FOFB.VertD;
3563
3564             % Add button to change #ivectors, CMs, IDBPMs,
3565             EditFlag = 0;
3566             %h_fig1 = figure;
3567             while EditFlag ~= 3
3568
3569                 %EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'HCM List', 'VCM List', ...
3570                 %   'IDBPM List', 'BBPM List', 'Continue');
3571                 % Use menu below until other FFB config routines work (then also uncomment options 3,4,5,6 below)
3572                 EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'Continue');
3573
3574                 if EditFlag == 1
3575                     % change rate
3576
3577                     prompt={'Enter the desired Fast Feedback Frequency (1-1000 Hz)'};
3578                     def={num2str(FOFBFreq)};
3579                     titlestr='Fast Feedback Setup';
3580                     lineNo=1;
3581                     answer=inputdlg(prompt,titlestr,lineNo,def);
3582                     if ~isempty(answer)
3583                         FOFBFreq = fix(str2num(answer{1}));
3584                         if isempty(FOFBFreq)
3585                             disp('   Frequency value cannot be empty.  No change made.');
3586                             FOFBFreq = getsp('SR01____FFBFREQAC00');
3587                         else
3588                             if FOFBFreq < 1 || FOFBFreq > 1000
3589                                 disp('   Frequency must be between 1 and 1000 Hz.  No change made.');
3590                                 FOFBFreq = getsp('SR01____FFBFREQAC00');
3591                             end
3592                         end
3593                         setsp('SR01____FFBFREQAC00',FOFBFreq); % change freq
3594                         pause(0.5);
3595                         fprintf('   Fast orbit feedback frequency is running at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
3596                     else
3597                         FOFBFreq = getsp('SR01____FFBFREQAC00');
3598                     end
3599                 end
3600
3601                 if EditFlag == 2
3602                     % edit  PIDs
3603                     % User defaults are HorP=2, HorI=300, HorD=0.002, VertP=1, VertI=100, VertD=0.0015
3604                     prompt={'P horizontal', 'I horizontal', 'D horizontal', 'P vertical', 'I vertical', 'D vertical'};
3605                     def={num2str(HorP), num2str(HorI), num2str(HorD), num2str(VertP), num2str(VertI), num2str(VertD)};
3606                     titlestr='Fast Feedback PID Setup';
3607                     lineNo=1;
3608                     answer=inputdlg(prompt,titlestr,lineNo,def);
3609                     if ~isempty(answer)
3610                         HorPnewnum = str2num(answer{1});
3611                         if isempty(HorPnewnum)
3612                             disp('   HorP value cannot be empty.  No change made.');
3613                         else
3614                             HorP = HorPnewnum;
3615                         end
3616                         HorInewnum = str2num(answer{2});
3617                         if isempty(HorInewnum)
3618                             disp('   HorI value cannot be empty.  No change made.');
3619                         else
3620                             HorI = HorInewnum;
3621                         end
3622                         HorDnewnum = str2num(answer{3});
3623                         if isempty(HorDnewnum)
3624                             disp('   HorD value cannot be empty.  No change made.');
3625                         else
3626                             HorD = HorDnewnum;
3627                         end
3628                         VertPnewnum = str2num(answer{4});
3629                         if isempty(VertPnewnum)
3630                             disp('   VertP value cannot be empty.  No change made.');
3631                         else
3632                             VertP = VertPnewnum;
3633                         end
3634                         VertInewnum = str2num(answer{5});
3635                         if isempty(VertInewnum)
3636                             disp('   VertI value cannot be empty.  No change made.');
3637                         else
3638                             VertI = VertInewnum;
3639                         end
3640                         VertDnewnum = str2num(answer{6});
3641                         if isempty(VertDnewnum)
3642                             disp('   VertD value cannot be empty.  No change made.');
3643                         else
3644                             VertD = VertDnewnum;
3645                         end
3646
3647                         try
3648                             write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3649                             fprintf('   Setting FFB gains to Horizontal P=%.2f, I=%.1f, D=%.4f;  Vertical P=%.2f, I=%.1f, D=%.4f\n', HorP, HorI, HorD, VertP, VertI, VertD);
3650                         catch
3651                             disp('   Trouble setting Fast Orbit Feedback parameters!');
3652                         end
3653                     end
3654                 end
3655
3656                 %if EditFlag == 3
3657                 %   disp('   This function not yet available.');
3658                 %   % change HCM List
3659                 %end
3660                 %
3661                 %if EditFlag == 4
3662                 %   disp('   This function not yet available.');
3663                 %   % change VCM List
3664                 %end
3665                 %
3666                 %if EditFlag == 5
3667                 %   disp('   This function not yet available.');
3668                 %   % change IDBPM List
3669                 %end
3670                 %
3671                 %if EditFlag == 6
3672                 %   disp('   This function not yet available.');
3673                 %   % change BBPM List
3674                 %end
3675
3676             end
3677             %close(h_fig1);
3678         end
3679
3680         % Save vectors
3681         FOFB.FOFBFreq = FOFBFreq;
3682         FOFB.HorP = HorP;
3683         FOFB.HorI = HorI;
3684         FOFB.HorD = HorD;
3685         FOFB.VertP = VertP;
3686         FOFB.VertI = VertI;
3687         FOFB.VertD = VertD;
3688         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata',FOFB);
3689
3690     otherwise
3691         fprintf('   No action for %s.\n', action);
3692 end   % end case