Description of srcontrol5_including_vectorized_EPU_FF
Home > ALS > StorageRing > srcontrol5_including_vectorized_EPU_FF.m
srcontrol5_including_vectorized_EPU_FF
PURPOSE
srcontrol5
SYNOPSIS
function srcontrol5(action, Input2, Input3)
DESCRIPTION
 srcontrol5
 Storage ring control program
 This program controls all storage ring magnets, performs orbit feedback and
 tune feedforward and helps to diagnose problems in routine user operation
 of the ALS storage ring. It includes a gui to simplify the use of this
 program.
 It was originally programmed by Greg Portmann (until December 2000) with input
 from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
 and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
 The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
 Christoph Steier, July 2002
 SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
 Tom Scarvie, April 2005
CROSS-REFERENCE INFORMATION
This function calls:
bend2gev BEND2GEV - Compute the energy based on the ramp tables
checksrmags CHECKSRMAGS - Check SR power supplies against a lattice file
checksrorbit ErrorNums =checksrorbit(Sector, BPMxtolerance [.015 mm], [BPMytolerance [.015 mm]])
gap2tune GAP2TUNE - Computes the vertical tune shift for a insertion device gap change.
gaplimit [GapMin, GapMax] = gaplimit(ID_Number);
getff function [FFEnableBM, FFEnableBC, GapEnableBM, GapEnableBC, Sector] = getff(Sector)
getid GETID - Get the insertion device position, velocity, run flag, and user requested gap
getsrstate [StateNumber, StateString] = getsrstate
set_alarmhandler_AHU_thresholds_inject function set_alarmhandler_AHU_thresholds_inject
set_alarmhandler_thresholds set_alarmhandler_thresholds
set_alarmhandler_thresholds_new set_alarmhandler_thresholds_new
setbpmtimeconstant SETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
setbumps SETBUMPS - Make a straight section bump
setff function setff(Sector, FFEnableBC, GapEnableBC)
setid SETID - Set the insertion device vertical gap
setsrstatechannels
shift2tune SHIFT2TUNE - Computes the horizontal tune shift for a EPU gap and horizontal shift
srcycle SRCYCLE - Storage ring cycle
srramp SRRAMP - Ramp the storage ring energy
write_goldenorbit_ffb function write_goldenorbit_ffb
write_goldenorbit_ffb_2planes WRITE_GOLDENORBIT_FFTB_2PLANES - Sets the BPM setpoints which are used by the fast feedback system
This function is called by:
SOURCE CODE
function srcontrol5(action, Input2, Input3)
% srcontrol5
% Storage ring control program
%
% This program controls all storage ring magnets, performs orbit feedback and
% tune feedforward and helps to diagnose problems in routine user operation
% of the ALS storage ring. It includes a gui to simplify the use of this
% program.
%
% It was originally programmed by Greg Portmann (until December 2000) with input
% from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
% and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
%
% The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
%
% Christoph Steier, July 2002
%
% SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
%
% Tom Scarvie, April 2005
% known bugs/problems (May 2001):
% - IDBPM averaging might be a bit too long for orbit feedback
%        solved after Superbend shutdown ... Instead of averaging, digital low pass filters are used
% - gap2tune does not give correct answers for wiggler and potentially other IDs -> orbit feedback
%        seems to be OK for other IDs, has been corrected for wiggler (fit to insertion device
%        compensation table)
% - chicanes do not work in orbit feedback
%        solved. One problem was that orbit response matrizes were mis-scaled by factor of two.
%        Second problem was different time constant of power supply control. Solved by moving controls
%        of center chicanes to cPCI (and magnets are fast, hysteresis free, aircore coils).
%        Center chicane in sector 4 is now routinely used in orbit feedback. Sector 11 to follow soon.
% - zero reading of ID gap dumps beam
%        solved in srcontrol5, still a problem in srcontrol5_hightune (but that routine has to be completely
%        rewritten because of all recent changes to srcontrol5, anyhow). For gap readings below the minimum
%        allowed gap for a device, the tune feedforward disables itself.
% - cycling of lattice causes frequent power supply failures
%        solved by changing the cycling procedure. 1.5 GeV operation is now on the upper hysteresis branch
%        as was the 1.9 GeV injection lattice before.
% - frequently stalled data in IDBPM readout
%        solved with new BPM readouts and digital filtering. Seems to have been a resolution problem
%        of the digital averaging algorithm.
% - magnet ramp tables are not in perfect agreement with magnetic measurements
%        Does not appear to be a serious problem. Superbends are slightly out of sync with other magnets,
%        but this does not cause any negative effects while ramping.
% - no good way to operate with injection at 1.5 GeV and storage energy below that
%        There now is a reasonable way to inject at 1.5 GeV and ramp down to lower storage energy. But
%        it has to be tested again after implementing new (and more) chicanes ...
% revision history
% 2001-05-10, Christoph Steier
% check whether readback from insertion device is significantly (more than 1 mm) below minimum
% gap, to avoid false zero readings of insertion device gaps to cause the tune feed forward
% to implement false huge correction (and dump the beam). If the insertion device gap readbacks
% gets more than 1 mm below the nominal minimum gap, the routine now assumes the insertion device
% to be open.
%
% 2001-08-30 and during Superbend commissioning, Christoph Steier, Tom Scarvie, Winni Decking
% various changes have been made to incorporate the Superbends and some other new equipment
% installed in the Superbend shutdown. This included some changes to programs being called by srcontrol
% (like srload, srsave, srcycle, srramp, ...). The main changes within srcontrol were in the orbit
% correction and slow orbit feedback routines (incorporating frequency feedback, ...)
%
% 2002-05-04, Christoph Steier
% added new IDBPMs, modified orbit feedback to use trim DACs, removed LSB toggling in vertical
% orbit feedback, ...
%
% 2002-07-29, T.Scarvie
% added check of CM trim currents to warn of problems that might rail the orbit feedback
%
% 2002-07-31, Christoph Steier
% increased the gain of the RF frequency feedback from 1/50 of the gain of the horizontal
% orbit feedback to 1/20. Reason was that the frequency feedback was reacting a bit too slow if all
% insertion device gaps are closed at once at high speed at the beginning of a fill.
%
% 2002-08-05, C.Steier, T.Scarvie
% Added conditional to reduce orbit feedback gain if running in two-bunch mode
%
% 2003-06-02, T.Scarvie
% Added loop inside orbit feedback to reset the SR11 chicane M1 and M2 motors every 20s to combat drift problem
%
% 2003-06-18, C. Steier
% Disabled loop to periodically reset chicane in SR11. Al Robb replaced power supply, seems to be no problem anymore.
%
% 2004-05-10, C. Steier
% The list of all BBPMs is now set up automatically be calling getlist('BBPMx'). This way, new BBPMs have to be added
% at fewer places in the software. It should now be sufficient to modify getlist and run the orbit response matrix
% rountine (getsmat) once to enable use of the new BBPMs.
%
% 2004-05-14, C. Steier
% Modified parameters for ramprate reduction (in srramp and here). Previous parameters were slightly too
% cautious. Increased initial slow ramprate to 0.4 A/s.
%
% 2004-05-14, C. Steier
% Incorporated insertion device compensation schemes for nu_y = 9.2 lattice.
%
% 2004-06-14, T.Scarvie
% Added controls for fast orbit feedback
%
% 2004-06-21, C. Steier
% Added tune feedforward (in the global tune compensation scheme for the nu_y=9.2 lattice) for the shift
% dependent tune shift of the EPUs, as well as a skew quadrupole feedforward for the EPU im sector 11
% (both only active in parallel mode so far).
%
% 2005-02-13, T.Scarvie
% Separated horizontal and vertical planes for setting Fast Feedback PIDs
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NOTES for conversion to new Middle Layer %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% We never use the gap and bump control flags - the radio buttons have been disabled -
%        should we try to keep the functionality?
%
% remove handle globals
% set(0,'showhiddenhandles','on'); what does this do?
% grampbsc -> should be handled by new srramp (which uses k-values)
% checksrmags
% checksrorbit(...)
% getdcct
% setbpmtimeconstant
% getsmatelements
% Chicane trims are now part of the corrector family
% getname('IDrunflag',...) family name change
% write_goldenorbit_ffb, write_goldenorbit_ffb2
% For the compiler
%#function goldenpage
%#function setoperationalmode
% Check if the AO exists
checkforao;
%%%%%%%%%%%%%%
% Initialize %
%%%%%%%%%%%%%%
global FEEDBACK_STOP_FLAG
SR_Mode = getfamilydata('OperationalMode');
SR_GEV = getfamilydata('Energy');
BSCramprate = getfamilydata('BSCRampRate');
if isnan(BSCramprate) | isempty(BSCramprate)
    BSCramprate = 0.4;
    setfamilydata(BSCramprate, 'BSCRampRate');
end
if nargin < 1
    action = 'Initialize';
end
if nargin < 2
    Input2 = 0;
end
if nargin < 3
    Input3 = 0;
end
if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
    FOFBcheckboxVal = 0;
else
    FOFBcheckboxVal = 1;
end
%%%%%%%%%%%%%%%%
% Main Program %
%%%%%%%%%%%%%%%%
switch(action)
    case 'StopOrbitFeedback'
        FEEDBACK_STOP_FLAG = 1;
    case 'Initialize'
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % GUI
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        ButtonWidth = 200;
        ButtonHeight  = 25;
        Offset1 = 8*25+12 + 47 + 25+25;
        Offset2 = 47+25+25;
        Offset3 = 45+25;
        Offset4 = 1;
        Offset5 = 30;
        FigWidth = ButtonWidth+6;
        FigHeight  = 3+7*(ButtonHeight+6)+24+Offset1;
        ButtonWidth = 200-6;
        % Change figure position
        set(0,'Units','pixels');
        p=get(0,'screensize');
        h0 = figure( ...
            'Color',[0.8 0.8 0.8], ...
            'HandleVisibility','Off', ...
            'Interruptible', 'on', ...
            'MenuBar','none', ...
            'Name','ALS SR CONTROL', ...
            'NumberTitle','off', ...
            'Units','pixels', ...
            'Position',[30 p(4)-FigHeight-40 FigWidth FigHeight+Offset5], ...
            'Resize','off', ...
            'Tag','SRCTRLFig1');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'FontWeight','Bold', ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+6*(ButtonHeight+3)+19+19+8+Offset1  ButtonWidth 20+Offset5], ...
            'Style','text', ...
            'String','', ...
            'Tag','SRCTRLTitle');
        % Frame Box I
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+1*(ButtonHeight+3)+Offset1-3+Offset5 ButtonWidth+6 7*ButtonHeight+18], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+7*(ButtonHeight+3)+Offset1  ButtonWidth 15+Offset5], ...
            'Style','text', ...
            'String','Lattice Setup Functions');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Cycle'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+6*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Cycle SR Lattice', ...
            'Tag','SRCTRLButton1');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Injection'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+5*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Injection', ...
            'Tag','SRCTRLButton2');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Production'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+4*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String',['Production'], ...
            'Tag','SRCTRLButton3');
        h1 = uicontrol('Parent',h0, ...
            'Callback',[...
            'fprintf(''\n'');' ...
            'disp([''   **********************************************'']);', ...
            'disp([''   **  Changing Storage Ring Operational Mode  **'']);', ...
            'disp([''   **********************************************'']);', ...
            'setoperationalmode;', ...
            'srcontrol5(''CheckInputs'');', ...
            'disp([''   ****************************'']);', ...
            'disp([''   **  Mode Change Complete  **'']);', ...
            'disp([''   ****************************'']);', ...
            'fprintf(''\n'');'], ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+3*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'Value',1, ...
            'String','Change Operational Mode', ...
            'Tag','SRCTRLButtonChangeMode');
        h1 = uicontrol(...
            'Parent',h0, ...
            'Callback', [...
            'srcontrol5(''CheckInputs'');',...
            'srcontrol5(''SRState'');'], ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+2*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Check For Problems', ...
            'Tag','SRCTRLButtonSRState');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs''); goldenpage;', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+1*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Golden Page', ...
            'Tag','SRCTRLButtonGoldenPage');
        % Frame Box II
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+7*(ButtonHeight+3)-29+Offset2+Offset5 ButtonWidth+6 2*ButtonHeight+15], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+8*(ButtonHeight+3)-10+Offset2 ButtonWidth .6*ButtonHeight+Offset5], ...
            'String','Global/Local Orbit Correction', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''OrbitCorrection'');', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+7*(ButtonHeight+3)-6+Offset2+Offset5 ButtonWidth ButtonHeight], ...
            'String','Correct Global Orbit w/ IDBPMs', ...
            'Tag','SRCTRLButtonOrbitCorrection');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''OrbitCorrectionSetup'',1);', ...
            'callback','srcontrol5(''OrbitCorrectionSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[6 7*(ButtonHeight+3)-22+Offset2+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Edit IDBPM, CM, & Local Bump Lists', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonOrbitCorrectionSetup');
        % Frame Box III
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 1.25*(ButtonHeight)+Offset3-45+Offset5 ButtonWidth+6 8*ButtonHeight+5], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+7*(ButtonHeight+3)+Offset3-25 ButtonWidth .55*ButtonHeight+Offset5], ...
            'String','Orbit Feedback', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+6*(ButtonHeight+3)+Offset3-18+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Slow Orbit Correction', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxSOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+5*(ButtonHeight+3)+Offset3-9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Fast Orbit Correction', ...
            'Style','checkbox', ...
            'Value',FOFBcheckboxVal,...
            'Tag','SRCTRLCheckboxFOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+4*(ButtonHeight+3)+Offset3+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct ID Tune Shift  ', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxTune');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+3*(ButtonHeight+3)+Offset3+9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct RF Frequency', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxRF');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''Feedback'');', ...
            'Enable','on', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[8 3+3*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Start FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStart');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''StopOrbitFeedback'');pause(0);', ...
            'Enable','off', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[.5*FigWidth+3 3+3*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Stop FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStop');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[14 3+2*(ButtonHeight)+14+Offset3-25+Offset5 ButtonWidth-14 .75*ButtonHeight], ...
            'String','Horizontal RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHorizontal');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[26 3+1.25*(ButtonHeight)+16+Offset3-25+Offset5 ButtonWidth-26 .75*ButtonHeight], ...
            'String','Vertical RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextVertical');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FeedbackSetup'',1);', ...
            'callback','srcontrol5(''FeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 3+1.25*(ButtonHeight)+.5+Offset3-25+Offset5 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit SOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFeedbackSetup');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FastFeedbackSetup'',1);', ...
            'callback','srcontrol5(''FastFeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 3+1.25*(ButtonHeight)+.5+Offset3-45+Offset5 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit FOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFastFeedbackSetup');
        % Frame Box IV
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+ButtonHeight+Offset4-14+Offset5 ButtonWidth+6 ButtonHeight+12], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+1.75*ButtonHeight+5+Offset4-21+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Storage Ring State', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHeader');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''CheckInputs'');', ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ForegroundColor','b', ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+ButtonHeight+6+3+2+Offset4-22+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','   ', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextInformation');
        % Frame Box "Close"
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 8 ButtonWidth+6 ButtonHeight+8], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'Callback','close(gcbf);', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 13 ButtonWidth ButtonHeight], ...
            'String','Close', ...
            'Tag','SRCTRLClose');
        % Update database channels
        setsrstatechannels;
        if nargout > 0
            fig = h0;
        end
    case 'Cycle'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        disp('   **************************');
        disp('   **  Storage Ring Cycle  **');
        disp('   **************************');
        a = clock; fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        BSCFlag = questdlg(sprintf('Cycle Superbend Magnets?'),'SR Cycle','Yes','No','No');
        %if strcmp(BSCFlag,'No')
        %    disp(['   ** Superbends will not be cycled. **']);
        %else
        %    disp(['   ** Superbends will be cycled during the second mini-cycle only. **']);
        %end
        ChicSQFlag = questdlg(sprintf('Cycle chicanes and skew quads and home motor chicanes?'),'SR Cycle','Yes','No','No');
        %if strcmp(ChicSQFlag,'No')
        %    disp(['   ** Chicanes and skew quads will not be cycled; motor chicanes will not be homed. **']);
        %else
        %    disp(['   ** Chicanes and skew quads will be cycled; motor chicanes will be homed. **']);
        %end
        StartFlag = questdlg(sprintf('Start %.1f GeV Cycle?',SR_GEV),'SR Cycle','Yes','No','No');
        if strcmp(StartFlag,'No')
            disp(['   ***************************']);
            disp(['   **    Cycle  Canceled    **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        end
        try
            if GapFlag
                % Make sure that the gaps are open with FF off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open.');
                    disp('   Opening all gaps at maximum speed.');
                    setff([], 1, 0);
                    disp('   Gap control disabled.');
                    disp('   Feed forward enabled.');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened.');
                    disp('   Feed forward and gap control disabled.');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled.');
                end
            else
                disp('   Feed forward and gap control disabled.');
            end
            setff([], 0, 0);
            pause(1);
            srcycle(BSCFlag, ChicSQFlag);
            setpv('SR_STATE',1);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Cycle failed due to error condition! \n\n');
            setpv('SR_STATE',-1);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp('   **********************************************');
            disp('   **  SR Cycle complete, ready for injection  **');
            disp('   **********************************************'); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp('   **********************************');
            disp('   **  Problem cycling SR lattice  **');
            disp('   **********************************'); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
    case 'Injection'
        AD = getad;
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            fprintf('   ***************************************************\n');
            fprintf('   **  Setup For %.2f GeV Injection (with ramping)  **\n', getfamilydata('InjectionEnergy'));
            fprintf('   ***************************************************\n');
            set_alarmhandler_AHU_thresholds_inject;
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',getfamilydata('InjectionEnergy')),'Injection Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            fprintf('   *************************************************\n');
            fprintf('   **  Setup For On Energy Injection at %.2f GeV  **\n', SR_GEV);
            fprintf('   *************************************************\n');
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',SR_GEV),'Injection Setup','Yes','Cancel','Cancel');
        end
        if strcmp(StartFlag,'Cancel')
            disp(['   ********************************']);
            disp(['   **  Injection Setup Canceled  **']);
            disp(['   ********************************']);
            set_alarmhandler_thresholds;
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                setff([],1,0);
                disp('   Gap control disabled');
                disp('   Feed forward enabled');
                pause(1);
                % Set IDs at max velocity w/ velocity profile off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    disp('   Opening all gaps');
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                end
                disp('   Gaps are open');
                disp('   Feed forward and gap control disabled');
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            if (AD.Energy-AD.InjectionEnergy) > 0.05
                % Ramp down to Injection Energy
                ErrorFlag = srramp('Injection');
                if ErrorFlag
                    error('Superbends over temperature.');
                end
                a = clock; fprintf('   %s %d:%d:%.0f\n\n',date, a(4), a(5), a(6));
            elseif (AD.Energy-AD.InjectionEnergy) < -0.05
                % first load injection lattice, then ramp to 1.9 GeV and back to 1.5 GeV to get onto same hysteresis branch
                srload('Injection');
                % load 1.9 GeV lattice
                tempfilename = sprintf('%s19nuy9prod.mat', getfamilydata('Directory','OpsData'));
                srload(tempfilename);
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                pause(5);
            end
            srload('Injection');
            setpv('SR_STATE',2);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Injection lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-2);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            if AD.Energy <= 1.5
                disp(['   *******************************************************************************']);
                disp(['   **  Function complete:  the storage ring is setup for injection at ',sprintf('%.2f',SR_GEV),' GeV  **']);
                disp(['   *******************************************************************************']);
                fprintf('\n');
            else
                fprintf('   **********************************************************************************************\n');
                fprintf('   **  Function complete:  the storage ring is setup for injection at %.2f GeV (upper branch)  **\n', getfamilydata('InjectionEnergy'));
                fprintf('   **********************************************************************************************\n');
                fprintf('\n');
            end
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   ************************************']);
            disp(['   **  Problem with injection setup  **']);
            disp(['   ************************************']);
            fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        %soundchord;
        setfamilydata(0.8, 'BSCRampRate');
    case 'Production'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        AD=getad;
        fprintf('\n');
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            disp('   ********************************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation (with ramping)  **',SR_GEV));
            disp('   ********************************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            disp('   *****************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation  **',SR_GEV));
            disp('   *****************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Yes','Cancel','Cancel');
        end
        if strcmp(StartFlag,'Cancel')
            disp(['   ***************************']);
            disp(['   **  User Setup Canceled  **']);
            disp(['   ***************************']);
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                % Make sure that the gaps are open
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open');
                    disp('   Opening all gaps at maximum speed');
                    setff([], 1, 0);
                    disp('   Gap control disabled');
                    disp('   Feed forward enabled');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened');
                    disp('   Feed forward and gap control disabled');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled');
                end
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            % Ramp up to the production lattice
            ErrorFlag = srramp('Production');
            if ErrorFlag
                error('Superbends over temperature.');
            end
            a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            srload('Production');
            if GapFlag
                setff([], 1, 0);
                disp('   Gap control disabled');
                disp('   Feed forward enable');
                pause(1);
                disp('   Insertion device velocity profile boolean control off');
                disp('   Closing all gaps at maximum speed');
                % Set IDs at max velocity w/ velocity profile off
                [Position, Velocity, RunFlag, UserGap] = getid;
                setid([], UserGap, maxsp('IDvel'), 1, 0, 1);
                % Turn velocity profile on
                disp('   Insertion device velocity profile boolean control is on');
                setid([], [], maxsp('IDvel'), 1, 1, 0);
                disp('   Gaps are closed');
                setff([4;7;8;9;10;12], 1, 1);
                setff(5, 1, 0);
                disp('   Gap control enabled (except sector 5 (W16))');
            end
            set_alarmhandler_thresholds_new;
            setpv('SR_STATE',3);
        catch
            fprintf('   %s \n', lasterr);
            fprintf('   User lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-3);
        end
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp(['   **************************************************************************']);
            disp(['   **  Function complete:  the storage ring is setup for users at ',sprintf('%.1f',SR_GEV),' GeV  **']);
            disp(['   **************************************************************************']); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   *************************************']);
            disp(['   **  Problem with production setup  **']);
            disp(['   *************************************']); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        setfamilydata(0.8, 'BSCRampRate');
    case 'CheckInputs'
        SR_GEV = getfamilydata('Energy');
        AD=getad;
        setsrstatechannels;
        set(0,'showhiddenhandles','on');
        if AD.Energy > 1.55
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Down)']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users (Ramp Up)']);
        elseif AD.Energy < 1.45
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Up+cycle)']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV (Ramp Down)']);
        else
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV']);
        end
        set(findobj('Tag','SRCTRLTitle'),'String',SR_Mode);
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
        else
            set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
        end
        set(0,'showhiddenhandles','off');
    case 'SRState'
        NumErrors = 0;
        fprintf('\n');
        disp('   ***********************************');
        disp('   **  Checking Storage Ring State  **');
        disp('   ***********************************');
        a = clock;
        fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        %       FileName = getpv('SR_LATTICE_FILE','String');   % Last srload file name (in OLD MIDDLE LAYER nomenclature!!)
        GeVnow = bend2gev;
        if GeVnow == getfamilydata('Energy')
            [ConfigSetpoint, ConfigMonitor, FileName] = getproductionlattice;
        elseif GeVnow == getfamilydata('InjectionEnergy')
            [ConfigSetpoint, ConfigMonitor, FileName] = getinjectionlattice;
        else
            FileName = '';
        end
        [StateNumber, StateString] = getsrstate;
        fprintf('   Storage ring operational mode: %s\n', SR_Mode);
        if StateNumber < 0
            fprintf('   Storage ring state error: %s\n', StateString);
            NumErrors = NumErrors + 1;
        else
            fprintf('   Storage ring state: %s\n', StateString);
        end
        if StateNumber==0
            % Storage ring state unknown
            NumErrors = NumErrors + 1;
        elseif abs(StateNumber)==1 || abs(StateNumber)==2
            FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','InjectionFile') '.mat'];
            if ~strcmp(FileName, FileNameGoal)
                fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','InjectionFile'), FileName);
                NumErrors = NumErrors + 1;
            end
        else
            FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile') '.mat'];
            if ~strcmp(FileName, FileNameGoal)
                fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','LatticeFile'), FileName);
                NumErrors = NumErrors + 1;
            end
        end
        % Check all SR magnets
        if isempty(FileName)
            fprintf('   Goal setpoints will not be checked since the last lattice load is unknown.\n');
            NumErrors1 = checksrmags('');
        else
%            NumErrors1 = checksrmags([getfamilydata('Directory','OpsData') FileName]);
            NumErrors1 = checksrmags(FileName);
        end
        if NumErrors1 == 0
            fprintf('   SR magnets power supplies are OK.\n');
        end
        NumErrors = NumErrors + NumErrors1;
        % Check RF frequency
        if isempty(FileName)
            fprintf('   RF frequency will not be checked since the last lattice load is unknown.\n');
        else
%            load([getfamilydata('Directory','OpsData'), FileName]);
            load(FileName);
            [tmp, RFHPCounterPresent] = getrf;
            if abs(RFHPCounterPresent-ConfigSetpoint.RF.Setpoint.Data) > .002
                NumErrors = NumErrors + 1;
                fprintf('   RF frequency should be %f, presently it is %f MHz (as measured by the HP counter).\n', ConfigSetpoint.RF.Setpoint.Data, RFHPCounterPresent);
            else
                fprintf('   RF frequency is OK (HP counter is %f MHz, at the time of the lattice save it was %f MHz).\n', RFHPCounterPresent, ConfigSetpoint.RF.Setpoint.Data);
            end
        end
        % Check for orbit problems
        if (StateNumber >= 3) & (getdcct > 2)   % Production lattice is loaded with beam in the machine
            Xtol = 0.070;
            Ytol = 0.010;
            NumErrors1 = checksrorbit([],Xtol,Ytol);
            if NumErrors1
                fprintf('   SR orbit in the ID straight sections or at Bergoz BPMs deviates more than allowed from the golden orbit.\n');
            else
                fprintf('   SR orbit in the ID straight sections and at Bergoz BPMs is OK.\n');
                fprintf('   The orbit is within %.3f mm horizontally and %.3f mm vertically', Xtol, Ytol);
            end
            NumErrors = NumErrors + NumErrors1;
        else
            fprintf('   Storage ring orbit was not checked.\n');
        end
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        if NumErrors
            disp('   *********************************');
            disp('   **  Storage Ring Has Problems  **');
            disp('   *********************************');
        else
            disp('   **********************************');
            disp('   **  Storage Ring Lattice is OK  **');
            disp('   **********************************');
        end
        fprintf('   \n');
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
        end
        set(0,'showhiddenhandles','off');
    case 'OrbitCorrection'
        fprintf('\n');
        fprintf('   *********************************\n');
        fprintf('   **  Starting Orbit Correction  **\n');
        fprintf('   *********************************\n');
        a = clock;
        fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        StartFlag = questdlg(sprintf('Start orbit correction, %.1f GeV?',SR_GEV),'Orbit Correction','Yes','No','No');
        if strcmp(StartFlag,'No')
            disp(['   ********************************']);
1000             disp(['   **  Orbit Correction Aborted  **']);
1001             disp(['   ********************************']);
1002             fprintf('\n');
1003             return
1004         end
1005
1006         if getdcct < 5     % Don't correct the orbit if the current is too small
1007             fprintf('   Orbit not corrected due to small current.\n');
1008             return
1009         end
1010
1011         if abs(SR_GEV-bend2gev(getpv('BEND',[1 1])))>  0.05     % Don't use this routine for the injection lattice
1012             fprintf('   This routine should only be used for the production energy: Correction aborted\n');
1013             return
1014         end
1015
1016         SR_STATE_OLD = scaget('SR_STATE');
1017         set(0,'showhiddenhandles','on');
1018         setpv('SR_STATE',4);
1019         [StateNumber, StateString] = getsrstate;
1020         if StateNumber >= 0
1021             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1022         else
1023             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1024         end
1025         set(0,'showhiddenhandles','off');
1026
1027
1028         try
1029
1030             % 2 Hz update rate on IDBPMs
1031             disp('   IDBPM time constant set to 0.5s.')
1032             setbpmtimeconstant(0.5)
1033             pause(2);
1034
1035
1036             % Turn off feed forward
1037             fprintf('   Turning feed forward off.\n');
1038             [FFEnableBM, FFEnableBC] = getff;
1039             setff([], 0);
1040             scasleep(.2);
1041
1042
1043             % Get vectors
1044             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1045             LocalBumplist = FB.LocalBumplist;
1046
1047         catch
1048
1049             fprintf('   %s \n',lasterr);
1050             fprintf('   Orbit correction setup failed due to error condition! \n\n');
1051             setpv('SR_STATE',-4);
1052             set(0,'showhiddenhandles','on');
1053             [StateNumber, StateString] = getsrstate;
1054             if StateNumber >= 0
1055                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1056             else
1057                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1058             end
1059             set(0,'showhiddenhandles','off');
1060             return
1061
1062         end
1063
1064         iNotHCMChicane = find(FB.HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
1065         iHCMChicane = find(FB.HCMlist1(:,2) == 10);
1066         iNotVCMChicane = find(FB.VCMlist1(:,2) < 10);
1067         iVCMChicane = find(FB.VCMlist1(:,2) == 10);
1068
1069         fprintf('   Starting horizontal and vertical global orbit correction (SVD method).\n');
1070
1071         for iloop = 1:3
1072             try
1073                 % use the following to get corrector settings in OCS without setting them, so the values can be checked
1074                 FB.OCSx = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
1075                 FB.OCSy = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
1076                 if any(abs(FB.OCSx.CM.Delta(iNotHCMChicane)) > 5)
1077                   disp('   Orbit Correction is changing some horizontal corrector(s) > 5A!!');
1078                 end
1079                 if any(abs(FB.OCSy.CM.Delta(iNotVCMChicane)) > 5)
1080                   disp('   Orbit Correction is changing some vertical corrector(s) > 5A!!');
1081                 end
1082                 if any(abs(FB.OCSx.CM.Delta(iHCMChicane)) > 10)
1083                   disp('   Orbit Correction is changing some horizontal chicane corrector(s) > 10A!!');
1084                 end
1085                 if any(abs(FB.OCSy.CM.Delta(iVCMChicane)) > 10)
1086                   disp('   Orbit Correction is changing some vertical chicane corrector(s) > 10A!!');
1087                 end
1088
1089
1090                 % Correct horizontal orbit
1091                 FB.OCSx = setorbit(FB.OCSx,'NoDisplay');
1092                 % Correct vertical orbit
1093                 FB.OCSy = setorbit(FB.OCSy,'NoDisplay');
1094
1095
1096                 % Check for current in machine - stop orbit correction if DCCT < 5mA
1097                 if (getdcct < 4.5)
1098                     error('**There is less than 5mA in the machine! Stopping orbit correction.');
1099                 end
1100
1101                 % Check state of gaps - stop orbit correction if any are moving
1102                 GAPrunflag = getpv('ID','RunFlag');
1103                 if any(GAPrunflag-round(GAPrunflag))
1104                     error('**One or more of the gaps are moving! Stopping orbit correction.');
1105                 end
1106
1107                 x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
1108                 y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
1109                 fprintf('   %d. Horizontal RMS = %.3f mm\n', iloop, norm(x)/sqrt(length(x)));
1110                 fprintf('   %d.   Vertical RMS = %.3f mm\n', iloop, norm(y)/sqrt(length(y)));
1111
1112             catch
1113                 % fprintf('   %s \n',lasterr);
1114                 fprintf('   Orbit correction failed due to error condition!\n  Fix the problem, reload the lattice (srload), and try again.  \n\n');
1115                 setpv('SR_STATE',-4);
1116                 set(0,'showhiddenhandles','on');
1117                 [StateNumber, StateString] = getsrstate;
1118                 if StateNumber >= 0
1119                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1120                 else
1121                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1122                 end
1123                 set(0,'showhiddenhandles','off');
1124                 return
1125             end
1126         end
1127
1128
1129         % Set user bumps w/o sextupole correctors
1130         try
1131
1132             %turn up corrector speed here to quicken setting bumps
1133             HCMramprate = getpv('HCM', 'RampRate');
1134             VCMramprate = getpv('VCM', 'RampRate');
1135             setpv('HCM', 'RampRate', 10, [], 0);
1136             setpv('VCM', 'RampRate', 10, [], 0);
1137
1138             if ~isempty(LocalBumplist)
1139                 fprintf('   Setting local bumps in the straight sections.\n');
1140                 for loop = 1:size(LocalBumplist,1)
1141
1142                     % Check for current in machine - stop orbit correction if DCCT < 5mA
1143                     if (getdcct < 5)
1144                         error('** There is less than 5mA in the machine! Stopping local bumps.');
1145                     end
1146
1147                     % Check state of gaps - stop setting bumps if any are moving
1148                     GAPrunflag = getpv('ID','RunFlag');
1149                     if any(GAPrunflag-round(GAPrunflag))
1150                         error('** One or more of the gaps are moving! Stopping local bumps.');
1151                     end
1152
1153                     HCMoldsp = getsp('HCM', FB.HCMlist1);
1154                     VCMoldsp = getsp('VCM', FB.VCMlist1);
1155
1156                     if any(LocalBumplist(loop,1) == [4 6 11])
1157                         if LocalBumplist(loop,2) == 0
1158                             % Upstream bump
1159                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1160                             if isempty(iRemove)
1161                                 setbumps(LocalBumplist(loop,:), 1);
1162                             else
1163                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1164                             end
1165                         elseif LocalBumplist(loop,2) == 1
1166                             % Upstream bump
1167                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;],FB.OCSx.BPM.DeviceList);
1168                             if isempty(iRemove)
1169                                 setbumps(LocalBumplist(loop,:), 1);
1170                             else
1171                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1172                             end
1173                         else
1174                             % Downstream bump
1175                             [i, iRemove] = findrowindex([LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1176                             if isempty(iRemove)
1177                                 setbumps(LocalBumplist(loop,:), 1);
1178                             else
1179                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1180                             end
1181                         end
1182                     else
1183                         [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1184                         if isempty(iRemove)
1185                             setbumps(LocalBumplist(loop,:), 1);
1186                         else
1187                             fprintf('\n   BPMs missing from Sector %02d - skipping local bump for that sector.\n\n', LocalBumplist(loop,1));
1188                         end
1189                     end
1190
1191                     HCMnewsp = getsp('HCM', FB.HCMlist1);
1192                     VCMnewsp = getsp('VCM', FB.VCMlist1);
1193                     % Remove center chicane trim from corrector check
1194                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 5) | (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 10)
1195                         error('**Setbumps caused some corrector magnet currents to change by more than 5(Horiz)/10(Vert) A!');
1196                     end
1197                     % Now check center chicane trims
1198                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 10) | (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 15)
1199                         error('**Setbumps caused some chicane trim magnet currents to change by more than 10(Horiz)/15(Vert) A!');
1200                     end
1201                 end
1202             end
1203
1204             %restore corrector speeds
1205             setpv('HCM', 'RampRate', HCMramprate, [], 0);
1206             setpv('VCM', 'RampRate', VCMramprate, [], 0);
1207
1208         catch
1209             fprintf('   %s \n',lasterr);
1210             fprintf('   Setbumps failed due to error condition!  Fix the problem, reload the lattice (srload), and try again.\n\n');
1211             setpv('SR_STATE',-4);
1212             set(0,'showhiddenhandles','on');
1213             [StateNumber, StateString] = getsrstate;
1214             if StateNumber >= 0
1215                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1216             else
1217                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1218             end
1219             set(0,'showhiddenhandles','off');
1220             return
1221         end
1222
1223
1224         % Turn feed forward back to it's original state
1225         if any(FFEnableBC)
1226             fprintf('   Turning feed forward back on.\n');
1227             setff([], FFEnableBC);
1228         end
1229
1230
1231         a = clock;
1232         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1233         [StateNumber, StateString] = getsrstate;
1234         set(0,'showhiddenhandles','on');
1235         if StateNumber >= 0
1236             setpv('SR_STATE',4.1);
1237             [StateNumber, StateString] = getsrstate;
1238             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1239             fprintf('   *********************************\n');
1240             fprintf('   **  Orbit Correction Complete  **\n');
1241             fprintf('   *********************************\n\n');
1242         else
1243             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1244             fprintf('   *************************************\n');
1245             fprintf('   **  Problem With Orbit Correction  **\n');
1246             fprintf('   *************************************\n\n');
1247         end
1248         set(0,'showhiddenhandles','off');
1249         pause(0);
1250
1251
1252     case 'OrbitCorrectionSetup'
1253         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
1254
1255         if InitFlag
1256             % Setup feedback elements
1257             % disp('Orbit correction condition: InitFlag=1 -- debugging message');
1258
1259             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1260             % Edit the following lists to change default configuration of Orbit Correction %
1261             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1262             hlist=[];vlist=[];
1263             for Sector =1:12
1264                 if Sector == 1
1265                     vlist = [vlist;Sector 2;Sector 4;Sector 5;Sector 8];
1266                     hlist = [hlist;Sector 2;Sector 7];
1267                 elseif Sector == 3
1268                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1269                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1270                 elseif Sector == 5
1271                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1272                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1273                 elseif Sector == 10
1274                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1275                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1276                 elseif Sector == 12
1277                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 7];
1278                     hlist = [hlist;Sector 2;Sector 7];
1279                 else
1280                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8];
1281                     hlist = [hlist;Sector 2;Sector 7];
1282                 end
1283             end
1284             HCMlist1 = hlist;
1285             VCMlist1 = vlist;
1286
1287             BPMlist1 = [
1288                 1 2
1289                 1 5
1290                 1 6
1291                 1 10
1292                 2 1
1293                 2 5
1294                 2 6
1295                 2 9
1296                 3 2
1297                 3 5
1298                 3 6
1299                 3 10
1300                 3 11
1301                 3 12
1302                 4 1
1303                 4 5
1304                 4 6
1305                 4 10
1306                 5 1
1307                 5 5
1308                 5 6
1309                 5 10
1310                 5 11
1311                 5 12
1312                 6 1
1313                 6 5
1314                 6 6
1315                 6 10
1316                 7 1
1317                 7 5
1318                 7 6
1319                 7 10
1320                 8 1
1321                 8 5
1322                 8 6
1323                 8 10
1324                 9 1
1325                 9 5
1326                 9 6
1327                 9 10
1328                 10 1
1329                 10 5
1330                 10 6
1331                 10 10
1332                 10 11
1333                 10 12
1334                 11 1
1335                 11 5
1336                 11 6
1337                 11 10
1338                 12 1
1339                 12 5
1340                 12 6
1341                 12 9];
1342
1343             % SVD orbit correction
1344             Xivec = [1:28];
1345             Yivec = [1:48];
1346
1347
1348             LocalBumplist = [
1349               % 1 1
1350               % 2 1
1351               % 3 1
1352                 4 1
1353               % 4 2
1354                 5 1
1355                 6 1
1356               % 6 2
1357                 7 1
1358                 8 1
1359                 9 1
1360                 10 1
1361                 11 1
1362                 11 2
1363                 12 1
1364 ];
1365             %LocalBumplist = []
1366
1367             % initialize RFCorrFlag
1368             RFCorrFlag = 'Yes';
1369         else
1370
1371             % Get vectors
1372             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1373             BPMlist1 = FB.BPMlist1;
1374             HCMlist1 = FB.HCMlist1;
1375             VCMlist1 = FB.VCMlist1;
1376             Xivec = FB.Xivec;
1377             Yivec = FB.Yivec;
1378             LocalBumplist = FB.LocalBumplist;
1379             Xgoal = FB.Xgoal;
1380             Ygoal = FB.Ygoal;
1381             RFCorrFlag = FB.RFCorrFlag;
1382
1383             % Add button to change #ivectors, CMs, IDBPMs,
1384             EditFlag = 0;
1385             h_fig1 = figure;
1386             while EditFlag ~= 8
1387
1388                 % Sensitivity matrix
1389                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
1390                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
1391
1392                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1393                 % Can the call below work for setting FOFB RF parameter? %
1394                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1395                 if strcmpi(RFCorrFlag, 'Yes')
1396                     Sx = [Sx getdisp('BPMx',BPMlist1)];
1397                 end
1398
1399                 [Ux, SVx, Vx] = svd(Sx);
1400                 [Uy, SVy, Vy] = svd(Sy);
1401
1402
1403                 % Remove singular values greater than the actual number of singular values
1404                 i = find(Xivec>length(diag(SVx)));
1405                 if ~isempty(i)
1406                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
1407                     pause(0);
1408                     Xivec(i) = [];
1409                 end
1410                 i = find(Yivec>length(diag(SVy)));
1411                 if ~isempty(i)
1412                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
1413                     pause(0);
1414                     Yivec(i) = [];
1415                 end
1416
1417
1418                 Ax = Sx*Vx(:,Xivec);
1419                 Tx = inv(Ax'*Ax)*Ax';
1420
1421                 Ay = Sy*Vy(:,Yivec);
1422                 Ty = inv(Ay'*Ay)*Ay';
1423
1424
1425                 figure(h_fig1);
1426                 subplot(2,1,1);
1427                 semilogy(diag(SVx),'b');
1428                 hold on;
1429                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
1430                 ylabel('Horizontal');
1431                 title('Response Matrix Singular Values');
1432                 hold off;
1433                 subplot(2,1,2);
1434                 semilogy(diag(SVy),'b');
1435                 hold on;
1436                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
1437                 xlabel('Singular Value Number');
1438                 ylabel('Vertical');
1439                 hold off;
1440                 drawnow;
1441
1442                 if strcmp(RFCorrFlag,'No')
1443                     RFCorrState = 'NOT CORRECTED';
1444                 elseif strcmp(RFCorrFlag,'Yes')
1445                     RFCorrState = 'CORRECTED';
1446                 else
1447                     RFCorrState = '???';
1448                 end
1449
1450                 %         EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','HCM Chicane List','VCM Chicane List','IDBPM List','BBPM List','Change Golden Orbit',...
1451                 %            'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1452                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','BPM List','Change Golden Orbit',...
1453                     'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1454
1455                 if EditFlag == 1
1456                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
1457                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
1458                     titlestr='SVD Orbit Feedback';
1459                     lineNo=1;
1460                     answer=inputdlg(prompt,titlestr,lineNo,def);
1461                     if ~isempty(answer)
1462                         XivecNew = fix(str2num(answer{1}));
1463                         if isempty(XivecNew)
1464                             disp('   Horizontal E-vector cannot be empty.  No change made.');
1465                         else
1466                             if any(XivecNew<=0) | max(XivecNew)>length(diag(SVx))
1467                                 disp('   Error reading horizontal E-vector.  No change made.');
1468                             else
1469                                 Xivec = XivecNew;
1470                             end
1471                         end
1472                         YivecNew = fix(str2num(answer{2}));
1473                         if isempty(YivecNew)
1474                             disp('   Vertical E-vector cannot be empty.  No change made.');
1475                         else
1476                             if any(YivecNew<=0) | max(YivecNew)>length(diag(SVy))
1477                                 disp('   Error reading vertical E-vector.  No change made.');
1478                             else
1479                                 Yivec = YivecNew;
1480                             end
1481                         end
1482                     end
1483                 end
1484
1485                 if EditFlag == 2
1486                     List = getlist('HCM');
1487                     CheckList = zeros(size(List,1));
1488                     Elem = dev2elem('HCM', HCMlist1);
1489                     CheckList(Elem) = ones(size(Elem));
1490                     CheckList = CheckList(dev2elem('HCM',List));
1491                     newList = editlist(List, 'HCM', CheckList);
1492                     if isempty(newList)
1493                         fprintf('   Horizontal corrector magnet list cannot be empty.  No change made.\n');
1494                     else
1495                         HCMlist1 = newList;
1496                     end
1497                 end
1498
1499                 if EditFlag == 3
1500                     List = getlist('VCM');
1501                     CheckList = zeros(size(List,1));
1502                     Elem = dev2elem('VCM', VCMlist1);
1503                     CheckList(Elem) = ones(size(Elem));
1504                     CheckList = CheckList(dev2elem('VCM',List));
1505                     newList = editlist(List, 'VCM', CheckList);
1506                     if isempty(newList)
1507                         fprintf('   Vertical corrector magnet cannot be empty.  No change made.\n');
1508                     else
1509                         VCMlist1 = newList;
1510                     end
1511                 end
1512
1513                 if EditFlag == 4
1514                     ListOld = BPMlist1;
1515                     XgoalOld = Xgoal;
1516                     YgoalOld = Ygoal;
1517
1518                     % Full BPM list
1519                     List = [
1520                         1 2
1521                         1 5
1522                         1 6
1523                         1 10
1524                         2 1
1525                         2 5
1526                         2 6
1527                         2 9
1528                         3 2
1529                         3 5
1530                         3 6
1531                         3 10
1532                         3 11
1533                         3 12
1534                         4 1
1535                         4 5
1536                         4 6
1537                         4 10
1538                         5 1
1539                         5 5
1540                         5 6
1541                         5 10
1542                         5 11
1543                         5 12
1544                         6 1
1545                         6 5
1546                         6 6
1547                         6 10
1548                         7 1
1549                         7 5
1550                         7 6
1551                         7 10
1552                         8 1
1553                         8 5
1554                         8 6
1555                         8 10
1556                         9 1
1557                         9 5
1558                         9 6
1559                         9 10
1560                         10 1
1561                         10 5
1562                         10 6
1563                         10 10
1564                         10 11
1565                         10 12
1566                         11 1
1567                         11 5
1568                         11 6
1569                         11 10
1570                         12 1
1571                         12 5
1572                         12 6
1573                         12 9
1574                         ];
1575
1576                     CheckList = zeros(size(List,1),1);
1577                     if ~isempty(BPMlist1)
1578                         for i = 1:size(List,1)
1579                             k = find(List(i,1)==BPMlist1(:,1));
1580                             l = find(List(i,2)==BPMlist1(k,2));
1581
1582                             if isempty(k) | isempty(l)
1583                                 % Item not in list
1584                             else
1585                                 CheckList(i) = 1;
1586                             end
1587                         end
1588                     end
1589
1590                     newList = editlist(List, 'BPM', CheckList);
1591                     if isempty(newList)
1592                         fprintf('   BPM list cannot be empty.  No change made.\n');
1593                     else
1594                         BPMlist1 = newList;
1595                     end
1596
1597                     % Set the goal orbit to the golden orbit
1598                     Xgoal = getgolden('BPMx', BPMlist1);
1599                     Ygoal = getgolden('BPMy', BPMlist1);
1600
1601
1602                     % If a new BPM is added, then set the goal orbit to the golden orbit
1603                     for i = 1:size(BPMlist1,1)
1604
1605                         % Is it a new BPM?
1606                         k = find(BPMlist1(i,1)==ListOld(:,1));
1607                         l = find(BPMlist1(i,2)==ListOld(k,2));
1608
1609                         if isempty(k) | isempty(l)
1610                             % New BPM
1611                         else
1612                             % Use the old value for old BPM
1613                             Xgoal(i) = XgoalOld(k(l));
1614                             Ygoal(i) = YgoalOld(k(l));
1615                         end
1616                     end
1617                 end
1618
1619                 if EditFlag == 5
1620
1621                     ChangeList = editlist(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
1622                     for i = 1:size(ChangeList,1)
1623
1624                         k = find(ChangeList(i,1)==BPMlist1(:,1));
1625                         l = find(ChangeList(i,2)==BPMlist1(k,2));
1626
1627                         prompt = {sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
1628                         def = {sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
1629                         titlestr = 'CHANGE THE GOAL ORBIT';
1630                         lineNo = 1;
1631                         answer = inputdlg(prompt, titlestr, lineNo, def);
1632
1633                         if isempty(answer)
1634                             % No change
1635                             fprintf('   No change was made to the golden orbit.\n');
1636                         else
1637                             Xgoalnew = str2num(answer{1});
1638                             if isempty(Xgoalnew)
1639                                 fprintf('   No change was made to the horizontal golden orbit.\n');
1640                             else
1641                                 Xgoal(k(l)) = Xgoalnew;
1642                             end
1643
1644                             Ygoalnew = str2num(answer{2});
1645                             if isempty(Ygoalnew)
1646                                 fprintf('   No change was made to the vertical golden orbit.\n');
1647                             else
1648                                 Ygoal(k(l)) = Ygoalnew;
1649                             end
1650                         end
1651                     end
1652                     if ~isempty(ChangeList)
1653                         fprintf('   Note:  changing the goal orbit for "Orbit Correction" does not change the goal orbit for "Slow Orbit Feedback."\n');
1654                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
1655                     end
1656                 end
1657
1658                 if EditFlag == 6
1659                     List = [
1660                         1 1
1661                         2 1
1662                         3 1
1663                         4 1
1664                         4 2
1665                         5 1
1666                         6 1
1667                         6 2
1668                         7 1
1669                         8 1
1670                         9 1
1671                         10 1
1672                         11 1
1673                         11 2
1674                         12 1];
1675                     CheckList = zeros(size(List,1),1);
1676                     if ~isempty(LocalBumplist)
1677                         for i = 1:size(List,1)
1678                             k = find(List(i,1)==LocalBumplist(:,1));
1679                             l = find(List(i,2)==LocalBumplist(k,2));
1680
1681                             if isempty(k) | isempty(l)
1682                                 % Item not in list
1683                             else
1684                                 CheckList(i) = 1;
1685                             end
1686                         end
1687                     end
1688                     LocalBumplist = editlist2(List, 'Sector', CheckList);
1689                 end
1690
1691                 if EditFlag == 7
1692                     RFCorrFlag = questdlg(sprintf('Set RF Frequency during Orbit Correction?'),'RF Frequency','Yes','No', 'No');
1693                     if strcmp(RFCorrFlag,'No')
1694                         disp(['   RF Frequency will not be included in global orbit correction.']);
1695                     elseif strcmp(RFCorrFlag,'Yes')
1696                         disp(['   RF Frequency will be included in global orbit correction.']);
1697                     end
1698
1699                 end
1700             end
1701             close(h_fig1);
1702         end
1703
1704 %  ORBIT CORRECTION STRUCTURE (OCS)
1705 %    OCS.BPM (data structure)
1706 %    OCS.CM  (data structure)
1707 %    OCS.GoalOrbit
1708 %    OCS.NIter
1709 %    OCS.SVDIndex
1710 %    OCS.IncrementalFlag = 'Yes'/'No'
1711 %    OCS.BPMWeight
1712 %    OCS.Flags = { 'FitRF' , etc.  }
1713         OCSx.BPM = getx(BPMlist1, 'struct');
1714         OCSx.CM = getsp('HCM', HCMlist1, 'struct');
1715         OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
1716         OCSx.NIter = 1;
1717         OCSx.SVDIndex = Xivec;
1718         OCSx.IncrementalFlag = 'No';
1719         OCSx.FitRF = 1;
1720         OCSy.BPM = gety(BPMlist1, 'struct');
1721         OCSy.CM = getsp('VCM', VCMlist1, 'struct');
1722         OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
1723         OCSy.NIter = 1;
1724         OCSy.SVDIndex = Yivec;
1725         OCSy.IncrementalFlag = 'No';
1726         OCSy.FitRF = 0;
1727
1728         % Save vectors
1729         FB.OCSx = OCSx;
1730         FB.OCSy = OCSy;
1731
1732         FB.BPMlist1 = BPMlist1;
1733         FB.HCMlist1 = HCMlist1;
1734         FB.VCMlist1 = VCMlist1;
1735         FB.Xivec = Xivec;
1736         FB.Yivec = Yivec;
1737         FB.Xgoal = OCSx.GoalOrbit;
1738         FB.Ygoal = OCSy.GoalOrbit;
1739         FB.RFCorrFlag = RFCorrFlag;
1740         FB.LocalBumplist = LocalBumplist;
1741         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata',FB);
1742
1743
1744     case 'Feedback'
1745
1746         FBloopIter = 1;
1747         if get(findobj(gcbf,'Tag','SRCTRLCheckboxFOFB'),'Value') == 1
1748             StartFOFBFlag = 1;
1749         else
1750             StartFOFBFlag = 0;
1751         end
1752
1753         FEEDBACK_STOP_FLAG = 0;
1754         HWarnNum=0;
1755         VWarnNum=0;
1756
1757         SR_GeV = getenergy;
1758         % Feedback loop setup
1759         PlotInfoFlag = 0;           % Plot micado stuff
1760         LoopDelay = 1.0;           % Period of feedback loop [seconds], make sure the BPM averaging is correct
1761         VCM_LSB = .00366211;
1762         VCMCHICANE_LSB = .002441;   % 80 max?,  Note: not fully implemented
1763
1764         if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
1765             Xgain  = 0.2;
1766             Ygain  = 0.1;
1767         else
1768             Xgain  = 0.8; % raised 0.5->0.8 at 17:20, 3-2-05 to more quickly correct EPU4 fast switching orbit distortions
1769             Ygain  = 0.8;
1770         end
1771
1772         % Load lattice set for tune feed forward
1773         ConfigSetpoint = getproductionlattice;
1774         %load([getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile')]);
1775         QFsp = ConfigSetpoint.QF.Setpoint.Data;
1776         QDsp = ConfigSetpoint.QD.Setpoint.Data;
1777         TuneW16Min = gap2tune(5, 13.23, 1.8909);
1778         % Tune response matrix
1779         SR_TUNE_MATRIX = gettuneresp({'QF','QD'}, {[],[]}, getenergy('Production'));    % Approx. [0.1944 -0.0286;-0.1182 0.1526];
1780         %SR_TUNE_MATRIX = [0.1641 -0.0245
1781         %                 -0.1149 0.1477];
1782
1783         % ID tune compensation does not work in the injection lattice, so ...
1784         if abs(SR_GEV - bend2gev)>  0.05     % Don't use this routine for the injection lattice
1785             fprintf('   This routine should only be used for the production energy: Orbit feedback aborted\n');
1786             return
1787         end
1788
1789         set(0,'showhiddenhandles','on');
1790
1791         try
1792             fprintf('\n');
1793             fprintf('   *******************************\n');
1794             fprintf('   **  Starting Orbit Feedback  **\n');
1795             fprintf('   *******************************\n');
1796             a = clock;
1797             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1798             fprintf('   Note: the Matlab command window will be used to display status information.\n');
1799             fprintf('         It cannot be used to enter commands during slow orbit feedback.\n');
1800
1801
1802             % >= 2 Hz update rate on IDBPMs
1803             disp('   IDBPM time constant set to 0.2s.')
1804             setbpmtimeconstant(0.2)
1805             pause(1.1);
1806
1807             % Check whether bumps and kickers are on and warn to turn off before starting feedback if necessary
1808             try
1809                 if (getsp('SR01S___BUMP1__BC21')==1 & getsp('SR01S___BUMP1P_BC22')==1) | (getsp('SR01S___SEK____BC21')==1 & getsp('SR01S___SEK_P__BC23')==1) | (getsp('SR01S___SEN____BC20')==1 & getsp('SR01S___SEN_P__BC22')==1)
1810                     soundtada;
1811                     fprintf('   \n');
1812                     fprintf('   *********************************************************************************\n');
1813                     fprintf('   ** One or more of the pulsed SR injection magnets is still on!  Turn them off! **\n');
1814                     fprintf('   *********************************************************************************\n');
1815                     fprintf('   \n');
1816                 end
1817             catch
1818                 disp('**Problem checking the state of the bumps and kickers - please check that they are not pulsing.');
1819             end
1820
1821             % Get vectors
1822
1823             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
1824
1825             BPMlist1 = FB.OCSx.BPM.DeviceList;
1826             % FOFB_BPMlist =
1827             HCMlist1 = FB.HCMlist1;
1828             VCMlist1 = FB.VCMlist1;
1829             Xivec = FB.Xivec;
1830             Yivec = FB.Yivec;
1831             Xgoal = FB.OCSx.GoalOrbit;
1832             Ygoal = FB.OCSy.GoalOrbit;
1833             FFTypeFlag = FB.FFTypeFlag;   %local or global tune correction
1834
1835             iNotHCMChicane = find(HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
1836             iHCMChicane = find(HCMlist1(:,2) == 10);
1837             iNotVCMChicane = find(VCMlist1(:,2) < 10);
1838             iVCMChicane = find(VCMlist1(:,2) == 10);
1839
1840             % Sensitivity matrix for setting fast feedback setpoints
1841             Sx1 = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
1842             Sy1 = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
1843
1844         catch
1845             fprintf('\n  %s \n',lasterr);
1846
1847             % >= 2 Hz update rate on IDBPMs
1848             disp('   IDBPM time constant set to 0.25s.')
1849             setbpmtimeconstant(0.25)
1850
1851
1852             a = clock;
1853             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1854             fprintf('   *************************************************************\n');
1855             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
1856             fprintf('   *************************************************************\n\n');
1857             set(0,'showhiddenhandles','off');
1858             pause(0);
1859
1860             return
1861         end
1862
1863         StartFlag = questdlg(strvcat('','Is it OK to start orbit feedback?'),'Orbit Feedback','Yes','No','No');
1864         if strcmp(StartFlag,'No')
1865             % >= 2 Hz update rate on IDBPMs
1866             disp('   IDBPM time constant set to 0.25s.')
1867             setbpmtimeconstant(0.25)
1868
1869             a = clock;
1870             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1871             fprintf('   ***************************\n');
1872             fprintf('   **  Orbit Feedback Exit  **\n');
1873             fprintf('   ***************************\n\n');
1874             pause(0);
1875             return
1876         end
1877
1878         SR_STATE_OLD = scaget('SR_STATE');
1879         setpv('SR_STATE', 5);
1880         set(0,'showhiddenhandles','on');
1881         [StateNumber, StateString] = getsrstate;
1882         if StateNumber >= 0
1883             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1884         else
1885             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1886         end
1887         fprintf('   Using %d E-vectors horizontally.\n', length(Xivec));
1888         fprintf('   Using %d E-vectors vertically.\n',   length(Yivec));
1889         fprintf('   Starting slow orbit correction every %.1f seconds.\n', LoopDelay);
1890         %  fprintf('   Resetting SR11 chicane motors every 20 seconds to fix drift problem.\n');
1891
1892         IDSector = getlist('ID');
1893         EPUlist = find((IDSector(:,1)==4) | (IDSector(:,1)==11));
1894         oldgap=210*ones(size(getlist('ID')),1);
1895           oldShift=zeros(size(oldgap));
1896
1897         try
1898
1899             % Get and display data
1900             x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
1901             y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
1902             STDx = norm(x)/sqrt(length(x));
1903             STDy = norm(y)/sqrt(length(y));
1904             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
1905             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
1906
1907             % write goldenorbit values to Fast Orbit Feedback
1908             try
1909                 write_goldenorbit_ffb;
1910             catch
1911                 disp('write_goldenorbit_ffb did not work!');
1912             end
1913             setpv('SR01____FFBON__BC00',2);
1914             pause(0);
1915
1916         catch
1917
1918             fprintf('\n  %s \n',lasterr);
1919
1920             % >= 2 Hz update rate on IDBPMs
1921             disp('   IDBPM time constant set to 0.25s.')
1922             setbpmtimeconstant(0.25);
1923
1924
1925             a = clock;
1926             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1927             fprintf('   *************************************************************\n');
1928             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
1929             fprintf('   *************************************************************\n\n');
1930
1931             setpv('SR_STATE',SR_STATE_OLD);
1932             [StateNumber, StateString] = getsrstate;
1933             if StateNumber >= 0
1934                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1935             else
1936                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1937             end
1938             set(0,'showhiddenhandles','off');
1939             pause(0);
1940
1941             return
1942
1943         end
1944
1945
1946         % Disable buttons
1947         set(0,'showhiddenhandles','on');
1948         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','off');
1949         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','on');
1950         set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','off');
1951         set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','off');
1952         set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','off');
1953         set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','off');
1954         set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','off');
1955         set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','off');
1956         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','off');
1957         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','off');
1958         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','off');
1959         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','off');
1960         set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','off');
1961         pause(0);
1962
1963
1964         % Initialize feedback loop
1965         StartTime = gettime;
1966         StartErrorTime = gettime;
1967         Xold = getx(FB.OCSx.BPM.DeviceList);
1968         Yold = gety(FB.OCSy.BPM.DeviceList);
1969         HQMOFM_stalenum = 0;
1970         pause(LoopDelay);
1971
1972         N_HCM = size(HCMlist1,1);
1973         N_VCM = size(VCMlist1,1);
1974
1975         N_RFMO = 1;
1976
1977         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
1978             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'SetRF','Nodisplay','Nosetsp');
1979         else
1980             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
1981         end
1982         [FB.OCSx, Smatx, Sx, Ux, Vx] = orbitcorrectionmethods(FB.OCSx);
1983
1984         [FB.OCSy, junk, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
1985         [FB.OCSy, Smaty, Sy, Uy, Vy] = orbitcorrectionmethods(FB.OCSy);
1986
1987
1988         %%%%%%%%%%%%%%%%%%%%%%%
1989         % Start feedback loop %
1990         %%%%%%%%%%%%%%%%%%%%%%%
1991
1992         % chicaneloop=1;  % loop variable for resetting drifting chicanes (see a few lines below)
1993         % fftest=figure;
1994
1995         setpv('SR01____FFBON__BC00',2); % put FOFB in open loop so beamnoise gets recorded even if FOFB is not enabled
1996
1997         while 1
1998             try
1999                 t00 = gettime;
2000
2001                 %          if chicaneloop==20 % reset SR11 motor chicane setpoints every 20s due to drifting positions
2002                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(6),[11 1],0);
2003                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(7),[11 2],0);
2004                 %             chicaneloop = 1;
2005                 %          else
2006                 %             chicaneloop = chicaneloop + 1;
2007                 %          end
2008
2009                 % Check if GUI has been closed
2010                 if isempty(gcbf)
2011                     FEEDBACK_STOP_FLAG = 1;
2012                     lasterr('SRCONTROL GUI DISAPPEARED!');
2013                     error('SRCONTROL GUI DISAPPEARED!');
2014                 end
2015
2016                 %%%%%%%%%%%%%%%%%%%%%%%
2017                 % Fast orbit feedback %
2018                 %%%%%%%%%%%%%%%%%%%%%%%
2019                 if StartFOFBFlag == 1 & FBloopIter > 3
2020                     setpv('SR01____FFBON__BC00',2);
2021                     pause(0.5);
2022                     setpv('SR01____FFBON__BC00',1);
2023                     StartFOFBFlag = 0;
2024                     pause(1);
2025                     FOFBOnStatus = [getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2026                         getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2027                         getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2028                         getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2029                     if any(FOFBOnStatus==0) | any(FOFBOnStatus==2)
2030                         setpv('SR01____FFBON__BC00',2); % open FOFB loop
2031                         disp('************************************************************************************************************');
2032                         disp('** Problem turning on Fast Orbit Feedback system...                                                       **');
2033                         disp('** Check status of ffbsecXX crates - but remember that a crate reboot will turn off Quads in that sector! **');
2034                         disp('** Suggest disabling the "Fast Orbit Correction" checkbox and starting Orbit Feedback again.              **');
2035                         disp('************************************************************************************************************');
2036                     else
2037                         fprintf('   Starting Fast Orbit Feedback at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
2038                     end
2039                 end
2040
2041
2042                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2043                 % Horizontal plane "feedback" %
2044                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2045
2046                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxSOFB'),'Value') == 1
2047
2048                     % Get orbit and check that the BPMs are different from the last update
2049                     Xnew = getx(FB.OCSx.BPM.DeviceList);
2050
2051                     % Don't feedback if the current is too small
2052                     if getdcct < 5
2053                         FEEDBACK_STOP_FLAG = 1;
2054                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2055                         break;
2056                     end
2057
2058                     x = Xgoal - Xnew;
2059                     STDx = norm(x)/sqrt(length(x));
2060
2061                     if any(Xold == Xnew)
2062                         a = clock;
2063                         N_Stale_Data_Points = find((Xold==Xnew)==1);
2064                         for loop = N_Stale_Data_Points'
2065                             fprintf('   Stale data: BPMx(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSx.BPM.DeviceList(loop,1), FB.OCSx.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2066                         end
2067                     else
2068                         % Compute horizontal correction
2069                         %%%OCSx0 = FB.OCSx;
2070                         FB.OCSx.BPM.Data = Xnew;
2071                         FB.OCSx = orbitcorrectionmethods(FB.OCSx, Smatx, Sx, Ux, Vx);
2072
2073                         %%%[FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
2074
2075                         % reduced feedback gain (implemented by Greg Portmann, December 2000)
2076                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2077                         % increased back to 0.8 C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2078                         % increased to 1.0, C. Steier, 2002-05-04, trim DACs
2079                         X = Xgain .* FB.OCSx.CM.Delta;
2080                         X(N_HCM+1) = 0.3*FB.OCSx.DeltaRF/4.988e-3;
2081                         %%%X = Xgain .* (FB.OCSx.CM.Data - OCSx0.CM.Data);
2082
2083                         % check for trim values+next step values, warn or stop FB as necessary
2084                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2085                         % need to extract Chicanes from this comparison or maybe check them first for range %
2086                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2087                         HCMtrimSP=getpv('HCM','Trim',HCMlist1);
2088                         HCMtrimSP_next = HCMtrimSP + X(1:N_HCM);
2089                         if max(abs(HCMtrimSP_next)) > 4
2090                             HCMtrimnum=find(abs(HCMtrimSP_next) > 4);
2091
2092                             % print message to screen
2093                             fprintf('**One or more of the horizontal correctors is at its maximum!! Stopping orbit feedback. \n');
2094                             fprintf('%s\n',datestr(now));
2095                             for loop = HCMtrimnum'
2096                                 fprintf('**%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2097                             end
2098
2099                             % send alphapage to operator pager
2100                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2101                             FEEDBACK_STOP_FLAG = 1;
2102
2103                             setpv('SR_STATE', -5);
2104                             [StateNumber, StateString] = getsrstate;
2105                             if StateNumber >= 0
2106                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2107                             else
2108                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2109                             end
2110                         end
2111
2112                         if FEEDBACK_STOP_FLAG == 1
2113                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2114                             if getpv('SR01____FFBON__BC00')==1
2115                                 disp('   Stopping Fast Orbit Feedback.');
2116                             end
2117                             setpv('SR01____FFBON__BC00',0);
2118                             pause(0.5);
2119                             setpv('SR01____FFBON__BC00',2);
2120                             break;
2121                         end
2122
2123                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2124                         pause(0);
2125
2126                         if max(abs(HCMtrimSP_next) > 3)
2127                             HCMtrimnum=find(abs(HCMtrimSP_next) > 3);
2128                             HWarnNum=HWarnNum+1;
2129                             if (HWarnNum==1 | rem(HWarnNum,120)==0)
2130
2131                                 % print message to screen every two minutes
2132                                 fprintf('**One or more of the horizontal corrector trims is above 3A or below -3A! \n');
2133                                 fprintf('%s\n',datestr(now));
2134                                 for loop = HCMtrimnum'
2135                                     fprintf('**%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2136                                 end
2137                                 fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2138
2139                                 %send alphapage to operator pager the first time then at 10 minutes
2140                                 if (HWarnNum==1 | HWarnNum==600)
2141                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageHCM.txt
2142                                 end
2143                             end
2144                         else
2145                             HWarnNum=0;
2146                         end
2147
2148                         % Don't feedback if the current is too small
2149                         if getdcct < 5
2150                             FEEDBACK_STOP_FLAG = 1;
2151                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2152                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2153                             break;
2154                         end
2155
2156                         if N_HCM > 0
2157                             steppv('HCM','Trim', X(iNotHCMChicane), HCMlist1(iNotHCMChicane,:), 0);
2158                             steppv('HCM','Setpoint', X(iHCMChicane), HCMlist1(iHCMChicane,:), 0);
2159                         end
2160
2161                         % write fast orbit feedback setpoints
2162                         if 1
2163                             %write_goldenorbit_ffb_2planes(1, Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM)+Sx3*X(length(X))/20, BPMlist1);
2164                             % should be corrected to include result of next frequency step ...
2165                             write_goldenorbit_ffb_2planes(1,Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM),BPMlist1);
2166                         end
2167
2168                         %fprintf('Horizontal Done: %f \n',gettime-t00);
2169
2170                         % RF feedback
2171                         HQMOFMsp_last = getpv('EG______HQMOFM_AC01');
2172
2173                         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2174                             if N_RFMO > 0
2175                                 if abs(X(end)/3) < .01
2176                                 % if abs(FB.OCSx.DeltaRF/3) < .01
2177                                     steppv('EG______HQMOFM_AC01', X(end));
2178                                 else
2179                                     steppv('EG______HQMOFM_AC01', 0.01*sign(X(end)));
2180                                 end
2181                             end
2182
2183                             HQMOFMsp_now = getpv('EG______HQMOFM_AC01');
2184
2185                             % Check for stale RF feedback
2186                             if HQMOFMsp_last == HQMOFMsp_now
2187                                 HQMOFM_stalenum = HQMOFM_stalenum + 1;
2188                                 if HQMOFM_stalenum == 30 % warn and message to pager if stale for 30 secs
2189                                     fprintf('**The RF is not responding to orbit feedback changes! \n');
2190                                     fprintf('%s\n',datestr(now));
2191                                     fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2192                                     fprintf('**ILC 73 controls the EG______HQMOFM_AC01 channel, which sets the RF frequency. \n');
2193                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstaleRFmessage.txt
2194                                 end
2195                                 if rem(HQMOFM_stalenum,120)==0 % message to screen every 2 minutes
2196                                     fprintf('**The RF is not responding to orbit feedback changes! (%s)\n',datestr(now));
2197                                 end
2198                             else
2199                                 HQMOFM_stalenum = 0;
2200                             end
2201
2202                         end
2203
2204                         %fprintf('RF Done: %f \n',gettime-t00);
2205
2206                         Xold = Xnew;
2207                     end % End horizontal correction
2208
2209
2210                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2211                     % Vertical plane "feedback" %
2212                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2213
2214                     % Get orbit and check that the BPMs are different from the last update
2215                     Ynew = gety(FB.OCSy.BPM.DeviceList);
2216
2217                     % Don't feedback if the current is too small
2218                     if getdcct < 5
2219                         FEEDBACK_STOP_FLAG = 1;
2220                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2221                         break;
2222                     end
2223
2224                     y = Ygoal - Ynew;
2225                     STDy = norm(y)/sqrt(length(y));
2226
2227                     if any(Yold == Ynew)
2228                         a = clock;
2229                         N_Stale_Data_Points = find((Yold==Ynew)==1);
2230                         for loop = N_Stale_Data_Points'
2231                             fprintf('   Stale data: BPMy(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSy.BPM.DeviceList(loop,1), FB.OCSy.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2232                         end
2233
2234                     else
2235
2236                         % Compute vertical correction
2237                         %%%OCSy0 = FB.OCSy;
2238                         FB.OCSy.BPM.Data = Ynew;
2239                         FB.OCSy = orbitcorrectionmethods(FB.OCSy, Smaty, Sy, Uy, Vy);
2240
2241                         %%%[FB.OCSy, RF, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
2242
2243                         % reduced feedback gain, C. Steier, 2001-03-25
2244                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2245                         % increased back to 0.8, C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2246                         % set to unity gain, C. Steier, 2002-05-04, trim DACs
2247                         Y = Ygain .* FB.OCSy.CM.Delta;
2248                         %%%Y = Ygain .* (FB.OCSy.CM.Data - OCSy0.CM.Data);
2249
2250                         % Just SVD correction
2251                         % warning('Not using "micado" correction in the vertical plane.');
2252
2253                         % check for trim values+next step values, warn or stop FB as necessary
2254                         VCMtrimSP = getpv('VCM','Trim',VCMlist1);
2255                         VCMtrimSP_next = VCMtrimSP + Y(1:N_VCM);
2256                         if max(abs(VCMtrimSP_next)) > 12
2257                             VCMtrimnum=find(abs(VCMtrimSP_next) > 12);
2258
2259                             % print message to screen
2260                             fprintf('**One or more of the vertical correctors is at its maximum!! Stopping orbit feedback. \n');
2261                             fprintf('%s\n',datestr(now));
2262                             for loop = VCMtrimnum'
2263                                 fprintf('**%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2264                             end
2265
2266                             % send alphapage to operator pager
2267                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2268                             FEEDBACK_STOP_FLAG = 1;
2269
2270                             setpv('SR_STATE', -5);
2271                             [StateNumber, StateString] = getsrstate;
2272                             if StateNumber >= 0
2273                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2274                             else
2275                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2276                             end
2277                         end
2278
2279                         if FEEDBACK_STOP_FLAG == 1
2280                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2281                             if getpv('SR01____FFBON__BC00')==1
2282                                 disp('   Stopping Fast Orbit Feedback.');
2283                             end
2284                             setpv('SR01____FFBON__BC00',0);
2285                             pause(0.5);
2286                             setpv('SR01____FFBON__BC00',2);
2287                             break;
2288                         end
2289
2290                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2291                         % pause(0);
2292
2293                         if max(abs(VCMtrimSP_next) > 4)
2294                             VCMtrimnum=find(abs(VCMtrimSP_next) > 4);
2295                             VWarnNum=VWarnNum+1;
2296                             if (VWarnNum==1 | rem(VWarnNum,120)==0)
2297
2298                                 % print message to screen every two minutes
2299                                 fprintf('**One or more of the vertical corrector trims is above 4A or below -4A! \n');
2300                                 fprintf('%s\n',datestr(now));
2301                                 for loop = VCMtrimnum'
2302                                     fprintf('**%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2303                                 end
2304                                 fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2305
2306                                 %send alphapage to operator pager the first time then at 10 minutes
2307                                 if (VWarnNum==1 | VWarnNum==600)
2308                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageVCM.txt
2309                                 end
2310                             end
2311                         else
2312                             VWarnNum=0;
2313                         end
2314
2315                         % Don't feedback if the current is too small
2316                         if getdcct < 5
2317                             FEEDBACK_STOP_FLAG = 1;
2318                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2319                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2320                             break;
2321                         end
2322
2323                         if N_VCM > 0
2324                             steppv('VCM','Trim', Y(iNotVCMChicane), VCMlist1(iNotVCMChicane,:), 0);
2325                             steppv('VCM','Setpoint', Y(iVCMChicane), VCMlist1(iVCMChicane,:), 0);
2326                         end
2327
2328                         % write fast orbit feedback setpoints
2329                         if 1
2330                             write_goldenorbit_ffb_2planes(2,Ynew(1:size(BPMlist1,1))+Sy1*Y(1:N_VCM),BPMlist1);
2331                         end
2332
2333                     end
2334
2335                     Yold = Ynew;
2336
2337                     %fprintf('Vertical Done: %f \n',gettime-t00);
2338                 end % End vertical correction
2339
2340
2341                 %%%%%%%%%%%%%%%%%%%%%
2342                 % Tune feed forward %
2343                 %%%%%%%%%%%%%%%%%%%%%
2344                 % We should do a Sector limit check
2345
2346                 tic;
2347                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxTune'),'Value') == 1
2348
2349                     if strcmp(SR_Mode, '1.9 GeV, High Tune') || strcmp(SR_Mode, '1.9 GeV, Inject at 1.23') || strcmp(SR_Mode, '1.9 GeV, Two-Bunch')
2350
2351                         addQFsp = zeros(24,1);
2352                         addQDsp = zeros(24,1);
2353
2354                         if strcmp(FFTypeFlag,'Local')
2355                             disp('  No local tune compensation available - global is the default now.');
2356                         elseif strcmp(FFTypeFlag,'Global')
2357
2358                             % The vectorized gets were put outside of loop for speed reasons
2359                             %
2360                             % should also set up QFfac, Quadelem, Quadlist structures outside loop
2361                             actualgap = getid(IDSector);
2362                             [gapmin,gapmax] = gaplimit(IDSector);
2363                             corrind = find(actualgap<(gapmin-1));
2364                             actualgap(corrind)=gapmax(corrind);
2365                             Shift=zeros(size(actualgap));
2366                             Shift(EPUlist)=getpv('EPU');
2367
2368                             IDchangedList=find((abs(actualgap-oldgap)>0.001) | (abs(Shift-oldShift)>0.001));
2369                             oldgap=actualgap;
2370                             oldShift=Shift;
2371
2372                             for gapnum = IDchangedList'
2373                                 % Change in tune and [QF;QD] from maximum gap
2374
2375                                 if (IDSector(gapnum,1) == 4) | (IDSector(gapnum,1) == 11)
2376                                     if IDSector(gapnum,2) == 1
2377                                         modenamestr = sprintf('SR%02dU___ODS1M__DC00',IDSector(gapnum,1));
2378                                     else % if IDSector(gapnum,2) == 2
2379                                         modenamestr = sprintf('SR%02dU___ODS2M__DC00',IDSector(gapnum,1));
2380                                     end
2381                                     epumode = getpvonline(modenamestr);
2382                                     if IDSector(gapnum,2)==2
2383                                         longshift=3;
2384                                     else
2385                                         longshift=0;
2386                                     end
2387                                     if (epumode==0) & (IDSector(gapnum,:)~=[11 1])      % antiparallel tables need to be fit to data so that they could be used here
2388                                         DeltaNuX = shift2tune(IDSector(gapnum,1),actualgap(gapnum),Shift(gapnum)+longshift,SR_GeV)+0.0015;
2389                                         DeltaNuY = 0;   % vertical tune shift of EPUs is very small
2390                                     else
2391                                         DeltaNuX = 0;
2392                                         DeltaNuY = 0;   % vertical tune shift of EPUs is very small
2393                                     end
2394
2395                                 else
2396                                     DeltaNuX = 0;
2397                                     DeltaNuY = gap2tune(IDSector(gapnum,:), actualgap(gapnum), SR_GeV);
2398                                 end
2399
2400                                 DelQF = zeros(length(QFsp),1);
2401                                 DelQD = zeros(length(QFsp),1);
2402
2403                                 fraccorr = DeltaNuY ./ TuneW16Min;
2404
2405                                 % Find which quads to change (local beta beating correction
2406                                 % (horizontal for EPU, vertical otherwise)
2407                                 QuadList = [IDSector(gapnum,1)-1 2; IDSector(gapnum,1) 1];
2408                                 QuadElem = dev2elem('QF',QuadList); % in reality use QF and QD ...
2409
2410                                 % global vertical tune correction
2411                                 % 24 QF+ 24 QD
2412                                 DeltaAmps = inv(SR_TUNE_MATRIX) * [(fraccorr*6.23e-4); fraccorr*(-0.05301)];    %  DelAmps =  [QF; QD];
2413                                 DelQF = DelQF + DeltaAmps(1,:);
2414                                 DelQD = DelQD + DeltaAmps(2,:);
2415
2416                                 % local horizontal tune correction (is also nearly a beta beating correction) only nonzero for EPUs!
2417                                 % 2 QF + 2 QD
2418                                 DeltaAmpsLocal = 12*inv(SR_TUNE_MATRIX) * [-DeltaNuX;0];                       %  DelAmps =  [QF; QD];
2419                                 DelQF(QuadElem) = DelQF(QuadElem)+DeltaAmpsLocal(1,1);
2420                                 DelQD(QuadElem) = DelQD(QuadElem)+DeltaAmpsLocal(2,1);
2421
2422                                 % local vertical beta beating correction (should be used together with above global tune correction)
2423                                 % set to zero for EPUs, since their vertical tune shift is small
2424                                 % 2 QF + 2QD
2425                                 if (IDSector(gapnum,1)==6) | (IDSector(gapnum,1)==7) | (IDSector(gapnum,1)==10) | (IDSector(gapnum,1)==11)
2426                                     QFfac = ([2.243127/2.237111; 2.243127/2.237111]-1) * fraccorr;
2427                                     QDfac = ([2.556392/2.511045; 2.556392/2.511045]-1) * fraccorr;
2428                                 elseif (IDSector(gapnum,1)==5) | (IDSector(gapnum,1)==9)
2429                                     QFfac = ([2.225965/2.219784; 2.243096/2.237111]-1) * fraccorr;
2430                                     QDfac = ([2.528950/2.483259; 2.556345/2.511045]-1) * fraccorr;
2431                                 elseif (IDSector(gapnum,1)==4) | (IDSector(gapnum,1)==8) | (IDSector(gapnum,1)==12)
2432                                     QFfac = ([2.243096/2.237111; 2.225965/2.219784]-1) * fraccorr;
2433                                     QDfac = ([2.556345/2.511045; 2.528950/2.483259]-1) * fraccorr;
2434                                 else
2435                                     QFfac = zeros(2,1);
2436                                     QDfac = zeros(2,1);
2437                                 end
2438
2439                                 DelQF(QuadElem,:) = DelQF(QuadElem,:) + QFfac.*QFsp(QuadElem,:);
2440                                 DelQD(QuadElem,:) = DelQD(QuadElem,:) + QDfac.*QDsp(QuadElem,:);
2441
2442                                 % add all tune and beta beating corrections for this one ID to the summed up correction vectors for all IDs
2443                                 addQFsp = addQFsp+DelQF;
2444                                 addQDsp = addQDsp+DelQD;
2445
2446                             end
2447
2448                         else
2449                             error('Unknown type selected for tune FF');
2450                         end
2451
2452                         % Set quadrupoles using main setpoint channels
2453                         setpv('QF', QFsp+addQFsp,[], 0);
2454                         setpv('QD', QDsp+addQDsp,[], 0);
2455
2456                         % % Set quadrupoles using FF setpoint channels
2457                         % setpv('QF', 'FF', addQFsp, [], 0);
2458                         % setpv('QD', 'FF', addQDsp, [], 0);
2459
2460                     else
2461                         disp('  No tune FF algorithm for non-production modes yet...');
2462                     end
2463                 end
2464
2465                 ffdeltaquad_delay = toc;
2466                 %fprintf('tune FF delay = %.1f seconds\n',ffdeltaquad_delay);
2467                 % fprintf('Tune Done: %f \n',gettime-t00);
2468
2469                 % Output info to screen
2470                 set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
2471                 set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
2472                 pause(0);
2473
2474
2475                 %fprintf('End of feedback operations: %f \n\n',gettime-t00);
2476
2477                 % Wait for next update time or stop request
2478                 while (gettime-t00) < LoopDelay
2479                     %disp('interval could be shorter')
2480                     pause(.05);
2481                     % Check if GUI has been closed
2482                     if isempty(gcbf)
2483                         FEEDBACK_STOP_FLAG = 1;
2484                         lasterr('SRCONTROL GUI DISAPPEARED!');
2485                         error('SRCONTROL GUI DISAPPEARED!');
2486                     end
2487
2488                     % Check if Stop button was pressed
2489                     if FEEDBACK_STOP_FLAG == 1
2490                         % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2491                         if getpv('SR01____FFBON__BC00')==1
2492                             disp('   Stopping Fast Orbit Feedback.');
2493                         end
2494                         setpv('SR01____FFBON__BC00',0);
2495                         pause(0.5);
2496                         setpv('SR01____FFBON__BC00',2);
2497                         break;
2498                     end
2499                 end
2500
2501
2502                 if FEEDBACK_STOP_FLAG == 1
2503                     % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2504                     if getpv('SR01____FFBON__BC00')==1
2505                         disp('   Stopping Fast Orbit Feedback.');
2506                     end
2507                     setpv('SR01____FFBON__BC00',0);
2508                     pause(0.5);
2509                     setpv('SR01____FFBON__BC00',2);
2510                     break;
2511                 end
2512
2513                 StartErrorTime = gettime;
2514
2515             catch
2516
2517                 fprintf('\n  %s \n',lasterr);
2518
2519                 % Quit if error exists for more than 20 seconds
2520                 if gettime-StartErrorTime>20 | FEEDBACK_STOP_FLAG==1
2521                     fprintf('%s  Orbit feedback stopped due to error condition. \n\n',datestr(now));
2522
2523                     %send alphapage to operator pager
2524                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2525                     FEEDBACK_STOP_FLAG = 1;
2526
2527                     setpv('SR_STATE', -5);
2528                     [StateNumber, StateString] = getsrstate;
2529                     if StateNumber >= 0
2530                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2531                     else
2532                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2533                     end
2534                 else
2535                     a = clock;
2536                     fprintf('   Orbit feedback was paused due to error condition (%s %d:%d:%.0f). \n', date, a(4), a(5), a(6));
2537                     fprintf('   Orbit feedback has automatically restarted and is running. \n\n');
2538                 end
2539
2540             end
2541
2542             if FEEDBACK_STOP_FLAG == 1
2543                 % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2544                 if getpv('SR01____FFBON__BC00')==1
2545                     disp('   Stopping Fast Orbit Feedback.');
2546                 end
2547                 setpv('SR01____FFBON__BC00',0);
2548                 pause(0.5);
2549                 setpv('SR01____FFBON__BC00',2);
2550                 break;
2551             end
2552
2553             %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2554
2555             %pause(0);
2556
2557             % this loop delays turn on of Fast Feedback system
2558             if FBloopIter < 5
2559                 FBloopIter = FBloopIter + 1;
2560             end
2561
2562         end  % End of feedback loop
2563
2564
2565         % End feedback, reset all parameters
2566         try
2567
2568             % Enable buttons
2569             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','on');
2570             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','off');
2571             set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','on');
2572             set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','on');
2573             set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','on');
2574             set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','on');
2575             set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','on');
2576             set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','on');
2577             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','on');
2578             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','on');
2579             set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','on');
2580             set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','on');
2581             set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','on');
2582
2583             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = _____ mm'),'ForegroundColor',[0 0 0]);
2584             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = _____ mm'),'ForegroundColor',[0 0 0]);
2585             pause(0);
2586
2587         catch
2588
2589             % GUI must have been closed
2590
2591         end
2592
2593
2594         % >= 2 Hz update rate on IDBPMs
2595         disp('   IDBPM time constant set to 0.25s.');
2596         setbpmtimeconstant(0.25);
2597
2598
2599         a = clock;
2600         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2601         [StateNumber, StateString] = getsrstate;
2602         if StateNumber >= 0
2603             setpv('SR_STATE',5.1);
2604             [StateNumber, StateString] = getsrstate;
2605             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2606             fprintf('   ******************************\n');
2607             fprintf('   **  Orbit Feedback Stopped  **\n');
2608             fprintf('   ******************************\n\n');
2609         else
2610             [StateNumber, StateString] = getsrstate;
2611             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2612             fprintf('   ****************************************\n');
2613             fprintf('   **  Problem With Slow Orbit Feedback  **\n');
2614             fprintf('   ****************************************\n\n');
2615         end
2616         set(0,'showhiddenhandles','off');
2617         pause(0);
2618
2619
2620     case 'FeedbackSetup'
2621         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
2622
2623         if InitFlag
2624             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2625             % Edit the following lists to change default configuration of Orbit Correction %
2626             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2627
2628             % Corrector magnets
2629             listh=[
2630                 1 2;
2631                 1 8;
2632                 2 1;
2633                 2 8;
2634                 3 1;
2635                 3 8;
2636                 3 10; %SR04U_HCM2 (chicane trim)
2637                 4 1;
2638                 4 8;
2639                 5 1;
2640                 5 8;
2641                 5 10; %SR06U_HCM2 (chicane trim)
2642                 6 1;
2643                 6 8;
2644                 7 1;
2645                 7 8;
2646                 8 1;
2647                 8 8;
2648                 9 1;
2649                 9 8;
2650                 10 1;
2651                 10 8;
2652                 10 10; %SR11U_HCM2 (chicane trim)
2653                 11 1;
2654                 11 8;
2655                 12 1;
2656                 12 7];
2657             listv=[
2658                 1 2;
2659                 1 8;
2660                 2 1;
2661                 2 8;
2662                 3 1;
2663                 3 7;
2664                 3 8;
2665                 3 10; %SR04U_VHCM2 (chicane trim)
2666                 4 1;
2667                 4 7;
2668                 4 8;
2669                 5 1;
2670                 5 8;
2671                 5 10; %SR06U_VHCM2 (chicane trim)
2672                 6 1;
2673                 6 8;
2674                 7 1;
2675                 7 8;
2676                 8 1;
2677                 8 8;
2678                 9 1;
2679                 9 8;
2680                 10 1;
2681                 10 2;
2682                 10 7;
2683                 10 8;
2684                 10 10; %SR11U_VHCM2 (chicane trim)
2685                 11 1;
2686                 11 7;
2687                 11 8;
2688                 12 1;
2689                 12 7];
2690
2691             Xivec = [1:28];
2692             Yivec = [1:32];
2693             HCMlist1 = listh;
2694             VCMlist1 = listv;
2695
2696             % Full BPM list
2697             BPMlist1 = [
2698                 1 2
2699                 1 5
2700                 1 6
2701                 1 10
2702                 2 1
2703                 2 5
2704                 2 6
2705                 2 9
2706                 3 2
2707                 3 5
2708                 3 6
2709                 3 10
2710                 3 11
2711                 3 12
2712                 4 1
2713                 4 5
2714                 4 6
2715                 4 10
2716                 5 1
2717                 5 5
2718                 5 6
2719                 5 10
2720                 5 11
2721                 5 12
2722                 6 1
2723                 6 5
2724                 6 6
2725                 6 10
2726                 7 1
2727                 7 5
2728                 7 6
2729                 7 10
2730                 8 1
2731                 8 5
2732                 8 6
2733                 8 10
2734                 9 1
2735                 9 5
2736                 9 6
2737                 9 10
2738                 10 1
2739                 10 5
2740                 10 6
2741                 10 10
2742                 10 11
2743                 10 12
2744                 11 1
2745                 11 5
2746                 11 6
2747                 11 10
2748                 12 1
2749                 12 5
2750                 12 6
2751                 12 9
2752                 ];
2753
2754             % remove Bergoz BPMs in SR01 and SR03 for 2-bunch (noisy at low currents) and drop singular values
2755             if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
2756                     BPMlist1 = [
2757                          %1 2
2758                          1 5
2759                          1 6
2760                          1 10
2761                          2 1
2762                          2 5
2763                          2 6
2764                          %2 9
2765                          %3 2
2766                          3 5
2767                          3 6
2768                          3 10
2769                          3 11
2770                          3 12
2771                          4 1
2772                          4 5
2773                          4 6
2774                          4 10
2775                          5 1
2776                          5 5
2777                          5 6
2778                          5 10
2779                          5 11
2780                          5 12
2781                          6 1
2782                          6 5
2783                          6 6
2784                          6 10
2785                          7 1
2786                          7 5
2787                          7 6
2788                          7 10
2789                          8 1
2790                          8 5
2791                          8 6
2792                          8 10
2793                          9 1
2794                          9 5
2795                          9 6
2796                          9 10
2797                          10 1
2798                          10 5
2799                          10 6
2800                          10 10
2801                          10 11
2802                          10 12
2803                          11 1
2804                          11 5
2805                          11 6
2806                          11 10
2807                          12 1
2808                          12 5
2809                          12 6
2810                          %12 9
2811                          ];
2812             end
2813
2814             OCSx.BPM = getx(BPMlist1, 'struct');
2815             OCSx.CM = getsp('HCM', HCMlist1, 'struct');
2816             OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
2817             OCSx.NIter = 1;
2818             OCSx.SVDIndex = Xivec;
2819             OCSx.IncrementalFlag = 'No';
2820             OCSx.BPMWeight = {[]};
2821             OCSx.FitRF = 0;
2822             OCSy.BPM = gety(BPMlist1, 'struct');
2823             OCSy.CM = getsp('VCM', VCMlist1, 'struct');
2824             OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
2825             OCSy.NIter = 1;
2826             OCSy.SVDIndex = Yivec;
2827             OCSy.IncrementalFlag = 'No';
2828             OCSy.BPMWeight = {[]};
2829             OCSy.FitRF = 0;
2830             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2831             % do we need these Smat calls? %
2832             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2833             SXmat = getrespmat(OCSx.BPM, OCSx.CM, 'numeric');
2834             SYmat = getrespmat(OCSy.BPM, OCSy.CM, 'numeric');
2835             % [OCSx, Sx, Ux, Vx] = orbitcorrectionmethods(OCSx, SXmat);
2836             % [OCSy, Sy, Uy, Vy] = orbitcorrectionmethods(OCSy, SYmat);
2837
2838             % initialize FFTypeFlag
2839             FFTypeFlag = 'Global';
2840
2841         else
2842
2843             % Get vectors
2844             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
2845             % the two lines below seem to fix BPMlist editing problem
2846             OCSx = FB.OCSx;
2847             OCSy = FB.OCSy;
2848             BPMlist1 = FB.BPMlist1;
2849             HCMlist1 = FB.HCMlist1;
2850             VCMlist1 = FB.VCMlist1;
2851             Xivec = FB.Xivec;
2852             Yivec = FB.Yivec;
2853             Xgoal = FB.OCSx.GoalOrbit;
2854             OCSx.GoalOrbit = Xgoal;
2855             Ygoal = FB.OCSy.GoalOrbit;
2856             OCSy.GoalOrbit = Ygoal;
2857             FFTypeFlag = FB.FFTypeFlag;
2858
2859
2860             % FF corrector magnet list
2861             ListFF = [
2862                 4     2
2863                 4     8
2864                 5     1
2865                 5     7
2866 %               5     8 % why are these out???
2867 %               6     1 % why are these out???
2868                 6     8
2869                 7     1
2870                 7     8
2871                 8     1
2872                 8     8
2873                 9     1
2874                 9     8
2875                 10    1
2876                 11    8
2877                 12    1];
2878             ElemFF = dev2elem('HCM',ListFF);
2879
2880
2881             % Add button to change #ivectors, cm, IDBPMs,
2882             EditFlag = 0;
2883             h_fig1 = figure;
2884             while EditFlag ~= 6
2885
2886                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
2887                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
2888
2889                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2890                     DispOrbit = getdisp('BPMx', BPMlist1);
2891                     Sx = [Sx DispOrbit];
2892                 end
2893
2894                 [Ux, SVx, Vx] = svd(Sx);
2895                 [Uy, SVy, Vy] = svd(Sy);
2896
2897
2898                 % Remove singular values greater than the actual number of singular values
2899                 i = find(Xivec>length(diag(SVx)));
2900                 if ~isempty(i)
2901                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
2902                     pause(0);
2903                     Xivec(i) = [];
2904                 end
2905                 i = find(Yivec>length(diag(SVy)));
2906                 if ~isempty(i)
2907                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
2908                     pause(0);
2909                     Yivec(i) = [];
2910                 end
2911
2912
2913                 Ax = Sx*Vx(:,Xivec);
2914                 Tx = inv(Ax'*Ax)*Ax';
2915
2916                 Ay = Sy*Vy(:,Yivec);
2917                 Ty = inv(Ay'*Ay)*Ay';
2918
2919                 figure(h_fig1);
2920                 subplot(2,1,1);
2921                 semilogy(diag(SVx),'b');
2922                 hold on;
2923                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
2924                 ylabel('Horizontal');
2925                 title('Response Matrix Singular Values');
2926                 hold off;
2927                 subplot(2,1,2);
2928                 semilogy(diag(SVy),'b');
2929                 hold on;
2930                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
2931                 xlabel('Singular Value Number');
2932                 ylabel('Vertical');
2933                 hold off;
2934                 drawnow;
2935
2936                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List', ...
2937                     'BPM List','Change the Goal Orbit','Continue');
2938
2939                 if EditFlag == 1
2940                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
2941                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
2942                     titlestr='SVD Orbit Feedback';
2943                     lineNo=1;
2944                     answer=inputdlg(prompt,titlestr,lineNo,def);
2945                     if ~isempty(answer)
2946                         XivecNew = fix(str2num(answer{1}));
2947                         if isempty(XivecNew)
2948                             disp('   Horizontal E-vector cannot be empty.  No change made.');
2949                         else
2950                             if any(XivecNew<=0) | max(XivecNew)>length(diag(SVx))
2951                                 disp('   Error reading horizontal E-vector.  No change made.');
2952                             else
2953                                 Xivec = XivecNew;
2954                             end
2955                         end
2956                         YivecNew = fix(str2num(answer{2}));
2957                         if isempty(YivecNew)
2958                             disp('   Vertical E-vector cannot be empty.  No change made.');
2959                         else
2960                             if any(YivecNew<=0) | max(YivecNew)>length(diag(SVy))
2961                                 disp('   Error reading vertical E-vector.  No change made.');
2962                             else
2963                                 Yivec = YivecNew;
2964                             end
2965                         end
2966                     end
2967                 end
2968
2969                 if EditFlag == 2
2970                     List= getlist('HCM','Trim');
2971                     CheckList = zeros(96,1);
2972                     Elem = dev2elem('HCM', HCMlist1);
2973                     CheckList(Elem) = ones(size(Elem));
2974                     CheckList = CheckList(dev2elem('HCM',List));
2975
2976                     % Remove FF corrrectors
2977                     %           Elem = dev2elem('HCM',List);
2978                     %           for j = length(ElemFF):-1:1
2979                     %              i = find(Elem==ElemFF(j));
2980                     %              Elem(i,:) = [];
2981                     %              List(i,:) = [];
2982                     %              CheckList(i,:) = [];
2983                     %           end
2984
2985                     newList = editlist(List, 'HCMtrim', CheckList);
2986
2987                     if isempty(newList)
2988                         fprintf('   WARNING: Horizontal corrector magnet list is empty!\n');
2989                         HCMlist1 = newList;
2990                     else
2991                         HCMlist1 = newList;
2992                     end
2993                 end
2994
2995                 if EditFlag == 3
2996                     List = getlist('VCM','Trim');
2997                     CheckList = zeros(96,1);
2998                     Elem = dev2elem('VCM', VCMlist1);
2999                     CheckList(Elem) = ones(size(Elem));
3000                     CheckList = CheckList(dev2elem('VCM',List));
3001
3002                     % Remove FF corrrectors
3003                     %           Elem = dev2elem('VCM',List);
3004                     %           for j = length(ElemFF):-1:1
3005                     %              i = find(Elem==ElemFF(j));
3006                     %              Elem(i,:) = [];
3007                     %              List(i,:) = [];
3008                     %              CheckList(i,:) = [];
3009                     %           end
3010
3011                     newList = editlist(List, 'VCMtrim', CheckList);
3012
3013                     if isempty(newList)
3014                         fprintf('   WARNING: Vertical corrector magnet list is empty!\n');
3015                         VCMlist1 = newList;
3016                     else
3017                         VCMlist1 = newList;
3018                     end
3019                 end
3020
3021                 if EditFlag == 4
3022                     ListOld = BPMlist1;
3023                     XgoalOld = Xgoal;
3024                     YgoalOld = Ygoal;
3025
3026                     % Full BPM list
3027                     List = [
3028                         1 2
3029                         1 5
3030                         1 6
3031                         1 10
3032                         2 1
3033                         2 5
3034                         2 6
3035                         2 9
3036                         3 2
3037                         3 5
3038                         3 6
3039                         3 10
3040                         3 11
3041                         3 12
3042                         4 1
3043                         4 5
3044                         4 6
3045                         4 10
3046                         5 1
3047                         5 5
3048                         5 6
3049                         5 10
3050                         5 11
3051                         5 12
3052                         6 1
3053                         6 5
3054                         6 6
3055                         6 10
3056                         7 1
3057                         7 5
3058                         7 6
3059                         7 10
3060                         8 1
3061                         8 5
3062                         8 6
3063                         8 10
3064                         9 1
3065                         9 5
3066                         9 6
3067                         9 10
3068                         10 1
3069                         10 5
3070                         10 6
3071                         10 10
3072                         10 11
3073                         10 12
3074                         11 1
3075                         11 5
3076                         11 6
3077                         11 10
3078                         12 1
3079                         12 5
3080                         12 6
3081                         12 9
3082                         ];
3083
3084
3085                     CheckList = zeros(size(List,1),1);
3086                     if ~isempty(BPMlist1)
3087                         for i = 1:size(List,1)
3088                             k = find(List(i,1)==BPMlist1(:,1));
3089                             l = find(List(i,2)==BPMlist1(k,2));
3090
3091                             if isempty(k) | isempty(l)
3092                                 % Item not in list
3093                             else
3094                                 CheckList(i) = 1;
3095                             end
3096                         end
3097                     end
3098
3099                     newList = editlist(List, 'BPM', CheckList);
3100                     if isempty(newList)
3101                         fprintf('   BPM list cannot be empty.  No change made.\n');
3102                     else
3103                         BPMlist1 = newList;
3104                     end
3105
3106                     % Set the goal orbit to the golden orbit
3107                     Xgoal = getgolden('BPMx', BPMlist1);
3108                     Ygoal = getgolden('BPMy', BPMlist1);
3109
3110
3111                     % If a new BPM is added, then set the goal orbit to the golden orbit
3112                     for i = 1:size(BPMlist1,1)
3113
3114                         % Is it a new BPM?
3115                         k = find(BPMlist1(i,1)==ListOld(:,1));
3116                         l = find(BPMlist1(i,2)==ListOld(k,2));
3117
3118                         if isempty(k) | isempty(l)
3119                             % New BPM
3120                         else
3121                             % Use the old value for old BPM
3122                             Xgoal(i) = XgoalOld(k(l));
3123                             Ygoal(i) = YgoalOld(k(l));
3124                         end
3125                     end
3126                     OCSx.BPM.DeviceList = BPMlist1;
3127                     OCSy.BPM.DeviceList = BPMlist1;
3128                     OCSx.GoalOrbit = Xgoal;
3129                     OCSy.GoalOrbit = Ygoal;
3130                 end
3131
3132                 if EditFlag == 5
3133                     ChangeList = editlist2(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
3134
3135                     for i = 1:size(ChangeList,1)
3136
3137                         k = find(ChangeList(i,1)==BPMlist1(:,1));
3138                         l = find(ChangeList(i,2)==BPMlist1(k,2));
3139
3140                         prompt={sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
3141                         def={sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
3142                         titlestr='CHANGE THE GOAL ORBIT';
3143                         lineNo=1;
3144                         answer = inputdlg(prompt, titlestr, lineNo, def);
3145
3146                         if isempty(answer)
3147                             % No change
3148                             fprintf('   No change was made to the golden orbit.\n');
3149                         else
3150                             Xgoalnew = str2num(answer{1});
3151                             if isempty(Xgoalnew)
3152                                 fprintf('   No change was made to the horizontal golden orbit.\n');
3153                             else
3154                                 Xgoal(k(l)) = Xgoalnew;
3155                             end
3156
3157                             Ygoalnew = str2num(answer{2});
3158                             if isempty(Ygoalnew)
3159                                 fprintf('   No change was made to the vertical golden orbit.\n');
3160                             else
3161                                 Ygoal(k(l)) = Ygoalnew;
3162                             end
3163                         end
3164                     end
3165                     if ~isempty(ChangeList)
3166                         fprintf('   Note:  Changing the goal orbit for "Slow Orbit Feedback" does not change the goal orbit for "Orbit Correction."\n');
3167                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
3168                     end
3169                     OCSx.GoalOrbit = Xgoal;
3170                     OCSy.GoalOrbit = Ygoal;
3171                 end
3172
3173 %                 if EditFlag == 6
3174 %                     FFTypeFlag = questdlg(sprintf('Do you want to use a fully local or a combined local/global compensation of IDs? (nuy=9.2 only)'),'Tune FF','Local','Global', 'Global');
3175 %                     if strcmp(FFTypeFlag,'Local')
3176 %                         disp(['   The tune FF will use 8 local quadrupoles to compensate beta beating and tune shift']);
3177 %                         disp(['   from each ID.']);
3178 %                     elseif strcmp(FFTypeFlag,'Global')
3179 %                         disp(['   The tune FF will use 4 local quadrupoles to compensate beta beating and all QF+QD']);
3180 %                         disp(['   to compensate tune shift from each ID.']);
3181 %                     end
3182 %                 end
3183
3184             end
3185             close(h_fig1);
3186         end
3187
3188         % Save vectors
3189         FB.Xivec = Xivec;
3190         FB.Yivec = Yivec;
3191         FB.HCMlist1 = HCMlist1;
3192         FB.VCMlist1 = VCMlist1;
3193         FB.BPMlist1 = BPMlist1;
3194
3195         OCSx.SVDIndex = Xivec;
3196         OCSy.SVDIndex = Yivec;
3197         FB.OCSx = OCSx;
3198         FB.OCSy = OCSy;
3199
3200         FB.FFTypeFlag = FFTypeFlag;
3201         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata',FB);
3202
3203
3204     case 'FastFeedbackSetup'
3205
3206         InitFlag = Input2;
3207
3208         if InitFlag
3209             FOFBFreq = 1000;
3210             % user operations 9/14-10/17/04: P=0.5, I=120, D=0.0015 (for both planes)
3211             % below are known good values for user ops as of 8-1-05
3212             HorP = 2;
3213             HorI = 300;
3214             HorD = 0.002;
3215             VertP = 1;
3216             VertI = 100;
3217             VertD = 0.0015;
3218
3219             % this initial set is now done in hwinit.m because it's not a good idea to set anything when srcontrol is launched
3220             % try
3221             %     setsp('SR01____FFBFREQAC00', FOFBFreq); % set freq
3222             %     write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3223             % catch
3224             %     disp('   Trouble setting Fast Orbit Feedback parameters!');
3225             % end
3226
3227         else
3228             % Get vectors
3229             FOFB = get(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata');
3230             FOFBFreq = FOFB.FOFBFreq;
3231             HorP  = FOFB.HorP;
3232             HorI  = FOFB.HorI;
3233             HorD  = FOFB.HorD;
3234             VertP = FOFB.VertP;
3235             VertI = FOFB.VertI;
3236             VertD = FOFB.VertD;
3237
3238             % Add button to change #ivectors, CMs, IDBPMs,
3239             EditFlag = 0;
3240             %h_fig1 = figure;
3241             while EditFlag ~= 3
3242
3243                 %EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'HCM List', 'VCM List', ...
3244                 %   'IDBPM List', 'BBPM List', 'Continue');
3245                 % Use menu below until other FFB config routines work (then also uncomment options 3,4,5,6 below)
3246                 EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'Continue');
3247
3248                 if EditFlag == 1
3249                     % change rate
3250
3251                     prompt={'Enter the desired Fast Feedback Frequency (1-1000 Hz)'};
3252                     def={num2str(FOFBFreq)};
3253                     titlestr='Fast Feedback Setup';
3254                     lineNo=1;
3255                     answer=inputdlg(prompt,titlestr,lineNo,def);
3256                     if ~isempty(answer)
3257                         FOFBFreq = fix(str2num(answer{1}));
3258                         if isempty(FOFBFreq)
3259                             disp('   Frequency value cannot be empty.  No change made.');
3260                             FOFBFreq = getsp('SR01____FFBFREQAC00');
3261                         else
3262                             if FOFBFreq < 1 | FOFBFreq > 1000
3263                                 disp('   Frequency must be between 1 and 1000 Hz.  No change made.');
3264                                 FOFBFreq = getsp('SR01____FFBFREQAC00');
3265                             end
3266                         end
3267                         setsp('SR01____FFBFREQAC00',FOFBFreq); % change freq
3268                         pause(0.5);
3269                         fprintf('   Fast orbit feedback frequency is running at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
3270                     else
3271                         FOFBFreq = getsp('SR01____FFBFREQAC00');
3272                     end
3273                 end
3274
3275                 if EditFlag == 2
3276                     % edit  PIDs
3277                     % User defaults are HorP=2, HorI=300, HorD=0.002, VertP=1, VertI=100, VertD=0.0015
3278                     prompt={'P horizontal', 'I horizontal', 'D horizontal', 'P vertical', 'I vertical', 'D vertical'};
3279                     def={num2str(HorP), num2str(HorI), num2str(HorD), num2str(VertP), num2str(VertI), num2str(VertD)};
3280                     titlestr='Fast Feedback PID Setup';
3281                     lineNo=1;
3282                     answer=inputdlg(prompt,titlestr,lineNo,def);
3283                     if ~isempty(answer)
3284                         HorPnewnum = str2num(answer{1});
3285                         if isempty(HorPnewnum)
3286                             disp('   HorP value cannot be empty.  No change made.');
3287                         else
3288                             HorP = HorPnewnum;
3289                         end
3290                         HorInewnum = str2num(answer{2});
3291                         if isempty(HorInewnum)
3292                             disp('   HorI value cannot be empty.  No change made.');
3293                         else
3294                             HorI = HorInewnum;
3295                         end
3296                         HorDnewnum = str2num(answer{3});
3297                         if isempty(HorDnewnum)
3298                             disp('   HorD value cannot be empty.  No change made.');
3299                         else
3300                             HorD = HorDnewnum;
3301                         end
3302                         VertPnewnum = str2num(answer{4});
3303                         if isempty(VertPnewnum)
3304                             disp('   VertP value cannot be empty.  No change made.');
3305                         else
3306                             VertP = VertPnewnum;
3307                         end
3308                         VertInewnum = str2num(answer{5});
3309                         if isempty(VertInewnum)
3310                             disp('   VertI value cannot be empty.  No change made.');
3311                         else
3312                             VertI = VertInewnum;
3313                         end
3314                         VertDnewnum = str2num(answer{6});
3315                         if isempty(VertDnewnum)
3316                             disp('   VertD value cannot be empty.  No change made.');
3317                         else
3318                             VertD = VertDnewnum;
3319                         end
3320
3321                         try
3322                             write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3323                             fprintf('   Setting FFB gains to Horizontal P=%.2f, I=%.1f, D=%.4f;  Vertical P=%.2f, I=%.1f, D=%.4f\n', HorP, HorI, HorD, VertP, VertI, VertD);
3324                         catch
3325                             disp('   Trouble setting Fast Orbit Feedback parameters!');
3326                         end
3327                     end
3328                 end
3329
3330                 %if EditFlag == 3
3331                 %   disp('   This function not yet available.');
3332                 %   % change HCM List
3333                 %end
3334                 %
3335                 %if EditFlag == 4
3336                 %   disp('   This function not yet available.');
3337                 %   % change VCM List
3338                 %end
3339                 %
3340                 %if EditFlag == 5
3341                 %   disp('   This function not yet available.');
3342                 %   % change IDBPM List
3343                 %end
3344                 %
3345                 %if EditFlag == 6
3346                 %   disp('   This function not yet available.');
3347                 %   % change BBPM List
3348                 %end
3349
3350             end
3351             %close(h_fig1);
3352         end
3353
3354         % Save vectors
3355         FOFB.FOFBFreq = FOFBFreq;
3356         FOFB.HorP = HorP;
3357         FOFB.HorI = HorI;
3358         FOFB.HorD = HorD;
3359         FOFB.VertP = VertP;
3360         FOFB.VertI = VertI;
3361         FOFB.VertD = VertD;
3362         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata',FOFB);
3363
3364     otherwise
3365         fprintf('   No action for %s.\n', action);
3366 end   % end case