Description of srcontrol5_includingEPUtuneFF
Home > ALS > StorageRing > srcontrol5_includingEPUtuneFF.m
srcontrol5_includingEPUtuneFF
PURPOSE
srcontrol5
SYNOPSIS
function srcontrol5(action, Input2, Input3)
DESCRIPTION
 srcontrol5
 Storage ring control program
 This program controls all storage ring magnets, performs orbit feedback and
 tune feedforward and helps to diagnose problems in routine user operation
 of the ALS storage ring. It includes a gui to simplify the use of this
 program.
 It was originally programmed by Greg Portmann (until December 2000) with input
 from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
 and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
 The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
 Christoph Steier, July 2002
 SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
 Tom Scarvie, April 2005
CROSS-REFERENCE INFORMATION
This function calls:
bend2gev BEND2GEV - Compute the energy based on the ramp tables
checksrmags CHECKSRMAGS - Check SR power supplies against a lattice file
checksrorbit ErrorNums =checksrorbit(Sector, BPMxtolerance [.015 mm], [BPMytolerance [.015 mm]])
gap2tune GAP2TUNE - Computes the vertical tune shift for a insertion device gap change.
gaplimit [GapMin, GapMax] = gaplimit(ID_Number);
getff function [FFEnableBM, FFEnableBC, GapEnableBM, GapEnableBC, Sector] = getff(Sector)
getid GETID - Get the insertion device position, velocity, run flag, and user requested gap
getsrstate [StateNumber, StateString] = getsrstate
set_alarmhandler_AHU_thresholds_inject function set_alarmhandler_AHU_thresholds_inject
set_alarmhandler_thresholds set_alarmhandler_thresholds
set_alarmhandler_thresholds_new set_alarmhandler_thresholds_new
setbpmtimeconstant SETBPMTIMECONSTANT - Sets the timeconstants for the Bergoz style BPMs.
setbumps SETBUMPS - Make a straight section bump
setff function setff(Sector, FFEnableBC, GapEnableBC)
setid SETID - Set the insertion device vertical gap
setsrstatechannels
shift2tune SHIFT2TUNE - Computes the horizontal tune shift for a EPU gap and horizontal shift
srcycle SRCYCLE - Storage ring cycle
srramp SRRAMP - Ramp the storage ring energy
write_goldenorbit_ffb function write_goldenorbit_ffb
write_goldenorbit_ffb_2planes WRITE_GOLDENORBIT_FFTB_2PLANES - Sets the BPM setpoints which are used by the fast feedback system
This function is called by:
SOURCE CODE
function srcontrol5(action, Input2, Input3)
% srcontrol5
% Storage ring control program
%
% This program controls all storage ring magnets, performs orbit feedback and
% tune feedforward and helps to diagnose problems in routine user operation
% of the ALS storage ring. It includes a gui to simplify the use of this
% program.
%
% It was originally programmed by Greg Portmann (until December 2000) with input
% from Winfried Decking, David Robin, Christoph Steier, Ying Wu and others
% and is currently (July 2002) maintained by Christoph Steier and Tom Scarvie.
%
% The actual version of this program is srcontrol5 (is called by default if you call srcontrol).
%
% Christoph Steier, July 2002
%
% SRCONTROL5 is the newest versionof SRCONTROL, edited to work with G. Portmann's new (2005) Matlab middle layer.
%
% Tom Scarvie, April 2005
% known bugs/problems (May 2001):
% - IDBPM averaging might be a bit too long for orbit feedback
%        solved after Superbend shutdown ... Instead of averaging, digital low pass filters are used
% - gap2tune does not give correct answers for wiggler and potentially other IDs -> orbit feedback
%        seems to be OK for other IDs, has been corrected for wiggler (fit to insertion device
%        compensation table)
% - chicanes do not work in orbit feedback
%        solved. One problem was that orbit response matrizes were mis-scaled by factor of two.
%        Second problem was different time constant of power supply control. Solved by moving controls
%        of center chicanes to cPCI (and magnets are fast, hysteresis free, aircore coils).
%        Center chicane in sector 4 is now routinely used in orbit feedback. Sector 11 to follow soon.
% - zero reading of ID gap dumps beam
%        solved in srcontrol5, still a problem in srcontrol5_hightune (but that routine has to be completely
%        rewritten because of all recent changes to srcontrol5, anyhow). For gap readings below the minimum
%        allowed gap for a device, the tune feedforward disables itself.
% - cycling of lattice causes frequent power supply failures
%        solved by changing the cycling procedure. 1.5 GeV operation is now on the upper hysteresis branch
%        as was the 1.9 GeV injection lattice before.
% - frequently stalled data in IDBPM readout
%        solved with new BPM readouts and digital filtering. Seems to have been a resolution problem
%        of the digital averaging algorithm.
% - magnet ramp tables are not in perfect agreement with magnetic measurements
%        Does not appear to be a serious problem. Superbends are slightly out of sync with other magnets,
%        but this does not cause any negative effects while ramping.
% - no good way to operate with injection at 1.5 GeV and storage energy below that
%        There now is a reasonable way to inject at 1.5 GeV and ramp down to lower storage energy. But
%        it has to be tested again after implementing new (and more) chicanes ...
% revision history
% 2001-05-10, Christoph Steier
% check whether readback from insertion device is significantly (more than 1 mm) below minimum
% gap, to avoid false zero readings of insertion device gaps to cause the tune feed forward
% to implement false huge correction (and dump the beam). If the insertion device gap readbacks
% gets more than 1 mm below the nominal minimum gap, the routine now assumes the insertion device
% to be open.
%
% 2001-08-30 and during Superbend commissioning, Christoph Steier, Tom Scarvie, Winni Decking
% various changes have been made to incorporate the Superbends and some other new equipment
% installed in the Superbend shutdown. This included some changes to programs being called by srcontrol
% (like srload, srsave, srcycle, srramp, ...). The main changes within srcontrol were in the orbit
% correction and slow orbit feedback routines (incorporating frequency feedback, ...)
%
% 2002-05-04, Christoph Steier
% added new IDBPMs, modified orbit feedback to use trim DACs, removed LSB toggling in vertical
% orbit feedback, ...
%
% 2002-07-29, T.Scarvie
% added check of CM trim currents to warn of problems that might rail the orbit feedback
%
% 2002-07-31, Christoph Steier
% increased the gain of the RF frequency feedback from 1/50 of the gain of the horizontal
% orbit feedback to 1/20. Reason was that the frequency feedback was reacting a bit too slow if all
% insertion device gaps are closed at once at high speed at the beginning of a fill.
%
% 2002-08-05, C.Steier, T.Scarvie
% Added conditional to reduce orbit feedback gain if running in two-bunch mode
%
% 2003-06-02, T.Scarvie
% Added loop inside orbit feedback to reset the SR11 chicane M1 and M2 motors every 20s to combat drift problem
%
% 2003-06-18, C. Steier
% Disabled loop to periodically reset chicane in SR11. Al Robb replaced power supply, seems to be no problem anymore.
%
% 2004-05-10, C. Steier
% The list of all BBPMs is now set up automatically be calling getlist('BBPMx'). This way, new BBPMs have to be added
% at fewer places in the software. It should now be sufficient to modify getlist and run the orbit response matrix
% rountine (getsmat) once to enable use of the new BBPMs.
%
% 2004-05-14, C. Steier
% Modified parameters for ramprate reduction (in srramp and here). Previous parameters were slightly too
% cautious. Increased initial slow ramprate to 0.4 A/s.
%
% 2004-05-14, C. Steier
% Incorporated insertion device compensation schemes for nu_y = 9.2 lattice.
%
% 2004-06-14, T.Scarvie
% Added controls for fast orbit feedback
%
% 2004-06-21, C. Steier
% Added tune feedforward (in the global tune compensation scheme for the nu_y=9.2 lattice) for the shift
% dependent tune shift of the EPUs, as well as a skew quadrupole feedforward for the EPU im sector 11
% (both only active in parallel mode so far).
%
% 2005-02-13, T.Scarvie
% Separated horizontal and vertical planes for setting Fast Feedback PIDs
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% NOTES for conversion to new Middle Layer %
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%
% We never use the gap and bump control flags - the radio buttons have been disabled -
%        should we try to keep the functionality?
%
% remove handle globals
% set(0,'showhiddenhandles','on'); what does this do?
% grampbsc -> should be handled by new srramp (which uses k-values)
% checksrmags
% checksrorbit(...)
% getdcct
% setbpmtimeconstant
% getsmatelements
% Chicane trims are now part of the corrector family
% getname('IDrunflag',...) family name change
% write_goldenorbit_ffb, write_goldenorbit_ffb2
% For the compiler
%#function goldenpage
%#function setoperationalmode
% Check if the AO exists
checkforao;
%%%%%%%%%%%%%%
% Initialize %
%%%%%%%%%%%%%%
global FEEDBACK_STOP_FLAG
SR_Mode = getfamilydata('OperationalMode');
SR_GEV = getfamilydata('Energy');
BSCramprate = getfamilydata('BSCRampRate');
if isnan(BSCramprate) || isempty(BSCramprate)
    BSCramprate = 0.4;
    setfamilydata(BSCramprate, 'BSCRampRate');
end
if nargin < 1
    action = 'Initialize';
end
if nargin < 2
    Input2 = 0;
end
if nargin < 3
    Input3 = 0;
end
if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
    FOFBcheckboxVal = 0;
else
    FOFBcheckboxVal = 1;
end
%%%%%%%%%%%%%%%%
% Main Program %
%%%%%%%%%%%%%%%%
switch(action)
    case 'StopOrbitFeedback'
        FEEDBACK_STOP_FLAG = 1;
    case 'Initialize'
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        % GUI
        %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        ButtonWidth = 200;
        ButtonHeight  = 25;
        Offset1 = 8*25+12 + 47 + 25+25;
        Offset2 = 47+25+25;
        Offset3 = 45+25;
        Offset4 = 1;
        Offset5 = 30;
        FigWidth = ButtonWidth+6;
        FigHeight  = 3+7*(ButtonHeight+6)+24+Offset1;
        ButtonWidth = 200-6;
        % Change figure position
        set(0,'Units','pixels');
        p=get(0,'screensize');
        h0 = figure( ...
            'Color',[0.8 0.8 0.8], ...
            'HandleVisibility','Off', ...
            'Interruptible', 'on', ...
            'MenuBar','none', ...
            'Name','ALS SR CONTROL', ...
            'NumberTitle','off', ...
            'Units','pixels', ...
            'Position',[30 p(4)-FigHeight-40 FigWidth FigHeight+Offset5], ...
            'Resize','off', ...
            'Tag','SRCTRLFig1');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'FontWeight','Bold', ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+6*(ButtonHeight+3)+19+19+8+Offset1  ButtonWidth 20+Offset5], ...
            'Style','text', ...
            'String','', ...
            'Tag','SRCTRLTitle');
        % Frame Box I
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+1*(ButtonHeight+3)+Offset1-3+Offset5 ButtonWidth+6 7*ButtonHeight+18], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Callback','', ...
            'Enable','On', ...
            'FontSize',10, ...
            'Interruptible','Off', ...
            'HorizontalAlignment','Center', ...
            'Position',[6 3+7*(ButtonHeight+3)+Offset1  ButtonWidth 15+Offset5], ...
            'Style','text', ...
            'String','Lattice Setup Functions');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Cycle'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+6*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Cycle SR Lattice', ...
            'Tag','SRCTRLButton1');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Injection'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+5*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Injection', ...
            'Tag','SRCTRLButton2');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs'');srcontrol5(''Production'',get(findobj(gcbf,''Tag'',''SRCTRLRadioGaps''),''Value''),get(findobj(gcbf,''Tag'',''SRCTRLRadioBumps''),''Value''));', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+4*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Production', ...
            'Tag','SRCTRLButton3');
        h1 = uicontrol('Parent',h0, ...
            'Callback',[...
            'fprintf(''\n'');' ...
            'disp([''   **********************************************'']);', ...
            'disp([''   **  Changing Storage Ring Operational Mode  **'']);', ...
            'disp([''   **********************************************'']);', ...
            'setoperationalmode;', ...
            'srcontrol5(''CheckInputs'');', ...
            'disp([''   ****************************'']);', ...
            'disp([''   **  Mode Change Complete  **'']);', ...
            'disp([''   ****************************'']);', ...
            'fprintf(''\n'');'], ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 3+3*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'Value',1, ...
            'String','Change Operational Mode', ...
            'Tag','SRCTRLButtonChangeMode');
        h1 = uicontrol(...
            'Parent',h0, ...
            'Callback', [...
            'srcontrol5(''CheckInputs'');',...
            'srcontrol5(''SRState'');'], ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+2*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Check For Problems', ...
            'Tag','SRCTRLButtonSRState');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''CheckInputs''); goldenpage;', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+1*(ButtonHeight+3)+Offset1+Offset5 ButtonWidth ButtonHeight], ...
            'String','Golden Page', ...
            'Tag','SRCTRLButtonGoldenPage');
        % Frame Box II
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+7*(ButtonHeight+3)-29+Offset2+Offset5 ButtonWidth+6 2*ButtonHeight+15], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+8*(ButtonHeight+3)-10+Offset2 ButtonWidth .6*ButtonHeight+Offset5], ...
            'String','Global/Local Orbit Correction', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'Callback','srcontrol5(''OrbitCorrection'');', ...
            'Interruptible','Off', ...
            'Enable','On', ...
            'Position',[6 3+7*(ButtonHeight+3)-6+Offset2+Offset5 ButtonWidth ButtonHeight], ...
            'String','Correct Global Orbit w/ IDBPMs', ...
            'Tag','SRCTRLButtonOrbitCorrection');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''OrbitCorrectionSetup'',1);', ...
            'callback','srcontrol5(''OrbitCorrectionSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[6 7*(ButtonHeight+3)-22+Offset2+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Edit IDBPM, CM, & Local Bump Lists', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonOrbitCorrectionSetup');
        % Frame Box III
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 1.25*(ButtonHeight)+Offset3-45+Offset5 ButtonWidth+6 8*ButtonHeight+5], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'FontSize',10, ...
            'ListboxTop',0, ...
            'Position',[6 3+7*(ButtonHeight+3)+Offset3-25 ButtonWidth .55*ButtonHeight+Offset5], ...
            'String','Orbit Feedback', ...
            'Style','text');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+6*(ButtonHeight+3)+Offset3-18+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Slow Orbit Correction', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxSOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+5*(ButtonHeight+3)+Offset3-9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Fast Orbit Correction', ...
            'Style','checkbox', ...
            'Value',FOFBcheckboxVal,...
            'Tag','SRCTRLCheckboxFOFB');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+4*(ButtonHeight+3)+Offset3+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct ID Tune Shift  ', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxTune');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'Enable','on', ...
            'Interruptible', 'on', ...
            'Position',[26 3+3*(ButtonHeight+3)+Offset3+9+Offset5 ButtonWidth-32 .8*ButtonHeight], ...
            'String','Correct RF Frequency', ...
            'Style','checkbox', ...
            'Value',1,...
            'Tag','SRCTRLCheckboxRF');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''Feedback'');', ...
            'Enable','on', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[8 3+3*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Start FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStart');
        h1 = uicontrol('Parent',h0, ...
            'callback','srcontrol5(''StopOrbitFeedback'');pause(0);', ...
            'Enable','off', ...
            'FontSize',12, ...
            'Interruptible', 'on', ...
            'ListboxTop',0, ...
            'Position',[.5*FigWidth+3 3+3*(ButtonHeight+3)+3+Offset3-25+Offset5 .5*ButtonWidth-6 1.0*ButtonHeight], ...
            'String','Stop FB', ...
            'Value',0, ...
            'Tag','SRCTRLPushbuttonStop');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[14 3+2*(ButtonHeight)+14+Offset3-25+Offset5 ButtonWidth-14 .75*ButtonHeight], ...
            'String','Horizontal RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHorizontal');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','left', ...
            'ListboxTop',0, ...
            'Position',[26 3+1.25*(ButtonHeight)+16+Offset3-25+Offset5 ButtonWidth-26 .75*ButtonHeight], ...
            'String','Vertical RMS = _____ mm', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextVertical');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FeedbackSetup'',1);', ...
            'callback','srcontrol5(''FeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 3+1.25*(ButtonHeight)+.5+Offset3-25+Offset5 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit SOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFeedbackSetup');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''FastFeedbackSetup'',1);', ...
            'callback','srcontrol5(''FastFeedbackSetup'',0);', ...
            'Enable','on', ...
            'Interruptible', 'off', ...
            'Position',[8 3+1.25*(ButtonHeight)+.5+Offset3-45+Offset5 ButtonWidth-5 .75*ButtonHeight], ...
            'String','Edit FOFB Setup', ...
            'Style','PushButton', ...
            'Value',0,...
            'Tag','SRCTRLButtonFastFeedbackSetup');
        % Frame Box IV
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 3+ButtonHeight+Offset4-14+Offset5 ButtonWidth+6 ButtonHeight+12], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+1.75*ButtonHeight+5+Offset4-21+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','Storage Ring State', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextHeader');
        h1 = uicontrol('Parent',h0, ...
            'CreateFcn','srcontrol5(''CheckInputs'');', ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ForegroundColor','b', ...
            'HorizontalAlignment','center', ...
            'ListboxTop',0, ...
            'Position',[6 3+ButtonHeight+6+3+2+Offset4-22+Offset5 ButtonWidth .7*ButtonHeight], ...
            'String','   ', ...
            'Style','text', ...
            'Tag','SRCTRLStaticTextInformation');
        % Frame Box "Close"
        h1 = uicontrol('Parent',h0, ...
            'BackgroundColor',[0.8 0.8 0.8], ...
            'ListboxTop',0, ...
            'Position',[3 8 ButtonWidth+6 ButtonHeight+8], ...
            'Style','frame');
        h1 = uicontrol('Parent',h0, ...
            'Callback','close(gcbf);', ...
            'Enable','On', ...
            'Interruptible','Off', ...
            'Position',[6 13 ButtonWidth ButtonHeight], ...
            'String','Close', ...
            'Tag','SRCTRLClose');
        % Update database channels
        setsrstatechannels;
        if nargout > 0
            fig = h0;
        end
    case 'Cycle'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        disp('   **************************');
        disp('   **  Storage Ring Cycle  **');
        disp('   **************************');
        a = clock; fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        BSCFlag = questdlg(sprintf('Cycle Superbend Magnets?'),'SR Cycle','Yes','No','No');
        %if strcmp(BSCFlag,'No')
        %    disp(['   ** Superbends will not be cycled. **']);
        %else
        %    disp(['   ** Superbends will be cycled during the second mini-cycle only. **']);
        %end
        ChicSQFlag = questdlg(sprintf('Cycle chicanes and skew quads and home motor chicanes?'),'SR Cycle','Yes','No','No');
        %if strcmp(ChicSQFlag,'No')
        %    disp(['   ** Chicanes and skew quads will not be cycled; motor chicanes will not be homed. **']);
        %else
        %    disp(['   ** Chicanes and skew quads will be cycled; motor chicanes will be homed. **']);
        %end
        StartFlag = questdlg(sprintf('Start %.1f GeV Cycle?',SR_GEV),'SR Cycle','Yes','No','No');
        if strcmp(StartFlag,'No')
            disp('   ***************************');
            disp('   **    Cycle  Canceled    **');
            disp('   ***************************');
            fprintf('\n');
            return
        end
        try
            if GapFlag
                % Make sure that the gaps are open with FF off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open.');
                    disp('   Opening all gaps at maximum speed.');
                    setff([], 1, 0);
                    disp('   Gap control disabled.');
                    disp('   Feed forward enabled.');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened.');
                    disp('   Feed forward and gap control disabled.');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled.');
                end
            else
                disp('   Feed forward and gap control disabled.');
            end
            setff([], 0, 0);
            pause(1);
            srcycle(BSCFlag, ChicSQFlag);
            setpv('SR_STATE',1);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Cycle failed due to error condition! \n\n');
            setpv('SR_STATE',-1);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp('   **********************************************');
            disp('   **  SR Cycle complete, ready for injection  **');
            disp('   **********************************************'); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp('   **********************************');
            disp('   **  Problem cycling SR lattice  **');
            disp('   **********************************'); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
    case 'Injection'
        AD = getad;
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        fprintf('\n');
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            fprintf('   ***************************************************\n');
            fprintf('   **  Setup For %.2f GeV Injection (with ramping)  **\n', getfamilydata('InjectionEnergy'));
            fprintf('   ***************************************************\n');
            set_alarmhandler_AHU_thresholds_inject;
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',getfamilydata('InjectionEnergy')),'Injection Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            fprintf('   *************************************************\n');
            fprintf('   **  Setup For On Energy Injection at %.2f GeV  **\n', SR_GEV);
            fprintf('   *************************************************\n');
            StartFlag = questdlg(sprintf('Start setup for injection, %.2f GeV?',SR_GEV),'Injection Setup','Yes','Cancel','Cancel');
        end
        if strcmp(StartFlag,'Cancel')
            disp('   ********************************');
            disp('   **  Injection Setup Canceled  **');
            disp('   ********************************');
            set_alarmhandler_thresholds;
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                setff([],1,0);
                disp('   Gap control disabled');
                disp('   Feed forward enabled');
                pause(1);
                % Set IDs at max velocity w/ velocity profile off
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    disp('   Opening all gaps');
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                end
                disp('   Gaps are open');
                disp('   Feed forward and gap control disabled');
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            if (AD.Energy-AD.InjectionEnergy) > 0.05
                % Ramp down to Injection Energy
                ErrorFlag = srramp('Injection');
                if ErrorFlag
                    error('Superbends over temperature.');
                end
                a = clock; fprintf('   %s %d:%d:%.0f\n\n',date, a(4), a(5), a(6));
            elseif (AD.Energy-AD.InjectionEnergy) < -0.05
                % first load injection lattice, then ramp to 1.9 GeV and back to 1.5 GeV to get onto same hysteresis branch
                srload('Injection');
                % load 1.9 GeV lattice
                tempfilename = sprintf('%s19nuy9prod.mat', getfamilydata('Directory','OpsData'));
                srload(tempfilename);
                a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                pause(5);
            end
            srload('Injection');
            setpv('SR_STATE',2);
        catch
            fprintf('   %s \n',lasterr);
            fprintf('   Injection lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-2);
        end
        date;
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            if AD.Energy <= 1.5
                disp(['   *******************************************************************************']);
                disp(['   **  Function complete:  the storage ring is setup for injection at ',sprintf('%.2f',SR_GEV),' GeV  **']);
                disp(['   *******************************************************************************']);
                fprintf('\n');
            else
                fprintf('   **********************************************************************************************\n');
                fprintf('   **  Function complete:  the storage ring is setup for injection at %.2f GeV (upper branch)  **\n', getfamilydata('InjectionEnergy'));
                fprintf('   **********************************************************************************************\n');
                fprintf('\n');
            end
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp('   ************************************');
            disp('   **  Problem with injection setup  **');
            disp('   ************************************');
            fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        %soundchord;
        setfamilydata(0.8, 'BSCRampRate');
    case 'Production'
        GapFlag = Input2;
        BumpMagnetFlag = Input3;
        AD=getad;
        fprintf('\n');
        a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
        if abs(AD.Energy - AD.InjectionEnergy) > .05
            disp('   ********************************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation (with ramping)  **',SR_GEV));
            disp('   ********************************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Ramp quickly','Ramp slowly','Cancel','Cancel');
        else
            disp('   *****************************************');
            disp(sprintf('   **  Setup For %.2f GeV User Operation  **',SR_GEV));
            disp('   *****************************************');
            StartFlag = questdlg(sprintf('Start setup for users, %.1f GeV?',SR_GEV),'User Setup','Yes','Cancel','Cancel');
        end
        if strcmp(StartFlag,'Cancel')
            disp('   ***************************');
            disp('   **  User Setup Canceled  **');
            disp('   ***************************');
            fprintf('\n');
            return
        elseif strcmp(StartFlag,'Ramp quickly')
            setfamilydata(0.8, 'BSCRampRate');
        elseif strcmp(StartFlag,'Ramp slowly')
            setfamilydata(0.4, 'BSCRampRate');
        end
        try
            if GapFlag
                % Make sure that the gaps are open
                if any(getsp('IDpos') ~= maxsp('IDpos'))
                    % Set IDs at max velocity w/ velocity profile off
                    disp('   Insertion device gaps are not open');
                    disp('   Opening all gaps at maximum speed');
                    setff([], 1, 0);
                    disp('   Gap control disabled');
                    disp('   Feed forward enabled');
                    pause(1);
                    setid([], maxsp('IDpos'), maxsp('IDvel'), 1, 0, 1);
                    disp('   Gaps opened');
                    disp('   Feed forward and gap control disabled');
                    a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
                else
                    disp('   Feed forward and gap control disabled');
                end
            else
                disp('   Feed forward and gap control disabled');
            end
            setff([], 0, 0);
            pause(1);
            % Ramp up to the production lattice
            ErrorFlag = srramp('Production');
            if ErrorFlag
                error('Superbends over temperature.');
            end
            a = clock; fprintf('   %s %d:%d:%.0f\n',date, a(4), a(5), a(6));
            srload('Production');
            if GapFlag
                setff([], 1, 0);
                disp('   Gap control disabled');
                disp('   Feed forward enable');
                pause(1);
                disp('   Insertion device velocity profile boolean control off');
                disp('   Closing all gaps at maximum speed');
                % Set IDs at max velocity w/ velocity profile off
                [Position, Velocity, RunFlag, UserGap] = getid;
                setid([], UserGap, maxsp('IDvel'), 1, 0, 1);
                % Turn velocity profile on
                disp('   Insertion device velocity profile boolean control is on');
                setid([], [], maxsp('IDvel'), 1, 1, 0);
                disp('   Gaps are closed');
                setff([4;7;8;9;10;12], 1, 1);
                setff(5, 1, 0);
                disp('   Gap control enabled (except sector 5 (W16))');
            end
            set_alarmhandler_thresholds_new;
            setpv('SR_STATE',3);
        catch
            fprintf('   %s \n', lasterr);
            fprintf('   User lattice setup failed due to error condition! \n\n');
            setpv('SR_STATE',-3);
        end
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
            disp(['   **************************************************************************']);
            disp(['   **  Function complete:  the storage ring is setup for users at ',sprintf('%.1f',SR_GEV),' GeV  **']);
            disp(['   **************************************************************************']); fprintf('\n');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
            disp(['   *************************************']);
            disp(['   **  Problem with production setup  **']);
            disp(['   *************************************']); fprintf('\n');
        end
        set(0,'showhiddenhandles','off');
        setfamilydata(0.8, 'BSCRampRate');
    case 'CheckInputs'
        SR_GEV = getfamilydata('Energy');
        AD=getad;
        setsrstatechannels;
        set(0,'showhiddenhandles','on');
        if AD.Energy > 1.55
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Down)']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users (Ramp Up)']);
        elseif AD.Energy < 1.45
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection (Ramp Up+cycle)']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV (Ramp Down)']);
        else
            set(findobj('Tag','SRCTRLButton2'),'String',['Setup For Injection']);
            set(findobj('Tag','SRCTRLButton3'),'String',['Setup For Users, ',num2str(round(10*SR_GEV)/10),' GeV']);
        end
        set(findobj('Tag','SRCTRLTitle'),'String',SR_Mode);
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
        else
            set(findobj('Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
        end
        set(0,'showhiddenhandles','off');
    case 'SRState'
        NumErrors = 0;
        fprintf('\n');
        disp('   ***********************************');
        disp('   **  Checking Storage Ring State  **');
        disp('   ***********************************');
        a = clock;
        fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        %       FileName = getpv('SR_LATTICE_FILE','String');   % Last srload file name (in OLD MIDDLE LAYER nomenclature!!)
        GeVnow = bend2gev;
        if GeVnow == getfamilydata('Energy')
            [ConfigSetpoint, ConfigMonitor, FileName] = getproductionlattice;
        elseif GeVnow == getfamilydata('InjectionEnergy')
            [ConfigSetpoint, ConfigMonitor, FileName] = getinjectionlattice;
        else
            FileName = '';
        end
        [StateNumber, StateString] = getsrstate;
        fprintf('   Storage ring operational mode: %s\n', SR_Mode);
        if StateNumber < 0
            fprintf('   Storage ring state error: %s\n', StateString);
            NumErrors = NumErrors + 1;
        else
            fprintf('   Storage ring state: %s\n', StateString);
        end
        if StateNumber==0
            % Storage ring state unknown
            NumErrors = NumErrors + 1;
        elseif abs(StateNumber)==1 || abs(StateNumber)==2
            FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','InjectionFile') '.mat'];
            if ~strcmp(FileName, FileNameGoal)
                fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','InjectionFile'), FileName);
                NumErrors = NumErrors + 1;
            end
        else
            FileNameGoal = [getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile') '.mat'];
            if ~strcmp(FileName, FileNameGoal)
                fprintf('   Lattice file %s should be loaded but it appears that %s is loaded.\n', getfamilydata('OpsData','LatticeFile'), FileName);
                NumErrors = NumErrors + 1;
            end
        end
        % Check all SR magnets
        if isempty(FileName)
            fprintf('   Goal setpoints will not be checked since the last lattice load is unknown.\n');
            NumErrors1 = checksrmags('');
        else
%            NumErrors1 = checksrmags([getfamilydata('Directory','OpsData') FileName]);
            NumErrors1 = checksrmags(FileName);
        end
        if NumErrors1 == 0
            fprintf('   SR magnets power supplies are OK.\n');
        end
        NumErrors = NumErrors + NumErrors1;
        % Check RF frequency
        if isempty(FileName)
            fprintf('   RF frequency will not be checked since the last lattice load is unknown.\n');
        else
%            load([getfamilydata('Directory','OpsData'), FileName]);
            load(FileName);
            [tmp, RFHPCounterPresent] = getrf;
            if abs(RFHPCounterPresent-ConfigSetpoint.RF.Setpoint.Data) > .002
                NumErrors = NumErrors + 1;
                fprintf('   RF frequency should be %f, presently it is %f MHz (as measured by the HP counter).\n', ConfigSetpoint.RF.Setpoint.Data, RFHPCounterPresent);
            else
                fprintf('   RF frequency is OK (HP counter is %f MHz, at the time of the lattice save it was %f MHz).\n', RFHPCounterPresent, ConfigSetpoint.RF.Setpoint.Data);
            end
        end
        % Check for orbit problems
        if (StateNumber >= 3) && (getdcct > 2)   % Production lattice is loaded with beam in the machine
            Xtol = 0.070;
            Ytol = 0.010;
            NumErrors1 = checksrorbit([],Xtol,Ytol);
            if NumErrors1
                fprintf('   SR orbit in the ID straight sections or at Bergoz BPMs deviates more than allowed from the golden orbit.\n');
            else
                fprintf('   SR orbit in the ID straight sections and at Bergoz BPMs is OK.\n');
                fprintf('   The orbit is within %.3f mm horizontally and %.3f mm vertically', Xtol, Ytol);
            end
            NumErrors = NumErrors + NumErrors1;
        else
            fprintf('   Storage ring orbit was not checked.\n');
        end
        a = clock;
        datestr1=date;
        fprintf('   %s %d:%d:%.0f\n', datestr1, a(4), a(5), a(6));
        if NumErrors
            disp('   *********************************');
            disp('   **  Storage Ring Has Problems  **');
            disp('   *********************************');
        else
            disp('   **********************************');
            disp('   **  Storage Ring Lattice is OK  **');
            disp('   **********************************');
        end
        fprintf('   \n');
        set(0,'showhiddenhandles','on');
        [StateNumber, StateString] = getsrstate;
        if StateNumber >= 0
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
        else
            set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
        end
        set(0,'showhiddenhandles','off');
    case 'OrbitCorrection'
        fprintf('\n');
        fprintf('   *********************************\n');
        fprintf('   **  Starting Orbit Correction  **\n');
        fprintf('   *********************************\n');
        a = clock;
        fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
        StartFlag = questdlg(sprintf('Start orbit correction, %.1f GeV?',SR_GEV),'Orbit Correction','Yes','No','No');
        if strcmp(StartFlag,'No')
            disp('   ********************************');
1000             disp('   **  Orbit Correction Aborted  **');
1001             disp('   ********************************');
1002             fprintf('\n');
1003             return
1004         end
1005
1006         if getdcct < 5     % Don't correct the orbit if the current is too small
1007             fprintf('   Orbit not corrected due to small current.\n');
1008             return
1009         end
1010
1011         if abs(SR_GEV-bend2gev(getpv('BEND',[1 1])))>  0.05     % Don't use this routine for the injection lattice
1012             fprintf('   This routine should only be used for the production energy: Correction aborted\n');
1013             return
1014         end
1015
1016         SR_STATE_OLD = scaget('SR_STATE');
1017         set(0,'showhiddenhandles','on');
1018         setpv('SR_STATE',4);
1019         [StateNumber, StateString] = getsrstate;
1020         if StateNumber >= 0
1021             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1022         else
1023             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1024         end
1025         set(0,'showhiddenhandles','off');
1026
1027
1028         try
1029
1030             % 2 Hz update rate on IDBPMs
1031             disp('   IDBPM time constant set to 0.5s.')
1032             setbpmtimeconstant(0.5)
1033             pause(2);
1034
1035
1036             % Turn off feed forward
1037             fprintf('   Turning feed forward off.\n');
1038             [FFEnableBM, FFEnableBC] = getff;
1039             setff([], 0);
1040             scasleep(.2);
1041
1042
1043             % Get vectors
1044             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1045             LocalBumplist = FB.LocalBumplist;
1046
1047         catch
1048
1049             fprintf('   %s \n',lasterr);
1050             fprintf('   Orbit correction setup failed due to error condition! \n\n');
1051             setpv('SR_STATE',-4);
1052             set(0,'showhiddenhandles','on');
1053             [StateNumber, StateString] = getsrstate;
1054             if StateNumber >= 0
1055                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1056             else
1057                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1058             end
1059             set(0,'showhiddenhandles','off');
1060             return
1061
1062         end
1063
1064         iNotHCMChicane = find(FB.HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
1065         iHCMChicane = find(FB.HCMlist1(:,2) == 10);
1066         iNotVCMChicane = find(FB.VCMlist1(:,2) < 10);
1067         iVCMChicane = find(FB.VCMlist1(:,2) == 10);
1068
1069         fprintf('   Starting horizontal and vertical global orbit correction (SVD method).\n');
1070
1071         for iloop = 1:3
1072             try
1073                 % use the following to get corrector settings in OCS without setting them, so the values can be checked
1074                 FB.OCSx = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
1075                 FB.OCSy = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
1076                 if any(abs(FB.OCSx.CM.Delta(iNotHCMChicane)) > 5)
1077                   disp('   Orbit Correction is changing some horizontal corrector(s) > 5A!!');
1078                 end
1079                 if any(abs(FB.OCSy.CM.Delta(iNotVCMChicane)) > 5)
1080                   disp('   Orbit Correction is changing some vertical corrector(s) > 5A!!');
1081                 end
1082                 if any(abs(FB.OCSx.CM.Delta(iHCMChicane)) > 10)
1083                   disp('   Orbit Correction is changing some horizontal chicane corrector(s) > 10A!!');
1084                 end
1085                 if any(abs(FB.OCSy.CM.Delta(iVCMChicane)) > 10)
1086                   disp('   Orbit Correction is changing some vertical chicane corrector(s) > 10A!!');
1087                 end
1088
1089
1090                 % Correct horizontal orbit
1091                 FB.OCSx = setorbit(FB.OCSx,'NoDisplay');
1092                 % Correct vertical orbit
1093                 FB.OCSy = setorbit(FB.OCSy,'NoDisplay');
1094
1095
1096                 % Check for current in machine - stop orbit correction if DCCT < 5mA
1097                 if (getdcct < 4.5)
1098                     error('**There is less than 5mA in the machine! Stopping orbit correction.');
1099                 end
1100
1101                 % Check state of gaps - stop orbit correction if any are moving
1102                 GAPrunflag = getpv('ID','RunFlag');
1103                 if any(GAPrunflag-round(GAPrunflag))
1104                     error('**One or more of the gaps are moving! Stopping orbit correction.');
1105                 end
1106
1107                 x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
1108                 y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
1109                 fprintf('   %d. Horizontal RMS = %.3f mm\n', iloop, norm(x)/sqrt(length(x)));
1110                 fprintf('   %d.   Vertical RMS = %.3f mm\n', iloop, norm(y)/sqrt(length(y)));
1111
1112             catch
1113                 % fprintf('   %s \n',lasterr);
1114                 fprintf('   Orbit correction failed due to error condition!\n  Fix the problem, reload the lattice (srload), and try again.  \n\n');
1115                 setpv('SR_STATE',-4);
1116                 set(0,'showhiddenhandles','on');
1117                 [StateNumber, StateString] = getsrstate;
1118                 if StateNumber >= 0
1119                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1120                 else
1121                     set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1122                 end
1123                 set(0,'showhiddenhandles','off');
1124                 return
1125             end
1126         end
1127
1128
1129         % Set user bumps w/o sextupole correctors
1130         try
1131
1132             %turn up corrector speed here to quicken setting bumps
1133             HCMramprate = getpv('HCM', 'RampRate');
1134             VCMramprate = getpv('VCM', 'RampRate');
1135             setpv('HCM', 'RampRate', 10, [], 0);
1136             setpv('VCM', 'RampRate', 10, [], 0);
1137
1138             if ~isempty(LocalBumplist)
1139                 fprintf('   Setting local bumps in the straight sections.\n');
1140                 for loop = 1:size(LocalBumplist,1)
1141
1142                     % Check for current in machine - stop orbit correction if DCCT < 5mA
1143                     if (getdcct < 5)
1144                         error('** There is less than 5mA in the machine! Stopping local bumps.');
1145                     end
1146
1147                     % Check state of gaps - stop setting bumps if any are moving
1148                     GAPrunflag = getpv('ID','RunFlag');
1149                     if any(GAPrunflag-round(GAPrunflag))
1150                         error('** One or more of the gaps are moving! Stopping local bumps.');
1151                     end
1152
1153                     HCMoldsp = getsp('HCM', FB.HCMlist1);
1154                     VCMoldsp = getsp('VCM', FB.VCMlist1);
1155
1156                     if any(LocalBumplist(loop,1) == [4 6 11])
1157                         if LocalBumplist(loop,2) == 0
1158                             % Upstream bump
1159                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1160                             if isempty(iRemove)
1161                                 setbumps(LocalBumplist(loop,:), 1);
1162                             else
1163                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1164                             end
1165                         elseif LocalBumplist(loop,2) == 1
1166                             % Upstream bump
1167                             [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1)-1 11;],FB.OCSx.BPM.DeviceList);
1168                             if isempty(iRemove)
1169                                 setbumps(LocalBumplist(loop,:), 1);
1170                             else
1171                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1172                             end
1173                         else
1174                             % Downstream bump
1175                             [i, iRemove] = findrowindex([LocalBumplist(loop,1)-1 12;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1176                             if isempty(iRemove)
1177                                 setbumps(LocalBumplist(loop,:), 1);
1178                             else
1179                                 fprintf('\n   BPMs missing from Sector(%02d,%02d) - skipping local bump for that sector.\n\n', LocalBumplist(loop,:));
1180                             end
1181                         end
1182                     else
1183                         [i,iRemove] = findrowindex([LocalBumplist(loop,1)-1 10;LocalBumplist(loop,1) 1],FB.OCSx.BPM.DeviceList);
1184                         if isempty(iRemove)
1185                             setbumps(LocalBumplist(loop,:), 1);
1186                         else
1187                             fprintf('\n   BPMs missing from Sector %02d - skipping local bump for that sector.\n\n', LocalBumplist(loop,1));
1188                         end
1189                     end
1190
1191                     HCMnewsp = getsp('HCM', FB.HCMlist1);
1192                     VCMnewsp = getsp('VCM', FB.VCMlist1);
1193                     % Remove center chicane trim from corrector check
1194                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 5) || (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 10)
1195                         error('**Setbumps caused some corrector magnet currents to change by more than 5(Horiz)/10(Vert) A!');
1196                     end
1197                     % Now check center chicane trims
1198                     if (max(abs(HCMoldsp(iNotHCMChicane)-HCMnewsp(iNotHCMChicane))) > 10) || (max(abs(VCMoldsp(iNotVCMChicane)-VCMnewsp(iNotVCMChicane))) > 15)
1199                         error('**Setbumps caused some chicane trim magnet currents to change by more than 10(Horiz)/15(Vert) A!');
1200                     end
1201                 end
1202             end
1203
1204             %restore corrector speeds
1205             setpv('HCM', 'RampRate', HCMramprate, [], 0);
1206             setpv('VCM', 'RampRate', VCMramprate, [], 0);
1207
1208         catch
1209             fprintf('   %s \n',lasterr);
1210             fprintf('   Setbumps failed due to error condition!  Fix the problem, reload the lattice (srload), and try again.\n\n');
1211             setpv('SR_STATE',-4);
1212             set(0,'showhiddenhandles','on');
1213             [StateNumber, StateString] = getsrstate;
1214             if StateNumber >= 0
1215                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1216             else
1217                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1218             end
1219             set(0,'showhiddenhandles','off');
1220             return
1221         end
1222
1223
1224         % Turn feed forward back to it's original state
1225         if any(FFEnableBC)
1226             fprintf('   Turning feed forward back on.\n');
1227             setff([], FFEnableBC);
1228         end
1229
1230
1231         a = clock;
1232         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1233         [StateNumber, StateString] = getsrstate;
1234         set(0,'showhiddenhandles','on');
1235         if StateNumber >= 0
1236             setpv('SR_STATE',4.1);
1237             [StateNumber, StateString] = getsrstate;
1238             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1239             fprintf('   *********************************\n');
1240             fprintf('   **  Orbit Correction Complete  **\n');
1241             fprintf('   *********************************\n\n');
1242         else
1243             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1244             fprintf('   *************************************\n');
1245             fprintf('   **  Problem With Orbit Correction  **\n');
1246             fprintf('   *************************************\n\n');
1247         end
1248         set(0,'showhiddenhandles','off');
1249         pause(0);
1250
1251
1252     case 'OrbitCorrectionSetup'
1253         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
1254
1255         if InitFlag
1256             % Setup feedback elements
1257             % disp('Orbit correction condition: InitFlag=1 -- debugging message');
1258
1259             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1260             % Edit the following lists to change default configuration of Orbit Correction %
1261             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1262             hlist=[];vlist=[];
1263             for Sector =1:12
1264                 if Sector == 1
1265                     vlist = [vlist;Sector 2;Sector 4;Sector 5;Sector 8];
1266                     hlist = [hlist;Sector 2;Sector 7];
1267                 elseif Sector == 3
1268                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1269                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1270                 elseif Sector == 5
1271                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1272                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1273                 elseif Sector == 10
1274                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8;Sector 10];
1275                     hlist = [hlist;Sector 2;Sector 7;Sector 10];
1276                 elseif Sector == 12
1277                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 7];
1278                     hlist = [hlist;Sector 2;Sector 7];
1279                 else
1280                     vlist = [vlist;Sector 1;Sector 4;Sector 5;Sector 8];
1281                     hlist = [hlist;Sector 2;Sector 7];
1282                 end
1283             end
1284             HCMlist1 = hlist;
1285             VCMlist1 = vlist;
1286
1287             BPMlist1 = [
1288                 1 2
1289                 1 5
1290                 1 6
1291                 1 10
1292                 2 1
1293                 2 5
1294                 2 6
1295                 2 9
1296                 3 2
1297                 3 5
1298                 3 6
1299                 3 10
1300                 3 11
1301                 3 12
1302                 4 1
1303                 4 5
1304                 4 6
1305                 4 10
1306                 5 1
1307                 5 5
1308                 5 6
1309                 5 10
1310                 5 11
1311                 5 12
1312                 6 1
1313                 6 5
1314                 6 6
1315                 6 10
1316                 7 1
1317                 7 5
1318                 7 6
1319                 7 10
1320                 8 1
1321                 8 5
1322                 8 6
1323                 8 10
1324                 9 1
1325                 9 5
1326                 9 6
1327                 9 10
1328                 10 1
1329                 10 5
1330                 10 6
1331                 10 10
1332                 10 11
1333                 10 12
1334                 11 1
1335                 11 5
1336                 11 6
1337                 11 10
1338                 12 1
1339                 12 5
1340                 12 6
1341                 12 9];
1342
1343             % SVD orbit correction
1344             Xivec = [1:28];
1345             Yivec = [1:48];
1346
1347
1348             LocalBumplist = [
1349               % 1 1
1350               % 2 1
1351               % 3 1
1352                 4 1
1353               % 4 2
1354                 5 1
1355                 6 1
1356               % 6 2
1357                 7 1
1358                 8 1
1359                 9 1
1360                 10 1
1361                 11 1
1362                 11 2
1363                 12 1
1364 ];
1365             %LocalBumplist = []
1366
1367             % initialize RFCorrFlag
1368             RFCorrFlag = 'Yes';
1369         else
1370
1371             % Get vectors
1372             FB = get(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata');
1373             BPMlist1 = FB.BPMlist1;
1374             HCMlist1 = FB.HCMlist1;
1375             VCMlist1 = FB.VCMlist1;
1376             Xivec = FB.Xivec;
1377             Yivec = FB.Yivec;
1378             LocalBumplist = FB.LocalBumplist;
1379             Xgoal = FB.Xgoal;
1380             Ygoal = FB.Ygoal;
1381             RFCorrFlag = FB.RFCorrFlag;
1382
1383             % Add button to change #ivectors, CMs, IDBPMs,
1384             EditFlag = 0;
1385             h_fig1 = figure;
1386             while EditFlag ~= 8
1387
1388                 % Sensitivity matrix
1389                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
1390                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
1391
1392                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1393                 % Can the call below work for setting FOFB RF parameter? %
1394                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
1395                 if strcmpi(RFCorrFlag, 'Yes')
1396                     Sx = [Sx getdisp('BPMx',BPMlist1)];
1397                 end
1398
1399                 [Ux, SVx, Vx] = svd(Sx);
1400                 [Uy, SVy, Vy] = svd(Sy);
1401
1402
1403                 % Remove singular values greater than the actual number of singular values
1404                 i = find(Xivec>length(diag(SVx)));
1405                 if ~isempty(i)
1406                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
1407                     pause(0);
1408                     Xivec(i) = [];
1409                 end
1410                 i = find(Yivec>length(diag(SVy)));
1411                 if ~isempty(i)
1412                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
1413                     pause(0);
1414                     Yivec(i) = [];
1415                 end
1416
1417
1418                 Ax = Sx*Vx(:,Xivec);
1419                 Tx = inv(Ax'*Ax)*Ax';
1420
1421                 Ay = Sy*Vy(:,Yivec);
1422                 Ty = inv(Ay'*Ay)*Ay';
1423
1424
1425                 figure(h_fig1);
1426                 subplot(2,1,1);
1427                 semilogy(diag(SVx),'b');
1428                 hold on;
1429                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
1430                 ylabel('Horizontal');
1431                 title('Response Matrix Singular Values');
1432                 hold off;
1433                 subplot(2,1,2);
1434                 semilogy(diag(SVy),'b');
1435                 hold on;
1436                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
1437                 xlabel('Singular Value Number');
1438                 ylabel('Vertical');
1439                 hold off;
1440                 drawnow;
1441
1442                 if strcmp(RFCorrFlag,'No')
1443                     RFCorrState = 'NOT CORRECTED';
1444                 elseif strcmp(RFCorrFlag,'Yes')
1445                     RFCorrState = 'CORRECTED';
1446                 else
1447                     RFCorrState = '???';
1448                 end
1449
1450                 %         EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','HCM Chicane List','VCM Chicane List','IDBPM List','BBPM List','Change Golden Orbit',...
1451                 %            'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1452                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List','BPM List','Change Golden Orbit',...
1453                     'Local Bump List',sprintf('RF Frequency (currently %s)',RFCorrState),'Continue');
1454
1455                 if EditFlag == 1
1456                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
1457                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
1458                     titlestr='SVD Orbit Feedback';
1459                     lineNo=1;
1460                     answer=inputdlg(prompt,titlestr,lineNo,def);
1461                     if ~isempty(answer)
1462                         XivecNew = fix(str2num(answer{1}));
1463                         if isempty(XivecNew)
1464                             disp('   Horizontal E-vector cannot be empty.  No change made.');
1465                         else
1466                             if any(XivecNew<=0) || max(XivecNew)>length(diag(SVx))
1467                                 disp('   Error reading horizontal E-vector.  No change made.');
1468                             else
1469                                 Xivec = XivecNew;
1470                             end
1471                         end
1472                         YivecNew = fix(str2num(answer{2}));
1473                         if isempty(YivecNew)
1474                             disp('   Vertical E-vector cannot be empty.  No change made.');
1475                         else
1476                             if any(YivecNew<=0) || max(YivecNew)>length(diag(SVy))
1477                                 disp('   Error reading vertical E-vector.  No change made.');
1478                             else
1479                                 Yivec = YivecNew;
1480                             end
1481                         end
1482                     end
1483                 end
1484
1485                 if EditFlag == 2
1486                     List = getlist('HCM');
1487                     CheckList = zeros(size(List,1));
1488                     Elem = dev2elem('HCM', HCMlist1);
1489                     CheckList(Elem) = ones(size(Elem));
1490                     CheckList = CheckList(dev2elem('HCM',List));
1491                     newList = editlist(List, 'HCM', CheckList);
1492                     if isempty(newList)
1493                         fprintf('   Horizontal corrector magnet list cannot be empty.  No change made.\n');
1494                     else
1495                         HCMlist1 = newList;
1496                     end
1497                 end
1498
1499                 if EditFlag == 3
1500                     List = getlist('VCM');
1501                     CheckList = zeros(size(List,1));
1502                     Elem = dev2elem('VCM', VCMlist1);
1503                     CheckList(Elem) = ones(size(Elem));
1504                     CheckList = CheckList(dev2elem('VCM',List));
1505                     newList = editlist(List, 'VCM', CheckList);
1506                     if isempty(newList)
1507                         fprintf('   Vertical corrector magnet cannot be empty.  No change made.\n');
1508                     else
1509                         VCMlist1 = newList;
1510                     end
1511                 end
1512
1513                 if EditFlag == 4
1514                     ListOld = BPMlist1;
1515                     XgoalOld = Xgoal;
1516                     YgoalOld = Ygoal;
1517
1518                     % Full BPM list
1519                     List = [
1520                         1 2
1521                         1 5
1522                         1 6
1523                         1 10
1524                         2 1
1525                         2 5
1526                         2 6
1527                         2 9
1528                         3 2
1529                         3 5
1530                         3 6
1531                         3 10
1532                         3 11
1533                         3 12
1534                         4 1
1535                         4 5
1536                         4 6
1537                         4 10
1538                         5 1
1539                         5 5
1540                         5 6
1541                         5 10
1542                         5 11
1543                         5 12
1544                         6 1
1545                         6 5
1546                         6 6
1547                         6 10
1548                         7 1
1549                         7 5
1550                         7 6
1551                         7 10
1552                         8 1
1553                         8 5
1554                         8 6
1555                         8 10
1556                         9 1
1557                         9 5
1558                         9 6
1559                         9 10
1560                         10 1
1561                         10 5
1562                         10 6
1563                         10 10
1564                         10 11
1565                         10 12
1566                         11 1
1567                         11 5
1568                         11 6
1569                         11 10
1570                         12 1
1571                         12 5
1572                         12 6
1573                         12 9
1574                         ];
1575
1576                     CheckList = zeros(size(List,1),1);
1577                     if ~isempty(BPMlist1)
1578                         for i = 1:size(List,1)
1579                             k = find(List(i,1)==BPMlist1(:,1));
1580                             l = find(List(i,2)==BPMlist1(k,2));
1581
1582                             if isempty(k) || isempty(l)
1583                                 % Item not in list
1584                             else
1585                                 CheckList(i) = 1;
1586                             end
1587                         end
1588                     end
1589
1590                     newList = editlist(List, 'BPM', CheckList);
1591                     if isempty(newList)
1592                         fprintf('   BPM list cannot be empty.  No change made.\n');
1593                     else
1594                         BPMlist1 = newList;
1595                     end
1596
1597                     % Set the goal orbit to the golden orbit
1598                     Xgoal = getgolden('BPMx', BPMlist1);
1599                     Ygoal = getgolden('BPMy', BPMlist1);
1600
1601
1602                     % If a new BPM is added, then set the goal orbit to the golden orbit
1603                     for i = 1:size(BPMlist1,1)
1604
1605                         % Is it a new BPM?
1606                         k = find(BPMlist1(i,1)==ListOld(:,1));
1607                         l = find(BPMlist1(i,2)==ListOld(k,2));
1608
1609                         if isempty(k) || isempty(l)
1610                             % New BPM
1611                         else
1612                             % Use the old value for old BPM
1613                             Xgoal(i) = XgoalOld(k(l));
1614                             Ygoal(i) = YgoalOld(k(l));
1615                         end
1616                     end
1617                 end
1618
1619                 if EditFlag == 5
1620
1621                     ChangeList = editlist(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
1622                     for i = 1:size(ChangeList,1)
1623
1624                         k = find(ChangeList(i,1)==BPMlist1(:,1));
1625                         l = find(ChangeList(i,2)==BPMlist1(k,2));
1626
1627                         prompt = {sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
1628                         def = {sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
1629                         titlestr = 'CHANGE THE GOAL ORBIT';
1630                         lineNo = 1;
1631                         answer = inputdlg(prompt, titlestr, lineNo, def);
1632
1633                         if isempty(answer)
1634                             % No change
1635                             fprintf('   No change was made to the golden orbit.\n');
1636                         else
1637                             Xgoalnew = str2num(answer{1});
1638                             if isempty(Xgoalnew)
1639                                 fprintf('   No change was made to the horizontal golden orbit.\n');
1640                             else
1641                                 Xgoal(k(l)) = Xgoalnew;
1642                             end
1643
1644                             Ygoalnew = str2num(answer{2});
1645                             if isempty(Ygoalnew)
1646                                 fprintf('   No change was made to the vertical golden orbit.\n');
1647                             else
1648                                 Ygoal(k(l)) = Ygoalnew;
1649                             end
1650                         end
1651                     end
1652                     if ~isempty(ChangeList)
1653                         fprintf('   Note:  changing the goal orbit for "Orbit Correction" does not change the goal orbit for "Slow Orbit Feedback."\n');
1654                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
1655                     end
1656                 end
1657
1658                 if EditFlag == 6
1659                     List = [
1660                         1 1
1661                         2 1
1662                         3 1
1663                         4 1
1664                         4 2
1665                         5 1
1666                         6 1
1667                         6 2
1668                         7 1
1669                         8 1
1670                         9 1
1671                         10 1
1672                         11 1
1673                         11 2
1674                         12 1];
1675                     CheckList = zeros(size(List,1),1);
1676                     if ~isempty(LocalBumplist)
1677                         for i = 1:size(List,1)
1678                             k = find(List(i,1)==LocalBumplist(:,1));
1679                             l = find(List(i,2)==LocalBumplist(k,2));
1680
1681                             if isempty(k) | isempty(l)
1682                                 % Item not in list
1683                             else
1684                                 CheckList(i) = 1;
1685                             end
1686                         end
1687                     end
1688                     LocalBumplist = editlist2(List, 'Sector', CheckList);
1689                 end
1690
1691                 if EditFlag == 7
1692                     RFCorrFlag = questdlg(sprintf('Set RF Frequency during Orbit Correction?'),'RF Frequency','Yes','No', 'No');
1693                     if strcmp(RFCorrFlag,'No')
1694                         disp(['   RF Frequency will not be included in global orbit correction.']);
1695                     elseif strcmp(RFCorrFlag,'Yes')
1696                         disp(['   RF Frequency will be included in global orbit correction.']);
1697                     end
1698
1699                 end
1700             end
1701             close(h_fig1);
1702         end
1703
1704 %  ORBIT CORRECTION STRUCTURE (OCS)
1705 %    OCS.BPM (data structure)
1706 %    OCS.CM  (data structure)
1707 %    OCS.GoalOrbit
1708 %    OCS.NIter
1709 %    OCS.SVDIndex
1710 %    OCS.IncrementalFlag = 'Yes'/'No'
1711 %    OCS.BPMWeight
1712 %    OCS.Flags = { 'FitRF' , etc.  }
1713         OCSx.BPM = getx(BPMlist1, 'struct');
1714         OCSx.CM = getsp('HCM', HCMlist1, 'struct');
1715         OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
1716         OCSx.NIter = 1;
1717         OCSx.SVDIndex = Xivec;
1718         OCSx.IncrementalFlag = 'No';
1719         OCSx.FitRF = 1;
1720         OCSy.BPM = gety(BPMlist1, 'struct');
1721         OCSy.CM = getsp('VCM', VCMlist1, 'struct');
1722         OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
1723         OCSy.NIter = 1;
1724         OCSy.SVDIndex = Yivec;
1725         OCSy.IncrementalFlag = 'No';
1726         OCSy.FitRF = 0;
1727
1728         % Save vectors
1729         FB.OCSx = OCSx;
1730         FB.OCSy = OCSy;
1731
1732         FB.BPMlist1 = BPMlist1;
1733         FB.HCMlist1 = HCMlist1;
1734         FB.VCMlist1 = VCMlist1;
1735         FB.Xivec = Xivec;
1736         FB.Yivec = Yivec;
1737         FB.Xgoal = OCSx.GoalOrbit;
1738         FB.Ygoal = OCSy.GoalOrbit;
1739         FB.RFCorrFlag = RFCorrFlag;
1740         FB.LocalBumplist = LocalBumplist;
1741         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Userdata',FB);
1742
1743
1744     case 'Feedback'
1745
1746         FBloopIter = 1;
1747         if get(findobj(gcbf,'Tag','SRCTRLCheckboxFOFB'),'Value') == 1
1748             StartFOFBFlag = 1;
1749         else
1750             StartFOFBFlag = 0;
1751         end
1752
1753         FEEDBACK_STOP_FLAG = 0;
1754         HWarnNum=0;
1755         VWarnNum=0;
1756
1757         SR_GeV = getenergy;
1758         % Feedback loop setup
1759         PlotInfoFlag = 0;           % Plot micado stuff
1760         LoopDelay = 2;           % Period of feedback loop [seconds], make sure the BPM averaging is correct
1761         VCM_LSB = .00366211;
1762         VCMCHICANE_LSB = .002441;   % 80 max?,  Note: not fully implemented
1763
1764         if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
1765             Xgain  = 0.2;
1766             Ygain  = 0.1;
1767         else
1768             Xgain  = 0.8; % raised 0.5->0.8 at 17:20, 3-2-05 to more quickly correct EPU4 fast switching orbit distortions
1769             Ygain  = 0.8;
1770         end
1771
1772         % Load lattice set for tune feed forward
1773         ConfigSetpoint = getproductionlattice;
1774         %load([getfamilydata('Directory','OpsData') getfamilydata('OpsData','LatticeFile')]);
1775         QFsp = ConfigSetpoint.QF.Setpoint.Data;
1776         QDsp = ConfigSetpoint.QD.Setpoint.Data;
1777         TuneW16Min = gap2tune(5, 13.23, 1.8909);
1778         % Tune response matrix
1779         SR_TUNE_MATRIX = gettuneresp({'QF','QD'}, {[],[]}, getenergy('Production'));    % Approx. [0.1944 -0.0286;-0.1182 0.1526];
1780         %SR_TUNE_MATRIX = [0.1641 -0.0245
1781         %                 -0.1149 0.1477];
1782
1783         % ID tune compensation does not work in the injection lattice, so ...
1784         if abs(SR_GEV - bend2gev)>  0.05     % Don't use this routine for the injection lattice
1785             fprintf('   This routine should only be used for the production energy: Orbit feedback aborted\n');
1786             return
1787         end
1788
1789         set(0,'showhiddenhandles','on');
1790
1791         try
1792             fprintf('\n');
1793             fprintf('   *******************************\n');
1794             fprintf('   **  Starting Orbit Feedback  **\n');
1795             fprintf('   *******************************\n');
1796             a = clock;
1797             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1798             fprintf('   Note: the Matlab command window will be used to display status information.\n');
1799             fprintf('         It cannot be used to enter commands during slow orbit feedback.\n');
1800
1801
1802             % >= 2 Hz update rate on IDBPMs
1803             disp('   IDBPM time constant set to 0.2s.')
1804             setbpmtimeconstant(0.2)
1805             pause(1.1);
1806
1807             % Check whether bumps and kickers are on and warn to turn off before starting feedback if necessary
1808             try
1809                 if (getsp('SR01S___BUMP1__BC21')==1 && getsp('SR01S___BUMP1P_BC22')==1) || (getsp('SR01S___SEK____BC21')==1 && getsp('SR01S___SEK_P__BC23')==1) || (getsp('SR01S___SEN____BC20')==1 && getsp('SR01S___SEN_P__BC22')==1)
1810                     soundtada;
1811                     fprintf('   \n');
1812                     fprintf('   *********************************************************************************\n');
1813                     fprintf('   ** One or more of the pulsed SR injection magnets is still on!  Turn them off! **\n');
1814                     fprintf('   *********************************************************************************\n');
1815                     fprintf('   \n');
1816                 end
1817             catch
1818                 disp('**Problem checking the state of the bumps and kickers - please check that they are not pulsing.');
1819             end
1820
1821             % Get vectors
1822
1823             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
1824
1825             BPMlist1 = FB.OCSx.BPM.DeviceList;
1826             % FOFB_BPMlist =
1827             HCMlist1 = FB.HCMlist1;
1828             VCMlist1 = FB.VCMlist1;
1829             Xivec = FB.Xivec;
1830             Yivec = FB.Yivec;
1831             Xgoal = FB.OCSx.GoalOrbit;
1832             Ygoal = FB.OCSy.GoalOrbit;
1833             FFTypeFlag = FB.FFTypeFlag;   %local or global tune correction
1834
1835             iNotHCMChicane = find(HCMlist1(:,2) < 10); %used by steppv's for setting correctors in loop
1836             iHCMChicane = find(HCMlist1(:,2) == 10);
1837             iNotVCMChicane = find(VCMlist1(:,2) < 10);
1838             iVCMChicane = find(VCMlist1(:,2) == 10);
1839
1840             % Sensitivity matrix for setting fast feedback setpoints
1841             Sx1 = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
1842             Sy1 = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
1843
1844         catch
1845             fprintf('\n  %s \n',lasterr);
1846
1847             % >= 2 Hz update rate on IDBPMs
1848             disp('   IDBPM time constant set to 0.25s.')
1849             setbpmtimeconstant(0.25)
1850
1851
1852             a = clock;
1853             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1854             fprintf('   *************************************************************\n');
1855             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
1856             fprintf('   *************************************************************\n\n');
1857             set(0,'showhiddenhandles','off');
1858             pause(0);
1859
1860             return
1861         end
1862
1863         StartFlag = questdlg(strvcat('','Is it OK to start orbit feedback?'),'Orbit Feedback','Yes','No','No');
1864         if strcmp(StartFlag,'No')
1865             % >= 2 Hz update rate on IDBPMs
1866             disp('   IDBPM time constant set to 0.25s.')
1867             setbpmtimeconstant(0.25)
1868
1869             a = clock;
1870             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1871             fprintf('   ***************************\n');
1872             fprintf('   **  Orbit Feedback Exit  **\n');
1873             fprintf('   ***************************\n\n');
1874             pause(0);
1875             return
1876         end
1877
1878         SR_STATE_OLD = scaget('SR_STATE');
1879         setpv('SR_STATE', 5);
1880         set(0,'showhiddenhandles','on');
1881         [StateNumber, StateString] = getsrstate;
1882         if StateNumber >= 0
1883             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1884         else
1885             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1886         end
1887         fprintf('   Using %d E-vectors horizontally.\n', length(Xivec));
1888         fprintf('   Using %d E-vectors vertically.\n',   length(Yivec));
1889         fprintf('   Starting slow orbit correction every %.1f seconds.\n', LoopDelay);
1890         %  fprintf('   Resetting SR11 chicane motors every 20 seconds to fix drift problem.\n');
1891
1892
1893         try
1894
1895             % Get and display data
1896             x = FB.OCSx.GoalOrbit - getx(FB.OCSx.BPM.DeviceList);
1897             y = FB.OCSy.GoalOrbit - gety(FB.OCSy.BPM.DeviceList);
1898             STDx = norm(x)/sqrt(length(x));
1899             STDy = norm(y)/sqrt(length(y));
1900             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
1901             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
1902
1903             % write goldenorbit values to Fast Orbit Feedback
1904             try
1905                 write_goldenorbit_ffb;
1906             catch
1907                 disp('write_goldenorbit_ffb did not work!');
1908             end
1909             setpv('SR01____FFBON__BC00',2);
1910             pause(0);
1911
1912         catch
1913
1914             fprintf('\n  %s \n',lasterr);
1915
1916             % >= 2 Hz update rate on IDBPMs
1917             disp('   IDBPM time constant set to 0.25s.')
1918             setbpmtimeconstant(0.25);
1919
1920
1921             a = clock;
1922             fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
1923             fprintf('   *************************************************************\n');
1924             fprintf('   **  Orbit feedback could not start due to error condition  **\n');
1925             fprintf('   *************************************************************\n\n');
1926
1927             setpv('SR_STATE',SR_STATE_OLD);
1928             [StateNumber, StateString] = getsrstate;
1929             if StateNumber >= 0
1930                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
1931             else
1932                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
1933             end
1934             set(0,'showhiddenhandles','off');
1935             pause(0);
1936
1937             return
1938
1939         end
1940
1941
1942         % Disable buttons
1943         set(0,'showhiddenhandles','on');
1944         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','off');
1945         set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','on');
1946         set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','off');
1947         set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','off');
1948         set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','off');
1949         set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','off');
1950         set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','off');
1951         set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','off');
1952         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','off');
1953         set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','off');
1954         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','off');
1955         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','off');
1956         set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','off');
1957         pause(0);
1958
1959
1960         % Initialize feedback loop
1961         StartTime = gettime;
1962         StartErrorTime = gettime;
1963         Xold = getx(FB.OCSx.BPM.DeviceList);
1964         Yold = gety(FB.OCSy.BPM.DeviceList);
1965         HQMOFM_stalenum = 0;
1966         pause(LoopDelay);
1967
1968         N_HCM = size(HCMlist1,1);
1969         N_VCM = size(VCMlist1,1);
1970
1971         N_RFMO = 1;
1972
1973         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
1974             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'SetRF','Nodisplay','Nosetsp');
1975         else
1976             [FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
1977         end
1978         [FB.OCSx, Smatx, Sx, Ux, Vx] = orbitcorrectionmethods(FB.OCSx);
1979
1980         [FB.OCSy, junk, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
1981         [FB.OCSy, Smaty, Sy, Uy, Vy] = orbitcorrectionmethods(FB.OCSy);
1982
1983
1984         %%%%%%%%%%%%%%%%%%%%%%%
1985         % Start feedback loop %
1986         %%%%%%%%%%%%%%%%%%%%%%%
1987
1988         % chicaneloop=1;  % loop variable for resetting drifting chicanes (see a few lines below)
1989         % fftest=figure;
1990
1991         setpv('SR01____FFBON__BC00',2); % put FOFB in open loop so beamnoise gets recorded even if FOFB is not enabled
1992
1993         while 1
1994             try
1995                 t00 = gettime;
1996
1997                 %          if chicaneloop==20 % reset SR11 motor chicane setpoints every 20s due to drifting positions
1998                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(6),[11 1],0);
1999                 %             setsp('HCMCHICANEM',HCMCHICANEMsp(7),[11 2],0);
2000                 %             chicaneloop = 1;
2001                 %          else
2002                 %             chicaneloop = chicaneloop + 1;
2003                 %          end
2004
2005                 % Check if GUI has been closed
2006                 if isempty(gcbf)
2007                     FEEDBACK_STOP_FLAG = 1;
2008                     lasterr('SRCONTROL GUI DISAPPEARED!');
2009                     error('SRCONTROL GUI DISAPPEARED!');
2010                 end
2011
2012                 %%%%%%%%%%%%%%%%%%%%%%%
2013                 % Fast orbit feedback %
2014                 %%%%%%%%%%%%%%%%%%%%%%%
2015                 if StartFOFBFlag == 1 && FBloopIter > 3
2016                     setpv('SR01____FFBON__BC00',2);
2017                     pause(0.5);
2018                     setpv('SR01____FFBON__BC00',1);
2019                     StartFOFBFlag = 0;
2020                     pause(1);
2021
2022                     FOFBOnStatus = [ ...
2023                         getpv('SR01____FFBON__BM00') getpv('SR02____FFBON__BM00') getpv('SR03____FFBON__BM00')...
2024                         getpv('SR04____FFBON__BM00') getpv('SR05____FFBON__BM00') getpv('SR06____FFBON__BM00')...
2025                         getpv('SR07____FFBON__BM00') getpv('SR08____FFBON__BM00') getpv('SR09____FFBON__BM00')...
2026                         getpv('SR10____FFBON__BM00') getpv('SR11____FFBON__BM00') getpv('SR12____FFBON__BM00')];
2027
2028                     if any(FOFBOnStatus==0) || any(FOFBOnStatus==2)
2029                         setpv('SR01____FFBON__BC00',2); % open FOFB loop
2030                         disp('************************************************************************************************************');
2031                         disp('** Problem turning on Fast Orbit Feedback system...                                                       **');
2032                         disp('** Check status of ffbsecXX crates - but remember that a crate reboot will turn off Quads in that sector! **');
2033                         disp('** Suggest disabling the "Fast Orbit Correction" checkbox and starting Orbit Feedback again.              **');
2034                         disp('************************************************************************************************************');
2035                     else
2036                         fprintf('   Starting Fast Orbit Feedback at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
2037                     end
2038                 end
2039
2040
2041                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2042                 % Horizontal plane "feedback" %
2043                 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2044
2045                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxSOFB'),'Value') == 1
2046
2047                     % Get orbit and check that the BPMs are different from the last update
2048                     Xnew = getx(FB.OCSx.BPM.DeviceList);
2049
2050                     % Don't feedback if the current is too small
2051                     if getdcct < 5
2052                         FEEDBACK_STOP_FLAG = 1;
2053                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2054                         break;
2055                     end
2056
2057                     x = Xgoal - Xnew;
2058                     STDx = norm(x)/sqrt(length(x));
2059
2060                     if any(Xold == Xnew)
2061                         a = clock;
2062                         N_Stale_Data_Points = find((Xold==Xnew)==1);
2063                         for loop = N_Stale_Data_Points'
2064                             fprintf('   Stale data: BPMx(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSx.BPM.DeviceList(loop,1), FB.OCSx.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2065                         end
2066                     else
2067                         % Compute horizontal correction
2068                         %%%OCSx0 = FB.OCSx;
2069                         FB.OCSx.BPM.Data = Xnew;
2070                         FB.OCSx = orbitcorrectionmethods(FB.OCSx, Smatx, Sx, Ux, Vx);
2071
2072                         %%%[FB.OCSx, RF, OCSx0] = setorbit(FB.OCSx,'Nodisplay','Nosetsp');
2073
2074                         % reduced feedback gain (implemented by Greg Portmann, December 2000)
2075                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2076                         % increased back to 0.8 C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2077                         % increased to 1.0, C. Steier, 2002-05-04, trim DACs
2078                         X = Xgain .* FB.OCSx.CM.Delta;
2079                         X(N_HCM+1) = 0.3*FB.OCSx.DeltaRF/4.988e-3;
2080                         %%%X = Xgain .* (FB.OCSx.CM.Data - OCSx0.CM.Data);
2081
2082                         % check for trim values+next step values, warn or stop FB as necessary
2083                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2084                         % need to extract Chicanes from this comparison or maybe check them first for range %
2085                         %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2086                         HCMtrimSP=getpv('HCM','Trim',HCMlist1);
2087                         HCMtrimSP_next = HCMtrimSP + X(1:N_HCM);
2088                         if max(abs(HCMtrimSP_next)) > 4
2089                             HCMtrimnum=find(abs(HCMtrimSP_next) > 4);
2090
2091                             % print message to screen
2092                             fprintf('**One or more of the horizontal correctors is at its maximum!! Stopping orbit feedback. \n');
2093                             fprintf('%s\n',datestr(now));
2094                             for loop = HCMtrimnum'
2095                                 fprintf('**%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2096                             end
2097
2098                             % send alphapage to operator pager
2099                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2100                             FEEDBACK_STOP_FLAG = 1;
2101
2102                             setpv('SR_STATE', -5);
2103                             [StateNumber, StateString] = getsrstate;
2104                             if StateNumber >= 0
2105                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2106                             else
2107                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2108                             end
2109                         end
2110
2111                         if FEEDBACK_STOP_FLAG == 1
2112                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2113                             if getpv('SR01____FFBON__BC00')==1
2114                                 disp('   Stopping Fast Orbit Feedback.');
2115                             end
2116                             setpv('SR01____FFBON__BC00',0);
2117                             pause(0.5);
2118                             setpv('SR01____FFBON__BC00',2);
2119                             break;
2120                         end
2121
2122                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2123                         pause(0);
2124
2125                         if max(abs(HCMtrimSP_next) > 3)
2126                             HCMtrimnum = find(abs(HCMtrimSP_next) > 3);
2127                             HWarnNum = HWarnNum + 1;
2128                             if HWarnNum==1 || rem(HWarnNum,120)==0
2129
2130                                 % print message to screen every two minutes
2131                                 fprintf('**One or more of the horizontal corrector trims is above 3A or below -3A! \n');
2132                                 fprintf('%s\n',datestr(now));
2133                                 for loop = HCMtrimnum'
2134                                     fprintf('**%s is one of the problem correctors.\n',getname('HCM','Trim',HCMlist1(loop,:)));
2135                                 end
2136                                 fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2137
2138                                 %send alphapage to operator pager the first time then at 10 minutes
2139                                 if (HWarnNum==1 || HWarnNum==600)
2140                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageHCM.txt
2141                                 end
2142                             end
2143                         else
2144                             HWarnNum=0;
2145                         end
2146
2147                         % Don't feedback if the current is too small
2148                         if getdcct < 5
2149                             FEEDBACK_STOP_FLAG = 1;
2150                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2151                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2152                             break;
2153                         end
2154
2155                         if N_HCM > 0
2156                             steppv('HCM','Trim', X(iNotHCMChicane), HCMlist1(iNotHCMChicane,:), 0);
2157                             steppv('HCM','Setpoint', X(iHCMChicane), HCMlist1(iHCMChicane,:), 0);
2158                         end
2159
2160                         % write fast orbit feedback setpoints
2161                         if 1
2162                             %write_goldenorbit_ffb_2planes(1, Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM)+Sx3*X(length(X))/20, BPMlist1);
2163                             % should be corrected to include result of next frequency step ...
2164                             write_goldenorbit_ffb_2planes(1,Xnew(1:size(BPMlist1,1))+Sx1*X(1:N_HCM),BPMlist1);
2165                         end
2166
2167                         %fprintf('Horizontal Done: %f \n',gettime-t00);
2168
2169                         % RF feedback
2170                         HQMOFMsp_last = getpv('EG______HQMOFM_AC01');
2171
2172                         if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
2173                             if N_RFMO > 0
2174                                 if abs(X(end)/3) < .01
2175                                 % if abs(FB.OCSx.DeltaRF/3) < .01
2176                                     steppv('EG______HQMOFM_AC01', X(end));
2177                                 else
2178                                     steppv('EG______HQMOFM_AC01', 0.01*sign(X(end)));
2179                                 end
2180                             end
2181
2182                             HQMOFMsp_now = getpv('EG______HQMOFM_AC01');
2183
2184                             % Check for stale RF feedback
2185                             if HQMOFMsp_last == HQMOFMsp_now
2186                                 HQMOFM_stalenum = HQMOFM_stalenum + 1;
2187                                 if HQMOFM_stalenum == 30 % warn and message to pager if stale for 30 secs
2188                                     fprintf('**The RF is not responding to orbit feedback changes! \n');
2189                                     fprintf('%s\n',datestr(now));
2190                                     fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2191                                     fprintf('**ILC 73 controls the EG______HQMOFM_AC01 channel, which sets the RF frequency. \n');
2192                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstaleRFmessage.txt
2193                                 end
2194                                 if rem(HQMOFM_stalenum,120)==0 % message to screen every 2 minutes
2195                                     fprintf('**The RF is not responding to orbit feedback changes! (%s)\n',datestr(now));
2196                                 end
2197                             else
2198                                 HQMOFM_stalenum = 0;
2199                             end
2200
2201                         end
2202
2203                         %fprintf('RF Done: %f \n',gettime-t00);
2204
2205                         Xold = Xnew;
2206                     end % End horizontal correction
2207
2208
2209                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2210                     % Vertical plane "feedback" %
2211                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2212
2213                     % Get orbit and check that the BPMs are different from the last update
2214                     Ynew = gety(FB.OCSy.BPM.DeviceList);
2215
2216                     % Don't feedback if the current is too small
2217                     if getdcct < 5
2218                         FEEDBACK_STOP_FLAG = 1;
2219                         fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2220                         break;
2221                     end
2222
2223                     y = Ygoal - Ynew;
2224                     STDy = norm(y)/sqrt(length(y));
2225
2226                     if any(Yold == Ynew)
2227                         a = clock;
2228                         N_Stale_Data_Points = find((Yold==Ynew)==1);
2229                         for loop = N_Stale_Data_Points'
2230                             fprintf('   Stale data: BPMy(%2d,%d), feedback step skipped (%s %d:%d:%.0f). \n', FB.OCSy.BPM.DeviceList(loop,1), FB.OCSy.BPM.DeviceList(loop,2), date, a(4), a(5), a(6));
2231                         end
2232
2233                     else
2234
2235                         % Compute vertical correction
2236                         %%%OCSy0 = FB.OCSy;
2237                         FB.OCSy.BPM.Data = Ynew;
2238                         FB.OCSy = orbitcorrectionmethods(FB.OCSy, Smaty, Sy, Uy, Vy);
2239
2240                         %%%[FB.OCSy, RF, OCSy0] = setorbit(FB.OCSy,'Nodisplay','Nosetsp');
2241
2242                         % reduced feedback gain, C. Steier, 2001-03-25
2243                         % reduced to 0.1, C. Steier, 2001-09-04, IDBPMs are noisy at the moment
2244                         % increased back to 0.8, C. Steier, 2001-09-29, IDBPMs filtering + direct DAC read/write + all SVDs (no arc BPMs)
2245                         % set to unity gain, C. Steier, 2002-05-04, trim DACs
2246                         Y = Ygain .* FB.OCSy.CM.Delta;
2247                         %%%Y = Ygain .* (FB.OCSy.CM.Data - OCSy0.CM.Data);
2248
2249                         % Just SVD correction
2250                         % warning('Not using "micado" correction in the vertical plane.');
2251
2252                         % check for trim values+next step values, warn or stop FB as necessary
2253                         VCMtrimSP = getpv('VCM','Trim',VCMlist1);
2254                         VCMtrimSP_next = VCMtrimSP + Y(1:N_VCM);
2255                         if max(abs(VCMtrimSP_next)) > 12
2256                             VCMtrimnum=find(abs(VCMtrimSP_next) > 12);
2257
2258                             % print message to screen
2259                             fprintf('**One or more of the vertical correctors is at its maximum!! Stopping orbit feedback. \n');
2260                             fprintf('%s\n',datestr(now));
2261                             for loop = VCMtrimnum'
2262                                 fprintf('**%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2263                             end
2264
2265                             % send alphapage to operator pager
2266                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2267                             FEEDBACK_STOP_FLAG = 1;
2268
2269                             setpv('SR_STATE', -5);
2270                             [StateNumber, StateString] = getsrstate;
2271                             if StateNumber >= 0
2272                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2273                             else
2274                                 set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2275                             end
2276                         end
2277
2278                         if FEEDBACK_STOP_FLAG == 1
2279                             % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2280                             if getpv('SR01____FFBON__BC00')==1
2281                                 disp('   Stopping Fast Orbit Feedback.');
2282                             end
2283                             setpv('SR01____FFBON__BC00',0);
2284                             pause(0.5);
2285                             setpv('SR01____FFBON__BC00',2);
2286                             break;
2287                         end
2288
2289                         %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2290                         % pause(0);
2291
2292                         if max(abs(VCMtrimSP_next) > 4)
2293                             VCMtrimnum=find(abs(VCMtrimSP_next) > 4);
2294                             VWarnNum=VWarnNum+1;
2295                             if (VWarnNum==1 | rem(VWarnNum,120)==0)
2296
2297                                 % print message to screen every two minutes
2298                                 fprintf('**One or more of the vertical corrector trims is above 4A or below -4A! \n');
2299                                 fprintf('%s\n',datestr(now));
2300                                 for loop = VCMtrimnum'
2301                                     fprintf('**%s is one of the problem correctors.\n',getname('VCM','Trim',VCMlist1(loop,:)));
2302                                 end
2303                                 fprintf('**The orbit feedback is still working but this problem should be investigated. \n');
2304
2305                                 %send alphapage to operator pager the first time then at 10 minutes
2306                                 if (VWarnNum==1 | VWarnNum==600)
2307                                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBwarningmessageVCM.txt
2308                                 end
2309                             end
2310                         else
2311                             VWarnNum=0;
2312                         end
2313
2314                         % Don't feedback if the current is too small
2315                         if getdcct < 5
2316                             FEEDBACK_STOP_FLAG = 1;
2317                             fprintf('%s         Orbit feedback stopped due to low beam current (<5mA)\n',datestr(now));
2318                             !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/beamisoff.txt
2319                             break;
2320                         end
2321
2322                         if N_VCM > 0
2323                             steppv('VCM','Trim', Y(iNotVCMChicane), VCMlist1(iNotVCMChicane,:), 0);
2324                             steppv('VCM','Setpoint', Y(iVCMChicane), VCMlist1(iVCMChicane,:), 0);
2325                         end
2326
2327                         % write fast orbit feedback setpoints
2328                         if 1
2329                             write_goldenorbit_ffb_2planes(2,Ynew(1:size(BPMlist1,1))+Sy1*Y(1:N_VCM),BPMlist1);
2330                         end
2331
2332                     end
2333
2334                     Yold = Ynew;
2335
2336                     %fprintf('Vertical Done: %f \n',gettime-t00);
2337                 end % End vertical correction
2338
2339
2340                 %%%%%%%%%%%%%%%%%%%%%
2341                 % Tune feed forward %
2342                 %%%%%%%%%%%%%%%%%%%%%
2343                 % We should do a Sector limit check
2344
2345                 tic;
2346                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxTune'),'Value') == 1
2347
2348                     if strcmp(SR_Mode, '1.9 GeV, High Tune') || strcmp(SR_Mode, '1.9 GeV, Inject at 1.23') || strcmp(SR_Mode, '1.9 GeV, Two-Bunch')
2349
2350                         if strcmp(FFTypeFlag,'Local')
2351                             disp('  No local tune compensation available - global is the default now.');
2352                         elseif strcmp(FFTypeFlag,'Global')
2353
2354                             addQFsp = zeros(24,1);
2355                             addQDsp = zeros(24,1);
2356                             Sector = getlist('ID');
2357                             for gapnum = 1:size(Sector,1)
2358                                 % Change in tune and [QF;QD] from maximum gap
2359                                 actualgap = getid(Sector(gapnum,:));
2360                                 [gapmin,gapmax] = gaplimit(Sector(gapnum,:));
2361                                 if actualgap < (gapmin-1)
2362                                     actualgap = gapmax;
2363                                 end
2364
2365                                 if (Sector(gapnum,1) == 4) | (Sector(gapnum,1) == 11)
2366                                     Shift = getsp('EPU', Sector);
2367                                     if Sector(gapnum,2) == 1
2368                                         modenamestr = sprintf('SR%02dU___ODS1M__DC00',Sector(gapnum,1));
2369                                     else % if Sector(gapnum,2) == 2
2370                                         modenamestr = sprintf('SR%02dU___ODS2M__DC00',Sector(gapnum,1));
2371                                     end
2372                                     epumode = getpv(modenamestr);
2373
2374                                     DelQF = zeros(length(QFsp),1);
2375                                     DelQD = zeros(length(QFsp),1);
2376
2377                                     % This subroutine call replaced by code in this routine for efficiency
2378                                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2379                                     % [DelQF, DelQD] = ...                                                                         %
2380                                     %      ffdeltaquadepu(Sector(gapnum,:), actualgap, getepu(Sector(gapnum,:)), epumode, SR_GeV); %
2381                                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2382                                     if strcmp(SR_Mode, '1.9 GeV, High Tune') ||  strcmp(SR_Mode, '1.9 GeV, Inject at 1.23') || strcmp(SR_Mode, '1.9 GeV, Two-Bunch')
2383
2384                                         if strcmp(FFTypeFlag,'Local')
2385                                             % Change in tune and [QF;QD] from maximum gap
2386                                             DeltaNuY = gap2tune(Sector(gapnum,:), actualgap, SR_GeV);
2387                                             fraccorr = 1.15 * DeltaNuY / TuneW16Min;
2388
2389                                             % Find which quads to change
2390                                             QuadList = [Sector(gapnum,1)-1 1;Sector(gapnum,1)-1 2;Sector(gapnum,1) 1;Sector(gapnum,1) 2];
2391                                             QuadElem = dev2elem('QF', QuadList);
2392
2393                                             if (Sector(gapnum,1)==7) | (Sector(gapnum,1)==10) | (Sector(gapnum,1)==11)
2394                                                 QFfac = ([2.227520/2.237111; 2.239570/2.237111; 2.239570/2.237111; 2.227520/2.237111]-1) * fraccorr;
2395                                                 QDfac = ([2.432264/2.511045; 2.543089/2.511045; 2.543080/2.511045; 2.432264/2.511045]-1) * fraccorr;
2396                                             elseif (Sector(gapnum,1)==5) | (Sector(gapnum,1)==9)
2397                                                 QFfac = ([2.208418/2.219784; 2.225926/2.219784; 2.231777/2.237111; 2.233775/2.237111]-1) * fraccorr;
2398                                                 QDfac = ([2.386512/2.483259; 2.545907/2.483259; 2.474571/2.511045; 2.491079/2.511045]-1) * fraccorr;
2399                                             elseif (Sector(gapnum,1)==4) | (Sector(gapnum,1)==8) | (Sector(gapnum,1)==12)
2400                                                 QFfac = ([2.233775/2.237111; 2.231777/2.237111; 2.225926/2.219784; 2.208418/2.219784]-1) * fraccorr;
2401                                                 QDfac = ([2.491079/2.511045; 2.474571/2.511045; 2.545907/2.483259; 2.386512/2.483259]-1) * fraccorr;
2402                                             else
2403                                                 QFfac = zeros(4,size(actualgap,2));
2404                                                 QDfac = zeros(4,size(actualgap,2));
2405                                             end
2406
2407                                             DelQF(QuadElem,:) = DelQF(QuadElem,:) + QFfac.*QFsp(QuadElem,:);
2408                                             DelQD(QuadElem,:) = DelQD(QuadElem,:) + QDfac.*QDsp(QuadElem,:);
2409
2410                                         elseif strcmp(FFTypeFlag,'Global')
2411                                             % Change in tune and [QF;QD] from maximum gap
2412
2413                                             DeltaNuX = 0;
2414                                             DeltaNuY = gap2tune(Sector(gapnum,:), actualgap, SR_GeV);
2415
2416                                             if (Sector(gapnum,1) == 4) | (Sector(gapnum,1) == 11)
2417                                                 if Sector(i,2)==2
2418                                                     longshift=3;
2419                                                 else
2420                                                     longshift=0;
2421                                                 end
2422                                                 if mode(i)==0
2423                                                     DeltaNuX = shift2tune(Sector(gapnum,1),actualgap,Shift(gapnum,:)+longshift,SR_GeV)+0.0015;
2424                                                     DeltaNuY = 0;   % vertical tune shift of EPUs is very small
2425                                                 else
2426                                                     DeltaNuX = 0;
2427                                                     DeltaNuY = 0;
2428                                                 end
2429                                             else
2430                                                 DeltaNuX = 0;
2431                                             end
2432
2433
2434                                             fraccorr = DeltaNuY ./ TuneW16Min;
2435
2436                                             % Find which quads to change
2437                                             QuadList = [Sector(gapnum,1)-1 2; Sector(gapnum,1) 1];
2438                                             QuadElem = dev2elem('QF',QuadList);
2439
2440                                             DeltaAmps = inv(SR_TUNE_MATRIX) * [(fraccorr*6.23e-4); fraccorr*(-0.05301)];    %  DelAmps =  [QF; QD];
2441
2442                                             DelQF = DelQF + DeltaAmps(1,:);
2443                                             DelQD = DelQD + DeltaAmps(2,:);
2444
2445                                             DeltaAmpsLocal = 12*inv(SR_TUNE_MATRIX) * [-0.8*DeltaNuX;0];                       %  DelAmps =  [QF; QD];
2446                                             DelQF(QuadElem) = DelQF(QuadElem)+DeltaAmpsLocal(1,1);
2447                                             DelQD(QuadElem) = DelQD(QuadElem)+DeltaAmpsLocal(2,1);
2448
2449                                             if (Sector(gapnum,1)==6) | (Sector(gapnum,1)==7) | (Sector(gapnum,1)==10) | (Sector(gapnum,1)==11)
2450                                                 QFfac = ([2.243127/2.237111; 2.243127/2.237111]-1) * fraccorr;
2451                                                 QDfac = ([2.556392/2.511045; 2.556392/2.511045]-1) * fraccorr;
2452                                             elseif (Sector(gapnum,1)==5) | (Sector(gapnum,1)==9)
2453                                                 QFfac = ([2.225965/2.219784; 2.243096/2.237111]-1) * fraccorr;
2454                                                 QDfac = ([2.528950/2.483259; 2.556345/2.511045]-1) * fraccorr;
2455                                             elseif (Sector(gapnum,1)==4) | (Sector(gapnum,1)==8) | (Sector(gapnum,1)==12)
2456                                                 QFfac = ([2.243096/2.237111; 2.225965/2.219784]-1) * fraccorr;
2457                                                 QDfac = ([2.556345/2.511045; 2.528950/2.483259]-1) * fraccorr;
2458                                             else
2459                                                 QFfac = zeros(2,size(actualgap,2));
2460                                                 QDfac = zeros(2,size(actualgap,2));
2461                                             end
2462
2463                                             DelQF(QuadElem,:) = DelQF(QuadElem,:) + QFfac.*QFsp(QuadElem,:);
2464                                             DelQD(QuadElem,:) = DelQD(QuadElem,:) + QDfac.*QDsp(QuadElem,:);
2465
2466                                         else
2467                                             error('Unknown type selected for tune FF');
2468                                         end
2469
2470                                     else
2471
2472                                         % Change in tune and [QF;QD] from maximum gap
2473                                         DeltaNuY = gap2tune(Sector(gapnum,:), actualgap, SR_GeV);
2474
2475                                         if (Sector(gapnum,1)==7) | (Sector(gapnum,1)==10) | (Sector(gapnum,1)==11)
2476                                             DeltaAmps = inv(SR_TUNE_MATRIX/12) * [zeros(size(DeltaNuY)); -DeltaNuY];    %  DelAmps =  [QF; QD];
2477                                             DeltaAmpsQF = [DeltaAmps(1,:); DeltaAmps(1,:)];
2478                                             DeltaAmpsQD = [DeltaAmps(2,:); DeltaAmps(2,:)];
2479                                         elseif (Sector(gapnum,1)==5) | (Sector(gapnum,1)==9)
2480                                             DeltaAmpsQF = [-1.0637; -0.5132] * DeltaNuY / 0.0181 * 0.37;
2481                                             DeltaAmpsQD = [-6.6328; -3.3434] * DeltaNuY / 0.0181 * 0.37;
2482                                         elseif (Sector(gapnum,1)==4) | (Sector(gapnum,1)==8) | (Sector(gapnum,1)==12)
2483                                             DeltaAmpsQF = [-0.5132; -1.0637] * DeltaNuY / 0.0181 * 0.37;
2484                                             DeltaAmpsQD = [-3.3434; -6.6328] * DeltaNuY / 0.0181 * 0.37;
2485                                         else
2486                                             DeltaAmpsQF = zeros(2,size(actualgap,2));
2487                                             DeltaAmpsQD = zeros(2,size(actualgap,2));
2488                                         end
2489
2490                                         % Find which quads to change
2491                                         QuadList = [Sector(gapnum,1)-1 1;Sector(gapnum,1) 2];
2492                                         QuadElem = dev2elem('QF', QuadList);
2493
2494                                         DelQF(QuadElem,:) = DelQF(QuadElem,:) + DeltaAmpsQF;
2495                                         DelQD(QuadElem,:) = DelQD(QuadElem,:) + DeltaAmpsQD;
2496                                     end
2497                                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2498                                     % ffdeltaquadepu code ends here %
2499                                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2500
2501                                 else
2502                                     % This subroutine call replaced by code in this routine for efficiency
2503                                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2504                                     %[DelQF, DelQD] = ...                                  %
2505                                     %    ffdeltaquad(Sector(gapnum,:), actualgap, SR_GeV); %
2506                                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2507
2508                                     % Initialize
2509                                     DelQF  = zeros(length(QFsp), 1);
2510                                     DelQD  = zeros(length(QDsp), 1);
2511
2512                                     if strcmp(SR_Mode, '1.9 GeV, High Tune') ||  strcmp(SR_Mode, '1.9 GeV, Inject at 1.23') || strcmp(SR_Mode, '1.9 GeV, Two-Bunch')
2513
2514                                         if strcmp(FFTypeFlag,'Local')
2515                                             % Change in tune and [QF;QD] from maximum gap
2516                                             DeltaNuY = gap2tune(Sector(gapnum,:), actualgap, SR_GeV);
2517                                             fraccorr = 1.15 * DeltaNuY / TuneW16Min;
2518
2519                                             % Find which quads to change
2520                                             QuadList = [Sector(gapnum,1)-1 1;Sector(gapnum,1)-1 2;Sector(gapnum,1) 1;Sector(gapnum,1) 2];
2521                                             QuadElem = dev2elem('QF', QuadList);
2522
2523                                             if (Sector(gapnum,1)==7) | (Sector(gapnum,1)==10) | (Sector(gapnum,1)==11)
2524                                                 QFfac = ([2.227520/2.237111; 2.239570/2.237111; 2.239570/2.237111; 2.227520/2.237111]-1) * fraccorr;
2525                                                 QDfac = ([2.432264/2.511045; 2.543089/2.511045; 2.543080/2.511045; 2.432264/2.511045]-1) * fraccorr;
2526                                             elseif (Sector(gapnum,1)==5) | (Sector(gapnum,1)==9)
2527                                                 QFfac = ([2.208418/2.219784; 2.225926/2.219784; 2.231777/2.237111; 2.233775/2.237111]-1) * fraccorr;
2528                                                 QDfac = ([2.386512/2.483259; 2.545907/2.483259; 2.474571/2.511045; 2.491079/2.511045]-1) * fraccorr;
2529                                             elseif (Sector(gapnum,1)==4) | (Sector(gapnum,1)==8) | (Sector(gapnum,1)==12)
2530                                                 QFfac = ([2.233775/2.237111; 2.231777/2.237111; 2.225926/2.219784; 2.208418/2.219784]-1) * fraccorr;
2531                                                 QDfac = ([2.491079/2.511045; 2.474571/2.511045; 2.545907/2.483259; 2.386512/2.483259]-1) * fraccorr;
2532                                             else
2533                                                 QFfac = zeros(4,size(actualgap,2));
2534                                                 QDfac = zeros(4,size(actualgap,2));
2535                                             end
2536
2537                                             DelQF(QuadElem,:) = DelQF(QuadElem,:) + QFfac.*QFsp(QuadElem,:);
2538                                             DelQD(QuadElem,:) = DelQD(QuadElem,:) + QDfac.*QDsp(QuadElem,:);
2539
2540                                         elseif strcmp(FFTypeFlag,'Global')
2541                                             % Change in tune and [QF;QD] from maximum gap
2542
2543                                             DeltaNuX = 0;
2544                                             DeltaNuY = gap2tune(Sector(gapnum,:), actualgap, SR_GeV);
2545
2546                                             if (Sector(gapnum,1) == 4) | (Sector(gapnum,1) == 11)
2547                                                 % Remove sector 4 and 11 tune correction
2548                                                 DeltaNuY = 0;
2549                                             end
2550
2551                                             fraccorr = DeltaNuY ./ TuneW16Min;
2552
2553                                             % Find which quads to change
2554                                             QuadList = [Sector(gapnum,1)-1 2; Sector(gapnum,1) 1];
2555                                             QuadElem = dev2elem('QF',QuadList);
2556
2557                                             DeltaAmps = inv(SR_TUNE_MATRIX) * [(fraccorr*6.23e-4)-DeltaNuX; fraccorr*(-0.05301)];    %  DelAmps =  [QF; QD];
2558
2559                                             DelQF = DelQF + DeltaAmps(1,:);
2560                                             DelQD = DelQD + DeltaAmps(2,:);
2561
2562                                             DeltaAmpsLocal = 12*inv(SR_TUNE_MATRIX) * [-DeltaNuX;0];                       %  DelAmps =  [QF; QD];
2563                                             DelQF(QuadElem) = DelQF(QuadElem)+DeltaAmpsLocal(1,1);
2564                                             DelQD(QuadElem) = DelQD(QuadElem)+DeltaAmpsLocal(2,1);
2565
2566                                             if (Sector(gapnum,1)==6) | (Sector(gapnum,1)==7) | (Sector(gapnum,1)==10) | (Sector(gapnum,1)==11)
2567                                                 QFfac = ([2.243127/2.237111; 2.243127/2.237111]-1) * fraccorr;
2568                                                 QDfac = ([2.556392/2.511045; 2.556392/2.511045]-1) * fraccorr;
2569                                             elseif (Sector(gapnum,1)==5) | (Sector(gapnum,1)==9)
2570                                                 QFfac = ([2.225965/2.219784; 2.243096/2.237111]-1) * fraccorr;
2571                                                 QDfac = ([2.528950/2.483259; 2.556345/2.511045]-1) * fraccorr;
2572                                             elseif (Sector(gapnum,1)==4) | (Sector(gapnum,1)==8) | (Sector(gapnum,1)==12)
2573                                                 QFfac = ([2.243096/2.237111; 2.225965/2.219784]-1) * fraccorr;
2574                                                 QDfac = ([2.556345/2.511045; 2.528950/2.483259]-1) * fraccorr;
2575                                             else
2576                                                 QFfac = zeros(2,size(actualgap,2));
2577                                                 QDfac = zeros(2,size(actualgap,2));
2578                                             end
2579
2580                                             DelQF(QuadElem,:) = DelQF(QuadElem,:) + QFfac.*QFsp(QuadElem,:);
2581                                             DelQD(QuadElem,:) = DelQD(QuadElem,:) + QDfac.*QDsp(QuadElem,:);
2582
2583                                         else
2584                                             error('Unknown type selected for tune FF');
2585                                         end
2586
2587                                     else
2588
2589                                         % Change in tune and [QF;QD] from maximum gap
2590                                         DeltaNuY = gap2tune(Sector(gapnum,:), actualgap, SR_GeV);
2591
2592                                         if (Sector(gapnum,1)==7) | (Sector(gapnum,1)==10) | (Sector(gapnum,1)==11)
2593                                             DeltaAmps = inv(SR_TUNE_MATRIX/12) * [zeros(size(DeltaNuY)); -DeltaNuY];    %  DelAmps =  [QF; QD];
2594                                             DeltaAmpsQF = [DeltaAmps(1,:); DeltaAmps(1,:)];
2595                                             DeltaAmpsQD = [DeltaAmps(2,:); DeltaAmps(2,:)];
2596                                         elseif (Sector(gapnum,1)==5) | (Sector(gapnum,1)==9)
2597                                             DeltaAmpsQF = [-1.0637; -0.5132] * DeltaNuY / 0.0181 * 0.37;
2598                                             DeltaAmpsQD = [-6.6328; -3.3434] * DeltaNuY / 0.0181 * 0.37;
2599                                         elseif (Sector(gapnum,1)==4) | (Sector(gapnum,1)==8) | (Sector(gapnum,1)==12)
2600                                             DeltaAmpsQF = [-0.5132; -1.0637] * DeltaNuY / 0.0181 * 0.37;
2601                                             DeltaAmpsQD = [-3.3434; -6.6328] * DeltaNuY / 0.0181 * 0.37;
2602                                         else
2603                                             DeltaAmpsQF = zeros(2,size(actualgap,2));
2604                                             DeltaAmpsQD = zeros(2,size(actualgap,2));
2605                                         end
2606
2607                                         % Find which quads to change
2608                                         QuadList = [Sector(gapnum,1)-1 1;Sector(gapnum,1) 2];
2609                                         QuadElem = dev2elem('QF', QuadList);
2610
2611                                         DelQF(QuadElem,:) = DelQF(QuadElem,:) + DeltaAmpsQF;
2612                                         DelQD(QuadElem,:) = DelQD(QuadElem,:) + DeltaAmpsQD;
2613                                     end
2614                                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2615                                     % ffdeltaquad code ends here %
2616                                     %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2617                                 end
2618
2619                                 addQFsp = addQFsp+DelQF;
2620                                 addQDsp = addQDsp+DelQD;
2621                             end
2622                         else
2623                             error('Unknown type selected for tune FF');
2624                         end
2625
2626                         % Set quadrupoles using main setpoint channels
2627                         setpv('QF', QFsp+addQFsp,[], 0);
2628                         setpv('QD', QDsp+addQDsp,[], 0);
2629
2630                         % % Set quadrupoles using FF setpoint channels
2631                         % setpv('QF', 'FF', addQFsp, [], 0);
2632                         % setpv('QD', 'FF', addQDsp, [], 0);
2633
2634                     else
2635                         disp('  No tune FF algorithm for non-production modes yet...');
2636                     end
2637                 end
2638
2639                 ffdeltaquad_delay = toc;
2640                 fprintf('tune FF delay = %.1f seconds\n',ffdeltaquad_delay);
2641                 % fprintf('Tune Done: %f \n',gettime-t00);
2642
2643                 % Output info to screen
2644                 set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = %.4f mm',STDx),'ForegroundColor',[0 0 0]);
2645                 set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = %.4f mm',STDy),'ForegroundColor',[0 0 0]);
2646                 pause(0);
2647
2648
2649                 fprintf('End of feedback operations: %f \n\n',gettime-t00);
2650
2651                 % Wait for next update time or stop request
2652                 while (gettime-t00) < LoopDelay
2653                     %disp('interval could be shorter')
2654                     pause(.05);
2655                     % Check if GUI has been closed
2656                     if isempty(gcbf)
2657                         FEEDBACK_STOP_FLAG = 1;
2658                         lasterr('SRCONTROL GUI DISAPPEARED!');
2659                         error('SRCONTROL GUI DISAPPEARED!');
2660                     end
2661
2662                     % Check if Stop button was pressed
2663                     if FEEDBACK_STOP_FLAG == 1
2664                         % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2665                         if getpv('SR01____FFBON__BC00')==1
2666                             disp('   Stopping Fast Orbit Feedback.');
2667                         end
2668                         setpv('SR01____FFBON__BC00',0);
2669                         pause(0.5);
2670                         setpv('SR01____FFBON__BC00',2);
2671                         break;
2672                     end
2673                 end
2674
2675
2676                 if FEEDBACK_STOP_FLAG == 1
2677                     % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2678                     if getpv('SR01____FFBON__BC00')==1
2679                         disp('   Stopping Fast Orbit Feedback.');
2680                     end
2681                     setpv('SR01____FFBON__BC00',0);
2682                     pause(0.5);
2683                     setpv('SR01____FFBON__BC00',2);
2684                     break;
2685                 end
2686
2687                 StartErrorTime = gettime;
2688
2689             catch
2690
2691                 fprintf('\n  %s \n',lasterr);
2692
2693                 % Quit if error exists for more than 20 seconds
2694                 if gettime-StartErrorTime>20 | FEEDBACK_STOP_FLAG==1
2695                     fprintf('%s  Orbit feedback stopped due to error condition. \n\n',datestr(now));
2696
2697                     %send alphapage to operator pager
2698                     !/usr/ucb/Mail 5108120447@mmode.com < /home/als/physbase/machine/ALS/StorageRing/SOFBstoppedmessage.txt
2699                     FEEDBACK_STOP_FLAG = 1;
2700
2701                     setpv('SR_STATE', -5);
2702                     [StateNumber, StateString] = getsrstate;
2703                     if StateNumber >= 0
2704                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2705                     else
2706                         set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2707                     end
2708                 else
2709                     a = clock;
2710                     fprintf('   Orbit feedback was paused due to error condition (%s %d:%d:%.0f). \n', date, a(4), a(5), a(6));
2711                     fprintf('   Orbit feedback has automatically restarted and is running. \n\n');
2712                 end
2713
2714             end
2715
2716             if FEEDBACK_STOP_FLAG == 1
2717                 % turn off then open FOFB loop (turn off to transfer correctors, then open to enable logging
2718                 if getpv('SR01____FFBON__BC00')==1
2719                     disp('   Stopping Fast Orbit Feedback.');
2720                 end
2721                 setpv('SR01____FFBON__BC00',0);
2722                 pause(0.5);
2723                 setpv('SR01____FFBON__BC00',2);
2724                 break;
2725             end
2726
2727             %fprintf('End of feedback loop: %f \n\n',gettime-t00);
2728
2729             %pause(0);
2730
2731             % this loop delays turn on of Fast Feedback system
2732             if FBloopIter < 5
2733                 FBloopIter = FBloopIter + 1;
2734             end
2735
2736         end  % End of feedback loop
2737
2738
2739         % End feedback, reset all parameters
2740         try
2741
2742             % Enable buttons
2743             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStart'),'Enable','on');
2744             set(findobj(gcbf,'Tag','SRCTRLPushbuttonStop'),'Enable','off');
2745             set(findobj(gcbf,'Tag','SRCTRLButton1'),'Enable','on');
2746             set(findobj(gcbf,'Tag','SRCTRLButton2'),'Enable','on');
2747             set(findobj(gcbf,'Tag','SRCTRLButton3'),'Enable','on');
2748             set(findobj(gcbf,'Tag','SRCTRLButtonChangeMode'),'Enable','on');
2749             set(findobj(gcbf,'Tag','SRCTRLButtonSRState'),'Enable','on');
2750             set(findobj(gcbf,'Tag','SRCTRLButtonGoldenPage'),'Enable','on');
2751             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrection'),'Enable','on');
2752             set(findobj(gcbf,'Tag','SRCTRLButtonOrbitCorrectionSetup'),'Enable','on');
2753             set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Enable','on');
2754             set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Enable','on');
2755             set(findobj(gcbf,'Tag','SRCTRLClose'),'Enable','on');
2756
2757             set(findobj(gcbf,'Tag','SRCTRLStaticTextHorizontal'),'String',sprintf('Horizontal RMS = _____ mm'),'ForegroundColor',[0 0 0]);
2758             set(findobj(gcbf,'Tag','SRCTRLStaticTextVertical'),'String',sprintf('Vertical RMS = _____ mm'),'ForegroundColor',[0 0 0]);
2759             pause(0);
2760
2761         catch
2762
2763             % GUI must have been closed
2764
2765         end
2766
2767
2768         % >= 2 Hz update rate on IDBPMs
2769         disp('   IDBPM time constant set to 0.25s.');
2770         setbpmtimeconstant(0.25);
2771
2772
2773         a = clock;
2774         fprintf('   %s %d:%d:%.0f\n', date, a(4), a(5), a(6));
2775         [StateNumber, StateString] = getsrstate;
2776         if StateNumber >= 0
2777             setpv('SR_STATE',5.1);
2778             [StateNumber, StateString] = getsrstate;
2779             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','b');
2780             fprintf('   ******************************\n');
2781             fprintf('   **  Orbit Feedback Stopped  **\n');
2782             fprintf('   ******************************\n\n');
2783         else
2784             [StateNumber, StateString] = getsrstate;
2785             set(findobj(gcbf,'Tag','SRCTRLStaticTextInformation'),'String',StateString,'ForegroundColor','r');
2786             fprintf('   ****************************************\n');
2787             fprintf('   **  Problem With Slow Orbit Feedback  **\n');
2788             fprintf('   ****************************************\n\n');
2789         end
2790         set(0,'showhiddenhandles','off');
2791         pause(0);
2792
2793
2794     case 'FeedbackSetup'
2795         InitFlag = Input2;           % Input #2: if InitFlag, then initialize variables
2796
2797         if InitFlag
2798             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2799             % Edit the following lists to change default configuration of Orbit Correction %
2800             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
2801
2802             % Corrector magnets
2803             listh=[
2804                 1 2;
2805                 1 8;
2806                 2 1;
2807                 2 8;
2808                 3 1;
2809                 3 8;
2810                 3 10; %SR04U_HCM2 (chicane trim)
2811                 4 1;
2812                 4 8;
2813                 5 1;
2814                 5 8;
2815                 5 10; %SR06U_HCM2 (chicane trim)
2816                 6 1;
2817                 6 8;
2818                 7 1;
2819                 7 8;
2820                 8 1;
2821                 8 8;
2822                 9 1;
2823                 9 8;
2824                 10 1;
2825                 10 8;
2826                 10 10; %SR11U_HCM2 (chicane trim)
2827                 11 1;
2828                 11 8;
2829                 12 1;
2830                 12 7];
2831             listv=[
2832                 1 2;
2833                 1 8;
2834                 2 1;
2835                 2 8;
2836                 3 1;
2837                 3 7;
2838                 3 8;
2839                 3 10; %SR04U_VHCM2 (chicane trim)
2840                 4 1;
2841                 4 7;
2842                 4 8;
2843                 5 1;
2844                 5 8;
2845                 5 10; %SR06U_VHCM2 (chicane trim)
2846                 6 1;
2847                 6 8;
2848                 7 1;
2849                 7 8;
2850                 8 1;
2851                 8 8;
2852                 9 1;
2853                 9 8;
2854                 10 1;
2855                 10 2;
2856                 10 7;
2857                 10 8;
2858                 10 10; %SR11U_VHCM2 (chicane trim)
2859                 11 1;
2860                 11 7;
2861                 11 8;
2862                 12 1;
2863                 12 7];
2864
2865             Xivec = [1:28];
2866             Yivec = [1:32];
2867             HCMlist1 = listh;
2868             VCMlist1 = listv;
2869
2870             % Full BPM list
2871             BPMlist1 = [
2872                 1 2
2873                 1 5
2874                 1 6
2875                 1 10
2876                 2 1
2877                 2 5
2878                 2 6
2879                 2 9
2880                 3 2
2881                 3 5
2882                 3 6
2883                 3 10
2884                 3 11
2885                 3 12
2886                 4 1
2887                 4 5
2888                 4 6
2889                 4 10
2890                 5 1
2891                 5 5
2892                 5 6
2893                 5 10
2894                 5 11
2895                 5 12
2896                 6 1
2897                 6 5
2898                 6 6
2899                 6 10
2900                 7 1
2901                 7 5
2902                 7 6
2903                 7 10
2904                 8 1
2905                 8 5
2906                 8 6
2907                 8 10
2908                 9 1
2909                 9 5
2910                 9 6
2911                 9 10
2912                 10 1
2913                 10 5
2914                 10 6
2915                 10 10
2916                 10 11
2917                 10 12
2918                 11 1
2919                 11 5
2920                 11 6
2921                 11 10
2922                 12 1
2923                 12 5
2924                 12 6
2925                 12 9
2926                 ];
2927
2928             % remove Bergoz BPMs in SR01 and SR03 for 2-bunch (noisy at low currents) and drop singular values
2929             if strcmp(getfamilydata('OperationalMode'), '1.9 GeV, Two-Bunch')
2930                     BPMlist1 = [
2931                          %1 2
2932                          1 5
2933                          1 6
2934                          1 10
2935                          2 1
2936                          2 5
2937                          2 6
2938                          %2 9
2939                          %3 2
2940                          3 5
2941                          3 6
2942                          3 10
2943                          3 11
2944                          3 12
2945                          4 1
2946                          4 5
2947                          4 6
2948                          4 10
2949                          5 1
2950                          5 5
2951                          5 6
2952                          5 10
2953                          5 11
2954                          5 12
2955                          6 1
2956                          6 5
2957                          6 6
2958                          6 10
2959                          7 1
2960                          7 5
2961                          7 6
2962                          7 10
2963                          8 1
2964                          8 5
2965                          8 6
2966                          8 10
2967                          9 1
2968                          9 5
2969                          9 6
2970                          9 10
2971                          10 1
2972                          10 5
2973                          10 6
2974                          10 10
2975                          10 11
2976                          10 12
2977                          11 1
2978                          11 5
2979                          11 6
2980                          11 10
2981                          12 1
2982                          12 5
2983                          12 6
2984                          %12 9
2985                          ];
2986             end
2987
2988             OCSx.BPM = getx(BPMlist1, 'struct');
2989             OCSx.CM = getsp('HCM', HCMlist1, 'struct');
2990             OCSx.GoalOrbit = getgolden(OCSx.BPM, 'numeric');
2991             OCSx.NIter = 1;
2992             OCSx.SVDIndex = Xivec;
2993             OCSx.IncrementalFlag = 'No';
2994             OCSx.BPMWeight = {[]};
2995             OCSx.FitRF = 0;
2996             OCSy.BPM = gety(BPMlist1, 'struct');
2997             OCSy.CM = getsp('VCM', VCMlist1, 'struct');
2998             OCSy.GoalOrbit = getgolden(OCSy.BPM, 'numeric');
2999             OCSy.NIter = 1;
3000             OCSy.SVDIndex = Yivec;
3001             OCSy.IncrementalFlag = 'No';
3002             OCSy.BPMWeight = {[]};
3003             OCSy.FitRF = 0;
3004             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
3005             % do we need these Smat calls? %
3006             %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
3007             SXmat = getrespmat(OCSx.BPM, OCSx.CM, 'numeric');
3008             SYmat = getrespmat(OCSy.BPM, OCSy.CM, 'numeric');
3009             % [OCSx, Sx, Ux, Vx] = orbitcorrectionmethods(OCSx, SXmat);
3010             % [OCSy, Sy, Uy, Vy] = orbitcorrectionmethods(OCSy, SYmat);
3011
3012             % initialize FFTypeFlag
3013             FFTypeFlag = 'Global';
3014
3015         else
3016
3017             % Get vectors
3018             FB = get(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata');
3019             % the two lines below seem to fix BPMlist editing problem
3020             OCSx = FB.OCSx;
3021             OCSy = FB.OCSy;
3022             BPMlist1 = FB.BPMlist1;
3023             HCMlist1 = FB.HCMlist1;
3024             VCMlist1 = FB.VCMlist1;
3025             Xivec = FB.Xivec;
3026             Yivec = FB.Yivec;
3027             Xgoal = FB.OCSx.GoalOrbit;
3028             OCSx.GoalOrbit = Xgoal;
3029             Ygoal = FB.OCSy.GoalOrbit;
3030             OCSy.GoalOrbit = Ygoal;
3031             FFTypeFlag = FB.FFTypeFlag;
3032
3033
3034             % FF corrector magnet list
3035             ListFF = [
3036                 4     2
3037                 4     8
3038                 5     1
3039                 5     7
3040 %               5     8 % why are these out???
3041 %               6     1 % why are these out???
3042                 6     8
3043                 7     1
3044                 7     8
3045                 8     1
3046                 8     8
3047                 9     1
3048                 9     8
3049                 10    1
3050                 11    8
3051                 12    1];
3052             ElemFF = dev2elem('HCM',ListFF);
3053
3054
3055             % Add button to change #ivectors, cm, IDBPMs,
3056             EditFlag = 0;
3057             h_fig1 = figure;
3058             while EditFlag ~= 7
3059
3060                 Sx = getrespmat('BPMx', BPMlist1, 'HCM', HCMlist1, [], SR_GEV);
3061                 Sy = getrespmat('BPMy', BPMlist1, 'VCM', VCMlist1, [], SR_GEV);
3062
3063                 if get(findobj(gcbf,'Tag','SRCTRLCheckboxRF'),'Value') == 1
3064                     DispOrbit = getdisp('BPMx', BPMlist1);
3065                     Sx = [Sx DispOrbit];
3066                 end
3067
3068                 [Ux, SVx, Vx] = svd(Sx);
3069                 [Uy, SVy, Vy] = svd(Sy);
3070
3071
3072                 % Remove singular values greater than the actual number of singular values
3073                 i = find(Xivec>length(diag(SVx)));
3074                 if ~isempty(i)
3075                     disp('   Horizontal E-vector scaled since there were more elements in the vector than singular values.');
3076                     pause(0);
3077                     Xivec(i) = [];
3078                 end
3079                 i = find(Yivec>length(diag(SVy)));
3080                 if ~isempty(i)
3081                     disp('   Vertical E-vector scaled since there were more elements in the vector than singular values.');
3082                     pause(0);
3083                     Yivec(i) = [];
3084                 end
3085
3086
3087                 Ax = Sx*Vx(:,Xivec);
3088                 Tx = inv(Ax'*Ax)*Ax';
3089
3090                 Ay = Sy*Vy(:,Yivec);
3091                 Ty = inv(Ay'*Ay)*Ay';
3092
3093                 figure(h_fig1);
3094                 subplot(2,1,1);
3095                 semilogy(diag(SVx),'b');
3096                 hold on;
3097                 semilogy(diag(SVx(Xivec,Xivec)),'xr');
3098                 ylabel('Horizontal');
3099                 title('Response Matrix Singular Values');
3100                 hold off;
3101                 subplot(2,1,2);
3102                 semilogy(diag(SVy),'b');
3103                 hold on;
3104                 semilogy(diag(SVy(Yivec,Yivec)),'xr');
3105                 xlabel('Singular Value Number');
3106                 ylabel('Vertical');
3107                 hold off;
3108                 drawnow;
3109
3110                 EditFlag = menu('Change Parameters?','Singular Values','HCM List','VCM List', ...
3111                     'BPM List','Change the Goal Orbit', ...
3112                     'Change Tune FF Method (nuy=9.2 only)','Continue');
3113
3114                 if EditFlag == 1
3115                     prompt={'Enter the horizontal E-vector numbers (Matlab vector format):','Enter the vertical E-vector numbers (Matlab vector format):'};
3116                     def={sprintf('[%d:%d]',1,Xivec(end)),sprintf('[%d:%d]',1,Yivec(end))};
3117                     titlestr='SVD Orbit Feedback';
3118                     lineNo=1;
3119                     answer=inputdlg(prompt,titlestr,lineNo,def);
3120                     if ~isempty(answer)
3121                         XivecNew = fix(str2num(answer{1}));
3122                         if isempty(XivecNew)
3123                             disp('   Horizontal E-vector cannot be empty.  No change made.');
3124                         else
3125                             if any(XivecNew<=0) | max(XivecNew)>length(diag(SVx))
3126                                 disp('   Error reading horizontal E-vector.  No change made.');
3127                             else
3128                                 Xivec = XivecNew;
3129                             end
3130                         end
3131                         YivecNew = fix(str2num(answer{2}));
3132                         if isempty(YivecNew)
3133                             disp('   Vertical E-vector cannot be empty.  No change made.');
3134                         else
3135                             if any(YivecNew<=0) | max(YivecNew)>length(diag(SVy))
3136                                 disp('   Error reading vertical E-vector.  No change made.');
3137                             else
3138                                 Yivec = YivecNew;
3139                             end
3140                         end
3141                     end
3142                 end
3143
3144                 if EditFlag == 2
3145                     List= getlist('HCM','Trim');
3146                     CheckList = zeros(96,1);
3147                     Elem = dev2elem('HCM', HCMlist1);
3148                     CheckList(Elem) = ones(size(Elem));
3149                     CheckList = CheckList(dev2elem('HCM',List));
3150
3151                     % Remove FF corrrectors
3152                     %           Elem = dev2elem('HCM',List);
3153                     %           for j = length(ElemFF):-1:1
3154                     %              i = find(Elem==ElemFF(j));
3155                     %              Elem(i,:) = [];
3156                     %              List(i,:) = [];
3157                     %              CheckList(i,:) = [];
3158                     %           end
3159
3160                     newList = editlist(List, 'HCMtrim', CheckList);
3161
3162                     if isempty(newList)
3163                         fprintf('   WARNING: Horizontal corrector magnet list is empty!\n');
3164                         HCMlist1 = newList;
3165                     else
3166                         HCMlist1 = newList;
3167                     end
3168                 end
3169
3170                 if EditFlag == 3
3171                     List = getlist('VCM','Trim');
3172                     CheckList = zeros(96,1);
3173                     Elem = dev2elem('VCM', VCMlist1);
3174                     CheckList(Elem) = ones(size(Elem));
3175                     CheckList = CheckList(dev2elem('VCM',List));
3176
3177                     % Remove FF corrrectors
3178                     %           Elem = dev2elem('VCM',List);
3179                     %           for j = length(ElemFF):-1:1
3180                     %              i = find(Elem==ElemFF(j));
3181                     %              Elem(i,:) = [];
3182                     %              List(i,:) = [];
3183                     %              CheckList(i,:) = [];
3184                     %           end
3185
3186                     newList = editlist(List, 'VCMtrim', CheckList);
3187
3188                     if isempty(newList)
3189                         fprintf('   WARNING: Vertical corrector magnet list is empty!\n');
3190                         VCMlist1 = newList;
3191                     else
3192                         VCMlist1 = newList;
3193                     end
3194                 end
3195
3196                 if EditFlag == 4
3197                     ListOld = BPMlist1;
3198                     XgoalOld = Xgoal;
3199                     YgoalOld = Ygoal;
3200
3201                     % Full BPM list
3202                     List = [
3203                         1 2
3204                         1 5
3205                         1 6
3206                         1 10
3207                         2 1
3208                         2 5
3209                         2 6
3210                         2 9
3211                         3 2
3212                         3 5
3213                         3 6
3214                         3 10
3215                         3 11
3216                         3 12
3217                         4 1
3218                         4 5
3219                         4 6
3220                         4 10
3221                         5 1
3222                         5 5
3223                         5 6
3224                         5 10
3225                         5 11
3226                         5 12
3227                         6 1
3228                         6 5
3229                         6 6
3230                         6 10
3231                         7 1
3232                         7 5
3233                         7 6
3234                         7 10
3235                         8 1
3236                         8 5
3237                         8 6
3238                         8 10
3239                         9 1
3240                         9 5
3241                         9 6
3242                         9 10
3243                         10 1
3244                         10 5
3245                         10 6
3246                         10 10
3247                         10 11
3248                         10 12
3249                         11 1
3250                         11 5
3251                         11 6
3252                         11 10
3253                         12 1
3254                         12 5
3255                         12 6
3256                         12 9
3257                         ];
3258
3259
3260                     CheckList = zeros(size(List,1),1);
3261                     if ~isempty(BPMlist1)
3262                         for i = 1:size(List,1)
3263                             k = find(List(i,1)==BPMlist1(:,1));
3264                             l = find(List(i,2)==BPMlist1(k,2));
3265
3266                             if isempty(k) | isempty(l)
3267                                 % Item not in list
3268                             else
3269                                 CheckList(i) = 1;
3270                             end
3271                         end
3272                     end
3273
3274                     newList = editlist(List, 'BPM', CheckList);
3275                     if isempty(newList)
3276                         fprintf('   BPM list cannot be empty.  No change made.\n');
3277                     else
3278                         BPMlist1 = newList;
3279                     end
3280
3281                     % Set the goal orbit to the golden orbit
3282                     Xgoal = getgolden('BPMx', BPMlist1);
3283                     Ygoal = getgolden('BPMy', BPMlist1);
3284
3285
3286                     % If a new BPM is added, then set the goal orbit to the golden orbit
3287                     for i = 1:size(BPMlist1,1)
3288
3289                         % Is it a new BPM?
3290                         k = find(BPMlist1(i,1)==ListOld(:,1));
3291                         l = find(BPMlist1(i,2)==ListOld(k,2));
3292
3293                         if isempty(k) | isempty(l)
3294                             % New BPM
3295                         else
3296                             % Use the old value for old BPM
3297                             Xgoal(i) = XgoalOld(k(l));
3298                             Ygoal(i) = YgoalOld(k(l));
3299                         end
3300                     end
3301                     OCSx.BPM.DeviceList = BPMlist1;
3302                     OCSy.BPM.DeviceList = BPMlist1;
3303                     OCSx.GoalOrbit = Xgoal;
3304                     OCSy.GoalOrbit = Ygoal;
3305                 end
3306
3307                 if EditFlag == 5
3308                     ChangeList = editlist2(BPMlist1, 'Change BPM', zeros(size(BPMlist1,1),1));
3309
3310                     for i = 1:size(ChangeList,1)
3311
3312                         k = find(ChangeList(i,1)==BPMlist1(:,1));
3313                         l = find(ChangeList(i,2)==BPMlist1(k,2));
3314
3315                         prompt={sprintf('Enter the new horizontal goal orbit for BPMx(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2)),sprintf('Enter the new vertical goal orbit for BPMy(%d,%d):',BPMlist1(k(l),1),BPMlist1(k(l),2))};
3316                         def={sprintf('%f',Xgoal(k(l))),sprintf('%f',Ygoal(k(l)))};
3317                         titlestr='CHANGE THE GOAL ORBIT';
3318                         lineNo=1;
3319                         answer = inputdlg(prompt, titlestr, lineNo, def);
3320
3321                         if isempty(answer)
3322                             % No change
3323                             fprintf('   No change was made to the golden orbit.\n');
3324                         else
3325                             Xgoalnew = str2num(answer{1});
3326                             if isempty(Xgoalnew)
3327                                 fprintf('   No change was made to the horizontal golden orbit.\n');
3328                             else
3329                                 Xgoal(k(l)) = Xgoalnew;
3330                             end
3331
3332                             Ygoalnew = str2num(answer{2});
3333                             if isempty(Ygoalnew)
3334                                 fprintf('   No change was made to the vertical golden orbit.\n');
3335                             else
3336                                 Ygoal(k(l)) = Ygoalnew;
3337                             end
3338                         end
3339                     end
3340                     if ~isempty(ChangeList)
3341                         fprintf('   Note:  Changing the goal orbit for "Slow Orbit Feedback" does not change the goal orbit for "Orbit Correction."\n');
3342                         fprintf('          Re-running srcontrol will restart the goal orbit to the golden orbit."\n');
3343                     end
3344                     OCSx.GoalOrbit = Xgoal;
3345                     OCSy.GoalOrbit = Ygoal;
3346                 end
3347
3348                 if EditFlag == 6
3349                     FFTypeFlag = questdlg(sprintf('Do you want to use a fully local or a combined local/global compensation of IDs? (nuy=9.2 only)'),'Tune FF','Local','Global', 'Global');
3350                     if strcmp(FFTypeFlag,'Local')
3351                         disp(['   The tune FF will use 8 local quadrupoles to compensate beta beating and tune shift']);
3352                         disp(['   from each ID.']);
3353                     elseif strcmp(FFTypeFlag,'Global')
3354                         disp(['   The tune FF will use 4 local quadrupoles to compensate beta beating and all QF+QD']);
3355                         disp(['   to compensate tune shift from each ID.']);
3356                     end
3357
3358                 end
3359
3360             end
3361             close(h_fig1);
3362         end
3363
3364         % Save vectors
3365         FB.Xivec = Xivec;
3366         FB.Yivec = Yivec;
3367         FB.HCMlist1 = HCMlist1;
3368         FB.VCMlist1 = VCMlist1;
3369         FB.BPMlist1 = BPMlist1;
3370
3371         OCSx.SVDIndex = Xivec;
3372         OCSy.SVDIndex = Yivec;
3373         FB.OCSx = OCSx;
3374         FB.OCSy = OCSy;
3375
3376         FB.FFTypeFlag = FFTypeFlag;
3377         set(findobj(gcbf,'Tag','SRCTRLButtonFeedbackSetup'),'Userdata',FB);
3378
3379
3380     case 'FastFeedbackSetup'
3381
3382         InitFlag = Input2;
3383
3384         if InitFlag
3385             FOFBFreq = 1000;
3386             % user operations 9/14-10/17/04: P=0.5, I=120, D=0.0015 (for both planes)
3387             % below are known good values for user ops as of 8-1-05
3388             HorP = 2;
3389             HorI = 300;
3390             HorD = 0.002;
3391             VertP = 1;
3392             VertI = 100;
3393             VertD = 0.0015;
3394
3395             % this initial set is now done in hwinit.m because it's not a good idea to set anything when srcontrol is launched
3396             % try
3397             %     setsp('SR01____FFBFREQAC00', FOFBFreq); % set freq
3398             %     write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3399             % catch
3400             %     disp('   Trouble setting Fast Orbit Feedback parameters!');
3401             % end
3402
3403         else
3404             % Get vectors
3405             FOFB = get(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata');
3406             FOFBFreq = FOFB.FOFBFreq;
3407             HorP  = FOFB.HorP;
3408             HorI  = FOFB.HorI;
3409             HorD  = FOFB.HorD;
3410             VertP = FOFB.VertP;
3411             VertI = FOFB.VertI;
3412             VertD = FOFB.VertD;
3413
3414             % Add button to change #ivectors, CMs, IDBPMs,
3415             EditFlag = 0;
3416             %h_fig1 = figure;
3417             while EditFlag ~= 3
3418
3419                 %EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'HCM List', 'VCM List', ...
3420                 %   'IDBPM List', 'BBPM List', 'Continue');
3421                 % Use menu below until other FFB config routines work (then also uncomment options 3,4,5,6 below)
3422                 EditFlag = menu('Change Parameters?', 'Fast Feedback Frequency', 'PID Values', 'Continue');
3423
3424                 if EditFlag == 1
3425                     % change rate
3426
3427                     prompt={'Enter the desired Fast Feedback Frequency (1-1000 Hz)'};
3428                     def={num2str(FOFBFreq)};
3429                     titlestr='Fast Feedback Setup';
3430                     lineNo=1;
3431                     answer=inputdlg(prompt,titlestr,lineNo,def);
3432                     if ~isempty(answer)
3433                         FOFBFreq = fix(str2num(answer{1}));
3434                         if isempty(FOFBFreq)
3435                             disp('   Frequency value cannot be empty.  No change made.');
3436                             FOFBFreq = getsp('SR01____FFBFREQAC00');
3437                         else
3438                             if FOFBFreq < 1 | FOFBFreq > 1000
3439                                 disp('   Frequency must be between 1 and 1000 Hz.  No change made.');
3440                                 FOFBFreq = getsp('SR01____FFBFREQAC00');
3441                             end
3442                         end
3443                         setsp('SR01____FFBFREQAC00',FOFBFreq); % change freq
3444                         pause(0.5);
3445                         fprintf('   Fast orbit feedback frequency is running at %.0f Hz.\n', getpv('SR01____FFBFREQAM00'));
3446                     else
3447                         FOFBFreq = getsp('SR01____FFBFREQAC00');
3448                     end
3449                 end
3450
3451                 if EditFlag == 2
3452                     % edit  PIDs
3453                     % User defaults are HorP=2, HorI=300, HorD=0.002, VertP=1, VertI=100, VertD=0.0015
3454                     prompt={'P horizontal', 'I horizontal', 'D horizontal', 'P vertical', 'I vertical', 'D vertical'};
3455                     def={num2str(HorP), num2str(HorI), num2str(HorD), num2str(VertP), num2str(VertI), num2str(VertD)};
3456                     titlestr='Fast Feedback PID Setup';
3457                     lineNo=1;
3458                     answer=inputdlg(prompt,titlestr,lineNo,def);
3459                     if ~isempty(answer)
3460                         HorPnewnum = str2num(answer{1});
3461                         if isempty(HorPnewnum)
3462                             disp('   HorP value cannot be empty.  No change made.');
3463                         else
3464                             HorP = HorPnewnum;
3465                         end
3466                         HorInewnum = str2num(answer{2});
3467                         if isempty(HorInewnum)
3468                             disp('   HorI value cannot be empty.  No change made.');
3469                         else
3470                             HorI = HorInewnum;
3471                         end
3472                         HorDnewnum = str2num(answer{3});
3473                         if isempty(HorDnewnum)
3474                             disp('   HorD value cannot be empty.  No change made.');
3475                         else
3476                             HorD = HorDnewnum;
3477                         end
3478                         VertPnewnum = str2num(answer{4});
3479                         if isempty(VertPnewnum)
3480                             disp('   VertP value cannot be empty.  No change made.');
3481                         else
3482                             VertP = VertPnewnum;
3483                         end
3484                         VertInewnum = str2num(answer{5});
3485                         if isempty(VertInewnum)
3486                             disp('   VertI value cannot be empty.  No change made.');
3487                         else
3488                             VertI = VertInewnum;
3489                         end
3490                         VertDnewnum = str2num(answer{6});
3491                         if isempty(VertDnewnum)
3492                             disp('   VertD value cannot be empty.  No change made.');
3493                         else
3494                             VertD = VertDnewnum;
3495                         end
3496
3497                         try
3498                             write_pid_ffb2_patch(HorP, HorI, HorD, VertP, VertI, VertD);
3499                             fprintf('   Setting FFB gains to Horizontal P=%.2f, I=%.1f, D=%.4f;  Vertical P=%.2f, I=%.1f, D=%.4f\n', HorP, HorI, HorD, VertP, VertI, VertD);
3500                         catch
3501                             disp('   Trouble setting Fast Orbit Feedback parameters!');
3502                         end
3503                     end
3504                 end
3505
3506                 %if EditFlag == 3
3507                 %   disp('   This function not yet available.');
3508                 %   % change HCM List
3509                 %end
3510                 %
3511                 %if EditFlag == 4
3512                 %   disp('   This function not yet available.');
3513                 %   % change VCM List
3514                 %end
3515                 %
3516                 %if EditFlag == 5
3517                 %   disp('   This function not yet available.');
3518                 %   % change IDBPM List
3519                 %end
3520                 %
3521                 %if EditFlag == 6
3522                 %   disp('   This function not yet available.');
3523                 %   % change BBPM List
3524                 %end
3525
3526             end
3527             %close(h_fig1);
3528         end
3529
3530         % Save vectors
3531         FOFB.FOFBFreq = FOFBFreq;
3532         FOFB.HorP = HorP;
3533         FOFB.HorI = HorI;
3534         FOFB.HorD = HorD;
3535         FOFB.VertP = VertP;
3536         FOFB.VertI = VertI;
3537         FOFB.VertD = VertD;
3538         set(findobj(gcbf,'Tag','SRCTRLButtonFastFeedbackSetup'),'Userdata',FOFB);
3539
3540     otherwise
3541         fprintf('   No action for %s.\n', action);
3542 end   % end case