Description of locomcf
Home > applications > loco > locomcf.m
locomcf
PURPOSE
LOCOMCF - Returns the momentum compaction factor
SYNOPSIS
function Alpha = locomcf(RINGData)
DESCRIPTION
LOCOMCF - Returns the momentum compaction factor
  Alpha = locomcf(RINGData)
  Momentum compaction factor
  Written by Greg Portmann
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
calclocochi2 CALCLOCOCHI2 - Calculate the contribution to chi^2 of each fit parameter in LOCO
loco LOCO - Main routine for the LOCO algorithm
lococalcchi2 LOCOCALCCHI2 - Calculate the contribution to chi^2 of each fit parameter in LOCO
locodata LOCODATA - Extracts data from a LOCO file
locogui LOCOGUI - Graphical interface for running the LOCO algorithm
locoplot LOCOPLOT - Subroutines for plotting LOCO output
locoplotrms LOCOPLOTRMS - Plots the RMS of the LOCO fits
SOURCE CODE
function Alpha = locomcf(RINGData)
%LOCOMCF - Returns the momentum compaction factor
%  Alpha = locomcf(RINGData)
%  Momentum compaction factor
%
%  Written by Greg Portmann
Alpha = mcf(RINGData.Lattice);