Description of locosetlatticeparam
Home > applications > loco > locosetlatticeparam.m
locosetlatticeparam
PURPOSE
LOCOSETLATTICEPARAM - Set the AT lattice from the LOCO fit parameters
SYNOPSIS
function RINGData = locosetlatticeparam(RINGData, LocoParams, LocoValues)
DESCRIPTION
LOCOSETLATTICEPARAM - Set the AT lattice from the LOCO fit parameters
  RINGData = locosetlatticeparam(RINGData, LocoParams, LocoValues)
  This function is shortcut to the AT function setparamgroup
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
calclocochi2 CALCLOCOCHI2 - Calculate the contribution to chi^2 of each fit parameter in LOCO
loco LOCO - Main routine for the LOCO algorithm
lococalcchi2 LOCOCALCCHI2 - Calculate the contribution to chi^2 of each fit parameter in LOCO
locodata LOCODATA - Extracts data from a LOCO file
locogui LOCOGUI - Graphical interface for running the LOCO algorithm
locoplot LOCOPLOT - Subroutines for plotting LOCO output
locoplotrms LOCOPLOTRMS - Plots the RMS of the LOCO fits
setlocodata_example SETLOCODATA - Applies the LOCO output data to the the accelerator, MML setup, and AT model
SOURCE CODE
function RINGData = locosetlatticeparam(RINGData, LocoParams, LocoValues)
%LOCOSETLATTICEPARAM - Set the AT lattice from the LOCO fit parameters
%  RINGData = locosetlatticeparam(RINGData, LocoParams, LocoValues)
%
%  This function is shortcut to the AT function setparamgroup
RINGData.Lattice = setparamgroup(RINGData.Lattice, LocoParams, LocoValues);